/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 Broadcom Proprietary and Confidential
******************************************************************************/
/**
    @file safetyisland_rdb.h
    @brief RDB File for SAFETYISLAND

    @version BCM89580_A0_20230125_RDB
*/

#ifndef SAFETYISLAND_RDB_H
#define SAFETYISLAND_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t SAFETYISLAND_FAUL_CONT_TYPE;
#define SAFETYISLAND_FAUL_CONT_SOFT_SECURE_BOOT_EN_MASK (0x400UL)
#define SAFETYISLAND_FAUL_CONT_SOFT_SECURE_BOOT_EN_SHIFT (10UL)
#define SAFETYISLAND_FAUL_CONT_FAULT_CAUSE_EN_MASK (0x200UL)
#define SAFETYISLAND_FAUL_CONT_FAULT_CAUSE_EN_SHIFT (9UL)
#define SAFETYISLAND_FAUL_CONT_MCU_0_NMI_TIMEOUT_RESET_MASK (0x100UL)
#define SAFETYISLAND_FAUL_CONT_MCU_0_NMI_TIMEOUT_RESET_SHIFT (8UL)
#define SAFETYISLAND_FAUL_CONT_MCU_0_NMI_TIMEOUT_SCALER_MASK (0xf0UL)
#define SAFETYISLAND_FAUL_CONT_MCU_0_NMI_TIMEOUT_SCALER_SHIFT (4UL)
#define SAFETYISLAND_FAUL_CONT_RESETFSM_RESET_OUT_COUNT_SCALER_MASK (0xfUL)
#define SAFETYISLAND_FAUL_CONT_RESETFSM_RESET_OUT_COUNT_SCALER_SHIFT (0UL)




typedef uint32_t SAFETYISLAND_FAULT_STATUS_TYPE;
#define SAFETYISLAND_FAULT_STATUS_RIGEL_FAULT_OUT_LIVE_MASK (0x80000000UL)
#define SAFETYISLAND_FAULT_STATUS_RIGEL_FAULT_OUT_LIVE_SHIFT (31UL)
#define SAFETYISLAND_FAULT_STATUS_CPU_FAULT_OUT_W2CLR_MASK (0x1000000UL)
#define SAFETYISLAND_FAULT_STATUS_CPU_FAULT_OUT_W2CLR_SHIFT (24UL)
#define SAFETYISLAND_FAULT_STATUS_QSPI_FIFO_OVERUNDER_FLOW_W2CLR_MASK (0x800000UL)
#define SAFETYISLAND_FAULT_STATUS_QSPI_FIFO_OVERUNDER_FLOW_W2CLR_SHIFT (23UL)
#define SAFETYISLAND_FAULT_STATUS_AHB_APB_BUS_W2CLR_MASK (0x400000UL)
#define SAFETYISLAND_FAULT_STATUS_AHB_APB_BUS_W2CLR_SHIFT (22UL)
#define SAFETYISLAND_FAULT_STATUS_SYSFABRIC_NOC_W2CLR_MASK (0x200000UL)
#define SAFETYISLAND_FAULT_STATUS_SYSFABRIC_NOC_W2CLR_SHIFT (21UL)
#define SAFETYISLAND_FAULT_STATUS_OVERHEAT_DETECTOR_W2CLR_MASK (0x100000UL)
#define SAFETYISLAND_FAULT_STATUS_OVERHEAT_DETECTOR_W2CLR_SHIFT (20UL)
#define SAFETYISLAND_FAULT_STATUS_BROWNOUT_DETECTOR_W2CLR_MASK (0x80000UL)
#define SAFETYISLAND_FAULT_STATUS_BROWNOUT_DETECTOR_W2CLR_SHIFT (19UL)
#define SAFETYISLAND_FAULT_STATUS_POWER_GOOD_PIN_W2CLR_MASK (0x40000UL)
#define SAFETYISLAND_FAULT_STATUS_POWER_GOOD_PIN_W2CLR_SHIFT (18UL)
#define SAFETYISLAND_FAULT_STATUS_RIG_DED_W2CLR_MASK (0x10000UL)
#define SAFETYISLAND_FAULT_STATUS_RIG_DED_W2CLR_SHIFT (16UL)
#define SAFETYISLAND_FAULT_STATUS_MCU1_LOCKUP_Q8_FATAL_W2CLR_MASK (0x8000UL)
#define SAFETYISLAND_FAULT_STATUS_MCU1_LOCKUP_Q8_FATAL_W2CLR_SHIFT (15UL)
#define SAFETYISLAND_FAULT_STATUS_SM_GP_SRAM_MEM_PROTECT_W2CLR_MASK (0x4000UL)
#define SAFETYISLAND_FAULT_STATUS_SM_GP_SRAM_MEM_PROTECT_W2CLR_SHIFT (14UL)
#define SAFETYISLAND_FAULT_STATUS_SM_ACQ_HSADC_FUNC_W2CLR_MASK (0x2000UL)
#define SAFETYISLAND_FAULT_STATUS_SM_ACQ_HSADC_FUNC_W2CLR_SHIFT (13UL)
#define SAFETYISLAND_FAULT_STATUS_SM_PMIC_INT_W2CLR_MASK (0x1000UL)
#define SAFETYISLAND_FAULT_STATUS_SM_PMIC_INT_W2CLR_SHIFT (12UL)
#define SAFETYISLAND_FAULT_STATUS_WWDT_1_7_TIMEOUT_W2CLR_MASK (0x800UL)
#define SAFETYISLAND_FAULT_STATUS_WWDT_1_7_TIMEOUT_W2CLR_SHIFT (11UL)
#define SAFETYISLAND_FAULT_STATUS_MCU_0_WWDT0_TIMEOUT_W2CLR_MASK (0x400UL)
#define SAFETYISLAND_FAULT_STATUS_MCU_0_WWDT0_TIMEOUT_W2CLR_SHIFT (10UL)
#define SAFETYISLAND_FAULT_STATUS_MCU_0_NMI_TIMEOUT_W2CLR_MASK (0x200UL)
#define SAFETYISLAND_FAULT_STATUS_MCU_0_NMI_TIMEOUT_W2CLR_SHIFT (9UL)
#define SAFETYISLAND_FAULT_STATUS_M0SRRW2_MASK (0x100UL)
#define SAFETYISLAND_FAULT_STATUS_M0SRRW2_SHIFT (8UL)
#define SAFETYISLAND_FAULT_STATUS_MCU_0_FUNCTIONAL_W2CLR_MASK (0x80UL)
#define SAFETYISLAND_FAULT_STATUS_MCU_0_FUNCTIONAL_W2CLR_SHIFT (7UL)
#define SAFETYISLAND_FAULT_STATUS_MCU_0_MEM_DED_W2CLR_MASK (0x40UL)
#define SAFETYISLAND_FAULT_STATUS_MCU_0_MEM_DED_W2CLR_SHIFT (6UL)
#define SAFETYISLAND_FAULT_STATUS_MCU_0_MEM_INIT_W2CLR_MASK (0x20UL)
#define SAFETYISLAND_FAULT_STATUS_MCU_0_MEM_INIT_W2CLR_SHIFT (5UL)
#define SAFETYISLAND_FAULT_STATUS_MCU_0_MBIST_FAIL_W2CLR_MASK (0x10UL)
#define SAFETYISLAND_FAULT_STATUS_MCU_0_MBIST_FAIL_W2CLR_SHIFT (4UL)
#define SAFETYISLAND_FAULT_STATUS_SYSPLL_LOCK_TIMEOUT_W2CLR_MASK (0x8UL)
#define SAFETYISLAND_FAULT_STATUS_SYSPLL_LOCK_TIMEOUT_W2CLR_SHIFT (3UL)
#define SAFETYISLAND_FAULT_STATUS_SYSPLL_LOCK_LOSS_W2CLR_MASK (0x4UL)
#define SAFETYISLAND_FAULT_STATUS_SYSPLL_LOCK_LOSS_W2CLR_SHIFT (2UL)
#define SAFETYISLAND_FAULT_STATUS_BISR_FAIL_W2CLR_MASK (0x2UL)
#define SAFETYISLAND_FAULT_STATUS_BISR_FAIL_W2CLR_SHIFT (1UL)
#define SAFETYISLAND_FAULT_STATUS_OTP0_FDONE_TIMEOUT_W2CLR_MASK (0x1UL)
#define SAFETYISLAND_FAULT_STATUS_OTP0_FDONE_TIMEOUT_W2CLR_SHIFT (0UL)




typedef uint32_t SAFETYISLAND_FAULT_MASK_TYPE;
#define SAFETYISLAND_FAULT_MASK_CPU_FAULT_OUT_MASK_MASK (0x1000000UL)
#define SAFETYISLAND_FAULT_MASK_CPU_FAULT_OUT_MASK_SHIFT (24UL)
#define SAFETYISLAND_FAULT_MASK_QSPI_FIFO_OVERUNDER_FLOW_MASK_MASK (0x800000UL)
#define SAFETYISLAND_FAULT_MASK_QSPI_FIFO_OVERUNDER_FLOW_MASK_SHIFT (23UL)
#define SAFETYISLAND_FAULT_MASK_AHB_APB_BUS_MASK_MASK (0x400000UL)
#define SAFETYISLAND_FAULT_MASK_AHB_APB_BUS_MASK_SHIFT (22UL)
#define SAFETYISLAND_FAULT_MASK_SYSFABRIC_NOC_MASK_MASK (0x200000UL)
#define SAFETYISLAND_FAULT_MASK_SYSFABRIC_NOC_MASK_SHIFT (21UL)
#define SAFETYISLAND_FAULT_MASK_OVERHEAT_DETECTOR_MASK_MASK (0x100000UL)
#define SAFETYISLAND_FAULT_MASK_OVERHEAT_DETECTOR_MASK_SHIFT (20UL)
#define SAFETYISLAND_FAULT_MASK_BROWNOUT_DETECTOR_MASK_MASK (0x80000UL)
#define SAFETYISLAND_FAULT_MASK_BROWNOUT_DETECTOR_MASK_SHIFT (19UL)
#define SAFETYISLAND_FAULT_MASK_POWER_GOOD_PIN_MASK_MASK (0x40000UL)
#define SAFETYISLAND_FAULT_MASK_POWER_GOOD_PIN_MASK_SHIFT (18UL)
#define SAFETYISLAND_FAULT_MASK_RESETB_IN_PIN_MASK_MASK (0x20000UL)
#define SAFETYISLAND_FAULT_MASK_RESETB_IN_PIN_MASK_SHIFT (17UL)
#define SAFETYISLAND_FAULT_MASK_RIG_DED_MASK_MASK (0x10000UL)
#define SAFETYISLAND_FAULT_MASK_RIG_DED_MASK_SHIFT (16UL)
#define SAFETYISLAND_FAULT_MASK_MCU1_LOCKUP_Q8_FATAL_MASK_MASK (0x8000UL)
#define SAFETYISLAND_FAULT_MASK_MCU1_LOCKUP_Q8_FATAL_MASK_SHIFT (15UL)
#define SAFETYISLAND_FAULT_MASK_SM_GP_SRAM_MEM_PROTECT_MASK_MASK (0x4000UL)
#define SAFETYISLAND_FAULT_MASK_SM_GP_SRAM_MEM_PROTECT_MASK_SHIFT (14UL)
#define SAFETYISLAND_FAULT_MASK_SM_ACQ_HSADC_FUNC_MASK_MASK (0x2000UL)
#define SAFETYISLAND_FAULT_MASK_SM_ACQ_HSADC_FUNC_MASK_SHIFT (13UL)
#define SAFETYISLAND_FAULT_MASK_SM_PMIC_INT_MASK_MASK (0x1000UL)
#define SAFETYISLAND_FAULT_MASK_SM_PMIC_INT_MASK_SHIFT (12UL)
#define SAFETYISLAND_FAULT_MASK_WWDT_1_7_TIMEOUT_MASK_MASK (0x800UL)
#define SAFETYISLAND_FAULT_MASK_WWDT_1_7_TIMEOUT_MASK_SHIFT (11UL)
#define SAFETYISLAND_FAULT_MASK_MCU_0_WWDT0_TIMEOUT_MASK_MASK (0x400UL)
#define SAFETYISLAND_FAULT_MASK_MCU_0_WWDT0_TIMEOUT_MASK_SHIFT (10UL)
#define SAFETYISLAND_FAULT_MASK_MCU_0_FUNCTIONAL_MASK_MASK (0x80UL)
#define SAFETYISLAND_FAULT_MASK_MCU_0_FUNCTIONAL_MASK_SHIFT (7UL)
#define SAFETYISLAND_FAULT_MASK_MCU_0_MEM_DED_MASK_MASK (0x40UL)
#define SAFETYISLAND_FAULT_MASK_MCU_0_MEM_DED_MASK_SHIFT (6UL)
#define SAFETYISLAND_FAULT_MASK_MCU_0_MEM_INIT_TIMEOUT_MASK_MASK (0x20UL)
#define SAFETYISLAND_FAULT_MASK_MCU_0_MEM_INIT_TIMEOUT_MASK_SHIFT (5UL)
#define SAFETYISLAND_FAULT_MASK_SYSPLL_LOCK_TIMEOUT_MASK_MASK (0x8UL)
#define SAFETYISLAND_FAULT_MASK_SYSPLL_LOCK_TIMEOUT_MASK_SHIFT (3UL)
#define SAFETYISLAND_FAULT_MASK_SYSPLL_LOCK_LOSS_MASK_MASK (0x4UL)
#define SAFETYISLAND_FAULT_MASK_SYSPLL_LOCK_LOSS_MASK_SHIFT (2UL)
#define SAFETYISLAND_FAULT_MASK_BISR_FAIL_MASK_MASK (0x2UL)
#define SAFETYISLAND_FAULT_MASK_BISR_FAIL_MASK_SHIFT (1UL)
#define SAFETYISLAND_FAULT_MASK_OTP0_FDONE_TIMEOUT_MASK_MASK (0x1UL)
#define SAFETYISLAND_FAULT_MASK_OTP0_FDONE_TIMEOUT_MASK_SHIFT (0UL)




typedef uint32_t SAFETYISLAND_SAFETY_STATUS_TYPE;
#define SAFETYISLAND_SAFETY_STATUS_RIGEL_BISR_GOOD_MASK (0x20000000UL)
#define SAFETYISLAND_SAFETY_STATUS_RIGEL_BISR_GOOD_SHIFT (29UL)
#define SAFETYISLAND_SAFETY_STATUS_RIGEL_BISR_DONE_MASK (0x10000000UL)
#define SAFETYISLAND_SAFETY_STATUS_RIGEL_BISR_DONE_SHIFT (28UL)
#define SAFETYISLAND_SAFETY_STATUS_MCU_0_MEM_INIT_STARTED_W2CLR_MASK (0x8000000UL)
#define SAFETYISLAND_SAFETY_STATUS_MCU_0_MEM_INIT_STARTED_W2CLR_SHIFT (27UL)
#define SAFETYISLAND_SAFETY_STATUS_MCU_0_MEM_INIT_GOOD_W2CLR_MASK (0x4000000UL)
#define SAFETYISLAND_SAFETY_STATUS_MCU_0_MEM_INIT_GOOD_W2CLR_SHIFT (26UL)
#define SAFETYISLAND_SAFETY_STATUS_MCU_0_MEM_INIT_ERROR_W2CLR_MASK (0x2000000UL)
#define SAFETYISLAND_SAFETY_STATUS_MCU_0_MEM_INIT_ERROR_W2CLR_SHIFT (25UL)
#define SAFETYISLAND_SAFETY_STATUS_MCU_0_MEM_INIT_DONE_W2CLR_MASK (0x1000000UL)
#define SAFETYISLAND_SAFETY_STATUS_MCU_0_MEM_INIT_DONE_W2CLR_SHIFT (24UL)
#define SAFETYISLAND_SAFETY_STATUS_MCU_0_MBIST_GOOD_W2CLR_MASK (0x200000UL)
#define SAFETYISLAND_SAFETY_STATUS_MCU_0_MBIST_GOOD_W2CLR_SHIFT (21UL)
#define SAFETYISLAND_SAFETY_STATUS_MCU_0_MBIST_DONE_W2CLR_MASK (0x100000UL)
#define SAFETYISLAND_SAFETY_STATUS_MCU_0_MBIST_DONE_W2CLR_SHIFT (20UL)
#define SAFETYISLAND_SAFETY_STATUS_RST_SEQUENCER_STATE_W2CLR_MASK (0x7ffffUL)
#define SAFETYISLAND_SAFETY_STATUS_RST_SEQUENCER_STATE_W2CLR_SHIFT (0UL)




typedef uint32_t SAFETYISLAND_CPU_RESET_REQ_TYPE;
#define SAFETYISLAND_CPU_RESET_REQ_VAL_MASK (0x80000000UL)
#define SAFETYISLAND_CPU_RESET_REQ_VAL_SHIFT (31UL)
#define SAFETYISLAND_CPU_RESET_REQ_KEY_MASK (0x7fffffffUL)
#define SAFETYISLAND_CPU_RESET_REQ_KEY_SHIFT (0UL)




typedef uint32_t SAFETYISLAND_CPU_RESET_OUT_TYPE;
#define SAFETYISLAND_CPU_RESET_OUT_VAL_MASK (0x80000000UL)
#define SAFETYISLAND_CPU_RESET_OUT_VAL_SHIFT (31UL)
#define SAFETYISLAND_CPU_RESET_OUT_KEY_MASK (0x7fffffffUL)
#define SAFETYISLAND_CPU_RESET_OUT_KEY_SHIFT (0UL)




typedef uint32_t SAFETYISLAND_CPU_FAULT_OUT_TYPE;
#define SAFETYISLAND_CPU_FAULT_OUT_VAL_MASK (0x80000000UL)
#define SAFETYISLAND_CPU_FAULT_OUT_VAL_SHIFT (31UL)
#define SAFETYISLAND_CPU_FAULT_OUT_KEY_MASK (0x7fffffffUL)
#define SAFETYISLAND_CPU_FAULT_OUT_KEY_SHIFT (0UL)




typedef uint32_t SAFETYISLAND_FAULT_DEBUG0_TYPE;
#define SAFETYISLAND_FAULT_DEBUG0_REG_MASK (0xffffffffUL)
#define SAFETYISLAND_FAULT_DEBUG0_REG_SHIFT (0UL)



#define SAFETYISLAND_FAULT_DEBUG_SIZE  (128UL)


typedef volatile struct sSAFETYISLAND_RDBType {
    SAFETYISLAND_FAUL_CONT_TYPE fault_control; /* OFFSET: 0x0 */
    SAFETYISLAND_FAULT_STATUS_TYPE fault_status; /* OFFSET: 0x4 */
    SAFETYISLAND_FAULT_MASK_TYPE fault_mask; /* OFFSET: 0x8 */
    SAFETYISLAND_SAFETY_STATUS_TYPE safety_status; /* OFFSET: 0xc */
    SAFETYISLAND_CPU_RESET_REQ_TYPE cpu_reset_req; /* OFFSET: 0x10 */
    SAFETYISLAND_CPU_RESET_OUT_TYPE cpu_reset_out; /* OFFSET: 0x14 */
    SAFETYISLAND_CPU_FAULT_OUT_TYPE cpu_fault_out; /* OFFSET: 0x18 */
    SAFETYISLAND_FAULT_DEBUG0_TYPE fault_debug[SAFETYISLAND_FAULT_DEBUG_SIZE]; /* OFFSET: 0x1c */
} SAFETYISLAND_RDBType;


#define RIG_SAFETY_CTRL_BASE            (0xE0240800UL)



#define SAFETYISLAND_MAX_HW_ID          (1UL)

#endif /* SAFETYISLAND_RDB_H */
