/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file hsref_intr_rdb.h
    @brief RDB File for HSREF_INTR

    @version BCM89580_A0_20230125_RDB
*/

#ifndef HSREF_INTR_RDB_H
#define HSREF_INTR_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t HSREF_INTR_AHCIE_TYPE;
#define HSREF_INTR_AHCIE_P_ADC_CALIB_ERR_INTR_MASK (0x80000000UL)
#define HSREF_INTR_AHCIE_P_ADC_CALIB_ERR_INTR_SHIFT (31UL)
#define HSREF_INTR_AHCIE_P_ADC_CALIB_DONE_INTR_MASK (0x1UL)
#define HSREF_INTR_AHCIE_P_ADC_CALIB_DONE_INTR_SHIFT (0UL)




typedef uint32_t HSREF_INTR_AHCIE1_TYPE;
#define HSREF_INTR_AHCIE1_ADC_CALIB_ERR_INTR_W2CLR_MASK (0x80000000UL)
#define HSREF_INTR_AHCIE1_ADC_CALIB_ERR_INTR_W2CLR_SHIFT (31UL)
#define HSREF_INTR_AHCIE1_ADC_CALIB_DONE_INTR_W2CLR_MASK (0x1UL)
#define HSREF_INTR_AHCIE1_ADC_CALIB_DONE_INTR_W2CLR_SHIFT (0UL)




typedef uint32_t HSREF_INTR_AHCIE2_TYPE;
#define HSREF_INTR_AHCIE2_ENABLE_ADC_CALIB_ERR_INTR_MASK (0x80000000UL)
#define HSREF_INTR_AHCIE2_ENABLE_ADC_CALIB_ERR_INTR_SHIFT (31UL)
#define HSREF_INTR_AHCIE2_ENABLE_ADC_CALIB_DONE_INTR_MASK (0x1UL)
#define HSREF_INTR_AHCIE2_ENABLE_ADC_CALIB_DONE_INTR_SHIFT (0UL)




typedef uint32_t HSREF_INTR_AHCFL0IE_TYPE;
#define HSREF_INTR_AHCFL0IE_P_LN0_CAPBUF0_FIFO_OVERFLOW_INTR_MASK (0x80000000UL)
#define HSREF_INTR_AHCFL0IE_P_LN0_CAPBUF0_FIFO_OVERFLOW_INTR_SHIFT (31UL)
#define HSREF_INTR_AHCFL0IE_P_LN0_CAPBUF0_FIFO_THRESHOLD_INTR_MASK (0x1UL)
#define HSREF_INTR_AHCFL0IE_P_LN0_CAPBUF0_FIFO_THRESHOLD_INTR_SHIFT (0UL)




typedef uint32_t HSREF_INTR_AHCFL0IE1_TYPE;
#define HSREF_INTR_AHCFL0IE1_LN0_CAPBUF0_FIFO_OVERFLOW_INTR_W2CLR_MASK (0x80000000UL)
#define HSREF_INTR_AHCFL0IE1_LN0_CAPBUF0_FIFO_OVERFLOW_INTR_W2CLR_SHIFT (31UL)
#define HSREF_INTR_AHCFL0IE1_L0C0FTIW2_MASK (0x1UL)
#define HSREF_INTR_AHCFL0IE1_L0C0FTIW2_SHIFT (0UL)




typedef uint32_t HSREF_INTR_AHCFL0IE2_TYPE;
#define HSREF_INTR_AHCFL0IE2_EL0C0FOI_MASK (0x80000000UL)
#define HSREF_INTR_AHCFL0IE2_EL0C0FOI_SHIFT (31UL)
#define HSREF_INTR_AHCFL0IE2_EL0C0FTI_MASK (0x1UL)
#define HSREF_INTR_AHCFL0IE2_EL0C0FTI_SHIFT (0UL)




typedef uint32_t HSREF_INTR_AHCFL1IE_TYPE;
#define HSREF_INTR_AHCFL1IE_P_LN1_CAPBUF0_FIFO_OVERFLOW_INTR_MASK (0x80000000UL)
#define HSREF_INTR_AHCFL1IE_P_LN1_CAPBUF0_FIFO_OVERFLOW_INTR_SHIFT (31UL)
#define HSREF_INTR_AHCFL1IE_P_LN1_CAPBUF0_FIFO_THRESHOLD_INTR_MASK (0x1UL)
#define HSREF_INTR_AHCFL1IE_P_LN1_CAPBUF0_FIFO_THRESHOLD_INTR_SHIFT (0UL)




typedef uint32_t HSREF_INTR_AHCFL1IE1_TYPE;
#define HSREF_INTR_AHCFL1IE1_LN1_CAPBUF0_FIFO_OVERFLOW_INTR_W2CLR_MASK (0x80000000UL)
#define HSREF_INTR_AHCFL1IE1_LN1_CAPBUF0_FIFO_OVERFLOW_INTR_W2CLR_SHIFT (31UL)
#define HSREF_INTR_AHCFL1IE1_L1C0FTIW2_MASK (0x1UL)
#define HSREF_INTR_AHCFL1IE1_L1C0FTIW2_SHIFT (0UL)




typedef uint32_t HSREF_INTR_AHCFL1IE2_TYPE;
#define HSREF_INTR_AHCFL1IE2_EL1C0FOI_MASK (0x80000000UL)
#define HSREF_INTR_AHCFL1IE2_EL1C0FOI_SHIFT (31UL)
#define HSREF_INTR_AHCFL1IE2_EL1C0FTI_MASK (0x1UL)
#define HSREF_INTR_AHCFL1IE2_EL1C0FTI_SHIFT (0UL)




typedef uint32_t HSREF_INTR_AHZFIE_TYPE;
#define HSREF_INTR_AHZFIE_P_ZCROSS_FIFO_OVERFLOW_INTR_MASK (0x80000000UL)
#define HSREF_INTR_AHZFIE_P_ZCROSS_FIFO_OVERFLOW_INTR_SHIFT (31UL)
#define HSREF_INTR_AHZFIE_P_ZCROSS_FIFO_THRESHOLD_INTR_MASK (0x1UL)
#define HSREF_INTR_AHZFIE_P_ZCROSS_FIFO_THRESHOLD_INTR_SHIFT (0UL)




typedef uint32_t HSREF_INTR_AHZFIE1_TYPE;
#define HSREF_INTR_AHZFIE1_ZCROSS_FIFO_OVERFLOW_INTR_W2CLR_MASK (0x80000000UL)
#define HSREF_INTR_AHZFIE1_ZCROSS_FIFO_OVERFLOW_INTR_W2CLR_SHIFT (31UL)
#define HSREF_INTR_AHZFIE1_ZCROSS_FIFO_THRESHOLD_INTR_W2CLR_MASK (0x1UL)
#define HSREF_INTR_AHZFIE1_ZCROSS_FIFO_THRESHOLD_INTR_W2CLR_SHIFT (0UL)




typedef uint32_t HSREF_INTR_AHZFIE2_TYPE;
#define HSREF_INTR_AHZFIE2_ENABLE_ZCROSS_FIFO_OVERFLOW_INTR_MASK (0x80000000UL)
#define HSREF_INTR_AHZFIE2_ENABLE_ZCROSS_FIFO_OVERFLOW_INTR_SHIFT (31UL)
#define HSREF_INTR_AHZFIE2_ENABLE_ZCROSS_FIFO_THRESHOLD_INTR_MASK (0x1UL)
#define HSREF_INTR_AHZFIE2_ENABLE_ZCROSS_FIFO_THRESHOLD_INTR_SHIFT (0UL)




typedef uint32_t HSREF_INTR_AHMISIE_TYPE;
#define HSREF_INTR_AHMISIE_P_CAPBUF_MEM_INIT_ERR_INTR_MASK (0x4UL)
#define HSREF_INTR_AHMISIE_P_CAPBUF_MEM_INIT_ERR_INTR_SHIFT (2UL)
#define HSREF_INTR_AHMISIE_P_CAPBUF_MEM_INIT_DONE_INTR_MASK (0x2UL)
#define HSREF_INTR_AHMISIE_P_CAPBUF_MEM_INIT_DONE_INTR_SHIFT (1UL)




typedef uint32_t HSREF_INTR_AHMISIE1_TYPE;
#define HSREF_INTR_AHMISIE1_CAPBUF_MEM_INIT_ERR_INTR_W2CLR_MASK (0x4UL)
#define HSREF_INTR_AHMISIE1_CAPBUF_MEM_INIT_ERR_INTR_W2CLR_SHIFT (2UL)
#define HSREF_INTR_AHMISIE1_CAPBUF_MEM_INIT_DONE_INTR_W2CLR_MASK (0x2UL)
#define HSREF_INTR_AHMISIE1_CAPBUF_MEM_INIT_DONE_INTR_W2CLR_SHIFT (1UL)




typedef uint32_t HSREF_INTR_AHMISIE2_TYPE;
#define HSREF_INTR_AHMISIE2_ENABLE_CAPBUF_MEM_INIT_ERR_INTR_MASK (0x4UL)
#define HSREF_INTR_AHMISIE2_ENABLE_CAPBUF_MEM_INIT_ERR_INTR_SHIFT (2UL)
#define HSREF_INTR_AHMISIE2_ENABLE_CAPBUF_MEM_INIT_DONE_INTR_MASK (0x2UL)
#define HSREF_INTR_AHMISIE2_ENABLE_CAPBUF_MEM_INIT_DONE_INTR_SHIFT (1UL)




typedef uint8_t HSREF_INTR_RESERVED_TYPE;




typedef uint32_t HSREF_INTR_SPARE_END_REG_TYPE;
#define HSREF_INTR_SPARE_END_REG_MASK (0xffffffffUL)
#define HSREF_INTR_SPARE_END_REG_SHIFT (0UL)




typedef volatile struct sHSREF_INTR_RDBType {
    HSREF_INTR_AHCIE_TYPE acq_hsref_calib_intr_eipr; /* OFFSET: 0x0 */
    HSREF_INTR_AHCIE1_TYPE acq_hsref_calib_intr_eisr; /* OFFSET: 0x4 */
    HSREF_INTR_AHCIE2_TYPE acq_hsref_calib_intr_eier; /* OFFSET: 0x8 */
    HSREF_INTR_AHCFL0IE_TYPE acq_hsref_capbuf_fifo_ln0_intr_eipr; /* OFFSET: 0xc */
    HSREF_INTR_AHCFL0IE1_TYPE acq_hsref_capbuf_fifo_ln0_intr_eisr; /* OFFSET: 0x10 */
    HSREF_INTR_AHCFL0IE2_TYPE acq_hsref_capbuf_fifo_ln0_intr_eier; /* OFFSET: 0x14 */
    HSREF_INTR_AHCFL1IE_TYPE acq_hsref_capbuf_fifo_ln1_intr_eipr; /* OFFSET: 0x18 */
    HSREF_INTR_AHCFL1IE1_TYPE acq_hsref_capbuf_fifo_ln1_intr_eisr; /* OFFSET: 0x1c */
    HSREF_INTR_AHCFL1IE2_TYPE acq_hsref_capbuf_fifo_ln1_intr_eier; /* OFFSET: 0x20 */
    HSREF_INTR_AHZFIE_TYPE acq_hsref_zcross_fifo_intr_eipr; /* OFFSET: 0x24 */
    HSREF_INTR_AHZFIE1_TYPE acq_hsref_zcross_fifo_intr_eisr; /* OFFSET: 0x28 */
    HSREF_INTR_AHZFIE2_TYPE acq_hsref_zcross_fifo_intr_eier; /* OFFSET: 0x2c */
    HSREF_INTR_AHMISIE_TYPE acq_hsref_mem_init_sec_intr_eipr; /* OFFSET: 0x30 */
    HSREF_INTR_AHMISIE1_TYPE acq_hsref_mem_init_sec_intr_eisr; /* OFFSET: 0x34 */
    HSREF_INTR_AHMISIE2_TYPE acq_hsref_mem_init_sec_intr_eier; /* OFFSET: 0x38 */
    HSREF_INTR_RESERVED_TYPE rsvd0[192]; /* OFFSET: 0x3c */
    HSREF_INTR_SPARE_END_REG_TYPE spare_end_reg; /* OFFSET: 0xfc */
} HSREF_INTR_RDBType;


#define HSREF_INTR_BASE                 (0xE0606F00UL)



#define HSREF_INTR_MAX_HW_ID            (1UL)

#endif /* HSREF_INTR_RDB_H */
