/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file hsref_rdb.h
    @brief RDB File for HSREF

    @version BCM89580_A0_20230125_RDB
*/

#ifndef HSREF_RDB_H
#define HSREF_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t HSREF_ADCCAL_CONTROL0_TYPE;
#define HSREF_ADCCAL_CONTROL0_CAL_BUSY_MASK (0x80000000UL)
#define HSREF_ADCCAL_CONTROL0_CAL_BUSY_SHIFT (31UL)
#define HSREF_ADCCAL_CONTROL0_CAL_START_MASK (0x20UL)
#define HSREF_ADCCAL_CONTROL0_CAL_START_SHIFT (5UL)
#define HSREF_ADCCAL_CONTROL0_CAL_STATES_EN_MASK (0x1fUL)
#define HSREF_ADCCAL_CONTROL0_CAL_STATES_EN_SHIFT (0UL)




typedef uint32_t HSREF_ADCCAL_CONTROL1_TYPE;
#define HSREF_ADCCAL_CONTROL1_CAL_BG_RDB_DURATION_MASK (0xffffUL)
#define HSREF_ADCCAL_CONTROL1_CAL_BG_RDB_DURATION_SHIFT (0UL)




typedef uint32_t HSREF_ADCCAL_CONTROL2_TYPE;
#define HSREF_ADCCAL_CONTROL2_BG_OFFSET_CLR_MASK (0x80000000UL)
#define HSREF_ADCCAL_CONTROL2_BG_OFFSET_CLR_SHIFT (31UL)
#define HSREF_ADCCAL_CONTROL2_BG_OFFSET_MU_MASK (0x7000UL)
#define HSREF_ADCCAL_CONTROL2_BG_OFFSET_MU_SHIFT (12UL)
#define HSREF_ADCCAL_CONTROL2_BG_CAL_CFG_MASK (0xc00UL)
#define HSREF_ADCCAL_CONTROL2_BG_CAL_CFG_SHIFT (10UL)




typedef uint32_t HSREF_ADCCAL_CONTROL3_TYPE;




typedef uint32_t HSREF_ADCCAL_CONTROL4_TYPE;
#define HSREF_ADCCAL_CONTROL4_FG_ADC_TAH_ZERO_OVR_VAL_MASK (0x400UL)
#define HSREF_ADCCAL_CONTROL4_FG_ADC_TAH_ZERO_OVR_VAL_SHIFT (10UL)
#define HSREF_ADCCAL_CONTROL4_FG_ADC_SAR_ZERO_OVR_VAL_MASK (0x200UL)
#define HSREF_ADCCAL_CONTROL4_FG_ADC_SAR_ZERO_OVR_VAL_SHIFT (9UL)
#define HSREF_ADCCAL_CONTROL4_FG_CAL_OVERRIDE_EN_MASK (0x100UL)
#define HSREF_ADCCAL_CONTROL4_FG_CAL_OVERRIDE_EN_SHIFT (8UL)
#define HSREF_ADCCAL_CONTROL4_FG_OFFSET_ERROR_MASK (0x40UL)
#define HSREF_ADCCAL_CONTROL4_FG_OFFSET_ERROR_SHIFT (6UL)
#define HSREF_ADCCAL_CONTROL4_FG_OFFSET_ACC_DLY_MASK (0x30UL)
#define HSREF_ADCCAL_CONTROL4_FG_OFFSET_ACC_DLY_SHIFT (4UL)
#define HSREF_ADCCAL_CONTROL4_FG_OFFSET_INIT_DLY_MASK (0xcUL)
#define HSREF_ADCCAL_CONTROL4_FG_OFFSET_INIT_DLY_SHIFT (2UL)
#define HSREF_ADCCAL_CONTROL4_FG_OFFSET_SWAP_POLARITY_MASK (0x2UL)
#define HSREF_ADCCAL_CONTROL4_FG_OFFSET_SWAP_POLARITY_SHIFT (1UL)
#define HSREF_ADCCAL_CONTROL4_FG_OFFSET_MODE_MASK (0x1UL)
#define HSREF_ADCCAL_CONTROL4_FG_OFFSET_MODE_SHIFT (0UL)




typedef uint32_t HSREF_ADCCAL_CONTROL5_TYPE;
#define HSREF_ADCCAL_CONTROL5_FG_DACCAL_LANE_CTL_MASK (0x30000UL)
#define HSREF_ADCCAL_CONTROL5_FG_DACCAL_LANE_CTL_SHIFT (16UL)
#define HSREF_ADCCAL_CONTROL5_FG_DACCAL_UNDERFLOW_ERROR_MASK (0x400UL)
#define HSREF_ADCCAL_CONTROL5_FG_DACCAL_UNDERFLOW_ERROR_SHIFT (10UL)
#define HSREF_ADCCAL_CONTROL5_FG_DACCAL_OVERFLOW_ERROR_MASK (0x200UL)
#define HSREF_ADCCAL_CONTROL5_FG_DACCAL_OVERFLOW_ERROR_SHIFT (9UL)
#define HSREF_ADCCAL_CONTROL5_FG_DACCAL_OVR_STATE_VAL_MASK (0x1c0UL)
#define HSREF_ADCCAL_CONTROL5_FG_DACCAL_OVR_STATE_VAL_SHIFT (6UL)
#define HSREF_ADCCAL_CONTROL5_FG_DACCAL_OVR_EN_VAL_MASK (0x20UL)
#define HSREF_ADCCAL_CONTROL5_FG_DACCAL_OVR_EN_VAL_SHIFT (5UL)
#define HSREF_ADCCAL_CONTROL5_FG_DACCAL_OVERRIDE_EN_MASK (0x10UL)
#define HSREF_ADCCAL_CONTROL5_FG_DACCAL_OVERRIDE_EN_SHIFT (4UL)
#define HSREF_ADCCAL_CONTROL5_FG_DACCAL_NMAX_MASK (0xfUL)
#define HSREF_ADCCAL_CONTROL5_FG_DACCAL_NMAX_SHIFT (0UL)




typedef uint32_t HSREF_ADCCAL_IND_CONTROL_TYPE;
#define HSREF_ADCCAL_IND_CONTROL_WR_STROBE_MASK (0x80000000UL)
#define HSREF_ADCCAL_IND_CONTROL_WR_STROBE_SHIFT (31UL)
#define HSREF_ADCCAL_IND_CONTROL_ADDRESS_MASK (0xffUL)
#define HSREF_ADCCAL_IND_CONTROL_ADDRESS_SHIFT (0UL)




typedef uint32_t HSREF_ADCCAL_IND_WR_DATA_TYPE;
#define HSREF_ADCCAL_IND_WR_DATA_WRITE_MASK (0xffffffffUL)
#define HSREF_ADCCAL_IND_WR_DATA_WRITE_SHIFT (0UL)




typedef uint32_t HSREF_ADCCAL_IND_RD_DATA_TYPE;
#define HSREF_ADCCAL_IND_RD_DATA_READ_MASK (0xffffffffUL)
#define HSREF_ADCCAL_IND_RD_DATA_READ_SHIFT (0UL)




typedef uint32_t HSREF_SVF_CONTROL0_TYPE;
#define HSREF_SVF_CONTROL0_SEL_MASK (0x2UL)
#define HSREF_SVF_CONTROL0_SEL_SHIFT (1UL)
#define HSREF_SVF_CONTROL0_EN_MASK (0x1UL)
#define HSREF_SVF_CONTROL0_EN_SHIFT (0UL)




typedef uint32_t HSREF_SVF_CONTROL1_TYPE;
#define HSREF_SVF_CONTROL1_Q_VAR_MASK (0x3ff0000UL)
#define HSREF_SVF_CONTROL1_Q_VAR_SHIFT (16UL)
#define HSREF_SVF_CONTROL1_F_VAR_MASK (0x1ffUL)
#define HSREF_SVF_CONTROL1_F_VAR_SHIFT (0UL)




typedef uint32_t HSREF_ZCROSS_CONTROL0_TYPE;
#define HSREF_ZCROSS_CONTROL0_HYS_RANGE_MASK (0xf0UL)
#define HSREF_ZCROSS_CONTROL0_HYS_RANGE_SHIFT (4UL)
#define HSREF_ZCROSS_CONTROL0_HYS_EN_MASK (0x2UL)
#define HSREF_ZCROSS_CONTROL0_HYS_EN_SHIFT (1UL)
#define HSREF_ZCROSS_CONTROL0_EN_MASK (0x1UL)
#define HSREF_ZCROSS_CONTROL0_EN_SHIFT (0UL)




typedef uint32_t HSREF_ZCROSS_CONTROL1_TYPE;
#define HSREF_ZCROSS_CONTROL1_PRE_MASK_CAP_DURATION_MASK (0xffff0000UL)
#define HSREF_ZCROSS_CONTROL1_PRE_MASK_CAP_DURATION_SHIFT (16UL)
#define HSREF_ZCROSS_CONTROL1_CAP_DURATION_MASK (0xffffUL)
#define HSREF_ZCROSS_CONTROL1_CAP_DURATION_SHIFT (0UL)




typedef uint32_t HSREF_ZCROSS_FIFO_CONTROL_TYPE;
#define HSREF_ZCROSS_FIFO_CONTROL_RD_MASK (0x10UL)
#define HSREF_ZCROSS_FIFO_CONTROL_RD_SHIFT (4UL)
#define HSREF_ZCROSS_FIFO_CONTROL_RESET_MASK (0x8UL)
#define HSREF_ZCROSS_FIFO_CONTROL_RESET_SHIFT (3UL)
#define HSREF_ZCROSS_FIFO_CONTROL_THRESHOLD_MASK (0x7UL)
#define HSREF_ZCROSS_FIFO_CONTROL_THRESHOLD_SHIFT (0UL)




typedef uint32_t HSREF_ZCROSS_FIFO_STATUS_TYPE;
#define HSREF_ZCROSS_FIFO_STATUS_MASK (0xffffffffUL)
#define HSREF_ZCROSS_FIFO_STATUS_SHIFT (0UL)




typedef uint32_t HSREF_ZCROSS_FIFO_RD_DATA_TYPE;
#define HSREF_ZCROSS_FIFO_RD_DATA_MASK (0xffffffffUL)
#define HSREF_ZCROSS_FIFO_RD_DATA_SHIFT (0UL)




typedef uint32_t HSREF_CAP_BUF_CONTROL0_TYPE;
#define HSREF_CAP_BUF_CONTROL0_SVF_POST_DIV_MASK (0xcUL)
#define HSREF_CAP_BUF_CONTROL0_SVF_POST_DIV_SHIFT (2UL)
#define HSREF_CAP_BUF_CONTROL0_CAP_BUF_EN_MASK (0x1UL)
#define HSREF_CAP_BUF_CONTROL0_CAP_BUF_EN_SHIFT (0UL)




typedef uint32_t HSREF_CAP_BUF_CONTROL1_TYPE;
#define HSREF_CAP_BUF_CONTROL1_SAMPLES_CNT_MASK (0xffffffUL)
#define HSREF_CAP_BUF_CONTROL1_SAMPLES_CNT_SHIFT (0UL)




typedef uint32_t HSREF_CAP_BUF_FIFO_CONTROL0_TYPE;
#define HSREF_CAP_BUF_FIFO_CONTROL0_RESET_MASK (0x100UL)
#define HSREF_CAP_BUF_FIFO_CONTROL0_RESET_SHIFT (8UL)
#define HSREF_CAP_BUF_FIFO_CONTROL0_THRESHOLD_MASK (0xffUL)
#define HSREF_CAP_BUF_FIFO_CONTROL0_THRESHOLD_SHIFT (0UL)




typedef uint32_t HSREF_CAP_BUF_FIFO_STATUS_TYPE;
#define HSREF_CAP_BUF_FIFO_STATUS_MASK (0xffffffffUL)
#define HSREF_CAP_BUF_FIFO_STATUS_SHIFT (0UL)




typedef uint32_t HSREF_MEM_INIT_CONTROL_TYPE;
#define HSREF_MEM_INIT_CONTROL_CAPBUF_RSTB_MASK (0x4UL)
#define HSREF_MEM_INIT_CONTROL_CAPBUF_RSTB_SHIFT (2UL)
#define HSREF_MEM_INIT_CONTROL_CAPBUF_INIT_EN_MASK (0x2UL)
#define HSREF_MEM_INIT_CONTROL_CAPBUF_INIT_EN_SHIFT (1UL)
#define HSREF_MEM_INIT_CONTROL_CAPBUF_INT_CHK_EN_MASK (0x1UL)
#define HSREF_MEM_INIT_CONTROL_CAPBUF_INT_CHK_EN_SHIFT (0UL)




typedef uint32_t HSREF_MEM_TM_TYPE;
#define HSREF_MEM_TM_CAPBUF_MASK (0xfUL)
#define HSREF_MEM_TM_CAPBUF_SHIFT (0UL)




typedef uint8_t HSREF_RESERVED_TYPE;




typedef uint32_t HSREF_AFE_SPARE_END_TYPE;
#define HSREF_AFE_SPARE_END_MASK (0xffffffffUL)
#define HSREF_AFE_SPARE_END_SHIFT (0UL)



#define HSREF_ZCROSS_FIFO_RD_DATA_SIZE  (8UL)

#define HSREF_CAP_BUF_FIFO_STATUS_LN_SIZE  (2UL)


typedef volatile struct sHSREF_RDBType {
    HSREF_ADCCAL_CONTROL0_TYPE adccal_control0; /* OFFSET: 0x0 */
    HSREF_ADCCAL_CONTROL1_TYPE adccal_control1; /* OFFSET: 0x4 */
    HSREF_ADCCAL_CONTROL2_TYPE adccal_control2; /* OFFSET: 0x8 */
    HSREF_ADCCAL_CONTROL3_TYPE adccal_control3; /* OFFSET: 0xc */
    HSREF_ADCCAL_CONTROL4_TYPE adccal_control4; /* OFFSET: 0x10 */
    HSREF_ADCCAL_CONTROL5_TYPE adccal_control5; /* OFFSET: 0x14 */
    HSREF_ADCCAL_IND_CONTROL_TYPE adccal_ind_control; /* OFFSET: 0x18 */
    HSREF_ADCCAL_IND_WR_DATA_TYPE adccal_ind_wr_data; /* OFFSET: 0x1c */
    HSREF_ADCCAL_IND_RD_DATA_TYPE adccal_ind_rd_data; /* OFFSET: 0x20 */
    HSREF_SVF_CONTROL0_TYPE svf_control0; /* OFFSET: 0x24 */
    HSREF_SVF_CONTROL1_TYPE svf_control1; /* OFFSET: 0x28 */
    HSREF_ZCROSS_CONTROL0_TYPE zcross_control0; /* OFFSET: 0x2c */
    HSREF_ZCROSS_CONTROL1_TYPE zcross_control1; /* OFFSET: 0x30 */
    HSREF_ZCROSS_FIFO_CONTROL_TYPE zcross_fifo_control; /* OFFSET: 0x34 */
    HSREF_ZCROSS_FIFO_STATUS_TYPE zcross_fifo_status; /* OFFSET: 0x38 */
    HSREF_ZCROSS_FIFO_RD_DATA_TYPE zcross_fifo_rd_data[HSREF_ZCROSS_FIFO_RD_DATA_SIZE]; /* OFFSET: 0x3c */
    HSREF_CAP_BUF_CONTROL0_TYPE cap_buf_control0; /* OFFSET: 0x5c */
    HSREF_CAP_BUF_CONTROL1_TYPE cap_buf_control1; /* OFFSET: 0x60 */
    HSREF_CAP_BUF_FIFO_CONTROL0_TYPE cap_buf_fifo_control0; /* OFFSET: 0x64 */
    HSREF_CAP_BUF_FIFO_STATUS_TYPE cap_buf_fifo_status_ln[HSREF_CAP_BUF_FIFO_STATUS_LN_SIZE]; /* OFFSET: 0x68 */
    HSREF_MEM_INIT_CONTROL_TYPE mem_init_ctrl; /* OFFSET: 0x70 */
    HSREF_MEM_TM_TYPE mem_tm; /* OFFSET: 0x74 */
    HSREF_RESERVED_TYPE rsvd0[3716]; /* OFFSET: 0x78 */
    HSREF_AFE_SPARE_END_TYPE spare_end; /* OFFSET: 0xefc */
} HSREF_RDBType;


#define HSREF_ACQ_BASE                  (0xE0606000UL)



#define HSREF_MAX_HW_ID                 (1UL)

#endif /* HSREF_RDB_H */
