/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file macsec_e_secy_cntrs_rdb.h
    @brief RDB File for MACSEC_E_SECY_CNTRS

    @version BCM89580_AQ_TSLA_A0_20240304_R10
*/

#ifndef MACSEC_E_SECY_CNTRS_RDB_H
#define MACSEC_E_SECY_CNTRS_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t MACSEC_E_SECY_CNTRS_RESERVED_TYPE;




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_0_TRANSFORMERRORPKTS_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_0_TRANSFORMERRORPKTS_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_0_TRANSFORMERRORPKTS_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_0_TRANSFORMERRORPKTS_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_0_TRANSFORMERRORPKTS_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_0_TRANSFORMERRORPKTS_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_0_OUTPKTSCTRL_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_0_OUTPKTSCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_0_OUTPKTSCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_0_OUTPKTSCTRL_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_0_OUTPKTSCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_0_OUTPKTSCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_0_OUTPKTSUNTAGGED_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_0_OUTPKTSUNTAGGED_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_0_OUTPKTSUNTAGGED_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_0_OUTPKTSUNTAGGED_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_0_OUTPKTSUNTAGGED_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_0_OUTPKTSUNTAGGED_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_1_TRANSFORMERRORPKTS_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_1_TRANSFORMERRORPKTS_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_1_TRANSFORMERRORPKTS_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_1_TRANSFORMERRORPKTS_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_1_TRANSFORMERRORPKTS_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_1_TRANSFORMERRORPKTS_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_1_OUTPKTSCTRL_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_1_OUTPKTSCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_1_OUTPKTSCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_1_OUTPKTSCTRL_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_1_OUTPKTSCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_1_OUTPKTSCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_1_OUTPKTSUNTAGGED_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_1_OUTPKTSUNTAGGED_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_1_OUTPKTSUNTAGGED_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_1_OUTPKTSUNTAGGED_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_1_OUTPKTSUNTAGGED_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_1_OUTPKTSUNTAGGED_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_2_TRANSFORMERRORPKTS_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_2_TRANSFORMERRORPKTS_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_2_TRANSFORMERRORPKTS_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_2_TRANSFORMERRORPKTS_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_2_TRANSFORMERRORPKTS_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_2_TRANSFORMERRORPKTS_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_2_OUTPKTSCTRL_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_2_OUTPKTSCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_2_OUTPKTSCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_2_OUTPKTSCTRL_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_2_OUTPKTSCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_2_OUTPKTSCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_2_OUTPKTSUNTAGGED_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_2_OUTPKTSUNTAGGED_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_2_OUTPKTSUNTAGGED_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_2_OUTPKTSUNTAGGED_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_2_OUTPKTSUNTAGGED_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_2_OUTPKTSUNTAGGED_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_3_TRANSFORMERRORPKTS_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_3_TRANSFORMERRORPKTS_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_3_TRANSFORMERRORPKTS_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_3_TRANSFORMERRORPKTS_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_3_TRANSFORMERRORPKTS_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_3_TRANSFORMERRORPKTS_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_3_OUTPKTSCTRL_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_3_OUTPKTSCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_3_OUTPKTSCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_3_OUTPKTSCTRL_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_3_OUTPKTSCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_3_OUTPKTSCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_3_OUTPKTSUNTAGGED_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_3_OUTPKTSUNTAGGED_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_3_OUTPKTSUNTAGGED_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_3_OUTPKTSUNTAGGED_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_3_OUTPKTSUNTAGGED_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_3_OUTPKTSUNTAGGED_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_4_TRANSFORMERRORPKTS_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_4_TRANSFORMERRORPKTS_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_4_TRANSFORMERRORPKTS_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_4_TRANSFORMERRORPKTS_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_4_TRANSFORMERRORPKTS_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_4_TRANSFORMERRORPKTS_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_4_OUTPKTSCTRL_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_4_OUTPKTSCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_4_OUTPKTSCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_4_OUTPKTSCTRL_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_4_OUTPKTSCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_4_OUTPKTSCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_4_OUTPKTSUNTAGGED_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_4_OUTPKTSUNTAGGED_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_4_OUTPKTSUNTAGGED_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_4_OUTPKTSUNTAGGED_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_4_OUTPKTSUNTAGGED_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_4_OUTPKTSUNTAGGED_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_5_TRANSFORMERRORPKTS_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_5_TRANSFORMERRORPKTS_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_5_TRANSFORMERRORPKTS_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_5_TRANSFORMERRORPKTS_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_5_TRANSFORMERRORPKTS_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_5_TRANSFORMERRORPKTS_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_5_OUTPKTSCTRL_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_5_OUTPKTSCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_5_OUTPKTSCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_5_OUTPKTSCTRL_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_5_OUTPKTSCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_5_OUTPKTSCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_5_OUTPKTSUNTAGGED_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_5_OUTPKTSUNTAGGED_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_5_OUTPKTSUNTAGGED_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_5_OUTPKTSUNTAGGED_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_5_OUTPKTSUNTAGGED_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_5_OUTPKTSUNTAGGED_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_6_TRANSFORMERRORPKTS_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_6_TRANSFORMERRORPKTS_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_6_TRANSFORMERRORPKTS_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_6_TRANSFORMERRORPKTS_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_6_TRANSFORMERRORPKTS_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_6_TRANSFORMERRORPKTS_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_6_OUTPKTSCTRL_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_6_OUTPKTSCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_6_OUTPKTSCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_6_OUTPKTSCTRL_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_6_OUTPKTSCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_6_OUTPKTSCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_6_OUTPKTSUNTAGGED_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_6_OUTPKTSUNTAGGED_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_6_OUTPKTSUNTAGGED_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_6_OUTPKTSUNTAGGED_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_6_OUTPKTSUNTAGGED_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_6_OUTPKTSUNTAGGED_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_7_TRANSFORMERRORPKTS_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_7_TRANSFORMERRORPKTS_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_7_TRANSFORMERRORPKTS_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_7_TRANSFORMERRORPKTS_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_7_TRANSFORMERRORPKTS_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_7_TRANSFORMERRORPKTS_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_7_OUTPKTSCTRL_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_7_OUTPKTSCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_7_OUTPKTSCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_7_OUTPKTSCTRL_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_7_OUTPKTSCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_7_OUTPKTSCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_7_OUTPKTSUNTAGGED_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_7_OUTPKTSUNTAGGED_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_7_OUTPKTSUNTAGGED_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_7_OUTPKTSUNTAGGED_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_7_OUTPKTSUNTAGGED_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_7_OUTPKTSUNTAGGED_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_8_TRANSFORMERRORPKTS_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_8_TRANSFORMERRORPKTS_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_8_TRANSFORMERRORPKTS_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_8_TRANSFORMERRORPKTS_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_8_TRANSFORMERRORPKTS_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_8_TRANSFORMERRORPKTS_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_8_OUTPKTSCTRL_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_8_OUTPKTSCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_8_OUTPKTSCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_8_OUTPKTSCTRL_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_8_OUTPKTSCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_8_OUTPKTSCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_8_OUTPKTSUNTAGGED_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_8_OUTPKTSUNTAGGED_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_8_OUTPKTSUNTAGGED_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_8_OUTPKTSUNTAGGED_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_8_OUTPKTSUNTAGGED_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_8_OUTPKTSUNTAGGED_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_9_TRANSFORMERRORPKTS_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_9_TRANSFORMERRORPKTS_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_9_TRANSFORMERRORPKTS_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_9_TRANSFORMERRORPKTS_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_9_TRANSFORMERRORPKTS_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_9_TRANSFORMERRORPKTS_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_9_OUTPKTSCTRL_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_9_OUTPKTSCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_9_OUTPKTSCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_9_OUTPKTSCTRL_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_9_OUTPKTSCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_9_OUTPKTSCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_9_OUTPKTSUNTAGGED_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_9_OUTPKTSUNTAGGED_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_9_OUTPKTSUNTAGGED_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_9_OUTPKTSUNTAGGED_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_9_OUTPKTSUNTAGGED_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_9_OUTPKTSUNTAGGED_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_10_TRANSFORMERRORPKTS_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_10_TRANSFORMERRORPKTS_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_10_TRANSFORMERRORPKTS_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_10_TRANSFORMERRORPKTS_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_10_TRANSFORMERRORPKTS_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_10_TRANSFORMERRORPKTS_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_10_OUTPKTSCTRL_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_10_OUTPKTSCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_10_OUTPKTSCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_10_OUTPKTSCTRL_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_10_OUTPKTSCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_10_OUTPKTSCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_10_OUTPKTSUNTAGGED_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_10_OUTPKTSUNTAGGED_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_10_OUTPKTSUNTAGGED_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_10_OUTPKTSUNTAGGED_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_10_OUTPKTSUNTAGGED_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_10_OUTPKTSUNTAGGED_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_11_TRANSFORMERRORPKTS_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_11_TRANSFORMERRORPKTS_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_11_TRANSFORMERRORPKTS_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_11_TRANSFORMERRORPKTS_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_11_TRANSFORMERRORPKTS_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_11_TRANSFORMERRORPKTS_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_11_OUTPKTSCTRL_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_11_OUTPKTSCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_11_OUTPKTSCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_11_OUTPKTSCTRL_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_11_OUTPKTSCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_11_OUTPKTSCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_11_OUTPKTSUNTAGGED_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_11_OUTPKTSUNTAGGED_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_11_OUTPKTSUNTAGGED_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_11_OUTPKTSUNTAGGED_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_11_OUTPKTSUNTAGGED_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_11_OUTPKTSUNTAGGED_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_12_TRANSFORMERRORPKTS_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_12_TRANSFORMERRORPKTS_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_12_TRANSFORMERRORPKTS_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_12_TRANSFORMERRORPKTS_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_12_TRANSFORMERRORPKTS_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_12_TRANSFORMERRORPKTS_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_12_OUTPKTSCTRL_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_12_OUTPKTSCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_12_OUTPKTSCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_12_OUTPKTSCTRL_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_12_OUTPKTSCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_12_OUTPKTSCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_12_OUTPKTSUNTAGGED_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_12_OUTPKTSUNTAGGED_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_12_OUTPKTSUNTAGGED_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_12_OUTPKTSUNTAGGED_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_12_OUTPKTSUNTAGGED_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_12_OUTPKTSUNTAGGED_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_13_TRANSFORMERRORPKTS_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_13_TRANSFORMERRORPKTS_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_13_TRANSFORMERRORPKTS_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_13_TRANSFORMERRORPKTS_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_13_TRANSFORMERRORPKTS_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_13_TRANSFORMERRORPKTS_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_13_OUTPKTSCTRL_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_13_OUTPKTSCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_13_OUTPKTSCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_13_OUTPKTSCTRL_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_13_OUTPKTSCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_13_OUTPKTSCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_13_OUTPKTSUNTAGGED_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_13_OUTPKTSUNTAGGED_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_13_OUTPKTSUNTAGGED_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_13_OUTPKTSUNTAGGED_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_13_OUTPKTSUNTAGGED_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_13_OUTPKTSUNTAGGED_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_14_TRANSFORMERRORPKTS_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_14_TRANSFORMERRORPKTS_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_14_TRANSFORMERRORPKTS_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_14_TRANSFORMERRORPKTS_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_14_TRANSFORMERRORPKTS_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_14_TRANSFORMERRORPKTS_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_14_OUTPKTSCTRL_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_14_OUTPKTSCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_14_OUTPKTSCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_14_OUTPKTSCTRL_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_14_OUTPKTSCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_14_OUTPKTSCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_14_OUTPKTSUNTAGGED_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_14_OUTPKTSUNTAGGED_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_14_OUTPKTSUNTAGGED_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_14_OUTPKTSUNTAGGED_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_14_OUTPKTSUNTAGGED_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_14_OUTPKTSUNTAGGED_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_15_TRANSFORMERRORPKTS_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_15_TRANSFORMERRORPKTS_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_15_TRANSFORMERRORPKTS_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_15_TRANSFORMERRORPKTS_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_15_TRANSFORMERRORPKTS_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_15_TRANSFORMERRORPKTS_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_15_OUTPKTSCTRL_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_15_OUTPKTSCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_15_OUTPKTSCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_15_OUTPKTSCTRL_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_15_OUTPKTSCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_15_OUTPKTSCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_15_OUTPKTSUNTAGGED_LO_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_15_OUTPKTSUNTAGGED_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_15_OUTPKTSUNTAGGED_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SECY_CNTRS_SECY_15_OUTPKTSUNTAGGED_HI_TYPE;
#define MACSEC_E_SECY_CNTRS_SECY_15_OUTPKTSUNTAGGED_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SECY_CNTRS_SECY_15_OUTPKTSUNTAGGED_HI_COUNTER_SHIFT (0UL)


typedef volatile struct sMACSEC_E_SECY_CNTRS_CNTRSRDBType {
    MACSEC_E_SECY_CNTRS_SECY_0_TRANSFORMERRORPKTS_LO_TYPE m0_transformerrorpkts_lo; /* OFFSET: 0x1a000 */
    MACSEC_E_SECY_CNTRS_SECY_0_TRANSFORMERRORPKTS_HI_TYPE m0_transformerrorpkts_hi; /* OFFSET: 0x1a004 */
    MACSEC_E_SECY_CNTRS_SECY_0_OUTPKTSCTRL_LO_TYPE m0_outpktsctrl_lo; /* OFFSET: 0x1a008 */
    MACSEC_E_SECY_CNTRS_SECY_0_OUTPKTSCTRL_HI_TYPE m0_outpktsctrl_hi; /* OFFSET: 0x1a00c */
    MACSEC_E_SECY_CNTRS_SECY_0_OUTPKTSUNTAGGED_LO_TYPE m0_outpktsuntagged_lo; /* OFFSET: 0x1a010 */
    MACSEC_E_SECY_CNTRS_SECY_0_OUTPKTSUNTAGGED_HI_TYPE m0_outpktsuntagged_hi; /* OFFSET: 0x1a014 */
    MACSEC_E_SECY_CNTRS_RESERVED_TYPE rsvd1[104]; /* OFFSET: 0x1a018 */
} MACSEC_E_SECY_CNTRS_CNTRSRDBType;


#define MACSEC_E_SECY_CNTRS_REGS_SIZE  (16UL)


typedef volatile struct sMACSEC_E_SECY_CNTRS_RDBType {
    MACSEC_E_SECY_CNTRS_RESERVED_TYPE rsvd0[106496]; /* OFFSET: 0x0 */
    MACSEC_E_SECY_CNTRS_CNTRSRDBType regs[MACSEC_E_SECY_CNTRS_REGS_SIZE]; /* OFFSET: 0x1a000 */
} MACSEC_E_SECY_CNTRS_RDBType;

#endif /* MACSEC_E_SECY_CNTRS_RDB_H */
