/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file macsec_sysmisc_rdb.h
    @brief RDB File for MACSEC_SYSMISC

    @version BCM89580_B0_20230817_R18_RDB
*/

#ifndef MACSEC_SYSMISC_RDB_H
#define MACSEC_SYSMISC_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t MACSEC_SYSMISC_MSPU_CTRL1_TYPE;
#define MACSEC_SYSMISC_MSPU_CTRL1_INBOUND_SEL_MASK (0xffffffffUL)
#define MACSEC_SYSMISC_MSPU_CTRL1_INBOUND_SEL_SHIFT (0UL)




typedef uint32_t MACSEC_SYSMISC_MSPU_CTRL2_TYPE;
#define MACSEC_SYSMISC_MSPU_CTRL2_OUTBOUND_SEL_MASK (0xffffffffUL)
#define MACSEC_SYSMISC_MSPU_CTRL2_OUTBOUND_SEL_SHIFT (0UL)




typedef uint32_t MACSEC_SYSMISC_MSPU_CTRL3_TYPE;
#define MACSEC_SYSMISC_MSPU_CTRL3_SOFT_RESET_MASK (0xffffffffUL)
#define MACSEC_SYSMISC_MSPU_CTRL3_SOFT_RESET_SHIFT (0UL)




typedef uint32_t MACSEC_SYSMISC_TESTMODE_CTRL1_TYPE;
#define MACSEC_SYSMISC_TESTMODE_CTRL1_MSPU_INGRESS_MASK (0xffffffffUL)
#define MACSEC_SYSMISC_TESTMODE_CTRL1_MSPU_INGRESS_SHIFT (0UL)




typedef uint32_t MACSEC_SYSMISC_TESTMODE_CTRL2_TYPE;
#define MACSEC_SYSMISC_TESTMODE_CTRL2_MSPU_EGRESS_MASK (0xffffffffUL)
#define MACSEC_SYSMISC_TESTMODE_CTRL2_MSPU_EGRESS_SHIFT (0UL)




typedef uint32_t MACSEC_SYSMISC_PROBESEL_CTRL_TYPE;
#define MACSEC_SYSMISC_PROBESEL_CTRL_MSPU_PROBE_SEL_MASK (0xfUL)
#define MACSEC_SYSMISC_PROBESEL_CTRL_MSPU_PROBE_SEL_SHIFT (0UL)




typedef uint32_t MACSEC_SYSMISC_INTERRUPT_STAT_TYPE;
#define MACSEC_SYSMISC_INTERRUPT_STAT_MSPU_INT_MASK (0xffffffffUL)
#define MACSEC_SYSMISC_INTERRUPT_STAT_MSPU_INT_SHIFT (0UL)




typedef uint32_t MACSEC_SYSMISC_INTERRUPT_MASK_TYPE;
#define MACSEC_SYSMISC_INTERRUPT_MASK_MSPU_INTMASK_MASK (0xffffffffUL)
#define MACSEC_SYSMISC_INTERRUPT_MASK_MSPU_INTMASK_SHIFT (0UL)




typedef uint32_t MACSEC_SYSMISC_INTERRUPT_CLEAR_TYPE;
#define MACSEC_SYSMISC_INTERRUPT_CLEAR_MSPU_11_MASK (0x800UL)
#define MACSEC_SYSMISC_INTERRUPT_CLEAR_MSPU_11_SHIFT (11UL)
#define MACSEC_SYSMISC_INTERRUPT_CLEAR_MSPU_10_MASK (0x400UL)
#define MACSEC_SYSMISC_INTERRUPT_CLEAR_MSPU_10_SHIFT (10UL)
#define MACSEC_SYSMISC_INTERRUPT_CLEAR_MSPU_9_MASK (0x200UL)
#define MACSEC_SYSMISC_INTERRUPT_CLEAR_MSPU_9_SHIFT (9UL)
#define MACSEC_SYSMISC_INTERRUPT_CLEAR_MSPU_8_MASK (0x100UL)
#define MACSEC_SYSMISC_INTERRUPT_CLEAR_MSPU_8_SHIFT (8UL)
#define MACSEC_SYSMISC_INTERRUPT_CLEAR_MSPU_7_MASK (0x80UL)
#define MACSEC_SYSMISC_INTERRUPT_CLEAR_MSPU_7_SHIFT (7UL)
#define MACSEC_SYSMISC_INTERRUPT_CLEAR_MSPU_6_MASK (0x40UL)
#define MACSEC_SYSMISC_INTERRUPT_CLEAR_MSPU_6_SHIFT (6UL)
#define MACSEC_SYSMISC_INTERRUPT_CLEAR_MSPU_5_MASK (0x20UL)
#define MACSEC_SYSMISC_INTERRUPT_CLEAR_MSPU_5_SHIFT (5UL)
#define MACSEC_SYSMISC_INTERRUPT_CLEAR_MSPU_4_MASK (0x10UL)
#define MACSEC_SYSMISC_INTERRUPT_CLEAR_MSPU_4_SHIFT (4UL)
#define MACSEC_SYSMISC_INTERRUPT_CLEAR_MSPU_3_MASK (0x8UL)
#define MACSEC_SYSMISC_INTERRUPT_CLEAR_MSPU_3_SHIFT (3UL)
#define MACSEC_SYSMISC_INTERRUPT_CLEAR_MSPU_2_MASK (0x4UL)
#define MACSEC_SYSMISC_INTERRUPT_CLEAR_MSPU_2_SHIFT (2UL)
#define MACSEC_SYSMISC_INTERRUPT_CLEAR_MSPU_1_MASK (0x2UL)
#define MACSEC_SYSMISC_INTERRUPT_CLEAR_MSPU_1_SHIFT (1UL)
#define MACSEC_SYSMISC_INTERRUPT_CLEAR_MSPU_0_MASK (0x1UL)
#define MACSEC_SYSMISC_INTERRUPT_CLEAR_MSPU_0_SHIFT (0UL)




typedef uint32_t MACSEC_SYSMISC_PES_TYPE;
#define MACSEC_SYSMISC_PES_MSPU_PKTINFLIGHT_EGRESS_MASK (0xffffffffUL)
#define MACSEC_SYSMISC_PES_MSPU_PKTINFLIGHT_EGRESS_SHIFT (0UL)




typedef uint32_t MACSEC_SYSMISC_PIS_TYPE;
#define MACSEC_SYSMISC_PIS_MSPU_11_PKTINFLIGHT_INGRESS_MASK (0xffffffffUL)
#define MACSEC_SYSMISC_PIS_MSPU_11_PKTINFLIGHT_INGRESS_SHIFT (0UL)




typedef uint8_t MACSEC_SYSMISC_RESERVED_TYPE;




typedef uint32_t MACSEC_SYSMISC_SPARE_REG_TYPE;
#define MACSEC_SYSMISC_SPARE_REG_MASK (0xffffffffUL)
#define MACSEC_SYSMISC_SPARE_REG_SHIFT (0UL)


typedef volatile struct sMACSEC_SYSMISC_REGS1_RDBType {
    MACSEC_SYSMISC_INTERRUPT_STAT_TYPE interrupt_stat; /* OFFSET: 0x18 */
    MACSEC_SYSMISC_INTERRUPT_MASK_TYPE interrupt_mask; /* OFFSET: 0x1c */
    MACSEC_SYSMISC_INTERRUPT_CLEAR_TYPE interrupt_clear; /* OFFSET: 0x20 */
    MACSEC_SYSMISC_PES_TYPE pktinflight_egress_stat; /* OFFSET: 0x24 */
    MACSEC_SYSMISC_PIS_TYPE pktinflight_ingress_stat; /* OFFSET: 0x28 */
    MACSEC_SYSMISC_RESERVED_TYPE rsvd0[208]; /* OFFSET: 0x2c */
    MACSEC_SYSMISC_SPARE_REG_TYPE spare_reg; /* OFFSET: 0xfc */
} MACSEC_SYSMISC_REGS1_RDBType;



typedef volatile struct sMACSEC_SYSMISC_RDBType {
    MACSEC_SYSMISC_MSPU_CTRL1_TYPE mspu_ctrl1; /* OFFSET: 0x0 */
    MACSEC_SYSMISC_MSPU_CTRL2_TYPE mspu_ctrl2; /* OFFSET: 0x4 */
    MACSEC_SYSMISC_MSPU_CTRL3_TYPE mspu_ctrl3; /* OFFSET: 0x8 */
    MACSEC_SYSMISC_TESTMODE_CTRL1_TYPE testmode_ctrl1; /* OFFSET: 0xc */
    MACSEC_SYSMISC_TESTMODE_CTRL2_TYPE testmode_ctrl2; /* OFFSET: 0x10 */
    MACSEC_SYSMISC_PROBESEL_CTRL_TYPE probesel_ctrl; /* OFFSET: 0x14 */
    MACSEC_SYSMISC_REGS1_RDBType regs1; /* OFFSET: 0x18 */
} MACSEC_SYSMISC_RDBType;


#define MACSEC_SYSMISC_MSPU_CTRL_0_OUTBOUND_SEL_SHIFT  (10UL)


#define MACSEC_SYSMISC_MSPU_CTRL_0_SOFT_RESET_SHIFT  (20UL)

#endif /* MACSEC_SYSMISC_RDB_H */
