/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file macsec_i_rxsc_camkey_rdb.h
    @brief RDB File for MACSEC_I_RXSC_CAMKEY

    @version BCM89580_AQ_TSLA_A0_20240304_R10
*/

#ifndef MACSEC_I_RXSC_CAMKEY_RDB_H
#define MACSEC_I_RXSC_CAMKEY_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t MACSEC_I_RXSC_CAMKEY_RESERVED_TYPE;




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_0_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_0_31_MASK (0xffffffffUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_0_31_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_0_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_0_63_32_MASK (0xffffffffUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_0_63_32_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_0_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_0_VPORT_INDEX_MASK (0xfUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_0_VPORT_INDEX_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_1_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_1_31_0_MASK (0xffffffffUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_1_31_0_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_1_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_1_63_32_MASK (0xffffffffUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_1_63_32_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_1_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_1_VPORT_INDEX_MASK (0xfUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_1_VPORT_INDEX_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_2_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_2_31_0_MASK (0xffffffffUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_2_31_0_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_2_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_2_63_32_MASK (0xffffffffUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_2_63_32_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_2_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_2_VPORT_INDEX_MASK (0xfUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_2_VPORT_INDEX_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_3_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_3_31_0_MASK (0xffffffffUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_3_31_0_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_3_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_3_63_32_MASK (0xffffffffUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_3_63_32_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_3_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_3_VPORT_INDEX_MASK (0xfUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_3_VPORT_INDEX_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_4_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_4_31_0_MASK (0xffffffffUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_4_31_0_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_4_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_4_63_32_MASK (0xffffffffUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_4_63_32_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_4_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_4_VPORT_INDEX_MASK (0xfUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_4_VPORT_INDEX_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_5_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_5_31_0_MASK (0xffffffffUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_5_31_0_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_5_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_5_63_32_MASK (0xffffffffUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_5_63_32_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_5_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_5_VPORT_INDEX_MASK (0xfUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_5_VPORT_INDEX_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_6_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_6_31_0_MASK (0xffffffffUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_6_31_0_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_6_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_6_63_32_MASK (0xffffffffUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_6_63_32_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_6_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_6_VPORT_INDEX_MASK (0xfUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_6_VPORT_INDEX_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_7_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_7_31_0_MASK (0xffffffffUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_7_31_0_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_7_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_7_63_32_MASK (0xffffffffUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_7_63_32_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_7_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_7_VPORT_INDEX_MASK (0xfUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_7_VPORT_INDEX_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_8_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_8_31_0_MASK (0xffffffffUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_8_31_0_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_8_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_8_63_32_MASK (0xffffffffUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_8_63_32_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_8_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_8_VPORT_INDEX_MASK (0xfUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_8_VPORT_INDEX_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_9_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_9_31_0_MASK (0xffffffffUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_9_31_0_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_9_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_9_63_32_MASK (0xffffffffUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_9_63_32_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_9_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_9_VPORT_INDEX_MASK (0xfUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_9_VPORT_INDEX_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_10_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_10_31_0_MASK (0xffffffffUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_10_31_0_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_10_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_10_63_32_MASK (0xffffffffUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_10_63_32_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_10_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_10_VPORT_INDEX_MASK (0xfUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_10_VPORT_INDEX_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_11_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_11_31_0_MASK (0xffffffffUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_11_31_0_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_11_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_11_63_32_MASK (0xffffffffUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_11_63_32_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_11_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_11_VPORT_INDEX_MASK (0xfUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_11_VPORT_INDEX_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_12_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_12_31_0_MASK (0xffffffffUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_12_31_0_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_12_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_12_63_32_MASK (0xffffffffUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_12_63_32_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_12_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_12_VPORT_INDEX_MASK (0xfUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_12_VPORT_INDEX_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_13_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_13_31_0_MASK (0xffffffffUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_13_31_0_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_13_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_13_63_32_MASK (0xffffffffUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_13_63_32_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_13_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_13_VPORT_INDEX_MASK (0xfUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_13_VPORT_INDEX_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_14_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_14_31_0_MASK (0xffffffffUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_14_31_0_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_14_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_14_63_32_MASK (0xffffffffUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_14_63_32_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_14_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_14_VPORT_INDEX_MASK (0xfUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_14_VPORT_INDEX_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_15_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_15_31_0_MASK (0xffffffffUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_15_31_0_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_15_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_15_63_32_MASK (0xffffffffUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_15_63_32_SHIFT (0UL)




typedef uint32_t MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_15_TYPE;
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_15_VPORT_INDEX_MASK (0xfUL)
#define MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_15_VPORT_INDEX_SHIFT (0UL)


typedef volatile struct sMACSEC_I_RXSC_CAMKEY_SCI_RDBType {
    MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_LO_0_TYPE sci_lo_0; /* OFFSET: 0x3400 */
    MACSEC_I_RXSC_CAMKEY_RXSC_CAM_SCI_HI_0_TYPE sci_hi_0; /* OFFSET: 0x3404 */
    MACSEC_I_RXSC_CAMKEY_RXSC_CAM_CTRL_0_TYPE ctrl_0; /* OFFSET: 0x3408 */
    MACSEC_I_RXSC_CAMKEY_RESERVED_TYPE rsvd1[4]; /* OFFSET: 0x340c */
} MACSEC_I_RXSC_CAMKEY_SCI_RDBType;


#define MACSEC_I_RXSC_CAMKEY_SCI_REGS_SIZE  (16UL)


typedef volatile struct sMACSEC_I_RXSC_CAMKEY_RDBType {
    MACSEC_I_RXSC_CAMKEY_RESERVED_TYPE rsvd0[13312]; /* OFFSET: 0x0 */
    MACSEC_I_RXSC_CAMKEY_SCI_RDBType sci_regs[MACSEC_I_RXSC_CAMKEY_SCI_REGS_SIZE]; /* OFFSET: 0x3400 */
} MACSEC_I_RXSC_CAMKEY_RDBType;

#endif /* MACSEC_I_RXSC_CAMKEY_RDB_H */
