/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file macsec_i_secy_cntrs_rdb.h
    @brief RDB File for MACSEC_I_SECY_CNTRS

    @version BCM89580_AQ_TSLA_A0_20240304_R10
*/

#ifndef MACSEC_I_SECY_CNTRS_RDB_H
#define MACSEC_I_SECY_CNTRS_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t MACSEC_I_SECY_CNTRS_RESERVED_TYPE;




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_0_TRANSFORMERRORPKTS_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_0_TRANSFORMERRORPKTS_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_0_TRANSFORMERRORPKTS_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_0_TRANSFORMERRORPKTS_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_0_TRANSFORMERRORPKTS_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_0_TRANSFORMERRORPKTS_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_0_INPKTSCTRL_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_0_INPKTSCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_0_INPKTSCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_0_INPKTSCTRL_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_0_INPKTSCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_0_INPKTSCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_0_INPKTSUNTAGGED_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_0_INPKTSUNTAGGED_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_0_INPKTSUNTAGGED_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_0_INPKTSUNTAGGED_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_0_INPKTSUNTAGGED_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_0_INPKTSUNTAGGED_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_0_INPKTSNOTAG_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_0_INPKTSNOTAG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_0_INPKTSNOTAG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_0_INPKTSNOTAG_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_0_INPKTSNOTAG_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_0_INPKTSNOTAG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_0_INPKTSBADTAG_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_0_INPKTSBADTAG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_0_INPKTSBADTAG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_0_INPKTSBADTAG_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_0_INPKTSBADTAG_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_0_INPKTSBADTAG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_0_INPKTSNOSCI_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_0_INPKTSNOSCI_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_0_INPKTSNOSCI_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_0_INPKTSNOSCI_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_0_INPKTSNOSCI_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_0_INPKTSNOSCI_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_0_INPKTSUNKNOWNSCI_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_0_INPKTSUNKNOWNSCI_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_0_INPKTSUNKNOWNSCI_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_0_INPKTSUNKNOWNSCI_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_0_INPKTSUNKNOWNSCI_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_0_INPKTSUNKNOWNSCI_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_0_INPKTSTAGGEDCTRL_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_0_INPKTSTAGGEDCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_0_INPKTSTAGGEDCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_0_INPKTSTAGGEDCTRL_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_0_INPKTSTAGGEDCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_0_INPKTSTAGGEDCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_1_TRANSFORMERRORPKTS_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_1_TRANSFORMERRORPKTS_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_1_TRANSFORMERRORPKTS_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_1_TRANSFORMERRORPKTS_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_1_TRANSFORMERRORPKTS_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_1_TRANSFORMERRORPKTS_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_1_INPKTSCTRL_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_1_INPKTSCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_1_INPKTSCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_1_INPKTSCTRL_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_1_INPKTSCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_1_INPKTSCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_1_INPKTSUNTAGGED_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_1_INPKTSUNTAGGED_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_1_INPKTSUNTAGGED_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_1_INPKTSUNTAGGED_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_1_INPKTSUNTAGGED_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_1_INPKTSUNTAGGED_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_1_INPKTSNOTAG_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_1_INPKTSNOTAG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_1_INPKTSNOTAG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_1_INPKTSNOTAG_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_1_INPKTSNOTAG_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_1_INPKTSNOTAG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_1_INPKTSBADTAG_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_1_INPKTSBADTAG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_1_INPKTSBADTAG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_1_INPKTSBADTAG_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_1_INPKTSBADTAG_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_1_INPKTSBADTAG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_1_INPKTSNOSCI_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_1_INPKTSNOSCI_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_1_INPKTSNOSCI_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_1_INPKTSNOSCI_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_1_INPKTSNOSCI_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_1_INPKTSNOSCI_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_1_INPKTSUNKNOWNSCI_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_1_INPKTSUNKNOWNSCI_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_1_INPKTSUNKNOWNSCI_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_1_INPKTSUNKNOWNSCI_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_1_INPKTSUNKNOWNSCI_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_1_INPKTSUNKNOWNSCI_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_1_INPKTSTAGGEDCTRL_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_1_INPKTSTAGGEDCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_1_INPKTSTAGGEDCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_1_INPKTSTAGGEDCTRL_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_1_INPKTSTAGGEDCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_1_INPKTSTAGGEDCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_2_TRANSFORMERRORPKTS_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_2_TRANSFORMERRORPKTS_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_2_TRANSFORMERRORPKTS_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_2_TRANSFORMERRORPKTS_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_2_TRANSFORMERRORPKTS_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_2_TRANSFORMERRORPKTS_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_2_INPKTSCTRL_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_2_INPKTSCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_2_INPKTSCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_2_INPKTSCTRL_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_2_INPKTSCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_2_INPKTSCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_2_INPKTSUNTAGGED_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_2_INPKTSUNTAGGED_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_2_INPKTSUNTAGGED_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_2_INPKTSUNTAGGED_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_2_INPKTSUNTAGGED_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_2_INPKTSUNTAGGED_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_2_INPKTSNOTAG_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_2_INPKTSNOTAG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_2_INPKTSNOTAG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_2_INPKTSNOTAG_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_2_INPKTSNOTAG_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_2_INPKTSNOTAG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_2_INPKTSBADTAG_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_2_INPKTSBADTAG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_2_INPKTSBADTAG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_2_INPKTSBADTAG_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_2_INPKTSBADTAG_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_2_INPKTSBADTAG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_2_INPKTSNOSCI_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_2_INPKTSNOSCI_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_2_INPKTSNOSCI_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_2_INPKTSNOSCI_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_2_INPKTSNOSCI_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_2_INPKTSNOSCI_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_2_INPKTSUNKNOWNSCI_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_2_INPKTSUNKNOWNSCI_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_2_INPKTSUNKNOWNSCI_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_2_INPKTSUNKNOWNSCI_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_2_INPKTSUNKNOWNSCI_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_2_INPKTSUNKNOWNSCI_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_2_INPKTSTAGGEDCTRL_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_2_INPKTSTAGGEDCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_2_INPKTSTAGGEDCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_2_INPKTSTAGGEDCTRL_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_2_INPKTSTAGGEDCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_2_INPKTSTAGGEDCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_3_TRANSFORMERRORPKTS_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_3_TRANSFORMERRORPKTS_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_3_TRANSFORMERRORPKTS_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_3_TRANSFORMERRORPKTS_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_3_TRANSFORMERRORPKTS_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_3_TRANSFORMERRORPKTS_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_3_INPKTSCTRL_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_3_INPKTSCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_3_INPKTSCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_3_INPKTSCTRL_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_3_INPKTSCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_3_INPKTSCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_3_INPKTSUNTAGGED_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_3_INPKTSUNTAGGED_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_3_INPKTSUNTAGGED_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_3_INPKTSUNTAGGED_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_3_INPKTSUNTAGGED_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_3_INPKTSUNTAGGED_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_3_INPKTSNOTAG_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_3_INPKTSNOTAG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_3_INPKTSNOTAG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_3_INPKTSNOTAG_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_3_INPKTSNOTAG_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_3_INPKTSNOTAG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_3_INPKTSBADTAG_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_3_INPKTSBADTAG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_3_INPKTSBADTAG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_3_INPKTSBADTAG_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_3_INPKTSBADTAG_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_3_INPKTSBADTAG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_3_INPKTSNOSCI_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_3_INPKTSNOSCI_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_3_INPKTSNOSCI_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_3_INPKTSNOSCI_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_3_INPKTSNOSCI_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_3_INPKTSNOSCI_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_3_INPKTSUNKNOWNSCI_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_3_INPKTSUNKNOWNSCI_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_3_INPKTSUNKNOWNSCI_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_3_INPKTSUNKNOWNSCI_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_3_INPKTSUNKNOWNSCI_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_3_INPKTSUNKNOWNSCI_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_3_INPKTSTAGGEDCTRL_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_3_INPKTSTAGGEDCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_3_INPKTSTAGGEDCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_3_INPKTSTAGGEDCTRL_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_3_INPKTSTAGGEDCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_3_INPKTSTAGGEDCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_4_TRANSFORMERRORPKTS_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_4_TRANSFORMERRORPKTS_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_4_TRANSFORMERRORPKTS_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_4_TRANSFORMERRORPKTS_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_4_TRANSFORMERRORPKTS_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_4_TRANSFORMERRORPKTS_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_4_INPKTSCTRL_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_4_INPKTSCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_4_INPKTSCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_4_INPKTSCTRL_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_4_INPKTSCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_4_INPKTSCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_4_INPKTSUNTAGGED_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_4_INPKTSUNTAGGED_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_4_INPKTSUNTAGGED_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_4_INPKTSUNTAGGED_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_4_INPKTSUNTAGGED_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_4_INPKTSUNTAGGED_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_4_INPKTSNOTAG_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_4_INPKTSNOTAG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_4_INPKTSNOTAG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_4_INPKTSNOTAG_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_4_INPKTSNOTAG_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_4_INPKTSNOTAG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_4_INPKTSBADTAG_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_4_INPKTSBADTAG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_4_INPKTSBADTAG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_4_INPKTSBADTAG_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_4_INPKTSBADTAG_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_4_INPKTSBADTAG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_4_INPKTSNOSCI_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_4_INPKTSNOSCI_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_4_INPKTSNOSCI_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_4_INPKTSNOSCI_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_4_INPKTSNOSCI_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_4_INPKTSNOSCI_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_4_INPKTSUNKNOWNSCI_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_4_INPKTSUNKNOWNSCI_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_4_INPKTSUNKNOWNSCI_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_4_INPKTSUNKNOWNSCI_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_4_INPKTSUNKNOWNSCI_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_4_INPKTSUNKNOWNSCI_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_4_INPKTSTAGGEDCTRL_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_4_INPKTSTAGGEDCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_4_INPKTSTAGGEDCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_4_INPKTSTAGGEDCTRL_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_4_INPKTSTAGGEDCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_4_INPKTSTAGGEDCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_5_TRANSFORMERRORPKTS_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_5_TRANSFORMERRORPKTS_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_5_TRANSFORMERRORPKTS_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_5_TRANSFORMERRORPKTS_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_5_TRANSFORMERRORPKTS_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_5_TRANSFORMERRORPKTS_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_5_INPKTSCTRL_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_5_INPKTSCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_5_INPKTSCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_5_INPKTSCTRL_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_5_INPKTSCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_5_INPKTSCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_5_INPKTSUNTAGGED_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_5_INPKTSUNTAGGED_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_5_INPKTSUNTAGGED_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_5_INPKTSUNTAGGED_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_5_INPKTSUNTAGGED_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_5_INPKTSUNTAGGED_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_5_INPKTSNOTAG_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_5_INPKTSNOTAG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_5_INPKTSNOTAG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_5_INPKTSNOTAG_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_5_INPKTSNOTAG_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_5_INPKTSNOTAG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_5_INPKTSBADTAG_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_5_INPKTSBADTAG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_5_INPKTSBADTAG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_5_INPKTSBADTAG_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_5_INPKTSBADTAG_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_5_INPKTSBADTAG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_5_INPKTSNOSCI_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_5_INPKTSNOSCI_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_5_INPKTSNOSCI_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_5_INPKTSNOSCI_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_5_INPKTSNOSCI_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_5_INPKTSNOSCI_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_5_INPKTSUNKNOWNSCI_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_5_INPKTSUNKNOWNSCI_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_5_INPKTSUNKNOWNSCI_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_5_INPKTSUNKNOWNSCI_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_5_INPKTSUNKNOWNSCI_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_5_INPKTSUNKNOWNSCI_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_5_INPKTSTAGGEDCTRL_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_5_INPKTSTAGGEDCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_5_INPKTSTAGGEDCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_5_INPKTSTAGGEDCTRL_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_5_INPKTSTAGGEDCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_5_INPKTSTAGGEDCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_6_TRANSFORMERRORPKTS_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_6_TRANSFORMERRORPKTS_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_6_TRANSFORMERRORPKTS_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_6_TRANSFORMERRORPKTS_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_6_TRANSFORMERRORPKTS_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_6_TRANSFORMERRORPKTS_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_6_INPKTSCTRL_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_6_INPKTSCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_6_INPKTSCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_6_INPKTSCTRL_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_6_INPKTSCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_6_INPKTSCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_6_INPKTSUNTAGGED_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_6_INPKTSUNTAGGED_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_6_INPKTSUNTAGGED_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_6_INPKTSUNTAGGED_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_6_INPKTSUNTAGGED_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_6_INPKTSUNTAGGED_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_6_INPKTSNOTAG_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_6_INPKTSNOTAG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_6_INPKTSNOTAG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_6_INPKTSNOTAG_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_6_INPKTSNOTAG_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_6_INPKTSNOTAG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_6_INPKTSBADTAG_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_6_INPKTSBADTAG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_6_INPKTSBADTAG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_6_INPKTSBADTAG_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_6_INPKTSBADTAG_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_6_INPKTSBADTAG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_6_INPKTSNOSCI_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_6_INPKTSNOSCI_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_6_INPKTSNOSCI_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_6_INPKTSNOSCI_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_6_INPKTSNOSCI_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_6_INPKTSNOSCI_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_6_INPKTSUNKNOWNSCI_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_6_INPKTSUNKNOWNSCI_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_6_INPKTSUNKNOWNSCI_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_6_INPKTSUNKNOWNSCI_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_6_INPKTSUNKNOWNSCI_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_6_INPKTSUNKNOWNSCI_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_6_INPKTSTAGGEDCTRL_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_6_INPKTSTAGGEDCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_6_INPKTSTAGGEDCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_6_INPKTSTAGGEDCTRL_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_6_INPKTSTAGGEDCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_6_INPKTSTAGGEDCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_7_TRANSFORMERRORPKTS_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_7_TRANSFORMERRORPKTS_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_7_TRANSFORMERRORPKTS_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_7_TRANSFORMERRORPKTS_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_7_TRANSFORMERRORPKTS_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_7_TRANSFORMERRORPKTS_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_7_INPKTSCTRL_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_7_INPKTSCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_7_INPKTSCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_7_INPKTSCTRL_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_7_INPKTSCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_7_INPKTSCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_7_INPKTSUNTAGGED_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_7_INPKTSUNTAGGED_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_7_INPKTSUNTAGGED_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_7_INPKTSUNTAGGED_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_7_INPKTSUNTAGGED_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_7_INPKTSUNTAGGED_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_7_INPKTSNOTAG_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_7_INPKTSNOTAG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_7_INPKTSNOTAG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_7_INPKTSNOTAG_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_7_INPKTSNOTAG_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_7_INPKTSNOTAG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_7_INPKTSBADTAG_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_7_INPKTSBADTAG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_7_INPKTSBADTAG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_7_INPKTSBADTAG_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_7_INPKTSBADTAG_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_7_INPKTSBADTAG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_7_INPKTSNOSCI_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_7_INPKTSNOSCI_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_7_INPKTSNOSCI_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_7_INPKTSNOSCI_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_7_INPKTSNOSCI_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_7_INPKTSNOSCI_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_7_INPKTSUNKNOWNSCI_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_7_INPKTSUNKNOWNSCI_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_7_INPKTSUNKNOWNSCI_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_7_INPKTSUNKNOWNSCI_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_7_INPKTSUNKNOWNSCI_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_7_INPKTSUNKNOWNSCI_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_7_INPKTSTAGGEDCTRL_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_7_INPKTSTAGGEDCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_7_INPKTSTAGGEDCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_7_INPKTSTAGGEDCTRL_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_7_INPKTSTAGGEDCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_7_INPKTSTAGGEDCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_8_TRANSFORMERRORPKTS_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_8_TRANSFORMERRORPKTS_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_8_TRANSFORMERRORPKTS_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_8_TRANSFORMERRORPKTS_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_8_TRANSFORMERRORPKTS_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_8_TRANSFORMERRORPKTS_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_8_INPKTSCTRL_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_8_INPKTSCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_8_INPKTSCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_8_INPKTSCTRL_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_8_INPKTSCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_8_INPKTSCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_8_INPKTSUNTAGGED_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_8_INPKTSUNTAGGED_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_8_INPKTSUNTAGGED_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_8_INPKTSUNTAGGED_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_8_INPKTSUNTAGGED_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_8_INPKTSUNTAGGED_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_8_INPKTSNOTAG_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_8_INPKTSNOTAG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_8_INPKTSNOTAG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_8_INPKTSNOTAG_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_8_INPKTSNOTAG_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_8_INPKTSNOTAG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_8_INPKTSBADTAG_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_8_INPKTSBADTAG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_8_INPKTSBADTAG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_8_INPKTSBADTAG_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_8_INPKTSBADTAG_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_8_INPKTSBADTAG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_8_INPKTSNOSCI_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_8_INPKTSNOSCI_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_8_INPKTSNOSCI_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_8_INPKTSNOSCI_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_8_INPKTSNOSCI_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_8_INPKTSNOSCI_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_8_INPKTSUNKNOWNSCI_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_8_INPKTSUNKNOWNSCI_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_8_INPKTSUNKNOWNSCI_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_8_INPKTSUNKNOWNSCI_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_8_INPKTSUNKNOWNSCI_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_8_INPKTSUNKNOWNSCI_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_8_INPKTSTAGGEDCTRL_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_8_INPKTSTAGGEDCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_8_INPKTSTAGGEDCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_8_INPKTSTAGGEDCTRL_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_8_INPKTSTAGGEDCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_8_INPKTSTAGGEDCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_9_TRANSFORMERRORPKTS_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_9_TRANSFORMERRORPKTS_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_9_TRANSFORMERRORPKTS_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_9_TRANSFORMERRORPKTS_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_9_TRANSFORMERRORPKTS_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_9_TRANSFORMERRORPKTS_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_9_INPKTSCTRL_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_9_INPKTSCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_9_INPKTSCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_9_INPKTSCTRL_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_9_INPKTSCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_9_INPKTSCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_9_INPKTSUNTAGGED_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_9_INPKTSUNTAGGED_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_9_INPKTSUNTAGGED_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_9_INPKTSUNTAGGED_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_9_INPKTSUNTAGGED_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_9_INPKTSUNTAGGED_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_9_INPKTSNOTAG_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_9_INPKTSNOTAG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_9_INPKTSNOTAG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_9_INPKTSNOTAG_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_9_INPKTSNOTAG_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_9_INPKTSNOTAG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_9_INPKTSBADTAG_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_9_INPKTSBADTAG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_9_INPKTSBADTAG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_9_INPKTSBADTAG_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_9_INPKTSBADTAG_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_9_INPKTSBADTAG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_9_INPKTSNOSCI_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_9_INPKTSNOSCI_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_9_INPKTSNOSCI_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_9_INPKTSNOSCI_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_9_INPKTSNOSCI_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_9_INPKTSNOSCI_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_9_INPKTSUNKNOWNSCI_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_9_INPKTSUNKNOWNSCI_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_9_INPKTSUNKNOWNSCI_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_9_INPKTSUNKNOWNSCI_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_9_INPKTSUNKNOWNSCI_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_9_INPKTSUNKNOWNSCI_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_9_INPKTSTAGGEDCTRL_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_9_INPKTSTAGGEDCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_9_INPKTSTAGGEDCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_9_INPKTSTAGGEDCTRL_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_9_INPKTSTAGGEDCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_9_INPKTSTAGGEDCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_10_TRANSFORMERRORPKTS_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_10_TRANSFORMERRORPKTS_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_10_TRANSFORMERRORPKTS_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_10_TRANSFORMERRORPKTS_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_10_TRANSFORMERRORPKTS_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_10_TRANSFORMERRORPKTS_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_10_INPKTSCTRL_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_10_INPKTSCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_10_INPKTSCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_10_INPKTSCTRL_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_10_INPKTSCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_10_INPKTSCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_10_INPKTSUNTAGGED_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_10_INPKTSUNTAGGED_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_10_INPKTSUNTAGGED_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_10_INPKTSUNTAGGED_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_10_INPKTSUNTAGGED_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_10_INPKTSUNTAGGED_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_10_INPKTSNOTAG_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_10_INPKTSNOTAG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_10_INPKTSNOTAG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_10_INPKTSNOTAG_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_10_INPKTSNOTAG_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_10_INPKTSNOTAG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_10_INPKTSBADTAG_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_10_INPKTSBADTAG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_10_INPKTSBADTAG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_10_INPKTSBADTAG_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_10_INPKTSBADTAG_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_10_INPKTSBADTAG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_10_INPKTSNOSCI_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_10_INPKTSNOSCI_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_10_INPKTSNOSCI_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_10_INPKTSNOSCI_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_10_INPKTSNOSCI_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_10_INPKTSNOSCI_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_10_INPKTSUNKNOWNSCI_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_10_INPKTSUNKNOWNSCI_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_10_INPKTSUNKNOWNSCI_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_10_INPKTSUNKNOWNSCI_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_10_INPKTSUNKNOWNSCI_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_10_INPKTSUNKNOWNSCI_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_10_INPKTSTAGGEDCTRL_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_10_INPKTSTAGGEDCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_10_INPKTSTAGGEDCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_10_INPKTSTAGGEDCTRL_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_10_INPKTSTAGGEDCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_10_INPKTSTAGGEDCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_11_TRANSFORMERRORPKTS_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_11_TRANSFORMERRORPKTS_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_11_TRANSFORMERRORPKTS_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_11_TRANSFORMERRORPKTS_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_11_TRANSFORMERRORPKTS_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_11_TRANSFORMERRORPKTS_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_11_INPKTSCTRL_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_11_INPKTSCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_11_INPKTSCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_11_INPKTSCTRL_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_11_INPKTSCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_11_INPKTSCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_11_INPKTSUNTAGGED_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_11_INPKTSUNTAGGED_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_11_INPKTSUNTAGGED_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_11_INPKTSUNTAGGED_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_11_INPKTSUNTAGGED_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_11_INPKTSUNTAGGED_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_11_INPKTSNOTAG_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_11_INPKTSNOTAG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_11_INPKTSNOTAG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_11_INPKTSNOTAG_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_11_INPKTSNOTAG_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_11_INPKTSNOTAG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_11_INPKTSBADTAG_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_11_INPKTSBADTAG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_11_INPKTSBADTAG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_11_INPKTSBADTAG_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_11_INPKTSBADTAG_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_11_INPKTSBADTAG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_11_INPKTSNOSCI_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_11_INPKTSNOSCI_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_11_INPKTSNOSCI_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_11_INPKTSNOSCI_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_11_INPKTSNOSCI_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_11_INPKTSNOSCI_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_11_INPKTSUNKNOWNSCI_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_11_INPKTSUNKNOWNSCI_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_11_INPKTSUNKNOWNSCI_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_11_INPKTSUNKNOWNSCI_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_11_INPKTSUNKNOWNSCI_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_11_INPKTSUNKNOWNSCI_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_11_INPKTSTAGGEDCTRL_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_11_INPKTSTAGGEDCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_11_INPKTSTAGGEDCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_11_INPKTSTAGGEDCTRL_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_11_INPKTSTAGGEDCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_11_INPKTSTAGGEDCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_12_TRANSFORMERRORPKTS_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_12_TRANSFORMERRORPKTS_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_12_TRANSFORMERRORPKTS_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_12_TRANSFORMERRORPKTS_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_12_TRANSFORMERRORPKTS_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_12_TRANSFORMERRORPKTS_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_12_INPKTSCTRL_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_12_INPKTSCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_12_INPKTSCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_12_INPKTSCTRL_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_12_INPKTSCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_12_INPKTSCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_12_INPKTSUNTAGGED_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_12_INPKTSUNTAGGED_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_12_INPKTSUNTAGGED_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_12_INPKTSUNTAGGED_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_12_INPKTSUNTAGGED_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_12_INPKTSUNTAGGED_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_12_INPKTSNOTAG_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_12_INPKTSNOTAG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_12_INPKTSNOTAG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_12_INPKTSNOTAG_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_12_INPKTSNOTAG_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_12_INPKTSNOTAG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_12_INPKTSBADTAG_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_12_INPKTSBADTAG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_12_INPKTSBADTAG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_12_INPKTSBADTAG_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_12_INPKTSBADTAG_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_12_INPKTSBADTAG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_12_INPKTSNOSCI_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_12_INPKTSNOSCI_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_12_INPKTSNOSCI_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_12_INPKTSNOSCI_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_12_INPKTSNOSCI_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_12_INPKTSNOSCI_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_12_INPKTSUNKNOWNSCI_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_12_INPKTSUNKNOWNSCI_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_12_INPKTSUNKNOWNSCI_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_12_INPKTSUNKNOWNSCI_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_12_INPKTSUNKNOWNSCI_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_12_INPKTSUNKNOWNSCI_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_12_INPKTSTAGGEDCTRL_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_12_INPKTSTAGGEDCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_12_INPKTSTAGGEDCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_12_INPKTSTAGGEDCTRL_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_12_INPKTSTAGGEDCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_12_INPKTSTAGGEDCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_13_TRANSFORMERRORPKTS_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_13_TRANSFORMERRORPKTS_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_13_TRANSFORMERRORPKTS_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_13_TRANSFORMERRORPKTS_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_13_TRANSFORMERRORPKTS_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_13_TRANSFORMERRORPKTS_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_13_INPKTSCTRL_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_13_INPKTSCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_13_INPKTSCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_13_INPKTSCTRL_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_13_INPKTSCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_13_INPKTSCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_13_INPKTSUNTAGGED_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_13_INPKTSUNTAGGED_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_13_INPKTSUNTAGGED_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_13_INPKTSUNTAGGED_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_13_INPKTSUNTAGGED_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_13_INPKTSUNTAGGED_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_13_INPKTSNOTAG_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_13_INPKTSNOTAG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_13_INPKTSNOTAG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_13_INPKTSNOTAG_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_13_INPKTSNOTAG_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_13_INPKTSNOTAG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_13_INPKTSBADTAG_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_13_INPKTSBADTAG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_13_INPKTSBADTAG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_13_INPKTSBADTAG_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_13_INPKTSBADTAG_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_13_INPKTSBADTAG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_13_INPKTSNOSCI_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_13_INPKTSNOSCI_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_13_INPKTSNOSCI_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_13_INPKTSNOSCI_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_13_INPKTSNOSCI_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_13_INPKTSNOSCI_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_13_INPKTSUNKNOWNSCI_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_13_INPKTSUNKNOWNSCI_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_13_INPKTSUNKNOWNSCI_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_13_INPKTSUNKNOWNSCI_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_13_INPKTSUNKNOWNSCI_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_13_INPKTSUNKNOWNSCI_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_13_INPKTSTAGGEDCTRL_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_13_INPKTSTAGGEDCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_13_INPKTSTAGGEDCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_13_INPKTSTAGGEDCTRL_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_13_INPKTSTAGGEDCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_13_INPKTSTAGGEDCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_14_TRANSFORMERRORPKTS_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_14_TRANSFORMERRORPKTS_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_14_TRANSFORMERRORPKTS_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_14_TRANSFORMERRORPKTS_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_14_TRANSFORMERRORPKTS_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_14_TRANSFORMERRORPKTS_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_14_INPKTSCTRL_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_14_INPKTSCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_14_INPKTSCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_14_INPKTSCTRL_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_14_INPKTSCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_14_INPKTSCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_14_INPKTSUNTAGGED_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_14_INPKTSUNTAGGED_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_14_INPKTSUNTAGGED_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_14_INPKTSUNTAGGED_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_14_INPKTSUNTAGGED_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_14_INPKTSUNTAGGED_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_14_INPKTSNOTAG_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_14_INPKTSNOTAG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_14_INPKTSNOTAG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_14_INPKTSNOTAG_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_14_INPKTSNOTAG_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_14_INPKTSNOTAG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_14_INPKTSBADTAG_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_14_INPKTSBADTAG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_14_INPKTSBADTAG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_14_INPKTSBADTAG_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_14_INPKTSBADTAG_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_14_INPKTSBADTAG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_14_INPKTSNOSCI_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_14_INPKTSNOSCI_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_14_INPKTSNOSCI_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_14_INPKTSNOSCI_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_14_INPKTSNOSCI_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_14_INPKTSNOSCI_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_14_INPKTSUNKNOWNSCI_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_14_INPKTSUNKNOWNSCI_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_14_INPKTSUNKNOWNSCI_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_14_INPKTSUNKNOWNSCI_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_14_INPKTSUNKNOWNSCI_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_14_INPKTSUNKNOWNSCI_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_14_INPKTSTAGGEDCTRL_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_14_INPKTSTAGGEDCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_14_INPKTSTAGGEDCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_14_INPKTSTAGGEDCTRL_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_14_INPKTSTAGGEDCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_14_INPKTSTAGGEDCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_15_TRANSFORMERRORPKTS_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_15_TRANSFORMERRORPKTS_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_15_TRANSFORMERRORPKTS_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_15_TRANSFORMERRORPKTS_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_15_TRANSFORMERRORPKTS_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_15_TRANSFORMERRORPKTS_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_15_INPKTSCTRL_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_15_INPKTSCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_15_INPKTSCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_15_INPKTSCTRL_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_15_INPKTSCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_15_INPKTSCTRL_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_15_INPKTSUNTAGGED_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_15_INPKTSUNTAGGED_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_15_INPKTSUNTAGGED_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_15_INPKTSUNTAGGED_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_15_INPKTSUNTAGGED_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_15_INPKTSUNTAGGED_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_15_INPKTSNOTAG_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_15_INPKTSNOTAG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_15_INPKTSNOTAG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_15_INPKTSNOTAG_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_15_INPKTSNOTAG_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_15_INPKTSNOTAG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_15_INPKTSBADTAG_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_15_INPKTSBADTAG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_15_INPKTSBADTAG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_15_INPKTSBADTAG_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_15_INPKTSBADTAG_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_15_INPKTSBADTAG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_15_INPKTSNOSCI_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_15_INPKTSNOSCI_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_15_INPKTSNOSCI_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_15_INPKTSNOSCI_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_15_INPKTSNOSCI_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_15_INPKTSNOSCI_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_15_INPKTSUNKNOWNSCI_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_15_INPKTSUNKNOWNSCI_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_15_INPKTSUNKNOWNSCI_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_15_INPKTSUNKNOWNSCI_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_15_INPKTSUNKNOWNSCI_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_15_INPKTSUNKNOWNSCI_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_15_INPKTSTAGGEDCTRL_LO_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_15_INPKTSTAGGEDCTRL_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_15_INPKTSTAGGEDCTRL_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_SECY_CNTRS_SECY_15_INPKTSTAGGEDCTRL_HI_TYPE;
#define MACSEC_I_SECY_CNTRS_SECY_15_INPKTSTAGGEDCTRL_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_SECY_CNTRS_SECY_15_INPKTSTAGGEDCTRL_HI_COUNTER_SHIFT (0UL)


typedef volatile struct sMACSEC_I_SECY_CNTRS_CNTRSRDBType {
    MACSEC_I_SECY_CNTRS_SECY_0_TRANSFORMERRORPKTS_LO_TYPE m0_transformerrorpkts_lo; /* OFFSET: 0xa000 */
    MACSEC_I_SECY_CNTRS_SECY_0_TRANSFORMERRORPKTS_HI_TYPE m0_transformerrorpkts_hi; /* OFFSET: 0xa004 */
    MACSEC_I_SECY_CNTRS_SECY_0_INPKTSCTRL_LO_TYPE m0_inpktsctrl_lo; /* OFFSET: 0xa008 */
    MACSEC_I_SECY_CNTRS_SECY_0_INPKTSCTRL_HI_TYPE m0_inpktsctrl_hi; /* OFFSET: 0xa00c */
    MACSEC_I_SECY_CNTRS_SECY_0_INPKTSUNTAGGED_LO_TYPE m0_inpktsuntagged_lo; /* OFFSET: 0xa010 */
    MACSEC_I_SECY_CNTRS_SECY_0_INPKTSUNTAGGED_HI_TYPE m0_inpktsuntagged_hi; /* OFFSET: 0xa014 */
    MACSEC_I_SECY_CNTRS_SECY_0_INPKTSNOTAG_LO_TYPE m0_inpktsnotag_lo; /* OFFSET: 0xa018 */
    MACSEC_I_SECY_CNTRS_SECY_0_INPKTSNOTAG_HI_TYPE m0_inpktsnotag_hi; /* OFFSET: 0xa01c */
    MACSEC_I_SECY_CNTRS_SECY_0_INPKTSBADTAG_LO_TYPE m0_inpktsbadtag_lo; /* OFFSET: 0xa020 */
    MACSEC_I_SECY_CNTRS_SECY_0_INPKTSBADTAG_HI_TYPE m0_inpktsbadtag_hi; /* OFFSET: 0xa024 */
    MACSEC_I_SECY_CNTRS_SECY_0_INPKTSNOSCI_LO_TYPE m0_inpktsnosci_lo; /* OFFSET: 0xa028 */
    MACSEC_I_SECY_CNTRS_SECY_0_INPKTSNOSCI_HI_TYPE m0_inpktsnosci_hi; /* OFFSET: 0xa02c */
    MACSEC_I_SECY_CNTRS_SECY_0_INPKTSUNKNOWNSCI_LO_TYPE m0_inpktsunknownsci_lo; /* OFFSET: 0xa030 */
    MACSEC_I_SECY_CNTRS_SECY_0_INPKTSUNKNOWNSCI_HI_TYPE m0_inpktsunknownsci_hi; /* OFFSET: 0xa034 */
    MACSEC_I_SECY_CNTRS_SECY_0_INPKTSTAGGEDCTRL_LO_TYPE m0_inpktstaggedctrl_lo; /* OFFSET: 0xa038 */
    MACSEC_I_SECY_CNTRS_SECY_0_INPKTSTAGGEDCTRL_HI_TYPE m0_inpktstaggedctrl_hi; /* OFFSET: 0xa03c */
    MACSEC_I_SECY_CNTRS_RESERVED_TYPE rsvd1[64]; /* OFFSET: 0xa040 */
} MACSEC_I_SECY_CNTRS_CNTRSRDBType;


#define MACSEC_I_SECY_CNTRS_REGS_SIZE  (16UL)


typedef volatile struct sMACSEC_I_SECY_CNTRS_RDBType {
    MACSEC_I_SECY_CNTRS_RESERVED_TYPE rsvd0[40960]; /* OFFSET: 0x0 */
    MACSEC_I_SECY_CNTRS_CNTRSRDBType regs[MACSEC_I_SECY_CNTRS_REGS_SIZE]; /* OFFSET: 0xa000 */
} MACSEC_I_SECY_CNTRS_RDBType;

#endif /* MACSEC_I_SECY_CNTRS_RDB_H */
