/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file macsec_eip165_aic_regs_rdb.h
    @brief RDB File for MACSEC_EIP165_AIC_REGS

    @version BCM89580_AQ_TSLA_A0_20240304_R10
*/

#ifndef MACSEC_EIP165_AIC_REGS_RDB_H
#define MACSEC_EIP165_AIC_REGS_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t MACSEC_EIP165_AIC_REGS_RESERVED_TYPE;




typedef uint32_t MACSEC_EIP165_AIC_REGS_AIC_POL_CTRL_TYPE;
#define MACSEC_EIP165_AIC_REGS_AIC_POL_CTRL_POLARITY_CONTROL_0_MASK (0x1UL)
#define MACSEC_EIP165_AIC_REGS_AIC_POL_CTRL_POLARITY_CONTROL_0_SHIFT (0UL)
#define MACSEC_EIP165_AIC_REGS_AIC_POL_CTRL_POLARITY_CONTROL_1_MASK (0x2UL)
#define MACSEC_EIP165_AIC_REGS_AIC_POL_CTRL_POLARITY_CONTROL_1_SHIFT (1UL)
#define MACSEC_EIP165_AIC_REGS_AIC_POL_CTRL_POLARITY_CONTROL_2_MASK (0x4UL)
#define MACSEC_EIP165_AIC_REGS_AIC_POL_CTRL_POLARITY_CONTROL_2_SHIFT (2UL)
#define MACSEC_EIP165_AIC_REGS_AIC_POL_CTRL_POLARITY_CONTROL_3_MASK (0x8UL)
#define MACSEC_EIP165_AIC_REGS_AIC_POL_CTRL_POLARITY_CONTROL_3_SHIFT (3UL)
#define MACSEC_EIP165_AIC_REGS_AIC_POL_CTRL_POLARITY_CONTROL_4_MASK (0x10UL)
#define MACSEC_EIP165_AIC_REGS_AIC_POL_CTRL_POLARITY_CONTROL_4_SHIFT (4UL)
#define MACSEC_EIP165_AIC_REGS_AIC_POL_CTRL_POLARITY_CONTROL_5_MASK (0x20UL)
#define MACSEC_EIP165_AIC_REGS_AIC_POL_CTRL_POLARITY_CONTROL_5_SHIFT (5UL)
#define MACSEC_EIP165_AIC_REGS_AIC_POL_CTRL_POLARITY_CONTROL_6_MASK (0x40UL)
#define MACSEC_EIP165_AIC_REGS_AIC_POL_CTRL_POLARITY_CONTROL_6_SHIFT (6UL)
#define MACSEC_EIP165_AIC_REGS_AIC_POL_CTRL_POLARITY_CONTROL_7_MASK (0x80UL)
#define MACSEC_EIP165_AIC_REGS_AIC_POL_CTRL_POLARITY_CONTROL_7_SHIFT (7UL)
#define MACSEC_EIP165_AIC_REGS_AIC_POL_CTRL_POLARITY_CONTROL_8_MASK (0x100UL)
#define MACSEC_EIP165_AIC_REGS_AIC_POL_CTRL_POLARITY_CONTROL_8_SHIFT (8UL)
#define MACSEC_EIP165_AIC_REGS_AIC_POL_CTRL_POLARITY_CONTROL_9_MASK (0x200UL)
#define MACSEC_EIP165_AIC_REGS_AIC_POL_CTRL_POLARITY_CONTROL_9_SHIFT (9UL)
#define MACSEC_EIP165_AIC_REGS_AIC_POL_CTRL_POLARITY_CONTROL_10_MASK (0x400UL)
#define MACSEC_EIP165_AIC_REGS_AIC_POL_CTRL_POLARITY_CONTROL_10_SHIFT (10UL)
#define MACSEC_EIP165_AIC_REGS_AIC_POL_CTRL_POLARITY_CONTROL_11_MASK (0x800UL)
#define MACSEC_EIP165_AIC_REGS_AIC_POL_CTRL_POLARITY_CONTROL_11_SHIFT (11UL)
#define MACSEC_EIP165_AIC_REGS_AIC_POL_CTRL_POLARITY_CONTROL_12_MASK (0x1000UL)
#define MACSEC_EIP165_AIC_REGS_AIC_POL_CTRL_POLARITY_CONTROL_12_SHIFT (12UL)




typedef uint32_t MACSEC_EIP165_AIC_REGS_AIC_CTRL_TYPE;
#define MACSEC_EIP165_AIC_REGS_AIC_CTRL_TYPE_CONTROL_0_MASK (0x1UL)
#define MACSEC_EIP165_AIC_REGS_AIC_CTRL_TYPE_CONTROL_0_SHIFT (0UL)
#define MACSEC_EIP165_AIC_REGS_AIC_CTRL_TYPE_CONTROL_1_MASK (0x2UL)
#define MACSEC_EIP165_AIC_REGS_AIC_CTRL_TYPE_CONTROL_1_SHIFT (1UL)
#define MACSEC_EIP165_AIC_REGS_AIC_CTRL_TYPE_CONTROL_2_MASK (0x4UL)
#define MACSEC_EIP165_AIC_REGS_AIC_CTRL_TYPE_CONTROL_2_SHIFT (2UL)
#define MACSEC_EIP165_AIC_REGS_AIC_CTRL_TYPE_CONTROL_3_MASK (0x8UL)
#define MACSEC_EIP165_AIC_REGS_AIC_CTRL_TYPE_CONTROL_3_SHIFT (3UL)
#define MACSEC_EIP165_AIC_REGS_AIC_CTRL_TYPE_CONTROL_4_MASK (0x10UL)
#define MACSEC_EIP165_AIC_REGS_AIC_CTRL_TYPE_CONTROL_4_SHIFT (4UL)
#define MACSEC_EIP165_AIC_REGS_AIC_CTRL_TYPE_CONTROL_5_MASK (0x20UL)
#define MACSEC_EIP165_AIC_REGS_AIC_CTRL_TYPE_CONTROL_5_SHIFT (5UL)
#define MACSEC_EIP165_AIC_REGS_AIC_CTRL_TYPE_CONTROL_6_MASK (0x40UL)
#define MACSEC_EIP165_AIC_REGS_AIC_CTRL_TYPE_CONTROL_6_SHIFT (6UL)
#define MACSEC_EIP165_AIC_REGS_AIC_CTRL_TYPE_CONTROL_7_MASK (0x80UL)
#define MACSEC_EIP165_AIC_REGS_AIC_CTRL_TYPE_CONTROL_7_SHIFT (7UL)
#define MACSEC_EIP165_AIC_REGS_AIC_CTRL_TYPE_CONTROL_8_MASK (0x100UL)
#define MACSEC_EIP165_AIC_REGS_AIC_CTRL_TYPE_CONTROL_8_SHIFT (8UL)
#define MACSEC_EIP165_AIC_REGS_AIC_CTRL_TYPE_CONTROL_9_MASK (0x200UL)
#define MACSEC_EIP165_AIC_REGS_AIC_CTRL_TYPE_CONTROL_9_SHIFT (9UL)
#define MACSEC_EIP165_AIC_REGS_AIC_CTRL_TYPE_CONTROL_10_MASK (0x400UL)
#define MACSEC_EIP165_AIC_REGS_AIC_CTRL_TYPE_CONTROL_10_SHIFT (10UL)
#define MACSEC_EIP165_AIC_REGS_AIC_CTRL_TYPE_CONTROL_11_MASK (0x800UL)
#define MACSEC_EIP165_AIC_REGS_AIC_CTRL_TYPE_CONTROL_11_SHIFT (11UL)
#define MACSEC_EIP165_AIC_REGS_AIC_CTRL_TYPE_CONTROL_12_MASK (0x1000UL)
#define MACSEC_EIP165_AIC_REGS_AIC_CTRL_TYPE_CONTROL_12_SHIFT (12UL)




typedef uint32_t MACSEC_EIP165_AIC_REGS_AIC_ENABLE_CTRL_TYPE;
#define MACSEC_EIP165_AIC_REGS_AIC_ENABLE_CTRL_CONTROL_MASK (0x1fffUL)
#define MACSEC_EIP165_AIC_REGS_AIC_ENABLE_CTRL_CONTROL_SHIFT (0UL)




typedef uint32_t MACSEC_EIP165_AIC_REGS_ARSES_TYPE;
#define MACSEC_EIP165_AIC_REGS_ARSES_RAW_STATUS_ENABLE_SET_MASK (0x1fffUL)
#define MACSEC_EIP165_AIC_REGS_ARSES_RAW_STATUS_ENABLE_SET_SHIFT (0UL)




typedef uint32_t MACSEC_EIP165_AIC_REGS_AESA_TYPE;
#define MACSEC_EIP165_AIC_REGS_AESA_ENABLED_STATUS_ACK_MASK (0x1fffUL)
#define MACSEC_EIP165_AIC_REGS_AESA_ENABLED_STATUS_ACK_SHIFT (0UL)




typedef uint32_t MACSEC_EIP165_AIC_REGS_AIC_ENABLE_CLR_TYPE;
#define MACSEC_EIP165_AIC_REGS_AIC_ENABLE_CLR_MASK (0x1fffUL)
#define MACSEC_EIP165_AIC_REGS_AIC_ENABLE_CLR_SHIFT (0UL)




typedef uint32_t MACSEC_EIP165_AIC_REGS_AIC_OPTIONS_TYPE;
#define MACSEC_EIP165_AIC_REGS_AIC_OPTIONS_NR_OF_INPUTS_MASK (0x3fUL)
#define MACSEC_EIP165_AIC_REGS_AIC_OPTIONS_NR_OF_INPUTS_SHIFT (0UL)
#define MACSEC_EIP165_AIC_REGS_AIC_OPTIONS_EXT_REG_MAP_MASK (0x80UL)
#define MACSEC_EIP165_AIC_REGS_AIC_OPTIONS_EXT_REG_MAP_SHIFT (7UL)




typedef uint32_t MACSEC_EIP165_AIC_REGS_AIC_VERSION_TYPE;
#define MACSEC_EIP165_AIC_REGS_AIC_VERSION_EIP_NUMBER_MASK (0xffUL)
#define MACSEC_EIP165_AIC_REGS_AIC_VERSION_EIP_NUMBER_SHIFT (0UL)
#define MACSEC_EIP165_AIC_REGS_AIC_VERSION_EIP_NUMBER_COMPL_MASK (0xff00UL)
#define MACSEC_EIP165_AIC_REGS_AIC_VERSION_EIP_NUMBER_COMPL_SHIFT (8UL)
#define MACSEC_EIP165_AIC_REGS_AIC_VERSION_PATCH_LEVEL_MASK (0xf0000UL)
#define MACSEC_EIP165_AIC_REGS_AIC_VERSION_PATCH_LEVEL_SHIFT (16UL)
#define MACSEC_EIP165_AIC_REGS_AIC_VERSION_MINOR_VERSION_MASK (0xf00000UL)
#define MACSEC_EIP165_AIC_REGS_AIC_VERSION_MINOR_VERSION_SHIFT (20UL)
#define MACSEC_EIP165_AIC_REGS_AIC_VERSION_MAJOR_VERSION_MASK (0xf000000UL)
#define MACSEC_EIP165_AIC_REGS_AIC_VERSION_MAJOR_VERSION_SHIFT (24UL)




typedef volatile struct sMACSEC_EIP165_AIC_REGS_RDBType {
    MACSEC_EIP165_AIC_REGS_RESERVED_TYPE rsvd0[134656]; /* OFFSET: 0x0 */
    MACSEC_EIP165_AIC_REGS_AIC_POL_CTRL_TYPE pol_ctrl; /* OFFSET: 0x20e00 */
    MACSEC_EIP165_AIC_REGS_AIC_CTRL_TYPE type_ctrl; /* OFFSET: 0x20e04 */
    MACSEC_EIP165_AIC_REGS_AIC_ENABLE_CTRL_TYPE enable_ctrl; /* OFFSET: 0x20e08 */
    MACSEC_EIP165_AIC_REGS_ARSES_TYPE raw_stat_enable_set; /* OFFSET: 0x20e0c */
    MACSEC_EIP165_AIC_REGS_AESA_TYPE enabled_stat_ack; /* OFFSET: 0x20e10 */
    MACSEC_EIP165_AIC_REGS_AIC_ENABLE_CLR_TYPE enable_clr; /* OFFSET: 0x20e14 */
    MACSEC_EIP165_AIC_REGS_AIC_OPTIONS_TYPE options; /* OFFSET: 0x20e18 */
    MACSEC_EIP165_AIC_REGS_AIC_VERSION_TYPE version; /* OFFSET: 0x20e1c */
} MACSEC_EIP165_AIC_REGS_RDBType;

#endif /* MACSEC_EIP165_AIC_REGS_RDB_H */
