/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file macsec_e_sa_cntrs_rdb.h
    @brief RDB File for MACSEC_E_SA_CNTRS

    @version BCM89580_AQ_TSLA_A0_20240304_R10
*/

#ifndef MACSEC_E_SA_CNTRS_RDB_H
#define MACSEC_E_SA_CNTRS_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t MACSEC_E_SA_CNTRS_RESERVED_TYPE;




typedef uint32_t MACSEC_E_SA_CNTRS_SS0OL_TYPE;
#define MACSEC_E_SA_CNTRS_SS0OL_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS0OL_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS0OH_TYPE;
#define MACSEC_E_SA_CNTRS_SS0OH_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS0OH_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS0OL1_TYPE;
#define MACSEC_E_SA_CNTRS_SS0OL1_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS0OL1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS0OH1_TYPE;
#define MACSEC_E_SA_CNTRS_SS0OH1_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS0OH1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_0_OUTPKTSTOOLONG_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_0_OUTPKTSTOOLONG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_0_OUTPKTSTOOLONG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_0_OUTPKTSTOOLONG_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_0_OUTPKTSTOOLONG_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_0_OUTPKTSTOOLONG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_0_OUTPKTSSANOTINUSE_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_0_OUTPKTSSANOTINUSE_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_0_OUTPKTSSANOTINUSE_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_0_OUTPKTSSANOTINUSE_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_0_OUTPKTSSANOTINUSE_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_0_OUTPKTSSANOTINUSE_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS1OL_TYPE;
#define MACSEC_E_SA_CNTRS_SS1OL_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS1OL_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS1OH_TYPE;
#define MACSEC_E_SA_CNTRS_SS1OH_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS1OH_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS1OL1_TYPE;
#define MACSEC_E_SA_CNTRS_SS1OL1_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS1OL1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS1OH1_TYPE;
#define MACSEC_E_SA_CNTRS_SS1OH1_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS1OH1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_1_OUTPKTSTOOLONG_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_1_OUTPKTSTOOLONG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_1_OUTPKTSTOOLONG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_1_OUTPKTSTOOLONG_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_1_OUTPKTSTOOLONG_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_1_OUTPKTSTOOLONG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_1_OUTPKTSSANOTINUSE_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_1_OUTPKTSSANOTINUSE_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_1_OUTPKTSSANOTINUSE_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_1_OUTPKTSSANOTINUSE_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_1_OUTPKTSSANOTINUSE_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_1_OUTPKTSSANOTINUSE_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS2OL_TYPE;
#define MACSEC_E_SA_CNTRS_SS2OL_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS2OL_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS2OH_TYPE;
#define MACSEC_E_SA_CNTRS_SS2OH_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS2OH_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS2OL1_TYPE;
#define MACSEC_E_SA_CNTRS_SS2OL1_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS2OL1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS2OH1_TYPE;
#define MACSEC_E_SA_CNTRS_SS2OH1_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS2OH1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_2_OUTPKTSTOOLONG_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_2_OUTPKTSTOOLONG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_2_OUTPKTSTOOLONG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_2_OUTPKTSTOOLONG_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_2_OUTPKTSTOOLONG_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_2_OUTPKTSTOOLONG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_2_OUTPKTSSANOTINUSE_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_2_OUTPKTSSANOTINUSE_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_2_OUTPKTSSANOTINUSE_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_2_OUTPKTSSANOTINUSE_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_2_OUTPKTSSANOTINUSE_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_2_OUTPKTSSANOTINUSE_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS3OL_TYPE;
#define MACSEC_E_SA_CNTRS_SS3OL_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS3OL_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS3OH_TYPE;
#define MACSEC_E_SA_CNTRS_SS3OH_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS3OH_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS3OL1_TYPE;
#define MACSEC_E_SA_CNTRS_SS3OL1_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS3OL1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS3OH1_TYPE;
#define MACSEC_E_SA_CNTRS_SS3OH1_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS3OH1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_3_OUTPKTSTOOLONG_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_3_OUTPKTSTOOLONG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_3_OUTPKTSTOOLONG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_3_OUTPKTSTOOLONG_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_3_OUTPKTSTOOLONG_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_3_OUTPKTSTOOLONG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_3_OUTPKTSSANOTINUSE_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_3_OUTPKTSSANOTINUSE_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_3_OUTPKTSSANOTINUSE_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_3_OUTPKTSSANOTINUSE_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_3_OUTPKTSSANOTINUSE_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_3_OUTPKTSSANOTINUSE_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS4OL_TYPE;
#define MACSEC_E_SA_CNTRS_SS4OL_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS4OL_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS4OH_TYPE;
#define MACSEC_E_SA_CNTRS_SS4OH_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS4OH_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS4OL1_TYPE;
#define MACSEC_E_SA_CNTRS_SS4OL1_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS4OL1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS4OH1_TYPE;
#define MACSEC_E_SA_CNTRS_SS4OH1_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS4OH1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_4_OUTPKTSTOOLONG_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_4_OUTPKTSTOOLONG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_4_OUTPKTSTOOLONG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_4_OUTPKTSTOOLONG_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_4_OUTPKTSTOOLONG_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_4_OUTPKTSTOOLONG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_4_OUTPKTSSANOTINUSE_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_4_OUTPKTSSANOTINUSE_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_4_OUTPKTSSANOTINUSE_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_4_OUTPKTSSANOTINUSE_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_4_OUTPKTSSANOTINUSE_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_4_OUTPKTSSANOTINUSE_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS5OL_TYPE;
#define MACSEC_E_SA_CNTRS_SS5OL_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS5OL_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS5OH_TYPE;
#define MACSEC_E_SA_CNTRS_SS5OH_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS5OH_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS5OL1_TYPE;
#define MACSEC_E_SA_CNTRS_SS5OL1_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS5OL1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS5OH1_TYPE;
#define MACSEC_E_SA_CNTRS_SS5OH1_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS5OH1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_5_OUTPKTSTOOLONG_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_5_OUTPKTSTOOLONG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_5_OUTPKTSTOOLONG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_5_OUTPKTSTOOLONG_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_5_OUTPKTSTOOLONG_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_5_OUTPKTSTOOLONG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_5_OUTPKTSSANOTINUSE_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_5_OUTPKTSSANOTINUSE_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_5_OUTPKTSSANOTINUSE_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_5_OUTPKTSSANOTINUSE_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_5_OUTPKTSSANOTINUSE_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_5_OUTPKTSSANOTINUSE_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS6OL_TYPE;
#define MACSEC_E_SA_CNTRS_SS6OL_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS6OL_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS6OH_TYPE;
#define MACSEC_E_SA_CNTRS_SS6OH_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS6OH_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS6OL1_TYPE;
#define MACSEC_E_SA_CNTRS_SS6OL1_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS6OL1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS6OH1_TYPE;
#define MACSEC_E_SA_CNTRS_SS6OH1_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS6OH1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_6_OUTPKTSTOOLONG_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_6_OUTPKTSTOOLONG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_6_OUTPKTSTOOLONG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_6_OUTPKTSTOOLONG_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_6_OUTPKTSTOOLONG_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_6_OUTPKTSTOOLONG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_6_OUTPKTSSANOTINUSE_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_6_OUTPKTSSANOTINUSE_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_6_OUTPKTSSANOTINUSE_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_6_OUTPKTSSANOTINUSE_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_6_OUTPKTSSANOTINUSE_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_6_OUTPKTSSANOTINUSE_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS7OL_TYPE;
#define MACSEC_E_SA_CNTRS_SS7OL_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS7OL_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS7OH_TYPE;
#define MACSEC_E_SA_CNTRS_SS7OH_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS7OH_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS7OL1_TYPE;
#define MACSEC_E_SA_CNTRS_SS7OL1_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS7OL1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS7OH1_TYPE;
#define MACSEC_E_SA_CNTRS_SS7OH1_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS7OH1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_7_OUTPKTSTOOLONG_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_7_OUTPKTSTOOLONG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_7_OUTPKTSTOOLONG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_7_OUTPKTSTOOLONG_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_7_OUTPKTSTOOLONG_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_7_OUTPKTSTOOLONG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_7_OUTPKTSSANOTINUSE_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_7_OUTPKTSSANOTINUSE_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_7_OUTPKTSSANOTINUSE_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_7_OUTPKTSSANOTINUSE_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_7_OUTPKTSSANOTINUSE_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_7_OUTPKTSSANOTINUSE_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS8OL_TYPE;
#define MACSEC_E_SA_CNTRS_SS8OL_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS8OL_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS8OH_TYPE;
#define MACSEC_E_SA_CNTRS_SS8OH_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS8OH_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS8OL1_TYPE;
#define MACSEC_E_SA_CNTRS_SS8OL1_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS8OL1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS8OH1_TYPE;
#define MACSEC_E_SA_CNTRS_SS8OH1_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS8OH1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_8_OUTPKTSTOOLONG_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_8_OUTPKTSTOOLONG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_8_OUTPKTSTOOLONG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_8_OUTPKTSTOOLONG_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_8_OUTPKTSTOOLONG_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_8_OUTPKTSTOOLONG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_8_OUTPKTSSANOTINUSE_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_8_OUTPKTSSANOTINUSE_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_8_OUTPKTSSANOTINUSE_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_8_OUTPKTSSANOTINUSE_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_8_OUTPKTSSANOTINUSE_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_8_OUTPKTSSANOTINUSE_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS9OL_TYPE;
#define MACSEC_E_SA_CNTRS_SS9OL_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS9OL_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS9OH_TYPE;
#define MACSEC_E_SA_CNTRS_SS9OH_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS9OH_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS9OL1_TYPE;
#define MACSEC_E_SA_CNTRS_SS9OL1_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS9OL1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS9OH1_TYPE;
#define MACSEC_E_SA_CNTRS_SS9OH1_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS9OH1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_9_OUTPKTSTOOLONG_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_9_OUTPKTSTOOLONG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_9_OUTPKTSTOOLONG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_9_OUTPKTSTOOLONG_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_9_OUTPKTSTOOLONG_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_9_OUTPKTSTOOLONG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_9_OUTPKTSSANOTINUSE_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_9_OUTPKTSSANOTINUSE_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_9_OUTPKTSSANOTINUSE_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_9_OUTPKTSSANOTINUSE_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_9_OUTPKTSSANOTINUSE_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_9_OUTPKTSSANOTINUSE_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS10OL_TYPE;
#define MACSEC_E_SA_CNTRS_SS10OL_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS10OL_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS10OH_TYPE;
#define MACSEC_E_SA_CNTRS_SS10OH_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS10OH_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS10OL1_TYPE;
#define MACSEC_E_SA_CNTRS_SS10OL1_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS10OL1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS10OH1_TYPE;
#define MACSEC_E_SA_CNTRS_SS10OH1_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS10OH1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_10_OUTPKTSTOOLONG_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_10_OUTPKTSTOOLONG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_10_OUTPKTSTOOLONG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_10_OUTPKTSTOOLONG_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_10_OUTPKTSTOOLONG_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_10_OUTPKTSTOOLONG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_10_OUTPKTSSANOTINUSE_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_10_OUTPKTSSANOTINUSE_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_10_OUTPKTSSANOTINUSE_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_10_OUTPKTSSANOTINUSE_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_10_OUTPKTSSANOTINUSE_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_10_OUTPKTSSANOTINUSE_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS11OL_TYPE;
#define MACSEC_E_SA_CNTRS_SS11OL_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS11OL_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS11OH_TYPE;
#define MACSEC_E_SA_CNTRS_SS11OH_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS11OH_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS11OL1_TYPE;
#define MACSEC_E_SA_CNTRS_SS11OL1_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS11OL1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS11OH1_TYPE;
#define MACSEC_E_SA_CNTRS_SS11OH1_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS11OH1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_11_OUTPKTSTOOLONG_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_11_OUTPKTSTOOLONG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_11_OUTPKTSTOOLONG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_11_OUTPKTSTOOLONG_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_11_OUTPKTSTOOLONG_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_11_OUTPKTSTOOLONG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_11_OUTPKTSSANOTINUSE_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_11_OUTPKTSSANOTINUSE_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_11_OUTPKTSSANOTINUSE_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_11_OUTPKTSSANOTINUSE_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_11_OUTPKTSSANOTINUSE_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_11_OUTPKTSSANOTINUSE_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS12OL_TYPE;
#define MACSEC_E_SA_CNTRS_SS12OL_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS12OL_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS12OH_TYPE;
#define MACSEC_E_SA_CNTRS_SS12OH_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS12OH_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS12OL1_TYPE;
#define MACSEC_E_SA_CNTRS_SS12OL1_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS12OL1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS12OH1_TYPE;
#define MACSEC_E_SA_CNTRS_SS12OH1_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS12OH1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_12_OUTPKTSTOOLONG_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_12_OUTPKTSTOOLONG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_12_OUTPKTSTOOLONG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_12_OUTPKTSTOOLONG_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_12_OUTPKTSTOOLONG_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_12_OUTPKTSTOOLONG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_12_OUTPKTSSANOTINUSE_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_12_OUTPKTSSANOTINUSE_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_12_OUTPKTSSANOTINUSE_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_12_OUTPKTSSANOTINUSE_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_12_OUTPKTSSANOTINUSE_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_12_OUTPKTSSANOTINUSE_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS13OL_TYPE;
#define MACSEC_E_SA_CNTRS_SS13OL_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS13OL_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS13OH_TYPE;
#define MACSEC_E_SA_CNTRS_SS13OH_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS13OH_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS13OL1_TYPE;
#define MACSEC_E_SA_CNTRS_SS13OL1_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS13OL1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS13OH1_TYPE;
#define MACSEC_E_SA_CNTRS_SS13OH1_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS13OH1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_13_OUTPKTSTOOLONG_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_13_OUTPKTSTOOLONG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_13_OUTPKTSTOOLONG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_13_OUTPKTSTOOLONG_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_13_OUTPKTSTOOLONG_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_13_OUTPKTSTOOLONG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_13_OUTPKTSSANOTINUSE_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_13_OUTPKTSSANOTINUSE_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_13_OUTPKTSSANOTINUSE_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_13_OUTPKTSSANOTINUSE_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_13_OUTPKTSSANOTINUSE_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_13_OUTPKTSSANOTINUSE_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS14OL_TYPE;
#define MACSEC_E_SA_CNTRS_SS14OL_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS14OL_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS14OH_TYPE;
#define MACSEC_E_SA_CNTRS_SS14OH_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS14OH_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS14OL1_TYPE;
#define MACSEC_E_SA_CNTRS_SS14OL1_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS14OL1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS14OH1_TYPE;
#define MACSEC_E_SA_CNTRS_SS14OH1_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS14OH1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_14_OUTPKTSTOOLONG_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_14_OUTPKTSTOOLONG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_14_OUTPKTSTOOLONG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_14_OUTPKTSTOOLONG_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_14_OUTPKTSTOOLONG_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_14_OUTPKTSTOOLONG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_14_OUTPKTSSANOTINUSE_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_14_OUTPKTSSANOTINUSE_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_14_OUTPKTSSANOTINUSE_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_14_OUTPKTSSANOTINUSE_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_14_OUTPKTSSANOTINUSE_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_14_OUTPKTSSANOTINUSE_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS15OL_TYPE;
#define MACSEC_E_SA_CNTRS_SS15OL_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS15OL_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS15OH_TYPE;
#define MACSEC_E_SA_CNTRS_SS15OH_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS15OH_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS15OL1_TYPE;
#define MACSEC_E_SA_CNTRS_SS15OL1_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS15OL1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS15OH1_TYPE;
#define MACSEC_E_SA_CNTRS_SS15OH1_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS15OH1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_15_OUTPKTSTOOLONG_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_15_OUTPKTSTOOLONG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_15_OUTPKTSTOOLONG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_15_OUTPKTSTOOLONG_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_15_OUTPKTSTOOLONG_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_15_OUTPKTSTOOLONG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_15_OUTPKTSSANOTINUSE_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_15_OUTPKTSSANOTINUSE_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_15_OUTPKTSSANOTINUSE_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_15_OUTPKTSSANOTINUSE_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_15_OUTPKTSSANOTINUSE_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_15_OUTPKTSSANOTINUSE_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS16OL_TYPE;
#define MACSEC_E_SA_CNTRS_SS16OL_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS16OL_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS16OH_TYPE;
#define MACSEC_E_SA_CNTRS_SS16OH_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS16OH_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS16OL1_TYPE;
#define MACSEC_E_SA_CNTRS_SS16OL1_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS16OL1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS16OH1_TYPE;
#define MACSEC_E_SA_CNTRS_SS16OH1_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS16OH1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_16_OUTPKTSTOOLONG_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_16_OUTPKTSTOOLONG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_16_OUTPKTSTOOLONG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_16_OUTPKTSTOOLONG_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_16_OUTPKTSTOOLONG_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_16_OUTPKTSTOOLONG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_16_OUTPKTSSANOTINUSE_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_16_OUTPKTSSANOTINUSE_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_16_OUTPKTSSANOTINUSE_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_16_OUTPKTSSANOTINUSE_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_16_OUTPKTSSANOTINUSE_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_16_OUTPKTSSANOTINUSE_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS17OL_TYPE;
#define MACSEC_E_SA_CNTRS_SS17OL_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS17OL_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS17OH_TYPE;
#define MACSEC_E_SA_CNTRS_SS17OH_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS17OH_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS17OL1_TYPE;
#define MACSEC_E_SA_CNTRS_SS17OL1_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS17OL1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS17OH1_TYPE;
#define MACSEC_E_SA_CNTRS_SS17OH1_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS17OH1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_17_OUTPKTSTOOLONG_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_17_OUTPKTSTOOLONG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_17_OUTPKTSTOOLONG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_17_OUTPKTSTOOLONG_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_17_OUTPKTSTOOLONG_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_17_OUTPKTSTOOLONG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_17_OUTPKTSSANOTINUSE_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_17_OUTPKTSSANOTINUSE_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_17_OUTPKTSSANOTINUSE_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_17_OUTPKTSSANOTINUSE_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_17_OUTPKTSSANOTINUSE_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_17_OUTPKTSSANOTINUSE_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS18OL_TYPE;
#define MACSEC_E_SA_CNTRS_SS18OL_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS18OL_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS18OH_TYPE;
#define MACSEC_E_SA_CNTRS_SS18OH_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS18OH_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS18OL1_TYPE;
#define MACSEC_E_SA_CNTRS_SS18OL1_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS18OL1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS18OH1_TYPE;
#define MACSEC_E_SA_CNTRS_SS18OH1_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS18OH1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_18_OUTPKTSTOOLONG_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_18_OUTPKTSTOOLONG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_18_OUTPKTSTOOLONG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_18_OUTPKTSTOOLONG_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_18_OUTPKTSTOOLONG_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_18_OUTPKTSTOOLONG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_18_OUTPKTSSANOTINUSE_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_18_OUTPKTSSANOTINUSE_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_18_OUTPKTSSANOTINUSE_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_18_OUTPKTSSANOTINUSE_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_18_OUTPKTSSANOTINUSE_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_18_OUTPKTSSANOTINUSE_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS19OL_TYPE;
#define MACSEC_E_SA_CNTRS_SS19OL_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS19OL_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS19OH_TYPE;
#define MACSEC_E_SA_CNTRS_SS19OH_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS19OH_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS19OL1_TYPE;
#define MACSEC_E_SA_CNTRS_SS19OL1_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS19OL1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS19OH1_TYPE;
#define MACSEC_E_SA_CNTRS_SS19OH1_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS19OH1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_19_OUTPKTSTOOLONG_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_19_OUTPKTSTOOLONG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_19_OUTPKTSTOOLONG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_19_OUTPKTSTOOLONG_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_19_OUTPKTSTOOLONG_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_19_OUTPKTSTOOLONG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_19_OUTPKTSSANOTINUSE_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_19_OUTPKTSSANOTINUSE_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_19_OUTPKTSSANOTINUSE_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_19_OUTPKTSSANOTINUSE_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_19_OUTPKTSSANOTINUSE_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_19_OUTPKTSSANOTINUSE_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS20OL_TYPE;
#define MACSEC_E_SA_CNTRS_SS20OL_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS20OL_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS20OH_TYPE;
#define MACSEC_E_SA_CNTRS_SS20OH_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS20OH_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS20OL1_TYPE;
#define MACSEC_E_SA_CNTRS_SS20OL1_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS20OL1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS20OH1_TYPE;
#define MACSEC_E_SA_CNTRS_SS20OH1_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS20OH1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_20_OUTPKTSTOOLONG_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_20_OUTPKTSTOOLONG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_20_OUTPKTSTOOLONG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_20_OUTPKTSTOOLONG_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_20_OUTPKTSTOOLONG_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_20_OUTPKTSTOOLONG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_20_OUTPKTSSANOTINUSE_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_20_OUTPKTSSANOTINUSE_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_20_OUTPKTSSANOTINUSE_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_20_OUTPKTSSANOTINUSE_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_20_OUTPKTSSANOTINUSE_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_20_OUTPKTSSANOTINUSE_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS21OL_TYPE;
#define MACSEC_E_SA_CNTRS_SS21OL_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS21OL_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS21OH_TYPE;
#define MACSEC_E_SA_CNTRS_SS21OH_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS21OH_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS21OL1_TYPE;
#define MACSEC_E_SA_CNTRS_SS21OL1_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS21OL1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS21OH1_TYPE;
#define MACSEC_E_SA_CNTRS_SS21OH1_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS21OH1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_21_OUTPKTSTOOLONG_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_21_OUTPKTSTOOLONG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_21_OUTPKTSTOOLONG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_21_OUTPKTSTOOLONG_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_21_OUTPKTSTOOLONG_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_21_OUTPKTSTOOLONG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_21_OUTPKTSSANOTINUSE_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_21_OUTPKTSSANOTINUSE_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_21_OUTPKTSSANOTINUSE_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_21_OUTPKTSSANOTINUSE_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_21_OUTPKTSSANOTINUSE_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_21_OUTPKTSSANOTINUSE_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS22OL_TYPE;
#define MACSEC_E_SA_CNTRS_SS22OL_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS22OL_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS22OH_TYPE;
#define MACSEC_E_SA_CNTRS_SS22OH_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS22OH_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS22OL1_TYPE;
#define MACSEC_E_SA_CNTRS_SS22OL1_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS22OL1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS22OH1_TYPE;
#define MACSEC_E_SA_CNTRS_SS22OH1_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS22OH1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_22_OUTPKTSTOOLONG_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_22_OUTPKTSTOOLONG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_22_OUTPKTSTOOLONG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_22_OUTPKTSTOOLONG_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_22_OUTPKTSTOOLONG_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_22_OUTPKTSTOOLONG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_22_OUTPKTSSANOTINUSE_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_22_OUTPKTSSANOTINUSE_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_22_OUTPKTSSANOTINUSE_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_22_OUTPKTSSANOTINUSE_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_22_OUTPKTSSANOTINUSE_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_22_OUTPKTSSANOTINUSE_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS23OL_TYPE;
#define MACSEC_E_SA_CNTRS_SS23OL_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS23OL_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS23OH_TYPE;
#define MACSEC_E_SA_CNTRS_SS23OH_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS23OH_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS23OL1_TYPE;
#define MACSEC_E_SA_CNTRS_SS23OL1_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS23OL1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS23OH1_TYPE;
#define MACSEC_E_SA_CNTRS_SS23OH1_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS23OH1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_23_OUTPKTSTOOLONG_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_23_OUTPKTSTOOLONG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_23_OUTPKTSTOOLONG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_23_OUTPKTSTOOLONG_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_23_OUTPKTSTOOLONG_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_23_OUTPKTSTOOLONG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_23_OUTPKTSSANOTINUSE_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_23_OUTPKTSSANOTINUSE_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_23_OUTPKTSSANOTINUSE_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_23_OUTPKTSSANOTINUSE_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_23_OUTPKTSSANOTINUSE_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_23_OUTPKTSSANOTINUSE_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS24OL_TYPE;
#define MACSEC_E_SA_CNTRS_SS24OL_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS24OL_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS24OH_TYPE;
#define MACSEC_E_SA_CNTRS_SS24OH_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS24OH_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS24OL1_TYPE;
#define MACSEC_E_SA_CNTRS_SS24OL1_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS24OL1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS24OH1_TYPE;
#define MACSEC_E_SA_CNTRS_SS24OH1_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS24OH1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_24_OUTPKTSTOOLONG_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_24_OUTPKTSTOOLONG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_24_OUTPKTSTOOLONG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_24_OUTPKTSTOOLONG_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_24_OUTPKTSTOOLONG_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_24_OUTPKTSTOOLONG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_24_OUTPKTSSANOTINUSE_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_24_OUTPKTSSANOTINUSE_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_24_OUTPKTSSANOTINUSE_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_24_OUTPKTSSANOTINUSE_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_24_OUTPKTSSANOTINUSE_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_24_OUTPKTSSANOTINUSE_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS25OL_TYPE;
#define MACSEC_E_SA_CNTRS_SS25OL_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS25OL_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS25OH_TYPE;
#define MACSEC_E_SA_CNTRS_SS25OH_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS25OH_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS25OL1_TYPE;
#define MACSEC_E_SA_CNTRS_SS25OL1_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS25OL1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS25OH1_TYPE;
#define MACSEC_E_SA_CNTRS_SS25OH1_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS25OH1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_25_OUTPKTSTOOLONG_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_25_OUTPKTSTOOLONG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_25_OUTPKTSTOOLONG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_25_OUTPKTSTOOLONG_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_25_OUTPKTSTOOLONG_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_25_OUTPKTSTOOLONG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_25_OUTPKTSSANOTINUSE_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_25_OUTPKTSSANOTINUSE_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_25_OUTPKTSSANOTINUSE_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_25_OUTPKTSSANOTINUSE_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_25_OUTPKTSSANOTINUSE_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_25_OUTPKTSSANOTINUSE_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS26OL_TYPE;
#define MACSEC_E_SA_CNTRS_SS26OL_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS26OL_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS26OH_TYPE;
#define MACSEC_E_SA_CNTRS_SS26OH_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS26OH_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS26OL1_TYPE;
#define MACSEC_E_SA_CNTRS_SS26OL1_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS26OL1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS26OH1_TYPE;
#define MACSEC_E_SA_CNTRS_SS26OH1_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS26OH1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_26_OUTPKTSTOOLONG_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_26_OUTPKTSTOOLONG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_26_OUTPKTSTOOLONG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_26_OUTPKTSTOOLONG_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_26_OUTPKTSTOOLONG_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_26_OUTPKTSTOOLONG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_26_OUTPKTSSANOTINUSE_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_26_OUTPKTSSANOTINUSE_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_26_OUTPKTSSANOTINUSE_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_26_OUTPKTSSANOTINUSE_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_26_OUTPKTSSANOTINUSE_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_26_OUTPKTSSANOTINUSE_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS27OL_TYPE;
#define MACSEC_E_SA_CNTRS_SS27OL_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS27OL_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS27OH_TYPE;
#define MACSEC_E_SA_CNTRS_SS27OH_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS27OH_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS27OL1_TYPE;
#define MACSEC_E_SA_CNTRS_SS27OL1_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS27OL1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS27OH1_TYPE;
#define MACSEC_E_SA_CNTRS_SS27OH1_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS27OH1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_27_OUTPKTSTOOLONG_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_27_OUTPKTSTOOLONG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_27_OUTPKTSTOOLONG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_27_OUTPKTSTOOLONG_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_27_OUTPKTSTOOLONG_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_27_OUTPKTSTOOLONG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_27_OUTPKTSSANOTINUSE_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_27_OUTPKTSSANOTINUSE_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_27_OUTPKTSSANOTINUSE_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_27_OUTPKTSSANOTINUSE_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_27_OUTPKTSSANOTINUSE_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_27_OUTPKTSSANOTINUSE_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS28OL_TYPE;
#define MACSEC_E_SA_CNTRS_SS28OL_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS28OL_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS28OH_TYPE;
#define MACSEC_E_SA_CNTRS_SS28OH_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS28OH_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS28OL1_TYPE;
#define MACSEC_E_SA_CNTRS_SS28OL1_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS28OL1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS28OH1_TYPE;
#define MACSEC_E_SA_CNTRS_SS28OH1_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS28OH1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_28_OUTPKTSTOOLONG_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_28_OUTPKTSTOOLONG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_28_OUTPKTSTOOLONG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_28_OUTPKTSTOOLONG_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_28_OUTPKTSTOOLONG_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_28_OUTPKTSTOOLONG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_28_OUTPKTSSANOTINUSE_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_28_OUTPKTSSANOTINUSE_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_28_OUTPKTSSANOTINUSE_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_28_OUTPKTSSANOTINUSE_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_28_OUTPKTSSANOTINUSE_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_28_OUTPKTSSANOTINUSE_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS29OL_TYPE;
#define MACSEC_E_SA_CNTRS_SS29OL_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS29OL_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS29OH_TYPE;
#define MACSEC_E_SA_CNTRS_SS29OH_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS29OH_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS29OL1_TYPE;
#define MACSEC_E_SA_CNTRS_SS29OL1_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS29OL1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS29OH1_TYPE;
#define MACSEC_E_SA_CNTRS_SS29OH1_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS29OH1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_29_OUTPKTSTOOLONG_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_29_OUTPKTSTOOLONG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_29_OUTPKTSTOOLONG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_29_OUTPKTSTOOLONG_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_29_OUTPKTSTOOLONG_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_29_OUTPKTSTOOLONG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_29_OUTPKTSSANOTINUSE_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_29_OUTPKTSSANOTINUSE_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_29_OUTPKTSSANOTINUSE_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_29_OUTPKTSSANOTINUSE_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_29_OUTPKTSSANOTINUSE_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_29_OUTPKTSSANOTINUSE_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS30OL_TYPE;
#define MACSEC_E_SA_CNTRS_SS30OL_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS30OL_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS30OH_TYPE;
#define MACSEC_E_SA_CNTRS_SS30OH_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS30OH_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS30OL1_TYPE;
#define MACSEC_E_SA_CNTRS_SS30OL1_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS30OL1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS30OH1_TYPE;
#define MACSEC_E_SA_CNTRS_SS30OH1_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS30OH1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_30_OUTPKTSTOOLONG_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_30_OUTPKTSTOOLONG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_30_OUTPKTSTOOLONG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_30_OUTPKTSTOOLONG_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_30_OUTPKTSTOOLONG_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_30_OUTPKTSTOOLONG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_30_OUTPKTSSANOTINUSE_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_30_OUTPKTSSANOTINUSE_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_30_OUTPKTSSANOTINUSE_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_30_OUTPKTSSANOTINUSE_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_30_OUTPKTSSANOTINUSE_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_30_OUTPKTSSANOTINUSE_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS31OL_TYPE;
#define MACSEC_E_SA_CNTRS_SS31OL_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS31OL_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS31OH_TYPE;
#define MACSEC_E_SA_CNTRS_SS31OH_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS31OH_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS31OL1_TYPE;
#define MACSEC_E_SA_CNTRS_SS31OL1_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SS31OL1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SS31OH1_TYPE;
#define MACSEC_E_SA_CNTRS_SS31OH1_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SS31OH1_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_31_OUTPKTSTOOLONG_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_31_OUTPKTSTOOLONG_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_31_OUTPKTSTOOLONG_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_31_OUTPKTSTOOLONG_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_31_OUTPKTSTOOLONG_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_31_OUTPKTSTOOLONG_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_31_OUTPKTSSANOTINUSE_LO_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_31_OUTPKTSSANOTINUSE_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_31_OUTPKTSSANOTINUSE_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_E_SA_CNTRS_SA_SA_31_OUTPKTSSANOTINUSE_HI_TYPE;
#define MACSEC_E_SA_CNTRS_SA_SA_31_OUTPKTSSANOTINUSE_HI_COUNTER_MASK (0xffUL)
#define MACSEC_E_SA_CNTRS_SA_SA_31_OUTPKTSSANOTINUSE_HI_COUNTER_SHIFT (0UL)


typedef volatile struct sMACSEC_E_SA_CNTRS_CNTRSRDBType {
    MACSEC_E_SA_CNTRS_SS0OL_TYPE m0_outoctetsencryptedprotected_lo; /* OFFSET: 0x18000 */
    MACSEC_E_SA_CNTRS_SS0OH_TYPE m0_outoctetsencryptedprotected_hi; /* OFFSET: 0x18004 */
    MACSEC_E_SA_CNTRS_SS0OL1_TYPE m0_outpktsencryptedprotected_lo; /* OFFSET: 0x18008 */
    MACSEC_E_SA_CNTRS_SS0OH1_TYPE m0_outpktsencryptedprotected_hi; /* OFFSET: 0x1800c */
    MACSEC_E_SA_CNTRS_SA_SA_0_OUTPKTSTOOLONG_LO_TYPE m0_outpktstoolong_lo; /* OFFSET: 0x18010 */
    MACSEC_E_SA_CNTRS_SA_SA_0_OUTPKTSTOOLONG_HI_TYPE m0_outpktstoolong_hi; /* OFFSET: 0x18014 */
    MACSEC_E_SA_CNTRS_SA_SA_0_OUTPKTSSANOTINUSE_LO_TYPE m0_outpktssanotinuse_lo; /* OFFSET: 0x18018 */
    MACSEC_E_SA_CNTRS_SA_SA_0_OUTPKTSSANOTINUSE_HI_TYPE m0_outpktssanotinuse_hi; /* OFFSET: 0x1801c */
    MACSEC_E_SA_CNTRS_RESERVED_TYPE rsvd1[96]; /* OFFSET: 0x18020 */
} MACSEC_E_SA_CNTRS_CNTRSRDBType;


#define MACSEC_E_SA_CNTRS_REGS_SIZE  (32UL)


typedef volatile struct sMACSEC_E_SA_CNTRS_RDBType {
    MACSEC_E_SA_CNTRS_RESERVED_TYPE rsvd0[98304]; /* OFFSET: 0x0 */
    MACSEC_E_SA_CNTRS_CNTRSRDBType regs[MACSEC_E_SA_CNTRS_REGS_SIZE]; /* OFFSET: 0x18000 */
} MACSEC_E_SA_CNTRS_RDBType;

#endif /* MACSEC_E_SA_CNTRS_RDB_H */
