/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file sdc_csr_rdb.h
    @brief RDB File for SDC_CSR

    @version BCM89580_A0_20230125_RDB
*/

#ifndef SDC_CSR_RDB_H
#define SDC_CSR_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t SDC_CSR_CS_TYPE;
#define SDC_CSR_CS_STALLING_MASK (0x1000000UL)
#define SDC_CSR_CS_STALLING_SHIFT (24UL)
#define SDC_CSR_CS_EXCEPTION_MASK (0x800000UL)
#define SDC_CSR_CS_EXCEPTION_SHIFT (23UL)
#define SDC_CSR_CS_ASHDN_T_MASK (0x780000UL)
#define SDC_CSR_CS_ASHDN_T_SHIFT (19UL)
#define SDC_CSR_CS_SREF_RESTART_MASK (0x40000UL)
#define SDC_CSR_CS_SREF_RESTART_SHIFT (18UL)
#define SDC_CSR_CS_ASHDNE_MASK (0x20000UL)
#define SDC_CSR_CS_ASHDNE_SHIFT (17UL)
#define SDC_CSR_CS_RDH_IDLE_MASK (0x10000UL)
#define SDC_CSR_CS_RDH_IDLE_SHIFT (16UL)
#define SDC_CSR_CS_SDUP_MASK (0x8000UL)
#define SDC_CSR_CS_SDUP_SHIFT (15UL)
#define SDC_CSR_CS_CLKOFF_MASK (0x4000UL)
#define SDC_CSR_CS_CLKOFF_SHIFT (14UL)
#define SDC_CSR_CS_SREF_MASK (0x800UL)
#define SDC_CSR_CS_SREF_SHIFT (11UL)
#define SDC_CSR_CS_SHUTDOWN_MASK (0x400UL)
#define SDC_CSR_CS_SHUTDOWN_SHIFT (10UL)
#define SDC_CSR_CS_IDLE_MASK (0x200UL)
#define SDC_CSR_CS_IDLE_SHIFT (9UL)
#define SDC_CSR_CS_SREF2RUN_MASK (0x100UL)
#define SDC_CSR_CS_SREF2RUN_SHIFT (8UL)
#define SDC_CSR_CS_STOP_MASK (0x80UL)
#define SDC_CSR_CS_STOP_SHIFT (7UL)
#define SDC_CSR_CS_STATEN_MASK (0x40UL)
#define SDC_CSR_CS_STATEN_SHIFT (6UL)
#define SDC_CSR_CS_NOP_ONLY_MASK (0x20UL)
#define SDC_CSR_CS_NOP_ONLY_SHIFT (5UL)
#define SDC_CSR_CS_RETUNE_MASK (0x10UL)
#define SDC_CSR_CS_RETUNE_SHIFT (4UL)
#define SDC_CSR_CS_STBY_MASK (0x8UL)
#define SDC_CSR_CS_STBY_SHIFT (3UL)
#define SDC_CSR_CS_EN_MASK (0x2UL)
#define SDC_CSR_CS_EN_SHIFT (1UL)
#define SDC_CSR_CS_RESTRT_MASK (0x1UL)
#define SDC_CSR_CS_RESTRT_SHIFT (0UL)




typedef uint32_t SDC_CSR_SA_TYPE;
#define SDC_CSR_SA_RFSH_T_MASK (0xffff0000UL)
#define SDC_CSR_SA_RFSH_T_SHIFT (16UL)
#define SDC_CSR_SA_RT_RATE_MASK (0x8000UL)
#define SDC_CSR_SA_RT_RATE_SHIFT (15UL)
#define SDC_CSR_SA_RT_RATIO_MASK (0x4000UL)
#define SDC_CSR_SA_RT_RATIO_SHIFT (14UL)
#define SDC_CSR_SA_RT_REF_ADJ_MASK (0x2000UL)
#define SDC_CSR_SA_RT_REF_ADJ_SHIFT (13UL)
#define SDC_CSR_SA_T_RFCAB_MASK (0x1ff8UL)
#define SDC_CSR_SA_T_RFCAB_SHIFT (3UL)
#define SDC_CSR_SA_REF_WAKE_MASK (0x7UL)
#define SDC_CSR_SA_REF_WAKE_SHIFT (0UL)




typedef uint32_t SDC_CSR_SB_TYPE;
#define SDC_CSR_SB_LPDDR5_MASK (0x10000000UL)
#define SDC_CSR_SB_LPDDR5_SHIFT (28UL)
#define SDC_CSR_SB_REORDER_MASK (0x2000000UL)
#define SDC_CSR_SB_REORDER_SHIFT (25UL)
#define SDC_CSR_SB_WR_REORDER_MASK (0x1000000UL)
#define SDC_CSR_SB_WR_REORDER_SHIFT (24UL)
#define SDC_CSR_SB_THREE_QTR_MASK (0x200000UL)
#define SDC_CSR_SB_THREE_QTR_SHIFT (21UL)
#define SDC_CSR_SB_INHIBIT_LA_MASK (0x100000UL)
#define SDC_CSR_SB_INHIBIT_LA_SHIFT (20UL)
#define SDC_CSR_SB_AD_MIRROR_MASK (0x40000UL)
#define SDC_CSR_SB_AD_MIRROR_SHIFT (18UL)
#define SDC_CSR_SB_FOUR_RANK_MASK (0x20000UL)
#define SDC_CSR_SB_FOUR_RANK_SHIFT (17UL)
#define SDC_CSR_SB_TWO_RANK_MASK (0x10000UL)
#define SDC_CSR_SB_TWO_RANK_SHIFT (16UL)
#define SDC_CSR_SB_BANKLOW_MASK (0x7000UL)
#define SDC_CSR_SB_BANKLOW_SHIFT (12UL)
#define SDC_CSR_SB_BANK_GROUP_MASK (0x400UL)
#define SDC_CSR_SB_BANK_GROUP_SHIFT (10UL)
#define SDC_CSR_SB_BANKS_16_MASK (0x100UL)
#define SDC_CSR_SB_BANKS_16_SHIFT (8UL)
#define SDC_CSR_SB_ROWBITS_MASK (0x70UL)
#define SDC_CSR_SB_ROWBITS_SHIFT (4UL)
#define SDC_CSR_SB_COLBITS_MASK (0x1UL)
#define SDC_CSR_SB_COLBITS_SHIFT (0UL)




typedef uint32_t SDC_CSR_SC_TYPE;
#define SDC_CSR_SC_PDX_CS_MASK (0xfff00000UL)
#define SDC_CSR_SC_PDX_CS_SHIFT (20UL)
#define SDC_CSR_SC_T_PDX_MASK (0xf0000UL)
#define SDC_CSR_SC_T_PDX_SHIFT (16UL)
#define SDC_CSR_SC_T_CKCKEH_MASK (0xf000UL)
#define SDC_CSR_SC_T_CKCKEH_SHIFT (12UL)
#define SDC_CSR_SC_T_XP_MASK (0xf00UL)
#define SDC_CSR_SC_T_XP_SHIFT (8UL)
#define SDC_CSR_SC_T_CPDED_MASK (0xf0UL)
#define SDC_CSR_SC_T_CPDED_SHIFT (4UL)
#define SDC_CSR_SC_T_CKE_MASK (0xfUL)
#define SDC_CSR_SC_T_CKE_SHIFT (0UL)




typedef uint32_t SDC_CSR_SD_TYPE;
#define SDC_CSR_SD_STBY_T_MASK (0xfff00000UL)
#define SDC_CSR_SD_STBY_T_SHIFT (20UL)
#define SDC_CSR_SD_T_CKOFF_MASK (0xc0000UL)
#define SDC_CSR_SD_T_CKOFF_SHIFT (18UL)
#define SDC_CSR_SD_WCK_STOP_MASK (0x20000UL)
#define SDC_CSR_SD_WCK_STOP_SHIFT (17UL)
#define SDC_CSR_SD_CLKSTOP_MASK (0x10000UL)
#define SDC_CSR_SD_CLKSTOP_SHIFT (16UL)
#define SDC_CSR_SD_POWSAVE_MASK (0x1000UL)
#define SDC_CSR_SD_POWSAVE_SHIFT (12UL)
#define SDC_CSR_SD_POWSAV_T_MASK (0x3ffUL)
#define SDC_CSR_SD_POWSAV_T_SHIFT (0UL)




typedef uint32_t SDC_CSR_SE_TYPE;
#define SDC_CSR_SE_T_FAW_MASK (0x7f000000UL)
#define SDC_CSR_SE_T_FAW_SHIFT (24UL)
#define SDC_CSR_SE_T_RRD_MASK (0x1f0000UL)
#define SDC_CSR_SE_T_RRD_SHIFT (16UL)
#define SDC_CSR_SE_T_RC_MASK (0x1ffUL)
#define SDC_CSR_SE_T_RC_SHIFT (0UL)




typedef uint32_t SDC_CSR_SF_TYPE;
#define SDC_CSR_SF_T_RPPB_MASK (0x7f000000UL)
#define SDC_CSR_SF_T_RPPB_SHIFT (24UL)
#define SDC_CSR_SF_T_RPAB_MASK (0x3f0000UL)
#define SDC_CSR_SF_T_RPAB_SHIFT (16UL)
#define SDC_CSR_SF_T_PPD_MASK (0x7000UL)
#define SDC_CSR_SF_T_PPD_SHIFT (12UL)
#define SDC_CSR_SF_T_RTP_MASK (0x3fUL)
#define SDC_CSR_SF_T_RTP_SHIFT (0UL)




typedef uint32_t SDC_CSR_SG_TYPE;
#define SDC_CSR_SG_EARLY_W_MASK (0x80000000UL)
#define SDC_CSR_SG_EARLY_W_SHIFT (31UL)
#define SDC_CSR_SG_T_CCDMW_MASK (0x3f000000UL)
#define SDC_CSR_SG_T_CCDMW_SHIFT (24UL)
#define SDC_CSR_SG_T_WR_MASK (0xff0000UL)
#define SDC_CSR_SG_T_WR_SHIFT (16UL)
#define SDC_CSR_SG_T_WOP_MASK (0xf000UL)
#define SDC_CSR_SG_T_WOP_SHIFT (12UL)
#define SDC_CSR_SG_T_WOR_MASK (0xf00UL)
#define SDC_CSR_SG_T_WOR_SHIFT (8UL)
#define SDC_CSR_SG_WL_MASK (0x7fUL)
#define SDC_CSR_SG_WL_SHIFT (0UL)




typedef uint32_t SDC_CSR_SH_TYPE;
#define SDC_CSR_SH_RL_MASK (0x7f000000UL)
#define SDC_CSR_SH_RL_SHIFT (24UL)
#define SDC_CSR_SH_T_ROP_MASK (0xf00000UL)
#define SDC_CSR_SH_T_ROP_SHIFT (20UL)
#define SDC_CSR_SH_T_ROR_MASK (0xf0000UL)
#define SDC_CSR_SH_T_ROR_SHIFT (16UL)
#define SDC_CSR_SH_T_RTW_MASK (0x7f00UL)
#define SDC_CSR_SH_T_RTW_SHIFT (8UL)
#define SDC_CSR_SH_T_WTR_MASK (0x3fUL)
#define SDC_CSR_SH_T_WTR_SHIFT (0UL)




typedef uint32_t SDC_CSR_SJ_TYPE;
#define SDC_CSR_SJ_T_SRCK_MASK (0x3f000000UL)
#define SDC_CSR_SJ_T_SRCK_SHIFT (24UL)
#define SDC_CSR_SJ_T_SR_MASK (0x1f0000UL)
#define SDC_CSR_SJ_T_SR_SHIFT (16UL)
#define SDC_CSR_SJ_T_ESCKE_MASK (0x3000UL)
#define SDC_CSR_SJ_T_ESCKE_SHIFT (12UL)
#define SDC_CSR_SJ_SR_CLKSTOP_MASK (0x200UL)
#define SDC_CSR_SJ_SR_CLKSTOP_SHIFT (9UL)
#define SDC_CSR_SJ_T_XSR_MASK (0x1ffUL)
#define SDC_CSR_SJ_T_XSR_SHIFT (0UL)




typedef uint32_t SDC_CSR_SK_TYPE;
#define SDC_CSR_SK_AP_AGR_MASK (0x20000000UL)
#define SDC_CSR_SK_AP_AGR_SHIFT (29UL)
#define SDC_CSR_SK_AP_EN_MASK (0x10000000UL)
#define SDC_CSR_SK_AP_EN_SHIFT (28UL)
#define SDC_CSR_SK_AP_THRESH_MASK (0xf000000UL)
#define SDC_CSR_SK_AP_THRESH_SHIFT (24UL)
#define SDC_CSR_SK_PGEHLD_IDL_MASK (0x100000UL)
#define SDC_CSR_SK_PGEHLD_IDL_SHIFT (20UL)
#define SDC_CSR_SK_PGEHLDE_MASK (0x10000UL)
#define SDC_CSR_SK_PGEHLDE_SHIFT (16UL)
#define SDC_CSR_SK_PGEHLD_T_MASK (0x3ffUL)
#define SDC_CSR_SK_PGEHLD_T_SHIFT (0UL)




typedef uint32_t SDC_CSR_SL_TYPE;
#define SDC_CSR_SL_T_PBR2PBR_MASK (0xff000000UL)
#define SDC_CSR_SL_T_PBR2PBR_SHIFT (24UL)
#define SDC_CSR_SL_T_PBR2ACT_MASK (0xf00000UL)
#define SDC_CSR_SL_T_PBR2ACT_SHIFT (20UL)
#define SDC_CSR_SL_T_RFMAB_MASK (0xffc00UL)
#define SDC_CSR_SL_T_RFMAB_SHIFT (10UL)
#define SDC_CSR_SL_T_RFMPB_MASK (0x3ffUL)
#define SDC_CSR_SL_T_RFMPB_SHIFT (0UL)




typedef uint32_t SDC_CSR_SM_TYPE;
#define SDC_CSR_SM_T_WTR_L_MASK (0x7f00UL)
#define SDC_CSR_SM_T_WTR_L_SHIFT (8UL)
#define SDC_CSR_SM_WTR_OR_EN_MASK (0x80UL)
#define SDC_CSR_SM_WTR_OR_EN_SHIFT (7UL)
#define SDC_CSR_SM_T_WTR_OR_MASK (0xfUL)
#define SDC_CSR_SM_T_WTR_OR_SHIFT (0UL)




typedef uint32_t SDC_CSR_SN_TYPE;
#define SDC_CSR_SN_T_WCKSUS_MASK (0x30000000UL)
#define SDC_CSR_SN_T_WCKSUS_SHIFT (28UL)
#define SDC_CSR_SN_T_FS_WSUSP_MASK (0xf000000UL)
#define SDC_CSR_SN_T_FS_WSUSP_SHIFT (24UL)
#define SDC_CSR_SN_CK_RATIO4_MASK (0x800000UL)
#define SDC_CSR_SN_CK_RATIO4_SHIFT (23UL)
#define SDC_CSR_SN_ENHANCED_WCK_MASK (0x400000UL)
#define SDC_CSR_SN_ENHANCED_WCK_SHIFT (22UL)
#define SDC_CSR_SN_WCK_SUSPEND_MASK (0x200000UL)
#define SDC_CSR_SN_WCK_SUSPEND_SHIFT (21UL)
#define SDC_CSR_SN_WCK_SYNC_ALL_MASK (0x100000UL)
#define SDC_CSR_SN_WCK_SYNC_ALL_SHIFT (20UL)
#define SDC_CSR_SN_T_WCKOFF_ON_MASK (0xc0000UL)
#define SDC_CSR_SN_T_WCKOFF_ON_SHIFT (18UL)
#define SDC_CSR_SN_T_WSFS_RW_MASK (0x1e000UL)
#define SDC_CSR_SN_T_WSFS_RW_SHIFT (13UL)
#define SDC_CSR_SN_T_R_WSOFF_MASK (0x1f00UL)
#define SDC_CSR_SN_T_R_WSOFF_SHIFT (8UL)
#define SDC_CSR_SN_T_W_WSOFF_MASK (0x1fUL)
#define SDC_CSR_SN_T_W_WSOFF_SHIFT (0UL)




typedef uint32_t SDC_CSR_SP_TYPE;
#define SDC_CSR_SP_DSM_EN_MASK (0x10000000UL)
#define SDC_CSR_SP_DSM_EN_SHIFT (28UL)
#define SDC_CSR_SP_T_PDN_MASK (0xf0000UL)
#define SDC_CSR_SP_T_PDN_SHIFT (16UL)
#define SDC_CSR_SP_T_PDX_SRX_MASK (0xffffUL)
#define SDC_CSR_SP_T_PDX_SRX_SHIFT (0UL)




typedef uint32_t SDC_CSR_SQ_TYPE;
#define SDC_CSR_SQ_T_XDSM_XP_MASK (0x3ffffUL)
#define SDC_CSR_SQ_T_XDSM_XP_SHIFT (0UL)




typedef uint32_t SDC_CSR_SR_TYPE;
#define SDC_CSR_SR_T_RFCPB_MASK (0x3ff00000UL)
#define SDC_CSR_SR_T_RFCPB_SHIFT (20UL)
#define SDC_CSR_SR_BG_CKE_DISABLE_MASK (0x20000UL)
#define SDC_CSR_SR_BG_CKE_DISABLE_SHIFT (17UL)
#define SDC_CSR_SR_BG_REF_MASK (0x10000UL)
#define SDC_CSR_SR_BG_REF_SHIFT (16UL)
#define SDC_CSR_SR_BG_MAX_MASK (0x7000UL)
#define SDC_CSR_SR_BG_MAX_SHIFT (12UL)
#define SDC_CSR_SR_RFSH_POST_MASK (0x7UL)
#define SDC_CSR_SR_RFSH_POST_SHIFT (0UL)




typedef uint32_t SDC_CSR_SS_TYPE;
#define SDC_CSR_SS_T_CMDPD_MASK (0x3UL)
#define SDC_CSR_SS_T_CMDPD_SHIFT (0UL)




typedef uint32_t SDC_CSR_ST_TYPE;
#define SDC_CSR_ST_T_RCDR_MASK (0x7f00000UL)
#define SDC_CSR_ST_T_RCDR_SHIFT (20UL)
#define SDC_CSR_ST_T_RCDW_MASK (0x7f000UL)
#define SDC_CSR_ST_T_RCDW_SHIFT (12UL)
#define SDC_CSR_ST_T_RAS_MASK (0xffUL)
#define SDC_CSR_ST_T_RAS_SHIFT (0UL)




typedef uint8_t SDC_CSR_RESERVED_TYPE;




typedef uint32_t SDC_CSR_PPR_TYPE;
#define SDC_CSR_PPR_PPR_MODE_MASK (0x80000000UL)
#define SDC_CSR_PPR_PPR_MODE_SHIFT (31UL)
#define SDC_CSR_PPR_PPR_CONFIRM_MASK (0x40000000UL)
#define SDC_CSR_PPR_PPR_CONFIRM_SHIFT (30UL)
#define SDC_CSR_PPR_PPR_ACT_MASK (0x20000000UL)
#define SDC_CSR_PPR_PPR_ACT_SHIFT (29UL)
#define SDC_CSR_PPR_PPR_PRE_MASK (0x10000000UL)
#define SDC_CSR_PPR_PPR_PRE_SHIFT (28UL)
#define SDC_CSR_PPR_RANK_MASK (0x3000000UL)
#define SDC_CSR_PPR_RANK_SHIFT (24UL)
#define SDC_CSR_PPR_BANK_MASK (0xf00000UL)
#define SDC_CSR_PPR_BANK_SHIFT (20UL)
#define SDC_CSR_PPR_CHAN_MASK (0x80000UL)
#define SDC_CSR_PPR_CHAN_SHIFT (19UL)
#define SDC_CSR_PPR_ROW_MASK (0x7ffffUL)
#define SDC_CSR_PPR_ROW_SHIFT (0UL)




typedef uint32_t SDC_CSR_MRT_TYPE;
#define SDC_CSR_MRT_T_MRRI_MASK (0x3f00UL)
#define SDC_CSR_MRT_T_MRRI_SHIFT (8UL)
#define SDC_CSR_MRT_T_MRW_MASK (0x1fUL)
#define SDC_CSR_MRT_T_MRW_SHIFT (0UL)




typedef uint32_t SDC_CSR_RFM_TYPE;
#define SDC_CSR_RFM_RFM_EN_MASK (0x80000000UL)
#define SDC_CSR_RFM_RFM_EN_SHIFT (31UL)
#define SDC_CSR_RFM_RFM_SB_MASK (0x40000000UL)
#define SDC_CSR_RFM_RFM_SB_SHIFT (30UL)
#define SDC_CSR_RFM_RFM_PB_MASK (0x20000000UL)
#define SDC_CSR_RFM_RFM_PB_SHIFT (29UL)
#define SDC_CSR_RFM_RAAMMT_MASK (0x1ffc0000UL)
#define SDC_CSR_RFM_RAAMMT_SHIFT (18UL)
#define SDC_CSR_RFM_RFM_DECR_MASK (0x3ff00UL)
#define SDC_CSR_RFM_RFM_DECR_SHIFT (8UL)
#define SDC_CSR_RFM_RAAIMT_MASK (0xffUL)
#define SDC_CSR_RFM_RAAIMT_SHIFT (0UL)




typedef uint32_t SDC_CSR_AXI_ARBITER_CONTROL_TYPE;
#define SDC_CSR_AXI_ARBITER_CONTROL_PAGE_MATCH_MASK (0x1000000UL)
#define SDC_CSR_AXI_ARBITER_CONTROL_PAGE_MATCH_SHIFT (24UL)
#define SDC_CSR_AXI_ARBITER_CONTROL_CHANNEL_INHIBIT_MASK (0xff00UL)
#define SDC_CSR_AXI_ARBITER_CONTROL_CHANNEL_INHIBIT_SHIFT (8UL)
#define SDC_CSR_AXI_ARBITER_CONTROL_ALGORITHM_MASK (0xe0UL)
#define SDC_CSR_AXI_ARBITER_CONTROL_ALGORITHM_SHIFT (5UL)
#define SDC_CSR_AXI_ARBITER_CONTROL_THRESHOLD_MASK (0x18UL)
#define SDC_CSR_AXI_ARBITER_CONTROL_THRESHOLD_SHIFT (3UL)
#define SDC_CSR_AXI_ARBITER_CONTROL_BUCKET_SIZE_MASK (0x3UL)
#define SDC_CSR_AXI_ARBITER_CONTROL_BUCKET_SIZE_SHIFT (0UL)




typedef uint32_t SDC_CSR_PORTC_TYPE;
#define SDC_CSR_PORTC_SDC_PORTS_MASK (0x70000000UL)
#define SDC_CSR_PORTC_SDC_PORTS_SHIFT (28UL)
#define SDC_CSR_PORTC_SDC_PDW_MASK (0xff00000UL)
#define SDC_CSR_PORTC_SDC_PDW_SHIFT (20UL)
#define SDC_CSR_PORTC_SD_PSL7_MASK (0xc000UL)
#define SDC_CSR_PORTC_SD_PSL7_SHIFT (14UL)
#define SDC_CSR_PORTC_SD_PSL6_MASK (0x3000UL)
#define SDC_CSR_PORTC_SD_PSL6_SHIFT (12UL)
#define SDC_CSR_PORTC_SD_PSL5_MASK (0xc00UL)
#define SDC_CSR_PORTC_SD_PSL5_SHIFT (10UL)
#define SDC_CSR_PORTC_SD_PSL4_MASK (0x300UL)
#define SDC_CSR_PORTC_SD_PSL4_SHIFT (8UL)
#define SDC_CSR_PORTC_SD_PSL3_MASK (0xc0UL)
#define SDC_CSR_PORTC_SD_PSL3_SHIFT (6UL)
#define SDC_CSR_PORTC_SD_PSL2_MASK (0x30UL)
#define SDC_CSR_PORTC_SD_PSL2_SHIFT (4UL)
#define SDC_CSR_PORTC_SD_PSL1_MASK (0xcUL)
#define SDC_CSR_PORTC_SD_PSL1_SHIFT (2UL)
#define SDC_CSR_PORTC_SD_PSL0_MASK (0x3UL)
#define SDC_CSR_PORTC_SD_PSL0_SHIFT (0UL)




typedef uint32_t SDC_CSR_PHYC_TYPE;
#define SDC_CSR_PHYC_DFI_ERRI_A_MASK (0xff000000UL)
#define SDC_CSR_PHYC_DFI_ERRI_A_SHIFT (24UL)
#define SDC_CSR_PHYC_DFI_ERRI_B_MASK (0xff0000UL)
#define SDC_CSR_PHYC_DFI_ERRI_B_SHIFT (16UL)
#define SDC_CSR_PHYC_LOCK_PLL_MASK (0x8000UL)
#define SDC_CSR_PHYC_LOCK_PLL_SHIFT (15UL)
#define SDC_CSR_PHYC_PHY_RBUS_IS_IDLE_MASK (0x4000UL)
#define SDC_CSR_PHYC_PHY_RBUS_IS_IDLE_SHIFT (14UL)
#define SDC_CSR_PHYC_PHY_READY_MASK (0x2000UL)
#define SDC_CSR_PHYC_PHY_READY_SHIFT (13UL)
#define SDC_CSR_PHYC_PHY_IS_IDLE_MASK (0x1000UL)
#define SDC_CSR_PHYC_PHY_IS_IDLE_SHIFT (12UL)
#define SDC_CSR_PHYC_TUNE_ENABLED_MASK (0x400UL)
#define SDC_CSR_PHYC_TUNE_ENABLED_SHIFT (10UL)
#define SDC_CSR_PHYC_DFI_ERR_A_MASK (0x200UL)
#define SDC_CSR_PHYC_DFI_ERR_A_SHIFT (9UL)
#define SDC_CSR_PHYC_DFI_ERR_B_MASK (0x100UL)
#define SDC_CSR_PHYC_DFI_ERR_B_SHIFT (8UL)
#define SDC_CSR_PHYC_PHY_PLL_RESET_MASK (0x80UL)
#define SDC_CSR_PHYC_PHY_PLL_RESET_SHIFT (7UL)




typedef uint32_t SDC_CSR_PHYHS_TYPE;
#define SDC_CSR_PHYHS_SW_TUNING_CTRL_MASK (0x10000000UL)
#define SDC_CSR_PHYHS_SW_TUNING_CTRL_SHIFT (28UL)
#define SDC_CSR_PHYHS_STOP_TUNING_MASK (0x1000000UL)
#define SDC_CSR_PHYHS_STOP_TUNING_SHIFT (24UL)
#define SDC_CSR_PHYHS_RETUNE_MASK (0x100000UL)
#define SDC_CSR_PHYHS_RETUNE_SHIFT (20UL)
#define SDC_CSR_PHYHS_SRX_ALLOWED_MASK (0x10000UL)
#define SDC_CSR_PHYHS_SRX_ALLOWED_SHIFT (16UL)
#define SDC_CSR_PHYHS_PHYUPD_REQ_MASK (0x100UL)
#define SDC_CSR_PHYHS_PHYUPD_REQ_SHIFT (8UL)
#define SDC_CSR_PHYHS_CKE_REQ_MASK (0x10UL)
#define SDC_CSR_PHYHS_CKE_REQ_SHIFT (4UL)
#define SDC_CSR_PHYHS_NOT_TUNED_MASK (0x1UL)
#define SDC_CSR_PHYHS_NOT_TUNED_SHIFT (0UL)




typedef uint32_t SDC_CSR_STALL_TYPE;
#define SDC_CSR_STALL_CYCLES_MASK (0x3ffUL)
#define SDC_CSR_STALL_CYCLES_SHIFT (0UL)




typedef uint32_t SDC_CSR_MR_TYPE;
#define SDC_CSR_MR_DONE_MASK (0x80000000UL)
#define SDC_CSR_MR_DONE_SHIFT (31UL)
#define SDC_CSR_MR_TIMEOUT_MASK (0x40000000UL)
#define SDC_CSR_MR_TIMEOUT_SHIFT (30UL)
#define SDC_CSR_MR_RW_MASK (0x20000000UL)
#define SDC_CSR_MR_RW_SHIFT (29UL)
#define SDC_CSR_MR_WR_ALL_RANK_MASK (0x10000000UL)
#define SDC_CSR_MR_WR_ALL_RANK_SHIFT (28UL)
#define SDC_CSR_MR_WR_1CH_MASK (0x8000000UL)
#define SDC_CSR_MR_WR_1CH_SHIFT (27UL)
#define SDC_CSR_MR_CHANNEL_MASK (0x4000000UL)
#define SDC_CSR_MR_CHANNEL_SHIFT (26UL)
#define SDC_CSR_MR_DEVICE_MASK (0x3000000UL)
#define SDC_CSR_MR_DEVICE_SHIFT (24UL)
#define SDC_CSR_MR_RDATA_MASK (0xff0000UL)
#define SDC_CSR_MR_RDATA_SHIFT (16UL)
#define SDC_CSR_MR_WDATA_MASK (0xff00UL)
#define SDC_CSR_MR_WDATA_SHIFT (8UL)
#define SDC_CSR_MR_MRR_BYTE_MASK (0x80UL)
#define SDC_CSR_MR_MRR_BYTE_SHIFT (7UL)
#define SDC_CSR_MR_ADDR_MASK (0x7fUL)
#define SDC_CSR_MR_ADDR_SHIFT (0UL)




typedef uint32_t SDC_CSR_MPC_TYPE;
#define SDC_CSR_MPC_DONE_MASK (0x80000000UL)
#define SDC_CSR_MPC_DONE_SHIFT (31UL)
#define SDC_CSR_MPC_PRECH_MASK (0x10000000UL)
#define SDC_CSR_MPC_PRECH_SHIFT (28UL)
#define SDC_CSR_MPC_MPC_1CH_MASK (0x8000000UL)
#define SDC_CSR_MPC_MPC_1CH_SHIFT (27UL)
#define SDC_CSR_MPC_CHANNEL_MASK (0x4000000UL)
#define SDC_CSR_MPC_CHANNEL_SHIFT (26UL)
#define SDC_CSR_MPC_DEVICE_MASK (0x3000000UL)
#define SDC_CSR_MPC_DEVICE_SHIFT (24UL)
#define SDC_CSR_MPC_MPC_OP_MASK (0xff0000UL)
#define SDC_CSR_MPC_MPC_OP_SHIFT (16UL)
#define SDC_CSR_MPC_T_MPC_MASK (0xfffUL)
#define SDC_CSR_MPC_T_MPC_SHIFT (0UL)




typedef uint32_t SDC_CSR_VER_TYPE;
#define SDC_CSR_VER_VERSION_MASK (0xffffffffUL)
#define SDC_CSR_VER_VERSION_SHIFT (0UL)




typedef uint32_t SDC_CSR_STFILT_TYPE;
#define SDC_CSR_STFILT_PORT_VALUE_MASK (0xf0000000UL)
#define SDC_CSR_STFILT_PORT_VALUE_SHIFT (28UL)
#define SDC_CSR_STFILT_ID_VALUE_MASK (0xfff0000UL)
#define SDC_CSR_STFILT_ID_VALUE_SHIFT (16UL)
#define SDC_CSR_STFILT_PORT_MASK_MASK (0xf000UL)
#define SDC_CSR_STFILT_PORT_MASK_SHIFT (12UL)
#define SDC_CSR_STFILT_ID_MASK_MASK (0xfffUL)
#define SDC_CSR_STFILT_ID_MASK_SHIFT (0UL)




typedef uint32_t SDC_CSR_IDL_TYPE;
#define SDC_CSR_IDL_IDLE_MASK (0xffffffffUL)
#define SDC_CSR_IDL_IDLE_SHIFT (0UL)




typedef uint32_t SDC_CSR_RTC_TYPE;
#define SDC_CSR_RTC_CYCLE_MASK (0xffffffffUL)
#define SDC_CSR_RTC_CYCLE_SHIFT (0UL)




typedef uint32_t SDC_CSR_WTC_TYPE;
#define SDC_CSR_WTC_CYCLE_MASK (0xffffffffUL)
#define SDC_CSR_WTC_CYCLE_SHIFT (0UL)




typedef uint32_t SDC_CSR_RDC_TYPE;
#define SDC_CSR_RDC_BYTE_MASK (0xffffffffUL)
#define SDC_CSR_RDC_BYTE_SHIFT (0UL)




typedef uint32_t SDC_CSR_WDC_TYPE;
#define SDC_CSR_WDC_BYTE_MASK (0xffffffffUL)
#define SDC_CSR_WDC_BYTE_SHIFT (0UL)




typedef uint32_t SDC_CSR_RAC_TYPE;
#define SDC_CSR_RAC_COUNT_MASK (0xffffffffUL)
#define SDC_CSR_RAC_COUNT_SHIFT (0UL)




typedef uint32_t SDC_CSR_CYC_TYPE;
#define SDC_CSR_CYC_COUNT_MASK (0xffffffffUL)
#define SDC_CSR_CYC_COUNT_SHIFT (0UL)




typedef uint32_t SDC_CSR_CMD_TYPE;
#define SDC_CSR_CMD_COUNT_MASK (0xffffffffUL)
#define SDC_CSR_CMD_COUNT_SHIFT (0UL)




typedef uint32_t SDC_CSR_DAT_TYPE;
#define SDC_CSR_DAT_COUNT_MASK (0xffffffffUL)
#define SDC_CSR_DAT_COUNT_SHIFT (0UL)




typedef uint32_t SDC_CSR_CNT_TYPE;
#define SDC_CSR_CNT_COUNT_MASK (0xffffffffUL)
#define SDC_CSR_CNT_COUNT_SHIFT (0UL)




typedef uint32_t SDC_CSR_QMX_TYPE;
#define SDC_CSR_QMX_COUNT_MASK (0x1fUL)
#define SDC_CSR_QMX_COUNT_SHIFT (0UL)




typedef uint32_t SDC_CSR_REORD_TYPE;
#define SDC_CSR_REORD_COUNT_MASK (0xffffffffUL)
#define SDC_CSR_REORD_COUNT_SHIFT (0UL)




typedef uint32_t SDC_CSR_LAC_TYPE;
#define SDC_CSR_LAC_COUNT_MASK (0xffffffffUL)
#define SDC_CSR_LAC_COUNT_SHIFT (0UL)




typedef uint32_t SDC_CSR_RFMCYC_TYPE;
#define SDC_CSR_RFMCYC_CYCLES_MASK (0xffffffffUL)
#define SDC_CSR_RFMCYC_CYCLES_SHIFT (0UL)




typedef uint32_t SDC_CSR_RFMCNT_TYPE;
#define SDC_CSR_RFMCNT_COUNT_MASK (0xffffffffUL)
#define SDC_CSR_RFMCNT_COUNT_SHIFT (0UL)




typedef uint32_t SDC_CSR_STTIME_TYPE;
#define SDC_CSR_STTIME_TIME_ST_EN_MASK (0x80000000UL)
#define SDC_CSR_STTIME_TIME_ST_EN_SHIFT (31UL)
#define SDC_CSR_STTIME_COMPLETE_MASK (0x40000000UL)
#define SDC_CSR_STTIME_COMPLETE_SHIFT (30UL)
#define SDC_CSR_STTIME_TRIG_DIR_MASK (0x20000000UL)
#define SDC_CSR_STTIME_TRIG_DIR_SHIFT (29UL)
#define SDC_CSR_STTIME_TRIG_WR_MASK (0x10000000UL)
#define SDC_CSR_STTIME_TRIG_WR_SHIFT (28UL)
#define SDC_CSR_STTIME_COUNT_MASK (0xfffffffUL)
#define SDC_CSR_STTIME_COUNT_SHIFT (0UL)




typedef uint32_t SDC_CSR_STTAM_TYPE;
#define SDC_CSR_STTAM_A_MASK_MASK (0xffffffffUL)
#define SDC_CSR_STTAM_A_MASK_SHIFT (0UL)




typedef uint32_t SDC_CSR_STTAV_TYPE;
#define SDC_CSR_STTAV_A_VALUE_MASK (0xffffffffUL)
#define SDC_CSR_STTAV_A_VALUE_SHIFT (0UL)




typedef uint32_t SDC_CSR_STTID_TYPE;
#define SDC_CSR_STTID_PORT_VALUE_MASK (0xf0000000UL)
#define SDC_CSR_STTID_PORT_VALUE_SHIFT (28UL)
#define SDC_CSR_STTID_ID_VALUE_MASK (0xfff0000UL)
#define SDC_CSR_STTID_ID_VALUE_SHIFT (16UL)
#define SDC_CSR_STTID_PORT_MASK_MASK (0xf000UL)
#define SDC_CSR_STTID_PORT_MASK_SHIFT (12UL)
#define SDC_CSR_STTID_ID_MASK_MASK (0xfffUL)
#define SDC_CSR_STTID_ID_MASK_SHIFT (0UL)




typedef uint32_t SDC_CSR_VADH_TYPE;
#define SDC_CSR_VADH_ADDRESS_MASK (0xfUL)
#define SDC_CSR_VADH_ADDRESS_SHIFT (0UL)




typedef uint32_t SDC_CSR_VADL_TYPE;
#define SDC_CSR_VADL_ADDRESS_MASK (0xffffffffUL)
#define SDC_CSR_VADL_ADDRESS_SHIFT (0UL)




typedef uint32_t SDC_CSR_VIN_TYPE;
#define SDC_CSR_VIN_CLEAR_MASK (0x80000000UL)
#define SDC_CSR_VIN_CLEAR_SHIFT (31UL)
#define SDC_CSR_VIN_INT_EN_MASK (0x10000000UL)
#define SDC_CSR_VIN_INT_EN_SHIFT (28UL)
#define SDC_CSR_VIN_MULT_MASK (0x1000000UL)
#define SDC_CSR_VIN_MULT_SHIFT (24UL)
#define SDC_CSR_VIN_VIO_MASK (0x100000UL)
#define SDC_CSR_VIN_VIO_SHIFT (20UL)
#define SDC_CSR_VIN_SPLIT_MASK (0x20000UL)
#define SDC_CSR_VIN_SPLIT_SHIFT (17UL)
#define SDC_CSR_VIN_WRITE_MASK (0x10000UL)
#define SDC_CSR_VIN_WRITE_SHIFT (16UL)
#define SDC_CSR_VIN_PORT_MASK (0xf000UL)
#define SDC_CSR_VIN_PORT_SHIFT (12UL)
#define SDC_CSR_VIN_ID_MASK (0xfffUL)
#define SDC_CSR_VIN_ID_SHIFT (0UL)




typedef uint32_t SDC_CSR_DIAGP_TYPE;
#define SDC_CSR_DIAGP_SEEN_MASK (0x20000000UL)
#define SDC_CSR_DIAGP_SEEN_SHIFT (29UL)
#define SDC_CSR_DIAGP_SPLIT_MASK (0x10000000UL)
#define SDC_CSR_DIAGP_SPLIT_SHIFT (28UL)
#define SDC_CSR_DIAGP_AD35_32_MASK (0xf000000UL)
#define SDC_CSR_DIAGP_AD35_32_SHIFT (24UL)
#define SDC_CSR_DIAGP_WR_MASK (0x800000UL)
#define SDC_CSR_DIAGP_WR_SHIFT (23UL)
#define SDC_CSR_DIAGP_SIZE_MASK (0x700000UL)
#define SDC_CSR_DIAGP_SIZE_SHIFT (20UL)
#define SDC_CSR_DIAGP_LEN_MASK (0xf0000UL)
#define SDC_CSR_DIAGP_LEN_SHIFT (16UL)
#define SDC_CSR_DIAGP_PORT_MASK (0xf000UL)
#define SDC_CSR_DIAGP_PORT_SHIFT (12UL)
#define SDC_CSR_DIAGP_ID_MASK (0xfffUL)
#define SDC_CSR_DIAGP_ID_SHIFT (0UL)




typedef uint32_t SDC_CSR_DIAGA_TYPE;
#define SDC_CSR_DIAGA_AD31_0_MASK (0xffffffffUL)
#define SDC_CSR_DIAGA_AD31_0_SHIFT (0UL)




typedef uint32_t SDC_CSR_DIAGI_TYPE;
#define SDC_CSR_DIAGI_LTRAP_MASK (0x80000000UL)
#define SDC_CSR_DIAGI_LTRAP_SHIFT (31UL)
#define SDC_CSR_DIAGI_CUR_PID_MASK (0x7fff0000UL)
#define SDC_CSR_DIAGI_CUR_PID_SHIFT (16UL)
#define SDC_CSR_DIAGI_CA_VALID_MASK (0x8000UL)
#define SDC_CSR_DIAGI_CA_VALID_SHIFT (15UL)
#define SDC_CSR_DIAGI_WR_ORD_ST_MASK (0x4000UL)
#define SDC_CSR_DIAGI_WR_ORD_ST_SHIFT (14UL)
#define SDC_CSR_DIAGI_RD_BUF_SPC_MASK (0x2000UL)
#define SDC_CSR_DIAGI_RD_BUF_SPC_SHIFT (13UL)
#define SDC_CSR_DIAGI_W2AW_STALL_MASK (0x1000UL)
#define SDC_CSR_DIAGI_W2AW_STALL_SHIFT (12UL)
#define SDC_CSR_DIAGI_GSM_ST_MASK (0xfe0UL)
#define SDC_CSR_DIAGI_GSM_ST_SHIFT (5UL)
#define SDC_CSR_DIAGI_Q_CNT_MASK (0x1fUL)
#define SDC_CSR_DIAGI_Q_CNT_SHIFT (0UL)




typedef uint32_t SDC_CSR_SECSRT0_TYPE;
#define SDC_CSR_SECSRT0_ADDR_MS_MASK (0xfffffe00UL)
#define SDC_CSR_SECSRT0_ADDR_MS_SHIFT (9UL)
#define SDC_CSR_SECSRT0_MASK_MASK (0x1feUL)
#define SDC_CSR_SECSRT0_MASK_SHIFT (1UL)
#define SDC_CSR_SECSRT0_ENABLE_MASK (0x1UL)
#define SDC_CSR_SECSRT0_ENABLE_SHIFT (0UL)




typedef uint32_t SDC_CSR_SECEND0_TYPE;
#define SDC_CSR_SECEND0_ADDR_MS_MASK (0xfffffe00UL)
#define SDC_CSR_SECEND0_ADDR_MS_SHIFT (9UL)
#define SDC_CSR_SECEND0_ADDR_LS_MASK (0x1ffUL)
#define SDC_CSR_SECEND0_ADDR_LS_SHIFT (0UL)




typedef uint32_t SDC_CSR_PHYBS_TYPE;
#define SDC_CSR_PHYBS_DPFE_BLK_DFI_MASK (0x20UL)
#define SDC_CSR_PHYBS_DPFE_BLK_DFI_SHIFT (5UL)
#define SDC_CSR_PHYBS_DPFE_DISABLE_MASK (0x10UL)
#define SDC_CSR_PHYBS_DPFE_DISABLE_SHIFT (4UL)
#define SDC_CSR_PHYBS_DPFE_BLK_MEM_MASK (0xfUL)
#define SDC_CSR_PHYBS_DPFE_BLK_MEM_SHIFT (0UL)



#define SDC_CSR_SECSRT_SIZE  (32UL)

#define SDC_CSR_SECEND_SIZE  (32UL)


typedef volatile struct sSDC_CSR_RDBType {
    SDC_CSR_CS_TYPE cs; /* OFFSET: 0x0 */
    SDC_CSR_SA_TYPE sa; /* OFFSET: 0x4 */
    SDC_CSR_SB_TYPE sb; /* OFFSET: 0x8 */
    SDC_CSR_SC_TYPE sc; /* OFFSET: 0xc */
    SDC_CSR_SD_TYPE sd; /* OFFSET: 0x10 */
    SDC_CSR_SE_TYPE se; /* OFFSET: 0x14 */
    SDC_CSR_SF_TYPE sf; /* OFFSET: 0x18 */
    SDC_CSR_SG_TYPE sg; /* OFFSET: 0x1c */
    SDC_CSR_SH_TYPE sh; /* OFFSET: 0x20 */
    SDC_CSR_SJ_TYPE sj; /* OFFSET: 0x24 */
    SDC_CSR_SK_TYPE sk; /* OFFSET: 0x28 */
    SDC_CSR_SL_TYPE sl; /* OFFSET: 0x2c */
    SDC_CSR_SM_TYPE sm; /* OFFSET: 0x30 */
    SDC_CSR_SN_TYPE sn; /* OFFSET: 0x34 */
    SDC_CSR_SP_TYPE sp; /* OFFSET: 0x38 */
    SDC_CSR_SQ_TYPE sq; /* OFFSET: 0x3c */
    SDC_CSR_SR_TYPE sr; /* OFFSET: 0x40 */
    SDC_CSR_SS_TYPE ss; /* OFFSET: 0x44 */
    SDC_CSR_ST_TYPE st; /* OFFSET: 0x48 */
    SDC_CSR_RESERVED_TYPE rsvd0[16]; /* OFFSET: 0x4c */
    SDC_CSR_PPR_TYPE ppr; /* OFFSET: 0x5c */
    SDC_CSR_MRT_TYPE mrt; /* OFFSET: 0x60 */
    SDC_CSR_RFM_TYPE rfm; /* OFFSET: 0x64 */
    SDC_CSR_AXI_ARBITER_CONTROL_TYPE arb_ctrl; /* OFFSET: 0x68 */
    SDC_CSR_PORTC_TYPE portc; /* OFFSET: 0x6c */
    SDC_CSR_PHYC_TYPE phyc; /* OFFSET: 0x70 */
    SDC_CSR_PHYHS_TYPE phyhs; /* OFFSET: 0x74 */
    SDC_CSR_STALL_TYPE stall; /* OFFSET: 0x78 */
    SDC_CSR_RESERVED_TYPE rsvd1[20]; /* OFFSET: 0x7c */
    SDC_CSR_MR_TYPE mr; /* OFFSET: 0x90 */
    SDC_CSR_MPC_TYPE mpc; /* OFFSET: 0x94 */
    SDC_CSR_RESERVED_TYPE rsvd2[8]; /* OFFSET: 0x98 */
    SDC_CSR_VER_TYPE ver; /* OFFSET: 0xa0 */
    SDC_CSR_RESERVED_TYPE rsvd3[92]; /* OFFSET: 0xa4 */
    SDC_CSR_STFILT_TYPE stfilt; /* OFFSET: 0x100 */
    SDC_CSR_IDL_TYPE idl; /* OFFSET: 0x104 */
    SDC_CSR_RTC_TYPE rtc; /* OFFSET: 0x108 */
    SDC_CSR_WTC_TYPE wtc; /* OFFSET: 0x10c */
    SDC_CSR_RDC_TYPE rdc; /* OFFSET: 0x110 */
    SDC_CSR_WDC_TYPE wdc; /* OFFSET: 0x114 */
    SDC_CSR_RAC_TYPE rac; /* OFFSET: 0x118 */
    SDC_CSR_CYC_TYPE cyc; /* OFFSET: 0x11c */
    SDC_CSR_CMD_TYPE cmd; /* OFFSET: 0x120 */
    SDC_CSR_DAT_TYPE dat; /* OFFSET: 0x124 */
    SDC_CSR_CNT_TYPE wrcmd; /* OFFSET: 0x128 */
    SDC_CSR_CNT_TYPE wrsub; /* OFFSET: 0x12c */
    SDC_CSR_CNT_TYPE mwrcmd; /* OFFSET: 0x130 */
    SDC_CSR_CNT_TYPE mwrsub; /* OFFSET: 0x134 */
    SDC_CSR_CNT_TYPE rdcmd; /* OFFSET: 0x138 */
    SDC_CSR_CNT_TYPE rdsub; /* OFFSET: 0x13c */
    SDC_CSR_QMX_TYPE qmx; /* OFFSET: 0x140 */
    SDC_CSR_REORD_TYPE reord; /* OFFSET: 0x144 */
    SDC_CSR_LAC_TYPE lac; /* OFFSET: 0x148 */
    SDC_CSR_CNT_TYPE pre; /* OFFSET: 0x14c */
    SDC_CSR_REORD_TYPE wreord; /* OFFSET: 0x150 */
    SDC_CSR_RAC_TYPE proc_act; /* OFFSET: 0x154 */
    SDC_CSR_RFMCYC_TYPE raaimtcyc; /* OFFSET: 0x158 */
    SDC_CSR_RFMCYC_TYPE raammtcyc; /* OFFSET: 0x15c */
    SDC_CSR_RFMCNT_TYPE rfmpbcnt; /* OFFSET: 0x160 */
    SDC_CSR_RFMCNT_TYPE rfmabcnt; /* OFFSET: 0x164 */
    SDC_CSR_STTIME_TYPE sttime; /* OFFSET: 0x168 */
    SDC_CSR_STTAM_TYPE sttam; /* OFFSET: 0x16c */
    SDC_CSR_STTAV_TYPE sttav; /* OFFSET: 0x170 */
    SDC_CSR_STTID_TYPE sttid; /* OFFSET: 0x174 */
    SDC_CSR_RESERVED_TYPE rsvd4[136]; /* OFFSET: 0x178 */
    SDC_CSR_VADH_TYPE vadh; /* OFFSET: 0x200 */
    SDC_CSR_VADL_TYPE vadl; /* OFFSET: 0x204 */
    SDC_CSR_VIN_TYPE vin; /* OFFSET: 0x208 */
    SDC_CSR_RESERVED_TYPE rsvd5[36]; /* OFFSET: 0x20c */
    SDC_CSR_DIAGP_TYPE diagsop; /* OFFSET: 0x230 */
    SDC_CSR_DIAGA_TYPE diagsoa; /* OFFSET: 0x234 */
    SDC_CSR_DIAGP_TYPE diagmwp; /* OFFSET: 0x238 */
    SDC_CSR_DIAGA_TYPE diagmwa; /* OFFSET: 0x23c */
    SDC_CSR_DIAGI_TYPE diagi; /* OFFSET: 0x240 */
    SDC_CSR_RESERVED_TYPE rsvd6[188]; /* OFFSET: 0x244 */
    SDC_CSR_SECSRT0_TYPE secsrt[SDC_CSR_SECSRT_SIZE]; /* OFFSET: 0x300 */
    SDC_CSR_SECEND0_TYPE secend[SDC_CSR_SECEND_SIZE]; /* OFFSET: 0x380 */
    SDC_CSR_RESERVED_TYPE rsvd7[2816]; /* OFFSET: 0x400 */
    SDC_CSR_PHYBS_TYPE phybs; /* OFFSET: 0xf00 */
} SDC_CSR_RDBType;


#define SDC_CSR_BASE                    (0xE029B000UL)



#define SDC_CSR_MAX_HW_ID               (1UL)

#endif /* SDC_CSR_RDB_H */
