/*****************************************************************************
 Copyright 2025 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file hsadc_rdb.h
    @brief RDB File for HSADC

    @version BCM89580_A0_20230125_RDB
*/

#ifndef HSADC_RDB_H
#define HSADC_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t HSADC_ADCCAL_CONTROL0_TYPE;
#define HSADC_ADCCAL_CONTROL0_CAL_BUSY_MASK (0x80000000UL)
#define HSADC_ADCCAL_CONTROL0_CAL_BUSY_SHIFT (31UL)
#define HSADC_ADCCAL_CONTROL0_CAL_HW_BG_EN_MASK (0x80UL)
#define HSADC_ADCCAL_CONTROL0_CAL_HW_BG_EN_SHIFT (7UL)
#define HSADC_ADCCAL_CONTROL0_CAL_START_MASK (0x20UL)
#define HSADC_ADCCAL_CONTROL0_CAL_START_SHIFT (5UL)
#define HSADC_ADCCAL_CONTROL0_CAL_STATES_EN_MASK (0x1fUL)
#define HSADC_ADCCAL_CONTROL0_CAL_STATES_EN_SHIFT (0UL)




typedef uint32_t HSADC_ADCCAL_CONTROL1_TYPE;
#define HSADC_ADCCAL_CONTROL1_CAL_BG_RDB_DURATION_MASK (0xffffUL)
#define HSADC_ADCCAL_CONTROL1_CAL_BG_RDB_DURATION_SHIFT (0UL)




typedef uint32_t HSADC_ADCCAL_CONTROL2_TYPE;
#define HSADC_ADCCAL_CONTROL2_BG_OFFSET_CLR_MASK (0x80000000UL)
#define HSADC_ADCCAL_CONTROL2_BG_OFFSET_CLR_SHIFT (31UL)
#define HSADC_ADCCAL_CONTROL2_BG_GAIN_CLR_MASK (0x40000000UL)
#define HSADC_ADCCAL_CONTROL2_BG_GAIN_CLR_SHIFT (30UL)
#define HSADC_ADCCAL_CONTROL2_BG_CAL_SETUP_TIME_MASK (0xc0000UL)
#define HSADC_ADCCAL_CONTROL2_BG_CAL_SETUP_TIME_SHIFT (18UL)
#define HSADC_ADCCAL_CONTROL2_BG_CAL_CLAMP_PERIOD_MASK (0x30000UL)
#define HSADC_ADCCAL_CONTROL2_BG_CAL_CLAMP_PERIOD_SHIFT (16UL)
#define HSADC_ADCCAL_CONTROL2_RESERVED_15_MASK (0x8000UL)
#define HSADC_ADCCAL_CONTROL2_RESERVED_15_SHIFT (15UL)
#define HSADC_ADCCAL_CONTROL2_BG_OFFSET_MU_MASK (0x7000UL)
#define HSADC_ADCCAL_CONTROL2_BG_OFFSET_MU_SHIFT (12UL)
#define HSADC_ADCCAL_CONTROL2_BG_CAL_CFG_MASK (0xc00UL)
#define HSADC_ADCCAL_CONTROL2_BG_CAL_CFG_SHIFT (10UL)
#define HSADC_ADCCAL_CONTROL2_BG_GAIN_MODE_MASK (0x300UL)
#define HSADC_ADCCAL_CONTROL2_BG_GAIN_MODE_SHIFT (8UL)
#define HSADC_ADCCAL_CONTROL2_BG_GAIN_REF_AVG_ALL_MASK (0x80UL)
#define HSADC_ADCCAL_CONTROL2_BG_GAIN_REF_AVG_ALL_SHIFT (7UL)
#define HSADC_ADCCAL_CONTROL2_BG_GAIN_NMAX_MASK (0x70UL)
#define HSADC_ADCCAL_CONTROL2_BG_GAIN_NMAX_SHIFT (4UL)
#define HSADC_ADCCAL_CONTROL2_BG_GAIN_MU_MASK (0xfUL)
#define HSADC_ADCCAL_CONTROL2_BG_GAIN_MU_SHIFT (0UL)




typedef uint32_t HSADC_ADCCAL_CONTROL3_TYPE;
#define HSADC_ADCCAL_CONTROL3_BG_CLAMP_EN_MASK (0x40000000UL)
#define HSADC_ADCCAL_CONTROL3_BG_CLAMP_EN_SHIFT (30UL)
#define HSADC_ADCCAL_CONTROL3_BG_SF1_PD_MASK (0x20000000UL)
#define HSADC_ADCCAL_CONTROL3_BG_SF1_PD_SHIFT (29UL)
#define HSADC_ADCCAL_CONTROL3_NON_BG_SF1_PD_MASK (0x10000000UL)
#define HSADC_ADCCAL_CONTROL3_NON_BG_SF1_PD_SHIFT (28UL)
#define HSADC_ADCCAL_CONTROL3_BG_SF_BIAS_MODE_MASK (0xc000000UL)
#define HSADC_ADCCAL_CONTROL3_BG_SF_BIAS_MODE_SHIFT (26UL)
#define HSADC_ADCCAL_CONTROL3_NON_BG_SF_BIAS_MODE_MASK (0x3000000UL)
#define HSADC_ADCCAL_CONTROL3_NON_BG_SF_BIAS_MODE_SHIFT (24UL)
#define HSADC_ADCCAL_CONTROL3_BG_ADC_DC_OFFSET_MASK (0xf00000UL)
#define HSADC_ADCCAL_CONTROL3_BG_ADC_DC_OFFSET_SHIFT (20UL)
#define HSADC_ADCCAL_CONTROL3_NON_BG_ADC_DC_OFFSET_MASK (0xf0000UL)
#define HSADC_ADCCAL_CONTROL3_NON_BG_ADC_DC_OFFSET_SHIFT (16UL)
#define HSADC_ADCCAL_CONTROL3_BG_RDB_REF_MASK (0xffffUL)
#define HSADC_ADCCAL_CONTROL3_BG_RDB_REF_SHIFT (0UL)




typedef uint32_t HSADC_ADCCAL_CONTROL4_TYPE;
#define HSADC_ADCCAL_CONTROL4_FG_ADC_TAH_ZERO_OVR_VAL_MASK (0x400UL)
#define HSADC_ADCCAL_CONTROL4_FG_ADC_TAH_ZERO_OVR_VAL_SHIFT (10UL)
#define HSADC_ADCCAL_CONTROL4_FG_ADC_SAR_ZERO_OVR_VAL_MASK (0x200UL)
#define HSADC_ADCCAL_CONTROL4_FG_ADC_SAR_ZERO_OVR_VAL_SHIFT (9UL)
#define HSADC_ADCCAL_CONTROL4_FG_CAL_OVERRIDE_EN_MASK (0x100UL)
#define HSADC_ADCCAL_CONTROL4_FG_CAL_OVERRIDE_EN_SHIFT (8UL)
#define HSADC_ADCCAL_CONTROL4_FG_OFFSET_ERROR_MASK (0x40UL)
#define HSADC_ADCCAL_CONTROL4_FG_OFFSET_ERROR_SHIFT (6UL)
#define HSADC_ADCCAL_CONTROL4_FG_OFFSET_ACC_DLY_MASK (0x30UL)
#define HSADC_ADCCAL_CONTROL4_FG_OFFSET_ACC_DLY_SHIFT (4UL)
#define HSADC_ADCCAL_CONTROL4_FG_OFFSET_INIT_DLY_MASK (0xcUL)
#define HSADC_ADCCAL_CONTROL4_FG_OFFSET_INIT_DLY_SHIFT (2UL)
#define HSADC_ADCCAL_CONTROL4_FG_OFFSET_SWAP_POLARITY_MASK (0x2UL)
#define HSADC_ADCCAL_CONTROL4_FG_OFFSET_SWAP_POLARITY_SHIFT (1UL)
#define HSADC_ADCCAL_CONTROL4_FG_OFFSET_MODE_MASK (0x1UL)
#define HSADC_ADCCAL_CONTROL4_FG_OFFSET_MODE_SHIFT (0UL)




typedef uint32_t HSADC_ADCCAL_CONTROL5_TYPE;
#define HSADC_ADCCAL_CONTROL5_FG_DACCAL_LANE_CTL_MASK (0xffff0000UL)
#define HSADC_ADCCAL_CONTROL5_FG_DACCAL_LANE_CTL_SHIFT (16UL)
#define HSADC_ADCCAL_CONTROL5_FG_DACCAL_UNDERFLOW_ERROR_MASK (0x400UL)
#define HSADC_ADCCAL_CONTROL5_FG_DACCAL_UNDERFLOW_ERROR_SHIFT (10UL)
#define HSADC_ADCCAL_CONTROL5_FG_DACCAL_OVERFLOW_ERROR_MASK (0x200UL)
#define HSADC_ADCCAL_CONTROL5_FG_DACCAL_OVERFLOW_ERROR_SHIFT (9UL)
#define HSADC_ADCCAL_CONTROL5_FG_DACCAL_OVR_STATE_VAL_MASK (0x1c0UL)
#define HSADC_ADCCAL_CONTROL5_FG_DACCAL_OVR_STATE_VAL_SHIFT (6UL)
#define HSADC_ADCCAL_CONTROL5_FG_DACCAL_OVR_EN_VAL_MASK (0x20UL)
#define HSADC_ADCCAL_CONTROL5_FG_DACCAL_OVR_EN_VAL_SHIFT (5UL)
#define HSADC_ADCCAL_CONTROL5_FG_DACCAL_OVERRIDE_EN_MASK (0x10UL)
#define HSADC_ADCCAL_CONTROL5_FG_DACCAL_OVERRIDE_EN_SHIFT (4UL)
#define HSADC_ADCCAL_CONTROL5_FG_DACCAL_NMAX_MASK (0xfUL)
#define HSADC_ADCCAL_CONTROL5_FG_DACCAL_NMAX_SHIFT (0UL)




typedef uint8_t HSADC_RESERVED_TYPE;




typedef uint32_t HSADC_ACQ_CONTROL0_TYPE;
#define HSADC_ACQ_CONTROL0_CAP_BUSY_MASK (0x80000000UL)
#define HSADC_ACQ_CONTROL0_CAP_BUSY_SHIFT (31UL)
#define HSADC_ACQ_CONTROL0_AGG_CNT_MASK (0x1f0000UL)
#define HSADC_ACQ_CONTROL0_AGG_CNT_SHIFT (16UL)
#define HSADC_ACQ_CONTROL0_SAMPLING_MODE_MASK (0xc000UL)
#define HSADC_ACQ_CONTROL0_SAMPLING_MODE_SHIFT (14UL)
#define HSADC_ACQ_CONTROL0_DEC_RATE_MASK (0x3000UL)
#define HSADC_ACQ_CONTROL0_DEC_RATE_SHIFT (12UL)
#define HSADC_ACQ_CONTROL0_FFT_EN_MASK (0x800UL)
#define HSADC_ACQ_CONTROL0_FFT_EN_SHIFT (11UL)
#define HSADC_ACQ_CONTROL0_FFT_SIZE_MASK (0x700UL)
#define HSADC_ACQ_CONTROL0_FFT_SIZE_SHIFT (8UL)
#define HSADC_ACQ_CONTROL0_CH_EN_MASK (0xf0UL)
#define HSADC_ACQ_CONTROL0_CH_EN_SHIFT (4UL)
#define HSADC_ACQ_CONTROL0_OCP_TESTMODE_MASK (0x8UL)
#define HSADC_ACQ_CONTROL0_OCP_TESTMODE_SHIFT (3UL)
#define HSADC_ACQ_CONTROL0_CAP_MODE_MASK (0x7UL)
#define HSADC_ACQ_CONTROL0_CAP_MODE_SHIFT (0UL)




typedef uint32_t HSADC_ACQ_CONTROL1_TYPE;
#define HSADC_ACQ_CONTROL1_SPARE_MASK (0xffffffffUL)
#define HSADC_ACQ_CONTROL1_SPARE_SHIFT (0UL)




typedef uint32_t HSADC_ACQ_CONTROL2_TYPE;
#define HSADC_ACQ_CONTROL2_CAP_START_ADDR_MASK (0x3ff0000UL)
#define HSADC_ACQ_CONTROL2_CAP_START_ADDR_SHIFT (16UL)
#define HSADC_ACQ_CONTROL2_CAP_SIZE_MASK (0x7ffUL)
#define HSADC_ACQ_CONTROL2_CAP_SIZE_SHIFT (0UL)




typedef uint32_t HSADC_ACQ_CONTROL3_TYPE;
#define HSADC_ACQ_CONTROL3_RD_DONE_ADDR_MASK (0x7ff0000UL)
#define HSADC_ACQ_CONTROL3_RD_DONE_ADDR_SHIFT (16UL)
#define HSADC_ACQ_CONTROL3_RD_CAP_SIZE_MASK (0x3fffUL)
#define HSADC_ACQ_CONTROL3_RD_CAP_SIZE_SHIFT (0UL)




typedef uint32_t HSADC_ACQ_CONTROL4_TYPE;
#define HSADC_ACQ_CONTROL4_FFT_PREDIV_MASK (0xf0000UL)
#define HSADC_ACQ_CONTROL4_FFT_PREDIV_SHIFT (16UL)
#define HSADC_ACQ_CONTROL4_FFT_RD_PERIOD_MASK (0xffffUL)
#define HSADC_ACQ_CONTROL4_FFT_RD_PERIOD_SHIFT (0UL)




typedef uint32_t HSADC_ACQ_BUF_STATUS_TYPE;
#define HSADC_ACQ_BUF_STATUS_LOST_FRAMES_MASK (0xffff0000UL)
#define HSADC_ACQ_BUF_STATUS_LOST_FRAMES_SHIFT (16UL)
#define HSADC_ACQ_BUF_STATUS_LOST_FRAMES_CLR_MASK (0x200UL)
#define HSADC_ACQ_BUF_STATUS_LOST_FRAMES_CLR_SHIFT (9UL)
#define HSADC_ACQ_BUF_STATUS_BUF_STATUS_CLR_MASK (0x100UL)
#define HSADC_ACQ_BUF_STATUS_BUF_STATUS_CLR_SHIFT (8UL)
#define HSADC_ACQ_BUF_STATUS_BUF_B_STATUS_MASK (0xcUL)
#define HSADC_ACQ_BUF_STATUS_BUF_B_STATUS_SHIFT (2UL)
#define HSADC_ACQ_BUF_STATUS_BUF_A_STATUS_MASK (0x3UL)
#define HSADC_ACQ_BUF_STATUS_BUF_A_STATUS_SHIFT (0UL)




typedef uint32_t HSADC_WND_CONTROL_TYPE;
#define HSADC_WND_CONTROL_ADDR_MASK (0xff00UL)
#define HSADC_WND_CONTROL_ADDR_SHIFT (8UL)
#define HSADC_WND_CONTROL_RD_STROBE_MASK (0x8UL)
#define HSADC_WND_CONTROL_RD_STROBE_SHIFT (3UL)
#define HSADC_WND_CONTROL_WR_STROBE_MASK (0x4UL)
#define HSADC_WND_CONTROL_WR_STROBE_SHIFT (2UL)
#define HSADC_WND_CONTROL_EN_MASK (0x1UL)
#define HSADC_WND_CONTROL_EN_SHIFT (0UL)




typedef uint32_t HSADC_WND_DATA_REG_TYPE;
#define HSADC_WND_DATA_REG_MASK (0xffffffffUL)
#define HSADC_WND_DATA_REG_SHIFT (0UL)




typedef uint32_t HSADC_CLAMP_CONTROL_TYPE;
#define HSADC_CLAMP_CONTROL_ADC_DELAY_MASK (0xffff0000UL)
#define HSADC_CLAMP_CONTROL_ADC_DELAY_SHIFT (16UL)
#define HSADC_CLAMP_CONTROL_ADC_DURATION_MASK (0x1ffeUL)
#define HSADC_CLAMP_CONTROL_ADC_DURATION_SHIFT (1UL)
#define HSADC_CLAMP_CONTROL_ADC_EN_MASK (0x1UL)
#define HSADC_CLAMP_CONTROL_ADC_EN_SHIFT (0UL)




typedef uint32_t HSADC_TOF_OFFSET_TYPE;
#define HSADC_TOF_OFFSET_MASK (0x3ffUL)
#define HSADC_TOF_OFFSET_SHIFT (0UL)




typedef uint32_t HSADC_FIR_CONTROL_TYPE;
#define HSADC_FIR_CONTROL_DGAIN_MASK (0xcUL)
#define HSADC_FIR_CONTROL_DGAIN_SHIFT (2UL)
#define HSADC_FIR_CONTROL_FIR_EN_MASK (0x1UL)
#define HSADC_FIR_CONTROL_FIR_EN_SHIFT (0UL)




typedef uint32_t HSADC_FIR_COEFF_TYPE;
#define HSADC_FIR_COEFF_MASK (0x3ffUL)
#define HSADC_FIR_COEFF_SHIFT (0UL)




typedef uint32_t HSADC_AXIS_INFO_CONTROL_TYPE;
#define HSADC_AXIS_INFO_CONTROL_FFT_AXIS_CAP_MASK (0x2UL)
#define HSADC_AXIS_INFO_CONTROL_FFT_AXIS_CAP_SHIFT (1UL)
#define HSADC_AXIS_INFO_CONTROL_ADCBUF_AXIS_CAP_MASK (0x1UL)
#define HSADC_AXIS_INFO_CONTROL_ADCBUF_AXIS_CAP_SHIFT (0UL)




typedef uint32_t HSADC_AXIS_INFO_READ_TYPE;
#define HSADC_AXIS_INFO_READ_FFT_MASK (0xffffffffUL)
#define HSADC_AXIS_INFO_READ_FFT_SHIFT (0UL)




typedef uint32_t HSADC_MEM_INIT_CONTROL_TYPE;
#define HSADC_MEM_INIT_CONTROL_FFT_MEM_RSTB_MASK (0x100UL)
#define HSADC_MEM_INIT_CONTROL_FFT_MEM_RSTB_SHIFT (8UL)
#define HSADC_MEM_INIT_CONTROL_FFT_MEM_INIT_EN_MASK (0x80UL)
#define HSADC_MEM_INIT_CONTROL_FFT_MEM_INIT_EN_SHIFT (7UL)
#define HSADC_MEM_INIT_CONTROL_FFT_MEM_INT_CHK_EN_MASK (0x40UL)
#define HSADC_MEM_INIT_CONTROL_FFT_MEM_INT_CHK_EN_SHIFT (6UL)
#define HSADC_MEM_INIT_CONTROL_FFTBUF_MEM_RSTB_MASK (0x20UL)
#define HSADC_MEM_INIT_CONTROL_FFTBUF_MEM_RSTB_SHIFT (5UL)
#define HSADC_MEM_INIT_CONTROL_FFTBUF_MEM_INIT_EN_MASK (0x10UL)
#define HSADC_MEM_INIT_CONTROL_FFTBUF_MEM_INIT_EN_SHIFT (4UL)
#define HSADC_MEM_INIT_CONTROL_FFTBUF_MEM_INT_CHK_EN_MASK (0x8UL)
#define HSADC_MEM_INIT_CONTROL_FFTBUF_MEM_INT_CHK_EN_SHIFT (3UL)
#define HSADC_MEM_INIT_CONTROL_ADCBUF_MEM_RSTB_MASK (0x4UL)
#define HSADC_MEM_INIT_CONTROL_ADCBUF_MEM_RSTB_SHIFT (2UL)
#define HSADC_MEM_INIT_CONTROL_ADCBUF_MEM_INIT_EN_MASK (0x2UL)
#define HSADC_MEM_INIT_CONTROL_ADCBUF_MEM_INIT_EN_SHIFT (1UL)
#define HSADC_MEM_INIT_CONTROL_ADCBUF_MEM_INT_CHK_EN_MASK (0x1UL)
#define HSADC_MEM_INIT_CONTROL_ADCBUF_MEM_INT_CHK_EN_SHIFT (0UL)




typedef uint32_t HSADC_MEM_TM_TYPE;
#define HSADC_MEM_TM_FFT_TM_MASK (0xf000000UL)
#define HSADC_MEM_TM_FFT_TM_SHIFT (24UL)
#define HSADC_MEM_TM_FFTBUF_TM_MASK (0x7f0000UL)
#define HSADC_MEM_TM_FFTBUF_TM_SHIFT (16UL)
#define HSADC_MEM_TM_WND_TM_MASK (0x7f00UL)
#define HSADC_MEM_TM_WND_TM_SHIFT (8UL)
#define HSADC_MEM_TM_ADCBUF_TM_MASK (0x7fUL)
#define HSADC_MEM_TM_ADCBUF_TM_SHIFT (0UL)




typedef uint32_t HSADC_AFE_SPARE_END_TYPE;
#define HSADC_AFE_SPARE_END_MASK (0xffffffffUL)
#define HSADC_AFE_SPARE_END_SHIFT (0UL)




typedef volatile struct sHSADC_RDBType {
    HSADC_ADCCAL_CONTROL0_TYPE adccal_control0; /* OFFSET: 0x0 */
    HSADC_ADCCAL_CONTROL1_TYPE adccal_control1; /* OFFSET: 0x4 */
    HSADC_ADCCAL_CONTROL2_TYPE adccal_control2; /* OFFSET: 0x8 */
    HSADC_ADCCAL_CONTROL3_TYPE adccal_control3; /* OFFSET: 0xc */
    HSADC_ADCCAL_CONTROL4_TYPE adccal_control4; /* OFFSET: 0x10 */
    HSADC_ADCCAL_CONTROL5_TYPE adccal_control5; /* OFFSET: 0x14 */
    uint32_t reserved_48; /* OFFSET: 0x18 */
    uint32_t reserved_49; /* OFFSET: 0x1c */
    uint32_t reserved_50; /* OFFSET: 0x20 */
    HSADC_RESERVED_TYPE rsvd0[28]; /* OFFSET: 0x24 */
    HSADC_ACQ_CONTROL0_TYPE acq_control0; /* OFFSET: 0x40 */
    HSADC_ACQ_CONTROL1_TYPE acq_control1; /* OFFSET: 0x44 */
    HSADC_ACQ_CONTROL2_TYPE acq_control2; /* OFFSET: 0x48 */
    HSADC_ACQ_CONTROL3_TYPE acq_control3; /* OFFSET: 0x4c */
    HSADC_ACQ_CONTROL4_TYPE acq_control4; /* OFFSET: 0x50 */
    HSADC_ACQ_BUF_STATUS_TYPE acq_ch0_buf_status; /* OFFSET: 0x54 */
    HSADC_ACQ_BUF_STATUS_TYPE acq_ch1_buf_status; /* OFFSET: 0x58 */
    HSADC_ACQ_BUF_STATUS_TYPE acq_ch2_buf_status; /* OFFSET: 0x5c */
    HSADC_ACQ_BUF_STATUS_TYPE acq_ch3_buf_status; /* OFFSET: 0x60 */
    HSADC_WND_CONTROL_TYPE wnd_control; /* OFFSET: 0x64 */
    HSADC_WND_DATA_REG_TYPE wnd_data7; /* OFFSET: 0x68 */
    HSADC_WND_DATA_REG_TYPE wnd_data6; /* OFFSET: 0x6c */
    HSADC_WND_DATA_REG_TYPE wnd_data5; /* OFFSET: 0x70 */
    HSADC_WND_DATA_REG_TYPE wnd_data4; /* OFFSET: 0x74 */
    HSADC_WND_DATA_REG_TYPE wnd_data3; /* OFFSET: 0x78 */
    HSADC_WND_DATA_REG_TYPE wnd_data2; /* OFFSET: 0x7c */
    HSADC_WND_DATA_REG_TYPE wnd_data1; /* OFFSET: 0x80 */
    HSADC_WND_DATA_REG_TYPE wnd_data0; /* OFFSET: 0x84 */
    HSADC_CLAMP_CONTROL_TYPE clamp_control; /* OFFSET: 0x88 */
    HSADC_TOF_OFFSET_TYPE tof_offset; /* OFFSET: 0x8c */
    HSADC_FIR_CONTROL_TYPE fir_control; /* OFFSET: 0x90 */
    HSADC_FIR_COEFF_TYPE fir_coeff31; /* OFFSET: 0x94 */
    HSADC_FIR_COEFF_TYPE fir_coeff30; /* OFFSET: 0x98 */
    HSADC_FIR_COEFF_TYPE fir_coeff29; /* OFFSET: 0x9c */
    HSADC_FIR_COEFF_TYPE fir_coeff28; /* OFFSET: 0xa0 */
    HSADC_FIR_COEFF_TYPE fir_coeff27; /* OFFSET: 0xa4 */
    HSADC_FIR_COEFF_TYPE fir_coeff26; /* OFFSET: 0xa8 */
    HSADC_FIR_COEFF_TYPE fir_coeff25; /* OFFSET: 0xac */
    HSADC_FIR_COEFF_TYPE fir_coeff24; /* OFFSET: 0xb0 */
    HSADC_FIR_COEFF_TYPE fir_coeff23; /* OFFSET: 0xb4 */
    HSADC_FIR_COEFF_TYPE fir_coeff22; /* OFFSET: 0xb8 */
    HSADC_FIR_COEFF_TYPE fir_coeff21; /* OFFSET: 0xbc */
    HSADC_FIR_COEFF_TYPE fir_coeff20; /* OFFSET: 0xc0 */
    HSADC_FIR_COEFF_TYPE fir_coeff19; /* OFFSET: 0xc4 */
    HSADC_FIR_COEFF_TYPE fir_coeff18; /* OFFSET: 0xc8 */
    HSADC_FIR_COEFF_TYPE fir_coeff17; /* OFFSET: 0xcc */
    HSADC_FIR_COEFF_TYPE fir_coeff16; /* OFFSET: 0xd0 */
    HSADC_FIR_COEFF_TYPE fir_coeff15; /* OFFSET: 0xd4 */
    HSADC_FIR_COEFF_TYPE fir_coeff14; /* OFFSET: 0xd8 */
    HSADC_FIR_COEFF_TYPE fir_coeff13; /* OFFSET: 0xdc */
    HSADC_FIR_COEFF_TYPE fir_coeff12; /* OFFSET: 0xe0 */
    HSADC_FIR_COEFF_TYPE fir_coeff11; /* OFFSET: 0xe4 */
    HSADC_FIR_COEFF_TYPE fir_coeff10; /* OFFSET: 0xe8 */
    HSADC_FIR_COEFF_TYPE fir_coeff9; /* OFFSET: 0xec */
    HSADC_FIR_COEFF_TYPE fir_coeff8; /* OFFSET: 0xf0 */
    HSADC_FIR_COEFF_TYPE fir_coeff7; /* OFFSET: 0xf4 */
    HSADC_FIR_COEFF_TYPE fir_coeff6; /* OFFSET: 0xf8 */
    HSADC_FIR_COEFF_TYPE fir_coeff5; /* OFFSET: 0xfc */
    HSADC_FIR_COEFF_TYPE fir_coeff4; /* OFFSET: 0x100 */
    HSADC_FIR_COEFF_TYPE fir_coeff3; /* OFFSET: 0x104 */
    HSADC_FIR_COEFF_TYPE fir_coeff2; /* OFFSET: 0x108 */
    HSADC_FIR_COEFF_TYPE fir_coeff1; /* OFFSET: 0x10c */
    HSADC_FIR_COEFF_TYPE fir_coeff0; /* OFFSET: 0x110 */
    HSADC_AXIS_INFO_CONTROL_TYPE axis_info_control; /* OFFSET: 0x114 */
    HSADC_AXIS_INFO_READ_TYPE axis_info_read_lo; /* OFFSET: 0x118 */
    HSADC_AXIS_INFO_READ_TYPE axis_info_read_hi; /* OFFSET: 0x11c */
    HSADC_MEM_INIT_CONTROL_TYPE mem_init_ctrl; /* OFFSET: 0x120 */
    HSADC_MEM_TM_TYPE mem_tm; /* OFFSET: 0x124 */
    HSADC_RESERVED_TYPE rsvd1[3540]; /* OFFSET: 0x128 */
    HSADC_AFE_SPARE_END_TYPE spare_end; /* OFFSET: 0xefc */
} HSADC_RDBType;


#define HSADC_ACQ_0_BASE                (0xE0602000UL)

#define HSADC_ACQ_1_BASE                (0xE0603000UL)

#define HSADC_ACQ_2_BASE                (0xE0604000UL)

#define HSADC_ACQ_3_BASE                (0xE0605000UL)



#define HSADC_MAX_HW_ID                 (4UL)

#endif /* HSADC_RDB_H */
