/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file hsadc_intr_rdb.h
    @brief RDB File for HSADC_INTR

    @version BCM89580_A0_20230125_RDB
*/

#ifndef HSADC_INTR_RDB_H
#define HSADC_INTR_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t HSADC_INTR_AHFIE_TYPE;
#define HSADC_INTR_AHFIE_P_ADC_CALIB_ERR_INTR_MASK (0x80000000UL)
#define HSADC_INTR_AHFIE_P_ADC_CALIB_ERR_INTR_SHIFT (31UL)
#define HSADC_INTR_AHFIE_P_CAP_MODE_COMPLETE_INTR_MASK (0x2UL)
#define HSADC_INTR_AHFIE_P_CAP_MODE_COMPLETE_INTR_SHIFT (1UL)
#define HSADC_INTR_AHFIE_P_ADC_CALIB_DONE_INTR_MASK (0x1UL)
#define HSADC_INTR_AHFIE_P_ADC_CALIB_DONE_INTR_SHIFT (0UL)




typedef uint32_t HSADC_INTR_AHFIE1_TYPE;
#define HSADC_INTR_AHFIE1_ADC_CALIB_ERR_INTR_W2CLR_MASK (0x80000000UL)
#define HSADC_INTR_AHFIE1_ADC_CALIB_ERR_INTR_W2CLR_SHIFT (31UL)
#define HSADC_INTR_AHFIE1_CAP_MODE_COMPLETE_INTR_W2CLR_MASK (0x2UL)
#define HSADC_INTR_AHFIE1_CAP_MODE_COMPLETE_INTR_W2CLR_SHIFT (1UL)
#define HSADC_INTR_AHFIE1_ADC_CALIB_DONE_INTR_W2CLR_MASK (0x1UL)
#define HSADC_INTR_AHFIE1_ADC_CALIB_DONE_INTR_W2CLR_SHIFT (0UL)




typedef uint32_t HSADC_INTR_AHFIE2_TYPE;
#define HSADC_INTR_AHFIE2_ENABLE_ADC_CALIB_ERR_INTR_MASK (0x80000000UL)
#define HSADC_INTR_AHFIE2_ENABLE_ADC_CALIB_ERR_INTR_SHIFT (31UL)
#define HSADC_INTR_AHFIE2_ENABLE_CAP_MODE_COMPLETE_INTR_MASK (0x2UL)
#define HSADC_INTR_AHFIE2_ENABLE_CAP_MODE_COMPLETE_INTR_SHIFT (1UL)
#define HSADC_INTR_AHFIE2_ENABLE_ADC_CALIB_DONE_INTR_MASK (0x1UL)
#define HSADC_INTR_AHFIE2_ENABLE_ADC_CALIB_DONE_INTR_SHIFT (0UL)




typedef uint32_t HSADC_INTR_AHBIE_TYPE;
#define HSADC_INTR_AHBIE_P_CH3_FFT_DONE_INTR_MASK (0x80UL)
#define HSADC_INTR_AHBIE_P_CH3_FFT_DONE_INTR_SHIFT (7UL)
#define HSADC_INTR_AHBIE_P_CH2_FFT_DONE_INTR_MASK (0x40UL)
#define HSADC_INTR_AHBIE_P_CH2_FFT_DONE_INTR_SHIFT (6UL)
#define HSADC_INTR_AHBIE_P_CH1_FFT_DONE_INTR_MASK (0x20UL)
#define HSADC_INTR_AHBIE_P_CH1_FFT_DONE_INTR_SHIFT (5UL)
#define HSADC_INTR_AHBIE_P_CH0_FFT_DONE_INTR_MASK (0x10UL)
#define HSADC_INTR_AHBIE_P_CH0_FFT_DONE_INTR_SHIFT (4UL)
#define HSADC_INTR_AHBIE_P_CH3_ADC_BUF_CAP_DONE_INTR_MASK (0x8UL)
#define HSADC_INTR_AHBIE_P_CH3_ADC_BUF_CAP_DONE_INTR_SHIFT (3UL)
#define HSADC_INTR_AHBIE_P_CH2_ADC_BUF_CAP_DONE_INTR_MASK (0x4UL)
#define HSADC_INTR_AHBIE_P_CH2_ADC_BUF_CAP_DONE_INTR_SHIFT (2UL)
#define HSADC_INTR_AHBIE_P_CH1_ADC_BUF_CAP_DONE_INTR_MASK (0x2UL)
#define HSADC_INTR_AHBIE_P_CH1_ADC_BUF_CAP_DONE_INTR_SHIFT (1UL)
#define HSADC_INTR_AHBIE_P_CH0_ADC_BUF_CAP_DONE_INTR_MASK (0x1UL)
#define HSADC_INTR_AHBIE_P_CH0_ADC_BUF_CAP_DONE_INTR_SHIFT (0UL)




typedef uint32_t HSADC_INTR_AHBIE1_TYPE;
#define HSADC_INTR_AHBIE1_CH3_FFT_DONE_INTR_W2CLR_MASK (0x80UL)
#define HSADC_INTR_AHBIE1_CH3_FFT_DONE_INTR_W2CLR_SHIFT (7UL)
#define HSADC_INTR_AHBIE1_CH2_FFT_DONE_INTR_W2CLR_MASK (0x40UL)
#define HSADC_INTR_AHBIE1_CH2_FFT_DONE_INTR_W2CLR_SHIFT (6UL)
#define HSADC_INTR_AHBIE1_CH1_FFT_DONE_INTR_W2CLR_MASK (0x20UL)
#define HSADC_INTR_AHBIE1_CH1_FFT_DONE_INTR_W2CLR_SHIFT (5UL)
#define HSADC_INTR_AHBIE1_CH0_FFT_DONE_INTR_W2CLR_MASK (0x10UL)
#define HSADC_INTR_AHBIE1_CH0_FFT_DONE_INTR_W2CLR_SHIFT (4UL)
#define HSADC_INTR_AHBIE1_CH3_ADC_BUF_CAP_DONE_INTR_W2CLR_MASK (0x8UL)
#define HSADC_INTR_AHBIE1_CH3_ADC_BUF_CAP_DONE_INTR_W2CLR_SHIFT (3UL)
#define HSADC_INTR_AHBIE1_CH2_ADC_BUF_CAP_DONE_INTR_W2CLR_MASK (0x4UL)
#define HSADC_INTR_AHBIE1_CH2_ADC_BUF_CAP_DONE_INTR_W2CLR_SHIFT (2UL)
#define HSADC_INTR_AHBIE1_CH1_ADC_BUF_CAP_DONE_INTR_W2CLR_MASK (0x2UL)
#define HSADC_INTR_AHBIE1_CH1_ADC_BUF_CAP_DONE_INTR_W2CLR_SHIFT (1UL)
#define HSADC_INTR_AHBIE1_CH0_ADC_BUF_CAP_DONE_INTR_W2CLR_MASK (0x1UL)
#define HSADC_INTR_AHBIE1_CH0_ADC_BUF_CAP_DONE_INTR_W2CLR_SHIFT (0UL)




typedef uint32_t HSADC_INTR_AHBIE2_TYPE;
#define HSADC_INTR_AHBIE2_ENABLE_CH3_FFT_DONE_INTR_MASK (0x80UL)
#define HSADC_INTR_AHBIE2_ENABLE_CH3_FFT_DONE_INTR_SHIFT (7UL)
#define HSADC_INTR_AHBIE2_ENABLE_CH2_FFT_DONE_INTR_MASK (0x40UL)
#define HSADC_INTR_AHBIE2_ENABLE_CH2_FFT_DONE_INTR_SHIFT (6UL)
#define HSADC_INTR_AHBIE2_ENABLE_CH1_FFT_DONE_INTR_MASK (0x20UL)
#define HSADC_INTR_AHBIE2_ENABLE_CH1_FFT_DONE_INTR_SHIFT (5UL)
#define HSADC_INTR_AHBIE2_ENABLE_CH0_FFT_DONE_INTR_MASK (0x10UL)
#define HSADC_INTR_AHBIE2_ENABLE_CH0_FFT_DONE_INTR_SHIFT (4UL)
#define HSADC_INTR_AHBIE2_ENABLE_CH3_ADC_BUF_CAP_DONE_INTR_MASK (0x8UL)
#define HSADC_INTR_AHBIE2_ENABLE_CH3_ADC_BUF_CAP_DONE_INTR_SHIFT (3UL)
#define HSADC_INTR_AHBIE2_ENABLE_CH2_ADC_BUF_CAP_DONE_INTR_MASK (0x4UL)
#define HSADC_INTR_AHBIE2_ENABLE_CH2_ADC_BUF_CAP_DONE_INTR_SHIFT (2UL)
#define HSADC_INTR_AHBIE2_ENABLE_CH1_ADC_BUF_CAP_DONE_INTR_MASK (0x2UL)
#define HSADC_INTR_AHBIE2_ENABLE_CH1_ADC_BUF_CAP_DONE_INTR_SHIFT (1UL)
#define HSADC_INTR_AHBIE2_ENABLE_CH0_ADC_BUF_CAP_DONE_INTR_MASK (0x1UL)
#define HSADC_INTR_AHBIE2_ENABLE_CH0_ADC_BUF_CAP_DONE_INTR_SHIFT (0UL)




typedef uint32_t HSADC_INTR_AHFEIE_TYPE;
#define HSADC_INTR_AHFEIE_P_FFT_IN_ERR_INTR_MASK (0x2000UL)
#define HSADC_INTR_AHFEIE_P_FFT_IN_ERR_INTR_SHIFT (13UL)
#define HSADC_INTR_AHFEIE_P_FFT_DATAPATH_ERR_INTR_MASK (0x1000UL)
#define HSADC_INTR_AHFEIE_P_FFT_DATAPATH_ERR_INTR_SHIFT (12UL)
#define HSADC_INTR_AHFEIE_P_FFT_MEM3_WR_ERR_INTR_MASK (0x800UL)
#define HSADC_INTR_AHFEIE_P_FFT_MEM3_WR_ERR_INTR_SHIFT (11UL)
#define HSADC_INTR_AHFEIE_P_FFT_MEM2_WR_ERR_INTR_MASK (0x400UL)
#define HSADC_INTR_AHFEIE_P_FFT_MEM2_WR_ERR_INTR_SHIFT (10UL)
#define HSADC_INTR_AHFEIE_P_FFT_MEM1_WR_ERR_INTR_MASK (0x200UL)
#define HSADC_INTR_AHFEIE_P_FFT_MEM1_WR_ERR_INTR_SHIFT (9UL)
#define HSADC_INTR_AHFEIE_P_FFT_MEM0_WR_ERR_INTR_MASK (0x100UL)
#define HSADC_INTR_AHFEIE_P_FFT_MEM0_WR_ERR_INTR_SHIFT (8UL)
#define HSADC_INTR_AHFEIE_P_BUF3_OCP_RD_ERR_INTR_MASK (0x80UL)
#define HSADC_INTR_AHFEIE_P_BUF3_OCP_RD_ERR_INTR_SHIFT (7UL)
#define HSADC_INTR_AHFEIE_P_BUF2_OCP_RD_ERR_INTR_MASK (0x40UL)
#define HSADC_INTR_AHFEIE_P_BUF2_OCP_RD_ERR_INTR_SHIFT (6UL)
#define HSADC_INTR_AHFEIE_P_BUF1_OCP_RD_ERR_INTR_MASK (0x20UL)
#define HSADC_INTR_AHFEIE_P_BUF1_OCP_RD_ERR_INTR_SHIFT (5UL)
#define HSADC_INTR_AHFEIE_P_BUF0_OCP_RD_ERR_INTR_MASK (0x10UL)
#define HSADC_INTR_AHFEIE_P_BUF0_OCP_RD_ERR_INTR_SHIFT (4UL)
#define HSADC_INTR_AHFEIE_P_ADC_DMA3_ERR_INTR_MASK (0x8UL)
#define HSADC_INTR_AHFEIE_P_ADC_DMA3_ERR_INTR_SHIFT (3UL)
#define HSADC_INTR_AHFEIE_P_ADC_DMA2_ERR_INTR_MASK (0x4UL)
#define HSADC_INTR_AHFEIE_P_ADC_DMA2_ERR_INTR_SHIFT (2UL)
#define HSADC_INTR_AHFEIE_P_ADC_DMA1_ERR_INTR_MASK (0x2UL)
#define HSADC_INTR_AHFEIE_P_ADC_DMA1_ERR_INTR_SHIFT (1UL)
#define HSADC_INTR_AHFEIE_P_ADC_DMA0_ERR_INTR_MASK (0x1UL)
#define HSADC_INTR_AHFEIE_P_ADC_DMA0_ERR_INTR_SHIFT (0UL)




typedef uint32_t HSADC_INTR_AHFEIE1_TYPE;
#define HSADC_INTR_AHFEIE1_FFT_IN_ERR_INTR_W2CLR_MASK (0x2000UL)
#define HSADC_INTR_AHFEIE1_FFT_IN_ERR_INTR_W2CLR_SHIFT (13UL)
#define HSADC_INTR_AHFEIE1_FFT_DATAPATH_ERR_INTR_W2CLR_MASK (0x1000UL)
#define HSADC_INTR_AHFEIE1_FFT_DATAPATH_ERR_INTR_W2CLR_SHIFT (12UL)
#define HSADC_INTR_AHFEIE1_FFT_MEM3_WR_ERR_INTR_W2CLR_MASK (0x800UL)
#define HSADC_INTR_AHFEIE1_FFT_MEM3_WR_ERR_INTR_W2CLR_SHIFT (11UL)
#define HSADC_INTR_AHFEIE1_FFT_MEM2_WR_ERR_INTR_W2CLR_MASK (0x400UL)
#define HSADC_INTR_AHFEIE1_FFT_MEM2_WR_ERR_INTR_W2CLR_SHIFT (10UL)
#define HSADC_INTR_AHFEIE1_FFT_MEM1_WR_ERR_INTR_W2CLR_MASK (0x200UL)
#define HSADC_INTR_AHFEIE1_FFT_MEM1_WR_ERR_INTR_W2CLR_SHIFT (9UL)
#define HSADC_INTR_AHFEIE1_FFT_MEM0_WR_ERR_INTR_W2CLR_MASK (0x100UL)
#define HSADC_INTR_AHFEIE1_FFT_MEM0_WR_ERR_INTR_W2CLR_SHIFT (8UL)
#define HSADC_INTR_AHFEIE1_BUF3_OCP_RD_ERR_INTR_W2CLR_MASK (0x80UL)
#define HSADC_INTR_AHFEIE1_BUF3_OCP_RD_ERR_INTR_W2CLR_SHIFT (7UL)
#define HSADC_INTR_AHFEIE1_BUF2_OCP_RD_ERR_INTR_W2CLR_MASK (0x40UL)
#define HSADC_INTR_AHFEIE1_BUF2_OCP_RD_ERR_INTR_W2CLR_SHIFT (6UL)
#define HSADC_INTR_AHFEIE1_BUF1_OCP_RD_ERR_INTR_W2CLR_MASK (0x20UL)
#define HSADC_INTR_AHFEIE1_BUF1_OCP_RD_ERR_INTR_W2CLR_SHIFT (5UL)
#define HSADC_INTR_AHFEIE1_BUF0_OCP_RD_ERR_INTR_W2CLR_MASK (0x10UL)
#define HSADC_INTR_AHFEIE1_BUF0_OCP_RD_ERR_INTR_W2CLR_SHIFT (4UL)
#define HSADC_INTR_AHFEIE1_ADC_DMA3_ERR_INTR_W2CLR_MASK (0x8UL)
#define HSADC_INTR_AHFEIE1_ADC_DMA3_ERR_INTR_W2CLR_SHIFT (3UL)
#define HSADC_INTR_AHFEIE1_ADC_DMA2_ERR_INTR_W2CLR_MASK (0x4UL)
#define HSADC_INTR_AHFEIE1_ADC_DMA2_ERR_INTR_W2CLR_SHIFT (2UL)
#define HSADC_INTR_AHFEIE1_ADC_DMA1_ERR_INTR_W2CLR_MASK (0x2UL)
#define HSADC_INTR_AHFEIE1_ADC_DMA1_ERR_INTR_W2CLR_SHIFT (1UL)
#define HSADC_INTR_AHFEIE1_ADC_DMA0_ERR_INTR_W2CLR_MASK (0x1UL)
#define HSADC_INTR_AHFEIE1_ADC_DMA0_ERR_INTR_W2CLR_SHIFT (0UL)




typedef uint32_t HSADC_INTR_AHFEIE2_TYPE;
#define HSADC_INTR_AHFEIE2_ENABLE_FFT_IN_ERR_INTR_MASK (0x2000UL)
#define HSADC_INTR_AHFEIE2_ENABLE_FFT_IN_ERR_INTR_SHIFT (13UL)
#define HSADC_INTR_AHFEIE2_ENABLE_FFT_DATAPATH_ERR_INTR_MASK (0x1000UL)
#define HSADC_INTR_AHFEIE2_ENABLE_FFT_DATAPATH_ERR_INTR_SHIFT (12UL)
#define HSADC_INTR_AHFEIE2_ENABLE_FFT_MEM3_WR_ERR_INTR_MASK (0x800UL)
#define HSADC_INTR_AHFEIE2_ENABLE_FFT_MEM3_WR_ERR_INTR_SHIFT (11UL)
#define HSADC_INTR_AHFEIE2_ENABLE_FFT_MEM2_WR_ERR_INTR_MASK (0x400UL)
#define HSADC_INTR_AHFEIE2_ENABLE_FFT_MEM2_WR_ERR_INTR_SHIFT (10UL)
#define HSADC_INTR_AHFEIE2_ENABLE_FFT_MEM1_WR_ERR_INTR_MASK (0x200UL)
#define HSADC_INTR_AHFEIE2_ENABLE_FFT_MEM1_WR_ERR_INTR_SHIFT (9UL)
#define HSADC_INTR_AHFEIE2_ENABLE_FFT_MEM0_WR_ERR_INTR_MASK (0x100UL)
#define HSADC_INTR_AHFEIE2_ENABLE_FFT_MEM0_WR_ERR_INTR_SHIFT (8UL)
#define HSADC_INTR_AHFEIE2_ENABLE_BUF3_OCP_RD_ERR_INTR_MASK (0x80UL)
#define HSADC_INTR_AHFEIE2_ENABLE_BUF3_OCP_RD_ERR_INTR_SHIFT (7UL)
#define HSADC_INTR_AHFEIE2_ENABLE_BUF2_OCP_RD_ERR_INTR_MASK (0x40UL)
#define HSADC_INTR_AHFEIE2_ENABLE_BUF2_OCP_RD_ERR_INTR_SHIFT (6UL)
#define HSADC_INTR_AHFEIE2_ENABLE_BUF1_OCP_RD_ERR_INTR_MASK (0x20UL)
#define HSADC_INTR_AHFEIE2_ENABLE_BUF1_OCP_RD_ERR_INTR_SHIFT (5UL)
#define HSADC_INTR_AHFEIE2_ENABLE_BUF0_OCP_RD_ERR_INTR_MASK (0x10UL)
#define HSADC_INTR_AHFEIE2_ENABLE_BUF0_OCP_RD_ERR_INTR_SHIFT (4UL)
#define HSADC_INTR_AHFEIE2_ENABLE_ADC_DMA3_ERR_INTR_MASK (0x8UL)
#define HSADC_INTR_AHFEIE2_ENABLE_ADC_DMA3_ERR_INTR_SHIFT (3UL)
#define HSADC_INTR_AHFEIE2_ENABLE_ADC_DMA2_ERR_INTR_MASK (0x4UL)
#define HSADC_INTR_AHFEIE2_ENABLE_ADC_DMA2_ERR_INTR_SHIFT (2UL)
#define HSADC_INTR_AHFEIE2_ENABLE_ADC_DMA1_ERR_INTR_MASK (0x2UL)
#define HSADC_INTR_AHFEIE2_ENABLE_ADC_DMA1_ERR_INTR_SHIFT (1UL)
#define HSADC_INTR_AHFEIE2_ENABLE_ADC_DMA0_ERR_INTR_MASK (0x1UL)
#define HSADC_INTR_AHFEIE2_ENABLE_ADC_DMA0_ERR_INTR_SHIFT (0UL)




typedef uint32_t HSADC_INTR_AHMISIE_TYPE;
#define HSADC_INTR_AHMISIE_P_WNDBUF_MEM_INIT_ERR_INTR_MASK (0x800UL)
#define HSADC_INTR_AHMISIE_P_WNDBUF_MEM_INIT_ERR_INTR_SHIFT (11UL)
#define HSADC_INTR_AHMISIE_P_WNDBUF_MEM_INIT_DONE_INTR_MASK (0x400UL)
#define HSADC_INTR_AHMISIE_P_WNDBUF_MEM_INIT_DONE_INTR_SHIFT (10UL)
#define HSADC_INTR_AHMISIE_P_WNDBUF_SEC_INTR_MASK (0x200UL)
#define HSADC_INTR_AHMISIE_P_WNDBUF_SEC_INTR_SHIFT (9UL)
#define HSADC_INTR_AHMISIE_P_FFTBUF_MEM_INIT_ERR_INTR_MASK (0x100UL)
#define HSADC_INTR_AHMISIE_P_FFTBUF_MEM_INIT_ERR_INTR_SHIFT (8UL)
#define HSADC_INTR_AHMISIE_P_FFTBUF_MEM_INIT_DONE_INTR_MASK (0x80UL)
#define HSADC_INTR_AHMISIE_P_FFTBUF_MEM_INIT_DONE_INTR_SHIFT (7UL)
#define HSADC_INTR_AHMISIE_P_FFT_MEM_INIT_ERR_INTR_MASK (0x20UL)
#define HSADC_INTR_AHMISIE_P_FFT_MEM_INIT_ERR_INTR_SHIFT (5UL)
#define HSADC_INTR_AHMISIE_P_FFT_MEM_INIT_DONE_INTR_MASK (0x10UL)
#define HSADC_INTR_AHMISIE_P_FFT_MEM_INIT_DONE_INTR_SHIFT (4UL)
#define HSADC_INTR_AHMISIE_P_ADCBUF_MEM_INIT_ERR_INTR_MASK (0x4UL)
#define HSADC_INTR_AHMISIE_P_ADCBUF_MEM_INIT_ERR_INTR_SHIFT (2UL)
#define HSADC_INTR_AHMISIE_P_ADCBUF_MEM_INIT_DONE_INTR_MASK (0x2UL)
#define HSADC_INTR_AHMISIE_P_ADCBUF_MEM_INIT_DONE_INTR_SHIFT (1UL)




typedef uint32_t HSADC_INTR_AHMISIE1_TYPE;
#define HSADC_INTR_AHMISIE1_WNDBUF_MEM_INIT_ERR_INTR_W2CLR_MASK (0x800UL)
#define HSADC_INTR_AHMISIE1_WNDBUF_MEM_INIT_ERR_INTR_W2CLR_SHIFT (11UL)
#define HSADC_INTR_AHMISIE1_WNDBUF_MEM_INIT_DONE_INTR_W2CLR_MASK (0x400UL)
#define HSADC_INTR_AHMISIE1_WNDBUF_MEM_INIT_DONE_INTR_W2CLR_SHIFT (10UL)
#define HSADC_INTR_AHMISIE1_WNDBUF_SEC_INTR_W2CLR_MASK (0x200UL)
#define HSADC_INTR_AHMISIE1_WNDBUF_SEC_INTR_W2CLR_SHIFT (9UL)
#define HSADC_INTR_AHMISIE1_FFTBUF_MEM_INIT_ERR_INTR_W2CLR_MASK (0x100UL)
#define HSADC_INTR_AHMISIE1_FFTBUF_MEM_INIT_ERR_INTR_W2CLR_SHIFT (8UL)
#define HSADC_INTR_AHMISIE1_FFTBUF_MEM_INIT_DONE_INTR_W2CLR_MASK (0x80UL)
#define HSADC_INTR_AHMISIE1_FFTBUF_MEM_INIT_DONE_INTR_W2CLR_SHIFT (7UL)
#define HSADC_INTR_AHMISIE1_FFT_MEM_INIT_ERR_INTR_W2CLR_MASK (0x20UL)
#define HSADC_INTR_AHMISIE1_FFT_MEM_INIT_ERR_INTR_W2CLR_SHIFT (5UL)
#define HSADC_INTR_AHMISIE1_FFT_MEM_INIT_DONE_INTR_W2CLR_MASK (0x10UL)
#define HSADC_INTR_AHMISIE1_FFT_MEM_INIT_DONE_INTR_W2CLR_SHIFT (4UL)
#define HSADC_INTR_AHMISIE1_ADCBUF_MEM_INIT_ERR_INTR_W2CLR_MASK (0x4UL)
#define HSADC_INTR_AHMISIE1_ADCBUF_MEM_INIT_ERR_INTR_W2CLR_SHIFT (2UL)
#define HSADC_INTR_AHMISIE1_ADCBUF_MEM_INIT_DONE_INTR_W2CLR_MASK (0x2UL)
#define HSADC_INTR_AHMISIE1_ADCBUF_MEM_INIT_DONE_INTR_W2CLR_SHIFT (1UL)




typedef uint32_t HSADC_INTR_AHMISIE2_TYPE;
#define HSADC_INTR_AHMISIE2_ENABLE_WNDBUF_MEM_INIT_ERR_INTR_MASK (0x800UL)
#define HSADC_INTR_AHMISIE2_ENABLE_WNDBUF_MEM_INIT_ERR_INTR_SHIFT (11UL)
#define HSADC_INTR_AHMISIE2_ENABLE_WNDBUF_MEM_INIT_DONE_INTR_MASK (0x400UL)
#define HSADC_INTR_AHMISIE2_ENABLE_WNDBUF_MEM_INIT_DONE_INTR_SHIFT (10UL)
#define HSADC_INTR_AHMISIE2_ENABLE_WNDBUF_SEC_INTR_MASK (0x200UL)
#define HSADC_INTR_AHMISIE2_ENABLE_WNDBUF_SEC_INTR_SHIFT (9UL)
#define HSADC_INTR_AHMISIE2_ENABLE_FFTBUF_MEM_INIT_ERR_INTR_MASK (0x100UL)
#define HSADC_INTR_AHMISIE2_ENABLE_FFTBUF_MEM_INIT_ERR_INTR_SHIFT (8UL)
#define HSADC_INTR_AHMISIE2_ENABLE_FFTBUF_MEM_INIT_DONE_INTR_MASK (0x80UL)
#define HSADC_INTR_AHMISIE2_ENABLE_FFTBUF_MEM_INIT_DONE_INTR_SHIFT (7UL)
#define HSADC_INTR_AHMISIE2_ENABLE_FFT_MEM_INIT_ERR_INTR_MASK (0x20UL)
#define HSADC_INTR_AHMISIE2_ENABLE_FFT_MEM_INIT_ERR_INTR_SHIFT (5UL)
#define HSADC_INTR_AHMISIE2_ENABLE_FFT_MEM_INIT_DONE_INTR_MASK (0x10UL)
#define HSADC_INTR_AHMISIE2_ENABLE_FFT_MEM_INIT_DONE_INTR_SHIFT (4UL)
#define HSADC_INTR_AHMISIE2_ENABLE_ADCBUF_MEM_INIT_ERR_INTR_MASK (0x4UL)
#define HSADC_INTR_AHMISIE2_ENABLE_ADCBUF_MEM_INIT_ERR_INTR_SHIFT (2UL)
#define HSADC_INTR_AHMISIE2_ENABLE_ADCBUF_MEM_INIT_DONE_INTR_MASK (0x2UL)
#define HSADC_INTR_AHMISIE2_ENABLE_ADCBUF_MEM_INIT_DONE_INTR_SHIFT (1UL)




typedef uint32_t HSADC_INTR_ACQ_HSADC_DED_INTR_EIPR_TYPE;
#define HSADC_INTR_ACQ_HSADC_DED_INTR_EIPR_P_WNDBUF_MASK (0x8UL)
#define HSADC_INTR_ACQ_HSADC_DED_INTR_EIPR_P_WNDBUF_SHIFT (3UL)




typedef uint32_t HSADC_INTR_ACQ_HSADC_DED_INTR_EISR_TYPE;
#define HSADC_INTR_ACQ_HSADC_DED_INTR_EISR_WNDBUF_W2CLR_MASK (0x8UL)
#define HSADC_INTR_ACQ_HSADC_DED_INTR_EISR_WNDBUF_W2CLR_SHIFT (3UL)




typedef uint32_t HSADC_INTR_ACQ_HSADC_DED_INTR_EIER_TYPE;
#define HSADC_INTR_ACQ_HSADC_DED_INTR_EIER_ENABLE_WNDBUF_MASK (0x8UL)
#define HSADC_INTR_ACQ_HSADC_DED_INTR_EIER_ENABLE_WNDBUF_SHIFT (3UL)




typedef uint8_t HSADC_INTR_RESERVED_TYPE;




typedef uint32_t HSADC_INTR_SPARE_END_REG_TYPE;
#define HSADC_INTR_SPARE_END_REG_MASK (0xffffffffUL)
#define HSADC_INTR_SPARE_END_REG_SHIFT (0UL)




typedef volatile struct sHSADC_INTR_RDBType {
    HSADC_INTR_AHFIE_TYPE acq_hsadc_func_intr_eipr; /* OFFSET: 0x0 */
    HSADC_INTR_AHFIE1_TYPE acq_hsadc_func_intr_eisr; /* OFFSET: 0x4 */
    HSADC_INTR_AHFIE2_TYPE acq_hsadc_func_intr_eier; /* OFFSET: 0x8 */
    HSADC_INTR_AHBIE_TYPE acq_hsadc_buf_intr_eipr; /* OFFSET: 0xc */
    HSADC_INTR_AHBIE1_TYPE acq_hsadc_buf_intr_eisr; /* OFFSET: 0x10 */
    HSADC_INTR_AHBIE2_TYPE acq_hsadc_buf_intr_eier; /* OFFSET: 0x14 */
    HSADC_INTR_AHFEIE_TYPE acq_hsadc_func_err_intr_eipr; /* OFFSET: 0x18 */
    HSADC_INTR_AHFEIE1_TYPE acq_hsadc_func_err_intr_eisr; /* OFFSET: 0x1c */
    HSADC_INTR_AHFEIE2_TYPE acq_hsadc_func_err_intr_eier; /* OFFSET: 0x20 */
    HSADC_INTR_AHMISIE_TYPE acq_hsadc_mem_init_sec_intr_eipr; /* OFFSET: 0x24 */
    HSADC_INTR_AHMISIE1_TYPE acq_hsadc_mem_init_sec_intr_eisr; /* OFFSET: 0x28 */
    HSADC_INTR_AHMISIE2_TYPE acq_hsadc_mem_init_sec_intr_eier; /* OFFSET: 0x2c */
    HSADC_INTR_ACQ_HSADC_DED_INTR_EIPR_TYPE acq_hsadc_ded_intr_eipr; /* OFFSET: 0x30 */
    HSADC_INTR_ACQ_HSADC_DED_INTR_EISR_TYPE acq_hsadc_ded_intr_eisr; /* OFFSET: 0x34 */
    HSADC_INTR_ACQ_HSADC_DED_INTR_EIER_TYPE acq_hsadc_ded_intr_eier; /* OFFSET: 0x38 */
    HSADC_INTR_RESERVED_TYPE rsvd0[192]; /* OFFSET: 0x3c */
    HSADC_INTR_SPARE_END_REG_TYPE spare_end_reg; /* OFFSET: 0xfc */
} HSADC_INTR_RDBType;


#define HSADC_INTR_0_BASE               (0xE0602F00UL)

#define HSADC_INTR_1_BASE               (0xE0603F00UL)

#define HSADC_INTR_2_BASE               (0xE0604F00UL)

#define HSADC_INTR_3_BASE               (0xE0605F00UL)



#define HSADC_INTR_MAX_HW_ID            (4UL)

#endif /* HSADC_INTR_RDB_H */
