/*****************************************************************************
 Copyright 2025 Broadcom.  All rights reserved.
 Broadcom Proprietary and Confidential
******************************************************************************/
/**
    @file clkrst_rdb.h
    @brief RDB File for CLKRST

    @version BCM89580_A0_20230125_RDB
*/

#ifndef CLKRST_RDB_H
#define CLKRST_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t CLKRST_RIGEL_TOP_CLK_CTRL_TYPE;
#define CLKRST_RIGEL_TOP_CLK_CTRL_ISTK_CNTL_PCLK_DIV_RATIO_MASK (0xff0000UL)
#define CLKRST_RIGEL_TOP_CLK_CTRL_ISTK_CNTL_PCLK_DIV_RATIO_SHIFT (16UL)
#define CLKRST_RIGEL_TOP_CLK_CTRL_TOP_AHB_CK_DIV_RATIO_MASK (0x700UL)
#define CLKRST_RIGEL_TOP_CLK_CTRL_TOP_AHB_CK_DIV_RATIO_SHIFT (8UL)
#define CLKRST_RIGEL_TOP_CLK_CTRL_LSP_AHB_CK_DIV_RATIO_MASK (0x70UL)
#define CLKRST_RIGEL_TOP_CLK_CTRL_LSP_AHB_CK_DIV_RATIO_SHIFT (4UL)
#define CLKRST_RIGEL_TOP_CLK_CTRL_Q8_PB_CK_DIV_RATIO_MASK (0xcUL)
#define CLKRST_RIGEL_TOP_CLK_CTRL_Q8_PB_CK_DIV_RATIO_SHIFT (2UL)




typedef uint32_t CLKRST_DMA330_CLK_CTRL_TYPE;
#define CLKRST_DMA330_CLK_CTRL_CLKEN_DLY_VAL_MASK (0xcUL)
#define CLKRST_DMA330_CLK_CTRL_CLKEN_DLY_VAL_SHIFT (2UL)
#define CLKRST_DMA330_CLK_CTRL_CLKEN_VAL_MASK (0x3UL)
#define CLKRST_DMA330_CLK_CTRL_CLKEN_VAL_SHIFT (0UL)




typedef uint32_t CLKRST_ACQ_TOP_RESET_CONTROL_TYPE;
#define CLKRST_ACQ_TOP_RESET_CONTROL_HARD_RESETN_FRC_MASK (0x8UL)
#define CLKRST_ACQ_TOP_RESET_CONTROL_HARD_RESETN_FRC_SHIFT (3UL)
#define CLKRST_ACQ_TOP_RESET_CONTROL_HARD_RESETN_FRCVAL_MASK (0x4UL)
#define CLKRST_ACQ_TOP_RESET_CONTROL_HARD_RESETN_FRCVAL_SHIFT (2UL)
#define CLKRST_ACQ_TOP_RESET_CONTROL_HRESETN_FRC_MASK (0x2UL)
#define CLKRST_ACQ_TOP_RESET_CONTROL_HRESETN_FRC_SHIFT (1UL)
#define CLKRST_ACQ_TOP_RESET_CONTROL_HRESETN_FRCVAL_MASK (0x1UL)
#define CLKRST_ACQ_TOP_RESET_CONTROL_HRESETN_FRCVAL_SHIFT (0UL)




typedef uint32_t CLKRST_A55PRC_TYPE;
#define CLKRST_A55PRC_A55_PROC_ARM_1588_TIMER_RSTN_FRC_MASK (0x200UL)
#define CLKRST_A55PRC_A55_PROC_ARM_1588_TIMER_RSTN_FRC_SHIFT (9UL)
#define CLKRST_A55PRC_A55_PROC_ARM_1588_TIMER_RSTN_FRCVAL_MASK (0x100UL)
#define CLKRST_A55PRC_A55_PROC_ARM_1588_TIMER_RSTN_FRCVAL_SHIFT (8UL)
#define CLKRST_A55PRC_A55_PROC_DAPRESETN_FRC_MASK (0x80UL)
#define CLKRST_A55PRC_A55_PROC_DAPRESETN_FRC_SHIFT (7UL)
#define CLKRST_A55PRC_A55_PROC_DAPRESETN_FRCVAL_MASK (0x40UL)
#define CLKRST_A55PRC_A55_PROC_DAPRESETN_FRCVAL_SHIFT (6UL)
#define CLKRST_A55PRC_A55_PROC_ARM_RESETN_FRC_MASK (0x20UL)
#define CLKRST_A55PRC_A55_PROC_ARM_RESETN_FRC_SHIFT (5UL)
#define CLKRST_A55PRC_A55_PROC_ARM_RESETN_FRCVAL_MASK (0x10UL)
#define CLKRST_A55PRC_A55_PROC_ARM_RESETN_FRCVAL_SHIFT (4UL)
#define CLKRST_A55PRC_A55_PROC_PRESETN_FRC_MASK (0x8UL)
#define CLKRST_A55PRC_A55_PROC_PRESETN_FRC_SHIFT (3UL)
#define CLKRST_A55PRC_A55_PROC_PRESETN_FRCVAL_MASK (0x4UL)
#define CLKRST_A55PRC_A55_PROC_PRESETN_FRCVAL_SHIFT (2UL)
#define CLKRST_A55PRC_A55_PROC_HRESETN_FRC_MASK (0x2UL)
#define CLKRST_A55PRC_A55_PROC_HRESETN_FRC_SHIFT (1UL)
#define CLKRST_A55PRC_A55_PROC_HRESETN_FRCVAL_MASK (0x1UL)
#define CLKRST_A55PRC_A55_PROC_HRESETN_FRCVAL_SHIFT (0UL)




typedef uint32_t CLKRST_CDSRC_TYPE;
#define CLKRST_CDSRC_CPU_DMA_SYS_DMA330_ARESETN_FRC_MASK (0x200UL)
#define CLKRST_CDSRC_CPU_DMA_SYS_DMA330_ARESETN_FRC_SHIFT (9UL)
#define CLKRST_CDSRC_CPU_DMA_SYS_DMA330_ARESETN_FRCVAL_MASK (0x100UL)
#define CLKRST_CDSRC_CPU_DMA_SYS_DMA330_ARESETN_FRCVAL_SHIFT (8UL)
#define CLKRST_CDSRC_CPU_DMA_SYS_DAP_RSTB_FRC_MASK (0x80UL)
#define CLKRST_CDSRC_CPU_DMA_SYS_DAP_RSTB_FRC_SHIFT (7UL)
#define CLKRST_CDSRC_CPU_DMA_SYS_DAP_RSTB_FRCVAL_MASK (0x40UL)
#define CLKRST_CDSRC_CPU_DMA_SYS_DAP_RSTB_FRCVAL_SHIFT (6UL)
#define CLKRST_CDSRC_CPU_DMA_SYS_MCU1_RSTB_FRC_MASK (0x20UL)
#define CLKRST_CDSRC_CPU_DMA_SYS_MCU1_RSTB_FRC_SHIFT (5UL)
#define CLKRST_CDSRC_CPU_DMA_SYS_MCU1_RSTB_FRCVAL_MASK (0x10UL)
#define CLKRST_CDSRC_CPU_DMA_SYS_MCU1_RSTB_FRCVAL_SHIFT (4UL)
#define CLKRST_CDSRC_CPU_DMA_SYS_MCU0_RSTB_FRC_MASK (0x8UL)
#define CLKRST_CDSRC_CPU_DMA_SYS_MCU0_RSTB_FRC_SHIFT (3UL)
#define CLKRST_CDSRC_CPU_DMA_SYS_MCU0_RSTB_FRCVAL_MASK (0x4UL)
#define CLKRST_CDSRC_CPU_DMA_SYS_MCU0_RSTB_FRCVAL_SHIFT (2UL)
#define CLKRST_CDSRC_CPU_DMA_SYS_HRESETN_FRC_MASK (0x2UL)
#define CLKRST_CDSRC_CPU_DMA_SYS_HRESETN_FRC_SHIFT (1UL)
#define CLKRST_CDSRC_CPU_DMA_SYS_HRESETN_FRCVAL_MASK (0x1UL)
#define CLKRST_CDSRC_CPU_DMA_SYS_HRESETN_FRCVAL_SHIFT (0UL)




typedef uint32_t CLKRST_DEBUG_SYS_RESET_CONTROL_TYPE;
#define CLKRST_DEBUG_SYS_RESET_CONTROL_DAPRESETN_FRC_MASK (0x20UL)
#define CLKRST_DEBUG_SYS_RESET_CONTROL_DAPRESETN_FRC_SHIFT (5UL)
#define CLKRST_DEBUG_SYS_RESET_CONTROL_DAPRESETN_FRCVAL_MASK (0x10UL)
#define CLKRST_DEBUG_SYS_RESET_CONTROL_DAPRESETN_FRCVAL_SHIFT (4UL)




typedef uint32_t CLKRST_GP_SRAM_RESET_CONTROL_TYPE;
#define CLKRST_GP_SRAM_RESET_CONTROL_BLK_EN_FRC_MASK (0x80UL)
#define CLKRST_GP_SRAM_RESET_CONTROL_BLK_EN_FRC_SHIFT (7UL)
#define CLKRST_GP_SRAM_RESET_CONTROL_BLK_EN_FRCVAL_MASK (0x40UL)
#define CLKRST_GP_SRAM_RESET_CONTROL_BLK_EN_FRCVAL_SHIFT (6UL)
#define CLKRST_GP_SRAM_RESET_CONTROL_CRSTB_FRC_MASK (0x20UL)
#define CLKRST_GP_SRAM_RESET_CONTROL_CRSTB_FRC_SHIFT (5UL)
#define CLKRST_GP_SRAM_RESET_CONTROL_CRSTB_FRCVAL_MASK (0x10UL)
#define CLKRST_GP_SRAM_RESET_CONTROL_CRSTB_FRCVAL_SHIFT (4UL)




typedef uint32_t CLKRST_HSIO_SYS_RESET_CONTROL_TYPE;
#define CLKRST_HSIO_SYS_RESET_CONTROL_PCIE_RSTB_FRC_MASK (0x20UL)
#define CLKRST_HSIO_SYS_RESET_CONTROL_PCIE_RSTB_FRC_SHIFT (5UL)
#define CLKRST_HSIO_SYS_RESET_CONTROL_PCIE_RSTB_FRCVAL_MASK (0x10UL)
#define CLKRST_HSIO_SYS_RESET_CONTROL_PCIE_RSTB_FRCVAL_SHIFT (4UL)
#define CLKRST_HSIO_SYS_RESET_CONTROL_CRSTB_FRC_MASK (0x8UL)
#define CLKRST_HSIO_SYS_RESET_CONTROL_CRSTB_FRC_SHIFT (3UL)
#define CLKRST_HSIO_SYS_RESET_CONTROL_CRSTB_FRCVAL_MASK (0x4UL)
#define CLKRST_HSIO_SYS_RESET_CONTROL_CRSTB_FRCVAL_SHIFT (2UL)
#define CLKRST_HSIO_SYS_RESET_CONTROL_HRESETN_FRC_MASK (0x2UL)
#define CLKRST_HSIO_SYS_RESET_CONTROL_HRESETN_FRC_SHIFT (1UL)
#define CLKRST_HSIO_SYS_RESET_CONTROL_HRESETN_FRCVAL_MASK (0x1UL)
#define CLKRST_HSIO_SYS_RESET_CONTROL_HRESETN_FRCVAL_SHIFT (0UL)




typedef uint32_t CLKRST_LSP_SYS_RESET_CONTROL_TYPE;
#define CLKRST_LSP_SYS_RESET_CONTROL_RSTB_FRC_MASK (0x8UL)
#define CLKRST_LSP_SYS_RESET_CONTROL_RSTB_FRC_SHIFT (3UL)
#define CLKRST_LSP_SYS_RESET_CONTROL_RSTB_FRCVAL_MASK (0x4UL)
#define CLKRST_LSP_SYS_RESET_CONTROL_RSTB_FRCVAL_SHIFT (2UL)
#define CLKRST_LSP_SYS_RESET_CONTROL_HRESETN_FRC_MASK (0x2UL)
#define CLKRST_LSP_SYS_RESET_CONTROL_HRESETN_FRC_SHIFT (1UL)
#define CLKRST_LSP_SYS_RESET_CONTROL_HRESETN_FRCVAL_MASK (0x1UL)
#define CLKRST_LSP_SYS_RESET_CONTROL_HRESETN_FRCVAL_SHIFT (0UL)




typedef uint32_t CLKRST_MAIN_NOC_RESET_CONTROL_TYPE;
#define CLKRST_MAIN_NOC_RESET_CONTROL_RSTN_FRC_MASK (0x2UL)
#define CLKRST_MAIN_NOC_RESET_CONTROL_RSTN_FRC_SHIFT (1UL)
#define CLKRST_MAIN_NOC_RESET_CONTROL_RSTN_FRCVAL_MASK (0x1UL)
#define CLKRST_MAIN_NOC_RESET_CONTROL_RSTN_FRCVAL_SHIFT (0UL)




typedef uint32_t CLKRST_Q8_TOP_RESET_CONTROL_TYPE;
#define CLKRST_Q8_TOP_RESET_CONTROL_APBSLAVE_RSTB_3_FRC_MASK (0x80000000UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_APBSLAVE_RSTB_3_FRC_SHIFT (31UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_APBSLAVE_RSTB_3_FRCVAL_MASK (0x40000000UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_APBSLAVE_RSTB_3_FRCVAL_SHIFT (30UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_APBSLAVE_RSTB_2_FRC_MASK (0x20000000UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_APBSLAVE_RSTB_2_FRC_SHIFT (29UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_APBSLAVE_RSTB_2_FRCVAL_MASK (0x10000000UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_APBSLAVE_RSTB_2_FRCVAL_SHIFT (28UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_APBSLAVE_RSTB_1_FRC_MASK (0x8000000UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_APBSLAVE_RSTB_1_FRC_SHIFT (27UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_APBSLAVE_RSTB_1_FRCVAL_MASK (0x4000000UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_APBSLAVE_RSTB_1_FRCVAL_SHIFT (26UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_APBSLAVE_RSTB_0_FRC_MASK (0x2000000UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_APBSLAVE_RSTB_0_FRC_SHIFT (25UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_APBSLAVE_RSTB_0_FRCVAL_MASK (0x1000000UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_APBSLAVE_RSTB_0_FRCVAL_SHIFT (24UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_CRSTB_3_FRC_MASK (0x800000UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_CRSTB_3_FRC_SHIFT (23UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_CRSTB_3_FRCVAL_MASK (0x400000UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_CRSTB_3_FRCVAL_SHIFT (22UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_CRSTB_2_FRC_MASK (0x200000UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_CRSTB_2_FRC_SHIFT (21UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_CRSTB_2_FRCVAL_MASK (0x100000UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_CRSTB_2_FRCVAL_SHIFT (20UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_CRSTB_1_FRC_MASK (0x80000UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_CRSTB_1_FRC_SHIFT (19UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_CRSTB_1_FRCVAL_MASK (0x40000UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_CRSTB_1_FRCVAL_SHIFT (18UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_CRSTB_0_FRC_MASK (0x20000UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_CRSTB_0_FRC_SHIFT (17UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_CRSTB_0_FRCVAL_MASK (0x10000UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_CRSTB_0_FRCVAL_SHIFT (16UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_PRESETN_3_FRC_MASK (0x8000UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_PRESETN_3_FRC_SHIFT (15UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_PRESETN_3_FRCVAL_MASK (0x4000UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_PRESETN_3_FRCVAL_SHIFT (14UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_PRESETN_2_FRC_MASK (0x2000UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_PRESETN_2_FRC_SHIFT (13UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_PRESETN_2_FRCVAL_MASK (0x1000UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_PRESETN_2_FRCVAL_SHIFT (12UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_PRESETN_1_FRC_MASK (0x800UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_PRESETN_1_FRC_SHIFT (11UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_PRESETN_1_FRCVAL_MASK (0x400UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_PRESETN_1_FRCVAL_SHIFT (10UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_PRESETN_0_FRC_MASK (0x200UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_PRESETN_0_FRC_SHIFT (9UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_PRESETN_0_FRCVAL_MASK (0x100UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_PRESETN_0_FRCVAL_SHIFT (8UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_HRESETN_FRC_MASK (0x2UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_HRESETN_FRC_SHIFT (1UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_HRESETN_FRCVAL_MASK (0x1UL)
#define CLKRST_Q8_TOP_RESET_CONTROL_HRESETN_FRCVAL_SHIFT (0UL)




typedef uint32_t CLKRST_DLTRC_TYPE;
#define CLKRST_DLTRC_DDR_LLC_TOP_SDC_200CLK_RESETN_FRC_MASK (0x20UL)
#define CLKRST_DLTRC_DDR_LLC_TOP_SDC_200CLK_RESETN_FRC_SHIFT (5UL)
#define CLKRST_DLTRC_DDR_LLC_TOP_SDC_200CLK_RESETN_FRCVAL_MASK (0x10UL)
#define CLKRST_DLTRC_DDR_LLC_TOP_SDC_200CLK_RESETN_FRCVAL_SHIFT (4UL)
#define CLKRST_DLTRC_DDR_LLC_TOP_CRSTB_FRC_MASK (0x8UL)
#define CLKRST_DLTRC_DDR_LLC_TOP_CRSTB_FRC_SHIFT (3UL)
#define CLKRST_DLTRC_DDR_LLC_TOP_CRSTB_FRCVAL_MASK (0x4UL)
#define CLKRST_DLTRC_DDR_LLC_TOP_CRSTB_FRCVAL_SHIFT (2UL)
#define CLKRST_DLTRC_DDR_LLC_TOP_HRESETN_FRC_MASK (0x2UL)
#define CLKRST_DLTRC_DDR_LLC_TOP_HRESETN_FRC_SHIFT (1UL)
#define CLKRST_DLTRC_DDR_LLC_TOP_HRESETN_FRCVAL_MASK (0x1UL)
#define CLKRST_DLTRC_DDR_LLC_TOP_HRESETN_FRCVAL_SHIFT (0UL)




typedef uint32_t CLKRST_RIGEL_HSADC_REFCLK_CTRL_TYPE;
#define CLKRST_RIGEL_HSADC_REFCLK_CTRL_REF_OUTEN_MASK (0x80UL)
#define CLKRST_RIGEL_HSADC_REFCLK_CTRL_REF_OUTEN_SHIFT (7UL)
#define CLKRST_RIGEL_HSADC_REFCLK_CTRL_RESERVED_2_MASK (0xcUL)
#define CLKRST_RIGEL_HSADC_REFCLK_CTRL_RESERVED_2_SHIFT (2UL)
#define CLKRST_RIGEL_HSADC_REFCLK_CTRL_RESERVED_0_MASK (0x3UL)
#define CLKRST_RIGEL_HSADC_REFCLK_CTRL_RESERVED_0_SHIFT (0UL)




typedef volatile struct sCLKRST_RDBType {
    CLKRST_RIGEL_TOP_CLK_CTRL_TYPE rigel_top_clk_ctrl; /* OFFSET: 0x0 */
    CLKRST_DMA330_CLK_CTRL_TYPE dma330_clk_ctrl; /* OFFSET: 0x4 */
    CLKRST_ACQ_TOP_RESET_CONTROL_TYPE acq_top_reset_control; /* OFFSET: 0x8 */
    CLKRST_A55PRC_TYPE a55_proc_reset_control; /* OFFSET: 0xc */
    CLKRST_CDSRC_TYPE cpu_dma_sys_reset_control; /* OFFSET: 0x10 */
    CLKRST_DEBUG_SYS_RESET_CONTROL_TYPE debug_sys_reset_control; /* OFFSET: 0x14 */
    CLKRST_GP_SRAM_RESET_CONTROL_TYPE gp_sram_reset_control; /* OFFSET: 0x18 */
    CLKRST_HSIO_SYS_RESET_CONTROL_TYPE hsio_sys_reset_control; /* OFFSET: 0x1c */
    uint32_t reserved_0; /* OFFSET: 0x20 */
    CLKRST_LSP_SYS_RESET_CONTROL_TYPE lsp_sys_reset_control; /* OFFSET: 0x24 */
    CLKRST_MAIN_NOC_RESET_CONTROL_TYPE main_noc_reset_control; /* OFFSET: 0x28 */
    CLKRST_Q8_TOP_RESET_CONTROL_TYPE q8_top_reset_control; /* OFFSET: 0x2c */
    CLKRST_DLTRC_TYPE ddr_llc_top_reset_control; /* OFFSET: 0x30 */
    uint32_t reserved_1; /* OFFSET: 0x34 */
    CLKRST_RIGEL_HSADC_REFCLK_CTRL_TYPE rigel_hsadc_refclk_control; /* OFFSET: 0x38 */
    uint32_t reserved_2; /* OFFSET: 0x3c */
} CLKRST_RDBType;


#define RIG_CLKNRST_BASE                (0xE0240600UL)



#define CLKRST_MAX_HW_ID                (1UL)

#endif /* CLKRST_RDB_H */
