/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file cpu_rdb.h
    @brief RDB File for CPU

    @version BCM89580_A0_20230125_RDB
*/

#ifndef CPU_RDB_H
#define CPU_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t CPU_MCU_ID_TYPE;
#define CPU_MCU_ID_MASK (0xffUL)
#define CPU_MCU_ID_SHIFT (0UL)




typedef uint32_t CPU_DCACHE_ERR_TYPE;
#define CPU_DCACHE_ERR_DCERR_MASK (0x3fffff0UL)
#define CPU_DCACHE_ERR_DCERR_SHIFT (4UL)
#define CPU_DCACHE_ERR_DCDET_MASK (0xfUL)
#define CPU_DCACHE_ERR_DCDET_SHIFT (0UL)




typedef uint32_t CPU_ICACHE_ERR_TYPE;
#define CPU_ICACHE_ERR_ICERR_MASK (0x3fffff0UL)
#define CPU_ICACHE_ERR_ICERR_SHIFT (4UL)
#define CPU_ICACHE_ERR_ICDET_MASK (0xfUL)
#define CPU_ICACHE_ERR_ICDET_SHIFT (0UL)




typedef uint32_t CPU_ID_CACHE_SEC_CNT_TYPE;
#define CPU_ID_CACHE_SEC_CNT_R2CLR_MASK (0xfUL)
#define CPU_ID_CACHE_SEC_CNT_R2CLR_SHIFT (0UL)




typedef uint32_t CPU_MEMCTL_TYPE;
#define CPU_MEMCTL_ITCM_INIT_EN1_MASK (0x8000000UL)
#define CPU_MEMCTL_ITCM_INIT_EN1_SHIFT (27UL)
#define CPU_MEMCTL_ITCM_INIT_CHK_EN1_MASK (0x4000000UL)
#define CPU_MEMCTL_ITCM_INIT_CHK_EN1_SHIFT (26UL)
#define CPU_MEMCTL_DTCM_INIT_EN1_MASK (0x2000000UL)
#define CPU_MEMCTL_DTCM_INIT_EN1_SHIFT (25UL)
#define CPU_MEMCTL_DTCM_INIT_CHK_EN1_MASK (0x1000000UL)
#define CPU_MEMCTL_DTCM_INIT_CHK_EN1_SHIFT (24UL)
#define CPU_MEMCTL_ITCM_TM_MASK (0x7f0000UL)
#define CPU_MEMCTL_ITCM_TM_SHIFT (16UL)
#define CPU_MEMCTL_DTCM_INIT_EN0_MASK (0x8000UL)
#define CPU_MEMCTL_DTCM_INIT_EN0_SHIFT (15UL)
#define CPU_MEMCTL_DTCM1_TM_MASK (0x7f00UL)
#define CPU_MEMCTL_DTCM1_TM_SHIFT (8UL)
#define CPU_MEMCTL_DTCM_INIT_CHK_EN0_MASK (0x80UL)
#define CPU_MEMCTL_DTCM_INIT_CHK_EN0_SHIFT (7UL)
#define CPU_MEMCTL_DTCM0_TM_MASK (0x7fUL)
#define CPU_MEMCTL_DTCM0_TM_SHIFT (0UL)




typedef uint32_t CPU_DBG_SCRATCH_TYPE;
#define CPU_DBG_SCRATCH_MASK (0xffffffffUL)
#define CPU_DBG_SCRATCH_SHIFT (0UL)




typedef uint32_t CPU_INITVTR_4_UTILITY_TYPE;
#define CPU_INITVTR_4_UTILITY_MCU_INITVTOR_MASK (0xffffff80UL)
#define CPU_INITVTR_4_UTILITY_MCU_INITVTOR_SHIFT (7UL)




typedef uint32_t CPU_MISC_CTL_TYPE;
#define CPU_MISC_CTL_TSTAMP_START_MASK (0x80000000UL)
#define CPU_MISC_CTL_TSTAMP_START_SHIFT (31UL)
#define CPU_MISC_CTL_TSTAMP_STOP_MASK (0x40000000UL)
#define CPU_MISC_CTL_TSTAMP_STOP_SHIFT (30UL)
#define CPU_MISC_CTL_U_MCU_EN_MASK (0x20000000UL)
#define CPU_MISC_CTL_U_MCU_EN_SHIFT (29UL)
#define CPU_MISC_CTL_U_MCU_WAIT_MASK (0x10000000UL)
#define CPU_MISC_CTL_U_MCU_WAIT_SHIFT (28UL)
#define CPU_MISC_CTL_HRESP_EN_MASK (0x8000000UL)
#define CPU_MISC_CTL_HRESP_EN_SHIFT (27UL)
#define CPU_MISC_CTL_TRACESWO2GPIO_MASK (0x20000UL)
#define CPU_MISC_CTL_TRACESWO2GPIO_SHIFT (17UL)
#define CPU_MISC_CTL_TRACESWO2JTAG_MASK (0x10000UL)
#define CPU_MISC_CTL_TRACESWO2JTAG_SHIFT (16UL)
#define CPU_MISC_CTL_TIMEOUT_EN_MASK (0x1000UL)
#define CPU_MISC_CTL_TIMEOUT_EN_SHIFT (12UL)
#define CPU_MISC_CTL_TIMEOUT_CFG_MASK (0xf00UL)
#define CPU_MISC_CTL_TIMEOUT_CFG_SHIFT (8UL)
#define CPU_MISC_CTL_GICT_ALLOW_NS_MASK (0x80UL)
#define CPU_MISC_CTL_GICT_ALLOW_NS_SHIFT (7UL)
#define CPU_MISC_CTL_GICP_ALLOW_NS_MASK (0x40UL)
#define CPU_MISC_CTL_GICP_ALLOW_NS_SHIFT (6UL)
#define CPU_MISC_CTL_DBGEN_MASK (0x20UL)
#define CPU_MISC_CTL_DBGEN_SHIFT (5UL)
#define CPU_MISC_CTL_NIDEN_MASK (0x10UL)
#define CPU_MISC_CTL_NIDEN_SHIFT (4UL)
#define CPU_MISC_CTL_UTILITY_MODE_MASK (0x8UL)
#define CPU_MISC_CTL_UTILITY_MODE_SHIFT (3UL)
#define CPU_MISC_CTL_CPU_CLKEN_OVR_MASK (0x4UL)
#define CPU_MISC_CTL_CPU_CLKEN_OVR_SHIFT (2UL)
#define CPU_MISC_CTL_ROM_CLKEN_OVR_MASK (0x2UL)
#define CPU_MISC_CTL_ROM_CLKEN_OVR_SHIFT (1UL)
#define CPU_MISC_CTL_ATB_CLKEN_OVR_MASK (0x1UL)
#define CPU_MISC_CTL_ATB_CLKEN_OVR_SHIFT (0UL)




typedef uint32_t CPU_BOOT_CTYPE_TYPE;
#define CPU_BOOT_CTYPE_MANAGER_NS_MASK (0x2UL)
#define CPU_BOOT_CTYPE_MANAGER_NS_SHIFT (1UL)
#define CPU_BOOT_CTYPE_FROM_PC_MASK (0x1UL)
#define CPU_BOOT_CTYPE_FROM_PC_SHIFT (0UL)




typedef uint32_t CPU_BOOT_ADDR_CTYPE_TYPE;
#define CPU_BOOT_ADDR_CTYPE_MASK (0xffffffffUL)
#define CPU_BOOT_ADDR_CTYPE_SHIFT (0UL)




typedef uint32_t CPU_BOOT_IRQ_NS_CTYPE_TYPE;
#define CPU_BOOT_IRQ_NS_CTYPE_MASK (0xffffffffUL)
#define CPU_BOOT_IRQ_NS_CTYPE_SHIFT (0UL)




typedef uint32_t CPU_BOOT_PERIPH_NS_CTYPE_TYPE;
#define CPU_BOOT_PERIPH_NS_CTYPE_MASK (0xffffffffUL)
#define CPU_BOOT_PERIPH_NS_CTYPE_SHIFT (0UL)




typedef uint32_t CPU_DMA_SHIM0_CTYPE_TYPE;
#define CPU_DMA_SHIM0_CTYPE_RG_DMA330_SHIM_PROCID_VAL_CH3_MASK (0xf8000000UL)
#define CPU_DMA_SHIM0_CTYPE_RG_DMA330_SHIM_PROCID_VAL_CH3_SHIFT (27UL)
#define CPU_DMA_SHIM0_CTYPE_RG_DMA330_SHIM_PPROT_VAL_CH3_MASK (0x7000000UL)
#define CPU_DMA_SHIM0_CTYPE_RG_DMA330_SHIM_PPROT_VAL_CH3_SHIFT (24UL)
#define CPU_DMA_SHIM0_CTYPE_RG_DMA330_SHIM_PROCID_VAL_CH2_MASK (0xf80000UL)
#define CPU_DMA_SHIM0_CTYPE_RG_DMA330_SHIM_PROCID_VAL_CH2_SHIFT (19UL)
#define CPU_DMA_SHIM0_CTYPE_RG_DMA330_SHIM_PPROT_VAL_CH2_MASK (0x70000UL)
#define CPU_DMA_SHIM0_CTYPE_RG_DMA330_SHIM_PPROT_VAL_CH2_SHIFT (16UL)
#define CPU_DMA_SHIM0_CTYPE_RG_DMA330_SHIM_PROCID_VAL_CH1_MASK (0xf800UL)
#define CPU_DMA_SHIM0_CTYPE_RG_DMA330_SHIM_PROCID_VAL_CH1_SHIFT (11UL)
#define CPU_DMA_SHIM0_CTYPE_RG_DMA330_SHIM_PPROT_VAL_CH1_MASK (0x700UL)
#define CPU_DMA_SHIM0_CTYPE_RG_DMA330_SHIM_PPROT_VAL_CH1_SHIFT (8UL)
#define CPU_DMA_SHIM0_CTYPE_RG_DMA330_SHIM_PROCID_VAL_CH0_MASK (0xf8UL)
#define CPU_DMA_SHIM0_CTYPE_RG_DMA330_SHIM_PROCID_VAL_CH0_SHIFT (3UL)
#define CPU_DMA_SHIM0_CTYPE_RG_DMA330_SHIM_PPROT_VAL_CH0_MASK (0x7UL)
#define CPU_DMA_SHIM0_CTYPE_RG_DMA330_SHIM_PPROT_VAL_CH0_SHIFT (0UL)




typedef uint32_t CPU_DMA_SHIM1_CTYPE_TYPE;
#define CPU_DMA_SHIM1_CTYPE_RG_DMA330_SHIM_PROCID_VAL_CH7_MASK (0xf8000000UL)
#define CPU_DMA_SHIM1_CTYPE_RG_DMA330_SHIM_PROCID_VAL_CH7_SHIFT (27UL)
#define CPU_DMA_SHIM1_CTYPE_RG_DMA330_SHIM_PPROT_VAL_CH7_MASK (0x7000000UL)
#define CPU_DMA_SHIM1_CTYPE_RG_DMA330_SHIM_PPROT_VAL_CH7_SHIFT (24UL)
#define CPU_DMA_SHIM1_CTYPE_RG_DMA330_SHIM_PROCID_VAL_CH6_MASK (0xf80000UL)
#define CPU_DMA_SHIM1_CTYPE_RG_DMA330_SHIM_PROCID_VAL_CH6_SHIFT (19UL)
#define CPU_DMA_SHIM1_CTYPE_RG_DMA330_SHIM_PPROT_VAL_CH6_MASK (0x70000UL)
#define CPU_DMA_SHIM1_CTYPE_RG_DMA330_SHIM_PPROT_VAL_CH6_SHIFT (16UL)
#define CPU_DMA_SHIM1_CTYPE_RG_DMA330_SHIM_PROCID_VAL_CH5_MASK (0xf800UL)
#define CPU_DMA_SHIM1_CTYPE_RG_DMA330_SHIM_PROCID_VAL_CH5_SHIFT (11UL)
#define CPU_DMA_SHIM1_CTYPE_RG_DMA330_SHIM_PPROT_VAL_CH5_MASK (0x700UL)
#define CPU_DMA_SHIM1_CTYPE_RG_DMA330_SHIM_PPROT_VAL_CH5_SHIFT (8UL)
#define CPU_DMA_SHIM1_CTYPE_RG_DMA330_SHIM_PROCID_VAL_CH4_MASK (0xf8UL)
#define CPU_DMA_SHIM1_CTYPE_RG_DMA330_SHIM_PROCID_VAL_CH4_SHIFT (3UL)
#define CPU_DMA_SHIM1_CTYPE_RG_DMA330_SHIM_PPROT_VAL_CH4_MASK (0x7UL)
#define CPU_DMA_SHIM1_CTYPE_RG_DMA330_SHIM_PPROT_VAL_CH4_SHIFT (0UL)




typedef uint32_t CPU_DMA_SHIM2_CTYPE_TYPE;
#define CPU_DMA_SHIM2_CTYPE_RG_DMA330_SHIM_LOAD_EN_MASK (0x80000000UL)
#define CPU_DMA_SHIM2_CTYPE_RG_DMA330_SHIM_LOAD_EN_SHIFT (31UL)
#define CPU_DMA_SHIM2_CTYPE_RG_DMA330_SHIM_PROCID_VAL_MNGR_MASK (0xf80UL)
#define CPU_DMA_SHIM2_CTYPE_RG_DMA330_SHIM_PROCID_VAL_MNGR_SHIFT (7UL)
#define CPU_DMA_SHIM2_CTYPE_RG_DMA330_SHIM_PPROT_VAL_MNGR_MASK (0x70UL)
#define CPU_DMA_SHIM2_CTYPE_RG_DMA330_SHIM_PPROT_VAL_MNGR_SHIFT (4UL)
#define CPU_DMA_SHIM2_CTYPE_RG_DMA330_SHIM_PROCID_SEL_MASK (0xcUL)
#define CPU_DMA_SHIM2_CTYPE_RG_DMA330_SHIM_PROCID_SEL_SHIFT (2UL)
#define CPU_DMA_SHIM2_CTYPE_RG_DMA330_SHIM_PPROT_SEL_MASK (0x3UL)
#define CPU_DMA_SHIM2_CTYPE_RG_DMA330_SHIM_PPROT_SEL_SHIFT (0UL)




typedef volatile struct sCPU_RDBType {
    CPU_MCU_ID_TYPE mcu_cluster_id; /* OFFSET: 0x0 */
    CPU_DCACHE_ERR_TYPE dcache_err; /* OFFSET: 0x4 */
    CPU_ICACHE_ERR_TYPE icache_err; /* OFFSET: 0x8 */
    CPU_ID_CACHE_SEC_CNT_TYPE id_cache_sec_cnt; /* OFFSET: 0xc */
    CPU_MEMCTL_TYPE memctl; /* OFFSET: 0x10 */
    CPU_DBG_SCRATCH_TYPE dbg_scratch; /* OFFSET: 0x14 */
    CPU_INITVTR_4_UTILITY_TYPE u_initvtor; /* OFFSET: 0x18 */
    CPU_MISC_CTL_TYPE misc_ctl; /* OFFSET: 0x1c */
    CPU_BOOT_CTYPE_TYPE dma330_boot_ctrl; /* OFFSET: 0x20 */
    CPU_BOOT_ADDR_CTYPE_TYPE dma330_boot_addr; /* OFFSET: 0x24 */
    CPU_BOOT_IRQ_NS_CTYPE_TYPE dma330_boot_sec_ctrl0; /* OFFSET: 0x28 */
    CPU_BOOT_PERIPH_NS_CTYPE_TYPE dma330_boot_sec_ctrl1; /* OFFSET: 0x2c */
    CPU_DMA_SHIM0_CTYPE_TYPE dma330_shim0_ctrl; /* OFFSET: 0x30 */
    CPU_DMA_SHIM1_CTYPE_TYPE dma330_shim1_ctrl; /* OFFSET: 0x34 */
    CPU_DMA_SHIM2_CTYPE_TYPE dma330_shim2_ctrl; /* OFFSET: 0x38 */
} CPU_RDBType;


#define MCU_BASE                        (0xE1000000UL)



#define CPU_MAX_HW_ID                   (1UL)

#endif /* CPU_RDB_H */
