/*****************************************************************************
 Copyright 2024 Broadcom.  All rights reserved.
 Broadcom Proprietary and Confidential
******************************************************************************/
/**
    @file syspll_rdb.h
    @brief RDB File for SYSPLL

    @version BCM89580_A0_20230125_RDB
*/

#ifndef SYSPLL_RDB_H
#define SYSPLL_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t SYSPLL_PLLSTATUS_TYPE;
#define SYSPLL_PLLSTATUS_STAT_OUT_MASK (0xfff0UL)
#define SYSPLL_PLLSTATUS_STAT_OUT_SHIFT (4UL)
#define SYSPLL_PLLSTATUS_FB_LOCK_MASK (0x8UL)
#define SYSPLL_PLLSTATUS_FB_LOCK_SHIFT (3UL)
#define SYSPLL_PLLSTATUS_POST_HELD_MASK (0x4UL)
#define SYSPLL_PLLSTATUS_POST_HELD_SHIFT (2UL)
#define SYSPLL_PLLSTATUS_PLL_LOCK_LOST_MASK (0x2UL)
#define SYSPLL_PLLSTATUS_PLL_LOCK_LOST_SHIFT (1UL)
#define SYSPLL_PLLSTATUS_PLL_LOCK_MASK (0x1UL)
#define SYSPLL_PLLSTATUS_PLL_LOCK_SHIFT (0UL)




typedef uint32_t SYSPLL_VCO_FREQ_CNFG_SET0_TYPE;
#define SYSPLL_VCO_FREQ_CNFG_SET0_NDIV_P_MASK (0x3ff0000UL)
#define SYSPLL_VCO_FREQ_CNFG_SET0_NDIV_P_SHIFT (16UL)
#define SYSPLL_VCO_FREQ_CNFG_SET0_NDIV_INT_MASK (0x3ff0UL)
#define SYSPLL_VCO_FREQ_CNFG_SET0_NDIV_INT_SHIFT (4UL)
#define SYSPLL_VCO_FREQ_CNFG_SET0_PDIV_MASK (0xfUL)
#define SYSPLL_VCO_FREQ_CNFG_SET0_PDIV_SHIFT (0UL)




typedef uint32_t SYSPLL_VCO_FREQ_CNFG_SET1_TYPE;
#define SYSPLL_VCO_FREQ_CNFG_SET1_FB_EN_MASK (0x1000000UL)
#define SYSPLL_VCO_FREQ_CNFG_SET1_FB_EN_SHIFT (24UL)
#define SYSPLL_VCO_FREQ_CNFG_SET1_I_32K_REFCLOCK_SEL_MASK (0x800000UL)
#define SYSPLL_VCO_FREQ_CNFG_SET1_I_32K_REFCLOCK_SEL_SHIFT (23UL)
#define SYSPLL_VCO_FREQ_CNFG_SET1_RANGE_SELECTION_MASK (0x400000UL)
#define SYSPLL_VCO_FREQ_CNFG_SET1_RANGE_SELECTION_SHIFT (22UL)
#define SYSPLL_VCO_FREQ_CNFG_SET1_FREFEFF_INFO_MASK (0x3f0000UL)
#define SYSPLL_VCO_FREQ_CNFG_SET1_FREFEFF_INFO_SHIFT (16UL)
#define SYSPLL_VCO_FREQ_CNFG_SET1_NDIV_FRAC_MODE_SEL_MASK (0x1000UL)
#define SYSPLL_VCO_FREQ_CNFG_SET1_NDIV_FRAC_MODE_SEL_SHIFT (12UL)
#define SYSPLL_VCO_FREQ_CNFG_SET1_NDIV_Q_MASK (0x3ffUL)
#define SYSPLL_VCO_FREQ_CNFG_SET1_NDIV_Q_SHIFT (0UL)




typedef uint32_t SYSPLL_POST_DIVIDERS_TYPE;
#define SYSPLL_POST_DIVIDERS_AUX_POST_HOLD_MASK (0x400000UL)
#define SYSPLL_POST_DIVIDERS_AUX_POST_HOLD_SHIFT (22UL)
#define SYSPLL_POST_DIVIDERS_AUX_POST_DIFFCMOS_EN_MASK (0x200000UL)
#define SYSPLL_POST_DIVIDERS_AUX_POST_DIFFCMOS_EN_SHIFT (21UL)
#define SYSPLL_POST_DIVIDERS_AUX_POST_ENABLEB_MASK (0x100000UL)
#define SYSPLL_POST_DIVIDERS_AUX_POST_ENABLEB_SHIFT (20UL)
#define SYSPLL_POST_DIVIDERS_AUX_POST_BYP_EN_MASK (0x40000UL)
#define SYSPLL_POST_DIVIDERS_AUX_POST_BYP_EN_SHIFT (18UL)
#define SYSPLL_POST_DIVIDERS_AUX_POST_MDIV_MASK (0x30000UL)
#define SYSPLL_POST_DIVIDERS_AUX_POST_MDIV_SHIFT (16UL)
#define SYSPLL_POST_DIVIDERS_POST_RST_HOLD_SEL_MASK (0x6UL)
#define SYSPLL_POST_DIVIDERS_POST_RST_HOLD_SEL_SHIFT (1UL)
#define SYSPLL_POST_DIVIDERS_POST_HOLD_ALL_MASK (0x1UL)
#define SYSPLL_POST_DIVIDERS_POST_HOLD_ALL_SHIFT (0UL)




typedef uint32_t SYSPLL_POST_DIVIDERS_6CH_SET0_TYPE;
#define SYSPLL_POST_DIVIDERS_6CH_SET0_CH_HOLD_MASK (0x3f000000UL)
#define SYSPLL_POST_DIVIDERS_6CH_SET0_CH_HOLD_SHIFT (24UL)
#define SYSPLL_POST_DIVIDERS_6CH_SET0_CH_ENABLEB_MASK (0x3f0000UL)
#define SYSPLL_POST_DIVIDERS_6CH_SET0_CH_ENABLEB_SHIFT (16UL)
#define SYSPLL_POST_DIVIDERS_6CH_SET0_CH_MDEL_MASK (0x3f00UL)
#define SYSPLL_POST_DIVIDERS_6CH_SET0_CH_MDEL_SHIFT (8UL)
#define SYSPLL_POST_DIVIDERS_6CH_SET0_CH_BYP_EN_MASK (0x3fUL)
#define SYSPLL_POST_DIVIDERS_6CH_SET0_CH_BYP_EN_SHIFT (0UL)




typedef uint32_t SYSPLL_POST_DIVIDERS_6CH_SET1_TYPE;
#define SYSPLL_POST_DIVIDERS_6CH_SET1_CH1_MDIV_MASK (0x1ff0000UL)
#define SYSPLL_POST_DIVIDERS_6CH_SET1_CH1_MDIV_SHIFT (16UL)
#define SYSPLL_POST_DIVIDERS_6CH_SET1_CH0_MDIV_MASK (0x1ffUL)
#define SYSPLL_POST_DIVIDERS_6CH_SET1_CH0_MDIV_SHIFT (0UL)




typedef uint32_t SYSPLL_POST_DIVIDERS_6CH_SET2_TYPE;
#define SYSPLL_POST_DIVIDERS_6CH_SET2_CH3_MDIV_MASK (0x1ff0000UL)
#define SYSPLL_POST_DIVIDERS_6CH_SET2_CH3_MDIV_SHIFT (16UL)
#define SYSPLL_POST_DIVIDERS_6CH_SET2_CH2_MDIV_MASK (0x1ffUL)
#define SYSPLL_POST_DIVIDERS_6CH_SET2_CH2_MDIV_SHIFT (0UL)




typedef uint32_t SYSPLL_POST_DIVIDERS_6CH_SET3_TYPE;
#define SYSPLL_POST_DIVIDERS_6CH_SET3_CH5_MDIV_MASK (0x1ff0000UL)
#define SYSPLL_POST_DIVIDERS_6CH_SET3_CH5_MDIV_SHIFT (16UL)
#define SYSPLL_POST_DIVIDERS_6CH_SET3_CH4_MDIV_MASK (0x1ffUL)
#define SYSPLL_POST_DIVIDERS_6CH_SET3_CH4_MDIV_SHIFT (0UL)




typedef uint32_t SYSPLL_LOOP_OP_PGRM_TYPE;
#define SYSPLL_LOOP_OP_PGRM_NDIV_RELOCK_MASK (0x100000UL)
#define SYSPLL_LOOP_OP_PGRM_NDIV_RELOCK_SHIFT (20UL)
#define SYSPLL_LOOP_OP_PGRM_FAST_LOCK_MASK (0x80000UL)
#define SYSPLL_LOOP_OP_PGRM_FAST_LOCK_SHIFT (19UL)
#define SYSPLL_LOOP_OP_PGRM_EXTRA_SETTLING_MASK (0x40000UL)
#define SYSPLL_LOOP_OP_PGRM_EXTRA_SETTLING_SHIFT (18UL)
#define SYSPLL_LOOP_OP_PGRM_DCO_BYPASS_EN_MASK (0x20000UL)
#define SYSPLL_LOOP_OP_PGRM_DCO_BYPASS_EN_SHIFT (17UL)
#define SYSPLL_LOOP_OP_PGRM_INIT_WITH_BYPASS_MASK (0x10000UL)
#define SYSPLL_LOOP_OP_PGRM_INIT_WITH_BYPASS_SHIFT (16UL)
#define SYSPLL_LOOP_OP_PGRM_DCO_BYPASS_MASK (0xfffUL)
#define SYSPLL_LOOP_OP_PGRM_DCO_BYPASS_SHIFT (0UL)




typedef uint32_t SYSPLL_ATE_CNTRL_AND_OUTPUT_TYPE;
#define SYSPLL_ATE_CNTRL_AND_OUTPUT_STAT_UPDATE_MASK (0x40UL)
#define SYSPLL_ATE_CNTRL_AND_OUTPUT_STAT_UPDATE_SHIFT (6UL)
#define SYSPLL_ATE_CNTRL_AND_OUTPUT_STAT_MODE_MASK (0x30UL)
#define SYSPLL_ATE_CNTRL_AND_OUTPUT_STAT_MODE_SHIFT (4UL)
#define SYSPLL_ATE_CNTRL_AND_OUTPUT_STAT_RESET_MASK (0x8UL)
#define SYSPLL_ATE_CNTRL_AND_OUTPUT_STAT_RESET_SHIFT (3UL)
#define SYSPLL_ATE_CNTRL_AND_OUTPUT_STAT_SELECT_MASK (0x7UL)
#define SYSPLL_ATE_CNTRL_AND_OUTPUT_STAT_SELECT_SHIFT (0UL)




typedef uint32_t SYSPLL_SPREAD_SPECTRUM_CNTRL_SET0_TYPE;
#define SYSPLL_SPREAD_SPECTRUM_CNTRL_SET0_SSC_DOWNSPREAD_MASK (0x800000UL)
#define SYSPLL_SPREAD_SPECTRUM_CNTRL_SET0_SSC_DOWNSPREAD_SHIFT (23UL)
#define SYSPLL_SPREAD_SPECTRUM_CNTRL_SET0_SSC_MODE_MASK (0x400000UL)
#define SYSPLL_SPREAD_SPECTRUM_CNTRL_SET0_SSC_MODE_SHIFT (22UL)
#define SYSPLL_SPREAD_SPECTRUM_CNTRL_SET0_SSC_LIMIT_25_4_MASK (0x3fffffUL)
#define SYSPLL_SPREAD_SPECTRUM_CNTRL_SET0_SSC_LIMIT_25_4_SHIFT (0UL)




typedef uint32_t SYSPLL_SPREAD_SPECTRUM_CNTRL_SET1_TYPE;
#define SYSPLL_SPREAD_SPECTRUM_CNTRL_SET1_SSC_STEP_MASK (0xffffUL)
#define SYSPLL_SPREAD_SPECTRUM_CNTRL_SET1_SSC_STEP_SHIFT (0UL)




typedef uint32_t SYSPLL_DYN_PARA_MANUAL_CONFIG_TYPE;
#define SYSPLL_DYN_PARA_MANUAL_CONFIG_PWM_RATE_MASK (0x7000UL)
#define SYSPLL_DYN_PARA_MANUAL_CONFIG_PWM_RATE_SHIFT (12UL)
#define SYSPLL_DYN_PARA_MANUAL_CONFIG_KP_MASK (0xf00UL)
#define SYSPLL_DYN_PARA_MANUAL_CONFIG_KP_SHIFT (8UL)
#define SYSPLL_DYN_PARA_MANUAL_CONFIG_KA_MASK (0xf0UL)
#define SYSPLL_DYN_PARA_MANUAL_CONFIG_KA_SHIFT (4UL)
#define SYSPLL_DYN_PARA_MANUAL_CONFIG_VCO_FB_DIV2_MASK (0x8UL)
#define SYSPLL_DYN_PARA_MANUAL_CONFIG_VCO_FB_DIV2_SHIFT (3UL)
#define SYSPLL_DYN_PARA_MANUAL_CONFIG_KI_MASK (0x7UL)
#define SYSPLL_DYN_PARA_MANUAL_CONFIG_KI_SHIFT (0UL)




typedef uint32_t SYSPLL_BACKUP_AND_DEBUG_PINS_TYPE;
#define SYSPLL_BACKUP_AND_DEBUG_PINS_DISABLE_WDT_RESET_MASK (0x80000000UL)
#define SYSPLL_BACKUP_AND_DEBUG_PINS_DISABLE_WDT_RESET_SHIFT (31UL)
#define SYSPLL_BACKUP_AND_DEBUG_PINS_CTRL_DCPROBE_OUT_MASK (0x70000000UL)
#define SYSPLL_BACKUP_AND_DEBUG_PINS_CTRL_DCPROBE_OUT_SHIFT (28UL)
#define SYSPLL_BACKUP_AND_DEBUG_PINS_PROG_SMTH_ADD_SUB_MASK (0xc000000UL)
#define SYSPLL_BACKUP_AND_DEBUG_PINS_PROG_SMTH_ADD_SUB_SHIFT (26UL)
#define SYSPLL_BACKUP_AND_DEBUG_PINS_EXT_EXTRADIV_MASK (0x3000000UL)
#define SYSPLL_BACKUP_AND_DEBUG_PINS_EXT_EXTRADIV_SHIFT (24UL)
#define SYSPLL_BACKUP_AND_DEBUG_PINS_PROG_FBSLEW_CTRL_MASK (0xc00000UL)
#define SYSPLL_BACKUP_AND_DEBUG_PINS_PROG_FBSLEW_CTRL_SHIFT (22UL)
#define SYSPLL_BACKUP_AND_DEBUG_PINS_LOCK_PHASE_DETECTOR_MASK (0x300000UL)
#define SYSPLL_BACKUP_AND_DEBUG_PINS_LOCK_PHASE_DETECTOR_SHIFT (20UL)
#define SYSPLL_BACKUP_AND_DEBUG_PINS_DISABLE_SMOOTHER_MASK (0x80000UL)
#define SYSPLL_BACKUP_AND_DEBUG_PINS_DISABLE_SMOOTHER_SHIFT (19UL)
#define SYSPLL_BACKUP_AND_DEBUG_PINS_AUTOCONFIGON_NDIVUPDATE_MASK (0x40000UL)
#define SYSPLL_BACKUP_AND_DEBUG_PINS_AUTOCONFIGON_NDIVUPDATE_SHIFT (18UL)
#define SYSPLL_BACKUP_AND_DEBUG_PINS_LOCK_COUNTS_CTRL_MASK (0x30000UL)
#define SYSPLL_BACKUP_AND_DEBUG_PINS_LOCK_COUNTS_CTRL_SHIFT (16UL)
#define SYSPLL_BACKUP_AND_DEBUG_PINS_DIV2DIV4_ON_MASK (0x8000UL)
#define SYSPLL_BACKUP_AND_DEBUG_PINS_DIV2DIV4_ON_SHIFT (15UL)
#define SYSPLL_BACKUP_AND_DEBUG_PINS_POR_ENABLE_MASK (0x4000UL)
#define SYSPLL_BACKUP_AND_DEBUG_PINS_POR_ENABLE_SHIFT (14UL)
#define SYSPLL_BACKUP_AND_DEBUG_PINS_LDO_POSTDIV_MASK (0x3000UL)
#define SYSPLL_BACKUP_AND_DEBUG_PINS_LDO_POSTDIV_SHIFT (12UL)
#define SYSPLL_BACKUP_AND_DEBUG_PINS_UPSHIFTDCO_MASK (0x800UL)
#define SYSPLL_BACKUP_AND_DEBUG_PINS_UPSHIFTDCO_SHIFT (11UL)
#define SYSPLL_BACKUP_AND_DEBUG_PINS_DOWNSHIFTDCO_MASK (0x400UL)
#define SYSPLL_BACKUP_AND_DEBUG_PINS_DOWNSHIFTDCO_SHIFT (10UL)
#define SYSPLL_BACKUP_AND_DEBUG_PINS_LDO_DCORE_MASK (0x300UL)
#define SYSPLL_BACKUP_AND_DEBUG_PINS_LDO_DCORE_SHIFT (8UL)
#define SYSPLL_BACKUP_AND_DEBUG_PINS_DISABLE_EXTRA_POSTDIVISION_MASK (0x80UL)
#define SYSPLL_BACKUP_AND_DEBUG_PINS_DISABLE_EXTRA_POSTDIVISION_SHIFT (7UL)
#define SYSPLL_BACKUP_AND_DEBUG_PINS_LOCK_LOST_CLR_MASK (0x40UL)
#define SYSPLL_BACKUP_AND_DEBUG_PINS_LOCK_LOST_CLR_SHIFT (6UL)
#define SYSPLL_BACKUP_AND_DEBUG_PINS_LDO_ANALOG_MASK (0x30UL)
#define SYSPLL_BACKUP_AND_DEBUG_PINS_LDO_ANALOG_SHIFT (4UL)
#define SYSPLL_BACKUP_AND_DEBUG_PINS_LDO_STB_MASK (0x7UL)
#define SYSPLL_BACKUP_AND_DEBUG_PINS_LDO_STB_SHIFT (0UL)




typedef uint32_t SYSPLL_RESERVED_DEBUG_PINS_TYPE;




typedef volatile struct sSYSPLL_RDBType {
    SYSPLL_PLLSTATUS_TYPE pll_status; /* OFFSET: 0x0 */
    SYSPLL_VCO_FREQ_CNFG_SET0_TYPE vco_freq_cnfg_set0; /* OFFSET: 0x4 */
    SYSPLL_VCO_FREQ_CNFG_SET1_TYPE vco_freq_cnfg_set1; /* OFFSET: 0x8 */
    SYSPLL_POST_DIVIDERS_TYPE post_dividers; /* OFFSET: 0xc */
    SYSPLL_POST_DIVIDERS_6CH_SET0_TYPE aux_post_dividers_6ch_set0; /* OFFSET: 0x10 */
    SYSPLL_POST_DIVIDERS_6CH_SET1_TYPE aux_post_dividers_6ch_set1; /* OFFSET: 0x14 */
    SYSPLL_POST_DIVIDERS_6CH_SET2_TYPE aux_post_dividers_6ch_set2; /* OFFSET: 0x18 */
    SYSPLL_POST_DIVIDERS_6CH_SET3_TYPE aux_post_dividers_6ch_set3; /* OFFSET: 0x1c */
    SYSPLL_LOOP_OP_PGRM_TYPE loop_op_pgrm; /* OFFSET: 0x20 */
    SYSPLL_ATE_CNTRL_AND_OUTPUT_TYPE ate_cntrl_and_output; /* OFFSET: 0x24 */
    SYSPLL_SPREAD_SPECTRUM_CNTRL_SET0_TYPE spread_spectrum_cntrl_set0; /* OFFSET: 0x28 */
    SYSPLL_SPREAD_SPECTRUM_CNTRL_SET1_TYPE spread_spectrum_cntrl_set1; /* OFFSET: 0x2c */
    SYSPLL_DYN_PARA_MANUAL_CONFIG_TYPE dyn_para_manual_config; /* OFFSET: 0x30 */
    SYSPLL_BACKUP_AND_DEBUG_PINS_TYPE backup_and_debug_pins; /* OFFSET: 0x34 */
    SYSPLL_RESERVED_DEBUG_PINS_TYPE reserved_debug_pins; /* OFFSET: 0x38 */
} SYSPLL_RDBType;


#define SYSPLL_BASE                     (0xE0262100UL)



#define SYSPLL_MAX_HW_ID                (1UL)

#endif /* SYSPLL_RDB_H */
