/*****************************************************************************
  Copyright 2024 Broadcom Limited.  All rights reserved.
  Broadcom Proprietary and Confidential
******************************************************************************/
/**
    @file pl08x_rdb.h
    @brief RDB File for PL08X

    @version BCM89580_A0_20230125_RDB
*/

#ifndef PL08X_RDB_H
#define PL08X_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t PL08X_DMACINTSTATUS_TYPE;
#define PL08X_DMACINTSTATUS_INTSTATUS_MASK (0xffUL)
#define PL08X_DMACINTSTATUS_INTSTATUS_SHIFT (0UL)




typedef uint32_t PL08X_DMACINTTCSTATUS_TYPE;
#define PL08X_DMACINTTCSTATUS_INTTCSTATUS_MASK (0xffUL)
#define PL08X_DMACINTTCSTATUS_INTTCSTATUS_SHIFT (0UL)




typedef uint32_t PL08X_DMACINTTCCLEAR_TYPE;
#define PL08X_DMACINTTCCLEAR_INTTCCLEAR_MASK (0xffUL)
#define PL08X_DMACINTTCCLEAR_INTTCCLEAR_SHIFT (0UL)




typedef uint32_t PL08X_DMACINTERRORSTATUS_TYPE;
#define PL08X_DMACINTERRORSTATUS_INTERRORSTATUS_MASK (0xffUL)
#define PL08X_DMACINTERRORSTATUS_INTERRORSTATUS_SHIFT (0UL)




typedef uint32_t PL08X_DMACINTERRCLR_TYPE;
#define PL08X_DMACINTERRCLR_INTERRCLR_MASK (0xffUL)
#define PL08X_DMACINTERRCLR_INTERRCLR_SHIFT (0UL)




typedef uint32_t PL08X_DMACRAWINTTCSTATUS_TYPE;
#define PL08X_DMACRAWINTTCSTATUS_RAWINTTCSTATUS_MASK (0xffUL)
#define PL08X_DMACRAWINTTCSTATUS_RAWINTTCSTATUS_SHIFT (0UL)




typedef uint32_t PL08X_DMACRAWINTERRORSTATUS_TYPE;
#define PL08X_DMACRAWINTERRORSTATUS_RAWINTERRORSTATUS_MASK (0xffUL)
#define PL08X_DMACRAWINTERRORSTATUS_RAWINTERRORSTATUS_SHIFT (0UL)




typedef uint32_t PL08X_DMACENBLDCHNS_TYPE;
#define PL08X_DMACENBLDCHNS_ENABLEDCHANNELS_MASK (0xffUL)
#define PL08X_DMACENBLDCHNS_ENABLEDCHANNELS_SHIFT (0UL)




typedef uint32_t PL08X_DMACSOFTBREQ_TYPE;
#define PL08X_DMACSOFTBREQ_SOFTBREQ_MASK (0xffffUL)
#define PL08X_DMACSOFTBREQ_SOFTBREQ_SHIFT (0UL)




typedef uint32_t PL08X_DMACSOFTSREQ_TYPE;
#define PL08X_DMACSOFTSREQ_SOFTSREQ_MASK (0xffffUL)
#define PL08X_DMACSOFTSREQ_SOFTSREQ_SHIFT (0UL)




typedef uint32_t PL08X_DMACSOFTLBREQ_TYPE;
#define PL08X_DMACSOFTLBREQ_SOFTLSREQ_MASK (0xffffUL)
#define PL08X_DMACSOFTLBREQ_SOFTLSREQ_SHIFT (0UL)




typedef uint32_t PL08X_DMACSOFTLSREQ_TYPE;
#define PL08X_DMACSOFTLSREQ_SOFTLBREQ_MASK (0xffffUL)
#define PL08X_DMACSOFTLSREQ_SOFTLBREQ_SHIFT (0UL)




typedef uint32_t PL08X_DMACCONFIGURATION_TYPE;
#define PL08X_DMACCONFIGURATION_M2_MASK (0x4UL)
#define PL08X_DMACCONFIGURATION_M2_SHIFT (2UL)
#define PL08X_DMACCONFIGURATION_M1_MASK (0x2UL)
#define PL08X_DMACCONFIGURATION_M1_SHIFT (1UL)
#define PL08X_DMACCONFIGURATION_E_MASK (0x1UL)
#define PL08X_DMACCONFIGURATION_E_SHIFT (0UL)




typedef uint32_t PL08X_DMACSYNC_TYPE;
#define PL08X_DMACSYNC_MASK (0xffffUL)
#define PL08X_DMACSYNC_SHIFT (0UL)




typedef uint8_t PL08X_RESERVED_TYPE;




typedef uint32_t PL08X_DMACCNSRCADDR_TYPE;
#define PL08X_DMACCNSRCADDR_SRCADDR_MASK (0xffffffffUL)
#define PL08X_DMACCNSRCADDR_SRCADDR_SHIFT (0UL)




typedef uint32_t PL08X_DMACCNDESTADDR_TYPE;
#define PL08X_DMACCNDESTADDR_DESTADDR_MASK (0xffffffffUL)
#define PL08X_DMACCNDESTADDR_DESTADDR_SHIFT (0UL)




typedef uint32_t PL08X_DMACCNLLI_TYPE;
#define PL08X_DMACCNLLI_LLI_MASK (0xfffffffcUL)
#define PL08X_DMACCNLLI_LLI_SHIFT (2UL)
#define PL08X_DMACCNLLI_LM_MASK (0x1UL)
#define PL08X_DMACCNLLI_LM_SHIFT (0UL)




typedef uint32_t PL08X_DMACCNCONTROL_TYPE;
#define PL08X_DMACCNCONTROL_I_MASK (0x80000000UL)
#define PL08X_DMACCNCONTROL_I_SHIFT (31UL)
#define PL08X_DMACCNCONTROL_PORT_MASK (0x70000000UL)
#define PL08X_DMACCNCONTROL_PORT_SHIFT (28UL)
#define PL08X_DMACCNCONTROL_DI_MASK (0x8000000UL)
#define PL08X_DMACCNCONTROL_DI_SHIFT (27UL)
#define PL08X_DMACCNCONTROL_SI_MASK (0x4000000UL)
#define PL08X_DMACCNCONTROL_SI_SHIFT (26UL)
#define PL08X_DMACCNCONTROL_D_MASK (0x2000000UL)
#define PL08X_DMACCNCONTROL_D_SHIFT (25UL)
#define PL08X_DMACCNCONTROL_S_MASK (0x1000000UL)
#define PL08X_DMACCNCONTROL_S_SHIFT (24UL)
#define PL08X_DMACCNCONTROL_DWIDTH_MASK (0xe00000UL)
#define PL08X_DMACCNCONTROL_DWIDTH_SHIFT (21UL)
#define PL08X_DMACCNCONTROL_SWIDTH_MASK (0x1c0000UL)
#define PL08X_DMACCNCONTROL_SWIDTH_SHIFT (18UL)
#define PL08X_DMACCNCONTROL_DBSIZE_MASK (0x38000UL)
#define PL08X_DMACCNCONTROL_DBSIZE_SHIFT (15UL)
#define PL08X_DMACCNCONTROL_SBSIZE_MASK (0x7000UL)
#define PL08X_DMACCNCONTROL_SBSIZE_SHIFT (12UL)
#define PL08X_DMACCNCONTROL_TRANSFERSIZE_MASK (0xfffUL)
#define PL08X_DMACCNCONTROL_TRANSFERSIZE_SHIFT (0UL)




typedef uint32_t PL08X_DMACCNCONFIGURATION_TYPE;
#define PL08X_DMACCNCONFIGURATION_H_MASK (0x40000UL)
#define PL08X_DMACCNCONFIGURATION_H_SHIFT (18UL)
#define PL08X_DMACCNCONFIGURATION_A_MASK (0x20000UL)
#define PL08X_DMACCNCONFIGURATION_A_SHIFT (17UL)
#define PL08X_DMACCNCONFIGURATION_L_MASK (0x10000UL)
#define PL08X_DMACCNCONFIGURATION_L_SHIFT (16UL)
#define PL08X_DMACCNCONFIGURATION_ITC_MASK (0x8000UL)
#define PL08X_DMACCNCONFIGURATION_ITC_SHIFT (15UL)
#define PL08X_DMACCNCONFIGURATION_IE_MASK (0x4000UL)
#define PL08X_DMACCNCONFIGURATION_IE_SHIFT (14UL)
#define PL08X_DMACCNCONFIGURATION_FLOWCNTRL_MASK (0x3800UL)
#define PL08X_DMACCNCONFIGURATION_FLOWCNTRL_SHIFT (11UL)
#define PL08X_DMACCNCONFIGURATION_DESTPERIPHERAL_MASK (0x3c0UL)
#define PL08X_DMACCNCONFIGURATION_DESTPERIPHERAL_SHIFT (6UL)
#define PL08X_DMACCNCONFIGURATION_SRCPERIPHERAL_MASK (0x1eUL)
#define PL08X_DMACCNCONFIGURATION_SRCPERIPHERAL_SHIFT (1UL)
#define PL08X_DMACCNCONFIGURATION_E_MASK (0x1UL)
#define PL08X_DMACCNCONFIGURATION_E_SHIFT (0UL)




typedef uint32_t PL08X_DMACITCR_TYPE;
#define PL08X_DMACITCR_T_MASK (0x1UL)
#define PL08X_DMACITCR_T_SHIFT (0UL)




typedef uint32_t PL08X_DMACITOP1_TYPE;
#define PL08X_DMACITOP1_DMACCLR_MASK (0xffffUL)
#define PL08X_DMACITOP1_DMACCLR_SHIFT (0UL)




typedef uint32_t PL08X_DMACITOP2_TYPE;
#define PL08X_DMACITOP2_DMACTC_MASK (0xffffUL)
#define PL08X_DMACITOP2_DMACTC_SHIFT (0UL)




typedef uint32_t PL08X_DMACITOP3_TYPE;
#define PL08X_DMACITOP3_E_MASK (0x2UL)
#define PL08X_DMACITOP3_E_SHIFT (1UL)
#define PL08X_DMACITOP3_TC_MASK (0x1UL)
#define PL08X_DMACITOP3_TC_SHIFT (0UL)




typedef uint32_t PL08X_DMACPERIPHID0_TYPE;
#define PL08X_DMACPERIPHID0_PARTNUMBER0_MASK (0xffUL)
#define PL08X_DMACPERIPHID0_PARTNUMBER0_SHIFT (0UL)




typedef uint32_t PL08X_DMACPERIPHID1_TYPE;
#define PL08X_DMACPERIPHID1_DESIGNER0_MASK (0xf0UL)
#define PL08X_DMACPERIPHID1_DESIGNER0_SHIFT (4UL)
#define PL08X_DMACPERIPHID1_PARTNUMBER1_MASK (0xfUL)
#define PL08X_DMACPERIPHID1_PARTNUMBER1_SHIFT (0UL)




typedef uint32_t PL08X_DMACPERIPHID2_TYPE;
#define PL08X_DMACPERIPHID2_REVISION_MASK (0xf0UL)
#define PL08X_DMACPERIPHID2_REVISION_SHIFT (4UL)
#define PL08X_DMACPERIPHID2_DESIGNER1_MASK (0xfUL)
#define PL08X_DMACPERIPHID2_DESIGNER1_SHIFT (0UL)




typedef uint32_t PL08X_DMACPERIPHID3_TYPE;
#define PL08X_DMACPERIPHID3_CONFIGURATION_1_MASK (0x80UL)
#define PL08X_DMACPERIPHID3_CONFIGURATION_1_SHIFT (7UL)
#define PL08X_DMACPERIPHID3_CONFIGURATION_2_MASK (0x70UL)
#define PL08X_DMACPERIPHID3_CONFIGURATION_2_SHIFT (4UL)
#define PL08X_DMACPERIPHID3_CONFIGURATION_3_MASK (0x8UL)
#define PL08X_DMACPERIPHID3_CONFIGURATION_3_SHIFT (3UL)
#define PL08X_DMACPERIPHID3_CONFIGURATION_4_MASK (0x7UL)
#define PL08X_DMACPERIPHID3_CONFIGURATION_4_SHIFT (0UL)




typedef uint32_t PL08X_DMACPCELLID0_TYPE;
#define PL08X_DMACPCELLID0_MASK (0xffUL)
#define PL08X_DMACPCELLID0_SHIFT (0UL)




typedef uint32_t PL08X_DMACPCELLID1_TYPE;
#define PL08X_DMACPCELLID1_MASK (0xffUL)
#define PL08X_DMACPCELLID1_SHIFT (0UL)




typedef uint32_t PL08X_DMACPCELLID2_TYPE;
#define PL08X_DMACPCELLID2_MASK (0xffUL)
#define PL08X_DMACPCELLID2_SHIFT (0UL)




typedef uint32_t PL08X_DMACPCELLID3_TYPE;
#define PL08X_DMACPCELLID3_MASK (0xffUL)
#define PL08X_DMACPCELLID3_SHIFT (0UL)


typedef volatile struct sPL08X_CHAN_RDBType {
    PL08X_DMACCNSRCADDR_TYPE dmacc0srcaddr; /* OFFSET: 0x100 */
    PL08X_DMACCNDESTADDR_TYPE dmacc0destaddr; /* OFFSET: 0x104 */
    PL08X_DMACCNLLI_TYPE dmacc0lli; /* OFFSET: 0x108 */
    PL08X_DMACCNCONTROL_TYPE dmacc0control; /* OFFSET: 0x10c */
    PL08X_DMACCNCONFIGURATION_TYPE dmacc0configuration; /* OFFSET: 0x110 */
    PL08X_RESERVED_TYPE rsvd1[12]; /* OFFSET: 0x114 */
} PL08X_CHAN_RDBType;


#define PL08X_CHAN_SIZE  (8UL)


typedef volatile struct sPL08X_RDBType {
    PL08X_DMACINTSTATUS_TYPE dmacintstatus; /* OFFSET: 0x0 */
    PL08X_DMACINTTCSTATUS_TYPE dmacinttcstatus; /* OFFSET: 0x4 */
    PL08X_DMACINTTCCLEAR_TYPE dmacinttcclear; /* OFFSET: 0x8 */
    PL08X_DMACINTERRORSTATUS_TYPE dmacinterrorstatus; /* OFFSET: 0xc */
    PL08X_DMACINTERRCLR_TYPE dmacinterrclr; /* OFFSET: 0x10 */
    PL08X_DMACRAWINTTCSTATUS_TYPE dmacrawinttcstatus; /* OFFSET: 0x14 */
    PL08X_DMACRAWINTERRORSTATUS_TYPE dmacrawinterrorstatus; /* OFFSET: 0x18 */
    PL08X_DMACENBLDCHNS_TYPE dmacenbldchns; /* OFFSET: 0x1c */
    PL08X_DMACSOFTBREQ_TYPE dmacsoftbreq; /* OFFSET: 0x20 */
    PL08X_DMACSOFTSREQ_TYPE dmacsoftsreq; /* OFFSET: 0x24 */
    PL08X_DMACSOFTLBREQ_TYPE dmacsoftlbreq; /* OFFSET: 0x28 */
    PL08X_DMACSOFTLSREQ_TYPE dmacsoftlsreq; /* OFFSET: 0x2c */
    PL08X_DMACCONFIGURATION_TYPE dmacconfiguration; /* OFFSET: 0x30 */
    PL08X_DMACSYNC_TYPE dmacsync; /* OFFSET: 0x34 */
    PL08X_RESERVED_TYPE rsvd0[200]; /* OFFSET: 0x38 */
    PL08X_CHAN_RDBType chan[PL08X_CHAN_SIZE]; /* OFFSET: 0x100 */
    PL08X_RESERVED_TYPE rsvd8[768]; /* OFFSET: 0x200 */
    PL08X_DMACITCR_TYPE dmacitcr; /* OFFSET: 0x500 */
    PL08X_DMACITOP1_TYPE dmacitop1; /* OFFSET: 0x504 */
    PL08X_DMACITOP2_TYPE dmacitop2; /* OFFSET: 0x508 */
    PL08X_DMACITOP3_TYPE dmacitop3; /* OFFSET: 0x50c */
    PL08X_RESERVED_TYPE rsvd9[2768]; /* OFFSET: 0x510 */
    PL08X_DMACPERIPHID0_TYPE dmacperiphid0; /* OFFSET: 0xfe0 */
    PL08X_DMACPERIPHID1_TYPE dmacperiphid1; /* OFFSET: 0xfe4 */
    PL08X_DMACPERIPHID2_TYPE dmacperiphid2; /* OFFSET: 0xfe8 */
    PL08X_DMACPERIPHID3_TYPE dmacperiphid3; /* OFFSET: 0xfec */
    PL08X_DMACPCELLID0_TYPE dmacpcellid0; /* OFFSET: 0xff0 */
    PL08X_DMACPCELLID1_TYPE dmacpcellid1; /* OFFSET: 0xff4 */
    PL08X_DMACPCELLID2_TYPE dmacpcellid2; /* OFFSET: 0xff8 */
    PL08X_DMACPCELLID3_TYPE dmacpcellid3; /* OFFSET: 0xffc */
} PL08X_RDBType;


#define PL08X_BASE                      (0xE0260000UL)

#define PL08X_CHAN_RDBTYPE_OFFSET       (0xE0260100UL)



#define PL08X_MAX_HW_ID                 (2UL)


#define DMA_PL081_BASE                  (PL08X_BASE)


#define DMA_PL081_2_BASE                (0xE0261000UL)



#define PL08X_DMACC0CONFIGURATION_C0HALT_MASK  (0x40000UL)


#define PL08X_DMACC0CONFIGURATION_C0HALT_SHIFT  (18UL)


#define PL08X_DMACC0CONFIGURATION_C0ACTIVE_MASK  (0x20000UL)


#define PL08X_DMACC0CONFIGURATION_C0ACTIVE_SHIFT  (17UL)


#define PL08X_DMACC0CONFIGURATION_C0LOCK_MASK  (0x10000UL)


#define PL08X_DMACC0CONFIGURATION_C0LOCK_SHIFT  (16UL)


#define PL08X_DMACC0CONFIGURATION_C0INTTCMASK_MASK  (0x8000UL)


#define PL08X_DMACC0CONFIGURATION_C0INTTCMASK_SHIFT  (15UL)


#define PL08X_DMACC0CONFIGURATION_C0INTERRORMASK_MASK  (0x4000UL)


#define PL08X_DMACC0CONFIGURATION_C0INTERRORMASK_SHIFT  (14UL)


#define PL08X_DMACC0CONFIGURATION_C0FLOWCNTRL_MASK  (0x3800UL)


#define PL08X_DMACC0CONFIGURATION_C0FLOWCNTRL_SHIFT  (11UL)


#define PL08X_DMACC0CONFIGURATION_C0DESTPERIPHERAL_MASK  (0x3c0UL)


#define PL08X_DMACC0CONFIGURATION_C0DESTPERIPHERAL_SHIFT  (6UL)


#define PL08X_DMACC0CONFIGURATION_C0SRCPERIPHERAL_MASK  (0x1eUL)


#define PL08X_DMACC0CONFIGURATION_C0SRCPERIPHERAL_SHIFT  (1UL)


#define PL08X_DMACC0CONFIGURATION_C0ENABLE_MASK  (0x1UL)


#define PL08X_DMACC0CONFIGURATION_C0ENABLE_SHIFT  (0UL)


#define PL08X_DMACC0CONTROL_C0I_MASK    (0x80000000UL)


#define PL08X_DMACC0CONTROL_C0I_SHIFT   (31UL)


#define PL08X_DMACC0CONTROL_C0PROT_MASK  (0x70000000UL)


#define PL08X_DMACC0CONTROL_C0PROT_SHIFT  (28UL)


#define PL08X_DMACC0CONTROL_C0DESTINC_MASK  (0x8000000UL)


#define PL08X_DMACC0CONTROL_C0DESTINC_SHIFT  (27UL)


#define PL08X_DMACC0CONTROL_C0SRCINC_MASK  (0x4000000UL)


#define PL08X_DMACC0CONTROL_C0SRCINC_SHIFT  (26UL)


#define PL08X_DMACC0CONTROL_C0DESTWIDTH_MASK  (0xe00000UL)


#define PL08X_DMACC0CONTROL_C0DESTWIDTH_SHIFT  (21UL)


#define PL08X_DMACC0CONTROL_C0SRCWIDTH_MASK  (0x1c0000UL)


#define PL08X_DMACC0CONTROL_C0SRCWIDTH_SHIFT  (18UL)


#define PL08X_DMACC0CONTROL_C0DESTBURSTSIZE_MASK  (0x38000UL)


#define PL08X_DMACC0CONTROL_C0DESTBURSTSIZE_SHIFT  (15UL)


#define PL08X_DMACC0CONTROL_C0SRCBURSTSIZE_MASK  (0x7000UL)


#define PL08X_DMACC0CONTROL_C0SRCBURSTSIZE_SHIFT  (12UL)


#define PL08X_DMACC0CONTROL_C0TRANSFERSIZE_MASK  (0xfffUL)


#define PL08X_DMACC0CONTROL_C0TRANSFERSIZE_SHIFT  (0UL)

#endif /* PL08X_RDB_H */
