/*****************************************************************************
 Copyright 2025 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file cfg_aer_rdb.h
    @brief RDB File for CFG_AER

    @version BCM89580_A0_20230125_RDB
*/

#ifndef CFG_AER_RDB_H
#define CFG_AER_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t CFG_AER_ADV_ERR_CAP_TYPE;
#define CFG_AER_ADV_ERR_CAP_NEXT_MASK (0xfff00000UL)
#define CFG_AER_ADV_ERR_CAP_NEXT_SHIFT (20UL)
#define CFG_AER_ADV_ERR_CAP_VER_MASK (0xf0000UL)
#define CFG_AER_ADV_ERR_CAP_VER_SHIFT (16UL)
#define CFG_AER_ADV_ERR_CAP_ADV_ERR_CAP_ID_MASK (0xffffUL)
#define CFG_AER_ADV_ERR_CAP_ADV_ERR_CAP_ID_SHIFT (0UL)




typedef uint32_t CFG_AER_UC_ERR_STATUS_TYPE;
#define CFG_AER_UC_ERR_STATUS_UIES_MASK (0x400000UL)
#define CFG_AER_UC_ERR_STATUS_UIES_SHIFT (22UL)
#define CFG_AER_UC_ERR_STATUS_URES_MASK (0x100000UL)
#define CFG_AER_UC_ERR_STATUS_URES_SHIFT (20UL)
#define CFG_AER_UC_ERR_STATUS_ECRCS_MASK (0x80000UL)
#define CFG_AER_UC_ERR_STATUS_ECRCS_SHIFT (19UL)
#define CFG_AER_UC_ERR_STATUS_MTLPS_MASK (0x40000UL)
#define CFG_AER_UC_ERR_STATUS_MTLPS_SHIFT (18UL)
#define CFG_AER_UC_ERR_STATUS_ROS_MASK (0x20000UL)
#define CFG_AER_UC_ERR_STATUS_ROS_SHIFT (17UL)
#define CFG_AER_UC_ERR_STATUS_UCS_MASK (0x10000UL)
#define CFG_AER_UC_ERR_STATUS_UCS_SHIFT (16UL)
#define CFG_AER_UC_ERR_STATUS_CAS_MASK (0x8000UL)
#define CFG_AER_UC_ERR_STATUS_CAS_SHIFT (15UL)
#define CFG_AER_UC_ERR_STATUS_CTS_MASK (0x4000UL)
#define CFG_AER_UC_ERR_STATUS_CTS_SHIFT (14UL)
#define CFG_AER_UC_ERR_STATUS_FCPES_MASK (0x2000UL)
#define CFG_AER_UC_ERR_STATUS_FCPES_SHIFT (13UL)
#define CFG_AER_UC_ERR_STATUS_PTLPS_MASK (0x1000UL)
#define CFG_AER_UC_ERR_STATUS_PTLPS_SHIFT (12UL)
#define CFG_AER_UC_ERR_STATUS_DLPES_MASK (0x10UL)
#define CFG_AER_UC_ERR_STATUS_DLPES_SHIFT (4UL)
#define CFG_AER_UC_ERR_STATUS_RESERVED0_MASK (0xfUL)
#define CFG_AER_UC_ERR_STATUS_RESERVED0_SHIFT (0UL)
#define CFG_AER_UC_ERR_STATUS_RESERVED1_MASK (0xfe0UL)
#define CFG_AER_UC_ERR_STATUS_RESERVED1_SHIFT (5UL)
#define CFG_AER_UC_ERR_STATUS_RESERVED2_MASK (0x200000UL)
#define CFG_AER_UC_ERR_STATUS_RESERVED2_SHIFT (21UL)
#define CFG_AER_UC_ERR_STATUS_RESERVED3_MASK (0xff800000UL)
#define CFG_AER_UC_ERR_STATUS_RESERVED3_SHIFT (23UL)




typedef uint32_t CFG_AER_UCORR_ERR_MASK_TYPE;
#define CFG_AER_UCORR_ERR_MASK_UIEM_MASK (0x400000UL)
#define CFG_AER_UCORR_ERR_MASK_UIEM_SHIFT (22UL)
#define CFG_AER_UCORR_ERR_MASK_UREM_MASK (0x100000UL)
#define CFG_AER_UCORR_ERR_MASK_UREM_SHIFT (20UL)
#define CFG_AER_UCORR_ERR_MASK_ECRCEM_MASK (0x80000UL)
#define CFG_AER_UCORR_ERR_MASK_ECRCEM_SHIFT (19UL)
#define CFG_AER_UCORR_ERR_MASK_MTLPM_MASK (0x40000UL)
#define CFG_AER_UCORR_ERR_MASK_MTLPM_SHIFT (18UL)
#define CFG_AER_UCORR_ERR_MASK_ROM_MASK (0x20000UL)
#define CFG_AER_UCORR_ERR_MASK_ROM_SHIFT (17UL)
#define CFG_AER_UCORR_ERR_MASK_UCM_MASK (0x10000UL)
#define CFG_AER_UCORR_ERR_MASK_UCM_SHIFT (16UL)
#define CFG_AER_UCORR_ERR_MASK_CAM_MASK (0x8000UL)
#define CFG_AER_UCORR_ERR_MASK_CAM_SHIFT (15UL)
#define CFG_AER_UCORR_ERR_MASK_CTM_MASK (0x4000UL)
#define CFG_AER_UCORR_ERR_MASK_CTM_SHIFT (14UL)
#define CFG_AER_UCORR_ERR_MASK_FCPEM_MASK (0x2000UL)
#define CFG_AER_UCORR_ERR_MASK_FCPEM_SHIFT (13UL)
#define CFG_AER_UCORR_ERR_MASK_PTLPM_MASK (0x1000UL)
#define CFG_AER_UCORR_ERR_MASK_PTLPM_SHIFT (12UL)
#define CFG_AER_UCORR_ERR_MASK_SDEM_MASK (0x20UL)
#define CFG_AER_UCORR_ERR_MASK_SDEM_SHIFT (5UL)
#define CFG_AER_UCORR_ERR_MASK_DLPEM_MASK (0x10UL)
#define CFG_AER_UCORR_ERR_MASK_DLPEM_SHIFT (4UL)
#define CFG_AER_UCORR_ERR_MASK_RESERVED0_MASK (0xfUL)
#define CFG_AER_UCORR_ERR_MASK_RESERVED0_SHIFT (0UL)
#define CFG_AER_UCORR_ERR_MASK_RESERVED1_MASK (0xfc0UL)
#define CFG_AER_UCORR_ERR_MASK_RESERVED1_SHIFT (6UL)
#define CFG_AER_UCORR_ERR_MASK_RESERVED2_MASK (0x200000UL)
#define CFG_AER_UCORR_ERR_MASK_RESERVED2_SHIFT (21UL)
#define CFG_AER_UCORR_ERR_MASK_RESERVED3_MASK (0xff800000UL)
#define CFG_AER_UCORR_ERR_MASK_RESERVED3_SHIFT (23UL)




typedef uint32_t CFG_AER_UCORR_ERR_SEVR_TYPE;
#define CFG_AER_UCORR_ERR_SEVR_UIES_MASK (0x400000UL)
#define CFG_AER_UCORR_ERR_SEVR_UIES_SHIFT (22UL)
#define CFG_AER_UCORR_ERR_SEVR_URES_MASK (0x100000UL)
#define CFG_AER_UCORR_ERR_SEVR_URES_SHIFT (20UL)
#define CFG_AER_UCORR_ERR_SEVR_ECRCES_MASK (0x80000UL)
#define CFG_AER_UCORR_ERR_SEVR_ECRCES_SHIFT (19UL)
#define CFG_AER_UCORR_ERR_SEVR_MTLPS_MASK (0x40000UL)
#define CFG_AER_UCORR_ERR_SEVR_MTLPS_SHIFT (18UL)
#define CFG_AER_UCORR_ERR_SEVR_ROS_MASK (0x20000UL)
#define CFG_AER_UCORR_ERR_SEVR_ROS_SHIFT (17UL)
#define CFG_AER_UCORR_ERR_SEVR_UCS_MASK (0x10000UL)
#define CFG_AER_UCORR_ERR_SEVR_UCS_SHIFT (16UL)
#define CFG_AER_UCORR_ERR_SEVR_CAS_MASK (0x8000UL)
#define CFG_AER_UCORR_ERR_SEVR_CAS_SHIFT (15UL)
#define CFG_AER_UCORR_ERR_SEVR_CTS_MASK (0x4000UL)
#define CFG_AER_UCORR_ERR_SEVR_CTS_SHIFT (14UL)
#define CFG_AER_UCORR_ERR_SEVR_FCPES_MASK (0x2000UL)
#define CFG_AER_UCORR_ERR_SEVR_FCPES_SHIFT (13UL)
#define CFG_AER_UCORR_ERR_SEVR_PTLPS_MASK (0x1000UL)
#define CFG_AER_UCORR_ERR_SEVR_PTLPS_SHIFT (12UL)
#define CFG_AER_UCORR_ERR_SEVR_SDES_MASK (0x20UL)
#define CFG_AER_UCORR_ERR_SEVR_SDES_SHIFT (5UL)
#define CFG_AER_UCORR_ERR_SEVR_DLPES_MASK (0x10UL)
#define CFG_AER_UCORR_ERR_SEVR_DLPES_SHIFT (4UL)
#define CFG_AER_UCORR_ERR_SEVR_RESERVED0_MASK (0xfUL)
#define CFG_AER_UCORR_ERR_SEVR_RESERVED0_SHIFT (0UL)
#define CFG_AER_UCORR_ERR_SEVR_RESERVED1_MASK (0xfc0UL)
#define CFG_AER_UCORR_ERR_SEVR_RESERVED1_SHIFT (6UL)
#define CFG_AER_UCORR_ERR_SEVR_RESERVED2_MASK (0x200000UL)
#define CFG_AER_UCORR_ERR_SEVR_RESERVED2_SHIFT (21UL)
#define CFG_AER_UCORR_ERR_SEVR_RESERVED3_MASK (0xff800000UL)
#define CFG_AER_UCORR_ERR_SEVR_RESERVED3_SHIFT (23UL)




typedef uint32_t CFG_AER_CORR_ERR_STATUS_TYPE;
#define CFG_AER_CORR_ERR_STATUS_ADVSRY_ERR_STATUS_MASK (0x2000UL)
#define CFG_AER_CORR_ERR_STATUS_ADVSRY_ERR_STATUS_SHIFT (13UL)
#define CFG_AER_CORR_ERR_STATUS_RPLAY_TMR_TO_STATUS_MASK (0x1000UL)
#define CFG_AER_CORR_ERR_STATUS_RPLAY_TMR_TO_STATUS_SHIFT (12UL)
#define CFG_AER_CORR_ERR_STATUS_RPLAY_NUM_RO_STATUS_MASK (0x100UL)
#define CFG_AER_CORR_ERR_STATUS_RPLAY_NUM_RO_STATUS_SHIFT (8UL)
#define CFG_AER_CORR_ERR_STATUS_BAD_DLLP_STATUS_MASK (0x80UL)
#define CFG_AER_CORR_ERR_STATUS_BAD_DLLP_STATUS_SHIFT (7UL)
#define CFG_AER_CORR_ERR_STATUS_BAD_TLP_STATUS_MASK (0x40UL)
#define CFG_AER_CORR_ERR_STATUS_BAD_TLP_STATUS_SHIFT (6UL)
#define CFG_AER_CORR_ERR_STATUS_RX_ERR_STATUS_MASK (0x1UL)
#define CFG_AER_CORR_ERR_STATUS_RX_ERR_STATUS_SHIFT (0UL)
#define CFG_AER_CORR_ERR_STATUS_RESERVED0_MASK (0x3eUL)
#define CFG_AER_CORR_ERR_STATUS_RESERVED0_SHIFT (1UL)
#define CFG_AER_CORR_ERR_STATUS_RESERVED1_MASK (0xe00UL)
#define CFG_AER_CORR_ERR_STATUS_RESERVED1_SHIFT (9UL)
#define CFG_AER_CORR_ERR_STATUS_RESERVED2_MASK (0xffffc000UL)
#define CFG_AER_CORR_ERR_STATUS_RESERVED2_SHIFT (14UL)




typedef uint32_t CFG_AER_CORR_ERR_MASK_TYPE;
#define CFG_AER_CORR_ERR_MASK_ANFM_MASK (0x2000UL)
#define CFG_AER_CORR_ERR_MASK_ANFM_SHIFT (13UL)
#define CFG_AER_CORR_ERR_MASK_RTTS_MASK (0x1000UL)
#define CFG_AER_CORR_ERR_MASK_RTTS_SHIFT (12UL)
#define CFG_AER_CORR_ERR_MASK_RNRS_MASK (0x100UL)
#define CFG_AER_CORR_ERR_MASK_RNRS_SHIFT (8UL)
#define CFG_AER_CORR_ERR_MASK_BDLLPS_MASK (0x80UL)
#define CFG_AER_CORR_ERR_MASK_BDLLPS_SHIFT (7UL)
#define CFG_AER_CORR_ERR_MASK_BTLPS_MASK (0x40UL)
#define CFG_AER_CORR_ERR_MASK_BTLPS_SHIFT (6UL)
#define CFG_AER_CORR_ERR_MASK_RES_MASK (0x1UL)
#define CFG_AER_CORR_ERR_MASK_RES_SHIFT (0UL)
#define CFG_AER_CORR_ERR_MASK_RESERVED0_MASK (0x3eUL)
#define CFG_AER_CORR_ERR_MASK_RESERVED0_SHIFT (1UL)
#define CFG_AER_CORR_ERR_MASK_RESERVED1_MASK (0xe00UL)
#define CFG_AER_CORR_ERR_MASK_RESERVED1_SHIFT (9UL)
#define CFG_AER_CORR_ERR_MASK_RESERVED2_MASK (0xffffc000UL)
#define CFG_AER_CORR_ERR_MASK_RESERVED2_SHIFT (14UL)




typedef uint32_t CFG_AER_ADV_ERR_CAP_CONTROL_TYPE;
#define CFG_AER_ADV_ERR_CAP_CONTROL_ECRCEN_MASK (0x100UL)
#define CFG_AER_ADV_ERR_CAP_CONTROL_ECRCEN_SHIFT (8UL)
#define CFG_AER_ADV_ERR_CAP_CONTROL_ECRCCAP_MASK (0x80UL)
#define CFG_AER_ADV_ERR_CAP_CONTROL_ECRCCAP_SHIFT (7UL)
#define CFG_AER_ADV_ERR_CAP_CONTROL_ECRCGEN_MASK (0x40UL)
#define CFG_AER_ADV_ERR_CAP_CONTROL_ECRCGEN_SHIFT (6UL)
#define CFG_AER_ADV_ERR_CAP_CONTROL_ECRCGCAP_MASK (0x20UL)
#define CFG_AER_ADV_ERR_CAP_CONTROL_ECRCGCAP_SHIFT (5UL)
#define CFG_AER_ADV_ERR_CAP_CONTROL_FIRST_UERR_PTR_MASK (0x1fUL)
#define CFG_AER_ADV_ERR_CAP_CONTROL_FIRST_UERR_PTR_SHIFT (0UL)
#define CFG_AER_ADV_ERR_CAP_CONTROL_RESERVED0_MASK (0xfffffe00UL)
#define CFG_AER_ADV_ERR_CAP_CONTROL_RESERVED0_SHIFT (9UL)




typedef uint32_t CFG_AER_HEADER_LOG1_TYPE;
#define CFG_AER_HEADER_LOG1_MASK (0xffffffffUL)
#define CFG_AER_HEADER_LOG1_SHIFT (0UL)




typedef uint32_t CFG_AER_HEADER_LOG2_TYPE;
#define CFG_AER_HEADER_LOG2_CONFIG_IND_ADDR_MASK (0xffffffffUL)
#define CFG_AER_HEADER_LOG2_CONFIG_IND_ADDR_SHIFT (0UL)




typedef uint32_t CFG_AER_HEADER_LOG3_TYPE;
#define CFG_AER_HEADER_LOG3_CONFIG_IND_DATA_MASK (0xffffffffUL)
#define CFG_AER_HEADER_LOG3_CONFIG_IND_DATA_SHIFT (0UL)




typedef uint32_t CFG_AER_HEADER_LOG4_TYPE;
#define CFG_AER_HEADER_LOG4_MASK (0xffffffffUL)
#define CFG_AER_HEADER_LOG4_SHIFT (0UL)




typedef uint32_t CFG_AER_ROOT_ERROR_COMMAND_TYPE;
#define CFG_AER_ROOT_ERROR_COMMAND_UNUSED_MASK (0xffffffffUL)
#define CFG_AER_ROOT_ERROR_COMMAND_UNUSED_SHIFT (0UL)




typedef uint32_t CFG_AER_ROOT_ERROR_STATUS_TYPE;
#define CFG_AER_ROOT_ERROR_STATUS_UNUSED_MASK (0xffffffffUL)
#define CFG_AER_ROOT_ERROR_STATUS_UNUSED_SHIFT (0UL)




typedef uint32_t CFG_AER_ROOT_ERR_ID_TYPE;
#define CFG_AER_ROOT_ERR_ID_UNUSED_MASK (0xffffffffUL)
#define CFG_AER_ROOT_ERR_ID_UNUSED_SHIFT (0UL)




typedef volatile struct sCFG_AER_RDBType {
    CFG_AER_ADV_ERR_CAP_TYPE adv_err_cap; /* OFFSET: 0x0 */
    CFG_AER_UC_ERR_STATUS_TYPE uc_err_status; /* OFFSET: 0x4 */
    CFG_AER_UCORR_ERR_MASK_TYPE ucorr_err_mask; /* OFFSET: 0x8 */
    CFG_AER_UCORR_ERR_SEVR_TYPE ucorr_err_sevr; /* OFFSET: 0xc */
    CFG_AER_CORR_ERR_STATUS_TYPE corr_err_status; /* OFFSET: 0x10 */
    CFG_AER_CORR_ERR_MASK_TYPE corr_err_mask; /* OFFSET: 0x14 */
    CFG_AER_ADV_ERR_CAP_CONTROL_TYPE adv_err_cap_control; /* OFFSET: 0x18 */
    CFG_AER_HEADER_LOG1_TYPE header_log1; /* OFFSET: 0x1c */
    CFG_AER_HEADER_LOG2_TYPE config_ind_addr; /* OFFSET: 0x20 */
    CFG_AER_HEADER_LOG3_TYPE config_ind_data; /* OFFSET: 0x24 */
    CFG_AER_HEADER_LOG4_TYPE header_log4; /* OFFSET: 0x28 */
    CFG_AER_ROOT_ERROR_COMMAND_TYPE root_error_command; /* OFFSET: 0x2c */
    CFG_AER_ROOT_ERROR_STATUS_TYPE root_error_status; /* OFFSET: 0x30 */
    CFG_AER_ROOT_ERR_ID_TYPE root_err_id; /* OFFSET: 0x34 */
} CFG_AER_RDBType;


#define CFG_AER0_BASE                   ((uintptr_t)(0xE02D2100UL))

#define CFG_AER1_BASE                   ((uintptr_t)(0xE02D2100UL))



#define CFG_AER_MAX_HW_ID               (2UL)

#endif /* CFG_AER_RDB_H */
