/*****************************************************************************
 Copyright 2025 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file cfg_priv1_rdb.h
    @brief RDB File for CFG_PRIV1

    @version BCM89580_A0_20230125_RDB
*/

#ifndef CFG_PRIV1_RDB_H
#define CFG_PRIV1_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t CFG_PRIV1_VPD_INTF_TYPE;
#define CFG_PRIV1_VPD_INTF_REQ_MASK (0x1UL)
#define CFG_PRIV1_VPD_INTF_REQ_SHIFT (0UL)
#define CFG_PRIV1_VPD_INTF_RESERVED0_MASK (0xfffffffeUL)
#define CFG_PRIV1_VPD_INTF_RESERVED0_SHIFT (1UL)




typedef uint32_t CFG_PRIV1_VPD_ADDR_FLAG_TYPE;
#define CFG_PRIV1_VPD_ADDR_FLAG_WR_MASK (0x80000000UL)
#define CFG_PRIV1_VPD_ADDR_FLAG_WR_SHIFT (31UL)
#define CFG_PRIV1_VPD_ADDR_FLAG_ADDRESS_MASK (0x7ffc0000UL)
#define CFG_PRIV1_VPD_ADDR_FLAG_ADDRESS_SHIFT (18UL)
#define CFG_PRIV1_VPD_ADDR_FLAG_RESERVED0_MASK (0x3ffffUL)
#define CFG_PRIV1_VPD_ADDR_FLAG_RESERVED0_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_VPD_DATA_TYPE;
#define CFG_PRIV1_VPD_DATA_MASK (0xffffffffUL)
#define CFG_PRIV1_VPD_DATA_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_ID_VAL1_TYPE;
#define CFG_PRIV1_ID_VAL1_VENDOR_ID_MASK (0xffff0000UL)
#define CFG_PRIV1_ID_VAL1_VENDOR_ID_SHIFT (16UL)
#define CFG_PRIV1_ID_VAL1_DEVICE_ID_MASK (0xffffUL)
#define CFG_PRIV1_ID_VAL1_DEVICE_ID_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_ID_VAL2_TYPE;
#define CFG_PRIV1_ID_VAL2_SUBSYSTEM_ID_MASK (0xffff0000UL)
#define CFG_PRIV1_ID_VAL2_SUBSYSTEM_ID_SHIFT (16UL)
#define CFG_PRIV1_ID_VAL2_SUBSYSTEM_VENDOR_ID_MASK (0xffffUL)
#define CFG_PRIV1_ID_VAL2_SUBSYSTEM_VENDOR_ID_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_ID_VAL3_TYPE;
#define CFG_PRIV1_ID_VAL3_REVISION_ID_MASK (0xff000000UL)
#define CFG_PRIV1_ID_VAL3_REVISION_ID_SHIFT (24UL)
#define CFG_PRIV1_ID_VAL3_CLASS_CODE_MASK (0xffffffUL)
#define CFG_PRIV1_ID_VAL3_CLASS_CODE_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_ID_VAL4_TYPE;
#define CFG_PRIV1_ID_VAL4_RESERVED3_MASK (0xffff0000UL)
#define CFG_PRIV1_ID_VAL4_RESERVED3_SHIFT (16UL)
#define CFG_PRIV1_ID_VAL4_MSI_ENABLE_MASK (0x8000UL)
#define CFG_PRIV1_ID_VAL4_MSI_ENABLE_SHIFT (15UL)
#define CFG_PRIV1_ID_VAL4_MULTI_MSG_CAP_MASK (0x7000UL)
#define CFG_PRIV1_ID_VAL4_MULTI_MSG_CAP_SHIFT (12UL)
#define CFG_PRIV1_ID_VAL4_MSI_LIMIT_MASK (0xe00UL)
#define CFG_PRIV1_ID_VAL4_MSI_LIMIT_SHIFT (9UL)
#define CFG_PRIV1_ID_VAL4_MSI_PV_MASK_CAPABLE_MASK (0x100UL)
#define CFG_PRIV1_ID_VAL4_MSI_PV_MASK_CAPABLE_SHIFT (8UL)
#define CFG_PRIV1_ID_VAL4_PM_DATA_SCALE_MASK (0xc0UL)
#define CFG_PRIV1_ID_VAL4_PM_DATA_SCALE_SHIFT (6UL)
#define CFG_PRIV1_ID_VAL4_CAP_ENA_MASK (0xfUL)
#define CFG_PRIV1_ID_VAL4_CAP_ENA_SHIFT (0UL)
#define CFG_PRIV1_ID_VAL4_RESERVED0_MASK (0x30UL)
#define CFG_PRIV1_ID_VAL4_RESERVED0_SHIFT (4UL)




typedef uint32_t CFG_PRIV1_ID_VAL5_TYPE;
#define CFG_PRIV1_ID_VAL5_RESERVED0_MASK (0xfffff800UL)
#define CFG_PRIV1_ID_VAL5_RESERVED0_SHIFT (11UL)
#define CFG_PRIV1_ID_VAL5_PME_IN_D3_COLD_MASK_MASK (0x400UL)
#define CFG_PRIV1_ID_VAL5_PME_IN_D3_COLD_MASK_SHIFT (10UL)
#define CFG_PRIV1_ID_VAL5_NO_SOFT_RESET_MASK (0x200UL)
#define CFG_PRIV1_ID_VAL5_NO_SOFT_RESET_SHIFT (9UL)
#define CFG_PRIV1_ID_VAL5_PM_VERSION_MASK (0x1c0UL)
#define CFG_PRIV1_ID_VAL5_PM_VERSION_SHIFT (6UL)
#define CFG_PRIV1_ID_VAL5_PME_IN_D3_HOT_MASK (0x20UL)
#define CFG_PRIV1_ID_VAL5_PME_IN_D3_HOT_SHIFT (5UL)
#define CFG_PRIV1_ID_VAL5_PME_IN_D2_MASK (0x10UL)
#define CFG_PRIV1_ID_VAL5_PME_IN_D2_SHIFT (4UL)
#define CFG_PRIV1_ID_VAL5_PME_IN_D1_MASK (0x8UL)
#define CFG_PRIV1_ID_VAL5_PME_IN_D1_SHIFT (3UL)
#define CFG_PRIV1_ID_VAL5_PME_IN_D0_MASK (0x4UL)
#define CFG_PRIV1_ID_VAL5_PME_IN_D0_SHIFT (2UL)
#define CFG_PRIV1_ID_VAL5_D2_SUPPORT_MASK (0x2UL)
#define CFG_PRIV1_ID_VAL5_D2_SUPPORT_SHIFT (1UL)
#define CFG_PRIV1_ID_VAL5_D1_SUPPORT_MASK (0x1UL)
#define CFG_PRIV1_ID_VAL5_D1_SUPPORT_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_UNUSED_H_TYPE;
#define CFG_PRIV1_UNUSED_H_RESERVED_MASK (0xffffffffUL)
#define CFG_PRIV1_UNUSED_H_RESERVED_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_ID_VAL6_TYPE;
#define CFG_PRIV1_ID_VAL6_BIST_MASK (0xff0000UL)
#define CFG_PRIV1_ID_VAL6_BIST_SHIFT (16UL)
#define CFG_PRIV1_ID_VAL6_RESERVED0_MASK (0xffffUL)
#define CFG_PRIV1_ID_VAL6_RESERVED0_SHIFT (0UL)
#define CFG_PRIV1_ID_VAL6_RESERVED1_MASK (0xff000000UL)
#define CFG_PRIV1_ID_VAL6_RESERVED1_SHIFT (24UL)




typedef uint32_t CFG_PRIV1_MSI_DATA_TYPE;
#define CFG_PRIV1_MSI_DATA_MASK (0xffffUL)
#define CFG_PRIV1_MSI_DATA_SHIFT (0UL)
#define CFG_PRIV1_MSI_DATA_RESERVED0_MASK (0xffff0000UL)
#define CFG_PRIV1_MSI_DATA_RESERVED0_SHIFT (16UL)




typedef uint32_t CFG_PRIV1_MSI_ADDR_H_TYPE;
#define CFG_PRIV1_MSI_ADDR_H_MASK (0xffffffffUL)
#define CFG_PRIV1_MSI_ADDR_H_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_MSI_ADDR_L_TYPE;
#define CFG_PRIV1_MSI_ADDR_L_MASK (0xffffffffUL)
#define CFG_PRIV1_MSI_ADDR_L_SHIFT (0UL)




typedef uint8_t CFG_PRIV1_RESERVED_TYPE;




typedef uint32_t CFG_PRIV1_MSI_MASK_TYPE;
#define CFG_PRIV1_MSI_MASK_MASK (0xffffffffUL)
#define CFG_PRIV1_MSI_MASK_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_MSI_PEND_TYPE;
#define CFG_PRIV1_MSI_PEND_MASK (0xffffffffUL)
#define CFG_PRIV1_MSI_PEND_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_PM_DATA_C_TYPE;
#define CFG_PRIV1_PM_DATA_C_RESERVED0_MASK (0xffffff00UL)
#define CFG_PRIV1_PM_DATA_C_RESERVED0_SHIFT (8UL)
#define CFG_PRIV1_PM_DATA_C_8_PRG_MASK (0xffUL)
#define CFG_PRIV1_PM_DATA_C_8_PRG_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_MSIX_CONTROL_TYPE;
#define CFG_PRIV1_MSIX_CONTROL_RESERVED0_MASK (0xfffff800UL)
#define CFG_PRIV1_MSIX_CONTROL_RESERVED0_SHIFT (11UL)
#define CFG_PRIV1_MSIX_CONTROL_TBL_SIZ_MASK (0x7ffUL)
#define CFG_PRIV1_MSIX_CONTROL_TBL_SIZ_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_MSIX_TBL_OFF_BIR_TYPE;
#define CFG_PRIV1_MSIX_TBL_OFF_BIR_OFF_MASK (0xfffffff8UL)
#define CFG_PRIV1_MSIX_TBL_OFF_BIR_OFF_SHIFT (3UL)
#define CFG_PRIV1_MSIX_TBL_OFF_BIR_BIR_MASK (0x7UL)
#define CFG_PRIV1_MSIX_TBL_OFF_BIR_BIR_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_MSIX_PBA_OFF_BIR_TYPE;
#define CFG_PRIV1_MSIX_PBA_OFF_BIR_OFF_MASK (0xfffffff8UL)
#define CFG_PRIV1_MSIX_PBA_OFF_BIR_OFF_SHIFT (3UL)
#define CFG_PRIV1_MSIX_PBA_OFF_BIR_BIR_MASK (0x7UL)
#define CFG_PRIV1_MSIX_PBA_OFF_BIR_BIR_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_UNUSED_K_TYPE;
#define CFG_PRIV1_UNUSED_K_RESERVED_MASK (0xffffffffUL)
#define CFG_PRIV1_UNUSED_K_RESERVED_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_PCIE_CAPABILITY_TYPE;
#define CFG_PRIV1_PCIE_CAPABILITY_ASPM_OPTIONALITY_MASK (0x40UL)
#define CFG_PRIV1_PCIE_CAPABILITY_ASPM_OPTIONALITY_SHIFT (6UL)
#define CFG_PRIV1_PCIE_CAPABILITY_COMPLY_PCIE_1_1_MASK (0x20UL)
#define CFG_PRIV1_PCIE_CAPABILITY_COMPLY_PCIE_1_1_SHIFT (5UL)
#define CFG_PRIV1_PCIE_CAPABILITY_INTERRUPT_MSG_NUM_MASK (0x1fUL)
#define CFG_PRIV1_PCIE_CAPABILITY_INTERRUPT_MSG_NUM_SHIFT (0UL)
#define CFG_PRIV1_PCIE_CAPABILITY_RESERVED0_MASK (0xffffff80UL)
#define CFG_PRIV1_PCIE_CAPABILITY_RESERVED0_SHIFT (7UL)




typedef uint32_t CFG_PRIV1_DEVICE_CAPABILITY_TYPE;
#define CFG_PRIV1_DEVICE_CAPABILITY_ROLE_BASED_ERR_RPT_MASK (0x8000UL)
#define CFG_PRIV1_DEVICE_CAPABILITY_ROLE_BASED_ERR_RPT_SHIFT (15UL)
#define CFG_PRIV1_DEVICE_CAPABILITY_L1_ACCEPTABLE_LATENCY_MASK (0xe00UL)
#define CFG_PRIV1_DEVICE_CAPABILITY_L1_ACCEPTABLE_LATENCY_SHIFT (9UL)
#define CFG_PRIV1_DEVICE_CAPABILITY_L0S_ACCEPTABLE_LATENCY_MASK (0x1c0UL)
#define CFG_PRIV1_DEVICE_CAPABILITY_L0S_ACCEPTABLE_LATENCY_SHIFT (6UL)
#define CFG_PRIV1_DEVICE_CAPABILITY_EXTENDED_TAG_SUPPORT_MASK (0x20UL)
#define CFG_PRIV1_DEVICE_CAPABILITY_EXTENDED_TAG_SUPPORT_SHIFT (5UL)
#define CFG_PRIV1_DEVICE_CAPABILITY_MAX_PL_SIZE_SUPPORTED_MASK (0x7UL)
#define CFG_PRIV1_DEVICE_CAPABILITY_MAX_PL_SIZE_SUPPORTED_SHIFT (0UL)
#define CFG_PRIV1_DEVICE_CAPABILITY_RESERVED0_MASK (0x18UL)
#define CFG_PRIV1_DEVICE_CAPABILITY_RESERVED0_SHIFT (3UL)
#define CFG_PRIV1_DEVICE_CAPABILITY_RESERVED1_MASK (0x7000UL)
#define CFG_PRIV1_DEVICE_CAPABILITY_RESERVED1_SHIFT (12UL)
#define CFG_PRIV1_DEVICE_CAPABILITY_RESERVED2_MASK (0xffff0000UL)
#define CFG_PRIV1_DEVICE_CAPABILITY_RESERVED2_SHIFT (16UL)




typedef uint32_t CFG_PRIV1_DEVICE_CONTROL_TYPE;
#define CFG_PRIV1_DEVICE_CONTROL_RESERVED_MASK (0xffffffffUL)
#define CFG_PRIV1_DEVICE_CONTROL_RESERVED_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_LINK_CAPABILITY_TYPE;
#define CFG_PRIV1_LINK_CAPABILITY_PORT_NUM_MASK (0xff000000UL)
#define CFG_PRIV1_LINK_CAPABILITY_PORT_NUM_SHIFT (24UL)
#define CFG_PRIV1_LINK_CAPABILITY_L1_EXIT_COMM_LAT_MASK (0xe00000UL)
#define CFG_PRIV1_LINK_CAPABILITY_L1_EXIT_COMM_LAT_SHIFT (21UL)
#define CFG_PRIV1_LINK_CAPABILITY_L0S_EXIT_COMM_LAT_MASK (0x1c0000UL)
#define CFG_PRIV1_LINK_CAPABILITY_L0S_EXIT_COMM_LAT_SHIFT (18UL)
#define CFG_PRIV1_LINK_CAPABILITY_L1_EXIT_LAT_MASK (0x38000UL)
#define CFG_PRIV1_LINK_CAPABILITY_L1_EXIT_LAT_SHIFT (15UL)
#define CFG_PRIV1_LINK_CAPABILITY_L0S_EXIT_LAT_MASK (0x7000UL)
#define CFG_PRIV1_LINK_CAPABILITY_L0S_EXIT_LAT_SHIFT (12UL)
#define CFG_PRIV1_LINK_CAPABILITY_ASPM_SUPPORT_MASK (0xc00UL)
#define CFG_PRIV1_LINK_CAPABILITY_ASPM_SUPPORT_SHIFT (10UL)
#define CFG_PRIV1_LINK_CAPABILITY_CLK_POWER_MGMT_MASK (0x200UL)
#define CFG_PRIV1_LINK_CAPABILITY_CLK_POWER_MGMT_SHIFT (9UL)
#define CFG_PRIV1_LINK_CAPABILITY_MAX_LINK_WIDTH_MASK (0x1f0UL)
#define CFG_PRIV1_LINK_CAPABILITY_MAX_LINK_WIDTH_SHIFT (4UL)
#define CFG_PRIV1_LINK_CAPABILITY_MAX_LINK_SPEED_MASK (0xfUL)
#define CFG_PRIV1_LINK_CAPABILITY_MAX_LINK_SPEED_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_BAR2_CONFIG_TYPE;
#define CFG_PRIV1_BAR2_CONFIG_RESERVED_MASK (0xffffffc0UL)
#define CFG_PRIV1_BAR2_CONFIG_RESERVED_SHIFT (6UL)
#define CFG_PRIV1_BAR2_CONFIG_PREFETCH_MASK (0x20UL)
#define CFG_PRIV1_BAR2_CONFIG_PREFETCH_SHIFT (5UL)
#define CFG_PRIV1_BAR2_CONFIG_64ENA_MASK (0x10UL)
#define CFG_PRIV1_BAR2_CONFIG_64ENA_SHIFT (4UL)
#define CFG_PRIV1_BAR2_CONFIG_SIZE_MASK (0xfUL)
#define CFG_PRIV1_BAR2_CONFIG_SIZE_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_PCIE_DEVICE_CAPABILITY_2_TYPE;
#define CFG_PRIV1_PCIE_DEVICE_CAPABILITY_2_OBFF_SUPPORTED_MASK (0xc0000UL)
#define CFG_PRIV1_PCIE_DEVICE_CAPABILITY_2_OBFF_SUPPORTED_SHIFT (18UL)
#define CFG_PRIV1_PCIE_DEVICE_CAPABILITY_2_IDO_SUPPORTED_MASK (0x400UL)
#define CFG_PRIV1_PCIE_DEVICE_CAPABILITY_2_IDO_SUPPORTED_SHIFT (10UL)
#define CFG_PRIV1_PCIE_DEVICE_CAPABILITY_2_RESERVED2_MASK (0x3e0UL)
#define CFG_PRIV1_PCIE_DEVICE_CAPABILITY_2_RESERVED2_SHIFT (5UL)
#define CFG_PRIV1_PCIE_DEVICE_CAPABILITY_2_CMPL_TO_DISABL_SUPP_MASK (0x10UL)
#define CFG_PRIV1_PCIE_DEVICE_CAPABILITY_2_CMPL_TO_DISABL_SUPP_SHIFT (4UL)
#define CFG_PRIV1_PCIE_DEVICE_CAPABILITY_2_CMPL_TO_RANGE_SUPP_MASK (0xfUL)
#define CFG_PRIV1_PCIE_DEVICE_CAPABILITY_2_CMPL_TO_RANGE_SUPP_SHIFT (0UL)
#define CFG_PRIV1_PCIE_DEVICE_CAPABILITY_2_RESERVED0_MASK (0x3f800UL)
#define CFG_PRIV1_PCIE_DEVICE_CAPABILITY_2_RESERVED0_SHIFT (11UL)
#define CFG_PRIV1_PCIE_DEVICE_CAPABILITY_2_RESERVED1_MASK (0xfff00000UL)
#define CFG_PRIV1_PCIE_DEVICE_CAPABILITY_2_RESERVED1_SHIFT (20UL)




typedef uint32_t CFG_PRIV1_PCIE_LINK_CAPABILITY_2_TYPE;
#define CFG_PRIV1_PCIE_LINK_CAPABILITY_2_RESERVED_0_MASK (0xfe000000UL)
#define CFG_PRIV1_PCIE_LINK_CAPABILITY_2_RESERVED_0_SHIFT (25UL)
#define CFG_PRIV1_PCIE_LINK_CAPABILITY_2_RESERVED_1_MASK (0x1ffffffUL)
#define CFG_PRIV1_PCIE_LINK_CAPABILITY_2_RESERVED_1_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_PCIE_LINK_CONTROL_TYPE;
#define CFG_PRIV1_PCIE_LINK_CONTROL_RC_RCB_MASK (0x1UL)
#define CFG_PRIV1_PCIE_LINK_CONTROL_RC_RCB_SHIFT (0UL)
#define CFG_PRIV1_PCIE_LINK_CONTROL_RESERVED0_MASK (0xfffffffeUL)
#define CFG_PRIV1_PCIE_LINK_CONTROL_RESERVED0_SHIFT (1UL)




typedef uint32_t CFG_PRIV1_PCIE_LINK_CAPABILITY_RC_TYPE;
#define CFG_PRIV1_PCIE_LINK_CAPABILITY_RC_RC_DL_ACTIVE_CAP_MASK (0x1UL)
#define CFG_PRIV1_PCIE_LINK_CAPABILITY_RC_RC_DL_ACTIVE_CAP_SHIFT (0UL)
#define CFG_PRIV1_PCIE_LINK_CAPABILITY_RC_SLOT_CLK_CONFIG_MASK (0x2UL)
#define CFG_PRIV1_PCIE_LINK_CAPABILITY_RC_SLOT_CLK_CONFIG_SHIFT (1UL)
#define CFG_PRIV1_PCIE_LINK_CAPABILITY_RC_RESERVED0_MASK (0xfffffffcUL)
#define CFG_PRIV1_PCIE_LINK_CAPABILITY_RC_RESERVED0_SHIFT (2UL)




typedef uint32_t CFG_PRIV1_BAR3_CONFIG_TYPE;
#define CFG_PRIV1_BAR3_CONFIG_RESERVED_MASK (0xffffffc0UL)
#define CFG_PRIV1_BAR3_CONFIG_RESERVED_SHIFT (6UL)
#define CFG_PRIV1_BAR3_CONFIG_PREFETCH_MASK (0x20UL)
#define CFG_PRIV1_BAR3_CONFIG_PREFETCH_SHIFT (5UL)
#define CFG_PRIV1_BAR3_CONFIG_64ENA_MASK (0x10UL)
#define CFG_PRIV1_BAR3_CONFIG_64ENA_SHIFT (4UL)
#define CFG_PRIV1_BAR3_CONFIG_SIZE_MASK (0xfUL)
#define CFG_PRIV1_BAR3_CONFIG_SIZE_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_ROOT_CAP_TYPE;
#define CFG_PRIV1_ROOT_CAP_RC_CRS_CAP_MASK (0x1UL)
#define CFG_PRIV1_ROOT_CAP_RC_CRS_CAP_SHIFT (0UL)
#define CFG_PRIV1_ROOT_CAP_RC_LTR_SUPPORTED_MASK (0x2UL)
#define CFG_PRIV1_ROOT_CAP_RC_LTR_SUPPORTED_SHIFT (1UL)
#define CFG_PRIV1_ROOT_CAP_RC_CLKREQ_SUPPORTED_MASK (0x4UL)
#define CFG_PRIV1_ROOT_CAP_RC_CLKREQ_SUPPORTED_SHIFT (2UL)
#define CFG_PRIV1_ROOT_CAP_RC_EXT2_CAP_ENA_MASK (0xf8UL)
#define CFG_PRIV1_ROOT_CAP_RC_EXT2_CAP_ENA_SHIFT (3UL)
#define CFG_PRIV1_ROOT_CAP_RESERVED0_MASK (0xffffff00UL)
#define CFG_PRIV1_ROOT_CAP_RESERVED0_SHIFT (8UL)




typedef uint32_t CFG_PRIV1_ROOT_CONTROL_TYPE;
#define CFG_PRIV1_ROOT_CONTROL_RC_CLKREQ_ENABLED_MASK (0x1UL)
#define CFG_PRIV1_ROOT_CONTROL_RC_CLKREQ_ENABLED_SHIFT (0UL)
#define CFG_PRIV1_ROOT_CONTROL_RESERVED0_MASK (0xfffffffeUL)
#define CFG_PRIV1_ROOT_CONTROL_RESERVED0_SHIFT (1UL)




typedef uint32_t CFG_PRIV1_DEV_SER_NUM_CAP_ID_TYPE;
#define CFG_PRIV1_DEV_SER_NUM_CAP_ID_RC_EXT_CAP_ENA_MASK (0xc0000000UL)
#define CFG_PRIV1_DEV_SER_NUM_CAP_ID_RC_EXT_CAP_ENA_SHIFT (30UL)
#define CFG_PRIV1_DEV_SER_NUM_CAP_ID_EXT_REG_CAP_ENA_MASK (0x3c000000UL)
#define CFG_PRIV1_DEV_SER_NUM_CAP_ID_EXT_REG_CAP_ENA_SHIFT (26UL)
#define CFG_PRIV1_DEV_SER_NUM_CAP_ID_EXT_CAP_ENA_MASK (0x3f00000UL)
#define CFG_PRIV1_DEV_SER_NUM_CAP_ID_EXT_CAP_ENA_SHIFT (20UL)
#define CFG_PRIV1_DEV_SER_NUM_CAP_ID_DEV_SER_NUM_CAP_VER_MASK (0xf0000UL)
#define CFG_PRIV1_DEV_SER_NUM_CAP_ID_DEV_SER_NUM_CAP_VER_SHIFT (16UL)
#define CFG_PRIV1_DEV_SER_NUM_CAP_ID_DEV_SER_NUM_CAP_ID_MASK (0xffffUL)
#define CFG_PRIV1_DEV_SER_NUM_CAP_ID_DEV_SER_NUM_CAP_ID_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_LOWER_SER_NUM_TYPE;
#define CFG_PRIV1_LOWER_SER_NUM_MASK (0xffffffffUL)
#define CFG_PRIV1_LOWER_SER_NUM_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_UPPER_SER_NUM_TYPE;
#define CFG_PRIV1_UPPER_SER_NUM_MASK (0xffffffffUL)
#define CFG_PRIV1_UPPER_SER_NUM_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_ADV_ERR_CAP_TYPE;
#define CFG_PRIV1_ADV_ERR_CAP_ECRC_GEN_CAP_MASK (0x2UL)
#define CFG_PRIV1_ADV_ERR_CAP_ECRC_GEN_CAP_SHIFT (1UL)
#define CFG_PRIV1_ADV_ERR_CAP_ECRC_CHK_CAP_MASK (0x1UL)
#define CFG_PRIV1_ADV_ERR_CAP_ECRC_CHK_CAP_SHIFT (0UL)
#define CFG_PRIV1_ADV_ERR_CAP_RESERVED0_MASK (0xfffffffcUL)
#define CFG_PRIV1_ADV_ERR_CAP_RESERVED0_SHIFT (2UL)




typedef uint32_t CFG_PRIV1_PWR_BDGT_DATA_0_TYPE;
#define CFG_PRIV1_PWR_BDGT_DATA_0_RESERVED_MASK (0xffe00000UL)
#define CFG_PRIV1_PWR_BDGT_DATA_0_RESERVED_SHIFT (21UL)
#define CFG_PRIV1_PWR_BDGT_DATA_0_MASK (0x1fffffUL)
#define CFG_PRIV1_PWR_BDGT_DATA_0_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_PWR_BDGT_DATA_1_TYPE;
#define CFG_PRIV1_PWR_BDGT_DATA_1_RW_MASK (0xffe00000UL)
#define CFG_PRIV1_PWR_BDGT_DATA_1_RW_SHIFT (21UL)
#define CFG_PRIV1_PWR_BDGT_DATA_1_PWR_BDGT_DATA_1_MASK (0x1fffffUL)
#define CFG_PRIV1_PWR_BDGT_DATA_1_PWR_BDGT_DATA_1_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_PWR_BDGT_DATA_2_TYPE;
#define CFG_PRIV1_PWR_BDGT_DATA_2_RW_MASK (0xffe00000UL)
#define CFG_PRIV1_PWR_BDGT_DATA_2_RW_SHIFT (21UL)
#define CFG_PRIV1_PWR_BDGT_DATA_2_PWR_BDGT_DATA_2_MASK (0x1fffffUL)
#define CFG_PRIV1_PWR_BDGT_DATA_2_PWR_BDGT_DATA_2_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_PWR_BDGT_DATA_3_TYPE;
#define CFG_PRIV1_PWR_BDGT_DATA_3_RW_MASK (0xffe00000UL)
#define CFG_PRIV1_PWR_BDGT_DATA_3_RW_SHIFT (21UL)
#define CFG_PRIV1_PWR_BDGT_DATA_3_PWR_BDGT_DATA_3_MASK (0x1fffffUL)
#define CFG_PRIV1_PWR_BDGT_DATA_3_PWR_BDGT_DATA_3_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_PWR_BDGT_DATA_4_TYPE;
#define CFG_PRIV1_PWR_BDGT_DATA_4_RW_MASK (0xffe00000UL)
#define CFG_PRIV1_PWR_BDGT_DATA_4_RW_SHIFT (21UL)
#define CFG_PRIV1_PWR_BDGT_DATA_4_PWR_BDGT_DATA_4_MASK (0x1fffffUL)
#define CFG_PRIV1_PWR_BDGT_DATA_4_PWR_BDGT_DATA_4_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_PWR_BDGT_DATA_5_TYPE;
#define CFG_PRIV1_PWR_BDGT_DATA_5_RW_MASK (0xffe00000UL)
#define CFG_PRIV1_PWR_BDGT_DATA_5_RW_SHIFT (21UL)
#define CFG_PRIV1_PWR_BDGT_DATA_5_PWR_BDGT_DATA_5_MASK (0x1fffffUL)
#define CFG_PRIV1_PWR_BDGT_DATA_5_PWR_BDGT_DATA_5_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_PWR_BDGT_DATA_6_TYPE;
#define CFG_PRIV1_PWR_BDGT_DATA_6_RW_MASK (0xffe00000UL)
#define CFG_PRIV1_PWR_BDGT_DATA_6_RW_SHIFT (21UL)
#define CFG_PRIV1_PWR_BDGT_DATA_6_PWR_BDGT_DATA_6_MASK (0x1fffffUL)
#define CFG_PRIV1_PWR_BDGT_DATA_6_PWR_BDGT_DATA_6_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_PWR_BDGT_DATA_7_TYPE;
#define CFG_PRIV1_PWR_BDGT_DATA_7_RW_MASK (0xffe00000UL)
#define CFG_PRIV1_PWR_BDGT_DATA_7_RW_SHIFT (21UL)
#define CFG_PRIV1_PWR_BDGT_DATA_7_PWR_BDGT_DATA_7_MASK (0x1fffffUL)
#define CFG_PRIV1_PWR_BDGT_DATA_7_PWR_BDGT_DATA_7_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_EXT2_CAP_ADDR_TYPE;
#define CFG_PRIV1_EXT2_CAP_ADDR_RW_MASK (0xfffff000UL)
#define CFG_PRIV1_EXT2_CAP_ADDR_RW_SHIFT (12UL)
#define CFG_PRIV1_EXT2_CAP_ADDR_EXT4_CAP_ENA_MASK (0xf00UL)
#define CFG_PRIV1_EXT2_CAP_ADDR_EXT4_CAP_ENA_SHIFT (8UL)
#define CFG_PRIV1_EXT2_CAP_ADDR_EXT3_CAP_ENA_MASK (0xf0UL)
#define CFG_PRIV1_EXT2_CAP_ADDR_EXT3_CAP_ENA_SHIFT (4UL)
#define CFG_PRIV1_EXT2_CAP_ADDR_EXT2_CAP_ENA_MASK (0xfUL)
#define CFG_PRIV1_EXT2_CAP_ADDR_EXT2_CAP_ENA_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_PWR_BDGT_DATA_8_TYPE;
#define CFG_PRIV1_PWR_BDGT_DATA_8_RESERVED_MASK (0xffe00000UL)
#define CFG_PRIV1_PWR_BDGT_DATA_8_RESERVED_SHIFT (21UL)
#define CFG_PRIV1_PWR_BDGT_DATA_8_MASK (0x1fffffUL)
#define CFG_PRIV1_PWR_BDGT_DATA_8_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_L1SUB_CAP_TYPE;
#define CFG_PRIV1_L1SUB_CAP_RESERVED_MASK (0xff000000UL)
#define CFG_PRIV1_L1SUB_CAP_RESERVED_SHIFT (24UL)
#define CFG_PRIV1_L1SUB_CAP_L1SUB_PWR_ON_VALUE_MASK (0xf80000UL)
#define CFG_PRIV1_L1SUB_CAP_L1SUB_PWR_ON_VALUE_SHIFT (19UL)
#define CFG_PRIV1_L1SUB_CAP_RESERVED_0_MASK (0x40000UL)
#define CFG_PRIV1_L1SUB_CAP_RESERVED_0_SHIFT (18UL)
#define CFG_PRIV1_L1SUB_CAP_L1SUB_PWR_ON_SCALE_MASK (0x30000UL)
#define CFG_PRIV1_L1SUB_CAP_L1SUB_PWR_ON_SCALE_SHIFT (16UL)
#define CFG_PRIV1_L1SUB_CAP_L1SUB_CMN_MODE_UP_TIME_MASK (0xff00UL)
#define CFG_PRIV1_L1SUB_CAP_L1SUB_CMN_MODE_UP_TIME_SHIFT (8UL)
#define CFG_PRIV1_L1SUB_CAP_RESERVED_1_MASK (0xe0UL)
#define CFG_PRIV1_L1SUB_CAP_RESERVED_1_SHIFT (5UL)
#define CFG_PRIV1_L1SUB_CAP_CLKREQ_L1SUB_SUPP_MASK (0x10UL)
#define CFG_PRIV1_L1SUB_CAP_CLKREQ_L1SUB_SUPP_SHIFT (4UL)
#define CFG_PRIV1_L1SUB_CAP_ASPM_L1_1_SUPP_MASK (0x8UL)
#define CFG_PRIV1_L1SUB_CAP_ASPM_L1_1_SUPP_SHIFT (3UL)
#define CFG_PRIV1_L1SUB_CAP_ASPM_L1_2_SUPP_MASK (0x4UL)
#define CFG_PRIV1_L1SUB_CAP_ASPM_L1_2_SUPP_SHIFT (2UL)
#define CFG_PRIV1_L1SUB_CAP_PM_L1_1_SUPP_MASK (0x2UL)
#define CFG_PRIV1_L1SUB_CAP_PM_L1_1_SUPP_SHIFT (1UL)
#define CFG_PRIV1_L1SUB_CAP_PM_L1_2_SUPP_MASK (0x1UL)
#define CFG_PRIV1_L1SUB_CAP_PM_L1_2_SUPP_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_L1SUB_EXT_CAP_TYPE;
#define CFG_PRIV1_L1SUB_EXT_CAP_RESERVED_MASK (0xfff00000UL)
#define CFG_PRIV1_L1SUB_EXT_CAP_RESERVED_SHIFT (20UL)
#define CFG_PRIV1_L1SUB_EXT_CAP_VERSION_CAPID_MASK (0xfffffUL)
#define CFG_PRIV1_L1SUB_EXT_CAP_VERSION_CAPID_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_MARGIN_PORT_CAP_STATUS_TYPE;
#define CFG_PRIV1_MARGIN_PORT_CAP_STATUS_RESERVED_MASK (0xfffc0000UL)
#define CFG_PRIV1_MARGIN_PORT_CAP_STATUS_RESERVED_SHIFT (18UL)
#define CFG_PRIV1_MARGIN_PORT_CAP_STATUS_SW_READY_MASK (0x20000UL)
#define CFG_PRIV1_MARGIN_PORT_CAP_STATUS_SW_READY_SHIFT (17UL)
#define CFG_PRIV1_MARGIN_PORT_CAP_STATUS_READY_MASK (0x10000UL)
#define CFG_PRIV1_MARGIN_PORT_CAP_STATUS_READY_SHIFT (16UL)
#define CFG_PRIV1_MARGIN_PORT_CAP_STATUS_RESERVED_1_MASK (0xfffeUL)
#define CFG_PRIV1_MARGIN_PORT_CAP_STATUS_RESERVED_1_SHIFT (1UL)
#define CFG_PRIV1_MARGIN_PORT_CAP_STATUS_USE_DRV_SW_MASK (0x1UL)
#define CFG_PRIV1_MARGIN_PORT_CAP_STATUS_USE_DRV_SW_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_PWR_BDGT_CAPABILITY_TYPE;
#define CFG_PRIV1_PWR_BDGT_CAPABILITY_RESERVED_MASK (0xfffffffeUL)
#define CFG_PRIV1_PWR_BDGT_CAPABILITY_RESERVED_SHIFT (1UL)
#define CFG_PRIV1_PWR_BDGT_CAPABILITY_SYSTEM_ALLOC_MASK (0x1UL)
#define CFG_PRIV1_PWR_BDGT_CAPABILITY_SYSTEM_ALLOC_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_VSEC_HDR_TYPE;
#define CFG_PRIV1_VSEC_HDR_LENGTH_MASK (0xfff00000UL)
#define CFG_PRIV1_VSEC_HDR_LENGTH_SHIFT (20UL)
#define CFG_PRIV1_VSEC_HDR_REV_MASK (0xf0000UL)
#define CFG_PRIV1_VSEC_HDR_REV_SHIFT (16UL)
#define CFG_PRIV1_VSEC_HDR_ID_MASK (0xffffUL)
#define CFG_PRIV1_VSEC_HDR_ID_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_RC_USER_MEM_LO1_TYPE;
#define CFG_PRIV1_RC_USER_MEM_LO1_RC_USER_MEM_ADDR_LO1_MASK (0xffff0000UL)
#define CFG_PRIV1_RC_USER_MEM_LO1_RC_USER_MEM_ADDR_LO1_SHIFT (16UL)
#define CFG_PRIV1_RC_USER_MEM_LO1_UNUSED_1_MASK (0xff00UL)
#define CFG_PRIV1_RC_USER_MEM_LO1_UNUSED_1_SHIFT (8UL)
#define CFG_PRIV1_RC_USER_MEM_LO1_RC_USER_MEM_EN1_MASK (0x80UL)
#define CFG_PRIV1_RC_USER_MEM_LO1_RC_USER_MEM_EN1_SHIFT (7UL)
#define CFG_PRIV1_RC_USER_MEM_LO1_RC_USER_SIZE1_EXT_MASK (0x70UL)
#define CFG_PRIV1_RC_USER_MEM_LO1_RC_USER_SIZE1_EXT_SHIFT (4UL)
#define CFG_PRIV1_RC_USER_MEM_LO1_RC_USER_SIZE1_MASK (0xfUL)
#define CFG_PRIV1_RC_USER_MEM_LO1_RC_USER_SIZE1_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_RC_USER_MEM_HI1_TYPE;
#define CFG_PRIV1_RC_USER_MEM_HI1_ADDR_MASK (0xffffffffUL)
#define CFG_PRIV1_RC_USER_MEM_HI1_ADDR_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_RC_USER_MEM_LO2_TYPE;
#define CFG_PRIV1_RC_USER_MEM_LO2_RC_USER_MEM_ADDR_LO2_MASK (0xffff0000UL)
#define CFG_PRIV1_RC_USER_MEM_LO2_RC_USER_MEM_ADDR_LO2_SHIFT (16UL)
#define CFG_PRIV1_RC_USER_MEM_LO2_UNUSED_1_MASK (0xff00UL)
#define CFG_PRIV1_RC_USER_MEM_LO2_UNUSED_1_SHIFT (8UL)
#define CFG_PRIV1_RC_USER_MEM_LO2_RC_USER_MEM_EN2_MASK (0x80UL)
#define CFG_PRIV1_RC_USER_MEM_LO2_RC_USER_MEM_EN2_SHIFT (7UL)
#define CFG_PRIV1_RC_USER_MEM_LO2_RC_USER_SIZE2_EXT_MASK (0x70UL)
#define CFG_PRIV1_RC_USER_MEM_LO2_RC_USER_SIZE2_EXT_SHIFT (4UL)
#define CFG_PRIV1_RC_USER_MEM_LO2_RC_USER_SIZE2_MASK (0xfUL)
#define CFG_PRIV1_RC_USER_MEM_LO2_RC_USER_SIZE2_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_RC_USER_MEM_HI2_TYPE;
#define CFG_PRIV1_RC_USER_MEM_HI2_ADDR_MASK (0xffffffffUL)
#define CFG_PRIV1_RC_USER_MEM_HI2_ADDR_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_PCIER_MC_WINDOW_SIZE_REQ_TYPE;
#define CFG_PRIV1_PCIER_MC_WINDOW_SIZE_REQ_MASK (0x3fUL)
#define CFG_PRIV1_PCIER_MC_WINDOW_SIZE_REQ_SHIFT (0UL)
#define CFG_PRIV1_PCIER_MC_WINDOW_SIZE_REQ_RESERVED0_MASK (0xffffffc0UL)
#define CFG_PRIV1_PCIER_MC_WINDOW_SIZE_REQ_RESERVED0_SHIFT (6UL)




typedef uint32_t CFG_PRIV1_PTM_CAP_TYPE;
#define CFG_PRIV1_PTM_CAP_ROOT_CAPABLE_MASK (0x4UL)
#define CFG_PRIV1_PTM_CAP_ROOT_CAPABLE_SHIFT (2UL)
#define CFG_PRIV1_PTM_CAP_RESP_CAPABLE_MASK (0x2UL)
#define CFG_PRIV1_PTM_CAP_RESP_CAPABLE_SHIFT (1UL)
#define CFG_PRIV1_PTM_CAP_REQ_CAPABLE_MASK (0x1UL)
#define CFG_PRIV1_PTM_CAP_REQ_CAPABLE_SHIFT (0UL)
#define CFG_PRIV1_PTM_CAP_RESERVED0_MASK (0xfffffff8UL)
#define CFG_PRIV1_PTM_CAP_RESERVED0_SHIFT (3UL)




typedef uint32_t CFG_PRIV1_TPH_CAP_TYPE;
#define CFG_PRIV1_TPH_CAP_ST_TABLE_SIZE_MASK (0x7ff0UL)
#define CFG_PRIV1_TPH_CAP_ST_TABLE_SIZE_SHIFT (4UL)
#define CFG_PRIV1_TPH_CAP_ST_TABLE_LOCATION_MASK (0xcUL)
#define CFG_PRIV1_TPH_CAP_ST_TABLE_LOCATION_SHIFT (2UL)
#define CFG_PRIV1_TPH_CAP_DEV_SPEC_MODE_MASK (0x2UL)
#define CFG_PRIV1_TPH_CAP_DEV_SPEC_MODE_SHIFT (1UL)
#define CFG_PRIV1_TPH_CAP_INT_VEC_MODE_SUPP_MASK (0x1UL)
#define CFG_PRIV1_TPH_CAP_INT_VEC_MODE_SUPP_SHIFT (0UL)
#define CFG_PRIV1_TPH_CAP_RESERVED0_MASK (0xffff8000UL)
#define CFG_PRIV1_TPH_CAP_RESERVED0_SHIFT (15UL)




typedef uint32_t CFG_PRIV1_RESIZEBAR_CAP_TYPE;
#define CFG_PRIV1_RESIZEBAR_CAP_SIZE_512G_TO_2G_CAPABILITY_MASK (0xff8000UL)
#define CFG_PRIV1_RESIZEBAR_CAP_SIZE_512G_TO_2G_CAPABILITY_SHIFT (15UL)
#define CFG_PRIV1_RESIZEBAR_CAP_SIZE_1G_CAPABILITY_MASK (0x4000UL)
#define CFG_PRIV1_RESIZEBAR_CAP_SIZE_1G_CAPABILITY_SHIFT (14UL)
#define CFG_PRIV1_RESIZEBAR_CAP_SIZE_512M_CAPABILITY_MASK (0x2000UL)
#define CFG_PRIV1_RESIZEBAR_CAP_SIZE_512M_CAPABILITY_SHIFT (13UL)
#define CFG_PRIV1_RESIZEBAR_CAP_SIZE_256M_CAPABILITY_MASK (0x1000UL)
#define CFG_PRIV1_RESIZEBAR_CAP_SIZE_256M_CAPABILITY_SHIFT (12UL)
#define CFG_PRIV1_RESIZEBAR_CAP_SIZE_128M_CAPABILITY_MASK (0x800UL)
#define CFG_PRIV1_RESIZEBAR_CAP_SIZE_128M_CAPABILITY_SHIFT (11UL)
#define CFG_PRIV1_RESIZEBAR_CAP_SIZE_64M_CAPABILITY_MASK (0x400UL)
#define CFG_PRIV1_RESIZEBAR_CAP_SIZE_64M_CAPABILITY_SHIFT (10UL)
#define CFG_PRIV1_RESIZEBAR_CAP_SIZE_32M_CAPABILITY_MASK (0x200UL)
#define CFG_PRIV1_RESIZEBAR_CAP_SIZE_32M_CAPABILITY_SHIFT (9UL)
#define CFG_PRIV1_RESIZEBAR_CAP_SIZE_16M_CAPABILITY_MASK (0x100UL)
#define CFG_PRIV1_RESIZEBAR_CAP_SIZE_16M_CAPABILITY_SHIFT (8UL)
#define CFG_PRIV1_RESIZEBAR_CAP_SIZE_8M_CAPABILITY_MASK (0x80UL)
#define CFG_PRIV1_RESIZEBAR_CAP_SIZE_8M_CAPABILITY_SHIFT (7UL)
#define CFG_PRIV1_RESIZEBAR_CAP_SIZE_4M_CAPABILITY_MASK (0x40UL)
#define CFG_PRIV1_RESIZEBAR_CAP_SIZE_4M_CAPABILITY_SHIFT (6UL)
#define CFG_PRIV1_RESIZEBAR_CAP_SIZE_2M_CAPABILITY_MASK (0x20UL)
#define CFG_PRIV1_RESIZEBAR_CAP_SIZE_2M_CAPABILITY_SHIFT (5UL)
#define CFG_PRIV1_RESIZEBAR_CAP_SIZE_1M_CAPABILITY_MASK (0x10UL)
#define CFG_PRIV1_RESIZEBAR_CAP_SIZE_1M_CAPABILITY_SHIFT (4UL)
#define CFG_PRIV1_RESIZEBAR_CAP_SIZE_CAPABILITY_MASK (0xfUL)
#define CFG_PRIV1_RESIZEBAR_CAP_SIZE_CAPABILITY_SHIFT (0UL)
#define CFG_PRIV1_RESIZEBAR_CAP_RESERVED0_MASK (0xff000000UL)
#define CFG_PRIV1_RESIZEBAR_CAP_RESERVED0_SHIFT (24UL)




typedef uint32_t CFG_PRIV1_ARI_CAP_TYPE;
#define CFG_PRIV1_ARI_CAP_NEXT_FUNCTION_NUMBER_MASK (0xffUL)
#define CFG_PRIV1_ARI_CAP_NEXT_FUNCTION_NUMBER_SHIFT (0UL)
#define CFG_PRIV1_ARI_CAP_RESERVED0_MASK (0xffffff00UL)
#define CFG_PRIV1_ARI_CAP_RESERVED0_SHIFT (8UL)




typedef uint32_t CFG_PRIV1_INITVF_TYPE;
#define CFG_PRIV1_INITVF_RESERVED_MASK (0xffffffffUL)
#define CFG_PRIV1_INITVF_RESERVED_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_VF_OFFSET_TYPE;
#define CFG_PRIV1_VF_OFFSET_RESERVED_MASK (0xffffffffUL)
#define CFG_PRIV1_VF_OFFSET_RESERVED_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_VF_BAR_REG_TYPE;
#define CFG_PRIV1_VF_BAR_REG_RESERVED_MASK (0xffffffffUL)
#define CFG_PRIV1_VF_BAR_REG_RESERVED_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_VF_SUPP_PAGE_SIZE_TYPE;
#define CFG_PRIV1_VF_SUPP_PAGE_SIZE_RESERVED_MASK (0xffffffffUL)
#define CFG_PRIV1_VF_SUPP_PAGE_SIZE_RESERVED_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_VF_CAP_EN_TYPE;
#define CFG_PRIV1_VF_CAP_EN_RESERVED_MASK (0xffffffffUL)
#define CFG_PRIV1_VF_CAP_EN_RESERVED_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_VF_MSIX_TBL_BIR_OFF_TYPE;
#define CFG_PRIV1_VF_MSIX_TBL_BIR_OFF_RESERVED_MASK (0xffffffffUL)
#define CFG_PRIV1_VF_MSIX_TBL_BIR_OFF_RESERVED_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_VF_MSIX_PBA_OFF_BIR_TYPE;
#define CFG_PRIV1_VF_MSIX_PBA_OFF_BIR_RESERVED_MASK (0xffffffffUL)
#define CFG_PRIV1_VF_MSIX_PBA_OFF_BIR_RESERVED_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_VF_MSIX_CONTROL_TYPE;
#define CFG_PRIV1_VF_MSIX_CONTROL_RESERVED_MASK (0xffffffffUL)
#define CFG_PRIV1_VF_MSIX_CONTROL_RESERVED_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_VF_BAR4_REG_TYPE;
#define CFG_PRIV1_VF_BAR4_REG_VFBAR4_PREFETCH_MASK (0x20UL)
#define CFG_PRIV1_VF_BAR4_REG_VFBAR4_PREFETCH_SHIFT (5UL)
#define CFG_PRIV1_VF_BAR4_REG_VFBAR4_64ENA_MASK (0x10UL)
#define CFG_PRIV1_VF_BAR4_REG_VFBAR4_64ENA_SHIFT (4UL)
#define CFG_PRIV1_VF_BAR4_REG_BAR4_SIZE_OF_VF_MASK (0xfUL)
#define CFG_PRIV1_VF_BAR4_REG_BAR4_SIZE_OF_VF_SHIFT (0UL)
#define CFG_PRIV1_VF_BAR4_REG_RESERVED0_MASK (0xffffffc0UL)
#define CFG_PRIV1_VF_BAR4_REG_RESERVED0_SHIFT (6UL)




typedef uint32_t CFG_PRIV1_PF_INITVF_TYPE;
#define CFG_PRIV1_PF_INITVF_FIRST_VF_NUM_MASK (0x1fUL)
#define CFG_PRIV1_PF_INITVF_FIRST_VF_NUM_SHIFT (0UL)
#define CFG_PRIV1_PF_INITVF_RESERVED0_MASK (0xffffffe0UL)
#define CFG_PRIV1_PF_INITVF_RESERVED0_SHIFT (5UL)




typedef uint32_t CFG_PRIV1_VF_NSP_TYPE;
#define CFG_PRIV1_VF_NSP_PF_VFBAR4_NSP_MASK (0xf00UL)
#define CFG_PRIV1_VF_NSP_PF_VFBAR4_NSP_SHIFT (8UL)
#define CFG_PRIV1_VF_NSP_PF_VFBAR2_NSP_MASK (0xf0UL)
#define CFG_PRIV1_VF_NSP_PF_VFBAR2_NSP_SHIFT (4UL)
#define CFG_PRIV1_VF_NSP_PF_VFBAR0_NSP_MASK (0xfUL)
#define CFG_PRIV1_VF_NSP_PF_VFBAR0_NSP_SHIFT (0UL)
#define CFG_PRIV1_VF_NSP_RESERVED0_MASK (0xfffff000UL)
#define CFG_PRIV1_VF_NSP_RESERVED0_SHIFT (12UL)




typedef uint32_t CFG_PRIV1_ATS_INLD_QUEUE_DEPTH_TYPE;
#define CFG_PRIV1_ATS_INLD_QUEUE_DEPTH_RESERVED_MASK (0xffffffffUL)
#define CFG_PRIV1_ATS_INLD_QUEUE_DEPTH_RESERVED_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_VFTPH_CAP_TYPE;
#define CFG_PRIV1_VFTPH_CAP_TPH_SUPP_INVF_MASK (0x80000000UL)
#define CFG_PRIV1_VFTPH_CAP_TPH_SUPP_INVF_SHIFT (31UL)
#define CFG_PRIV1_VFTPH_CAP_VFTPH_ST_TABLE_SIZE_MASK (0x7ff0UL)
#define CFG_PRIV1_VFTPH_CAP_VFTPH_ST_TABLE_SIZE_SHIFT (4UL)
#define CFG_PRIV1_VFTPH_CAP_VFTPH_ST_TABLE_LOCATION_MASK (0xcUL)
#define CFG_PRIV1_VFTPH_CAP_VFTPH_ST_TABLE_LOCATION_SHIFT (2UL)
#define CFG_PRIV1_VFTPH_CAP_VFTPH_DEV_SPEC_MODE_MASK (0x2UL)
#define CFG_PRIV1_VFTPH_CAP_VFTPH_DEV_SPEC_MODE_SHIFT (1UL)
#define CFG_PRIV1_VFTPH_CAP_VFTPH_INT_VEC_MODE_SUPP_MASK (0x1UL)
#define CFG_PRIV1_VFTPH_CAP_VFTPH_INT_VEC_MODE_SUPP_SHIFT (0UL)
#define CFG_PRIV1_VFTPH_CAP_RESERVED0_MASK (0x7fff8000UL)
#define CFG_PRIV1_VFTPH_CAP_RESERVED0_SHIFT (15UL)




typedef uint32_t CFG_PRIV1_PSEC0A_TYPE;
#define CFG_PRIV1_PSEC0A_DP_TX_PRESET_0_MASK (0xfUL)
#define CFG_PRIV1_PSEC0A_DP_TX_PRESET_0_SHIFT (0UL)
#define CFG_PRIV1_PSEC0A_DP_RX_PRESET_HINT_0_MASK (0x70UL)
#define CFG_PRIV1_PSEC0A_DP_RX_PRESET_HINT_0_SHIFT (4UL)
#define CFG_PRIV1_PSEC0A_RESERVED_DP_0_MASK (0x80UL)
#define CFG_PRIV1_PSEC0A_RESERVED_DP_0_SHIFT (7UL)
#define CFG_PRIV1_PSEC0A_DP_UPTX_PRESET_0_MASK (0xf00UL)
#define CFG_PRIV1_PSEC0A_DP_UPTX_PRESET_0_SHIFT (8UL)
#define CFG_PRIV1_PSEC0A_DP_UPRX_PRESET_HINT_0_MASK (0x7000UL)
#define CFG_PRIV1_PSEC0A_DP_UPRX_PRESET_HINT_0_SHIFT (12UL)
#define CFG_PRIV1_PSEC0A_RESERVED_UP_0_MASK (0x8000UL)
#define CFG_PRIV1_PSEC0A_RESERVED_UP_0_SHIFT (15UL)
#define CFG_PRIV1_PSEC0A_DP_TX_PRESET_1_MASK (0xf0000UL)
#define CFG_PRIV1_PSEC0A_DP_TX_PRESET_1_SHIFT (16UL)
#define CFG_PRIV1_PSEC0A_DP_RX_PRESET_HINT_1_MASK (0x700000UL)
#define CFG_PRIV1_PSEC0A_DP_RX_PRESET_HINT_1_SHIFT (20UL)
#define CFG_PRIV1_PSEC0A_RESERVED_DP_1_MASK (0x800000UL)
#define CFG_PRIV1_PSEC0A_RESERVED_DP_1_SHIFT (23UL)
#define CFG_PRIV1_PSEC0A_DP_UPTX_PRESET_1_MASK (0xf000000UL)
#define CFG_PRIV1_PSEC0A_DP_UPTX_PRESET_1_SHIFT (24UL)
#define CFG_PRIV1_PSEC0A_DP_UPRX_PRESET_HINT_1_MASK (0x70000000UL)
#define CFG_PRIV1_PSEC0A_DP_UPRX_PRESET_HINT_1_SHIFT (28UL)
#define CFG_PRIV1_PSEC0A_RESERVED_UP_1_MASK (0x80000000UL)
#define CFG_PRIV1_PSEC0A_RESERVED_UP_1_SHIFT (31UL)




typedef uint32_t CFG_PRIV1_PSEC2A_TYPE;
#define CFG_PRIV1_PSEC2A_DP_TX_PRESET_2_MASK (0xfUL)
#define CFG_PRIV1_PSEC2A_DP_TX_PRESET_2_SHIFT (0UL)
#define CFG_PRIV1_PSEC2A_DP_RX_PRESET_HINT_2_MASK (0x70UL)
#define CFG_PRIV1_PSEC2A_DP_RX_PRESET_HINT_2_SHIFT (4UL)
#define CFG_PRIV1_PSEC2A_RESERVED_DP_2_MASK (0x80UL)
#define CFG_PRIV1_PSEC2A_RESERVED_DP_2_SHIFT (7UL)
#define CFG_PRIV1_PSEC2A_DP_UPTX_PRESET_2_MASK (0xf00UL)
#define CFG_PRIV1_PSEC2A_DP_UPTX_PRESET_2_SHIFT (8UL)
#define CFG_PRIV1_PSEC2A_DP_UPRX_PRESET_HINT_2_MASK (0x7000UL)
#define CFG_PRIV1_PSEC2A_DP_UPRX_PRESET_HINT_2_SHIFT (12UL)
#define CFG_PRIV1_PSEC2A_RESERVED_UP_2_MASK (0x8000UL)
#define CFG_PRIV1_PSEC2A_RESERVED_UP_2_SHIFT (15UL)
#define CFG_PRIV1_PSEC2A_DP_TX_PRESET_3_MASK (0xf0000UL)
#define CFG_PRIV1_PSEC2A_DP_TX_PRESET_3_SHIFT (16UL)
#define CFG_PRIV1_PSEC2A_DP_RX_PRESET_HINT_3_MASK (0x700000UL)
#define CFG_PRIV1_PSEC2A_DP_RX_PRESET_HINT_3_SHIFT (20UL)
#define CFG_PRIV1_PSEC2A_RESERVED_DP_3_MASK (0x800000UL)
#define CFG_PRIV1_PSEC2A_RESERVED_DP_3_SHIFT (23UL)
#define CFG_PRIV1_PSEC2A_DP_UPTX_PRESET_3_MASK (0xf000000UL)
#define CFG_PRIV1_PSEC2A_DP_UPTX_PRESET_3_SHIFT (24UL)
#define CFG_PRIV1_PSEC2A_DP_UPRX_PRESET_HINT_3_MASK (0x70000000UL)
#define CFG_PRIV1_PSEC2A_DP_UPRX_PRESET_HINT_3_SHIFT (28UL)
#define CFG_PRIV1_PSEC2A_RESERVED_UP_3_MASK (0x80000000UL)
#define CFG_PRIV1_PSEC2A_RESERVED_UP_3_SHIFT (31UL)




typedef uint32_t CFG_PRIV1_PCIER_SECPCIE_EQ_CONTROL_4_ADDR_TYPE;
#define CFG_PRIV1_PCIER_SECPCIE_EQ_CONTROL_4_ADDR_RESERVED_LANE45_MASK (0xffffffffUL)
#define CFG_PRIV1_PCIER_SECPCIE_EQ_CONTROL_4_ADDR_RESERVED_LANE45_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_PCIER_SECPCIE_EQ_CONTROL_6_ADDR_TYPE;
#define CFG_PRIV1_PCIER_SECPCIE_EQ_CONTROL_6_ADDR_RESERVED_LANE67_MASK (0xffffffffUL)
#define CFG_PRIV1_PCIER_SECPCIE_EQ_CONTROL_6_ADDR_RESERVED_LANE67_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_PCIER_SECPCIE_EQ_CONTROL_8_ADDR_TYPE;
#define CFG_PRIV1_PCIER_SECPCIE_EQ_CONTROL_8_ADDR_RESERVED_LANE89_MASK (0xffffffffUL)
#define CFG_PRIV1_PCIER_SECPCIE_EQ_CONTROL_8_ADDR_RESERVED_LANE89_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_PSEC10A_TYPE;
#define CFG_PRIV1_PSEC10A_RESERVED_LANE1011_MASK (0xffffffffUL)
#define CFG_PRIV1_PSEC10A_RESERVED_LANE1011_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_PSEC12A_TYPE;
#define CFG_PRIV1_PSEC12A_RESERVED_LANE1213_MASK (0xffffffffUL)
#define CFG_PRIV1_PSEC12A_RESERVED_LANE1213_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_PSEC14A_TYPE;
#define CFG_PRIV1_PSEC14A_RESERVED_LANE1415_MASK (0xffffffffUL)
#define CFG_PRIV1_PSEC14A_RESERVED_LANE1415_SHIFT (0UL)




typedef uint32_t CFG_PRIV1_PSEC24A_TYPE;
#define CFG_PRIV1_PSEC24A_DP_G4TX_PRESET_8_MASK (0xfUL)
#define CFG_PRIV1_PSEC24A_DP_G4TX_PRESET_8_SHIFT (0UL)
#define CFG_PRIV1_PSEC24A_DP_G4UPTX_PRESET_8_MASK (0xf0UL)
#define CFG_PRIV1_PSEC24A_DP_G4UPTX_PRESET_8_SHIFT (4UL)
#define CFG_PRIV1_PSEC24A_DP_G4TX_PRESET_9_MASK (0xf00UL)
#define CFG_PRIV1_PSEC24A_DP_G4TX_PRESET_9_SHIFT (8UL)
#define CFG_PRIV1_PSEC24A_DP_G4UPTX_PRESET_9_MASK (0xf000UL)
#define CFG_PRIV1_PSEC24A_DP_G4UPTX_PRESET_9_SHIFT (12UL)
#define CFG_PRIV1_PSEC24A_DP_G4TX_PRESET_10_MASK (0xf0000UL)
#define CFG_PRIV1_PSEC24A_DP_G4TX_PRESET_10_SHIFT (16UL)
#define CFG_PRIV1_PSEC24A_DP_G4UPTX_PRESET_10_MASK (0xf00000UL)
#define CFG_PRIV1_PSEC24A_DP_G4UPTX_PRESET_10_SHIFT (20UL)
#define CFG_PRIV1_PSEC24A_DP_G4TX_PRESET_11_MASK (0xf000000UL)
#define CFG_PRIV1_PSEC24A_DP_G4TX_PRESET_11_SHIFT (24UL)
#define CFG_PRIV1_PSEC24A_DP_G4UPTX_PRESET_11_MASK (0xf0000000UL)
#define CFG_PRIV1_PSEC24A_DP_G4UPTX_PRESET_11_SHIFT (28UL)




typedef uint32_t CFG_PRIV1_PSEC26A_TYPE;
#define CFG_PRIV1_PSEC26A_DP_G4TX_PRESET_12_MASK (0xfUL)
#define CFG_PRIV1_PSEC26A_DP_G4TX_PRESET_12_SHIFT (0UL)
#define CFG_PRIV1_PSEC26A_DP_G4UPTX_PRESET_12_MASK (0xf0UL)
#define CFG_PRIV1_PSEC26A_DP_G4UPTX_PRESET_12_SHIFT (4UL)
#define CFG_PRIV1_PSEC26A_DP_G4TX_PRESET_13_MASK (0xf00UL)
#define CFG_PRIV1_PSEC26A_DP_G4TX_PRESET_13_SHIFT (8UL)
#define CFG_PRIV1_PSEC26A_DP_G4UPTX_PRESET_13_MASK (0xf000UL)
#define CFG_PRIV1_PSEC26A_DP_G4UPTX_PRESET_13_SHIFT (12UL)
#define CFG_PRIV1_PSEC26A_DP_G4TX_PRESET_14_MASK (0xf0000UL)
#define CFG_PRIV1_PSEC26A_DP_G4TX_PRESET_14_SHIFT (16UL)
#define CFG_PRIV1_PSEC26A_DP_G4UPTX_PRESET_14_MASK (0xf00000UL)
#define CFG_PRIV1_PSEC26A_DP_G4UPTX_PRESET_14_SHIFT (20UL)
#define CFG_PRIV1_PSEC26A_DP_G4TX_PRESET_15_MASK (0xf000000UL)
#define CFG_PRIV1_PSEC26A_DP_G4TX_PRESET_15_SHIFT (24UL)
#define CFG_PRIV1_PSEC26A_DP_G4UPTX_PRESET_15_MASK (0xf0000000UL)
#define CFG_PRIV1_PSEC26A_DP_G4UPTX_PRESET_15_SHIFT (28UL)




typedef volatile struct sCFG_PRIV1_RDBType {
    CFG_PRIV1_VPD_INTF_TYPE vpd_intf; /* OFFSET: 0x0 */
    CFG_PRIV1_VPD_ADDR_FLAG_TYPE vpd_addr_flag; /* OFFSET: 0x4 */
    CFG_PRIV1_VPD_DATA_TYPE vpd_data; /* OFFSET: 0x8 */
    CFG_PRIV1_ID_VAL1_TYPE id_val1; /* OFFSET: 0xc */
    CFG_PRIV1_ID_VAL2_TYPE id_val2; /* OFFSET: 0x10 */
    CFG_PRIV1_ID_VAL3_TYPE id_val3; /* OFFSET: 0x14 */
    CFG_PRIV1_ID_VAL4_TYPE id_val4; /* OFFSET: 0x18 */
    CFG_PRIV1_ID_VAL5_TYPE id_val5; /* OFFSET: 0x1c */
    CFG_PRIV1_UNUSED_H_TYPE unused_h; /* OFFSET: 0x20 */
    CFG_PRIV1_ID_VAL6_TYPE id_val6; /* OFFSET: 0x24 */
    CFG_PRIV1_MSI_DATA_TYPE msi_data; /* OFFSET: 0x28 */
    CFG_PRIV1_MSI_ADDR_H_TYPE msi_addr_h; /* OFFSET: 0x2c */
    CFG_PRIV1_MSI_ADDR_L_TYPE msi_addr_l; /* OFFSET: 0x30 */
    CFG_PRIV1_RESERVED_TYPE rsvd0[8]; /* OFFSET: 0x34 */
    CFG_PRIV1_MSI_MASK_TYPE msi_mask; /* OFFSET: 0x3c */
    CFG_PRIV1_MSI_PEND_TYPE msi_pend; /* OFFSET: 0x40 */
    CFG_PRIV1_PM_DATA_C_TYPE pm_data_c; /* OFFSET: 0x44 */
    CFG_PRIV1_RESERVED_TYPE rsvd1[80]; /* OFFSET: 0x48 */
    CFG_PRIV1_MSIX_CONTROL_TYPE msix_control; /* OFFSET: 0x98 */
    CFG_PRIV1_MSIX_TBL_OFF_BIR_TYPE msix_tbl_off_bir; /* OFFSET: 0x9c */
    CFG_PRIV1_MSIX_PBA_OFF_BIR_TYPE msix_pba_off_bir; /* OFFSET: 0xa0 */
    CFG_PRIV1_UNUSED_K_TYPE unused_k; /* OFFSET: 0xa4 */
    CFG_PRIV1_PCIE_CAPABILITY_TYPE pcie_capability; /* OFFSET: 0xa8 */
    CFG_PRIV1_DEVICE_CAPABILITY_TYPE device_capability; /* OFFSET: 0xac */
    CFG_PRIV1_DEVICE_CONTROL_TYPE device_control; /* OFFSET: 0xb0 */
    CFG_PRIV1_LINK_CAPABILITY_TYPE link_capability; /* OFFSET: 0xb4 */
    CFG_PRIV1_BAR2_CONFIG_TYPE bar2_config; /* OFFSET: 0xb8 */
    CFG_PRIV1_PCIE_DEVICE_CAPABILITY_2_TYPE pcie_device_capability_2; /* OFFSET: 0xbc */
    CFG_PRIV1_PCIE_LINK_CAPABILITY_2_TYPE pcie_link_capability_2; /* OFFSET: 0xc0 */
    CFG_PRIV1_PCIE_LINK_CONTROL_TYPE pcie_link_control; /* OFFSET: 0xc4 */
    CFG_PRIV1_PCIE_LINK_CAPABILITY_RC_TYPE pcie_link_capability_rc; /* OFFSET: 0xc8 */
    CFG_PRIV1_BAR3_CONFIG_TYPE bar3_config; /* OFFSET: 0xcc */
    CFG_PRIV1_ROOT_CAP_TYPE root_cap; /* OFFSET: 0xd0 */
    CFG_PRIV1_ROOT_CONTROL_TYPE root_control; /* OFFSET: 0xd4 */
    CFG_PRIV1_DEV_SER_NUM_CAP_ID_TYPE dev_ser_num_cap_id; /* OFFSET: 0xd8 */
    CFG_PRIV1_LOWER_SER_NUM_TYPE lower_ser_num; /* OFFSET: 0xdc */
    CFG_PRIV1_UPPER_SER_NUM_TYPE upper_ser_num; /* OFFSET: 0xe0 */
    CFG_PRIV1_ADV_ERR_CAP_TYPE adv_err_cap; /* OFFSET: 0xe4 */
    CFG_PRIV1_PWR_BDGT_DATA_0_TYPE pwr_bdgt_data_0; /* OFFSET: 0xe8 */
    CFG_PRIV1_PWR_BDGT_DATA_1_TYPE pwr_bdgt_data_1; /* OFFSET: 0xec */
    CFG_PRIV1_PWR_BDGT_DATA_2_TYPE pwr_bdgt_data_2; /* OFFSET: 0xf0 */
    CFG_PRIV1_PWR_BDGT_DATA_3_TYPE pwr_bdgt_data_3; /* OFFSET: 0xf4 */
    CFG_PRIV1_PWR_BDGT_DATA_4_TYPE pwr_bdgt_data_4; /* OFFSET: 0xf8 */
    CFG_PRIV1_PWR_BDGT_DATA_5_TYPE pwr_bdgt_data_5; /* OFFSET: 0xfc */
    CFG_PRIV1_PWR_BDGT_DATA_6_TYPE pwr_bdgt_data_6; /* OFFSET: 0x100 */
    CFG_PRIV1_PWR_BDGT_DATA_7_TYPE pwr_bdgt_data_7; /* OFFSET: 0x104 */
    CFG_PRIV1_EXT2_CAP_ADDR_TYPE ext2_cap_addr; /* OFFSET: 0x108 */
    CFG_PRIV1_PWR_BDGT_DATA_8_TYPE pwr_bdgt_data_8; /* OFFSET: 0x10c */
    CFG_PRIV1_RESERVED_TYPE rsvd2[8]; /* OFFSET: 0x110 */
    CFG_PRIV1_L1SUB_CAP_TYPE l1sub_cap; /* OFFSET: 0x118 */
    CFG_PRIV1_L1SUB_EXT_CAP_TYPE l1sub_ext_cap; /* OFFSET: 0x11c */
    CFG_PRIV1_MARGIN_PORT_CAP_STATUS_TYPE margin_port_cap_status; /* OFFSET: 0x120 */
    CFG_PRIV1_RESERVED_TYPE rsvd3[4]; /* OFFSET: 0x124 */
    CFG_PRIV1_PWR_BDGT_CAPABILITY_TYPE pwr_bdgt_capability; /* OFFSET: 0x128 */
    CFG_PRIV1_VSEC_HDR_TYPE vsec_hdr; /* OFFSET: 0x12c */
    CFG_PRIV1_RC_USER_MEM_LO1_TYPE rc_user_mem_lo1; /* OFFSET: 0x130 */
    CFG_PRIV1_RC_USER_MEM_HI1_TYPE rc_user_mem_hi1; /* OFFSET: 0x134 */
    CFG_PRIV1_RC_USER_MEM_LO2_TYPE rc_user_mem_lo2; /* OFFSET: 0x138 */
    CFG_PRIV1_RC_USER_MEM_HI2_TYPE rc_user_mem_hi2; /* OFFSET: 0x13c */
    CFG_PRIV1_RESERVED_TYPE rsvd4[132]; /* OFFSET: 0x140 */
    CFG_PRIV1_PCIER_MC_WINDOW_SIZE_REQ_TYPE pcier_mc_window_size_req; /* OFFSET: 0x1c4 */
    CFG_PRIV1_PTM_CAP_TYPE ptm_cap; /* OFFSET: 0x1c8 */
    CFG_PRIV1_TPH_CAP_TYPE tph_cap; /* OFFSET: 0x1cc */
    CFG_PRIV1_RESIZEBAR_CAP_TYPE resizebar_cap; /* OFFSET: 0x1d0 */
    CFG_PRIV1_ARI_CAP_TYPE ari_cap; /* OFFSET: 0x1d4 */
    CFG_PRIV1_INITVF_TYPE initvf; /* OFFSET: 0x1d8 */
    CFG_PRIV1_VF_OFFSET_TYPE vf_offset; /* OFFSET: 0x1dc */
    CFG_PRIV1_VF_BAR_REG_TYPE vf_bar_reg; /* OFFSET: 0x1e0 */
    CFG_PRIV1_VF_SUPP_PAGE_SIZE_TYPE vf_supp_page_size; /* OFFSET: 0x1e4 */
    CFG_PRIV1_VF_CAP_EN_TYPE vf_cap_en; /* OFFSET: 0x1e8 */
    CFG_PRIV1_VF_MSIX_TBL_BIR_OFF_TYPE vf_msix_tbl_bir_off; /* OFFSET: 0x1ec */
    CFG_PRIV1_VF_MSIX_PBA_OFF_BIR_TYPE vf_msix_pba_off_bir; /* OFFSET: 0x1f0 */
    CFG_PRIV1_VF_MSIX_CONTROL_TYPE vf_msix_control; /* OFFSET: 0x1f4 */
    CFG_PRIV1_VF_BAR4_REG_TYPE vf_bar4_reg; /* OFFSET: 0x1f8 */
    CFG_PRIV1_PF_INITVF_TYPE pf_initvf; /* OFFSET: 0x1fc */
    CFG_PRIV1_VF_NSP_TYPE vf_nsp; /* OFFSET: 0x200 */
    CFG_PRIV1_RESERVED_TYPE rsvd5[4]; /* OFFSET: 0x204 */
    CFG_PRIV1_ATS_INLD_QUEUE_DEPTH_TYPE ats_inld_queue_depth; /* OFFSET: 0x208 */
    CFG_PRIV1_VFTPH_CAP_TYPE vftph_cap; /* OFFSET: 0x20c */
    CFG_PRIV1_PSEC0A_TYPE pcier_secpcie_eq_control_0_addr; /* OFFSET: 0x210 */
    CFG_PRIV1_PSEC2A_TYPE pcier_secpcie_eq_control_2_addr; /* OFFSET: 0x214 */
    CFG_PRIV1_PCIER_SECPCIE_EQ_CONTROL_4_ADDR_TYPE pcier_secpcie_eq_control_4_addr; /* OFFSET: 0x218 */
    CFG_PRIV1_PCIER_SECPCIE_EQ_CONTROL_6_ADDR_TYPE pcier_secpcie_eq_control_6_addr; /* OFFSET: 0x21c */
    CFG_PRIV1_PCIER_SECPCIE_EQ_CONTROL_8_ADDR_TYPE pcier_secpcie_eq_control_8_addr; /* OFFSET: 0x220 */
    CFG_PRIV1_PSEC10A_TYPE pcier_secpcie_eq_control_10_addr; /* OFFSET: 0x224 */
    CFG_PRIV1_PSEC12A_TYPE pcier_secpcie_eq_control_12_addr; /* OFFSET: 0x228 */
    CFG_PRIV1_PSEC14A_TYPE pcier_secpcie_eq_control_14_addr; /* OFFSET: 0x22c */
    CFG_PRIV1_RESERVED_TYPE rsvd6[32]; /* OFFSET: 0x230 */
    CFG_PRIV1_PSEC24A_TYPE pcier_secpcie_eq_control2_4_addr; /* OFFSET: 0x250 */
    CFG_PRIV1_PSEC26A_TYPE pcier_secpcie_eq_control2_6_addr; /* OFFSET: 0x254 */
} CFG_PRIV1_RDBType;


#define CFG_PRIVB0_BASE                 ((uintptr_t)(0xE02D2428UL))

#define CFG_PRIVB1_BASE                 ((uintptr_t)(0xE02D2428UL))



#define CFG_PRIV1_MAX_HW_ID             (2UL)


#define CFG_PRIV1_BASE                  (CFG_PRIVB0_BASE)

#endif /* CFG_PRIV1_RDB_H */
