/*****************************************************************************
 Copyright 2025 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file cfg_priv0_rdb.h
    @brief RDB File for CFG_PRIV0

    @version BCM89580_A0_20230125_RDB
*/

#ifndef CFG_PRIV0_RDB_H
#define CFG_PRIV0_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t CFG_PRIV0_UNUSED_F_TYPE;
#define CFG_PRIV0_UNUSED_F_RESERVED_MASK (0xffffffffUL)
#define CFG_PRIV0_UNUSED_F_RESERVED_SHIFT (0UL)




typedef uint32_t CFG_PRIV0_CONFIG_2_TYPE;
#define CFG_PRIV0_CONFIG_2_RESERVED0_MASK (0xfffe0000UL)
#define CFG_PRIV0_CONFIG_2_RESERVED0_SHIFT (17UL)
#define CFG_PRIV0_CONFIG_2_BAR_PREFETCH_MASK (0x10000UL)
#define CFG_PRIV0_CONFIG_2_BAR_PREFETCH_SHIFT (16UL)
#define CFG_PRIV0_CONFIG_2_ROM_BAR_SIZE_MASK (0xff00UL)
#define CFG_PRIV0_CONFIG_2_ROM_BAR_SIZE_SHIFT (8UL)
#define CFG_PRIV0_CONFIG_2_FIRST_CFG_DONE_MASK (0x80UL)
#define CFG_PRIV0_CONFIG_2_FIRST_CFG_DONE_SHIFT (7UL)
#define CFG_PRIV0_CONFIG_2_CFG_CYCLE_RETRY_MASK (0x40UL)
#define CFG_PRIV0_CONFIG_2_CFG_CYCLE_RETRY_SHIFT (6UL)
#define CFG_PRIV0_CONFIG_2_EXP_ROM_RETRY_MASK (0x20UL)
#define CFG_PRIV0_CONFIG_2_EXP_ROM_RETRY_SHIFT (5UL)
#define CFG_PRIV0_CONFIG_2_BAR1_64ENA_MASK (0x10UL)
#define CFG_PRIV0_CONFIG_2_BAR1_64ENA_SHIFT (4UL)
#define CFG_PRIV0_CONFIG_2_BAR1_SIZE_MASK (0xfUL)
#define CFG_PRIV0_CONFIG_2_BAR1_SIZE_SHIFT (0UL)




typedef uint32_t CFG_PRIV0_CONFIG_3_TYPE;
#define CFG_PRIV0_CONFIG_3_PCI_POWER_MASK (0x80000000UL)
#define CFG_PRIV0_CONFIG_3_PCI_POWER_SHIFT (31UL)
#define CFG_PRIV0_CONFIG_3_VAUX_PRESENT_MASK (0x40000000UL)
#define CFG_PRIV0_CONFIG_3_VAUX_PRESENT_SHIFT (30UL)
#define CFG_PRIV0_CONFIG_3_PM_STATE_MASK (0x18000000UL)
#define CFG_PRIV0_CONFIG_3_PM_STATE_SHIFT (27UL)
#define CFG_PRIV0_CONFIG_3_PME_ENABLE_MASK (0x4000000UL)
#define CFG_PRIV0_CONFIG_3_PME_ENABLE_SHIFT (26UL)
#define CFG_PRIV0_CONFIG_3_PME_STATUS_MASK (0x2000000UL)
#define CFG_PRIV0_CONFIG_3_PME_STATUS_SHIFT (25UL)
#define CFG_PRIV0_CONFIG_3_FORCE_PME_MASK (0x1000000UL)
#define CFG_PRIV0_CONFIG_3_FORCE_PME_SHIFT (24UL)
#define CFG_PRIV0_CONFIG_3_REG_STICKY_BYTE_MASK (0xff00UL)
#define CFG_PRIV0_CONFIG_3_REG_STICKY_BYTE_SHIFT (8UL)
#define CFG_PRIV0_CONFIG_3_STICKY_BYTE_MASK (0xffUL)
#define CFG_PRIV0_CONFIG_3_STICKY_BYTE_SHIFT (0UL)
#define CFG_PRIV0_CONFIG_3_RESERVED0_MASK (0xff0000UL)
#define CFG_PRIV0_CONFIG_3_RESERVED0_SHIFT (16UL)
#define CFG_PRIV0_CONFIG_3_RESERVED1_MASK (0x20000000UL)
#define CFG_PRIV0_CONFIG_3_RESERVED1_SHIFT (29UL)




typedef uint32_t CFG_PRIV0_PM_DATA_A_TYPE;
#define CFG_PRIV0_PM_DATA_A_3_PRG_MASK (0xff000000UL)
#define CFG_PRIV0_PM_DATA_A_3_PRG_SHIFT (24UL)
#define CFG_PRIV0_PM_DATA_A_2_PRG_MASK (0xff0000UL)
#define CFG_PRIV0_PM_DATA_A_2_PRG_SHIFT (16UL)
#define CFG_PRIV0_PM_DATA_A_1_PRG_MASK (0xff00UL)
#define CFG_PRIV0_PM_DATA_A_1_PRG_SHIFT (8UL)
#define CFG_PRIV0_PM_DATA_A_0_PRG_MASK (0xffUL)
#define CFG_PRIV0_PM_DATA_A_0_PRG_SHIFT (0UL)




typedef uint32_t CFG_PRIV0_PM_DATA_B_TYPE;
#define CFG_PRIV0_PM_DATA_B_7_PRG_MASK (0xff000000UL)
#define CFG_PRIV0_PM_DATA_B_7_PRG_SHIFT (24UL)
#define CFG_PRIV0_PM_DATA_B_6_PRG_MASK (0xff0000UL)
#define CFG_PRIV0_PM_DATA_B_6_PRG_SHIFT (16UL)
#define CFG_PRIV0_PM_DATA_B_5_PRG_MASK (0xff00UL)
#define CFG_PRIV0_PM_DATA_B_5_PRG_SHIFT (8UL)
#define CFG_PRIV0_PM_DATA_B_4_PRG_MASK (0xffUL)
#define CFG_PRIV0_PM_DATA_B_4_PRG_SHIFT (0UL)




typedef uint32_t CFG_PRIV0_PCI_EXTENDED_BAR_SIZE_TYPE;
#define CFG_PRIV0_PCI_EXTENDED_BAR_SIZE_3_SIZE_LOEXT_MASK (0x380000UL)
#define CFG_PRIV0_PCI_EXTENDED_BAR_SIZE_3_SIZE_LOEXT_SHIFT (19UL)
#define CFG_PRIV0_PCI_EXTENDED_BAR_SIZE_2_SIZE_LOEXT_MASK (0x70000UL)
#define CFG_PRIV0_PCI_EXTENDED_BAR_SIZE_2_SIZE_LOEXT_SHIFT (16UL)
#define CFG_PRIV0_PCI_EXTENDED_BAR_SIZE_1_SIZE_LOEXT_MASK (0x7000UL)
#define CFG_PRIV0_PCI_EXTENDED_BAR_SIZE_1_SIZE_LOEXT_SHIFT (12UL)
#define CFG_PRIV0_PCI_EXTENDED_BAR_SIZE_3_SIZE_HIEXT_MASK (0xf00UL)
#define CFG_PRIV0_PCI_EXTENDED_BAR_SIZE_3_SIZE_HIEXT_SHIFT (8UL)
#define CFG_PRIV0_PCI_EXTENDED_BAR_SIZE_2_SIZE_HIEXT_MASK (0xf0UL)
#define CFG_PRIV0_PCI_EXTENDED_BAR_SIZE_2_SIZE_HIEXT_SHIFT (4UL)
#define CFG_PRIV0_PCI_EXTENDED_BAR_SIZE_1_SIZE_HIEXT_MASK (0xfUL)
#define CFG_PRIV0_PCI_EXTENDED_BAR_SIZE_1_SIZE_HIEXT_SHIFT (0UL)
#define CFG_PRIV0_PCI_EXTENDED_BAR_SIZE_RESERVED0_MASK (0x8000UL)
#define CFG_PRIV0_PCI_EXTENDED_BAR_SIZE_RESERVED0_SHIFT (15UL)
#define CFG_PRIV0_PCI_EXTENDED_BAR_SIZE_RESERVED1_MASK (0xffc00000UL)
#define CFG_PRIV0_PCI_EXTENDED_BAR_SIZE_RESERVED1_SHIFT (22UL)




typedef volatile struct sCFG_PRIV0_RDBType {
    CFG_PRIV0_UNUSED_F_TYPE unused_f; /* OFFSET: 0x0 */
    CFG_PRIV0_CONFIG_2_TYPE config_2; /* OFFSET: 0x4 */
    CFG_PRIV0_CONFIG_3_TYPE config_3; /* OFFSET: 0x8 */
    CFG_PRIV0_PM_DATA_A_TYPE pm_data_a; /* OFFSET: 0xc */
    CFG_PRIV0_PM_DATA_B_TYPE pm_data_b; /* OFFSET: 0x10 */
    CFG_PRIV0_PCI_EXTENDED_BAR_SIZE_TYPE pci_extended_bar_size; /* OFFSET: 0x14 */
} CFG_PRIV0_RDBType;


#define CFG_PRIVA0_BASE                 ((uintptr_t)(0xE02D2404UL))

#define CFG_PRIVA1_BASE                 ((uintptr_t)(0xE02D2404UL))



#define CFG_PRIV0_MAX_HW_ID             (2UL)


#define CFG_PRIV0_BASE                  (CFG_PRIVA0_BASE)

#endif /* CFG_PRIV0_RDB_H */
