/*****************************************************************************
 Copyright 2025 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file pcie_common_rdb.h
    @brief RDB File for PCIE_COMMON

    @version BCM89580_A0_20230125_RDB
*/

#ifndef PCIE_COMMON_RDB_H
#define PCIE_COMMON_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t PCIE_COMMON_PCIE_CMN_0_TYPE;
#define PCIE_COMMON_PCIE_CMN_0_STRAP_PCIE_RC_MODE_MASK (0x80000000UL)
#define PCIE_COMMON_PCIE_CMN_0_STRAP_PCIE_RC_MODE_SHIFT (31UL)
#define PCIE_COMMON_PCIE_CMN_0_PCIE_EP_MODE_PERST_OVRD_SEL_MASK (0x40000000UL)
#define PCIE_COMMON_PCIE_CMN_0_PCIE_EP_MODE_PERST_OVRD_SEL_SHIFT (30UL)
#define PCIE_COMMON_PCIE_CMN_0_PCIE_EP_MODE_PERST_OVRD_VAL_MASK (0x20000000UL)
#define PCIE_COMMON_PCIE_CMN_0_PCIE_EP_MODE_PERST_OVRD_VAL_SHIFT (29UL)
#define PCIE_COMMON_PCIE_CMN_0_PCIE_LNK_PHY_GLOOPBACK_OVRD_SEL_MASK (0x10000000UL)
#define PCIE_COMMON_PCIE_CMN_0_PCIE_LNK_PHY_GLOOPBACK_OVRD_SEL_SHIFT (28UL)
#define PCIE_COMMON_PCIE_CMN_0_PCIE_LNK_PHY_GLOOPBACK_OVRD_VAL_MASK (0x8000000UL)
#define PCIE_COMMON_PCIE_CMN_0_PCIE_LNK_PHY_GLOOPBACK_OVRD_VAL_SHIFT (27UL)
#define PCIE_COMMON_PCIE_CMN_0_PCIE_CHP_PHY_STANDALONE_MODE_MASK (0x4000000UL)
#define PCIE_COMMON_PCIE_CMN_0_PCIE_CHP_PHY_STANDALONE_MODE_SHIFT (26UL)
#define PCIE_COMMON_PCIE_CMN_0_PCIE_IN_WAKE_MASK (0x2000000UL)
#define PCIE_COMMON_PCIE_CMN_0_PCIE_IN_WAKE_SHIFT (25UL)
#define PCIE_COMMON_PCIE_CMN_0_ICFG_IPROC_INT_ENABLE_WR1B_MODE_MASK (0x1000000UL)
#define PCIE_COMMON_PCIE_CMN_0_ICFG_IPROC_INT_ENABLE_WR1B_MODE_SHIFT (24UL)
#define PCIE_COMMON_PCIE_CMN_0_STRAP_CHIP_REVISION_ID_MASK (0xff0000UL)
#define PCIE_COMMON_PCIE_CMN_0_STRAP_CHIP_REVISION_ID_SHIFT (16UL)
#define PCIE_COMMON_PCIE_CMN_0_STRAP_IPROC_PCIE_USER_DEVICE_ID_MASK (0xffffUL)
#define PCIE_COMMON_PCIE_CMN_0_STRAP_IPROC_PCIE_USER_DEVICE_ID_SHIFT (0UL)




typedef uint32_t PCIE_COMMON_PCIE_CMN_1_TYPE;
#define PCIE_COMMON_PCIE_CMN_1_PCIE_CMN_1_SPARES_MASK (0xffff0000UL)
#define PCIE_COMMON_PCIE_CMN_1_PCIE_CMN_1_SPARES_SHIFT (16UL)
#define PCIE_COMMON_PCIE_CMN_1_STRAP_IPROC_IP_DISABLE_PCIE_MASK (0x8000UL)
#define PCIE_COMMON_PCIE_CMN_1_STRAP_IPROC_IP_DISABLE_PCIE_SHIFT (15UL)
#define PCIE_COMMON_PCIE_CMN_1_STRAP_IPROC_PCIE_USER_FORCE_LANE_MASK (0x6000UL)
#define PCIE_COMMON_PCIE_CMN_1_STRAP_IPROC_PCIE_USER_FORCE_LANE_SHIFT (13UL)
#define PCIE_COMMON_PCIE_CMN_1_STRAP_IPROC_PCIE_USER_FORCE_GEN_MASK (0x1800UL)
#define PCIE_COMMON_PCIE_CMN_1_STRAP_IPROC_PCIE_USER_FORCE_GEN_SHIFT (11UL)
#define PCIE_COMMON_PCIE_CMN_1_STRAP_DISABLE_HOTSWAP_MASK (0x400UL)
#define PCIE_COMMON_PCIE_CMN_1_STRAP_DISABLE_HOTSWAP_SHIFT (10UL)
#define PCIE_COMMON_PCIE_CMN_1_PCIE_CHP_PHY_MDIO_PRTAD_STRAP_DST_MASK (0x3e0UL)
#define PCIE_COMMON_PCIE_CMN_1_PCIE_CHP_PHY_MDIO_PRTAD_STRAP_DST_SHIFT (5UL)
#define PCIE_COMMON_PCIE_CMN_1_PCIE_CHP_PHY_MDIO_DEVID_STRAP_MASK (0x1fUL)
#define PCIE_COMMON_PCIE_CMN_1_PCIE_CHP_PHY_MDIO_DEVID_STRAP_SHIFT (0UL)




typedef uint32_t PCIE_COMMON_PCIE_CMN_2_TYPE;
#define PCIE_COMMON_PCIE_CMN_2_IO_CONTROL_M0_SIDE_BUS_MASK (0xffffffffUL)
#define PCIE_COMMON_PCIE_CMN_2_IO_CONTROL_M0_SIDE_BUS_SHIFT (0UL)




typedef uint32_t PCIE_COMMON_PCIE_CMN_3_TYPE;
#define PCIE_COMMON_PCIE_CMN_3_IO_CONTROL_S0_SIDE_BUS_MASK (0xffffffffUL)
#define PCIE_COMMON_PCIE_CMN_3_IO_CONTROL_S0_SIDE_BUS_SHIFT (0UL)




typedef uint32_t PCIE_COMMON_PCIE_CMN_4_TYPE;
#define PCIE_COMMON_PCIE_CMN_4_DBG_SEL_MASK (0xf0000000UL)
#define PCIE_COMMON_PCIE_CMN_4_DBG_SEL_SHIFT (28UL)
#define PCIE_COMMON_PCIE_CMN_4_SPARE_PCIE04_MASK (0xfff8000UL)
#define PCIE_COMMON_PCIE_CMN_4_SPARE_PCIE04_SHIFT (15UL)
#define PCIE_COMMON_PCIE_CMN_4_RG_AXI_SECURE_BYPASS_MASK (0x4000UL)
#define PCIE_COMMON_PCIE_CMN_4_RG_AXI_SECURE_BYPASS_SHIFT (14UL)
#define PCIE_COMMON_PCIE_CMN_4_PCIE_PHY_TEST_MODE_MASK (0x2000UL)
#define PCIE_COMMON_PCIE_CMN_4_PCIE_PHY_TEST_MODE_SHIFT (13UL)
#define PCIE_COMMON_PCIE_CMN_4_PCIE_REFCLKZ_IN_SELECT_MASK (0x1c00UL)
#define PCIE_COMMON_PCIE_CMN_4_PCIE_REFCLKZ_IN_SELECT_SHIFT (10UL)
#define PCIE_COMMON_PCIE_CMN_4_RESET_OUTN_PCIE_M0_SIDE_BUS_MASK (0x200UL)
#define PCIE_COMMON_PCIE_CMN_4_RESET_OUTN_PCIE_M0_SIDE_BUS_SHIFT (9UL)
#define PCIE_COMMON_PCIE_CMN_4_RESET_OUTN_PCIE_S0_SIDE_BUS_MASK (0x100UL)
#define PCIE_COMMON_PCIE_CMN_4_RESET_OUTN_PCIE_S0_SIDE_BUS_SHIFT (8UL)
#define PCIE_COMMON_PCIE_CMN_4_PCIE_MISC_DEBUG_SEL_2_MASK (0xf0UL)
#define PCIE_COMMON_PCIE_CMN_4_PCIE_MISC_DEBUG_SEL_2_SHIFT (4UL)
#define PCIE_COMMON_PCIE_CMN_4_PCIE_MISC_DEBUG_SEL_1_MASK (0xfUL)
#define PCIE_COMMON_PCIE_CMN_4_PCIE_MISC_DEBUG_SEL_1_SHIFT (0UL)




typedef uint32_t PCIE_COMMON_PCIE_CMN_5_TYPE;
#define PCIE_COMMON_PCIE_CMN_5_SPARE_MASK (0xffffffffUL)
#define PCIE_COMMON_PCIE_CMN_5_SPARE_SHIFT (0UL)




typedef uint32_t PCIE_COMMON_PCIE_CMN_6_TYPE;
#define PCIE_COMMON_PCIE_CMN_6_SPARE_MASK (0xffffffffUL)
#define PCIE_COMMON_PCIE_CMN_6_SPARE_SHIFT (0UL)




typedef uint32_t PCIE_COMMON_PCIE_CMN_7_TYPE;
#define PCIE_COMMON_PCIE_CMN_7_SPARE_OUT_MASK (0xffffffffUL)
#define PCIE_COMMON_PCIE_CMN_7_SPARE_OUT_SHIFT (0UL)




typedef uint32_t PCIE_COMMON_AXI_WR_ACCESS_POLICY_TYPE;
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_WR_SECATTR_MASK (0xe0000000UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_WR_SECATTR_SHIFT (29UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_WR_SECATTR_EN_MASK (0x1c000000UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_WR_SECATTR_EN_SHIFT (26UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_MCU_1_UTILITY_AXI_WR_ACCCTRL_MASK (0x2UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_MCU_1_UTILITY_AXI_WR_ACCCTRL_SHIFT (1UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_A55_AXI_WR_ACCCTRL_MASK (0x4UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_A55_AXI_WR_ACCCTRL_SHIFT (2UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_GP_DMA_AXI_WR_ACCCTRL_MASK (0x10UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_GP_DMA_AXI_WR_ACCCTRL_SHIFT (4UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_SPACC_DMA_AXI_WR_ACCCTRL_MASK (0x20UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_SPACC_DMA_AXI_WR_ACCCTRL_SHIFT (5UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_PL80_0_LSP_AXI_WR_ACCCTRL_MASK (0x40UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_PL80_0_LSP_AXI_WR_ACCCTRL_SHIFT (6UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_PL80_1_ACQ_AXI_WR_ACCCTRL_MASK (0x80UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_PL80_1_ACQ_AXI_WR_ACCCTRL_SHIFT (7UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_MIPI_AXI_WR_ACCCTRL_MASK (0x100UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_MIPI_AXI_WR_ACCCTRL_SHIFT (8UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_PCIE_MST_AXI_WR_ACCCTRL_MASK (0x200UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_PCIE_MST_AXI_WR_ACCCTRL_SHIFT (9UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_XGMAC_AXI_WR_ACCCTRL_MASK (0x400UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_XGMAC_AXI_WR_ACCCTRL_SHIFT (10UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_Q8_DATA_0_AXI_WR_ACCCTRL_MASK (0x1000UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_Q8_DATA_0_AXI_WR_ACCCTRL_SHIFT (12UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_Q8_DATA_1_AXI_WR_ACCCTRL_MASK (0x2000UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_Q8_DATA_1_AXI_WR_ACCCTRL_SHIFT (13UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_Q8_DATA_2_AXI_WR_ACCCTRL_MASK (0x4000UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_Q8_DATA_2_AXI_WR_ACCCTRL_SHIFT (14UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_Q8_DATA_3_AXI_WR_ACCCTRL_MASK (0x8000UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_Q8_DATA_3_AXI_WR_ACCCTRL_SHIFT (15UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_Q8_IDMA_0_AXI_WR_ACCCTRL_MASK (0x10000UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_Q8_IDMA_0_AXI_WR_ACCCTRL_SHIFT (16UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_Q8_IDMA_1_AXI_WR_ACCCTRL_MASK (0x20000UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_Q8_IDMA_1_AXI_WR_ACCCTRL_SHIFT (17UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_Q8_IDMA_2_AXI_WR_ACCCTRL_MASK (0x40000UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_Q8_IDMA_2_AXI_WR_ACCCTRL_SHIFT (18UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_Q8_IDMA_3_AXI_WR_ACCCTRL_MASK (0x80000UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_Q8_IDMA_3_AXI_WR_ACCCTRL_SHIFT (19UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_SPI_DBG_AXI_WR_ACCCTRL_MASK (0x100000UL)
#define PCIE_COMMON_AXI_WR_ACCESS_POLICY_SPI_DBG_AXI_WR_ACCCTRL_SHIFT (20UL)




typedef uint32_t PCIE_COMMON_AXI_RD_ACCESS_POLICY_TYPE;
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_RD_SECATTR_MASK (0xe0000000UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_RD_SECATTR_SHIFT (29UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_RD_SECATTR_EN_MASK (0x1c000000UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_RD_SECATTR_EN_SHIFT (26UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_MCU_1_UTILITY_AXI_RD_ACCCTRL_MASK (0x2UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_MCU_1_UTILITY_AXI_RD_ACCCTRL_SHIFT (1UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_A55_AXI_RD_ACCCTRL_MASK (0x4UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_A55_AXI_RD_ACCCTRL_SHIFT (2UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_GP_DMA_AXI_RD_ACCCTRL_MASK (0x10UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_GP_DMA_AXI_RD_ACCCTRL_SHIFT (4UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_SPACC_DMA_AXI_RD_ACCCTRL_MASK (0x20UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_SPACC_DMA_AXI_RD_ACCCTRL_SHIFT (5UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_PL80_0_LSP_AXI_RD_ACCCTRL_MASK (0x40UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_PL80_0_LSP_AXI_RD_ACCCTRL_SHIFT (6UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_PL80_1_ACQ_AXI_RD_ACCCTRL_MASK (0x80UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_PL80_1_ACQ_AXI_RD_ACCCTRL_SHIFT (7UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_MIPI_AXI_RD_ACCCTRL_MASK (0x100UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_MIPI_AXI_RD_ACCCTRL_SHIFT (8UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_PCIE_MST_AXI_RD_ACCCTRL_MASK (0x200UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_PCIE_MST_AXI_RD_ACCCTRL_SHIFT (9UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_XGMAC_AXI_RD_ACCCTRL_MASK (0x400UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_XGMAC_AXI_RD_ACCCTRL_SHIFT (10UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_Q8_DATA_0_AXI_RD_ACCCTRL_MASK (0x1000UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_Q8_DATA_0_AXI_RD_ACCCTRL_SHIFT (12UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_Q8_DATA_1_AXI_RD_ACCCTRL_MASK (0x2000UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_Q8_DATA_1_AXI_RD_ACCCTRL_SHIFT (13UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_Q8_DATA_2_AXI_RD_ACCCTRL_MASK (0x4000UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_Q8_DATA_2_AXI_RD_ACCCTRL_SHIFT (14UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_Q8_DATA_3_AXI_RD_ACCCTRL_MASK (0x8000UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_Q8_DATA_3_AXI_RD_ACCCTRL_SHIFT (15UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_Q8_IDMA_0_AXI_RD_ACCCTRL_MASK (0x10000UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_Q8_IDMA_0_AXI_RD_ACCCTRL_SHIFT (16UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_Q8_IDMA_1_AXI_RD_ACCCTRL_MASK (0x20000UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_Q8_IDMA_1_AXI_RD_ACCCTRL_SHIFT (17UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_Q8_IDMA_2_AXI_RD_ACCCTRL_MASK (0x40000UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_Q8_IDMA_2_AXI_RD_ACCCTRL_SHIFT (18UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_Q8_IDMA_3_AXI_RD_ACCCTRL_MASK (0x80000UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_Q8_IDMA_3_AXI_RD_ACCCTRL_SHIFT (19UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_SPI_DBG_AXI_RD_ACCCTRL_MASK (0x100000UL)
#define PCIE_COMMON_AXI_RD_ACCESS_POLICY_SPI_DBG_AXI_RD_ACCCTRL_SHIFT (20UL)




typedef uint8_t PCIE_COMMON_RESERVED_TYPE;




typedef uint32_t PCIE_COMMON_PCIE_STAT_32BIT_0_TYPE;
#define PCIE_COMMON_PCIE_STAT_32BIT_0_SPARE31_MASK (0x80000000UL)
#define PCIE_COMMON_PCIE_STAT_32BIT_0_SPARE31_SHIFT (31UL)
#define PCIE_COMMON_PCIE_STAT_32BIT_0_EXT_CLKREQ_IN_MASK (0x40000000UL)
#define PCIE_COMMON_PCIE_STAT_32BIT_0_EXT_CLKREQ_IN_SHIFT (30UL)
#define PCIE_COMMON_PCIE_STAT_32BIT_0_EP_MODE_CLKREQ_MASK (0x20000000UL)
#define PCIE_COMMON_PCIE_STAT_32BIT_0_EP_MODE_CLKREQ_SHIFT (29UL)
#define PCIE_COMMON_PCIE_STAT_32BIT_0_SPARE28_MASK (0x10000000UL)
#define PCIE_COMMON_PCIE_STAT_32BIT_0_SPARE28_SHIFT (28UL)
#define PCIE_COMMON_PCIE_STAT_32BIT_0_EP_MODE_PERST_MASK (0x8000000UL)
#define PCIE_COMMON_PCIE_STAT_32BIT_0_EP_MODE_PERST_SHIFT (27UL)
#define PCIE_COMMON_PCIE_STAT_32BIT_0_RC_MODE_PERST_MASK (0x4000000UL)
#define PCIE_COMMON_PCIE_STAT_32BIT_0_RC_MODE_PERST_SHIFT (26UL)
#define PCIE_COMMON_PCIE_STAT_32BIT_0_RES_CAL_VALID_MASK (0x2000000UL)
#define PCIE_COMMON_PCIE_STAT_32BIT_0_RES_CAL_VALID_SHIFT (25UL)
#define PCIE_COMMON_PCIE_STAT_32BIT_0_SPARE_3B_MASK (0x1c00000UL)
#define PCIE_COMMON_PCIE_STAT_32BIT_0_SPARE_3B_SHIFT (22UL)
#define PCIE_COMMON_PCIE_STAT_32BIT_0_DEBUG_VECTOR_2_MASK (0x3ff800UL)
#define PCIE_COMMON_PCIE_STAT_32BIT_0_DEBUG_VECTOR_2_SHIFT (11UL)
#define PCIE_COMMON_PCIE_STAT_32BIT_0_DEBUG_VECTOR_1_MASK (0x7ffUL)
#define PCIE_COMMON_PCIE_STAT_32BIT_0_DEBUG_VECTOR_1_SHIFT (0UL)




typedef uint32_t PCIE_COMMON_PCIE_STAT_32BIT_1_TYPE;
#define PCIE_COMMON_PCIE_STAT_32BIT_1_PCIE_STATUS_3_MASK (0xffffffc0UL)
#define PCIE_COMMON_PCIE_STAT_32BIT_1_PCIE_STATUS_3_SHIFT (6UL)
#define PCIE_COMMON_PCIE_STAT_32BIT_1_AXI_PCIE_INTR_MASK (0x3fUL)
#define PCIE_COMMON_PCIE_STAT_32BIT_1_AXI_PCIE_INTR_SHIFT (0UL)




typedef uint32_t PCIE_COMMON_PCIE_STAT_32BIT_2_TYPE;
#define PCIE_COMMON_PCIE_STAT_32BIT_2_IO_STATUS_M_SIDE_BUS_MASK (0xffffffffUL)
#define PCIE_COMMON_PCIE_STAT_32BIT_2_IO_STATUS_M_SIDE_BUS_SHIFT (0UL)




typedef uint32_t PCIE_COMMON_PCIE_STAT_32BIT_3_TYPE;
#define PCIE_COMMON_PCIE_STAT_32BIT_3_IO_STATUS_S_SIDE_BUS_MASK (0xffffffffUL)
#define PCIE_COMMON_PCIE_STAT_32BIT_3_IO_STATUS_S_SIDE_BUS_SHIFT (0UL)




typedef uint32_t PCIE_COMMON_PCIE_STAT_32BIT_4_TYPE;
#define PCIE_COMMON_PCIE_STAT_32BIT_4_IO_CONTROL_INIT_M0_PINS_BUS_MASK (0xffffffffUL)
#define PCIE_COMMON_PCIE_STAT_32BIT_4_IO_CONTROL_INIT_M0_PINS_BUS_SHIFT (0UL)




typedef uint32_t PCIE_COMMON_PCIE_STAT_32BIT_5_TYPE;
#define PCIE_COMMON_PCIE_STAT_32BIT_5_IO_CONTROL_INIT_S0_PINS_BUS_MASK (0xffffffffUL)
#define PCIE_COMMON_PCIE_STAT_32BIT_5_IO_CONTROL_INIT_S0_PINS_BUS_SHIFT (0UL)




typedef uint32_t PCIE_COMMON_PCIE_STAT_32BIT_6_TYPE;
#define PCIE_COMMON_PCIE_STAT_32BIT_6_SPARE_IN_MASK (0xffffffffUL)
#define PCIE_COMMON_PCIE_STAT_32BIT_6_SPARE_IN_SHIFT (0UL)




typedef uint32_t PCIE_COMMON_LCPLL_00_TYPE;
#define PCIE_COMMON_LCPLL_00_SSC_MODE_MASK (0x80000000UL)
#define PCIE_COMMON_LCPLL_00_SSC_MODE_SHIFT (31UL)
#define PCIE_COMMON_LCPLL_00_CODE_VCOCAL_MASK (0x60000000UL)
#define PCIE_COMMON_LCPLL_00_CODE_VCOCAL_SHIFT (29UL)
#define PCIE_COMMON_LCPLL_00_SPARE00_MASK (0x1ffffc00UL)
#define PCIE_COMMON_LCPLL_00_SPARE00_SHIFT (10UL)
#define PCIE_COMMON_LCPLL_00_ENABLEB_CH_MASK (0x3f0UL)
#define PCIE_COMMON_LCPLL_00_ENABLEB_CH_SHIFT (4UL)
#define PCIE_COMMON_LCPLL_00_LOCK_LOST_CLR_MASK (0x8UL)
#define PCIE_COMMON_LCPLL_00_LOCK_LOST_CLR_SHIFT (3UL)
#define PCIE_COMMON_LCPLL_00_POST_RESETB_MASK (0x4UL)
#define PCIE_COMMON_LCPLL_00_POST_RESETB_SHIFT (2UL)
#define PCIE_COMMON_LCPLL_00_RESETB_MASK (0x2UL)
#define PCIE_COMMON_LCPLL_00_RESETB_SHIFT (1UL)
#define PCIE_COMMON_LCPLL_00_PWR_ON_MASK (0x1UL)
#define PCIE_COMMON_LCPLL_00_PWR_ON_SHIFT (0UL)




typedef uint32_t PCIE_COMMON_LCPLL_01_TYPE;
#define PCIE_COMMON_LCPLL_01_FREFEFF_INFO_MASK (0xff000000UL)
#define PCIE_COMMON_LCPLL_01_FREFEFF_INFO_SHIFT (24UL)
#define PCIE_COMMON_LCPLL_01_AUTO_CNFG_DSBL_MASK (0xff0000UL)
#define PCIE_COMMON_LCPLL_01_AUTO_CNFG_DSBL_SHIFT (16UL)
#define PCIE_COMMON_LCPLL_01_STAT_RESET_MASK (0x8000UL)
#define PCIE_COMMON_LCPLL_01_STAT_RESET_SHIFT (15UL)
#define PCIE_COMMON_LCPLL_01_STAT_MODE_MASK (0x6000UL)
#define PCIE_COMMON_LCPLL_01_STAT_MODE_SHIFT (13UL)
#define PCIE_COMMON_LCPLL_01_STAT_SELECT_MASK (0x1c00UL)
#define PCIE_COMMON_LCPLL_01_STAT_SELECT_SHIFT (10UL)
#define PCIE_COMMON_LCPLL_01_NDIV_INT_MASK (0x3ffUL)
#define PCIE_COMMON_LCPLL_01_NDIV_INT_SHIFT (0UL)




typedef uint32_t PCIE_COMMON_LCPLL_02_TYPE;
#define PCIE_COMMON_LCPLL_02_PDIV_MASK (0xf0000000UL)
#define PCIE_COMMON_LCPLL_02_PDIV_SHIFT (28UL)
#define PCIE_COMMON_LCPLL_02_SPARE02_MASK (0xe000000UL)
#define PCIE_COMMON_LCPLL_02_SPARE02_SHIFT (25UL)
#define PCIE_COMMON_LCPLL_02_PQ_MODE_MASK (0x1000000UL)
#define PCIE_COMMON_LCPLL_02_PQ_MODE_SHIFT (24UL)
#define PCIE_COMMON_LCPLL_02_NDIV_FRAC_MASK (0xffffffUL)
#define PCIE_COMMON_LCPLL_02_NDIV_FRAC_SHIFT (0UL)




typedef uint32_t PCIE_COMMON_LCPLL_03_TYPE;
#define PCIE_COMMON_LCPLL_03_HOLD_ALL_MASK (0x80000000UL)
#define PCIE_COMMON_LCPLL_03_HOLD_ALL_SHIFT (31UL)
#define PCIE_COMMON_LCPLL_03_POST_RSTB_SEL_MASK (0x60000000UL)
#define PCIE_COMMON_LCPLL_03_POST_RSTB_SEL_SHIFT (29UL)
#define PCIE_COMMON_LCPLL_03_SPARE03_MASK (0x1f000000UL)
#define PCIE_COMMON_LCPLL_03_SPARE03_SHIFT (24UL)
#define PCIE_COMMON_LCPLL_03_EN_CTRL_MASK (0xff0000UL)
#define PCIE_COMMON_LCPLL_03_EN_CTRL_SHIFT (16UL)
#define PCIE_COMMON_LCPLL_03_SPARE03A_MASK (0x8000UL)
#define PCIE_COMMON_LCPLL_03_SPARE03A_SHIFT (15UL)
#define PCIE_COMMON_LCPLL_03_BYP_EN_CH_MASK (0x7e00UL)
#define PCIE_COMMON_LCPLL_03_BYP_EN_CH_SHIFT (9UL)
#define PCIE_COMMON_LCPLL_03_ROUTE_CTRL_MASK (0x1ffUL)
#define PCIE_COMMON_LCPLL_03_ROUTE_CTRL_SHIFT (0UL)




typedef uint32_t PCIE_COMMON_LCPLL_04_TYPE;
#define PCIE_COMMON_LCPLL_04_SPARE04_MASK (0xf8000000UL)
#define PCIE_COMMON_LCPLL_04_SPARE04_SHIFT (27UL)
#define PCIE_COMMON_LCPLL_04_CZ_MASK (0x7000000UL)
#define PCIE_COMMON_LCPLL_04_CZ_SHIFT (24UL)
#define PCIE_COMMON_LCPLL_04_DC_COMP_OPT_MASK (0xe00000UL)
#define PCIE_COMMON_LCPLL_04_DC_COMP_OPT_SHIFT (21UL)
#define PCIE_COMMON_LCPLL_04_CH_MDEL_MASK (0x1f8000UL)
#define PCIE_COMMON_LCPLL_04_CH_MDEL_SHIFT (15UL)
#define PCIE_COMMON_LCPLL_04_HOLD_CH_MASK (0x7e00UL)
#define PCIE_COMMON_LCPLL_04_HOLD_CH_SHIFT (9UL)
#define PCIE_COMMON_LCPLL_04_LOCK_CNT_MASK (0x1c0UL)
#define PCIE_COMMON_LCPLL_04_LOCK_CNT_SHIFT (6UL)
#define PCIE_COMMON_LCPLL_04_NOREF_CHK_ENB_MASK (0x20UL)
#define PCIE_COMMON_LCPLL_04_NOREF_CHK_ENB_SHIFT (5UL)
#define PCIE_COMMON_LCPLL_04_RATE_MNGR_MODE_MASK (0x10UL)
#define PCIE_COMMON_LCPLL_04_RATE_MNGR_MODE_SHIFT (4UL)
#define PCIE_COMMON_LCPLL_04_MASH11_MODE_MASK (0x8UL)
#define PCIE_COMMON_LCPLL_04_MASH11_MODE_SHIFT (3UL)
#define PCIE_COMMON_LCPLL_04_DITH_ORDER_MASK (0x6UL)
#define PCIE_COMMON_LCPLL_04_DITH_ORDER_SHIFT (1UL)
#define PCIE_COMMON_LCPLL_04_DITH_EN_MASK (0x1UL)
#define PCIE_COMMON_LCPLL_04_DITH_EN_SHIFT (0UL)




typedef uint32_t PCIE_COMMON_LCPLL_05_TYPE;
#define PCIE_COMMON_LCPLL_05_SSC_STEP_MASK (0xffff0000UL)
#define PCIE_COMMON_LCPLL_05_SSC_STEP_SHIFT (16UL)
#define PCIE_COMMON_LCPLL_05_SSC_DOWNSPREAD_MASK (0x8000UL)
#define PCIE_COMMON_LCPLL_05_SSC_DOWNSPREAD_SHIFT (15UL)
#define PCIE_COMMON_LCPLL_05_SPARE05_MASK (0x4000UL)
#define PCIE_COMMON_LCPLL_05_SPARE05_SHIFT (14UL)
#define PCIE_COMMON_LCPLL_05_BYPASS_MODE_MASK (0x2000UL)
#define PCIE_COMMON_LCPLL_05_BYPASS_MODE_SHIFT (13UL)
#define PCIE_COMMON_LCPLL_05_RP_MASK (0x1e00UL)
#define PCIE_COMMON_LCPLL_05_RP_SHIFT (9UL)
#define PCIE_COMMON_LCPLL_05_CH_MDIV_MASK (0x1ffUL)
#define PCIE_COMMON_LCPLL_05_CH_MDIV_SHIFT (0UL)




typedef uint32_t PCIE_COMMON_LCPLL_06_TYPE;
#define PCIE_COMMON_LCPLL_06_WDT_CNT_MASK (0xc0000000UL)
#define PCIE_COMMON_LCPLL_06_WDT_CNT_SHIFT (30UL)
#define PCIE_COMMON_LCPLL_06_SPARE06_MASK (0x30000000UL)
#define PCIE_COMMON_LCPLL_06_SPARE06_SHIFT (28UL)
#define PCIE_COMMON_LCPLL_06_CP_MASK (0xe000000UL)
#define PCIE_COMMON_LCPLL_06_CP_SHIFT (25UL)
#define PCIE_COMMON_LCPLL_06_CP1_MASK (0x1c00000UL)
#define PCIE_COMMON_LCPLL_06_CP1_SHIFT (22UL)
#define PCIE_COMMON_LCPLL_06_SSC_LIMIT_MASK (0x3fffffUL)
#define PCIE_COMMON_LCPLL_06_SSC_LIMIT_SHIFT (0UL)




typedef uint32_t PCIE_COMMON_LCPLL_07_TYPE;
#define PCIE_COMMON_LCPLL_07_BYPASS_DAC_MASK (0xff800000UL)
#define PCIE_COMMON_LCPLL_07_BYPASS_DAC_SHIFT (23UL)
#define PCIE_COMMON_LCPLL_07_HOLD_DELAY_MASK (0x700000UL)
#define PCIE_COMMON_LCPLL_07_HOLD_DELAY_SHIFT (20UL)
#define PCIE_COMMON_LCPLL_07_WDT_ENB_MASK (0x80000UL)
#define PCIE_COMMON_LCPLL_07_WDT_ENB_SHIFT (19UL)
#define PCIE_COMMON_LCPLL_07_ICP_BLEED_MASK (0x7c000UL)
#define PCIE_COMMON_LCPLL_07_ICP_BLEED_SHIFT (14UL)
#define PCIE_COMMON_LCPLL_07_ICP_MASK (0x3f00UL)
#define PCIE_COMMON_LCPLL_07_ICP_SHIFT (8UL)
#define PCIE_COMMON_LCPLL_07_VCO_GAIN_MASK (0xf0UL)
#define PCIE_COMMON_LCPLL_07_VCO_GAIN_SHIFT (4UL)
#define PCIE_COMMON_LCPLL_07_RZ_MASK (0xfUL)
#define PCIE_COMMON_LCPLL_07_RZ_SHIFT (0UL)




typedef uint32_t PCIE_COMMON_LCPLL_08_TYPE;
#define PCIE_COMMON_LCPLL_08_BUF_CTRL_MASK (0xff000000UL)
#define PCIE_COMMON_LCPLL_08_BUF_CTRL_SHIFT (24UL)
#define PCIE_COMMON_LCPLL_08_PLL_CTRL_MASK (0xffffffUL)
#define PCIE_COMMON_LCPLL_08_PLL_CTRL_SHIFT (0UL)




typedef uint32_t PCIE_COMMON_LCPLL_09_TYPE;
#define PCIE_COMMON_LCPLL_09_D2C1_CTRL_MASK (0xff000000UL)
#define PCIE_COMMON_LCPLL_09_D2C1_CTRL_SHIFT (24UL)
#define PCIE_COMMON_LCPLL_09_CP_CTRL_MASK (0xff0000UL)
#define PCIE_COMMON_LCPLL_09_CP_CTRL_SHIFT (16UL)
#define PCIE_COMMON_LCPLL_09_LDO_CTRL_MASK (0xffffUL)
#define PCIE_COMMON_LCPLL_09_LDO_CTRL_SHIFT (0UL)




typedef uint32_t PCIE_COMMON_LCPLL_10_TYPE;
#define PCIE_COMMON_LCPLL_10_STAT_UPDATE_MASK (0x80000000UL)
#define PCIE_COMMON_LCPLL_10_STAT_UPDATE_SHIFT (31UL)
#define PCIE_COMMON_LCPLL_10_VC_OVERRIDE_MASK (0x40000000UL)
#define PCIE_COMMON_LCPLL_10_VC_OVERRIDE_SHIFT (30UL)
#define PCIE_COMMON_LCPLL_10_STAYS_LOCKED_MASK (0x20000000UL)
#define PCIE_COMMON_LCPLL_10_STAYS_LOCKED_SHIFT (29UL)
#define PCIE_COMMON_LCPLL_10_VCO_FB_DIV2_MASK (0x10000000UL)
#define PCIE_COMMON_LCPLL_10_VCO_FB_DIV2_SHIFT (28UL)
#define PCIE_COMMON_LCPLL_10_BG_CTRL_MASK (0xfffff00UL)
#define PCIE_COMMON_LCPLL_10_BG_CTRL_SHIFT (8UL)
#define PCIE_COMMON_LCPLL_10_D2C2_CTRL_MASK (0xffUL)
#define PCIE_COMMON_LCPLL_10_D2C2_CTRL_SHIFT (0UL)




typedef uint32_t PCIE_COMMON_LCPLL_STATUS_TYPE;
#define PCIE_COMMON_LCPLL_STATUS_SPARE_STAT_MASK (0xf0000000UL)
#define PCIE_COMMON_LCPLL_STATUS_SPARE_STAT_SHIFT (28UL)
#define PCIE_COMMON_LCPLL_STATUS_STAT_OUT_MASK (0xfff0000UL)
#define PCIE_COMMON_LCPLL_STATUS_STAT_OUT_SHIFT (16UL)
#define PCIE_COMMON_LCPLL_STATUS_SPARE_STATA_MASK (0xfffcUL)
#define PCIE_COMMON_LCPLL_STATUS_SPARE_STATA_SHIFT (2UL)
#define PCIE_COMMON_LCPLL_STATUS_ALL_HELD_MASK (0x2UL)
#define PCIE_COMMON_LCPLL_STATUS_ALL_HELD_SHIFT (1UL)
#define PCIE_COMMON_LCPLL_STATUS_LOCK_MASK (0x1UL)
#define PCIE_COMMON_LCPLL_STATUS_LOCK_SHIFT (0UL)




typedef volatile struct sPCIE_COMMON_RDBType {
    PCIE_COMMON_PCIE_CMN_0_TYPE pcie_cmn_0; /* OFFSET: 0x0 */
    PCIE_COMMON_PCIE_CMN_1_TYPE pcie_cmn_1; /* OFFSET: 0x4 */
    PCIE_COMMON_PCIE_CMN_2_TYPE pcie_cmn_2; /* OFFSET: 0x8 */
    PCIE_COMMON_PCIE_CMN_3_TYPE pcie_cmn_3; /* OFFSET: 0xc */
    PCIE_COMMON_PCIE_CMN_4_TYPE pcie_cmn_4; /* OFFSET: 0x10 */
    PCIE_COMMON_PCIE_CMN_5_TYPE pcie_cmn_5; /* OFFSET: 0x14 */
    PCIE_COMMON_PCIE_CMN_6_TYPE pcie_cmn_6; /* OFFSET: 0x18 */
    PCIE_COMMON_PCIE_CMN_7_TYPE pcie_cmn_7; /* OFFSET: 0x1c */
    PCIE_COMMON_AXI_WR_ACCESS_POLICY_TYPE axi_wr_access_policy; /* OFFSET: 0x20 */
    PCIE_COMMON_AXI_RD_ACCESS_POLICY_TYPE axi_rd_access_policy; /* OFFSET: 0x24 */
    PCIE_COMMON_RESERVED_TYPE rsvd0[8]; /* OFFSET: 0x28 */
    PCIE_COMMON_PCIE_STAT_32BIT_0_TYPE pcie_stat_0; /* OFFSET: 0x30 */
    PCIE_COMMON_PCIE_STAT_32BIT_1_TYPE pcie_stat_1; /* OFFSET: 0x34 */
    PCIE_COMMON_PCIE_STAT_32BIT_2_TYPE pcie_stat_2; /* OFFSET: 0x38 */
    PCIE_COMMON_PCIE_STAT_32BIT_3_TYPE pcie_stat_3; /* OFFSET: 0x3c */
    PCIE_COMMON_PCIE_STAT_32BIT_4_TYPE pcie_stat_4; /* OFFSET: 0x40 */
    PCIE_COMMON_PCIE_STAT_32BIT_5_TYPE pcie_stat_5; /* OFFSET: 0x44 */
    PCIE_COMMON_PCIE_STAT_32BIT_6_TYPE pcie_stat_6; /* OFFSET: 0x48 */
    PCIE_COMMON_RESERVED_TYPE rsvd1[52]; /* OFFSET: 0x4c */
    PCIE_COMMON_LCPLL_00_TYPE ctrl00; /* OFFSET: 0x80 */
    PCIE_COMMON_LCPLL_01_TYPE ctrl01; /* OFFSET: 0x84 */
    PCIE_COMMON_LCPLL_02_TYPE ctrl02; /* OFFSET: 0x88 */
    PCIE_COMMON_LCPLL_03_TYPE ctrl03; /* OFFSET: 0x8c */
    PCIE_COMMON_LCPLL_04_TYPE ctrl04; /* OFFSET: 0x90 */
    PCIE_COMMON_LCPLL_05_TYPE ctrl05; /* OFFSET: 0x94 */
    PCIE_COMMON_LCPLL_06_TYPE ctrl06; /* OFFSET: 0x98 */
    PCIE_COMMON_LCPLL_07_TYPE ctrl07; /* OFFSET: 0x9c */
    PCIE_COMMON_LCPLL_08_TYPE ctrl08; /* OFFSET: 0xa0 */
    PCIE_COMMON_LCPLL_09_TYPE ctrl09; /* OFFSET: 0xa4 */
    PCIE_COMMON_LCPLL_10_TYPE ctrl10; /* OFFSET: 0xa8 */
    PCIE_COMMON_LCPLL_STATUS_TYPE stat00; /* OFFSET: 0xac */
} PCIE_COMMON_RDBType;


#define EPCOMMON_BASE                   ((uintptr_t)(0xE02D1000UL))



#define PCIE_COMMON_MAX_HW_ID           (1UL)

#endif /* PCIE_COMMON_RDB_H */
