/*****************************************************************************
 Copyright 2024 Broadcom.  All rights reserved.

 Broadcom Proprietary and Confidential
******************************************************************************/
/**
    @file hkdac_intr_rdb.h
    @brief RDB File for HKDAC_INTR

    @version BCM89580_A0_20230125_RDB
*/

#ifndef HKDAC_INTR_RDB_H
#define HKDAC_INTR_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t HKDAC_INTR_AHD0FIE_TYPE;
#define HKDAC_INTR_AHD0FIE_P_DAC0_FIFO_OVERFLOW_INTR_MASK (0x80000000UL)
#define HKDAC_INTR_AHD0FIE_P_DAC0_FIFO_OVERFLOW_INTR_SHIFT (31UL)
#define HKDAC_INTR_AHD0FIE_P_DAC0_FIFO_EMPTY_INTR_MASK (0x1UL)
#define HKDAC_INTR_AHD0FIE_P_DAC0_FIFO_EMPTY_INTR_SHIFT (0UL)




typedef uint32_t HKDAC_INTR_AHD0FIE1_TYPE;
#define HKDAC_INTR_AHD0FIE1_DAC0_FIFO_OVERFLOW_INTR_W2CLR_MASK (0x80000000UL)
#define HKDAC_INTR_AHD0FIE1_DAC0_FIFO_OVERFLOW_INTR_W2CLR_SHIFT (31UL)
#define HKDAC_INTR_AHD0FIE1_DAC0_FIFO_EMPTY_INTR_W2CLR_MASK (0x1UL)
#define HKDAC_INTR_AHD0FIE1_DAC0_FIFO_EMPTY_INTR_W2CLR_SHIFT (0UL)




typedef uint32_t HKDAC_INTR_AHD0FIE2_TYPE;
#define HKDAC_INTR_AHD0FIE2_ENABLE_DAC0_FIFO_OVERFLOW_INTR_MASK (0x80000000UL)
#define HKDAC_INTR_AHD0FIE2_ENABLE_DAC0_FIFO_OVERFLOW_INTR_SHIFT (31UL)
#define HKDAC_INTR_AHD0FIE2_ENABLE_DAC0_FIFO_EMPTY_INTR_MASK (0x1UL)
#define HKDAC_INTR_AHD0FIE2_ENABLE_DAC0_FIFO_EMPTY_INTR_SHIFT (0UL)




typedef uint32_t HKDAC_INTR_AHD1FIE_TYPE;
#define HKDAC_INTR_AHD1FIE_P_DAC1_FIFO_OVERFLOW_INTR_MASK (0x80000000UL)
#define HKDAC_INTR_AHD1FIE_P_DAC1_FIFO_OVERFLOW_INTR_SHIFT (31UL)
#define HKDAC_INTR_AHD1FIE_P_DAC1_FIFO_EMPTY_INTR_MASK (0x1UL)
#define HKDAC_INTR_AHD1FIE_P_DAC1_FIFO_EMPTY_INTR_SHIFT (0UL)




typedef uint32_t HKDAC_INTR_AHD1FIE1_TYPE;
#define HKDAC_INTR_AHD1FIE1_DAC1_FIFO_OVERFLOW_INTR_W2CLR_MASK (0x80000000UL)
#define HKDAC_INTR_AHD1FIE1_DAC1_FIFO_OVERFLOW_INTR_W2CLR_SHIFT (31UL)
#define HKDAC_INTR_AHD1FIE1_DAC1_FIFO_EMPTY_INTR_W2CLR_MASK (0x1UL)
#define HKDAC_INTR_AHD1FIE1_DAC1_FIFO_EMPTY_INTR_W2CLR_SHIFT (0UL)




typedef uint32_t HKDAC_INTR_AHD1FIE2_TYPE;
#define HKDAC_INTR_AHD1FIE2_ENABLE_DAC1_FIFO_OVERFLOW_INTR_MASK (0x80000000UL)
#define HKDAC_INTR_AHD1FIE2_ENABLE_DAC1_FIFO_OVERFLOW_INTR_SHIFT (31UL)
#define HKDAC_INTR_AHD1FIE2_ENABLE_DAC1_FIFO_EMPTY_INTR_MASK (0x1UL)
#define HKDAC_INTR_AHD1FIE2_ENABLE_DAC1_FIFO_EMPTY_INTR_SHIFT (0UL)




typedef uint32_t HKDAC_INTR_AHD2FIE_TYPE;
#define HKDAC_INTR_AHD2FIE_P_DAC2_FIFO_OVERFLOW_INTR_MASK (0x80000000UL)
#define HKDAC_INTR_AHD2FIE_P_DAC2_FIFO_OVERFLOW_INTR_SHIFT (31UL)
#define HKDAC_INTR_AHD2FIE_P_DAC2_FIFO_EMPTY_INTR_MASK (0x1UL)
#define HKDAC_INTR_AHD2FIE_P_DAC2_FIFO_EMPTY_INTR_SHIFT (0UL)




typedef uint32_t HKDAC_INTR_AHD2FIE1_TYPE;
#define HKDAC_INTR_AHD2FIE1_DAC2_FIFO_OVERFLOW_INTR_W2CLR_MASK (0x80000000UL)
#define HKDAC_INTR_AHD2FIE1_DAC2_FIFO_OVERFLOW_INTR_W2CLR_SHIFT (31UL)
#define HKDAC_INTR_AHD2FIE1_DAC2_FIFO_EMPTY_INTR_W2CLR_MASK (0x1UL)
#define HKDAC_INTR_AHD2FIE1_DAC2_FIFO_EMPTY_INTR_W2CLR_SHIFT (0UL)




typedef uint32_t HKDAC_INTR_AHD2FIE2_TYPE;
#define HKDAC_INTR_AHD2FIE2_ENABLE_DAC2_FIFO_OVERFLOW_INTR_MASK (0x80000000UL)
#define HKDAC_INTR_AHD2FIE2_ENABLE_DAC2_FIFO_OVERFLOW_INTR_SHIFT (31UL)
#define HKDAC_INTR_AHD2FIE2_ENABLE_DAC2_FIFO_EMPTY_INTR_MASK (0x1UL)
#define HKDAC_INTR_AHD2FIE2_ENABLE_DAC2_FIFO_EMPTY_INTR_SHIFT (0UL)




typedef uint32_t HKDAC_INTR_AHD3FIE_TYPE;
#define HKDAC_INTR_AHD3FIE_P_DAC3_FIFO_OVERFLOW_INTR_MASK (0x80000000UL)
#define HKDAC_INTR_AHD3FIE_P_DAC3_FIFO_OVERFLOW_INTR_SHIFT (31UL)
#define HKDAC_INTR_AHD3FIE_P_DAC3_FIFO_EMPTY_INTR_MASK (0x1UL)
#define HKDAC_INTR_AHD3FIE_P_DAC3_FIFO_EMPTY_INTR_SHIFT (0UL)




typedef uint32_t HKDAC_INTR_AHD3FIE1_TYPE;
#define HKDAC_INTR_AHD3FIE1_DAC3_FIFO_OVERFLOW_INTR_W2CLR_MASK (0x80000000UL)
#define HKDAC_INTR_AHD3FIE1_DAC3_FIFO_OVERFLOW_INTR_W2CLR_SHIFT (31UL)
#define HKDAC_INTR_AHD3FIE1_DAC3_FIFO_EMPTY_INTR_W2CLR_MASK (0x1UL)
#define HKDAC_INTR_AHD3FIE1_DAC3_FIFO_EMPTY_INTR_W2CLR_SHIFT (0UL)




typedef uint32_t HKDAC_INTR_AHD3FIE2_TYPE;
#define HKDAC_INTR_AHD3FIE2_ENABLE_DAC3_FIFO_OVERFLOW_INTR_MASK (0x80000000UL)
#define HKDAC_INTR_AHD3FIE2_ENABLE_DAC3_FIFO_OVERFLOW_INTR_SHIFT (31UL)
#define HKDAC_INTR_AHD3FIE2_ENABLE_DAC3_FIFO_EMPTY_INTR_MASK (0x1UL)
#define HKDAC_INTR_AHD3FIE2_ENABLE_DAC3_FIFO_EMPTY_INTR_SHIFT (0UL)




typedef uint32_t HKDAC_INTR_AHD4FIE_TYPE;
#define HKDAC_INTR_AHD4FIE_P_DAC4_FIFO_OVERFLOW_INTR_MASK (0x80000000UL)
#define HKDAC_INTR_AHD4FIE_P_DAC4_FIFO_OVERFLOW_INTR_SHIFT (31UL)
#define HKDAC_INTR_AHD4FIE_P_DAC4_FIFO_EMPTY_INTR_MASK (0x1UL)
#define HKDAC_INTR_AHD4FIE_P_DAC4_FIFO_EMPTY_INTR_SHIFT (0UL)




typedef uint32_t HKDAC_INTR_AHD4FIE1_TYPE;
#define HKDAC_INTR_AHD4FIE1_DAC4_FIFO_OVERFLOW_INTR_W2CLR_MASK (0x80000000UL)
#define HKDAC_INTR_AHD4FIE1_DAC4_FIFO_OVERFLOW_INTR_W2CLR_SHIFT (31UL)
#define HKDAC_INTR_AHD4FIE1_DAC4_FIFO_EMPTY_INTR_W2CLR_MASK (0x1UL)
#define HKDAC_INTR_AHD4FIE1_DAC4_FIFO_EMPTY_INTR_W2CLR_SHIFT (0UL)




typedef uint32_t HKDAC_INTR_AHD4FIE2_TYPE;
#define HKDAC_INTR_AHD4FIE2_ENABLE_DAC4_FIFO_OVERFLOW_INTR_MASK (0x80000000UL)
#define HKDAC_INTR_AHD4FIE2_ENABLE_DAC4_FIFO_OVERFLOW_INTR_SHIFT (31UL)
#define HKDAC_INTR_AHD4FIE2_ENABLE_DAC4_FIFO_EMPTY_INTR_MASK (0x1UL)
#define HKDAC_INTR_AHD4FIE2_ENABLE_DAC4_FIFO_EMPTY_INTR_SHIFT (0UL)




typedef uint32_t HKDAC_INTR_AHD5FIE_TYPE;
#define HKDAC_INTR_AHD5FIE_P_DAC5_FIFO_OVERFLOW_INTR_MASK (0x80000000UL)
#define HKDAC_INTR_AHD5FIE_P_DAC5_FIFO_OVERFLOW_INTR_SHIFT (31UL)
#define HKDAC_INTR_AHD5FIE_P_DAC5_FIFO_EMPTY_INTR_MASK (0x1UL)
#define HKDAC_INTR_AHD5FIE_P_DAC5_FIFO_EMPTY_INTR_SHIFT (0UL)




typedef uint32_t HKDAC_INTR_AHD5FIE1_TYPE;
#define HKDAC_INTR_AHD5FIE1_DAC5_FIFO_OVERFLOW_INTR_W2CLR_MASK (0x80000000UL)
#define HKDAC_INTR_AHD5FIE1_DAC5_FIFO_OVERFLOW_INTR_W2CLR_SHIFT (31UL)
#define HKDAC_INTR_AHD5FIE1_DAC5_FIFO_EMPTY_INTR_W2CLR_MASK (0x1UL)
#define HKDAC_INTR_AHD5FIE1_DAC5_FIFO_EMPTY_INTR_W2CLR_SHIFT (0UL)




typedef uint32_t HKDAC_INTR_AHD5FIE2_TYPE;
#define HKDAC_INTR_AHD5FIE2_ENABLE_DAC5_FIFO_OVERFLOW_INTR_MASK (0x80000000UL)
#define HKDAC_INTR_AHD5FIE2_ENABLE_DAC5_FIFO_OVERFLOW_INTR_SHIFT (31UL)
#define HKDAC_INTR_AHD5FIE2_ENABLE_DAC5_FIFO_EMPTY_INTR_MASK (0x1UL)
#define HKDAC_INTR_AHD5FIE2_ENABLE_DAC5_FIFO_EMPTY_INTR_SHIFT (0UL)




typedef uint32_t HKDAC_INTR_AHD6FIE_TYPE;
#define HKDAC_INTR_AHD6FIE_P_DAC6_FIFO_OVERFLOW_INTR_MASK (0x80000000UL)
#define HKDAC_INTR_AHD6FIE_P_DAC6_FIFO_OVERFLOW_INTR_SHIFT (31UL)
#define HKDAC_INTR_AHD6FIE_P_DAC6_FIFO_EMPTY_INTR_MASK (0x1UL)
#define HKDAC_INTR_AHD6FIE_P_DAC6_FIFO_EMPTY_INTR_SHIFT (0UL)




typedef uint32_t HKDAC_INTR_AHD6FIE1_TYPE;
#define HKDAC_INTR_AHD6FIE1_DAC6_FIFO_OVERFLOW_INTR_W2CLR_MASK (0x80000000UL)
#define HKDAC_INTR_AHD6FIE1_DAC6_FIFO_OVERFLOW_INTR_W2CLR_SHIFT (31UL)
#define HKDAC_INTR_AHD6FIE1_DAC6_FIFO_EMPTY_INTR_W2CLR_MASK (0x1UL)
#define HKDAC_INTR_AHD6FIE1_DAC6_FIFO_EMPTY_INTR_W2CLR_SHIFT (0UL)




typedef uint32_t HKDAC_INTR_AHD6FIE2_TYPE;
#define HKDAC_INTR_AHD6FIE2_ENABLE_DAC6_FIFO_OVERFLOW_INTR_MASK (0x80000000UL)
#define HKDAC_INTR_AHD6FIE2_ENABLE_DAC6_FIFO_OVERFLOW_INTR_SHIFT (31UL)
#define HKDAC_INTR_AHD6FIE2_ENABLE_DAC6_FIFO_EMPTY_INTR_MASK (0x1UL)
#define HKDAC_INTR_AHD6FIE2_ENABLE_DAC6_FIFO_EMPTY_INTR_SHIFT (0UL)




typedef uint32_t HKDAC_INTR_AHD7FIE_TYPE;
#define HKDAC_INTR_AHD7FIE_P_DAC7_FIFO_OVERFLOW_INTR_MASK (0x80000000UL)
#define HKDAC_INTR_AHD7FIE_P_DAC7_FIFO_OVERFLOW_INTR_SHIFT (31UL)
#define HKDAC_INTR_AHD7FIE_P_DAC7_FIFO_EMPTY_INTR_MASK (0x1UL)
#define HKDAC_INTR_AHD7FIE_P_DAC7_FIFO_EMPTY_INTR_SHIFT (0UL)




typedef uint32_t HKDAC_INTR_AHD7FIE1_TYPE;
#define HKDAC_INTR_AHD7FIE1_DAC7_FIFO_OVERFLOW_INTR_W2CLR_MASK (0x80000000UL)
#define HKDAC_INTR_AHD7FIE1_DAC7_FIFO_OVERFLOW_INTR_W2CLR_SHIFT (31UL)
#define HKDAC_INTR_AHD7FIE1_DAC7_FIFO_EMPTY_INTR_W2CLR_MASK (0x1UL)
#define HKDAC_INTR_AHD7FIE1_DAC7_FIFO_EMPTY_INTR_W2CLR_SHIFT (0UL)




typedef uint32_t HKDAC_INTR_AHD7FIE2_TYPE;
#define HKDAC_INTR_AHD7FIE2_ENABLE_DAC7_FIFO_OVERFLOW_INTR_MASK (0x80000000UL)
#define HKDAC_INTR_AHD7FIE2_ENABLE_DAC7_FIFO_OVERFLOW_INTR_SHIFT (31UL)
#define HKDAC_INTR_AHD7FIE2_ENABLE_DAC7_FIFO_EMPTY_INTR_MASK (0x1UL)
#define HKDAC_INTR_AHD7FIE2_ENABLE_DAC7_FIFO_EMPTY_INTR_SHIFT (0UL)




typedef uint8_t HKDAC_INTR_RESERVED_TYPE;




typedef uint32_t HKDAC_INTR_SPARE_END_REG_TYPE;
#define HKDAC_INTR_SPARE_END_REG_MASK (0xffffffffUL)
#define HKDAC_INTR_SPARE_END_REG_SHIFT (0UL)


typedef volatile struct sHKDAC_INTR_HKDAC_DAC_CHANNEL_INTR_Type {
    HKDAC_INTR_AHD0FIE_TYPE acq_hkdac_dac0_fifo_intr_eipr; /* OFFSET: 0x0 */
    HKDAC_INTR_AHD0FIE1_TYPE acq_hkdac_dac0_fifo_intr_eisr; /* OFFSET: 0x4 */
    HKDAC_INTR_AHD0FIE2_TYPE acq_hkdac_dac0_fifo_intr_eier; /* OFFSET: 0x8 */
} HKDAC_INTR_HKDAC_DAC_CHANNEL_INTR_Type;


#define HKDAC_INTR_CHAN_SIZE  (8UL)


typedef volatile struct sHKDAC_INTR_RDBType {
    HKDAC_INTR_HKDAC_DAC_CHANNEL_INTR_Type chan[HKDAC_INTR_CHAN_SIZE]; /* OFFSET: 0x0 */
    HKDAC_INTR_RESERVED_TYPE rsvd0[156]; /* OFFSET: 0x60 */
    HKDAC_INTR_SPARE_END_REG_TYPE spare_end_reg; /* OFFSET: 0xfc */
} HKDAC_INTR_RDBType;


#define HKDAC_INTR_BASE                 (0xE0609F00UL)

#define HKDAC_INTR_HKDAC_DAC_CHANNEL_INTR_TYPE_OFFSET  (0xE0609f00UL)



#define HKDAC_INTR_MAX_HW_ID            (1UL)

#endif /* HKDAC_INTR_RDB_H */
