/*****************************************************************************
 Copyright 2024 Broadcom.  All rights reserved.

 Broadcom Proprietary and Confidential
******************************************************************************/
/**
    @file hkdac_rdb.h
    @brief RDB File for HKDAC

    @version BCM89580_A0_20230125_RDB
*/

#ifndef HKDAC_RDB_H
#define HKDAC_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t HKDAC_DAC_CTRL_TYPE;
#define HKDAC_DAC_CTRL_CTRL_BUSY_MASK (0x80000000UL)
#define HKDAC_DAC_CTRL_CTRL_BUSY_SHIFT (31UL)
#define HKDAC_DAC_CTRL_EN_AWG_MASK (0x20000000UL)
#define HKDAC_DAC_CTRL_EN_AWG_SHIFT (29UL)
#define HKDAC_DAC_CTRL_EN_DAC_CTRL_MASK (0x10000000UL)
#define HKDAC_DAC_CTRL_EN_DAC_CTRL_SHIFT (28UL)
#define HKDAC_DAC_CTRL_EN_LOWPOWER_MASK (0x8000000UL)
#define HKDAC_DAC_CTRL_EN_LOWPOWER_SHIFT (27UL)
#define HKDAC_DAC_CTRL_PDB_MASK (0x4000000UL)
#define HKDAC_DAC_CTRL_PDB_SHIFT (26UL)
#define HKDAC_DAC_CTRL_SYNC_MODE_MASK (0x3000000UL)
#define HKDAC_DAC_CTRL_SYNC_MODE_SHIFT (24UL)
#define HKDAC_DAC_CTRL_SYNC_GRP_MASK (0xff0000UL)
#define HKDAC_DAC_CTRL_SYNC_GRP_SHIFT (16UL)
#define HKDAC_DAC_CTRL_PROG_RATE_CNT_MASK (0xffffUL)
#define HKDAC_DAC_CTRL_PROG_RATE_CNT_SHIFT (0UL)




typedef uint32_t HKDAC_DAC_DATA_TYPE;
#define HKDAC_DAC_DATA_UPPER_DATA_REG_MASK (0xfff0000UL)
#define HKDAC_DAC_DATA_UPPER_DATA_REG_SHIFT (16UL)
#define HKDAC_DAC_DATA_LOWER_DATA_REG_MASK (0xfffUL)
#define HKDAC_DAC_DATA_LOWER_DATA_REG_SHIFT (0UL)




typedef uint32_t HKDAC_DAC_DBG_TYPE;
#define HKDAC_DAC_DBG_INT_EN_DAC_CTRL_MASK (0x1000UL)
#define HKDAC_DAC_DBG_INT_EN_DAC_CTRL_SHIFT (12UL)
#define HKDAC_DAC_DBG_DMA_REQ_MASK (0x800UL)
#define HKDAC_DAC_DBG_DMA_REQ_SHIFT (11UL)
#define HKDAC_DAC_DBG_FIFO_OVERFLOW_MASK (0x400UL)
#define HKDAC_DAC_DBG_FIFO_OVERFLOW_SHIFT (10UL)
#define HKDAC_DAC_DBG_FIFO_FULL_MASK (0x200UL)
#define HKDAC_DAC_DBG_FIFO_FULL_SHIFT (9UL)
#define HKDAC_DAC_DBG_FIFO_EMPTY_MASK (0x100UL)
#define HKDAC_DAC_DBG_FIFO_EMPTY_SHIFT (8UL)
#define HKDAC_DAC_DBG_FIFO_STAT_MASK (0x1fUL)
#define HKDAC_DAC_DBG_FIFO_STAT_SHIFT (0UL)




typedef uint8_t HKDAC_RESERVED_TYPE;




typedef uint32_t HKDAC_AFE_CFG_0_TYPE;
#define HKDAC_AFE_CFG_0_REFMUX_SEL_MASK (0xe000UL)
#define HKDAC_AFE_CFG_0_REFMUX_SEL_SHIFT (13UL)
#define HKDAC_AFE_CFG_0_PD_PATTERN_MASK (0x1000UL)
#define HKDAC_AFE_CFG_0_PD_PATTERN_SHIFT (12UL)
#define HKDAC_AFE_CFG_0_MBIAS_MASK (0xc00UL)
#define HKDAC_AFE_CFG_0_MBIAS_SHIFT (10UL)
#define HKDAC_AFE_CFG_0_SEL_EXT_VREF_MASK (0x200UL)
#define HKDAC_AFE_CFG_0_SEL_EXT_VREF_SHIFT (9UL)
#define HKDAC_AFE_CFG_0_EN_GAINBOOST_MASK (0x100UL)
#define HKDAC_AFE_CFG_0_EN_GAINBOOST_SHIFT (8UL)
#define HKDAC_AFE_CFG_0_PTAT_VBG_MASK (0xf0UL)
#define HKDAC_AFE_CFG_0_PTAT_VBG_SHIFT (4UL)
#define HKDAC_AFE_CFG_0_REFSEL_MASK (0xeUL)
#define HKDAC_AFE_CFG_0_REFSEL_SHIFT (1UL)
#define HKDAC_AFE_CFG_0_PDBG_MASK (0x1UL)
#define HKDAC_AFE_CFG_0_PDBG_SHIFT (0UL)




typedef uint32_t HKDAC_AFE_CFG_1_TYPE;
#define HKDAC_AFE_CFG_1_CONFIG1_SPARE_MASK (0xf000UL)
#define HKDAC_AFE_CFG_1_CONFIG1_SPARE_SHIFT (12UL)
#define HKDAC_AFE_CFG_1_DAC3_OUTAMP_BW_MASK (0xe00UL)
#define HKDAC_AFE_CFG_1_DAC3_OUTAMP_BW_SHIFT (9UL)
#define HKDAC_AFE_CFG_1_DAC2_OUTAMP_BW_MASK (0x1c0UL)
#define HKDAC_AFE_CFG_1_DAC2_OUTAMP_BW_SHIFT (6UL)
#define HKDAC_AFE_CFG_1_DAC1_OUTAMP_BW_MASK (0x38UL)
#define HKDAC_AFE_CFG_1_DAC1_OUTAMP_BW_SHIFT (3UL)
#define HKDAC_AFE_CFG_1_DAC0_OUTAMP_BW_MASK (0x7UL)
#define HKDAC_AFE_CFG_1_DAC0_OUTAMP_BW_SHIFT (0UL)




typedef uint32_t HKDAC_AFE_CFG_2_TYPE;
#define HKDAC_AFE_CFG_2_CONFIG2_SPARE_MASK (0xf000UL)
#define HKDAC_AFE_CFG_2_CONFIG2_SPARE_SHIFT (12UL)
#define HKDAC_AFE_CFG_2_DAC3_REFBUF_BW_MASK (0xe00UL)
#define HKDAC_AFE_CFG_2_DAC3_REFBUF_BW_SHIFT (9UL)
#define HKDAC_AFE_CFG_2_DAC2_REFBUF_BW_MASK (0x1c0UL)
#define HKDAC_AFE_CFG_2_DAC2_REFBUF_BW_SHIFT (6UL)
#define HKDAC_AFE_CFG_2_DAC1_REFBUF_BW_MASK (0x38UL)
#define HKDAC_AFE_CFG_2_DAC1_REFBUF_BW_SHIFT (3UL)
#define HKDAC_AFE_CFG_2_DAC0_REFBUF_BW_MASK (0x7UL)
#define HKDAC_AFE_CFG_2_DAC0_REFBUF_BW_SHIFT (0UL)




typedef uint32_t HKDAC_AFE_CFG_3_TYPE;
#define HKDAC_AFE_CFG_3_CONFIG3_SPARE_MASK (0xffffUL)
#define HKDAC_AFE_CFG_3_CONFIG3_SPARE_SHIFT (0UL)




typedef uint32_t HKDAC_AFE_CFG_4_TYPE;
#define HKDAC_AFE_CFG_4_RESET_MASK (0x1UL)
#define HKDAC_AFE_CFG_4_RESET_SHIFT (0UL)




typedef uint32_t HKDAC_SPARE_END_ADDR_TYPE;
#define HKDAC_SPARE_END_ADDR_MASK (0xffffffffUL)
#define HKDAC_SPARE_END_ADDR_SHIFT (0UL)


typedef volatile struct sDAC_CHANNEL_Type {
    HKDAC_DAC_CTRL_TYPE dac0_ctrl; /* OFFSET: 0x0 */
    HKDAC_DAC_DATA_TYPE dac0_data; /* OFFSET: 0x4 */
    HKDAC_DAC_DBG_TYPE dac0_dbg; /* OFFSET: 0x8 */
    HKDAC_RESERVED_TYPE rsvd0[52]; /* OFFSET: 0xc */
} HKDAC_DAC_CHANNEL_Type;


#define HKDAC_CHAN_SIZE  (8UL)


typedef volatile struct sHKDAC_RDBType {
    HKDAC_DAC_CHANNEL_Type chan[HKDAC_CHAN_SIZE]; /* OFFSET: 0x0 */
    HKDAC_RESERVED_TYPE rsvd7[1536]; /* OFFSET: 0x200 */
    HKDAC_AFE_CFG_0_TYPE afe_blk0_cfg0; /* OFFSET: 0x800 */
    HKDAC_AFE_CFG_1_TYPE afe_blk0_cfg1; /* OFFSET: 0x804 */
    HKDAC_AFE_CFG_2_TYPE afe_blk0_cfg2; /* OFFSET: 0x808 */
    HKDAC_AFE_CFG_3_TYPE afe_blk0_cfg3; /* OFFSET: 0x80c */
    HKDAC_AFE_CFG_4_TYPE afe_blk0_cfg4; /* OFFSET: 0x810 */
    HKDAC_RESERVED_TYPE rsvd8[108]; /* OFFSET: 0x814 */
    HKDAC_AFE_CFG_0_TYPE afe_blk1_cfg0; /* OFFSET: 0x880 */
    HKDAC_AFE_CFG_1_TYPE afe_blk1_cfg1; /* OFFSET: 0x884 */
    HKDAC_AFE_CFG_2_TYPE afe_blk1_cfg2; /* OFFSET: 0x888 */
    HKDAC_AFE_CFG_3_TYPE afe_blk1_cfg3; /* OFFSET: 0x88c */
    HKDAC_AFE_CFG_4_TYPE afe_blk1_cfg4; /* OFFSET: 0x890 */
    HKDAC_RESERVED_TYPE rsvd9[1640]; /* OFFSET: 0x894 */
    HKDAC_SPARE_END_ADDR_TYPE spare_end_addr; /* OFFSET: 0xefc */
} HKDAC_RDBType;


#define HKDAC_BASE                      (0xE0609000UL)

#define DAC_CHANNEL_TYPE_OFFSET         (0xE0609000UL)



#define HKDAC_MAX_HW_ID                 (1UL)

#endif /* HKDAC_RDB_H */
