/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file brphy1gv2_t1_core_rdb.h
    @brief RDB File for BRPHY1GV2_T1_CORE

    @version BCM89580_A0_20230125_RDB
*/

#ifndef BRPHY1GV2_T1_CORE_RDB_H
#define BRPHY1GV2_T1_CORE_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t BRPHY1GV2_T1_CORE_PGCA_TYPE;
#define BRPHY1GV2_T1_CORE_PGCA_TX_ERR_MASK (0x8000U)
#define BRPHY1GV2_T1_CORE_PGCA_TX_ERR_SHIFT (15U)
#define BRPHY1GV2_T1_CORE_PGCA_SKIP_CRC_MASK (0x4000U)
#define BRPHY1GV2_T1_CORE_PGCA_SKIP_CRC_SHIFT (14U)
#define BRPHY1GV2_T1_CORE_PGCA_IPG_SEL_MASK (0x3800U)
#define BRPHY1GV2_T1_CORE_PGCA_IPG_SEL_SHIFT (11U)
#define BRPHY1GV2_T1_CORE_PGCA_STOP_MODE_MASK (0x8U)
#define BRPHY1GV2_T1_CORE_PGCA_STOP_MODE_SHIFT (3U)
#define BRPHY1GV2_T1_CORE_PGCA_RUN_PAT_GEN_MASK (0x4U)
#define BRPHY1GV2_T1_CORE_PGCA_RUN_PAT_GEN_SHIFT (2U)
#define BRPHY1GV2_T1_CORE_PGCA_SELECT_PATGEN_DATA_MASK (0x3U)
#define BRPHY1GV2_T1_CORE_PGCA_SELECT_PATGEN_DATA_SHIFT (0U)




typedef uint8_t BRPHY1GV2_T1_CORE_RESERVED_TYPE;




typedef uint16_t BRPHY1GV2_T1_CORE_PGCB_TYPE;
#define BRPHY1GV2_T1_CORE_PGCB_SELECT_CRC_CHECKER_MASK (0x300U)
#define BRPHY1GV2_T1_CORE_PGCB_SELECT_CRC_CHECKER_SHIFT (8U)
#define BRPHY1GV2_T1_CORE_PGCB_GENERATE_RANDOM_PKT_SIZE_MASK (0x4U)
#define BRPHY1GV2_T1_CORE_PGCB_GENERATE_RANDOM_PKT_SIZE_SHIFT (2U)
#define BRPHY1GV2_T1_CORE_PGCB_CARRIER_EXTENSION_MASK (0x2U)
#define BRPHY1GV2_T1_CORE_PGCB_CARRIER_EXTENSION_SHIFT (1U)
#define BRPHY1GV2_T1_CORE_PGCB_GENERATE_RANDOM_DATA_MASK (0x1U)
#define BRPHY1GV2_T1_CORE_PGCB_GENERATE_RANDOM_DATA_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1_CORE_PATTERN_GEN_STATUS_TYPE;
#define BRPHY1GV2_T1_CORE_PATTERN_GEN_STATUS_PAT_ACTIVE_MASK (0x8U)
#define BRPHY1GV2_T1_CORE_PATTERN_GEN_STATUS_PAT_ACTIVE_SHIFT (3U)
#define BRPHY1GV2_T1_CORE_PATTERN_GEN_STATUS_PAT_FSM_MASK (0x7U)
#define BRPHY1GV2_T1_CORE_PATTERN_GEN_STATUS_PAT_FSM_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1_CORE_CRC_ERROR_COUNTER_TYPE;
#define BRPHY1GV2_T1_CORE_CRC_ERROR_COUNTER_COUNT_MASK (0xffffU)
#define BRPHY1GV2_T1_CORE_CRC_ERROR_COUNTER_COUNT_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1_CORE_PACKET_COUNTER_TYPE;
#define BRPHY1GV2_T1_CORE_PACKET_COUNTER_COUNT_MASK (0xffffU)
#define BRPHY1GV2_T1_CORE_PACKET_COUNTER_COUNT_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1_CORE_RCOE_TYPE;
#define BRPHY1GV2_T1_CORE_RCOE_CLKOFF_RXC_CLOCK_MASK (0x8000U)
#define BRPHY1GV2_T1_CORE_RCOE_CLKOFF_RXC_CLOCK_SHIFT (15U)
#define BRPHY1GV2_T1_CORE_RCOE_CLKOFF_GPCS_RX_CLOCK_MASK (0x4000U)
#define BRPHY1GV2_T1_CORE_RCOE_CLKOFF_GPCS_RX_CLOCK_SHIFT (14U)
#define BRPHY1GV2_T1_CORE_RCOE_CLKOFF_125_25MHZ_RX_CLOCK_MASK (0x2000U)
#define BRPHY1GV2_T1_CORE_RCOE_CLKOFF_125_25MHZ_RX_CLOCK_SHIFT (13U)
#define BRPHY1GV2_T1_CORE_RCOE_CLKOFF_250_50MHZ_RX_CLOCK_MASK (0x1000U)
#define BRPHY1GV2_T1_CORE_RCOE_CLKOFF_250_50MHZ_RX_CLOCK_SHIFT (12U)
#define BRPHY1GV2_T1_CORE_RCOE_CLKOFF_PCS_RX_CLOCK_MASK (0x800U)
#define BRPHY1GV2_T1_CORE_RCOE_CLKOFF_PCS_RX_CLOCK_SHIFT (11U)
#define BRPHY1GV2_T1_CORE_RCOE_CLKOFF_FECRXFIFO_RX_CLOCK_MASK (0x400U)
#define BRPHY1GV2_T1_CORE_RCOE_CLKOFF_FECRXFIFO_RX_CLOCK_SHIFT (10U)
#define BRPHY1GV2_T1_CORE_RCOE_NOT_USED_MASK (0x3c0U)
#define BRPHY1GV2_T1_CORE_RCOE_NOT_USED_SHIFT (6U)
#define BRPHY1GV2_T1_CORE_RCOE_CLKOFF_DSP_RX_CLOCK_MASK (0x20U)
#define BRPHY1GV2_T1_CORE_RCOE_CLKOFF_DSP_RX_CLOCK_SHIFT (5U)
#define BRPHY1GV2_T1_CORE_RCOE_CLKOFF_RX_INTFC_RX_CLOCK_MASK (0x10U)
#define BRPHY1GV2_T1_CORE_RCOE_CLKOFF_RX_INTFC_RX_CLOCK_SHIFT (4U)
#define BRPHY1GV2_T1_CORE_RCOE_CLKOFF_ADCCAL_RX_CLOCK_MASK (0x8U)
#define BRPHY1GV2_T1_CORE_RCOE_CLKOFF_ADCCAL_RX_CLOCK_SHIFT (3U)
#define BRPHY1GV2_T1_CORE_RCOE_CLKOFF_ACD_RX_CLOCK_MASK (0x4U)
#define BRPHY1GV2_T1_CORE_RCOE_CLKOFF_ACD_RX_CLOCK_SHIFT (2U)
#define BRPHY1GV2_T1_CORE_RCOE_CLKOFF_TPC2_RX_CLOCK_MASK (0x2U)
#define BRPHY1GV2_T1_CORE_RCOE_CLKOFF_TPC2_RX_CLOCK_SHIFT (1U)
#define BRPHY1GV2_T1_CORE_RCOE_CLKOFF_TPC1_RX_CLOCK_MASK (0x1U)
#define BRPHY1GV2_T1_CORE_RCOE_CLKOFF_TPC1_RX_CLOCK_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1_CORE_RCOV_TYPE;
#define BRPHY1GV2_T1_CORE_RCOV_CLKOFF_RXC_CLOCK_MASK (0x8000U)
#define BRPHY1GV2_T1_CORE_RCOV_CLKOFF_RXC_CLOCK_SHIFT (15U)
#define BRPHY1GV2_T1_CORE_RCOV_CLKOFF_GPCS_RX_CLOCK_MASK (0x4000U)
#define BRPHY1GV2_T1_CORE_RCOV_CLKOFF_GPCS_RX_CLOCK_SHIFT (14U)
#define BRPHY1GV2_T1_CORE_RCOV_CLKOFF_125_25MHZ_RX_CLOCK_MASK (0x2000U)
#define BRPHY1GV2_T1_CORE_RCOV_CLKOFF_125_25MHZ_RX_CLOCK_SHIFT (13U)
#define BRPHY1GV2_T1_CORE_RCOV_CLKOFF_250_50MHZ_RX_CLOCK_MASK (0x1000U)
#define BRPHY1GV2_T1_CORE_RCOV_CLKOFF_250_50MHZ_RX_CLOCK_SHIFT (12U)
#define BRPHY1GV2_T1_CORE_RCOV_CLKOFF_PCS_RX_CLOCK_MASK (0x800U)
#define BRPHY1GV2_T1_CORE_RCOV_CLKOFF_PCS_RX_CLOCK_SHIFT (11U)
#define BRPHY1GV2_T1_CORE_RCOV_CLKOFF_FECRXFIFO_RX_CLOCK_MASK (0x400U)
#define BRPHY1GV2_T1_CORE_RCOV_CLKOFF_FECRXFIFO_RX_CLOCK_SHIFT (10U)
#define BRPHY1GV2_T1_CORE_RCOV_NOT_USED_MASK (0x3c0U)
#define BRPHY1GV2_T1_CORE_RCOV_NOT_USED_SHIFT (6U)
#define BRPHY1GV2_T1_CORE_RCOV_CLKOFF_DSP_RX_CLOCK_MASK (0x20U)
#define BRPHY1GV2_T1_CORE_RCOV_CLKOFF_DSP_RX_CLOCK_SHIFT (5U)
#define BRPHY1GV2_T1_CORE_RCOV_CLKOFF_RX_INTFC_RX_CLOCK_MASK (0x10U)
#define BRPHY1GV2_T1_CORE_RCOV_CLKOFF_RX_INTFC_RX_CLOCK_SHIFT (4U)
#define BRPHY1GV2_T1_CORE_RCOV_CLKOFF_ADCCAL_RX_CLOCK_MASK (0x8U)
#define BRPHY1GV2_T1_CORE_RCOV_CLKOFF_ADCCAL_RX_CLOCK_SHIFT (3U)
#define BRPHY1GV2_T1_CORE_RCOV_CLKOFF_ACD_RX_CLOCK_MASK (0x4U)
#define BRPHY1GV2_T1_CORE_RCOV_CLKOFF_ACD_RX_CLOCK_SHIFT (2U)
#define BRPHY1GV2_T1_CORE_RCOV_CLKOFF_TPC2_RX_CLOCK_MASK (0x2U)
#define BRPHY1GV2_T1_CORE_RCOV_CLKOFF_TPC2_RX_CLOCK_SHIFT (1U)
#define BRPHY1GV2_T1_CORE_RCOV_CLKOFF_TPC1_RX_CLOCK_MASK (0x1U)
#define BRPHY1GV2_T1_CORE_RCOV_CLKOFF_TPC1_RX_CLOCK_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1_CORE_CLOCK_GEN_STATUS_TYPE;
#define BRPHY1GV2_T1_CORE_CLOCK_GEN_STATUS_BITS_MASK (0xffffU)
#define BRPHY1GV2_T1_CORE_CLOCK_GEN_STATUS_BITS_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1_CORE_CORE_INTR_STATUS_TYPE;
#define BRPHY1GV2_T1_CORE_CORE_INTR_STATUS_AUTONEG_COMPLETE_MASK (0x8000U)
#define BRPHY1GV2_T1_CORE_CORE_INTR_STATUS_AUTONEG_COMPLETE_SHIFT (15U)
#define BRPHY1GV2_T1_CORE_CORE_INTR_STATUS_AUTONEG_PAGE_RECEIVED_MASK (0x4000U)
#define BRPHY1GV2_T1_CORE_CORE_INTR_STATUS_AUTONEG_PAGE_RECEIVED_SHIFT (14U)
#define BRPHY1GV2_T1_CORE_CORE_INTR_STATUS_AUTONEG_RESTARTED_MASK (0x2000U)
#define BRPHY1GV2_T1_CORE_CORE_INTR_STATUS_AUTONEG_RESTARTED_SHIFT (13U)
#define BRPHY1GV2_T1_CORE_CORE_INTR_STATUS_FREEZE_DONE_MASK (0x4U)
#define BRPHY1GV2_T1_CORE_CORE_INTR_STATUS_FREEZE_DONE_SHIFT (2U)
#define BRPHY1GV2_T1_CORE_CORE_INTR_STATUS_CRC_ERROR_DETECTED_MASK (0x2U)
#define BRPHY1GV2_T1_CORE_CORE_INTR_STATUS_CRC_ERROR_DETECTED_SHIFT (1U)
#define BRPHY1GV2_T1_CORE_CORE_INTR_STATUS_PATTERN_GEN_STOPPED_MASK (0x1U)
#define BRPHY1GV2_T1_CORE_CORE_INTR_STATUS_PATTERN_GEN_STOPPED_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1_CORE_CORE_INTR_ENABLE_TYPE;
#define BRPHY1GV2_T1_CORE_CORE_INTR_ENABLE_MASK (0xffffU)
#define BRPHY1GV2_T1_CORE_CORE_INTR_ENABLE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1_CORE_TCOE_TYPE;
#define BRPHY1GV2_T1_CORE_TCOE_RC_OSC_EN_OVERRIDE_ENABLE_MASK (0x8000U)
#define BRPHY1GV2_T1_CORE_TCOE_RC_OSC_EN_OVERRIDE_ENABLE_SHIFT (15U)
#define BRPHY1GV2_T1_CORE_TCOE_RC_OSC_IN_OVERRIDE_ENABLE_MASK (0x4000U)
#define BRPHY1GV2_T1_CORE_TCOE_RC_OSC_IN_OVERRIDE_ENABLE_SHIFT (14U)
#define BRPHY1GV2_T1_CORE_TCOE_RC_OSC_SEL_MASK (0x2000U)
#define BRPHY1GV2_T1_CORE_TCOE_RC_OSC_SEL_SHIFT (13U)
#define BRPHY1GV2_T1_CORE_TCOE_CLKOFF_TPC_TX_CLOCK_MASK (0x1000U)
#define BRPHY1GV2_T1_CORE_TCOE_CLKOFF_TPC_TX_CLOCK_SHIFT (12U)
#define BRPHY1GV2_T1_CORE_TCOE_CLKOFF_TPC_RX_CLOCK_MASK (0x800U)
#define BRPHY1GV2_T1_CORE_TCOE_CLKOFF_TPC_RX_CLOCK_SHIFT (11U)
#define BRPHY1GV2_T1_CORE_TCOE_SPARE_MASK (0x400U)
#define BRPHY1GV2_T1_CORE_TCOE_SPARE_SHIFT (10U)
#define BRPHY1GV2_T1_CORE_TCOE_CLKOFF_CRC_CHECK_CLOCK_MASK (0x200U)
#define BRPHY1GV2_T1_CORE_TCOE_CLKOFF_CRC_CHECK_CLOCK_SHIFT (9U)
#define BRPHY1GV2_T1_CORE_TCOE_CLKOFF_PATGEN_CLOCK_MASK (0x100U)
#define BRPHY1GV2_T1_CORE_TCOE_CLKOFF_PATGEN_CLOCK_SHIFT (8U)
#define BRPHY1GV2_T1_CORE_TCOE_CLKOFF_GPCS_TX_CLOCK_MASK (0x80U)
#define BRPHY1GV2_T1_CORE_TCOE_CLKOFF_GPCS_TX_CLOCK_SHIFT (7U)
#define BRPHY1GV2_T1_CORE_TCOE_CLKOFF_TX_CLOCK_125_25_MASK (0x40U)
#define BRPHY1GV2_T1_CORE_TCOE_CLKOFF_TX_CLOCK_125_25_SHIFT (6U)
#define BRPHY1GV2_T1_CORE_TCOE_CLKOFF_FECTX_TX_CLOCK_MASK (0x20U)
#define BRPHY1GV2_T1_CORE_TCOE_CLKOFF_FECTX_TX_CLOCK_SHIFT (5U)
#define BRPHY1GV2_T1_CORE_TCOE_CLKOFF_PCS_TX_CLOCK_MASK (0x10U)
#define BRPHY1GV2_T1_CORE_TCOE_CLKOFF_PCS_TX_CLOCK_SHIFT (4U)
#define BRPHY1GV2_T1_CORE_TCOE_NOT_USED_MASK (0x8U)
#define BRPHY1GV2_T1_CORE_TCOE_NOT_USED_SHIFT (3U)
#define BRPHY1GV2_T1_CORE_TCOE_CLKOFF_SCR_TX_CLOCK_MASK (0x4U)
#define BRPHY1GV2_T1_CORE_TCOE_CLKOFF_SCR_TX_CLOCK_SHIFT (2U)
#define BRPHY1GV2_T1_CORE_TCOE_NOT_USED1_MASK (0x2U)
#define BRPHY1GV2_T1_CORE_TCOE_NOT_USED1_SHIFT (1U)
#define BRPHY1GV2_T1_CORE_TCOE_CLKOFF_ACD_TX_CLOCK_MASK (0x1U)
#define BRPHY1GV2_T1_CORE_TCOE_CLKOFF_ACD_TX_CLOCK_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1_CORE_TCOV_TYPE;
#define BRPHY1GV2_T1_CORE_TCOV_RC_OSC_EN_OVERRIDE_VALUE_MASK (0x8000U)
#define BRPHY1GV2_T1_CORE_TCOV_RC_OSC_EN_OVERRIDE_VALUE_SHIFT (15U)
#define BRPHY1GV2_T1_CORE_TCOV_RC_OSC_IN_OVERRIDE_VALUE_MASK (0x4000U)
#define BRPHY1GV2_T1_CORE_TCOV_RC_OSC_IN_OVERRIDE_VALUE_SHIFT (14U)
#define BRPHY1GV2_T1_CORE_TCOV_DISABLE_DSP_RDB_CLOCK_MASK (0x2000U)
#define BRPHY1GV2_T1_CORE_TCOV_DISABLE_DSP_RDB_CLOCK_SHIFT (13U)
#define BRPHY1GV2_T1_CORE_TCOV_CLKOFF_TPC_TX_CLOCK_MASK (0x1000U)
#define BRPHY1GV2_T1_CORE_TCOV_CLKOFF_TPC_TX_CLOCK_SHIFT (12U)
#define BRPHY1GV2_T1_CORE_TCOV_CLKOFF_TPC_RX_CLOCK_MASK (0x800U)
#define BRPHY1GV2_T1_CORE_TCOV_CLKOFF_TPC_RX_CLOCK_SHIFT (11U)
#define BRPHY1GV2_T1_CORE_TCOV_SPARE_MASK (0x400U)
#define BRPHY1GV2_T1_CORE_TCOV_SPARE_SHIFT (10U)
#define BRPHY1GV2_T1_CORE_TCOV_CLKOFF_CRC_CHECK_CLOCK_MASK (0x200U)
#define BRPHY1GV2_T1_CORE_TCOV_CLKOFF_CRC_CHECK_CLOCK_SHIFT (9U)
#define BRPHY1GV2_T1_CORE_TCOV_CLKOFF_PATGEN_CLOCK_MASK (0x100U)
#define BRPHY1GV2_T1_CORE_TCOV_CLKOFF_PATGEN_CLOCK_SHIFT (8U)
#define BRPHY1GV2_T1_CORE_TCOV_CLKOFF_GPCS_TX_CLOCK_MASK (0x80U)
#define BRPHY1GV2_T1_CORE_TCOV_CLKOFF_GPCS_TX_CLOCK_SHIFT (7U)
#define BRPHY1GV2_T1_CORE_TCOV_CLKOFF_TX_CLOCK_125_25_MASK (0x40U)
#define BRPHY1GV2_T1_CORE_TCOV_CLKOFF_TX_CLOCK_125_25_SHIFT (6U)
#define BRPHY1GV2_T1_CORE_TCOV_CLKOFF_FECTX_TX_CLOCK_MASK (0x20U)
#define BRPHY1GV2_T1_CORE_TCOV_CLKOFF_FECTX_TX_CLOCK_SHIFT (5U)
#define BRPHY1GV2_T1_CORE_TCOV_CLKOFF_PCS_TX_CLOCK_MASK (0x10U)
#define BRPHY1GV2_T1_CORE_TCOV_CLKOFF_PCS_TX_CLOCK_SHIFT (4U)
#define BRPHY1GV2_T1_CORE_TCOV_NOT_USED_MASK (0x8U)
#define BRPHY1GV2_T1_CORE_TCOV_NOT_USED_SHIFT (3U)
#define BRPHY1GV2_T1_CORE_TCOV_CLKOFF_SCR_TX_CLOCK_MASK (0x4U)
#define BRPHY1GV2_T1_CORE_TCOV_CLKOFF_SCR_TX_CLOCK_SHIFT (2U)
#define BRPHY1GV2_T1_CORE_TCOV_NOT_USED1_MASK (0x2U)
#define BRPHY1GV2_T1_CORE_TCOV_NOT_USED1_SHIFT (1U)
#define BRPHY1GV2_T1_CORE_TCOV_CLKOFF_ACD_TX_CLOCK_MASK (0x1U)
#define BRPHY1GV2_T1_CORE_TCOV_CLKOFF_ACD_TX_CLOCK_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1_CORE_CLOCK_GEN_STATUS2_TYPE;
#define BRPHY1GV2_T1_CORE_CLOCK_GEN_STATUS2_RC_OSC_IN_VALUE_MASK (0x8000U)
#define BRPHY1GV2_T1_CORE_CLOCK_GEN_STATUS2_RC_OSC_IN_VALUE_SHIFT (15U)
#define BRPHY1GV2_T1_CORE_CLOCK_GEN_STATUS2_CLOCK_GEN_STATUS_BITS_MASK (0x7fffU)
#define BRPHY1GV2_T1_CORE_CLOCK_GEN_STATUS2_CLOCK_GEN_STATUS_BITS_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1_CORE_PGCC_TYPE;
#define BRPHY1GV2_T1_CORE_PGCC_PATTERN_GEN_NUM_OF_PACKETS_MASK (0xffffU)
#define BRPHY1GV2_T1_CORE_PGCC_PATTERN_GEN_NUM_OF_PACKETS_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1_CORE_PATTERN_GEN_CONTROL_D_TYPE;
#define BRPHY1GV2_T1_CORE_PATTERN_GEN_CONTROL_D_PKT_SIZE_MASK (0xffffU)
#define BRPHY1GV2_T1_CORE_PATTERN_GEN_CONTROL_D_PKT_SIZE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1_CORE_WUP_TEST_CONTROL_TYPE;
#define BRPHY1GV2_T1_CORE_WUP_TEST_CONTROL_POLARITY_SWAP_MASK (0x4U)
#define BRPHY1GV2_T1_CORE_WUP_TEST_CONTROL_POLARITY_SWAP_SHIFT (2U)
#define BRPHY1GV2_T1_CORE_WUP_TEST_CONTROL_SYMBOL_SWAP_MASK (0x2U)
#define BRPHY1GV2_T1_CORE_WUP_TEST_CONTROL_SYMBOL_SWAP_SHIFT (1U)
#define BRPHY1GV2_T1_CORE_WUP_TEST_CONTROL_EDGERATE_ENABLE_MASK (0x1U)
#define BRPHY1GV2_T1_CORE_WUP_TEST_CONTROL_EDGERATE_ENABLE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1_CORE_MIIF_CONT_TYPE;
#define BRPHY1GV2_T1_CORE_MIIF_CONT_MIIFIFO_SFT_RESET_MASK (0x8000U)
#define BRPHY1GV2_T1_CORE_MIIF_CONT_MIIFIFO_SFT_RESET_SHIFT (15U)
#define BRPHY1GV2_T1_CORE_MIIF_CONT_MIIFIFO_DISABLE_FIFO_MASK (0x4000U)
#define BRPHY1GV2_T1_CORE_MIIF_CONT_MIIFIFO_DISABLE_FIFO_SHIFT (14U)
#define BRPHY1GV2_T1_CORE_MIIF_CONT_MIIFIFO_LPI_FEATURE_ENABLE_MASK (0x2000U)
#define BRPHY1GV2_T1_CORE_MIIF_CONT_MIIFIFO_LPI_FEATURE_ENABLE_SHIFT (13U)
#define BRPHY1GV2_T1_CORE_MIIF_CONT_MIIFIFO_MIN_IPG_MASK (0xf00U)
#define BRPHY1GV2_T1_CORE_MIIF_CONT_MIIFIFO_MIN_IPG_SHIFT (8U)
#define BRPHY1GV2_T1_CORE_MIIF_CONT_MIIFIFO_WRBLOCK_OVR_MASK (0xf0U)
#define BRPHY1GV2_T1_CORE_MIIF_CONT_MIIFIFO_WRBLOCK_OVR_SHIFT (4U)
#define BRPHY1GV2_T1_CORE_MIIF_CONT_MIIFIFO_WRBLOCK_MODE_MASK (0x8U)
#define BRPHY1GV2_T1_CORE_MIIF_CONT_MIIFIFO_WRBLOCK_MODE_SHIFT (3U)
#define BRPHY1GV2_T1_CORE_MIIF_CONT_MIIFIFO_ELASTICITY_MODE_MASK (0x3U)
#define BRPHY1GV2_T1_CORE_MIIF_CONT_MIIFIFO_ELASTICITY_MODE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1_CORE_TRA_TYPE;
#define BRPHY1GV2_T1_CORE_TRA_PHY_CONTROL_TUNING_PARAMETERS_MASK (0xf000U)
#define BRPHY1GV2_T1_CORE_TRA_PHY_CONTROL_TUNING_PARAMETERS_SHIFT (12U)
#define BRPHY1GV2_T1_CORE_TRA_DSP_TUNING_PARAMETERS_MASK (0xf00U)
#define BRPHY1GV2_T1_CORE_TRA_DSP_TUNING_PARAMETERS_SHIFT (8U)
#define BRPHY1GV2_T1_CORE_TRA_FORCED_POLARITY_ENABLE_MASK (0x8U)
#define BRPHY1GV2_T1_CORE_TRA_FORCED_POLARITY_ENABLE_SHIFT (3U)
#define BRPHY1GV2_T1_CORE_TRA_FORCED_POLARITY_VALUE_MASK (0x4U)
#define BRPHY1GV2_T1_CORE_TRA_FORCED_POLARITY_VALUE_SHIFT (2U)
#define BRPHY1GV2_T1_CORE_TRA_FORCED_MSE_OK_MASK (0x2U)
#define BRPHY1GV2_T1_CORE_TRA_FORCED_MSE_OK_SHIFT (1U)
#define BRPHY1GV2_T1_CORE_TRA_FORCED_ALIGNMENT_MASK (0x1U)
#define BRPHY1GV2_T1_CORE_TRA_FORCED_ALIGNMENT_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1_CORE_TRB_TYPE;
#define BRPHY1GV2_T1_CORE_TRB_PHY_STATE_MASK (0xff00U)
#define BRPHY1GV2_T1_CORE_TRB_PHY_STATE_SHIFT (8U)
#define BRPHY1GV2_T1_CORE_TRB_SYNCHRONIZATION_DONE_MASK (0x40U)
#define BRPHY1GV2_T1_CORE_TRB_SYNCHRONIZATION_DONE_SHIFT (6U)
#define BRPHY1GV2_T1_CORE_TRB_ADC_OVERFLOW_MASK (0x20U)
#define BRPHY1GV2_T1_CORE_TRB_ADC_OVERFLOW_SHIFT (5U)
#define BRPHY1GV2_T1_CORE_TRB_ALIGNMENT_OK_MASK (0x10U)
#define BRPHY1GV2_T1_CORE_TRB_ALIGNMENT_OK_SHIFT (4U)
#define BRPHY1GV2_T1_CORE_TRB_CRC_ERROR_MASK (0x8U)
#define BRPHY1GV2_T1_CORE_TRB_CRC_ERROR_SHIFT (3U)
#define BRPHY1GV2_T1_CORE_TRB_RETRAIN_MASK (0x4U)
#define BRPHY1GV2_T1_CORE_TRB_RETRAIN_SHIFT (2U)
#define BRPHY1GV2_T1_CORE_TRB_REMOTE_RECEIVER_STATUS_MASK (0x2U)
#define BRPHY1GV2_T1_CORE_TRB_REMOTE_RECEIVER_STATUS_SHIFT (1U)
#define BRPHY1GV2_T1_CORE_TRB_LOCAL_RECEIVER_STATUS_MASK (0x1U)
#define BRPHY1GV2_T1_CORE_TRB_LOCAL_RECEIVER_STATUS_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1_CORE_TRC_TYPE;
#define BRPHY1GV2_T1_CORE_TRC_INTERNAL_LOOPBACK_MASK (0x4000U)
#define BRPHY1GV2_T1_CORE_TRC_INTERNAL_LOOPBACK_SHIFT (14U)
#define BRPHY1GV2_T1_CORE_TRC_AGC_FREEZE_MASK (0x80U)
#define BRPHY1GV2_T1_CORE_TRC_AGC_FREEZE_SHIFT (7U)
#define BRPHY1GV2_T1_CORE_TRC_AGC_OVERRIDE_ENABLE_MASK (0x40U)
#define BRPHY1GV2_T1_CORE_TRC_AGC_OVERRIDE_ENABLE_SHIFT (6U)
#define BRPHY1GV2_T1_CORE_TRC_AGC_VALUE_OR_OVERRIDE_VALUE_MASK (0x3fU)
#define BRPHY1GV2_T1_CORE_TRC_AGC_VALUE_OR_OVERRIDE_VALUE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1_CORE_NOCP_TYPE;
#define BRPHY1GV2_T1_CORE_NOCP_NUMBER_OF_CORRECTED_RS_PACKETS_MASK (0xffffU)
#define BRPHY1GV2_T1_CORE_NOCP_NUMBER_OF_CORRECTED_RS_PACKETS_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1_CORE_FREEZE_COUNTER_LSB_TYPE;
#define BRPHY1GV2_T1_CORE_FREEZE_COUNTER_LSB_MASK (0xffffU)
#define BRPHY1GV2_T1_CORE_FREEZE_COUNTER_LSB_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1_CORE_FREEZE_COUNTER_MSB_TYPE;
#define BRPHY1GV2_T1_CORE_FREEZE_COUNTER_MSB_MASK (0xffffU)
#define BRPHY1GV2_T1_CORE_FREEZE_COUNTER_MSB_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1_CORE_FREEZE_TYPE;
#define BRPHY1GV2_T1_CORE_FREEZE_TYPE_MASK (0x7U)
#define BRPHY1GV2_T1_CORE_FREEZE_TYPE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1_CORE_PCS_SOP_CONTROL_TYPE;
#define BRPHY1GV2_T1_CORE_PCS_SOP_CONTROL_TIMESYNC_ENABLE_MASK (0x8U)
#define BRPHY1GV2_T1_CORE_PCS_SOP_CONTROL_TIMESYNC_ENABLE_SHIFT (3U)
#define BRPHY1GV2_T1_CORE_PCS_SOP_CONTROL_TX_SOP_SELECT_MASK (0x4U)
#define BRPHY1GV2_T1_CORE_PCS_SOP_CONTROL_TX_SOP_SELECT_SHIFT (2U)
#define BRPHY1GV2_T1_CORE_PCS_SOP_CONTROL_RX_SOP_SELECT_MASK (0x2U)
#define BRPHY1GV2_T1_CORE_PCS_SOP_CONTROL_RX_SOP_SELECT_SHIFT (1U)
#define BRPHY1GV2_T1_CORE_PCS_SOP_CONTROL_RXSOP_SFD_OPT_MASK (0x1U)
#define BRPHY1GV2_T1_CORE_PCS_SOP_CONTROL_RXSOP_SFD_OPT_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1_CORE_PCS_SOP_STATUS_TYPE;
#define BRPHY1GV2_T1_CORE_PCS_SOP_STATUS_G_TSYNC_ERR_TX_MASK (0x2U)
#define BRPHY1GV2_T1_CORE_PCS_SOP_STATUS_G_TSYNC_ERR_TX_SHIFT (1U)
#define BRPHY1GV2_T1_CORE_PCS_SOP_STATUS_G_TSYNC_ERR_RX_MASK (0x1U)
#define BRPHY1GV2_T1_CORE_PCS_SOP_STATUS_G_TSYNC_ERR_RX_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1_CORE_CLOCK_GEN_STATUS3_TYPE;
#define BRPHY1GV2_T1_CORE_CLOCK_GEN_STATUS3_STATUS_BITS_MASK (0xffffU)
#define BRPHY1GV2_T1_CORE_CLOCK_GEN_STATUS3_STATUS_BITS_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1_CORE_RFGCFBIT_TYPE;
#define BRPHY1GV2_T1_CORE_RFGCFBIT_PATGEN_GTX_CLK_SELECT_MASK (0x2U)
#define BRPHY1GV2_T1_CORE_RFGCFBIT_PATGEN_GTX_CLK_SELECT_SHIFT (1U)
#define BRPHY1GV2_T1_CORE_RFGCFBIT_RFGCFBIT1_MASK (0x1U)
#define BRPHY1GV2_T1_CORE_RFGCFBIT_RFGCFBIT1_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1_CORE_HARD_RESET_COUNT_TYPE;
#define BRPHY1GV2_T1_CORE_HARD_RESET_COUNT_MASK (0xffffU)
#define BRPHY1GV2_T1_CORE_HARD_RESET_COUNT_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1_CORE_ISRC_TYPE;
#define BRPHY1GV2_T1_CORE_ISRC_IEEE_SOFT_RESET_COUNT_MASK (0xffffU)
#define BRPHY1GV2_T1_CORE_ISRC_IEEE_SOFT_RESET_COUNT_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1_CORE_E70SRC_TYPE;
#define BRPHY1GV2_T1_CORE_E70SRC_EXP70_SOFT_RESET_COUNT_MASK (0xffffU)
#define BRPHY1GV2_T1_CORE_E70SRC_EXP70_SOFT_RESET_COUNT_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1_CORE_SAFETY_CONCEPT_TYPE;
#define BRPHY1GV2_T1_CORE_SAFETY_CONCEPT_TX_DISABLE_OCCUR_MASK (0x2U)
#define BRPHY1GV2_T1_CORE_SAFETY_CONCEPT_TX_DISABLE_OCCUR_SHIFT (1U)
#define BRPHY1GV2_T1_CORE_SAFETY_CONCEPT_SAFETY_CONCEPT_EN_MASK (0x1U)
#define BRPHY1GV2_T1_CORE_SAFETY_CONCEPT_SAFETY_CONCEPT_EN_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1_CORE_PSD_CNTRL_TYPE;
#define BRPHY1GV2_T1_CORE_PSD_CNTRL_BR_PIN_DISABLE_MASK (0x2U)
#define BRPHY1GV2_T1_CORE_PSD_CNTRL_BR_PIN_DISABLE_SHIFT (1U)
#define BRPHY1GV2_T1_CORE_PSD_CNTRL_BR_OFF_MASK (0x1U)
#define BRPHY1GV2_T1_CORE_PSD_CNTRL_BR_OFF_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1_CORE_DCCFLD_TYPE;
#define BRPHY1GV2_T1_CORE_DCCFLD_DSP_CLK_COUNTER_FROM_LINK_DROP_MASK (0xffU)
#define BRPHY1GV2_T1_CORE_DCCFLD_DSP_CLK_COUNTER_FROM_LINK_DROP_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1_CORE_SPARE_END_ADDR_TYPE;
#define BRPHY1GV2_T1_CORE_SPARE_END_ADDR_MASK (0xffffU)
#define BRPHY1GV2_T1_CORE_SPARE_END_ADDR_SHIFT (0U)




typedef volatile struct sBRPHY1GV2_T1_CORE_RDBType {
    BRPHY1GV2_T1_CORE_PGCA_TYPE pattern_gen_control_a; /* OFFSET: 0x0 */
    BRPHY1GV2_T1_CORE_RESERVED_TYPE rsvd0[2]; /* OFFSET: 0x2 */
    BRPHY1GV2_T1_CORE_PGCB_TYPE pattern_gen_control_b; /* OFFSET: 0x4 */
    BRPHY1GV2_T1_CORE_RESERVED_TYPE rsvd1[2]; /* OFFSET: 0x6 */
    BRPHY1GV2_T1_CORE_PATTERN_GEN_STATUS_TYPE pattern_gen_status; /* OFFSET: 0x8 */
    BRPHY1GV2_T1_CORE_RESERVED_TYPE rsvd2[2]; /* OFFSET: 0xa */
    BRPHY1GV2_T1_CORE_CRC_ERROR_COUNTER_TYPE crc_error_counter; /* OFFSET: 0xc */
    BRPHY1GV2_T1_CORE_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0xe */
    BRPHY1GV2_T1_CORE_PACKET_COUNTER_TYPE packet_counter; /* OFFSET: 0x10 */
    BRPHY1GV2_T1_CORE_RESERVED_TYPE rsvd4[2]; /* OFFSET: 0x12 */
    BRPHY1GV2_T1_CORE_RCOE_TYPE rx_clock_override_enable; /* OFFSET: 0x14 */
    BRPHY1GV2_T1_CORE_RESERVED_TYPE rsvd5[2]; /* OFFSET: 0x16 */
    BRPHY1GV2_T1_CORE_RCOV_TYPE rx_clock_override_value; /* OFFSET: 0x18 */
    BRPHY1GV2_T1_CORE_RESERVED_TYPE rsvd6[2]; /* OFFSET: 0x1a */
    BRPHY1GV2_T1_CORE_CLOCK_GEN_STATUS_TYPE clock_gen_status; /* OFFSET: 0x1c */
    BRPHY1GV2_T1_CORE_RESERVED_TYPE rsvd7[2]; /* OFFSET: 0x1e */
    BRPHY1GV2_T1_CORE_CORE_INTR_STATUS_TYPE core_intr_status; /* OFFSET: 0x20 */
    BRPHY1GV2_T1_CORE_RESERVED_TYPE rsvd8[2]; /* OFFSET: 0x22 */
    BRPHY1GV2_T1_CORE_CORE_INTR_ENABLE_TYPE core_intr_enable; /* OFFSET: 0x24 */
    BRPHY1GV2_T1_CORE_RESERVED_TYPE rsvd9[2]; /* OFFSET: 0x26 */
    BRPHY1GV2_T1_CORE_TCOE_TYPE tx_clock_override_enable; /* OFFSET: 0x28 */
    BRPHY1GV2_T1_CORE_RESERVED_TYPE rsvd10[2]; /* OFFSET: 0x2a */
    BRPHY1GV2_T1_CORE_TCOV_TYPE tx_clock_override_value; /* OFFSET: 0x2c */
    BRPHY1GV2_T1_CORE_RESERVED_TYPE rsvd11[2]; /* OFFSET: 0x2e */
    BRPHY1GV2_T1_CORE_CLOCK_GEN_STATUS2_TYPE clock_gen_status2; /* OFFSET: 0x30 */
    BRPHY1GV2_T1_CORE_RESERVED_TYPE rsvd12[2]; /* OFFSET: 0x32 */
    BRPHY1GV2_T1_CORE_PGCC_TYPE pattern_gen_control_c; /* OFFSET: 0x34 */
    BRPHY1GV2_T1_CORE_RESERVED_TYPE rsvd13[2]; /* OFFSET: 0x36 */
    BRPHY1GV2_T1_CORE_PATTERN_GEN_CONTROL_D_TYPE pattern_gen_control_d; /* OFFSET: 0x38 */
    BRPHY1GV2_T1_CORE_RESERVED_TYPE rsvd14[2]; /* OFFSET: 0x3a */
    BRPHY1GV2_T1_CORE_WUP_TEST_CONTROL_TYPE wup_test_control; /* OFFSET: 0x3c */
    BRPHY1GV2_T1_CORE_RESERVED_TYPE rsvd15[2]; /* OFFSET: 0x3e */
    BRPHY1GV2_T1_CORE_MIIF_CONT_TYPE miififo_control; /* OFFSET: 0x40 */
    BRPHY1GV2_T1_CORE_RESERVED_TYPE rsvd16[190]; /* OFFSET: 0x42 */
    BRPHY1GV2_T1_CORE_TRA_TYPE testability_reg_a; /* OFFSET: 0x100 */
    BRPHY1GV2_T1_CORE_RESERVED_TYPE rsvd17[2]; /* OFFSET: 0x102 */
    BRPHY1GV2_T1_CORE_TRB_TYPE testability_reg_b; /* OFFSET: 0x104 */
    BRPHY1GV2_T1_CORE_RESERVED_TYPE rsvd18[2]; /* OFFSET: 0x106 */
    BRPHY1GV2_T1_CORE_TRC_TYPE testability_reg_c; /* OFFSET: 0x108 */
    BRPHY1GV2_T1_CORE_RESERVED_TYPE rsvd19[2]; /* OFFSET: 0x10a */
    BRPHY1GV2_T1_CORE_NOCP_TYPE number_of_corrected_packets; /* OFFSET: 0x10c */
    BRPHY1GV2_T1_CORE_RESERVED_TYPE rsvd20[2]; /* OFFSET: 0x10e */
    BRPHY1GV2_T1_CORE_FREEZE_COUNTER_LSB_TYPE freeze_counter_lsb; /* OFFSET: 0x110 */
    BRPHY1GV2_T1_CORE_RESERVED_TYPE rsvd21[2]; /* OFFSET: 0x112 */
    BRPHY1GV2_T1_CORE_FREEZE_COUNTER_MSB_TYPE freeze_counter_msb; /* OFFSET: 0x114 */
    BRPHY1GV2_T1_CORE_RESERVED_TYPE rsvd22[2]; /* OFFSET: 0x116 */
    BRPHY1GV2_T1_CORE_FREEZE_TYPE freeze_type; /* OFFSET: 0x118 */
    BRPHY1GV2_T1_CORE_RESERVED_TYPE rsvd23[2]; /* OFFSET: 0x11a */
    BRPHY1GV2_T1_CORE_PCS_SOP_CONTROL_TYPE pcs_sop_control; /* OFFSET: 0x11c */
    BRPHY1GV2_T1_CORE_RESERVED_TYPE rsvd24[2]; /* OFFSET: 0x11e */
    BRPHY1GV2_T1_CORE_PCS_SOP_STATUS_TYPE pcs_sop_status; /* OFFSET: 0x120 */
    BRPHY1GV2_T1_CORE_RESERVED_TYPE rsvd25[2]; /* OFFSET: 0x122 */
    BRPHY1GV2_T1_CORE_CLOCK_GEN_STATUS3_TYPE clock_gen_status3; /* OFFSET: 0x124 */
    BRPHY1GV2_T1_CORE_RESERVED_TYPE rsvd26[2]; /* OFFSET: 0x126 */
    BRPHY1GV2_T1_CORE_RFGCFBIT_TYPE rxc_for_gtx_clk_for_burn_in_test; /* OFFSET: 0x128 */
    BRPHY1GV2_T1_CORE_RESERVED_TYPE rsvd27[2]; /* OFFSET: 0x12a */
    BRPHY1GV2_T1_CORE_HARD_RESET_COUNT_TYPE hard_reset_count; /* OFFSET: 0x12c */
    BRPHY1GV2_T1_CORE_RESERVED_TYPE rsvd28[2]; /* OFFSET: 0x12e */
    BRPHY1GV2_T1_CORE_ISRC_TYPE ieee_soft_reset_count; /* OFFSET: 0x130 */
    BRPHY1GV2_T1_CORE_RESERVED_TYPE rsvd29[2]; /* OFFSET: 0x132 */
    BRPHY1GV2_T1_CORE_E70SRC_TYPE exp70_soft_reset_count; /* OFFSET: 0x134 */
    BRPHY1GV2_T1_CORE_RESERVED_TYPE rsvd30[2]; /* OFFSET: 0x136 */
    BRPHY1GV2_T1_CORE_SAFETY_CONCEPT_TYPE safety_concept; /* OFFSET: 0x138 */
    BRPHY1GV2_T1_CORE_RESERVED_TYPE rsvd31[2]; /* OFFSET: 0x13a */
    BRPHY1GV2_T1_CORE_PSD_CNTRL_TYPE psd_cntrl_0; /* OFFSET: 0x13c */
    BRPHY1GV2_T1_CORE_RESERVED_TYPE rsvd32[2]; /* OFFSET: 0x13e */
    BRPHY1GV2_T1_CORE_DCCFLD_TYPE dsp_clk_counter_from_link_drop; /* OFFSET: 0x140 */
    BRPHY1GV2_T1_CORE_RESERVED_TYPE rsvd33[2746]; /* OFFSET: 0x142 */
    BRPHY1GV2_T1_CORE_SPARE_END_ADDR_TYPE spare_end_addr; /* OFFSET: 0xbfc */
} BRPHY1GV2_T1_CORE_RDBType;


#define BRPHY0_1G_T1_CORE_BASE          (0xE0564000UL)



#define BRPHY1GV2_T1_CORE_MAX_HW_ID     (1UL)

#endif /* BRPHY1GV2_T1_CORE_RDB_H */
