/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file brphy1gv2_br_gpcs_rdb.h
    @brief RDB File for BRPHY1GV2_BR_GPCS

    @version BCM89580_A0_20230125_RDB
*/

#ifndef BRPHY1GV2_BR_GPCS_RDB_H
#define BRPHY1GV2_BR_GPCS_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t BRPHY1GV2_BR_GPCS_GMII_FIFO_CTL0_TYPE;
#define BRPHY1GV2_BR_GPCS_GMII_FIFO_CTL0_CONTROL_MASK (0xffffU)
#define BRPHY1GV2_BR_GPCS_GMII_FIFO_CTL0_CONTROL_SHIFT (0U)




typedef uint8_t BRPHY1GV2_BR_GPCS_RESERVED_TYPE;




typedef uint16_t BRPHY1GV2_BR_GPCS_GMII_FIFO_CTL1_TYPE;
#define BRPHY1GV2_BR_GPCS_GMII_FIFO_CTL1_FIFO_BYPASS_MASK (0x4U)
#define BRPHY1GV2_BR_GPCS_GMII_FIFO_CTL1_FIFO_BYPASS_SHIFT (2U)
#define BRPHY1GV2_BR_GPCS_GMII_FIFO_CTL1_GFEM_MASK (0x3U)
#define BRPHY1GV2_BR_GPCS_GMII_FIFO_CTL1_GFEM_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_DATA_SW_PFC_OFFSET0_TYPE;
#define BRPHY1GV2_BR_GPCS_DATA_SW_PFC_OFFSET0_DATASWPFC24_MASK (0xffffU)
#define BRPHY1GV2_BR_GPCS_DATA_SW_PFC_OFFSET0_DATASWPFC24_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_DSPO1_TYPE;
#define BRPHY1GV2_BR_GPCS_DSPO1_DATASWPFC24_OFFSET_OV_MASK (0x100U)
#define BRPHY1GV2_BR_GPCS_DSPO1_DATASWPFC24_OFFSET_OV_SHIFT (8U)
#define BRPHY1GV2_BR_GPCS_DSPO1_DATASWPFC24_OFFSET1_MASK (0xffU)
#define BRPHY1GV2_BR_GPCS_DSPO1_DATASWPFC24_OFFSET1_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_SCRA_CTL_TYPE;
#define BRPHY1GV2_BR_GPCS_SCRA_CTL_INVERT_TX_POLARITY_MASK (0x10U)
#define BRPHY1GV2_BR_GPCS_SCRA_CTL_INVERT_TX_POLARITY_SHIFT (4U)
#define BRPHY1GV2_BR_GPCS_SCRA_CTL_BYPASS_DATA_SCRAMBLER_MASK (0x8U)
#define BRPHY1GV2_BR_GPCS_SCRA_CTL_BYPASS_DATA_SCRAMBLER_SHIFT (3U)
#define BRPHY1GV2_BR_GPCS_SCRA_CTL_BYPASS_DESCRAMBLER_MASK (0x4U)
#define BRPHY1GV2_BR_GPCS_SCRA_CTL_BYPASS_DESCRAMBLER_SHIFT (2U)
#define BRPHY1GV2_BR_GPCS_SCRA_CTL_BYPASS_TRAINING_SCRAMBLER_MASK (0x2U)
#define BRPHY1GV2_BR_GPCS_SCRA_CTL_BYPASS_TRAINING_SCRAMBLER_SHIFT (1U)
#define BRPHY1GV2_BR_GPCS_SCRA_CTL_BYPASS_TRAINING_DESCRAMBLER_MASK (0x1U)
#define BRPHY1GV2_BR_GPCS_SCRA_CTL_BYPASS_TRAINING_DESCRAMBLER_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_TXPC_SEED_CTL_TYPE;
#define BRPHY1GV2_BR_GPCS_TXPC_SEED_CTL_TXPCS_SEED_SET_MASK (0x8000U)
#define BRPHY1GV2_BR_GPCS_TXPC_SEED_CTL_TXPCS_SEED_SET_SHIFT (15U)
#define BRPHY1GV2_BR_GPCS_TXPC_SEED_CTL_TSSFDM_MASK (0x7fffU)
#define BRPHY1GV2_BR_GPCS_TXPC_SEED_CTL_TSSFDM_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_PAM3_CTL_TYPE;
#define BRPHY1GV2_BR_GPCS_PAM3_CTL_P3125WOAT125_MASK (0x1000U)
#define BRPHY1GV2_BR_GPCS_PAM3_CTL_P3125WOAT125_SHIFT (12U)
#define BRPHY1GV2_BR_GPCS_PAM3_CTL_CP3SPWCAT125_MASK (0xff8U)
#define BRPHY1GV2_BR_GPCS_PAM3_CTL_CP3SPWCAT125_SHIFT (3U)
#define BRPHY1GV2_BR_GPCS_PAM3_CTL_P3375DOAT375_MASK (0x4U)
#define BRPHY1GV2_BR_GPCS_PAM3_CTL_P3375DOAT375_SHIFT (2U)
#define BRPHY1GV2_BR_GPCS_PAM3_CTL_PP3DCAT375_MASK (0x3U)
#define BRPHY1GV2_BR_GPCS_PAM3_CTL_PP3DCAT375_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_OAM_CTL_TYPE;
#define BRPHY1GV2_BR_GPCS_OAM_CTL_TX_CALC_CRC16_BYP_MASK (0x20U)
#define BRPHY1GV2_BR_GPCS_OAM_CTL_TX_CALC_CRC16_BYP_SHIFT (5U)
#define BRPHY1GV2_BR_GPCS_OAM_CTL_RX_OAMCRC_BYP_MASK (0x10U)
#define BRPHY1GV2_BR_GPCS_OAM_CTL_RX_OAMCRC_BYP_SHIFT (4U)
#define BRPHY1GV2_BR_GPCS_OAM_CTL_RX_FECERR_BYP_MASK (0x8U)
#define BRPHY1GV2_BR_GPCS_OAM_CTL_RX_FECERR_BYP_SHIFT (3U)
#define BRPHY1GV2_BR_GPCS_OAM_CTL_RX_PARITY_ERR_BYP_MASK (0x4U)
#define BRPHY1GV2_BR_GPCS_OAM_CTL_RX_PARITY_ERR_BYP_SHIFT (2U)
#define BRPHY1GV2_BR_GPCS_OAM_CTL_TX_OAMSYM_SWAP_MASK (0x2U)
#define BRPHY1GV2_BR_GPCS_OAM_CTL_TX_OAMSYM_SWAP_SHIFT (1U)
#define BRPHY1GV2_BR_GPCS_OAM_CTL_RX_OAMSYM_SWAP_MASK (0x1U)
#define BRPHY1GV2_BR_GPCS_OAM_CTL_RX_OAMSYM_SWAP_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_OAM_STATUS_TYPE;
#define BRPHY1GV2_BR_GPCS_OAM_STATUS_OAM_TC10_WUR_LPS_SENT_MASK (0x100U)
#define BRPHY1GV2_BR_GPCS_OAM_STATUS_OAM_TC10_WUR_LPS_SENT_SHIFT (8U)
#define BRPHY1GV2_BR_GPCS_OAM_STATUS_OAM_FRAME_RX_WUR_MASK (0x80U)
#define BRPHY1GV2_BR_GPCS_OAM_STATUS_OAM_FRAME_RX_WUR_SHIFT (7U)
#define BRPHY1GV2_BR_GPCS_OAM_STATUS_OAM_FRAME_RX_LPS_MASK (0x40U)
#define BRPHY1GV2_BR_GPCS_OAM_STATUS_OAM_FRAME_RX_LPS_SHIFT (6U)
#define BRPHY1GV2_BR_GPCS_OAM_STATUS_OAM_FRAME_TX_WUR_MASK (0x20U)
#define BRPHY1GV2_BR_GPCS_OAM_STATUS_OAM_FRAME_TX_WUR_SHIFT (5U)
#define BRPHY1GV2_BR_GPCS_OAM_STATUS_OAM_FRAME_TX_LPS_MASK (0x10U)
#define BRPHY1GV2_BR_GPCS_OAM_STATUS_OAM_FRAME_TX_LPS_SHIFT (4U)
#define BRPHY1GV2_BR_GPCS_OAM_STATUS_OAM_SYM_PAR_DISORD_MASK (0x8U)
#define BRPHY1GV2_BR_GPCS_OAM_STATUS_OAM_SYM_PAR_DISORD_SHIFT (3U)
#define BRPHY1GV2_BR_GPCS_OAM_STATUS_OAM_INCORRECT_PARITY_MASK (0x4U)
#define BRPHY1GV2_BR_GPCS_OAM_STATUS_OAM_INCORRECT_PARITY_SHIFT (2U)
#define BRPHY1GV2_BR_GPCS_OAM_STATUS_DEC_OUT_ERR_MASK (0x2U)
#define BRPHY1GV2_BR_GPCS_OAM_STATUS_DEC_OUT_ERR_SHIFT (1U)
#define BRPHY1GV2_BR_GPCS_OAM_STATUS_OAM_FRAME_CRC_STATUS_MASK (0x1U)
#define BRPHY1GV2_BR_GPCS_OAM_STATUS_OAM_FRAME_CRC_STATUS_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_RXPC_SEED_CTL_TYPE;
#define BRPHY1GV2_BR_GPCS_RXPC_SEED_CTL_RXPCS_SEED_SET_MASK (0x8000U)
#define BRPHY1GV2_BR_GPCS_RXPC_SEED_CTL_RXPCS_SEED_SET_SHIFT (15U)
#define BRPHY1GV2_BR_GPCS_RXPC_SEED_CTL_RSSFDM_MASK (0x7fffU)
#define BRPHY1GV2_BR_GPCS_RXPC_SEED_CTL_RSSFDM_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_FIFO_STATUS_TYPE;
#define BRPHY1GV2_BR_GPCS_FIFO_STATUS_TXFIFO_UDRUN_FLAG_MASK (0x80U)
#define BRPHY1GV2_BR_GPCS_FIFO_STATUS_TXFIFO_UDRUN_FLAG_SHIFT (7U)
#define BRPHY1GV2_BR_GPCS_FIFO_STATUS_TXFIFO_EMPTY_FLAG_MASK (0x40U)
#define BRPHY1GV2_BR_GPCS_FIFO_STATUS_TXFIFO_EMPTY_FLAG_SHIFT (6U)
#define BRPHY1GV2_BR_GPCS_FIFO_STATUS_TXFIFO_OVRUN_FLAG_MASK (0x20U)
#define BRPHY1GV2_BR_GPCS_FIFO_STATUS_TXFIFO_OVRUN_FLAG_SHIFT (5U)
#define BRPHY1GV2_BR_GPCS_FIFO_STATUS_TXFIFO_FULL_FLAG_MASK (0x10U)
#define BRPHY1GV2_BR_GPCS_FIFO_STATUS_TXFIFO_FULL_FLAG_SHIFT (4U)
#define BRPHY1GV2_BR_GPCS_FIFO_STATUS_RXFIFO_UDRUN_FLAG_MASK (0x8U)
#define BRPHY1GV2_BR_GPCS_FIFO_STATUS_RXFIFO_UDRUN_FLAG_SHIFT (3U)
#define BRPHY1GV2_BR_GPCS_FIFO_STATUS_RXFIFO_EMPTY_FLAG_MASK (0x4U)
#define BRPHY1GV2_BR_GPCS_FIFO_STATUS_RXFIFO_EMPTY_FLAG_SHIFT (2U)
#define BRPHY1GV2_BR_GPCS_FIFO_STATUS_RXFIFO_OVRUN_FLAG_MASK (0x2U)
#define BRPHY1GV2_BR_GPCS_FIFO_STATUS_RXFIFO_OVRUN_FLAG_SHIFT (1U)
#define BRPHY1GV2_BR_GPCS_FIFO_STATUS_RXFIFO_FULL_FLAG_MASK (0x1U)
#define BRPHY1GV2_BR_GPCS_FIFO_STATUS_RXFIFO_FULL_FLAG_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_RXTRAIN_SEED_CTL2_TYPE;
#define BRPHY1GV2_BR_GPCS_RXTRAIN_SEED_CTL2_32_MASK (0x2U)
#define BRPHY1GV2_BR_GPCS_RXTRAIN_SEED_CTL2_32_SHIFT (1U)
#define BRPHY1GV2_BR_GPCS_RXTRAIN_SEED_CTL2_SET_MASK (0x1U)
#define BRPHY1GV2_BR_GPCS_RXTRAIN_SEED_CTL2_SET_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_RXTRAIN_SEED_CTL1_TYPE;
#define BRPHY1GV2_BR_GPCS_RXTRAIN_SEED_CTL1_31_16_MASK (0xffffU)
#define BRPHY1GV2_BR_GPCS_RXTRAIN_SEED_CTL1_31_16_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_RXTRAIN_SEED_CTL0_TYPE;
#define BRPHY1GV2_BR_GPCS_RXTRAIN_SEED_CTL0_15_0_MASK (0xffffU)
#define BRPHY1GV2_BR_GPCS_RXTRAIN_SEED_CTL0_15_0_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_TXTRAIN_SEED_CTL2_TYPE;
#define BRPHY1GV2_BR_GPCS_TXTRAIN_SEED_CTL2_FEC_RNDERR_BIT_SET_MASK (0x8000U)
#define BRPHY1GV2_BR_GPCS_TXTRAIN_SEED_CTL2_FEC_RNDERR_BIT_SET_SHIFT (15U)
#define BRPHY1GV2_BR_GPCS_TXTRAIN_SEED_CTL2_FEC_RNDERR_SYM_SET_MASK (0x4000U)
#define BRPHY1GV2_BR_GPCS_TXTRAIN_SEED_CTL2_FEC_RNDERR_SYM_SET_SHIFT (14U)
#define BRPHY1GV2_BR_GPCS_TXTRAIN_SEED_CTL2_FEC_RNDERR_BIT_TYP_MASK (0x2000U)
#define BRPHY1GV2_BR_GPCS_TXTRAIN_SEED_CTL2_FEC_RNDERR_BIT_TYP_SHIFT (13U)
#define BRPHY1GV2_BR_GPCS_TXTRAIN_SEED_CTL2_FEC_RNDERR_SYM_TYP_MASK (0x1000U)
#define BRPHY1GV2_BR_GPCS_TXTRAIN_SEED_CTL2_FEC_RNDERR_SYM_TYP_SHIFT (12U)
#define BRPHY1GV2_BR_GPCS_TXTRAIN_SEED_CTL2_TXTRAIN_SEED_32_MASK (0x2U)
#define BRPHY1GV2_BR_GPCS_TXTRAIN_SEED_CTL2_TXTRAIN_SEED_32_SHIFT (1U)
#define BRPHY1GV2_BR_GPCS_TXTRAIN_SEED_CTL2_TXTRAIN_SEED_SET_MASK (0x1U)
#define BRPHY1GV2_BR_GPCS_TXTRAIN_SEED_CTL2_TXTRAIN_SEED_SET_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_TXTRAIN_SEED_CTL1_TYPE;
#define BRPHY1GV2_BR_GPCS_TXTRAIN_SEED_CTL1_31_16_MASK (0xffffU)
#define BRPHY1GV2_BR_GPCS_TXTRAIN_SEED_CTL1_31_16_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_TXTRAIN_SEED_CTL0_TYPE;
#define BRPHY1GV2_BR_GPCS_TXTRAIN_SEED_CTL0_15_0_MASK (0xffffU)
#define BRPHY1GV2_BR_GPCS_TXTRAIN_SEED_CTL0_15_0_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_RXTRAIN_CTL0_TYPE;
#define BRPHY1GV2_BR_GPCS_RXTRAIN_CTL0_BYP_BLOCK_LOCK_MON_MASK (0x8000U)
#define BRPHY1GV2_BR_GPCS_RXTRAIN_CTL0_BYP_BLOCK_LOCK_MON_SHIFT (15U)
#define BRPHY1GV2_BR_GPCS_RXTRAIN_CTL0_BYP_NONIDLE_MON_MASK (0x4000U)
#define BRPHY1GV2_BR_GPCS_RXTRAIN_CTL0_BYP_NONIDLE_MON_SHIFT (14U)
#define BRPHY1GV2_BR_GPCS_RXTRAIN_CTL0_BYP_CRC_MON_MASK (0x2000U)
#define BRPHY1GV2_BR_GPCS_RXTRAIN_CTL0_BYP_CRC_MON_SHIFT (13U)
#define BRPHY1GV2_BR_GPCS_RXTRAIN_CTL0_PAM3_FRAME_DLY_MASK (0x1800U)
#define BRPHY1GV2_BR_GPCS_RXTRAIN_CTL0_PAM3_FRAME_DLY_SHIFT (11U)
#define BRPHY1GV2_BR_GPCS_RXTRAIN_CTL0_RX_PAM3_DLY_MASK (0x700U)
#define BRPHY1GV2_BR_GPCS_RXTRAIN_CTL0_RX_PAM3_DLY_SHIFT (8U)
#define BRPHY1GV2_BR_GPCS_RXTRAIN_CTL0_S2_CHK_T0_MASK (0x80U)
#define BRPHY1GV2_BR_GPCS_RXTRAIN_CTL0_S2_CHK_T0_SHIFT (7U)
#define BRPHY1GV2_BR_GPCS_RXTRAIN_CTL0_S4_CHK2FEC_MASK (0x40U)
#define BRPHY1GV2_BR_GPCS_RXTRAIN_CTL0_S4_CHK2FEC_SHIFT (6U)
#define BRPHY1GV2_BR_GPCS_RXTRAIN_CTL0_CHKCRC_THRESH_MASK (0x30U)
#define BRPHY1GV2_BR_GPCS_RXTRAIN_CTL0_CHKCRC_THRESH_SHIFT (4U)
#define BRPHY1GV2_BR_GPCS_RXTRAIN_CTL0_NONIDLE_THRESH_MASK (0xcU)
#define BRPHY1GV2_BR_GPCS_RXTRAIN_CTL0_NONIDLE_THRESH_SHIFT (2U)
#define BRPHY1GV2_BR_GPCS_RXTRAIN_CTL0_INFO_QUAL_MASK (0x3U)
#define BRPHY1GV2_BR_GPCS_RXTRAIN_CTL0_INFO_QUAL_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_MISC_STATUS0_TYPE;
#define BRPHY1GV2_BR_GPCS_MISC_STATUS0_PAM_ERR_O_IS0_MASK (0x1000U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS0_PAM_ERR_O_IS0_SHIFT (12U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS0_PAM_ERR_O_ISP1_MASK (0x800U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS0_PAM_ERR_O_ISP1_SHIFT (11U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS0_PAM_ERR_O_ISN1_MASK (0x400U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS0_PAM_ERR_O_ISN1_SHIFT (10U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS0_PAM_ERR_E_IS0_MASK (0x200U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS0_PAM_ERR_E_IS0_SHIFT (9U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS0_PAM_ERR_E_ISP1_MASK (0x100U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS0_PAM_ERR_E_ISP1_SHIFT (8U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS0_PAM_ERR_E_ISN1_MASK (0x80U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS0_PAM_ERR_E_ISN1_SHIFT (7U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS0_PTR_UNDEF_MASK (0x40U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS0_PTR_UNDEF_SHIFT (6U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS0_PTR_OUTORDER_MASK (0x20U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS0_PTR_OUTORDER_SHIFT (5U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS0_PTR_MISS_N_MASK (0x10U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS0_PTR_MISS_N_SHIFT (4U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS0_BLK_FECERR_MASK (0x8U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS0_BLK_FECERR_SHIFT (3U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS0_UDEF_CTRLCODE_MASK (0x4U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS0_UDEF_CTRLCODE_SHIFT (2U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS0_RCV_LPIDLE_MASK (0x2U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS0_RCV_LPIDLE_SHIFT (1U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS0_RX_EVENODDADJ_MASK (0x1U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS0_RX_EVENODDADJ_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_MISC_STATUS1_TYPE;
#define BRPHY1GV2_BR_GPCS_MISC_STATUS1_LINK_STATUS_MASK (0x8000U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS1_LINK_STATUS_SHIFT (15U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS1_LOC_RCVR_STATUS_MASK (0x4000U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS1_LOC_RCVR_STATUS_SHIFT (14U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS1_LOC_PHY_READY_MASK (0x2000U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS1_LOC_PHY_READY_SHIFT (13U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS1_REM_RCVR_STATUS_MASK (0x1000U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS1_REM_RCVR_STATUS_SHIFT (12U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS1_REM_PHY_READY_MASK (0x800U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS1_REM_PHY_READY_SHIFT (11U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS1_PCS_RX_FAULT_MASK (0x400U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS1_PCS_RX_FAULT_SHIFT (10U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS1_REM_TIMING_LOCK_OK_MASK (0x200U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS1_REM_TIMING_LOCK_OK_SHIFT (9U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS1_TIMING_LOCK_OK_MASK (0x100U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS1_TIMING_LOCK_OK_SHIFT (8U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS1_EN_SLAVE_TX_MASK (0x80U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS1_EN_SLAVE_TX_SHIFT (7U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS1_BLOCK_LOCK_DROP_MASK (0x40U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS1_BLOCK_LOCK_DROP_SHIFT (6U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS1_NON_IDLE_OVFL_MASK (0x20U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS1_NON_IDLE_OVFL_SHIFT (5U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS1_BAD_CRC_OVFL_MASK (0x10U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS1_BAD_CRC_OVFL_SHIFT (4U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS1_PAM_NEG_ONE_ERR_MASK (0x8U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS1_PAM_NEG_ONE_ERR_SHIFT (3U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS1_PAM_POS_ONE_ERR_MASK (0x4U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS1_PAM_POS_ONE_ERR_SHIFT (2U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS1_PAM_ZERO_ERR_MASK (0x2U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS1_PAM_ZERO_ERR_SHIFT (1U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS1_SCR_STATUS_MASK (0x1U)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS1_SCR_STATUS_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_MISC_STATUS2_TYPE;
#define BRPHY1GV2_BR_GPCS_MISC_STATUS2_BAD_CRC16_CNT_MASK (0xffffU)
#define BRPHY1GV2_BR_GPCS_MISC_STATUS2_BAD_CRC16_CNT_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_PCS_MISC_CTL0_TYPE;
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL0_SOFT_RESET_PCS_MASK (0x8000U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL0_SOFT_RESET_PCS_SHIFT (15U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL0_SOFT_RESET_TXPCS_MASK (0x4000U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL0_SOFT_RESET_TXPCS_SHIFT (14U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL0_SOFT_RESET_RXPCS_MASK (0x2000U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL0_SOFT_RESET_RXPCS_SHIFT (13U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL0_BYP_FEC_SYNDR_MASK (0x1000U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL0_BYP_FEC_SYNDR_SHIFT (12U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL0_SOFT_RSTN_FECDEC_MASK (0x800U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL0_SOFT_RSTN_FECDEC_SHIFT (11U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL0_SOFT_RSTN_FECENC_MASK (0x400U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL0_SOFT_RSTN_FECENC_SHIFT (10U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL0_BYP_FEC_DEC_SYNDR_MASK (0x200U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL0_BYP_FEC_DEC_SYNDR_SHIFT (9U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL0_BYP_FEC_ENC_SYNDR_MASK (0x100U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL0_BYP_FEC_ENC_SYNDR_SHIFT (8U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL0_PCS_RX_FAULT_DIS_MASK (0x80U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL0_PCS_RX_FAULT_DIS_SHIFT (7U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL0_BYP_PAM_CHK_MASK (0x40U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL0_BYP_PAM_CHK_SHIFT (6U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL0_COUNTDOWN_CRC_EN_MASK (0x20U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL0_COUNTDOWN_CRC_EN_SHIFT (5U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL0_DEC81_RPT_EN_MASK (0x10U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL0_DEC81_RPT_EN_SHIFT (4U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL0_DRV_PMA_DIS_MASK (0x8U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL0_DRV_PMA_DIS_SHIFT (3U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL0_FEC_DEC_BYPASS_EN_MASK (0x4U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL0_FEC_DEC_BYPASS_EN_SHIFT (2U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL0_FEC_ENC_BYPASS_EN_MASK (0x2U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL0_FEC_ENC_BYPASS_EN_SHIFT (1U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL0_PATCH_RXSTATE_EN_MASK (0x1U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL0_PATCH_RXSTATE_EN_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_TXFIFO_RAMCTL0_TYPE;
#define BRPHY1GV2_BR_GPCS_TXFIFO_RAMCTL0_TX_LVM_MASK (0x4000U)
#define BRPHY1GV2_BR_GPCS_TXFIFO_RAMCTL0_TX_LVM_SHIFT (14U)
#define BRPHY1GV2_BR_GPCS_TXFIFO_RAMCTL0_TX_RDS_MASK (0x2000U)
#define BRPHY1GV2_BR_GPCS_TXFIFO_RAMCTL0_TX_RDS_SHIFT (13U)
#define BRPHY1GV2_BR_GPCS_TXFIFO_RAMCTL0_TX_RAM_BYP_MASK (0x1000U)
#define BRPHY1GV2_BR_GPCS_TXFIFO_RAMCTL0_TX_RAM_BYP_SHIFT (12U)
#define BRPHY1GV2_BR_GPCS_TXFIFO_RAMCTL0_TX_TM_MASK (0xfffU)
#define BRPHY1GV2_BR_GPCS_TXFIFO_RAMCTL0_TX_TM_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_RXFIFO_RAMCTL0_TYPE;
#define BRPHY1GV2_BR_GPCS_RXFIFO_RAMCTL0_RX_LVM_MASK (0x4000U)
#define BRPHY1GV2_BR_GPCS_RXFIFO_RAMCTL0_RX_LVM_SHIFT (14U)
#define BRPHY1GV2_BR_GPCS_RXFIFO_RAMCTL0_RX_RDS_MASK (0x2000U)
#define BRPHY1GV2_BR_GPCS_RXFIFO_RAMCTL0_RX_RDS_SHIFT (13U)
#define BRPHY1GV2_BR_GPCS_RXFIFO_RAMCTL0_RX_RAM_BYP_MASK (0x1000U)
#define BRPHY1GV2_BR_GPCS_RXFIFO_RAMCTL0_RX_RAM_BYP_SHIFT (12U)
#define BRPHY1GV2_BR_GPCS_RXFIFO_RAMCTL0_RX_TM_MASK (0xfffU)
#define BRPHY1GV2_BR_GPCS_RXFIFO_RAMCTL0_RX_TM_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_RAM_STATUS_TYPE;
#define BRPHY1GV2_BR_GPCS_RAM_STATUS_TX_SEC_FLAG_MASK (0x8U)
#define BRPHY1GV2_BR_GPCS_RAM_STATUS_TX_SEC_FLAG_SHIFT (3U)
#define BRPHY1GV2_BR_GPCS_RAM_STATUS_TX_DED_FLAG_MASK (0x4U)
#define BRPHY1GV2_BR_GPCS_RAM_STATUS_TX_DED_FLAG_SHIFT (2U)
#define BRPHY1GV2_BR_GPCS_RAM_STATUS_RX_SEC_FLAG_MASK (0x2U)
#define BRPHY1GV2_BR_GPCS_RAM_STATUS_RX_SEC_FLAG_SHIFT (1U)
#define BRPHY1GV2_BR_GPCS_RAM_STATUS_RX_DED_FLAG_MASK (0x1U)
#define BRPHY1GV2_BR_GPCS_RAM_STATUS_RX_DED_FLAG_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_PCS_MISC_CTL1_TYPE;
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL1_SPARE_15_MASK (0x8000U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL1_SPARE_15_SHIFT (15U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL1_EMI_PROTECT_EN_MASK (0x4000U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL1_EMI_PROTECT_EN_SHIFT (14U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL1_BLKLOCK_LIMIT_MASK (0x3000U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL1_BLKLOCK_LIMIT_SHIFT (12U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL1_BYP_SD_TRANSIT_MON_MASK (0x800U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL1_BYP_SD_TRANSIT_MON_SHIFT (11U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL1_PFC_LIMIT_MASK (0x600U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL1_PFC_LIMIT_SHIFT (9U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL1_ALIGN_CRC_EN_MASK (0x100U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL1_ALIGN_CRC_EN_SHIFT (8U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL1_SRCH_LIMIT_DIS_MASK (0x80U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL1_SRCH_LIMIT_DIS_SHIFT (7U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL1_ALIGN_CRC_LIMIT_MASK (0x70U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL1_ALIGN_CRC_LIMIT_SHIFT (4U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL1_EMI_HOLD_MASK (0x8U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL1_EMI_HOLD_SHIFT (3U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL1_BRCM_TM_1011_MASK (0x4U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL1_BRCM_TM_1011_SHIFT (2U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL1_BRCM_TM_1001_MASK (0x2U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL1_BRCM_TM_1001_SHIFT (1U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL1_WAIT_ALIGNDROP_RPT_MASK (0x1U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL1_WAIT_ALIGNDROP_RPT_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_PCS_MISC_CTL2_TYPE;
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL2_RX_OV_CTRL_0_MASK (0xffffU)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL2_RX_OV_CTRL_0_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_PCS_MISC_CTL3_TYPE;
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL3_BLOCK_LOCK_VAL_MASK (0x8000U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL3_BLOCK_LOCK_VAL_SHIFT (15U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL3_HI_RFER_VAL_MASK (0x4000U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL3_HI_RFER_VAL_SHIFT (14U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL3_ALIGNMENTSTATE_VAL_MASK (0x3c00U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL3_ALIGNMENTSTATE_VAL_SHIFT (10U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL3_POLARITYA_VAL_MASK (0x200U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL3_POLARITYA_VAL_SHIFT (9U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL3_EVENODDADJ_VAL_MASK (0x100U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL3_EVENODDADJ_VAL_SHIFT (8U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL3_ALIGNMENTCOMPLETE_VAL_MASK (0x80U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL3_ALIGNMENTCOMPLETE_VAL_SHIFT (7U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL3_ERRORCOUNT_VAL_MASK (0x70U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL3_ERRORCOUNT_VAL_SHIFT (4U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL3_SCRAMBLERMODE_VAL_MASK (0xcU)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL3_SCRAMBLERMODE_VAL_SHIFT (2U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL3_ENABLE_PF_BIT_CNT_VAL_MASK (0x2U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL3_ENABLE_PF_BIT_CNT_VAL_SHIFT (1U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL3_SECOND_LOAD_VAL_MASK (0x1U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL3_SECOND_LOAD_VAL_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_PCS_MISC_CTL4_TYPE;
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL4_BIT_INV_CNT_VAL_MASK (0xf000U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL4_BIT_INV_CNT_VAL_SHIFT (12U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL4_TIMERA_VAL_MASK (0xfffU)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL4_TIMERA_VAL_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_PCS_MISC_CTL5_TYPE;
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL5_RCVD_PATTERN_VAL_MASK (0xffffU)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL5_RCVD_PATTERN_VAL_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_PCS_MISC_CTL6_TYPE;
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL6_SPARE_15_10_MASK (0xfc00U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL6_SPARE_15_10_SHIFT (10U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL6_PCS_STATUS_VAL_MASK (0x200U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL6_PCS_STATUS_VAL_SHIFT (9U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL6_INFO_SRCH_VAL_MASK (0x100U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL6_INFO_SRCH_VAL_SHIFT (8U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL6_RCVD_PATTERN_VAL_MASK (0xffU)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL6_RCVD_PATTERN_VAL_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_PCS_MISC_CTL7_TYPE;
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL7_RX_OV_CTRL_1_MASK (0xffffU)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL7_RX_OV_CTRL_1_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_PCS_MISC_CTL8_TYPE;
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL8_LP_OAMEN_VAL_MASK (0x4000U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL8_LP_OAMEN_VAL_SHIFT (14U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL8_ALIGN_OK_VAL_MASK (0x2000U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL8_ALIGN_OK_VAL_SHIFT (13U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL8_ENABLE_SCR15_VAL_MASK (0x1000U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL8_ENABLE_SCR15_VAL_SHIFT (12U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL8_EN_FDX_DETECT_VAL_MASK (0x800U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL8_EN_FDX_DETECT_VAL_SHIFT (11U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL8_REM_RCVR_STATUS_VAL_MASK (0x400U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL8_REM_RCVR_STATUS_VAL_SHIFT (10U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL8_PCS_SCR_START_VAL_MASK (0x200U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL8_PCS_SCR_START_VAL_SHIFT (9U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL8_DEC_OUT_ERR_VAL_MASK (0x100U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL8_DEC_OUT_ERR_VAL_SHIFT (8U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL8_ID_IDLE_GOOD_VAL_MASK (0x80U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL8_ID_IDLE_GOOD_VAL_SHIFT (7U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL8_REM_COUNTDOWN_DONE_VAL_MASK (0x40U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL8_REM_COUNTDOWN_DONE_VAL_SHIFT (6U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL8_RX_AGGREGATE_VAL_MASK (0x20U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL8_RX_AGGREGATE_VAL_SHIFT (5U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL8_RX_STATE_VAL_MASK (0x10U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL8_RX_STATE_VAL_SHIFT (4U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL8_FALSE_PTR_1_VAL_MASK (0x8U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL8_FALSE_PTR_1_VAL_SHIFT (3U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL8_FALSE_PTR_2_VAL_MASK (0x4U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL8_FALSE_PTR_2_VAL_SHIFT (2U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL8_FALSE_PTR_3_VAL_MASK (0x2U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL8_FALSE_PTR_3_VAL_SHIFT (1U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL8_REM_PHY_READY_VAL_MASK (0x1U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL8_REM_PHY_READY_VAL_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_PCS_MISC_CTL9_TYPE;
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL9_SPARE_15_3_MASK (0xfff8U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL9_SPARE_15_3_SHIFT (3U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL9_INVALID_BLOCK_SEL_MASK (0x4U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL9_INVALID_BLOCK_SEL_SHIFT (2U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL9_TXLPI_CONV_EN_MASK (0x2U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL9_TXLPI_CONV_EN_SHIFT (1U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL9_RXLPI_CONV_EN_MASK (0x1U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL9_RXLPI_CONV_EN_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_PCS_MISC_CTL10_TYPE;
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL10_SPARE_15_MASK (0x8000U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL10_SPARE_15_SHIFT (15U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL10_PTR_NFLAG_OV_MASK (0x4000U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL10_PTR_NFLAG_OV_SHIFT (14U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL10_PTR_NFLAG_VAL_MASK (0x2000U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL10_PTR_NFLAG_VAL_SHIFT (13U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL10_BYTE_LOC_VAL_MASK (0x1e00U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL10_BYTE_LOC_VAL_SHIFT (9U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL10_PTR_CNT_OV_MASK (0x100U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL10_PTR_CNT_OV_SHIFT (8U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL10_UNDEF_PTR_VAL_MASK (0xf0U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL10_UNDEF_PTR_VAL_SHIFT (4U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL10_CTRLCODE_OV_MASK (0x8U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL10_CTRLCODE_OV_SHIFT (3U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL10_UNDEF_CTRL_VAL_MASK (0x7U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL10_UNDEF_CTRL_VAL_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_PCS_MISC_CTL11_TYPE;
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL11_FEC_ERR_INJ_EN_MASK (0x4000U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL11_FEC_ERR_INJ_EN_SHIFT (14U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL11_FEC_ERR_FRAME_MASK (0x3e00U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL11_FEC_ERR_FRAME_SHIFT (9U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL11_FEC_ERR_PTR_MASK (0x1ffU)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL11_FEC_ERR_PTR_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_PCS_MISC_CTL12_TYPE;
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL12_TX_PAM2_POL_INV_MASK (0x8000U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL12_TX_PAM2_POL_INV_SHIFT (15U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL12_RX_PAM2_POL_INV_MASK (0x4000U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL12_RX_PAM2_POL_INV_SHIFT (14U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL12_TX_PCS_SEED_SWAP_MASK (0x2000U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL12_TX_PCS_SEED_SWAP_SHIFT (13U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL12_RX_PCS_SEED_SWAP_MASK (0x1000U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL12_RX_PCS_SEED_SWAP_SHIFT (12U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL12_TX_PAM3_HALF_DLY_MASK (0x800U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL12_TX_PAM3_HALF_DLY_SHIFT (11U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL12_RX_PAM3_HALF_DLY_MASK (0x400U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL12_RX_PAM3_HALF_DLY_SHIFT (10U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL12_FEC_ERR_BIT_TYP_MASK (0x200U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL12_FEC_ERR_BIT_TYP_SHIFT (9U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL12_FEC_ERR_BITMAP_MASK (0x1ffU)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL12_FEC_ERR_BITMAP_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_PCS_MISC_CTL13_TYPE;
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL13_TX_STATE_TEST1_MASK (0x8000U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL13_TX_STATE_TEST1_SHIFT (15U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL13_TX_STATE_TEST2_MASK (0x4000U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL13_TX_STATE_TEST2_SHIFT (14U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL13_PCS_SCR_OPSEL_MASK (0x1000U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL13_PCS_SCR_OPSEL_SHIFT (12U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL13_TX_PAM3_POL_INV_MASK (0x800U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL13_TX_PAM3_POL_INV_SHIFT (11U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL13_RX_PAM3_POL_INV_MASK (0x400U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL13_RX_PAM3_POL_INV_SHIFT (10U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL13_FEC_ERR_SYM_TYP_MASK (0x200U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL13_FEC_ERR_SYM_TYP_SHIFT (9U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL13_FEC_ERR_SYMNUM_MASK (0x1ffU)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL13_FEC_ERR_SYMNUM_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_PCS_MISC_CTL14_TYPE;
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL14_SPARE_15_2_MASK (0xfffcU)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL14_SPARE_15_2_SHIFT (2U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL14_SPARE_1_MASK (0x2U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL14_SPARE_1_SHIFT (1U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL14_FAKE_TXER_OV_MASK (0x1U)
#define BRPHY1GV2_BR_GPCS_PCS_MISC_CTL14_FAKE_TXER_OV_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_RXPROBE0_TYPE;
#define BRPHY1GV2_BR_GPCS_RXPROBE0_RX_DEBUG_0_MASK (0xffffU)
#define BRPHY1GV2_BR_GPCS_RXPROBE0_RX_DEBUG_0_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_RXPROBE1_TYPE;
#define BRPHY1GV2_BR_GPCS_RXPROBE1_RX_DEBUG_1_MASK (0xffffU)
#define BRPHY1GV2_BR_GPCS_RXPROBE1_RX_DEBUG_1_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_RXPROBE2_TYPE;
#define BRPHY1GV2_BR_GPCS_RXPROBE2_RX_DEBUG_2_MASK (0xffffU)
#define BRPHY1GV2_BR_GPCS_RXPROBE2_RX_DEBUG_2_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_RXPROBE3_TYPE;
#define BRPHY1GV2_BR_GPCS_RXPROBE3_RX_DEBUG_3_MASK (0xffffU)
#define BRPHY1GV2_BR_GPCS_RXPROBE3_RX_DEBUG_3_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_RXPROBE4_TYPE;
#define BRPHY1GV2_BR_GPCS_RXPROBE4_RX_DEBUG_4_MASK (0xffffU)
#define BRPHY1GV2_BR_GPCS_RXPROBE4_RX_DEBUG_4_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_RXPROBE5_TYPE;
#define BRPHY1GV2_BR_GPCS_RXPROBE5_RX_DEBUG_5_MASK (0xffffU)
#define BRPHY1GV2_BR_GPCS_RXPROBE5_RX_DEBUG_5_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_RXPROBE6_TYPE;
#define BRPHY1GV2_BR_GPCS_RXPROBE6_RX_DEBUG_6_MASK (0xffffU)
#define BRPHY1GV2_BR_GPCS_RXPROBE6_RX_DEBUG_6_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_TXPROBE0_TYPE;
#define BRPHY1GV2_BR_GPCS_TXPROBE0_TX_DEBUG_0_MASK (0xffffU)
#define BRPHY1GV2_BR_GPCS_TXPROBE0_TX_DEBUG_0_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_TXPROBE1_TYPE;
#define BRPHY1GV2_BR_GPCS_TXPROBE1_TX_DEBUG_1_MASK (0xffffU)
#define BRPHY1GV2_BR_GPCS_TXPROBE1_TX_DEBUG_1_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_TXPROBE2_TYPE;
#define BRPHY1GV2_BR_GPCS_TXPROBE2_TX_DEBUG_2_MASK (0xffffU)
#define BRPHY1GV2_BR_GPCS_TXPROBE2_TX_DEBUG_2_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_TXPROBE3_TYPE;
#define BRPHY1GV2_BR_GPCS_TXPROBE3_TX_DEBUG_3_MASK (0xffffU)
#define BRPHY1GV2_BR_GPCS_TXPROBE3_TX_DEBUG_3_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_TXPROBE4_TYPE;
#define BRPHY1GV2_BR_GPCS_TXPROBE4_TX_DEBUG_4_MASK (0xffffU)
#define BRPHY1GV2_BR_GPCS_TXPROBE4_TX_DEBUG_4_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_TXPROBE5_TYPE;
#define BRPHY1GV2_BR_GPCS_TXPROBE5_TX_DEBUG_5_MASK (0xffffU)
#define BRPHY1GV2_BR_GPCS_TXPROBE5_TX_DEBUG_5_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_RXPROBE7_TYPE;
#define BRPHY1GV2_BR_GPCS_RXPROBE7_RX_DEBUG_7_MASK (0xffffU)
#define BRPHY1GV2_BR_GPCS_RXPROBE7_RX_DEBUG_7_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_RFER_MON_LIMIT_TYPE;
#define BRPHY1GV2_BR_GPCS_RFER_MON_LIMIT_RFER_LIMIT_OV_MASK (0x8000U)
#define BRPHY1GV2_BR_GPCS_RFER_MON_LIMIT_RFER_LIMIT_OV_SHIFT (15U)
#define BRPHY1GV2_BR_GPCS_RFER_MON_LIMIT_RFER_CNT_LIMIT_MASK (0x7f00U)
#define BRPHY1GV2_BR_GPCS_RFER_MON_LIMIT_RFER_CNT_LIMIT_SHIFT (8U)
#define BRPHY1GV2_BR_GPCS_RFER_MON_LIMIT_RFRX_CNT_LIMIT_MASK (0x7fU)
#define BRPHY1GV2_BR_GPCS_RFER_MON_LIMIT_RFRX_CNT_LIMIT_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_RFER_CNT_RAW_TYPE;
#define BRPHY1GV2_BR_GPCS_RFER_CNT_RAW_RFER_CNT_RAW_MASK (0x7f00U)
#define BRPHY1GV2_BR_GPCS_RFER_CNT_RAW_RFER_CNT_RAW_SHIFT (8U)
#define BRPHY1GV2_BR_GPCS_RFER_CNT_RAW_RFRX_CNT_RAW_MASK (0x7fU)
#define BRPHY1GV2_BR_GPCS_RFER_CNT_RAW_RFRX_CNT_RAW_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_RFER_MON_TEST_TYPE;
#define BRPHY1GV2_BR_GPCS_RFER_MON_TEST_REG_RESET_MON_MASK (0x8000U)
#define BRPHY1GV2_BR_GPCS_RFER_MON_TEST_REG_RESET_MON_SHIFT (15U)
#define BRPHY1GV2_BR_GPCS_RFER_MON_TEST_RFER_STATE_M4_MASK (0x7000U)
#define BRPHY1GV2_BR_GPCS_RFER_MON_TEST_RFER_STATE_M4_SHIFT (12U)
#define BRPHY1GV2_BR_GPCS_RFER_MON_TEST_RFER_STATE_M3_MASK (0xe00U)
#define BRPHY1GV2_BR_GPCS_RFER_MON_TEST_RFER_STATE_M3_SHIFT (9U)
#define BRPHY1GV2_BR_GPCS_RFER_MON_TEST_RFER_STATE_M2_MASK (0x1c0U)
#define BRPHY1GV2_BR_GPCS_RFER_MON_TEST_RFER_STATE_M2_SHIFT (6U)
#define BRPHY1GV2_BR_GPCS_RFER_MON_TEST_RFER_STATE_M1_MASK (0x38U)
#define BRPHY1GV2_BR_GPCS_RFER_MON_TEST_RFER_STATE_M1_SHIFT (3U)
#define BRPHY1GV2_BR_GPCS_RFER_MON_TEST_RFER_STATE_MASK (0x7U)
#define BRPHY1GV2_BR_GPCS_RFER_MON_TEST_RFER_STATE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_T351S_TYPE;
#define BRPHY1GV2_BR_GPCS_T351S_NORMAL_INTER_FRAME_MASK (0x200U)
#define BRPHY1GV2_BR_GPCS_T351S_NORMAL_INTER_FRAME_SHIFT (9U)
#define BRPHY1GV2_BR_GPCS_T351S_RESERVED_0_MASK (0x100U)
#define BRPHY1GV2_BR_GPCS_T351S_RESERVED_0_SHIFT (8U)
#define BRPHY1GV2_BR_GPCS_T351S_ASSERT_LPI_MASK (0x80U)
#define BRPHY1GV2_BR_GPCS_T351S_ASSERT_LPI_SHIFT (7U)
#define BRPHY1GV2_BR_GPCS_T351S_RESERVED_1_MASK (0x40U)
#define BRPHY1GV2_BR_GPCS_T351S_RESERVED_1_SHIFT (6U)
#define BRPHY1GV2_BR_GPCS_T351S_CARRIER_EXTEND_MASK (0x20U)
#define BRPHY1GV2_BR_GPCS_T351S_CARRIER_EXTEND_SHIFT (5U)
#define BRPHY1GV2_BR_GPCS_T351S_RESERVED_2_MASK (0x10U)
#define BRPHY1GV2_BR_GPCS_T351S_RESERVED_2_SHIFT (4U)
#define BRPHY1GV2_BR_GPCS_T351S_CARRIER_EXTEND_ERROR_MASK (0x8U)
#define BRPHY1GV2_BR_GPCS_T351S_CARRIER_EXTEND_ERROR_SHIFT (3U)
#define BRPHY1GV2_BR_GPCS_T351S_RESERVED_3_MASK (0x4U)
#define BRPHY1GV2_BR_GPCS_T351S_RESERVED_3_SHIFT (2U)
#define BRPHY1GV2_BR_GPCS_T351S_NORMAL_DATA_TRANSMISSION_MASK (0x2U)
#define BRPHY1GV2_BR_GPCS_T351S_NORMAL_DATA_TRANSMISSION_SHIFT (1U)
#define BRPHY1GV2_BR_GPCS_T351S_TRANSMIT_ERROR_PROPAGATION_MASK (0x1U)
#define BRPHY1GV2_BR_GPCS_T351S_TRANSMIT_ERROR_PROPAGATION_SHIFT (0U)




typedef uint16_t BRPHY1GV2_BR_GPCS_SPARE_END_ADDR_TYPE;
#define BRPHY1GV2_BR_GPCS_SPARE_END_ADDR_MASK (0xffffU)
#define BRPHY1GV2_BR_GPCS_SPARE_END_ADDR_SHIFT (0U)




typedef volatile struct sBRPHY1GV2_BR_GPCS_RDBType {
    BRPHY1GV2_BR_GPCS_GMII_FIFO_CTL0_TYPE gmii_fifo_ctl0; /* OFFSET: 0x0 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd0[2]; /* OFFSET: 0x2 */
    BRPHY1GV2_BR_GPCS_GMII_FIFO_CTL1_TYPE gmii_fifo_ctl1; /* OFFSET: 0x4 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd1[2]; /* OFFSET: 0x6 */
    BRPHY1GV2_BR_GPCS_DATA_SW_PFC_OFFSET0_TYPE data_sw_pfc_offset0; /* OFFSET: 0x8 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd2[2]; /* OFFSET: 0xa */
    BRPHY1GV2_BR_GPCS_DSPO1_TYPE data_sw_pfc_offset1; /* OFFSET: 0xc */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0xe */
    BRPHY1GV2_BR_GPCS_SCRA_CTL_TYPE scrambler_ctl; /* OFFSET: 0x10 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd4[2]; /* OFFSET: 0x12 */
    BRPHY1GV2_BR_GPCS_TXPC_SEED_CTL_TYPE txpcs_seed_ctl; /* OFFSET: 0x14 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd5[2]; /* OFFSET: 0x16 */
    BRPHY1GV2_BR_GPCS_PAM3_CTL_TYPE pam3_ctl; /* OFFSET: 0x18 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd6[2]; /* OFFSET: 0x1a */
    BRPHY1GV2_BR_GPCS_OAM_CTL_TYPE oam_ctl; /* OFFSET: 0x1c */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd7[2]; /* OFFSET: 0x1e */
    BRPHY1GV2_BR_GPCS_OAM_STATUS_TYPE oam_status; /* OFFSET: 0x20 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd8[2]; /* OFFSET: 0x22 */
    BRPHY1GV2_BR_GPCS_RXPC_SEED_CTL_TYPE rxpcs_seed_ctl; /* OFFSET: 0x24 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd9[2]; /* OFFSET: 0x26 */
    BRPHY1GV2_BR_GPCS_FIFO_STATUS_TYPE fifo_status; /* OFFSET: 0x28 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd10[2]; /* OFFSET: 0x2a */
    BRPHY1GV2_BR_GPCS_RXTRAIN_SEED_CTL2_TYPE rxtrain_seed_ctl2; /* OFFSET: 0x2c */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd11[2]; /* OFFSET: 0x2e */
    BRPHY1GV2_BR_GPCS_RXTRAIN_SEED_CTL1_TYPE rxtrain_seed_ctl1; /* OFFSET: 0x30 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd12[2]; /* OFFSET: 0x32 */
    BRPHY1GV2_BR_GPCS_RXTRAIN_SEED_CTL0_TYPE rxtrain_seed_ctl0; /* OFFSET: 0x34 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd13[2]; /* OFFSET: 0x36 */
    BRPHY1GV2_BR_GPCS_TXTRAIN_SEED_CTL2_TYPE txtrain_seed_ctl2; /* OFFSET: 0x38 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd14[2]; /* OFFSET: 0x3a */
    BRPHY1GV2_BR_GPCS_TXTRAIN_SEED_CTL1_TYPE txtrain_seed_ctl1; /* OFFSET: 0x3c */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd15[2]; /* OFFSET: 0x3e */
    BRPHY1GV2_BR_GPCS_TXTRAIN_SEED_CTL0_TYPE txtrain_seed_ctl0; /* OFFSET: 0x40 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd16[2]; /* OFFSET: 0x42 */
    BRPHY1GV2_BR_GPCS_RXTRAIN_CTL0_TYPE rxtrain_ctl0; /* OFFSET: 0x44 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd17[2]; /* OFFSET: 0x46 */
    BRPHY1GV2_BR_GPCS_MISC_STATUS0_TYPE misc_status0; /* OFFSET: 0x48 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd18[2]; /* OFFSET: 0x4a */
    BRPHY1GV2_BR_GPCS_MISC_STATUS1_TYPE misc_status1; /* OFFSET: 0x4c */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd19[2]; /* OFFSET: 0x4e */
    BRPHY1GV2_BR_GPCS_MISC_STATUS2_TYPE misc_status2; /* OFFSET: 0x50 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd20[46]; /* OFFSET: 0x52 */
    BRPHY1GV2_BR_GPCS_PCS_MISC_CTL0_TYPE pcs_misc_ctl0; /* OFFSET: 0x80 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd21[2]; /* OFFSET: 0x82 */
    BRPHY1GV2_BR_GPCS_TXFIFO_RAMCTL0_TYPE txfifo_ramctl0; /* OFFSET: 0x84 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd22[2]; /* OFFSET: 0x86 */
    BRPHY1GV2_BR_GPCS_RXFIFO_RAMCTL0_TYPE rxfifo_ramctl0; /* OFFSET: 0x88 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd23[2]; /* OFFSET: 0x8a */
    BRPHY1GV2_BR_GPCS_RAM_STATUS_TYPE ram_status; /* OFFSET: 0x8c */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd24[2]; /* OFFSET: 0x8e */
    BRPHY1GV2_BR_GPCS_PCS_MISC_CTL1_TYPE pcs_misc_ctl1; /* OFFSET: 0x90 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd25[2]; /* OFFSET: 0x92 */
    BRPHY1GV2_BR_GPCS_PCS_MISC_CTL2_TYPE pcs_misc_ctl2; /* OFFSET: 0x94 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd26[2]; /* OFFSET: 0x96 */
    BRPHY1GV2_BR_GPCS_PCS_MISC_CTL3_TYPE pcs_misc_ctl3; /* OFFSET: 0x98 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd27[2]; /* OFFSET: 0x9a */
    BRPHY1GV2_BR_GPCS_PCS_MISC_CTL4_TYPE pcs_misc_ctl4; /* OFFSET: 0x9c */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd28[2]; /* OFFSET: 0x9e */
    BRPHY1GV2_BR_GPCS_PCS_MISC_CTL5_TYPE pcs_misc_ctl5; /* OFFSET: 0xa0 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd29[2]; /* OFFSET: 0xa2 */
    BRPHY1GV2_BR_GPCS_PCS_MISC_CTL6_TYPE pcs_misc_ctl6; /* OFFSET: 0xa4 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd30[2]; /* OFFSET: 0xa6 */
    BRPHY1GV2_BR_GPCS_PCS_MISC_CTL7_TYPE pcs_misc_ctl7; /* OFFSET: 0xa8 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd31[2]; /* OFFSET: 0xaa */
    BRPHY1GV2_BR_GPCS_PCS_MISC_CTL8_TYPE pcs_misc_ctl8; /* OFFSET: 0xac */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd32[2]; /* OFFSET: 0xae */
    BRPHY1GV2_BR_GPCS_PCS_MISC_CTL9_TYPE pcs_misc_ctl9; /* OFFSET: 0xb0 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd33[2]; /* OFFSET: 0xb2 */
    BRPHY1GV2_BR_GPCS_PCS_MISC_CTL10_TYPE pcs_misc_ctl10; /* OFFSET: 0xb4 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd34[2]; /* OFFSET: 0xb6 */
    BRPHY1GV2_BR_GPCS_PCS_MISC_CTL11_TYPE pcs_misc_ctl11; /* OFFSET: 0xb8 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd35[2]; /* OFFSET: 0xba */
    BRPHY1GV2_BR_GPCS_PCS_MISC_CTL12_TYPE pcs_misc_ctl12; /* OFFSET: 0xbc */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd36[2]; /* OFFSET: 0xbe */
    BRPHY1GV2_BR_GPCS_PCS_MISC_CTL13_TYPE pcs_misc_ctl13; /* OFFSET: 0xc0 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd37[2]; /* OFFSET: 0xc2 */
    BRPHY1GV2_BR_GPCS_PCS_MISC_CTL14_TYPE pcs_misc_ctl14; /* OFFSET: 0xc4 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd38[122]; /* OFFSET: 0xc6 */
    BRPHY1GV2_BR_GPCS_RXPROBE0_TYPE rxprobe0; /* OFFSET: 0x140 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd39[2]; /* OFFSET: 0x142 */
    BRPHY1GV2_BR_GPCS_RXPROBE1_TYPE rxprobe1; /* OFFSET: 0x144 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd40[2]; /* OFFSET: 0x146 */
    BRPHY1GV2_BR_GPCS_RXPROBE2_TYPE rxprobe2; /* OFFSET: 0x148 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd41[2]; /* OFFSET: 0x14a */
    BRPHY1GV2_BR_GPCS_RXPROBE3_TYPE rxprobe3; /* OFFSET: 0x14c */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd42[2]; /* OFFSET: 0x14e */
    BRPHY1GV2_BR_GPCS_RXPROBE4_TYPE rxprobe4; /* OFFSET: 0x150 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd43[2]; /* OFFSET: 0x152 */
    BRPHY1GV2_BR_GPCS_RXPROBE5_TYPE rxprobe5; /* OFFSET: 0x154 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd44[2]; /* OFFSET: 0x156 */
    BRPHY1GV2_BR_GPCS_RXPROBE6_TYPE rxprobe6; /* OFFSET: 0x158 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd45[38]; /* OFFSET: 0x15a */
    BRPHY1GV2_BR_GPCS_TXPROBE0_TYPE txprobe0; /* OFFSET: 0x180 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd46[2]; /* OFFSET: 0x182 */
    BRPHY1GV2_BR_GPCS_TXPROBE1_TYPE txprobe1; /* OFFSET: 0x184 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd47[2]; /* OFFSET: 0x186 */
    BRPHY1GV2_BR_GPCS_TXPROBE2_TYPE txprobe2; /* OFFSET: 0x188 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd48[2]; /* OFFSET: 0x18a */
    BRPHY1GV2_BR_GPCS_TXPROBE3_TYPE txprobe3; /* OFFSET: 0x18c */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd49[2]; /* OFFSET: 0x18e */
    BRPHY1GV2_BR_GPCS_TXPROBE4_TYPE txprobe4; /* OFFSET: 0x190 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd50[2]; /* OFFSET: 0x192 */
    BRPHY1GV2_BR_GPCS_TXPROBE5_TYPE txprobe5; /* OFFSET: 0x194 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd51[2]; /* OFFSET: 0x196 */
    BRPHY1GV2_BR_GPCS_RXPROBE7_TYPE rxprobe7; /* OFFSET: 0x198 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd52[2]; /* OFFSET: 0x19a */
    BRPHY1GV2_BR_GPCS_RFER_MON_LIMIT_TYPE rfer_mon_limit; /* OFFSET: 0x19c */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd53[2]; /* OFFSET: 0x19e */
    BRPHY1GV2_BR_GPCS_RFER_CNT_RAW_TYPE rfer_cnt_raw; /* OFFSET: 0x1a0 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd54[2]; /* OFFSET: 0x1a2 */
    BRPHY1GV2_BR_GPCS_RFER_MON_TEST_TYPE rfer_mon_test; /* OFFSET: 0x1a4 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd55[30]; /* OFFSET: 0x1a6 */
    BRPHY1GV2_BR_GPCS_T351S_TYPE table35_1_status; /* OFFSET: 0x1c4 */
    BRPHY1GV2_BR_GPCS_RESERVED_TYPE rsvd56[1078]; /* OFFSET: 0x1c6 */
    BRPHY1GV2_BR_GPCS_SPARE_END_ADDR_TYPE spare_end_addr; /* OFFSET: 0x5fc */
} BRPHY1GV2_BR_GPCS_RDBType;


#define BRPHY0_1G_BR_GPCS_BASE          (0xE0563000UL)



#define BRPHY1GV2_BR_GPCS_MAX_HW_ID     (1UL)

#endif /* BRPHY1GV2_BR_GPCS_RDB_H */
