/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file brphy1gv2_t1core_rdb.h
    @brief RDB File for BRPHY1GV2_T1CORE

    @version BCM89580_A0_20230125_RDB
*/

#ifndef BRPHY1GV2_T1CORE_RDB_H
#define BRPHY1GV2_T1CORE_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t BRPHY1GV2_T1CORE_RESERVED_TYPE;




typedef uint16_t BRPHY1GV2_T1CORE_TCOV_TYPE;
#define BRPHY1GV2_T1CORE_TCOV_RC_OSC_EN_OVERRIDE_VALUE_MASK (0x8000U)
#define BRPHY1GV2_T1CORE_TCOV_RC_OSC_EN_OVERRIDE_VALUE_SHIFT (15U)
#define BRPHY1GV2_T1CORE_TCOV_RC_OSC_IN_OVERRIDE_VALUE_MASK (0x4000U)
#define BRPHY1GV2_T1CORE_TCOV_RC_OSC_IN_OVERRIDE_VALUE_SHIFT (14U)
#define BRPHY1GV2_T1CORE_TCOV_DISABLE_DSP_RDB_CLOCK_MASK (0x2000U)
#define BRPHY1GV2_T1CORE_TCOV_DISABLE_DSP_RDB_CLOCK_SHIFT (13U)
#define BRPHY1GV2_T1CORE_TCOV_CLKOFF_TPC_TX_CLOCK_MASK (0x1000U)
#define BRPHY1GV2_T1CORE_TCOV_CLKOFF_TPC_TX_CLOCK_SHIFT (12U)
#define BRPHY1GV2_T1CORE_TCOV_CLKOFF_TPC_RX_CLOCK_MASK (0x800U)
#define BRPHY1GV2_T1CORE_TCOV_CLKOFF_TPC_RX_CLOCK_SHIFT (11U)
#define BRPHY1GV2_T1CORE_TCOV_SPARE_MASK (0x400U)
#define BRPHY1GV2_T1CORE_TCOV_SPARE_SHIFT (10U)
#define BRPHY1GV2_T1CORE_TCOV_CLKOFF_CRC_CHECK_CLOCK_MASK (0x200U)
#define BRPHY1GV2_T1CORE_TCOV_CLKOFF_CRC_CHECK_CLOCK_SHIFT (9U)
#define BRPHY1GV2_T1CORE_TCOV_CLKOFF_PATGEN_CLOCK_MASK (0x100U)
#define BRPHY1GV2_T1CORE_TCOV_CLKOFF_PATGEN_CLOCK_SHIFT (8U)
#define BRPHY1GV2_T1CORE_TCOV_CLKOFF_GPCS_TX_CLOCK_MASK (0x80U)
#define BRPHY1GV2_T1CORE_TCOV_CLKOFF_GPCS_TX_CLOCK_SHIFT (7U)
#define BRPHY1GV2_T1CORE_TCOV_CLKOFF_TX_CLOCK_125_25_MASK (0x40U)
#define BRPHY1GV2_T1CORE_TCOV_CLKOFF_TX_CLOCK_125_25_SHIFT (6U)
#define BRPHY1GV2_T1CORE_TCOV_CLKOFF_FECTX_TX_CLOCK_MASK (0x20U)
#define BRPHY1GV2_T1CORE_TCOV_CLKOFF_FECTX_TX_CLOCK_SHIFT (5U)
#define BRPHY1GV2_T1CORE_TCOV_CLKOFF_PCS_TX_CLOCK_MASK (0x10U)
#define BRPHY1GV2_T1CORE_TCOV_CLKOFF_PCS_TX_CLOCK_SHIFT (4U)
#define BRPHY1GV2_T1CORE_TCOV_NOT_USED_MASK (0x8U)
#define BRPHY1GV2_T1CORE_TCOV_NOT_USED_SHIFT (3U)
#define BRPHY1GV2_T1CORE_TCOV_CLKOFF_SCR_TX_CLOCK_MASK (0x4U)
#define BRPHY1GV2_T1CORE_TCOV_CLKOFF_SCR_TX_CLOCK_SHIFT (2U)
#define BRPHY1GV2_T1CORE_TCOV_NOT_USED1_MASK (0x2U)
#define BRPHY1GV2_T1CORE_TCOV_NOT_USED1_SHIFT (1U)
#define BRPHY1GV2_T1CORE_TCOV_CLKOFF_ACD_TX_CLOCK_MASK (0x1U)
#define BRPHY1GV2_T1CORE_TCOV_CLKOFF_ACD_TX_CLOCK_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1CORE_CLOCK_GEN_STATUS2_TYPE;
#define BRPHY1GV2_T1CORE_CLOCK_GEN_STATUS2_RC_OSC_IN_VALUE_MASK (0x8000U)
#define BRPHY1GV2_T1CORE_CLOCK_GEN_STATUS2_RC_OSC_IN_VALUE_SHIFT (15U)
#define BRPHY1GV2_T1CORE_CLOCK_GEN_STATUS2_CLOCK_GEN_STATUS_BITS_MASK (0x7fffU)
#define BRPHY1GV2_T1CORE_CLOCK_GEN_STATUS2_CLOCK_GEN_STATUS_BITS_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1CORE_PGCC_TYPE;
#define BRPHY1GV2_T1CORE_PGCC_PATTERN_GEN_NUM_OF_PACKETS_MASK (0xffffU)
#define BRPHY1GV2_T1CORE_PGCC_PATTERN_GEN_NUM_OF_PACKETS_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1CORE_PATTERN_GEN_CONTROL_D_TYPE;
#define BRPHY1GV2_T1CORE_PATTERN_GEN_CONTROL_D_PKT_SIZE_MASK (0xffffU)
#define BRPHY1GV2_T1CORE_PATTERN_GEN_CONTROL_D_PKT_SIZE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1CORE_WUP_TEST_CONTROL_TYPE;
#define BRPHY1GV2_T1CORE_WUP_TEST_CONTROL_POLARITY_SWAP_MASK (0x4U)
#define BRPHY1GV2_T1CORE_WUP_TEST_CONTROL_POLARITY_SWAP_SHIFT (2U)
#define BRPHY1GV2_T1CORE_WUP_TEST_CONTROL_SYMBOL_SWAP_MASK (0x2U)
#define BRPHY1GV2_T1CORE_WUP_TEST_CONTROL_SYMBOL_SWAP_SHIFT (1U)
#define BRPHY1GV2_T1CORE_WUP_TEST_CONTROL_EDGERATE_ENABLE_MASK (0x1U)
#define BRPHY1GV2_T1CORE_WUP_TEST_CONTROL_EDGERATE_ENABLE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1CORE_MIIF_CONT_TYPE;
#define BRPHY1GV2_T1CORE_MIIF_CONT_MIIFIFO_SFT_RESET_MASK (0x8000U)
#define BRPHY1GV2_T1CORE_MIIF_CONT_MIIFIFO_SFT_RESET_SHIFT (15U)
#define BRPHY1GV2_T1CORE_MIIF_CONT_MIIFIFO_DISABLE_FIFO_MASK (0x4000U)
#define BRPHY1GV2_T1CORE_MIIF_CONT_MIIFIFO_DISABLE_FIFO_SHIFT (14U)
#define BRPHY1GV2_T1CORE_MIIF_CONT_MIIFIFO_LPI_FEATURE_ENABLE_MASK (0x2000U)
#define BRPHY1GV2_T1CORE_MIIF_CONT_MIIFIFO_LPI_FEATURE_ENABLE_SHIFT (13U)
#define BRPHY1GV2_T1CORE_MIIF_CONT_MIIFIFO_MIN_IPG_MASK (0xf00U)
#define BRPHY1GV2_T1CORE_MIIF_CONT_MIIFIFO_MIN_IPG_SHIFT (8U)
#define BRPHY1GV2_T1CORE_MIIF_CONT_MIIFIFO_WRBLOCK_OVR_MASK (0xf0U)
#define BRPHY1GV2_T1CORE_MIIF_CONT_MIIFIFO_WRBLOCK_OVR_SHIFT (4U)
#define BRPHY1GV2_T1CORE_MIIF_CONT_MIIFIFO_WRBLOCK_MODE_MASK (0x8U)
#define BRPHY1GV2_T1CORE_MIIF_CONT_MIIFIFO_WRBLOCK_MODE_SHIFT (3U)
#define BRPHY1GV2_T1CORE_MIIF_CONT_MIIFIFO_ELASTICITY_MODE_MASK (0x3U)
#define BRPHY1GV2_T1CORE_MIIF_CONT_MIIFIFO_ELASTICITY_MODE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1CORE_TRA_TYPE;
#define BRPHY1GV2_T1CORE_TRA_PHY_CONTROL_TUNING_PARAMETERS_MASK (0xf000U)
#define BRPHY1GV2_T1CORE_TRA_PHY_CONTROL_TUNING_PARAMETERS_SHIFT (12U)
#define BRPHY1GV2_T1CORE_TRA_DSP_TUNING_PARAMETERS_MASK (0xf00U)
#define BRPHY1GV2_T1CORE_TRA_DSP_TUNING_PARAMETERS_SHIFT (8U)
#define BRPHY1GV2_T1CORE_TRA_FORCED_POLARITY_ENABLE_MASK (0x8U)
#define BRPHY1GV2_T1CORE_TRA_FORCED_POLARITY_ENABLE_SHIFT (3U)
#define BRPHY1GV2_T1CORE_TRA_FORCED_POLARITY_VALUE_MASK (0x4U)
#define BRPHY1GV2_T1CORE_TRA_FORCED_POLARITY_VALUE_SHIFT (2U)
#define BRPHY1GV2_T1CORE_TRA_FORCED_MSE_OK_MASK (0x2U)
#define BRPHY1GV2_T1CORE_TRA_FORCED_MSE_OK_SHIFT (1U)
#define BRPHY1GV2_T1CORE_TRA_FORCED_ALIGNMENT_MASK (0x1U)
#define BRPHY1GV2_T1CORE_TRA_FORCED_ALIGNMENT_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1CORE_TESTABILITY_REG_B_TYPE;
#define BRPHY1GV2_T1CORE_TESTABILITY_REG_B_PHY_STATE_MASK (0xff00U)
#define BRPHY1GV2_T1CORE_TESTABILITY_REG_B_PHY_STATE_SHIFT (8U)
#define BRPHY1GV2_T1CORE_TESTABILITY_REG_B_SYNCHRONIZATION_DONE_MASK (0x40U)
#define BRPHY1GV2_T1CORE_TESTABILITY_REG_B_SYNCHRONIZATION_DONE_SHIFT (6U)
#define BRPHY1GV2_T1CORE_TESTABILITY_REG_B_ADC_OVERFLOW_MASK (0x20U)
#define BRPHY1GV2_T1CORE_TESTABILITY_REG_B_ADC_OVERFLOW_SHIFT (5U)
#define BRPHY1GV2_T1CORE_TESTABILITY_REG_B_ALIGNMENT_OK_MASK (0x10U)
#define BRPHY1GV2_T1CORE_TESTABILITY_REG_B_ALIGNMENT_OK_SHIFT (4U)
#define BRPHY1GV2_T1CORE_TESTABILITY_REG_B_CRC_ERROR_MASK (0x8U)
#define BRPHY1GV2_T1CORE_TESTABILITY_REG_B_CRC_ERROR_SHIFT (3U)
#define BRPHY1GV2_T1CORE_TESTABILITY_REG_B_RETRAIN_MASK (0x4U)
#define BRPHY1GV2_T1CORE_TESTABILITY_REG_B_RETRAIN_SHIFT (2U)
#define BRPHY1GV2_T1CORE_TESTABILITY_REG_B_REMOTE_RECEIVER_STATUS_MASK (0x2U)
#define BRPHY1GV2_T1CORE_TESTABILITY_REG_B_REMOTE_RECEIVER_STATUS_SHIFT (1U)
#define BRPHY1GV2_T1CORE_TESTABILITY_REG_B_LOCAL_RECEIVER_STATUS_MASK (0x1U)
#define BRPHY1GV2_T1CORE_TESTABILITY_REG_B_LOCAL_RECEIVER_STATUS_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1CORE_TRC_TYPE;
#define BRPHY1GV2_T1CORE_TRC_INTERNAL_LOOPBACK_MASK (0x4000U)
#define BRPHY1GV2_T1CORE_TRC_INTERNAL_LOOPBACK_SHIFT (14U)
#define BRPHY1GV2_T1CORE_TRC_AGC_FREEZE_MASK (0x80U)
#define BRPHY1GV2_T1CORE_TRC_AGC_FREEZE_SHIFT (7U)
#define BRPHY1GV2_T1CORE_TRC_AGC_OVERRIDE_ENABLE_MASK (0x40U)
#define BRPHY1GV2_T1CORE_TRC_AGC_OVERRIDE_ENABLE_SHIFT (6U)
#define BRPHY1GV2_T1CORE_TRC_AGC_VALUE_OR_OVERRIDE_VALUE_MASK (0x3fU)
#define BRPHY1GV2_T1CORE_TRC_AGC_VALUE_OR_OVERRIDE_VALUE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_T1CORE_PSD_CNTRL_TYPE;
#define BRPHY1GV2_T1CORE_PSD_CNTRL_BR_PIN_DISABLE_MASK (0x2U)
#define BRPHY1GV2_T1CORE_PSD_CNTRL_BR_PIN_DISABLE_SHIFT (1U)
#define BRPHY1GV2_T1CORE_PSD_CNTRL_BR_OFF_MASK (0x1U)
#define BRPHY1GV2_T1CORE_PSD_CNTRL_BR_OFF_SHIFT (0U)




typedef volatile struct sBRPHY1GV2_T1CORE_RDBType {
    BRPHY1GV2_T1CORE_RESERVED_TYPE rsvd0[44]; /* OFFSET: 0x0 */
    BRPHY1GV2_T1CORE_TCOV_TYPE tx_clock_override_value; /* OFFSET: 0x2c */
    BRPHY1GV2_T1CORE_RESERVED_TYPE rsvd1[2]; /* OFFSET: 0x2e */
    BRPHY1GV2_T1CORE_CLOCK_GEN_STATUS2_TYPE clock_gen_status2; /* OFFSET: 0x30 */
    BRPHY1GV2_T1CORE_RESERVED_TYPE rsvd2[2]; /* OFFSET: 0x32 */
    BRPHY1GV2_T1CORE_PGCC_TYPE pattern_gen_control_c; /* OFFSET: 0x34 */
    BRPHY1GV2_T1CORE_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0x36 */
    BRPHY1GV2_T1CORE_PATTERN_GEN_CONTROL_D_TYPE pattern_gen_control_d; /* OFFSET: 0x38 */
    BRPHY1GV2_T1CORE_RESERVED_TYPE rsvd4[2]; /* OFFSET: 0x3a */
    BRPHY1GV2_T1CORE_WUP_TEST_CONTROL_TYPE wup_test_control; /* OFFSET: 0x3c */
    BRPHY1GV2_T1CORE_RESERVED_TYPE rsvd5[2]; /* OFFSET: 0x3e */
    BRPHY1GV2_T1CORE_MIIF_CONT_TYPE miififo_control; /* OFFSET: 0x40 */
    BRPHY1GV2_T1CORE_RESERVED_TYPE rsvd6[190]; /* OFFSET: 0x42 */
    BRPHY1GV2_T1CORE_TRA_TYPE testability_reg_a; /* OFFSET: 0x100 */
    BRPHY1GV2_T1CORE_RESERVED_TYPE rsvd7[2]; /* OFFSET: 0x102 */
    BRPHY1GV2_T1CORE_TESTABILITY_REG_B_TYPE testability_reg_b; /* OFFSET: 0x104 */
    BRPHY1GV2_T1CORE_RESERVED_TYPE rsvd8[2]; /* OFFSET: 0x106 */
    BRPHY1GV2_T1CORE_TRC_TYPE testability_reg_c; /* OFFSET: 0x108 */
    BRPHY1GV2_T1CORE_RESERVED_TYPE rsvd9[50]; /* OFFSET: 0x10a */
    BRPHY1GV2_T1CORE_PSD_CNTRL_TYPE psd_cntrl_0; /* OFFSET: 0x13c */
    BRPHY1GV2_T1CORE_RESERVED_TYPE rsvd10[2752]; /* OFFSET: 0x13e */
} BRPHY1GV2_T1CORE_RDBType;


#define BRPHY0_1G_T1_CORE_BASE          (0xE0564000UL)



#define BRPHY1GV2_T1CORE_MAX_HW_ID      (1UL)


#define ENABLE_BRPHY1G_TC10_RETENTION   (0UL)

#endif /* BRPHY1GV2_T1CORE_RDB_H */
