/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file brphy1gv2_fec_rdb.h
    @brief RDB File for BRPHY1GV2_FEC

    @version BCM89580_A0_20230125_RDB
*/

#ifndef BRPHY1GV2_FEC_RDB_H
#define BRPHY1GV2_FEC_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t BRPHY1GV2_FEC_CONFIG_0_TYPE;
#define BRPHY1GV2_FEC_CONFIG_0_CLEAR_FEC_ERR_FRM16_MASK (0x8000U)
#define BRPHY1GV2_FEC_CONFIG_0_CLEAR_FEC_ERR_FRM16_SHIFT (15U)
#define BRPHY1GV2_FEC_CONFIG_0_CLEAR_FLB_ERR_FRM16_MASK (0x4000U)
#define BRPHY1GV2_FEC_CONFIG_0_CLEAR_FLB_ERR_FRM16_SHIFT (14U)
#define BRPHY1GV2_FEC_CONFIG_0_CLEAR_FEC_ERR_FRM_MASK (0x2000U)
#define BRPHY1GV2_FEC_CONFIG_0_CLEAR_FEC_ERR_FRM_SHIFT (13U)
#define BRPHY1GV2_FEC_CONFIG_0_CLEAR_FLB_ERR_FRM_MASK (0x1000U)
#define BRPHY1GV2_FEC_CONFIG_0_CLEAR_FLB_ERR_FRM_SHIFT (12U)
#define BRPHY1GV2_FEC_CONFIG_0_FEC_CNTS_ENABLE_MASK (0x800U)
#define BRPHY1GV2_FEC_CONFIG_0_FEC_CNTS_ENABLE_SHIFT (11U)
#define BRPHY1GV2_FEC_CONFIG_0_CLEAR_FAV_ERR_REG_MASK (0x400U)
#define BRPHY1GV2_FEC_CONFIG_0_CLEAR_FAV_ERR_REG_SHIFT (10U)
#define BRPHY1GV2_FEC_CONFIG_0_CLEAR_FLB_ERR_REG_MASK (0x200U)
#define BRPHY1GV2_FEC_CONFIG_0_CLEAR_FLB_ERR_REG_SHIFT (9U)
#define BRPHY1GV2_FEC_CONFIG_0_CLEAR_DEC_COR_ERRSYM_512F_MASK (0x100U)
#define BRPHY1GV2_FEC_CONFIG_0_CLEAR_DEC_COR_ERRSYM_512F_SHIFT (8U)
#define BRPHY1GV2_FEC_CONFIG_0_FEC_DEC_STAT_CLR_MASK (0x80U)
#define BRPHY1GV2_FEC_CONFIG_0_FEC_DEC_STAT_CLR_SHIFT (7U)
#define BRPHY1GV2_FEC_CONFIG_0_FEC_DEC_INIT_MASK (0x40U)
#define BRPHY1GV2_FEC_CONFIG_0_FEC_DEC_INIT_SHIFT (6U)
#define BRPHY1GV2_FEC_CONFIG_0_CLEAR_SYMB_ERR_CNT_MASK (0x20U)
#define BRPHY1GV2_FEC_CONFIG_0_CLEAR_SYMB_ERR_CNT_SHIFT (5U)
#define BRPHY1GV2_FEC_CONFIG_0_CLEAR_BLK_ERR_CNT_MASK (0x10U)
#define BRPHY1GV2_FEC_CONFIG_0_CLEAR_BLK_ERR_CNT_SHIFT (4U)
#define BRPHY1GV2_FEC_CONFIG_0_CLEAR_BLK_CNT_MASK (0x8U)
#define BRPHY1GV2_FEC_CONFIG_0_CLEAR_BLK_CNT_SHIFT (3U)
#define BRPHY1GV2_FEC_CONFIG_0_MASK_ERROR_MASK (0x4U)
#define BRPHY1GV2_FEC_CONFIG_0_MASK_ERROR_SHIFT (2U)
#define BRPHY1GV2_FEC_CONFIG_0_SUB_DISABLE_MASK (0x2U)
#define BRPHY1GV2_FEC_CONFIG_0_SUB_DISABLE_SHIFT (1U)
#define BRPHY1GV2_FEC_CONFIG_0_BYPASS_MASK (0x1U)
#define BRPHY1GV2_FEC_CONFIG_0_BYPASS_SHIFT (0U)




typedef uint8_t BRPHY1GV2_FEC_RESERVED_TYPE;




typedef uint16_t BRPHY1GV2_FEC_BLK_CNT_PERIOD_LSB_TYPE;
#define BRPHY1GV2_FEC_BLK_CNT_PERIOD_LSB_MASK (0xffffU)
#define BRPHY1GV2_FEC_BLK_CNT_PERIOD_LSB_SHIFT (0U)




typedef uint16_t BRPHY1GV2_FEC_BLK_CNT_PERIOD_MSB_TYPE;
#define BRPHY1GV2_FEC_BLK_CNT_PERIOD_MSB_MASK (0xffffU)
#define BRPHY1GV2_FEC_BLK_CNT_PERIOD_MSB_SHIFT (0U)




typedef uint16_t BRPHY1GV2_FEC_BLK_CNT_LSB_TYPE;
#define BRPHY1GV2_FEC_BLK_CNT_LSB_MASK (0xffffU)
#define BRPHY1GV2_FEC_BLK_CNT_LSB_SHIFT (0U)




typedef uint16_t BRPHY1GV2_FEC_BLK_CNT_MSB_TYPE;
#define BRPHY1GV2_FEC_BLK_CNT_MSB_MASK (0xffffU)
#define BRPHY1GV2_FEC_BLK_CNT_MSB_SHIFT (0U)




typedef uint16_t BRPHY1GV2_FEC_BLK_ERR_CNT_LSB_TYPE;
#define BRPHY1GV2_FEC_BLK_ERR_CNT_LSB_MASK (0xffffU)
#define BRPHY1GV2_FEC_BLK_ERR_CNT_LSB_SHIFT (0U)




typedef uint16_t BRPHY1GV2_FEC_BLK_ERR_CNT_MSB_TYPE;
#define BRPHY1GV2_FEC_BLK_ERR_CNT_MSB_MASK (0xffffU)
#define BRPHY1GV2_FEC_BLK_ERR_CNT_MSB_SHIFT (0U)




typedef uint16_t BRPHY1GV2_FEC_SYMB_ERR_CNT_LSB_TYPE;
#define BRPHY1GV2_FEC_SYMB_ERR_CNT_LSB_MASK (0xffffU)
#define BRPHY1GV2_FEC_SYMB_ERR_CNT_LSB_SHIFT (0U)




typedef uint16_t BRPHY1GV2_FEC_SYMB_ERR_CNT_MSB_TYPE;
#define BRPHY1GV2_FEC_SYMB_ERR_CNT_MSB_MASK (0xffffU)
#define BRPHY1GV2_FEC_SYMB_ERR_CNT_MSB_SHIFT (0U)




typedef uint16_t BRPHY1GV2_FEC_STATUS_TYPE;
#define BRPHY1GV2_FEC_STATUS_SPARE_MASK (0xfffcU)
#define BRPHY1GV2_FEC_STATUS_SPARE_SHIFT (2U)
#define BRPHY1GV2_FEC_STATUS_SOF_SLOW_MASK (0x2U)
#define BRPHY1GV2_FEC_STATUS_SOF_SLOW_SHIFT (1U)
#define BRPHY1GV2_FEC_STATUS_SOF_FAST_MASK (0x1U)
#define BRPHY1GV2_FEC_STATUS_SOF_FAST_SHIFT (0U)




typedef uint16_t BRPHY1GV2_FEC_EBC_ACCUM_LSB_TYPE;
#define BRPHY1GV2_FEC_EBC_ACCUM_LSB_MASK (0xffffU)
#define BRPHY1GV2_FEC_EBC_ACCUM_LSB_SHIFT (0U)




typedef uint16_t BRPHY1GV2_FEC_EBC_ACCUM_MSB_TYPE;
#define BRPHY1GV2_FEC_EBC_ACCUM_MSB_MASK (0xffffU)
#define BRPHY1GV2_FEC_EBC_ACCUM_MSB_SHIFT (0U)




typedef uint16_t BRPHY1GV2_FEC_EBC_ACCUM_LRG_LSB_TYPE;
#define BRPHY1GV2_FEC_EBC_ACCUM_LRG_LSB_MASK (0xffffU)
#define BRPHY1GV2_FEC_EBC_ACCUM_LRG_LSB_SHIFT (0U)




typedef uint16_t BRPHY1GV2_FEC_EBC_ACCUM_LRG_MSB_TYPE;
#define BRPHY1GV2_FEC_EBC_ACCUM_LRG_MSB_MASK (0xffffU)
#define BRPHY1GV2_FEC_EBC_ACCUM_LRG_MSB_SHIFT (0U)




typedef uint16_t BRPHY1GV2_FEC_CONFIG_EN_TYPE;
#define BRPHY1GV2_FEC_CONFIG_EN_SPARE_H_MASK (0xfc00U)
#define BRPHY1GV2_FEC_CONFIG_EN_SPARE_H_SHIFT (10U)
#define BRPHY1GV2_FEC_CONFIG_EN_EDC_CORR_EN_MASK (0x200U)
#define BRPHY1GV2_FEC_CONFIG_EN_EDC_CORR_EN_SHIFT (9U)
#define BRPHY1GV2_FEC_CONFIG_EN_OTF_EN_MASK (0x100U)
#define BRPHY1GV2_FEC_CONFIG_EN_OTF_EN_SHIFT (8U)
#define BRPHY1GV2_FEC_CONFIG_EN_CHIEN_EN_MASK (0x80U)
#define BRPHY1GV2_FEC_CONFIG_EN_CHIEN_EN_SHIFT (7U)
#define BRPHY1GV2_FEC_CONFIG_EN_SPARE_L_MASK (0x70U)
#define BRPHY1GV2_FEC_CONFIG_EN_SPARE_L_SHIFT (4U)
#define BRPHY1GV2_FEC_CONFIG_EN_OTF_INIT_EN_MASK (0x8U)
#define BRPHY1GV2_FEC_CONFIG_EN_OTF_INIT_EN_SHIFT (3U)
#define BRPHY1GV2_FEC_CONFIG_EN_ECC_CORR_EN_MASK (0x4U)
#define BRPHY1GV2_FEC_CONFIG_EN_ECC_CORR_EN_SHIFT (2U)
#define BRPHY1GV2_FEC_CONFIG_EN_RED_CORR_EN_MASK (0x2U)
#define BRPHY1GV2_FEC_CONFIG_EN_RED_CORR_EN_SHIFT (1U)
#define BRPHY1GV2_FEC_CONFIG_EN_DATA_CORR_EN_MASK (0x1U)
#define BRPHY1GV2_FEC_CONFIG_EN_DATA_CORR_EN_SHIFT (0U)




typedef uint16_t BRPHY1GV2_FEC_DEC_FIFO_SRAM_CTRL0_TYPE;
#define BRPHY1GV2_FEC_DEC_FIFO_SRAM_CTRL0_SPARE_MASK (0xe000U)
#define BRPHY1GV2_FEC_DEC_FIFO_SRAM_CTRL0_SPARE_SHIFT (13U)
#define BRPHY1GV2_FEC_DEC_FIFO_SRAM_CTRL0_PDA_MASK (0x1000U)
#define BRPHY1GV2_FEC_DEC_FIFO_SRAM_CTRL0_PDA_SHIFT (12U)
#define BRPHY1GV2_FEC_DEC_FIFO_SRAM_CTRL0_OVSTB_MASK (0x800U)
#define BRPHY1GV2_FEC_DEC_FIFO_SRAM_CTRL0_OVSTB_SHIFT (11U)
#define BRPHY1GV2_FEC_DEC_FIFO_SRAM_CTRL0_ISO_MASK (0x400U)
#define BRPHY1GV2_FEC_DEC_FIFO_SRAM_CTRL0_ISO_SHIFT (10U)
#define BRPHY1GV2_FEC_DEC_FIFO_SRAM_CTRL0_POWEROKIN_MASK (0x200U)
#define BRPHY1GV2_FEC_DEC_FIFO_SRAM_CTRL0_POWEROKIN_SHIFT (9U)
#define BRPHY1GV2_FEC_DEC_FIFO_SRAM_CTRL0_POWERONIN_MASK (0x100U)
#define BRPHY1GV2_FEC_DEC_FIFO_SRAM_CTRL0_POWERONIN_SHIFT (8U)
#define BRPHY1GV2_FEC_DEC_FIFO_SRAM_CTRL0_ECC_MODE_MASK (0x80U)
#define BRPHY1GV2_FEC_DEC_FIFO_SRAM_CTRL0_ECC_MODE_SHIFT (7U)
#define BRPHY1GV2_FEC_DEC_FIFO_SRAM_CTRL0_TM_MASK (0x7fU)
#define BRPHY1GV2_FEC_DEC_FIFO_SRAM_CTRL0_TM_SHIFT (0U)




typedef uint16_t BRPHY1GV2_FEC_DEC_FIFO_SRAM_STATUS_TYPE;
#define BRPHY1GV2_FEC_DEC_FIFO_SRAM_STATUS_SPARE_MASK (0xfff0U)
#define BRPHY1GV2_FEC_DEC_FIFO_SRAM_STATUS_SPARE_SHIFT (4U)
#define BRPHY1GV2_FEC_DEC_FIFO_SRAM_STATUS_DED_FLAG_MASK (0x8U)
#define BRPHY1GV2_FEC_DEC_FIFO_SRAM_STATUS_DED_FLAG_SHIFT (3U)
#define BRPHY1GV2_FEC_DEC_FIFO_SRAM_STATUS_SEC_FLAG_MASK (0x4U)
#define BRPHY1GV2_FEC_DEC_FIFO_SRAM_STATUS_SEC_FLAG_SHIFT (2U)
#define BRPHY1GV2_FEC_DEC_FIFO_SRAM_STATUS_POWEROKOUT_MASK (0x2U)
#define BRPHY1GV2_FEC_DEC_FIFO_SRAM_STATUS_POWEROKOUT_SHIFT (1U)
#define BRPHY1GV2_FEC_DEC_FIFO_SRAM_STATUS_POWERONOUT_MASK (0x1U)
#define BRPHY1GV2_FEC_DEC_FIFO_SRAM_STATUS_POWERONOUT_SHIFT (0U)




typedef uint16_t BRPHY1GV2_FEC_CRCT_SYM_REG_TYPE;
#define BRPHY1GV2_FEC_CRCT_SYM_REG_MASK (0xffffU)
#define BRPHY1GV2_FEC_CRCT_SYM_REG_SHIFT (0U)




typedef uint16_t BRPHY1GV2_FEC_FLB_ERR_REG_TYPE;
#define BRPHY1GV2_FEC_FLB_ERR_REG_BLK_SIZE_MASK (0xfc00U)
#define BRPHY1GV2_FEC_FLB_ERR_REG_BLK_SIZE_SHIFT (10U)
#define BRPHY1GV2_FEC_FLB_ERR_REG_ERR_REG_MASK (0x3ffU)
#define BRPHY1GV2_FEC_FLB_ERR_REG_ERR_REG_SHIFT (0U)




typedef uint16_t BRPHY1GV2_FEC_FAV_ERR_REG_TYPE;
#define BRPHY1GV2_FEC_FAV_ERR_REG_MASK (0x3ffU)
#define BRPHY1GV2_FEC_FAV_ERR_REG_SHIFT (0U)




typedef uint16_t BRPHY1GV2_FEC_BBER_CTL_TYPE;
#define BRPHY1GV2_FEC_BBER_CTL_SPARE_15_MASK (0x8000U)
#define BRPHY1GV2_FEC_BBER_CTL_SPARE_15_SHIFT (15U)
#define BRPHY1GV2_FEC_BBER_CTL_BBER_DETECTED_MASK (0x4000U)
#define BRPHY1GV2_FEC_BBER_CTL_BBER_DETECTED_SHIFT (14U)
#define BRPHY1GV2_FEC_BBER_CTL_BBER_STATUS_MASK (0x2000U)
#define BRPHY1GV2_FEC_BBER_CTL_BBER_STATUS_SHIFT (13U)
#define BRPHY1GV2_FEC_BBER_CTL_BBER_DIS_MASK (0x1000U)
#define BRPHY1GV2_FEC_BBER_CTL_BBER_DIS_SHIFT (12U)
#define BRPHY1GV2_FEC_BBER_CTL_FEC_BBER_DET_OV_MASK (0x800U)
#define BRPHY1GV2_FEC_BBER_CTL_FEC_BBER_DET_OV_SHIFT (11U)
#define BRPHY1GV2_FEC_BBER_CTL_FEC_BBER_DET_VAL_MASK (0x400U)
#define BRPHY1GV2_FEC_BBER_CTL_FEC_BBER_DET_VAL_SHIFT (10U)
#define BRPHY1GV2_FEC_BBER_CTL_MAX_SYMB_ERR_OV_MASK (0x200U)
#define BRPHY1GV2_FEC_BBER_CTL_MAX_SYMB_ERR_OV_SHIFT (9U)
#define BRPHY1GV2_FEC_BBER_CTL_MAX_SYMB_ERR_MASK (0x1f0U)
#define BRPHY1GV2_FEC_BBER_CTL_MAX_SYMB_ERR_SHIFT (4U)
#define BRPHY1GV2_FEC_BBER_CTL_MAX_FRM_NUM_OV_MASK (0x8U)
#define BRPHY1GV2_FEC_BBER_CTL_MAX_FRM_NUM_OV_SHIFT (3U)
#define BRPHY1GV2_FEC_BBER_CTL_MAX_FRM_NUM_MASK (0x7U)
#define BRPHY1GV2_FEC_BBER_CTL_MAX_FRM_NUM_SHIFT (0U)




typedef uint16_t BRPHY1GV2_FEC_FLB_ERR_FRM_TYPE;
#define BRPHY1GV2_FEC_FLB_ERR_FRM_MASK (0x3ffU)
#define BRPHY1GV2_FEC_FLB_ERR_FRM_SHIFT (0U)




typedef uint16_t BRPHY1GV2_FEC_ERR_FRM_TYPE;
#define BRPHY1GV2_FEC_ERR_FRM_FLB_MASK (0x3ffU)
#define BRPHY1GV2_FEC_ERR_FRM_FLB_SHIFT (0U)




typedef uint16_t BRPHY1GV2_FEC_FLB_ERR_FRM16_TYPE;
#define BRPHY1GV2_FEC_FLB_ERR_FRM16_MASK (0xffffU)
#define BRPHY1GV2_FEC_FLB_ERR_FRM16_SHIFT (0U)




typedef uint16_t BRPHY1GV2_FEC_ERR_FRM16_TYPE;
#define BRPHY1GV2_FEC_ERR_FRM16_MASK (0xffffU)
#define BRPHY1GV2_FEC_ERR_FRM16_SHIFT (0U)




typedef uint16_t BRPHY1GV2_FEC_CNT_CLR_CTRL_TYPE;
#define BRPHY1GV2_FEC_CNT_CLR_CTRL_BLK_ERR_DIS_MASK (0x20U)
#define BRPHY1GV2_FEC_CNT_CLR_CTRL_BLK_ERR_DIS_SHIFT (5U)
#define BRPHY1GV2_FEC_CNT_CLR_CTRL_SYMB_ERR_CNT_DIS_MASK (0x10U)
#define BRPHY1GV2_FEC_CNT_CLR_CTRL_SYMB_ERR_CNT_DIS_SHIFT (4U)
#define BRPHY1GV2_FEC_CNT_CLR_CTRL_FEC_ERR_FRM16_DIS_MASK (0x8U)
#define BRPHY1GV2_FEC_CNT_CLR_CTRL_FEC_ERR_FRM16_DIS_SHIFT (3U)
#define BRPHY1GV2_FEC_CNT_CLR_CTRL_FLB_ERR_FRM16_DIS_MASK (0x4U)
#define BRPHY1GV2_FEC_CNT_CLR_CTRL_FLB_ERR_FRM16_DIS_SHIFT (2U)
#define BRPHY1GV2_FEC_CNT_CLR_CTRL_FEC_ERR_FRM_DIS_MASK (0x2U)
#define BRPHY1GV2_FEC_CNT_CLR_CTRL_FEC_ERR_FRM_DIS_SHIFT (1U)
#define BRPHY1GV2_FEC_CNT_CLR_CTRL_FLB_ERR_FRM_DIS_MASK (0x1U)
#define BRPHY1GV2_FEC_CNT_CLR_CTRL_FLB_ERR_FRM_DIS_SHIFT (0U)




typedef uint16_t BRPHY1GV2_FEC_END_TYPE;
#define BRPHY1GV2_FEC_END_MASK (0xffffU)
#define BRPHY1GV2_FEC_END_SHIFT (0U)




typedef volatile struct sBRPHY1GV2_FEC_RDBType {
    BRPHY1GV2_FEC_CONFIG_0_TYPE config_0; /* OFFSET: 0x0 */
    BRPHY1GV2_FEC_RESERVED_TYPE rsvd0[2]; /* OFFSET: 0x2 */
    BRPHY1GV2_FEC_BLK_CNT_PERIOD_LSB_TYPE blk_cnt_period_lsb; /* OFFSET: 0x4 */
    BRPHY1GV2_FEC_RESERVED_TYPE rsvd1[2]; /* OFFSET: 0x6 */
    BRPHY1GV2_FEC_BLK_CNT_PERIOD_MSB_TYPE blk_cnt_period_msb; /* OFFSET: 0x8 */
    BRPHY1GV2_FEC_RESERVED_TYPE rsvd2[2]; /* OFFSET: 0xa */
    BRPHY1GV2_FEC_BLK_CNT_LSB_TYPE blk_cnt_lsb; /* OFFSET: 0xc */
    BRPHY1GV2_FEC_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0xe */
    BRPHY1GV2_FEC_BLK_CNT_MSB_TYPE blk_cnt_msb; /* OFFSET: 0x10 */
    BRPHY1GV2_FEC_RESERVED_TYPE rsvd4[2]; /* OFFSET: 0x12 */
    BRPHY1GV2_FEC_BLK_ERR_CNT_LSB_TYPE blk_err_cnt_lsb; /* OFFSET: 0x14 */
    BRPHY1GV2_FEC_RESERVED_TYPE rsvd5[2]; /* OFFSET: 0x16 */
    BRPHY1GV2_FEC_BLK_ERR_CNT_MSB_TYPE blk_err_cnt_msb; /* OFFSET: 0x18 */
    BRPHY1GV2_FEC_RESERVED_TYPE rsvd6[2]; /* OFFSET: 0x1a */
    BRPHY1GV2_FEC_SYMB_ERR_CNT_LSB_TYPE symb_err_cnt_lsb; /* OFFSET: 0x1c */
    BRPHY1GV2_FEC_RESERVED_TYPE rsvd7[2]; /* OFFSET: 0x1e */
    BRPHY1GV2_FEC_SYMB_ERR_CNT_MSB_TYPE symb_err_cnt_msb; /* OFFSET: 0x20 */
    BRPHY1GV2_FEC_RESERVED_TYPE rsvd8[2]; /* OFFSET: 0x22 */
    BRPHY1GV2_FEC_STATUS_TYPE status; /* OFFSET: 0x24 */
    BRPHY1GV2_FEC_RESERVED_TYPE rsvd9[2]; /* OFFSET: 0x26 */
    BRPHY1GV2_FEC_EBC_ACCUM_LSB_TYPE ebc_accum_lsb; /* OFFSET: 0x28 */
    BRPHY1GV2_FEC_RESERVED_TYPE rsvd10[2]; /* OFFSET: 0x2a */
    BRPHY1GV2_FEC_EBC_ACCUM_MSB_TYPE ebc_accum_msb; /* OFFSET: 0x2c */
    BRPHY1GV2_FEC_RESERVED_TYPE rsvd11[2]; /* OFFSET: 0x2e */
    BRPHY1GV2_FEC_EBC_ACCUM_LRG_LSB_TYPE ebc_accum_lrg_lsb; /* OFFSET: 0x30 */
    BRPHY1GV2_FEC_RESERVED_TYPE rsvd12[2]; /* OFFSET: 0x32 */
    BRPHY1GV2_FEC_EBC_ACCUM_LRG_MSB_TYPE ebc_accum_lrg_msb; /* OFFSET: 0x34 */
    BRPHY1GV2_FEC_RESERVED_TYPE rsvd13[2]; /* OFFSET: 0x36 */
    BRPHY1GV2_FEC_CONFIG_EN_TYPE config_en; /* OFFSET: 0x38 */
    BRPHY1GV2_FEC_RESERVED_TYPE rsvd14[2]; /* OFFSET: 0x3a */
    BRPHY1GV2_FEC_DEC_FIFO_SRAM_CTRL0_TYPE dec_fifo_sram_ctrl0; /* OFFSET: 0x3c */
    BRPHY1GV2_FEC_RESERVED_TYPE rsvd15[2]; /* OFFSET: 0x3e */
    BRPHY1GV2_FEC_DEC_FIFO_SRAM_STATUS_TYPE dec_fifo_sram_status; /* OFFSET: 0x40 */
    BRPHY1GV2_FEC_RESERVED_TYPE rsvd16[2]; /* OFFSET: 0x42 */
    BRPHY1GV2_FEC_CRCT_SYM_REG_TYPE crct_sym_reg; /* OFFSET: 0x44 */
    BRPHY1GV2_FEC_RESERVED_TYPE rsvd17[2]; /* OFFSET: 0x46 */
    BRPHY1GV2_FEC_FLB_ERR_REG_TYPE flb_err_reg; /* OFFSET: 0x48 */
    BRPHY1GV2_FEC_RESERVED_TYPE rsvd18[2]; /* OFFSET: 0x4a */
    BRPHY1GV2_FEC_FAV_ERR_REG_TYPE fav_err_reg; /* OFFSET: 0x4c */
    BRPHY1GV2_FEC_RESERVED_TYPE rsvd19[2]; /* OFFSET: 0x4e */
    BRPHY1GV2_FEC_BBER_CTL_TYPE bber_ctl; /* OFFSET: 0x50 */
    BRPHY1GV2_FEC_RESERVED_TYPE rsvd20[2]; /* OFFSET: 0x52 */
    BRPHY1GV2_FEC_FLB_ERR_FRM_TYPE flb_err_frm; /* OFFSET: 0x54 */
    BRPHY1GV2_FEC_RESERVED_TYPE rsvd21[2]; /* OFFSET: 0x56 */
    BRPHY1GV2_FEC_ERR_FRM_TYPE fec_err_frm; /* OFFSET: 0x58 */
    BRPHY1GV2_FEC_RESERVED_TYPE rsvd22[2]; /* OFFSET: 0x5a */
    BRPHY1GV2_FEC_FLB_ERR_FRM16_TYPE flb_err_frm16; /* OFFSET: 0x5c */
    BRPHY1GV2_FEC_RESERVED_TYPE rsvd23[2]; /* OFFSET: 0x5e */
    BRPHY1GV2_FEC_ERR_FRM16_TYPE fec_err_frm16; /* OFFSET: 0x60 */
    BRPHY1GV2_FEC_RESERVED_TYPE rsvd24[2]; /* OFFSET: 0x62 */
    BRPHY1GV2_FEC_CNT_CLR_CTRL_TYPE cnt_clr_ctrl; /* OFFSET: 0x64 */
    BRPHY1GV2_FEC_RESERVED_TYPE rsvd25[406]; /* OFFSET: 0x66 */
    BRPHY1GV2_FEC_END_TYPE fec_end; /* OFFSET: 0x1fc */
} BRPHY1GV2_FEC_RDBType;


#define BRPHY0_1G_FEC_BASE              (0xE0563600UL)



#define BRPHY1GV2_FEC_MAX_HW_ID         (1UL)

#endif /* BRPHY1GV2_FEC_RDB_H */
