/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file brphy1gv2_ffe_rdb.h
    @brief RDB File for BRPHY1GV2_FFE

    @version BCM89580_A0_20230125_RDB
*/

#ifndef BRPHY1GV2_FFE_RDB_H
#define BRPHY1GV2_FFE_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t BRPHY1GV2_FFE_CONTROL_0_TYPE;
#define BRPHY1GV2_FFE_CONTROL_0_FFERSTN_FORCE_DEASSERT_MASK (0x4000U)
#define BRPHY1GV2_FFE_CONTROL_0_FFERSTN_FORCE_DEASSERT_SHIFT (14U)
#define BRPHY1GV2_FFE_CONTROL_0_FFERSTN_FORCE_ASSERT_MASK (0x2000U)
#define BRPHY1GV2_FFE_CONTROL_0_FFERSTN_FORCE_ASSERT_SHIFT (13U)
#define BRPHY1GV2_FFE_CONTROL_0_MU_OVERRIDE_MASK (0x1000U)
#define BRPHY1GV2_FFE_CONTROL_0_MU_OVERRIDE_SHIFT (12U)
#define BRPHY1GV2_FFE_CONTROL_0_FFELGEAR_MASK (0x800U)
#define BRPHY1GV2_FFE_CONTROL_0_FFELGEAR_SHIFT (11U)
#define BRPHY1GV2_FFE_CONTROL_0_HI_MU_CTL_MASK (0x600U)
#define BRPHY1GV2_FFE_CONTROL_0_HI_MU_CTL_SHIFT (9U)
#define BRPHY1GV2_FFE_CONTROL_0_LO_MU_CTL_MASK (0x180U)
#define BRPHY1GV2_FFE_CONTROL_0_LO_MU_CTL_SHIFT (7U)
#define BRPHY1GV2_FFE_CONTROL_0_LMS_LKG_SEL_MASK (0x60U)
#define BRPHY1GV2_FFE_CONTROL_0_LMS_LKG_SEL_SHIFT (5U)
#define BRPHY1GV2_FFE_CONTROL_0_LMS_LKG_EN_MASK (0x10U)
#define BRPHY1GV2_FFE_CONTROL_0_LMS_LKG_EN_SHIFT (4U)
#define BRPHY1GV2_FFE_CONTROL_0_LMS_UPDT_CTL_MASK (0x8U)
#define BRPHY1GV2_FFE_CONTROL_0_LMS_UPDT_CTL_SHIFT (3U)
#define BRPHY1GV2_FFE_CONTROL_0_POST_CURSOR_SEL_MASK (0x4U)
#define BRPHY1GV2_FFE_CONTROL_0_POST_CURSOR_SEL_SHIFT (2U)
#define BRPHY1GV2_FFE_CONTROL_0_GAMMA_SEL_MASK (0x2U)
#define BRPHY1GV2_FFE_CONTROL_0_GAMMA_SEL_SHIFT (1U)
#define BRPHY1GV2_FFE_CONTROL_0_MAIN_TAP_SEL_MASK (0x1U)
#define BRPHY1GV2_FFE_CONTROL_0_MAIN_TAP_SEL_SHIFT (0U)




typedef uint8_t BRPHY1GV2_FFE_RESERVED_TYPE;




typedef uint16_t BRPHY1GV2_FFE_FFA1500_TYPE;
#define BRPHY1GV2_FFE_FFA1500_FREEZE_FORCE_ASSERT_15_00_MASK (0xffffU)
#define BRPHY1GV2_FFE_FFA1500_FREEZE_FORCE_ASSERT_15_00_SHIFT (0U)




typedef uint16_t BRPHY1GV2_FFE_FFA3116_TYPE;
#define BRPHY1GV2_FFE_FFA3116_FREEZE_FORCE_ASSERT_31_16_MASK (0xffffU)
#define BRPHY1GV2_FFE_FFA3116_FREEZE_FORCE_ASSERT_31_16_SHIFT (0U)




typedef uint16_t BRPHY1GV2_FFE_FFD1500_TYPE;
#define BRPHY1GV2_FFE_FFD1500_FREEZE_FORCE_DEASSERT_15_00_MASK (0xffffU)
#define BRPHY1GV2_FFE_FFD1500_FREEZE_FORCE_DEASSERT_15_00_SHIFT (0U)




typedef uint16_t BRPHY1GV2_FFE_FFD3116_TYPE;
#define BRPHY1GV2_FFE_FFD3116_FREEZE_FORCE_DEASSERT_31_16_MASK (0xffffU)
#define BRPHY1GV2_FFE_FFD3116_FREEZE_FORCE_DEASSERT_31_16_SHIFT (0U)




typedef uint16_t BRPHY1GV2_FFE_COEFF_LSB_TYPE;
#define BRPHY1GV2_FFE_COEFF_LSB_MASK (0xffffU)
#define BRPHY1GV2_FFE_COEFF_LSB_SHIFT (0U)




typedef uint16_t BRPHY1GV2_FFE_COEFF_MSB_TYPE;
#define BRPHY1GV2_FFE_COEFF_MSB_MASK (0x1ffU)
#define BRPHY1GV2_FFE_COEFF_MSB_SHIFT (0U)




typedef uint16_t BRPHY1GV2_FFE_SPARE_END_ADDR_TYPE;
#define BRPHY1GV2_FFE_SPARE_END_ADDR_MASK (0xffffU)
#define BRPHY1GV2_FFE_SPARE_END_ADDR_SHIFT (0U)




typedef volatile struct sBRPHY1GV2_FFE_RDBType {
    BRPHY1GV2_FFE_CONTROL_0_TYPE control_0; /* OFFSET: 0x0 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd0[2]; /* OFFSET: 0x2 */
    BRPHY1GV2_FFE_FFA1500_TYPE freeze_force_assert_15_00; /* OFFSET: 0x4 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd1[2]; /* OFFSET: 0x6 */
    BRPHY1GV2_FFE_FFA3116_TYPE freeze_force_assert_31_16; /* OFFSET: 0x8 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd2[2]; /* OFFSET: 0xa */
    BRPHY1GV2_FFE_FFD1500_TYPE freeze_force_deassert_15_00; /* OFFSET: 0xc */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0xe */
    BRPHY1GV2_FFE_FFD3116_TYPE freeze_force_deassert_31_16; /* OFFSET: 0x10 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd4[46]; /* OFFSET: 0x12 */
    BRPHY1GV2_FFE_COEFF_LSB_TYPE coeff_00_lsb; /* OFFSET: 0x40 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd5[2]; /* OFFSET: 0x42 */
    BRPHY1GV2_FFE_COEFF_MSB_TYPE coeff_00_msb; /* OFFSET: 0x44 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd6[2]; /* OFFSET: 0x46 */
    BRPHY1GV2_FFE_COEFF_LSB_TYPE coeff_01_lsb; /* OFFSET: 0x48 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd7[2]; /* OFFSET: 0x4a */
    BRPHY1GV2_FFE_COEFF_MSB_TYPE coeff_01_msb; /* OFFSET: 0x4c */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd8[2]; /* OFFSET: 0x4e */
    BRPHY1GV2_FFE_COEFF_LSB_TYPE coeff_02_lsb; /* OFFSET: 0x50 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd9[2]; /* OFFSET: 0x52 */
    BRPHY1GV2_FFE_COEFF_MSB_TYPE coeff_02_msb; /* OFFSET: 0x54 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd10[2]; /* OFFSET: 0x56 */
    BRPHY1GV2_FFE_COEFF_LSB_TYPE coeff_03_lsb; /* OFFSET: 0x58 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd11[2]; /* OFFSET: 0x5a */
    BRPHY1GV2_FFE_COEFF_MSB_TYPE coeff_03_msb; /* OFFSET: 0x5c */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd12[2]; /* OFFSET: 0x5e */
    BRPHY1GV2_FFE_COEFF_LSB_TYPE coeff_04_lsb; /* OFFSET: 0x60 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd13[2]; /* OFFSET: 0x62 */
    BRPHY1GV2_FFE_COEFF_MSB_TYPE coeff_04_msb; /* OFFSET: 0x64 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd14[2]; /* OFFSET: 0x66 */
    BRPHY1GV2_FFE_COEFF_LSB_TYPE coeff_05_lsb; /* OFFSET: 0x68 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd15[2]; /* OFFSET: 0x6a */
    BRPHY1GV2_FFE_COEFF_MSB_TYPE coeff_05_msb; /* OFFSET: 0x6c */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd16[2]; /* OFFSET: 0x6e */
    BRPHY1GV2_FFE_COEFF_LSB_TYPE coeff_06_lsb; /* OFFSET: 0x70 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd17[2]; /* OFFSET: 0x72 */
    BRPHY1GV2_FFE_COEFF_MSB_TYPE coeff_06_msb; /* OFFSET: 0x74 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd18[2]; /* OFFSET: 0x76 */
    BRPHY1GV2_FFE_COEFF_LSB_TYPE coeff_07_lsb; /* OFFSET: 0x78 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd19[2]; /* OFFSET: 0x7a */
    BRPHY1GV2_FFE_COEFF_MSB_TYPE coeff_07_msb; /* OFFSET: 0x7c */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd20[2]; /* OFFSET: 0x7e */
    BRPHY1GV2_FFE_COEFF_LSB_TYPE coeff_08_lsb; /* OFFSET: 0x80 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd21[2]; /* OFFSET: 0x82 */
    BRPHY1GV2_FFE_COEFF_MSB_TYPE coeff_08_msb; /* OFFSET: 0x84 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd22[2]; /* OFFSET: 0x86 */
    BRPHY1GV2_FFE_COEFF_LSB_TYPE coeff_09_lsb; /* OFFSET: 0x88 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd23[2]; /* OFFSET: 0x8a */
    BRPHY1GV2_FFE_COEFF_MSB_TYPE coeff_09_msb; /* OFFSET: 0x8c */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd24[2]; /* OFFSET: 0x8e */
    BRPHY1GV2_FFE_COEFF_LSB_TYPE coeff_10_lsb; /* OFFSET: 0x90 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd25[2]; /* OFFSET: 0x92 */
    BRPHY1GV2_FFE_COEFF_MSB_TYPE coeff_10_msb; /* OFFSET: 0x94 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd26[2]; /* OFFSET: 0x96 */
    BRPHY1GV2_FFE_COEFF_LSB_TYPE coeff_11_lsb; /* OFFSET: 0x98 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd27[2]; /* OFFSET: 0x9a */
    BRPHY1GV2_FFE_COEFF_MSB_TYPE coeff_11_msb; /* OFFSET: 0x9c */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd28[2]; /* OFFSET: 0x9e */
    BRPHY1GV2_FFE_COEFF_LSB_TYPE coeff_12_lsb; /* OFFSET: 0xa0 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd29[2]; /* OFFSET: 0xa2 */
    BRPHY1GV2_FFE_COEFF_MSB_TYPE coeff_12_msb; /* OFFSET: 0xa4 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd30[2]; /* OFFSET: 0xa6 */
    BRPHY1GV2_FFE_COEFF_LSB_TYPE coeff_13_lsb; /* OFFSET: 0xa8 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd31[2]; /* OFFSET: 0xaa */
    BRPHY1GV2_FFE_COEFF_MSB_TYPE coeff_13_msb; /* OFFSET: 0xac */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd32[2]; /* OFFSET: 0xae */
    BRPHY1GV2_FFE_COEFF_LSB_TYPE coeff_14_lsb; /* OFFSET: 0xb0 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd33[2]; /* OFFSET: 0xb2 */
    BRPHY1GV2_FFE_COEFF_MSB_TYPE coeff_14_msb; /* OFFSET: 0xb4 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd34[2]; /* OFFSET: 0xb6 */
    BRPHY1GV2_FFE_COEFF_LSB_TYPE coeff_15_lsb; /* OFFSET: 0xb8 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd35[2]; /* OFFSET: 0xba */
    BRPHY1GV2_FFE_COEFF_MSB_TYPE coeff_15_msb; /* OFFSET: 0xbc */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd36[2]; /* OFFSET: 0xbe */
    BRPHY1GV2_FFE_COEFF_LSB_TYPE coeff_16_lsb; /* OFFSET: 0xc0 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd37[2]; /* OFFSET: 0xc2 */
    BRPHY1GV2_FFE_COEFF_MSB_TYPE coeff_16_msb; /* OFFSET: 0xc4 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd38[2]; /* OFFSET: 0xc6 */
    BRPHY1GV2_FFE_COEFF_LSB_TYPE coeff_17_lsb; /* OFFSET: 0xc8 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd39[2]; /* OFFSET: 0xca */
    BRPHY1GV2_FFE_COEFF_MSB_TYPE coeff_17_msb; /* OFFSET: 0xcc */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd40[2]; /* OFFSET: 0xce */
    BRPHY1GV2_FFE_COEFF_LSB_TYPE coeff_18_lsb; /* OFFSET: 0xd0 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd41[2]; /* OFFSET: 0xd2 */
    BRPHY1GV2_FFE_COEFF_MSB_TYPE coeff_18_msb; /* OFFSET: 0xd4 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd42[2]; /* OFFSET: 0xd6 */
    BRPHY1GV2_FFE_COEFF_LSB_TYPE coeff_19_lsb; /* OFFSET: 0xd8 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd43[2]; /* OFFSET: 0xda */
    BRPHY1GV2_FFE_COEFF_MSB_TYPE coeff_19_msb; /* OFFSET: 0xdc */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd44[2]; /* OFFSET: 0xde */
    BRPHY1GV2_FFE_COEFF_LSB_TYPE coeff_20_lsb; /* OFFSET: 0xe0 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd45[2]; /* OFFSET: 0xe2 */
    BRPHY1GV2_FFE_COEFF_MSB_TYPE coeff_20_msb; /* OFFSET: 0xe4 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd46[2]; /* OFFSET: 0xe6 */
    BRPHY1GV2_FFE_COEFF_LSB_TYPE coeff_21_lsb; /* OFFSET: 0xe8 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd47[2]; /* OFFSET: 0xea */
    BRPHY1GV2_FFE_COEFF_MSB_TYPE coeff_21_msb; /* OFFSET: 0xec */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd48[2]; /* OFFSET: 0xee */
    BRPHY1GV2_FFE_COEFF_LSB_TYPE coeff_22_lsb; /* OFFSET: 0xf0 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd49[2]; /* OFFSET: 0xf2 */
    BRPHY1GV2_FFE_COEFF_MSB_TYPE coeff_22_msb; /* OFFSET: 0xf4 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd50[2]; /* OFFSET: 0xf6 */
    BRPHY1GV2_FFE_COEFF_LSB_TYPE coeff_23_lsb; /* OFFSET: 0xf8 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd51[2]; /* OFFSET: 0xfa */
    BRPHY1GV2_FFE_COEFF_MSB_TYPE coeff_23_msb; /* OFFSET: 0xfc */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd52[2]; /* OFFSET: 0xfe */
    BRPHY1GV2_FFE_COEFF_LSB_TYPE coeff_24_lsb; /* OFFSET: 0x100 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd53[2]; /* OFFSET: 0x102 */
    BRPHY1GV2_FFE_COEFF_MSB_TYPE coeff_24_msb; /* OFFSET: 0x104 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd54[2]; /* OFFSET: 0x106 */
    BRPHY1GV2_FFE_COEFF_LSB_TYPE coeff_25_lsb; /* OFFSET: 0x108 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd55[2]; /* OFFSET: 0x10a */
    BRPHY1GV2_FFE_COEFF_MSB_TYPE coeff_25_msb; /* OFFSET: 0x10c */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd56[2]; /* OFFSET: 0x10e */
    BRPHY1GV2_FFE_COEFF_LSB_TYPE coeff_26_lsb; /* OFFSET: 0x110 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd57[2]; /* OFFSET: 0x112 */
    BRPHY1GV2_FFE_COEFF_MSB_TYPE coeff_26_msb; /* OFFSET: 0x114 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd58[2]; /* OFFSET: 0x116 */
    BRPHY1GV2_FFE_COEFF_LSB_TYPE coeff_27_lsb; /* OFFSET: 0x118 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd59[2]; /* OFFSET: 0x11a */
    BRPHY1GV2_FFE_COEFF_MSB_TYPE coeff_27_msb; /* OFFSET: 0x11c */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd60[2]; /* OFFSET: 0x11e */
    BRPHY1GV2_FFE_COEFF_LSB_TYPE coeff_28_lsb; /* OFFSET: 0x120 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd61[2]; /* OFFSET: 0x122 */
    BRPHY1GV2_FFE_COEFF_MSB_TYPE coeff_28_msb; /* OFFSET: 0x124 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd62[2]; /* OFFSET: 0x126 */
    BRPHY1GV2_FFE_COEFF_LSB_TYPE coeff_29_lsb; /* OFFSET: 0x128 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd63[2]; /* OFFSET: 0x12a */
    BRPHY1GV2_FFE_COEFF_MSB_TYPE coeff_29_msb; /* OFFSET: 0x12c */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd64[2]; /* OFFSET: 0x12e */
    BRPHY1GV2_FFE_COEFF_LSB_TYPE coeff_30_lsb; /* OFFSET: 0x130 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd65[2]; /* OFFSET: 0x132 */
    BRPHY1GV2_FFE_COEFF_MSB_TYPE coeff_30_msb; /* OFFSET: 0x134 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd66[2]; /* OFFSET: 0x136 */
    BRPHY1GV2_FFE_COEFF_LSB_TYPE coeff_31_lsb; /* OFFSET: 0x138 */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd67[2]; /* OFFSET: 0x13a */
    BRPHY1GV2_FFE_COEFF_MSB_TYPE coeff_31_msb; /* OFFSET: 0x13c */
    BRPHY1GV2_FFE_RESERVED_TYPE rsvd68[190]; /* OFFSET: 0x13e */
    BRPHY1GV2_FFE_SPARE_END_ADDR_TYPE spare_end_addr; /* OFFSET: 0x1fc */
} BRPHY1GV2_FFE_RDBType;


#define BRPHY0_1G_FFE_BASE              (0xE0561800UL)



#define BRPHY1GV2_FFE_MAX_HW_ID         (1UL)

#endif /* BRPHY1GV2_FFE_RDB_H */
