/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file brphy1gv2_test_rdb.h
    @brief RDB File for BRPHY1GV2_TEST

    @version BCM89580_A0_20230125_RDB
*/

#ifndef BRPHY1GV2_TEST_RDB_H
#define BRPHY1GV2_TEST_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t BRPHY1GV2_TEST_RESERVED_TYPE;




typedef uint16_t BRPHY1GV2_TEST_TC10_CONTROL_REG1_TYPE;
#define BRPHY1GV2_TEST_TC10_CONTROL_REG1_TC10_CTRL_MASK (0xc000U)
#define BRPHY1GV2_TEST_TC10_CONTROL_REG1_TC10_CTRL_SHIFT (14U)
#define BRPHY1GV2_TEST_TC10_CONTROL_REG1_PCS_SLEEP_TRIG_MASK (0x2000U)
#define BRPHY1GV2_TEST_TC10_CONTROL_REG1_PCS_SLEEP_TRIG_SHIFT (13U)
#define BRPHY1GV2_TEST_TC10_CONTROL_REG1_PSD_WAKE_FLAG_CLR_MASK (0x1000U)
#define BRPHY1GV2_TEST_TC10_CONTROL_REG1_PSD_WAKE_FLAG_CLR_SHIFT (12U)
#define BRPHY1GV2_TEST_TC10_CONTROL_REG1_TC10_DISABLE_CFG_MASK (0x800U)
#define BRPHY1GV2_TEST_TC10_CONTROL_REG1_TC10_DISABLE_CFG_SHIFT (11U)
#define BRPHY1GV2_TEST_TC10_CONTROL_REG1_TC10_INTR_EN_MASK (0x400U)
#define BRPHY1GV2_TEST_TC10_CONTROL_REG1_TC10_INTR_EN_SHIFT (10U)
#define BRPHY1GV2_TEST_TC10_CONTROL_REG1_TC10_INTR_ENABLES_MASK (0x3f0U)
#define BRPHY1GV2_TEST_TC10_CONTROL_REG1_TC10_INTR_ENABLES_SHIFT (4U)
#define BRPHY1GV2_TEST_TC10_CONTROL_REG1_WAKEUP_REQ_MASK (0x8U)
#define BRPHY1GV2_TEST_TC10_CONTROL_REG1_WAKEUP_REQ_SHIFT (3U)
#define BRPHY1GV2_TEST_TC10_CONTROL_REG1_SLEEPABORT_REQ_MASK (0x4U)
#define BRPHY1GV2_TEST_TC10_CONTROL_REG1_SLEEPABORT_REQ_SHIFT (2U)
#define BRPHY1GV2_TEST_TC10_CONTROL_REG1_SLEEP_REQ_MASK (0x2U)
#define BRPHY1GV2_TEST_TC10_CONTROL_REG1_SLEEP_REQ_SHIFT (1U)
#define BRPHY1GV2_TEST_TC10_CONTROL_REG1_GO2SLEEP_AUTO_MASK (0x1U)
#define BRPHY1GV2_TEST_TC10_CONTROL_REG1_GO2SLEEP_AUTO_SHIFT (0U)




typedef uint16_t BRPHY1GV2_TEST_TC10_STATUS_REG1_TYPE;
#define BRPHY1GV2_TEST_TC10_STATUS_REG1_UNUSED_MASK (0xf000U)
#define BRPHY1GV2_TEST_TC10_STATUS_REG1_UNUSED_SHIFT (12U)
#define BRPHY1GV2_TEST_TC10_STATUS_REG1_WAKEUP_STAT_MASK (0x800U)
#define BRPHY1GV2_TEST_TC10_STATUS_REG1_WAKEUP_STAT_SHIFT (11U)
#define BRPHY1GV2_TEST_TC10_STATUS_REG1_SLP_WUP_STATE_MASK (0x700U)
#define BRPHY1GV2_TEST_TC10_STATUS_REG1_SLP_WUP_STATE_SHIFT (8U)
#define BRPHY1GV2_TEST_TC10_STATUS_REG1_WURFAIL_LAT_MASK (0x80U)
#define BRPHY1GV2_TEST_TC10_STATUS_REG1_WURFAIL_LAT_SHIFT (7U)
#define BRPHY1GV2_TEST_TC10_STATUS_REG1_AFE_WVWAKE_LAT_MASK (0x40U)
#define BRPHY1GV2_TEST_TC10_STATUS_REG1_AFE_WVWAKE_LAT_SHIFT (6U)
#define BRPHY1GV2_TEST_TC10_STATUS_REG1_WAKEUP_LAT_MASK (0x20U)
#define BRPHY1GV2_TEST_TC10_STATUS_REG1_WAKEUP_LAT_SHIFT (5U)
#define BRPHY1GV2_TEST_TC10_STATUS_REG1_INHIBIT_MASK (0x10U)
#define BRPHY1GV2_TEST_TC10_STATUS_REG1_INHIBIT_SHIFT (4U)
#define BRPHY1GV2_TEST_TC10_STATUS_REG1_INHIBIT_LAT_MASK (0x8U)
#define BRPHY1GV2_TEST_TC10_STATUS_REG1_INHIBIT_LAT_SHIFT (3U)
#define BRPHY1GV2_TEST_TC10_STATUS_REG1_SLEEP_LAT_MASK (0x4U)
#define BRPHY1GV2_TEST_TC10_STATUS_REG1_SLEEP_LAT_SHIFT (2U)
#define BRPHY1GV2_TEST_TC10_STATUS_REG1_SLEEPFAIL_LAT_MASK (0x2U)
#define BRPHY1GV2_TEST_TC10_STATUS_REG1_SLEEPFAIL_LAT_SHIFT (1U)
#define BRPHY1GV2_TEST_TC10_STATUS_REG1_AFE_WVMDI_LAT_MASK (0x1U)
#define BRPHY1GV2_TEST_TC10_STATUS_REG1_AFE_WVMDI_LAT_SHIFT (0U)




typedef uint16_t BRPHY1GV2_TEST_TC10_CONTROL_1_REG1_TYPE;
#define BRPHY1GV2_TEST_TC10_CONTROL_1_REG1_WAKE_OUT_CLR_MASK (0x8000U)
#define BRPHY1GV2_TEST_TC10_CONTROL_1_REG1_WAKE_OUT_CLR_SHIFT (15U)
#define BRPHY1GV2_TEST_TC10_CONTROL_1_REG1_TC10_SFTW_DIS_MASK (0x4000U)
#define BRPHY1GV2_TEST_TC10_CONTROL_1_REG1_TC10_SFTW_DIS_SHIFT (14U)
#define BRPHY1GV2_TEST_TC10_CONTROL_1_REG1_BYPASS_DISABLE_CFG_MASK (0x2000U)
#define BRPHY1GV2_TEST_TC10_CONTROL_1_REG1_BYPASS_DISABLE_CFG_SHIFT (13U)
#define BRPHY1GV2_TEST_TC10_CONTROL_1_REG1_SLP_DONE_MASK_MASK (0x1000U)
#define BRPHY1GV2_TEST_TC10_CONTROL_1_REG1_SLP_DONE_MASK_SHIFT (12U)
#define BRPHY1GV2_TEST_TC10_CONTROL_1_REG1_WAKE_FWD_TRIG_MASK (0x800U)
#define BRPHY1GV2_TEST_TC10_CONTROL_1_REG1_WAKE_FWD_TRIG_SHIFT (11U)
#define BRPHY1GV2_TEST_TC10_CONTROL_1_REG1_TC10_LINKSTATUS_DIS_MASK (0x400U)
#define BRPHY1GV2_TEST_TC10_CONTROL_1_REG1_TC10_LINKSTATUS_DIS_SHIFT (10U)
#define BRPHY1GV2_TEST_TC10_CONTROL_1_REG1_TC10_POWER_DOWN_RESET_SELECT_MASK (0x8U)
#define BRPHY1GV2_TEST_TC10_CONTROL_1_REG1_TC10_POWER_DOWN_RESET_SEL_SHIFT (3U)
#define BRPHY1GV2_TEST_TC10_CONTROL_1_REG1_DIS_SMI_MASK (0x4U)
#define BRPHY1GV2_TEST_TC10_CONTROL_1_REG1_DIS_SMI_SHIFT (2U)
#define BRPHY1GV2_TEST_TC10_CONTROL_1_REG1_PHY_PRGM_DONE_MASK (0x1U)
#define BRPHY1GV2_TEST_TC10_CONTROL_1_REG1_PHY_PRGM_DONE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_TEST_TC10_CONTROL_2_REG1_TYPE;
#define BRPHY1GV2_TEST_TC10_CONTROL_2_REG1_WUP_FWD_EN_CFG_MASK (0x80U)
#define BRPHY1GV2_TEST_TC10_CONTROL_2_REG1_WUP_FWD_EN_CFG_SHIFT (7U)
#define BRPHY1GV2_TEST_TC10_CONTROL_2_REG1_LOC_WAKE_EN_CFG_MASK (0x40U)
#define BRPHY1GV2_TEST_TC10_CONTROL_2_REG1_LOC_WAKE_EN_CFG_SHIFT (6U)
#define BRPHY1GV2_TEST_TC10_CONTROL_2_REG1_WAKE_FWD_MDI_CFG_MASK (0x20U)
#define BRPHY1GV2_TEST_TC10_CONTROL_2_REG1_WAKE_FWD_MDI_CFG_SHIFT (5U)
#define BRPHY1GV2_TEST_TC10_CONTROL_2_REG1_WAKE_BY_WUP_CF_MASK (0x10U)
#define BRPHY1GV2_TEST_TC10_CONTROL_2_REG1_WAKE_BY_WUP_CF_SHIFT (4U)
#define BRPHY1GV2_TEST_TC10_CONTROL_2_REG1_EN_PHY_PRGM_CFG_MASK (0x8U)
#define BRPHY1GV2_TEST_TC10_CONTROL_2_REG1_EN_PHY_PRGM_CFG_SHIFT (3U)
#define BRPHY1GV2_TEST_TC10_CONTROL_2_REG1_DISABLE_IN_CFG_MASK (0x4U)
#define BRPHY1GV2_TEST_TC10_CONTROL_2_REG1_DISABLE_IN_CFG_SHIFT (2U)
#define BRPHY1GV2_TEST_TC10_CONTROL_2_REG1_TC10_SLEEP_MODE_CFG_MASK (0x2U)
#define BRPHY1GV2_TEST_TC10_CONTROL_2_REG1_TC10_SLEEP_MODE_CFG_SHIFT (1U)
#define BRPHY1GV2_TEST_TC10_CONTROL_2_REG1_TC10_GO2STNDBY_CFG_MASK (0x1U)
#define BRPHY1GV2_TEST_TC10_CONTROL_2_REG1_TC10_GO2STNDBY_CFG_SHIFT (0U)




typedef volatile struct sBRPHY1GV2_TEST_RDBType {
    BRPHY1GV2_TEST_RESERVED_TYPE rsvd0[8128]; /* OFFSET: 0x0 */
    BRPHY1GV2_TEST_TC10_CONTROL_REG1_TYPE control_register_1; /* OFFSET: 0x1fc0 */
    BRPHY1GV2_TEST_RESERVED_TYPE rsvd1[2]; /* OFFSET: 0x1fc2 */
    BRPHY1GV2_TEST_TC10_STATUS_REG1_TYPE status_register_1; /* OFFSET: 0x1fc4 */
    BRPHY1GV2_TEST_RESERVED_TYPE rsvd2[2]; /* OFFSET: 0x1fc6 */
    BRPHY1GV2_TEST_TC10_CONTROL_1_REG1_TYPE control_1_register_1; /* OFFSET: 0x1fc8 */
    BRPHY1GV2_TEST_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0x1fca */
    BRPHY1GV2_TEST_TC10_CONTROL_2_REG1_TYPE control_2_register_1; /* OFFSET: 0x1fcc */
    BRPHY1GV2_TEST_RESERVED_TYPE rsvd4[48]; /* OFFSET: 0x1fce */
} BRPHY1GV2_TEST_RDBType;


#define BRPHY0_1G_TEST_BASE             (0xE0566000UL)



#define BRPHY1GV2_TEST_MAX_HW_ID        (1UL)


#define BRPHY1GV2_TEST_TC10_CONTROL_REG1_TC10_CTRL_NORMAL1  (0U )


#define BRPHY1GV2_TEST_TC10_CONTROL_REG1_TC10_CTRL_NORMAL2  (1U )


#define BRPHY1GV2_TEST_TC10_CONTROL_REG1_TC10_CTRL_HOST  (2U )


#define BRPHY1GV2_TEST_TC10_CONTROL_REG1_TC10_CTRL_STANDBY  (3U )


#define BRPHY1GV2_TEST_TC10_CONTROL_REG1_REMOTE_WUP_FAIL_INTR_MASK  (0x0200U)


#define BRPHY1GV2_TEST_TC10_CONTROL_REG1_REMOTE_WUP_INTR_MASK  (0x0100U)


#define BRPHY1GV2_TEST_TC10_CONTROL_REG1_INHIBIT_INTR_MASK  (0x0080U)


#define BRPHY1GV2_TEST_TC10_CONTROL_REG1_SLEEP_FAIL_INTR_MASK  (0x0040U)


#define BRPHY1GV2_TEST_TC10_CONTROL_REG1_SLEEP_INTR_MASK  (0x0020U)


#define BRPHY1GV2_TEST_TC10_CONTROL_REG1_AFE_WUP_INTR_MASK  (0x0010U)


#define BRPHY1GV2_TEST_TC10_STATUS_STATE_AWAKE  (0x4U)


#define BRPHY1GV2_TEST_TC10_STATUS_STATE_SLEEP  (0x6U)

#endif /* BRPHY1GV2_TEST_RDB_H */
