/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file brphy1gv2_afe_rdb.h
    @brief RDB File for BRPHY1GV2_AFE

    @version BCM89580_A0_20230125_RDB
*/

#ifndef BRPHY1GV2_AFE_RDB_H
#define BRPHY1GV2_AFE_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t BRPHY1GV2_AFE_AFE_MISC_CTRL_TYPE;
#define BRPHY1GV2_AFE_AFE_MISC_CTRL_RESERVE_1512_MASK (0xf000U)
#define BRPHY1GV2_AFE_AFE_MISC_CTRL_RESERVE_1512_SHIFT (12U)
#define BRPHY1GV2_AFE_AFE_MISC_CTRL_RDAC_OTP_DIS_MASK (0x800U)
#define BRPHY1GV2_AFE_AFE_MISC_CTRL_RDAC_OTP_DIS_SHIFT (11U)
#define BRPHY1GV2_AFE_AFE_MISC_CTRL_RDAC_EN_MASK (0x400U)
#define BRPHY1GV2_AFE_AFE_MISC_CTRL_RDAC_EN_SHIFT (10U)
#define BRPHY1GV2_AFE_AFE_MISC_CTRL_PASSIVE_TERM_EN_OV_MASK (0x200U)
#define BRPHY1GV2_AFE_AFE_MISC_CTRL_PASSIVE_TERM_EN_OV_SHIFT (9U)
#define BRPHY1GV2_AFE_AFE_MISC_CTRL_PASSIVE_TERM_EN_MASK (0x100U)
#define BRPHY1GV2_AFE_AFE_MISC_CTRL_PASSIVE_TERM_EN_SHIFT (8U)
#define BRPHY1GV2_AFE_AFE_MISC_CTRL_RESET_CAL_OV_MASK (0x80U)
#define BRPHY1GV2_AFE_AFE_MISC_CTRL_RESET_CAL_OV_SHIFT (7U)
#define BRPHY1GV2_AFE_AFE_MISC_CTRL_RESET_CAL_MASK (0x40U)
#define BRPHY1GV2_AFE_AFE_MISC_CTRL_RESET_CAL_SHIFT (6U)
#define BRPHY1GV2_AFE_AFE_MISC_CTRL_RX_PWRDWN_OV_MASK (0x20U)
#define BRPHY1GV2_AFE_AFE_MISC_CTRL_RX_PWRDWN_OV_SHIFT (5U)
#define BRPHY1GV2_AFE_AFE_MISC_CTRL_RX_PWRDWN_MASK (0x10U)
#define BRPHY1GV2_AFE_AFE_MISC_CTRL_RX_PWRDWN_SHIFT (4U)
#define BRPHY1GV2_AFE_AFE_MISC_CTRL_RX_RESETB_OV_MASK (0x8U)
#define BRPHY1GV2_AFE_AFE_MISC_CTRL_RX_RESETB_OV_SHIFT (3U)
#define BRPHY1GV2_AFE_AFE_MISC_CTRL_RX_RESETB_MASK (0x4U)
#define BRPHY1GV2_AFE_AFE_MISC_CTRL_RX_RESETB_SHIFT (2U)
#define BRPHY1GV2_AFE_AFE_MISC_CTRL_TX_PWRDWN_OV_MASK (0x2U)
#define BRPHY1GV2_AFE_AFE_MISC_CTRL_TX_PWRDWN_OV_SHIFT (1U)
#define BRPHY1GV2_AFE_AFE_MISC_CTRL_TX_PWRDWN_MASK (0x1U)
#define BRPHY1GV2_AFE_AFE_MISC_CTRL_TX_PWRDWN_SHIFT (0U)




typedef uint8_t BRPHY1GV2_AFE_RESERVED_TYPE;




typedef uint16_t BRPHY1GV2_AFE_AFE_TXCONFIG_9_PHYX_TYPE;
#define BRPHY1GV2_AFE_AFE_TXCONFIG_9_PHYX_UNUSED_MASK (0xf000U)
#define BRPHY1GV2_AFE_AFE_TXCONFIG_9_PHYX_UNUSED_SHIFT (12U)
#define BRPHY1GV2_AFE_AFE_TXCONFIG_9_PHYX_DIG_PWR_BKOFF_1000T1_MASK (0xc00U)
#define BRPHY1GV2_AFE_AFE_TXCONFIG_9_PHYX_DIG_PWR_BKOFF_1000T1_SHIFT (10U)
#define BRPHY1GV2_AFE_AFE_TXCONFIG_9_PHYX_PBO_VALUE_1000T1_MASK (0x3c0U)
#define BRPHY1GV2_AFE_AFE_TXCONFIG_9_PHYX_PBO_VALUE_1000T1_SHIFT (6U)
#define BRPHY1GV2_AFE_AFE_TXCONFIG_9_PHYX_DIG_PWR_BKOFF_100T1_MASK (0x30U)
#define BRPHY1GV2_AFE_AFE_TXCONFIG_9_PHYX_DIG_PWR_BKOFF_100T1_SHIFT (4U)
#define BRPHY1GV2_AFE_AFE_TXCONFIG_9_PHYX_PBO_VALUE_100T1_ACD_MASK (0xfU)
#define BRPHY1GV2_AFE_AFE_TXCONFIG_9_PHYX_PBO_VALUE_100T1_ACD_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AFE_AFE_TXCONFIG_10_PHYX_TYPE;
#define BRPHY1GV2_AFE_AFE_TXCONFIG_10_PHYX_VALUE_MASK (0xffffU)
#define BRPHY1GV2_AFE_AFE_TXCONFIG_10_PHYX_VALUE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AFE_AFE_TXCONFIG_11_PHYX_TYPE;
#define BRPHY1GV2_AFE_AFE_TXCONFIG_11_PHYX_VALUE_MASK (0xffffU)
#define BRPHY1GV2_AFE_AFE_TXCONFIG_11_PHYX_VALUE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AFE_AFE_RXCONFIG_6_PHYX_TYPE;
#define BRPHY1GV2_AFE_AFE_RXCONFIG_6_PHYX_VALUE_MASK (0xffffU)
#define BRPHY1GV2_AFE_AFE_RXCONFIG_6_PHYX_VALUE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AFE_AFE_RXCONFIG_7_PHYX_TYPE;
#define BRPHY1GV2_AFE_AFE_RXCONFIG_7_PHYX_VALUE_MASK (0xffffU)
#define BRPHY1GV2_AFE_AFE_RXCONFIG_7_PHYX_VALUE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AFE_AFE_PLL_CONFIG0_TYPE;
#define BRPHY1GV2_AFE_AFE_PLL_CONFIG0_VALUE_MASK (0xffffU)
#define BRPHY1GV2_AFE_AFE_PLL_CONFIG0_VALUE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AFE_AFE_PLL_CONFIG1_TYPE;
#define BRPHY1GV2_AFE_AFE_PLL_CONFIG1_VALUE_MASK (0xffffU)
#define BRPHY1GV2_AFE_AFE_PLL_CONFIG1_VALUE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AFE_AFE_PLL_CONFIG2_TYPE;
#define BRPHY1GV2_AFE_AFE_PLL_CONFIG2_VALUE_MASK (0xffffU)
#define BRPHY1GV2_AFE_AFE_PLL_CONFIG2_VALUE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AFE_AFE_PLL_CONFIG3_TYPE;
#define BRPHY1GV2_AFE_AFE_PLL_CONFIG3_VALUE_MASK (0xffffU)
#define BRPHY1GV2_AFE_AFE_PLL_CONFIG3_VALUE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AFE_AFE_PLL_CONFIG4_TYPE;
#define BRPHY1GV2_AFE_AFE_PLL_CONFIG4_VALUE_MASK (0xffffU)
#define BRPHY1GV2_AFE_AFE_PLL_CONFIG4_VALUE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AFE_AFE_PLL_CONFIG5_TYPE;
#define BRPHY1GV2_AFE_AFE_PLL_CONFIG5_VALUE_MASK (0xffffU)
#define BRPHY1GV2_AFE_AFE_PLL_CONFIG5_VALUE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AFE_AFE_PLL_CONFIG11_TYPE;
#define BRPHY1GV2_AFE_AFE_PLL_CONFIG11_VALUE_MASK (0xffffU)
#define BRPHY1GV2_AFE_AFE_PLL_CONFIG11_VALUE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AFE_AFE_PLL_CAL_CONFIG3_TYPE;
#define BRPHY1GV2_AFE_AFE_PLL_CAL_CONFIG3_VALUE_MASK (0xffffU)
#define BRPHY1GV2_AFE_AFE_PLL_CAL_CONFIG3_VALUE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AFE_AFE_PLL_CAL_CONFIG4_TYPE;
#define BRPHY1GV2_AFE_AFE_PLL_CAL_CONFIG4_VALUE_MASK (0xffffU)
#define BRPHY1GV2_AFE_AFE_PLL_CAL_CONFIG4_VALUE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AFE_AFE_PLL_CAL_CONFIG5_TYPE;
#define BRPHY1GV2_AFE_AFE_PLL_CAL_CONFIG5_VALUE_MASK (0xffffU)
#define BRPHY1GV2_AFE_AFE_PLL_CAL_CONFIG5_VALUE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AFE_AFE_PLL_CTRL_TYPE;
#define BRPHY1GV2_AFE_AFE_PLL_CTRL_RESERVED_1512_MASK (0xf000U)
#define BRPHY1GV2_AFE_AFE_PLL_CTRL_RESERVED_1512_SHIFT (12U)
#define BRPHY1GV2_AFE_AFE_PLL_CTRL_PLL_VCO_RESETB_OV_MASK (0x800U)
#define BRPHY1GV2_AFE_AFE_PLL_CTRL_PLL_VCO_RESETB_OV_SHIFT (11U)
#define BRPHY1GV2_AFE_AFE_PLL_CTRL_PLL_VCO_RESETB_MASK (0x400U)
#define BRPHY1GV2_AFE_AFE_PLL_CTRL_PLL_VCO_RESETB_SHIFT (10U)
#define BRPHY1GV2_AFE_AFE_PLL_CTRL_CMOS_REFCLK_EN_OV_MASK (0x200U)
#define BRPHY1GV2_AFE_AFE_PLL_CTRL_CMOS_REFCLK_EN_OV_SHIFT (9U)
#define BRPHY1GV2_AFE_AFE_PLL_CTRL_CMOS_REFCLK_EN_MASK (0x100U)
#define BRPHY1GV2_AFE_AFE_PLL_CTRL_CMOS_REFCLK_EN_SHIFT (8U)
#define BRPHY1GV2_AFE_AFE_PLL_CTRL_CLK_RSTB_OV_MASK (0x80U)
#define BRPHY1GV2_AFE_AFE_PLL_CTRL_CLK_RSTB_OV_SHIFT (7U)
#define BRPHY1GV2_AFE_AFE_PLL_CTRL_CLK_RESET_MASK (0x40U)
#define BRPHY1GV2_AFE_AFE_PLL_CTRL_CLK_RESET_SHIFT (6U)
#define BRPHY1GV2_AFE_AFE_PLL_CTRL_PLL_POWER_ON_OV_MASK (0x20U)
#define BRPHY1GV2_AFE_AFE_PLL_CTRL_PLL_POWER_ON_OV_SHIFT (5U)
#define BRPHY1GV2_AFE_AFE_PLL_CTRL_PLL_POWER_ON_MASK (0x10U)
#define BRPHY1GV2_AFE_AFE_PLL_CTRL_PLL_POWER_ON_SHIFT (4U)
#define BRPHY1GV2_AFE_AFE_PLL_CTRL_PLL_RESETB_OV_MASK (0x8U)
#define BRPHY1GV2_AFE_AFE_PLL_CTRL_PLL_RESETB_OV_SHIFT (3U)
#define BRPHY1GV2_AFE_AFE_PLL_CTRL_PLL_RESETB_MASK (0x4U)
#define BRPHY1GV2_AFE_AFE_PLL_CTRL_PLL_RESETB_SHIFT (2U)
#define BRPHY1GV2_AFE_AFE_PLL_CTRL_PLL_TEST_EN_MASK (0x2U)
#define BRPHY1GV2_AFE_AFE_PLL_CTRL_PLL_TEST_EN_SHIFT (1U)
#define BRPHY1GV2_AFE_AFE_PLL_CTRL_PLLBYP_MASK (0x1U)
#define BRPHY1GV2_AFE_AFE_PLL_CTRL_PLLBYP_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AFE_AFE_BIAS_CONFIG0_TYPE;
#define BRPHY1GV2_AFE_AFE_BIAS_CONFIG0_VALUE_MASK (0xffffU)
#define BRPHY1GV2_AFE_AFE_BIAS_CONFIG0_VALUE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AFE_AFE_BIAS_CONFIG1_TYPE;
#define BRPHY1GV2_AFE_AFE_BIAS_CONFIG1_VALUE_MASK (0xffffU)
#define BRPHY1GV2_AFE_AFE_BIAS_CONFIG1_VALUE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AFE_AFE_BIAS_CONFIG2_TYPE;
#define BRPHY1GV2_AFE_AFE_BIAS_CONFIG2_VALUE_MASK (0xffffU)
#define BRPHY1GV2_AFE_AFE_BIAS_CONFIG2_VALUE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AFE_AFE_BIAS_CONFIG3_TYPE;
#define BRPHY1GV2_AFE_AFE_BIAS_CONFIG3_VALUE_MASK (0xffffU)
#define BRPHY1GV2_AFE_AFE_BIAS_CONFIG3_VALUE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AFE_AFE_CLKGEN_CONFIG2_PHYX_TYPE;
#define BRPHY1GV2_AFE_AFE_CLKGEN_CONFIG2_PHYX_VALUE_MASK (0xffffU)
#define BRPHY1GV2_AFE_AFE_CLKGEN_CONFIG2_PHYX_VALUE_SHIFT (0U)




typedef volatile struct sBRPHY1GV2_AFE_RDBType {
    BRPHY1GV2_AFE_AFE_MISC_CTRL_TYPE misc_ctrl; /* OFFSET: 0x0 */
    BRPHY1GV2_AFE_RESERVED_TYPE rsvd0[38]; /* OFFSET: 0x2 */
    BRPHY1GV2_AFE_AFE_TXCONFIG_9_PHYX_TYPE txconfig_9_phyx; /* OFFSET: 0x28 */
    BRPHY1GV2_AFE_RESERVED_TYPE rsvd1[2]; /* OFFSET: 0x2a */
    BRPHY1GV2_AFE_AFE_TXCONFIG_10_PHYX_TYPE txconfig_10_phyx; /* OFFSET: 0x2c */
    BRPHY1GV2_AFE_RESERVED_TYPE rsvd2[2]; /* OFFSET: 0x2e */
    BRPHY1GV2_AFE_AFE_TXCONFIG_11_PHYX_TYPE txconfig_11_phyx; /* OFFSET: 0x30 */
    BRPHY1GV2_AFE_RESERVED_TYPE rsvd3[106]; /* OFFSET: 0x32 */
    BRPHY1GV2_AFE_AFE_RXCONFIG_6_PHYX_TYPE rxconfig_6_phyx; /* OFFSET: 0x9c */
    BRPHY1GV2_AFE_RESERVED_TYPE rsvd4[2]; /* OFFSET: 0x9e */
    BRPHY1GV2_AFE_AFE_RXCONFIG_7_PHYX_TYPE rxconfig_7_phyx; /* OFFSET: 0xa0 */
    BRPHY1GV2_AFE_RESERVED_TYPE rsvd5[94]; /* OFFSET: 0xa2 */
    BRPHY1GV2_AFE_AFE_PLL_CONFIG0_TYPE pll_config0; /* OFFSET: 0x100 */
    BRPHY1GV2_AFE_RESERVED_TYPE rsvd6[2]; /* OFFSET: 0x102 */
    BRPHY1GV2_AFE_AFE_PLL_CONFIG1_TYPE pll_config1; /* OFFSET: 0x104 */
    BRPHY1GV2_AFE_RESERVED_TYPE rsvd7[2]; /* OFFSET: 0x106 */
    BRPHY1GV2_AFE_AFE_PLL_CONFIG2_TYPE pll_config2; /* OFFSET: 0x108 */
    BRPHY1GV2_AFE_RESERVED_TYPE rsvd8[2]; /* OFFSET: 0x10a */
    BRPHY1GV2_AFE_AFE_PLL_CONFIG3_TYPE pll_config3; /* OFFSET: 0x10c */
    BRPHY1GV2_AFE_RESERVED_TYPE rsvd9[2]; /* OFFSET: 0x10e */
    BRPHY1GV2_AFE_AFE_PLL_CONFIG4_TYPE pll_config4; /* OFFSET: 0x110 */
    BRPHY1GV2_AFE_RESERVED_TYPE rsvd10[2]; /* OFFSET: 0x112 */
    BRPHY1GV2_AFE_AFE_PLL_CONFIG5_TYPE pll_config5; /* OFFSET: 0x114 */
    BRPHY1GV2_AFE_RESERVED_TYPE rsvd11[22]; /* OFFSET: 0x116 */
    BRPHY1GV2_AFE_AFE_PLL_CONFIG11_TYPE pll_config11; /* OFFSET: 0x12c */
    BRPHY1GV2_AFE_RESERVED_TYPE rsvd12[14]; /* OFFSET: 0x12e */
    BRPHY1GV2_AFE_AFE_PLL_CAL_CONFIG3_TYPE pll_cal_config3; /* OFFSET: 0x13c */
    BRPHY1GV2_AFE_RESERVED_TYPE rsvd13[2]; /* OFFSET: 0x13e */
    BRPHY1GV2_AFE_AFE_PLL_CAL_CONFIG4_TYPE pll_cal_config4; /* OFFSET: 0x140 */
    BRPHY1GV2_AFE_RESERVED_TYPE rsvd14[2]; /* OFFSET: 0x142 */
    BRPHY1GV2_AFE_AFE_PLL_CAL_CONFIG5_TYPE pll_cal_config5; /* OFFSET: 0x144 */
    BRPHY1GV2_AFE_RESERVED_TYPE rsvd15[2]; /* OFFSET: 0x146 */
    BRPHY1GV2_AFE_AFE_PLL_CTRL_TYPE pll_ctrl; /* OFFSET: 0x148 */
    BRPHY1GV2_AFE_RESERVED_TYPE rsvd16[22]; /* OFFSET: 0x14a */
    BRPHY1GV2_AFE_AFE_BIAS_CONFIG0_TYPE bias_config0; /* OFFSET: 0x160 */
    BRPHY1GV2_AFE_RESERVED_TYPE rsvd17[2]; /* OFFSET: 0x162 */
    BRPHY1GV2_AFE_AFE_BIAS_CONFIG1_TYPE bias_config1; /* OFFSET: 0x164 */
    BRPHY1GV2_AFE_RESERVED_TYPE rsvd18[2]; /* OFFSET: 0x166 */
    BRPHY1GV2_AFE_AFE_BIAS_CONFIG2_TYPE bias_config2; /* OFFSET: 0x168 */
    BRPHY1GV2_AFE_RESERVED_TYPE rsvd19[2]; /* OFFSET: 0x16a */
    BRPHY1GV2_AFE_AFE_BIAS_CONFIG3_TYPE bias_config3; /* OFFSET: 0x16c */
    BRPHY1GV2_AFE_RESERVED_TYPE rsvd20[38]; /* OFFSET: 0x16e */
    BRPHY1GV2_AFE_AFE_CLKGEN_CONFIG2_PHYX_TYPE clkgen_config2_phyx; /* OFFSET: 0x194 */
    BRPHY1GV2_AFE_RESERVED_TYPE rsvd21[104]; /* OFFSET: 0x196 */
} BRPHY1GV2_AFE_RDBType;


#define BRPHY0_1G_AFE_1000T1_BASE       (0xE0570000UL)



#define BRPHY1GV2_AFE_MAX_HW_ID         (1UL)


#define ENABLE_BRPHY1G_AFE_CONFIG       (0x1UL)


#define BRPHY1GV2_BIAS_CONFIG2_VAL0     (0x8039U)


#define BRPHY1GV2_BIAS_CONFIG2_VAL1     (0x0039U)


#define BRPHY1GV2_AFE_TXCONFIG_9_PHYX_VAL  (0x0189U)


#define BRPHY1GV2_PLL_CONFIG5           (0x6B02U)


#define BRPHY1GV2_PLL_CONFIG0           (0x34E0U)


#define BRPHY1GV2_PLL_CONFIG11          (0x0004U)


#define BRPHY1GV2_0_AFE_BASE            (BRPHY0_1G_AFE_1000T1_BASE)


#define BRPHY1GV2_3_AFE_CONST1          (0xC000U)


#define BRPHY1GV2_3_AFE_CONST2          (0x0007U)


#define BRPHY1GV2_3_AFE_CONST3          (0x2088U)


#define BRPHY1GV2_3_AFE_CONST4          (0x8039U)


#define BRPHY1GV2_3_AFE_CONST5          (0xEC6FU)


#define BRPHY1GV2_3_AFE_CONST6          (0xEC6BU)


#define BRPHY1GV2_AFE_CLKGEN_CONFIG2_PHYX_CONST1  (0x1401U)


#define BRPHY1GV2_AFE_CLKGEN_CONFIG2_PHYX_CONST2  (0x1441U)


#define BRPHY1GV2_AFE_RXCONFIG_6_PHYX_CONST  (0xC208U)


#define BRPHY1GV2_AFE_RXCONFIG_7_PHYX_CONST  (0x000U)

#endif /* BRPHY1GV2_AFE_RDB_H */
