/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file brphy1gv2_acd_rdb.h
    @brief RDB File for BRPHY1GV2_ACD

    @version BCM89580_A0_20230125_RDB
*/

#ifndef BRPHY1GV2_ACD_RDB_H
#define BRPHY1GV2_ACD_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t BRPHY1GV2_ACD_EXPC0_TYPE;
#define BRPHY1GV2_ACD_EXPC0_RUN_IMMEDIATE_MASK (0x8000U)
#define BRPHY1GV2_ACD_EXPC0_RUN_IMMEDIATE_SHIFT (15U)
#define BRPHY1GV2_ACD_EXPC0_RUN_AT_AUTONEG_MASK (0x4000U)
#define BRPHY1GV2_ACD_EXPC0_RUN_AT_AUTONEG_SHIFT (14U)
#define BRPHY1GV2_ACD_EXPC0_INTER_PAIR_SHORT_DIS_MASK (0x2000U)
#define BRPHY1GV2_ACD_EXPC0_INTER_PAIR_SHORT_DIS_SHIFT (13U)
#define BRPHY1GV2_ACD_EXPC0_BREAK_LINK_MASK (0x1000U)
#define BRPHY1GV2_ACD_EXPC0_BREAK_LINK_SHIFT (12U)
#define BRPHY1GV2_ACD_EXPC0_CABLE_DIAG_STATUS_MASK (0x800U)
#define BRPHY1GV2_ACD_EXPC0_CABLE_DIAG_STATUS_SHIFT (11U)
#define BRPHY1GV2_ACD_EXPC0_CABLE_LEN_UNIT_MASK (0x400U)
#define BRPHY1GV2_ACD_EXPC0_CABLE_LEN_UNIT_SHIFT (10U)
#define BRPHY1GV2_ACD_EXPC0_ACD_MODE_ENABLE_MASK (0x200U)
#define BRPHY1GV2_ACD_EXPC0_ACD_MODE_ENABLE_SHIFT (9U)
#define BRPHY1GV2_ACD_EXPC0_FAST_TIMER_ENABLE_MASK (0x100U)
#define BRPHY1GV2_ACD_EXPC0_FAST_TIMER_ENABLE_SHIFT (8U)
#define BRPHY1GV2_ACD_EXPC0_INTRPT_ENABLE_MASK (0x80U)
#define BRPHY1GV2_ACD_EXPC0_INTRPT_ENABLE_SHIFT (7U)
#define BRPHY1GV2_ACD_EXPC0_STOP_PLL_CLK_MASK (0x40U)
#define BRPHY1GV2_ACD_EXPC0_STOP_PLL_CLK_SHIFT (6U)
#define BRPHY1GV2_ACD_EXPC0_TEST_ACD_DC_OFFSET_MASK (0x10U)
#define BRPHY1GV2_ACD_EXPC0_TEST_ACD_DC_OFFSET_SHIFT (4U)
#define BRPHY1GV2_ACD_EXPC0_INVALID_RESULT_MASK (0x8U)
#define BRPHY1GV2_ACD_EXPC0_INVALID_RESULT_SHIFT (3U)
#define BRPHY1GV2_ACD_EXPC0_CABLE_DIAG_EXE_MASK (0x4U)
#define BRPHY1GV2_ACD_EXPC0_CABLE_DIAG_EXE_SHIFT (2U)
#define BRPHY1GV2_ACD_EXPC0_AUTO_RUN_FOR_BROKEN_ANG_MASK (0x2U)
#define BRPHY1GV2_ACD_EXPC0_AUTO_RUN_FOR_BROKEN_ANG_SHIFT (1U)
#define BRPHY1GV2_ACD_EXPC0_CABLE_TYPE_MASK (0x1U)
#define BRPHY1GV2_ACD_EXPC0_CABLE_TYPE_SHIFT (0U)




typedef uint8_t BRPHY1GV2_ACD_RESERVED_TYPE;




typedef uint16_t BRPHY1GV2_ACD_EXPC1_TYPE;
#define BRPHY1GV2_ACD_EXPC1_PA_CD_CODE_MASK (0xf000U)
#define BRPHY1GV2_ACD_EXPC1_PA_CD_CODE_SHIFT (12U)
#define BRPHY1GV2_ACD_EXPC1_PB_CD_CODE_MASK (0xf00U)
#define BRPHY1GV2_ACD_EXPC1_PB_CD_CODE_SHIFT (8U)
#define BRPHY1GV2_ACD_EXPC1_PC_CD_CODE_MASK (0xf0U)
#define BRPHY1GV2_ACD_EXPC1_PC_CD_CODE_SHIFT (4U)
#define BRPHY1GV2_ACD_EXPC1_PD_CD_CODE_MASK (0xfU)
#define BRPHY1GV2_ACD_EXPC1_PD_CD_CODE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ACD_EXPC2_TYPE;
#define BRPHY1GV2_ACD_EXPC2_LENGTH_INDICATION_MASK (0xffffU)
#define BRPHY1GV2_ACD_EXPC2_LENGTH_INDICATION_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ACD_EXPC3_TYPE;
#define BRPHY1GV2_ACD_EXPC3_LENGTH_INDICATION_MASK (0xffffU)
#define BRPHY1GV2_ACD_EXPC3_LENGTH_INDICATION_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ACD_EXPC4_TYPE;
#define BRPHY1GV2_ACD_EXPC4_LENGTH_INDICATION_MASK (0xffffU)
#define BRPHY1GV2_ACD_EXPC4_LENGTH_INDICATION_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ACD_EXPC5_TYPE;
#define BRPHY1GV2_ACD_EXPC5_LENGTH_INDICATION_MASK (0xffffU)
#define BRPHY1GV2_ACD_EXPC5_LENGTH_INDICATION_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ACD_EXPC6_TYPE;
#define BRPHY1GV2_ACD_EXPC6_F_COUNT_0_MASK (0xffffU)
#define BRPHY1GV2_ACD_EXPC6_F_COUNT_0_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ACD_EXPC7_TYPE;
#define BRPHY1GV2_ACD_EXPC7_UNDEFINED_MASK (0xffffU)
#define BRPHY1GV2_ACD_EXPC7_UNDEFINED_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ACD_EXPC8_TYPE;
#define BRPHY1GV2_ACD_EXPC8_UNDEFINED_MASK (0xffffU)
#define BRPHY1GV2_ACD_EXPC8_UNDEFINED_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ACD_EXPC9_TYPE;
#define BRPHY1GV2_ACD_EXPC9_UNDEFINED_MASK (0xffffU)
#define BRPHY1GV2_ACD_EXPC9_UNDEFINED_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ACD_EXPCA_TYPE;
#define BRPHY1GV2_ACD_EXPCA_UNDEFINED_MASK (0xffffU)
#define BRPHY1GV2_ACD_EXPCA_UNDEFINED_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ACD_EXPCB_TYPE;
#define BRPHY1GV2_ACD_EXPCB_UNDEFINED_MASK (0xffffU)
#define BRPHY1GV2_ACD_EXPCB_UNDEFINED_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ACD_EXPCC_TYPE;
#define BRPHY1GV2_ACD_EXPCC_UNDEFINED_MASK (0xffffU)
#define BRPHY1GV2_ACD_EXPCC_UNDEFINED_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ACD_EXPCD_TYPE;
#define BRPHY1GV2_ACD_EXPCD_UNDEFINED_MASK (0xffffU)
#define BRPHY1GV2_ACD_EXPCD_UNDEFINED_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ACD_EXPCE_TYPE;
#define BRPHY1GV2_ACD_EXPCE_UNDEFINED_MASK (0xffffU)
#define BRPHY1GV2_ACD_EXPCE_UNDEFINED_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ACD_EXPCF_TYPE;
#define BRPHY1GV2_ACD_EXPCF_UNDEFINED_MASK (0xffffU)
#define BRPHY1GV2_ACD_EXPCF_UNDEFINED_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ACD_EXPE0_TYPE;
#define BRPHY1GV2_ACD_EXPE0_UNDEFINED_MASK (0xffffU)
#define BRPHY1GV2_ACD_EXPE0_UNDEFINED_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ACD_EXPE1_TYPE;
#define BRPHY1GV2_ACD_EXPE1_UNDEFINED_MASK (0xffffU)
#define BRPHY1GV2_ACD_EXPE1_UNDEFINED_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ACD_EXPE2_TYPE;
#define BRPHY1GV2_ACD_EXPE2_UNDEFINED_MASK (0xffffU)
#define BRPHY1GV2_ACD_EXPE2_UNDEFINED_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ACD_EXPE3_TYPE;
#define BRPHY1GV2_ACD_EXPE3_UNDEFINED_MASK (0xffffU)
#define BRPHY1GV2_ACD_EXPE3_UNDEFINED_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ACD_EXPE4_TYPE;
#define BRPHY1GV2_ACD_EXPE4_UNDEFINED_MASK (0xffffU)
#define BRPHY1GV2_ACD_EXPE4_UNDEFINED_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ACD_EXPE5_TYPE;
#define BRPHY1GV2_ACD_EXPE5_UNDEFINED_MASK (0xffffU)
#define BRPHY1GV2_ACD_EXPE5_UNDEFINED_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ACD_EXPE6_TYPE;
#define BRPHY1GV2_ACD_EXPE6_UNDEFINED_MASK (0xffffU)
#define BRPHY1GV2_ACD_EXPE6_UNDEFINED_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ACD_EXPE7_TYPE;
#define BRPHY1GV2_ACD_EXPE7_UNDEFINED_MASK (0xffffU)
#define BRPHY1GV2_ACD_EXPE7_UNDEFINED_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ACD_EXPE8_TYPE;
#define BRPHY1GV2_ACD_EXPE8_UNDEFINED_MASK (0xffffU)
#define BRPHY1GV2_ACD_EXPE8_UNDEFINED_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ACD_EXPE9_TYPE;
#define BRPHY1GV2_ACD_EXPE9_UNDEFINED_MASK (0xffffU)
#define BRPHY1GV2_ACD_EXPE9_UNDEFINED_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ACD_EXPEA_TYPE;
#define BRPHY1GV2_ACD_EXPEA_UNDEFINED_MASK (0xffffU)
#define BRPHY1GV2_ACD_EXPEA_UNDEFINED_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ACD_EXPEB_TYPE;
#define BRPHY1GV2_ACD_EXPEB_UNDEFINED_MASK (0xffffU)
#define BRPHY1GV2_ACD_EXPEB_UNDEFINED_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ACD_EXPEC_TYPE;
#define BRPHY1GV2_ACD_EXPEC_UNDEFINED_MASK (0xffffU)
#define BRPHY1GV2_ACD_EXPEC_UNDEFINED_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ACD_EXPED_TYPE;
#define BRPHY1GV2_ACD_EXPED_UNDEFINED_MASK (0xffffU)
#define BRPHY1GV2_ACD_EXPED_UNDEFINED_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ACD_EXPEE_TYPE;
#define BRPHY1GV2_ACD_EXPEE_UNDEFINED_MASK (0xffffU)
#define BRPHY1GV2_ACD_EXPEE_UNDEFINED_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ACD_EXPEF_TYPE;
#define BRPHY1GV2_ACD_EXPEF_UNDEFINED_MASK (0xffffU)
#define BRPHY1GV2_ACD_EXPEF_UNDEFINED_SHIFT (0U)




typedef volatile struct sBRPHY1GV2_ACD_RDBType {
    BRPHY1GV2_ACD_EXPC0_TYPE expc0; /* OFFSET: 0x0 */
    BRPHY1GV2_ACD_RESERVED_TYPE rsvd0[2]; /* OFFSET: 0x2 */
    BRPHY1GV2_ACD_EXPC1_TYPE expc1; /* OFFSET: 0x4 */
    BRPHY1GV2_ACD_RESERVED_TYPE rsvd1[2]; /* OFFSET: 0x6 */
    BRPHY1GV2_ACD_EXPC2_TYPE expc2; /* OFFSET: 0x8 */
    BRPHY1GV2_ACD_RESERVED_TYPE rsvd2[2]; /* OFFSET: 0xa */
    BRPHY1GV2_ACD_EXPC3_TYPE expc3; /* OFFSET: 0xc */
    BRPHY1GV2_ACD_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0xe */
    BRPHY1GV2_ACD_EXPC4_TYPE expc4; /* OFFSET: 0x10 */
    BRPHY1GV2_ACD_RESERVED_TYPE rsvd4[2]; /* OFFSET: 0x12 */
    BRPHY1GV2_ACD_EXPC5_TYPE expc5; /* OFFSET: 0x14 */
    BRPHY1GV2_ACD_RESERVED_TYPE rsvd5[2]; /* OFFSET: 0x16 */
    BRPHY1GV2_ACD_EXPC6_TYPE expc6; /* OFFSET: 0x18 */
    BRPHY1GV2_ACD_RESERVED_TYPE rsvd6[2]; /* OFFSET: 0x1a */
    BRPHY1GV2_ACD_EXPC7_TYPE expc7; /* OFFSET: 0x1c */
    BRPHY1GV2_ACD_RESERVED_TYPE rsvd7[2]; /* OFFSET: 0x1e */
    BRPHY1GV2_ACD_EXPC8_TYPE expc8; /* OFFSET: 0x20 */
    BRPHY1GV2_ACD_RESERVED_TYPE rsvd8[2]; /* OFFSET: 0x22 */
    BRPHY1GV2_ACD_EXPC9_TYPE expc9; /* OFFSET: 0x24 */
    BRPHY1GV2_ACD_RESERVED_TYPE rsvd9[2]; /* OFFSET: 0x26 */
    BRPHY1GV2_ACD_EXPCA_TYPE expca; /* OFFSET: 0x28 */
    BRPHY1GV2_ACD_RESERVED_TYPE rsvd10[2]; /* OFFSET: 0x2a */
    BRPHY1GV2_ACD_EXPCB_TYPE expcb; /* OFFSET: 0x2c */
    BRPHY1GV2_ACD_RESERVED_TYPE rsvd11[2]; /* OFFSET: 0x2e */
    BRPHY1GV2_ACD_EXPCC_TYPE expcc; /* OFFSET: 0x30 */
    BRPHY1GV2_ACD_RESERVED_TYPE rsvd12[2]; /* OFFSET: 0x32 */
    BRPHY1GV2_ACD_EXPCD_TYPE expcd; /* OFFSET: 0x34 */
    BRPHY1GV2_ACD_RESERVED_TYPE rsvd13[2]; /* OFFSET: 0x36 */
    BRPHY1GV2_ACD_EXPCE_TYPE expce; /* OFFSET: 0x38 */
    BRPHY1GV2_ACD_RESERVED_TYPE rsvd14[2]; /* OFFSET: 0x3a */
    BRPHY1GV2_ACD_EXPCF_TYPE expcf; /* OFFSET: 0x3c */
    BRPHY1GV2_ACD_RESERVED_TYPE rsvd15[2]; /* OFFSET: 0x3e */
    BRPHY1GV2_ACD_EXPE0_TYPE expe0; /* OFFSET: 0x40 */
    BRPHY1GV2_ACD_RESERVED_TYPE rsvd16[2]; /* OFFSET: 0x42 */
    BRPHY1GV2_ACD_EXPE1_TYPE expe1; /* OFFSET: 0x44 */
    BRPHY1GV2_ACD_RESERVED_TYPE rsvd17[2]; /* OFFSET: 0x46 */
    BRPHY1GV2_ACD_EXPE2_TYPE expe2; /* OFFSET: 0x48 */
    BRPHY1GV2_ACD_RESERVED_TYPE rsvd18[2]; /* OFFSET: 0x4a */
    BRPHY1GV2_ACD_EXPE3_TYPE expe3; /* OFFSET: 0x4c */
    BRPHY1GV2_ACD_RESERVED_TYPE rsvd19[2]; /* OFFSET: 0x4e */
    BRPHY1GV2_ACD_EXPE4_TYPE expe4; /* OFFSET: 0x50 */
    BRPHY1GV2_ACD_RESERVED_TYPE rsvd20[2]; /* OFFSET: 0x52 */
    BRPHY1GV2_ACD_EXPE5_TYPE expe5; /* OFFSET: 0x54 */
    BRPHY1GV2_ACD_RESERVED_TYPE rsvd21[2]; /* OFFSET: 0x56 */
    BRPHY1GV2_ACD_EXPE6_TYPE expe6; /* OFFSET: 0x58 */
    BRPHY1GV2_ACD_RESERVED_TYPE rsvd22[2]; /* OFFSET: 0x5a */
    BRPHY1GV2_ACD_EXPE7_TYPE expe7; /* OFFSET: 0x5c */
    BRPHY1GV2_ACD_RESERVED_TYPE rsvd23[2]; /* OFFSET: 0x5e */
    BRPHY1GV2_ACD_EXPE8_TYPE expe8; /* OFFSET: 0x60 */
    BRPHY1GV2_ACD_RESERVED_TYPE rsvd24[2]; /* OFFSET: 0x62 */
    BRPHY1GV2_ACD_EXPE9_TYPE expe9; /* OFFSET: 0x64 */
    BRPHY1GV2_ACD_RESERVED_TYPE rsvd25[2]; /* OFFSET: 0x66 */
    BRPHY1GV2_ACD_EXPEA_TYPE expea; /* OFFSET: 0x68 */
    BRPHY1GV2_ACD_RESERVED_TYPE rsvd26[2]; /* OFFSET: 0x6a */
    BRPHY1GV2_ACD_EXPEB_TYPE expeb; /* OFFSET: 0x6c */
    BRPHY1GV2_ACD_RESERVED_TYPE rsvd27[2]; /* OFFSET: 0x6e */
    BRPHY1GV2_ACD_EXPEC_TYPE expec; /* OFFSET: 0x70 */
    BRPHY1GV2_ACD_RESERVED_TYPE rsvd28[2]; /* OFFSET: 0x72 */
    BRPHY1GV2_ACD_EXPED_TYPE exped; /* OFFSET: 0x74 */
    BRPHY1GV2_ACD_RESERVED_TYPE rsvd29[2]; /* OFFSET: 0x76 */
    BRPHY1GV2_ACD_EXPEE_TYPE expee; /* OFFSET: 0x78 */
    BRPHY1GV2_ACD_RESERVED_TYPE rsvd30[2]; /* OFFSET: 0x7a */
    BRPHY1GV2_ACD_EXPEF_TYPE expef; /* OFFSET: 0x7c */
} BRPHY1GV2_ACD_RDBType;


#define BRPHY0_1G_ACD_BASE              (0xE0565C00UL)



#define BRPHY1GV2_ACD_MAX_HW_ID         (1UL)


#define BRPHY1GV2_ACD_STATUS_INVALID    (0U )


#define BRPHY1GV2_ACD_STATUS_NOFAULT    (1U )


#define BRPHY1GV2_ACD_STATUS_OPEN       (2U )


#define BRPHY1GV2_ACD_STATUS_SHORT      (3U )


#define BRPHY1GV2_ACD_STATUS_PIN_SHORT_OR_XT  (4U )


#define BRPHY1GV2_ACD_STATUS_FORCED     (9U )


#define BRPHY1GV2_ACD_WAIT_LOOP_TIME    (0xB0000UL)


#define BRPHY1GV2_ACD_LF_100            (100UL)


#define BRPHY1GV2_ACD_LF_1              (1UL)


#define BRPHY1GV2_ACD_PEAKAMPLITUDE_SCALE  (400UL)


#define BRPHY1GV2_ACD_OPENTHRESHOLD_112_400  (44800UL)


#define BRPHY1GV2_ACD_OPENTHRESHOLD_100_400  (40000UL)


#define BRPHY1GV2_ACD_OPENTHRESHOLD_N_LIMIT  (12UL)


#define BRPHY1GV2_ACD_OPENTHRESHOLD_117_400  (46800UL)


#define BRPHY1GV2_ACD_OPENTHRESHOLD_102_400  (40800UL)


#define BRPHY1GV2_ACD_OPENTHRESHOLD_2_5_400  (1000UL)


#define BRPHY1GV2_ACD_OPENTHRESHOLD_1_535_400  (614UL)


#define BRPHY1GV2_ACD_OPENTHRESHOLD_118_400  (47200UL)


#define BRPHY1GV2_ACD_CONST_SCALE_DEFAULT  (256UL)


#define BRPHY1GV2_ACD_CONST_A_CB0_DEFAULT  (207UL)


#define BRPHY1GV2_ACD_CONST_B_CB0_DEFAULT  (0UL)


#define BRPHY1GV2_ACD_CONST_C_CB0_DEFAULT  (410UL)


#define BRPHY1GV2_ACD_CONST_A_CB0_OPEN_DEFAULT  (198UL)


#define BRPHY1GV2_ACD_CONST_B_CB0_OPEN_DEFAULT  (0UL)


#define BRPHY1GV2_ACD_CONST_C_CB0_OPEN_DEFAULT  (422UL)


#define BRPHY1GV2_ACD_CONST_A_CB0_LP0_OPEN_GOOD  (192UL)


#define BRPHY1GV2_ACD_CONST_B_CB0_LP0_OPEN_GOOD  (0UL)


#define BRPHY1GV2_ACD_CONST_C_CB0_LP0_OPEN_GOOD  (493UL)


#define BRPHY1GV2_ACD_CONST_A_CB0_LP1_OPEN_GOOD  (209UL)


#define BRPHY1GV2_ACD_CONST_B_CB0_LP1_OPEN_GOOD  (0UL)


#define BRPHY1GV2_ACD_CONST_C_CB0_LP1_OPEN_GOOD  (1264UL)


#define BRPHY1GV2_ACD_CONST_A_CB0_SHORT  (194UL)


#define BRPHY1GV2_ACD_CONST_B_CB0_SHORT  (0UL)


#define BRPHY1GV2_ACD_CONST_C_CB0_SHORT  (397UL)


#define BRPHY1GV2_ACD_CONST_A_CB1_DEFAULT  (206UL)


#define BRPHY1GV2_ACD_CONST_B_CB1_DEFAULT  (0UL)


#define BRPHY1GV2_ACD_CONST_C_CB1_DEFAULT  (619UL)


#define BRPHY1GV2_ACD_CONST_A_CB1_OPEN_DEFAULT  (199UL)


#define BRPHY1GV2_ACD_CONST_B_CB1_OPEN_DEFAULT  (634UL)


#define BRPHY1GV2_ACD_CONST_C_CB1_OPEN_DEFAULT  (0UL)


#define BRPHY1GV2_ACD_CONST_A_CB1_LP0_OPEN_GOOD  (203UL)


#define BRPHY1GV2_ACD_CONST_B_CB1_LP0_OPEN_GOOD  (853UL)


#define BRPHY1GV2_ACD_CONST_C_CB1_LP0_OPEN_GOOD  (0UL)


#define BRPHY1GV2_ACD_CONST_A_CB1_LP1_OPEN_GOOD  (204UL)


#define BRPHY1GV2_ACD_CONST_B_CB1_LP1_OPEN_GOOD  (1027UL)


#define BRPHY1GV2_ACD_CONST_C_CB1_LP1_OPEN_GOOD  (165UL)


#define BRPHY1GV2_ACD_CONST_A_CB1_SHORT  (205UL)


#define BRPHY1GV2_ACD_CONST_B_CB1_SHORT  (750UL)


#define BRPHY1GV2_ACD_CONST_C_CB1_SHORT  (0UL)

#endif /* BRPHY1GV2_ACD_RDB_H */
