/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file brphy1gv2_pcs_rdb.h
    @brief RDB File for BRPHY1GV2_PCS

    @version BCM89580_A0_20230125_RDB
*/

#ifndef BRPHY1GV2_PCS_RDB_H
#define BRPHY1GV2_PCS_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t BRPHY1GV2_PCS_EXP90_TYPE;
#define BRPHY1GV2_PCS_EXP90_JABBER_DET_MASK (0x8000U)
#define BRPHY1GV2_PCS_EXP90_JABBER_DET_SHIFT (15U)
#define BRPHY1GV2_PCS_EXP90_BR_SCR_STATUS_MASK (0x6000U)
#define BRPHY1GV2_PCS_EXP90_BR_SCR_STATUS_SHIFT (13U)
#define BRPHY1GV2_PCS_EXP90_BR_ALIGN_STATE_MASK (0x1c00U)
#define BRPHY1GV2_PCS_EXP90_BR_ALIGN_STATE_SHIFT (10U)
#define BRPHY1GV2_PCS_EXP90_BR_RX_STATE_MASK (0x3c0U)
#define BRPHY1GV2_PCS_EXP90_BR_RX_STATE_SHIFT (6U)
#define BRPHY1GV2_PCS_EXP90_BR_PCS_STATE_MASK (0x3cU)
#define BRPHY1GV2_PCS_EXP90_BR_PCS_STATE_SHIFT (2U)
#define BRPHY1GV2_PCS_EXP90_BR_FORCE_LINK_CTL_MASK (0x2U)
#define BRPHY1GV2_PCS_EXP90_BR_FORCE_LINK_CTL_SHIFT (1U)
#define BRPHY1GV2_PCS_EXP90_BR_EN_MASK (0x1U)
#define BRPHY1GV2_PCS_EXP90_BR_EN_SHIFT (0U)




typedef uint8_t BRPHY1GV2_PCS_RESERVED_TYPE;




typedef uint16_t BRPHY1GV2_PCS_EXP91_TYPE;
#define BRPHY1GV2_PCS_EXP91_BR_N_TOGGLE_DIS_OV_MASK (0x4000U)
#define BRPHY1GV2_PCS_EXP91_BR_N_TOGGLE_DIS_OV_SHIFT (14U)
#define BRPHY1GV2_PCS_EXP91_PAIR_CFG_MASK (0xc0U)
#define BRPHY1GV2_PCS_EXP91_PAIR_CFG_SHIFT (6U)
#define BRPHY1GV2_PCS_EXP91_UNIDIR_AB_MASK (0x20U)
#define BRPHY1GV2_PCS_EXP91_UNIDIR_AB_SHIFT (5U)
#define BRPHY1GV2_PCS_EXP91_UNIDIR_EN_MASK (0x10U)
#define BRPHY1GV2_PCS_EXP91_UNIDIR_EN_SHIFT (4U)
#define BRPHY1GV2_PCS_EXP91_BR_N_TOGGLE_DIS_OV_VAL_MASK (0x4U)
#define BRPHY1GV2_PCS_EXP91_BR_N_TOGGLE_DIS_OV_VAL_SHIFT (2U)
#define BRPHY1GV2_PCS_EXP91_TXSCR_ZERO_SEED_MASK (0x2U)
#define BRPHY1GV2_PCS_EXP91_TXSCR_ZERO_SEED_SHIFT (1U)
#define BRPHY1GV2_PCS_EXP91_RXSCR_ZERO_SEED_MASK (0x1U)
#define BRPHY1GV2_PCS_EXP91_RXSCR_ZERO_SEED_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PCS_EXP92_TYPE;
#define BRPHY1GV2_PCS_EXP92_DLLCONV_OV_EN_MASK (0x8000U)
#define BRPHY1GV2_PCS_EXP92_DLLCONV_OV_EN_SHIFT (15U)
#define BRPHY1GV2_PCS_EXP92_DLLCONV_OV_VAL_MASK (0x4000U)
#define BRPHY1GV2_PCS_EXP92_DLLCONV_OV_VAL_SHIFT (14U)
#define BRPHY1GV2_PCS_EXP92_BR_SLAVE_POL_COR_EN_MASK (0x2000U)
#define BRPHY1GV2_PCS_EXP92_BR_SLAVE_POL_COR_EN_SHIFT (13U)
#define BRPHY1GV2_PCS_EXP92_BR_EDGE_RATE_SEL_MASK (0x1800U)
#define BRPHY1GV2_PCS_EXP92_BR_EDGE_RATE_SEL_SHIFT (11U)
#define BRPHY1GV2_PCS_EXP92_BR_PCS_RRNOK_POL_EN_MASK (0x400U)
#define BRPHY1GV2_PCS_EXP92_BR_PCS_RRNOK_POL_EN_SHIFT (10U)
#define BRPHY1GV2_PCS_EXP92_REM_RCV_2NDPCS_DET_MASK (0x200U)
#define BRPHY1GV2_PCS_EXP92_REM_RCV_2NDPCS_DET_SHIFT (9U)
#define BRPHY1GV2_PCS_EXP92_BR_PCS_POL_EN_MASK (0x100U)
#define BRPHY1GV2_PCS_EXP92_BR_PCS_POL_EN_SHIFT (8U)
#define BRPHY1GV2_PCS_EXP92_JAB_MON_DIS_MASK (0x80U)
#define BRPHY1GV2_PCS_EXP92_JAB_MON_DIS_SHIFT (7U)
#define BRPHY1GV2_PCS_EXP92_BR_AGCSID_TMR_EN_MASK (0x40U)
#define BRPHY1GV2_PCS_EXP92_BR_AGCSID_TMR_EN_SHIFT (6U)
#define BRPHY1GV2_PCS_EXP92_BR_SYM_XSCR_EN_MASK (0x20U)
#define BRPHY1GV2_PCS_EXP92_BR_SYM_XSCR_EN_SHIFT (5U)
#define BRPHY1GV2_PCS_EXP92_CHK_DELIMITER_MASK (0x10U)
#define BRPHY1GV2_PCS_EXP92_CHK_DELIMITER_SHIFT (4U)
#define BRPHY1GV2_PCS_EXP92_TX_READ_DLY_MASK (0xcU)
#define BRPHY1GV2_PCS_EXP92_TX_READ_DLY_SHIFT (2U)
#define BRPHY1GV2_PCS_EXP92_RX_READ_DLY_MASK (0x3U)
#define BRPHY1GV2_PCS_EXP92_RX_READ_DLY_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PCS_EXP93_TYPE;
#define BRPHY1GV2_PCS_EXP93_RESERVED_MASK (0xe000U)
#define BRPHY1GV2_PCS_EXP93_RESERVED_SHIFT (13U)
#define BRPHY1GV2_PCS_EXP93_COUNT4_LPSWURIDLE_MASK (0x1000U)
#define BRPHY1GV2_PCS_EXP93_COUNT4_LPSWURIDLE_SHIFT (12U)
#define BRPHY1GV2_PCS_EXP93_PMS_RX_BLOCK_DIS_MASK (0x800U)
#define BRPHY1GV2_PCS_EXP93_PMS_RX_BLOCK_DIS_SHIFT (11U)
#define BRPHY1GV2_PCS_EXP93_CONTI_LPS_DIS_MASK (0x400U)
#define BRPHY1GV2_PCS_EXP93_CONTI_LPS_DIS_SHIFT (10U)
#define BRPHY1GV2_PCS_EXP93_TX_LPS_WUR_OPT_MASK (0x300U)
#define BRPHY1GV2_PCS_EXP93_TX_LPS_WUR_OPT_SHIFT (8U)
#define BRPHY1GV2_PCS_EXP93_SEND_Z_DET_OPT_MASK (0xc0U)
#define BRPHY1GV2_PCS_EXP93_SEND_Z_DET_OPT_SHIFT (6U)
#define BRPHY1GV2_PCS_EXP93_TX_CHANNEL_DISABLE_AB_MASK (0x30U)
#define BRPHY1GV2_PCS_EXP93_TX_CHANNEL_DISABLE_AB_SHIFT (4U)
#define BRPHY1GV2_PCS_EXP93_COUNT16_LPSIDLE_MASK (0x8U)
#define BRPHY1GV2_PCS_EXP93_COUNT16_LPSIDLE_SHIFT (3U)
#define BRPHY1GV2_PCS_EXP93_PACKET_SIZE_MASK (0x4U)
#define BRPHY1GV2_PCS_EXP93_PACKET_SIZE_SHIFT (2U)
#define BRPHY1GV2_PCS_EXP93_SCRAMBLER_TEST_MASK (0x2U)
#define BRPHY1GV2_PCS_EXP93_SCRAMBLER_TEST_SHIFT (1U)
#define BRPHY1GV2_PCS_EXP93_PMS_FASTSIM_MODE_MASK (0x1U)
#define BRPHY1GV2_PCS_EXP93_PMS_FASTSIM_MODE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PCS_EXP94_TYPE;
#define BRPHY1GV2_PCS_EXP94_RESERVED_MASK (0xffffU)
#define BRPHY1GV2_PCS_EXP94_RESERVED_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PCS_EXP95_TYPE;
#define BRPHY1GV2_PCS_EXP95_RESERVED_MASK (0xfffcU)
#define BRPHY1GV2_PCS_EXP95_RESERVED_SHIFT (2U)
#define BRPHY1GV2_PCS_EXP95_EN_ESD2_FIX_MASK (0x2U)
#define BRPHY1GV2_PCS_EXP95_EN_ESD2_FIX_SHIFT (1U)
#define BRPHY1GV2_PCS_EXP95_DIS_RXDV_FIX_MASK (0x1U)
#define BRPHY1GV2_PCS_EXP95_DIS_RXDV_FIX_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PCS_EXP96_TYPE;
#define BRPHY1GV2_PCS_EXP96_SKEW_ADJ_A_MASK (0xf000U)
#define BRPHY1GV2_PCS_EXP96_SKEW_ADJ_A_SHIFT (12U)
#define BRPHY1GV2_PCS_EXP96_SKEW_ADJ_B_MASK (0xf00U)
#define BRPHY1GV2_PCS_EXP96_SKEW_ADJ_B_SHIFT (8U)
#define BRPHY1GV2_PCS_EXP96_ERROR_PAIR_SWAP_MASK (0x40U)
#define BRPHY1GV2_PCS_EXP96_ERROR_PAIR_SWAP_SHIFT (6U)
#define BRPHY1GV2_PCS_EXP96_PAIRSETTINGSVALID_MASK (0x20U)
#define BRPHY1GV2_PCS_EXP96_PAIRSETTINGSVALID_SHIFT (5U)
#define BRPHY1GV2_PCS_EXP96_SWAPAB_MASK (0x10U)
#define BRPHY1GV2_PCS_EXP96_SWAPAB_SHIFT (4U)
#define BRPHY1GV2_PCS_EXP96_POLARITYB_MASK (0x8U)
#define BRPHY1GV2_PCS_EXP96_POLARITYB_SHIFT (3U)
#define BRPHY1GV2_PCS_EXP96_POLARITYA_MASK (0x4U)
#define BRPHY1GV2_PCS_EXP96_POLARITYA_SHIFT (2U)
#define BRPHY1GV2_PCS_EXP96_PAIRBSELECT_MASK (0x2U)
#define BRPHY1GV2_PCS_EXP96_PAIRBSELECT_SHIFT (1U)
#define BRPHY1GV2_PCS_EXP96_PAIRASELECT_MASK (0x1U)
#define BRPHY1GV2_PCS_EXP96_PAIRASELECT_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PCS_EXP97_TYPE;
#define BRPHY1GV2_PCS_EXP97_IDLE_COUNT_MASK (0xffU)
#define BRPHY1GV2_PCS_EXP97_IDLE_COUNT_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PCS_EXP9B_TYPE;
#define BRPHY1GV2_PCS_EXP9B_BR_RATE_OV_MASK (0xe000U)
#define BRPHY1GV2_PCS_EXP9B_BR_RATE_OV_SHIFT (13U)
#define BRPHY1GV2_PCS_EXP9B_BR_PLL_CTL_EN_MASK (0x1U)
#define BRPHY1GV2_PCS_EXP9B_BR_PLL_CTL_EN_SHIFT (0U)




typedef volatile struct sBRPHY1GV2_PCS_RDBType {
    BRPHY1GV2_PCS_EXP90_TYPE exp90; /* OFFSET: 0x0 */
    BRPHY1GV2_PCS_RESERVED_TYPE rsvd0[2]; /* OFFSET: 0x2 */
    BRPHY1GV2_PCS_EXP91_TYPE exp91; /* OFFSET: 0x4 */
    BRPHY1GV2_PCS_RESERVED_TYPE rsvd1[2]; /* OFFSET: 0x6 */
    BRPHY1GV2_PCS_EXP92_TYPE exp92; /* OFFSET: 0x8 */
    BRPHY1GV2_PCS_RESERVED_TYPE rsvd2[2]; /* OFFSET: 0xa */
    BRPHY1GV2_PCS_EXP93_TYPE exp93; /* OFFSET: 0xc */
    BRPHY1GV2_PCS_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0xe */
    BRPHY1GV2_PCS_EXP94_TYPE exp94; /* OFFSET: 0x10 */
    BRPHY1GV2_PCS_RESERVED_TYPE rsvd4[2]; /* OFFSET: 0x12 */
    BRPHY1GV2_PCS_EXP95_TYPE exp95; /* OFFSET: 0x14 */
    BRPHY1GV2_PCS_RESERVED_TYPE rsvd5[2]; /* OFFSET: 0x16 */
    BRPHY1GV2_PCS_EXP96_TYPE exp96; /* OFFSET: 0x18 */
    BRPHY1GV2_PCS_RESERVED_TYPE rsvd6[2]; /* OFFSET: 0x1a */
    BRPHY1GV2_PCS_EXP97_TYPE exp97; /* OFFSET: 0x1c */
    BRPHY1GV2_PCS_RESERVED_TYPE rsvd7[14]; /* OFFSET: 0x1e */
    BRPHY1GV2_PCS_EXP9B_TYPE exp9b; /* OFFSET: 0x2c */
} BRPHY1GV2_PCS_RDBType;


#define BRPHY0_1G_BR_PCS_BASE           (0xE0562C00UL)



#define BRPHY1GV2_PCS_MAX_HW_ID         (1UL)


#define BRPHY1GV2_0_PCS_BASE            (BRPHY0_1G_BR_PCS_BASE)

#endif /* BRPHY1GV2_PCS_RDB_H */
