/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file brphy1gv2_autoneg_ieee_rdb.h
    @brief RDB File for BRPHY1GV2_AUTONEG_IEEE

    @version BCM89580_A0_20230125_RDB
*/

#ifndef BRPHY1GV2_AUTONEG_IEEE_RDB_H
#define BRPHY1GV2_AUTONEG_IEEE_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t BRPHY1GV2_AUTONEG_IEEE_RESERVED_TYPE;




typedef uint16_t BRPHY1GV2_AUTONEG_IEEE_TENG_AN_STAT_TYPE;
#define BRPHY1GV2_AUTONEG_IEEE_TENG_AN_STAT_MSTR_SLV_CONFIG_FAULT_MASK (0x8000U)
#define BRPHY1GV2_AUTONEG_IEEE_TENG_AN_STAT_MSTR_SLV_CONFIG_FAULT_SHIFT (15U)
#define BRPHY1GV2_AUTONEG_IEEE_TENG_AN_STAT_MSTR_SLV_CONFIG_RES_MASK (0x4000U)
#define BRPHY1GV2_AUTONEG_IEEE_TENG_AN_STAT_MSTR_SLV_CONFIG_RES_SHIFT (14U)
#define BRPHY1GV2_AUTONEG_IEEE_TENG_AN_STAT_LOCAL_RCVR_STAT_MASK (0x2000U)
#define BRPHY1GV2_AUTONEG_IEEE_TENG_AN_STAT_LOCAL_RCVR_STAT_SHIFT (13U)
#define BRPHY1GV2_AUTONEG_IEEE_TENG_AN_STAT_REMOTE_RCVR_STAT_MASK (0x1000U)
#define BRPHY1GV2_AUTONEG_IEEE_TENG_AN_STAT_REMOTE_RCVR_STAT_SHIFT (12U)
#define BRPHY1GV2_AUTONEG_IEEE_TENG_AN_STAT_LP_PHY_10GBASE_T_ABLE_MASK (0x800U)
#define BRPHY1GV2_AUTONEG_IEEE_TENG_AN_STAT_LP_PHY_10GBASE_T_ABLE_SHIFT (11U)
#define BRPHY1GV2_AUTONEG_IEEE_TENG_AN_STAT_LP_LOOP_TIMING_ABLE_MASK (0x400U)
#define BRPHY1GV2_AUTONEG_IEEE_TENG_AN_STAT_LP_LOOP_TIMING_ABLE_SHIFT (10U)
#define BRPHY1GV2_AUTONEG_IEEE_TENG_AN_STAT_LP_PMA_TRAIN_RST_REQ_MASK (0x200U)
#define BRPHY1GV2_AUTONEG_IEEE_TENG_AN_STAT_LP_PMA_TRAIN_RST_REQ_SHIFT (9U)
#define BRPHY1GV2_AUTONEG_IEEE_TENG_AN_STAT_LP_PHY_5GBASE_T_ABLE_MASK (0x40U)
#define BRPHY1GV2_AUTONEG_IEEE_TENG_AN_STAT_LP_PHY_5GBASE_T_ABLE_SHIFT (6U)
#define BRPHY1GV2_AUTONEG_IEEE_TENG_AN_STAT_LP25TA_MASK (0x20U)
#define BRPHY1GV2_AUTONEG_IEEE_TENG_AN_STAT_LP25TA_SHIFT (5U)
#define BRPHY1GV2_AUTONEG_IEEE_TENG_AN_STAT_LFRC5_MASK (0x10U)
#define BRPHY1GV2_AUTONEG_IEEE_TENG_AN_STAT_LFRC5_SHIFT (4U)
#define BRPHY1GV2_AUTONEG_IEEE_TENG_AN_STAT_LFRC25_MASK (0x8U)
#define BRPHY1GV2_AUTONEG_IEEE_TENG_AN_STAT_LFRC25_SHIFT (3U)
#define BRPHY1GV2_AUTONEG_IEEE_TENG_AN_STAT_LFRC10_MASK (0x2U)
#define BRPHY1GV2_AUTONEG_IEEE_TENG_AN_STAT_LFRC10_SHIFT (1U)




typedef uint16_t BRPHY1GV2_AUTONEG_IEEE_AB1AC_TYPE;
#define BRPHY1GV2_AUTONEG_IEEE_AB1AC_AUTONEG_RESET_MASK (0x8000U)
#define BRPHY1GV2_AUTONEG_IEEE_AB1AC_AUTONEG_RESET_SHIFT (15U)
#define BRPHY1GV2_AUTONEG_IEEE_AB1AC_AUTONEG_ENABLE_MASK (0x1000U)
#define BRPHY1GV2_AUTONEG_IEEE_AB1AC_AUTONEG_ENABLE_SHIFT (12U)
#define BRPHY1GV2_AUTONEG_IEEE_AB1AC_RESTART_AUTO_NEGOTIATION_MASK (0x200U)
#define BRPHY1GV2_AUTONEG_IEEE_AB1AC_RESTART_AUTO_NEGOTIATION_SHIFT (9U)




typedef uint16_t BRPHY1GV2_AUTONEG_IEEE_AB1AS_TYPE;
#define BRPHY1GV2_AUTONEG_IEEE_AB1AS_PAGE_RECEIVED_MASK (0x40U)
#define BRPHY1GV2_AUTONEG_IEEE_AB1AS_PAGE_RECEIVED_SHIFT (6U)
#define BRPHY1GV2_AUTONEG_IEEE_AB1AS_AUTONEG_COMPLETE_MASK (0x20U)
#define BRPHY1GV2_AUTONEG_IEEE_AB1AS_AUTONEG_COMPLETE_SHIFT (5U)
#define BRPHY1GV2_AUTONEG_IEEE_AB1AS_REMOTE_FAULT_MASK (0x10U)
#define BRPHY1GV2_AUTONEG_IEEE_AB1AS_REMOTE_FAULT_SHIFT (4U)
#define BRPHY1GV2_AUTONEG_IEEE_AB1AS_AUTONEG_ABILITY_MASK (0x8U)
#define BRPHY1GV2_AUTONEG_IEEE_AB1AS_AUTONEG_ABILITY_SHIFT (3U)
#define BRPHY1GV2_AUTONEG_IEEE_AB1AS_LINK_STATUS_MASK (0x4U)
#define BRPHY1GV2_AUTONEG_IEEE_AB1AS_LINK_STATUS_SHIFT (2U)




typedef uint16_t BRPHY1GV2_AUTONEG_IEEE_B1AAR0_TYPE;
#define BRPHY1GV2_AUTONEG_IEEE_B1AAR0_NEXT_PAGE_MASK (0x8000U)
#define BRPHY1GV2_AUTONEG_IEEE_B1AAR0_NEXT_PAGE_SHIFT (15U)
#define BRPHY1GV2_AUTONEG_IEEE_B1AAR0_ACKNOWLEDGE_MASK (0x4000U)
#define BRPHY1GV2_AUTONEG_IEEE_B1AAR0_ACKNOWLEDGE_SHIFT (14U)
#define BRPHY1GV2_AUTONEG_IEEE_B1AAR0_REMOTE_FAULT_MASK (0x2000U)
#define BRPHY1GV2_AUTONEG_IEEE_B1AAR0_REMOTE_FAULT_SHIFT (13U)
#define BRPHY1GV2_AUTONEG_IEEE_B1AAR0_FORCE_MASTER_SLAVE_MASK (0x1000U)
#define BRPHY1GV2_AUTONEG_IEEE_B1AAR0_FORCE_MASTER_SLAVE_SHIFT (12U)
#define BRPHY1GV2_AUTONEG_IEEE_B1AAR0_PAUSE_CAPABILITIES_MASK (0xc00U)
#define BRPHY1GV2_AUTONEG_IEEE_B1AAR0_PAUSE_CAPABILITIES_SHIFT (10U)
#define BRPHY1GV2_AUTONEG_IEEE_B1AAR0_ECHOED_NONCE_FIELD_MASK (0x3e0U)
#define BRPHY1GV2_AUTONEG_IEEE_B1AAR0_ECHOED_NONCE_FIELD_SHIFT (5U)
#define BRPHY1GV2_AUTONEG_IEEE_B1AAR0_SELECTOR_FIELD_MASK (0x1fU)
#define BRPHY1GV2_AUTONEG_IEEE_B1AAR0_SELECTOR_FIELD_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AUTONEG_IEEE_B1AAR1_TYPE;
#define BRPHY1GV2_AUTONEG_IEEE_B1AAR1_D31_D24_MASK (0xff00U)
#define BRPHY1GV2_AUTONEG_IEEE_B1AAR1_D31_D24_SHIFT (8U)
#define BRPHY1GV2_AUTONEG_IEEE_B1AAR1_ADVERISE_1000BASE_T1_MASK (0x80U)
#define BRPHY1GV2_AUTONEG_IEEE_B1AAR1_ADVERISE_1000BASE_T1_SHIFT (7U)
#define BRPHY1GV2_AUTONEG_IEEE_B1AAR1_D22_MASK (0x40U)
#define BRPHY1GV2_AUTONEG_IEEE_B1AAR1_D22_SHIFT (6U)
#define BRPHY1GV2_AUTONEG_IEEE_B1AAR1_ADVERISE_100BASE_T1_MASK (0x20U)
#define BRPHY1GV2_AUTONEG_IEEE_B1AAR1_ADVERISE_100BASE_T1_SHIFT (5U)
#define BRPHY1GV2_AUTONEG_IEEE_B1AAR1_MASTER_SLAVE_MASK (0x10U)
#define BRPHY1GV2_AUTONEG_IEEE_B1AAR1_MASTER_SLAVE_SHIFT (4U)
#define BRPHY1GV2_AUTONEG_IEEE_B1AAR1_TRANSMITTED_NONCE_FIELD_MASK (0xfU)
#define BRPHY1GV2_AUTONEG_IEEE_B1AAR1_TRANSMITTED_NONCE_FIELD_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AUTONEG_IEEE_B1AAR2_TYPE;
#define BRPHY1GV2_AUTONEG_IEEE_B1AAR2_D47_D32_MASK (0xffffU)
#define BRPHY1GV2_AUTONEG_IEEE_B1AAR2_D47_D32_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AUTONEG_IEEE_B1ALBPAR0_TYPE;
#define BRPHY1GV2_AUTONEG_IEEE_B1ALBPAR0_D15_D0_MASK (0xffffU)
#define BRPHY1GV2_AUTONEG_IEEE_B1ALBPAR0_D15_D0_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AUTONEG_IEEE_B1ALBPAR1_TYPE;
#define BRPHY1GV2_AUTONEG_IEEE_B1ALBPAR1_D31_D16_MASK (0xffffU)
#define BRPHY1GV2_AUTONEG_IEEE_B1ALBPAR1_D31_D16_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AUTONEG_IEEE_B1ALBPAR2_TYPE;
#define BRPHY1GV2_AUTONEG_IEEE_B1ALBPAR2_D47_D32_MASK (0xffffU)
#define BRPHY1GV2_AUTONEG_IEEE_B1ALBPAR2_D47_D32_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AUTONEG_IEEE_B1ANPTR0_TYPE;
#define BRPHY1GV2_AUTONEG_IEEE_B1ANPTR0_NEXT_PAGE_MASK (0x8000U)
#define BRPHY1GV2_AUTONEG_IEEE_B1ANPTR0_NEXT_PAGE_SHIFT (15U)
#define BRPHY1GV2_AUTONEG_IEEE_B1ANPTR0_MESSAGE_PAGE_MASK (0x2000U)
#define BRPHY1GV2_AUTONEG_IEEE_B1ANPTR0_MESSAGE_PAGE_SHIFT (13U)
#define BRPHY1GV2_AUTONEG_IEEE_B1ANPTR0_ACKNOWLEDGE2_MASK (0x1000U)
#define BRPHY1GV2_AUTONEG_IEEE_B1ANPTR0_ACKNOWLEDGE2_SHIFT (12U)
#define BRPHY1GV2_AUTONEG_IEEE_B1ANPTR0_TOGGLE_MASK (0x800U)
#define BRPHY1GV2_AUTONEG_IEEE_B1ANPTR0_TOGGLE_SHIFT (11U)
#define BRPHY1GV2_AUTONEG_IEEE_B1ANPTR0_MUCF_MASK (0x7ffU)
#define BRPHY1GV2_AUTONEG_IEEE_B1ANPTR0_MUCF_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AUTONEG_IEEE_B1ANPTR1_TYPE;
#define BRPHY1GV2_AUTONEG_IEEE_B1ANPTR1_UNFORMATTED_CODE_FIELD_1_MASK (0xffffU)
#define BRPHY1GV2_AUTONEG_IEEE_B1ANPTR1_UNFORMATTED_CODE_FIELD_1_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AUTONEG_IEEE_B1ANPTR2_TYPE;
#define BRPHY1GV2_AUTONEG_IEEE_B1ANPTR2_UNFORMATTED_CODE_FIELD_2_MASK (0xffffU)
#define BRPHY1GV2_AUTONEG_IEEE_B1ANPTR2_UNFORMATTED_CODE_FIELD_2_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AUTONEG_IEEE_B1ALNPAR0_TYPE;
#define BRPHY1GV2_AUTONEG_IEEE_B1ALNPAR0_NEXT_PAGE_MASK (0x8000U)
#define BRPHY1GV2_AUTONEG_IEEE_B1ALNPAR0_NEXT_PAGE_SHIFT (15U)
#define BRPHY1GV2_AUTONEG_IEEE_B1ALNPAR0_ACKNOWLEDGE_MASK (0x4000U)
#define BRPHY1GV2_AUTONEG_IEEE_B1ALNPAR0_ACKNOWLEDGE_SHIFT (14U)
#define BRPHY1GV2_AUTONEG_IEEE_B1ALNPAR0_MESSAGE_PAGE_MASK (0x2000U)
#define BRPHY1GV2_AUTONEG_IEEE_B1ALNPAR0_MESSAGE_PAGE_SHIFT (13U)
#define BRPHY1GV2_AUTONEG_IEEE_B1ALNPAR0_ACKNOWLEDGE2_MASK (0x1000U)
#define BRPHY1GV2_AUTONEG_IEEE_B1ALNPAR0_ACKNOWLEDGE2_SHIFT (12U)
#define BRPHY1GV2_AUTONEG_IEEE_B1ALNPAR0_TOGGLE_MASK (0x800U)
#define BRPHY1GV2_AUTONEG_IEEE_B1ALNPAR0_TOGGLE_SHIFT (11U)
#define BRPHY1GV2_AUTONEG_IEEE_B1ALNPAR0_MUCF1_MASK (0x7ffU)
#define BRPHY1GV2_AUTONEG_IEEE_B1ALNPAR0_MUCF1_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AUTONEG_IEEE_B1ALNPAR1_TYPE;
#define BRPHY1GV2_AUTONEG_IEEE_B1ALNPAR1_UNFORMATTED_CODE_FIELD_1_MASK (0xffffU)
#define BRPHY1GV2_AUTONEG_IEEE_B1ALNPAR1_UNFORMATTED_CODE_FIELD_1_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AUTONEG_IEEE_B1ALNPAR2_TYPE;
#define BRPHY1GV2_AUTONEG_IEEE_B1ALNPAR2_UNFORMATTED_CODE_FIELD_2_MASK (0xffffU)
#define BRPHY1GV2_AUTONEG_IEEE_B1ALNPAR2_UNFORMATTED_CODE_FIELD_2_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AUTONEG_IEEE_ATR0_TYPE;
#define BRPHY1GV2_AUTONEG_IEEE_ATR0_AUTONEG_WIRESPEED_ENABLE_MASK (0x8000U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR0_AUTONEG_WIRESPEED_ENABLE_SHIFT (15U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR0_AUTONEG_TEST_REG0_BIT_14_MASK (0x4000U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR0_AUTONEG_TEST_REG0_BIT_14_SHIFT (14U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR0_ADIDIACA_MASK (0x2000U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR0_ADIDIACA_SHIFT (13U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR0_ALFIDF_MASK (0x1000U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR0_ALFIDF_SHIFT (12U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR0_AUTONEG_MESSAGE_5_ENABLE_MASK (0x800U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR0_AUTONEG_MESSAGE_5_ENABLE_SHIFT (11U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR0_ADRWCA_MASK (0x400U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR0_ADRWCA_SHIFT (10U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR0_ABLTM_MASK (0x300U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR0_ABLTM_SHIFT (8U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR0_ALFITM_MASK (0xf0U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR0_ALFITM_SHIFT (4U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR0_ALFITF_MASK (0x8U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR0_ALFITF_SHIFT (3U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR0_AWAN_MASK (0x7U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR0_AWAN_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AUTONEG_IEEE_ATR1_TYPE;
#define BRPHY1GV2_AUTONEG_IEEE_ATR1_AUTONEG_FORCE_RESOLUTION_MASK (0x8000U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR1_AUTONEG_FORCE_RESOLUTION_SHIFT (15U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR1_AUTONEG_FORCE_MASTER_SLAVE_MASK (0x4000U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR1_AUTONEG_FORCE_MASTER_SLAVE_SHIFT (14U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR1_AFCF_MASK (0x2000U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR1_AFCF_SHIFT (13U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR1_AFLC10001_MASK (0x1000U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR1_AFLC10001_SHIFT (12U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR1_AFLC1001_MASK (0x800U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR1_AFLC1001_SHIFT (11U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR1_OVERRIDE_MS_RESOLUTION_FAULT_MASK (0x400U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR1_OVERRIDE_MS_RESOLUTION_FAULT_SHIFT (10U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR1_ORPV_MASK (0x200U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR1_ORPV_SHIFT (9U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR1_OVERRIDE_RANDOM_POLARITY_MASK (0x100U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR1_OVERRIDE_RANDOM_POLARITY_SHIFT (8U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR1_OVERRIDE_RANDOM_SEED_VALUE_MASK (0xf0U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR1_OVERRIDE_RANDOM_SEED_VALUE_SHIFT (4U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR1_OVERRIDE_RANDOM_SEED_MASK (0x8U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR1_OVERRIDE_RANDOM_SEED_SHIFT (3U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR1_ACCELERATE_LEGACY_TIMER_MASK (0x4U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR1_ACCELERATE_LEGACY_TIMER_SHIFT (2U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR1_ALFIT_MASK (0x2U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR1_ALFIT_SHIFT (1U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR1_ACCELERATE_BREAK_LINK_TIMER_MASK (0x1U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR1_ACCELERATE_BREAK_LINK_TIMER_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AUTONEG_IEEE_ATR2_TYPE;
#define BRPHY1GV2_AUTONEG_IEEE_ATR2_MR_AUTONEG_COMPLETE_MASK (0x8000U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR2_MR_AUTONEG_COMPLETE_SHIFT (15U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR2_AUTONEG_WIRESPEED_COUNT_MASK (0x7000U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR2_AUTONEG_WIRESPEED_COUNT_SHIFT (12U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR2_AUTONEG_WIRESPEED_DOWNGRADE_MASK (0x800U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR2_AUTONEG_WIRESPEED_DOWNGRADE_SHIFT (11U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR2_AUTONEG_LINK_GOOD_CHECK_MASK (0x400U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR2_AUTONEG_LINK_GOOD_CHECK_SHIFT (10U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR2_CONFIGURATION_FAULT_MASK (0x200U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR2_CONFIGURATION_FAULT_SHIFT (9U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR2_MASTER_SLAVE_MASK (0x100U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR2_MASTER_SLAVE_SHIFT (8U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR2_ASMCS_MASK (0xf0U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR2_ASMCS_SHIFT (4U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR2_HIGHEST_COMMON_DENOMINATOR_MASK (0xfU)
#define BRPHY1GV2_AUTONEG_IEEE_ATR2_HIGHEST_COMMON_DENOMINATOR_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AUTONEG_IEEE_ATR3_TYPE;
#define BRPHY1GV2_AUTONEG_IEEE_ATR3_DETECT_LEGACY_100T1_MASK (0x8000U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR3_DETECT_LEGACY_100T1_SHIFT (15U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR3_DETECT_TRANSITION_MASK (0x4000U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR3_DETECT_TRANSITION_SHIFT (14U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR3_DETECT_MV_END_MASK (0x2000U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR3_DETECT_MV_END_SHIFT (13U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR3_DETECT_MV_START_MASK (0x1000U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR3_DETECT_MV_START_SHIFT (12U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR3_DETECT_POLARITY_MASK (0x800U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR3_DETECT_POLARITY_SHIFT (11U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR3_RSMCS_MASK (0x700U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR3_RSMCS_SHIFT (8U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR3_LP_AUTONEG_ABLE_MASK (0x80U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR3_LP_AUTONEG_ABLE_SHIFT (7U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR3_TSMCS_MASK (0x70U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR3_TSMCS_SHIFT (4U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR3_HSMCS_MASK (0xfU)
#define BRPHY1GV2_AUTONEG_IEEE_ATR3_HSMCS_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AUTONEG_IEEE_ATR4_TYPE;
#define BRPHY1GV2_AUTONEG_IEEE_ATR4_ATMDM_MASK (0x8000U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR4_ATMDM_SHIFT (15U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR4_L1001DMET_MASK (0x4000U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR4_L1001DMET_SHIFT (14U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR4_LEGACY_100T1_DETECT_MS_VAL_MASK (0x2000U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR4_LEGACY_100T1_DETECT_MS_VAL_SHIFT (13U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR4_LEGACY_100T1_DETECTOR_VALUE_MASK (0x1000U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR4_LEGACY_100T1_DETECTOR_VALUE_SHIFT (12U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR4_LEGACY_100T1_DETECT_ENABLE_MASK (0x800U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR4_LEGACY_100T1_DETECT_ENABLE_SHIFT (11U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR4_AUTONEG_HPF_POLE_SEL_MASK (0x600U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR4_AUTONEG_HPF_POLE_SEL_SHIFT (9U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR4_L1001TMET_MASK (0x100U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR4_L1001TMET_SHIFT (8U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR4_LEGACY_100T1_TIMER_MS_VAL_MASK (0x80U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR4_LEGACY_100T1_TIMER_MS_VAL_SHIFT (7U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR4_LEGACY_100T1_TIMER_ENABLE_MASK (0x40U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR4_LEGACY_100T1_TIMER_ENABLE_SHIFT (6U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR4_DETECT_MV_END_COEFFICIENT_MASK (0x38U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR4_DETECT_MV_END_COEFFICIENT_SHIFT (3U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR4_DMTC_MASK (0x7U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR4_DMTC_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AUTONEG_IEEE_ATR5_TYPE;
#define BRPHY1GV2_AUTONEG_IEEE_ATR5_L1001DTV_MASK (0xffe0U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR5_L1001DTV_SHIFT (5U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR5_DETECT_MV_START_COEFFICIENT_MASK (0x1fU)
#define BRPHY1GV2_AUTONEG_IEEE_ATR5_DETECT_MV_START_COEFFICIENT_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AUTONEG_IEEE_ATR6_TYPE;
#define BRPHY1GV2_AUTONEG_IEEE_ATR6_DISABLE_SUM_ABS_PREV_CHECK_MASK (0x8000U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR6_DISABLE_SUM_ABS_PREV_CHECK_SHIFT (15U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR6_MDMST_MASK (0x7fffU)
#define BRPHY1GV2_AUTONEG_IEEE_ATR6_MDMST_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AUTONEG_IEEE_ATR7_TYPE;
#define BRPHY1GV2_AUTONEG_IEEE_ATR7_DMSMT_MASK (0xfc00U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR7_DMSMT_SHIFT (10U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR7_MDMTT_MASK (0x3ffU)
#define BRPHY1GV2_AUTONEG_IEEE_ATR7_MDMTT_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AUTONEG_IEEE_ATR8_TYPE;
#define BRPHY1GV2_AUTONEG_IEEE_ATR8_AUTONEG_PGA_VALUE_MASK (0xfc00U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR8_AUTONEG_PGA_VALUE_SHIFT (10U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR8_MDMET_MASK (0x3ffU)
#define BRPHY1GV2_AUTONEG_IEEE_ATR8_MDMET_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AUTONEG_IEEE_ATR9_TYPE;
#define BRPHY1GV2_AUTONEG_IEEE_ATR9_SPARE_BITS_TEST_REG9_MASK (0xfffeU)
#define BRPHY1GV2_AUTONEG_IEEE_ATR9_SPARE_BITS_TEST_REG9_SHIFT (1U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR9_TC10_RESOLUTION_MASK (0x1U)
#define BRPHY1GV2_AUTONEG_IEEE_ATR9_TC10_RESOLUTION_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AUTONEG_IEEE_AISR_TYPE;
#define BRPHY1GV2_AUTONEG_IEEE_AISR_AISRSB1512_MASK (0xf000U)
#define BRPHY1GV2_AUTONEG_IEEE_AISR_AISRSB1512_SHIFT (12U)
#define BRPHY1GV2_AUTONEG_IEEE_AISR_AWDIS_MASK (0x800U)
#define BRPHY1GV2_AUTONEG_IEEE_AISR_AWDIS_SHIFT (11U)
#define BRPHY1GV2_AUTONEG_IEEE_AISR_ALGCIS_MASK (0x400U)
#define BRPHY1GV2_AUTONEG_IEEE_AISR_ALGCIS_SHIFT (10U)
#define BRPHY1GV2_AUTONEG_IEEE_AISR_MARIS_MASK (0x200U)
#define BRPHY1GV2_AUTONEG_IEEE_AISR_MARIS_SHIFT (9U)
#define BRPHY1GV2_AUTONEG_IEEE_AISR_AISRSB8_MASK (0x100U)
#define BRPHY1GV2_AUTONEG_IEEE_AISR_AISRSB8_SHIFT (8U)
#define BRPHY1GV2_AUTONEG_IEEE_AISR_CFIS_MASK (0x80U)
#define BRPHY1GV2_AUTONEG_IEEE_AISR_CFIS_SHIFT (7U)
#define BRPHY1GV2_AUTONEG_IEEE_AISR_MR_PAGE_RX_INTERRUPT_STATUS_MASK (0x40U)
#define BRPHY1GV2_AUTONEG_IEEE_AISR_MR_PAGE_RX_INTERRUPT_STATUS_SHIFT (6U)
#define BRPHY1GV2_AUTONEG_IEEE_AISR_MACIS_MASK (0x20U)
#define BRPHY1GV2_AUTONEG_IEEE_AISR_MACIS_SHIFT (5U)
#define BRPHY1GV2_AUTONEG_IEEE_AISR_REMOTE_FAULT_INTERRUPT_STATUS_MASK (0x10U)
#define BRPHY1GV2_AUTONEG_IEEE_AISR_REMOTE_FAULT_INTERRUPT_STATUS_SHIFT (4U)
#define BRPHY1GV2_AUTONEG_IEEE_AISR_AISRSB3_MASK (0x8U)
#define BRPHY1GV2_AUTONEG_IEEE_AISR_AISRSB3_SHIFT (3U)
#define BRPHY1GV2_AUTONEG_IEEE_AISR_AISRSB2_MASK (0x4U)
#define BRPHY1GV2_AUTONEG_IEEE_AISR_AISRSB2_SHIFT (2U)
#define BRPHY1GV2_AUTONEG_IEEE_AISR_RLSUIS_MASK (0x2U)
#define BRPHY1GV2_AUTONEG_IEEE_AISR_RLSUIS_SHIFT (1U)
#define BRPHY1GV2_AUTONEG_IEEE_AISR_RLSDIS_MASK (0x1U)
#define BRPHY1GV2_AUTONEG_IEEE_AISR_RLSDIS_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AUTONEG_IEEE_AIER_TYPE;
#define BRPHY1GV2_AUTONEG_IEEE_AIER_AIERSB1512_MASK (0xf000U)
#define BRPHY1GV2_AUTONEG_IEEE_AIER_AIERSB1512_SHIFT (12U)
#define BRPHY1GV2_AUTONEG_IEEE_AIER_AWDIE_MASK (0x800U)
#define BRPHY1GV2_AUTONEG_IEEE_AIER_AWDIE_SHIFT (11U)
#define BRPHY1GV2_AUTONEG_IEEE_AIER_ALGCIE_MASK (0x400U)
#define BRPHY1GV2_AUTONEG_IEEE_AIER_ALGCIE_SHIFT (10U)
#define BRPHY1GV2_AUTONEG_IEEE_AIER_MARIE_MASK (0x200U)
#define BRPHY1GV2_AUTONEG_IEEE_AIER_MARIE_SHIFT (9U)
#define BRPHY1GV2_AUTONEG_IEEE_AIER_AIERSB8_MASK (0x100U)
#define BRPHY1GV2_AUTONEG_IEEE_AIER_AIERSB8_SHIFT (8U)
#define BRPHY1GV2_AUTONEG_IEEE_AIER_CFIE_MASK (0x80U)
#define BRPHY1GV2_AUTONEG_IEEE_AIER_CFIE_SHIFT (7U)
#define BRPHY1GV2_AUTONEG_IEEE_AIER_MR_PAGE_RX_INTERRUPT_ENABLE_MASK (0x40U)
#define BRPHY1GV2_AUTONEG_IEEE_AIER_MR_PAGE_RX_INTERRUPT_ENABLE_SHIFT (6U)
#define BRPHY1GV2_AUTONEG_IEEE_AIER_MACIE_MASK (0x20U)
#define BRPHY1GV2_AUTONEG_IEEE_AIER_MACIE_SHIFT (5U)
#define BRPHY1GV2_AUTONEG_IEEE_AIER_REMOTE_FAULT_INTERRUPT_ENABLE_MASK (0x10U)
#define BRPHY1GV2_AUTONEG_IEEE_AIER_REMOTE_FAULT_INTERRUPT_ENABLE_SHIFT (4U)
#define BRPHY1GV2_AUTONEG_IEEE_AIER_AIERSB3_MASK (0x8U)
#define BRPHY1GV2_AUTONEG_IEEE_AIER_AIERSB3_SHIFT (3U)
#define BRPHY1GV2_AUTONEG_IEEE_AIER_AIERSB2_MASK (0x4U)
#define BRPHY1GV2_AUTONEG_IEEE_AIER_AIERSB2_SHIFT (2U)
#define BRPHY1GV2_AUTONEG_IEEE_AIER_RLSUIE_MASK (0x2U)
#define BRPHY1GV2_AUTONEG_IEEE_AIER_RLSUIE_SHIFT (1U)
#define BRPHY1GV2_AUTONEG_IEEE_AIER_RLSDIE_MASK (0x1U)
#define BRPHY1GV2_AUTONEG_IEEE_AIER_RLSDIE_SHIFT (0U)




typedef volatile struct sBRPHY1GV2_AUTONEG_IEEE_RDBType {
    BRPHY1GV2_AUTONEG_IEEE_RESERVED_TYPE rsvd0[132]; /* OFFSET: 0x0 */
    BRPHY1GV2_AUTONEG_IEEE_TENG_AN_STAT_TYPE teng_an_stat; /* OFFSET: 0x84 */
    BRPHY1GV2_AUTONEG_IEEE_RESERVED_TYPE rsvd1[1914]; /* OFFSET: 0x86 */
    BRPHY1GV2_AUTONEG_IEEE_AB1AC_TYPE autoneg_baset1_an_control; /* OFFSET: 0x800 */
    BRPHY1GV2_AUTONEG_IEEE_RESERVED_TYPE rsvd2[2]; /* OFFSET: 0x802 */
    BRPHY1GV2_AUTONEG_IEEE_AB1AS_TYPE autoneg_baset1_an_status; /* OFFSET: 0x804 */
    BRPHY1GV2_AUTONEG_IEEE_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0x806 */
    BRPHY1GV2_AUTONEG_IEEE_B1AAR0_TYPE baset1_an_advertisement_reg0; /* OFFSET: 0x808 */
    BRPHY1GV2_AUTONEG_IEEE_RESERVED_TYPE rsvd4[2]; /* OFFSET: 0x80a */
    BRPHY1GV2_AUTONEG_IEEE_B1AAR1_TYPE baset1_an_advertisement_reg1; /* OFFSET: 0x80c */
    BRPHY1GV2_AUTONEG_IEEE_RESERVED_TYPE rsvd5[2]; /* OFFSET: 0x80e */
    BRPHY1GV2_AUTONEG_IEEE_B1AAR2_TYPE baset1_an_advertisement_reg2; /* OFFSET: 0x810 */
    BRPHY1GV2_AUTONEG_IEEE_RESERVED_TYPE rsvd6[2]; /* OFFSET: 0x812 */
    BRPHY1GV2_AUTONEG_IEEE_B1ALBPAR0_TYPE baset1_an_lp_base_page_ability_reg0; /* OFFSET: 0x814 */
    BRPHY1GV2_AUTONEG_IEEE_RESERVED_TYPE rsvd7[2]; /* OFFSET: 0x816 */
    BRPHY1GV2_AUTONEG_IEEE_B1ALBPAR1_TYPE baset1_an_lp_base_page_ability_reg1; /* OFFSET: 0x818 */
    BRPHY1GV2_AUTONEG_IEEE_RESERVED_TYPE rsvd8[2]; /* OFFSET: 0x81a */
    BRPHY1GV2_AUTONEG_IEEE_B1ALBPAR2_TYPE baset1_an_lp_base_page_ability_reg2; /* OFFSET: 0x81c */
    BRPHY1GV2_AUTONEG_IEEE_RESERVED_TYPE rsvd9[2]; /* OFFSET: 0x81e */
    BRPHY1GV2_AUTONEG_IEEE_B1ANPTR0_TYPE baset1_an_next_page_transmit_reg0; /* OFFSET: 0x820 */
    BRPHY1GV2_AUTONEG_IEEE_RESERVED_TYPE rsvd10[2]; /* OFFSET: 0x822 */
    BRPHY1GV2_AUTONEG_IEEE_B1ANPTR1_TYPE baset1_an_next_page_transmit_reg1; /* OFFSET: 0x824 */
    BRPHY1GV2_AUTONEG_IEEE_RESERVED_TYPE rsvd11[2]; /* OFFSET: 0x826 */
    BRPHY1GV2_AUTONEG_IEEE_B1ANPTR2_TYPE baset1_an_next_page_transmit_reg2; /* OFFSET: 0x828 */
    BRPHY1GV2_AUTONEG_IEEE_RESERVED_TYPE rsvd12[2]; /* OFFSET: 0x82a */
    BRPHY1GV2_AUTONEG_IEEE_B1ALNPAR0_TYPE baset1_an_lp_next_page_ability_reg0; /* OFFSET: 0x82c */
    BRPHY1GV2_AUTONEG_IEEE_RESERVED_TYPE rsvd13[2]; /* OFFSET: 0x82e */
    BRPHY1GV2_AUTONEG_IEEE_B1ALNPAR1_TYPE baset1_an_lp_next_page_ability_reg1; /* OFFSET: 0x830 */
    BRPHY1GV2_AUTONEG_IEEE_RESERVED_TYPE rsvd14[2]; /* OFFSET: 0x832 */
    BRPHY1GV2_AUTONEG_IEEE_B1ALNPAR2_TYPE baset1_an_lp_next_page_ability_reg2; /* OFFSET: 0x834 */
    BRPHY1GV2_AUTONEG_IEEE_RESERVED_TYPE rsvd15[129482]; /* OFFSET: 0x836 */
    BRPHY1GV2_AUTONEG_IEEE_ATR0_TYPE autoneg_test_reg0; /* OFFSET: 0x20200 */
    BRPHY1GV2_AUTONEG_IEEE_RESERVED_TYPE rsvd16[2]; /* OFFSET: 0x20202 */
    BRPHY1GV2_AUTONEG_IEEE_ATR1_TYPE autoneg_test_reg1; /* OFFSET: 0x20204 */
    BRPHY1GV2_AUTONEG_IEEE_RESERVED_TYPE rsvd17[2]; /* OFFSET: 0x20206 */
    BRPHY1GV2_AUTONEG_IEEE_ATR2_TYPE autoneg_test_reg2; /* OFFSET: 0x20208 */
    BRPHY1GV2_AUTONEG_IEEE_RESERVED_TYPE rsvd18[2]; /* OFFSET: 0x2020a */
    BRPHY1GV2_AUTONEG_IEEE_ATR3_TYPE autoneg_test_reg3; /* OFFSET: 0x2020c */
    BRPHY1GV2_AUTONEG_IEEE_RESERVED_TYPE rsvd19[2]; /* OFFSET: 0x2020e */
    BRPHY1GV2_AUTONEG_IEEE_ATR4_TYPE autoneg_test_reg4; /* OFFSET: 0x20210 */
    BRPHY1GV2_AUTONEG_IEEE_RESERVED_TYPE rsvd20[2]; /* OFFSET: 0x20212 */
    BRPHY1GV2_AUTONEG_IEEE_ATR5_TYPE autoneg_test_reg5; /* OFFSET: 0x20214 */
    BRPHY1GV2_AUTONEG_IEEE_RESERVED_TYPE rsvd21[2]; /* OFFSET: 0x20216 */
    BRPHY1GV2_AUTONEG_IEEE_ATR6_TYPE autoneg_test_reg6; /* OFFSET: 0x20218 */
    BRPHY1GV2_AUTONEG_IEEE_RESERVED_TYPE rsvd22[2]; /* OFFSET: 0x2021a */
    BRPHY1GV2_AUTONEG_IEEE_ATR7_TYPE autoneg_test_reg7; /* OFFSET: 0x2021c */
    BRPHY1GV2_AUTONEG_IEEE_RESERVED_TYPE rsvd23[2]; /* OFFSET: 0x2021e */
    BRPHY1GV2_AUTONEG_IEEE_ATR8_TYPE autoneg_test_reg8; /* OFFSET: 0x20220 */
    BRPHY1GV2_AUTONEG_IEEE_RESERVED_TYPE rsvd24[2]; /* OFFSET: 0x20222 */
    BRPHY1GV2_AUTONEG_IEEE_ATR9_TYPE autoneg_test_reg9; /* OFFSET: 0x20224 */
    BRPHY1GV2_AUTONEG_IEEE_RESERVED_TYPE rsvd25[26]; /* OFFSET: 0x20226 */
    BRPHY1GV2_AUTONEG_IEEE_AISR_TYPE autoneg_interrupt_status_reg; /* OFFSET: 0x20240 */
    BRPHY1GV2_AUTONEG_IEEE_RESERVED_TYPE rsvd26[2]; /* OFFSET: 0x20242 */
    BRPHY1GV2_AUTONEG_IEEE_AIER_TYPE autoneg_interrupt_enable_reg; /* OFFSET: 0x20244 */
} BRPHY1GV2_AUTONEG_IEEE_RDBType;


#define BRPHY0_1G_AUTONEG_IEEE_BASE     (0xE05D0000UL)



#define BRPHY1GV2_AUTONEG_IEEE_MAX_HW_ID  (1UL)

#endif /* BRPHY1GV2_AUTONEG_IEEE_RDB_H */
