/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file brphy1gv2_phycontrol_rdb.h
    @brief RDB File for BRPHY1GV2_PHYCONTROL

    @version BCM89580_A0_20230125_RDB
*/

#ifndef BRPHY1GV2_PHYCONTROL_RDB_H
#define BRPHY1GV2_PHYCONTROL_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t BRPHY1GV2_PHYCONTROL_RESERVED_TYPE;




typedef uint16_t BRPHY1GV2_PHYCONTROL_PATCH_STATE_CTL_TYPE;
#define BRPHY1GV2_PHYCONTROL_PATCH_STATE_CTL_FIX_STATE_MASK (0xff00U)
#define BRPHY1GV2_PHYCONTROL_PATCH_STATE_CTL_FIX_STATE_SHIFT (8U)
#define BRPHY1GV2_PHYCONTROL_PATCH_STATE_CTL_PATCH_STATE_MASK (0xffU)
#define BRPHY1GV2_PHYCONTROL_PATCH_STATE_CTL_PATCH_STATE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PHYCONTROL_TC1_DCQ_SQI_TYPE;
#define BRPHY1GV2_PHYCONTROL_TC1_DCQ_SQI_WC_MASK (0xe0U)
#define BRPHY1GV2_PHYCONTROL_TC1_DCQ_SQI_WC_SHIFT (5U)
#define BRPHY1GV2_PHYCONTROL_TC1_DCQ_SQI_MASK (0xeU)
#define BRPHY1GV2_PHYCONTROL_TC1_DCQ_SQI_SHIFT (1U)




typedef uint16_t BRPHY1GV2_PHYCONTROL_T1DST0_TYPE;
#define BRPHY1GV2_PHYCONTROL_T1DST0_SQI_THRESHOLD_MASK (0xfffU)
#define BRPHY1GV2_PHYCONTROL_T1DST0_SQI_THRESHOLD_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PHYCONTROL_T1DST1_TYPE;
#define BRPHY1GV2_PHYCONTROL_T1DST1_SQI_THRESHOLD_MASK (0xfffU)
#define BRPHY1GV2_PHYCONTROL_T1DST1_SQI_THRESHOLD_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PHYCONTROL_T1DST2_TYPE;
#define BRPHY1GV2_PHYCONTROL_T1DST2_SQI_THRESHOLD_MASK (0xfffU)
#define BRPHY1GV2_PHYCONTROL_T1DST2_SQI_THRESHOLD_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PHYCONTROL_T1DST3_TYPE;
#define BRPHY1GV2_PHYCONTROL_T1DST3_SQI_THRESHOLD_MASK (0xfffU)
#define BRPHY1GV2_PHYCONTROL_T1DST3_SQI_THRESHOLD_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PHYCONTROL_T1DST4_TYPE;
#define BRPHY1GV2_PHYCONTROL_T1DST4_SQI_THRESHOLD_MASK (0xfffU)
#define BRPHY1GV2_PHYCONTROL_T1DST4_SQI_THRESHOLD_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PHYCONTROL_T1DST5_TYPE;
#define BRPHY1GV2_PHYCONTROL_T1DST5_SQI_THRESHOLD_MASK (0xfffU)
#define BRPHY1GV2_PHYCONTROL_T1DST5_SQI_THRESHOLD_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PHYCONTROL_T1DST6_TYPE;
#define BRPHY1GV2_PHYCONTROL_T1DST6_SQI_THRESHOLD_MASK (0xfffU)
#define BRPHY1GV2_PHYCONTROL_T1DST6_SQI_THRESHOLD_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PHYCONTROL_STATE_BRANCH_CTL_TYPE;
#define BRPHY1GV2_PHYCONTROL_STATE_BRANCH_CTL_1_STATE_MASK (0xff00U)
#define BRPHY1GV2_PHYCONTROL_STATE_BRANCH_CTL_1_STATE_SHIFT (8U)
#define BRPHY1GV2_PHYCONTROL_STATE_BRANCH_CTL_0_STATE_MASK (0xffU)
#define BRPHY1GV2_PHYCONTROL_STATE_BRANCH_CTL_0_STATE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PHYCONTROL_BRANCH_COND_CTL_TYPE;
#define BRPHY1GV2_PHYCONTROL_BRANCH_COND_CTL_TIMER_SEL_MASK (0x8000U)
#define BRPHY1GV2_PHYCONTROL_BRANCH_COND_CTL_TIMER_SEL_SHIFT (15U)
#define BRPHY1GV2_PHYCONTROL_BRANCH_COND_CTL_OPERATOR_SEL_MASK (0x4000U)
#define BRPHY1GV2_PHYCONTROL_BRANCH_COND_CTL_OPERATOR_SEL_SHIFT (14U)
#define BRPHY1GV2_PHYCONTROL_BRANCH_COND_CTL_POLARITY_1_INV_SEL_MASK (0x2000U)
#define BRPHY1GV2_PHYCONTROL_BRANCH_COND_CTL_POLARITY_1_INV_SEL_SHIFT (13U)
#define BRPHY1GV2_PHYCONTROL_BRANCH_COND_CTL_CONDITION_1_MASK (0x1f80U)
#define BRPHY1GV2_PHYCONTROL_BRANCH_COND_CTL_CONDITION_1_SHIFT (7U)
#define BRPHY1GV2_PHYCONTROL_BRANCH_COND_CTL_POLARITY_0_INV_SEL_MASK (0x40U)
#define BRPHY1GV2_PHYCONTROL_BRANCH_COND_CTL_POLARITY_0_INV_SEL_SHIFT (6U)
#define BRPHY1GV2_PHYCONTROL_BRANCH_COND_CTL_CONDITION_0_MASK (0x3fU)
#define BRPHY1GV2_PHYCONTROL_BRANCH_COND_CTL_CONDITION_0_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PHYCONTROL_STATE_OUTPUT_TYPE;
#define BRPHY1GV2_PHYCONTROL_STATE_OUTPUT_MASK (0xffffU)
#define BRPHY1GV2_PHYCONTROL_STATE_OUTPUT_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PHYCONTROL_STATE_OUTPUT_8B_TYPE;
#define BRPHY1GV2_PHYCONTROL_STATE_OUTPUT_8B_MASK (0xffU)
#define BRPHY1GV2_PHYCONTROL_STATE_OUTPUT_8B_SHIFT (0U)




typedef volatile struct sBRPHY1GV2_PHYCONTROL_RDBType {
    BRPHY1GV2_PHYCONTROL_RESERVED_TYPE rsvd0[192]; /* OFFSET: 0x0 */
    BRPHY1GV2_PHYCONTROL_PATCH_STATE_CTL_TYPE patch_state_ctl_0; /* OFFSET: 0xc0 */
    BRPHY1GV2_PHYCONTROL_RESERVED_TYPE rsvd1[134]; /* OFFSET: 0xc2 */
    BRPHY1GV2_PHYCONTROL_TC1_DCQ_SQI_TYPE tc1_dcq_sqi; /* OFFSET: 0x148 */
    BRPHY1GV2_PHYCONTROL_RESERVED_TYPE rsvd2[2]; /* OFFSET: 0x14a */
    BRPHY1GV2_PHYCONTROL_T1DST0_TYPE tc1_dcq_sqi_threshold_0; /* OFFSET: 0x14c */
    BRPHY1GV2_PHYCONTROL_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0x14e */
    BRPHY1GV2_PHYCONTROL_T1DST1_TYPE tc1_dcq_sqi_threshold_1; /* OFFSET: 0x150 */
    BRPHY1GV2_PHYCONTROL_RESERVED_TYPE rsvd4[2]; /* OFFSET: 0x152 */
    BRPHY1GV2_PHYCONTROL_T1DST2_TYPE tc1_dcq_sqi_threshold_2; /* OFFSET: 0x154 */
    BRPHY1GV2_PHYCONTROL_RESERVED_TYPE rsvd5[2]; /* OFFSET: 0x156 */
    BRPHY1GV2_PHYCONTROL_T1DST3_TYPE tc1_dcq_sqi_threshold_3; /* OFFSET: 0x158 */
    BRPHY1GV2_PHYCONTROL_RESERVED_TYPE rsvd6[2]; /* OFFSET: 0x15a */
    BRPHY1GV2_PHYCONTROL_T1DST4_TYPE tc1_dcq_sqi_threshold_4; /* OFFSET: 0x15c */
    BRPHY1GV2_PHYCONTROL_RESERVED_TYPE rsvd7[2]; /* OFFSET: 0x15e */
    BRPHY1GV2_PHYCONTROL_T1DST5_TYPE tc1_dcq_sqi_threshold_5; /* OFFSET: 0x160 */
    BRPHY1GV2_PHYCONTROL_RESERVED_TYPE rsvd8[2]; /* OFFSET: 0x162 */
    BRPHY1GV2_PHYCONTROL_T1DST6_TYPE tc1_dcq_sqi_threshold_6; /* OFFSET: 0x164 */
    BRPHY1GV2_PHYCONTROL_RESERVED_TYPE rsvd9[666]; /* OFFSET: 0x166 */
    BRPHY1GV2_PHYCONTROL_STATE_BRANCH_CTL_TYPE state_e0_branch_ctl; /* OFFSET: 0x400 */
    BRPHY1GV2_PHYCONTROL_RESERVED_TYPE rsvd10[2]; /* OFFSET: 0x402 */
    BRPHY1GV2_PHYCONTROL_BRANCH_COND_CTL_TYPE state_e0_branch_0_cond_ctl; /* OFFSET: 0x404 */
    BRPHY1GV2_PHYCONTROL_RESERVED_TYPE rsvd11[2]; /* OFFSET: 0x406 */
    BRPHY1GV2_PHYCONTROL_BRANCH_COND_CTL_TYPE state_e0_branch_1_cond_ctl; /* OFFSET: 0x408 */
    BRPHY1GV2_PHYCONTROL_RESERVED_TYPE rsvd12[2]; /* OFFSET: 0x40a */
    BRPHY1GV2_PHYCONTROL_STATE_OUTPUT_TYPE state_e0_output_0; /* OFFSET: 0x40c */
    BRPHY1GV2_PHYCONTROL_RESERVED_TYPE rsvd13[2]; /* OFFSET: 0x40e */
    BRPHY1GV2_PHYCONTROL_STATE_OUTPUT_TYPE state_e0_output_1; /* OFFSET: 0x410 */
    BRPHY1GV2_PHYCONTROL_RESERVED_TYPE rsvd14[2]; /* OFFSET: 0x412 */
    BRPHY1GV2_PHYCONTROL_STATE_OUTPUT_TYPE state_e0_output_2; /* OFFSET: 0x414 */
    BRPHY1GV2_PHYCONTROL_RESERVED_TYPE rsvd15[2]; /* OFFSET: 0x416 */
    BRPHY1GV2_PHYCONTROL_STATE_OUTPUT_TYPE state_e0_output_3; /* OFFSET: 0x418 */
    BRPHY1GV2_PHYCONTROL_RESERVED_TYPE rsvd16[2]; /* OFFSET: 0x41a */
    BRPHY1GV2_PHYCONTROL_STATE_OUTPUT_8B_TYPE state_e0_output_4; /* OFFSET: 0x41c */
    BRPHY1GV2_PHYCONTROL_RESERVED_TYPE rsvd17[4060]; /* OFFSET: 0x41e */
} BRPHY1GV2_PHYCONTROL_RDBType;


#define BRPHY0_1G_PHYCONTROL_BASE       (0xE0560000UL)



#define BRPHY1GV2_PHYCONTROL_MAX_HW_ID  (1UL)


#define BRPHY1GV2_SQI_CONST0            (0x00C3U)


#define BRPHY1GV2_SQI_CONST1            (0x009BU)


#define BRPHY1GV2_SQI_CONST2            (0x007BU)


#define BRPHY1GV2_SQI_CONST3            (0x0062U)


#define BRPHY1GV2_SQI_CONST4            (0x004EU)


#define BRPHY1GV2_SQI_CONST5            (0x003EU)


#define BRPHY1GV2_SQI_CONST6            (0x0031U)


#define BRPHY1GV2_PHYC_PATCH_CONST1     (0x1433U)


#define BRPHY1GV2_PHYC_PATCH_CONST2     (0x0010U)


#define BRPHY1GV2_PHYC_PATCH_CONST3     (0x0048U)


#define BRPHY1GV2_PHYC_PATCH_CONST4     (0x7150U)


#define BRPHY1GV2_PHYC_PATCH_CONST5     (0xBF04U)


#define BRPHY1GV2_PHYC_PATCH_CONST6     (0x2100U)


#define BRPHY1GV2_PHYC_PATCH_CONST7     (0x2189U)


#define BRPHY1GV2_PHYC_PATCH_CONST8     (0x0000U)


#define BRPHY1GV2_PHYC_PATCH_CONST9     (0xE031U)

#endif /* BRPHY1GV2_PHYCONTROL_RDB_H */
