/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file brphy1gv2_tx_channel_rdb.h
    @brief RDB File for BRPHY1GV2_TX_CHANNEL

    @version BCM89580_A0_20230125_RDB
*/

#ifndef BRPHY1GV2_TX_CHANNEL_RDB_H
#define BRPHY1GV2_TX_CHANNEL_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t BRPHY1GV2_TX_CHANNEL_CTL_A_TYPE;
#define BRPHY1GV2_TX_CHANNEL_CTL_A_AFE_TX_T0_T1_SYM_INVERT_MASK (0x10U)
#define BRPHY1GV2_TX_CHANNEL_CTL_A_AFE_TX_T0_T1_SYM_INVERT_SHIFT (4U)
#define BRPHY1GV2_TX_CHANNEL_CTL_A_ATT0T1SBRO_MASK (0x8U)
#define BRPHY1GV2_TX_CHANNEL_CTL_A_ATT0T1SBRO_SHIFT (3U)
#define BRPHY1GV2_TX_CHANNEL_CTL_A_AFE_TX_T0_T1_SYM_SWAP_MASK (0x4U)
#define BRPHY1GV2_TX_CHANNEL_CTL_A_AFE_TX_T0_T1_SYM_SWAP_SHIFT (2U)
#define BRPHY1GV2_TX_CHANNEL_CTL_A_LINK_SYNC_T0_T1_SYM_SWAP_MASK (0x2U)
#define BRPHY1GV2_TX_CHANNEL_CTL_A_LINK_SYNC_T0_T1_SYM_SWAP_SHIFT (1U)
#define BRPHY1GV2_TX_CHANNEL_CTL_A_PCS_T0_T1_SYM_SWAP_MASK (0x1U)
#define BRPHY1GV2_TX_CHANNEL_CTL_A_PCS_T0_T1_SYM_SWAP_SHIFT (0U)




typedef uint8_t BRPHY1GV2_TX_CHANNEL_RESERVED_TYPE;




typedef uint16_t BRPHY1GV2_TX_CHANNEL_CTL_B_TYPE;
#define BRPHY1GV2_TX_CHANNEL_CTL_B_PRFBYP_1G_MASK (0x8000U)
#define BRPHY1GV2_TX_CHANNEL_CTL_B_PRFBYP_1G_SHIFT (15U)
#define BRPHY1GV2_TX_CHANNEL_CTL_B_DISABLE_PCS_RESIDUE_BLOCK_MASK (0x4000U)
#define BRPHY1GV2_TX_CHANNEL_CTL_B_DISABLE_PCS_RESIDUE_BLOCK_SHIFT (14U)
#define BRPHY1GV2_TX_CHANNEL_CTL_B_HALFOUT_MASK (0x2000U)
#define BRPHY1GV2_TX_CHANNEL_CTL_B_HALFOUT_SHIFT (13U)
#define BRPHY1GV2_TX_CHANNEL_CTL_B_BR_RATE_MASK (0x1c00U)
#define BRPHY1GV2_TX_CHANNEL_CTL_B_BR_RATE_SHIFT (10U)
#define BRPHY1GV2_TX_CHANNEL_CTL_B_BR_PAIR_MASK (0x300U)
#define BRPHY1GV2_TX_CHANNEL_CTL_B_BR_PAIR_SHIFT (8U)
#define BRPHY1GV2_TX_CHANNEL_CTL_B_BR_EDGE_RATE_AUTONEG_MASK (0xc0U)
#define BRPHY1GV2_TX_CHANNEL_CTL_B_BR_EDGE_RATE_AUTONEG_SHIFT (6U)
#define BRPHY1GV2_TX_CHANNEL_CTL_B_AGC_EN_MASK (0x20U)
#define BRPHY1GV2_TX_CHANNEL_CTL_B_AGC_EN_SHIFT (5U)
#define BRPHY1GV2_TX_CHANNEL_CTL_B_PRFBYP_MASK (0x10U)
#define BRPHY1GV2_TX_CHANNEL_CTL_B_PRFBYP_SHIFT (4U)
#define BRPHY1GV2_TX_CHANNEL_CTL_B_TX_CHANNEL_PWRDWN_MASK (0x8U)
#define BRPHY1GV2_TX_CHANNEL_CTL_B_TX_CHANNEL_PWRDWN_SHIFT (3U)
#define BRPHY1GV2_TX_CHANNEL_CTL_B_HYBMODE_MASK (0x4U)
#define BRPHY1GV2_TX_CHANNEL_CTL_B_HYBMODE_SHIFT (2U)
#define BRPHY1GV2_TX_CHANNEL_CTL_B_BR_EDGE_RATE_MASK (0x3U)
#define BRPHY1GV2_TX_CHANNEL_CTL_B_BR_EDGE_RATE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_TX_CHANNEL_CTL_C_TYPE;
#define BRPHY1GV2_TX_CHANNEL_CTL_C_TX_CHANNEL_TEMPLATE_MODE_MASK (0x10U)
#define BRPHY1GV2_TX_CHANNEL_CTL_C_TX_CHANNEL_TEMPLATE_MODE_SHIFT (4U)
#define BRPHY1GV2_TX_CHANNEL_CTL_C_TX_CHANNEL_TESTMODE_ANA_MASK (0x8U)
#define BRPHY1GV2_TX_CHANNEL_CTL_C_TX_CHANNEL_TESTMODE_ANA_SHIFT (3U)
#define BRPHY1GV2_TX_CHANNEL_CTL_C_TX_CHANNEL_TESTMODE_MASK (0x4U)
#define BRPHY1GV2_TX_CHANNEL_CTL_C_TX_CHANNEL_TESTMODE_SHIFT (2U)
#define BRPHY1GV2_TX_CHANNEL_CTL_C_DISABLE_TX_IN_PCS_LPBK_MASK (0x1U)
#define BRPHY1GV2_TX_CHANNEL_CTL_C_DISABLE_TX_IN_PCS_LPBK_SHIFT (0U)




typedef uint16_t BRPHY1GV2_TX_CHANNEL_TEMPLATE_A_TYPE;
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_A_CYC_2_MASK (0x7c00U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_A_CYC_2_SHIFT (10U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_A_CYC_1_MASK (0x3e0U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_A_CYC_1_SHIFT (5U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_A_CYC_0_MASK (0x1fU)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_A_CYC_0_SHIFT (0U)




typedef uint16_t BRPHY1GV2_TX_CHANNEL_TEMPLATE_B_TYPE;
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_B_CYC_5_MASK (0x7c00U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_B_CYC_5_SHIFT (10U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_B_CYC_4_MASK (0x3e0U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_B_CYC_4_SHIFT (5U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_B_CYC_3_MASK (0x1fU)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_B_CYC_3_SHIFT (0U)




typedef uint16_t BRPHY1GV2_TX_CHANNEL_TEMPLATE_C_TYPE;
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_C_CYC_8_MASK (0x7c00U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_C_CYC_8_SHIFT (10U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_C_CYC_7_MASK (0x3e0U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_C_CYC_7_SHIFT (5U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_C_CYC_6_MASK (0x1fU)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_C_CYC_6_SHIFT (0U)




typedef uint16_t BRPHY1GV2_TX_CHANNEL_TEMPLATE_D_TYPE;
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_D_CYC_11_MASK (0x7c00U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_D_CYC_11_SHIFT (10U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_D_CYC_10_MASK (0x3e0U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_D_CYC_10_SHIFT (5U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_D_CYC_9_MASK (0x1fU)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_D_CYC_9_SHIFT (0U)




typedef uint16_t BRPHY1GV2_TX_CHANNEL_TEMPLATE_E_TYPE;
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_E_CYC_14_MASK (0x7c00U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_E_CYC_14_SHIFT (10U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_E_CYC_13_MASK (0x3e0U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_E_CYC_13_SHIFT (5U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_E_CYC_12_MASK (0x1fU)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_E_CYC_12_SHIFT (0U)




typedef uint16_t BRPHY1GV2_TX_CHANNEL_TEMPLATE_F_TYPE;
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_F_CYC_17_MASK (0x7c00U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_F_CYC_17_SHIFT (10U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_F_CYC_16_MASK (0x3e0U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_F_CYC_16_SHIFT (5U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_F_CYC_15_MASK (0x1fU)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_F_CYC_15_SHIFT (0U)




typedef uint16_t BRPHY1GV2_TX_CHANNEL_TEMPLATE_G_TYPE;
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_G_CYC_20_MASK (0x7c00U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_G_CYC_20_SHIFT (10U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_G_CYC_19_MASK (0x3e0U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_G_CYC_19_SHIFT (5U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_G_CYC_18_MASK (0x1fU)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_G_CYC_18_SHIFT (0U)




typedef uint16_t BRPHY1GV2_TX_CHANNEL_TEMPLATE_H_TYPE;
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_H_CYC_23_MASK (0x7c00U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_H_CYC_23_SHIFT (10U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_H_CYC_22_MASK (0x3e0U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_H_CYC_22_SHIFT (5U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_H_CYC_21_MASK (0x1fU)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_H_CYC_21_SHIFT (0U)




typedef uint16_t BRPHY1GV2_TX_CHANNEL_TEMPLATE_I_TYPE;
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_I_CYC_26_MASK (0x7c00U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_I_CYC_26_SHIFT (10U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_I_CYC_25_MASK (0x3e0U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_I_CYC_25_SHIFT (5U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_I_CYC_24_MASK (0x1fU)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_I_CYC_24_SHIFT (0U)




typedef uint16_t BRPHY1GV2_TX_CHANNEL_TEMPLATE_J_TYPE;
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_J_CYC_29_MASK (0x7c00U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_J_CYC_29_SHIFT (10U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_J_CYC_28_MASK (0x3e0U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_J_CYC_28_SHIFT (5U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_J_CYC_27_MASK (0x1fU)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_J_CYC_27_SHIFT (0U)




typedef uint16_t BRPHY1GV2_TX_CHANNEL_TEMPLATE_K_TYPE;
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_K_CYC_31_MASK (0x3e0U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_K_CYC_31_SHIFT (5U)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_K_CYC_30_MASK (0x1fU)
#define BRPHY1GV2_TX_CHANNEL_TEMPLATE_K_CYC_30_SHIFT (0U)




typedef uint16_t BRPHY1GV2_TX_CHANNEL_SPARE_END_ADDR_TYPE;
#define BRPHY1GV2_TX_CHANNEL_SPARE_END_ADDR_MASK (0xffffU)
#define BRPHY1GV2_TX_CHANNEL_SPARE_END_ADDR_SHIFT (0U)




typedef volatile struct sBRPHY1GV2_TX_CHANNEL_RDBType {
    BRPHY1GV2_TX_CHANNEL_CTL_A_TYPE tx_channel_ctl_a; /* OFFSET: 0x0 */
    BRPHY1GV2_TX_CHANNEL_RESERVED_TYPE rsvd0[2]; /* OFFSET: 0x2 */
    BRPHY1GV2_TX_CHANNEL_CTL_B_TYPE tx_channel_ctl_b; /* OFFSET: 0x4 */
    BRPHY1GV2_TX_CHANNEL_RESERVED_TYPE rsvd1[2]; /* OFFSET: 0x6 */
    BRPHY1GV2_TX_CHANNEL_CTL_C_TYPE tx_channel_ctl_c; /* OFFSET: 0x8 */
    BRPHY1GV2_TX_CHANNEL_RESERVED_TYPE rsvd2[2]; /* OFFSET: 0xa */
    BRPHY1GV2_TX_CHANNEL_TEMPLATE_A_TYPE tx_channel_template_a; /* OFFSET: 0xc */
    BRPHY1GV2_TX_CHANNEL_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0xe */
    BRPHY1GV2_TX_CHANNEL_TEMPLATE_B_TYPE tx_channel_template_b; /* OFFSET: 0x10 */
    BRPHY1GV2_TX_CHANNEL_RESERVED_TYPE rsvd4[2]; /* OFFSET: 0x12 */
    BRPHY1GV2_TX_CHANNEL_TEMPLATE_C_TYPE tx_channel_template_c; /* OFFSET: 0x14 */
    BRPHY1GV2_TX_CHANNEL_RESERVED_TYPE rsvd5[2]; /* OFFSET: 0x16 */
    BRPHY1GV2_TX_CHANNEL_TEMPLATE_D_TYPE tx_channel_template_d; /* OFFSET: 0x18 */
    BRPHY1GV2_TX_CHANNEL_RESERVED_TYPE rsvd6[2]; /* OFFSET: 0x1a */
    BRPHY1GV2_TX_CHANNEL_TEMPLATE_E_TYPE tx_channel_template_e; /* OFFSET: 0x1c */
    BRPHY1GV2_TX_CHANNEL_RESERVED_TYPE rsvd7[2]; /* OFFSET: 0x1e */
    BRPHY1GV2_TX_CHANNEL_TEMPLATE_F_TYPE tx_channel_template_f; /* OFFSET: 0x20 */
    BRPHY1GV2_TX_CHANNEL_RESERVED_TYPE rsvd8[2]; /* OFFSET: 0x22 */
    BRPHY1GV2_TX_CHANNEL_TEMPLATE_G_TYPE tx_channel_template_g; /* OFFSET: 0x24 */
    BRPHY1GV2_TX_CHANNEL_RESERVED_TYPE rsvd9[2]; /* OFFSET: 0x26 */
    BRPHY1GV2_TX_CHANNEL_TEMPLATE_H_TYPE tx_channel_template_h; /* OFFSET: 0x28 */
    BRPHY1GV2_TX_CHANNEL_RESERVED_TYPE rsvd10[2]; /* OFFSET: 0x2a */
    BRPHY1GV2_TX_CHANNEL_TEMPLATE_I_TYPE tx_channel_template_i; /* OFFSET: 0x2c */
    BRPHY1GV2_TX_CHANNEL_RESERVED_TYPE rsvd11[2]; /* OFFSET: 0x2e */
    BRPHY1GV2_TX_CHANNEL_TEMPLATE_J_TYPE tx_channel_template_j; /* OFFSET: 0x30 */
    BRPHY1GV2_TX_CHANNEL_RESERVED_TYPE rsvd12[2]; /* OFFSET: 0x32 */
    BRPHY1GV2_TX_CHANNEL_TEMPLATE_K_TYPE tx_channel_template_k; /* OFFSET: 0x34 */
    BRPHY1GV2_TX_CHANNEL_RESERVED_TYPE rsvd13[962]; /* OFFSET: 0x36 */
    BRPHY1GV2_TX_CHANNEL_SPARE_END_ADDR_TYPE spare_end_addr; /* OFFSET: 0x3f8 */
} BRPHY1GV2_TX_CHANNEL_RDBType;


#define BRPHY0_1G_TX_CHANNEL_BASE       (0xE0565400UL)



#define BRPHY1GV2_TX_CHANNEL_MAX_HW_ID  (1UL)

#endif /* BRPHY1GV2_TX_CHANNEL_RDB_H */
