/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file brphy1gv2_pma_pmd_ieee_rdb.h
    @brief RDB File for BRPHY1GV2_PMA_PMD_IEEE

    @version BCM89580_A0_20230125_RDB
*/

#ifndef BRPHY1GV2_PMA_PMD_IEEE_RDB_H
#define BRPHY1GV2_PMA_PMD_IEEE_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t BRPHY1GV2_PMA_PMD_IEEE_CONTROL_REG1_TYPE;
#define BRPHY1GV2_PMA_PMD_IEEE_CONTROL_REG1_RESET_MASK (0x8000U)
#define BRPHY1GV2_PMA_PMD_IEEE_CONTROL_REG1_RESET_SHIFT (15U)
#define BRPHY1GV2_PMA_PMD_IEEE_CONTROL_REG1_SPEED_SEL_0_MASK (0x2000U)
#define BRPHY1GV2_PMA_PMD_IEEE_CONTROL_REG1_SPEED_SEL_0_SHIFT (13U)
#define BRPHY1GV2_PMA_PMD_IEEE_CONTROL_REG1_LOW_POWER_MASK (0x800U)
#define BRPHY1GV2_PMA_PMD_IEEE_CONTROL_REG1_LOW_POWER_SHIFT (11U)
#define BRPHY1GV2_PMA_PMD_IEEE_CONTROL_REG1_SPEED_SEL_1_MASK (0x40U)
#define BRPHY1GV2_PMA_PMD_IEEE_CONTROL_REG1_SPEED_SEL_1_SHIFT (6U)
#define BRPHY1GV2_PMA_PMD_IEEE_CONTROL_REG1_SPEED_SELECT_MASK (0x3cU)
#define BRPHY1GV2_PMA_PMD_IEEE_CONTROL_REG1_SPEED_SELECT_SHIFT (2U)
#define BRPHY1GV2_PMA_PMD_IEEE_CONTROL_REG1_REMOTE_LOOPBACK_MASK (0x2U)
#define BRPHY1GV2_PMA_PMD_IEEE_CONTROL_REG1_REMOTE_LOOPBACK_SHIFT (1U)
#define BRPHY1GV2_PMA_PMD_IEEE_CONTROL_REG1_LOCAL_LOOPBACK_MASK (0x1U)
#define BRPHY1GV2_PMA_PMD_IEEE_CONTROL_REG1_LOCAL_LOOPBACK_SHIFT (0U)




typedef uint8_t BRPHY1GV2_PMA_PMD_IEEE_RESERVED_TYPE;




typedef uint16_t BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG1_TYPE;
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG1_PIASA_MASK (0x200U)
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG1_PIASA_SHIFT (9U)
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG1_PEASA_MASK (0x100U)
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG1_PEASA_SHIFT (8U)
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG1_FAULT_MASK (0x80U)
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG1_FAULT_SHIFT (7U)
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG1_RECEIVE_LINK_STATUS_MASK (0x4U)
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG1_RECEIVE_LINK_STATUS_SHIFT (2U)
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG1_LOW_POWER_ABILITY_MASK (0x2U)
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG1_LOW_POWER_ABILITY_SHIFT (1U)




typedef uint16_t BRPHY1GV2_PMA_PMD_IEEE_DEVICE_ID_REG0_TYPE;
#define BRPHY1GV2_PMA_PMD_IEEE_DEVICE_ID_REG0_ID0_MASK (0xffffU)
#define BRPHY1GV2_PMA_PMD_IEEE_DEVICE_ID_REG0_ID0_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PMA_PMD_IEEE_DEVICE_ID_REG1_TYPE;
#define BRPHY1GV2_PMA_PMD_IEEE_DEVICE_ID_REG1_ID1_MASK (0xffffU)
#define BRPHY1GV2_PMA_PMD_IEEE_DEVICE_ID_REG1_ID1_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PMA_PMD_IEEE_PPSA_TYPE;
#define BRPHY1GV2_PMA_PMD_IEEE_PPSA_CAPABLE_100G_MASK (0x200U)
#define BRPHY1GV2_PMA_PMD_IEEE_PPSA_CAPABLE_100G_SHIFT (9U)
#define BRPHY1GV2_PMA_PMD_IEEE_PPSA_CAPABLE_40G_MASK (0x100U)
#define BRPHY1GV2_PMA_PMD_IEEE_PPSA_CAPABLE_40G_SHIFT (8U)
#define BRPHY1GV2_PMA_PMD_IEEE_PPSA_CAPABLE_10_1G_MASK (0x80U)
#define BRPHY1GV2_PMA_PMD_IEEE_PPSA_CAPABLE_10_1G_SHIFT (7U)
#define BRPHY1GV2_PMA_PMD_IEEE_PPSA_CAPABLE_10M_MASK (0x40U)
#define BRPHY1GV2_PMA_PMD_IEEE_PPSA_CAPABLE_10M_SHIFT (6U)
#define BRPHY1GV2_PMA_PMD_IEEE_PPSA_CAPABLE_100M_MASK (0x20U)
#define BRPHY1GV2_PMA_PMD_IEEE_PPSA_CAPABLE_100M_SHIFT (5U)
#define BRPHY1GV2_PMA_PMD_IEEE_PPSA_CAPABLE_1000M_MASK (0x10U)
#define BRPHY1GV2_PMA_PMD_IEEE_PPSA_CAPABLE_1000M_SHIFT (4U)
#define BRPHY1GV2_PMA_PMD_IEEE_PPSA_CAPABLE_10PASS_TS_MASK (0x4U)
#define BRPHY1GV2_PMA_PMD_IEEE_PPSA_CAPABLE_10PASS_TS_SHIFT (2U)
#define BRPHY1GV2_PMA_PMD_IEEE_PPSA_CAPABLE_2BASE_TL_MASK (0x2U)
#define BRPHY1GV2_PMA_PMD_IEEE_PPSA_CAPABLE_2BASE_TL_SHIFT (1U)
#define BRPHY1GV2_PMA_PMD_IEEE_PPSA_CAPABLE_10G_MASK (0x1U)
#define BRPHY1GV2_PMA_PMD_IEEE_PPSA_CAPABLE_10G_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PMA_PMD_IEEE_DIPR0_TYPE;
#define BRPHY1GV2_PMA_PMD_IEEE_DIPR0_SEPARATED_PMA_4_PRESENT_MASK (0x800U)
#define BRPHY1GV2_PMA_PMD_IEEE_DIPR0_SEPARATED_PMA_4_PRESENT_SHIFT (11U)
#define BRPHY1GV2_PMA_PMD_IEEE_DIPR0_SPP3P_MASK (0x400U)
#define BRPHY1GV2_PMA_PMD_IEEE_DIPR0_SPP3P_SHIFT (10U)
#define BRPHY1GV2_PMA_PMD_IEEE_DIPR0_SEPARATED_PMA_2_PRESENT_MASK (0x200U)
#define BRPHY1GV2_PMA_PMD_IEEE_DIPR0_SEPARATED_PMA_2_PRESENT_SHIFT (9U)
#define BRPHY1GV2_PMA_PMD_IEEE_DIPR0_SEPARATED_PMA_1_PRESENT_MASK (0x100U)
#define BRPHY1GV2_PMA_PMD_IEEE_DIPR0_SEPARATED_PMA_1_PRESENT_SHIFT (8U)
#define BRPHY1GV2_PMA_PMD_IEEE_DIPR0_AUTO_NEGOTIATION_PRESENT_MASK (0x80U)
#define BRPHY1GV2_PMA_PMD_IEEE_DIPR0_AUTO_NEGOTIATION_PRESENT_SHIFT (7U)
#define BRPHY1GV2_PMA_PMD_IEEE_DIPR0_TC_PRESENT_MASK (0x40U)
#define BRPHY1GV2_PMA_PMD_IEEE_DIPR0_TC_PRESENT_SHIFT (6U)
#define BRPHY1GV2_PMA_PMD_IEEE_DIPR0_DTE_XS_PRESENT_MASK (0x20U)
#define BRPHY1GV2_PMA_PMD_IEEE_DIPR0_DTE_XS_PRESENT_SHIFT (5U)
#define BRPHY1GV2_PMA_PMD_IEEE_DIPR0_PHY_XS_PRESENT_MASK (0x10U)
#define BRPHY1GV2_PMA_PMD_IEEE_DIPR0_PHY_XS_PRESENT_SHIFT (4U)
#define BRPHY1GV2_PMA_PMD_IEEE_DIPR0_PCS_PRESENT_MASK (0x8U)
#define BRPHY1GV2_PMA_PMD_IEEE_DIPR0_PCS_PRESENT_SHIFT (3U)
#define BRPHY1GV2_PMA_PMD_IEEE_DIPR0_WIS_PRESENT_MASK (0x4U)
#define BRPHY1GV2_PMA_PMD_IEEE_DIPR0_WIS_PRESENT_SHIFT (2U)
#define BRPHY1GV2_PMA_PMD_IEEE_DIPR0_PMD_PMA_PRESENT_MASK (0x2U)
#define BRPHY1GV2_PMA_PMD_IEEE_DIPR0_PMD_PMA_PRESENT_SHIFT (1U)
#define BRPHY1GV2_PMA_PMD_IEEE_DIPR0_CLAUSE_22_REGISTERS_PRESENT_MASK (0x1U)
#define BRPHY1GV2_PMA_PMD_IEEE_DIPR0_CLAUSE_22_REGISTERS_PRESENT_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PMA_PMD_IEEE_DIPR1_TYPE;
#define BRPHY1GV2_PMA_PMD_IEEE_DIPR1_VSD2P_MASK (0x8000U)
#define BRPHY1GV2_PMA_PMD_IEEE_DIPR1_VSD2P_SHIFT (15U)
#define BRPHY1GV2_PMA_PMD_IEEE_DIPR1_VSD1P_MASK (0x4000U)
#define BRPHY1GV2_PMA_PMD_IEEE_DIPR1_VSD1P_SHIFT (14U)
#define BRPHY1GV2_PMA_PMD_IEEE_DIPR1_CLAUSE_22_EXTENSION_PRESENT_MASK (0x2000U)
#define BRPHY1GV2_PMA_PMD_IEEE_DIPR1_CLAUSE_22_EXTENSION_PRESENT_SHIFT (13U)




typedef uint16_t BRPHY1GV2_PMA_PMD_IEEE_CONTROL_REG2_TYPE;
#define BRPHY1GV2_PMA_PMD_IEEE_CONTROL_REG2_PIASE_MASK (0x200U)
#define BRPHY1GV2_PMA_PMD_IEEE_CONTROL_REG2_PIASE_SHIFT (9U)
#define BRPHY1GV2_PMA_PMD_IEEE_CONTROL_REG2_PEASE_MASK (0x100U)
#define BRPHY1GV2_PMA_PMD_IEEE_CONTROL_REG2_PEASE_SHIFT (8U)
#define BRPHY1GV2_PMA_PMD_IEEE_CONTROL_REG2_PPTS_MASK (0x3fU)
#define BRPHY1GV2_PMA_PMD_IEEE_CONTROL_REG2_PPTS_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG2_TYPE;
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG2_DEVICE_PRESENT_MASK (0xc000U)
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG2_DEVICE_PRESENT_SHIFT (14U)
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG2_TRANSMIT_FAULT_ABILITY_MASK (0x2000U)
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG2_TRANSMIT_FAULT_ABILITY_SHIFT (13U)
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG2_RECEIVE_FAULT_ABILITY_MASK (0x1000U)
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG2_RECEIVE_FAULT_ABILITY_SHIFT (12U)
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG2_TRANSMI_FAULT_MASK (0x800U)
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG2_TRANSMI_FAULT_SHIFT (11U)
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG2_RECEIVE_FAULT_MASK (0x400U)
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG2_RECEIVE_FAULT_SHIFT (10U)
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG2_EXTENDED_ABILITIES_MASK (0x200U)
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG2_EXTENDED_ABILITIES_SHIFT (9U)
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG2_PTDA_MASK (0x100U)
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG2_PTDA_SHIFT (8U)
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG2_ABILITY_10GBASE_SR_MASK (0x80U)
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG2_ABILITY_10GBASE_SR_SHIFT (7U)
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG2_ABILITY_10GBASE_LR_MASK (0x40U)
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG2_ABILITY_10GBASE_LR_SHIFT (6U)
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG2_ABILITY_10GBASE_ER_MASK (0x20U)
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG2_ABILITY_10GBASE_ER_SHIFT (5U)
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG2_ABILITY_10GBASE_LX4_MASK (0x10U)
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG2_ABILITY_10GBASE_LX4_SHIFT (4U)
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG2_ABILITY_10GBASE_SW_MASK (0x8U)
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG2_ABILITY_10GBASE_SW_SHIFT (3U)
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG2_ABILITY_10GBASE_LW_MASK (0x4U)
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG2_ABILITY_10GBASE_LW_SHIFT (2U)
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG2_ABILITY_10GBASE_EW_MASK (0x2U)
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG2_ABILITY_10GBASE_EW_SHIFT (1U)
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG2_PLLA_MASK (0x1U)
#define BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG2_PLLA_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PMA_PMD_IEEE_TDR_TYPE;
#define BRPHY1GV2_PMA_PMD_IEEE_TDR_PMD_TRANSMIT_DISABLE_9_MASK (0x400U)
#define BRPHY1GV2_PMA_PMD_IEEE_TDR_PMD_TRANSMIT_DISABLE_9_SHIFT (10U)
#define BRPHY1GV2_PMA_PMD_IEEE_TDR_PMD_TRANSMIT_DISABLE_8_MASK (0x200U)
#define BRPHY1GV2_PMA_PMD_IEEE_TDR_PMD_TRANSMIT_DISABLE_8_SHIFT (9U)
#define BRPHY1GV2_PMA_PMD_IEEE_TDR_PMD_TRANSMIT_DISABLE_7_MASK (0x100U)
#define BRPHY1GV2_PMA_PMD_IEEE_TDR_PMD_TRANSMIT_DISABLE_7_SHIFT (8U)
#define BRPHY1GV2_PMA_PMD_IEEE_TDR_PMD_TRANSMIT_DISABLE_6_MASK (0x80U)
#define BRPHY1GV2_PMA_PMD_IEEE_TDR_PMD_TRANSMIT_DISABLE_6_SHIFT (7U)
#define BRPHY1GV2_PMA_PMD_IEEE_TDR_PMD_TRANSMIT_DISABLE_5_MASK (0x40U)
#define BRPHY1GV2_PMA_PMD_IEEE_TDR_PMD_TRANSMIT_DISABLE_5_SHIFT (6U)
#define BRPHY1GV2_PMA_PMD_IEEE_TDR_PMD_TRANSMIT_DISABLE_4_MASK (0x20U)
#define BRPHY1GV2_PMA_PMD_IEEE_TDR_PMD_TRANSMIT_DISABLE_4_SHIFT (5U)
#define BRPHY1GV2_PMA_PMD_IEEE_TDR_PMD_TRANSMIT_DISABLE_3_MASK (0x10U)
#define BRPHY1GV2_PMA_PMD_IEEE_TDR_PMD_TRANSMIT_DISABLE_3_SHIFT (4U)
#define BRPHY1GV2_PMA_PMD_IEEE_TDR_PMD_TRANSMIT_DISABLE_2_MASK (0x8U)
#define BRPHY1GV2_PMA_PMD_IEEE_TDR_PMD_TRANSMIT_DISABLE_2_SHIFT (3U)
#define BRPHY1GV2_PMA_PMD_IEEE_TDR_PMD_TRANSMIT_DISABLE_1_MASK (0x4U)
#define BRPHY1GV2_PMA_PMD_IEEE_TDR_PMD_TRANSMIT_DISABLE_1_SHIFT (2U)
#define BRPHY1GV2_PMA_PMD_IEEE_TDR_PMD_TRANSMIT_DISABLE_0_MASK (0x2U)
#define BRPHY1GV2_PMA_PMD_IEEE_TDR_PMD_TRANSMIT_DISABLE_0_SHIFT (1U)
#define BRPHY1GV2_PMA_PMD_IEEE_TDR_GLOBAL_PMD_TRANSMIT_DISABLE_MASK (0x1U)
#define BRPHY1GV2_PMA_PMD_IEEE_TDR_GLOBAL_PMD_TRANSMIT_DISABLE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PMA_PMD_IEEE_RSDR_TYPE;
#define BRPHY1GV2_PMA_PMD_IEEE_RSDR_PMD_RECEIVE_SIGNAL_DETECT_9_MASK (0x400U)
#define BRPHY1GV2_PMA_PMD_IEEE_RSDR_PMD_RECEIVE_SIGNAL_DETECT_9_SHIFT (10U)
#define BRPHY1GV2_PMA_PMD_IEEE_RSDR_PMD_RECEIVE_SIGNAL_DETECT_8_MASK (0x200U)
#define BRPHY1GV2_PMA_PMD_IEEE_RSDR_PMD_RECEIVE_SIGNAL_DETECT_8_SHIFT (9U)
#define BRPHY1GV2_PMA_PMD_IEEE_RSDR_PMD_RECEIVE_SIGNAL_DETECT_7_MASK (0x100U)
#define BRPHY1GV2_PMA_PMD_IEEE_RSDR_PMD_RECEIVE_SIGNAL_DETECT_7_SHIFT (8U)
#define BRPHY1GV2_PMA_PMD_IEEE_RSDR_PMD_RECEIVE_SIGNAL_DETECT_6_MASK (0x80U)
#define BRPHY1GV2_PMA_PMD_IEEE_RSDR_PMD_RECEIVE_SIGNAL_DETECT_6_SHIFT (7U)
#define BRPHY1GV2_PMA_PMD_IEEE_RSDR_PMD_RECEIVE_SIGNAL_DETECT_5_MASK (0x40U)
#define BRPHY1GV2_PMA_PMD_IEEE_RSDR_PMD_RECEIVE_SIGNAL_DETECT_5_SHIFT (6U)
#define BRPHY1GV2_PMA_PMD_IEEE_RSDR_PMD_RECEIVE_SIGNAL_DETECT_4_MASK (0x20U)
#define BRPHY1GV2_PMA_PMD_IEEE_RSDR_PMD_RECEIVE_SIGNAL_DETECT_4_SHIFT (5U)
#define BRPHY1GV2_PMA_PMD_IEEE_RSDR_PMD_RECEIVE_SIGNAL_DETECT_3_MASK (0x10U)
#define BRPHY1GV2_PMA_PMD_IEEE_RSDR_PMD_RECEIVE_SIGNAL_DETECT_3_SHIFT (4U)
#define BRPHY1GV2_PMA_PMD_IEEE_RSDR_PMD_RECEIVE_SIGNAL_DETECT_2_MASK (0x8U)
#define BRPHY1GV2_PMA_PMD_IEEE_RSDR_PMD_RECEIVE_SIGNAL_DETECT_2_SHIFT (3U)
#define BRPHY1GV2_PMA_PMD_IEEE_RSDR_PMD_RECEIVE_SIGNAL_DETECT_1_MASK (0x4U)
#define BRPHY1GV2_PMA_PMD_IEEE_RSDR_PMD_RECEIVE_SIGNAL_DETECT_1_SHIFT (2U)
#define BRPHY1GV2_PMA_PMD_IEEE_RSDR_PMD_RECEIVE_SIGNAL_DETECT_0_MASK (0x2U)
#define BRPHY1GV2_PMA_PMD_IEEE_RSDR_PMD_RECEIVE_SIGNAL_DETECT_0_SHIFT (1U)
#define BRPHY1GV2_PMA_PMD_IEEE_RSDR_GPRSD_MASK (0x1U)
#define BRPHY1GV2_PMA_PMD_IEEE_RSDR_GPRSD_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PMA_PMD_IEEE_EAR_TYPE;
#define BRPHY1GV2_PMA_PMD_IEEE_EAR_BASET1_EXTENDED_ABILITIES_MASK (0x800U)
#define BRPHY1GV2_PMA_PMD_IEEE_EAR_BASET1_EXTENDED_ABILITIES_SHIFT (11U)
#define BRPHY1GV2_PMA_PMD_IEEE_EAR_ABILITIES_40G_100G_EXTENDED_MASK (0x400U)
#define BRPHY1GV2_PMA_PMD_IEEE_EAR_ABILITIES_40G_100G_EXTENDED_SHIFT (10U)
#define BRPHY1GV2_PMA_PMD_IEEE_EAR_P2MP_ABILITY_MASK (0x200U)
#define BRPHY1GV2_PMA_PMD_IEEE_EAR_P2MP_ABILITY_SHIFT (9U)
#define BRPHY1GV2_PMA_PMD_IEEE_EAR_ABILITY_10BASET_MASK (0x100U)
#define BRPHY1GV2_PMA_PMD_IEEE_EAR_ABILITY_10BASET_SHIFT (8U)
#define BRPHY1GV2_PMA_PMD_IEEE_EAR_ABILITY_100BASETX_MASK (0x80U)
#define BRPHY1GV2_PMA_PMD_IEEE_EAR_ABILITY_100BASETX_SHIFT (7U)
#define BRPHY1GV2_PMA_PMD_IEEE_EAR_ABILITY_1000BASEKX_MASK (0x40U)
#define BRPHY1GV2_PMA_PMD_IEEE_EAR_ABILITY_1000BASEKX_SHIFT (6U)
#define BRPHY1GV2_PMA_PMD_IEEE_EAR_ABILITY_1000BASET_MASK (0x20U)
#define BRPHY1GV2_PMA_PMD_IEEE_EAR_ABILITY_1000BASET_SHIFT (5U)
#define BRPHY1GV2_PMA_PMD_IEEE_EAR_ABILITY_10GBASEKR_MASK (0x10U)
#define BRPHY1GV2_PMA_PMD_IEEE_EAR_ABILITY_10GBASEKR_SHIFT (4U)
#define BRPHY1GV2_PMA_PMD_IEEE_EAR_ABILITY_10GBASEKX4_MASK (0x8U)
#define BRPHY1GV2_PMA_PMD_IEEE_EAR_ABILITY_10GBASEKX4_SHIFT (3U)
#define BRPHY1GV2_PMA_PMD_IEEE_EAR_ABILITY_10GBASET_MASK (0x4U)
#define BRPHY1GV2_PMA_PMD_IEEE_EAR_ABILITY_10GBASET_SHIFT (2U)
#define BRPHY1GV2_PMA_PMD_IEEE_EAR_ABILITY_10GBASELRM_MASK (0x2U)
#define BRPHY1GV2_PMA_PMD_IEEE_EAR_ABILITY_10GBASELRM_SHIFT (1U)
#define BRPHY1GV2_PMA_PMD_IEEE_EAR_ABILITY_10GBASECX4_MASK (0x1U)
#define BRPHY1GV2_PMA_PMD_IEEE_EAR_ABILITY_10GBASECX4_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PMA_PMD_IEEE_PACKAGE_ID_REG0_TYPE;
#define BRPHY1GV2_PMA_PMD_IEEE_PACKAGE_ID_REG0_MASK (0xffffU)
#define BRPHY1GV2_PMA_PMD_IEEE_PACKAGE_ID_REG0_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PMA_PMD_IEEE_PACKAGE_ID_REG1_TYPE;
#define BRPHY1GV2_PMA_PMD_IEEE_PACKAGE_ID_REG1_MASK (0xffffU)
#define BRPHY1GV2_PMA_PMD_IEEE_PACKAGE_ID_REG1_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PMA_PMD_IEEE_B1PPEA_TYPE;
#define BRPHY1GV2_PMA_PMD_IEEE_B1PPEA_ABILITY_1000T1_MASK (0x2U)
#define BRPHY1GV2_PMA_PMD_IEEE_B1PPEA_ABILITY_1000T1_SHIFT (1U)
#define BRPHY1GV2_PMA_PMD_IEEE_B1PPEA_ABILITY_100T1_MASK (0x1U)
#define BRPHY1GV2_PMA_PMD_IEEE_B1PPEA_ABILITY_100T1_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PMA_PMD_IEEE_TIMESYNC_CAPABILITY_TYPE;
#define BRPHY1GV2_PMA_PMD_IEEE_TIMESYNC_CAPABILITY_ABILITY_1000T1_MASK (0x2U)
#define BRPHY1GV2_PMA_PMD_IEEE_TIMESYNC_CAPABILITY_ABILITY_1000T1_SHIFT (1U)
#define BRPHY1GV2_PMA_PMD_IEEE_TIMESYNC_CAPABILITY_ABILITY_100T1_MASK (0x1U)
#define BRPHY1GV2_PMA_PMD_IEEE_TIMESYNC_CAPABILITY_ABILITY_100T1_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PMA_PMD_IEEE_TPDDML_TYPE;
#define BRPHY1GV2_PMA_PMD_IEEE_TPDDML_TTPD_MASK (0xffffU)
#define BRPHY1GV2_PMA_PMD_IEEE_TPDDML_TTPD_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PMA_PMD_IEEE_TPDDMU_TYPE;
#define BRPHY1GV2_PMA_PMD_IEEE_TPDDMU_TTPD_MASK (0xffffU)
#define BRPHY1GV2_PMA_PMD_IEEE_TPDDMU_TTPD_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PMA_PMD_IEEE_TPDDML1_TYPE;
#define BRPHY1GV2_PMA_PMD_IEEE_TPDDML1_TTPD_MASK (0xffffU)
#define BRPHY1GV2_PMA_PMD_IEEE_TPDDML1_TTPD_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PMA_PMD_IEEE_TPDDMU1_TYPE;
#define BRPHY1GV2_PMA_PMD_IEEE_TPDDMU1_TTPD_MASK (0xffffU)
#define BRPHY1GV2_PMA_PMD_IEEE_TPDDMU1_TTPD_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PMA_PMD_IEEE_RPDDML_TYPE;
#define BRPHY1GV2_PMA_PMD_IEEE_RPDDML_TTPD_MASK (0xffffU)
#define BRPHY1GV2_PMA_PMD_IEEE_RPDDML_TTPD_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PMA_PMD_IEEE_RPDDMU_TYPE;
#define BRPHY1GV2_PMA_PMD_IEEE_RPDDMU_TTPDM_MASK (0xffffU)
#define BRPHY1GV2_PMA_PMD_IEEE_RPDDMU_TTPDM_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PMA_PMD_IEEE_RPDDML1_TYPE;
#define BRPHY1GV2_PMA_PMD_IEEE_RPDDML1_TTPD_MASK (0xffffU)
#define BRPHY1GV2_PMA_PMD_IEEE_RPDDML1_TTPD_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PMA_PMD_IEEE_RPDDMU1_TYPE;
#define BRPHY1GV2_PMA_PMD_IEEE_RPDDMU1_TTPD_MASK (0xffffU)
#define BRPHY1GV2_PMA_PMD_IEEE_RPDDMU1_TTPD_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PMA_PMD_IEEE_B1PPC_TYPE;
#define BRPHY1GV2_PMA_PMD_IEEE_B1PPC_B1PPCB15_MASK (0x8000U)
#define BRPHY1GV2_PMA_PMD_IEEE_B1PPC_B1PPCB15_SHIFT (15U)
#define BRPHY1GV2_PMA_PMD_IEEE_B1PPC_MASTER_SLAVE_MASK (0x4000U)
#define BRPHY1GV2_PMA_PMD_IEEE_B1PPC_MASTER_SLAVE_SHIFT (14U)
#define BRPHY1GV2_PMA_PMD_IEEE_B1PPC_T1_BASE_SEL_MASK (0xfU)
#define BRPHY1GV2_PMA_PMD_IEEE_B1PPC_T1_BASE_SEL_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PMA_PMD_IEEE_B1001PPTC_TYPE;
#define BRPHY1GV2_PMA_PMD_IEEE_B1001PPTC_TEST_CONTROL_MASK (0xe000U)
#define BRPHY1GV2_PMA_PMD_IEEE_B1001PPTC_TEST_CONTROL_SHIFT (13U)




typedef uint16_t BRPHY1GV2_PMA_PMD_IEEE_B10001PC_TYPE;
#define BRPHY1GV2_PMA_PMD_IEEE_B10001PC_PMA_PMD_RESET_MASK (0x8000U)
#define BRPHY1GV2_PMA_PMD_IEEE_B10001PC_PMA_PMD_RESET_SHIFT (15U)
#define BRPHY1GV2_PMA_PMD_IEEE_B10001PC_TRANSMIT_DISABLE_MASK (0x4000U)
#define BRPHY1GV2_PMA_PMD_IEEE_B10001PC_TRANSMIT_DISABLE_SHIFT (14U)
#define BRPHY1GV2_PMA_PMD_IEEE_B10001PC_LOW_POWER_MASK (0x800U)
#define BRPHY1GV2_PMA_PMD_IEEE_B10001PC_LOW_POWER_SHIFT (11U)




typedef uint16_t BRPHY1GV2_PMA_PMD_IEEE_BASE10001_STAT_TYPE;
#define BRPHY1GV2_PMA_PMD_IEEE_BASE10001_STAT_A10001O_MASK (0x800U)
#define BRPHY1GV2_PMA_PMD_IEEE_BASE10001_STAT_A10001O_SHIFT (11U)
#define BRPHY1GV2_PMA_PMD_IEEE_BASE10001_STAT_EEE_ABILITY_MASK (0x400U)
#define BRPHY1GV2_PMA_PMD_IEEE_BASE10001_STAT_EEE_ABILITY_SHIFT (10U)
#define BRPHY1GV2_PMA_PMD_IEEE_BASE10001_STAT_RFA_MASK (0x200U)
#define BRPHY1GV2_PMA_PMD_IEEE_BASE10001_STAT_RFA_SHIFT (9U)
#define BRPHY1GV2_PMA_PMD_IEEE_BASE10001_STAT_LOW_POWER_ABILITY_MASK (0x100U)
#define BRPHY1GV2_PMA_PMD_IEEE_BASE10001_STAT_LOW_POWER_ABILITY_SHIFT (8U)
#define BRPHY1GV2_PMA_PMD_IEEE_BASE10001_STAT_RECEIVE_POLARITY_MASK (0x4U)
#define BRPHY1GV2_PMA_PMD_IEEE_BASE10001_STAT_RECEIVE_POLARITY_SHIFT (2U)
#define BRPHY1GV2_PMA_PMD_IEEE_BASE10001_STAT_RECEIVE_FAULT_MASK (0x2U)
#define BRPHY1GV2_PMA_PMD_IEEE_BASE10001_STAT_RECEIVE_FAULT_SHIFT (1U)
#define BRPHY1GV2_PMA_PMD_IEEE_BASE10001_STAT_RECEIVE_LINK_STATUS_MASK (0x1U)
#define BRPHY1GV2_PMA_PMD_IEEE_BASE10001_STAT_RECEIVE_LINK_STATUS_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PMA_PMD_IEEE_BASE10001_TRAI_TYPE;
#define BRPHY1GV2_PMA_PMD_IEEE_BASE10001_TRAI_USER_FIELD_7_MASK (0x7f0U)
#define BRPHY1GV2_PMA_PMD_IEEE_BASE10001_TRAI_USER_FIELD_7_SHIFT (4U)
#define BRPHY1GV2_PMA_PMD_IEEE_BASE10001_TRAI_A10001O_MASK (0x2U)
#define BRPHY1GV2_PMA_PMD_IEEE_BASE10001_TRAI_A10001O_SHIFT (1U)
#define BRPHY1GV2_PMA_PMD_IEEE_BASE10001_TRAI_EEE_ADVERTISEMENT_MASK (0x1U)
#define BRPHY1GV2_PMA_PMD_IEEE_BASE10001_TRAI_EEE_ADVERTISEMENT_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PMA_PMD_IEEE_B10001LPT_TYPE;
#define BRPHY1GV2_PMA_PMD_IEEE_B10001LPT_LINK_PARTNER_USER_FIELD_MASK (0x7f0U)
#define BRPHY1GV2_PMA_PMD_IEEE_B10001LPT_LINK_PARTNER_USER_FIELD_SHIFT (4U)
#define BRPHY1GV2_PMA_PMD_IEEE_B10001LPT_LP10001O_MASK (0x2U)
#define BRPHY1GV2_PMA_PMD_IEEE_B10001LPT_LP10001O_SHIFT (1U)
#define BRPHY1GV2_PMA_PMD_IEEE_B10001LPT_LPEA_MASK (0x1U)
#define BRPHY1GV2_PMA_PMD_IEEE_B10001LPT_LPEA_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PMA_PMD_IEEE_B10001TMC_TYPE;
#define BRPHY1GV2_PMA_PMD_IEEE_B10001TMC_TEST_MODE_CONTROL_MASK (0xe000U)
#define BRPHY1GV2_PMA_PMD_IEEE_B10001TMC_TEST_MODE_CONTROL_SHIFT (13U)




typedef volatile struct sBRPHY1GV2_PMA_PMD_IEEE_RDBType {
    BRPHY1GV2_PMA_PMD_IEEE_CONTROL_REG1_TYPE m0; /* OFFSET: 0x0 */
    BRPHY1GV2_PMA_PMD_IEEE_RESERVED_TYPE rsvd0[2]; /* OFFSET: 0x2 */
    BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG1_TYPE m1; /* OFFSET: 0x4 */
    BRPHY1GV2_PMA_PMD_IEEE_RESERVED_TYPE rsvd1[2]; /* OFFSET: 0x6 */
    BRPHY1GV2_PMA_PMD_IEEE_DEVICE_ID_REG0_TYPE m2; /* OFFSET: 0x8 */
    BRPHY1GV2_PMA_PMD_IEEE_RESERVED_TYPE rsvd2[2]; /* OFFSET: 0xa */
    BRPHY1GV2_PMA_PMD_IEEE_DEVICE_ID_REG1_TYPE m3; /* OFFSET: 0xc */
    BRPHY1GV2_PMA_PMD_IEEE_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0xe */
    BRPHY1GV2_PMA_PMD_IEEE_PPSA_TYPE m4; /* OFFSET: 0x10 */
    BRPHY1GV2_PMA_PMD_IEEE_RESERVED_TYPE rsvd4[2]; /* OFFSET: 0x12 */
    BRPHY1GV2_PMA_PMD_IEEE_DIPR0_TYPE m5; /* OFFSET: 0x14 */
    BRPHY1GV2_PMA_PMD_IEEE_RESERVED_TYPE rsvd5[2]; /* OFFSET: 0x16 */
    BRPHY1GV2_PMA_PMD_IEEE_DIPR1_TYPE m6; /* OFFSET: 0x18 */
    BRPHY1GV2_PMA_PMD_IEEE_RESERVED_TYPE rsvd6[2]; /* OFFSET: 0x1a */
    BRPHY1GV2_PMA_PMD_IEEE_CONTROL_REG2_TYPE m7; /* OFFSET: 0x1c */
    BRPHY1GV2_PMA_PMD_IEEE_RESERVED_TYPE rsvd7[2]; /* OFFSET: 0x1e */
    BRPHY1GV2_PMA_PMD_IEEE_STATUS_REG2_TYPE m8; /* OFFSET: 0x20 */
    BRPHY1GV2_PMA_PMD_IEEE_RESERVED_TYPE rsvd8[2]; /* OFFSET: 0x22 */
    BRPHY1GV2_PMA_PMD_IEEE_TDR_TYPE m9; /* OFFSET: 0x24 */
    BRPHY1GV2_PMA_PMD_IEEE_RESERVED_TYPE rsvd9[2]; /* OFFSET: 0x26 */
    BRPHY1GV2_PMA_PMD_IEEE_RSDR_TYPE m10; /* OFFSET: 0x28 */
    BRPHY1GV2_PMA_PMD_IEEE_RESERVED_TYPE rsvd10[2]; /* OFFSET: 0x2a */
    BRPHY1GV2_PMA_PMD_IEEE_EAR_TYPE m11; /* OFFSET: 0x2c */
    BRPHY1GV2_PMA_PMD_IEEE_RESERVED_TYPE rsvd11[10]; /* OFFSET: 0x2e */
    BRPHY1GV2_PMA_PMD_IEEE_PACKAGE_ID_REG0_TYPE m14; /* OFFSET: 0x38 */
    BRPHY1GV2_PMA_PMD_IEEE_RESERVED_TYPE rsvd12[2]; /* OFFSET: 0x3a */
    BRPHY1GV2_PMA_PMD_IEEE_PACKAGE_ID_REG1_TYPE m15; /* OFFSET: 0x3c */
    BRPHY1GV2_PMA_PMD_IEEE_RESERVED_TYPE rsvd13[10]; /* OFFSET: 0x3e */
    BRPHY1GV2_PMA_PMD_IEEE_B1PPEA_TYPE m18; /* OFFSET: 0x48 */
    BRPHY1GV2_PMA_PMD_IEEE_RESERVED_TYPE rsvd14[7126]; /* OFFSET: 0x4a */
    BRPHY1GV2_PMA_PMD_IEEE_TIMESYNC_CAPABILITY_TYPE m1800; /* OFFSET: 0x1c20 */
    BRPHY1GV2_PMA_PMD_IEEE_RESERVED_TYPE rsvd15[2]; /* OFFSET: 0x1c22 */
    BRPHY1GV2_PMA_PMD_IEEE_TPDDML_TYPE m1801; /* OFFSET: 0x1c24 */
    BRPHY1GV2_PMA_PMD_IEEE_RESERVED_TYPE rsvd16[2]; /* OFFSET: 0x1c26 */
    BRPHY1GV2_PMA_PMD_IEEE_TPDDMU_TYPE m1802; /* OFFSET: 0x1c28 */
    BRPHY1GV2_PMA_PMD_IEEE_RESERVED_TYPE rsvd17[2]; /* OFFSET: 0x1c2a */
    BRPHY1GV2_PMA_PMD_IEEE_TPDDML1_TYPE m1803; /* OFFSET: 0x1c2c */
    BRPHY1GV2_PMA_PMD_IEEE_RESERVED_TYPE rsvd18[2]; /* OFFSET: 0x1c2e */
    BRPHY1GV2_PMA_PMD_IEEE_TPDDMU1_TYPE m1804; /* OFFSET: 0x1c30 */
    BRPHY1GV2_PMA_PMD_IEEE_RESERVED_TYPE rsvd19[2]; /* OFFSET: 0x1c32 */
    BRPHY1GV2_PMA_PMD_IEEE_RPDDML_TYPE m1805; /* OFFSET: 0x1c34 */
    BRPHY1GV2_PMA_PMD_IEEE_RESERVED_TYPE rsvd20[2]; /* OFFSET: 0x1c36 */
    BRPHY1GV2_PMA_PMD_IEEE_RPDDMU_TYPE m1806; /* OFFSET: 0x1c38 */
    BRPHY1GV2_PMA_PMD_IEEE_RESERVED_TYPE rsvd21[2]; /* OFFSET: 0x1c3a */
    BRPHY1GV2_PMA_PMD_IEEE_RPDDML1_TYPE m1807; /* OFFSET: 0x1c3c */
    BRPHY1GV2_PMA_PMD_IEEE_RESERVED_TYPE rsvd22[2]; /* OFFSET: 0x1c3e */
    BRPHY1GV2_PMA_PMD_IEEE_RPDDMU1_TYPE m1808; /* OFFSET: 0x1c40 */
    BRPHY1GV2_PMA_PMD_IEEE_RESERVED_TYPE rsvd23[1166]; /* OFFSET: 0x1c42 */
    BRPHY1GV2_PMA_PMD_IEEE_B1PPC_TYPE m2100; /* OFFSET: 0x20d0 */
    BRPHY1GV2_PMA_PMD_IEEE_RESERVED_TYPE rsvd24[6]; /* OFFSET: 0x20d2 */
    BRPHY1GV2_PMA_PMD_IEEE_B1001PPTC_TYPE m2102; /* OFFSET: 0x20d8 */
    BRPHY1GV2_PMA_PMD_IEEE_RESERVED_TYPE rsvd25[806]; /* OFFSET: 0x20da */
    BRPHY1GV2_PMA_PMD_IEEE_B10001PC_TYPE m2304; /* OFFSET: 0x2400 */
    BRPHY1GV2_PMA_PMD_IEEE_RESERVED_TYPE rsvd26[2]; /* OFFSET: 0x2402 */
    BRPHY1GV2_PMA_PMD_IEEE_BASE10001_STAT_TYPE m2305; /* OFFSET: 0x2404 */
    BRPHY1GV2_PMA_PMD_IEEE_RESERVED_TYPE rsvd27[2]; /* OFFSET: 0x2406 */
    BRPHY1GV2_PMA_PMD_IEEE_BASE10001_TRAI_TYPE m2306; /* OFFSET: 0x2408 */
    BRPHY1GV2_PMA_PMD_IEEE_RESERVED_TYPE rsvd28[2]; /* OFFSET: 0x240a */
    BRPHY1GV2_PMA_PMD_IEEE_B10001LPT_TYPE m2307; /* OFFSET: 0x240c */
    BRPHY1GV2_PMA_PMD_IEEE_RESERVED_TYPE rsvd29[2]; /* OFFSET: 0x240e */
    BRPHY1GV2_PMA_PMD_IEEE_B10001TMC_TYPE m2308; /* OFFSET: 0x2410 */
} BRPHY1GV2_PMA_PMD_IEEE_RDBType;


#define BRPHY0_1G_PMA_PMD_IEEE_BASE     (0xE0540000UL)



#define BRPHY1GV2_PMA_PMD_IEEE_MAX_HW_ID  (1UL)

#endif /* BRPHY1GV2_PMA_PMD_IEEE_RDB_H */
