/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file brphy1gv2_adccal_16nm_rdb.h
    @brief RDB File for BRPHY1GV2_ADCCAL_16NM

    @version BCM89580_A0_20230125_RDB
*/

#ifndef BRPHY1GV2_ADCCAL_16NM_RDB_H
#define BRPHY1GV2_ADCCAL_16NM_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t BRPHY1GV2_ADCCAL_16NM_CONTROL_0_TYPE;
#define BRPHY1GV2_ADCCAL_16NM_CONTROL_0_SOFT_RESET_MASK (0x8000U)
#define BRPHY1GV2_ADCCAL_16NM_CONTROL_0_SOFT_RESET_SHIFT (15U)
#define BRPHY1GV2_ADCCAL_16NM_CONTROL_0_OFFSET_CAL_CLK_OVR_MASK (0x8U)
#define BRPHY1GV2_ADCCAL_16NM_CONTROL_0_OFFSET_CAL_CLK_OVR_SHIFT (3U)
#define BRPHY1GV2_ADCCAL_16NM_CONTROL_0_GAIN_CAL_CLK_OVR_MASK (0x4U)
#define BRPHY1GV2_ADCCAL_16NM_CONTROL_0_GAIN_CAL_CLK_OVR_SHIFT (2U)
#define BRPHY1GV2_ADCCAL_16NM_CONTROL_0_OFFSET_CAL_ENABLE_MASK (0x2U)
#define BRPHY1GV2_ADCCAL_16NM_CONTROL_0_OFFSET_CAL_ENABLE_SHIFT (1U)
#define BRPHY1GV2_ADCCAL_16NM_CONTROL_0_GAIN_CAL_ENABLE_MASK (0x1U)
#define BRPHY1GV2_ADCCAL_16NM_CONTROL_0_GAIN_CAL_ENABLE_SHIFT (0U)




typedef uint8_t BRPHY1GV2_ADCCAL_16NM_RESERVED_TYPE;




typedef uint16_t BRPHY1GV2_ADCCAL_16NM_CONTROL_1_TYPE;
#define BRPHY1GV2_ADCCAL_16NM_CONTROL_1_MODE_MASK (0xc00U)
#define BRPHY1GV2_ADCCAL_16NM_CONTROL_1_MODE_SHIFT (10U)
#define BRPHY1GV2_ADCCAL_16NM_CONTROL_1_NMAX_MASK (0x380U)
#define BRPHY1GV2_ADCCAL_16NM_CONTROL_1_NMAX_SHIFT (7U)
#define BRPHY1GV2_ADCCAL_16NM_CONTROL_1_GAIN_MU_MASK (0x78U)
#define BRPHY1GV2_ADCCAL_16NM_CONTROL_1_GAIN_MU_SHIFT (3U)
#define BRPHY1GV2_ADCCAL_16NM_CONTROL_1_OFFSET_MU_MASK (0x7U)
#define BRPHY1GV2_ADCCAL_16NM_CONTROL_1_OFFSET_MU_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ADCCAL_16NM_DCS0_TYPE;
#define BRPHY1GV2_ADCCAL_16NM_DCS0_EXT_CTL_ENABLE_MASK (0x8000U)
#define BRPHY1GV2_ADCCAL_16NM_DCS0_EXT_CTL_ENABLE_SHIFT (15U)
#define BRPHY1GV2_ADCCAL_16NM_DCS0_DACCAL_NMAX_MASK (0xf00U)
#define BRPHY1GV2_ADCCAL_16NM_DCS0_DACCAL_NMAX_SHIFT (8U)
#define BRPHY1GV2_ADCCAL_16NM_DCS0_FG_OFFSET_ACC_CTL_MASK (0xc0U)
#define BRPHY1GV2_ADCCAL_16NM_DCS0_FG_OFFSET_ACC_CTL_SHIFT (6U)
#define BRPHY1GV2_ADCCAL_16NM_DCS0_FG_OFFSET_DLY_CTL_MASK (0x30U)
#define BRPHY1GV2_ADCCAL_16NM_DCS0_FG_OFFSET_DLY_CTL_SHIFT (4U)
#define BRPHY1GV2_ADCCAL_16NM_DCS0_FG_OFFSET_CAL_DONE_MASK (0x8U)
#define BRPHY1GV2_ADCCAL_16NM_DCS0_FG_OFFSET_CAL_DONE_SHIFT (3U)
#define BRPHY1GV2_ADCCAL_16NM_DCS0_DACCAL_DONE_MASK (0x4U)
#define BRPHY1GV2_ADCCAL_16NM_DCS0_DACCAL_DONE_SHIFT (2U)
#define BRPHY1GV2_ADCCAL_16NM_DCS0_FG_OFFSET_CAL_ENABLE_MASK (0x2U)
#define BRPHY1GV2_ADCCAL_16NM_DCS0_FG_OFFSET_CAL_ENABLE_SHIFT (1U)
#define BRPHY1GV2_ADCCAL_16NM_DCS0_DACCAL_ENABLE_MASK (0x1U)
#define BRPHY1GV2_ADCCAL_16NM_DCS0_DACCAL_ENABLE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ADCCAL_16NM_DCS1_TYPE;
#define BRPHY1GV2_ADCCAL_16NM_DCS1_FG_OFFSET_ERROR_MASK (0x400U)
#define BRPHY1GV2_ADCCAL_16NM_DCS1_FG_OFFSET_ERROR_SHIFT (10U)
#define BRPHY1GV2_ADCCAL_16NM_DCS1_UNDERFLOW_ERROR_MASK (0x200U)
#define BRPHY1GV2_ADCCAL_16NM_DCS1_UNDERFLOW_ERROR_SHIFT (9U)
#define BRPHY1GV2_ADCCAL_16NM_DCS1_OVERFLOW_ERROR_MASK (0x100U)
#define BRPHY1GV2_ADCCAL_16NM_DCS1_OVERFLOW_ERROR_SHIFT (8U)
#define BRPHY1GV2_ADCCAL_16NM_DCS1_SWAP_FG_OFFSET_POLARITY_MASK (0x80U)
#define BRPHY1GV2_ADCCAL_16NM_DCS1_SWAP_FG_OFFSET_POLARITY_SHIFT (7U)
#define BRPHY1GV2_ADCCAL_16NM_DCS1_FGCAL_OVERRIDE_EN_MASK (0x40U)
#define BRPHY1GV2_ADCCAL_16NM_DCS1_FGCAL_OVERRIDE_EN_SHIFT (6U)
#define BRPHY1GV2_ADCCAL_16NM_DCS1_FGCAL_EN_OVR_VAL_MASK (0x20U)
#define BRPHY1GV2_ADCCAL_16NM_DCS1_FGCAL_EN_OVR_VAL_SHIFT (5U)
#define BRPHY1GV2_ADCCAL_16NM_DCS1_FGCAL_STATE_OVR_VAL_MASK (0x1cU)
#define BRPHY1GV2_ADCCAL_16NM_DCS1_FGCAL_STATE_OVR_VAL_SHIFT (2U)
#define BRPHY1GV2_ADCCAL_16NM_DCS1_ADC_SAR_ZERO_EN_OVR_VAL_MASK (0x2U)
#define BRPHY1GV2_ADCCAL_16NM_DCS1_ADC_SAR_ZERO_EN_OVR_VAL_SHIFT (1U)
#define BRPHY1GV2_ADCCAL_16NM_DCS1_ADC_TAH_ZERO_EN_OVR_VAL_MASK (0x1U)
#define BRPHY1GV2_ADCCAL_16NM_DCS1_ADC_TAH_ZERO_EN_OVR_VAL_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ADCCAL_16NM_DACCAL_LANE_CTL_TYPE;
#define BRPHY1GV2_ADCCAL_16NM_DACCAL_LANE_CTL_ENABLE_MASK (0x3U)
#define BRPHY1GV2_ADCCAL_16NM_DACCAL_LANE_CTL_ENABLE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ADCCAL_16NM_DLES_TYPE;
#define BRPHY1GV2_ADCCAL_16NM_DLES_UNDERFLOW_ERROR_MASK (0x7f00U)
#define BRPHY1GV2_ADCCAL_16NM_DLES_UNDERFLOW_ERROR_SHIFT (8U)
#define BRPHY1GV2_ADCCAL_16NM_DLES_OVERFLOW_ERROR_MASK (0x7fU)
#define BRPHY1GV2_ADCCAL_16NM_DLES_OVERFLOW_ERROR_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ADCCAL_16NM_IND_CONTROL_TYPE;
#define BRPHY1GV2_ADCCAL_16NM_IND_CONTROL_WR_STROBE_MASK (0x8000U)
#define BRPHY1GV2_ADCCAL_16NM_IND_CONTROL_WR_STROBE_SHIFT (15U)
#define BRPHY1GV2_ADCCAL_16NM_IND_CONTROL_WRITE_BROADCAST_MASK (0x400U)
#define BRPHY1GV2_ADCCAL_16NM_IND_CONTROL_WRITE_BROADCAST_SHIFT (10U)
#define BRPHY1GV2_ADCCAL_16NM_IND_CONTROL_CHANNEL_SELECT_MASK (0x300U)
#define BRPHY1GV2_ADCCAL_16NM_IND_CONTROL_CHANNEL_SELECT_SHIFT (8U)
#define BRPHY1GV2_ADCCAL_16NM_IND_CONTROL_ADDRESS_MASK (0xffU)
#define BRPHY1GV2_ADCCAL_16NM_IND_CONTROL_ADDRESS_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ADCCAL_16NM_IND_RD_DATA_TYPE;
#define BRPHY1GV2_ADCCAL_16NM_IND_RD_DATA_READ_MASK (0xffffU)
#define BRPHY1GV2_ADCCAL_16NM_IND_RD_DATA_READ_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ADCCAL_16NM_IND_WR_DATA_TYPE;
#define BRPHY1GV2_ADCCAL_16NM_IND_WR_DATA_WRITE_MASK (0xffffU)
#define BRPHY1GV2_ADCCAL_16NM_IND_WR_DATA_WRITE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ADCCAL_16NM_TEST_CONTROL_TYPE;
#define BRPHY1GV2_ADCCAL_16NM_TEST_CONTROL_TPO_MODE_DEC_MASK (0xe000U)
#define BRPHY1GV2_ADCCAL_16NM_TEST_CONTROL_TPO_MODE_DEC_SHIFT (13U)
#define BRPHY1GV2_ADCCAL_16NM_TEST_CONTROL_TPO_MODE_ENABLE_MASK (0x1000U)
#define BRPHY1GV2_ADCCAL_16NM_TEST_CONTROL_TPO_MODE_ENABLE_SHIFT (12U)
#define BRPHY1GV2_ADCCAL_16NM_TEST_CONTROL_TPO_MODE_MASK (0x300U)
#define BRPHY1GV2_ADCCAL_16NM_TEST_CONTROL_TPO_MODE_SHIFT (8U)
#define BRPHY1GV2_ADCCAL_16NM_TEST_CONTROL_LANE_TOGGLE_EN_MASK (0x40U)
#define BRPHY1GV2_ADCCAL_16NM_TEST_CONTROL_LANE_TOGGLE_EN_SHIFT (6U)
#define BRPHY1GV2_ADCCAL_16NM_TEST_CONTROL_ADC_TEST_MODE_RESET_N_MASK (0x20U)
#define BRPHY1GV2_ADCCAL_16NM_TEST_CONTROL_ADC_TEST_MODE_RESET_N_SHIFT (5U)
#define BRPHY1GV2_ADCCAL_16NM_TEST_CONTROL_ADC_TEST_MODE_ENABLE_MASK (0x10U)
#define BRPHY1GV2_ADCCAL_16NM_TEST_CONTROL_ADC_TEST_MODE_ENABLE_SHIFT (4U)
#define BRPHY1GV2_ADCCAL_16NM_TEST_CONTROL_ADC_TEST_MODE_MASK (0xcU)
#define BRPHY1GV2_ADCCAL_16NM_TEST_CONTROL_ADC_TEST_MODE_SHIFT (2U)
#define BRPHY1GV2_ADCCAL_16NM_TEST_CONTROL_ADC_TEST_SUB_MODE_MASK (0x3U)
#define BRPHY1GV2_ADCCAL_16NM_TEST_CONTROL_ADC_TEST_SUB_MODE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ADCCAL_16NM_RDB_MAG_REF_TYPE;
#define BRPHY1GV2_ADCCAL_16NM_RDB_MAG_REF_MASK (0xffffU)
#define BRPHY1GV2_ADCCAL_16NM_RDB_MAG_REF_SHIFT (0U)




typedef uint16_t BRPHY1GV2_ADCCAL_16NM_SPARE_END_ADDR_TYPE;
#define BRPHY1GV2_ADCCAL_16NM_SPARE_END_ADDR_MASK (0xffffU)
#define BRPHY1GV2_ADCCAL_16NM_SPARE_END_ADDR_SHIFT (0U)




typedef volatile struct sBRPHY1GV2_ADCCAL_16NM_RDBType {
    BRPHY1GV2_ADCCAL_16NM_CONTROL_0_TYPE control_0; /* OFFSET: 0x0 */
    BRPHY1GV2_ADCCAL_16NM_RESERVED_TYPE rsvd0[2]; /* OFFSET: 0x2 */
    BRPHY1GV2_ADCCAL_16NM_CONTROL_1_TYPE control_1; /* OFFSET: 0x4 */
    BRPHY1GV2_ADCCAL_16NM_RESERVED_TYPE rsvd1[2]; /* OFFSET: 0x6 */
    BRPHY1GV2_ADCCAL_16NM_DCS0_TYPE daccal_ctl_stat_0; /* OFFSET: 0x8 */
    BRPHY1GV2_ADCCAL_16NM_RESERVED_TYPE rsvd2[2]; /* OFFSET: 0xa */
    BRPHY1GV2_ADCCAL_16NM_DCS1_TYPE daccal_ctl_stat_1; /* OFFSET: 0xc */
    BRPHY1GV2_ADCCAL_16NM_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0xe */
    BRPHY1GV2_ADCCAL_16NM_DACCAL_LANE_CTL_TYPE daccal_lane_ctl; /* OFFSET: 0x10 */
    BRPHY1GV2_ADCCAL_16NM_RESERVED_TYPE rsvd4[2]; /* OFFSET: 0x12 */
    BRPHY1GV2_ADCCAL_16NM_DLES_TYPE daccal_lane_error_stat_0; /* OFFSET: 0x14 */
    BRPHY1GV2_ADCCAL_16NM_RESERVED_TYPE rsvd5[2]; /* OFFSET: 0x16 */
    BRPHY1GV2_ADCCAL_16NM_DLES_TYPE daccal_lane_error_stat_1; /* OFFSET: 0x18 */
    BRPHY1GV2_ADCCAL_16NM_RESERVED_TYPE rsvd6[2]; /* OFFSET: 0x1a */
    BRPHY1GV2_ADCCAL_16NM_IND_CONTROL_TYPE ind_control; /* OFFSET: 0x1c */
    BRPHY1GV2_ADCCAL_16NM_RESERVED_TYPE rsvd7[2]; /* OFFSET: 0x1e */
    BRPHY1GV2_ADCCAL_16NM_IND_RD_DATA_TYPE ind_rd_data_0; /* OFFSET: 0x20 */
    BRPHY1GV2_ADCCAL_16NM_RESERVED_TYPE rsvd8[2]; /* OFFSET: 0x22 */
    BRPHY1GV2_ADCCAL_16NM_IND_RD_DATA_TYPE ind_rd_data_1; /* OFFSET: 0x24 */
    BRPHY1GV2_ADCCAL_16NM_RESERVED_TYPE rsvd9[2]; /* OFFSET: 0x26 */
    BRPHY1GV2_ADCCAL_16NM_IND_WR_DATA_TYPE ind_wr_data_0; /* OFFSET: 0x28 */
    BRPHY1GV2_ADCCAL_16NM_RESERVED_TYPE rsvd10[2]; /* OFFSET: 0x2a */
    BRPHY1GV2_ADCCAL_16NM_IND_WR_DATA_TYPE ind_wr_data_1; /* OFFSET: 0x2c */
    BRPHY1GV2_ADCCAL_16NM_RESERVED_TYPE rsvd11[2]; /* OFFSET: 0x2e */
    BRPHY1GV2_ADCCAL_16NM_TEST_CONTROL_TYPE test_control; /* OFFSET: 0x30 */
    BRPHY1GV2_ADCCAL_16NM_RESERVED_TYPE rsvd12[2]; /* OFFSET: 0x32 */
    BRPHY1GV2_ADCCAL_16NM_RDB_MAG_REF_TYPE rdb_t0_ref; /* OFFSET: 0x34 */
    BRPHY1GV2_ADCCAL_16NM_RESERVED_TYPE rsvd13[2]; /* OFFSET: 0x36 */
    BRPHY1GV2_ADCCAL_16NM_RDB_MAG_REF_TYPE rdb_t1_ref; /* OFFSET: 0x38 */
    BRPHY1GV2_ADCCAL_16NM_RESERVED_TYPE rsvd14[962]; /* OFFSET: 0x3a */
    BRPHY1GV2_ADCCAL_16NM_SPARE_END_ADDR_TYPE spare_end_addr; /* OFFSET: 0x3fc */
} BRPHY1GV2_ADCCAL_16NM_RDBType;


#define BRPHY0_1G_ADCCAL_16NM_BASE      (0xE0565800UL)



#define BRPHY1GV2_ADCCAL_16NM_MAX_HW_ID  (1UL)

#endif /* BRPHY1GV2_ADCCAL_16NM_RDB_H */
