/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file brphy1gv2_dsp_top_rdb.h
    @brief RDB File for BRPHY1GV2_DSP_TOP

    @version BCM89580_A0_20230125_RDB
*/

#ifndef BRPHY1GV2_DSP_TOP_RDB_H
#define BRPHY1GV2_DSP_TOP_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t BRPHY1GV2_DSP_TOP_DAGC_STATUS_0_TYPE;
#define BRPHY1GV2_DSP_TOP_DAGC_STATUS_0_ACCUM_MASK (0xffffU)
#define BRPHY1GV2_DSP_TOP_DAGC_STATUS_0_ACCUM_SHIFT (0U)




typedef uint8_t BRPHY1GV2_DSP_TOP_RESERVED_TYPE;




typedef uint16_t BRPHY1GV2_DSP_TOP_DAGC_STATUS_1_TYPE;
#define BRPHY1GV2_DSP_TOP_DAGC_STATUS_1_ACCUM_RND_MASK (0x1ffU)
#define BRPHY1GV2_DSP_TOP_DAGC_STATUS_1_ACCUM_RND_SHIFT (0U)




typedef uint16_t BRPHY1GV2_DSP_TOP_SOFT_DECISION_TYPE;
#define BRPHY1GV2_DSP_TOP_SOFT_DECISION_MASK (0xffffU)
#define BRPHY1GV2_DSP_TOP_SOFT_DECISION_SHIFT (0U)




typedef uint16_t BRPHY1GV2_DSP_TOP_AGC_REF_LVL_TYPE;
#define BRPHY1GV2_DSP_TOP_AGC_REF_LVL_MASK (0x1ffU)
#define BRPHY1GV2_DSP_TOP_AGC_REF_LVL_SHIFT (0U)




typedef uint16_t BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_0_TYPE;
#define BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_0_FAGC_SKIP_DIS_MASK (0x4000U)
#define BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_0_FAGC_SKIP_DIS_SHIFT (14U)
#define BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_0_FAGC_ERR_MULT_MASK (0x3000U)
#define BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_0_FAGC_ERR_MULT_SHIFT (12U)
#define BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_0_FAGCHIGEAR_OVR_VAL_MASK (0x800U)
#define BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_0_FAGCHIGEAR_OVR_VAL_SHIFT (11U)
#define BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_0_FAGCHIGEAR_OVR_MASK (0x400U)
#define BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_0_FAGCHIGEAR_OVR_SHIFT (10U)
#define BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_0_CAGCHIGEAR_OVR_VAL_MASK (0x200U)
#define BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_0_CAGCHIGEAR_OVR_VAL_SHIFT (9U)
#define BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_0_CAGCHIGEAR_OVR_MASK (0x100U)
#define BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_0_CAGCHIGEAR_OVR_SHIFT (8U)
#define BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_0_CAGCFRZ_OVR_VAL_MASK (0x80U)
#define BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_0_CAGCFRZ_OVR_VAL_SHIFT (7U)
#define BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_0_CAGCFRZ_OVR_MASK (0x40U)
#define BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_0_CAGCFRZ_OVR_SHIFT (6U)
#define BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_0_CAGCRST_OVR_VAL_MASK (0x20U)
#define BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_0_CAGCRST_OVR_VAL_SHIFT (5U)
#define BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_0_CAGCRST_OVR_MASK (0x10U)
#define BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_0_CAGCRST_OVR_SHIFT (4U)
#define BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_0_FAGCFRZ_OVR_VAL_MASK (0x8U)
#define BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_0_FAGCFRZ_OVR_VAL_SHIFT (3U)
#define BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_0_FAGCFRZ_OVR_MASK (0x4U)
#define BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_0_FAGCFRZ_OVR_SHIFT (2U)
#define BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_0_FAGCRST_OVR_VAL_MASK (0x2U)
#define BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_0_FAGCRST_OVR_VAL_SHIFT (1U)
#define BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_0_FAGCRST_OVR_MASK (0x1U)
#define BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_0_FAGCRST_OVR_SHIFT (0U)




typedef uint16_t BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_1_TYPE;
#define BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_1_COARSE_GAIN_CTL_OVR_VAL_MASK (0x1f00U)
#define BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_1_COARSE_GAIN_CTL_OVR_VAL_SHIFT (8U)
#define BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_1_COARSE_GAIN_CTL_OVR_MASK (0x80U)
#define BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_1_COARSE_GAIN_CTL_OVR_SHIFT (7U)
#define BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_1_FINE_GAIN_CTL_OVR_VAL_MASK (0x7eU)
#define BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_1_FINE_GAIN_CTL_OVR_VAL_SHIFT (1U)
#define BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_1_FINE_GAIN_CTL_OVR_MASK (0x1U)
#define BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_1_FINE_GAIN_CTL_OVR_SHIFT (0U)




typedef uint16_t BRPHY1GV2_DSP_TOP_DSP_TEST0_TYPE;
#define BRPHY1GV2_DSP_TOP_DSP_TEST0_DAGC_INIT_OPT_MASK (0x1000U)
#define BRPHY1GV2_DSP_TOP_DSP_TEST0_DAGC_INIT_OPT_SHIFT (12U)
#define BRPHY1GV2_DSP_TOP_DSP_TEST0_SDCORSTN_FORCE_DEASSERT_MASK (0x800U)
#define BRPHY1GV2_DSP_TOP_DSP_TEST0_SDCORSTN_FORCE_DEASSERT_SHIFT (11U)
#define BRPHY1GV2_DSP_TOP_DSP_TEST0_SDCORSTN_FORCE_ASSERT_MASK (0x400U)
#define BRPHY1GV2_DSP_TOP_DSP_TEST0_SDCORSTN_FORCE_ASSERT_SHIFT (10U)
#define BRPHY1GV2_DSP_TOP_DSP_TEST0_DAGCRSTN_FORCE_DEASSERT_MASK (0x200U)
#define BRPHY1GV2_DSP_TOP_DSP_TEST0_DAGCRSTN_FORCE_DEASSERT_SHIFT (9U)
#define BRPHY1GV2_DSP_TOP_DSP_TEST0_DAGCRSTN_FORCE_ASSERT_MASK (0x100U)
#define BRPHY1GV2_DSP_TOP_DSP_TEST0_DAGCRSTN_FORCE_ASSERT_SHIFT (8U)
#define BRPHY1GV2_DSP_TOP_DSP_TEST0_SDCO_FREEZE_FORCE_DEASSERT_MASK (0x80U)
#define BRPHY1GV2_DSP_TOP_DSP_TEST0_SDCO_FREEZE_FORCE_DEASSERT_SHIFT (7U)
#define BRPHY1GV2_DSP_TOP_DSP_TEST0_SDCO_FREEZE_FORCE_ASSERT_MASK (0x40U)
#define BRPHY1GV2_DSP_TOP_DSP_TEST0_SDCO_FREEZE_FORCE_ASSERT_SHIFT (6U)
#define BRPHY1GV2_DSP_TOP_DSP_TEST0_DAGC_MU_CONTROL_MASK (0x30U)
#define BRPHY1GV2_DSP_TOP_DSP_TEST0_DAGC_MU_CONTROL_SHIFT (4U)
#define BRPHY1GV2_DSP_TOP_DSP_TEST0_DAGC_FREEZE_FORCE_DEASSERT_MASK (0x8U)
#define BRPHY1GV2_DSP_TOP_DSP_TEST0_DAGC_FREEZE_FORCE_DEASSERT_SHIFT (3U)
#define BRPHY1GV2_DSP_TOP_DSP_TEST0_DAGC_FREEZE_FORCE_ASSERT_MASK (0x4U)
#define BRPHY1GV2_DSP_TOP_DSP_TEST0_DAGC_FREEZE_FORCE_ASSERT_SHIFT (2U)
#define BRPHY1GV2_DSP_TOP_DSP_TEST0_ALT_DSP_DIG_LPBK_MASK (0x2U)
#define BRPHY1GV2_DSP_TOP_DSP_TEST0_ALT_DSP_DIG_LPBK_SHIFT (1U)
#define BRPHY1GV2_DSP_TOP_DSP_TEST0_DSP_DIG_LPBK_EN_MASK (0x1U)
#define BRPHY1GV2_DSP_TOP_DSP_TEST0_DSP_DIG_LPBK_EN_SHIFT (0U)




typedef uint16_t BRPHY1GV2_DSP_TOP_DSP_TEST1_TYPE;
#define BRPHY1GV2_DSP_TOP_DSP_TEST1_EN_FFE_TE_FORCE_DEASSERT_MASK (0x40U)
#define BRPHY1GV2_DSP_TOP_DSP_TEST1_EN_FFE_TE_FORCE_DEASSERT_SHIFT (6U)
#define BRPHY1GV2_DSP_TOP_DSP_TEST1_EN_FFE_TE_FORCE_ASSERT_MASK (0x20U)
#define BRPHY1GV2_DSP_TOP_DSP_TEST1_EN_FFE_TE_FORCE_ASSERT_SHIFT (5U)
#define BRPHY1GV2_DSP_TOP_DSP_TEST1_LOC_TRAIN_FORCE_DEASSERT_MASK (0x10U)
#define BRPHY1GV2_DSP_TOP_DSP_TEST1_LOC_TRAIN_FORCE_DEASSERT_SHIFT (4U)
#define BRPHY1GV2_DSP_TOP_DSP_TEST1_LOC_TRAIN_FORCE_ASSERT_MASK (0x8U)
#define BRPHY1GV2_DSP_TOP_DSP_TEST1_LOC_TRAIN_FORCE_ASSERT_SHIFT (3U)
#define BRPHY1GV2_DSP_TOP_DSP_TEST1_SLCTL_OVERRIDE_MASK (0x4U)
#define BRPHY1GV2_DSP_TOP_DSP_TEST1_SLCTL_OVERRIDE_SHIFT (2U)
#define BRPHY1GV2_DSP_TOP_DSP_TEST1_SLICER_CTL_MASK (0x3U)
#define BRPHY1GV2_DSP_TOP_DSP_TEST1_SLICER_CTL_SHIFT (0U)




typedef uint16_t BRPHY1GV2_DSP_TOP_AGC_STATUS_TYPE;
#define BRPHY1GV2_DSP_TOP_AGC_STATUS_PGA_1GBT_COARSE_MASK (0x7c0U)
#define BRPHY1GV2_DSP_TOP_AGC_STATUS_PGA_1GBT_COARSE_SHIFT (6U)
#define BRPHY1GV2_DSP_TOP_AGC_STATUS_PGA_1GBT_FINE_MASK (0x3fU)
#define BRPHY1GV2_DSP_TOP_AGC_STATUS_PGA_1GBT_FINE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_DSP_TOP_PHSHFT_CONTROL_TYPE;
#define BRPHY1GV2_DSP_TOP_PHSHFT_CONTROL_MAN_OFFSET_CONTINUOUS_MASK (0x800U)
#define BRPHY1GV2_DSP_TOP_PHSHFT_CONTROL_MAN_OFFSET_CONTINUOUS_SHIFT (11U)
#define BRPHY1GV2_DSP_TOP_PHSHFT_CONTROL_PHSHFT_PEND_REQ_DIS_MASK (0x400U)
#define BRPHY1GV2_DSP_TOP_PHSHFT_CONTROL_PHSHFT_PEND_REQ_DIS_SHIFT (10U)
#define BRPHY1GV2_DSP_TOP_PHSHFT_CONTROL_PHSHFT_1000_SLOW_RATE_MASK (0x200U)
#define BRPHY1GV2_DSP_TOP_PHSHFT_CONTROL_PHSHFT_1000_SLOW_RATE_SHIFT (9U)
#define BRPHY1GV2_DSP_TOP_PHSHFT_CONTROL_PHSHFT_DIR_POL_100_MASK (0x100U)
#define BRPHY1GV2_DSP_TOP_PHSHFT_CONTROL_PHSHFT_DIR_POL_100_SHIFT (8U)
#define BRPHY1GV2_DSP_TOP_PHSHFT_CONTROL_PHSHFT_DIR_POL_MASK (0x80U)
#define BRPHY1GV2_DSP_TOP_PHSHFT_CONTROL_PHSHFT_DIR_POL_SHIFT (7U)
#define BRPHY1GV2_DSP_TOP_PHSHFT_CONTROL_PHSHFT_MAN_MODE_MASK (0x40U)
#define BRPHY1GV2_DSP_TOP_PHSHFT_CONTROL_PHSHFT_MAN_MODE_SHIFT (6U)
#define BRPHY1GV2_DSP_TOP_PHSHFT_CONTROL_MAN_OFFSET_REQ_MASK (0x20U)
#define BRPHY1GV2_DSP_TOP_PHSHFT_CONTROL_MAN_OFFSET_REQ_SHIFT (5U)
#define BRPHY1GV2_DSP_TOP_PHSHFT_CONTROL_MAN_OFFSET_DIR_MASK (0x10U)
#define BRPHY1GV2_DSP_TOP_PHSHFT_CONTROL_MAN_OFFSET_DIR_SHIFT (4U)
#define BRPHY1GV2_DSP_TOP_PHSHFT_CONTROL_MAN_OFFSET_VAL_MASK (0xfU)
#define BRPHY1GV2_DSP_TOP_PHSHFT_CONTROL_MAN_OFFSET_VAL_SHIFT (0U)




typedef uint16_t BRPHY1GV2_DSP_TOP_TED_DPLL_CONTROL_TYPE;
#define BRPHY1GV2_DSP_TOP_TED_DPLL_CONTROL_ZF_MM_EN_MASK (0x2000U)
#define BRPHY1GV2_DSP_TOP_TED_DPLL_CONTROL_ZF_MM_EN_SHIFT (13U)
#define BRPHY1GV2_DSP_TOP_TED_DPLL_CONTROL_CE_TERR_SCALE_MASK (0x1c00U)
#define BRPHY1GV2_DSP_TOP_TED_DPLL_CONTROL_CE_TERR_SCALE_SHIFT (10U)
#define BRPHY1GV2_DSP_TOP_TED_DPLL_CONTROL_BW_CNTL1_MASK (0x300U)
#define BRPHY1GV2_DSP_TOP_TED_DPLL_CONTROL_BW_CNTL1_SHIFT (8U)
#define BRPHY1GV2_DSP_TOP_TED_DPLL_CONTROL_BW_CNTL0_MASK (0xc0U)
#define BRPHY1GV2_DSP_TOP_TED_DPLL_CONTROL_BW_CNTL0_SHIFT (6U)
#define BRPHY1GV2_DSP_TOP_TED_DPLL_CONTROL_DPLL_KP_MASK (0x30U)
#define BRPHY1GV2_DSP_TOP_TED_DPLL_CONTROL_DPLL_KP_SHIFT (4U)
#define BRPHY1GV2_DSP_TOP_TED_DPLL_CONTROL_DPLL_G1_MASK (0x4U)
#define BRPHY1GV2_DSP_TOP_TED_DPLL_CONTROL_DPLL_G1_SHIFT (2U)
#define BRPHY1GV2_DSP_TOP_TED_DPLL_CONTROL_DPLL_G2_MASK (0x3U)
#define BRPHY1GV2_DSP_TOP_TED_DPLL_CONTROL_DPLL_G2_SHIFT (0U)




typedef uint16_t BRPHY1GV2_DSP_TOP_AGC_100_REF_LVL_TYPE;
#define BRPHY1GV2_DSP_TOP_AGC_100_REF_LVL_MASK (0x7fU)
#define BRPHY1GV2_DSP_TOP_AGC_100_REF_LVL_SHIFT (0U)




typedef uint16_t BRPHY1GV2_DSP_TOP_A100O0_TYPE;
#define BRPHY1GV2_DSP_TOP_A100O0_FAGCSCALE_100_MASK (0x3000U)
#define BRPHY1GV2_DSP_TOP_A100O0_FAGCSCALE_100_SHIFT (12U)
#define BRPHY1GV2_DSP_TOP_A100O0_AGC_PWRSAVE_DIS_100_MASK (0x400U)
#define BRPHY1GV2_DSP_TOP_A100O0_AGC_PWRSAVE_DIS_100_SHIFT (10U)
#define BRPHY1GV2_DSP_TOP_A100O0_CAGCHIGEAR_OVR_VAL_100_MASK (0x200U)
#define BRPHY1GV2_DSP_TOP_A100O0_CAGCHIGEAR_OVR_VAL_100_SHIFT (9U)
#define BRPHY1GV2_DSP_TOP_A100O0_CAGCHIGEAR_OVR_100_MASK (0x100U)
#define BRPHY1GV2_DSP_TOP_A100O0_CAGCHIGEAR_OVR_100_SHIFT (8U)
#define BRPHY1GV2_DSP_TOP_A100O0_CAGCFRZ_OVR_VAL_100_MASK (0x80U)
#define BRPHY1GV2_DSP_TOP_A100O0_CAGCFRZ_OVR_VAL_100_SHIFT (7U)
#define BRPHY1GV2_DSP_TOP_A100O0_CAGCFRZ_OVR_100_MASK (0x40U)
#define BRPHY1GV2_DSP_TOP_A100O0_CAGCFRZ_OVR_100_SHIFT (6U)
#define BRPHY1GV2_DSP_TOP_A100O0_CAGCRST_OVR_VAL_100_MASK (0x20U)
#define BRPHY1GV2_DSP_TOP_A100O0_CAGCRST_OVR_VAL_100_SHIFT (5U)
#define BRPHY1GV2_DSP_TOP_A100O0_CAGCRST_OVR_100_MASK (0x10U)
#define BRPHY1GV2_DSP_TOP_A100O0_CAGCRST_OVR_100_SHIFT (4U)
#define BRPHY1GV2_DSP_TOP_A100O0_FAGCFRZ_OVR_VAL_100_MASK (0x8U)
#define BRPHY1GV2_DSP_TOP_A100O0_FAGCFRZ_OVR_VAL_100_SHIFT (3U)
#define BRPHY1GV2_DSP_TOP_A100O0_FAGCFRZ_OVR_100_MASK (0x4U)
#define BRPHY1GV2_DSP_TOP_A100O0_FAGCFRZ_OVR_100_SHIFT (2U)
#define BRPHY1GV2_DSP_TOP_A100O0_FAGCRST_OVR_VAL_100_MASK (0x2U)
#define BRPHY1GV2_DSP_TOP_A100O0_FAGCRST_OVR_VAL_100_SHIFT (1U)
#define BRPHY1GV2_DSP_TOP_A100O0_FAGCRST_OVR_100_MASK (0x1U)
#define BRPHY1GV2_DSP_TOP_A100O0_FAGCRST_OVR_100_SHIFT (0U)




typedef uint16_t BRPHY1GV2_DSP_TOP_A100O1_TYPE;
#define BRPHY1GV2_DSP_TOP_A100O1_COARSE_GAIN_CTL_OVR_VAL_100_MASK (0xfeU)
#define BRPHY1GV2_DSP_TOP_A100O1_COARSE_GAIN_CTL_OVR_VAL_100_SHIFT (1U)
#define BRPHY1GV2_DSP_TOP_A100O1_COARSE_GAIN_CTL_OVR_100_MASK (0x1U)
#define BRPHY1GV2_DSP_TOP_A100O1_COARSE_GAIN_CTL_OVR_100_SHIFT (0U)




typedef uint16_t BRPHY1GV2_DSP_TOP_AGC_100_STATUS_TYPE;
#define BRPHY1GV2_DSP_TOP_AGC_100_STATUS_COARSE_FREEZE_SMPC_100_MASK (0x100U)
#define BRPHY1GV2_DSP_TOP_AGC_100_STATUS_COARSE_FREEZE_SMPC_100_SHIFT (8U)
#define BRPHY1GV2_DSP_TOP_AGC_100_STATUS_AGC_OVERFLOW_100_MASK (0x80U)
#define BRPHY1GV2_DSP_TOP_AGC_100_STATUS_AGC_OVERFLOW_100_SHIFT (7U)
#define BRPHY1GV2_DSP_TOP_AGC_100_STATUS_PGA_100BT_MASK (0x7fU)
#define BRPHY1GV2_DSP_TOP_AGC_100_STATUS_PGA_100BT_SHIFT (0U)




typedef uint16_t BRPHY1GV2_DSP_TOP_AGC_100_CTRL_0_TYPE;
#define BRPHY1GV2_DSP_TOP_AGC_100_CTRL_0_LEGACY_CTRL_100_MASK (0x7ffcU)
#define BRPHY1GV2_DSP_TOP_AGC_100_CTRL_0_LEGACY_CTRL_100_SHIFT (2U)
#define BRPHY1GV2_DSP_TOP_AGC_100_CTRL_0_RST_VAL_100_MASK (0x3U)
#define BRPHY1GV2_DSP_TOP_AGC_100_CTRL_0_RST_VAL_100_SHIFT (0U)




typedef uint16_t BRPHY1GV2_DSP_TOP_DCOFFSET_ACCUM_LSB_TYPE;
#define BRPHY1GV2_DSP_TOP_DCOFFSET_ACCUM_LSB_MASK (0xffffU)
#define BRPHY1GV2_DSP_TOP_DCOFFSET_ACCUM_LSB_SHIFT (0U)




typedef uint16_t BRPHY1GV2_DSP_TOP_DCOFFSET_ACCUM_MSB_TYPE;
#define BRPHY1GV2_DSP_TOP_DCOFFSET_ACCUM_MSB_MASK (0xfU)
#define BRPHY1GV2_DSP_TOP_DCOFFSET_ACCUM_MSB_SHIFT (0U)




typedef uint16_t BRPHY1GV2_DSP_TOP_DAGC_ACCUM_LSB_TYPE;
#define BRPHY1GV2_DSP_TOP_DAGC_ACCUM_LSB_MASK (0xffffU)
#define BRPHY1GV2_DSP_TOP_DAGC_ACCUM_LSB_SHIFT (0U)




typedef uint16_t BRPHY1GV2_DSP_TOP_DAGC_ACCUM_MSB_TYPE;
#define BRPHY1GV2_DSP_TOP_DAGC_ACCUM_MSB_MASK (0x7fU)
#define BRPHY1GV2_DSP_TOP_DAGC_ACCUM_MSB_SHIFT (0U)




typedef uint16_t BRPHY1GV2_DSP_TOP_DFBC_TYPE;
#define BRPHY1GV2_DSP_TOP_DFBC_DPLL_FRZ_FORCE_DEASSERT_MASK (0x100U)
#define BRPHY1GV2_DSP_TOP_DFBC_DPLL_FRZ_FORCE_DEASSERT_SHIFT (8U)
#define BRPHY1GV2_DSP_TOP_DFBC_DPLL_FRZ_FORCE_ASSERT_MASK (0x80U)
#define BRPHY1GV2_DSP_TOP_DFBC_DPLL_FRZ_FORCE_ASSERT_SHIFT (7U)
#define BRPHY1GV2_DSP_TOP_DFBC_DPLL_ILPFRZ_FORCE_DEASSERT_MASK (0x40U)
#define BRPHY1GV2_DSP_TOP_DFBC_DPLL_ILPFRZ_FORCE_DEASSERT_SHIFT (6U)
#define BRPHY1GV2_DSP_TOP_DFBC_DPLL_ILPFRZ_FORCE_ASSERT_MASK (0x20U)
#define BRPHY1GV2_DSP_TOP_DFBC_DPLL_ILPFRZ_FORCE_ASSERT_SHIFT (5U)
#define BRPHY1GV2_DSP_TOP_DFBC_DPLL_HIBW_OVERRIDE_MASK (0x10U)
#define BRPHY1GV2_DSP_TOP_DFBC_DPLL_HIBW_OVERRIDE_SHIFT (4U)
#define BRPHY1GV2_DSP_TOP_DFBC_DPLL_HIBW_MASK (0x8U)
#define BRPHY1GV2_DSP_TOP_DFBC_DPLL_HIBW_SHIFT (3U)
#define BRPHY1GV2_DSP_TOP_DFBC_DPLL_ILPBW_OVERRIDE_MASK (0x4U)
#define BRPHY1GV2_DSP_TOP_DFBC_DPLL_ILPBW_OVERRIDE_SHIFT (2U)
#define BRPHY1GV2_DSP_TOP_DFBC_DPLL_ILPBW_MASK (0x3U)
#define BRPHY1GV2_DSP_TOP_DFBC_DPLL_ILPBW_SHIFT (0U)




typedef uint16_t BRPHY1GV2_DSP_TOP_DFPC_TYPE;
#define BRPHY1GV2_DSP_TOP_DFPC_DPLL_FVAL_OVERRIDE_MASK (0x10U)
#define BRPHY1GV2_DSP_TOP_DFPC_DPLL_FVAL_OVERRIDE_SHIFT (4U)
#define BRPHY1GV2_DSP_TOP_DFPC_DPLL_FRST_FORCE_DEASSERT_MASK (0x8U)
#define BRPHY1GV2_DSP_TOP_DFPC_DPLL_FRST_FORCE_DEASSERT_SHIFT (3U)
#define BRPHY1GV2_DSP_TOP_DFPC_DPLL_FRST_FORCE_ASSERT_MASK (0x4U)
#define BRPHY1GV2_DSP_TOP_DFPC_DPLL_FRST_FORCE_ASSERT_SHIFT (2U)
#define BRPHY1GV2_DSP_TOP_DFPC_DPLL_PRAMP_FORCE_DEASSERT_MASK (0x2U)
#define BRPHY1GV2_DSP_TOP_DFPC_DPLL_PRAMP_FORCE_DEASSERT_SHIFT (1U)
#define BRPHY1GV2_DSP_TOP_DFPC_DPLL_PRAMP_FORCE_ASSERT_MASK (0x1U)
#define BRPHY1GV2_DSP_TOP_DFPC_DPLL_PRAMP_FORCE_ASSERT_SHIFT (0U)




typedef uint16_t BRPHY1GV2_DSP_TOP_DPLL_FVAL_LSB_TYPE;
#define BRPHY1GV2_DSP_TOP_DPLL_FVAL_LSB_DAGC_ACCUM_MASK (0xffffU)
#define BRPHY1GV2_DSP_TOP_DPLL_FVAL_LSB_DAGC_ACCUM_SHIFT (0U)




typedef uint16_t BRPHY1GV2_DSP_TOP_DPLL_FVAL_MSB_TYPE;
#define BRPHY1GV2_DSP_TOP_DPLL_FVAL_MSB_DAGC_ACCUM_MASK (0xfffU)
#define BRPHY1GV2_DSP_TOP_DPLL_FVAL_MSB_DAGC_ACCUM_SHIFT (0U)




typedef uint16_t BRPHY1GV2_DSP_TOP_CE_TIMING_ERROR_TYPE;
#define BRPHY1GV2_DSP_TOP_CE_TIMING_ERROR_MASK (0xfffU)
#define BRPHY1GV2_DSP_TOP_CE_TIMING_ERROR_SHIFT (0U)




typedef uint16_t BRPHY1GV2_DSP_TOP_PHERR_ACCUM_S1_TYPE;
#define BRPHY1GV2_DSP_TOP_PHERR_ACCUM_S1_MASK (0x3fffU)
#define BRPHY1GV2_DSP_TOP_PHERR_ACCUM_S1_SHIFT (0U)




typedef uint16_t BRPHY1GV2_DSP_TOP_PHERR_ACCUM_S2_TYPE;
#define BRPHY1GV2_DSP_TOP_PHERR_ACCUM_S2_MASK (0x3fffU)
#define BRPHY1GV2_DSP_TOP_PHERR_ACCUM_S2_SHIFT (0U)




typedef uint16_t BRPHY1GV2_DSP_TOP_PHASE_ERROR_TYPE;
#define BRPHY1GV2_DSP_TOP_PHASE_ERROR_MASK (0x3fffU)
#define BRPHY1GV2_DSP_TOP_PHASE_ERROR_SHIFT (0U)




typedef uint16_t BRPHY1GV2_DSP_TOP_INTEGRAL_ERROR_LSB_TYPE;
#define BRPHY1GV2_DSP_TOP_INTEGRAL_ERROR_LSB_MASK (0xffffU)
#define BRPHY1GV2_DSP_TOP_INTEGRAL_ERROR_LSB_SHIFT (0U)




typedef uint16_t BRPHY1GV2_DSP_TOP_INTEGRAL_ERROR_MSB_TYPE;
#define BRPHY1GV2_DSP_TOP_INTEGRAL_ERROR_MSB_MASK (0xfffU)
#define BRPHY1GV2_DSP_TOP_INTEGRAL_ERROR_MSB_SHIFT (0U)




typedef uint16_t BRPHY1GV2_DSP_TOP_NCO_ACCUM_LSB_TYPE;
#define BRPHY1GV2_DSP_TOP_NCO_ACCUM_LSB_MASK (0xffffU)
#define BRPHY1GV2_DSP_TOP_NCO_ACCUM_LSB_SHIFT (0U)




typedef uint16_t BRPHY1GV2_DSP_TOP_NCO_ACCUM_MSB_TYPE;
#define BRPHY1GV2_DSP_TOP_NCO_ACCUM_MSB_MASK (0x1fU)
#define BRPHY1GV2_DSP_TOP_NCO_ACCUM_MSB_SHIFT (0U)




typedef uint16_t BRPHY1GV2_DSP_TOP_PHASE_CONTROL_TYPE;
#define BRPHY1GV2_DSP_TOP_PHASE_CONTROL_MASK (0xfU)
#define BRPHY1GV2_DSP_TOP_PHASE_CONTROL_SHIFT (0U)




typedef uint16_t BRPHY1GV2_DSP_TOP_FCPL_TYPE;
#define BRPHY1GV2_DSP_TOP_FCPL_FIRST_CE_PRECURSOR_LSB_MASK (0xffffU)
#define BRPHY1GV2_DSP_TOP_FCPL_FIRST_CE_PRECURSOR_LSB_SHIFT (0U)




typedef uint16_t BRPHY1GV2_DSP_TOP_FCPM_TYPE;
#define BRPHY1GV2_DSP_TOP_FCPM_FIRST_CE_PRECURSOR_MSB_MASK (0x1ffU)
#define BRPHY1GV2_DSP_TOP_FCPM_FIRST_CE_PRECURSOR_MSB_SHIFT (0U)




typedef uint16_t BRPHY1GV2_DSP_TOP_SPARE_ADDR_TYPE;
#define BRPHY1GV2_DSP_TOP_SPARE_ADDR_REGISTER_MASK (0xffffU)
#define BRPHY1GV2_DSP_TOP_SPARE_ADDR_REGISTER_SHIFT (0U)




typedef volatile struct sBRPHY1GV2_DSP_TOP_RDBType {
    BRPHY1GV2_DSP_TOP_DAGC_STATUS_0_TYPE dagc_status_0; /* OFFSET: 0x0 */
    BRPHY1GV2_DSP_TOP_RESERVED_TYPE rsvd0[2]; /* OFFSET: 0x2 */
    BRPHY1GV2_DSP_TOP_DAGC_STATUS_1_TYPE dagc_status_1; /* OFFSET: 0x4 */
    BRPHY1GV2_DSP_TOP_RESERVED_TYPE rsvd1[2]; /* OFFSET: 0x6 */
    BRPHY1GV2_DSP_TOP_SOFT_DECISION_TYPE soft_decision_even; /* OFFSET: 0x8 */
    BRPHY1GV2_DSP_TOP_RESERVED_TYPE rsvd2[2]; /* OFFSET: 0xa */
    BRPHY1GV2_DSP_TOP_SOFT_DECISION_TYPE soft_decision_odd; /* OFFSET: 0xc */
    BRPHY1GV2_DSP_TOP_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0xe */
    BRPHY1GV2_DSP_TOP_AGC_REF_LVL_TYPE agc_ref_lvl; /* OFFSET: 0x10 */
    BRPHY1GV2_DSP_TOP_RESERVED_TYPE rsvd4[2]; /* OFFSET: 0x12 */
    BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_0_TYPE agc_override_0; /* OFFSET: 0x14 */
    BRPHY1GV2_DSP_TOP_RESERVED_TYPE rsvd5[2]; /* OFFSET: 0x16 */
    BRPHY1GV2_DSP_TOP_AGC_OVERRIDE_1_TYPE agc_override_1; /* OFFSET: 0x18 */
    BRPHY1GV2_DSP_TOP_RESERVED_TYPE rsvd6[2]; /* OFFSET: 0x1a */
    BRPHY1GV2_DSP_TOP_DSP_TEST0_TYPE dsp_test0; /* OFFSET: 0x1c */
    BRPHY1GV2_DSP_TOP_RESERVED_TYPE rsvd7[2]; /* OFFSET: 0x1e */
    BRPHY1GV2_DSP_TOP_DSP_TEST1_TYPE dsp_test1; /* OFFSET: 0x20 */
    BRPHY1GV2_DSP_TOP_RESERVED_TYPE rsvd8[2]; /* OFFSET: 0x22 */
    BRPHY1GV2_DSP_TOP_AGC_STATUS_TYPE agc_status; /* OFFSET: 0x24 */
    BRPHY1GV2_DSP_TOP_RESERVED_TYPE rsvd9[2]; /* OFFSET: 0x26 */
    BRPHY1GV2_DSP_TOP_PHSHFT_CONTROL_TYPE phshft_control; /* OFFSET: 0x28 */
    BRPHY1GV2_DSP_TOP_RESERVED_TYPE rsvd10[2]; /* OFFSET: 0x2a */
    BRPHY1GV2_DSP_TOP_TED_DPLL_CONTROL_TYPE ted_dpll_control; /* OFFSET: 0x2c */
    BRPHY1GV2_DSP_TOP_RESERVED_TYPE rsvd11[2]; /* OFFSET: 0x2e */
    BRPHY1GV2_DSP_TOP_AGC_100_REF_LVL_TYPE agc_100_ref_lvl; /* OFFSET: 0x30 */
    BRPHY1GV2_DSP_TOP_RESERVED_TYPE rsvd12[2]; /* OFFSET: 0x32 */
    BRPHY1GV2_DSP_TOP_A100O0_TYPE agc_100_override_0; /* OFFSET: 0x34 */
    BRPHY1GV2_DSP_TOP_RESERVED_TYPE rsvd13[2]; /* OFFSET: 0x36 */
    BRPHY1GV2_DSP_TOP_A100O1_TYPE agc_100_override_1; /* OFFSET: 0x38 */
    BRPHY1GV2_DSP_TOP_RESERVED_TYPE rsvd14[2]; /* OFFSET: 0x3a */
    BRPHY1GV2_DSP_TOP_AGC_100_STATUS_TYPE agc_100_status; /* OFFSET: 0x3c */
    BRPHY1GV2_DSP_TOP_RESERVED_TYPE rsvd15[2]; /* OFFSET: 0x3e */
    BRPHY1GV2_DSP_TOP_AGC_100_CTRL_0_TYPE agc_100_ctrl_0; /* OFFSET: 0x40 */
    BRPHY1GV2_DSP_TOP_RESERVED_TYPE rsvd16[2]; /* OFFSET: 0x42 */
    BRPHY1GV2_DSP_TOP_DCOFFSET_ACCUM_LSB_TYPE dcoffset_accum_lsb; /* OFFSET: 0x44 */
    BRPHY1GV2_DSP_TOP_RESERVED_TYPE rsvd17[2]; /* OFFSET: 0x46 */
    BRPHY1GV2_DSP_TOP_DCOFFSET_ACCUM_MSB_TYPE dcoffset_accum_msb; /* OFFSET: 0x48 */
    BRPHY1GV2_DSP_TOP_RESERVED_TYPE rsvd18[2]; /* OFFSET: 0x4a */
    BRPHY1GV2_DSP_TOP_DAGC_ACCUM_LSB_TYPE dagc_accum_lsb; /* OFFSET: 0x4c */
    BRPHY1GV2_DSP_TOP_RESERVED_TYPE rsvd19[2]; /* OFFSET: 0x4e */
    BRPHY1GV2_DSP_TOP_DAGC_ACCUM_MSB_TYPE dagc_accum_msb; /* OFFSET: 0x50 */
    BRPHY1GV2_DSP_TOP_RESERVED_TYPE rsvd20[2]; /* OFFSET: 0x52 */
    BRPHY1GV2_DSP_TOP_DFBC_TYPE dpll_frz_bw_control; /* OFFSET: 0x54 */
    BRPHY1GV2_DSP_TOP_RESERVED_TYPE rsvd21[2]; /* OFFSET: 0x56 */
    BRPHY1GV2_DSP_TOP_DFPC_TYPE dpll_frst_pramp_control; /* OFFSET: 0x58 */
    BRPHY1GV2_DSP_TOP_RESERVED_TYPE rsvd22[2]; /* OFFSET: 0x5a */
    BRPHY1GV2_DSP_TOP_DPLL_FVAL_LSB_TYPE dpll_fval_lsb; /* OFFSET: 0x5c */
    BRPHY1GV2_DSP_TOP_RESERVED_TYPE rsvd23[2]; /* OFFSET: 0x5e */
    BRPHY1GV2_DSP_TOP_DPLL_FVAL_MSB_TYPE dpll_fval_msb; /* OFFSET: 0x60 */
    BRPHY1GV2_DSP_TOP_RESERVED_TYPE rsvd24[2]; /* OFFSET: 0x62 */
    BRPHY1GV2_DSP_TOP_CE_TIMING_ERROR_TYPE ce_timing_error; /* OFFSET: 0x64 */
    BRPHY1GV2_DSP_TOP_RESERVED_TYPE rsvd25[2]; /* OFFSET: 0x66 */
    BRPHY1GV2_DSP_TOP_PHERR_ACCUM_S1_TYPE pherr_accum_s1; /* OFFSET: 0x68 */
    BRPHY1GV2_DSP_TOP_RESERVED_TYPE rsvd26[2]; /* OFFSET: 0x6a */
    BRPHY1GV2_DSP_TOP_PHERR_ACCUM_S2_TYPE pherr_accum_s2; /* OFFSET: 0x6c */
    BRPHY1GV2_DSP_TOP_RESERVED_TYPE rsvd27[2]; /* OFFSET: 0x6e */
    BRPHY1GV2_DSP_TOP_PHASE_ERROR_TYPE phase_error; /* OFFSET: 0x70 */
    BRPHY1GV2_DSP_TOP_RESERVED_TYPE rsvd28[2]; /* OFFSET: 0x72 */
    BRPHY1GV2_DSP_TOP_INTEGRAL_ERROR_LSB_TYPE integral_error_lsb; /* OFFSET: 0x74 */
    BRPHY1GV2_DSP_TOP_RESERVED_TYPE rsvd29[2]; /* OFFSET: 0x76 */
    BRPHY1GV2_DSP_TOP_INTEGRAL_ERROR_MSB_TYPE integral_error_msb; /* OFFSET: 0x78 */
    BRPHY1GV2_DSP_TOP_RESERVED_TYPE rsvd30[2]; /* OFFSET: 0x7a */
    BRPHY1GV2_DSP_TOP_NCO_ACCUM_LSB_TYPE nco_accum_lsb; /* OFFSET: 0x7c */
    BRPHY1GV2_DSP_TOP_RESERVED_TYPE rsvd31[2]; /* OFFSET: 0x7e */
    BRPHY1GV2_DSP_TOP_NCO_ACCUM_MSB_TYPE nco_accum_msb; /* OFFSET: 0x80 */
    BRPHY1GV2_DSP_TOP_RESERVED_TYPE rsvd32[2]; /* OFFSET: 0x82 */
    BRPHY1GV2_DSP_TOP_PHASE_CONTROL_TYPE phase_control; /* OFFSET: 0x84 */
    BRPHY1GV2_DSP_TOP_RESERVED_TYPE rsvd33[2]; /* OFFSET: 0x86 */
    BRPHY1GV2_DSP_TOP_FCPL_TYPE first_ce_precursor_lsb; /* OFFSET: 0x88 */
    BRPHY1GV2_DSP_TOP_RESERVED_TYPE rsvd34[2]; /* OFFSET: 0x8a */
    BRPHY1GV2_DSP_TOP_FCPM_TYPE first_ce_precursor_msb; /* OFFSET: 0x8c */
    BRPHY1GV2_DSP_TOP_RESERVED_TYPE rsvd35[110]; /* OFFSET: 0x8e */
    BRPHY1GV2_DSP_TOP_SPARE_ADDR_TYPE spare_end_addr; /* OFFSET: 0xfc */
} BRPHY1GV2_DSP_TOP_RDBType;


#define BRPHY0_1G_DSP_TOP_BASE          (0xE0561400UL)



#define BRPHY1GV2_DSP_TOP_MAX_HW_ID     (1UL)

#endif /* BRPHY1GV2_DSP_TOP_RDB_H */
