/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file brphy1gv2_link_sync_rdb.h
    @brief RDB File for BRPHY1GV2_LINK_SYNC

    @version BCM89580_A0_20230125_RDB
*/

#ifndef BRPHY1GV2_LINK_SYNC_RDB_H
#define BRPHY1GV2_LINK_SYNC_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t BRPHY1GV2_LINK_SYNC_SIGDET_THRESHOLD_TYPE;
#define BRPHY1GV2_LINK_SYNC_SIGDET_THRESHOLD_AUTO_THRESHOLD_MASK (0xf000U)
#define BRPHY1GV2_LINK_SYNC_SIGDET_THRESHOLD_AUTO_THRESHOLD_SHIFT (12U)
#define BRPHY1GV2_LINK_SYNC_SIGDET_THRESHOLD_THRESHOLD_MASK (0xfffU)
#define BRPHY1GV2_LINK_SYNC_SIGDET_THRESHOLD_THRESHOLD_SHIFT (0U)




typedef uint8_t BRPHY1GV2_LINK_SYNC_RESERVED_TYPE;




typedef uint16_t BRPHY1GV2_LINK_SYNC_SIGDET_WINDOW_TYPE;
#define BRPHY1GV2_LINK_SYNC_SIGDET_WINDOW_HIGH_MASK (0xff00U)
#define BRPHY1GV2_LINK_SYNC_SIGDET_WINDOW_HIGH_SHIFT (8U)
#define BRPHY1GV2_LINK_SYNC_SIGDET_WINDOW_LOW_MASK (0xffU)
#define BRPHY1GV2_LINK_SYNC_SIGDET_WINDOW_LOW_SHIFT (0U)




typedef uint16_t BRPHY1GV2_LINK_SYNC_CONTROL_A_TYPE;
#define BRPHY1GV2_LINK_SYNC_CONTROL_A_AUTOSPEED_EN_MASK (0x8000U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_A_AUTOSPEED_EN_SHIFT (15U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_A_SPARE_14_MASK (0x4000U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_A_SPARE_14_SHIFT (14U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_A_AUTOSPEED_MS_MASK (0x2000U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_A_AUTOSPEED_MS_SHIFT (13U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_A_AUTOSPEED_RX_SYMBOL_ORDER_MASK (0x1000U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_A_AUTOSPEED_RX_SYMBOL_ORDER_SHIFT (12U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_A_AUTOSPEED_TX_SYMBOL_ORDER_MASK (0x800U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_A_AUTOSPEED_TX_SYMBOL_ORDER_SHIFT (11U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_A_SPARE_10_MASK (0x400U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_A_SPARE_10_SHIFT (10U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_A_AUTOSPEED_OVR_FREQ_VALUE_MASK (0x300U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_A_AUTOSPEED_OVR_FREQ_VALUE_SHIFT (8U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_A_AUTOSPEED_OVR_FREQ_EN_MASK (0x80U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_A_AUTOSPEED_OVR_FREQ_EN_SHIFT (7U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_A_SYNC_1000T1_DETECT_VALUE_MASK (0x40U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_A_SYNC_1000T1_DETECT_VALUE_SHIFT (6U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_A_SYNC_1000T1_DETECT_FORCE_MASK (0x20U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_A_SYNC_1000T1_DETECT_FORCE_SHIFT (5U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_A_LEGACY_100T1_DETECT_VALUE_MASK (0x10U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_A_LEGACY_100T1_DETECT_VALUE_SHIFT (4U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_A_LEGACY_100T1_DETECT_FORCE_MASK (0x8U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_A_LEGACY_100T1_DETECT_FORCE_SHIFT (3U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_A_SYNC_LINK_CTRL_100T1_VALUE_MASK (0x4U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_A_SYNC_LINK_CTRL_100T1_VALUE_SHIFT (2U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_A_SYNC_LINK_CTRL_1000T1_VALUE_MASK (0x2U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_A_SYNC_LINK_CTRL_1000T1_VALUE_SHIFT (1U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_A_SYNC_LINK_CTRL_FORCE_MASK (0x1U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_A_SYNC_LINK_CTRL_FORCE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_LINK_SYNC_CONTROL_B_TYPE;
#define BRPHY1GV2_LINK_SYNC_CONTROL_B_MF_FORCE_CONFIG_POLARITY_MASK (0x8000U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_B_MF_FORCE_CONFIG_POLARITY_SHIFT (15U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_B_MF_ODDEVEN_SWAP_MASK (0x4000U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_B_MF_ODDEVEN_SWAP_SHIFT (14U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_B_MF_ENABLE_MASK (0x2000U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_B_MF_ENABLE_SHIFT (13U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_B_MF_INPUT_SHIFT_MASK (0x1800U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_B_MF_INPUT_SHIFT_SHIFT (11U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_B_MF_ONE_PEAK_EN_MASK (0x400U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_B_MF_ONE_PEAK_EN_SHIFT (10U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_B_MF_CLK_OVERRIDE_EN_MASK (0x200U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_B_MF_CLK_OVERRIDE_EN_SHIFT (9U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_B_LINK_SYNC_TEST_MODE_MASK (0x1e0U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_B_LINK_SYNC_TEST_MODE_SHIFT (5U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_B_LFITC_MASK (0x18U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_B_LFITC_SHIFT (3U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_B_BREAK_LINK_TIMER_ACCEL_MASK (0x4U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_B_BREAK_LINK_TIMER_ACCEL_SHIFT (2U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_B_LINK_MONITOR_STATE_VALUE_MASK (0x2U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_B_LINK_MONITOR_STATE_VALUE_SHIFT (1U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_B_LINK_MONITOR_STATE_FORCE_MASK (0x1U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_B_LINK_MONITOR_STATE_FORCE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_LINK_SYNC_CONTROL_C_TYPE;
#define BRPHY1GV2_LINK_SYNC_CONTROL_C_MF_WDOG_TIMER_DISABLE_MASK (0x8000U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_C_MF_WDOG_TIMER_DISABLE_SHIFT (15U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_C_MF_SKIP_DISABLE_MASK (0x4000U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_C_MF_SKIP_DISABLE_SHIFT (14U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_C_LYNKSYNC_PGA_FINE_MASK (0x3f00U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_C_LYNKSYNC_PGA_FINE_SHIFT (8U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_C_MF_SIGDET_CLEAR_TIMER_SEL_MASK (0xe0U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_C_MF_SIGDET_CLEAR_TIMER_SEL_SHIFT (5U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_C_LYNKSYNC_PGA_COARSE_MASK (0x1fU)
#define BRPHY1GV2_LINK_SYNC_CONTROL_C_LYNKSYNC_PGA_COARSE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_LINK_SYNC_STATUS_A_TYPE;
#define BRPHY1GV2_LINK_SYNC_STATUS_A_LEGACY_100T1_DETECT_STATUS_MASK (0x8000U)
#define BRPHY1GV2_LINK_SYNC_STATUS_A_LEGACY_100T1_DETECT_STATUS_SHIFT (15U)
#define BRPHY1GV2_LINK_SYNC_STATUS_A_AUTOSPEED_FSM_STAT_MASK (0x7000U)
#define BRPHY1GV2_LINK_SYNC_STATUS_A_AUTOSPEED_FSM_STAT_SHIFT (12U)
#define BRPHY1GV2_LINK_SYNC_STATUS_A_STATUS_A_SPARE_1_MASK (0x800U)
#define BRPHY1GV2_LINK_SYNC_STATUS_A_STATUS_A_SPARE_1_SHIFT (11U)
#define BRPHY1GV2_LINK_SYNC_STATUS_A_SYNC_LINK_FSM_STAT_MASK (0x700U)
#define BRPHY1GV2_LINK_SYNC_STATUS_A_SYNC_LINK_FSM_STAT_SHIFT (8U)
#define BRPHY1GV2_LINK_SYNC_STATUS_A_AACV_MASK (0xe0U)
#define BRPHY1GV2_LINK_SYNC_STATUS_A_AACV_SHIFT (5U)
#define BRPHY1GV2_LINK_SYNC_STATUS_A_AUTOSPEED_CHANGED_SPEED_MASK (0x10U)
#define BRPHY1GV2_LINK_SYNC_STATUS_A_AUTOSPEED_CHANGED_SPEED_SHIFT (4U)
#define BRPHY1GV2_LINK_SYNC_STATUS_A_STATUS_A_SPARE_0_MASK (0xcU)
#define BRPHY1GV2_LINK_SYNC_STATUS_A_STATUS_A_SPARE_0_SHIFT (2U)
#define BRPHY1GV2_LINK_SYNC_STATUS_A_SYNC_LINK_CONTROL_100T1_STAT_MASK (0x2U)
#define BRPHY1GV2_LINK_SYNC_STATUS_A_SYNC_LINK_CONTROL_100T1_STAT_SHIFT (1U)
#define BRPHY1GV2_LINK_SYNC_STATUS_A_SLC10001S_MASK (0x1U)
#define BRPHY1GV2_LINK_SYNC_STATUS_A_SLC10001S_SHIFT (0U)




typedef uint16_t BRPHY1GV2_LINK_SYNC_STATUS_B_TYPE;
#define BRPHY1GV2_LINK_SYNC_STATUS_B_STATUS_B_SPARE_1_MASK (0xfc00U)
#define BRPHY1GV2_LINK_SYNC_STATUS_B_STATUS_B_SPARE_1_SHIFT (10U)
#define BRPHY1GV2_LINK_SYNC_STATUS_B_SEND_S_SIGPOL_STAT_MASK (0x200U)
#define BRPHY1GV2_LINK_SYNC_STATUS_B_SEND_S_SIGPOL_STAT_SHIFT (9U)
#define BRPHY1GV2_LINK_SYNC_STATUS_B_SEND_S_SIGDET_STAT_MASK (0x100U)
#define BRPHY1GV2_LINK_SYNC_STATUS_B_SEND_S_SIGDET_STAT_SHIFT (8U)
#define BRPHY1GV2_LINK_SYNC_STATUS_B_STATUS_B_SPARE_0_MASK (0xfeU)
#define BRPHY1GV2_LINK_SYNC_STATUS_B_STATUS_B_SPARE_0_SHIFT (1U)
#define BRPHY1GV2_LINK_SYNC_STATUS_B_LINK_STAT_MASK (0x1U)
#define BRPHY1GV2_LINK_SYNC_STATUS_B_LINK_STAT_SHIFT (0U)




typedef uint16_t BRPHY1GV2_LINK_SYNC_WUP_CONTROL_TYPE;
#define BRPHY1GV2_LINK_SYNC_WUP_CONTROL_LOC_WAKE_REQ_MODES_MASK (0xe000U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONTROL_LOC_WAKE_REQ_MODES_SHIFT (13U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONTROL_LWR10001OE_MASK (0x1000U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONTROL_LWR10001OE_SHIFT (12U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONTROL_LWR10001OV_MASK (0x800U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONTROL_LWR10001OV_SHIFT (11U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONTROL_LWR1001OE_MASK (0x400U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONTROL_LWR1001OE_SHIFT (10U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONTROL_LWR1001OV_MASK (0x200U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONTROL_LWR1001OV_SHIFT (9U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONTROL_SWDOE_MASK (0x100U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONTROL_SWDOE_SHIFT (8U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONTROL_SWDOV_MASK (0x80U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONTROL_SWDOV_SHIFT (7U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONTROL_SEND_WUP_DONE_POLARITY_MASK (0x40U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONTROL_SEND_WUP_DONE_POLARITY_SHIFT (6U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONTROL_WUP_TIMER_EN_NON_TC10_MASK (0x20U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONTROL_WUP_TIMER_EN_NON_TC10_SHIFT (5U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONTROL_WTEF10001FMS_MASK (0x10U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONTROL_WTEF10001FMS_SHIFT (4U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONTROL_WTEF10001FMM_MASK (0x8U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONTROL_WTEF10001FMM_SHIFT (3U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONTROL_WTEF1001FMS_MASK (0x4U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONTROL_WTEF1001FMS_SHIFT (2U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONTROL_WTEF1001FMM_MASK (0x2U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONTROL_WTEF1001FMM_SHIFT (1U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONTROL_WUP_TIMER_EN_FOR_AN_MASK (0x1U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONTROL_WUP_TIMER_EN_FOR_AN_SHIFT (0U)




typedef uint16_t BRPHY1GV2_LINK_SYNC_WD_TIMER_VALUE_TYPE;
#define BRPHY1GV2_LINK_SYNC_WD_TIMER_VALUE_MASK (0xffffU)
#define BRPHY1GV2_LINK_SYNC_WD_TIMER_VALUE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_LINK_SYNC_CONTROL_D_TYPE;
#define BRPHY1GV2_LINK_SYNC_CONTROL_D_SPARE_15_MASK (0x8000U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_D_SPARE_15_SHIFT (15U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_D_LSMTFO_MASK (0x4000U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_D_LSMTFO_SHIFT (14U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_D_LSSTFO_MASK (0x2000U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_D_LSSTFO_SHIFT (13U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_D_LYNK_SYNC_SEND_I_FORCED_MASK (0x1000U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_D_LYNK_SYNC_SEND_I_FORCED_SHIFT (12U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_D_LSMBD_MASK (0xe00U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_D_LSMBD_SHIFT (9U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_D_LSSBD_MASK (0x1c0U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_D_LSSBD_SHIFT (6U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_D_LYNK_SYNC_ENABLE_HS_MASK (0x20U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_D_LYNK_SYNC_ENABLE_HS_SHIFT (5U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_D_LSEBN_MASK (0x1fU)
#define BRPHY1GV2_LINK_SYNC_CONTROL_D_LSEBN_SHIFT (0U)




typedef uint16_t BRPHY1GV2_LINK_SYNC_CONTROL_E_TYPE;
#define BRPHY1GV2_LINK_SYNC_CONTROL_E_PN_START_RANDOM_MASK (0x8000U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_E_PN_START_RANDOM_SHIFT (15U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_E_SPARE_14_10_MASK (0x7c00U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_E_SPARE_14_10_SHIFT (10U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_E_TX_FILTER_3G_ON_OVR_MASK (0x200U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_E_TX_FILTER_3G_ON_OVR_SHIFT (9U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_E_TX_FILTER_3G_ON_VAL_MASK (0x100U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_E_TX_FILTER_3G_ON_VAL_SHIFT (8U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_E_PN_START_VALUES_MASK (0xffU)
#define BRPHY1GV2_LINK_SYNC_CONTROL_E_PN_START_VALUES_SHIFT (0U)




typedef uint16_t BRPHY1GV2_LINK_SYNC_CONTROL_F_TYPE;
#define BRPHY1GV2_LINK_SYNC_CONTROL_F_WUP_DET_THRESHOLD_MASK (0xff00U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_F_WUP_DET_THRESHOLD_SHIFT (8U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_F_WUP_DET_TIMEOUT_MASK (0xf8U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_F_WUP_DET_TIMEOUT_SHIFT (3U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_F_WUP_DET_SHIFT_MASK (0x6U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_F_WUP_DET_SHIFT_SHIFT (1U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_F_WUP_DET_DISABLE_MASK (0x1U)
#define BRPHY1GV2_LINK_SYNC_CONTROL_F_WUP_DET_DISABLE_SHIFT (0U)




typedef uint16_t BRPHY1GV2_LINK_SYNC_MAEP1S_TYPE;
#define BRPHY1GV2_LINK_SYNC_MAEP1S_MF_ACCUM_E_STAT_PEAK1_MASK (0xfffU)
#define BRPHY1GV2_LINK_SYNC_MAEP1S_MF_ACCUM_E_STAT_PEAK1_SHIFT (0U)




typedef uint16_t BRPHY1GV2_LINK_SYNC_MAOP1S_TYPE;
#define BRPHY1GV2_LINK_SYNC_MAOP1S_MF_ACCUM_O_STAT_PEAK1_MASK (0xfffU)
#define BRPHY1GV2_LINK_SYNC_MAOP1S_MF_ACCUM_O_STAT_PEAK1_SHIFT (0U)




typedef uint16_t BRPHY1GV2_LINK_SYNC_MAEP2S_TYPE;
#define BRPHY1GV2_LINK_SYNC_MAEP2S_MF_ACCUM_E_STAT_PEAK2_MASK (0xfffU)
#define BRPHY1GV2_LINK_SYNC_MAEP2S_MF_ACCUM_E_STAT_PEAK2_SHIFT (0U)




typedef uint16_t BRPHY1GV2_LINK_SYNC_MAOP2S_TYPE;
#define BRPHY1GV2_LINK_SYNC_MAOP2S_MF_ACCUM_O_STAT_PEAK2_MASK (0xfffU)
#define BRPHY1GV2_LINK_SYNC_MAOP2S_MF_ACCUM_O_STAT_PEAK2_SHIFT (0U)




typedef uint16_t BRPHY1GV2_LINK_SYNC_MWEP2S_TYPE;
#define BRPHY1GV2_LINK_SYNC_MWEP2S_MF_WUP_E_STAT_PEAK2_MASK (0x1ffU)
#define BRPHY1GV2_LINK_SYNC_MWEP2S_MF_WUP_E_STAT_PEAK2_SHIFT (0U)




typedef uint16_t BRPHY1GV2_LINK_SYNC_MWOP2S_TYPE;
#define BRPHY1GV2_LINK_SYNC_MWOP2S_MF_WUP_O_STAT_PEAK2_MASK (0x1ffU)
#define BRPHY1GV2_LINK_SYNC_MWOP2S_MF_WUP_O_STAT_PEAK2_SHIFT (0U)




typedef uint16_t BRPHY1GV2_LINK_SYNC_WUP_CONT_2_TYPE;
#define BRPHY1GV2_LINK_SYNC_WUP_CONT_2_SPARE_15_6_MASK (0xffc0U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONT_2_SPARE_15_6_SHIFT (6U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONT_2_T10SLOE_MASK (0x20U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONT_2_T10SLOE_SHIFT (5U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONT_2_T10SLOV_MASK (0x10U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONT_2_T10SLOV_SHIFT (4U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONT_2_ESCOE_MASK (0x8U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONT_2_ESCOE_SHIFT (3U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONT_2_ESCOV_MASK (0x4U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONT_2_ESCOV_SHIFT (2U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONT_2_IIOE_MASK (0x2U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONT_2_IIOE_SHIFT (1U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONT_2_IIOV_MASK (0x1U)
#define BRPHY1GV2_LINK_SYNC_WUP_CONT_2_IIOV_SHIFT (0U)




typedef uint16_t BRPHY1GV2_LINK_SYNC_SPARE_TYPE;
#define BRPHY1GV2_LINK_SYNC_SPARE_REGISTER_MASK (0xffffU)
#define BRPHY1GV2_LINK_SYNC_SPARE_REGISTER_SHIFT (0U)




typedef volatile struct sBRPHY1GV2_LINK_SYNC_RDBType {
    BRPHY1GV2_LINK_SYNC_SIGDET_THRESHOLD_TYPE sigdet_threshold; /* OFFSET: 0x0 */
    BRPHY1GV2_LINK_SYNC_RESERVED_TYPE rsvd0[2]; /* OFFSET: 0x2 */
    BRPHY1GV2_LINK_SYNC_SIGDET_WINDOW_TYPE sigdet_window; /* OFFSET: 0x4 */
    BRPHY1GV2_LINK_SYNC_RESERVED_TYPE rsvd1[2]; /* OFFSET: 0x6 */
    BRPHY1GV2_LINK_SYNC_CONTROL_A_TYPE control_a; /* OFFSET: 0x8 */
    BRPHY1GV2_LINK_SYNC_RESERVED_TYPE rsvd2[2]; /* OFFSET: 0xa */
    BRPHY1GV2_LINK_SYNC_CONTROL_B_TYPE control_b; /* OFFSET: 0xc */
    BRPHY1GV2_LINK_SYNC_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0xe */
    BRPHY1GV2_LINK_SYNC_CONTROL_C_TYPE control_c; /* OFFSET: 0x10 */
    BRPHY1GV2_LINK_SYNC_RESERVED_TYPE rsvd4[2]; /* OFFSET: 0x12 */
    BRPHY1GV2_LINK_SYNC_STATUS_A_TYPE status_a; /* OFFSET: 0x14 */
    BRPHY1GV2_LINK_SYNC_RESERVED_TYPE rsvd5[2]; /* OFFSET: 0x16 */
    BRPHY1GV2_LINK_SYNC_STATUS_B_TYPE status_b; /* OFFSET: 0x18 */
    BRPHY1GV2_LINK_SYNC_RESERVED_TYPE rsvd6[2]; /* OFFSET: 0x1a */
    BRPHY1GV2_LINK_SYNC_WUP_CONTROL_TYPE wup_control; /* OFFSET: 0x1c */
    BRPHY1GV2_LINK_SYNC_RESERVED_TYPE rsvd7[2]; /* OFFSET: 0x1e */
    BRPHY1GV2_LINK_SYNC_WD_TIMER_VALUE_TYPE wd_timer_value; /* OFFSET: 0x20 */
    BRPHY1GV2_LINK_SYNC_RESERVED_TYPE rsvd8[2]; /* OFFSET: 0x22 */
    BRPHY1GV2_LINK_SYNC_CONTROL_D_TYPE control_d; /* OFFSET: 0x24 */
    BRPHY1GV2_LINK_SYNC_RESERVED_TYPE rsvd9[2]; /* OFFSET: 0x26 */
    BRPHY1GV2_LINK_SYNC_CONTROL_E_TYPE control_e; /* OFFSET: 0x28 */
    BRPHY1GV2_LINK_SYNC_RESERVED_TYPE rsvd10[2]; /* OFFSET: 0x2a */
    BRPHY1GV2_LINK_SYNC_CONTROL_F_TYPE control_f; /* OFFSET: 0x2c */
    BRPHY1GV2_LINK_SYNC_RESERVED_TYPE rsvd11[2]; /* OFFSET: 0x2e */
    BRPHY1GV2_LINK_SYNC_MAEP1S_TYPE mf_accum_e_peak1_stat; /* OFFSET: 0x30 */
    BRPHY1GV2_LINK_SYNC_RESERVED_TYPE rsvd12[2]; /* OFFSET: 0x32 */
    BRPHY1GV2_LINK_SYNC_MAOP1S_TYPE mf_accum_o_peak1_stat; /* OFFSET: 0x34 */
    BRPHY1GV2_LINK_SYNC_RESERVED_TYPE rsvd13[2]; /* OFFSET: 0x36 */
    BRPHY1GV2_LINK_SYNC_MAEP2S_TYPE mf_accum_e_peak2_stat; /* OFFSET: 0x38 */
    BRPHY1GV2_LINK_SYNC_RESERVED_TYPE rsvd14[2]; /* OFFSET: 0x3a */
    BRPHY1GV2_LINK_SYNC_MAOP2S_TYPE mf_accum_o_peak2_stat; /* OFFSET: 0x3c */
    BRPHY1GV2_LINK_SYNC_RESERVED_TYPE rsvd15[2]; /* OFFSET: 0x3e */
    BRPHY1GV2_LINK_SYNC_MWEP2S_TYPE mf_wup_e_peak2_stat; /* OFFSET: 0x40 */
    BRPHY1GV2_LINK_SYNC_RESERVED_TYPE rsvd16[2]; /* OFFSET: 0x42 */
    BRPHY1GV2_LINK_SYNC_MWOP2S_TYPE mf_wup_o_peak2_stat; /* OFFSET: 0x44 */
    BRPHY1GV2_LINK_SYNC_RESERVED_TYPE rsvd17[2]; /* OFFSET: 0x46 */
    BRPHY1GV2_LINK_SYNC_WUP_CONT_2_TYPE wup_control_2; /* OFFSET: 0x48 */
    BRPHY1GV2_LINK_SYNC_RESERVED_TYPE rsvd18[946]; /* OFFSET: 0x4a */
    BRPHY1GV2_LINK_SYNC_SPARE_TYPE spare_register; /* OFFSET: 0x3fc */
} BRPHY1GV2_LINK_SYNC_RDBType;


#define BRPHY0_1G_LINK_SYNC_BASE        (0xE0563C00UL)



#define BRPHY1GV2_LINK_SYNC_MAX_HW_ID   (1UL)


#define BRPHY1GV2_LINK_SYNC_CONST       (0x3000U)

#endif /* BRPHY1GV2_LINK_SYNC_RDB_H */
