/*****************************************************************************
 Copyright 2025 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file et_rdb.h
    @brief RDB File for ET

    @version BCM89580_A0_20230125_RDB
*/

#ifndef ET_RDB_H
#define ET_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t ET_S16UP_0_STYPE_TYPE;
#define ET_S16UP_0_STYPE_RX_SIGDET_MASK (0x1UL)
#define ET_S16UP_0_STYPE_RX_SIGDET_SHIFT (0UL)
#define ET_S16UP_0_STYPE_SGMII_MASK (0x2UL)
#define ET_S16UP_0_STYPE_SGMII_SHIFT (1UL)
#define ET_S16UP_0_STYPE_SPEED_10_MASK (0x4UL)
#define ET_S16UP_0_STYPE_SPEED_10_SHIFT (2UL)
#define ET_S16UP_0_STYPE_SPEED_100_MASK (0x8UL)
#define ET_S16UP_0_STYPE_SPEED_100_SHIFT (3UL)
#define ET_S16UP_0_STYPE_SPEED_1000_MASK (0x10UL)
#define ET_S16UP_0_STYPE_SPEED_1000_SHIFT (4UL)
#define ET_S16UP_0_STYPE_SPEED_2500R_MASK (0x20UL)
#define ET_S16UP_0_STYPE_SPEED_2500R_SHIFT (5UL)
#define ET_S16UP_0_STYPE_SPEED_2500X_XGMII_MASK (0x40UL)
#define ET_S16UP_0_STYPE_SPEED_2500X_XGMII_SHIFT (6UL)
#define ET_S16UP_0_STYPE_SPEED_2500X_GMII_MASK (0x80UL)
#define ET_S16UP_0_STYPE_SPEED_2500X_GMII_SHIFT (7UL)
#define ET_S16UP_0_STYPE_SYNC_STATUS_MASK (0x100UL)
#define ET_S16UP_0_STYPE_SYNC_STATUS_SHIFT (8UL)




typedef uint32_t ET_S16UP_0_CTYPE_TYPE;
#define ET_S16UP_0_CTYPE_EXT_FIBER_SIGNAL_DETECT_MASK (0x1UL)
#define ET_S16UP_0_CTYPE_EXT_FIBER_SIGNAL_DETECT_SHIFT (0UL)
#define ET_S16UP_0_CTYPE_LINESIDE_LINK_HW_MASK (0x2UL)
#define ET_S16UP_0_CTYPE_LINESIDE_LINK_HW_SHIFT (1UL)
#define ET_S16UP_0_CTYPE_PCS_SEL_MASK (0x4UL)
#define ET_S16UP_0_CTYPE_PCS_SEL_SHIFT (2UL)
#define ET_S16UP_0_CTYPE_PWRDWN_MASK (0x8UL)
#define ET_S16UP_0_CTYPE_PWRDWN_SHIFT (3UL)




typedef uint8_t ET_RESERVED_TYPE;




typedef uint32_t ET_BRPHY_0_STYPE_TYPE;
#define ET_BRPHY_0_STYPE_BRPHY_1PORT_LINK0_MASK (0x1UL)
#define ET_BRPHY_0_STYPE_BRPHY_1PORT_LINK0_SHIFT (0UL)
#define ET_BRPHY_0_STYPE_BRPHY_1PORT_SPD0_MASK (0x6UL)
#define ET_BRPHY_0_STYPE_BRPHY_1PORT_SPD0_SHIFT (1UL)
#define ET_BRPHY_0_STYPE_INTR_O_MASK (0x8UL)
#define ET_BRPHY_0_STYPE_INTR_O_SHIFT (3UL)
#define ET_BRPHY_0_STYPE_O_PLL_FREQ_LOCK_MASK (0x40UL)
#define ET_BRPHY_0_STYPE_O_PLL_FREQ_LOCK_SHIFT (6UL)
#define ET_BRPHY_0_STYPE_O_PLL_REF_EPWD_MASK (0x80UL)
#define ET_BRPHY_0_STYPE_O_PLL_REF_EPWD_SHIFT (7UL)
#define ET_BRPHY_0_STYPE_O_PLLRST_STARTUP_DONE_MASK (0x100UL)
#define ET_BRPHY_0_STYPE_O_PLLRST_STARTUP_DONE_SHIFT (8UL)
#define ET_BRPHY_0_STYPE_AFE_RCCAL_DONE_MASK (0x2000UL)
#define ET_BRPHY_0_STYPE_AFE_RCCAL_DONE_SHIFT (13UL)
#define ET_BRPHY_0_STYPE_AFE_RCCAL_CODE_MASK (0x7c000UL)
#define ET_BRPHY_0_STYPE_AFE_RCCAL_CODE_SHIFT (14UL)
#define ET_BRPHY_0_STYPE_ENERGY_DET_MASK (0x80000UL)
#define ET_BRPHY_0_STYPE_ENERGY_DET_SHIFT (19UL)




typedef uint32_t ET_BRPHY_1_STYPE_TYPE;
#define ET_BRPHY_1_STYPE_TC10_SLEEP_MODE_MASK (0x1UL)
#define ET_BRPHY_1_STYPE_TC10_SLEEP_MODE_SHIFT (0UL)
#define ET_BRPHY_1_STYPE_TC10_INTR_N_MASK (0x10UL)
#define ET_BRPHY_1_STYPE_TC10_INTR_N_SHIFT (4UL)
#define ET_BRPHY_1_STYPE_AFE_WAKE_VIA_WAKE_MASK (0x80000000UL)
#define ET_BRPHY_1_STYPE_AFE_WAKE_VIA_WAKE_SHIFT (31UL)




typedef uint32_t ET_BRPHY_0_CTYPE_TYPE;
#define ET_BRPHY_0_CTYPE_MODEL_NUM_LOW_MASK (0xffffffffUL)
#define ET_BRPHY_0_CTYPE_MODEL_NUM_LOW_SHIFT (0UL)




typedef uint32_t ET_BRPHY_1_CTYPE_TYPE;
#define ET_BRPHY_1_CTYPE_MODEL_NUM_HIGH_MASK (0x3fUL)
#define ET_BRPHY_1_CTYPE_MODEL_NUM_HIGH_SHIFT (0UL)
#define ET_BRPHY_1_CTYPE_PHYA_MASK (0xc0UL)
#define ET_BRPHY_1_CTYPE_PHYA_SHIFT (6UL)
#define ET_BRPHY_1_CTYPE_REV_NUM_MASK (0xf00UL)
#define ET_BRPHY_1_CTYPE_REV_NUM_SHIFT (8UL)




typedef uint32_t ET_BRPHY_2_CTYPE_TYPE;
#define ET_BRPHY_2_CTYPE_P1588_RX_EN_MASK (0x8UL)
#define ET_BRPHY_2_CTYPE_P1588_RX_EN_SHIFT (3UL)
#define ET_BRPHY_2_CTYPE_P1588_TX_EN_MASK (0x10UL)
#define ET_BRPHY_2_CTYPE_P1588_TX_EN_SHIFT (4UL)
#define ET_BRPHY_2_CTYPE_I_VTMON_PHY_PWRDN_MASK (0x20UL)
#define ET_BRPHY_2_CTYPE_I_VTMON_PHY_PWRDN_SHIFT (5UL)
#define ET_BRPHY_2_CTYPE_I_OTP_RCAL_MASK (0x7c0UL)
#define ET_BRPHY_2_CTYPE_I_OTP_RCAL_SHIFT (6UL)
#define ET_BRPHY_2_CTYPE_RING_OSC_SEL_MASK (0x8000UL)
#define ET_BRPHY_2_CTYPE_RING_OSC_SEL_SHIFT (15UL)
#define ET_BRPHY_2_CTYPE_RING_OSC_TESTMODE_MASK (0x10000UL)
#define ET_BRPHY_2_CTYPE_RING_OSC_TESTMODE_SHIFT (16UL)
#define ET_BRPHY_2_CTYPE_STARTUP_TESTMODE_MASK (0x20000UL)
#define ET_BRPHY_2_CTYPE_STARTUP_TESTMODE_SHIFT (17UL)
#define ET_BRPHY_2_CTYPE_SUPER_ISOLATE_DEF_MASK (0x40000UL)
#define ET_BRPHY_2_CTYPE_SUPER_ISOLATE_DEF_SHIFT (18UL)
#define ET_BRPHY_2_CTYPE_BR_1G_SPD_DEF_MASK (0x100000UL)
#define ET_BRPHY_2_CTYPE_BR_1G_SPD_DEF_SHIFT (20UL)
#define ET_BRPHY_2_CTYPE_BRPHY_1PORT_SOURCE_SYNC_MII_MASK (0x2000000UL)
#define ET_BRPHY_2_CTYPE_BRPHY_1PORT_SOURCE_SYNC_MII_SHIFT (25UL)




typedef uint32_t ET_BRPHY_3_CTYPE_TYPE;
#define ET_BRPHY_3_CTYPE_I_AFE_PD_CML_LCREFOUT_MASK (0x1UL)
#define ET_BRPHY_3_CTYPE_I_AFE_PD_CML_LCREFOUT_SHIFT (0UL)
#define ET_BRPHY_3_CTYPE_I_AFE_PD_CML_REFCLK_CHOUT_MASK (0x2UL)
#define ET_BRPHY_3_CTYPE_I_AFE_PD_CML_REFCLK_CHOUT_SHIFT (1UL)
#define ET_BRPHY_3_CTYPE_I_AFE_PLL_SEL_DIV5_MASK (0x4UL)
#define ET_BRPHY_3_CTYPE_I_AFE_PLL_SEL_DIV5_SHIFT (2UL)
#define ET_BRPHY_3_CTYPE_I_AFE_R_CAL_BYP_MASK (0x8UL)
#define ET_BRPHY_3_CTYPE_I_AFE_R_CAL_BYP_SHIFT (3UL)
#define ET_BRPHY_3_CTYPE_I_AFE_RC_CAL_BYP_MASK (0x10UL)
#define ET_BRPHY_3_CTYPE_I_AFE_RC_CAL_BYP_SHIFT (4UL)
#define ET_BRPHY_3_CTYPE_I_AFE_REF_CMOS_CLK_HZ_MASK (0x20UL)
#define ET_BRPHY_3_CTYPE_I_AFE_REF_CMOS_CLK_HZ_SHIFT (5UL)
#define ET_BRPHY_3_CTYPE_I_AFE_REFCLK_DIV2_MASK (0x40UL)
#define ET_BRPHY_3_CTYPE_I_AFE_REFCLK_DIV2_SHIFT (6UL)
#define ET_BRPHY_3_CTYPE_I_AFE_REFCLK_DIV4_MASK (0x80UL)
#define ET_BRPHY_3_CTYPE_I_AFE_REFCLK_DIV4_SHIFT (7UL)
#define ET_BRPHY_3_CTYPE_I_PLLRST_STARTUP_BYP_MASK (0x100UL)
#define ET_BRPHY_3_CTYPE_I_PLLRST_STARTUP_BYP_SHIFT (8UL)
#define ET_BRPHY_3_CTYPE_I_PLLRST_STARTUP_RSTB_MASK (0x200UL)
#define ET_BRPHY_3_CTYPE_I_PLLRST_STARTUP_RSTB_SHIFT (9UL)
#define ET_BRPHY_3_CTYPE_I_R_CAL_BYP_MASK (0x400UL)
#define ET_BRPHY_3_CTYPE_I_R_CAL_BYP_SHIFT (10UL)
#define ET_BRPHY_3_CTYPE_I_RC_CAL_BYP_MASK (0x800UL)
#define ET_BRPHY_3_CTYPE_I_RC_CAL_BYP_SHIFT (11UL)
#define ET_BRPHY_3_CTYPE_I_STRAP_XTAL_REFSEL_MASK (0x7000UL)
#define ET_BRPHY_3_CTYPE_I_STRAP_XTAL_REFSEL_SHIFT (12UL)
#define ET_BRPHY_3_CTYPE_SAFETY_PIN_N_PHY0_MASK (0x40000UL)
#define ET_BRPHY_3_CTYPE_SAFETY_PIN_N_PHY0_SHIFT (18UL)
#define ET_BRPHY_3_CTYPE_BRPHY_LINK_OVR_MASK (0x800000UL)
#define ET_BRPHY_3_CTYPE_BRPHY_LINK_OVR_SHIFT (23UL)
#define ET_BRPHY_3_CTYPE_BRPHY_LINK_OVR_VAL_MASK (0x1000000UL)
#define ET_BRPHY_3_CTYPE_BRPHY_LINK_OVR_VAL_SHIFT (24UL)
#define ET_BRPHY_3_CTYPE_BRPHY_TX_PAUSE_OVR_MASK (0x2000000UL)
#define ET_BRPHY_3_CTYPE_BRPHY_TX_PAUSE_OVR_SHIFT (25UL)
#define ET_BRPHY_3_CTYPE_BRPHY_TX_PAUSE_OVR_VAL_MASK (0x4000000UL)
#define ET_BRPHY_3_CTYPE_BRPHY_TX_PAUSE_OVR_VAL_SHIFT (26UL)
#define ET_BRPHY_3_CTYPE_BRPHY_RX_PAUSE_OVR_MASK (0x8000000UL)
#define ET_BRPHY_3_CTYPE_BRPHY_RX_PAUSE_OVR_SHIFT (27UL)
#define ET_BRPHY_3_CTYPE_BRPHY_RX_PAUSE_OVR_VAL_MASK (0x10000000UL)
#define ET_BRPHY_3_CTYPE_BRPHY_RX_PAUSE_OVR_VAL_SHIFT (28UL)




typedef uint32_t ET_BRPHY_4_CTYPE_TYPE;
#define ET_BRPHY_4_CTYPE_SWTCH_WAKE_VIA_WAKE_MASK (0x2UL)
#define ET_BRPHY_4_CTYPE_SWTCH_WAKE_VIA_WAKE_SHIFT (1UL)
#define ET_BRPHY_4_CTYPE_TC10_CTRL_DEF_MASK (0x60UL)
#define ET_BRPHY_4_CTYPE_TC10_CTRL_DEF_SHIFT (5UL)
#define ET_BRPHY_4_CTYPE_TC10_DIG_DIS_MASK (0x80UL)
#define ET_BRPHY_4_CTYPE_TC10_DIG_DIS_SHIFT (7UL)
#define ET_BRPHY_4_CTYPE_BR_AUTO_NEG_EN_STRAP_DEF_MASK (0x100UL)
#define ET_BRPHY_4_CTYPE_BR_AUTO_NEG_EN_STRAP_DEF_SHIFT (8UL)
#define ET_BRPHY_4_CTYPE_BR_MS_DEF_MASK (0x200UL)
#define ET_BRPHY_4_CTYPE_BR_MS_DEF_SHIFT (9UL)
#define ET_BRPHY_4_CTYPE_AFE_WAKE_VIA_WAKE_MASK (0x80000000UL)
#define ET_BRPHY_4_CTYPE_AFE_WAKE_VIA_WAKE_SHIFT (31UL)




typedef uint32_t ET_XGMAC_2_STYPE_TYPE;
#define ET_XGMAC_2_STYPE_SBD_RST_IN_PRGS_O_MASK (0x1UL)
#define ET_XGMAC_2_STYPE_SBD_RST_IN_PRGS_O_SHIFT (0UL)
#define ET_XGMAC_2_STYPE_MCGR_DMA_REQ_O_MASK (0x2UL)
#define ET_XGMAC_2_STYPE_MCGR_DMA_REQ_O_SHIFT (1UL)
#define ET_XGMAC_2_STYPE_SBD_AR_DMA_CH_NO_O_MASK (0x3cUL)
#define ET_XGMAC_2_STYPE_SBD_AR_DMA_CH_NO_O_SHIFT (2UL)
#define ET_XGMAC_2_STYPE_SBD_AW_DMA_CH_NO_O_MASK (0x1c0UL)
#define ET_XGMAC_2_STYPE_SBD_AW_DMA_CH_NO_O_SHIFT (6UL)
#define ET_XGMAC_2_STYPE_RST_CLK_APP_N_O_MASK (0x200UL)
#define ET_XGMAC_2_STYPE_RST_CLK_APP_N_O_SHIFT (9UL)
#define ET_XGMAC_2_STYPE_SBD_W_DMA_CH_NO_O_MASK (0x1c00UL)
#define ET_XGMAC_2_STYPE_SBD_W_DMA_CH_NO_O_SHIFT (10UL)
#define ET_XGMAC_2_STYPE_CSYSACK_O_MASK (0x2000UL)
#define ET_XGMAC_2_STYPE_CSYSACK_O_SHIFT (13UL)
#define ET_XGMAC_2_STYPE_CACTIVE_O_MASK (0x4000UL)
#define ET_XGMAC_2_STYPE_CACTIVE_O_SHIFT (14UL)
#define ET_XGMAC_2_STYPE_AWQOS_M_O_MASK (0x78000UL)
#define ET_XGMAC_2_STYPE_AWQOS_M_O_SHIFT (15UL)
#define ET_XGMAC_2_STYPE_AWDOMAIN_M_O_MASK (0x180000UL)
#define ET_XGMAC_2_STYPE_AWDOMAIN_M_O_SHIFT (19UL)
#define ET_XGMAC_2_STYPE_MTI_DISABLE_PRIORITY_O_MASK (0x1fe00000UL)
#define ET_XGMAC_2_STYPE_MTI_DISABLE_PRIORITY_O_SHIFT (21UL)
#define ET_XGMAC_2_STYPE_MTI_TX_PAUSE_O_MASK (0x20000000UL)
#define ET_XGMAC_2_STYPE_MTI_TX_PAUSE_O_SHIFT (29UL)
#define ET_XGMAC_2_STYPE_RST_CLK_TX_312PT5_N_O_MASK (0x40000000UL)
#define ET_XGMAC_2_STYPE_RST_CLK_TX_312PT5_N_O_SHIFT (30UL)
#define ET_XGMAC_2_STYPE_RST_CLK_RX_312PT5_N_O_MASK (0x80000000UL)
#define ET_XGMAC_2_STYPE_RST_CLK_RX_312PT5_N_O_SHIFT (31UL)




typedef uint32_t ET_XGMAC_3_STYPE_TYPE;
#define ET_XGMAC_3_STYPE_LOOPBACK_MODE_O_MASK (0x10UL)
#define ET_XGMAC_3_STYPE_LOOPBACK_MODE_O_SHIFT (4UL)
#define ET_XGMAC_3_STYPE_LPI_INTR_O_MASK (0x20UL)
#define ET_XGMAC_3_STYPE_LPI_INTR_O_SHIFT (5UL)
#define ET_XGMAC_3_STYPE_PMT_INTR_O_MASK (0x40UL)
#define ET_XGMAC_3_STYPE_PMT_INTR_O_SHIFT (6UL)
#define ET_XGMAC_3_STYPE_SBD_INTR_O_MASK (0x80UL)
#define ET_XGMAC_3_STYPE_SBD_INTR_O_SHIFT (7UL)
#define ET_XGMAC_3_STYPE_SBD_PWR_DOWN_ACK_O_MASK (0x100UL)
#define ET_XGMAC_3_STYPE_SBD_PWR_DOWN_ACK_O_SHIFT (8UL)
#define ET_XGMAC_3_STYPE_SBD_TX_CLK_GATING_CTRL_O_MASK (0x200UL)
#define ET_XGMAC_3_STYPE_SBD_TX_CLK_GATING_CTRL_O_SHIFT (9UL)
#define ET_XGMAC_3_STYPE_TRC_RD_EN_O_MASK (0x400UL)
#define ET_XGMAC_3_STYPE_TRC_RD_EN_O_SHIFT (10UL)
#define ET_XGMAC_3_STYPE_MAC_SPEED_O_MASK (0x3800UL)
#define ET_XGMAC_3_STYPE_MAC_SPEED_O_SHIFT (11UL)
#define ET_XGMAC_3_STYPE_RRC_RD_EN_O_MASK (0x4000UL)
#define ET_XGMAC_3_STYPE_RRC_RD_EN_O_SHIFT (14UL)
#define ET_XGMAC_3_STYPE_WDATA_M_SE_O_MASK (0x8000UL)
#define ET_XGMAC_3_STYPE_WDATA_M_SE_O_SHIFT (15UL)




typedef uint32_t ET_XGMAC_4_STYPE_TYPE;
#define ET_XGMAC_4_STYPE_SBD_PERCH_TX_INTR_O_MASK (0xffUL)
#define ET_XGMAC_4_STYPE_SBD_PERCH_TX_INTR_O_SHIFT (0UL)
#define ET_XGMAC_4_STYPE_SBD_PERCH_RX_INTR_O_MASK (0x300UL)
#define ET_XGMAC_4_STYPE_SBD_PERCH_RX_INTR_O_SHIFT (8UL)




typedef uint32_t ET_XGMAC_MEM_STATUS_STYPE_TYPE;
#define ET_XGMAC_MEM_STATUS_STYPE_DR_MEM_INIT_DONE_MASK (0x1UL)
#define ET_XGMAC_MEM_STATUS_STYPE_DR_MEM_INIT_DONE_SHIFT (0UL)
#define ET_XGMAC_MEM_STATUS_STYPE_TX_MEM_INIT_DONE_MASK (0x2UL)
#define ET_XGMAC_MEM_STATUS_STYPE_TX_MEM_INIT_DONE_SHIFT (1UL)
#define ET_XGMAC_MEM_STATUS_STYPE_RX_MEM_INIT_DONE_MASK (0x4UL)
#define ET_XGMAC_MEM_STATUS_STYPE_RX_MEM_INIT_DONE_SHIFT (2UL)
#define ET_XGMAC_MEM_STATUS_STYPE_DR_MEM_INIT_ERROR_MASK (0x8UL)
#define ET_XGMAC_MEM_STATUS_STYPE_DR_MEM_INIT_ERROR_SHIFT (3UL)
#define ET_XGMAC_MEM_STATUS_STYPE_TX_MEM_INIT_ERROR_MASK (0x10UL)
#define ET_XGMAC_MEM_STATUS_STYPE_TX_MEM_INIT_ERROR_SHIFT (4UL)
#define ET_XGMAC_MEM_STATUS_STYPE_RX_MEM_INIT_ERROR_MASK (0x20UL)
#define ET_XGMAC_MEM_STATUS_STYPE_RX_MEM_INIT_ERROR_SHIFT (5UL)




typedef uint32_t ET_XGMAC_2_CTYPE_TYPE;
#define ET_XGMAC_2_CTYPE_PWR_CLAMP_CTRL_I_MASK (0x2UL)
#define ET_XGMAC_2_CTYPE_PWR_CLAMP_CTRL_I_SHIFT (1UL)
#define ET_XGMAC_2_CTYPE_PWR_DOWN_CTRL_I_MASK (0x4UL)
#define ET_XGMAC_2_CTYPE_PWR_DOWN_CTRL_I_SHIFT (2UL)
#define ET_XGMAC_2_CTYPE_PWR_ISOLATE_I_MASK (0x8UL)
#define ET_XGMAC_2_CTYPE_PWR_ISOLATE_I_SHIFT (3UL)
#define ET_XGMAC_2_CTYPE_MCGR_DMA_ACK_I_MASK (0x10UL)
#define ET_XGMAC_2_CTYPE_MCGR_DMA_ACK_I_SHIFT (4UL)




typedef uint32_t ET_XGMAC_MEM_CNTRL_CTYPE_TYPE;
#define ET_XGMAC_MEM_CNTRL_CTYPE_DR_MEM_RESETB_OVERRIDE_MASK (0x1UL)
#define ET_XGMAC_MEM_CNTRL_CTYPE_DR_MEM_RESETB_OVERRIDE_SHIFT (0UL)
#define ET_XGMAC_MEM_CNTRL_CTYPE_TX_MEM_RESETB_OVERRIDE_MASK (0x2UL)
#define ET_XGMAC_MEM_CNTRL_CTYPE_TX_MEM_RESETB_OVERRIDE_SHIFT (1UL)
#define ET_XGMAC_MEM_CNTRL_CTYPE_RX_MEM_RESETB_OVERRIDE_MASK (0x4UL)
#define ET_XGMAC_MEM_CNTRL_CTYPE_RX_MEM_RESETB_OVERRIDE_SHIFT (2UL)




typedef uint32_t ET_XGMAC_DR_MEM_CTYPE_TYPE;
#define ET_XGMAC_DR_MEM_CTYPE_TM_MASK (0xffffUL)
#define ET_XGMAC_DR_MEM_CTYPE_TM_SHIFT (0UL)




typedef uint32_t ET_XGMAC_TX_MEM_CTYPE_TYPE;
#define ET_XGMAC_TX_MEM_CTYPE_TM_MASK (0xffffUL)
#define ET_XGMAC_TX_MEM_CTYPE_TM_SHIFT (0UL)




typedef uint32_t ET_XGMAC_RX_MEM_CTYPE_TYPE;
#define ET_XGMAC_RX_MEM_CTYPE_TM_MASK (0xffffUL)
#define ET_XGMAC_RX_MEM_CTYPE_TM_SHIFT (0UL)




typedef uint32_t ET_MSPU_1_STYPE_TYPE;
#define ET_MSPU_1_STYPE_PKT_IN_FLIGHT_EG_MASK (0x40000UL)
#define ET_MSPU_1_STYPE_PKT_IN_FLIGHT_EG_SHIFT (18UL)
#define ET_MSPU_1_STYPE_PKT_IN_FLIGHT_IG_MASK (0x80000UL)
#define ET_MSPU_1_STYPE_PKT_IN_FLIGHT_IG_SHIFT (19UL)




typedef uint32_t ET_MSPU_0_CTYPE_TYPE;
#define ET_MSPU_0_CTYPE_IROSC_EN_MASK (0x2UL)
#define ET_MSPU_0_CTYPE_IROSC_EN_SHIFT (1UL)
#define ET_MSPU_0_CTYPE_IROSC_SEL_MASK (0x4UL)
#define ET_MSPU_0_CTYPE_IROSC_SEL_SHIFT (2UL)
#define ET_MSPU_0_CTYPE_MSPU_INBOUND_SEL_MASK (0x8UL)
#define ET_MSPU_0_CTYPE_MSPU_INBOUND_SEL_SHIFT (3UL)
#define ET_MSPU_0_CTYPE_MSPU_LNMAC_COL_MASK (0x10UL)
#define ET_MSPU_0_CTYPE_MSPU_LNMAC_COL_SHIFT (4UL)
#define ET_MSPU_0_CTYPE_MSPU_LNMAC_CRS_MASK (0x20UL)
#define ET_MSPU_0_CTYPE_MSPU_LNMAC_CRS_SHIFT (5UL)
#define ET_MSPU_0_CTYPE_MSPU_LNMAC_SERDES_FULLD_MASK (0x40UL)
#define ET_MSPU_0_CTYPE_MSPU_LNMAC_SERDES_FULLD_SHIFT (6UL)
#define ET_MSPU_0_CTYPE_MSPU_LNMAC_SERDES_SPEED_10_MASK (0x400UL)
#define ET_MSPU_0_CTYPE_MSPU_LNMAC_SERDES_SPEED_10_SHIFT (10UL)
#define ET_MSPU_0_CTYPE_MSPU_LNMAC_SERDES_SPEED_100_MASK (0x800UL)
#define ET_MSPU_0_CTYPE_MSPU_LNMAC_SERDES_SPEED_100_SHIFT (11UL)
#define ET_MSPU_0_CTYPE_MSPU_LNMAC_SERDES_SPEED_1000_MASK (0x1000UL)
#define ET_MSPU_0_CTYPE_MSPU_LNMAC_SERDES_SPEED_1000_SHIFT (12UL)
#define ET_MSPU_0_CTYPE_MSPU_LNMAC_SERDES_SPEED_2500_MASK (0x2000UL)
#define ET_MSPU_0_CTYPE_MSPU_LNMAC_SERDES_SPEED_2500_SHIFT (13UL)
#define ET_MSPU_0_CTYPE_MSPU_OUTBOUND_SEL_MASK (0x4000UL)
#define ET_MSPU_0_CTYPE_MSPU_OUTBOUND_SEL_SHIFT (14UL)
#define ET_MSPU_0_CTYPE_MSPU_STANDALONE_TESTMODE_ESEC_MASK (0x80000UL)
#define ET_MSPU_0_CTYPE_MSPU_STANDALONE_TESTMODE_ESEC_SHIFT (19UL)
#define ET_MSPU_0_CTYPE_MSPU_STANDALONE_TESTMODE_ISEC_MASK (0x100000UL)
#define ET_MSPU_0_CTYPE_MSPU_STANDALONE_TESTMODE_ISEC_SHIFT (20UL)
#define ET_MSPU_0_CTYPE_MSPU_SWMAC_COL_MASK (0x200000UL)
#define ET_MSPU_0_CTYPE_MSPU_SWMAC_COL_SHIFT (21UL)
#define ET_MSPU_0_CTYPE_MSPU_SWMAC_CRS_MASK (0x400000UL)
#define ET_MSPU_0_CTYPE_MSPU_SWMAC_CRS_SHIFT (22UL)
#define ET_MSPU_0_CTYPE_MSPU_SWMAC_SERDES_FULLD_MASK (0x800000UL)
#define ET_MSPU_0_CTYPE_MSPU_SWMAC_SERDES_FULLD_SHIFT (23UL)
#define ET_MSPU_0_CTYPE_MSPU_SWMAC_SERDES_LINK_STAT_MASK (0x1000000UL)
#define ET_MSPU_0_CTYPE_MSPU_SWMAC_SERDES_LINK_STAT_SHIFT (24UL)
#define ET_MSPU_0_CTYPE_MSPU_SWMAC_SERDES_PAUSE_RX_MASK (0x2000000UL)
#define ET_MSPU_0_CTYPE_MSPU_SWMAC_SERDES_PAUSE_RX_SHIFT (25UL)
#define ET_MSPU_0_CTYPE_MSPU_SWMAC_SERDES_PAUSE_TX_MASK (0x4000000UL)
#define ET_MSPU_0_CTYPE_MSPU_SWMAC_SERDES_PAUSE_TX_SHIFT (26UL)
#define ET_MSPU_0_CTYPE_MSPU_SWMAC_SERDES_SPEED_10_MASK (0x8000000UL)
#define ET_MSPU_0_CTYPE_MSPU_SWMAC_SERDES_SPEED_10_SHIFT (27UL)
#define ET_MSPU_0_CTYPE_MSPU_SWMAC_SERDES_SPEED_100_MASK (0x10000000UL)
#define ET_MSPU_0_CTYPE_MSPU_SWMAC_SERDES_SPEED_100_SHIFT (28UL)
#define ET_MSPU_0_CTYPE_MSPU_SWMAC_SERDES_SPEED_1000_MASK (0x20000000UL)
#define ET_MSPU_0_CTYPE_MSPU_SWMAC_SERDES_SPEED_1000_SHIFT (29UL)
#define ET_MSPU_0_CTYPE_MSPU_SWMAC_SERDES_SPEED_2500_MASK (0x40000000UL)
#define ET_MSPU_0_CTYPE_MSPU_SWMAC_SERDES_SPEED_2500_SHIFT (30UL)




typedef uint32_t ET_TOP_0_CTYPE_TYPE;
#define ET_TOP_0_CTYPE_ETH_XGMAC_EN_MASK (0x1UL)
#define ET_TOP_0_CTYPE_ETH_XGMAC_EN_SHIFT (0UL)
#define ET_TOP_0_CTYPE_ETH_BRPHY_POR_EN_MASK (0x2UL)
#define ET_TOP_0_CTYPE_ETH_BRPHY_POR_EN_SHIFT (1UL)
#define ET_TOP_0_CTYPE_ETH_BRPHY__EN_MASK (0x4UL)
#define ET_TOP_0_CTYPE_ETH_BRPHY__EN_SHIFT (2UL)
#define ET_TOP_0_CTYPE_ETH_MSPU_EN_MASK (0x8UL)
#define ET_TOP_0_CTYPE_ETH_MSPU_EN_SHIFT (3UL)
#define ET_TOP_0_CTYPE_ETH_S16U_HW_EN_MASK (0x10UL)
#define ET_TOP_0_CTYPE_ETH_S16U_HW_EN_SHIFT (4UL)
#define ET_TOP_0_CTYPE_ETH_S16U_MDIOREGS_EN_MASK (0x20UL)
#define ET_TOP_0_CTYPE_ETH_S16U_MDIOREGS_EN_SHIFT (5UL)




typedef volatile struct sET_RDBType {
    ET_S16UP_0_STYPE_TYPE s16up_s0_reg; /* OFFSET: 0x0 */
    ET_S16UP_0_CTYPE_TYPE s16up_c0_reg; /* OFFSET: 0x4 */
    ET_RESERVED_TYPE rsvd0[8]; /* OFFSET: 0x8 */
    ET_BRPHY_0_STYPE_TYPE brphy_s0_reg; /* OFFSET: 0x10 */
    ET_BRPHY_1_STYPE_TYPE brphy_s1_reg; /* OFFSET: 0x14 */
    ET_BRPHY_0_CTYPE_TYPE brphy_c0_reg; /* OFFSET: 0x18 */
    ET_BRPHY_1_CTYPE_TYPE brphy_c1_reg; /* OFFSET: 0x1c */
    ET_BRPHY_2_CTYPE_TYPE brphy_c2_reg; /* OFFSET: 0x20 */
    ET_BRPHY_3_CTYPE_TYPE brphy_c3_reg; /* OFFSET: 0x24 */
    ET_BRPHY_4_CTYPE_TYPE brphy_c4_reg; /* OFFSET: 0x28 */
    ET_RESERVED_TYPE rsvd1[12]; /* OFFSET: 0x2c */
    ET_XGMAC_2_STYPE_TYPE xgmac_s2_reg; /* OFFSET: 0x38 */
    ET_XGMAC_3_STYPE_TYPE xgmac_s3_reg; /* OFFSET: 0x3c */
    ET_XGMAC_4_STYPE_TYPE xgmac_s4_reg; /* OFFSET: 0x40 */
    ET_XGMAC_MEM_STATUS_STYPE_TYPE xgmac_mem_status_reg; /* OFFSET: 0x44 */
    ET_RESERVED_TYPE rsvd2[16]; /* OFFSET: 0x48 */
    ET_XGMAC_2_CTYPE_TYPE xgmac_c2_reg; /* OFFSET: 0x58 */
    ET_XGMAC_MEM_CNTRL_CTYPE_TYPE xgmac_mem_cntrl_reg; /* OFFSET: 0x5c */
    ET_XGMAC_DR_MEM_CTYPE_TYPE xgmac_mem_dr_mem_reg; /* OFFSET: 0x60 */
    ET_XGMAC_TX_MEM_CTYPE_TYPE xgmac_mem_tx_mem_reg; /* OFFSET: 0x64 */
    ET_XGMAC_RX_MEM_CTYPE_TYPE xgmac_mem_rx_mem_reg; /* OFFSET: 0x68 */
    ET_RESERVED_TYPE rsvd3[8]; /* OFFSET: 0x6c */
    ET_MSPU_1_STYPE_TYPE mspu_s1_reg; /* OFFSET: 0x74 */
    ET_MSPU_0_CTYPE_TYPE mspu_c0_reg; /* OFFSET: 0x78 */
    ET_RESERVED_TYPE rsvd4[4]; /* OFFSET: 0x7c */
    ET_TOP_0_CTYPE_TYPE top_c0_reg; /* OFFSET: 0x80 */
} ET_RDBType;


#define ET_BASE                         ((uintptr_t)(0xE02DC000UL))



#define ET_MAX_HW_ID                    (1UL)

#endif /* ET_RDB_H */
