/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file hsio_eth_intr_ctrl_rdb.h
    @brief RDB File for HSIO_ETH_INTR_CTRL

    @version BCM89580_A0_20230125_RDB
*/

#ifndef HSIO_ETH_INTR_CTRL_RDB_H
#define HSIO_ETH_INTR_CTRL_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t HSIO_ETH_INTR_CTRL_RESERVED_TYPE;




typedef uint32_t HSIO_ETH_INTR_CTRL_HENFIE_TYPE;
#define HSIO_ETH_INTR_CTRL_HENFIE_P_INTR_AXIM_FAULT_MASK (0x4UL)
#define HSIO_ETH_INTR_CTRL_HENFIE_P_INTR_AXIM_FAULT_SHIFT (2UL)
#define HSIO_ETH_INTR_CTRL_HENFIE_P_AXIM_TIMEOUT_FAULT_MASK (0x2UL)
#define HSIO_ETH_INTR_CTRL_HENFIE_P_AXIM_TIMEOUT_FAULT_SHIFT (1UL)
#define HSIO_ETH_INTR_CTRL_HENFIE_P_AXIM_NO_PENDINGTRANS_MASK (0x1UL)
#define HSIO_ETH_INTR_CTRL_HENFIE_P_AXIM_NO_PENDINGTRANS_SHIFT (0UL)




typedef uint32_t HSIO_ETH_INTR_CTRL_HENFIE1_TYPE;
#define HSIO_ETH_INTR_CTRL_HENFIE1_INTR_AXIM_FAULT_W2CLR_MASK (0x4UL)
#define HSIO_ETH_INTR_CTRL_HENFIE1_INTR_AXIM_FAULT_W2CLR_SHIFT (2UL)
#define HSIO_ETH_INTR_CTRL_HENFIE1_AXIM_TIMEOUT_FAULT_W2CLR_MASK (0x2UL)
#define HSIO_ETH_INTR_CTRL_HENFIE1_AXIM_TIMEOUT_FAULT_W2CLR_SHIFT (1UL)
#define HSIO_ETH_INTR_CTRL_HENFIE1_AXIM_NO_PENDINGTRANS_W2CLR_MASK (0x1UL)
#define HSIO_ETH_INTR_CTRL_HENFIE1_AXIM_NO_PENDINGTRANS_W2CLR_SHIFT (0UL)




typedef uint32_t HSIO_ETH_INTR_CTRL_HENFIE2_TYPE;
#define HSIO_ETH_INTR_CTRL_HENFIE2_ENABLE_ETH_INTR_AXIM_FAULT_MASK (0x4UL)
#define HSIO_ETH_INTR_CTRL_HENFIE2_ENABLE_ETH_INTR_AXIM_FAULT_SHIFT (2UL)
#define HSIO_ETH_INTR_CTRL_HENFIE2_ENABLE_ETH_AXIM_TIMEOUT_FAULT_MASK (0x2UL)
#define HSIO_ETH_INTR_CTRL_HENFIE2_ENABLE_ETH_AXIM_TIMEOUT_FAULT_SHIFT (1UL)
#define HSIO_ETH_INTR_CTRL_HENFIE2_EEANP_MASK (0x1UL)
#define HSIO_ETH_INTR_CTRL_HENFIE2_EEANP_SHIFT (0UL)




typedef uint32_t HSIO_ETH_INTR_CTRL_SPARE_END_REG_TYPE;
#define HSIO_ETH_INTR_CTRL_SPARE_END_REG_MASK (0xffffffffUL)
#define HSIO_ETH_INTR_CTRL_SPARE_END_REG_SHIFT (0UL)




typedef volatile struct sHSIO_ETH_INTR_CTRL_RDBType {
    HSIO_ETH_INTR_CTRL_RESERVED_TYPE rsvd0[2048]; /* OFFSET: 0x0 */
    HSIO_ETH_INTR_CTRL_HENFIE_TYPE hsio_eth_noc_fault_intr_eipr; /* OFFSET: 0x800 */
    HSIO_ETH_INTR_CTRL_HENFIE1_TYPE hsio_eth_noc_fault_intr_eisr; /* OFFSET: 0x804 */
    HSIO_ETH_INTR_CTRL_HENFIE2_TYPE hsio_eth_noc_fault_intr_eier; /* OFFSET: 0x808 */
    HSIO_ETH_INTR_CTRL_RESERVED_TYPE rsvd1[48]; /* OFFSET: 0x80c */
    HSIO_ETH_INTR_CTRL_SPARE_END_REG_TYPE spare_end_reg; /* OFFSET: 0x83c */
} HSIO_ETH_INTR_CTRL_RDBType;


#define ETH_INTR_BASE                   (0xE02DC000UL)



#define HSIO_ETH_INTR_CTRL_MAX_HW_ID    (1UL)

#endif /* HSIO_ETH_INTR_CTRL_RDB_H */
