/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file s16up_tx2ln_pcs_rdb.h
    @brief RDB File for S16UP_TX2LN_PCS

    @version BCM89580_A0_20230125_RDB
*/

#ifndef S16UP_TX2LN_PCS_RDB_H
#define S16UP_TX2LN_PCS_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t S16UP_TX2LN_PCS_RESERVED_TYPE;




typedef uint16_t S16UP_TX2LN_PCS_FX100_TXCONTROL1_TYPE;
#define S16UP_TX2LN_PCS_FX100_TXCONTROL1_BYPASS_NRZ_MASK (0x10U)
#define S16UP_TX2LN_PCS_FX100_TXCONTROL1_BYPASS_NRZ_SHIFT (4U)
#define S16UP_TX2LN_PCS_FX100_TXCONTROL1_BYPASS_ENCODER_MASK (0x8U)
#define S16UP_TX2LN_PCS_FX100_TXCONTROL1_BYPASS_ENCODER_SHIFT (3U)
#define S16UP_TX2LN_PCS_FX100_TXCONTROL1_FAR_END_FAULT_EN_MASK (0x4U)
#define S16UP_TX2LN_PCS_FX100_TXCONTROL1_FAR_END_FAULT_EN_SHIFT (2U)
#define S16UP_TX2LN_PCS_FX100_TXCONTROL1_FORCE_LINK_MASK (0x2U)
#define S16UP_TX2LN_PCS_FX100_TXCONTROL1_FORCE_LINK_SHIFT (1U)
#define S16UP_TX2LN_PCS_FX100_TXCONTROL1_FAST_TIMERS_MASK (0x1U)
#define S16UP_TX2LN_PCS_FX100_TXCONTROL1_FAST_TIMERS_SHIFT (0U)




typedef uint16_t S16UP_TX2LN_PCS_T_MAC_SEQ_TSTMUX_STATUS_TYPE;
#define S16UP_TX2LN_PCS_T_MAC_SEQ_TSTMUX_STATUS_MASK (0xffffU)
#define S16UP_TX2LN_PCS_T_MAC_SEQ_TSTMUX_STATUS_SHIFT (0U)




typedef uint16_t S16UP_TX2LN_PCS_TMFSC1_TYPE;
#define S16UP_TX2LN_PCS_TMFSC1_FORCE_SEQUENCE_TX_DATA_BYTE1_MASK (0xff00U)
#define S16UP_TX2LN_PCS_TMFSC1_FORCE_SEQUENCE_TX_DATA_BYTE1_SHIFT (8U)
#define S16UP_TX2LN_PCS_TMFSC1_FORCE_SEQUENCE_TX_DATA_BYTE0_MASK (0xffU)
#define S16UP_TX2LN_PCS_TMFSC1_FORCE_SEQUENCE_TX_DATA_BYTE0_SHIFT (0U)




typedef uint16_t S16UP_TX2LN_PCS_TMFSC2_TYPE;
#define S16UP_TX2LN_PCS_TMFSC2_FORCE_SEQUENCE_TX_DATA_BYTE3_MASK (0xff00U)
#define S16UP_TX2LN_PCS_TMFSC2_FORCE_SEQUENCE_TX_DATA_BYTE3_SHIFT (8U)
#define S16UP_TX2LN_PCS_TMFSC2_FORCE_SEQUENCE_TX_DATA_BYTE2_MASK (0xffU)
#define S16UP_TX2LN_PCS_TMFSC2_FORCE_SEQUENCE_TX_DATA_BYTE2_SHIFT (0U)




typedef uint16_t S16UP_TX2LN_PCS_TMIC1_TYPE;
#define S16UP_TX2LN_PCS_TMIC1_FORCE_SEQUENCE_TX_DATA_C0_MASK (0x8000U)
#define S16UP_TX2LN_PCS_TMIC1_FORCE_SEQUENCE_TX_DATA_C0_SHIFT (15U)
#define S16UP_TX2LN_PCS_TMIC1_FORCE_SEQUENCE_TX_DATA_C1_MASK (0x4000U)
#define S16UP_TX2LN_PCS_TMIC1_FORCE_SEQUENCE_TX_DATA_C1_SHIFT (14U)
#define S16UP_TX2LN_PCS_TMIC1_FORCE_SEQUENCE_TX_DATA_C2_MASK (0x2000U)
#define S16UP_TX2LN_PCS_TMIC1_FORCE_SEQUENCE_TX_DATA_C2_SHIFT (13U)
#define S16UP_TX2LN_PCS_TMIC1_FORCE_SEQUENCE_TX_DATA_C3_MASK (0x1000U)
#define S16UP_TX2LN_PCS_TMIC1_FORCE_SEQUENCE_TX_DATA_C3_SHIFT (12U)
#define S16UP_TX2LN_PCS_TMIC1_FORCE_SEQUENCE_TX_MASK (0xf00U)
#define S16UP_TX2LN_PCS_TMIC1_FORCE_SEQUENCE_TX_SHIFT (8U)
#define S16UP_TX2LN_PCS_TMIC1_FORCE_SEQUENCE_TX_ENABLE_MASK (0x80U)
#define S16UP_TX2LN_PCS_TMIC1_FORCE_SEQUENCE_TX_ENABLE_SHIFT (7U)
#define S16UP_TX2LN_PCS_TMIC1_FILTER_EN_CL49_MASK (0x40U)
#define S16UP_TX2LN_PCS_TMIC1_FILTER_EN_CL49_SHIFT (6U)
#define S16UP_TX2LN_PCS_TMIC1_FILTER_LPI_EN_MASK (0x20U)
#define S16UP_TX2LN_PCS_TMIC1_FILTER_LPI_EN_SHIFT (5U)
#define S16UP_TX2LN_PCS_TMIC1_FILTER_BL_EN_MASK (0x10U)
#define S16UP_TX2LN_PCS_TMIC1_FILTER_BL_EN_SHIFT (4U)
#define S16UP_TX2LN_PCS_TMIC1_FILTER_LF_EN_MASK (0x8U)
#define S16UP_TX2LN_PCS_TMIC1_FILTER_LF_EN_SHIFT (3U)
#define S16UP_TX2LN_PCS_TMIC1_FILTER_RF_EN_MASK (0x4U)
#define S16UP_TX2LN_PCS_TMIC1_FILTER_RF_EN_SHIFT (2U)
#define S16UP_TX2LN_PCS_TMIC1_FILTER_ERR_EN_MASK (0x2U)
#define S16UP_TX2LN_PCS_TMIC1_FILTER_ERR_EN_SHIFT (1U)
#define S16UP_TX2LN_PCS_TMIC1_FILTER_ORDERED_SET_EN_MASK (0x1U)
#define S16UP_TX2LN_PCS_TMIC1_FILTER_ORDERED_SET_EN_SHIFT (0U)




typedef uint16_t S16UP_TX2LN_PCS_TMIC_TYPE;
#define S16UP_TX2LN_PCS_TMIC_GMII_FILTER_EN_OV_EN_MASK (0x8U)
#define S16UP_TX2LN_PCS_TMIC_GMII_FILTER_EN_OV_EN_SHIFT (3U)
#define S16UP_TX2LN_PCS_TMIC_GMII_FILTER_EN_OV_MASK (0x4U)
#define S16UP_TX2LN_PCS_TMIC_GMII_FILTER_EN_OV_SHIFT (2U)
#define S16UP_TX2LN_PCS_TMIC_FILTER_CE_EN_MASK (0x2U)
#define S16UP_TX2LN_PCS_TMIC_FILTER_CE_EN_SHIFT (1U)
#define S16UP_TX2LN_PCS_TMIC_T_MAC_INTF_PKT_CNT_PRESET_MASK (0x1U)
#define S16UP_TX2LN_PCS_TMIC_T_MAC_INTF_PKT_CNT_PRESET_SHIFT (0U)




typedef uint16_t S16UP_TX2LN_PCS_TMIPCL_TYPE;
#define S16UP_TX2LN_PCS_TMIPCL_T_MAC_INTF_PKT_CNT_LOW_MASK (0xffffU)
#define S16UP_TX2LN_PCS_TMIPCL_T_MAC_INTF_PKT_CNT_LOW_SHIFT (0U)




typedef uint16_t S16UP_TX2LN_PCS_T_MAC_INTF_PKT_STAT0_TYPE;
#define S16UP_TX2LN_PCS_T_MAC_INTF_PKT_STAT0_MASK (0xffffU)
#define S16UP_TX2LN_PCS_T_MAC_INTF_PKT_STAT0_SHIFT (0U)




typedef uint16_t S16UP_TX2LN_PCS_TMIPCU_TYPE;
#define S16UP_TX2LN_PCS_TMIPCU_T_MAC_INTF_PKT_CNT_UP_MASK (0xffffU)
#define S16UP_TX2LN_PCS_TMIPCU_T_MAC_INTF_PKT_CNT_UP_SHIFT (0U)




typedef uint16_t S16UP_TX2LN_PCS_T_MAC_INTF_PKT_STAT1_TYPE;
#define S16UP_TX2LN_PCS_T_MAC_INTF_PKT_STAT1_MASK (0xffffU)
#define S16UP_TX2LN_PCS_T_MAC_INTF_PKT_STAT1_SHIFT (0U)




typedef volatile struct sS16UP_TX2LN_PCS_RDBType {
    S16UP_TX2LN_PCS_RESERVED_TYPE rsvd0[12]; /* OFFSET: 0x0 */
    S16UP_TX2LN_PCS_FX100_TXCONTROL1_TYPE fx100_txcontrol1; /* OFFSET: 0xc */
    S16UP_TX2LN_PCS_RESERVED_TYPE rsvd1[10]; /* OFFSET: 0xe */
    S16UP_TX2LN_PCS_T_MAC_SEQ_TSTMUX_STATUS_TYPE t_mac_seq_tstmux_status; /* OFFSET: 0x18 */
    S16UP_TX2LN_PCS_RESERVED_TYPE rsvd2[2]; /* OFFSET: 0x1a */
    S16UP_TX2LN_PCS_TMFSC1_TYPE t_mac_force_sequence_control1; /* OFFSET: 0x1c */
    S16UP_TX2LN_PCS_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0x1e */
    S16UP_TX2LN_PCS_TMFSC2_TYPE t_mac_force_sequence_control2; /* OFFSET: 0x20 */
    S16UP_TX2LN_PCS_RESERVED_TYPE rsvd4[2]; /* OFFSET: 0x22 */
    S16UP_TX2LN_PCS_TMIC1_TYPE t_mac_intf_control_1; /* OFFSET: 0x24 */
    S16UP_TX2LN_PCS_RESERVED_TYPE rsvd5[2]; /* OFFSET: 0x26 */
    S16UP_TX2LN_PCS_TMIC_TYPE t_mac_intf_control; /* OFFSET: 0x28 */
    S16UP_TX2LN_PCS_RESERVED_TYPE rsvd6[2]; /* OFFSET: 0x2a */
    S16UP_TX2LN_PCS_TMIPCL_TYPE t_mac_intf_pkt_cnt_low; /* OFFSET: 0x2c */
    S16UP_TX2LN_PCS_RESERVED_TYPE rsvd7[2]; /* OFFSET: 0x2e */
    S16UP_TX2LN_PCS_T_MAC_INTF_PKT_STAT0_TYPE t_mac_intf_pkt_stat0; /* OFFSET: 0x30 */
    S16UP_TX2LN_PCS_RESERVED_TYPE rsvd8[2]; /* OFFSET: 0x32 */
    S16UP_TX2LN_PCS_TMIPCU_TYPE t_mac_intf_pkt_cnt_up; /* OFFSET: 0x34 */
    S16UP_TX2LN_PCS_RESERVED_TYPE rsvd9[2]; /* OFFSET: 0x36 */
    S16UP_TX2LN_PCS_T_MAC_INTF_PKT_STAT1_TYPE t_mac_intf_pkt_stat1; /* OFFSET: 0x38 */
} S16UP_TX2LN_PCS_RDBType;


#define TX_PCS_REG2_BASE                (0xE04E0240UL)



#define S16UP_TX2LN_PCS_MAX_HW_ID       (1UL)

#endif /* S16UP_TX2LN_PCS_RDB_H */
