/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file s16up_ana_pmd_blk0_rdb.h
    @brief RDB File for S16UP_ANA_PMD_BLK0

    @version BCM89580_A0_20230125_RDB
*/

#ifndef S16UP_ANA_PMD_BLK0_RDB_H
#define S16UP_ANA_PMD_BLK0_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t S16UP_ANA_PMD_BLK0_ANA_PMD_CTRL0_TYPE;
#define S16UP_ANA_PMD_BLK0_ANA_PMD_CTRL0_DIS_RX_FORCE_CK_SWITCH_MASK (0x80U)
#define S16UP_ANA_PMD_BLK0_ANA_PMD_CTRL0_DIS_RX_FORCE_CK_SWITCH_SHIFT (7U)
#define S16UP_ANA_PMD_BLK0_ANA_PMD_CTRL0_DIS_TX_FORCE_CK_SWITCH_MASK (0x40U)
#define S16UP_ANA_PMD_BLK0_ANA_PMD_CTRL0_DIS_TX_FORCE_CK_SWITCH_SHIFT (6U)
#define S16UP_ANA_PMD_BLK0_ANA_PMD_CTRL0_ANA_RG_TX_PD_OVRD_MASK (0x20U)
#define S16UP_ANA_PMD_BLK0_ANA_PMD_CTRL0_ANA_RG_TX_PD_OVRD_SHIFT (5U)
#define S16UP_ANA_PMD_BLK0_ANA_PMD_CTRL0_ANA_RG_TX_PD_MASK (0x10U)
#define S16UP_ANA_PMD_BLK0_ANA_PMD_CTRL0_ANA_RG_TX_PD_SHIFT (4U)
#define S16UP_ANA_PMD_BLK0_ANA_PMD_CTRL0_ANA_RG_RX_PD_OVRD_MASK (0x8U)
#define S16UP_ANA_PMD_BLK0_ANA_PMD_CTRL0_ANA_RG_RX_PD_OVRD_SHIFT (3U)
#define S16UP_ANA_PMD_BLK0_ANA_PMD_CTRL0_ANA_RG_RX_PD_MASK (0x4U)
#define S16UP_ANA_PMD_BLK0_ANA_PMD_CTRL0_ANA_RG_RX_PD_SHIFT (2U)
#define S16UP_ANA_PMD_BLK0_ANA_PMD_CTRL0_ANA_RG_SIGDET_PD_OVRD_MASK (0x2U)
#define S16UP_ANA_PMD_BLK0_ANA_PMD_CTRL0_ANA_RG_SIGDET_PD_OVRD_SHIFT (1U)
#define S16UP_ANA_PMD_BLK0_ANA_PMD_CTRL0_ANA_RG_SIGDET_PD_MASK (0x1U)
#define S16UP_ANA_PMD_BLK0_ANA_PMD_CTRL0_ANA_RG_SIGDET_PD_SHIFT (0U)




typedef uint8_t S16UP_ANA_PMD_BLK0_RESERVED_TYPE;




typedef uint16_t S16UP_ANA_PMD_BLK0_MISC_CTRL1_TYPE;
#define S16UP_ANA_PMD_BLK0_MISC_CTRL1_EMON_EN_SM_MASK (0x2U)
#define S16UP_ANA_PMD_BLK0_MISC_CTRL1_EMON_EN_SM_SHIFT (1U)
#define S16UP_ANA_PMD_BLK0_MISC_CTRL1_SIGDET_CLR_MASK (0x1U)
#define S16UP_ANA_PMD_BLK0_MISC_CTRL1_SIGDET_CLR_SHIFT (0U)




typedef uint16_t S16UP_ANA_PMD_BLK0_CAL_DLY_CTRL0_TYPE;
#define S16UP_ANA_PMD_BLK0_CAL_DLY_CTRL0_POST_AEQ_MASK (0xff00U)
#define S16UP_ANA_PMD_BLK0_CAL_DLY_CTRL0_POST_AEQ_SHIFT (8U)
#define S16UP_ANA_PMD_BLK0_CAL_DLY_CTRL0_POST_SLCAL_MASK (0xffU)
#define S16UP_ANA_PMD_BLK0_CAL_DLY_CTRL0_POST_SLCAL_SHIFT (0U)




typedef uint16_t S16UP_ANA_PMD_BLK0_CAL_DLY_CTRL2_TYPE;
#define S16UP_ANA_PMD_BLK0_CAL_DLY_CTRL2_PRE_AEQ_MASK (0xff00U)
#define S16UP_ANA_PMD_BLK0_CAL_DLY_CTRL2_PRE_AEQ_SHIFT (8U)
#define S16UP_ANA_PMD_BLK0_CAL_DLY_CTRL2_PRE_SLCAL_MASK (0xffU)
#define S16UP_ANA_PMD_BLK0_CAL_DLY_CTRL2_PRE_SLCAL_SHIFT (0U)




typedef uint16_t S16UP_ANA_PMD_BLK0_RES_CAL_LMTOFF_TYPE;
#define S16UP_ANA_PMD_BLK0_RES_CAL_LMTOFF_RG_OVRD_EN_MASK (0x40U)
#define S16UP_ANA_PMD_BLK0_RES_CAL_LMTOFF_RG_OVRD_EN_SHIFT (6U)
#define S16UP_ANA_PMD_BLK0_RES_CAL_LMTOFF_RG_OVRD_VAL_MASK (0x3fU)
#define S16UP_ANA_PMD_BLK0_RES_CAL_LMTOFF_RG_OVRD_VAL_SHIFT (0U)




typedef uint16_t S16UP_ANA_PMD_BLK0_SLOFF_CTRL0_TYPE;
#define S16UP_ANA_PMD_BLK0_SLOFF_CTRL0_RG1O_OVRD_VAL_MASK (0xf000U)
#define S16UP_ANA_PMD_BLK0_SLOFF_CTRL0_RG1O_OVRD_VAL_SHIFT (12U)
#define S16UP_ANA_PMD_BLK0_SLOFF_CTRL0_RG1E_OVRD_VAL_MASK (0xf00U)
#define S16UP_ANA_PMD_BLK0_SLOFF_CTRL0_RG1E_OVRD_VAL_SHIFT (8U)
#define S16UP_ANA_PMD_BLK0_SLOFF_CTRL0_RG0O_OVRD_VAL_MASK (0xf0U)
#define S16UP_ANA_PMD_BLK0_SLOFF_CTRL0_RG0O_OVRD_VAL_SHIFT (4U)
#define S16UP_ANA_PMD_BLK0_SLOFF_CTRL0_RG0E_OVRD_VAL_MASK (0xfU)
#define S16UP_ANA_PMD_BLK0_SLOFF_CTRL0_RG0E_OVRD_VAL_SHIFT (0U)




typedef uint16_t S16UP_ANA_PMD_BLK0_SLOFF_CTRL1_TYPE;
#define S16UP_ANA_PMD_BLK0_SLOFF_CTRL1_ARSROE_MASK (0x100U)
#define S16UP_ANA_PMD_BLK0_SLOFF_CTRL1_ARSROE_SHIFT (8U)
#define S16UP_ANA_PMD_BLK0_SLOFF_CTRL1_ANA_RG_SLOFF2O_OVRD_VAL_MASK (0xf0U)
#define S16UP_ANA_PMD_BLK0_SLOFF_CTRL1_ANA_RG_SLOFF2O_OVRD_VAL_SHIFT (4U)
#define S16UP_ANA_PMD_BLK0_SLOFF_CTRL1_ANA_RG_SLOFF2E_OVRD_VAL_MASK (0xfU)
#define S16UP_ANA_PMD_BLK0_SLOFF_CTRL1_ANA_RG_SLOFF2E_OVRD_VAL_SHIFT (0U)




typedef uint16_t S16UP_ANA_PMD_BLK0_MISC_ANA_CTRL0_TYPE;
#define S16UP_ANA_PMD_BLK0_MISC_ANA_CTRL0_AMAROE_MASK (0x800U)
#define S16UP_ANA_PMD_BLK0_MISC_ANA_CTRL0_AMAROE_SHIFT (11U)
#define S16UP_ANA_PMD_BLK0_MISC_ANA_CTRL0_ANA_MDIO_AEQ_FREEZE_DFS_MASK (0x400U)
#define S16UP_ANA_PMD_BLK0_MISC_ANA_CTRL0_ANA_MDIO_AEQ_FREEZE_DFS_SHIFT (10U)
#define S16UP_ANA_PMD_BLK0_MISC_ANA_CTRL0_AMCBA_MASK (0x200U)
#define S16UP_ANA_PMD_BLK0_MISC_ANA_CTRL0_AMCBA_SHIFT (9U)
#define S16UP_ANA_PMD_BLK0_MISC_ANA_CTRL0_AMCBS_MASK (0x100U)
#define S16UP_ANA_PMD_BLK0_MISC_ANA_CTRL0_AMCBS_SHIFT (8U)
#define S16UP_ANA_PMD_BLK0_MISC_ANA_CTRL0_AMCRA_MASK (0x80U)
#define S16UP_ANA_PMD_BLK0_MISC_ANA_CTRL0_AMCRA_SHIFT (7U)
#define S16UP_ANA_PMD_BLK0_MISC_ANA_CTRL0_AMCRS_MASK (0x40U)
#define S16UP_ANA_PMD_BLK0_MISC_ANA_CTRL0_AMCRS_SHIFT (6U)
#define S16UP_ANA_PMD_BLK0_MISC_ANA_CTRL0_ANA_MDIO_EQ_REG_VAL_DFS_MASK (0x3fU)
#define S16UP_ANA_PMD_BLK0_MISC_ANA_CTRL0_ANA_MDIO_EQ_REG_VAL_DFS_SHIFT (0U)




typedef uint16_t S16UP_ANA_PMD_BLK0_MISC_ANA_CTRL1_TYPE;
#define S16UP_ANA_PMD_BLK0_MISC_ANA_CTRL1_AMPCD_MASK (0xfU)
#define S16UP_ANA_PMD_BLK0_MISC_ANA_CTRL1_AMPCD_SHIFT (0U)




typedef volatile struct sS16UP_ANA_PMD_BLK0_RDBType {
    S16UP_ANA_PMD_BLK0_ANA_PMD_CTRL0_TYPE ana_pmd_ctrl0; /* OFFSET: 0x0 */
    S16UP_ANA_PMD_BLK0_RESERVED_TYPE rsvd0[2]; /* OFFSET: 0x2 */
    S16UP_ANA_PMD_BLK0_MISC_CTRL1_TYPE misc_ctrl1; /* OFFSET: 0x4 */
    S16UP_ANA_PMD_BLK0_RESERVED_TYPE rsvd1[2]; /* OFFSET: 0x6 */
    S16UP_ANA_PMD_BLK0_CAL_DLY_CTRL0_TYPE cal_dly_ctrl0; /* OFFSET: 0x8 */
    S16UP_ANA_PMD_BLK0_RESERVED_TYPE rsvd2[2]; /* OFFSET: 0xa */
    S16UP_ANA_PMD_BLK0_CAL_DLY_CTRL2_TYPE cal_dly_ctrl2; /* OFFSET: 0xc */
    S16UP_ANA_PMD_BLK0_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0xe */
    S16UP_ANA_PMD_BLK0_RES_CAL_LMTOFF_TYPE res_cal_lmtoff; /* OFFSET: 0x10 */
    S16UP_ANA_PMD_BLK0_RESERVED_TYPE rsvd4[2]; /* OFFSET: 0x12 */
    S16UP_ANA_PMD_BLK0_SLOFF_CTRL0_TYPE sloff_ctrl0; /* OFFSET: 0x14 */
    S16UP_ANA_PMD_BLK0_RESERVED_TYPE rsvd5[2]; /* OFFSET: 0x16 */
    S16UP_ANA_PMD_BLK0_SLOFF_CTRL1_TYPE sloff_ctrl1; /* OFFSET: 0x18 */
    S16UP_ANA_PMD_BLK0_RESERVED_TYPE rsvd6[2]; /* OFFSET: 0x1a */
    S16UP_ANA_PMD_BLK0_MISC_ANA_CTRL0_TYPE misc_ana_ctrl0; /* OFFSET: 0x1c */
    S16UP_ANA_PMD_BLK0_RESERVED_TYPE rsvd7[2]; /* OFFSET: 0x1e */
    S16UP_ANA_PMD_BLK0_MISC_ANA_CTRL1_TYPE misc_ana_ctrl1; /* OFFSET: 0x20 */
} S16UP_ANA_PMD_BLK0_RDBType;


#define ANA_PMD_BLK0_BASE               (0xE0468200UL)



#define S16UP_ANA_PMD_BLK0_MAX_HW_ID    (1UL)

#endif /* S16UP_ANA_PMD_BLK0_RDB_H */
