/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file s16up_tx_afe_rdb.h
    @brief RDB File for S16UP_TX_AFE

    @version BCM89580_A0_20230125_RDB
*/

#ifndef S16UP_TX_AFE_RDB_H
#define S16UP_TX_AFE_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t S16UP_TX_AFE_TXPMD_1TX_PMD_REV_ID_TYPE;
#define S16UP_TX_AFE_TXPMD_1TX_PMD_REV_ID_MASK (0xffffU)
#define S16UP_TX_AFE_TXPMD_1TX_PMD_REV_ID_SHIFT (0U)




typedef uint8_t S16UP_TX_AFE_RESERVED_TYPE;




typedef uint16_t S16UP_TX_AFE_TXPMD_1TX_CONTROL1_TYPE;
#define S16UP_TX_AFE_TXPMD_1TX_CONTROL1_TX_PHASE_POL_MASK (0x4000U)
#define S16UP_TX_AFE_TXPMD_1TX_CONTROL1_TX_PHASE_POL_SHIFT (14U)
#define S16UP_TX_AFE_TXPMD_1TX_CONTROL1_TX_PHASE_ENC_MD_MASK (0x2000U)
#define S16UP_TX_AFE_TXPMD_1TX_CONTROL1_TX_PHASE_ENC_MD_SHIFT (13U)
#define S16UP_TX_AFE_TXPMD_1TX_CONTROL1_TX_PHACT_8B4BN_MASK (0x1000U)
#define S16UP_TX_AFE_TXPMD_1TX_CONTROL1_TX_PHACT_8B4BN_SHIFT (12U)
#define S16UP_TX_AFE_TXPMD_1TX_CONTROL1_ANA_FAREND_LPBK_MASK (0x800U)
#define S16UP_TX_AFE_TXPMD_1TX_CONTROL1_ANA_FAREND_LPBK_SHIFT (11U)
#define S16UP_TX_AFE_TXPMD_1TX_CONTROL1_HSTR_FILT_BYPASS_MASK (0x400U)
#define S16UP_TX_AFE_TXPMD_1TX_CONTROL1_HSTR_FILT_BYPASS_SHIFT (10U)
#define S16UP_TX_AFE_TXPMD_1TX_CONTROL1_TX_HOST_TRACK_EN_MASK (0x200U)
#define S16UP_TX_AFE_TXPMD_1TX_CONTROL1_TX_HOST_TRACK_EN_SHIFT (9U)
#define S16UP_TX_AFE_TXPMD_1TX_CONTROL1_TX_PHS_STP_INV_MASK (0x100U)
#define S16UP_TX_AFE_TXPMD_1TX_CONTROL1_TX_PHS_STP_INV_SHIFT (8U)
#define S16UP_TX_AFE_TXPMD_1TX_CONTROL1_TX_PHASE_ROTATE_MASK (0xf0U)
#define S16UP_TX_AFE_TXPMD_1TX_CONTROL1_TX_PHASE_ROTATE_SHIFT (4U)
#define S16UP_TX_AFE_TXPMD_1TX_CONTROL1_TX_PMD_EN_FRC_VAL_MASK (0x8U)
#define S16UP_TX_AFE_TXPMD_1TX_CONTROL1_TX_PMD_EN_FRC_VAL_SHIFT (3U)
#define S16UP_TX_AFE_TXPMD_1TX_CONTROL1_TX_PMD_EN_FRC_MASK (0x4U)
#define S16UP_TX_AFE_TXPMD_1TX_CONTROL1_TX_PMD_EN_FRC_SHIFT (2U)
#define S16UP_TX_AFE_TXPMD_1TX_CONTROL1_TX_SSC_EN_FRC_VAL_MASK (0x2U)
#define S16UP_TX_AFE_TXPMD_1TX_CONTROL1_TX_SSC_EN_FRC_VAL_SHIFT (1U)
#define S16UP_TX_AFE_TXPMD_1TX_CONTROL1_TX_SSC_EN_FRC_MASK (0x1U)
#define S16UP_TX_AFE_TXPMD_1TX_CONTROL1_TX_SSC_EN_FRC_SHIFT (0U)




typedef uint16_t S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_CONTROL1_TYPE;
#define S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_CONTROL1_FIXED_FSTEP_MASK (0xffffU)
#define S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_CONTROL1_FIXED_FSTEP_SHIFT (0U)




typedef uint16_t S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_CONTROL2_TYPE;
#define S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_CONTROL2_USE_DFE_B_MASK (0x8000U)
#define S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_CONTROL2_USE_DFE_B_SHIFT (15U)
#define S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_CONTROL2_FIXED_FMIN_MASK (0x3ffU)
#define S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_CONTROL2_FIXED_FMIN_SHIFT (0U)




typedef uint16_t S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_CONTROL3_TYPE;
#define S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_CONTROL3_FIXED_FMAX_MASK (0x3ffU)
#define S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_CONTROL3_FIXED_FMAX_SHIFT (0U)




typedef uint16_t S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_CONTROL4_TYPE;
#define S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_CONTROL4_HSTR_INSEL_MASK (0x4000U)
#define S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_CONTROL4_HSTR_INSEL_SHIFT (14U)
#define S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_CONTROL4_HSTR_FILT1_SEL_MASK (0x3c00U)
#define S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_CONTROL4_HSTR_FILT1_SEL_SHIFT (10U)
#define S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_CONTROL4_HSTR_FILT2_SEL_MASK (0x3c0U)
#define S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_CONTROL4_HSTR_FILT2_SEL_SHIFT (6U)
#define S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_CONTROL4_HSTR_AVG_SEL_MASK (0x38U)
#define S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_CONTROL4_HSTR_AVG_SEL_SHIFT (3U)
#define S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_CONTROL4_HSTR_SSC_FREQ_MASK (0x7U)
#define S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_CONTROL4_HSTR_SSC_FREQ_SHIFT (0U)




typedef uint16_t S16UP_TX_AFE_T1FCC5_TYPE;
#define S16UP_TX_AFE_T1FCC5_HSTR_OFFSET_MASK (0xf0U)
#define S16UP_TX_AFE_T1FCC5_HSTR_OFFSET_SHIFT (4U)
#define S16UP_TX_AFE_T1FCC5_HSTR_UPD_READY_DLY_MASK (0x8U)
#define S16UP_TX_AFE_T1FCC5_HSTR_UPD_READY_DLY_SHIFT (3U)
#define S16UP_TX_AFE_T1FCC5_HSTR_UPD_DIS_MASK (0x4U)
#define S16UP_TX_AFE_T1FCC5_HSTR_UPD_DIS_SHIFT (2U)
#define S16UP_TX_AFE_T1FCC5_HSTR_BYPASS_MASK (0x2U)
#define S16UP_TX_AFE_T1FCC5_HSTR_BYPASS_SHIFT (1U)
#define S16UP_TX_AFE_T1FCC5_EARLY_TXPMD_RDY_MASK (0x1U)
#define S16UP_TX_AFE_T1FCC5_EARLY_TXPMD_RDY_SHIFT (0U)




typedef uint16_t S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_STATUS1_TYPE;
#define S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_STATUS1_TX_PMD_READY_MASK (0x400U)
#define S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_STATUS1_TX_PMD_READY_SHIFT (10U)
#define S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_STATUS1_HSTR_FREQ_CTRL_MASK (0x3ffU)
#define S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_STATUS1_HSTR_FREQ_CTRL_SHIFT (0U)




typedef uint16_t S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_STATUS2_TYPE;
#define S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_STATUS2_HSTR_FMIN_MASK (0x3ffU)
#define S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_STATUS2_HSTR_FMIN_SHIFT (0U)




typedef uint16_t S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_STATUS3_TYPE;
#define S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_STATUS3_HSTR_FMAX_MASK (0x3ffU)
#define S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_STATUS3_HSTR_FMAX_SHIFT (0U)




typedef uint16_t S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_STATUS4_TYPE;
#define S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_STATUS4_MASK (0x3ffU)
#define S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_STATUS4_SHIFT (0U)




typedef uint16_t S16UP_TX_AFE_TXPMD_1TX_HSPMD_STATUS1_TYPE;
#define S16UP_TX_AFE_TXPMD_1TX_HSPMD_STATUS1_PHASE_COUNTER_MASK (0x3fU)
#define S16UP_TX_AFE_TXPMD_1TX_HSPMD_STATUS1_PHASE_COUNTER_SHIFT (0U)




typedef uint16_t S16UP_TX_AFE_TXPMD_1TX_PRBS_CTRL1_TYPE;
#define S16UP_TX_AFE_TXPMD_1TX_PRBS_CTRL1_PRBSEN_MASK (0x8000U)
#define S16UP_TX_AFE_TXPMD_1TX_PRBS_CTRL1_PRBSEN_SHIFT (15U)
#define S16UP_TX_AFE_TXPMD_1TX_PRBS_CTRL1_PRBSMODE_MASK (0x6000U)
#define S16UP_TX_AFE_TXPMD_1TX_PRBS_CTRL1_PRBSMODE_SHIFT (13U)
#define S16UP_TX_AFE_TXPMD_1TX_PRBS_CTRL1_DATAINVERT_MASK (0x800U)
#define S16UP_TX_AFE_TXPMD_1TX_PRBS_CTRL1_DATAINVERT_SHIFT (11U)
#define S16UP_TX_AFE_TXPMD_1TX_PRBS_CTRL1_DATATRANSPOSE_MASK (0x400U)
#define S16UP_TX_AFE_TXPMD_1TX_PRBS_CTRL1_DATATRANSPOSE_SHIFT (10U)
#define S16UP_TX_AFE_TXPMD_1TX_PRBS_CTRL1_PRBSSEED_19_16_MASK (0xfU)
#define S16UP_TX_AFE_TXPMD_1TX_PRBS_CTRL1_PRBSSEED_19_16_SHIFT (0U)




typedef uint16_t S16UP_TX_AFE_TXPMD_1TX_PRBS_CTRL2_TYPE;
#define S16UP_TX_AFE_TXPMD_1TX_PRBS_CTRL2_PRBSSEED_15_0_MASK (0xffffU)
#define S16UP_TX_AFE_TXPMD_1TX_PRBS_CTRL2_PRBSSEED_15_0_SHIFT (0U)




typedef volatile struct sS16UP_TX_AFE_RDBType {
    S16UP_TX_AFE_TXPMD_1TX_PMD_REV_ID_TYPE pmd_rev_id; /* OFFSET: 0x0 */
    S16UP_TX_AFE_RESERVED_TYPE rsvd0[2]; /* OFFSET: 0x2 */
    S16UP_TX_AFE_TXPMD_1TX_CONTROL1_TYPE control1; /* OFFSET: 0x4 */
    S16UP_TX_AFE_RESERVED_TYPE rsvd1[2]; /* OFFSET: 0x6 */
    S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_CONTROL1_TYPE freq_ctrl_control1; /* OFFSET: 0x8 */
    S16UP_TX_AFE_RESERVED_TYPE rsvd2[2]; /* OFFSET: 0xa */
    S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_CONTROL2_TYPE freq_ctrl_control2; /* OFFSET: 0xc */
    S16UP_TX_AFE_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0xe */
    S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_CONTROL3_TYPE freq_ctrl_control3; /* OFFSET: 0x10 */
    S16UP_TX_AFE_RESERVED_TYPE rsvd4[2]; /* OFFSET: 0x12 */
    S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_CONTROL4_TYPE freq_ctrl_control4; /* OFFSET: 0x14 */
    S16UP_TX_AFE_RESERVED_TYPE rsvd5[2]; /* OFFSET: 0x16 */
    S16UP_TX_AFE_T1FCC5_TYPE freq_ctrl_control5; /* OFFSET: 0x18 */
    S16UP_TX_AFE_RESERVED_TYPE rsvd6[2]; /* OFFSET: 0x1a */
    S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_STATUS1_TYPE freq_ctrl_status1; /* OFFSET: 0x1c */
    S16UP_TX_AFE_RESERVED_TYPE rsvd7[2]; /* OFFSET: 0x1e */
    S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_STATUS2_TYPE freq_ctrl_status2; /* OFFSET: 0x20 */
    S16UP_TX_AFE_RESERVED_TYPE rsvd8[2]; /* OFFSET: 0x22 */
    S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_STATUS3_TYPE freq_ctrl_status3; /* OFFSET: 0x24 */
    S16UP_TX_AFE_RESERVED_TYPE rsvd9[2]; /* OFFSET: 0x26 */
    S16UP_TX_AFE_TXPMD_1TX_FREQ_CTRL_STATUS4_TYPE freq_ctrl_status4; /* OFFSET: 0x28 */
    S16UP_TX_AFE_RESERVED_TYPE rsvd10[2]; /* OFFSET: 0x2a */
    S16UP_TX_AFE_TXPMD_1TX_HSPMD_STATUS1_TYPE hspmd_status1; /* OFFSET: 0x2c */
    S16UP_TX_AFE_RESERVED_TYPE rsvd11[2]; /* OFFSET: 0x2e */
    S16UP_TX_AFE_TXPMD_1TX_PRBS_CTRL1_TYPE prbs_ctrl1; /* OFFSET: 0x30 */
    S16UP_TX_AFE_RESERVED_TYPE rsvd12[2]; /* OFFSET: 0x32 */
    S16UP_TX_AFE_TXPMD_1TX_PRBS_CTRL2_TYPE prbs_ctrl2; /* OFFSET: 0x34 */
} S16UP_TX_AFE_RDBType;


#define TX_AFE_BASE                     (0xE0468040UL)



#define S16UP_TX_AFE_MAX_HW_ID          (1UL)

#endif /* S16UP_TX_AFE_RDB_H */
