/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file s16up_rx_aeq_rdb.h
    @brief RDB File for S16UP_RX_AEQ

    @version BCM89580_A0_20230125_RDB
*/

#ifndef S16UP_RX_AEQ_RDB_H
#define S16UP_RX_AEQ_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t S16UP_RX_AEQ_AEQ_REV_ID_TYPE;
#define S16UP_RX_AEQ_AEQ_REV_ID_MASK (0xffffU)
#define S16UP_RX_AEQ_AEQ_REV_ID_SHIFT (0U)




typedef uint8_t S16UP_RX_AEQ_RESERVED_TYPE;




typedef uint16_t S16UP_RX_AEQ_AEQ_CONTROL1_TYPE;
#define S16UP_RX_AEQ_AEQ_CONTROL1_INVERT_OS_MASK (0x8000U)
#define S16UP_RX_AEQ_AEQ_CONTROL1_INVERT_OS_SHIFT (15U)
#define S16UP_RX_AEQ_AEQ_CONTROL1_INVERT_ISI_MASK (0x4000U)
#define S16UP_RX_AEQ_AEQ_CONTROL1_INVERT_ISI_SHIFT (14U)
#define S16UP_RX_AEQ_AEQ_CONTROL1_BALANCE_VAL_MASK (0x3000U)
#define S16UP_RX_AEQ_AEQ_CONTROL1_BALANCE_VAL_SHIFT (12U)
#define S16UP_RX_AEQ_AEQ_CONTROL1_OC_FRZ_OFFSET_MASK (0xf00U)
#define S16UP_RX_AEQ_AEQ_CONTROL1_OC_FRZ_OFFSET_SHIFT (8U)
#define S16UP_RX_AEQ_AEQ_CONTROL1_EQ_FRZ_OFFSET_MASK (0xf0U)
#define S16UP_RX_AEQ_AEQ_CONTROL1_EQ_FRZ_OFFSET_SHIFT (4U)
#define S16UP_RX_AEQ_AEQ_CONTROL1_FREEZE_MASK (0x8U)
#define S16UP_RX_AEQ_AEQ_CONTROL1_FREEZE_SHIFT (3U)
#define S16UP_RX_AEQ_AEQ_CONTROL1_ENABLE_MASK (0x4U)
#define S16UP_RX_AEQ_AEQ_CONTROL1_ENABLE_SHIFT (2U)
#define S16UP_RX_AEQ_AEQ_CONTROL1_RESET_MASK (0x2U)
#define S16UP_RX_AEQ_AEQ_CONTROL1_RESET_SHIFT (1U)
#define S16UP_RX_AEQ_AEQ_CONTROL1_PWRDN_MASK (0x1U)
#define S16UP_RX_AEQ_AEQ_CONTROL1_PWRDN_SHIFT (0U)




typedef uint16_t S16UP_RX_AEQ_AEQ_CONTROL2_TYPE;
#define S16UP_RX_AEQ_AEQ_CONTROL2_TEST_MUX_MASK (0xe000U)
#define S16UP_RX_AEQ_AEQ_CONTROL2_TEST_MUX_SHIFT (13U)
#define S16UP_RX_AEQ_AEQ_CONTROL2_EQ_FMT_MASK (0x1000U)
#define S16UP_RX_AEQ_AEQ_CONTROL2_EQ_FMT_SHIFT (12U)
#define S16UP_RX_AEQ_AEQ_CONTROL2_OC_FMT_MASK (0x800U)
#define S16UP_RX_AEQ_AEQ_CONTROL2_OC_FMT_SHIFT (11U)
#define S16UP_RX_AEQ_AEQ_CONTROL2_T_HG_ACQ_MASK (0x600U)
#define S16UP_RX_AEQ_AEQ_CONTROL2_T_HG_ACQ_SHIFT (9U)
#define S16UP_RX_AEQ_AEQ_CONTROL2_T_AEQ2_MASK (0x1c0U)
#define S16UP_RX_AEQ_AEQ_CONTROL2_T_AEQ2_SHIFT (6U)
#define S16UP_RX_AEQ_AEQ_CONTROL2_T_AEQ1_MASK (0x38U)
#define S16UP_RX_AEQ_AEQ_CONTROL2_T_AEQ1_SHIFT (3U)
#define S16UP_RX_AEQ_AEQ_CONTROL2_T_INIT_MASK (0x7U)
#define S16UP_RX_AEQ_AEQ_CONTROL2_T_INIT_SHIFT (0U)




typedef uint16_t S16UP_RX_AEQ_AEQ_FRC_EQ_TYPE;
#define S16UP_RX_AEQ_AEQ_FRC_EQ_FORCE_LOS_AEQ_RESET_MASK (0x8000U)
#define S16UP_RX_AEQ_AEQ_FRC_EQ_FORCE_LOS_AEQ_RESET_SHIFT (15U)
#define S16UP_RX_AEQ_AEQ_FRC_EQ_AEQ_FREEZE_OVRD_MASK (0x2000U)
#define S16UP_RX_AEQ_AEQ_FRC_EQ_AEQ_FREEZE_OVRD_SHIFT (13U)
#define S16UP_RX_AEQ_AEQ_FRC_EQ_AEQ_FREEZE_OVRD_VAL_MASK (0x1000U)
#define S16UP_RX_AEQ_AEQ_FRC_EQ_AEQ_FREEZE_OVRD_VAL_SHIFT (12U)
#define S16UP_RX_AEQ_AEQ_FRC_EQ_AEQ_ENABLE_OVRD_MASK (0x800U)
#define S16UP_RX_AEQ_AEQ_FRC_EQ_AEQ_ENABLE_OVRD_SHIFT (11U)
#define S16UP_RX_AEQ_AEQ_FRC_EQ_AEQ_ENABLE_OVRD_VAL_MASK (0x400U)
#define S16UP_RX_AEQ_AEQ_FRC_EQ_AEQ_ENABLE_OVRD_VAL_SHIFT (10U)
#define S16UP_RX_AEQ_AEQ_FRC_EQ_EQ_FRZ_FRC_VAL_MASK (0x200U)
#define S16UP_RX_AEQ_AEQ_FRC_EQ_EQ_FRZ_FRC_VAL_SHIFT (9U)
#define S16UP_RX_AEQ_AEQ_FRC_EQ_EQ_FRZ_FRC_MASK (0x100U)
#define S16UP_RX_AEQ_AEQ_FRC_EQ_EQ_FRZ_FRC_SHIFT (8U)
#define S16UP_RX_AEQ_AEQ_FRC_EQ_EQ_REG_VAL_MASK (0xfcU)
#define S16UP_RX_AEQ_AEQ_FRC_EQ_EQ_REG_VAL_SHIFT (2U)
#define S16UP_RX_AEQ_AEQ_FRC_EQ_EQ_REG_FRC_VAL_MASK (0x2U)
#define S16UP_RX_AEQ_AEQ_FRC_EQ_EQ_REG_FRC_VAL_SHIFT (1U)
#define S16UP_RX_AEQ_AEQ_FRC_EQ_EQ_REG_FRC_MASK (0x1U)
#define S16UP_RX_AEQ_AEQ_FRC_EQ_EQ_REG_FRC_SHIFT (0U)




typedef uint16_t S16UP_RX_AEQ_AEQ_FRC_OC_TYPE;
#define S16UP_RX_AEQ_AEQ_FRC_OC_EDGEK_OVR_VAL_MASK (0x3000U)
#define S16UP_RX_AEQ_AEQ_FRC_OC_EDGEK_OVR_VAL_SHIFT (12U)
#define S16UP_RX_AEQ_AEQ_FRC_OC_EDGEK_OVR_MASK (0x800U)
#define S16UP_RX_AEQ_AEQ_FRC_OC_EDGEK_OVR_SHIFT (11U)
#define S16UP_RX_AEQ_AEQ_FRC_OC_HG_FETCH_MASK (0x400U)
#define S16UP_RX_AEQ_AEQ_FRC_OC_HG_FETCH_SHIFT (10U)
#define S16UP_RX_AEQ_AEQ_FRC_OC_OC_FRZ_FRC_VAL_MASK (0x200U)
#define S16UP_RX_AEQ_AEQ_FRC_OC_OC_FRZ_FRC_VAL_SHIFT (9U)
#define S16UP_RX_AEQ_AEQ_FRC_OC_OC_FRZ_FRC_MASK (0x100U)
#define S16UP_RX_AEQ_AEQ_FRC_OC_OC_FRZ_FRC_SHIFT (8U)
#define S16UP_RX_AEQ_AEQ_FRC_OC_OC_REG_VAL_MASK (0xfcU)
#define S16UP_RX_AEQ_AEQ_FRC_OC_OC_REG_VAL_SHIFT (2U)
#define S16UP_RX_AEQ_AEQ_FRC_OC_OC_REG_FRC_VAL_MASK (0x2U)
#define S16UP_RX_AEQ_AEQ_FRC_OC_OC_REG_FRC_VAL_SHIFT (1U)
#define S16UP_RX_AEQ_AEQ_FRC_OC_OC_REG_FRC_MASK (0x1U)
#define S16UP_RX_AEQ_AEQ_FRC_OC_OC_REG_FRC_SHIFT (0U)




typedef uint16_t S16UP_RX_AEQ_AEQ_INIT_TYPE;
#define S16UP_RX_AEQ_AEQ_INIT_OS_PK_INIT_MASK (0x1000U)
#define S16UP_RX_AEQ_AEQ_INIT_OS_PK_INIT_SHIFT (12U)
#define S16UP_RX_AEQ_AEQ_INIT_OS_BAL_INIT_MASK (0x800U)
#define S16UP_RX_AEQ_AEQ_INIT_OS_BAL_INIT_SHIFT (11U)
#define S16UP_RX_AEQ_AEQ_INIT_OS_GAIN_INIT_MASK (0x700U)
#define S16UP_RX_AEQ_AEQ_INIT_OS_GAIN_INIT_SHIFT (8U)
#define S16UP_RX_AEQ_AEQ_INIT_OC_FRZ_INIT_MASK (0x80U)
#define S16UP_RX_AEQ_AEQ_INIT_OC_FRZ_INIT_SHIFT (7U)
#define S16UP_RX_AEQ_AEQ_INIT_OC_FRC_INIT_MASK (0x40U)
#define S16UP_RX_AEQ_AEQ_INIT_OC_FRC_INIT_SHIFT (6U)
#define S16UP_RX_AEQ_AEQ_INIT_ISI_BAL_INIT_MASK (0x20U)
#define S16UP_RX_AEQ_AEQ_INIT_ISI_BAL_INIT_SHIFT (5U)
#define S16UP_RX_AEQ_AEQ_INIT_ISI_GAIN_INIT_MASK (0x1cU)
#define S16UP_RX_AEQ_AEQ_INIT_ISI_GAIN_INIT_SHIFT (2U)
#define S16UP_RX_AEQ_AEQ_INIT_EQ_FRZ_INIT_MASK (0x2U)
#define S16UP_RX_AEQ_AEQ_INIT_EQ_FRZ_INIT_SHIFT (1U)
#define S16UP_RX_AEQ_AEQ_INIT_EQ_FRC_INIT_MASK (0x1U)
#define S16UP_RX_AEQ_AEQ_INIT_EQ_FRC_INIT_SHIFT (0U)




typedef uint16_t S16UP_RX_AEQ_AEQ_AEQ1_TYPE;
#define S16UP_RX_AEQ_AEQ_AEQ1_OS_PK_AEQ1_MASK (0x1000U)
#define S16UP_RX_AEQ_AEQ_AEQ1_OS_PK_AEQ1_SHIFT (12U)
#define S16UP_RX_AEQ_AEQ_AEQ1_OS_BAL_AEQ1_MASK (0x800U)
#define S16UP_RX_AEQ_AEQ_AEQ1_OS_BAL_AEQ1_SHIFT (11U)
#define S16UP_RX_AEQ_AEQ_AEQ1_OS_GAIN_AEQ1_MASK (0x700U)
#define S16UP_RX_AEQ_AEQ_AEQ1_OS_GAIN_AEQ1_SHIFT (8U)
#define S16UP_RX_AEQ_AEQ_AEQ1_OC_FRZ_AEQ1_MASK (0x80U)
#define S16UP_RX_AEQ_AEQ_AEQ1_OC_FRZ_AEQ1_SHIFT (7U)
#define S16UP_RX_AEQ_AEQ_AEQ1_OC_FRC_AEQ1_MASK (0x40U)
#define S16UP_RX_AEQ_AEQ_AEQ1_OC_FRC_AEQ1_SHIFT (6U)
#define S16UP_RX_AEQ_AEQ_AEQ1_ISI_BAL_AEQ1_MASK (0x20U)
#define S16UP_RX_AEQ_AEQ_AEQ1_ISI_BAL_AEQ1_SHIFT (5U)
#define S16UP_RX_AEQ_AEQ_AEQ1_ISI_GAIN_AEQ1_MASK (0x1cU)
#define S16UP_RX_AEQ_AEQ_AEQ1_ISI_GAIN_AEQ1_SHIFT (2U)
#define S16UP_RX_AEQ_AEQ_AEQ1_EQ_FRZ_AEQ1_MASK (0x2U)
#define S16UP_RX_AEQ_AEQ_AEQ1_EQ_FRZ_AEQ1_SHIFT (1U)
#define S16UP_RX_AEQ_AEQ_AEQ1_EQ_FRC_AEQ1_MASK (0x1U)
#define S16UP_RX_AEQ_AEQ_AEQ1_EQ_FRC_AEQ1_SHIFT (0U)




typedef uint16_t S16UP_RX_AEQ_AEQ_AEQ2_TYPE;
#define S16UP_RX_AEQ_AEQ_AEQ2_OS_PK_AEQ2_MASK (0x1000U)
#define S16UP_RX_AEQ_AEQ_AEQ2_OS_PK_AEQ2_SHIFT (12U)
#define S16UP_RX_AEQ_AEQ_AEQ2_OS_BAL_AEQ2_MASK (0x800U)
#define S16UP_RX_AEQ_AEQ_AEQ2_OS_BAL_AEQ2_SHIFT (11U)
#define S16UP_RX_AEQ_AEQ_AEQ2_OS_GAIN_AEQ2_MASK (0x700U)
#define S16UP_RX_AEQ_AEQ_AEQ2_OS_GAIN_AEQ2_SHIFT (8U)
#define S16UP_RX_AEQ_AEQ_AEQ2_OC_FRZ_AEQ2_MASK (0x80U)
#define S16UP_RX_AEQ_AEQ_AEQ2_OC_FRZ_AEQ2_SHIFT (7U)
#define S16UP_RX_AEQ_AEQ_AEQ2_OC_FRC_AEQ2_MASK (0x40U)
#define S16UP_RX_AEQ_AEQ_AEQ2_OC_FRC_AEQ2_SHIFT (6U)
#define S16UP_RX_AEQ_AEQ_AEQ2_ISI_BAL_AEQ2_MASK (0x20U)
#define S16UP_RX_AEQ_AEQ_AEQ2_ISI_BAL_AEQ2_SHIFT (5U)
#define S16UP_RX_AEQ_AEQ_AEQ2_ISI_GAIN_AEQ2_MASK (0x1cU)
#define S16UP_RX_AEQ_AEQ_AEQ2_ISI_GAIN_AEQ2_SHIFT (2U)
#define S16UP_RX_AEQ_AEQ_AEQ2_EQ_FRZ_AEQ2_MASK (0x2U)
#define S16UP_RX_AEQ_AEQ_AEQ2_EQ_FRZ_AEQ2_SHIFT (1U)
#define S16UP_RX_AEQ_AEQ_AEQ2_EQ_FRC_AEQ2_MASK (0x1U)
#define S16UP_RX_AEQ_AEQ_AEQ2_EQ_FRC_AEQ2_SHIFT (0U)




typedef uint16_t S16UP_RX_AEQ_AEQ_REGS_TYPE;
#define S16UP_RX_AEQ_AEQ_REGS_VAL_MASK (0xffffU)
#define S16UP_RX_AEQ_AEQ_REGS_VAL_SHIFT (0U)




typedef uint16_t S16UP_RX_AEQ_AEQ_TP_CTRL_TYPE;
#define S16UP_RX_AEQ_AEQ_TP_CTRL_STAT_CAP_MASK (0x10U)
#define S16UP_RX_AEQ_AEQ_TP_CTRL_STAT_CAP_SHIFT (4U)
#define S16UP_RX_AEQ_AEQ_TP_CTRL_TP_CTRL_MASK (0x7U)
#define S16UP_RX_AEQ_AEQ_TP_CTRL_TP_CTRL_SHIFT (0U)




typedef volatile struct sS16UP_RX_AEQ_RDBType {
    S16UP_RX_AEQ_AEQ_REV_ID_TYPE rev_id; /* OFFSET: 0x0 */
    S16UP_RX_AEQ_RESERVED_TYPE rsvd0[2]; /* OFFSET: 0x2 */
    S16UP_RX_AEQ_AEQ_CONTROL1_TYPE control1; /* OFFSET: 0x4 */
    S16UP_RX_AEQ_RESERVED_TYPE rsvd1[2]; /* OFFSET: 0x6 */
    S16UP_RX_AEQ_AEQ_CONTROL2_TYPE control2; /* OFFSET: 0x8 */
    S16UP_RX_AEQ_RESERVED_TYPE rsvd2[2]; /* OFFSET: 0xa */
    S16UP_RX_AEQ_AEQ_FRC_EQ_TYPE frc_eq; /* OFFSET: 0xc */
    S16UP_RX_AEQ_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0xe */
    S16UP_RX_AEQ_AEQ_FRC_OC_TYPE frc_oc; /* OFFSET: 0x10 */
    S16UP_RX_AEQ_RESERVED_TYPE rsvd4[2]; /* OFFSET: 0x12 */
    S16UP_RX_AEQ_AEQ_INIT_TYPE init; /* OFFSET: 0x14 */
    S16UP_RX_AEQ_RESERVED_TYPE rsvd5[2]; /* OFFSET: 0x16 */
    S16UP_RX_AEQ_AEQ_AEQ1_TYPE aeq1; /* OFFSET: 0x18 */
    S16UP_RX_AEQ_RESERVED_TYPE rsvd6[2]; /* OFFSET: 0x1a */
    S16UP_RX_AEQ_AEQ_AEQ2_TYPE aeq2; /* OFFSET: 0x1c */
    S16UP_RX_AEQ_RESERVED_TYPE rsvd7[2]; /* OFFSET: 0x1e */
    S16UP_RX_AEQ_AEQ_REGS_TYPE regs; /* OFFSET: 0x20 */
    S16UP_RX_AEQ_RESERVED_TYPE rsvd8[2]; /* OFFSET: 0x22 */
    S16UP_RX_AEQ_AEQ_TP_CTRL_TYPE tp_ctrl; /* OFFSET: 0x24 */
} S16UP_RX_AEQ_RDBType;


#define RX_AEQ_AFE_BASE                 (0xE04680C0UL)



#define S16UP_RX_AEQ_MAX_HW_ID          (1UL)

#endif /* S16UP_RX_AEQ_RDB_H */
