/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file s16up_u_tx_x8_status0_rdb.h
    @brief RDB File for S16UP_U_TX_X8_STATUS0

    @version BCM89580_A0_20230125_RDB
*/

#ifndef S16UP_U_TX_X8_STATUS0_RDB_H
#define S16UP_U_TX_X8_STATUS0_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t S16UP_U_TX_X8_STATUS0_UENCODE_STATUS_0_TYPE;
#define S16UP_U_TX_X8_STATUS0_UENCODE_STATUS_0_CL49_T_TYPE_CODED_MASK (0xf000U)
#define S16UP_U_TX_X8_STATUS0_UENCODE_STATUS_0_CL49_T_TYPE_CODED_SHIFT (12U)
#define S16UP_U_TX_X8_STATUS0_UENCODE_STATUS_0_CL49_TX_FAULT_DET_MASK (0x800U)
#define S16UP_U_TX_X8_STATUS0_UENCODE_STATUS_0_CL49_TX_FAULT_DET_SHIFT (11U)
#define S16UP_U_TX_X8_STATUS0_UENCODE_STATUS_0_CL49_LTXSM_STATE_MASK (0x7f8U)
#define S16UP_U_TX_X8_STATUS0_UENCODE_STATUS_0_CL49_LTXSM_STATE_SHIFT (3U)
#define S16UP_U_TX_X8_STATUS0_UENCODE_STATUS_0_CL49_TXSM_STATE_MASK (0x7U)
#define S16UP_U_TX_X8_STATUS0_UENCODE_STATUS_0_CL49_TXSM_STATE_SHIFT (0U)




typedef uint8_t S16UP_U_TX_X8_STATUS0_RESERVED_TYPE;




typedef uint16_t S16UP_U_TX_X8_STATUS0_UPCS_STATUS_TYPE;
#define S16UP_U_TX_X8_STATUS0_UPCS_STATUS_TX_LOCAL_FAULT_MASK (0x100U)
#define S16UP_U_TX_X8_STATUS0_UPCS_STATUS_TX_LOCAL_FAULT_SHIFT (8U)
#define S16UP_U_TX_X8_STATUS0_UPCS_STATUS_TX_REMOTE_FAULT_MASK (0x80U)
#define S16UP_U_TX_X8_STATUS0_UPCS_STATUS_TX_REMOTE_FAULT_SHIFT (7U)
#define S16UP_U_TX_X8_STATUS0_UPCS_STATUS_TX_LINK_INTERRUPT_MASK (0x40U)
#define S16UP_U_TX_X8_STATUS0_UPCS_STATUS_TX_LINK_INTERRUPT_SHIFT (6U)
#define S16UP_U_TX_X8_STATUS0_UPCS_STATUS_TX_LPI_RECEIVED_MASK (0x20U)
#define S16UP_U_TX_X8_STATUS0_UPCS_STATUS_TX_LPI_RECEIVED_SHIFT (5U)
#define S16UP_U_TX_X8_STATUS0_UPCS_STATUS_LINK_INTERRUPT_LH_MASK (0x10U)
#define S16UP_U_TX_X8_STATUS0_UPCS_STATUS_LINK_INTERRUPT_LH_SHIFT (4U)
#define S16UP_U_TX_X8_STATUS0_UPCS_STATUS_LOCAL_FAULT_LH_MASK (0x8U)
#define S16UP_U_TX_X8_STATUS0_UPCS_STATUS_LOCAL_FAULT_LH_SHIFT (3U)
#define S16UP_U_TX_X8_STATUS0_UPCS_STATUS_REMOTE_FAULT_LH_MASK (0x4U)
#define S16UP_U_TX_X8_STATUS0_UPCS_STATUS_REMOTE_FAULT_LH_SHIFT (2U)
#define S16UP_U_TX_X8_STATUS0_UPCS_STATUS_RESERVED_ORDERED_SET_LH_MASK (0x2U)
#define S16UP_U_TX_X8_STATUS0_UPCS_STATUS_RESERVED_ORDERED_SET_LH_SHIFT (1U)
#define S16UP_U_TX_X8_STATUS0_UPCS_STATUS_LPI_RECEIVED_LH_MASK (0x1U)
#define S16UP_U_TX_X8_STATUS0_UPCS_STATUS_LPI_RECEIVED_LH_SHIFT (0U)




typedef uint16_t S16UP_U_TX_X8_STATUS0_UCKCMP_STATUS_TYPE;
#define S16UP_U_TX_X8_STATUS0_UCKCMP_STATUS_CKCMP_MASK (0xffffU)
#define S16UP_U_TX_X8_STATUS0_UCKCMP_STATUS_CKCMP_SHIFT (0U)




typedef uint16_t S16UP_U_TX_X8_STATUS0_UURWDS_TYPE;
#define S16UP_U_TX_X8_STATUS0_UURWDS_RX_DECODE_STATE_IDLE_COL_L_MASK (0x80U)
#define S16UP_U_TX_X8_STATUS0_UURWDS_RX_DECODE_STATE_IDLE_COL_L_SHIFT (7U)
#define S16UP_U_TX_X8_STATUS0_UURWDS_RX_DECODE_STATE_DATA_COL_L_MASK (0x40U)
#define S16UP_U_TX_X8_STATUS0_UURWDS_RX_DECODE_STATE_DATA_COL_L_SHIFT (6U)
#define S16UP_U_TX_X8_STATUS0_UURWDS_RX_DECODE_STATE_SEQ_COL_L_MASK (0x20U)
#define S16UP_U_TX_X8_STATUS0_UURWDS_RX_DECODE_STATE_SEQ_COL_L_SHIFT (5U)
#define S16UP_U_TX_X8_STATUS0_UURWDS_RX_DECODE_STATE_ERR_COL_L_MASK (0x10U)
#define S16UP_U_TX_X8_STATUS0_UURWDS_RX_DECODE_STATE_ERR_COL_L_SHIFT (4U)




typedef uint16_t S16UP_U_TX_X8_STATUS0_UURTS_TYPE;
#define S16UP_U_TX_X8_STATUS0_UURTS_TURTS_MASK (0xffffU)
#define S16UP_U_TX_X8_STATUS0_UURTS_TURTS_SHIFT (0U)




typedef uint16_t S16UP_U_TX_X8_STATUS0_UMIPCL_TYPE;
#define S16UP_U_TX_X8_STATUS0_UMIPCL_T_MAC_INTF_PKT_CNT_LOW_MASK (0xffffU)
#define S16UP_U_TX_X8_STATUS0_UMIPCL_T_MAC_INTF_PKT_CNT_LOW_SHIFT (0U)




typedef uint16_t S16UP_U_TX_X8_STATUS0_UMIPCU_TYPE;
#define S16UP_U_TX_X8_STATUS0_UMIPCU_T_MAC_INTF_PKT_CNT_UP_MASK (0xffffU)
#define S16UP_U_TX_X8_STATUS0_UMIPCU_T_MAC_INTF_PKT_CNT_UP_SHIFT (0U)




typedef uint16_t S16UP_U_TX_X8_STATUS0_UMIPS0_TYPE;
#define S16UP_U_TX_X8_STATUS0_UMIPS0_T_MAC_INTF_PKT_STAT0_MASK (0xffffU)
#define S16UP_U_TX_X8_STATUS0_UMIPS0_T_MAC_INTF_PKT_STAT0_SHIFT (0U)




typedef uint16_t S16UP_U_TX_X8_STATUS0_UMIPS1_TYPE;
#define S16UP_U_TX_X8_STATUS0_UMIPS1_T_MAC_INTF_PKT_STAT1_MASK (0xffffU)
#define S16UP_U_TX_X8_STATUS0_UMIPS1_T_MAC_INTF_PKT_STAT1_SHIFT (0U)




typedef uint16_t S16UP_U_TX_X8_STATUS0_UMIPS2_TYPE;
#define S16UP_U_TX_X8_STATUS0_UMIPS2_T_MAC_INTF_PKT_STAT2_MASK (0xffffU)
#define S16UP_U_TX_X8_STATUS0_UMIPS2_T_MAC_INTF_PKT_STAT2_SHIFT (0U)




typedef uint16_t S16UP_U_TX_X8_STATUS0_UDIC_STATUS0_TYPE;
#define S16UP_U_TX_X8_STATUS0_UDIC_STATUS0_DIC_MASK (0xffffU)
#define S16UP_U_TX_X8_STATUS0_UDIC_STATUS0_DIC_SHIFT (0U)




typedef uint16_t S16UP_U_TX_X8_STATUS0_UDIC_STATUS1_TYPE;
#define S16UP_U_TX_X8_STATUS0_UDIC_STATUS1_DIC_MASK (0xffffU)
#define S16UP_U_TX_X8_STATUS0_UDIC_STATUS1_DIC_SHIFT (0U)




typedef uint16_t S16UP_U_TX_X8_STATUS0_UDIC_STATUS2_TYPE;
#define S16UP_U_TX_X8_STATUS0_UDIC_STATUS2_DIC_MASK (0xffffU)
#define S16UP_U_TX_X8_STATUS0_UDIC_STATUS2_DIC_SHIFT (0U)




typedef uint16_t S16UP_U_TX_X8_STATUS0_UMSTS_TYPE;
#define S16UP_U_TX_X8_STATUS0_UMSTS_T_MAC_SEQ_TSTMUX_MASK (0xffffU)
#define S16UP_U_TX_X8_STATUS0_UMSTS_T_MAC_SEQ_TSTMUX_SHIFT (0U)




typedef volatile struct sS16UP_U_TX_X8_STATUS0_RDBType {
    S16UP_U_TX_X8_STATUS0_UENCODE_STATUS_0_TYPE encode_status_0; /* OFFSET: 0x0 */
    S16UP_U_TX_X8_STATUS0_RESERVED_TYPE rsvd0[2]; /* OFFSET: 0x2 */
    S16UP_U_TX_X8_STATUS0_UPCS_STATUS_TYPE pcs_status; /* OFFSET: 0x4 */
    S16UP_U_TX_X8_STATUS0_RESERVED_TYPE rsvd1[2]; /* OFFSET: 0x6 */
    S16UP_U_TX_X8_STATUS0_UCKCMP_STATUS_TYPE tx_ckcmp_status; /* OFFSET: 0x8 */
    S16UP_U_TX_X8_STATUS0_RESERVED_TYPE rsvd2[2]; /* OFFSET: 0xa */
    S16UP_U_TX_X8_STATUS0_UURWDS_TYPE t_usxgmii_replicate_word_decode_status; /* OFFSET: 0xc */
    S16UP_U_TX_X8_STATUS0_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0xe */
    S16UP_U_TX_X8_STATUS0_UURTS_TYPE t_usxgmii_replicate_tstmux_status; /* OFFSET: 0x10 */
    S16UP_U_TX_X8_STATUS0_RESERVED_TYPE rsvd4[2]; /* OFFSET: 0x12 */
    S16UP_U_TX_X8_STATUS0_UMIPCL_TYPE t_mac_intf_pkt_cnt_low; /* OFFSET: 0x14 */
    S16UP_U_TX_X8_STATUS0_RESERVED_TYPE rsvd5[2]; /* OFFSET: 0x16 */
    S16UP_U_TX_X8_STATUS0_UMIPCU_TYPE t_mac_intf_pkt_cnt_up; /* OFFSET: 0x18 */
    S16UP_U_TX_X8_STATUS0_RESERVED_TYPE rsvd6[2]; /* OFFSET: 0x1a */
    S16UP_U_TX_X8_STATUS0_UMIPS0_TYPE t_mac_intf_pkt_stat0; /* OFFSET: 0x1c */
    S16UP_U_TX_X8_STATUS0_RESERVED_TYPE rsvd7[2]; /* OFFSET: 0x1e */
    S16UP_U_TX_X8_STATUS0_UMIPS1_TYPE t_mac_intf_pkt_stat1; /* OFFSET: 0x20 */
    S16UP_U_TX_X8_STATUS0_RESERVED_TYPE rsvd8[2]; /* OFFSET: 0x22 */
    S16UP_U_TX_X8_STATUS0_UMIPS2_TYPE t_mac_intf_pkt_stat2; /* OFFSET: 0x24 */
    S16UP_U_TX_X8_STATUS0_RESERVED_TYPE rsvd9[2]; /* OFFSET: 0x26 */
    S16UP_U_TX_X8_STATUS0_UDIC_STATUS0_TYPE dic_status0; /* OFFSET: 0x28 */
    S16UP_U_TX_X8_STATUS0_RESERVED_TYPE rsvd10[2]; /* OFFSET: 0x2a */
    S16UP_U_TX_X8_STATUS0_UDIC_STATUS1_TYPE dic_status1; /* OFFSET: 0x2c */
    S16UP_U_TX_X8_STATUS0_RESERVED_TYPE rsvd11[2]; /* OFFSET: 0x2e */
    S16UP_U_TX_X8_STATUS0_UDIC_STATUS2_TYPE dic_status2; /* OFFSET: 0x30 */
    S16UP_U_TX_X8_STATUS0_RESERVED_TYPE rsvd12[2]; /* OFFSET: 0x32 */
    S16UP_U_TX_X8_STATUS0_UMSTS_TYPE t_mac_seq_tstmux_status; /* OFFSET: 0x34 */
} S16UP_U_TX_X8_STATUS0_RDBType;


#define U_TX_X8_STATUS0_BASE            (0xE04F1900UL)



#define S16UP_U_TX_X8_STATUS0_MAX_HW_ID  (1UL)

#endif /* S16UP_U_TX_X8_STATUS0_RDB_H */
