/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file s16up_u_an_x8_usxgmii_rdb.h
    @brief RDB File for S16UP_U_AN_X8_USXGMII

    @version BCM89580_A0_20230125_RDB
*/

#ifndef S16UP_U_AN_X8_USXGMII_RDB_H
#define S16UP_U_AN_X8_USXGMII_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t S16UP_U_AN_X8_USXGMII_UATC_TYPE;
#define S16UP_U_AN_X8_USXGMII_UATC_LINK_MASK (0x8000U)
#define S16UP_U_AN_X8_USXGMII_UATC_LINK_SHIFT (15U)
#define S16UP_U_AN_X8_USXGMII_UATC_ACKNOWLEGE_MASK (0x4000U)
#define S16UP_U_AN_X8_USXGMII_UATC_ACKNOWLEGE_SHIFT (14U)
#define S16UP_U_AN_X8_USXGMII_UATC_DUPLEX_MASK (0x1000U)
#define S16UP_U_AN_X8_USXGMII_UATC_DUPLEX_SHIFT (12U)
#define S16UP_U_AN_X8_USXGMII_UATC_SPEED_MASK (0xe00U)
#define S16UP_U_AN_X8_USXGMII_UATC_SPEED_SHIFT (9U)
#define S16UP_U_AN_X8_USXGMII_UATC_EEE_CAPABILITY_MASK (0x100U)
#define S16UP_U_AN_X8_USXGMII_UATC_EEE_CAPABILITY_SHIFT (8U)
#define S16UP_U_AN_X8_USXGMII_UATC_EEE_CLOCK_STOP_CAPABILITY_MASK (0x80U)
#define S16UP_U_AN_X8_USXGMII_UATC_EEE_CLOCK_STOP_CAPABILITY_SHIFT (7U)
#define S16UP_U_AN_X8_USXGMII_UATC_SGMII_MASK (0x1U)
#define S16UP_U_AN_X8_USXGMII_UATC_SGMII_SHIFT (0U)




typedef uint8_t S16UP_U_AN_X8_USXGMII_RESERVED_TYPE;




typedef uint16_t S16UP_U_AN_X8_USXGMII_UAC0_TYPE;
#define S16UP_U_AN_X8_USXGMII_UAC0_TX_LF_MDI_LINKDOWN_MASK (0x8000U)
#define S16UP_U_AN_X8_USXGMII_UAC0_TX_LF_MDI_LINKDOWN_SHIFT (15U)
#define S16UP_U_AN_X8_USXGMII_UAC0_SPD_SWITCH_OV_EN_MASK (0x4000U)
#define S16UP_U_AN_X8_USXGMII_UAC0_SPD_SWITCH_OV_EN_SHIFT (14U)
#define S16UP_U_AN_X8_USXGMII_UAC0_SPD_SWITCH_OV_MASK (0x2000U)
#define S16UP_U_AN_X8_USXGMII_UAC0_SPD_SWITCH_OV_SHIFT (13U)
#define S16UP_U_AN_X8_USXGMII_UAC0_RESTART_AN_MASK (0x1000U)
#define S16UP_U_AN_X8_USXGMII_UAC0_RESTART_AN_SHIFT (12U)
#define S16UP_U_AN_X8_USXGMII_UAC0_DISABLE_RUDI_INVALID_MASK (0x800U)
#define S16UP_U_AN_X8_USXGMII_UAC0_DISABLE_RUDI_INVALID_SHIFT (11U)
#define S16UP_U_AN_X8_USXGMII_UAC0_ENABLE_LPI_IDLE_MATCH_MASK (0x400U)
#define S16UP_U_AN_X8_USXGMII_UAC0_ENABLE_LPI_IDLE_MATCH_SHIFT (10U)
#define S16UP_U_AN_X8_USXGMII_UAC0_ENABLE_LINKDOWN_RESTART_MASK (0x200U)
#define S16UP_U_AN_X8_USXGMII_UAC0_ENABLE_LINKDOWN_RESTART_SHIFT (9U)
#define S16UP_U_AN_X8_USXGMII_UAC0_CHECK_USXGMII_SELECTOR_MASK (0x100U)
#define S16UP_U_AN_X8_USXGMII_UAC0_CHECK_USXGMII_SELECTOR_SHIFT (8U)
#define S16UP_U_AN_X8_USXGMII_UAC0_ANERR_TIMER_EN_MASK (0x80U)
#define S16UP_U_AN_X8_USXGMII_UAC0_ANERR_TIMER_EN_SHIFT (7U)
#define S16UP_U_AN_X8_USXGMII_UAC0_AN_FAST_TIMER_MASK (0x40U)
#define S16UP_U_AN_X8_USXGMII_UAC0_AN_FAST_TIMER_SHIFT (6U)
#define S16UP_U_AN_X8_USXGMII_UAC0_FILTER_FORCED_LINK_MASK (0x20U)
#define S16UP_U_AN_X8_USXGMII_UAC0_FILTER_FORCED_LINK_SHIFT (5U)
#define S16UP_U_AN_X8_USXGMII_UAC0_LANE_STATUS_SEL_ENABLE_MASK (0x10U)
#define S16UP_U_AN_X8_USXGMII_UAC0_LANE_STATUS_SEL_ENABLE_SHIFT (4U)
#define S16UP_U_AN_X8_USXGMII_UAC0_PORT_LINK_STATUS_DELAY_EN_MASK (0x8U)
#define S16UP_U_AN_X8_USXGMII_UAC0_PORT_LINK_STATUS_DELAY_EN_SHIFT (3U)
#define S16UP_U_AN_X8_USXGMII_UAC0_FORCE_XMIT_DATA_MASK (0x4U)
#define S16UP_U_AN_X8_USXGMII_UAC0_FORCE_XMIT_DATA_SHIFT (2U)
#define S16UP_U_AN_X8_USXGMII_UAC0_USXGMII_AN_ENABLE_MASK (0x2U)
#define S16UP_U_AN_X8_USXGMII_UAC0_USXGMII_AN_ENABLE_SHIFT (1U)
#define S16UP_U_AN_X8_USXGMII_UAC0_USXGMII_MODE_MASK (0x1U)
#define S16UP_U_AN_X8_USXGMII_UAC0_USXGMII_MODE_SHIFT (0U)




typedef uint16_t S16UP_U_AN_X8_USXGMII_UAC1_TYPE;
#define S16UP_U_AN_X8_USXGMII_UAC1_RX_CLK_VLD_AN_ENABLE_MASK (0x8000U)
#define S16UP_U_AN_X8_USXGMII_UAC1_RX_CLK_VLD_AN_ENABLE_SHIFT (15U)
#define S16UP_U_AN_X8_USXGMII_UAC1_TX_CLK_VLD_AN_ENABLE_MASK (0x4000U)
#define S16UP_U_AN_X8_USXGMII_UAC1_TX_CLK_VLD_AN_ENABLE_SHIFT (14U)
#define S16UP_U_AN_X8_USXGMII_UAC1_CHECK_USXGMIICHANINFO_MASK (0x2000U)
#define S16UP_U_AN_X8_USXGMII_UAC1_CHECK_USXGMIICHANINFO_SHIFT (13U)
#define S16UP_U_AN_X8_USXGMII_UAC1_USXGMII_AN_SWITCH_OV_EN_MASK (0x1000U)
#define S16UP_U_AN_X8_USXGMII_UAC1_USXGMII_AN_SWITCH_OV_EN_SHIFT (12U)
#define S16UP_U_AN_X8_USXGMII_UAC1_USXGMII_AN_IDLE_OV_MASK (0x800U)
#define S16UP_U_AN_X8_USXGMII_UAC1_USXGMII_AN_IDLE_OV_SHIFT (11U)
#define S16UP_U_AN_X8_USXGMII_UAC1_USXGMII_AN_CONFIG_OV_MASK (0x400U)
#define S16UP_U_AN_X8_USXGMII_UAC1_USXGMII_AN_CONFIG_OV_SHIFT (10U)
#define S16UP_U_AN_X8_USXGMII_UAC1_USXGMII_MASTER_MODE_MASK (0x200U)
#define S16UP_U_AN_X8_USXGMII_UAC1_USXGMII_MASTER_MODE_SHIFT (9U)
#define S16UP_U_AN_X8_USXGMII_UAC1_USXGMII_EXT_SEL_MASK (0x100U)
#define S16UP_U_AN_X8_USXGMII_UAC1_USXGMII_EXT_SEL_SHIFT (8U)
#define S16UP_U_AN_X8_USXGMII_UAC1_FORCE_SEQUENCE_TX_EN_MASK (0x80U)
#define S16UP_U_AN_X8_USXGMII_UAC1_FORCE_SEQUENCE_TX_EN_SHIFT (7U)
#define S16UP_U_AN_X8_USXGMII_UAC1_FORCE_SEQUENCE_TX_SEL_MASK (0x78U)
#define S16UP_U_AN_X8_USXGMII_UAC1_FORCE_SEQUENCE_TX_SEL_SHIFT (3U)
#define S16UP_U_AN_X8_USXGMII_UAC1_SLAVE_CONFIG_OV_MASK (0x4U)
#define S16UP_U_AN_X8_USXGMII_UAC1_SLAVE_CONFIG_OV_SHIFT (2U)
#define S16UP_U_AN_X8_USXGMII_UAC1_LINESIDE_LINK_HW_OV_EN_MASK (0x2U)
#define S16UP_U_AN_X8_USXGMII_UAC1_LINESIDE_LINK_HW_OV_EN_SHIFT (1U)
#define S16UP_U_AN_X8_USXGMII_UAC1_LINESIDE_LINK_HW_OV_MASK (0x1U)
#define S16UP_U_AN_X8_USXGMII_UAC1_LINESIDE_LINK_HW_OV_SHIFT (0U)




typedef uint16_t S16UP_U_AN_X8_USXGMII_UAC2_TYPE;
#define S16UP_U_AN_X8_USXGMII_UAC2_USXGMII_SW_AN_ENABLE_MASK (0x1000U)
#define S16UP_U_AN_X8_USXGMII_UAC2_USXGMII_SW_AN_ENABLE_SHIFT (12U)
#define S16UP_U_AN_X8_USXGMII_UAC2_USXGMII_AN_FRC_SEL_MASK (0x800U)
#define S16UP_U_AN_X8_USXGMII_UAC2_USXGMII_AN_FRC_SEL_SHIFT (11U)
#define S16UP_U_AN_X8_USXGMII_UAC2_TX_CLK_VLD_DELAY_EN_MASK (0x400U)
#define S16UP_U_AN_X8_USXGMII_UAC2_TX_CLK_VLD_DELAY_EN_SHIFT (10U)
#define S16UP_U_AN_X8_USXGMII_UAC2_RX_CLK_VLD_DELAY_EN_MASK (0x200U)
#define S16UP_U_AN_X8_USXGMII_UAC2_RX_CLK_VLD_DELAY_EN_SHIFT (9U)
#define S16UP_U_AN_X8_USXGMII_UAC2_TX_CLK_VLD_OV_EN_MASK (0x100U)
#define S16UP_U_AN_X8_USXGMII_UAC2_TX_CLK_VLD_OV_EN_SHIFT (8U)
#define S16UP_U_AN_X8_USXGMII_UAC2_TX_CLK_VLD_OV_MASK (0x80U)
#define S16UP_U_AN_X8_USXGMII_UAC2_TX_CLK_VLD_OV_SHIFT (7U)
#define S16UP_U_AN_X8_USXGMII_UAC2_RX_CLK_VLD_OV_EN_MASK (0x40U)
#define S16UP_U_AN_X8_USXGMII_UAC2_RX_CLK_VLD_OV_EN_SHIFT (6U)
#define S16UP_U_AN_X8_USXGMII_UAC2_RX_CLK_VLD_OV_MASK (0x20U)
#define S16UP_U_AN_X8_USXGMII_UAC2_RX_CLK_VLD_OV_SHIFT (5U)
#define S16UP_U_AN_X8_USXGMII_UAC2_CL36_EN_LATENCY_MODE_MASK (0x3U)
#define S16UP_U_AN_X8_USXGMII_UAC2_CL36_EN_LATENCY_MODE_SHIFT (0U)




typedef uint16_t S16UP_U_AN_X8_USXGMII_UAC3_TYPE;
#define S16UP_U_AN_X8_USXGMII_UAC3_USXGMII_CLK_VLD_NATIVE_LINK_MASK (0x40U)
#define S16UP_U_AN_X8_USXGMII_UAC3_USXGMII_CLK_VLD_NATIVE_LINK_SHIFT (6U)
#define S16UP_U_AN_X8_USXGMII_UAC3_PORT_LINK_DELAY_MAX_CNT_MASK (0x3fU)
#define S16UP_U_AN_X8_USXGMII_UAC3_PORT_LINK_DELAY_MAX_CNT_SHIFT (0U)




typedef uint16_t S16UP_U_AN_X8_USXGMII_USXGMII_MR_BP_STATUS_TYPE;
#define S16UP_U_AN_X8_USXGMII_USXGMII_MR_BP_STATUS_MASK (0xffffU)
#define S16UP_U_AN_X8_USXGMII_USXGMII_MR_BP_STATUS_SHIFT (0U)




typedef uint16_t S16UP_U_AN_X8_USXGMII_UMLAAS_TYPE;
#define S16UP_U_AN_X8_USXGMII_UMLAAS_MR_LP_ADV_ABILITY_MASK (0xffffU)
#define S16UP_U_AN_X8_USXGMII_UMLAAS_MR_LP_ADV_ABILITY_SHIFT (0U)




typedef uint16_t S16UP_U_AN_X8_USXGMII_USXGMII_STATUS0_TYPE;
#define S16UP_U_AN_X8_USXGMII_USXGMII_STATUS0_MASK (0xffffU)
#define S16UP_U_AN_X8_USXGMII_USXGMII_STATUS0_SHIFT (0U)




typedef uint16_t S16UP_U_AN_X8_USXGMII_USXGMII_STATUS1_TYPE;
#define S16UP_U_AN_X8_USXGMII_USXGMII_STATUS1_MASK (0xffffU)
#define S16UP_U_AN_X8_USXGMII_USXGMII_STATUS1_SHIFT (0U)




typedef uint16_t S16UP_U_AN_X8_USXGMII_USXGMII_STATUS2_TYPE;
#define S16UP_U_AN_X8_USXGMII_USXGMII_STATUS2_MASK (0xffffU)
#define S16UP_U_AN_X8_USXGMII_USXGMII_STATUS2_SHIFT (0U)




typedef uint16_t S16UP_U_AN_X8_USXGMII_USXGMII_STATUS3_TYPE;
#define S16UP_U_AN_X8_USXGMII_USXGMII_STATUS3_MASK (0xffffU)
#define S16UP_U_AN_X8_USXGMII_USXGMII_STATUS3_SHIFT (0U)




typedef uint16_t S16UP_U_AN_X8_USXGMII_USRP_TYPE;
#define S16UP_U_AN_X8_USXGMII_USRP_SW_RESOLVE_PAGE_MASK (0xffffU)
#define S16UP_U_AN_X8_USXGMII_USRP_SW_RESOLVE_PAGE_SHIFT (0U)




typedef volatile struct sS16UP_U_AN_X8_USXGMII_RDBType {
    S16UP_U_AN_X8_USXGMII_UATC_TYPE an_config; /* OFFSET: 0x0 */
    S16UP_U_AN_X8_USXGMII_RESERVED_TYPE rsvd0[2]; /* OFFSET: 0x2 */
    S16UP_U_AN_X8_USXGMII_UAC0_TYPE an_control0; /* OFFSET: 0x4 */
    S16UP_U_AN_X8_USXGMII_RESERVED_TYPE rsvd1[2]; /* OFFSET: 0x6 */
    S16UP_U_AN_X8_USXGMII_UAC1_TYPE an_control1; /* OFFSET: 0x8 */
    S16UP_U_AN_X8_USXGMII_RESERVED_TYPE rsvd2[2]; /* OFFSET: 0xa */
    S16UP_U_AN_X8_USXGMII_UAC2_TYPE an_control2; /* OFFSET: 0xc */
    S16UP_U_AN_X8_USXGMII_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0xe */
    S16UP_U_AN_X8_USXGMII_UAC3_TYPE an_control3; /* OFFSET: 0x10 */
    S16UP_U_AN_X8_USXGMII_RESERVED_TYPE rsvd4[6]; /* OFFSET: 0x12 */
    S16UP_U_AN_X8_USXGMII_USXGMII_MR_BP_STATUS_TYPE mr_bp_status; /* OFFSET: 0x18 */
    S16UP_U_AN_X8_USXGMII_RESERVED_TYPE rsvd5[2]; /* OFFSET: 0x1a */
    S16UP_U_AN_X8_USXGMII_UMLAAS_TYPE mr_lp_adv_ability_status; /* OFFSET: 0x1c */
    S16UP_U_AN_X8_USXGMII_RESERVED_TYPE rsvd6[2]; /* OFFSET: 0x1e */
    S16UP_U_AN_X8_USXGMII_USXGMII_STATUS0_TYPE status0; /* OFFSET: 0x20 */
    S16UP_U_AN_X8_USXGMII_RESERVED_TYPE rsvd7[2]; /* OFFSET: 0x22 */
    S16UP_U_AN_X8_USXGMII_USXGMII_STATUS1_TYPE status1; /* OFFSET: 0x24 */
    S16UP_U_AN_X8_USXGMII_RESERVED_TYPE rsvd8[2]; /* OFFSET: 0x26 */
    S16UP_U_AN_X8_USXGMII_USXGMII_STATUS2_TYPE status2; /* OFFSET: 0x28 */
    S16UP_U_AN_X8_USXGMII_RESERVED_TYPE rsvd9[2]; /* OFFSET: 0x2a */
    S16UP_U_AN_X8_USXGMII_USXGMII_STATUS3_TYPE status3; /* OFFSET: 0x2c */
    S16UP_U_AN_X8_USXGMII_RESERVED_TYPE rsvd10[2]; /* OFFSET: 0x2e */
    S16UP_U_AN_X8_USXGMII_USRP_TYPE sw_resolve_page; /* OFFSET: 0x30 */
} S16UP_U_AN_X8_USXGMII_RDBType;


#define U_AN_X8_USXGMII_BASE            (0xE04F1300UL)



#define S16UP_U_AN_X8_USXGMII_MAX_HW_ID  (1UL)

#endif /* S16UP_U_AN_X8_USXGMII_RDB_H */
