/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file s16up_rx_pcs_rdb.h
    @brief RDB File for S16UP_RX_PCS

    @version BCM89580_A0_20230125_RDB
*/

#ifndef S16UP_RX_PCS_RDB_H
#define S16UP_RX_PCS_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t S16UP_RX_PCS_RX_STATUS_TYPE;
#define S16UP_RX_PCS_RX_STATUS_CX4_SIGDET_MASK (0x8000U)
#define S16UP_RX_PCS_RX_STATUS_CX4_SIGDET_SHIFT (15U)
#define S16UP_RX_PCS_RX_STATUS_RXSEQDONE_MASK (0x1000U)
#define S16UP_RX_PCS_RX_STATUS_RXSEQDONE_SHIFT (12U)
#define S16UP_RX_PCS_RX_STATUS_RX_SIGDET_LL_MASK (0x800U)
#define S16UP_RX_PCS_RX_STATUS_RX_SIGDET_LL_SHIFT (11U)
#define S16UP_RX_PCS_RX_STATUS_CS4_SIGDET_LL_MASK (0x400U)
#define S16UP_RX_PCS_RX_STATUS_CS4_SIGDET_LL_SHIFT (10U)
#define S16UP_RX_PCS_RX_STATUS_RX_RESET_MASK (0x200U)
#define S16UP_RX_PCS_RX_STATUS_RX_RESET_SHIFT (9U)
#define S16UP_RX_PCS_RX_STATUS_RX_PWRDN_MASK (0x100U)
#define S16UP_RX_PCS_RX_STATUS_RX_PWRDN_SHIFT (8U)

#if 0
#define S16UP_RX_PCS_RX_STATUS_TEST_ACQ_EN_MASK (0x400U)
#define S16UP_RX_PCS_RX_STATUS_TEST_ACQ_EN_SHIFT (10U)
#define S16UP_RX_PCS_RX_STATUS_RXSEQSTART_MASK (0x100U)
#define S16UP_RX_PCS_RX_STATUS_RXSEQSTART_SHIFT (8U)
#define S16UP_RX_PCS_RX_STATUS_MUX_COMADJ_SYNC_STATUS_MASK (0x80U)
#define S16UP_RX_PCS_RX_STATUS_MUX_COMADJ_SYNC_STATUS_SHIFT (7U)
#define S16UP_RX_PCS_RX_STATUS_SYNC_STATUS_MASK (0x40U)
#define S16UP_RX_PCS_RX_STATUS_SYNC_STATUS_SHIFT (6U)
#define S16UP_RX_PCS_RX_STATUS_RX_SIGDET_MASK (0x20U)
#define S16UP_RX_PCS_RX_STATUS_RX_SIGDET_SHIFT (5U)
#define S16UP_RX_PCS_RX_STATUS_SATURATE_STATUS_MASK (0x4U)
#define S16UP_RX_PCS_RX_STATUS_SATURATE_STATUS_SHIFT (2U)
#define S16UP_RX_PCS_RX_STATUS_CX4_SIGDET_MASK (0x2U)
#define S16UP_RX_PCS_RX_STATUS_CX4_SIGDET_SHIFT (1U)
#define S16UP_RX_PCS_RX_STATUS_RXSEQDONE_MASK (0x1U)
#define S16UP_RX_PCS_RX_STATUS_RXSEQDONE_SHIFT (0U)
#define S16UP_RX_PCS_RX_STATUS_INDCK_MODE_EN_MASK (0x200U)
#define S16UP_RX_PCS_RX_STATUS_INDCK_MODE_EN_SHIFT (9U)
#define S16UP_RX_PCS_RX_STATUS_PCI_MODE_EN_MASK (0x100U)
#define S16UP_RX_PCS_RX_STATUS_PCI_MODE_EN_SHIFT (8U)
#define S16UP_RX_PCS_RX_STATUS_RX_POLARITY_MASK (0x80U)
#define S16UP_RX_PCS_RX_STATUS_RX_POLARITY_SHIFT (7U)
#define S16UP_RX_PCS_RX_STATUS_RXPOL_FLIP_MASK (0x40U)
#define S16UP_RX_PCS_RX_STATUS_RXPOL_FLIP_SHIFT (6U)
#define S16UP_RX_PCS_RX_STATUS_COMMA_MASK_MASK (0x20U)
#define S16UP_RX_PCS_RX_STATUS_COMMA_MASK_SHIFT (5U)
#define S16UP_RX_PCS_RX_STATUS_LINK_EN_R_MASK (0x10U)
#define S16UP_RX_PCS_RX_STATUS_LINK_EN_R_SHIFT (4U)
#define S16UP_RX_PCS_RX_STATUS_COMMA_ADJ_EN_MASK (0x8U)
#define S16UP_RX_PCS_RX_STATUS_COMMA_ADJ_EN_SHIFT (3U)
#define S16UP_RX_PCS_RX_STATUS_COMMA_ADJ_EN_EXT_MASK (0x4U)
#define S16UP_RX_PCS_RX_STATUS_COMMA_ADJ_EN_EXT_SHIFT (2U)
#define S16UP_RX_PCS_RX_STATUS_CDRACQDONE_R2_MASK (0x10U)
#define S16UP_RX_PCS_RX_STATUS_CDRACQDONE_R2_SHIFT (4U)
#define S16UP_RX_PCS_RX_STATUS_FREQ_SEL_PC_MASK (0x8U)
#define S16UP_RX_PCS_RX_STATUS_FREQ_SEL_PC_SHIFT (3U)
#define S16UP_RX_PCS_RX_STATUS_FREQ_SEL_SM_MASK (0x4U)
#define S16UP_RX_PCS_RX_STATUS_FREQ_SEL_SM_SHIFT (2U)
#define S16UP_RX_PCS_RX_STATUS_INTEG_MODE_SM_MASK (0x3U)
#define S16UP_RX_PCS_RX_STATUS_INTEG_MODE_SM_SHIFT (0U)
#define S16UP_RX_PCS_RX_STATUS_PROP_SCALE_MASK (0xf000U)
#define S16UP_RX_PCS_RX_STATUS_PROP_SCALE_SHIFT (12U)
#define S16UP_RX_PCS_RX_STATUS_INTEG_SCALE_MASK (0xf00U)
#define S16UP_RX_PCS_RX_STATUS_INTEG_SCALE_SHIFT (8U)
#define S16UP_RX_PCS_RX_STATUS_PROP_SCALE_ACQ_MASK (0xf0U)
#define S16UP_RX_PCS_RX_STATUS_PROP_SCALE_ACQ_SHIFT (4U)
#define S16UP_RX_PCS_RX_STATUS_INTEG_SCALE_ACQ_MASK (0xfU)
#define S16UP_RX_PCS_RX_STATUS_INTEG_SCALE_ACQ_SHIFT (0U)
#define S16UP_RX_PCS_RX_STATUS_RXMUXCKSEL_MASK (0x40U)
#define S16UP_RX_PCS_RX_STATUS_RXMUXCKSEL_SHIFT (6U)
#define S16UP_RX_PCS_RX_STATUS_GLPBK_COMBO_MASK (0x20U)
#define S16UP_RX_PCS_RX_STATUS_GLPBK_COMBO_SHIFT (5U)
#define S16UP_RX_PCS_RX_STATUS_CLOCKSWITCHSEL_MASK (0x10U)
#define S16UP_RX_PCS_RX_STATUS_CLOCKSWITCHSEL_SHIFT (4U)
#define S16UP_RX_PCS_RX_STATUS_RXCK_TST_MASK (0x8U)
#define S16UP_RX_PCS_RX_STATUS_RXCK_TST_SHIFT (3U)
#define S16UP_RX_PCS_RX_STATUS_RXCK_I_MASK (0x4U)
#define S16UP_RX_PCS_RX_STATUS_RXCK_I_SHIFT (2U)
#define S16UP_RX_PCS_RX_STATUS_REFCLK_MASK (0x2U)
#define S16UP_RX_PCS_RX_STATUS_REFCLK_SHIFT (1U)
#define S16UP_RX_PCS_RX_STATUS_PLL_BYPASS_MASK (0x1U)
#define S16UP_RX_PCS_RX_STATUS_PLL_BYPASS_SHIFT (0U)
#define S16UP_RX_PCS_RX_STATUS_RXMUXCKSEL_MASK (0x20U)
#define S16UP_RX_PCS_RX_STATUS_RXMUXCKSEL_SHIFT (5U)
#define S16UP_RX_PCS_RX_STATUS_RXSEQSTART_MASK (0x10U)
#define S16UP_RX_PCS_RX_STATUS_RXSEQSTART_SHIFT (4U)
#define S16UP_RX_PCS_RX_STATUS_RXSEQDONE_MASK (0x1U)
#define S16UP_RX_PCS_RX_STATUS_RXSEQDONE_SHIFT (0U)
#define S16UP_RX_PCS_RX_STATUS_RXSEQSTART_MASK (0x8U)
#define S16UP_RX_PCS_RX_STATUS_RXSEQSTART_SHIFT (3U)
#define S16UP_RX_PCS_RX_STATUS_ALLOW_INCREMENT_PC_MASK (0x1U)
#define S16UP_RX_PCS_RX_STATUS_ALLOW_INCREMENT_PC_SHIFT (0U)
#define S16UP_RX_PCS_RX_STATUS_RX_PWRDN_MASK (0x80U)
#define S16UP_RX_PCS_RX_STATUS_RX_PWRDN_SHIFT (7U)
#define S16UP_RX_PCS_RX_STATUS_FREQ_SEL_MASK (0x40U)
#define S16UP_RX_PCS_RX_STATUS_FREQ_SEL_SHIFT (6U)
#define S16UP_RX_PCS_RX_STATUS_PLL_LOCK_RSTB_MASK (0x20U)
#define S16UP_RX_PCS_RX_STATUS_PLL_LOCK_RSTB_SHIFT (5U)
#define S16UP_RX_PCS_RX_STATUS_PWRDN_MASK (0x10U)
#define S16UP_RX_PCS_RX_STATUS_PWRDN_SHIFT (4U)
#define S16UP_RX_PCS_RX_STATUS_RX_RESET_MASK (0x10U)
#define S16UP_RX_PCS_RX_STATUS_RX_RESET_SHIFT (4U)
#define S16UP_RX_PCS_RX_STATUS_RX_PWRDN_MASK (0x8U)
#define S16UP_RX_PCS_RX_STATUS_RX_PWRDN_SHIFT (3U)
#define S16UP_RX_PCS_RX_STATUS_RESET_ANLG_MASK (0x4U)
#define S16UP_RX_PCS_RX_STATUS_RESET_ANLG_SHIFT (2U)
#define S16UP_RX_PCS_RX_STATUS_PWRDN_RX_MASK (0x2U)
#define S16UP_RX_PCS_RX_STATUS_PWRDN_RX_SHIFT (1U)
#define S16UP_RX_PCS_RX_STATUS_PWRDN_PLL_MASK (0x1U)
#define S16UP_RX_PCS_RX_STATUS_PWRDN_PLL_SHIFT (0U)
#define S16UP_RX_PCS_RX_STATUS_RXCK0_EVEN_MASK (0x10U)
#define S16UP_RX_PCS_RX_STATUS_RXCK0_EVEN_SHIFT (4U)
#define S16UP_RX_PCS_RX_STATUS_RXCK1_EVEN_MASK (0x8U)
#define S16UP_RX_PCS_RX_STATUS_RXCK1_EVEN_SHIFT (3U)
#define S16UP_RX_PCS_RX_STATUS_COMDET_EVEN_MASK (0x4U)
#define S16UP_RX_PCS_RX_STATUS_COMDET_EVEN_SHIFT (2U)
#define S16UP_RX_PCS_RX_STATUS_EN_CDET_EVEN_MASK (0x2U)
#define S16UP_RX_PCS_RX_STATUS_EN_CDET_EVEN_SHIFT (1U)
#define S16UP_RX_PCS_RX_STATUS_COMMA_ADJ_EN_EVEN_MASK (0x1U)
#define S16UP_RX_PCS_RX_STATUS_COMMA_ADJ_EN_EVEN_SHIFT (0U)
#define S16UP_RX_PCS_RX_STATUS_RXCK0_ODD_MASK (0x10U)
#define S16UP_RX_PCS_RX_STATUS_RXCK0_ODD_SHIFT (4U)
#define S16UP_RX_PCS_RX_STATUS_RXCK1_ODD_MASK (0x8U)
#define S16UP_RX_PCS_RX_STATUS_RXCK1_ODD_SHIFT (3U)
#define S16UP_RX_PCS_RX_STATUS_COMDET_ODD_MASK (0x4U)
#define S16UP_RX_PCS_RX_STATUS_COMDET_ODD_SHIFT (2U)
#define S16UP_RX_PCS_RX_STATUS_EN_CDET_ODD_MASK (0x2U)
#define S16UP_RX_PCS_RX_STATUS_EN_CDET_ODD_SHIFT (1U)
#define S16UP_RX_PCS_RX_STATUS_COMMA_ADJ_EN_ODD_MASK (0x1U)
#define S16UP_RX_PCS_RX_STATUS_COMMA_ADJ_EN_ODD_SHIFT (0U)
#define S16UP_RX_PCS_RX_STATUS_SIGDET_MASK (0x1U)
#define S16UP_RX_PCS_RX_STATUS_SIGDET_SHIFT (0U)
#define S16UP_RX_PCS_RX_STATUS_PRBS_EN_MASK (0x40U)
#define S16UP_RX_PCS_RX_STATUS_PRBS_EN_SHIFT (6U)
#define S16UP_RX_PCS_RX_STATUS_RSTB_TST_MASK (0x20U)
#define S16UP_RX_PCS_RX_STATUS_RSTB_TST_SHIFT (5U)
#define S16UP_RX_PCS_RX_STATUS_PRBS_STATE_MASK (0xfU)
#define S16UP_RX_PCS_RX_STATUS_PRBS_STATE_SHIFT (0U)
#define S16UP_RX_PCS_RX_STATUS_ENABLE4_MASK (0x20U)
#define S16UP_RX_PCS_RX_STATUS_ENABLE4_SHIFT (5U)
#define S16UP_RX_PCS_RX_STATUS_RADR_TEST_MASK (0x1fU)
#define S16UP_RX_PCS_RX_STATUS_RADR_TEST_SHIFT (0U)
#define S16UP_RX_PCS_RX_STATUS_WADR_TEST_MASK (0x1fU)
#define S16UP_RX_PCS_RX_STATUS_WADR_TEST_SHIFT (0U)
#define S16UP_RX_PCS_RX_STATUS_RXCK_66B_TMUX_MASK (0x20U)
#define S16UP_RX_PCS_RX_STATUS_RXCK_66B_TMUX_SHIFT (5U)
#define S16UP_RX_PCS_RX_STATUS_RSTB_66B_MASK (0x10U)
#define S16UP_RX_PCS_RX_STATUS_RSTB_66B_SHIFT (4U)
#define S16UP_RX_PCS_RX_STATUS_PRSTB_66B_MUX_MASK (0x8U)
#define S16UP_RX_PCS_RX_STATUS_PRSTB_66B_MUX_SHIFT (3U)
#define S16UP_RX_PCS_RX_STATUS_RXCK_I66_TMUX_MASK (0x4U)
#define S16UP_RX_PCS_RX_STATUS_RXCK_I66_TMUX_SHIFT (2U)
#define S16UP_RX_PCS_RX_STATUS_RSTB_I66_MASK (0x2U)
#define S16UP_RX_PCS_RX_STATUS_RSTB_I66_SHIFT (1U)
#define S16UP_RX_PCS_RX_STATUS_PRSTB_I66_MUX_MASK (0x1U)
#define S16UP_RX_PCS_RX_STATUS_PRSTB_I66_MUX_SHIFT (0U)
#define S16UP_RX_PCS_RX_STATUS_RFIFO_ERROR_R_MASK (0xcU)
#define S16UP_RX_PCS_RX_STATUS_RFIFO_ERROR_R_SHIFT (2U)
#define S16UP_RX_PCS_RX_STATUS_RFIFO_UNFLOW_MASK (0x2U)
#define S16UP_RX_PCS_RX_STATUS_RFIFO_UNFLOW_SHIFT (1U)
#define S16UP_RX_PCS_RX_STATUS_RFIFO_OVFLOW_MASK (0x1U)
#define S16UP_RX_PCS_RX_STATUS_RFIFO_OVFLOW_SHIFT (0U)
#define S16UP_RX_PCS_RX_STATUS_INTEG_STATUS_MASK (0xffffU)
#define S16UP_RX_PCS_RX_STATUS_INTEG_STATUS_SHIFT (0U)
#define S16UP_RX_PCS_RX_STATUS_VCO_STATUS_MASK (0xffffU)
#define S16UP_RX_PCS_RX_STATUS_VCO_STATUS_SHIFT (0U)
#define S16UP_RX_PCS_RX_STATUS_PRBS_LOCK_MASK (0x8000U)
#define S16UP_RX_PCS_RX_STATUS_PRBS_LOCK_SHIFT (15U)
#define S16UP_RX_PCS_RX_STATUS_PRBS_STKY_MASK (0x4000U)
#define S16UP_RX_PCS_RX_STATUS_PRBS_STKY_SHIFT (14U)
#define S16UP_RX_PCS_RX_STATUS_PRBS_ERRORS_MASK (0x3fffU)
#define S16UP_RX_PCS_RX_STATUS_PRBS_ERRORS_SHIFT (0U)
#define S16UP_RX_PCS_RX_STATUS_SYNC_STATUS_MASK (0x8000U)
#define S16UP_RX_PCS_RX_STATUS_SYNC_STATUS_SHIFT (15U)
#define S16UP_RX_PCS_RX_STATUS_E_COUNT_MASK (0x7fffU)
#define S16UP_RX_PCS_RX_STATUS_E_COUNT_SHIFT (0U)
#endif



typedef uint8_t S16UP_RX_PCS_RESERVED_TYPE;




typedef uint16_t S16UP_RX_PCS_RX_CONTROL_TYPE;
#define S16UP_RX_PCS_RX_CONTROL_STATUS_SEL_MASK (0x7U)
#define S16UP_RX_PCS_RX_CONTROL_STATUS_SEL_SHIFT (0U)




typedef uint16_t S16UP_RX_PCS_RMIC1_TYPE;
#define S16UP_RX_PCS_RMIC1_FORCE_SEQUENCE_RX_DATA_C0_MASK (0x8000U)
#define S16UP_RX_PCS_RMIC1_FORCE_SEQUENCE_RX_DATA_C0_SHIFT (15U)
#define S16UP_RX_PCS_RMIC1_FORCE_SEQUENCE_RX_DATA_C1_MASK (0x4000U)
#define S16UP_RX_PCS_RMIC1_FORCE_SEQUENCE_RX_DATA_C1_SHIFT (14U)
#define S16UP_RX_PCS_RMIC1_FORCE_SEQUENCE_RX_DATA_C2_MASK (0x2000U)
#define S16UP_RX_PCS_RMIC1_FORCE_SEQUENCE_RX_DATA_C2_SHIFT (13U)
#define S16UP_RX_PCS_RMIC1_FORCE_SEQUENCE_RX_DATA_C3_MASK (0x1000U)
#define S16UP_RX_PCS_RMIC1_FORCE_SEQUENCE_RX_DATA_C3_SHIFT (12U)
#define S16UP_RX_PCS_RMIC1_FORCE_SEQUENCE_RX_MASK (0xf00U)
#define S16UP_RX_PCS_RMIC1_FORCE_SEQUENCE_RX_SHIFT (8U)
#define S16UP_RX_PCS_RMIC1_FORCE_SEQUENCE_RX_ENABLE_MASK (0x80U)
#define S16UP_RX_PCS_RMIC1_FORCE_SEQUENCE_RX_ENABLE_SHIFT (7U)
#define S16UP_RX_PCS_RMIC1_FILTER_EN_CL49_MASK (0x40U)
#define S16UP_RX_PCS_RMIC1_FILTER_EN_CL49_SHIFT (6U)
#define S16UP_RX_PCS_RMIC1_FILTER_LPI_EN_MASK (0x20U)
#define S16UP_RX_PCS_RMIC1_FILTER_LPI_EN_SHIFT (5U)
#define S16UP_RX_PCS_RMIC1_FILTER_BL_EN_MASK (0x10U)
#define S16UP_RX_PCS_RMIC1_FILTER_BL_EN_SHIFT (4U)
#define S16UP_RX_PCS_RMIC1_FILTER_LF_EN_MASK (0x8U)
#define S16UP_RX_PCS_RMIC1_FILTER_LF_EN_SHIFT (3U)
#define S16UP_RX_PCS_RMIC1_FILTER_RF_EN_MASK (0x4U)
#define S16UP_RX_PCS_RMIC1_FILTER_RF_EN_SHIFT (2U)
#define S16UP_RX_PCS_RMIC1_FILTER_ERR_EN_MASK (0x2U)
#define S16UP_RX_PCS_RMIC1_FILTER_ERR_EN_SHIFT (1U)
#define S16UP_RX_PCS_RMIC1_FILTER_ORDERED_SET_EN_MASK (0x1U)
#define S16UP_RX_PCS_RMIC1_FILTER_ORDERED_SET_EN_SHIFT (0U)




typedef uint16_t S16UP_RX_PCS_RX_SIGDET_TYPE;
#define S16UP_RX_PCS_RX_SIGDET_R_MASK (0x10U)
#define S16UP_RX_PCS_RX_SIGDET_R_SHIFT (4U)
#define S16UP_RX_PCS_RX_SIGDET_FORCE_R_MASK (0x8U)
#define S16UP_RX_PCS_RX_SIGDET_FORCE_R_SHIFT (3U)




typedef uint16_t S16UP_RX_PCS_RX_PCS_STATUS_TYPE;
#define S16UP_RX_PCS_RX_PCS_STATUS_SEQ_DET_1_MASK (0x80U)
#define S16UP_RX_PCS_RX_PCS_STATUS_SEQ_DET_1_SHIFT (7U)
#define S16UP_RX_PCS_RX_PCS_STATUS_LF_DET_1_MASK (0x40U)
#define S16UP_RX_PCS_RX_PCS_STATUS_LF_DET_1_SHIFT (6U)
#define S16UP_RX_PCS_RX_PCS_STATUS_RF_DET_1_MASK (0x20U)
#define S16UP_RX_PCS_RX_PCS_STATUS_RF_DET_1_SHIFT (5U)
#define S16UP_RX_PCS_RX_PCS_STATUS_LI_DET_1_MASK (0x10U)
#define S16UP_RX_PCS_RX_PCS_STATUS_LI_DET_1_SHIFT (4U)
#define S16UP_RX_PCS_RX_PCS_STATUS_SEQ_DET_0_MASK (0x8U)
#define S16UP_RX_PCS_RX_PCS_STATUS_SEQ_DET_0_SHIFT (3U)
#define S16UP_RX_PCS_RX_PCS_STATUS_LF_DET_0_MASK (0x4U)
#define S16UP_RX_PCS_RX_PCS_STATUS_LF_DET_0_SHIFT (2U)
#define S16UP_RX_PCS_RX_PCS_STATUS_RF_DET_0_MASK (0x2U)
#define S16UP_RX_PCS_RX_PCS_STATUS_RF_DET_0_SHIFT (1U)
#define S16UP_RX_PCS_RX_PCS_STATUS_LI_DET_0_MASK (0x1U)
#define S16UP_RX_PCS_RX_PCS_STATUS_LI_DET_0_SHIFT (0U)




typedef uint16_t S16UP_RX_PCS_RMFSC1_TYPE;
#define S16UP_RX_PCS_RMFSC1_FORCE_SEQUENCE_DATA_BYTE1_MASK (0xff00U)
#define S16UP_RX_PCS_RMFSC1_FORCE_SEQUENCE_DATA_BYTE1_SHIFT (8U)
#define S16UP_RX_PCS_RMFSC1_FORCE_SEQUENCE_DATA_BYTE0_MASK (0xffU)
#define S16UP_RX_PCS_RMFSC1_FORCE_SEQUENCE_DATA_BYTE0_SHIFT (0U)




typedef uint16_t S16UP_RX_PCS_RMFSC2_TYPE;
#define S16UP_RX_PCS_RMFSC2_FORCE_SEQUENCE_DATA_BYTE3_MASK (0xff00U)
#define S16UP_RX_PCS_RMFSC2_FORCE_SEQUENCE_DATA_BYTE3_SHIFT (8U)
#define S16UP_RX_PCS_RMFSC2_FORCE_SEQUENCE_DATA_BYTE2_MASK (0xffU)
#define S16UP_RX_PCS_RMFSC2_FORCE_SEQUENCE_DATA_BYTE2_SHIFT (0U)




typedef uint16_t S16UP_RX_PCS_RX_CONTROL_PCI_TYPE;
#define S16UP_RX_PCS_RX_CONTROL_PCI_POLARITY_FORCE_SM_MASK (0x8U)
#define S16UP_RX_PCS_RX_CONTROL_PCI_POLARITY_FORCE_SM_SHIFT (3U)
#define S16UP_RX_PCS_RX_CONTROL_PCI_POLARITY_R_MASK (0x4U)
#define S16UP_RX_PCS_RX_CONTROL_PCI_POLARITY_R_SHIFT (2U)




typedef volatile struct sS16UP_RX_PCS_RDBType {
    S16UP_RX_PCS_RX_STATUS_TYPE anarxstatus; /* OFFSET: 0x0 */
    S16UP_RX_PCS_RESERVED_TYPE rsvd0[2]; /* OFFSET: 0x2 */
    S16UP_RX_PCS_RX_CONTROL_TYPE anarxcontrol; /* OFFSET: 0x4 */
    S16UP_RX_PCS_RESERVED_TYPE rsvd1[2]; /* OFFSET: 0x6 */
    S16UP_RX_PCS_RMIC1_TYPE r_mac_intf_control_1; /* OFFSET: 0x8 */
    S16UP_RX_PCS_RESERVED_TYPE rsvd2[6]; /* OFFSET: 0xa */
    S16UP_RX_PCS_RX_SIGDET_TYPE anarxsigdet; /* OFFSET: 0x10 */
    S16UP_RX_PCS_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0x12 */
    S16UP_RX_PCS_RX_PCS_STATUS_TYPE rx_pcs_status; /* OFFSET: 0x14 */
    S16UP_RX_PCS_RESERVED_TYPE rsvd4[2]; /* OFFSET: 0x16 */
    S16UP_RX_PCS_RMFSC1_TYPE r_mac_force_sequence_control1; /* OFFSET: 0x18 */
    S16UP_RX_PCS_RESERVED_TYPE rsvd5[2]; /* OFFSET: 0x1a */
    S16UP_RX_PCS_RMFSC2_TYPE r_mac_force_sequence_control2; /* OFFSET: 0x1c */
    S16UP_RX_PCS_RESERVED_TYPE rsvd6[10]; /* OFFSET: 0x1e */
    S16UP_RX_PCS_RX_CONTROL_PCI_TYPE anarxcontrolpci; /* OFFSET: 0x28 */
} S16UP_RX_PCS_RDBType;


#define RX_PCS_REG0_BASE                (0xE04E0300UL)



#define S16UP_RX_PCS_MAX_HW_ID          (1UL)

#endif /* S16UP_RX_PCS_RDB_H */
