/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file s16up_u_tx_x8_control0_rdb.h
    @brief RDB File for S16UP_U_TX_X8_CONTROL0

    @version BCM89580_A0_20230125_RDB
*/

#ifndef S16UP_U_TX_X8_CONTROL0_RDB_H
#define S16UP_U_TX_X8_CONTROL0_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t S16UP_U_TX_X8_CONTROL0_UCFC_TYPE;
#define S16UP_U_TX_X8_CONTROL0_UCFC_TX_CKCMP_PHASE_FIFO_EN_MASK (0x600U)
#define S16UP_U_TX_X8_CONTROL0_UCFC_TX_CKCMP_PHASE_FIFO_EN_SHIFT (9U)
#define S16UP_U_TX_X8_CONTROL0_UCFC_TX_CKCMP_STATUS_SEL_MASK (0x1e0U)
#define S16UP_U_TX_X8_CONTROL0_UCFC_TX_CKCMP_STATUS_SEL_SHIFT (5U)
#define S16UP_U_TX_X8_CONTROL0_UCFC_TX_CKCMP_RST_MASK (0x10U)
#define S16UP_U_TX_X8_CONTROL0_UCFC_TX_CKCMP_RST_SHIFT (4U)
#define S16UP_U_TX_X8_CONTROL0_UCFC_CKCMP_ADJUST_CNT_DEL_EN_CYA_MASK (0x8U)
#define S16UP_U_TX_X8_CONTROL0_UCFC_CKCMP_ADJUST_CNT_DEL_EN_CYA_SHIFT (3U)
#define S16UP_U_TX_X8_CONTROL0_UCFC_CKCMP_GT1_ICOL_DIS_MASK (0x4U)
#define S16UP_U_TX_X8_CONTROL0_UCFC_CKCMP_GT1_ICOL_DIS_SHIFT (2U)
#define S16UP_U_TX_X8_CONTROL0_UCFC_CKCMP_AFRST_EN_MASK (0x1U)
#define S16UP_U_TX_X8_CONTROL0_UCFC_CKCMP_AFRST_EN_SHIFT (0U)




typedef uint8_t S16UP_U_TX_X8_CONTROL0_RESERVED_TYPE;




typedef uint16_t S16UP_U_TX_X8_CONTROL0_UTX_X8_CONT_TYPE;
#define S16UP_U_TX_X8_CONTROL0_UTX_X8_CONT_TSN_ENABLE_MASK (0x8000U)
#define S16UP_U_TX_X8_CONTROL0_UTX_X8_CONT_TSN_ENABLE_SHIFT (15U)
#define S16UP_U_TX_X8_CONTROL0_UTX_X8_CONT_FVPE_MASK (0x4000U)
#define S16UP_U_TX_X8_CONTROL0_UTX_X8_CONT_FVPE_SHIFT (14U)
#define S16UP_U_TX_X8_CONTROL0_UTX_X8_CONT_URCO_MASK (0x3c00U)
#define S16UP_U_TX_X8_CONTROL0_UTX_X8_CONT_URCO_SHIFT (10U)
#define S16UP_U_TX_X8_CONTROL0_UTX_X8_CONT_URCOE_MASK (0x200U)
#define S16UP_U_TX_X8_CONTROL0_UTX_X8_CONT_URCOE_SHIFT (9U)
#define S16UP_U_TX_X8_CONTROL0_UTX_X8_CONT_RST_USXGMII_RLPBK_FIFO_MASK (0x100U)
#define S16UP_U_TX_X8_CONTROL0_UTX_X8_CONT_RST_USXGMII_RLPBK_FIFO_SHIFT (8U)
#define S16UP_U_TX_X8_CONTROL0_UTX_X8_CONT_PCS_RLOOP_EN_MASK (0x80U)
#define S16UP_U_TX_X8_CONTROL0_UTX_X8_CONT_PCS_RLOOP_EN_SHIFT (7U)
#define S16UP_U_TX_X8_CONTROL0_UTX_X8_CONT_ENABLE_SFD_DETECT_MASK (0x40U)
#define S16UP_U_TX_X8_CONTROL0_UTX_X8_CONT_ENABLE_SFD_DETECT_SHIFT (6U)
#define S16UP_U_TX_X8_CONTROL0_UTX_X8_CONT_FRC_TX_CLK_ON_MASK (0x20U)
#define S16UP_U_TX_X8_CONTROL0_UTX_X8_CONT_FRC_TX_CLK_ON_SHIFT (5U)
#define S16UP_U_TX_X8_CONTROL0_UTX_X8_CONT_RSTB_TX_PORT_MASK (0x10U)
#define S16UP_U_TX_X8_CONTROL0_UTX_X8_CONT_RSTB_TX_PORT_SHIFT (4U)
#define S16UP_U_TX_X8_CONTROL0_UTX_X8_CONT_TX_MAC_PORT_EN_MASK (0x8U)
#define S16UP_U_TX_X8_CONTROL0_UTX_X8_CONT_TX_MAC_PORT_EN_SHIFT (3U)
#define S16UP_U_TX_X8_CONTROL0_UTX_X8_CONT_TX_TESTMUX_SEL_MASK (0x7U)
#define S16UP_U_TX_X8_CONTROL0_UTX_X8_CONT_TX_TESTMUX_SEL_SHIFT (0U)




typedef uint16_t S16UP_U_TX_X8_CONTROL0_UMFSC0_TYPE;
#define S16UP_U_TX_X8_CONTROL0_UMFSC0_FORCE_SEQUENCE_TX_DATA_C0_MASK (0x8000U)
#define S16UP_U_TX_X8_CONTROL0_UMFSC0_FORCE_SEQUENCE_TX_DATA_C0_SHIFT (15U)
#define S16UP_U_TX_X8_CONTROL0_UMFSC0_FORCE_SEQUENCE_TX_DATA_C1_MASK (0x4000U)
#define S16UP_U_TX_X8_CONTROL0_UMFSC0_FORCE_SEQUENCE_TX_DATA_C1_SHIFT (14U)
#define S16UP_U_TX_X8_CONTROL0_UMFSC0_FORCE_SEQUENCE_TX_DATA_C2_MASK (0x2000U)
#define S16UP_U_TX_X8_CONTROL0_UMFSC0_FORCE_SEQUENCE_TX_DATA_C2_SHIFT (13U)
#define S16UP_U_TX_X8_CONTROL0_UMFSC0_FORCE_SEQUENCE_TX_DATA_C3_MASK (0x1000U)
#define S16UP_U_TX_X8_CONTROL0_UMFSC0_FORCE_SEQUENCE_TX_DATA_C3_SHIFT (12U)
#define S16UP_U_TX_X8_CONTROL0_UMFSC0_TX_MAC_AN_INTERRUPT_EN_MASK (0x8U)
#define S16UP_U_TX_X8_CONTROL0_UMFSC0_TX_MAC_AN_INTERRUPT_EN_SHIFT (3U)
#define S16UP_U_TX_X8_CONTROL0_UMFSC0_TX_MAC_AN_INTR_ST_EN_MASK (0x7U)
#define S16UP_U_TX_X8_CONTROL0_UMFSC0_TX_MAC_AN_INTR_ST_EN_SHIFT (0U)




typedef uint16_t S16UP_U_TX_X8_CONTROL0_UMFSC1_TYPE;
#define S16UP_U_TX_X8_CONTROL0_UMFSC1_FSTDB1_MASK (0xff00U)
#define S16UP_U_TX_X8_CONTROL0_UMFSC1_FSTDB1_SHIFT (8U)
#define S16UP_U_TX_X8_CONTROL0_UMFSC1_FSTDB0_MASK (0xffU)
#define S16UP_U_TX_X8_CONTROL0_UMFSC1_FSTDB0_SHIFT (0U)




typedef uint16_t S16UP_U_TX_X8_CONTROL0_UMFSC2_TYPE;
#define S16UP_U_TX_X8_CONTROL0_UMFSC2_FSTDB3_MASK (0xff00U)
#define S16UP_U_TX_X8_CONTROL0_UMFSC2_FSTDB3_SHIFT (8U)
#define S16UP_U_TX_X8_CONTROL0_UMFSC2_FSTDB2_MASK (0xffU)
#define S16UP_U_TX_X8_CONTROL0_UMFSC2_FSTDB2_SHIFT (0U)




typedef uint16_t S16UP_U_TX_X8_CONTROL0_UUR_TYPE;
#define S16UP_U_TX_X8_CONTROL0_UUR_INJECT_ERR_EN_MASK (0x800U)
#define S16UP_U_TX_X8_CONTROL0_UUR_INJECT_ERR_EN_SHIFT (11U)
#define S16UP_U_TX_X8_CONTROL0_UUR_INJECT_ERR_TYPE_MASK (0x700U)
#define S16UP_U_TX_X8_CONTROL0_UUR_INJECT_ERR_TYPE_SHIFT (8U)
#define S16UP_U_TX_X8_CONTROL0_UUR_INJECT_ERR_MASK_VAL_LN_MASK (0xf0U)
#define S16UP_U_TX_X8_CONTROL0_UUR_INJECT_ERR_MASK_VAL_LN_SHIFT (4U)
#define S16UP_U_TX_X8_CONTROL0_UUR_T_USXGMII_REPLICATE_TST_SEL_MASK (0xeU)
#define S16UP_U_TX_X8_CONTROL0_UUR_T_USXGMII_REPLICATE_TST_SEL_SHIFT (1U)
#define S16UP_U_TX_X8_CONTROL0_UUR_TURRAFR_MASK (0x1U)
#define S16UP_U_TX_X8_CONTROL0_UUR_TURRAFR_SHIFT (0U)




typedef uint16_t S16UP_U_TX_X8_CONTROL0_UMSC_TYPE;
#define S16UP_U_TX_X8_CONTROL0_UMSC_FILTER_EN_CL49_MASK (0x8000U)
#define S16UP_U_TX_X8_CONTROL0_UMSC_FILTER_EN_CL49_SHIFT (15U)
#define S16UP_U_TX_X8_CONTROL0_UMSC_TX_CLK_VLD_DELAY_MAX_MASK (0x7800U)
#define S16UP_U_TX_X8_CONTROL0_UMSC_TX_CLK_VLD_DELAY_MAX_SHIFT (11U)
#define S16UP_U_TX_X8_CONTROL0_UMSC_FILTER_EN_FLIP_USXGMII_AN_MASK (0x400U)
#define S16UP_U_TX_X8_CONTROL0_UMSC_FILTER_EN_FLIP_USXGMII_AN_SHIFT (10U)
#define S16UP_U_TX_X8_CONTROL0_UMSC_FILTER_EN_FLIP_USXGMII_FRC_MASK (0x200U)
#define S16UP_U_TX_X8_CONTROL0_UMSC_FILTER_EN_FLIP_USXGMII_FRC_SHIFT (9U)
#define S16UP_U_TX_X8_CONTROL0_UMSC_GMII_FILTER_EN_OV_EN_MASK (0x100U)
#define S16UP_U_TX_X8_CONTROL0_UMSC_GMII_FILTER_EN_OV_EN_SHIFT (8U)
#define S16UP_U_TX_X8_CONTROL0_UMSC_GMII_FILTER_EN_OV_MASK (0x80U)
#define S16UP_U_TX_X8_CONTROL0_UMSC_GMII_FILTER_EN_OV_SHIFT (7U)
#define S16UP_U_TX_X8_CONTROL0_UMSC_FILTER_LPI_EN_MASK (0x40U)
#define S16UP_U_TX_X8_CONTROL0_UMSC_FILTER_LPI_EN_SHIFT (6U)
#define S16UP_U_TX_X8_CONTROL0_UMSC_FILTER_BL_EN_MASK (0x20U)
#define S16UP_U_TX_X8_CONTROL0_UMSC_FILTER_BL_EN_SHIFT (5U)
#define S16UP_U_TX_X8_CONTROL0_UMSC_FILTER_LF_EN_MASK (0x10U)
#define S16UP_U_TX_X8_CONTROL0_UMSC_FILTER_LF_EN_SHIFT (4U)
#define S16UP_U_TX_X8_CONTROL0_UMSC_FILTER_RF_EN_MASK (0x8U)
#define S16UP_U_TX_X8_CONTROL0_UMSC_FILTER_RF_EN_SHIFT (3U)
#define S16UP_U_TX_X8_CONTROL0_UMSC_FILTER_CE_EN_MASK (0x4U)
#define S16UP_U_TX_X8_CONTROL0_UMSC_FILTER_CE_EN_SHIFT (2U)
#define S16UP_U_TX_X8_CONTROL0_UMSC_FILTER_ERR_EN_MASK (0x2U)
#define S16UP_U_TX_X8_CONTROL0_UMSC_FILTER_ERR_EN_SHIFT (1U)
#define S16UP_U_TX_X8_CONTROL0_UMSC_FILTER_ORDERED_SET_EN_MASK (0x1U)
#define S16UP_U_TX_X8_CONTROL0_UMSC_FILTER_ORDERED_SET_EN_SHIFT (0U)




typedef uint16_t S16UP_U_TX_X8_CONTROL0_UDIC_CONTROL_TYPE;
#define S16UP_U_TX_X8_CONTROL0_UDIC_CONTROL_TURRGF_MASK (0x80U)
#define S16UP_U_TX_X8_CONTROL0_UDIC_CONTROL_TURRGF_SHIFT (7U)
#define S16UP_U_TX_X8_CONTROL0_UDIC_CONTROL_DIC_TEST_RESTART_MASK (0x40U)
#define S16UP_U_TX_X8_CONTROL0_UDIC_CONTROL_DIC_TEST_RESTART_SHIFT (6U)
#define S16UP_U_TX_X8_CONTROL0_UDIC_CONTROL_DIC_PKT_CNT_TOTAL_MASK (0x3fU)
#define S16UP_U_TX_X8_CONTROL0_UDIC_CONTROL_DIC_PKT_CNT_TOTAL_SHIFT (0U)




typedef uint16_t S16UP_U_TX_X8_CONTROL0_UMSC2_TYPE;
#define S16UP_U_TX_X8_CONTROL0_UMSC2_RLOOP_FIFO_FORCE_IDLE_RF_MASK (0x100U)
#define S16UP_U_TX_X8_CONTROL0_UMSC2_RLOOP_FIFO_FORCE_IDLE_RF_SHIFT (8U)
#define S16UP_U_TX_X8_CONTROL0_UMSC2_MAC_INTF_PKT_CNT_DATA_SEL_MASK (0x80U)
#define S16UP_U_TX_X8_CONTROL0_UMSC2_MAC_INTF_PKT_CNT_DATA_SEL_SHIFT (7U)
#define S16UP_U_TX_X8_CONTROL0_UMSC2_MAC_INTF_TEST_RESTART_MASK (0x40U)
#define S16UP_U_TX_X8_CONTROL0_UMSC2_MAC_INTF_TEST_RESTART_SHIFT (6U)
#define S16UP_U_TX_X8_CONTROL0_UMSC2_MAC_INTF_PKT_CNT_TOTAL_MASK (0x3fU)
#define S16UP_U_TX_X8_CONTROL0_UMSC2_MAC_INTF_PKT_CNT_TOTAL_SHIFT (0U)




typedef volatile struct sS16UP_U_TX_X8_CONTROL0_RDBType {
    S16UP_U_TX_X8_CONTROL0_UCFC_TYPE tx_ckcmp_fifo_ctrl; /* OFFSET: 0x0 */
    S16UP_U_TX_X8_CONTROL0_RESERVED_TYPE rsvd0[2]; /* OFFSET: 0x2 */
    S16UP_U_TX_X8_CONTROL0_UTX_X8_CONT_TYPE tx_x8_control; /* OFFSET: 0x4 */
    S16UP_U_TX_X8_CONTROL0_RESERVED_TYPE rsvd1[10]; /* OFFSET: 0x6 */
    S16UP_U_TX_X8_CONTROL0_UMFSC0_TYPE t_mac_force_sequence_control0; /* OFFSET: 0x10 */
    S16UP_U_TX_X8_CONTROL0_RESERVED_TYPE rsvd2[2]; /* OFFSET: 0x12 */
    S16UP_U_TX_X8_CONTROL0_UMFSC1_TYPE t_mac_force_sequence_control1; /* OFFSET: 0x14 */
    S16UP_U_TX_X8_CONTROL0_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0x16 */
    S16UP_U_TX_X8_CONTROL0_UMFSC2_TYPE t_mac_force_sequence_control2; /* OFFSET: 0x18 */
    S16UP_U_TX_X8_CONTROL0_RESERVED_TYPE rsvd4[6]; /* OFFSET: 0x1a */
    S16UP_U_TX_X8_CONTROL0_UUR_TYPE t_usxgmii_replicate; /* OFFSET: 0x20 */
    S16UP_U_TX_X8_CONTROL0_RESERVED_TYPE rsvd5[2]; /* OFFSET: 0x22 */
    S16UP_U_TX_X8_CONTROL0_UMSC_TYPE t_mac_seq_control; /* OFFSET: 0x24 */
    S16UP_U_TX_X8_CONTROL0_RESERVED_TYPE rsvd6[14]; /* OFFSET: 0x26 */
    S16UP_U_TX_X8_CONTROL0_UDIC_CONTROL_TYPE dic_control; /* OFFSET: 0x34 */
    S16UP_U_TX_X8_CONTROL0_RESERVED_TYPE rsvd7[2]; /* OFFSET: 0x36 */
    S16UP_U_TX_X8_CONTROL0_UMSC2_TYPE t_mac_seq_control2; /* OFFSET: 0x38 */
} S16UP_U_TX_X8_CONTROL0_RDBType;


#define U_TX_X8_CONTROL0_BASE           (0xE04F1A00UL)



#define S16UP_U_TX_X8_CONTROL0_MAX_HW_ID  (1UL)

#endif /* S16UP_U_TX_X8_CONTROL0_RDB_H */
