/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file s16up_u_rx_x1_control0_rdb.h
    @brief RDB File for S16UP_U_RX_X1_CONTROL0

    @version BCM89580_A0_20230125_RDB
*/

#ifndef S16UP_U_RX_X1_CONTROL0_RDB_H
#define S16UP_U_RX_X1_CONTROL0_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t S16UP_U_RX_X1_CONTROL0_UR_DESCR1_TYPE;
#define S16UP_U_RX_X1_CONTROL0_UR_DESCR1_MODE_CUSTOM_MASK (0xcU)
#define S16UP_U_RX_X1_CONTROL0_UR_DESCR1_MODE_CUSTOM_SHIFT (2U)
#define S16UP_U_RX_X1_CONTROL0_UR_DESCR1_MODE_BYPASS_MASK (0x3U)
#define S16UP_U_RX_X1_CONTROL0_UR_DESCR1_MODE_BYPASS_SHIFT (0U)




typedef uint8_t S16UP_U_RX_X1_CONTROL0_RESERVED_TYPE;




typedef uint16_t S16UP_U_RX_X1_CONTROL0_UR_FEC_SYNC_TYPE;
#define S16UP_U_RX_X1_CONTROL0_UR_FEC_SYNC_FAST_LOCK_EN_MASK (0x1000U)
#define S16UP_U_RX_X1_CONTROL0_UR_FEC_SYNC_FAST_LOCK_EN_SHIFT (12U)
#define S16UP_U_RX_X1_CONTROL0_UR_FEC_SYNC_BLOCKSYNC_MODE_CUSTOM_MASK (0xe00U)
#define S16UP_U_RX_X1_CONTROL0_UR_FEC_SYNC_BLOCKSYNC_MODE_CUSTOM_SHIFT (9U)
#define S16UP_U_RX_X1_CONTROL0_UR_FEC_SYNC_BLOCKSYNC_MODE_FEC_MASK (0x1c0U)
#define S16UP_U_RX_X1_CONTROL0_UR_FEC_SYNC_BLOCKSYNC_MODE_FEC_SHIFT (6U)
#define S16UP_U_RX_X1_CONTROL0_UR_FEC_SYNC_BLOCKSYNC_MODE_CL49_MASK (0x38U)
#define S16UP_U_RX_X1_CONTROL0_UR_FEC_SYNC_BLOCKSYNC_MODE_CL49_SHIFT (3U)
#define S16UP_U_RX_X1_CONTROL0_UR_FEC_SYNC_BLOCKSYNC_MODE_8B10B_MASK (0x7U)
#define S16UP_U_RX_X1_CONTROL0_UR_FEC_SYNC_BLOCKSYNC_MODE_8B10B_SHIFT (0U)




typedef uint16_t S16UP_U_RX_X1_CONTROL0_UR_DEC1_TYPE;
#define S16UP_U_RX_X1_CONTROL0_UR_DEC1_DECODER_MODE_CUSTOM_MASK (0x1c0U)
#define S16UP_U_RX_X1_CONTROL0_UR_DEC1_DECODER_MODE_CUSTOM_SHIFT (6U)
#define S16UP_U_RX_X1_CONTROL0_UR_DEC1_DECODER_MODE_CL49_MASK (0x38U)
#define S16UP_U_RX_X1_CONTROL0_UR_DEC1_DECODER_MODE_CL49_SHIFT (3U)




typedef uint16_t S16UP_U_RX_X1_CONTROL0_UR_DESKEW_TYPE;
#define S16UP_U_RX_X1_CONTROL0_UR_DESKEW_MODE_CUSTOM_MASK (0x1c0U)
#define S16UP_U_RX_X1_CONTROL0_UR_DESKEW_MODE_CUSTOM_SHIFT (6U)
#define S16UP_U_RX_X1_CONTROL0_UR_DESKEW_MODE_BYPASS_MASK (0x38U)
#define S16UP_U_RX_X1_CONTROL0_UR_DESKEW_MODE_BYPASS_SHIFT (3U)




typedef uint16_t S16UP_U_RX_X1_CONTROL0_UR_GBOX_TYPE;
#define S16UP_U_RX_X1_CONTROL0_UR_GBOX_IDLE_FORCE_LINK_DOWN_MASK (0x20U)
#define S16UP_U_RX_X1_CONTROL0_UR_GBOX_IDLE_FORCE_LINK_DOWN_SHIFT (5U)
#define S16UP_U_RX_X1_CONTROL0_UR_GBOX_RX_GBOX_WATERMARK_MODE_MASK (0x10U)
#define S16UP_U_RX_X1_CONTROL0_UR_GBOX_RX_GBOX_WATERMARK_MODE_SHIFT (4U)
#define S16UP_U_RX_X1_CONTROL0_UR_GBOX_RXPOL_FLIP_MASK (0x8U)
#define S16UP_U_RX_X1_CONTROL0_UR_GBOX_RXPOL_FLIP_SHIFT (3U)
#define S16UP_U_RX_X1_CONTROL0_UR_GBOX_RX_GBOX_AFRST_SEL_MASK (0x7U)
#define S16UP_U_RX_X1_CONTROL0_UR_GBOX_RX_GBOX_AFRST_SEL_SHIFT (0U)




typedef uint16_t S16UP_U_RX_X1_CONTROL0_UR_DESC2_TYPE;
#define S16UP_U_RX_X1_CONTROL0_UR_DESC2_BYTE_DELETION_NONE_MASK (0x6000U)
#define S16UP_U_RX_X1_CONTROL0_UR_DESC2_BYTE_DELETION_NONE_SHIFT (13U)
#define S16UP_U_RX_X1_CONTROL0_UR_DESC2_BYTE_DELETION_100M_MASK (0x1800U)
#define S16UP_U_RX_X1_CONTROL0_UR_DESC2_BYTE_DELETION_100M_SHIFT (11U)
#define S16UP_U_RX_X1_CONTROL0_UR_DESC2_BYTE_DELETION_10M_MASK (0x600U)
#define S16UP_U_RX_X1_CONTROL0_UR_DESC2_BYTE_DELETION_10M_SHIFT (9U)
#define S16UP_U_RX_X1_CONTROL0_UR_DESC2_MODE_CUSTOM_MASK (0x1c0U)
#define S16UP_U_RX_X1_CONTROL0_UR_DESC2_MODE_CUSTOM_SHIFT (6U)
#define S16UP_U_RX_X1_CONTROL0_UR_DESC2_MODE_CL49_MASK (0x38U)
#define S16UP_U_RX_X1_CONTROL0_UR_DESC2_MODE_CL49_SHIFT (3U)




typedef uint16_t S16UP_U_RX_X1_CONTROL0_UC1_TYPE;
#define S16UP_U_RX_X1_CONTROL0_UC1_SET_BER_WINDOW_512_MASK (0x8000U)
#define S16UP_U_RX_X1_CONTROL0_UC1_SET_BER_WINDOW_512_SHIFT (15U)
#define S16UP_U_RX_X1_CONTROL0_UC1_CL49_BER_LIMIT_MASK (0xfcU)
#define S16UP_U_RX_X1_CONTROL0_UC1_CL49_BER_LIMIT_SHIFT (2U)




typedef uint16_t S16UP_U_RX_X1_CONTROL0_USHC_CL49_TYPE;
#define S16UP_U_RX_X1_CONTROL0_USHC_CL49_VALID_SH_CNT_MASK (0xff00U)
#define S16UP_U_RX_X1_CONTROL0_USHC_CL49_VALID_SH_CNT_SHIFT (8U)
#define S16UP_U_RX_X1_CONTROL0_USHC_CL49_INVALID_SH_CNT_MASK (0xffU)
#define S16UP_U_RX_X1_CONTROL0_USHC_CL49_INVALID_SH_CNT_SHIFT (0U)




typedef uint16_t S16UP_U_RX_X1_CONTROL0_URX_LOCK_DELA_TYPE;
#define S16UP_U_RX_X1_CONTROL0_URX_LOCK_DELA_PRSCO15E_MASK (0x400U)
#define S16UP_U_RX_X1_CONTROL0_URX_LOCK_DELA_PRSCO15E_SHIFT (10U)
#define S16UP_U_RX_X1_CONTROL0_URX_LOCK_DELA_PRSCO1E_MASK (0x200U)
#define S16UP_U_RX_X1_CONTROL0_URX_LOCK_DELA_PRSCO1E_SHIFT (9U)
#define S16UP_U_RX_X1_CONTROL0_URX_LOCK_DELA_PRSCOE_MASK (0x100U)
#define S16UP_U_RX_X1_CONTROL0_URX_LOCK_DELA_PRSCOE_SHIFT (8U)
#define S16UP_U_RX_X1_CONTROL0_URX_LOCK_DELA_PRLDC_MASK (0xffU)
#define S16UP_U_RX_X1_CONTROL0_URX_LOCK_DELA_PRLDC_SHIFT (0U)




typedef uint16_t S16UP_U_RX_X1_CONTROL0_UR_FEC_SYNC2_TYPE;
#define S16UP_U_RX_X1_CONTROL0_UR_FEC_SYNC2_DISABLE_FAST_AM_LOCK_MASK (0x200U)
#define S16UP_U_RX_X1_CONTROL0_UR_FEC_SYNC2_DISABLE_FAST_AM_LOCK_SHIFT (9U)
#define S16UP_U_RX_X1_CONTROL0_UR_FEC_SYNC2_AM_TM_DATA_SEL_MASK (0x1e0U)
#define S16UP_U_RX_X1_CONTROL0_UR_FEC_SYNC2_AM_TM_DATA_SEL_SHIFT (5U)
#define S16UP_U_RX_X1_CONTROL0_UR_FEC_SYNC2_AM_CMP_STRICT_MASK (0x1eU)
#define S16UP_U_RX_X1_CONTROL0_UR_FEC_SYNC2_AM_CMP_STRICT_SHIFT (1U)
#define S16UP_U_RX_X1_CONTROL0_UR_FEC_SYNC2_FEC_EN_MASK (0x1U)
#define S16UP_U_RX_X1_CONTROL0_UR_FEC_SYNC2_FEC_EN_SHIFT (0U)




typedef uint16_t S16UP_U_RX_X1_CONTROL0_UFEC_0_TYPE;
#define S16UP_U_RX_X1_CONTROL0_UFEC_0_FEC_ERR_ENABLE_MASK (0x2000U)
#define S16UP_U_RX_X1_CONTROL0_UFEC_0_FEC_ERR_ENABLE_SHIFT (13U)
#define S16UP_U_RX_X1_CONTROL0_UFEC_0_ERROR_EN_OVR_MASK (0x1000U)
#define S16UP_U_RX_X1_CONTROL0_UFEC_0_ERROR_EN_OVR_SHIFT (12U)
#define S16UP_U_RX_X1_CONTROL0_UFEC_0_ERROR_EN_OVR_VAL_MASK (0x800U)
#define S16UP_U_RX_X1_CONTROL0_UFEC_0_ERROR_EN_OVR_VAL_SHIFT (11U)
#define S16UP_U_RX_X1_CONTROL0_UFEC_0_DBG_ENABLE_MASK (0x400U)
#define S16UP_U_RX_X1_CONTROL0_UFEC_0_DBG_ENABLE_SHIFT (10U)




typedef uint16_t S16UP_U_RX_X1_CONTROL0_UCDM1_TYPE;
#define S16UP_U_RX_X1_CONTROL0_UCDM1_CKCMP_DELETE_MARGIN_2P5G_MASK (0x7c00U)
#define S16UP_U_RX_X1_CONTROL0_UCDM1_CKCMP_DELETE_MARGIN_2P5G_SHIFT (10U)
#define S16UP_U_RX_X1_CONTROL0_UCDM1_CKCMP_DELETE_MARGIN_5G_MASK (0x3e0U)
#define S16UP_U_RX_X1_CONTROL0_UCDM1_CKCMP_DELETE_MARGIN_5G_SHIFT (5U)
#define S16UP_U_RX_X1_CONTROL0_UCDM1_CKCMP_DELETE_MARGIN_10G_MASK (0x1fU)
#define S16UP_U_RX_X1_CONTROL0_UCDM1_CKCMP_DELETE_MARGIN_10G_SHIFT (0U)




typedef uint16_t S16UP_U_RX_X1_CONTROL0_UCDM2_TYPE;
#define S16UP_U_RX_X1_CONTROL0_UCDM2_CKCMP_DELETE_MARGIN_10M_MASK (0x7c00U)
#define S16UP_U_RX_X1_CONTROL0_UCDM2_CKCMP_DELETE_MARGIN_10M_SHIFT (10U)
#define S16UP_U_RX_X1_CONTROL0_UCDM2_CKCMP_DELETE_MARGIN_100M_MASK (0x3e0U)
#define S16UP_U_RX_X1_CONTROL0_UCDM2_CKCMP_DELETE_MARGIN_100M_SHIFT (5U)
#define S16UP_U_RX_X1_CONTROL0_UCDM2_CKCMP_DELETE_MARGIN_1G_MASK (0x1fU)
#define S16UP_U_RX_X1_CONTROL0_UCDM2_CKCMP_DELETE_MARGIN_1G_SHIFT (0U)




typedef volatile struct sS16UP_U_RX_X1_CONTROL0_RDBType {
    S16UP_U_RX_X1_CONTROL0_UR_DESCR1_TYPE descr1; /* OFFSET: 0x0 */
    S16UP_U_RX_X1_CONTROL0_RESERVED_TYPE rsvd0[2]; /* OFFSET: 0x2 */
    S16UP_U_RX_X1_CONTROL0_UR_FEC_SYNC_TYPE fec_sync; /* OFFSET: 0x4 */
    S16UP_U_RX_X1_CONTROL0_RESERVED_TYPE rsvd1[2]; /* OFFSET: 0x6 */
    S16UP_U_RX_X1_CONTROL0_UR_DEC1_TYPE dec1; /* OFFSET: 0x8 */
    S16UP_U_RX_X1_CONTROL0_RESERVED_TYPE rsvd2[2]; /* OFFSET: 0xa */
    S16UP_U_RX_X1_CONTROL0_UR_DESKEW_TYPE deskew; /* OFFSET: 0xc */
    S16UP_U_RX_X1_CONTROL0_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0xe */
    S16UP_U_RX_X1_CONTROL0_UR_GBOX_TYPE gbox; /* OFFSET: 0x10 */
    S16UP_U_RX_X1_CONTROL0_RESERVED_TYPE rsvd4[2]; /* OFFSET: 0x12 */
    S16UP_U_RX_X1_CONTROL0_UR_DESC2_TYPE desc2; /* OFFSET: 0x14 */
    S16UP_U_RX_X1_CONTROL0_RESERVED_TYPE rsvd5[2]; /* OFFSET: 0x16 */
    S16UP_U_RX_X1_CONTROL0_UC1_TYPE decode_control_1; /* OFFSET: 0x18 */
    S16UP_U_RX_X1_CONTROL0_RESERVED_TYPE rsvd6[2]; /* OFFSET: 0x1a */
    S16UP_U_RX_X1_CONTROL0_USHC_CL49_TYPE shcnt_cl49; /* OFFSET: 0x1c */
    S16UP_U_RX_X1_CONTROL0_RESERVED_TYPE rsvd7[2]; /* OFFSET: 0x1e */
    S16UP_U_RX_X1_CONTROL0_URX_LOCK_DELA_TYPE pmd_rx_lock_delay; /* OFFSET: 0x20 */
    S16UP_U_RX_X1_CONTROL0_RESERVED_TYPE rsvd8[2]; /* OFFSET: 0x22 */
    S16UP_U_RX_X1_CONTROL0_UR_FEC_SYNC2_TYPE fec_sync2; /* OFFSET: 0x24 */
    S16UP_U_RX_X1_CONTROL0_RESERVED_TYPE rsvd9[2]; /* OFFSET: 0x26 */
    S16UP_U_RX_X1_CONTROL0_UFEC_0_TYPE fec_0; /* OFFSET: 0x28 */
    S16UP_U_RX_X1_CONTROL0_RESERVED_TYPE rsvd10[10]; /* OFFSET: 0x2a */
    S16UP_U_RX_X1_CONTROL0_UCDM1_TYPE urx_ckcmp_delete_margin_1; /* OFFSET: 0x34 */
    S16UP_U_RX_X1_CONTROL0_RESERVED_TYPE rsvd11[2]; /* OFFSET: 0x36 */
    S16UP_U_RX_X1_CONTROL0_UCDM2_TYPE urx_ckcmp_delete_margin_2; /* OFFSET: 0x38 */
} S16UP_U_RX_X1_CONTROL0_RDBType;


#define U_RX_X1_CONTROL0_BASE           (0xE04E5080UL)



#define S16UP_U_RX_X1_CONTROL0_MAX_HW_ID  (1UL)

#endif /* S16UP_U_RX_X1_CONTROL0_RDB_H */
