/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file s16up_ana_pmd_blk2_rdb.h
    @brief RDB File for S16UP_ANA_PMD_BLK2

    @version BCM89580_A0_20230125_RDB
*/

#ifndef S16UP_ANA_PMD_BLK2_RDB_H
#define S16UP_ANA_PMD_BLK2_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t S16UP_ANA_PMD_BLK2_ANA_STATUS0_TYPE;
#define S16UP_ANA_PMD_BLK2_ANA_STATUS0_ANA_PMD_TMUX_EN_MASK (0x40U)
#define S16UP_ANA_PMD_BLK2_ANA_STATUS0_ANA_PMD_TMUX_EN_SHIFT (6U)
#define S16UP_ANA_PMD_BLK2_ANA_STATUS0_RX_SIGDET_LL_MASK (0x20U)
#define S16UP_ANA_PMD_BLK2_ANA_STATUS0_RX_SIGDET_LL_SHIFT (5U)
#define S16UP_ANA_PMD_BLK2_ANA_STATUS0_CX4_SIGDET_LL_MASK (0x10U)
#define S16UP_ANA_PMD_BLK2_ANA_STATUS0_CX4_SIGDET_LL_SHIFT (4U)
#define S16UP_ANA_PMD_BLK2_ANA_STATUS0_RX_SIGDET_FILTERED_MASK (0x8U)
#define S16UP_ANA_PMD_BLK2_ANA_STATUS0_RX_SIGDET_FILTERED_SHIFT (3U)
#define S16UP_ANA_PMD_BLK2_ANA_STATUS0_ANA_SLICER_CALVALID_MASK (0x4U)
#define S16UP_ANA_PMD_BLK2_ANA_STATUS0_ANA_SLICER_CALVALID_SHIFT (2U)
#define S16UP_ANA_PMD_BLK2_ANA_STATUS0_ANA_RX_CDR_LOCK_MASK (0x2U)
#define S16UP_ANA_PMD_BLK2_ANA_STATUS0_ANA_RX_CDR_LOCK_SHIFT (1U)
#define S16UP_ANA_PMD_BLK2_ANA_STATUS0_PMD_RX_LOCK_MASK (0x1U)
#define S16UP_ANA_PMD_BLK2_ANA_STATUS0_PMD_RX_LOCK_SHIFT (0U)




typedef uint8_t S16UP_ANA_PMD_BLK2_RESERVED_TYPE;




typedef uint16_t S16UP_ANA_PMD_BLK2_ANA_STATUS1_TYPE;
#define S16UP_ANA_PMD_BLK2_ANA_STATUS1_PF_CTRL_O_MASK (0xfU)
#define S16UP_ANA_PMD_BLK2_ANA_STATUS1_PF_CTRL_O_SHIFT (0U)




typedef uint16_t S16UP_ANA_PMD_BLK2_ANA_PMD_TMUX_TYPE;
#define S16UP_ANA_PMD_BLK2_ANA_PMD_TMUX_MASK (0xffffU)
#define S16UP_ANA_PMD_BLK2_ANA_PMD_TMUX_SHIFT (0U)




typedef uint16_t S16UP_ANA_PMD_BLK2_ANA_SLOFF_STATUS0_TYPE;
#define S16UP_ANA_PMD_BLK2_ANA_SLOFF_STATUS0_1O_VAL_MASK (0xf000U)
#define S16UP_ANA_PMD_BLK2_ANA_SLOFF_STATUS0_1O_VAL_SHIFT (12U)
#define S16UP_ANA_PMD_BLK2_ANA_SLOFF_STATUS0_1E_VAL_MASK (0xf00U)
#define S16UP_ANA_PMD_BLK2_ANA_SLOFF_STATUS0_1E_VAL_SHIFT (8U)
#define S16UP_ANA_PMD_BLK2_ANA_SLOFF_STATUS0_0O_VAL_MASK (0xf0U)
#define S16UP_ANA_PMD_BLK2_ANA_SLOFF_STATUS0_0O_VAL_SHIFT (4U)
#define S16UP_ANA_PMD_BLK2_ANA_SLOFF_STATUS0_0E_VAL_MASK (0xfU)
#define S16UP_ANA_PMD_BLK2_ANA_SLOFF_STATUS0_0E_VAL_SHIFT (0U)




typedef uint16_t S16UP_ANA_PMD_BLK2_ANA_SLOFF_STATUS1_TYPE;
#define S16UP_ANA_PMD_BLK2_ANA_SLOFF_STATUS1_SLOFF2O_VAL_MASK (0xf0U)
#define S16UP_ANA_PMD_BLK2_ANA_SLOFF_STATUS1_SLOFF2O_VAL_SHIFT (4U)
#define S16UP_ANA_PMD_BLK2_ANA_SLOFF_STATUS1_SLOFF2E_VAL_MASK (0xfU)
#define S16UP_ANA_PMD_BLK2_ANA_SLOFF_STATUS1_SLOFF2E_VAL_SHIFT (0U)




typedef volatile struct sS16UP_ANA_PMD_BLK2_RDBType {
    S16UP_ANA_PMD_BLK2_ANA_STATUS0_TYPE status0; /* OFFSET: 0x0 */
    S16UP_ANA_PMD_BLK2_RESERVED_TYPE rsvd0[2]; /* OFFSET: 0x2 */
    S16UP_ANA_PMD_BLK2_ANA_STATUS1_TYPE status1; /* OFFSET: 0x4 */
    S16UP_ANA_PMD_BLK2_RESERVED_TYPE rsvd1[2]; /* OFFSET: 0x6 */
    S16UP_ANA_PMD_BLK2_ANA_PMD_TMUX_TYPE pmd_tmux; /* OFFSET: 0x8 */
    S16UP_ANA_PMD_BLK2_RESERVED_TYPE rsvd2[2]; /* OFFSET: 0xa */
    S16UP_ANA_PMD_BLK2_ANA_SLOFF_STATUS0_TYPE sloff_status0; /* OFFSET: 0xc */
    S16UP_ANA_PMD_BLK2_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0xe */
    S16UP_ANA_PMD_BLK2_ANA_SLOFF_STATUS1_TYPE sloff_status1; /* OFFSET: 0x10 */
} S16UP_ANA_PMD_BLK2_RDBType;


#define ANA_PMD_BLK2_BASE               (0xE0468280UL)



#define S16UP_ANA_PMD_BLK2_MAX_HW_ID    (1UL)

#endif /* S16UP_ANA_PMD_BLK2_RDB_H */
