/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file s16up_rx_cdr_rdb.h
    @brief RDB File for S16UP_RX_CDR

    @version BCM89580_A0_20230125_RDB
*/

#ifndef S16UP_RX_CDR_RDB_H
#define S16UP_RX_CDR_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t S16UP_RX_CDR_RXPMD_1RXPMD_REV_ID_TYPE;
#define S16UP_RX_CDR_RXPMD_1RXPMD_REV_ID_MASK (0xffffU)
#define S16UP_RX_CDR_RXPMD_1RXPMD_REV_ID_SHIFT (0U)




typedef uint8_t S16UP_RX_CDR_RESERVED_TYPE;




typedef uint16_t S16UP_RX_CDR_RXPMD_1RX_CONTROL1_TYPE;
#define S16UP_RX_CDR_RXPMD_1RX_CONTROL1_CDR_LOCK_TVAL_USE_MD_MASK (0x8000U)
#define S16UP_RX_CDR_RXPMD_1RX_CONTROL1_CDR_LOCK_TVAL_USE_MD_SHIFT (15U)
#define S16UP_RX_CDR_RXPMD_1RX_CONTROL1_CDR_FORCE_LOS_FREEZE_MASK (0x4000U)
#define S16UP_RX_CDR_RXPMD_1RX_CONTROL1_CDR_FORCE_LOS_FREEZE_SHIFT (14U)
#define S16UP_RX_CDR_RXPMD_1RX_CONTROL1_RX_PMD_EN_FRC_VAL_MASK (0x2000U)
#define S16UP_RX_CDR_RXPMD_1RX_CONTROL1_RX_PMD_EN_FRC_VAL_SHIFT (13U)
#define S16UP_RX_CDR_RXPMD_1RX_CONTROL1_RX_PMD_EN_FRC_MASK (0x1000U)
#define S16UP_RX_CDR_RXPMD_1RX_CONTROL1_RX_PMD_EN_FRC_SHIFT (12U)
#define S16UP_RX_CDR_RXPMD_1RX_CONTROL1_RX_PPM_VAL_MASK (0x1ffU)
#define S16UP_RX_CDR_RXPMD_1RX_CONTROL1_RX_PPM_VAL_SHIFT (0U)




typedef uint16_t S16UP_RX_CDR_RXPMD_1RX_CDR_PROP_BW_TYPE;
#define S16UP_RX_CDR_RXPMD_1RX_CDR_PROP_BW_G3_CDR_PROP_BW_MASK (0x1c0U)
#define S16UP_RX_CDR_RXPMD_1RX_CDR_PROP_BW_G3_CDR_PROP_BW_SHIFT (6U)
#define S16UP_RX_CDR_RXPMD_1RX_CDR_PROP_BW_G2_CDR_PROP_BW_MASK (0x38U)
#define S16UP_RX_CDR_RXPMD_1RX_CDR_PROP_BW_G2_CDR_PROP_BW_SHIFT (3U)
#define S16UP_RX_CDR_RXPMD_1RX_CDR_PROP_BW_G1_CDR_PROP_BW_MASK (0x7U)
#define S16UP_RX_CDR_RXPMD_1RX_CDR_PROP_BW_G1_CDR_PROP_BW_SHIFT (0U)




typedef uint16_t S16UP_RX_CDR_R1CAIB_TYPE;
#define S16UP_RX_CDR_R1CAIB_G3_CDR_ACQ_INTEG_BW_MASK (0x1c0U)
#define S16UP_RX_CDR_R1CAIB_G3_CDR_ACQ_INTEG_BW_SHIFT (6U)
#define S16UP_RX_CDR_R1CAIB_G2_CDR_ACQ_INTEG_BW_MASK (0x38U)
#define S16UP_RX_CDR_R1CAIB_G2_CDR_ACQ_INTEG_BW_SHIFT (3U)
#define S16UP_RX_CDR_R1CAIB_G1_CDR_ACQ_INTEG_BW_MASK (0x7U)
#define S16UP_RX_CDR_R1CAIB_G1_CDR_ACQ_INTEG_BW_SHIFT (0U)




typedef uint16_t S16UP_RX_CDR_R1CLIB_TYPE;
#define S16UP_RX_CDR_R1CLIB_G3_CDR_LOCK_INTEG_BW_MASK (0x1c0U)
#define S16UP_RX_CDR_R1CLIB_G3_CDR_LOCK_INTEG_BW_SHIFT (6U)
#define S16UP_RX_CDR_R1CLIB_G2_CDR_LOCK_INTEG_BW_MASK (0x38U)
#define S16UP_RX_CDR_R1CLIB_G2_CDR_LOCK_INTEG_BW_SHIFT (3U)
#define S16UP_RX_CDR_R1CLIB_G1_CDR_LOCK_INTEG_BW_MASK (0x7U)
#define S16UP_RX_CDR_R1CLIB_G1_CDR_LOCK_INTEG_BW_SHIFT (0U)




typedef uint16_t S16UP_RX_CDR_RXPMD_1RX_CDR_TIMER_TYPE;
#define S16UP_RX_CDR_RXPMD_1RX_CDR_TIMER_LOCK_TVAL_FINE_MASK (0xff00U)
#define S16UP_RX_CDR_RXPMD_1RX_CDR_TIMER_LOCK_TVAL_FINE_SHIFT (8U)
#define S16UP_RX_CDR_RXPMD_1RX_CDR_TIMER_LOCK_TVAL_MASK (0xffU)
#define S16UP_RX_CDR_RXPMD_1RX_CDR_TIMER_LOCK_TVAL_SHIFT (0U)




typedef uint16_t S16UP_RX_CDR_RXPMD_1RX_FREQ_FRC_INTEG_TYPE;
#define S16UP_RX_CDR_RXPMD_1RX_FREQ_FRC_INTEG_REGRX_MASK (0x400U)
#define S16UP_RX_CDR_RXPMD_1RX_FREQ_FRC_INTEG_REGRX_SHIFT (10U)
#define S16UP_RX_CDR_RXPMD_1RX_FREQ_FRC_INTEG_REGRX_VAL_MASK (0x3ffU)
#define S16UP_RX_CDR_RXPMD_1RX_FREQ_FRC_INTEG_REGRX_VAL_SHIFT (0U)




typedef uint16_t S16UP_RX_CDR_RXPMD_1RX_FREQ_MON_CONTROL1_TYPE;
#define S16UP_RX_CDR_RXPMD_1RX_FREQ_MON_CONTROL1_CORRECT_EN_MASK (0x100U)
#define S16UP_RX_CDR_RXPMD_1RX_FREQ_MON_CONTROL1_CORRECT_EN_SHIFT (8U)
#define S16UP_RX_CDR_RXPMD_1RX_FREQ_MON_CONTROL1_MARGIN_VAL_MASK (0xffU)
#define S16UP_RX_CDR_RXPMD_1RX_FREQ_MON_CONTROL1_MARGIN_VAL_SHIFT (0U)




typedef uint16_t S16UP_RX_CDR_RXPMD_1RX_FREQ_MON_STATUS1_TYPE;
#define S16UP_RX_CDR_RXPMD_1RX_FREQ_MON_STATUS1_RX_BIT_RATE_GEN_MASK (0xc0U)
#define S16UP_RX_CDR_RXPMD_1RX_FREQ_MON_STATUS1_RX_BIT_RATE_GEN_SHIFT (6U)
#define S16UP_RX_CDR_RXPMD_1RX_FREQ_MON_STATUS1_RX_CDR_LOCK_MASK (0x4U)
#define S16UP_RX_CDR_RXPMD_1RX_FREQ_MON_STATUS1_RX_CDR_LOCK_SHIFT (2U)
#define S16UP_RX_CDR_RXPMD_1RX_FREQ_MON_STATUS1_MON_CORRECTED_MASK (0x2U)
#define S16UP_RX_CDR_RXPMD_1RX_FREQ_MON_STATUS1_MON_CORRECTED_SHIFT (1U)
#define S16UP_RX_CDR_RXPMD_1RX_FREQ_MON_STATUS1_MON_LOST_LOCK_MASK (0x1U)
#define S16UP_RX_CDR_RXPMD_1RX_FREQ_MON_STATUS1_MON_LOST_LOCK_SHIFT (0U)




typedef uint16_t S16UP_RX_CDR_RXPMD_1RX_HSPMD_CONTROL1_TYPE;
#define S16UP_RX_CDR_RXPMD_1RX_HSPMD_CONTROL1_PMD_TRANSPOSE_MASK (0x8000U)
#define S16UP_RX_CDR_RXPMD_1RX_HSPMD_CONTROL1_PMD_TRANSPOSE_SHIFT (15U)
#define S16UP_RX_CDR_RXPMD_1RX_HSPMD_CONTROL1_PMD_INVERT_MASK (0x4000U)
#define S16UP_RX_CDR_RXPMD_1RX_HSPMD_CONTROL1_PMD_INVERT_SHIFT (14U)
#define S16UP_RX_CDR_RXPMD_1RX_HSPMD_CONTROL1_PMD_CLKOUT_FLIP_MASK (0x2000U)
#define S16UP_RX_CDR_RXPMD_1RX_HSPMD_CONTROL1_PMD_CLKOUT_FLIP_SHIFT (13U)
#define S16UP_RX_CDR_RXPMD_1RX_HSPMD_CONTROL1_PHASE_ENC_POL_MASK (0x200U)
#define S16UP_RX_CDR_RXPMD_1RX_HSPMD_CONTROL1_PHASE_ENC_POL_SHIFT (9U)
#define S16UP_RX_CDR_RXPMD_1RX_HSPMD_CONTROL1_PHASE_ENC_MD_MASK (0x100U)
#define S16UP_RX_CDR_RXPMD_1RX_HSPMD_CONTROL1_PHASE_ENC_MD_SHIFT (8U)
#define S16UP_RX_CDR_RXPMD_1RX_HSPMD_CONTROL1_PHACT_8B4B_MASK (0x80U)
#define S16UP_RX_CDR_RXPMD_1RX_HSPMD_CONTROL1_PHACT_8B4B_SHIFT (7U)
#define S16UP_RX_CDR_RXPMD_1RX_HSPMD_CONTROL1_PDET_PZ_SWAP_MASK (0x40U)
#define S16UP_RX_CDR_RXPMD_1RX_HSPMD_CONTROL1_PDET_PZ_SWAP_SHIFT (6U)
#define S16UP_RX_CDR_RXPMD_1RX_HSPMD_CONTROL1_PDET_INV_MASK (0x20U)
#define S16UP_RX_CDR_RXPMD_1RX_HSPMD_CONTROL1_PDET_INV_SHIFT (5U)
#define S16UP_RX_CDR_RXPMD_1RX_HSPMD_CONTROL1_PHS_STP_INV_MASK (0x10U)
#define S16UP_RX_CDR_RXPMD_1RX_HSPMD_CONTROL1_PHS_STP_INV_SHIFT (4U)
#define S16UP_RX_CDR_RXPMD_1RX_HSPMD_CONTROL1_PHASE_ROTATE_MASK (0xfU)
#define S16UP_RX_CDR_RXPMD_1RX_HSPMD_CONTROL1_PHASE_ROTATE_SHIFT (0U)




typedef uint16_t S16UP_RX_CDR_RXPMD_1RX_HSPMD_STATUS1_TYPE;
#define S16UP_RX_CDR_RXPMD_1RX_HSPMD_STATUS1_PHASE_COUNTER_MASK (0xfc00U)
#define S16UP_RX_CDR_RXPMD_1RX_HSPMD_STATUS1_PHASE_COUNTER_SHIFT (10U)
#define S16UP_RX_CDR_RXPMD_1RX_HSPMD_STATUS1_INTEG_REG_MASK (0x3ffU)
#define S16UP_RX_CDR_RXPMD_1RX_HSPMD_STATUS1_INTEG_REG_SHIFT (0U)




typedef uint16_t S16UP_RX_CDR_RXPMD_1RX_PRBSCHK_CONTROL_TYPE;
#define S16UP_RX_CDR_RXPMD_1RX_PRBSCHK_CONTROL_PRBSCHK_EYEM_MASK (0x40U)
#define S16UP_RX_CDR_RXPMD_1RX_PRBSCHK_CONTROL_PRBSCHK_EYEM_SHIFT (6U)
#define S16UP_RX_CDR_RXPMD_1RX_PRBSCHK_CONTROL_PRBSCHK_TRANSPOSE_MASK (0x20U)
#define S16UP_RX_CDR_RXPMD_1RX_PRBSCHK_CONTROL_PRBSCHK_TRANSPOSE_SHIFT (5U)
#define S16UP_RX_CDR_RXPMD_1RX_PRBSCHK_CONTROL_PRBSCHK_SEL_MASK (0x18U)
#define S16UP_RX_CDR_RXPMD_1RX_PRBSCHK_CONTROL_PRBSCHK_SEL_SHIFT (3U)
#define S16UP_RX_CDR_RXPMD_1RX_PRBSCHK_CONTROL_PRBSCH_INV_MASK (0x4U)
#define S16UP_RX_CDR_RXPMD_1RX_PRBSCHK_CONTROL_PRBSCH_INV_SHIFT (2U)
#define S16UP_RX_CDR_RXPMD_1RX_PRBSCHK_CONTROL_PRBSCHK_SMPL_MASK (0x2U)
#define S16UP_RX_CDR_RXPMD_1RX_PRBSCHK_CONTROL_PRBSCHK_SMPL_SHIFT (1U)
#define S16UP_RX_CDR_RXPMD_1RX_PRBSCHK_CONTROL_PRBSCHK_EN_MASK (0x1U)
#define S16UP_RX_CDR_RXPMD_1RX_PRBSCHK_CONTROL_PRBSCHK_EN_SHIFT (0U)




typedef uint16_t S16UP_RX_CDR_RXPMD_1RX_PRBSCHK_STATUS_TYPE;
#define S16UP_RX_CDR_RXPMD_1RX_PRBSCHK_STATUS_NUMERR_MASK (0x3ffU)
#define S16UP_RX_CDR_RXPMD_1RX_PRBSCHK_STATUS_NUMERR_SHIFT (0U)




typedef uint16_t S16UP_RX_CDR_RXPMD_1RX_TESTMUX_CONTROL1_TYPE;
#define S16UP_RX_CDR_RXPMD_1RX_TESTMUX_CONTROL1_TMUX_PORT_EN_MASK (0x20U)
#define S16UP_RX_CDR_RXPMD_1RX_TESTMUX_CONTROL1_TMUX_PORT_EN_SHIFT (5U)
#define S16UP_RX_CDR_RXPMD_1RX_TESTMUX_CONTROL1_TMUX_SEL_READ_MASK (0x18U)
#define S16UP_RX_CDR_RXPMD_1RX_TESTMUX_CONTROL1_TMUX_SEL_READ_SHIFT (3U)
#define S16UP_RX_CDR_RXPMD_1RX_TESTMUX_CONTROL1_TMUX_SEL_MAIN_MASK (0x6U)
#define S16UP_RX_CDR_RXPMD_1RX_TESTMUX_CONTROL1_TMUX_SEL_MAIN_SHIFT (1U)
#define S16UP_RX_CDR_RXPMD_1RX_TESTMUX_CONTROL1_TMUX_FRZ_MASK (0x1U)
#define S16UP_RX_CDR_RXPMD_1RX_TESTMUX_CONTROL1_TMUX_FRZ_SHIFT (0U)




typedef volatile struct sS16UP_RX_CDR_RDBType {
    S16UP_RX_CDR_RXPMD_1RXPMD_REV_ID_TYPE m1rxpmd_rev_id; /* OFFSET: 0x0 */
    S16UP_RX_CDR_RESERVED_TYPE rsvd0[2]; /* OFFSET: 0x2 */
    S16UP_RX_CDR_RXPMD_1RX_CONTROL1_TYPE m1rx_control1; /* OFFSET: 0x4 */
    S16UP_RX_CDR_RESERVED_TYPE rsvd1[2]; /* OFFSET: 0x6 */
    S16UP_RX_CDR_RXPMD_1RX_CDR_PROP_BW_TYPE m1rx_cdr_prop_bw; /* OFFSET: 0x8 */
    S16UP_RX_CDR_RESERVED_TYPE rsvd2[2]; /* OFFSET: 0xa */
    S16UP_RX_CDR_R1CAIB_TYPE m1rx_cdr_acq_integ_bw; /* OFFSET: 0xc */
    S16UP_RX_CDR_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0xe */
    S16UP_RX_CDR_R1CLIB_TYPE m1rx_cdr_lock_integ_bw; /* OFFSET: 0x10 */
    S16UP_RX_CDR_RESERVED_TYPE rsvd4[2]; /* OFFSET: 0x12 */
    S16UP_RX_CDR_RXPMD_1RX_CDR_TIMER_TYPE m1rx_cdr_timer; /* OFFSET: 0x14 */
    S16UP_RX_CDR_RESERVED_TYPE rsvd5[2]; /* OFFSET: 0x16 */
    S16UP_RX_CDR_RXPMD_1RX_FREQ_FRC_INTEG_TYPE m1rx_freq_frc_integ; /* OFFSET: 0x18 */
    S16UP_RX_CDR_RESERVED_TYPE rsvd6[2]; /* OFFSET: 0x1a */
    S16UP_RX_CDR_RXPMD_1RX_FREQ_MON_CONTROL1_TYPE m1rx_freq_mon_control1; /* OFFSET: 0x1c */
    S16UP_RX_CDR_RESERVED_TYPE rsvd7[2]; /* OFFSET: 0x1e */
    S16UP_RX_CDR_RXPMD_1RX_FREQ_MON_STATUS1_TYPE m1rx_freq_mon_status1; /* OFFSET: 0x20 */
    S16UP_RX_CDR_RESERVED_TYPE rsvd8[2]; /* OFFSET: 0x22 */
    S16UP_RX_CDR_RXPMD_1RX_HSPMD_CONTROL1_TYPE m1rx_hspmd_control1; /* OFFSET: 0x24 */
    S16UP_RX_CDR_RESERVED_TYPE rsvd9[2]; /* OFFSET: 0x26 */
    S16UP_RX_CDR_RXPMD_1RX_HSPMD_STATUS1_TYPE m1rx_hspmd_status1; /* OFFSET: 0x28 */
    S16UP_RX_CDR_RESERVED_TYPE rsvd10[2]; /* OFFSET: 0x2a */
    S16UP_RX_CDR_RXPMD_1RX_PRBSCHK_CONTROL_TYPE m1rx_prbschk_control; /* OFFSET: 0x2c */
    S16UP_RX_CDR_RESERVED_TYPE rsvd11[2]; /* OFFSET: 0x2e */
    S16UP_RX_CDR_RXPMD_1RX_PRBSCHK_STATUS_TYPE m1rx_prbschk_status; /* OFFSET: 0x30 */
    S16UP_RX_CDR_RESERVED_TYPE rsvd12[6]; /* OFFSET: 0x32 */
    S16UP_RX_CDR_RXPMD_1RX_TESTMUX_CONTROL1_TYPE m1rx_testmux_control1; /* OFFSET: 0x38 */
} S16UP_RX_CDR_RDBType;


#define RX_CDR_AFE_BASE                 (0xE0468080UL)



#define S16UP_RX_CDR_MAX_HW_ID          (1UL)

#endif /* S16UP_RX_CDR_RDB_H */
