/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file s16up_u_tx_x1_control0_rdb.h
    @brief RDB File for S16UP_U_TX_X1_CONTROL0

    @version BCM89580_A0_20230125_RDB
*/

#ifndef S16UP_U_TX_X1_CONTROL0_RDB_H
#define S16UP_U_TX_X1_CONTROL0_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t S16UP_U_TX_X1_CONTROL0_RESERVED_TYPE;




typedef uint16_t S16UP_U_TX_X1_CONTROL0_UPMD_OSR_MODE_TYPE;
#define S16UP_U_TX_X1_CONTROL0_UPMD_OSR_MODE_PMD_8_MASK (0xf000U)
#define S16UP_U_TX_X1_CONTROL0_UPMD_OSR_MODE_PMD_8_SHIFT (12U)
#define S16UP_U_TX_X1_CONTROL0_UPMD_OSR_MODE_PMD_4_MASK (0xf00U)
#define S16UP_U_TX_X1_CONTROL0_UPMD_OSR_MODE_PMD_4_SHIFT (8U)
#define S16UP_U_TX_X1_CONTROL0_UPMD_OSR_MODE_PMD_2_MASK (0xf0U)
#define S16UP_U_TX_X1_CONTROL0_UPMD_OSR_MODE_PMD_2_SHIFT (4U)
#define S16UP_U_TX_X1_CONTROL0_UPMD_OSR_MODE_PMD_1_MASK (0xfU)
#define S16UP_U_TX_X1_CONTROL0_UPMD_OSR_MODE_PMD_1_SHIFT (0U)




typedef uint16_t S16UP_U_TX_X1_CONTROL0_UT_ENC_TYPE;
#define S16UP_U_TX_X1_CONTROL0_UT_ENC_SMD_CONFIG1_EN_MASK (0x8000U)
#define S16UP_U_TX_X1_CONTROL0_UT_ENC_SMD_CONFIG1_EN_SHIFT (15U)
#define S16UP_U_TX_X1_CONTROL0_UT_ENC_SMD_CONFIG0_EN_MASK (0x4000U)
#define S16UP_U_TX_X1_CONTROL0_UT_ENC_SMD_CONFIG0_EN_SHIFT (14U)
#define S16UP_U_TX_X1_CONTROL0_UT_ENC_ENCODE_MODE_CUSTOM_MASK (0x1c0U)
#define S16UP_U_TX_X1_CONTROL0_UT_ENC_ENCODE_MODE_CUSTOM_SHIFT (6U)
#define S16UP_U_TX_X1_CONTROL0_UT_ENC_ENCODE_MODE_CL49_MASK (0x38U)
#define S16UP_U_TX_X1_CONTROL0_UT_ENC_ENCODE_MODE_CL49_SHIFT (3U)
#define S16UP_U_TX_X1_CONTROL0_UT_ENC_ENCODE_MODE_CL36_MASK (0x7U)
#define S16UP_U_TX_X1_CONTROL0_UT_ENC_ENCODE_MODE_CL36_SHIFT (0U)




typedef uint16_t S16UP_U_TX_X1_CONTROL0_UT_SCR_TYPE;
#define S16UP_U_TX_X1_CONTROL0_UT_SCR_T_MODE_CUSTOM_MASK (0x30U)
#define S16UP_U_TX_X1_CONTROL0_UT_SCR_T_MODE_CUSTOM_SHIFT (4U)
#define S16UP_U_TX_X1_CONTROL0_UT_SCR_T_MODE_64B_MASK (0xcU)
#define S16UP_U_TX_X1_CONTROL0_UT_SCR_T_MODE_64B_SHIFT (2U)
#define S16UP_U_TX_X1_CONTROL0_UT_SCR_T_MODE_BYPASS_MASK (0x3U)
#define S16UP_U_TX_X1_CONTROL0_UT_SCR_T_MODE_BYPASS_SHIFT (0U)




typedef uint16_t S16UP_U_TX_X1_CONTROL0_UPMD_OSR_MODE_2_TYPE;
#define S16UP_U_TX_X1_CONTROL0_UPMD_OSR_MODE_2_CL73_MASK (0xf000U)
#define S16UP_U_TX_X1_CONTROL0_UPMD_OSR_MODE_2_CL73_SHIFT (12U)




typedef uint16_t S16UP_U_TX_X1_CONTROL0_UCW1_TYPE;
#define S16UP_U_TX_X1_CONTROL0_UCW1_CKCMP_WPTR_DEFAULT_5G_MASK (0x3f80U)
#define S16UP_U_TX_X1_CONTROL0_UCW1_CKCMP_WPTR_DEFAULT_5G_SHIFT (7U)
#define S16UP_U_TX_X1_CONTROL0_UCW1_CKCMP_WPTR_DEFAULT_10G_MASK (0x7fU)
#define S16UP_U_TX_X1_CONTROL0_UCW1_CKCMP_WPTR_DEFAULT_10G_SHIFT (0U)




typedef uint16_t S16UP_U_TX_X1_CONTROL0_UCW2_TYPE;
#define S16UP_U_TX_X1_CONTROL0_UCW2_CKCMP_WPTR_DEFAULT_1G_MASK (0x3f80U)
#define S16UP_U_TX_X1_CONTROL0_UCW2_CKCMP_WPTR_DEFAULT_1G_SHIFT (7U)
#define S16UP_U_TX_X1_CONTROL0_UCW2_CKCMP_WPTR_DEFAULT_2P5G_MASK (0x7fU)
#define S16UP_U_TX_X1_CONTROL0_UCW2_CKCMP_WPTR_DEFAULT_2P5G_SHIFT (0U)




typedef uint16_t S16UP_U_TX_X1_CONTROL0_UCW3_TYPE;
#define S16UP_U_TX_X1_CONTROL0_UCW3_CKCMP_WPTR_DEFAULT_10M_MASK (0x3f80U)
#define S16UP_U_TX_X1_CONTROL0_UCW3_CKCMP_WPTR_DEFAULT_10M_SHIFT (7U)
#define S16UP_U_TX_X1_CONTROL0_UCW3_CKCMP_WPTR_DEFAULT_100M_MASK (0x7fU)
#define S16UP_U_TX_X1_CONTROL0_UCW3_CKCMP_WPTR_DEFAULT_100M_SHIFT (0U)




typedef uint16_t S16UP_U_TX_X1_CONTROL0_UCC1_TYPE;
#define S16UP_U_TX_X1_CONTROL0_UCC1_TX_CKCMP_DELETE_MARGIN_10M_MASK (0xe000U)
#define S16UP_U_TX_X1_CONTROL0_UCC1_TX_CKCMP_DELETE_MARGIN_10M_SHIFT (13U)
#define S16UP_U_TX_X1_CONTROL0_UCC1_SINGLE_IDLE_COL_EN_10G_MASK (0x20U)
#define S16UP_U_TX_X1_CONTROL0_UCC1_SINGLE_IDLE_COL_EN_10G_SHIFT (5U)
#define S16UP_U_TX_X1_CONTROL0_UCC1_SINGLE_IDLE_COL_EN_5G_MASK (0x10U)
#define S16UP_U_TX_X1_CONTROL0_UCC1_SINGLE_IDLE_COL_EN_5G_SHIFT (4U)
#define S16UP_U_TX_X1_CONTROL0_UCC1_SINGLE_IDLE_COL_EN_2P5G_MASK (0x8U)
#define S16UP_U_TX_X1_CONTROL0_UCC1_SINGLE_IDLE_COL_EN_2P5G_SHIFT (3U)
#define S16UP_U_TX_X1_CONTROL0_UCC1_SINGLE_IDLE_COL_EN_1G_MASK (0x4U)
#define S16UP_U_TX_X1_CONTROL0_UCC1_SINGLE_IDLE_COL_EN_1G_SHIFT (2U)
#define S16UP_U_TX_X1_CONTROL0_UCC1_SINGLE_IDLE_COL_EN_100M_MASK (0x2U)
#define S16UP_U_TX_X1_CONTROL0_UCC1_SINGLE_IDLE_COL_EN_100M_SHIFT (1U)
#define S16UP_U_TX_X1_CONTROL0_UCC1_SINGLE_IDLE_COL_EN_10M_MASK (0x1U)
#define S16UP_U_TX_X1_CONTROL0_UCC1_SINGLE_IDLE_COL_EN_10M_SHIFT (0U)




typedef uint16_t S16UP_U_TX_X1_CONTROL0_UCC2_TYPE;
#define S16UP_U_TX_X1_CONTROL0_UCC2_CKCMP_DELETE_MARGIN_100M_MASK (0x7000U)
#define S16UP_U_TX_X1_CONTROL0_UCC2_CKCMP_DELETE_MARGIN_100M_SHIFT (12U)
#define S16UP_U_TX_X1_CONTROL0_UCC2_CKCMP_DELETE_MARGIN_1G_MASK (0xe00U)
#define S16UP_U_TX_X1_CONTROL0_UCC2_CKCMP_DELETE_MARGIN_1G_SHIFT (9U)
#define S16UP_U_TX_X1_CONTROL0_UCC2_CKCMP_DELETE_MARGIN_2P5G_MASK (0x1c0U)
#define S16UP_U_TX_X1_CONTROL0_UCC2_CKCMP_DELETE_MARGIN_2P5G_SHIFT (6U)
#define S16UP_U_TX_X1_CONTROL0_UCC2_CKCMP_DELETE_MARGIN_5G_MASK (0x38U)
#define S16UP_U_TX_X1_CONTROL0_UCC2_CKCMP_DELETE_MARGIN_5G_SHIFT (3U)
#define S16UP_U_TX_X1_CONTROL0_UCC2_CKCMP_DELETE_MARGIN_10G_MASK (0x7U)
#define S16UP_U_TX_X1_CONTROL0_UCC2_CKCMP_DELETE_MARGIN_10G_SHIFT (0U)




typedef uint16_t S16UP_U_TX_X1_CONTROL0_UTX_SMD_CONFIG_TYPE;
#define S16UP_U_TX_X1_CONTROL0_UTX_SMD_CONFIG_1_MASK (0xff00U)
#define S16UP_U_TX_X1_CONTROL0_UTX_SMD_CONFIG_1_SHIFT (8U)
#define S16UP_U_TX_X1_CONTROL0_UTX_SMD_CONFIG_0_MASK (0xffU)
#define S16UP_U_TX_X1_CONTROL0_UTX_SMD_CONFIG_0_SHIFT (0U)




typedef volatile struct sS16UP_U_TX_X1_CONTROL0_RDBType {
    S16UP_U_TX_X1_CONTROL0_RESERVED_TYPE rsvd0[8]; /* OFFSET: 0x0 */
    S16UP_U_TX_X1_CONTROL0_UPMD_OSR_MODE_TYPE pmd_osr_mode; /* OFFSET: 0x8 */
    S16UP_U_TX_X1_CONTROL0_RESERVED_TYPE rsvd1[2]; /* OFFSET: 0xa */
    S16UP_U_TX_X1_CONTROL0_UT_ENC_TYPE enc; /* OFFSET: 0xc */
    S16UP_U_TX_X1_CONTROL0_RESERVED_TYPE rsvd2[2]; /* OFFSET: 0xe */
    S16UP_U_TX_X1_CONTROL0_UT_SCR_TYPE scr; /* OFFSET: 0x10 */
    S16UP_U_TX_X1_CONTROL0_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0x12 */
    S16UP_U_TX_X1_CONTROL0_UPMD_OSR_MODE_2_TYPE pmd_osr_mode_2; /* OFFSET: 0x14 */
    S16UP_U_TX_X1_CONTROL0_RESERVED_TYPE rsvd4[2]; /* OFFSET: 0x16 */
    S16UP_U_TX_X1_CONTROL0_UCW1_TYPE tx_ckcmp_wptr_1; /* OFFSET: 0x18 */
    S16UP_U_TX_X1_CONTROL0_RESERVED_TYPE rsvd5[2]; /* OFFSET: 0x1a */
    S16UP_U_TX_X1_CONTROL0_UCW2_TYPE tx_ckcmp_wptr_2; /* OFFSET: 0x1c */
    S16UP_U_TX_X1_CONTROL0_RESERVED_TYPE rsvd6[2]; /* OFFSET: 0x1e */
    S16UP_U_TX_X1_CONTROL0_UCW3_TYPE tx_ckcmp_wptr_3; /* OFFSET: 0x20 */
    S16UP_U_TX_X1_CONTROL0_RESERVED_TYPE rsvd7[2]; /* OFFSET: 0x22 */
    S16UP_U_TX_X1_CONTROL0_UCC1_TYPE tx_ckcmp_ctrl_1; /* OFFSET: 0x24 */
    S16UP_U_TX_X1_CONTROL0_RESERVED_TYPE rsvd8[2]; /* OFFSET: 0x26 */
    S16UP_U_TX_X1_CONTROL0_UCC2_TYPE tx_ckcmp_ctrl_2; /* OFFSET: 0x28 */
    S16UP_U_TX_X1_CONTROL0_RESERVED_TYPE rsvd9[2]; /* OFFSET: 0x2a */
    S16UP_U_TX_X1_CONTROL0_UTX_SMD_CONFIG_TYPE tx_smd_config_type; /* OFFSET: 0x2c */
} S16UP_U_TX_X1_CONTROL0_RDBType;


#define U_TX_X1_CONTROL0_BASE           (0xE04E5000UL)



#define S16UP_U_TX_X1_CONTROL0_MAX_HW_ID  (1UL)

#endif /* S16UP_U_TX_X1_CONTROL0_RDB_H */
