/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file s16up_u_rx_x8_status0_rdb.h
    @brief RDB File for S16UP_U_RX_X8_STATUS0

    @version BCM89580_A0_20230125_RDB
*/

#ifndef S16UP_U_RX_X8_STATUS0_RDB_H
#define S16UP_U_RX_X8_STATUS0_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t S16UP_U_RX_X8_STATUS0_RESERVED_TYPE;




typedef uint16_t S16UP_U_RX_X8_STATUS0_UBARREL_SHIFTER_STATE_TYPE;
#define S16UP_U_RX_X8_STATUS0_UBARREL_SHIFTER_STATE_SHIFT_AMMOUNT_MASK (0xffU)
#define S16UP_U_RX_X8_STATUS0_UBARREL_SHIFTER_STATE_SHIFT_AMMOUNT_SHIFT (0U)




typedef uint16_t S16UP_U_RX_X8_STATUS0_U49LFS_TYPE;
#define S16UP_U_RX_X8_STATUS0_U49LFS_LSM_HIS_STATE_MASK (0x1cU)
#define S16UP_U_RX_X8_STATUS0_U49LFS_LSM_HIS_STATE_SHIFT (2U)
#define S16UP_U_RX_X8_STATUS0_U49LFS_LSM_CURR_STATE_MASK (0x3U)
#define S16UP_U_RX_X8_STATUS0_U49LFS_LSM_CURR_STATE_SHIFT (0U)




typedef uint16_t S16UP_U_RX_X8_STATUS0_US0_TYPE;
#define S16UP_U_RX_X8_STATUS0_US0_CL49_R_TYPE_CODED_MASK (0xf000U)
#define S16UP_U_RX_X8_STATUS0_US0_CL49_R_TYPE_CODED_SHIFT (12U)
#define S16UP_U_RX_X8_STATUS0_US0_CL49_RXSM_HISTORY_STATE_MASK (0x7f8U)
#define S16UP_U_RX_X8_STATUS0_US0_CL49_RXSM_HISTORY_STATE_SHIFT (3U)
#define S16UP_U_RX_X8_STATUS0_US0_CL49_RXSM_CURRENT_STATE_MASK (0x7U)
#define S16UP_U_RX_X8_STATUS0_US0_CL49_RXSM_CURRENT_STATE_SHIFT (0U)




typedef uint16_t S16UP_U_RX_X8_STATUS0_US1_TYPE;
#define S16UP_U_RX_X8_STATUS0_US1_CL49_BERMON_HISTORY_STATE_MASK (0x3e0U)
#define S16UP_U_RX_X8_STATUS0_US1_CL49_BERMON_HISTORY_STATE_SHIFT (5U)
#define S16UP_U_RX_X8_STATUS0_US1_CL49_BERMON_CURRENT_STATE_MASK (0x1fU)
#define S16UP_U_RX_X8_STATUS0_US1_CL49_BERMON_CURRENT_STATE_SHIFT (0U)




typedef uint16_t S16UP_U_RX_X8_STATUS0_UDECODE_STATUS_2_TYPE;
#define S16UP_U_RX_X8_STATUS0_UDECODE_STATUS_2_SYNC66ERRCOUNT_MASK (0xff00U)
#define S16UP_U_RX_X8_STATUS0_UDECODE_STATUS_2_SYNC66ERRCOUNT_SHIFT (8U)
#define S16UP_U_RX_X8_STATUS0_UDECODE_STATUS_2_KCODE66ERRCOUNT_MASK (0xffU)
#define S16UP_U_RX_X8_STATUS0_UDECODE_STATUS_2_KCODE66ERRCOUNT_SHIFT (0U)




typedef uint16_t S16UP_U_RX_X8_STATUS0_US3_TYPE;
#define S16UP_U_RX_X8_STATUS0_US3_CL49IEEE_ERRORED_BLOCKS_MASK (0x3fcU)
#define S16UP_U_RX_X8_STATUS0_US3_CL49IEEE_ERRORED_BLOCKS_SHIFT (2U)




typedef uint16_t S16UP_U_RX_X8_STATUS0_UBERCOUNT_TYPE;
#define S16UP_U_RX_X8_STATUS0_UBERCOUNT_BER_COUNT_PER_LN_MASK (0xffU)
#define S16UP_U_RX_X8_STATUS0_UBERCOUNT_BER_COUNT_PER_LN_SHIFT (0U)




typedef volatile struct sS16UP_U_RX_X8_STATUS0_RDBType {
    S16UP_U_RX_X8_STATUS0_RESERVED_TYPE rsvd0[16]; /* OFFSET: 0x0 */
    S16UP_U_RX_X8_STATUS0_UBARREL_SHIFTER_STATE_TYPE barrel_shifter_state; /* OFFSET: 0x10 */
    S16UP_U_RX_X8_STATUS0_RESERVED_TYPE rsvd1[2]; /* OFFSET: 0x12 */
    S16UP_U_RX_X8_STATUS0_U49LFS_TYPE cl49_lock_fsm_status; /* OFFSET: 0x14 */
    S16UP_U_RX_X8_STATUS0_RESERVED_TYPE rsvd2[2]; /* OFFSET: 0x16 */
    S16UP_U_RX_X8_STATUS0_US0_TYPE decode_status_0; /* OFFSET: 0x18 */
    S16UP_U_RX_X8_STATUS0_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0x1a */
    S16UP_U_RX_X8_STATUS0_US1_TYPE decode_status_1; /* OFFSET: 0x1c */
    S16UP_U_RX_X8_STATUS0_RESERVED_TYPE rsvd4[2]; /* OFFSET: 0x1e */
    S16UP_U_RX_X8_STATUS0_UDECODE_STATUS_2_TYPE decode_status_2; /* OFFSET: 0x20 */
    S16UP_U_RX_X8_STATUS0_RESERVED_TYPE rsvd5[2]; /* OFFSET: 0x22 */
    S16UP_U_RX_X8_STATUS0_US3_TYPE decode_status_3; /* OFFSET: 0x24 */
    S16UP_U_RX_X8_STATUS0_RESERVED_TYPE rsvd6[18]; /* OFFSET: 0x26 */
    S16UP_U_RX_X8_STATUS0_UBERCOUNT_TYPE bercount; /* OFFSET: 0x38 */
} S16UP_U_RX_X8_STATUS0_RDBType;


#define U_RX_X8_STATUS0_BASE            (0xE04F1980UL)



#define S16UP_U_RX_X8_STATUS0_MAX_HW_ID  (1UL)

#endif /* S16UP_U_RX_X8_STATUS0_RDB_H */
