/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file s16up_u_pcs_main1_rdb.h
    @brief RDB File for S16UP_U_PCS_MAIN1

    @version BCM89580_A0_20230125_RDB
*/

#ifndef S16UP_U_PCS_MAIN1_RDB_H
#define S16UP_U_PCS_MAIN1_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t S16UP_U_PCS_MAIN1_UAM0_B1_B0_TYPE;
#define S16UP_U_PCS_MAIN1_UAM0_B1_B0_AM0_B1_MASK (0xff00U)
#define S16UP_U_PCS_MAIN1_UAM0_B1_B0_AM0_B1_SHIFT (8U)
#define S16UP_U_PCS_MAIN1_UAM0_B1_B0_AM0_B0_MASK (0xffU)
#define S16UP_U_PCS_MAIN1_UAM0_B1_B0_AM0_B0_SHIFT (0U)




typedef uint8_t S16UP_U_PCS_MAIN1_RESERVED_TYPE;




typedef uint16_t S16UP_U_PCS_MAIN1_UAM1_B1_B0_TYPE;
#define S16UP_U_PCS_MAIN1_UAM1_B1_B0_AM1_B1_MASK (0xff00U)
#define S16UP_U_PCS_MAIN1_UAM1_B1_B0_AM1_B1_SHIFT (8U)
#define S16UP_U_PCS_MAIN1_UAM1_B1_B0_AM1_B0_MASK (0xffU)
#define S16UP_U_PCS_MAIN1_UAM1_B1_B0_AM1_B0_SHIFT (0U)




typedef uint16_t S16UP_U_PCS_MAIN1_UAM2_B1_B0_TYPE;
#define S16UP_U_PCS_MAIN1_UAM2_B1_B0_AM2_B1_MASK (0xff00U)
#define S16UP_U_PCS_MAIN1_UAM2_B1_B0_AM2_B1_SHIFT (8U)
#define S16UP_U_PCS_MAIN1_UAM2_B1_B0_AM2_B0_MASK (0xffU)
#define S16UP_U_PCS_MAIN1_UAM2_B1_B0_AM2_B0_SHIFT (0U)




typedef uint16_t S16UP_U_PCS_MAIN1_UAM3_B1_B0_TYPE;
#define S16UP_U_PCS_MAIN1_UAM3_B1_B0_AM3_B1_MASK (0xff00U)
#define S16UP_U_PCS_MAIN1_UAM3_B1_B0_AM3_B1_SHIFT (8U)
#define S16UP_U_PCS_MAIN1_UAM3_B1_B0_AM3_B0_MASK (0xffU)
#define S16UP_U_PCS_MAIN1_UAM3_B1_B0_AM3_B0_SHIFT (0U)




typedef uint16_t S16UP_U_PCS_MAIN1_UAM1_AM0_B2_TYPE;
#define S16UP_U_PCS_MAIN1_UAM1_AM0_B2_AM1_B2_MASK (0xff00U)
#define S16UP_U_PCS_MAIN1_UAM1_AM0_B2_AM1_B2_SHIFT (8U)
#define S16UP_U_PCS_MAIN1_UAM1_AM0_B2_AM0_B2_MASK (0xffU)
#define S16UP_U_PCS_MAIN1_UAM1_AM0_B2_AM0_B2_SHIFT (0U)




typedef uint16_t S16UP_U_PCS_MAIN1_UAM3_AM2_B2_TYPE;
#define S16UP_U_PCS_MAIN1_UAM3_AM2_B2_AM3_B2_MASK (0xff00U)
#define S16UP_U_PCS_MAIN1_UAM3_AM2_B2_AM3_B2_SHIFT (8U)
#define S16UP_U_PCS_MAIN1_UAM3_AM2_B2_AM2_B2_MASK (0xffU)
#define S16UP_U_PCS_MAIN1_UAM3_AM2_B2_AM2_B2_SHIFT (0U)




typedef uint16_t S16UP_U_PCS_MAIN1_UAM_PORT_CTRL_TYPE;
#define S16UP_U_PCS_MAIN1_UAM_PORT_CTRL_AM3_PORT_NUM_MASK (0xe00U)
#define S16UP_U_PCS_MAIN1_UAM_PORT_CTRL_AM3_PORT_NUM_SHIFT (9U)
#define S16UP_U_PCS_MAIN1_UAM_PORT_CTRL_AM2_PORT_NUM_MASK (0x1c0U)
#define S16UP_U_PCS_MAIN1_UAM_PORT_CTRL_AM2_PORT_NUM_SHIFT (6U)
#define S16UP_U_PCS_MAIN1_UAM_PORT_CTRL_AM1_PORT_NUM_MASK (0x38U)
#define S16UP_U_PCS_MAIN1_UAM_PORT_CTRL_AM1_PORT_NUM_SHIFT (3U)
#define S16UP_U_PCS_MAIN1_UAM_PORT_CTRL_AM0_PORT_NUM_MASK (0x7U)
#define S16UP_U_PCS_MAIN1_UAM_PORT_CTRL_AM0_PORT_NUM_SHIFT (0U)




typedef volatile struct sS16UP_U_PCS_MAIN1_RDBType {
    S16UP_U_PCS_MAIN1_UAM0_B1_B0_TYPE am0_b1_b0; /* OFFSET: 0x0 */
    S16UP_U_PCS_MAIN1_RESERVED_TYPE rsvd0[2]; /* OFFSET: 0x2 */
    S16UP_U_PCS_MAIN1_UAM1_B1_B0_TYPE am1_b1_b0; /* OFFSET: 0x4 */
    S16UP_U_PCS_MAIN1_RESERVED_TYPE rsvd1[2]; /* OFFSET: 0x6 */
    S16UP_U_PCS_MAIN1_UAM2_B1_B0_TYPE am2_b1_b0; /* OFFSET: 0x8 */
    S16UP_U_PCS_MAIN1_RESERVED_TYPE rsvd2[2]; /* OFFSET: 0xa */
    S16UP_U_PCS_MAIN1_UAM3_B1_B0_TYPE am3_b1_b0; /* OFFSET: 0xc */
    S16UP_U_PCS_MAIN1_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0xe */
    S16UP_U_PCS_MAIN1_UAM1_AM0_B2_TYPE am1_am0_b2; /* OFFSET: 0x10 */
    S16UP_U_PCS_MAIN1_RESERVED_TYPE rsvd4[2]; /* OFFSET: 0x12 */
    S16UP_U_PCS_MAIN1_UAM3_AM2_B2_TYPE am3_am2_b2; /* OFFSET: 0x14 */
    S16UP_U_PCS_MAIN1_RESERVED_TYPE rsvd5[2]; /* OFFSET: 0x16 */
    S16UP_U_PCS_MAIN1_UAM_PORT_CTRL_TYPE am_port_ctrl; /* OFFSET: 0x18 */
} S16UP_U_PCS_MAIN1_RDBType;


#define U_PCS_MAIN1_BASE                (0xE04E4C40UL)



#define S16UP_U_PCS_MAIN1_MAX_HW_ID     (1UL)

#endif /* S16UP_U_PCS_MAIN1_RDB_H */
