/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file s16up_mdio_mmdsel_aer_com_rdb.h
    @brief RDB File for S16UP_MDIO_MMDSEL_AER_COM

    @version BCM89580_A0_20230125_RDB
*/

#ifndef S16UP_MDIO_MMDSEL_AER_COM_RDB_H
#define S16UP_MDIO_MMDSEL_AER_COM_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t S16UP_MDIO_MMDSEL_AER_COM_RESERVED_TYPE;




typedef uint16_t S16UP_MDIO_MMDSEL_AER_COM_BRCS_PORT_ADDR_TYPE;
#define S16UP_MDIO_MMDSEL_AER_COM_BRCS_PORT_ADDR_MDIO_DRV_COMCLK_MASK (0x8000U)
#define S16UP_MDIO_MMDSEL_AER_COM_BRCS_PORT_ADDR_MDIO_DRV_COMCLK_SHIFT (15U)
#define S16UP_MDIO_MMDSEL_AER_COM_BRCS_PORT_ADDR_MBPA_MASK (0x1fU)
#define S16UP_MDIO_MMDSEL_AER_COM_BRCS_PORT_ADDR_MBPA_SHIFT (0U)




typedef uint16_t S16UP_MDIO_MMDSEL_AER_COM_MMDSELECT_TYPE;
#define S16UP_MDIO_MMDSEL_AER_COM_MMDSELECT_MULTI_PRTS_EN_MASK (0x8000U)
#define S16UP_MDIO_MMDSEL_AER_COM_MMDSELECT_MULTI_PRTS_EN_SHIFT (15U)
#define S16UP_MDIO_MMDSEL_AER_COM_MMDSELECT_MULTI_MMDS_EN_MASK (0x4000U)
#define S16UP_MDIO_MMDSEL_AER_COM_MMDSELECT_MULTI_MMDS_EN_SHIFT (14U)
#define S16UP_MDIO_MMDSEL_AER_COM_MMDSELECT_DEV_PCS_EN_MASK (0x40U)
#define S16UP_MDIO_MMDSEL_AER_COM_MMDSELECT_DEV_PCS_EN_SHIFT (6U)
#define S16UP_MDIO_MMDSEL_AER_COM_MMDSELECT_DEV_DTE_EN_MASK (0x20U)
#define S16UP_MDIO_MMDSEL_AER_COM_MMDSELECT_DEV_DTE_EN_SHIFT (5U)
#define S16UP_MDIO_MMDSEL_AER_COM_MMDSELECT_DEV_PHY_EN_MASK (0x10U)
#define S16UP_MDIO_MMDSEL_AER_COM_MMDSELECT_DEV_PHY_EN_SHIFT (4U)
#define S16UP_MDIO_MMDSEL_AER_COM_MMDSELECT_DEV_AN_EN_MASK (0x8U)
#define S16UP_MDIO_MMDSEL_AER_COM_MMDSELECT_DEV_AN_EN_SHIFT (3U)
#define S16UP_MDIO_MMDSEL_AER_COM_MMDSELECT_DEV_PMD_EN_MASK (0x4U)
#define S16UP_MDIO_MMDSEL_AER_COM_MMDSELECT_DEV_PMD_EN_SHIFT (2U)
#define S16UP_MDIO_MMDSEL_AER_COM_MMDSELECT_DEV_ID0_EN_MASK (0x1U)
#define S16UP_MDIO_MMDSEL_AER_COM_MMDSELECT_DEV_ID0_EN_SHIFT (0U)




typedef uint16_t S16UP_MDIO_MMDSEL_AER_COM_AER_TYPE;
#define S16UP_MDIO_MMDSEL_AER_COM_AER_MASK (0xffffU)
#define S16UP_MDIO_MMDSEL_AER_COM_AER_SHIFT (0U)




typedef volatile struct sS16UP_MDIO_MMDSEL_AER_COM_RDBType {
    S16UP_MDIO_MMDSEL_AER_COM_RESERVED_TYPE rsvd0[48]; /* OFFSET: 0x0 */
    S16UP_MDIO_MMDSEL_AER_COM_BRCS_PORT_ADDR_TYPE brcst_port_addr; /* OFFSET: 0x30 */
    S16UP_MDIO_MMDSEL_AER_COM_RESERVED_TYPE rsvd1[2]; /* OFFSET: 0x32 */
    S16UP_MDIO_MMDSEL_AER_COM_MMDSELECT_TYPE mmd_select; /* OFFSET: 0x34 */
    S16UP_MDIO_MMDSEL_AER_COM_RESERVED_TYPE rsvd2[2]; /* OFFSET: 0x36 */
    S16UP_MDIO_MMDSEL_AER_COM_AER_TYPE aer; /* OFFSET: 0x38 */
} S16UP_MDIO_MMDSEL_AER_COM_RDBType;


#define AERBLK_BASE                     (0xE047FF40UL)



#define S16UP_MDIO_MMDSEL_AER_COM_MAX_HW_ID  (1UL)

#endif /* S16UP_MDIO_MMDSEL_AER_COM_RDB_H */
