/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file s16up_rx2ln_pcs_rdb.h
    @brief RDB File for S16UP_RX2LN_PCS

    @version BCM89580_A0_20230125_RDB
*/

#ifndef S16UP_RX2LN_PCS_RDB_H
#define S16UP_RX2LN_PCS_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t S16UP_RX2LN_PCS_FX100_RXCONTROL1_TYPE;
#define S16UP_RX2LN_PCS_FX100_RXCONTROL1_RXDATA_SEL_MASK (0x3c0U)
#define S16UP_RX2LN_PCS_FX100_RXCONTROL1_RXDATA_SEL_SHIFT (6U)
#define S16UP_RX2LN_PCS_FX100_RXCONTROL1_FULL_DUPLEX_MASK (0x2U)
#define S16UP_RX2LN_PCS_FX100_RXCONTROL1_FULL_DUPLEX_SHIFT (1U)




typedef uint8_t S16UP_RX2LN_PCS_RESERVED_TYPE;




typedef uint16_t S16UP_RX2LN_PCS_FX100_RXCONTROL3_TYPE;
#define S16UP_RX2LN_PCS_FX100_RXCONTROL3_NUMBER_OF_IDLE_MASK (0xff00U)
#define S16UP_RX2LN_PCS_FX100_RXCONTROL3_NUMBER_OF_IDLE_SHIFT (8U)
#define S16UP_RX2LN_PCS_FX100_RXCONTROL3_CORRELATOR_DISABLE_MASK (0x80U)
#define S16UP_RX2LN_PCS_FX100_RXCONTROL3_CORRELATOR_DISABLE_SHIFT (7U)




typedef uint16_t S16UP_RX2LN_PCS_RX_CL127_CTRL_TYPE;
#define S16UP_RX2LN_PCS_RX_CL127_CTRL_RX_CL127_EN_MASK (0x800U)
#define S16UP_RX2LN_PCS_RX_CL127_CTRL_RX_CL127_EN_SHIFT (11U)
#define S16UP_RX2LN_PCS_RX_CL127_CTRL_RX_ALIGN_FSM_RESET_MASK (0x400U)
#define S16UP_RX2LN_PCS_RX_CL127_CTRL_RX_ALIGN_FSM_RESET_SHIFT (10U)
#define S16UP_RX2LN_PCS_RX_CL127_CTRL_CL127_RX_BUF_BUF_LOW_LN_MASK (0x3e0U)
#define S16UP_RX2LN_PCS_RX_CL127_CTRL_CL127_RX_BUF_BUF_LOW_LN_SHIFT (5U)
#define S16UP_RX2LN_PCS_RX_CL127_CTRL_CL127_RX_BUF_BUF_LMT_LN_MASK (0x1fU)
#define S16UP_RX2LN_PCS_RX_CL127_CTRL_CL127_RX_BUF_BUF_LMT_LN_SHIFT (0U)




typedef uint16_t S16UP_RX2LN_PCS_RX_CL127_STATUS_TYPE;
#define S16UP_RX2LN_PCS_RX_CL127_STATUS_WORD_ALIGN_MASK (0xff00U)
#define S16UP_RX2LN_PCS_RX_CL127_STATUS_WORD_ALIGN_SHIFT (8U)
#define S16UP_RX2LN_PCS_RX_CL127_STATUS_WORD_ENCODE_MASK (0xffU)
#define S16UP_RX2LN_PCS_RX_CL127_STATUS_WORD_ENCODE_SHIFT (0U)




typedef uint16_t S16UP_RX2LN_PCS_RMIC_TYPE;
#define S16UP_RX2LN_PCS_RMIC_GMII_FILTER_EN_OV_EN_MASK (0x8U)
#define S16UP_RX2LN_PCS_RMIC_GMII_FILTER_EN_OV_EN_SHIFT (3U)
#define S16UP_RX2LN_PCS_RMIC_GMII_FILTER_EN_OV_MASK (0x4U)
#define S16UP_RX2LN_PCS_RMIC_GMII_FILTER_EN_OV_SHIFT (2U)
#define S16UP_RX2LN_PCS_RMIC_FILTER_CE_EN_MASK (0x2U)
#define S16UP_RX2LN_PCS_RMIC_FILTER_CE_EN_SHIFT (1U)
#define S16UP_RX2LN_PCS_RMIC_R_MAC_INTF_PKT_CNT_PRESET_MASK (0x1U)
#define S16UP_RX2LN_PCS_RMIC_R_MAC_INTF_PKT_CNT_PRESET_SHIFT (0U)




typedef uint16_t S16UP_RX2LN_PCS_RMIPCL_TYPE;
#define S16UP_RX2LN_PCS_RMIPCL_R_MAC_INTF_PKT_CNT_LOW_MASK (0xffffU)
#define S16UP_RX2LN_PCS_RMIPCL_R_MAC_INTF_PKT_CNT_LOW_SHIFT (0U)




typedef uint16_t S16UP_RX2LN_PCS_RMIPCU_TYPE;
#define S16UP_RX2LN_PCS_RMIPCU_R_MAC_INTF_PKT_CNT_UP_MASK (0xffffU)
#define S16UP_RX2LN_PCS_RMIPCU_R_MAC_INTF_PKT_CNT_UP_SHIFT (0U)




typedef uint16_t S16UP_RX2LN_PCS_R_MAC_INTF_PKT_STAT0_TYPE;
#define S16UP_RX2LN_PCS_R_MAC_INTF_PKT_STAT0_MASK (0xffffU)
#define S16UP_RX2LN_PCS_R_MAC_INTF_PKT_STAT0_SHIFT (0U)




typedef uint16_t S16UP_RX2LN_PCS_R_MAC_INTF_PKT_STAT1_TYPE;
#define S16UP_RX2LN_PCS_R_MAC_INTF_PKT_STAT1_MASK (0xffffU)
#define S16UP_RX2LN_PCS_R_MAC_INTF_PKT_STAT1_SHIFT (0U)




typedef volatile struct sS16UP_RX2LN_PCS_RDBType {
    S16UP_RX2LN_PCS_FX100_RXCONTROL1_TYPE fx100_rxcontrol1; /* OFFSET: 0x0 */
    S16UP_RX2LN_PCS_RESERVED_TYPE rsvd0[6]; /* OFFSET: 0x2 */
    S16UP_RX2LN_PCS_FX100_RXCONTROL3_TYPE fx100_rxcontrol3; /* OFFSET: 0x8 */
    S16UP_RX2LN_PCS_RESERVED_TYPE rsvd1[22]; /* OFFSET: 0xa */
    S16UP_RX2LN_PCS_RX_CL127_CTRL_TYPE rx_cl127_ctrl; /* OFFSET: 0x20 */
    S16UP_RX2LN_PCS_RESERVED_TYPE rsvd2[2]; /* OFFSET: 0x22 */
    S16UP_RX2LN_PCS_RX_CL127_STATUS_TYPE rx_cl127_status; /* OFFSET: 0x24 */
    S16UP_RX2LN_PCS_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0x26 */
    S16UP_RX2LN_PCS_RMIC_TYPE r_mac_intf_control; /* OFFSET: 0x28 */
    S16UP_RX2LN_PCS_RESERVED_TYPE rsvd4[2]; /* OFFSET: 0x2a */
    S16UP_RX2LN_PCS_RMIPCL_TYPE r_mac_intf_pkt_cnt_low; /* OFFSET: 0x2c */
    S16UP_RX2LN_PCS_RESERVED_TYPE rsvd5[2]; /* OFFSET: 0x2e */
    S16UP_RX2LN_PCS_RMIPCU_TYPE r_mac_intf_pkt_cnt_up; /* OFFSET: 0x30 */
    S16UP_RX2LN_PCS_RESERVED_TYPE rsvd6[2]; /* OFFSET: 0x32 */
    S16UP_RX2LN_PCS_R_MAC_INTF_PKT_STAT0_TYPE r_mac_intf_pkt_stat0; /* OFFSET: 0x34 */
    S16UP_RX2LN_PCS_RESERVED_TYPE rsvd7[2]; /* OFFSET: 0x36 */
    S16UP_RX2LN_PCS_R_MAC_INTF_PKT_STAT1_TYPE r_mac_intf_pkt_stat1; /* OFFSET: 0x38 */
} S16UP_RX2LN_PCS_RDBType;


#define RX_PCS_REG2_BASE                (0xE04E0380UL)



#define S16UP_RX2LN_PCS_MAX_HW_ID       (1UL)

#endif /* S16UP_RX2LN_PCS_RDB_H */
