/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file s16up_ana_pmd_pmdcom_blk0_rdb.h
    @brief RDB File for S16UP_ANA_PMD_PMDCOM_BLK0

    @version BCM89580_A0_20230125_RDB
*/

#ifndef S16UP_ANA_PMD_PMDCOM_BLK0_RDB_H
#define S16UP_ANA_PMD_PMDCOM_BLK0_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t S16UP_ANA_PMD_PMDCOM_BLK0_ANA_PMD_CTRL0_TYPE;
#define S16UP_ANA_PMD_PMDCOM_BLK0_ANA_PMD_CTRL0_PMD_RG_PLL_RSTB_MASK (0x200U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_ANA_PMD_CTRL0_PMD_RG_PLL_RSTB_SHIFT (9U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_ANA_PMD_CTRL0_PMD_RG_MAIN_RSTB_MASK (0x100U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_ANA_PMD_CTRL0_PMD_RG_MAIN_RSTB_SHIFT (8U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_ANA_PMD_CTRL0_ARRRO_MASK (0x80U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_ANA_PMD_CTRL0_ARRRO_SHIFT (7U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_ANA_PMD_CTRL0_ARRR_MASK (0x40U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_ANA_PMD_CTRL0_ARRR_SHIFT (6U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_ANA_PMD_CTRL0_ARVRO_MASK (0x20U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_ANA_PMD_CTRL0_ARVRO_SHIFT (5U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_ANA_PMD_CTRL0_ARVR_MASK (0x10U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_ANA_PMD_CTRL0_ARVR_SHIFT (4U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_ANA_PMD_CTRL0_ARPSRO_MASK (0x8U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_ANA_PMD_CTRL0_ARPSRO_SHIFT (3U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_ANA_PMD_CTRL0_ARPSR_MASK (0x4U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_ANA_PMD_CTRL0_ARPSR_SHIFT (2U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_ANA_PMD_CTRL0_ARPPO_MASK (0x2U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_ANA_PMD_CTRL0_ARPPO_SHIFT (1U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_ANA_PMD_CTRL0_ANA_RG_PLL_PD_MASK (0x1U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_ANA_PMD_CTRL0_ANA_RG_PLL_PD_SHIFT (0U)




typedef uint8_t S16UP_ANA_PMD_PMDCOM_BLK0_RESERVED_TYPE;




typedef uint16_t S16UP_ANA_PMD_PMDCOM_BLK0_TICK_CTRL0_TYPE;
#define S16UP_ANA_PMD_PMDCOM_BLK0_TICK_CTRL0_NUMERATOR_MASK (0xffffU)
#define S16UP_ANA_PMD_PMDCOM_BLK0_TICK_CTRL0_NUMERATOR_SHIFT (0U)




typedef uint16_t S16UP_ANA_PMD_PMDCOM_BLK0_TICK_MISC_CTRL1_TYPE;
#define S16UP_ANA_PMD_PMDCOM_BLK0_TICK_MISC_CTRL1_OVERRIDE_MASK (0x100U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_TICK_MISC_CTRL1_OVERRIDE_SHIFT (8U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_TICK_MISC_CTRL1_DENO_MASK (0xffU)
#define S16UP_ANA_PMD_PMDCOM_BLK0_TICK_MISC_CTRL1_DENO_SHIFT (0U)




typedef uint16_t S16UP_ANA_PMD_PMDCOM_BLK0_CAL_DLY_CTRL1_TYPE;
#define S16UP_ANA_PMD_PMDCOM_BLK0_CAL_DLY_CTRL1_PRE_VCO_MASK (0xff00U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_CAL_DLY_CTRL1_PRE_VCO_SHIFT (8U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_CAL_DLY_CTRL1_POST_VCO_MASK (0xffU)
#define S16UP_ANA_PMD_PMDCOM_BLK0_CAL_DLY_CTRL1_POST_VCO_SHIFT (0U)




typedef uint16_t S16UP_ANA_PMD_PMDCOM_BLK0_RES_CAL_LMTO_TYPE;
#define S16UP_ANA_PMD_PMDCOM_BLK0_RES_CAL_LMTO_AMPMD_MASK (0x7000U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_RES_CAL_LMTO_AMPMD_SHIFT (12U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_RES_CAL_LMTO_AMCBV_MASK (0x800U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_RES_CAL_LMTO_AMCBV_SHIFT (11U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_RES_CAL_LMTO_AMCRA_MASK (0x400U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_RES_CAL_LMTO_AMCRA_SHIFT (10U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_RES_CAL_LMTO_AMCRV_MASK (0x200U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_RES_CAL_LMTO_AMCRV_SHIFT (9U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_RES_CAL_LMTO_ARRCOE_MASK (0x100U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_RES_CAL_LMTO_ARRCOE_SHIFT (8U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_RES_CAL_LMTO_ARRCOV_MASK (0xf0U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_RES_CAL_LMTO_ARRCOV_SHIFT (4U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_RES_CAL_LMTO_ANA_RG_RES_CAL_DFS_MASK (0xfU)
#define S16UP_ANA_PMD_PMDCOM_BLK0_RES_CAL_LMTO_ANA_RG_RES_CAL_DFS_SHIFT (0U)




typedef uint16_t S16UP_ANA_PMD_PMDCOM_BLK0_PLL_CTRL_AFE0_0_TYPE;
#define S16UP_ANA_PMD_PMDCOM_BLK0_PLL_CTRL_AFE0_0_AMPCA00_MASK (0xffffU)
#define S16UP_ANA_PMD_PMDCOM_BLK0_PLL_CTRL_AFE0_0_AMPCA00_SHIFT (0U)




typedef uint16_t S16UP_ANA_PMD_PMDCOM_BLK0_PLL_CTRL_AFE0_1_TYPE;
#define S16UP_ANA_PMD_PMDCOM_BLK0_PLL_CTRL_AFE0_1_AMPCA01_MASK (0xffffU)
#define S16UP_ANA_PMD_PMDCOM_BLK0_PLL_CTRL_AFE0_1_AMPCA01_SHIFT (0U)




typedef uint16_t S16UP_ANA_PMD_PMDCOM_BLK0_PNFD_TYPE;
#define S16UP_ANA_PMD_PMDCOM_BLK0_PNFD_MDIO_PLL_NDIV_FRAC_DFS_MASK (0xffffU)
#define S16UP_ANA_PMD_PMDCOM_BLK0_PNFD_MDIO_PLL_NDIV_FRAC_DFS_SHIFT (0U)




typedef uint16_t S16UP_ANA_PMD_PMDCOM_BLK0_APPPM0_TYPE;
#define S16UP_ANA_PMD_PMDCOM_BLK0_APPPM0_AMPFMD_MASK (0x3000U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_APPPM0_AMPFMD_SHIFT (12U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_APPPM0_AMPNID_MASK (0xffcU)
#define S16UP_ANA_PMD_PMDCOM_BLK0_APPPM0_AMPNID_SHIFT (2U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_APPPM0_AMPNFDMB_MASK (0x3U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_APPPM0_AMPNFDMB_SHIFT (0U)




typedef uint16_t S16UP_ANA_PMD_PMDCOM_BLK0_APPPM1_TYPE;
#define S16UP_ANA_PMD_PMDCOM_BLK0_APPPM1_ANA_MDIO_PLL_RANGE_OVRD_MASK (0x4000U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_APPPM1_ANA_MDIO_PLL_RANGE_OVRD_SHIFT (14U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_APPPM1_AMPROV_MASK (0x3f80U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_APPPM1_AMPROV_SHIFT (7U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_APPPM1_ANA_MDIO_PLL_RANGE_DFS_MASK (0x7fU)
#define S16UP_ANA_PMD_PMDCOM_BLK0_APPPM1_ANA_MDIO_PLL_RANGE_DFS_SHIFT (0U)




typedef uint16_t S16UP_ANA_PMD_PMDCOM_BLK0_APPPM2_TYPE;
#define S16UP_ANA_PMD_PMDCOM_BLK0_APPPM2_AMVVO_MASK (0x2000U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_APPPM2_AMVVO_SHIFT (13U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_APPPM2_AMVVOV_MASK (0x1000U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_APPPM2_AMVVOV_SHIFT (12U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_APPPM2_AMPP_MASK (0x800U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_APPPM2_AMPP_SHIFT (11U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_APPPM2_AMPVRD_MASK (0x7f0U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_APPPM2_AMPVRD_SHIFT (4U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_APPPM2_AMPCTE_MASK (0x8U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_APPPM2_AMPCTE_SHIFT (3U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_APPPM2_AMPCTS_MASK (0x7U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_APPPM2_AMPCTS_SHIFT (0U)




typedef uint16_t S16UP_ANA_PMD_PMDCOM_BLK0_APPPM3_TYPE;
#define S16UP_ANA_PMD_PMDCOM_BLK0_APPPM3_LN_OFFSET_STRAP_MASK (0xf80U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_APPPM3_LN_OFFSET_STRAP_SHIFT (7U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_APPPM3_PWRDN_CLKS_EN_MASK (0x40U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_APPPM3_PWRDN_CLKS_EN_SHIFT (6U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_APPPM3_RLPBK_SW_FORCE_MASK (0x20U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_APPPM3_RLPBK_SW_FORCE_SHIFT (5U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_APPPM3_LFCK_BYPASS_MASK (0x10U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_APPPM3_LFCK_BYPASS_SHIFT (4U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_APPPM3_RX1G_MODE_LN0_MASK (0xcU)
#define S16UP_ANA_PMD_PMDCOM_BLK0_APPPM3_RX1G_MODE_LN0_SHIFT (2U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_APPPM3_PRFCS_MASK (0x2U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_APPPM3_PRFCS_SHIFT (1U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_APPPM3_PTFCS_MASK (0x1U)
#define S16UP_ANA_PMD_PMDCOM_BLK0_APPPM3_PTFCS_SHIFT (0U)




typedef volatile struct sS16UP_ANA_PMD_PMDCOM_BLK0_RDBType {
    S16UP_ANA_PMD_PMDCOM_BLK0_ANA_PMD_CTRL0_TYPE ana_pmd_ctrl0; /* OFFSET: 0x0 */
    S16UP_ANA_PMD_PMDCOM_BLK0_RESERVED_TYPE rsvd0[2]; /* OFFSET: 0x2 */
    S16UP_ANA_PMD_PMDCOM_BLK0_TICK_CTRL0_TYPE tick_ctrl0; /* OFFSET: 0x4 */
    S16UP_ANA_PMD_PMDCOM_BLK0_RESERVED_TYPE rsvd1[2]; /* OFFSET: 0x6 */
    S16UP_ANA_PMD_PMDCOM_BLK0_TICK_MISC_CTRL1_TYPE tick_misc_ctrl1; /* OFFSET: 0x8 */
    S16UP_ANA_PMD_PMDCOM_BLK0_RESERVED_TYPE rsvd2[2]; /* OFFSET: 0xa */
    S16UP_ANA_PMD_PMDCOM_BLK0_CAL_DLY_CTRL1_TYPE cal_dly_ctrl1; /* OFFSET: 0xc */
    S16UP_ANA_PMD_PMDCOM_BLK0_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0xe */
    S16UP_ANA_PMD_PMDCOM_BLK0_RES_CAL_LMTO_TYPE res_cal_lmtoff; /* OFFSET: 0x10 */
    S16UP_ANA_PMD_PMDCOM_BLK0_RESERVED_TYPE rsvd4[2]; /* OFFSET: 0x12 */
    S16UP_ANA_PMD_PMDCOM_BLK0_PLL_CTRL_AFE0_0_TYPE pll_ctrl_afe0_0; /* OFFSET: 0x14 */
    S16UP_ANA_PMD_PMDCOM_BLK0_RESERVED_TYPE rsvd5[2]; /* OFFSET: 0x16 */
    S16UP_ANA_PMD_PMDCOM_BLK0_PLL_CTRL_AFE0_1_TYPE pll_ctrl_afe0_1; /* OFFSET: 0x18 */
    S16UP_ANA_PMD_PMDCOM_BLK0_RESERVED_TYPE rsvd6[2]; /* OFFSET: 0x1a */
    S16UP_ANA_PMD_PMDCOM_BLK0_PNFD_TYPE pll_ndiv_frac_dfs; /* OFFSET: 0x1c */
    S16UP_ANA_PMD_PMDCOM_BLK0_RESERVED_TYPE rsvd7[2]; /* OFFSET: 0x1e */
    S16UP_ANA_PMD_PMDCOM_BLK0_APPPM0_TYPE ana_pmd_pmdcom_pll_misc0; /* OFFSET: 0x20 */
    S16UP_ANA_PMD_PMDCOM_BLK0_RESERVED_TYPE rsvd8[2]; /* OFFSET: 0x22 */
    S16UP_ANA_PMD_PMDCOM_BLK0_APPPM1_TYPE ana_pmd_pmdcom_pll_misc1; /* OFFSET: 0x24 */
    S16UP_ANA_PMD_PMDCOM_BLK0_RESERVED_TYPE rsvd9[2]; /* OFFSET: 0x26 */
    S16UP_ANA_PMD_PMDCOM_BLK0_APPPM2_TYPE ana_pmd_pmdcom_pll_misc2; /* OFFSET: 0x28 */
    S16UP_ANA_PMD_PMDCOM_BLK0_RESERVED_TYPE rsvd10[2]; /* OFFSET: 0x2a */
    S16UP_ANA_PMD_PMDCOM_BLK0_APPPM3_TYPE ana_pmd_pmdcom_pll_misc3; /* OFFSET: 0x2c */
} S16UP_ANA_PMD_PMDCOM_BLK0_RDBType;


#define ANA_PMD_PMDCOM_BLK0_BASE        (0xE0468340UL)



#define S16UP_ANA_PMD_PMDCOM_BLK0_MAX_HW_ID  (1UL)

#endif /* S16UP_ANA_PMD_PMDCOM_BLK0_RDB_H */
