/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file s16up_u_rx_x8_status1_rdb.h
    @brief RDB File for S16UP_U_RX_X8_STATUS1

    @version BCM89580_A0_20230125_RDB
*/

#ifndef S16UP_U_RX_X8_STATUS1_RDB_H
#define S16UP_U_RX_X8_STATUS1_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t S16UP_U_RX_X8_STATUS1_RESERVED_TYPE;




typedef uint16_t S16UP_U_RX_X8_STATUS1_ULS1_TYPE;
#define S16UP_U_RX_X8_STATUS1_ULS1_LOCAL_FAULT_LH_MASK (0x8000U)
#define S16UP_U_RX_X8_STATUS1_ULS1_LOCAL_FAULT_LH_SHIFT (15U)
#define S16UP_U_RX_X8_STATUS1_ULS1_REMOTE_FAULT_LH_MASK (0x4000U)
#define S16UP_U_RX_X8_STATUS1_ULS1_REMOTE_FAULT_LH_SHIFT (14U)
#define S16UP_U_RX_X8_STATUS1_ULS1_LINK_INTERRUPT_LH_MASK (0x2000U)
#define S16UP_U_RX_X8_STATUS1_ULS1_LINK_INTERRUPT_LH_SHIFT (13U)
#define S16UP_U_RX_X8_STATUS1_ULS1_LPI_RECEIVED_LH_MASK (0x8U)
#define S16UP_U_RX_X8_STATUS1_ULS1_LPI_RECEIVED_LH_SHIFT (3U)




typedef uint16_t S16UP_U_RX_X8_STATUS1_ULS0_TYPE;
#define S16UP_U_RX_X8_STATUS1_ULS0_HI_BER_LH_MASK (0x800U)
#define S16UP_U_RX_X8_STATUS1_ULS0_HI_BER_LH_SHIFT (11U)
#define S16UP_U_RX_X8_STATUS1_ULS0_HI_BER_LL_MASK (0x400U)
#define S16UP_U_RX_X8_STATUS1_ULS0_HI_BER_LL_SHIFT (10U)
#define S16UP_U_RX_X8_STATUS1_ULS0_LINK_STATUS_LH_MASK (0x200U)
#define S16UP_U_RX_X8_STATUS1_ULS0_LINK_STATUS_LH_SHIFT (9U)
#define S16UP_U_RX_X8_STATUS1_ULS0_LINK_STATUS_LL_MASK (0x100U)
#define S16UP_U_RX_X8_STATUS1_ULS0_LINK_STATUS_LL_SHIFT (8U)
#define S16UP_U_RX_X8_STATUS1_ULS0_SYNC_STATUS_LH_MASK (0x80U)
#define S16UP_U_RX_X8_STATUS1_ULS0_SYNC_STATUS_LH_SHIFT (7U)
#define S16UP_U_RX_X8_STATUS1_ULS0_SYNC_STATUS_LL_MASK (0x40U)
#define S16UP_U_RX_X8_STATUS1_ULS0_SYNC_STATUS_LL_SHIFT (6U)




typedef uint16_t S16UP_U_RX_X8_STATUS1_ULS_TYPE;
#define S16UP_U_RX_X8_STATUS1_ULS_RX_PORT_LINK_STATUS_MASK (0x200U)
#define S16UP_U_RX_X8_STATUS1_ULS_RX_PORT_LINK_STATUS_SHIFT (9U)
#define S16UP_U_RX_X8_STATUS1_ULS_LOCAL_FAULT_MASK (0x100U)
#define S16UP_U_RX_X8_STATUS1_ULS_LOCAL_FAULT_SHIFT (8U)
#define S16UP_U_RX_X8_STATUS1_ULS_REMOTE_FAULT_MASK (0x80U)
#define S16UP_U_RX_X8_STATUS1_ULS_REMOTE_FAULT_SHIFT (7U)
#define S16UP_U_RX_X8_STATUS1_ULS_LINK_INTERRUPT_MASK (0x40U)
#define S16UP_U_RX_X8_STATUS1_ULS_LINK_INTERRUPT_SHIFT (6U)
#define S16UP_U_RX_X8_STATUS1_ULS_LPI_RECEIVED_MASK (0x20U)
#define S16UP_U_RX_X8_STATUS1_ULS_LPI_RECEIVED_SHIFT (5U)
#define S16UP_U_RX_X8_STATUS1_ULS_HI_BER_MASK (0x4U)
#define S16UP_U_RX_X8_STATUS1_ULS_HI_BER_SHIFT (2U)
#define S16UP_U_RX_X8_STATUS1_ULS_LINK_STATUS_MASK (0x2U)
#define S16UP_U_RX_X8_STATUS1_ULS_LINK_STATUS_SHIFT (1U)
#define S16UP_U_RX_X8_STATUS1_ULS_SYNC_STATUS_MASK (0x1U)
#define S16UP_U_RX_X8_STATUS1_ULS_SYNC_STATUS_SHIFT (0U)




typedef uint16_t S16UP_U_RX_X8_STATUS1_URS_TYPE;
#define S16UP_U_RX_X8_STATUS1_URS_IPG_REPAIR_STATUS_MUX_MASK (0xffffU)
#define S16UP_U_RX_X8_STATUS1_URS_IPG_REPAIR_STATUS_MUX_SHIFT (0U)




typedef uint16_t S16UP_U_RX_X8_STATUS1_UUDWES_TYPE;
#define S16UP_U_RX_X8_STATUS1_UUDWES_TX_WENCODE_STATE_IDLE_COL_L_MASK (0x80U)
#define S16UP_U_RX_X8_STATUS1_UUDWES_TX_WENCODE_STATE_IDLE_COL_L_SHIFT (7U)
#define S16UP_U_RX_X8_STATUS1_UUDWES_TX_WENCODE_STATE_DATA_COL_L_MASK (0x40U)
#define S16UP_U_RX_X8_STATUS1_UUDWES_TX_WENCODE_STATE_DATA_COL_L_SHIFT (6U)
#define S16UP_U_RX_X8_STATUS1_UUDWES_TX_WENCODE_STATE_SEQ_COL_L_MASK (0x20U)
#define S16UP_U_RX_X8_STATUS1_UUDWES_TX_WENCODE_STATE_SEQ_COL_L_SHIFT (5U)
#define S16UP_U_RX_X8_STATUS1_UUDWES_TX_WENCODE_STATE_ERR_COL_L_MASK (0x10U)
#define S16UP_U_RX_X8_STATUS1_UUDWES_TX_WENCODE_STATE_ERR_COL_L_SHIFT (4U)
#define S16UP_U_RX_X8_STATUS1_UUDWES_TX_WENCODE_STATE_IDLE_COL_H_MASK (0x8U)
#define S16UP_U_RX_X8_STATUS1_UUDWES_TX_WENCODE_STATE_IDLE_COL_H_SHIFT (3U)
#define S16UP_U_RX_X8_STATUS1_UUDWES_TX_WENCODE_STATE_DATA_COL_H_MASK (0x4U)
#define S16UP_U_RX_X8_STATUS1_UUDWES_TX_WENCODE_STATE_DATA_COL_H_SHIFT (2U)
#define S16UP_U_RX_X8_STATUS1_UUDWES_TX_WENCODE_STATE_SEQ_COL_H_MASK (0x2U)
#define S16UP_U_RX_X8_STATUS1_UUDWES_TX_WENCODE_STATE_SEQ_COL_H_SHIFT (1U)
#define S16UP_U_RX_X8_STATUS1_UUDWES_TX_WENCODE_STATE_ERR_COL_H_MASK (0x1U)
#define S16UP_U_RX_X8_STATUS1_UUDWES_TX_WENCODE_STATE_ERR_COL_H_SHIFT (0U)




typedef uint16_t S16UP_U_RX_X8_STATUS1_UUDTS_TYPE;
#define S16UP_U_RX_X8_STATUS1_UUDTS_RUDTS_MASK (0xffffU)
#define S16UP_U_RX_X8_STATUS1_UUDTS_RUDTS_SHIFT (0U)




typedef uint16_t S16UP_U_RX_X8_STATUS1_UMIPCL_TYPE;
#define S16UP_U_RX_X8_STATUS1_UMIPCL_R_MAC_INTF_PKT_CNT_LOW_MASK (0xffffU)
#define S16UP_U_RX_X8_STATUS1_UMIPCL_R_MAC_INTF_PKT_CNT_LOW_SHIFT (0U)




typedef uint16_t S16UP_U_RX_X8_STATUS1_UMIPCU_TYPE;
#define S16UP_U_RX_X8_STATUS1_UMIPCU_R_MAC_INTF_PKT_CNT_UP_MASK (0xffffU)
#define S16UP_U_RX_X8_STATUS1_UMIPCU_R_MAC_INTF_PKT_CNT_UP_SHIFT (0U)




typedef uint16_t S16UP_U_RX_X8_STATUS1_UMIPS0_TYPE;
#define S16UP_U_RX_X8_STATUS1_UMIPS0_R_MAC_INTF_PKT_STAT0_MASK (0xffffU)
#define S16UP_U_RX_X8_STATUS1_UMIPS0_R_MAC_INTF_PKT_STAT0_SHIFT (0U)




typedef uint16_t S16UP_U_RX_X8_STATUS1_UMIPS1_TYPE;
#define S16UP_U_RX_X8_STATUS1_UMIPS1_R_MAC_INTF_PKT_STAT1_MASK (0xffffU)
#define S16UP_U_RX_X8_STATUS1_UMIPS1_R_MAC_INTF_PKT_STAT1_SHIFT (0U)




typedef uint16_t S16UP_U_RX_X8_STATUS1_UMIPS2_TYPE;
#define S16UP_U_RX_X8_STATUS1_UMIPS2_R_MAC_INTF_PKT_STAT2_MASK (0xffffU)
#define S16UP_U_RX_X8_STATUS1_UMIPS2_R_MAC_INTF_PKT_STAT2_SHIFT (0U)




typedef volatile struct sS16UP_U_RX_X8_STATUS1_RDBType {
    S16UP_U_RX_X8_STATUS1_RESERVED_TYPE rsvd0[8]; /* OFFSET: 0x0 */
    S16UP_U_RX_X8_STATUS1_ULS1_TYPE pcs_latched_status_1; /* OFFSET: 0x8 */
    S16UP_U_RX_X8_STATUS1_RESERVED_TYPE rsvd1[2]; /* OFFSET: 0xa */
    S16UP_U_RX_X8_STATUS1_ULS0_TYPE pcs_latched_status_0; /* OFFSET: 0xc */
    S16UP_U_RX_X8_STATUS1_RESERVED_TYPE rsvd2[2]; /* OFFSET: 0xe */
    S16UP_U_RX_X8_STATUS1_ULS_TYPE pcs_live_status; /* OFFSET: 0x10 */
    S16UP_U_RX_X8_STATUS1_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0x12 */
    S16UP_U_RX_X8_STATUS1_URS_TYPE ipg_repair_status; /* OFFSET: 0x14 */
    S16UP_U_RX_X8_STATUS1_RESERVED_TYPE rsvd4[6]; /* OFFSET: 0x16 */
    S16UP_U_RX_X8_STATUS1_UUDWES_TYPE r_usxgmii_dereplicate_word_encode_status; /* OFFSET: 0x1c */
    S16UP_U_RX_X8_STATUS1_RESERVED_TYPE rsvd5[2]; /* OFFSET: 0x1e */
    S16UP_U_RX_X8_STATUS1_UUDTS_TYPE r_usxgmii_dereplicate_tstmux_status; /* OFFSET: 0x20 */
    S16UP_U_RX_X8_STATUS1_RESERVED_TYPE rsvd6[2]; /* OFFSET: 0x22 */
    S16UP_U_RX_X8_STATUS1_UMIPCL_TYPE r_mac_intf_pkt_cnt_low; /* OFFSET: 0x24 */
    S16UP_U_RX_X8_STATUS1_RESERVED_TYPE rsvd7[2]; /* OFFSET: 0x26 */
    S16UP_U_RX_X8_STATUS1_UMIPCU_TYPE r_mac_intf_pkt_cnt_up; /* OFFSET: 0x28 */
    S16UP_U_RX_X8_STATUS1_RESERVED_TYPE rsvd8[2]; /* OFFSET: 0x2a */
    S16UP_U_RX_X8_STATUS1_UMIPS0_TYPE r_mac_intf_pkt_stat0; /* OFFSET: 0x2c */
    S16UP_U_RX_X8_STATUS1_RESERVED_TYPE rsvd9[2]; /* OFFSET: 0x2e */
    S16UP_U_RX_X8_STATUS1_UMIPS1_TYPE r_mac_intf_pkt_stat1; /* OFFSET: 0x30 */
    S16UP_U_RX_X8_STATUS1_RESERVED_TYPE rsvd10[2]; /* OFFSET: 0x32 */
    S16UP_U_RX_X8_STATUS1_UMIPS2_TYPE r_mac_intf_pkt_stat2; /* OFFSET: 0x34 */
} S16UP_U_RX_X8_STATUS1_RDBType;


#define U_RX_X8_STATUS1_BASE            (0xE04F19C0UL)



#define S16UP_U_RX_X8_STATUS1_MAX_HW_ID  (1UL)

#endif /* S16UP_U_RX_X8_STATUS1_RDB_H */
