/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file s16up_u_rx_x1_control1_rdb.h
    @brief RDB File for S16UP_U_RX_X1_CONTROL1

    @version BCM89580_A0_20230125_RDB
*/

#ifndef S16UP_U_RX_X1_CONTROL1_RDB_H
#define S16UP_U_RX_X1_CONTROL1_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t S16UP_U_RX_X1_CONTROL1_UPCS_CONTROL_0_TYPE;
#define S16UP_U_RX_X1_CONTROL1_UPCS_CONTROL_0_RST_DV_GEN_RX_MASK (0x2000U)
#define S16UP_U_RX_X1_CONTROL1_UPCS_CONTROL_0_RST_DV_GEN_RX_SHIFT (13U)
#define S16UP_U_RX_X1_CONTROL1_UPCS_CONTROL_0_PCS_LINK_DELAY_EN_MASK (0x1000U)
#define S16UP_U_RX_X1_CONTROL1_UPCS_CONTROL_0_PCS_LINK_DELAY_EN_SHIFT (12U)
#define S16UP_U_RX_X1_CONTROL1_UPCS_CONTROL_0_PCS_LINK_DELAY_MAX_MASK (0xf00U)
#define S16UP_U_RX_X1_CONTROL1_UPCS_CONTROL_0_PCS_LINK_DELAY_MAX_SHIFT (8U)
#define S16UP_U_RX_X1_CONTROL1_UPCS_CONTROL_0_PMD_LOCK_DELAY_EN_MASK (0x80U)
#define S16UP_U_RX_X1_CONTROL1_UPCS_CONTROL_0_PMD_LOCK_DELAY_EN_SHIFT (7U)
#define S16UP_U_RX_X1_CONTROL1_UPCS_CONTROL_0_PMD_LOCK_DELAY_MAX_MASK (0x78U)
#define S16UP_U_RX_X1_CONTROL1_UPCS_CONTROL_0_PMD_LOCK_DELAY_MAX_SHIFT (3U)
#define S16UP_U_RX_X1_CONTROL1_UPCS_CONTROL_0_LPI_ENABLE_MASK (0x4U)
#define S16UP_U_RX_X1_CONTROL1_UPCS_CONTROL_0_LPI_ENABLE_SHIFT (2U)




typedef uint8_t S16UP_U_RX_X1_CONTROL1_RESERVED_TYPE;




typedef uint16_t S16UP_U_RX_X1_CONTROL1_UDDC0_TYPE;
#define S16UP_U_RX_X1_CONTROL1_UDDC0_CLK_DV_GMII_DLY_SEL_MASK (0x7000U)
#define S16UP_U_RX_X1_CONTROL1_UDDC0_CLK_DV_GMII_DLY_SEL_SHIFT (12U)
#define S16UP_U_RX_X1_CONTROL1_UDDC0_CLK_DV_GMII_INTF_DLY_SEL_MASK (0xe00U)
#define S16UP_U_RX_X1_CONTROL1_UDDC0_CLK_DV_GMII_INTF_DLY_SEL_SHIFT (9U)
#define S16UP_U_RX_X1_CONTROL1_UDDC0_CLK_DV_XGMII_INTF_DLY_SEL_MASK (0x1c0U)
#define S16UP_U_RX_X1_CONTROL1_UDDC0_CLK_DV_XGMII_INTF_DLY_SEL_SHIFT (6U)
#define S16UP_U_RX_X1_CONTROL1_UDDC0_CLK_DV_XGMII_DLY_SEL_MASK (0x38U)
#define S16UP_U_RX_X1_CONTROL1_UDDC0_CLK_DV_XGMII_DLY_SEL_SHIFT (3U)
#define S16UP_U_RX_X1_CONTROL1_UDDC0_CLK_DV_2X_XGMII_DLY_SEL_MASK (0x7U)
#define S16UP_U_RX_X1_CONTROL1_UDDC0_CLK_DV_2X_XGMII_DLY_SEL_SHIFT (0U)




typedef uint16_t S16UP_U_RX_X1_CONTROL1_UDDC1_TYPE;
#define S16UP_U_RX_X1_CONTROL1_UDDC1_CLK_DV_GMII_BYTE_DLY_SEL_MASK (0x7000U)
#define S16UP_U_RX_X1_CONTROL1_UDDC1_CLK_DV_GMII_BYTE_DLY_SEL_SHIFT (12U)
#define S16UP_U_RX_X1_CONTROL1_UDDC1_BYTE_CNT_GMII_BYTE_DLY_SEL_MASK (0xe00U)
#define S16UP_U_RX_X1_CONTROL1_UDDC1_BYTE_CNT_GMII_BYTE_DLY_SEL_SHIFT (9U)
#define S16UP_U_RX_X1_CONTROL1_UDDC1_CLK_DV_XGMII_0PPM_DLY_SEL_MASK (0x1c0U)
#define S16UP_U_RX_X1_CONTROL1_UDDC1_CLK_DV_XGMII_0PPM_DLY_SEL_SHIFT (6U)
#define S16UP_U_RX_X1_CONTROL1_UDDC1_CLK_DV_XGMII_AMPPM_DLY_SEL_MASK (0x38U)
#define S16UP_U_RX_X1_CONTROL1_UDDC1_CLK_DV_XGMII_AMPPM_DLY_SEL_SHIFT (3U)
#define S16UP_U_RX_X1_CONTROL1_UDDC1_CLK_DV_USXGMII_AN_DLY_SEL_MASK (0x7U)
#define S16UP_U_RX_X1_CONTROL1_UDDC1_CLK_DV_USXGMII_AN_DLY_SEL_SHIFT (0U)




typedef uint16_t S16UP_U_RX_X1_CONTROL1_UDDC2_TYPE;
#define S16UP_U_RX_X1_CONTROL1_UDDC2_CD15625IDS_MASK (0x7000U)
#define S16UP_U_RX_X1_CONTROL1_UDDC2_CD15625IDS_SHIFT (12U)
#define S16UP_U_RX_X1_CONTROL1_UDDC2_CLK_DV_REPX_RD_DLY_SEL_MASK (0xe00U)
#define S16UP_U_RX_X1_CONTROL1_UDDC2_CLK_DV_REPX_RD_DLY_SEL_SHIFT (9U)
#define S16UP_U_RX_X1_CONTROL1_UDDC2_CLK_DV_BASER_AMPPM_DLY_SEL_MASK (0x1c0U)
#define S16UP_U_RX_X1_CONTROL1_UDDC2_CLK_DV_BASER_AMPPM_DLY_SEL_SHIFT (6U)
#define S16UP_U_RX_X1_CONTROL1_UDDC2_CLK_DV_BASER_0PPM_DLY_SEL_MASK (0x38U)
#define S16UP_U_RX_X1_CONTROL1_UDDC2_CLK_DV_BASER_0PPM_DLY_SEL_SHIFT (3U)
#define S16UP_U_RX_X1_CONTROL1_UDDC2_TDM_AMPPM_PORT_NUM_DLY_SEL_MASK (0x7U)
#define S16UP_U_RX_X1_CONTROL1_UDDC2_TDM_AMPPM_PORT_NUM_DLY_SEL_SHIFT (0U)




typedef uint16_t S16UP_U_RX_X1_CONTROL1_UC0_TYPE;
#define S16UP_U_RX_X1_CONTROL1_UC0_BYPASS_CL49RXSM_MASK (0x8000U)
#define S16UP_U_RX_X1_CONTROL1_UC0_BYPASS_CL49RXSM_SHIFT (15U)
#define S16UP_U_RX_X1_CONTROL1_UC0_R_TEST_MODE_CFG_MASK (0x4000U)
#define S16UP_U_RX_X1_CONTROL1_UC0_R_TEST_MODE_CFG_SHIFT (14U)
#define S16UP_U_RX_X1_CONTROL1_UC0_H2MICE_MASK (0x2000U)
#define S16UP_U_RX_X1_CONTROL1_UC0_H2MICE_SHIFT (13U)
#define S16UP_U_RX_X1_CONTROL1_UC0_HG2_ENABLE_MASK (0x1000U)
#define S16UP_U_RX_X1_CONTROL1_UC0_HG2_ENABLE_SHIFT (12U)
#define S16UP_U_RX_X1_CONTROL1_UC0_DISABLE_CL49_BERMON_MASK (0x100U)
#define S16UP_U_RX_X1_CONTROL1_UC0_DISABLE_CL49_BERMON_SHIFT (8U)
#define S16UP_U_RX_X1_CONTROL1_UC0_CL49_HIGIG2_MSG_32BYTES_MASK (0x80U)
#define S16UP_U_RX_X1_CONTROL1_UC0_CL49_HIGIG2_MSG_32BYTES_SHIFT (7U)
#define S16UP_U_RX_X1_CONTROL1_UC0_CL49_RX_LI_ENABLE_MASK (0x40U)
#define S16UP_U_RX_X1_CONTROL1_UC0_CL49_RX_LI_ENABLE_SHIFT (6U)
#define S16UP_U_RX_X1_CONTROL1_UC0_CL49_RX_LF_ENABLE_MASK (0x20U)
#define S16UP_U_RX_X1_CONTROL1_UC0_CL49_RX_LF_ENABLE_SHIFT (5U)
#define S16UP_U_RX_X1_CONTROL1_UC0_CL49_RX_RF_ENABLE_MASK (0x10U)
#define S16UP_U_RX_X1_CONTROL1_UC0_CL49_RX_RF_ENABLE_SHIFT (4U)
#define S16UP_U_RX_X1_CONTROL1_UC0_BLOCK_SYNC_MODE_MASK (0x7U)
#define S16UP_U_RX_X1_CONTROL1_UC0_BLOCK_SYNC_MODE_SHIFT (0U)




typedef uint16_t S16UP_U_RX_X1_CONTROL1_UCWD1_TYPE;
#define S16UP_U_RX_X1_CONTROL1_UCWD1_CKCMP_WPTR_DEFAULT_2P5G_MASK (0x7c00U)
#define S16UP_U_RX_X1_CONTROL1_UCWD1_CKCMP_WPTR_DEFAULT_2P5G_SHIFT (10U)
#define S16UP_U_RX_X1_CONTROL1_UCWD1_CKCMP_WPTR_DEFAULT_5G_MASK (0x3e0U)
#define S16UP_U_RX_X1_CONTROL1_UCWD1_CKCMP_WPTR_DEFAULT_5G_SHIFT (5U)
#define S16UP_U_RX_X1_CONTROL1_UCWD1_CKCMP_WPTR_DEFAULT_10G_MASK (0x1fU)
#define S16UP_U_RX_X1_CONTROL1_UCWD1_CKCMP_WPTR_DEFAULT_10G_SHIFT (0U)




typedef uint16_t S16UP_U_RX_X1_CONTROL1_UCWD2_TYPE;
#define S16UP_U_RX_X1_CONTROL1_UCWD2_CKCMP_WPTR_DEFAULT_10M_MASK (0x7c00U)
#define S16UP_U_RX_X1_CONTROL1_UCWD2_CKCMP_WPTR_DEFAULT_10M_SHIFT (10U)
#define S16UP_U_RX_X1_CONTROL1_UCWD2_CKCMP_WPTR_DEFAULT_100M_MASK (0x3e0U)
#define S16UP_U_RX_X1_CONTROL1_UCWD2_CKCMP_WPTR_DEFAULT_100M_SHIFT (5U)
#define S16UP_U_RX_X1_CONTROL1_UCWD2_CKCMP_WPTR_DEFAULT_1G_MASK (0x1fU)
#define S16UP_U_RX_X1_CONTROL1_UCWD2_CKCMP_WPTR_DEFAULT_1G_SHIFT (0U)




typedef uint16_t S16UP_U_RX_X1_CONTROL1_UPMA_CONTROL_0_TYPE;
#define S16UP_U_RX_X1_CONTROL1_UPMA_CONTROL_0_RX_GBOX_PRST_MASK (0x8U)
#define S16UP_U_RX_X1_CONTROL1_UPMA_CONTROL_0_RX_GBOX_PRST_SHIFT (3U)
#define S16UP_U_RX_X1_CONTROL1_UPMA_CONTROL_0_RX_GBOX_ERR_DET_CLR_MASK (0x4U)
#define S16UP_U_RX_X1_CONTROL1_UPMA_CONTROL_0_RX_GBOX_ERR_DET_CLR_SHIFT (2U)
#define S16UP_U_RX_X1_CONTROL1_UPMA_CONTROL_0_RX_GBOX_AFRST_EN_MASK (0x2U)
#define S16UP_U_RX_X1_CONTROL1_UPMA_CONTROL_0_RX_GBOX_AFRST_EN_SHIFT (1U)
#define S16UP_U_RX_X1_CONTROL1_UPMA_CONTROL_0_RSTB_LANE_MASK (0x1U)
#define S16UP_U_RX_X1_CONTROL1_UPMA_CONTROL_0_RSTB_LANE_SHIFT (0U)




typedef uint16_t S16UP_U_RX_X1_CONTROL1_ULIN_CONT_TYPE;
#define S16UP_U_RX_X1_CONTROL1_ULIN_CONT_CL72_RX_TRAINED_MASK (0x2U)
#define S16UP_U_RX_X1_CONTROL1_ULIN_CONT_CL72_RX_TRAINED_SHIFT (1U)
#define S16UP_U_RX_X1_CONTROL1_ULIN_CONT_LATCH_LINKDOWN_ENABLE_MASK (0x1U)
#define S16UP_U_RX_X1_CONTROL1_ULIN_CONT_LATCH_LINKDOWN_ENABLE_SHIFT (0U)




typedef uint16_t S16UP_U_RX_X1_CONTROL1_UFP25C0_TYPE;
#define S16UP_U_RX_X1_CONTROL1_UFP25C0_FEC_P25G_RX_DECODE_MODE_MASK (0x1e0U)
#define S16UP_U_RX_X1_CONTROL1_UFP25C0_FEC_P25G_RX_DECODE_MODE_SHIFT (5U)
#define S16UP_U_RX_X1_CONTROL1_UFP25C0_U_MDIO_CWM_OVERRIDE_EN_MASK (0x10U)
#define S16UP_U_RX_X1_CONTROL1_UFP25C0_U_MDIO_CWM_OVERRIDE_EN_SHIFT (4U)
#define S16UP_U_RX_X1_CONTROL1_UFP25C0_U_AM_SPACING_CWM_CNT_MSB_MASK (0x4U)
#define S16UP_U_RX_X1_CONTROL1_UFP25C0_U_AM_SPACING_CWM_CNT_MSB_SHIFT (2U)
#define S16UP_U_RX_X1_CONTROL1_UFP25C0_U_AM_SPACING_OVERRIDE_EN_MASK (0x2U)
#define S16UP_U_RX_X1_CONTROL1_UFP25C0_U_AM_SPACING_OVERRIDE_EN_SHIFT (1U)
#define S16UP_U_RX_X1_CONTROL1_UFP25C0_U_MDIO_FIXED_CWM_EN_MASK (0x1U)
#define S16UP_U_RX_X1_CONTROL1_UFP25C0_U_MDIO_FIXED_CWM_EN_SHIFT (0U)




typedef uint16_t S16UP_U_RX_X1_CONTROL1_UFP25C1_TYPE;
#define S16UP_U_RX_X1_CONTROL1_UFP25C1_AM_SPACING_CWM_CNT_MASK (0xffffU)
#define S16UP_U_RX_X1_CONTROL1_UFP25C1_AM_SPACING_CWM_CNT_SHIFT (0U)




typedef uint16_t S16UP_U_RX_X1_CONTROL1_UFP25C2_TYPE;
#define S16UP_U_RX_X1_CONTROL1_UFP25C2_AM_SPACING_CWM_CNTH_MASK (0xffffU)
#define S16UP_U_RX_X1_CONTROL1_UFP25C2_AM_SPACING_CWM_CNTH_SHIFT (0U)




typedef uint16_t S16UP_U_RX_X1_CONTROL1_UCIM1_TYPE;
#define S16UP_U_RX_X1_CONTROL1_UCIM1_CKCMP_INSERT_MARGIN_2P5G_MASK (0x7c00U)
#define S16UP_U_RX_X1_CONTROL1_UCIM1_CKCMP_INSERT_MARGIN_2P5G_SHIFT (10U)
#define S16UP_U_RX_X1_CONTROL1_UCIM1_CKCMP_INSERT_MARGIN_5G_MASK (0x3e0U)
#define S16UP_U_RX_X1_CONTROL1_UCIM1_CKCMP_INSERT_MARGIN_5G_SHIFT (5U)
#define S16UP_U_RX_X1_CONTROL1_UCIM1_CKCMP_INSERT_MARGIN_10G_MASK (0x1fU)
#define S16UP_U_RX_X1_CONTROL1_UCIM1_CKCMP_INSERT_MARGIN_10G_SHIFT (0U)




typedef uint16_t S16UP_U_RX_X1_CONTROL1_UCIM2_TYPE;
#define S16UP_U_RX_X1_CONTROL1_UCIM2_CKCMP_INSERT_MARGIN_10M_MASK (0x7c00U)
#define S16UP_U_RX_X1_CONTROL1_UCIM2_CKCMP_INSERT_MARGIN_10M_SHIFT (10U)
#define S16UP_U_RX_X1_CONTROL1_UCIM2_CKCMP_INSERT_MARGIN_100M_MASK (0x3e0U)
#define S16UP_U_RX_X1_CONTROL1_UCIM2_CKCMP_INSERT_MARGIN_100M_SHIFT (5U)
#define S16UP_U_RX_X1_CONTROL1_UCIM2_CKCMP_INSERT_MARGIN_1G_MASK (0x1fU)
#define S16UP_U_RX_X1_CONTROL1_UCIM2_CKCMP_INSERT_MARGIN_1G_SHIFT (0U)




typedef volatile struct sS16UP_U_RX_X1_CONTROL1_RDBType {
    S16UP_U_RX_X1_CONTROL1_UPCS_CONTROL_0_TYPE pcs_control_0; /* OFFSET: 0x0 */
    S16UP_U_RX_X1_CONTROL1_RESERVED_TYPE rsvd0[2]; /* OFFSET: 0x2 */
    S16UP_U_RX_X1_CONTROL1_UDDC0_TYPE clk_dv_dly_control0; /* OFFSET: 0x4 */
    S16UP_U_RX_X1_CONTROL1_RESERVED_TYPE rsvd1[2]; /* OFFSET: 0x6 */
    S16UP_U_RX_X1_CONTROL1_UDDC1_TYPE clk_dv_dly_control1; /* OFFSET: 0x8 */
    S16UP_U_RX_X1_CONTROL1_RESERVED_TYPE rsvd2[2]; /* OFFSET: 0xa */
    S16UP_U_RX_X1_CONTROL1_UDDC2_TYPE clk_dv_dly_control2; /* OFFSET: 0xc */
    S16UP_U_RX_X1_CONTROL1_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0xe */
    S16UP_U_RX_X1_CONTROL1_UC0_TYPE decode_control_0; /* OFFSET: 0x10 */
    S16UP_U_RX_X1_CONTROL1_RESERVED_TYPE rsvd4[2]; /* OFFSET: 0x12 */
    S16UP_U_RX_X1_CONTROL1_UCWD1_TYPE urx_ckcmp_wptr_default_1; /* OFFSET: 0x14 */
    S16UP_U_RX_X1_CONTROL1_RESERVED_TYPE rsvd5[2]; /* OFFSET: 0x16 */
    S16UP_U_RX_X1_CONTROL1_UCWD2_TYPE urx_ckcmp_wptr_default_2; /* OFFSET: 0x18 */
    S16UP_U_RX_X1_CONTROL1_RESERVED_TYPE rsvd6[2]; /* OFFSET: 0x1a */
    S16UP_U_RX_X1_CONTROL1_UPMA_CONTROL_0_TYPE pma_control_0; /* OFFSET: 0x1c */
    S16UP_U_RX_X1_CONTROL1_RESERVED_TYPE rsvd7[6]; /* OFFSET: 0x1e */
    S16UP_U_RX_X1_CONTROL1_ULIN_CONT_TYPE link_control; /* OFFSET: 0x24 */
    S16UP_U_RX_X1_CONTROL1_RESERVED_TYPE rsvd8[2]; /* OFFSET: 0x26 */
    S16UP_U_RX_X1_CONTROL1_UFP25C0_TYPE rx_fec_p25g_control0; /* OFFSET: 0x28 */
    S16UP_U_RX_X1_CONTROL1_RESERVED_TYPE rsvd9[2]; /* OFFSET: 0x2a */
    S16UP_U_RX_X1_CONTROL1_UFP25C1_TYPE rx_fec_p25g_control1; /* OFFSET: 0x2c */
    S16UP_U_RX_X1_CONTROL1_RESERVED_TYPE rsvd10[2]; /* OFFSET: 0x2e */
    S16UP_U_RX_X1_CONTROL1_UFP25C2_TYPE rx_fec_p25g_control2; /* OFFSET: 0x30 */
    S16UP_U_RX_X1_CONTROL1_RESERVED_TYPE rsvd11[2]; /* OFFSET: 0x32 */
    S16UP_U_RX_X1_CONTROL1_UCIM1_TYPE urx_ckcmp_insert_margin_1; /* OFFSET: 0x34 */
    S16UP_U_RX_X1_CONTROL1_RESERVED_TYPE rsvd12[2]; /* OFFSET: 0x36 */
    S16UP_U_RX_X1_CONTROL1_UCIM2_TYPE urx_ckcmp_insert_margin_2; /* OFFSET: 0x38 */
} S16UP_U_RX_X1_CONTROL1_RDBType;


#define U_RX_X1_CONTROL1_BASE           (0xE04E50C0UL)



#define S16UP_U_RX_X1_CONTROL1_MAX_HW_ID  (1UL)

#endif /* S16UP_U_RX_X1_CONTROL1_RDB_H */
