/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file s16up_rx_pmd_test_rdb.h
    @brief RDB File for S16UP_RX_PMD_TEST

    @version BCM89580_A0_20230125_RDB
*/

#ifndef S16UP_RX_PMD_TEST_RDB_H
#define S16UP_RX_PMD_TEST_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t S16UP_RX_PMD_TEST_RESERVED_TYPE;




typedef uint16_t S16UP_RX_PMD_TEST_RXPMD_CONTROL0_TYPE;
#define S16UP_RX_PMD_TEST_RXPMD_CONTROL0_PMD_RLOOPBACK_MASK (0x8000U)
#define S16UP_RX_PMD_TEST_RXPMD_CONTROL0_PMD_RLOOPBACK_SHIFT (15U)
#define S16UP_RX_PMD_TEST_RXPMD_CONTROL0_RXPOL_FLIP_SM_MASK (0x200U)
#define S16UP_RX_PMD_TEST_RXPMD_CONTROL0_RXPOL_FLIP_SM_SHIFT (9U)
#define S16UP_RX_PMD_TEST_RXPMD_CONTROL0_PHASE_SEL_SM_MASK (0x80U)
#define S16UP_RX_PMD_TEST_RXPMD_CONTROL0_PHASE_SEL_SM_SHIFT (7U)
#define S16UP_RX_PMD_TEST_RXPMD_CONTROL0_RXCK_MII_GEN_SEL_FORCE_MASK (0x8U)
#define S16UP_RX_PMD_TEST_RXPMD_CONTROL0_RXCK_MII_GEN_SEL_FORCE_SHIFT (3U)
#define S16UP_RX_PMD_TEST_RXPMD_CONTROL0_FORCERXSEQDONE_SM_MASK (0x4U)
#define S16UP_RX_PMD_TEST_RXPMD_CONTROL0_FORCERXSEQDONE_SM_SHIFT (2U)
#define S16UP_RX_PMD_TEST_RXPMD_CONTROL0_FLIP_EYEMON_POLARITY_MASK (0x2U)
#define S16UP_RX_PMD_TEST_RXPMD_CONTROL0_FLIP_EYEMON_POLARITY_SHIFT (1U)




typedef uint16_t S16UP_RX_PMD_TEST_RXPM_CONT1_TYPE;
#define S16UP_RX_PMD_TEST_RXPM_CONT1_RX_PF_CTRL_MASK (0xf000U)
#define S16UP_RX_PMD_TEST_RXPM_CONT1_RX_PF_CTRL_SHIFT (12U)
#define S16UP_RX_PMD_TEST_RXPM_CONT1_RXSEQRESTART_SM_MASK (0x800U)
#define S16UP_RX_PMD_TEST_RXPM_CONT1_RXSEQRESTART_SM_SHIFT (11U)
#define S16UP_RX_PMD_TEST_RXPM_CONT1_RXSIGDETPWRDN_OVERRIDE_VAL_MASK (0x400U)
#define S16UP_RX_PMD_TEST_RXPM_CONT1_RXSIGDETPWRDN_OVERRIDE_VAL_SHIFT (10U)
#define S16UP_RX_PMD_TEST_RXPM_CONT1_RXSIGDETPWRDN_OVERRIDE_MASK (0x200U)
#define S16UP_RX_PMD_TEST_RXPM_CONT1_RXSIGDETPWRDN_OVERRIDE_SHIFT (9U)
#define S16UP_RX_PMD_TEST_RXPM_CONT1_SIGDETECTED_EN_SM_MASK (0x100U)
#define S16UP_RX_PMD_TEST_RXPM_CONT1_SIGDETECTED_EN_SM_SHIFT (8U)
#define S16UP_RX_PMD_TEST_RXPM_CONT1_SIGDETRESTART_EN_SM_MASK (0x80U)
#define S16UP_RX_PMD_TEST_RXPM_CONT1_SIGDETRESTART_EN_SM_SHIFT (7U)
#define S16UP_RX_PMD_TEST_RXPM_CONT1_SIGDETMONITOR_EN_SM_MASK (0x40U)
#define S16UP_RX_PMD_TEST_RXPM_CONT1_SIGDETMONITOR_EN_SM_SHIFT (6U)
#define S16UP_RX_PMD_TEST_RXPM_CONT1_RXSEQDONE_CYA_MASK (0x20U)
#define S16UP_RX_PMD_TEST_RXPM_CONT1_RXSEQDONE_CYA_SHIFT (5U)
#define S16UP_RX_PMD_TEST_RXPM_CONT1_SPD_RSTB_DIS_SM_MASK (0x10U)
#define S16UP_RX_PMD_TEST_RXPM_CONT1_SPD_RSTB_DIS_SM_SHIFT (4U)
#define S16UP_RX_PMD_TEST_RXPM_CONT1_RTBI_MODE_MASK (0x8U)
#define S16UP_RX_PMD_TEST_RXPM_CONT1_RTBI_MODE_SHIFT (3U)
#define S16UP_RX_PMD_TEST_RXPM_CONT1_INDCK_MODE_EN_RX_MASK (0x4U)
#define S16UP_RX_PMD_TEST_RXPM_CONT1_INDCK_MODE_EN_RX_SHIFT (2U)
#define S16UP_RX_PMD_TEST_RXPM_CONT1_COMBO_MODE_EN_RX_MASK (0x2U)
#define S16UP_RX_PMD_TEST_RXPM_CONT1_COMBO_MODE_EN_RX_SHIFT (1U)
#define S16UP_RX_PMD_TEST_RXPM_CONT1_CL36_PCS_EN_RX_MASK (0x1U)
#define S16UP_RX_PMD_TEST_RXPM_CONT1_CL36_PCS_EN_RX_SHIFT (0U)




typedef uint16_t S16UP_RX_PMD_TEST_RXPMD_CONTROL2_TYPE;
#define S16UP_RX_PMD_TEST_RXPMD_CONTROL2_SIGDET_MUX_SM_MASK (0xf000U)
#define S16UP_RX_PMD_TEST_RXPMD_CONTROL2_SIGDET_MUX_SM_SHIFT (12U)
#define S16UP_RX_PMD_TEST_RXPMD_CONTROL2_TPCTRL_SM_MASK (0x1f0U)
#define S16UP_RX_PMD_TEST_RXPMD_CONTROL2_TPCTRL_SM_SHIFT (4U)
#define S16UP_RX_PMD_TEST_RXPMD_CONTROL2_TESTMUXSELECT_SM_MASK (0xfU)
#define S16UP_RX_PMD_TEST_RXPMD_CONTROL2_TESTMUXSELECT_SM_SHIFT (0U)




typedef uint16_t S16UP_RX_PMD_TEST_RSC0_TYPE;
#define S16UP_RX_PMD_TEST_RSC0_INVERT_RX_SIGDET_MASK (0x20U)
#define S16UP_RX_PMD_TEST_RSC0_INVERT_RX_SIGDET_SHIFT (5U)
#define S16UP_RX_PMD_TEST_RSC0_CX4_SIGDET_CNT_LD_SM_MASK (0x10U)
#define S16UP_RX_PMD_TEST_RSC0_CX4_SIGDET_CNT_LD_SM_SHIFT (4U)
#define S16UP_RX_PMD_TEST_RSC0_CX4_SIGDET_EN_SM_MASK (0x8U)
#define S16UP_RX_PMD_TEST_RSC0_CX4_SIGDET_EN_SM_SHIFT (3U)
#define S16UP_RX_PMD_TEST_RSC0_EXT_SIGDET_EN_SM_MASK (0x4U)
#define S16UP_RX_PMD_TEST_RSC0_EXT_SIGDET_EN_SM_SHIFT (2U)
#define S16UP_RX_PMD_TEST_RSC0_OVERRIDE_SIGDET_EN_SM_MASK (0x2U)
#define S16UP_RX_PMD_TEST_RSC0_OVERRIDE_SIGDET_EN_SM_SHIFT (1U)
#define S16UP_RX_PMD_TEST_RSC0_OVERRIDE_SIGDET_VAL_SM_MASK (0x1U)
#define S16UP_RX_PMD_TEST_RSC0_OVERRIDE_SIGDET_VAL_SM_SHIFT (0U)




typedef uint16_t S16UP_RX_PMD_TEST_RXPMD_SIGDET_CTRL1_TYPE;
#define S16UP_RX_PMD_TEST_RXPMD_SIGDET_CTRL1_CX4_CNT_MASK (0xffffU)
#define S16UP_RX_PMD_TEST_RXPMD_SIGDET_CTRL1_CX4_CNT_SHIFT (0U)




typedef uint16_t S16UP_RX_PMD_TEST_RXPMD_SIGDET_STATUS_TYPE;
#define S16UP_RX_PMD_TEST_RXPMD_SIGDET_STATUS_RX_OS_MODE_MUXVAL_MASK (0x3cU)
#define S16UP_RX_PMD_TEST_RXPMD_SIGDET_STATUS_RX_OS_MODE_MUXVAL_SHIFT (2U)
#define S16UP_RX_PMD_TEST_RXPMD_SIGDET_STATUS_OS_1X_MODE_MASK (0x2U)
#define S16UP_RX_PMD_TEST_RXPMD_SIGDET_STATUS_OS_1X_MODE_SHIFT (1U)
#define S16UP_RX_PMD_TEST_RXPMD_SIGDET_STATUS_PMD_SIGDET_STATUS_MASK (0x1U)
#define S16UP_RX_PMD_TEST_RXPMD_SIGDET_STATUS_PMD_SIGDET_STATUS_SHIFT (0U)




typedef uint16_t S16UP_RX_PMD_TEST_RXPMD_CONTROL3_TYPE;
#define S16UP_RX_PMD_TEST_RXPMD_CONTROL3_OS_1X_MODE_OVERRIDE_VAL_MASK (0x40U)
#define S16UP_RX_PMD_TEST_RXPMD_CONTROL3_OS_1X_MODE_OVERRIDE_VAL_SHIFT (6U)
#define S16UP_RX_PMD_TEST_RXPMD_CONTROL3_OS_1X_MODE_OVERRIDE_MASK (0x20U)
#define S16UP_RX_PMD_TEST_RXPMD_CONTROL3_OS_1X_MODE_OVERRIDE_SHIFT (5U)
#define S16UP_RX_PMD_TEST_RXPMD_CONTROL3_OS_MODE_RX_PMD_OVERRIDE_MASK (0x10U)
#define S16UP_RX_PMD_TEST_RXPMD_CONTROL3_OS_MODE_RX_PMD_OVERRIDE_SHIFT (4U)
#define S16UP_RX_PMD_TEST_RXPMD_CONTROL3_OS_MODE_RX_PMD_MASK (0xfU)
#define S16UP_RX_PMD_TEST_RXPMD_CONTROL3_OS_MODE_RX_PMD_SHIFT (0U)




typedef volatile struct sS16UP_RX_PMD_TEST_RDBType {
    S16UP_RX_PMD_TEST_RESERVED_TYPE rsvd0[8]; /* OFFSET: 0x0 */
    S16UP_RX_PMD_TEST_RXPMD_CONTROL0_TYPE control0; /* OFFSET: 0x8 */
    S16UP_RX_PMD_TEST_RESERVED_TYPE rsvd1[2]; /* OFFSET: 0xa */
    S16UP_RX_PMD_TEST_RXPM_CONT1_TYPE control1; /* OFFSET: 0xc */
    S16UP_RX_PMD_TEST_RESERVED_TYPE rsvd2[2]; /* OFFSET: 0xe */
    S16UP_RX_PMD_TEST_RXPMD_CONTROL2_TYPE control2; /* OFFSET: 0x10 */
    S16UP_RX_PMD_TEST_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0x12 */
    S16UP_RX_PMD_TEST_RSC0_TYPE sigdet_ctrl0; /* OFFSET: 0x14 */
    S16UP_RX_PMD_TEST_RESERVED_TYPE rsvd4[2]; /* OFFSET: 0x16 */
    S16UP_RX_PMD_TEST_RXPMD_SIGDET_CTRL1_TYPE sigdet_ctrl1; /* OFFSET: 0x18 */
    S16UP_RX_PMD_TEST_RESERVED_TYPE rsvd5[2]; /* OFFSET: 0x1a */
    S16UP_RX_PMD_TEST_RXPMD_SIGDET_STATUS_TYPE sigdet_status; /* OFFSET: 0x1c */
    S16UP_RX_PMD_TEST_RESERVED_TYPE rsvd6[2]; /* OFFSET: 0x1e */
    S16UP_RX_PMD_TEST_RXPMD_CONTROL3_TYPE control3; /* OFFSET: 0x20 */
} S16UP_RX_PMD_TEST_RDBType;


#define RX_PMD_TEST_BASE                (0xE04E1880UL)



#define S16UP_RX_PMD_TEST_MAX_HW_ID     (1UL)

#endif /* S16UP_RX_PMD_TEST_RDB_H */
