/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file s16up_u_pcs_main0_rdb.h
    @brief RDB File for S16UP_U_PCS_MAIN0

    @version BCM89580_A0_20230125_RDB
*/

#ifndef S16UP_U_PCS_MAIN0_RDB_H
#define S16UP_U_PCS_MAIN0_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t S16UP_U_PCS_MAIN0_USETUP_0_TYPE;
#define S16UP_U_PCS_MAIN0_USETUP_0_SINGLE_PORT_MODE_MASK (0x8U)
#define S16UP_U_PCS_MAIN0_USETUP_0_SINGLE_PORT_MODE_SHIFT (3U)
#define S16UP_U_PCS_MAIN0_USETUP_0_STAND_ALONE_MODE_MASK (0x4U)
#define S16UP_U_PCS_MAIN0_USETUP_0_STAND_ALONE_MODE_SHIFT (2U)
#define S16UP_U_PCS_MAIN0_USETUP_0_PMD_IEEE_RST_DECOUPLE_EN_MASK (0x2U)
#define S16UP_U_PCS_MAIN0_USETUP_0_PMD_IEEE_RST_DECOUPLE_EN_SHIFT (1U)
#define S16UP_U_PCS_MAIN0_USETUP_0_MDIOREG_RST_SW_MASK (0x1U)
#define S16UP_U_PCS_MAIN0_USETUP_0_MDIOREG_RST_SW_SHIFT (0U)




typedef uint8_t S16UP_U_PCS_MAIN0_RESERVED_TYPE;




typedef uint16_t S16UP_U_PCS_MAIN0_USETUP_1_TYPE;
#define S16UP_U_PCS_MAIN0_USETUP_1_SW_UBAUD_FORCE_EN_MASK (0x100U)
#define S16UP_U_PCS_MAIN0_USETUP_1_SW_UBAUD_FORCE_EN_SHIFT (8U)
#define S16UP_U_PCS_MAIN0_USETUP_1_USXGMII_PCS_SEL_CKGATE_DISABLE_MASK (0x80U)
#define S16UP_U_PCS_MAIN0_USETUP_1_USXGMII_PCS_SEL_CKGATE_DISABLE_SHIFT (7U)
#define S16UP_U_PCS_MAIN0_USETUP_1_UPORT_BAUD_OVERRIDE_EN_MASK (0x40U)
#define S16UP_U_PCS_MAIN0_USETUP_1_UPORT_BAUD_OVERRIDE_EN_SHIFT (6U)
#define S16UP_U_PCS_MAIN0_USETUP_1_USXGMII_PCS_SEL_MASK (0x20U)
#define S16UP_U_PCS_MAIN0_USETUP_1_USXGMII_PCS_SEL_SHIFT (5U)
#define S16UP_U_PCS_MAIN0_USETUP_1_UPORT_NUM_MASK (0xcU)
#define S16UP_U_PCS_MAIN0_USETUP_1_UPORT_NUM_SHIFT (2U)
#define S16UP_U_PCS_MAIN0_USETUP_1_UBAUD_RATE_MASK (0x3U)
#define S16UP_U_PCS_MAIN0_USETUP_1_UBAUD_RATE_SHIFT (0U)




typedef uint16_t S16UP_U_PCS_MAIN0_UMISCDIGCONTROL_TYPE;
#define S16UP_U_PCS_MAIN0_UMISCDIGCONTROL_DRFR_MASK (0x800U)
#define S16UP_U_PCS_MAIN0_UMISCDIGCONTROL_DRFR_SHIFT (11U)
#define S16UP_U_PCS_MAIN0_UMISCDIGCONTROL_USE_IEEE_REG_CTRL_SEL_MASK (0x600U)
#define S16UP_U_PCS_MAIN0_UMISCDIGCONTROL_USE_IEEE_REG_CTRL_SEL_SHIFT (9U)
#define S16UP_U_PCS_MAIN0_UMISCDIGCONTROL_CREDIT_SW_EN_MASK (0x100U)
#define S16UP_U_PCS_MAIN0_UMISCDIGCONTROL_CREDIT_SW_EN_SHIFT (8U)
#define S16UP_U_PCS_MAIN0_UMISCDIGCONTROL_MAC_CREDITENABLE_MASK (0x80U)
#define S16UP_U_PCS_MAIN0_UMISCDIGCONTROL_MAC_CREDITENABLE_SHIFT (7U)
#define S16UP_U_PCS_MAIN0_UMISCDIGCONTROL_SASFE_MASK (0x40U)
#define S16UP_U_PCS_MAIN0_UMISCDIGCONTROL_SASFE_SHIFT (6U)
#define S16UP_U_PCS_MAIN0_UMISCDIGCONTROL_SW_ACTUAL_SPEED_MASK (0x3fU)
#define S16UP_U_PCS_MAIN0_UMISCDIGCONTROL_SW_ACTUAL_SPEED_SHIFT (0U)




typedef uint16_t S16UP_U_PCS_MAIN0_UPCS_MASKDATA_TYPE;
#define S16UP_U_PCS_MAIN0_UPCS_MASKDATA_MASK (0xffffU)
#define S16UP_U_PCS_MAIN0_UPCS_MASKDATA_SHIFT (0U)




typedef uint16_t S16UP_U_PCS_MAIN0_UMC_TYPE;
#define S16UP_U_PCS_MAIN0_UMC_PMD_PMI_LP_HIGH_PRIORITY_MASK (0x40U)
#define S16UP_U_PCS_MAIN0_UMC_PMD_PMI_LP_HIGH_PRIORITY_SHIFT (6U)
#define S16UP_U_PCS_MAIN0_UMC_DISABLE_ACK_TIMEOUT_MASK (0x20U)
#define S16UP_U_PCS_MAIN0_UMC_DISABLE_ACK_TIMEOUT_SHIFT (5U)
#define S16UP_U_PCS_MAIN0_UMC_PCS_MASKDATA_EN_MASK (0x10U)
#define S16UP_U_PCS_MAIN0_UMC_PCS_MASKDATA_EN_SHIFT (4U)
#define S16UP_U_PCS_MAIN0_UMC_PCS_MASKDATA_PINSEL_MASK (0x8U)
#define S16UP_U_PCS_MAIN0_UMC_PCS_MASKDATA_PINSEL_SHIFT (3U)
#define S16UP_U_PCS_MAIN0_UMC_PCS_MASKDATA_AUTO_RESET_MASK (0x4U)
#define S16UP_U_PCS_MAIN0_UMC_PCS_MASKDATA_AUTO_RESET_SHIFT (2U)
#define S16UP_U_PCS_MAIN0_UMC_PCS_MASKDATA_BUS_ASSIGN_MASK (0x3U)
#define S16UP_U_PCS_MAIN0_UMC_PCS_MASKDATA_BUS_ASSIGN_SHIFT (0U)




typedef uint16_t S16UP_U_PCS_MAIN0_UTICK_CONTROL_1_TYPE;
#define S16UP_U_PCS_MAIN0_UTICK_CONTROL_1_TICK_OVERRIDE_MASK (0x8000U)
#define S16UP_U_PCS_MAIN0_UTICK_CONTROL_1_TICK_OVERRIDE_SHIFT (15U)
#define S16UP_U_PCS_MAIN0_UTICK_CONTROL_1_TICK_NUMERATOR_UPPER_MASK (0x7fffU)
#define S16UP_U_PCS_MAIN0_UTICK_CONTROL_1_TICK_NUMERATOR_UPPER_SHIFT (0U)




typedef uint16_t S16UP_U_PCS_MAIN0_UTICK_CONTROL_0_TYPE;
#define S16UP_U_PCS_MAIN0_UTICK_CONTROL_0_TICK_NUMERATOR_LOWER_MASK (0xf000U)
#define S16UP_U_PCS_MAIN0_UTICK_CONTROL_0_TICK_NUMERATOR_LOWER_SHIFT (12U)
#define S16UP_U_PCS_MAIN0_UTICK_CONTROL_0_TICK_DENOMINATOR_MASK (0xffcU)
#define S16UP_U_PCS_MAIN0_UTICK_CONTROL_0_TICK_DENOMINATOR_SHIFT (2U)




typedef uint16_t S16UP_U_PCS_MAIN0_ULOO_CONT_TYPE;
#define S16UP_U_PCS_MAIN0_ULOO_CONT_REMOTE_PCS_LOOPBACK_ENABLE_MASK (0x20U)
#define S16UP_U_PCS_MAIN0_ULOO_CONT_REMOTE_PCS_LOOPBACK_ENABLE_SHIFT (5U)
#define S16UP_U_PCS_MAIN0_ULOO_CONT_LOCAL_PCS_LOOPBACK_ENABLE_MASK (0x10U)
#define S16UP_U_PCS_MAIN0_ULOO_CONT_LOCAL_PCS_LOOPBACK_ENABLE_SHIFT (4U)




typedef volatile struct sS16UP_U_PCS_MAIN0_RDBType {
    S16UP_U_PCS_MAIN0_USETUP_0_TYPE setup_0; /* OFFSET: 0x0 */
    S16UP_U_PCS_MAIN0_RESERVED_TYPE rsvd0[2]; /* OFFSET: 0x2 */
    S16UP_U_PCS_MAIN0_USETUP_1_TYPE setup_1; /* OFFSET: 0x4 */
    S16UP_U_PCS_MAIN0_RESERVED_TYPE rsvd1[2]; /* OFFSET: 0x6 */
    S16UP_U_PCS_MAIN0_UMISCDIGCONTROL_TYPE miscdigcontrol; /* OFFSET: 0x8 */
    S16UP_U_PCS_MAIN0_RESERVED_TYPE rsvd2[10]; /* OFFSET: 0xa */
    S16UP_U_PCS_MAIN0_UPCS_MASKDATA_TYPE pcs_maskdata; /* OFFSET: 0x14 */
    S16UP_U_PCS_MAIN0_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0x16 */
    S16UP_U_PCS_MAIN0_UMC_TYPE pcs_maskdata_ctrl; /* OFFSET: 0x18 */
    S16UP_U_PCS_MAIN0_RESERVED_TYPE rsvd4[2]; /* OFFSET: 0x1a */
    S16UP_U_PCS_MAIN0_UTICK_CONTROL_1_TYPE tick_control_1; /* OFFSET: 0x1c */
    S16UP_U_PCS_MAIN0_RESERVED_TYPE rsvd5[2]; /* OFFSET: 0x1e */
    S16UP_U_PCS_MAIN0_UTICK_CONTROL_0_TYPE tick_control_0; /* OFFSET: 0x20 */
    S16UP_U_PCS_MAIN0_RESERVED_TYPE rsvd6[2]; /* OFFSET: 0x22 */
    S16UP_U_PCS_MAIN0_ULOO_CONT_TYPE loopback_control; /* OFFSET: 0x24 */
} S16UP_U_PCS_MAIN0_RDBType;


#define U_PCS_MAIN0_BASE                (0xE04E4C00UL)



#define S16UP_U_PCS_MAIN0_MAX_HW_ID     (1UL)

#endif /* S16UP_U_PCS_MAIN0_RDB_H */
