/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file s16up_txrx_actrl_rdb.h
    @brief RDB File for S16UP_TXRX_ACTRL

    @version BCM89580_A0_20230125_RDB
*/

#ifndef S16UP_TXRX_ACTRL_RDB_H
#define S16UP_TXRX_ACTRL_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t S16UP_TXRX_ACTRL_RX0_15_00_TYPE;
#define S16UP_TXRX_ACTRL_RX0_15_00_RXBIT_MASK (0xffffU)
#define S16UP_TXRX_ACTRL_RX0_15_00_RXBIT_SHIFT (0U)




typedef uint8_t S16UP_TXRX_ACTRL_RESERVED_TYPE;




typedef uint16_t S16UP_TXRX_ACTRL_RX0_31_16_TYPE;
#define S16UP_TXRX_ACTRL_RX0_31_16_RXBIT_MASK (0xffffU)
#define S16UP_TXRX_ACTRL_RX0_31_16_RXBIT_SHIFT (0U)




typedef uint16_t S16UP_TXRX_ACTRL_RX0_47_32_TYPE;
#define S16UP_TXRX_ACTRL_RX0_47_32_RXBIT_MASK (0xffffU)
#define S16UP_TXRX_ACTRL_RX0_47_32_RXBIT_SHIFT (0U)




typedef uint16_t S16UP_TXRX_ACTRL_RX0_63_48_TYPE;
#define S16UP_TXRX_ACTRL_RX0_63_48_RXBIT_MASK (0xffffU)
#define S16UP_TXRX_ACTRL_RX0_63_48_RXBIT_SHIFT (0U)




typedef uint16_t S16UP_TXRX_ACTRL_RX0_79_64_TYPE;
#define S16UP_TXRX_ACTRL_RX0_79_64_RXBIT_MASK (0xffffU)
#define S16UP_TXRX_ACTRL_RX0_79_64_RXBIT_SHIFT (0U)




typedef uint16_t S16UP_TXRX_ACTRL_RX0_95_80_TYPE;
#define S16UP_TXRX_ACTRL_RX0_95_80_RXBIT_MASK (0xffffU)
#define S16UP_TXRX_ACTRL_RX0_95_80_RXBIT_SHIFT (0U)




typedef uint16_t S16UP_TXRX_ACTRL_TX0_15_00_TYPE;
#define S16UP_TXRX_ACTRL_TX0_15_00_TXBIT_MASK (0xffffU)
#define S16UP_TXRX_ACTRL_TX0_15_00_TXBIT_SHIFT (0U)




typedef uint16_t S16UP_TXRX_ACTRL_TX0_31_16_TYPE;
#define S16UP_TXRX_ACTRL_TX0_31_16_TXBIT_MASK (0xffffU)
#define S16UP_TXRX_ACTRL_TX0_31_16_TXBIT_SHIFT (0U)




typedef uint16_t S16UP_TXRX_ACTRL_TX0_47_32_TYPE;
#define S16UP_TXRX_ACTRL_TX0_47_32_TXBIT_MASK (0xffffU)
#define S16UP_TXRX_ACTRL_TX0_47_32_TXBIT_SHIFT (0U)




typedef uint16_t S16UP_TXRX_ACTRL_TX0_63_48_TYPE;
#define S16UP_TXRX_ACTRL_TX0_63_48_TXBIT_MASK (0xffffU)
#define S16UP_TXRX_ACTRL_TX0_63_48_TXBIT_SHIFT (0U)




typedef uint16_t S16UP_TXRX_ACTRL_TX_PHY_STATUS_TYPE;
#define S16UP_TXRX_ACTRL_TX_PHY_STATUS_I_RXDET_MASK (0x8000U)
#define S16UP_TXRX_ACTRL_TX_PHY_STATUS_I_RXDET_SHIFT (15U)
#define S16UP_TXRX_ACTRL_TX_PHY_STATUS_TX_SYNC_PDOUT_MASK (0x4000U)
#define S16UP_TXRX_ACTRL_TX_PHY_STATUS_TX_SYNC_PDOUT_SHIFT (14U)
#define S16UP_TXRX_ACTRL_TX_PHY_STATUS_TX_LFPS_BEACON_EN_MASK (0x2000U)
#define S16UP_TXRX_ACTRL_TX_PHY_STATUS_TX_LFPS_BEACON_EN_SHIFT (13U)
#define S16UP_TXRX_ACTRL_TX_PHY_STATUS_TX_ELEC_IDLE_MASK (0x1000U)
#define S16UP_TXRX_ACTRL_TX_PHY_STATUS_TX_ELEC_IDLE_SHIFT (12U)
#define S16UP_TXRX_ACTRL_TX_PHY_STATUS_TX_RXDETREQ_MASK (0x800U)
#define S16UP_TXRX_ACTRL_TX_PHY_STATUS_TX_RXDETREQ_SHIFT (11U)
#define S16UP_TXRX_ACTRL_TX_PHY_STATUS_TX_RATESELECT_MASK (0x400U)
#define S16UP_TXRX_ACTRL_TX_PHY_STATUS_TX_RATESELECT_SHIFT (10U)
#define S16UP_TXRX_ACTRL_TX_PHY_STATUS_TX_SLEWRATE_CONTROL_MASK (0x300U)
#define S16UP_TXRX_ACTRL_TX_PHY_STATUS_TX_SLEWRATE_CONTROL_SHIFT (8U)
#define S16UP_TXRX_ACTRL_TX_PHY_STATUS_TX_RESET_AFE_MASK (0x80U)
#define S16UP_TXRX_ACTRL_TX_PHY_STATUS_TX_RESET_AFE_SHIFT (7U)
#define S16UP_TXRX_ACTRL_TX_PHY_STATUS_TX_PD_MASK (0x40U)
#define S16UP_TXRX_ACTRL_TX_PHY_STATUS_TX_PD_SHIFT (6U)
#define S16UP_TXRX_ACTRL_TX_PHY_STATUS_TXLOCK_CDR_MASK (0x20U)
#define S16UP_TXRX_ACTRL_TX_PHY_STATUS_TXLOCK_CDR_SHIFT (5U)
#define S16UP_TXRX_ACTRL_TX_PHY_STATUS_TXRESET_PMD_MASK (0x10U)
#define S16UP_TXRX_ACTRL_TX_PHY_STATUS_TXRESET_PMD_SHIFT (4U)
#define S16UP_TXRX_ACTRL_TX_PHY_STATUS_TX_DATA_RATE_MASK (0xcU)
#define S16UP_TXRX_ACTRL_TX_PHY_STATUS_TX_DATA_RATE_SHIFT (2U)
#define S16UP_TXRX_ACTRL_TX_PHY_STATUS_SSC_EN_MASK (0x2U)
#define S16UP_TXRX_ACTRL_TX_PHY_STATUS_SSC_EN_SHIFT (1U)
#define S16UP_TXRX_ACTRL_TX_PHY_STATUS_TX_PMD_EN_MASK (0x1U)
#define S16UP_TXRX_ACTRL_TX_PHY_STATUS_TX_PMD_EN_SHIFT (0U)




typedef uint16_t S16UP_TXRX_ACTRL_RX_PHY_STATUS_TYPE;
#define S16UP_TXRX_ACTRL_RX_PHY_STATUS_RX_SIGDET_MASK (0x8000U)
#define S16UP_TXRX_ACTRL_RX_PHY_STATUS_RX_SIGDET_SHIFT (15U)
#define S16UP_TXRX_ACTRL_RX_PHY_STATUS_RX_SIGDET_PD_MASK (0x2000U)
#define S16UP_TXRX_ACTRL_RX_PHY_STATUS_RX_SIGDET_PD_SHIFT (13U)
#define S16UP_TXRX_ACTRL_RX_PHY_STATUS_RX_PD_MASK (0x1000U)
#define S16UP_TXRX_ACTRL_RX_PHY_STATUS_RX_PD_SHIFT (12U)
#define S16UP_TXRX_ACTRL_RX_PHY_STATUS_RX_HIZ_MASK (0x800U)
#define S16UP_TXRX_ACTRL_RX_PHY_STATUS_RX_HIZ_SHIFT (11U)
#define S16UP_TXRX_ACTRL_RX_PHY_STATUS_RX_RESET_AFE_MASK (0x400U)
#define S16UP_TXRX_ACTRL_RX_PHY_STATUS_RX_RESET_AFE_SHIFT (10U)
#define S16UP_TXRX_ACTRL_RX_PHY_STATUS_TEST_MASK (0x100U)
#define S16UP_TXRX_ACTRL_RX_PHY_STATUS_TEST_SHIFT (8U)
#define S16UP_TXRX_ACTRL_RX_PHY_STATUS_AEQ_DONE_MASK (0x80U)
#define S16UP_TXRX_ACTRL_RX_PHY_STATUS_AEQ_DONE_SHIFT (7U)
#define S16UP_TXRX_ACTRL_RX_PHY_STATUS_RX_PMD_EN_MASK (0x40U)
#define S16UP_TXRX_ACTRL_RX_PHY_STATUS_RX_PMD_EN_SHIFT (6U)
#define S16UP_TXRX_ACTRL_RX_PHY_STATUS_SLCAL_ENABLE_MASK (0x20U)
#define S16UP_TXRX_ACTRL_RX_PHY_STATUS_SLCAL_ENABLE_SHIFT (5U)
#define S16UP_TXRX_ACTRL_RX_PHY_STATUS_AEQ_ENABLE_MASK (0x10U)
#define S16UP_TXRX_ACTRL_RX_PHY_STATUS_AEQ_ENABLE_SHIFT (4U)
#define S16UP_TXRX_ACTRL_RX_PHY_STATUS_AEQ_FREEZE_MASK (0x8U)
#define S16UP_TXRX_ACTRL_RX_PHY_STATUS_AEQ_FREEZE_SHIFT (3U)
#define S16UP_TXRX_ACTRL_RX_PHY_STATUS_RXRESET_PMD_MASK (0x4U)
#define S16UP_TXRX_ACTRL_RX_PHY_STATUS_RXRESET_PMD_SHIFT (2U)
#define S16UP_TXRX_ACTRL_RX_PHY_STATUS_ADAPT_RESULT_OVRD_EN_MASK (0x2U)
#define S16UP_TXRX_ACTRL_RX_PHY_STATUS_ADAPT_RESULT_OVRD_EN_SHIFT (1U)
#define S16UP_TXRX_ACTRL_RX_PHY_STATUS_SLCAL_RESEULT_OVRD_EN_MASK (0x1U)
#define S16UP_TXRX_ACTRL_RX_PHY_STATUS_SLCAL_RESEULT_OVRD_EN_SHIFT (0U)




typedef uint16_t S16UP_TXRX_ACTRL_TX0_79_64_TYPE;
#define S16UP_TXRX_ACTRL_TX0_79_64_TXBIT_MASK (0xffffU)
#define S16UP_TXRX_ACTRL_TX0_79_64_TXBIT_SHIFT (0U)




typedef volatile struct sS16UP_TXRX_ACTRL_RDBType {
    S16UP_TXRX_ACTRL_RX0_15_00_TYPE rx0_15_00; /* OFFSET: 0x0 */
    S16UP_TXRX_ACTRL_RESERVED_TYPE rsvd0[2]; /* OFFSET: 0x2 */
    S16UP_TXRX_ACTRL_RX0_31_16_TYPE rx0_31_16; /* OFFSET: 0x4 */
    S16UP_TXRX_ACTRL_RESERVED_TYPE rsvd1[2]; /* OFFSET: 0x6 */
    S16UP_TXRX_ACTRL_RX0_47_32_TYPE rx0_47_32; /* OFFSET: 0x8 */
    S16UP_TXRX_ACTRL_RESERVED_TYPE rsvd2[2]; /* OFFSET: 0xa */
    S16UP_TXRX_ACTRL_RX0_63_48_TYPE rx0_63_48; /* OFFSET: 0xc */
    S16UP_TXRX_ACTRL_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0xe */
    S16UP_TXRX_ACTRL_RX0_79_64_TYPE rx0_79_64; /* OFFSET: 0x10 */
    S16UP_TXRX_ACTRL_RESERVED_TYPE rsvd4[2]; /* OFFSET: 0x12 */
    S16UP_TXRX_ACTRL_RX0_95_80_TYPE rx0_95_80; /* OFFSET: 0x14 */
    S16UP_TXRX_ACTRL_RESERVED_TYPE rsvd5[10]; /* OFFSET: 0x16 */
    S16UP_TXRX_ACTRL_TX0_15_00_TYPE tx0_15_00; /* OFFSET: 0x20 */
    S16UP_TXRX_ACTRL_RESERVED_TYPE rsvd6[2]; /* OFFSET: 0x22 */
    S16UP_TXRX_ACTRL_TX0_31_16_TYPE tx0_31_16; /* OFFSET: 0x24 */
    S16UP_TXRX_ACTRL_RESERVED_TYPE rsvd7[2]; /* OFFSET: 0x26 */
    S16UP_TXRX_ACTRL_TX0_47_32_TYPE tx0_47_32; /* OFFSET: 0x28 */
    S16UP_TXRX_ACTRL_RESERVED_TYPE rsvd8[2]; /* OFFSET: 0x2a */
    S16UP_TXRX_ACTRL_TX0_63_48_TYPE tx0_63_48; /* OFFSET: 0x2c */
    S16UP_TXRX_ACTRL_RESERVED_TYPE rsvd9[2]; /* OFFSET: 0x2e */
    S16UP_TXRX_ACTRL_TX_PHY_STATUS_TYPE tx_phy_status; /* OFFSET: 0x30 */
    S16UP_TXRX_ACTRL_RESERVED_TYPE rsvd10[2]; /* OFFSET: 0x32 */
    S16UP_TXRX_ACTRL_RX_PHY_STATUS_TYPE rx_phy_status; /* OFFSET: 0x34 */
    S16UP_TXRX_ACTRL_RESERVED_TYPE rsvd11[2]; /* OFFSET: 0x36 */
    S16UP_TXRX_ACTRL_TX0_79_64_TYPE tx0_79_64; /* OFFSET: 0x38 */
} S16UP_TXRX_ACTRL_RDBType;


#define TXRX_ACTRL_AFE_BASE             (0xE0468140UL)



#define S16UP_TXRX_ACTRL_MAX_HW_ID      (1UL)

#endif /* S16UP_TXRX_ACTRL_RDB_H */
