/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file s16up_u_tx_x1_control1_rdb.h
    @brief RDB File for S16UP_U_TX_X1_CONTROL1

    @version BCM89580_A0_20230125_RDB
*/

#ifndef S16UP_U_TX_X1_CONTROL1_RDB_H
#define S16UP_U_TX_X1_CONTROL1_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t S16UP_U_TX_X1_CONTROL1_RESERVED_TYPE;




typedef uint16_t S16UP_U_TX_X1_CONTROL1_UENCODE_0_TYPE;
#define S16UP_U_TX_X1_CONTROL1_UENCODE_0_CL49_HIGIG2_MSG_32BYTES_MASK (0x2000U)
#define S16UP_U_TX_X1_CONTROL1_UENCODE_0_CL49_HIGIG2_MSG_32BYTES_SHIFT (13U)
#define S16UP_U_TX_X1_CONTROL1_UENCODE_0_HG2_CODEC_MASK (0x1000U)
#define S16UP_U_TX_X1_CONTROL1_UENCODE_0_HG2_CODEC_SHIFT (12U)
#define S16UP_U_TX_X1_CONTROL1_UENCODE_0_H2MICE_MASK (0x800U)
#define S16UP_U_TX_X1_CONTROL1_UENCODE_0_H2MICE_SHIFT (11U)
#define S16UP_U_TX_X1_CONTROL1_UENCODE_0_HG2_ENABLE_MASK (0x400U)
#define S16UP_U_TX_X1_CONTROL1_UENCODE_0_HG2_ENABLE_SHIFT (10U)
#define S16UP_U_TX_X1_CONTROL1_UENCODE_0_CL49_BYPASS_TXSM_MASK (0x200U)
#define S16UP_U_TX_X1_CONTROL1_UENCODE_0_CL49_BYPASS_TXSM_SHIFT (9U)
#define S16UP_U_TX_X1_CONTROL1_UENCODE_0_CL49_TX_TL_MODE_MASK (0x60U)
#define S16UP_U_TX_X1_CONTROL1_UENCODE_0_CL49_TX_TL_MODE_SHIFT (5U)
#define S16UP_U_TX_X1_CONTROL1_UENCODE_0_ENCODEMODE_MASK (0x1cU)
#define S16UP_U_TX_X1_CONTROL1_UENCODE_0_ENCODEMODE_SHIFT (2U)




typedef uint16_t S16UP_U_TX_X1_CONTROL1_UENCODE_1_TYPE;
#define S16UP_U_TX_X1_CONTROL1_UENCODE_1_CATCH_ALL_8B10B_DIS_MASK (0x200U)
#define S16UP_U_TX_X1_CONTROL1_UENCODE_1_CATCH_ALL_8B10B_DIS_SHIFT (9U)
#define S16UP_U_TX_X1_CONTROL1_UENCODE_1_PROG_TL_EN_MASK (0x100U)
#define S16UP_U_TX_X1_CONTROL1_UENCODE_1_PROG_TL_EN_SHIFT (8U)
#define S16UP_U_TX_X1_CONTROL1_UENCODE_1_PROG_TL_CHAR_MASK (0xffU)
#define S16UP_U_TX_X1_CONTROL1_UENCODE_1_PROG_TL_CHAR_SHIFT (0U)




typedef uint16_t S16UP_U_TX_X1_CONTROL1_UMISC_TYPE;
#define S16UP_U_TX_X1_CONTROL1_UMISC_RST_DV_GEN_TX_MASK (0x4000U)
#define S16UP_U_TX_X1_CONTROL1_UMISC_RST_DV_GEN_TX_SHIFT (14U)
#define S16UP_U_TX_X1_CONTROL1_UMISC_TX_GBOX_PRST_MASK (0x2000U)
#define S16UP_U_TX_X1_CONTROL1_UMISC_TX_GBOX_PRST_SHIFT (13U)
#define S16UP_U_TX_X1_CONTROL1_UMISC_TX_GBOX_ERR_DET_CLR_MASK (0x1000U)
#define S16UP_U_TX_X1_CONTROL1_UMISC_TX_GBOX_ERR_DET_CLR_SHIFT (12U)
#define S16UP_U_TX_X1_CONTROL1_UMISC_TX_GBOX_AFRST_EN_MASK (0x800U)
#define S16UP_U_TX_X1_CONTROL1_UMISC_TX_GBOX_AFRST_EN_SHIFT (11U)
#define S16UP_U_TX_X1_CONTROL1_UMISC_FEC_ENABLE_MASK (0x400U)
#define S16UP_U_TX_X1_CONTROL1_UMISC_FEC_ENABLE_SHIFT (10U)
#define S16UP_U_TX_X1_CONTROL1_UMISC_TX_GBOX_ERRDET_SEL_MASK (0x200U)
#define S16UP_U_TX_X1_CONTROL1_UMISC_TX_GBOX_ERRDET_SEL_SHIFT (9U)
#define S16UP_U_TX_X1_CONTROL1_UMISC_CL49_TX_LI_ENABLE_MASK (0x100U)
#define S16UP_U_TX_X1_CONTROL1_UMISC_CL49_TX_LI_ENABLE_SHIFT (8U)
#define S16UP_U_TX_X1_CONTROL1_UMISC_CL49_TX_LF_ENABLE_MASK (0x80U)
#define S16UP_U_TX_X1_CONTROL1_UMISC_CL49_TX_LF_ENABLE_SHIFT (7U)
#define S16UP_U_TX_X1_CONTROL1_UMISC_CL49_TX_RF_ENABLE_MASK (0x40U)
#define S16UP_U_TX_X1_CONTROL1_UMISC_CL49_TX_RF_ENABLE_SHIFT (6U)
#define S16UP_U_TX_X1_CONTROL1_UMISC_TX_FIFO_WATERMARK_MASK (0xcU)
#define S16UP_U_TX_X1_CONTROL1_UMISC_TX_FIFO_WATERMARK_SHIFT (2U)
#define S16UP_U_TX_X1_CONTROL1_UMISC_RSTB_TX_LANE_MASK (0x2U)
#define S16UP_U_TX_X1_CONTROL1_UMISC_RSTB_TX_LANE_SHIFT (1U)
#define S16UP_U_TX_X1_CONTROL1_UMISC_ENABLE_TX_LANE_MASK (0x1U)
#define S16UP_U_TX_X1_CONTROL1_UMISC_ENABLE_TX_LANE_SHIFT (0U)




typedef uint16_t S16UP_U_TX_X1_CONTROL1_UMISC1_TYPE;
#define S16UP_U_TX_X1_CONTROL1_UMISC1_PMD_TX_DISABLE_MASK (0x20U)
#define S16UP_U_TX_X1_CONTROL1_UMISC1_PMD_TX_DISABLE_SHIFT (5U)
#define S16UP_U_TX_X1_CONTROL1_UMISC1_TX_TXPOL_FLIP_MASK (0x10U)
#define S16UP_U_TX_X1_CONTROL1_UMISC1_TX_TXPOL_FLIP_SHIFT (4U)
#define S16UP_U_TX_X1_CONTROL1_UMISC1_TX_DISABLE_MASK (0x8U)
#define S16UP_U_TX_X1_CONTROL1_UMISC1_TX_DISABLE_SHIFT (3U)
#define S16UP_U_TX_X1_CONTROL1_UMISC1_TX_GBOX_AFRST_SEL_MASK (0x6U)
#define S16UP_U_TX_X1_CONTROL1_UMISC1_TX_GBOX_AFRST_SEL_SHIFT (1U)
#define S16UP_U_TX_X1_CONTROL1_UMISC1_TX_GBOX_WATERMARK_MODE_MASK (0x1U)
#define S16UP_U_TX_X1_CONTROL1_UMISC1_TX_GBOX_WATERMARK_MODE_SHIFT (0U)




typedef uint16_t S16UP_U_TX_X1_CONTROL1_UFP25C0_TYPE;
#define S16UP_U_TX_X1_CONTROL1_UFP25C0_RS_FEC_ENABLE_MASK (0x200U)
#define S16UP_U_TX_X1_CONTROL1_UFP25C0_RS_FEC_ENABLE_SHIFT (9U)
#define S16UP_U_TX_X1_CONTROL1_UFP25C0_FEC_P25G_TX_ENCODE_MODE_MASK (0x1e0U)
#define S16UP_U_TX_X1_CONTROL1_UFP25C0_FEC_P25G_TX_ENCODE_MODE_SHIFT (5U)
#define S16UP_U_TX_X1_CONTROL1_UFP25C0_U_MDIO_CWM_OVERRIDE_EN_MASK (0x10U)
#define S16UP_U_TX_X1_CONTROL1_UFP25C0_U_MDIO_CWM_OVERRIDE_EN_SHIFT (4U)
#define S16UP_U_TX_X1_CONTROL1_UFP25C0_U_AM_SPACING_OVERRIDE_EN_MASK (0x2U)
#define S16UP_U_TX_X1_CONTROL1_UFP25C0_U_AM_SPACING_OVERRIDE_EN_SHIFT (1U)
#define S16UP_U_TX_X1_CONTROL1_UFP25C0_U_MDIO_FIXED_CWM_EN_MASK (0x1U)
#define S16UP_U_TX_X1_CONTROL1_UFP25C0_U_MDIO_FIXED_CWM_EN_SHIFT (0U)




typedef uint16_t S16UP_U_TX_X1_CONTROL1_UFP25C1_TYPE;
#define S16UP_U_TX_X1_CONTROL1_UFP25C1_AM_SPACING_AM_COUNT_MASK (0xffffU)
#define S16UP_U_TX_X1_CONTROL1_UFP25C1_AM_SPACING_AM_COUNT_SHIFT (0U)




typedef uint16_t S16UP_U_TX_X1_CONTROL1_UFP25C2_TYPE;
#define S16UP_U_TX_X1_CONTROL1_UFP25C2_AM_SPACING_CW_CNT_MAX_MASK (0x7fffU)
#define S16UP_U_TX_X1_CONTROL1_UFP25C2_AM_SPACING_CW_CNT_MAX_SHIFT (0U)




typedef uint16_t S16UP_U_TX_X1_CONTROL1_UDDC0_TYPE;
#define S16UP_U_TX_X1_CONTROL1_UDDC0_CLK_DV_GMII_DLY_SEL_MASK (0x7000U)
#define S16UP_U_TX_X1_CONTROL1_UDDC0_CLK_DV_GMII_DLY_SEL_SHIFT (12U)
#define S16UP_U_TX_X1_CONTROL1_UDDC0_CLK_DV_GMII_INTF_DLY_SEL_MASK (0xe00U)
#define S16UP_U_TX_X1_CONTROL1_UDDC0_CLK_DV_GMII_INTF_DLY_SEL_SHIFT (9U)
#define S16UP_U_TX_X1_CONTROL1_UDDC0_CLK_DV_XGMII_INTF_DLY_SEL_MASK (0x1c0U)
#define S16UP_U_TX_X1_CONTROL1_UDDC0_CLK_DV_XGMII_INTF_DLY_SEL_SHIFT (6U)
#define S16UP_U_TX_X1_CONTROL1_UDDC0_CLK_DV_XGMII_DLY_SEL_MASK (0x38U)
#define S16UP_U_TX_X1_CONTROL1_UDDC0_CLK_DV_XGMII_DLY_SEL_SHIFT (3U)
#define S16UP_U_TX_X1_CONTROL1_UDDC0_CLK_DV_2X_XGMII_DLY_SEL_MASK (0x7U)
#define S16UP_U_TX_X1_CONTROL1_UDDC0_CLK_DV_2X_XGMII_DLY_SEL_SHIFT (0U)




typedef uint16_t S16UP_U_TX_X1_CONTROL1_UDDC1_TYPE;
#define S16UP_U_TX_X1_CONTROL1_UDDC1_CLK_DV_GMII_BYTE_DLY_SEL_MASK (0x7000U)
#define S16UP_U_TX_X1_CONTROL1_UDDC1_CLK_DV_GMII_BYTE_DLY_SEL_SHIFT (12U)
#define S16UP_U_TX_X1_CONTROL1_UDDC1_BYTE_CNT_GMII_BYTE_DLY_SEL_MASK (0xe00U)
#define S16UP_U_TX_X1_CONTROL1_UDDC1_BYTE_CNT_GMII_BYTE_DLY_SEL_SHIFT (9U)
#define S16UP_U_TX_X1_CONTROL1_UDDC1_CLK_DV_XGMII_0PPM_DLY_SEL_MASK (0x1c0U)
#define S16UP_U_TX_X1_CONTROL1_UDDC1_CLK_DV_XGMII_0PPM_DLY_SEL_SHIFT (6U)
#define S16UP_U_TX_X1_CONTROL1_UDDC1_CLK_DV_XGMII_AMPPM_DLY_SEL_MASK (0x38U)
#define S16UP_U_TX_X1_CONTROL1_UDDC1_CLK_DV_XGMII_AMPPM_DLY_SEL_SHIFT (3U)
#define S16UP_U_TX_X1_CONTROL1_UDDC1_CLK_DV_USXGMII_AN_DLY_SEL_MASK (0x7U)
#define S16UP_U_TX_X1_CONTROL1_UDDC1_CLK_DV_USXGMII_AN_DLY_SEL_SHIFT (0U)




typedef uint16_t S16UP_U_TX_X1_CONTROL1_UDDC2_TYPE;
#define S16UP_U_TX_X1_CONTROL1_UDDC2_CD15625IDS_MASK (0x7000U)
#define S16UP_U_TX_X1_CONTROL1_UDDC2_CD15625IDS_SHIFT (12U)
#define S16UP_U_TX_X1_CONTROL1_UDDC2_CLK_DV_REPX_RD_DLY_SEL_MASK (0xe00U)
#define S16UP_U_TX_X1_CONTROL1_UDDC2_CLK_DV_REPX_RD_DLY_SEL_SHIFT (9U)
#define S16UP_U_TX_X1_CONTROL1_UDDC2_CLK_DV_BASER_AMPPM_DLY_SEL_MASK (0x1c0U)
#define S16UP_U_TX_X1_CONTROL1_UDDC2_CLK_DV_BASER_AMPPM_DLY_SEL_SHIFT (6U)
#define S16UP_U_TX_X1_CONTROL1_UDDC2_CLK_DV_BASER_0PPM_DLY_SEL_MASK (0x38U)
#define S16UP_U_TX_X1_CONTROL1_UDDC2_CLK_DV_BASER_0PPM_DLY_SEL_SHIFT (3U)
#define S16UP_U_TX_X1_CONTROL1_UDDC2_TDM_AMPPM_PORT_NUM_DLY_SEL_MASK (0x7U)
#define S16UP_U_TX_X1_CONTROL1_UDDC2_TDM_AMPPM_PORT_NUM_DLY_SEL_SHIFT (0U)




typedef uint16_t S16UP_U_TX_X1_CONTROL1_UFP25C3_TYPE;
#define S16UP_U_TX_X1_CONTROL1_UFP25C3_AM_SPACING_AM_COUNTH_MASK (0xffffU)
#define S16UP_U_TX_X1_CONTROL1_UFP25C3_AM_SPACING_AM_COUNTH_SHIFT (0U)




typedef uint16_t S16UP_U_TX_X1_CONTROL1_UFP25C4_TYPE;
#define S16UP_U_TX_X1_CONTROL1_UFP25C4_AM_SPACING_CW_CNT_MAXH_MASK (0x7fffU)
#define S16UP_U_TX_X1_CONTROL1_UFP25C4_AM_SPACING_CW_CNT_MAXH_SHIFT (0U)




typedef volatile struct sS16UP_U_TX_X1_CONTROL1_RDBType {
    S16UP_U_TX_X1_CONTROL1_RESERVED_TYPE rsvd0[4]; /* OFFSET: 0x0 */
    S16UP_U_TX_X1_CONTROL1_UENCODE_0_TYPE encode_0; /* OFFSET: 0x4 */
    S16UP_U_TX_X1_CONTROL1_RESERVED_TYPE rsvd1[2]; /* OFFSET: 0x6 */
    S16UP_U_TX_X1_CONTROL1_UENCODE_1_TYPE encode_1; /* OFFSET: 0x8 */
    S16UP_U_TX_X1_CONTROL1_RESERVED_TYPE rsvd2[2]; /* OFFSET: 0xa */
    S16UP_U_TX_X1_CONTROL1_UMISC_TYPE misc; /* OFFSET: 0xc */
    S16UP_U_TX_X1_CONTROL1_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0xe */
    S16UP_U_TX_X1_CONTROL1_UMISC1_TYPE misc1; /* OFFSET: 0x10 */
    S16UP_U_TX_X1_CONTROL1_RESERVED_TYPE rsvd4[2]; /* OFFSET: 0x12 */
    S16UP_U_TX_X1_CONTROL1_UFP25C0_TYPE tx_fec_p25g_control0; /* OFFSET: 0x14 */
    S16UP_U_TX_X1_CONTROL1_RESERVED_TYPE rsvd5[2]; /* OFFSET: 0x16 */
    S16UP_U_TX_X1_CONTROL1_UFP25C1_TYPE tx_fec_p25g_control1; /* OFFSET: 0x18 */
    S16UP_U_TX_X1_CONTROL1_RESERVED_TYPE rsvd6[2]; /* OFFSET: 0x1a */
    S16UP_U_TX_X1_CONTROL1_UFP25C2_TYPE tx_fec_p25g_control2; /* OFFSET: 0x1c */
    S16UP_U_TX_X1_CONTROL1_RESERVED_TYPE rsvd7[2]; /* OFFSET: 0x1e */
    S16UP_U_TX_X1_CONTROL1_UDDC0_TYPE clk_dv_dly_control0; /* OFFSET: 0x20 */
    S16UP_U_TX_X1_CONTROL1_RESERVED_TYPE rsvd8[2]; /* OFFSET: 0x22 */
    S16UP_U_TX_X1_CONTROL1_UDDC1_TYPE clk_dv_dly_control1; /* OFFSET: 0x24 */
    S16UP_U_TX_X1_CONTROL1_RESERVED_TYPE rsvd9[2]; /* OFFSET: 0x26 */
    S16UP_U_TX_X1_CONTROL1_UDDC2_TYPE clk_dv_dly_control2; /* OFFSET: 0x28 */
    S16UP_U_TX_X1_CONTROL1_RESERVED_TYPE rsvd10[2]; /* OFFSET: 0x2a */
    S16UP_U_TX_X1_CONTROL1_UFP25C3_TYPE tx_fec_p25g_control3; /* OFFSET: 0x2c */
    S16UP_U_TX_X1_CONTROL1_RESERVED_TYPE rsvd11[2]; /* OFFSET: 0x2e */
    S16UP_U_TX_X1_CONTROL1_UFP25C4_TYPE tx_fec_p25g_control4; /* OFFSET: 0x30 */
} S16UP_U_TX_X1_CONTROL1_RDBType;


#define U_TX_X1_CONTROL1_BASE           (0xE04E5040UL)



#define S16UP_U_TX_X1_CONTROL1_MAX_HW_ID  (1UL)

#endif /* S16UP_U_TX_X1_CONTROL1_RDB_H */
