/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file acqcmn_intr_rdb.h
    @brief RDB File for ACQCMN_INTR

    @version BCM89580_A0_20230125_RDB
*/

#ifndef ACQCMN_INTR_RDB_H
#define ACQCMN_INTR_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIPR_TYPE;
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIPR_P_CAPEVT7_INTR_MASK (0x8000UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIPR_P_CAPEVT7_INTR_SHIFT (15UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIPR_P_CAPEVT6_INTR_MASK (0x4000UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIPR_P_CAPEVT6_INTR_SHIFT (14UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIPR_P_CAPEVT5_INTR_MASK (0x2000UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIPR_P_CAPEVT5_INTR_SHIFT (13UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIPR_P_CAPEVT4_INTR_MASK (0x1000UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIPR_P_CAPEVT4_INTR_SHIFT (12UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIPR_P_CAPEVT3_INTR_MASK (0x800UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIPR_P_CAPEVT3_INTR_SHIFT (11UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIPR_P_CAPEVT2_INTR_MASK (0x400UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIPR_P_CAPEVT2_INTR_SHIFT (10UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIPR_P_CAPEVT1_INTR_MASK (0x200UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIPR_P_CAPEVT1_INTR_SHIFT (9UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIPR_P_CAPEVT0_INTR_MASK (0x100UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIPR_P_CAPEVT0_INTR_SHIFT (8UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIPR_P_GENEVT7_INTR_MASK (0x80UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIPR_P_GENEVT7_INTR_SHIFT (7UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIPR_P_GENEVT6_INTR_MASK (0x40UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIPR_P_GENEVT6_INTR_SHIFT (6UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIPR_P_GENEVT5_INTR_MASK (0x20UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIPR_P_GENEVT5_INTR_SHIFT (5UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIPR_P_GENEVT4_INTR_MASK (0x10UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIPR_P_GENEVT4_INTR_SHIFT (4UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIPR_P_GENEVT3_INTR_MASK (0x8UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIPR_P_GENEVT3_INTR_SHIFT (3UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIPR_P_GENEVT2_INTR_MASK (0x4UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIPR_P_GENEVT2_INTR_SHIFT (2UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIPR_P_GENEVT1_INTR_MASK (0x2UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIPR_P_GENEVT1_INTR_SHIFT (1UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIPR_P_GENEVT0_INTR_MASK (0x1UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIPR_P_GENEVT0_INTR_SHIFT (0UL)




typedef uint32_t ACQCMN_INTR_ACQ_NSU_EVT_INTR_EISR_TYPE;
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EISR_CAPEVT7_INTR_W2CLR_MASK (0x8000UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EISR_CAPEVT7_INTR_W2CLR_SHIFT (15UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EISR_CAPEVT6_INTR_W2CLR_MASK (0x4000UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EISR_CAPEVT6_INTR_W2CLR_SHIFT (14UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EISR_CAPEVT5_INTR_W2CLR_MASK (0x2000UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EISR_CAPEVT5_INTR_W2CLR_SHIFT (13UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EISR_CAPEVT4_INTR_W2CLR_MASK (0x1000UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EISR_CAPEVT4_INTR_W2CLR_SHIFT (12UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EISR_CAPEVT3_INTR_W2CLR_MASK (0x800UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EISR_CAPEVT3_INTR_W2CLR_SHIFT (11UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EISR_CAPEVT2_INTR_W2CLR_MASK (0x400UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EISR_CAPEVT2_INTR_W2CLR_SHIFT (10UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EISR_CAPEVT1_INTR_W2CLR_MASK (0x200UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EISR_CAPEVT1_INTR_W2CLR_SHIFT (9UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EISR_CAPEVT0_INTR_W2CLR_MASK (0x100UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EISR_CAPEVT0_INTR_W2CLR_SHIFT (8UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EISR_GENEVT7_INTR_W2CLR_MASK (0x80UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EISR_GENEVT7_INTR_W2CLR_SHIFT (7UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EISR_GENEVT6_INTR_W2CLR_MASK (0x40UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EISR_GENEVT6_INTR_W2CLR_SHIFT (6UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EISR_GENEVT5_INTR_W2CLR_MASK (0x20UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EISR_GENEVT5_INTR_W2CLR_SHIFT (5UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EISR_GENEVT4_INTR_W2CLR_MASK (0x10UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EISR_GENEVT4_INTR_W2CLR_SHIFT (4UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EISR_GENEVT3_INTR_W2CLR_MASK (0x8UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EISR_GENEVT3_INTR_W2CLR_SHIFT (3UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EISR_GENEVT2_INTR_W2CLR_MASK (0x4UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EISR_GENEVT2_INTR_W2CLR_SHIFT (2UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EISR_GENEVT1_INTR_W2CLR_MASK (0x2UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EISR_GENEVT1_INTR_W2CLR_SHIFT (1UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EISR_GENEVT0_INTR_W2CLR_MASK (0x1UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EISR_GENEVT0_INTR_W2CLR_SHIFT (0UL)




typedef uint32_t ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIER_TYPE;
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIER_ENABLE_CAPEVT7_INTR_MASK (0x8000UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIER_ENABLE_CAPEVT7_INTR_SHIFT (15UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIER_ENABLE_CAPEVT6_INTR_MASK (0x4000UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIER_ENABLE_CAPEVT6_INTR_SHIFT (14UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIER_ENABLE_CAPEVT5_INTR_MASK (0x2000UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIER_ENABLE_CAPEVT5_INTR_SHIFT (13UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIER_ENABLE_CAPEVT4_INTR_MASK (0x1000UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIER_ENABLE_CAPEVT4_INTR_SHIFT (12UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIER_ENABLE_CAPEVT3_INTR_MASK (0x800UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIER_ENABLE_CAPEVT3_INTR_SHIFT (11UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIER_ENABLE_CAPEVT2_INTR_MASK (0x400UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIER_ENABLE_CAPEVT2_INTR_SHIFT (10UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIER_ENABLE_CAPEVT1_INTR_MASK (0x200UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIER_ENABLE_CAPEVT1_INTR_SHIFT (9UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIER_ENABLE_CAPEVT0_INTR_MASK (0x100UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIER_ENABLE_CAPEVT0_INTR_SHIFT (8UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIER_ENABLE_GENEVT7_INTR_MASK (0x80UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIER_ENABLE_GENEVT7_INTR_SHIFT (7UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIER_ENABLE_GENEVT6_INTR_MASK (0x40UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIER_ENABLE_GENEVT6_INTR_SHIFT (6UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIER_ENABLE_GENEVT5_INTR_MASK (0x20UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIER_ENABLE_GENEVT5_INTR_SHIFT (5UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIER_ENABLE_GENEVT4_INTR_MASK (0x10UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIER_ENABLE_GENEVT4_INTR_SHIFT (4UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIER_ENABLE_GENEVT3_INTR_MASK (0x8UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIER_ENABLE_GENEVT3_INTR_SHIFT (3UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIER_ENABLE_GENEVT2_INTR_MASK (0x4UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIER_ENABLE_GENEVT2_INTR_SHIFT (2UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIER_ENABLE_GENEVT1_INTR_MASK (0x2UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIER_ENABLE_GENEVT1_INTR_SHIFT (1UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIER_ENABLE_GENEVT0_INTR_MASK (0x1UL)
#define ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIER_ENABLE_GENEVT0_INTR_SHIFT (0UL)




typedef uint32_t ACQCMN_INTR_ANS0IE_TYPE;
#define ACQCMN_INTR_ANS0IE_P_ACQ_SYSTICK0_MASK (0x1UL)
#define ACQCMN_INTR_ANS0IE_P_ACQ_SYSTICK0_SHIFT (0UL)




typedef uint32_t ACQCMN_INTR_ANS0IE1_TYPE;
#define ACQCMN_INTR_ANS0IE1_ACQ_SYSTICK0_W2CLR_MASK (0x1UL)
#define ACQCMN_INTR_ANS0IE1_ACQ_SYSTICK0_W2CLR_SHIFT (0UL)




typedef uint32_t ACQCMN_INTR_ANS0IE2_TYPE;
#define ACQCMN_INTR_ANS0IE2_ENABLE_ACQ_SYSTICK0_MASK (0x1UL)
#define ACQCMN_INTR_ANS0IE2_ENABLE_ACQ_SYSTICK0_SHIFT (0UL)




typedef uint32_t ACQCMN_INTR_ANS1IE_TYPE;
#define ACQCMN_INTR_ANS1IE_P_ACQ_SYSTICK1_MASK (0x1UL)
#define ACQCMN_INTR_ANS1IE_P_ACQ_SYSTICK1_SHIFT (0UL)




typedef uint32_t ACQCMN_INTR_ANS1IE1_TYPE;
#define ACQCMN_INTR_ANS1IE1_ACQ_SYSTICK1_W2CLR_MASK (0x1UL)
#define ACQCMN_INTR_ANS1IE1_ACQ_SYSTICK1_W2CLR_SHIFT (0UL)




typedef uint32_t ACQCMN_INTR_ANS1IE2_TYPE;
#define ACQCMN_INTR_ANS1IE2_ENABLE_ACQ_SYSTICK1_MASK (0x1UL)
#define ACQCMN_INTR_ANS1IE2_ENABLE_ACQ_SYSTICK1_SHIFT (0UL)




typedef uint32_t ACQCMN_INTR_ANS2IE_TYPE;
#define ACQCMN_INTR_ANS2IE_P_ACQ_SYSTICK2_MASK (0x1UL)
#define ACQCMN_INTR_ANS2IE_P_ACQ_SYSTICK2_SHIFT (0UL)




typedef uint32_t ACQCMN_INTR_ANS2IE1_TYPE;
#define ACQCMN_INTR_ANS2IE1_ACQ_SYSTICK2_W2CLR_MASK (0x1UL)
#define ACQCMN_INTR_ANS2IE1_ACQ_SYSTICK2_W2CLR_SHIFT (0UL)




typedef uint32_t ACQCMN_INTR_ANS2IE2_TYPE;
#define ACQCMN_INTR_ANS2IE2_ENABLE_ACQ_SYSTICK2_MASK (0x1UL)
#define ACQCMN_INTR_ANS2IE2_ENABLE_ACQ_SYSTICK2_SHIFT (0UL)




typedef uint32_t ACQCMN_INTR_ANS3IE_TYPE;
#define ACQCMN_INTR_ANS3IE_P_ACQ_SYSTICK3_MASK (0x1UL)
#define ACQCMN_INTR_ANS3IE_P_ACQ_SYSTICK3_SHIFT (0UL)




typedef uint32_t ACQCMN_INTR_ANS3IE1_TYPE;
#define ACQCMN_INTR_ANS3IE1_ACQ_SYSTICK3_W2CLR_MASK (0x1UL)
#define ACQCMN_INTR_ANS3IE1_ACQ_SYSTICK3_W2CLR_SHIFT (0UL)




typedef uint32_t ACQCMN_INTR_ANS3IE2_TYPE;
#define ACQCMN_INTR_ANS3IE2_ENABLE_ACQ_SYSTICK3_MASK (0x1UL)
#define ACQCMN_INTR_ANS3IE2_ENABLE_ACQ_SYSTICK3_SHIFT (0UL)




typedef uint8_t ACQCMN_INTR_RESERVED_TYPE;




typedef uint32_t ACQCMN_INTR_SPARE_END_REG_TYPE;
#define ACQCMN_INTR_SPARE_END_REG_MASK (0xffffffffUL)
#define ACQCMN_INTR_SPARE_END_REG_SHIFT (0UL)


typedef volatile struct sACQCMN_INTR_ACQ_NSU_SYSTICK_INTR_TYPE {
    ACQCMN_INTR_ANS0IE_TYPE acq_nsu_systick0_intr_eipr; /* OFFSET: 0xc */
    ACQCMN_INTR_ANS0IE1_TYPE acq_nsu_systick0_intr_eisr; /* OFFSET: 0x10 */
    ACQCMN_INTR_ANS0IE2_TYPE acq_nsu_systick0_intr_eier; /* OFFSET: 0x14 */
} ACQCMN_INTR_ACQ_NSU_SYSTICK_INTR_TYPE;


#define ACQCMN_INTR_SYSTICK_SIZE  (4UL)


typedef volatile struct sACQCMN_INTR_RDBType {
    ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIPR_TYPE acq_nsu_evt_intr_eipr; /* OFFSET: 0x0 */
    ACQCMN_INTR_ACQ_NSU_EVT_INTR_EISR_TYPE acq_nsu_evt_intr_eisr; /* OFFSET: 0x4 */
    ACQCMN_INTR_ACQ_NSU_EVT_INTR_EIER_TYPE acq_nsu_evt_intr_eier; /* OFFSET: 0x8 */
    ACQCMN_INTR_ACQ_NSU_SYSTICK_INTR_TYPE systick[ACQCMN_INTR_SYSTICK_SIZE]; /* OFFSET: 0xc */
    ACQCMN_INTR_RESERVED_TYPE rsvd0[192]; /* OFFSET: 0x3c */
    ACQCMN_INTR_SPARE_END_REG_TYPE spare_end_reg; /* OFFSET: 0xfc */
} ACQCMN_INTR_RDBType;


#define ACQ_COMMON_INTR_BASE            (0xE0600F00UL)

#define ACQCMN_INTR_ACQ_NSU_SYSTICK_INTR_TYPE_OFFSET  (0xE0600f0cUL)



#define ACQCMN_INTR_MAX_HW_ID           (1UL)

#endif /* ACQCMN_INTR_RDB_H */
