/*****************************************************************************
 Copyright 2025 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file acqcmn_rdb.h
    @brief RDB File for ACQCMN

    @version BCM89580_A0_20230125_RDB
*/

#ifndef ACQCMN_RDB_H
#define ACQCMN_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t ACQCMN_GLOBAL_RST_EN_TYPE;
#define ACQCMN_GLOBAL_RST_EN_MASK (0x1UL)
#define ACQCMN_GLOBAL_RST_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_LOCAL_RST_EN_TYPE;
#define ACQCMN_LOCAL_RST_EN_MASK (0x3fffffUL)
#define ACQCMN_LOCAL_RST_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_CLK_ENB_TYPE;
#define ACQCMN_CLK_ENB_MASK (0x1fffUL)
#define ACQCMN_CLK_ENB_SHIFT (0UL)




typedef uint8_t ACQCMN_RESERVED_TYPE;




typedef uint32_t ACQCMN_AXIS_CMN_CTRL_TYPE;
#define ACQCMN_AXIS_CMN_CTRL_NSU_BIN_CNTR_RES_MASK (0x1UL)
#define ACQCMN_AXIS_CMN_CTRL_NSU_BIN_CNTR_RES_SHIFT (0UL)




typedef uint32_t ACQCMN_AXIS_CTRL0_TYPE;
#define ACQCMN_AXIS_CTRL0_AWG_MUX_MASK (0x30000UL)
#define ACQCMN_AXIS_CTRL0_AWG_MUX_SHIFT (16UL)
#define ACQCMN_AXIS_CTRL0_DEGLITCH_EN_GPIO_B_MASK (0x4000UL)
#define ACQCMN_AXIS_CTRL0_DEGLITCH_EN_GPIO_B_SHIFT (14UL)
#define ACQCMN_AXIS_CTRL0_DEGLITCH_EN_GPIO_A_MASK (0x2000UL)
#define ACQCMN_AXIS_CTRL0_DEGLITCH_EN_GPIO_A_SHIFT (13UL)
#define ACQCMN_AXIS_CTRL0_DEGLITCH_EN_GPIO_Z_MASK (0x1000UL)
#define ACQCMN_AXIS_CTRL0_DEGLITCH_EN_GPIO_Z_SHIFT (12UL)
#define ACQCMN_AXIS_CTRL0_DEGLITCH_WIDTH_MASK (0x1ffUL)
#define ACQCMN_AXIS_CTRL0_DEGLITCH_WIDTH_SHIFT (0UL)




typedef uint32_t ACQCMN_AXIS_CTRL1_TYPE;
#define ACQCMN_AXIS_CTRL1_EDGE_SEL_MASK (0x3000000UL)
#define ACQCMN_AXIS_CTRL1_EDGE_SEL_SHIFT (24UL)
#define ACQCMN_AXIS_CTRL1_SENSOR_SEL_MASK (0x700000UL)
#define ACQCMN_AXIS_CTRL1_SENSOR_SEL_SHIFT (20UL)
#define ACQCMN_AXIS_CTRL1_PRESCALER_EN_MASK (0x10000UL)
#define ACQCMN_AXIS_CTRL1_PRESCALER_EN_SHIFT (16UL)
#define ACQCMN_AXIS_CTRL1_PRESCALER_VAL_MASK (0xffffUL)
#define ACQCMN_AXIS_CTRL1_PRESCALER_VAL_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR0_EVENT0_SRC_CTRL_TYPE;
#define ACQCMN_TMR0_EVENT0_SRC_CTRL_NSU_TRG0_MASK (0xfUL)
#define ACQCMN_TMR0_EVENT0_SRC_CTRL_NSU_TRG0_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR0_EVENT0_SRC_SEL_TYPE;
#define ACQCMN_TMR0_EVENT0_SRC_SEL_NSU_TRG0_EN_MASK (0x1UL)
#define ACQCMN_TMR0_EVENT0_SRC_SEL_NSU_TRG0_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR0_EVENT1_SRC_CTRL_TYPE;
#define ACQCMN_TMR0_EVENT1_SRC_CTRL_NSU_TRG1_MASK (0xfUL)
#define ACQCMN_TMR0_EVENT1_SRC_CTRL_NSU_TRG1_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR0_EVENT1_SRC_SEL_TYPE;
#define ACQCMN_TMR0_EVENT1_SRC_SEL_NSU_TRG1_EN_MASK (0x1UL)
#define ACQCMN_TMR0_EVENT1_SRC_SEL_NSU_TRG1_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR0_EVENT2_SRC_CTRL_TYPE;
#define ACQCMN_TMR0_EVENT2_SRC_CTRL_ACQ_TRG_MASK (0xfUL)
#define ACQCMN_TMR0_EVENT2_SRC_CTRL_ACQ_TRG_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR0_EVENT2_SRC_SEL_TYPE;
#define ACQCMN_TMR0_EVENT2_SRC_SEL_ACQ_TRG_EN_MASK (0x1UL)
#define ACQCMN_TMR0_EVENT2_SRC_SEL_ACQ_TRG_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR0_EVENT3_SRC_CTRL_TYPE;
#define ACQCMN_TMR0_EVENT3_SRC_CTRL_EVENT_GPIO_MASK (0xfUL)
#define ACQCMN_TMR0_EVENT3_SRC_CTRL_EVENT_GPIO_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR0_EVENT3_SRC_SEL_TYPE;
#define ACQCMN_TMR0_EVENT3_SRC_SEL_EVENT_GPIO_EN_MASK (0x1UL)
#define ACQCMN_TMR0_EVENT3_SRC_SEL_EVENT_GPIO_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR0_ETR_SRC_CTRL_TYPE;
#define ACQCMN_TMR0_ETR_SRC_CTRL_GPIO_MASK (0xfUL)
#define ACQCMN_TMR0_ETR_SRC_CTRL_GPIO_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR0_ETR_SRC_SEL_TYPE;
#define ACQCMN_TMR0_ETR_SRC_SEL_GPIO_EN_MASK (0x1UL)
#define ACQCMN_TMR0_ETR_SRC_SEL_GPIO_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR0_EN_SRC_CTRL_TYPE;
#define ACQCMN_TMR0_EN_SRC_CTRL_IN1_GPIO_MASK (0xfUL)
#define ACQCMN_TMR0_EN_SRC_CTRL_IN1_GPIO_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR0_EN_SRC_SEL_TYPE;
#define ACQCMN_TMR0_EN_SRC_SEL_IN1_GPIO_MASK (0x1UL)
#define ACQCMN_TMR0_EN_SRC_SEL_IN1_GPIO_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR0_IN0_SRC_CTRL_TYPE;
#define ACQCMN_TMR0_IN0_SRC_CTRL_GPIO_MASK (0xfUL)
#define ACQCMN_TMR0_IN0_SRC_CTRL_GPIO_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR0_IN0_SRC_SEL_TYPE;
#define ACQCMN_TMR0_IN0_SRC_SEL_GPIO_EN_MASK (0x1UL)
#define ACQCMN_TMR0_IN0_SRC_SEL_GPIO_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR0_IN1_SRC_CTRL_TYPE;
#define ACQCMN_TMR0_IN1_SRC_CTRL_GPIO_MASK (0xfUL)
#define ACQCMN_TMR0_IN1_SRC_CTRL_GPIO_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR0_IN1_SRC_SEL_TYPE;
#define ACQCMN_TMR0_IN1_SRC_SEL_GPIO_EN_MASK (0x1UL)
#define ACQCMN_TMR0_IN1_SRC_SEL_GPIO_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR0_IN2_SRC_CTRL_TYPE;
#define ACQCMN_TMR0_IN2_SRC_CTRL_GPIO_MASK (0xfUL)
#define ACQCMN_TMR0_IN2_SRC_CTRL_GPIO_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR0_IN2_SRC_SEL_TYPE;
#define ACQCMN_TMR0_IN2_SRC_SEL_GPIO_EN_MASK (0x1UL)
#define ACQCMN_TMR0_IN2_SRC_SEL_GPIO_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR0_IN3_SRC_CTRL_TYPE;
#define ACQCMN_TMR0_IN3_SRC_CTRL_GPIO_MASK (0xfUL)
#define ACQCMN_TMR0_IN3_SRC_CTRL_GPIO_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR0_IN3_SRC_SEL_TYPE;
#define ACQCMN_TMR0_IN3_SRC_SEL_GPIO_EN_MASK (0x1UL)
#define ACQCMN_TMR0_IN3_SRC_SEL_GPIO_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR1_EVENT0_SRC_CTRL_TYPE;
#define ACQCMN_TMR1_EVENT0_SRC_CTRL_NSU_TRG2_MASK (0xfUL)
#define ACQCMN_TMR1_EVENT0_SRC_CTRL_NSU_TRG2_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR1_EVENT0_SRC_SEL_TYPE;
#define ACQCMN_TMR1_EVENT0_SRC_SEL_NSU_TRG2_EN_MASK (0x1UL)
#define ACQCMN_TMR1_EVENT0_SRC_SEL_NSU_TRG2_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR1_EVENT1_SRC_CTRL_TYPE;
#define ACQCMN_TMR1_EVENT1_SRC_CTRL_NSU_TRG3_MASK (0xfUL)
#define ACQCMN_TMR1_EVENT1_SRC_CTRL_NSU_TRG3_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR1_EVENT1_SRC_SEL_TYPE;
#define ACQCMN_TMR1_EVENT1_SRC_SEL_NSU_TRG3_EN_MASK (0x1UL)
#define ACQCMN_TMR1_EVENT1_SRC_SEL_NSU_TRG3_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR1_EVENT2_SRC_CTRL_TYPE;
#define ACQCMN_TMR1_EVENT2_SRC_CTRL_ACQ_TRG_MASK (0xfUL)
#define ACQCMN_TMR1_EVENT2_SRC_CTRL_ACQ_TRG_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR1_EVENT2_SRC_SEL_TYPE;
#define ACQCMN_TMR1_EVENT2_SRC_SEL_ACQ_TRG_EN_MASK (0x1UL)
#define ACQCMN_TMR1_EVENT2_SRC_SEL_ACQ_TRG_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR1_EVENT3_SRC_CTRL_TYPE;
#define ACQCMN_TMR1_EVENT3_SRC_CTRL_EVENT_GPIO_MASK (0xfUL)
#define ACQCMN_TMR1_EVENT3_SRC_CTRL_EVENT_GPIO_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR1_EVENT3_SRC_SEL_TYPE;
#define ACQCMN_TMR1_EVENT3_SRC_SEL_EVENT_GPIO_EN_MASK (0x1UL)
#define ACQCMN_TMR1_EVENT3_SRC_SEL_EVENT_GPIO_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR1_ETR_SRC_CTRL_TYPE;
#define ACQCMN_TMR1_ETR_SRC_CTRL_GPIO_MASK (0xfUL)
#define ACQCMN_TMR1_ETR_SRC_CTRL_GPIO_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR1_ETR_SRC_SEL_TYPE;
#define ACQCMN_TMR1_ETR_SRC_SEL_GPIO_EN_MASK (0x1UL)
#define ACQCMN_TMR1_ETR_SRC_SEL_GPIO_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR1_EN_SRC_CTRL_TYPE;
#define ACQCMN_TMR1_EN_SRC_CTRL_IN1_GPIO_MASK (0xfUL)
#define ACQCMN_TMR1_EN_SRC_CTRL_IN1_GPIO_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR1_EN_SRC_SEL_TYPE;
#define ACQCMN_TMR1_EN_SRC_SEL_IN1_GPIO_MASK (0x1UL)
#define ACQCMN_TMR1_EN_SRC_SEL_IN1_GPIO_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR1_IN0_SRC_CTRL_TYPE;
#define ACQCMN_TMR1_IN0_SRC_CTRL_GPIO_MASK (0xfUL)
#define ACQCMN_TMR1_IN0_SRC_CTRL_GPIO_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR1_IN0_SRC_SEL_TYPE;
#define ACQCMN_TMR1_IN0_SRC_SEL_GPIO_EN_MASK (0x1UL)
#define ACQCMN_TMR1_IN0_SRC_SEL_GPIO_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR1_IN1_SRC_CTRL_TYPE;
#define ACQCMN_TMR1_IN1_SRC_CTRL_GPIO_MASK (0xfUL)
#define ACQCMN_TMR1_IN1_SRC_CTRL_GPIO_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR1_IN1_SRC_SEL_TYPE;
#define ACQCMN_TMR1_IN1_SRC_SEL_GPIO_EN_MASK (0x1UL)
#define ACQCMN_TMR1_IN1_SRC_SEL_GPIO_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR1_IN2_SRC_CTRL_TYPE;
#define ACQCMN_TMR1_IN2_SRC_CTRL_GPIO_MASK (0xfUL)
#define ACQCMN_TMR1_IN2_SRC_CTRL_GPIO_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR1_IN2_SRC_SEL_TYPE;
#define ACQCMN_TMR1_IN2_SRC_SEL_GPIO_EN_MASK (0x1UL)
#define ACQCMN_TMR1_IN2_SRC_SEL_GPIO_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR1_IN3_SRC_CTRL_TYPE;
#define ACQCMN_TMR1_IN3_SRC_CTRL_GPIO_MASK (0xfUL)
#define ACQCMN_TMR1_IN3_SRC_CTRL_GPIO_SHIFT (0UL)




typedef uint32_t ACQCMN_TMR1_IN3_SRC_SEL_TYPE;
#define ACQCMN_TMR1_IN3_SRC_SEL_GPIO_EN_MASK (0x1UL)
#define ACQCMN_TMR1_IN3_SRC_SEL_GPIO_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_CAPCOM_CMN_SRC_CTRL_TYPE;
#define ACQCMN_CAPCOM_CMN_SRC_CTRL_TMR1_COUT3_MASK (0xf0000000UL)
#define ACQCMN_CAPCOM_CMN_SRC_CTRL_TMR1_COUT3_SHIFT (28UL)
#define ACQCMN_CAPCOM_CMN_SRC_CTRL_TMR1_COUT2_MASK (0xf000000UL)
#define ACQCMN_CAPCOM_CMN_SRC_CTRL_TMR1_COUT2_SHIFT (24UL)
#define ACQCMN_CAPCOM_CMN_SRC_CTRL_TMR1_COUT1_MASK (0xf00000UL)
#define ACQCMN_CAPCOM_CMN_SRC_CTRL_TMR1_COUT1_SHIFT (20UL)
#define ACQCMN_CAPCOM_CMN_SRC_CTRL_TMR1_COUT0_MASK (0xf0000UL)
#define ACQCMN_CAPCOM_CMN_SRC_CTRL_TMR1_COUT0_SHIFT (16UL)
#define ACQCMN_CAPCOM_CMN_SRC_CTRL_TMR0_COUT3_MASK (0xf000UL)
#define ACQCMN_CAPCOM_CMN_SRC_CTRL_TMR0_COUT3_SHIFT (12UL)
#define ACQCMN_CAPCOM_CMN_SRC_CTRL_TMR0_COUT2_MASK (0xf00UL)
#define ACQCMN_CAPCOM_CMN_SRC_CTRL_TMR0_COUT2_SHIFT (8UL)
#define ACQCMN_CAPCOM_CMN_SRC_CTRL_TMR0_COUT1_MASK (0xf0UL)
#define ACQCMN_CAPCOM_CMN_SRC_CTRL_TMR0_COUT1_SHIFT (4UL)
#define ACQCMN_CAPCOM_CMN_SRC_CTRL_TMR0_COUT0_MASK (0xfUL)
#define ACQCMN_CAPCOM_CMN_SRC_CTRL_TMR0_COUT0_SHIFT (0UL)




typedef uint32_t ACQCMN_AWG_CMN_SRC_CTRL_TYPE;
#define ACQCMN_AWG_CMN_SRC_CTRL_3_SYNC1_MASK (0xf0000000UL)
#define ACQCMN_AWG_CMN_SRC_CTRL_3_SYNC1_SHIFT (28UL)
#define ACQCMN_AWG_CMN_SRC_CTRL_3_SYNC0_MASK (0xf000000UL)
#define ACQCMN_AWG_CMN_SRC_CTRL_3_SYNC0_SHIFT (24UL)
#define ACQCMN_AWG_CMN_SRC_CTRL_2_SYNC1_MASK (0xf00000UL)
#define ACQCMN_AWG_CMN_SRC_CTRL_2_SYNC1_SHIFT (20UL)
#define ACQCMN_AWG_CMN_SRC_CTRL_2_SYNC0_MASK (0xf0000UL)
#define ACQCMN_AWG_CMN_SRC_CTRL_2_SYNC0_SHIFT (16UL)
#define ACQCMN_AWG_CMN_SRC_CTRL_1_SYNC1_MASK (0xf000UL)
#define ACQCMN_AWG_CMN_SRC_CTRL_1_SYNC1_SHIFT (12UL)
#define ACQCMN_AWG_CMN_SRC_CTRL_1_SYNC0_MASK (0xf00UL)
#define ACQCMN_AWG_CMN_SRC_CTRL_1_SYNC0_SHIFT (8UL)
#define ACQCMN_AWG_CMN_SRC_CTRL_0_SYNC1_MASK (0xf0UL)
#define ACQCMN_AWG_CMN_SRC_CTRL_0_SYNC1_SHIFT (4UL)
#define ACQCMN_AWG_CMN_SRC_CTRL_0_SYNC0_MASK (0xfUL)
#define ACQCMN_AWG_CMN_SRC_CTRL_0_SYNC0_SHIFT (0UL)




typedef uint32_t ACQCMN_AWG_START_SRC_CTRL_TYPE;
#define ACQCMN_AWG_START_SRC_CTRL_AWG_START_GPIO_MASK (0xf00000UL)
#define ACQCMN_AWG_START_SRC_CTRL_AWG_START_GPIO_SHIFT (20UL)
#define ACQCMN_AWG_START_SRC_CTRL_RESERVED_16_MASK (0xf0000UL)
#define ACQCMN_AWG_START_SRC_CTRL_RESERVED_16_SHIFT (16UL)
#define ACQCMN_AWG_START_SRC_CTRL_NSU_TRG3_MASK (0xf000UL)
#define ACQCMN_AWG_START_SRC_CTRL_NSU_TRG3_SHIFT (12UL)
#define ACQCMN_AWG_START_SRC_CTRL_NSU_TRG2_MASK (0xf00UL)
#define ACQCMN_AWG_START_SRC_CTRL_NSU_TRG2_SHIFT (8UL)
#define ACQCMN_AWG_START_SRC_CTRL_NSU_TRG1_MASK (0xf0UL)
#define ACQCMN_AWG_START_SRC_CTRL_NSU_TRG1_SHIFT (4UL)
#define ACQCMN_AWG_START_SRC_CTRL_NSU_TRG0_MASK (0xfUL)
#define ACQCMN_AWG_START_SRC_CTRL_NSU_TRG0_SHIFT (0UL)




typedef uint32_t ACQCMN_AWG_START_SRC_SEL_TYPE;
#define ACQCMN_AWG_START_SRC_SEL_AWG_START_GPIO_EN_MASK (0x200000UL)
#define ACQCMN_AWG_START_SRC_SEL_AWG_START_GPIO_EN_SHIFT (21UL)
#define ACQCMN_AWG_START_SRC_SEL_RESERVED_20_MASK (0x100000UL)
#define ACQCMN_AWG_START_SRC_SEL_RESERVED_20_SHIFT (20UL)
#define ACQCMN_AWG_START_SRC_SEL_NSU_TRG3_EN_MASK (0x80000UL)
#define ACQCMN_AWG_START_SRC_SEL_NSU_TRG3_EN_SHIFT (19UL)
#define ACQCMN_AWG_START_SRC_SEL_NSU_TRG2_EN_MASK (0x40000UL)
#define ACQCMN_AWG_START_SRC_SEL_NSU_TRG2_EN_SHIFT (18UL)
#define ACQCMN_AWG_START_SRC_SEL_NSU_TRG1_EN_MASK (0x20000UL)
#define ACQCMN_AWG_START_SRC_SEL_NSU_TRG1_EN_SHIFT (17UL)
#define ACQCMN_AWG_START_SRC_SEL_NSU_TRG0_EN_MASK (0x10000UL)
#define ACQCMN_AWG_START_SRC_SEL_NSU_TRG0_EN_SHIFT (16UL)
#define ACQCMN_AWG_START_SRC_SEL_AWG3_SYNC1_EN_MASK (0x8000UL)
#define ACQCMN_AWG_START_SRC_SEL_AWG3_SYNC1_EN_SHIFT (15UL)
#define ACQCMN_AWG_START_SRC_SEL_AWG3_SYNC0_EN_MASK (0x4000UL)
#define ACQCMN_AWG_START_SRC_SEL_AWG3_SYNC0_EN_SHIFT (14UL)
#define ACQCMN_AWG_START_SRC_SEL_AWG2_SYNC1_EN_MASK (0x2000UL)
#define ACQCMN_AWG_START_SRC_SEL_AWG2_SYNC1_EN_SHIFT (13UL)
#define ACQCMN_AWG_START_SRC_SEL_AWG2_SYNC0_EN_MASK (0x1000UL)
#define ACQCMN_AWG_START_SRC_SEL_AWG2_SYNC0_EN_SHIFT (12UL)
#define ACQCMN_AWG_START_SRC_SEL_AWG1_SYNC1_EN_MASK (0x800UL)
#define ACQCMN_AWG_START_SRC_SEL_AWG1_SYNC1_EN_SHIFT (11UL)
#define ACQCMN_AWG_START_SRC_SEL_AWG1_SYNC0_EN_MASK (0x400UL)
#define ACQCMN_AWG_START_SRC_SEL_AWG1_SYNC0_EN_SHIFT (10UL)
#define ACQCMN_AWG_START_SRC_SEL_AWG0_SYNC1_EN_MASK (0x200UL)
#define ACQCMN_AWG_START_SRC_SEL_AWG0_SYNC1_EN_SHIFT (9UL)
#define ACQCMN_AWG_START_SRC_SEL_AWG0_SYNC0_EN_MASK (0x100UL)
#define ACQCMN_AWG_START_SRC_SEL_AWG0_SYNC0_EN_SHIFT (8UL)
#define ACQCMN_AWG_START_SRC_SEL_TMR1_COUT3_EN_MASK (0x80UL)
#define ACQCMN_AWG_START_SRC_SEL_TMR1_COUT3_EN_SHIFT (7UL)
#define ACQCMN_AWG_START_SRC_SEL_TMR1_COUT2_EN_MASK (0x40UL)
#define ACQCMN_AWG_START_SRC_SEL_TMR1_COUT2_EN_SHIFT (6UL)
#define ACQCMN_AWG_START_SRC_SEL_TMR1_COUT1_EN_MASK (0x20UL)
#define ACQCMN_AWG_START_SRC_SEL_TMR1_COUT1_EN_SHIFT (5UL)
#define ACQCMN_AWG_START_SRC_SEL_TMR1_COUT0_EN_MASK (0x10UL)
#define ACQCMN_AWG_START_SRC_SEL_TMR1_COUT0_EN_SHIFT (4UL)
#define ACQCMN_AWG_START_SRC_SEL_TMR0_COUT3_EN_MASK (0x8UL)
#define ACQCMN_AWG_START_SRC_SEL_TMR0_COUT3_EN_SHIFT (3UL)
#define ACQCMN_AWG_START_SRC_SEL_TMR0_COUT2_EN_MASK (0x4UL)
#define ACQCMN_AWG_START_SRC_SEL_TMR0_COUT2_EN_SHIFT (2UL)
#define ACQCMN_AWG_START_SRC_SEL_TMR0_COUT1_EN_MASK (0x2UL)
#define ACQCMN_AWG_START_SRC_SEL_TMR0_COUT1_EN_SHIFT (1UL)
#define ACQCMN_AWG_START_SRC_SEL_TMR0_COUT0_EN_MASK (0x1UL)
#define ACQCMN_AWG_START_SRC_SEL_TMR0_COUT0_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_AWG_INCR_SRC_CTRL_TYPE;
#define ACQCMN_AWG_INCR_SRC_CTRL_AWG_INCR_GPIO_MASK (0xf0UL)
#define ACQCMN_AWG_INCR_SRC_CTRL_AWG_INCR_GPIO_SHIFT (4UL)
#define ACQCMN_AWG_INCR_SRC_CTRL_RESERVED_0_MASK (0xfUL)
#define ACQCMN_AWG_INCR_SRC_CTRL_RESERVED_0_SHIFT (0UL)




typedef uint32_t ACQCMN_AWG_INCR_SRC_SEL_TYPE;
#define ACQCMN_AWG_INCR_SRC_SEL_AWG_INCR_GPIO_EN_MASK (0x20000UL)
#define ACQCMN_AWG_INCR_SRC_SEL_AWG_INCR_GPIO_EN_SHIFT (17UL)
#define ACQCMN_AWG_INCR_SRC_SEL_RESERVED_16_MASK (0x10000UL)
#define ACQCMN_AWG_INCR_SRC_SEL_RESERVED_16_SHIFT (16UL)
#define ACQCMN_AWG_INCR_SRC_SEL_AWG3_SYNC1_EN_MASK (0x8000UL)
#define ACQCMN_AWG_INCR_SRC_SEL_AWG3_SYNC1_EN_SHIFT (15UL)
#define ACQCMN_AWG_INCR_SRC_SEL_AWG3_SYNC0_EN_MASK (0x4000UL)
#define ACQCMN_AWG_INCR_SRC_SEL_AWG3_SYNC0_EN_SHIFT (14UL)
#define ACQCMN_AWG_INCR_SRC_SEL_AWG2_SYNC1_EN_MASK (0x2000UL)
#define ACQCMN_AWG_INCR_SRC_SEL_AWG2_SYNC1_EN_SHIFT (13UL)
#define ACQCMN_AWG_INCR_SRC_SEL_AWG2_SYNC0_EN_MASK (0x1000UL)
#define ACQCMN_AWG_INCR_SRC_SEL_AWG2_SYNC0_EN_SHIFT (12UL)
#define ACQCMN_AWG_INCR_SRC_SEL_AWG1_SYNC1_EN_MASK (0x800UL)
#define ACQCMN_AWG_INCR_SRC_SEL_AWG1_SYNC1_EN_SHIFT (11UL)
#define ACQCMN_AWG_INCR_SRC_SEL_AWG1_SYNC0_EN_MASK (0x400UL)
#define ACQCMN_AWG_INCR_SRC_SEL_AWG1_SYNC0_EN_SHIFT (10UL)
#define ACQCMN_AWG_INCR_SRC_SEL_AWG0_SYNC1_EN_MASK (0x200UL)
#define ACQCMN_AWG_INCR_SRC_SEL_AWG0_SYNC1_EN_SHIFT (9UL)
#define ACQCMN_AWG_INCR_SRC_SEL_AWG0_SYNC0_EN_MASK (0x100UL)
#define ACQCMN_AWG_INCR_SRC_SEL_AWG0_SYNC0_EN_SHIFT (8UL)
#define ACQCMN_AWG_INCR_SRC_SEL_TMR1_COUT3_EN_MASK (0x80UL)
#define ACQCMN_AWG_INCR_SRC_SEL_TMR1_COUT3_EN_SHIFT (7UL)
#define ACQCMN_AWG_INCR_SRC_SEL_TMR1_COUT2_EN_MASK (0x40UL)
#define ACQCMN_AWG_INCR_SRC_SEL_TMR1_COUT2_EN_SHIFT (6UL)
#define ACQCMN_AWG_INCR_SRC_SEL_TMR1_COUT1_EN_MASK (0x20UL)
#define ACQCMN_AWG_INCR_SRC_SEL_TMR1_COUT1_EN_SHIFT (5UL)
#define ACQCMN_AWG_INCR_SRC_SEL_TMR1_COUT0_EN_MASK (0x10UL)
#define ACQCMN_AWG_INCR_SRC_SEL_TMR1_COUT0_EN_SHIFT (4UL)
#define ACQCMN_AWG_INCR_SRC_SEL_TMR0_COUT3_EN_MASK (0x8UL)
#define ACQCMN_AWG_INCR_SRC_SEL_TMR0_COUT3_EN_SHIFT (3UL)
#define ACQCMN_AWG_INCR_SRC_SEL_TMR0_COUT2_EN_MASK (0x4UL)
#define ACQCMN_AWG_INCR_SRC_SEL_TMR0_COUT2_EN_SHIFT (2UL)
#define ACQCMN_AWG_INCR_SRC_SEL_TMR0_COUT1_EN_MASK (0x2UL)
#define ACQCMN_AWG_INCR_SRC_SEL_TMR0_COUT1_EN_SHIFT (1UL)
#define ACQCMN_AWG_INCR_SRC_SEL_TMR0_COUT0_EN_MASK (0x1UL)
#define ACQCMN_AWG_INCR_SRC_SEL_TMR0_COUT0_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_ACQ_TRG_SRC_CTRL_TYPE;
#define ACQCMN_ACQ_TRG_SRC_CTRL_ANALOG_EXT_INPUT_MASK (0xfUL)
#define ACQCMN_ACQ_TRG_SRC_CTRL_ANALOG_EXT_INPUT_SHIFT (0UL)




typedef uint32_t ACQCMN_ACQ_TRG_SRC_SEL_TYPE;
#define ACQCMN_ACQ_TRG_SRC_SEL_ANALOG_EXT_INPUT_EN_MASK (0x10000UL)
#define ACQCMN_ACQ_TRG_SRC_SEL_ANALOG_EXT_INPUT_EN_SHIFT (16UL)
#define ACQCMN_ACQ_TRG_SRC_SEL_AWG3_SYNC1_EN_MASK (0x8000UL)
#define ACQCMN_ACQ_TRG_SRC_SEL_AWG3_SYNC1_EN_SHIFT (15UL)
#define ACQCMN_ACQ_TRG_SRC_SEL_AWG3_SYNC0_EN_MASK (0x4000UL)
#define ACQCMN_ACQ_TRG_SRC_SEL_AWG3_SYNC0_EN_SHIFT (14UL)
#define ACQCMN_ACQ_TRG_SRC_SEL_AWG2_SYNC1_EN_MASK (0x2000UL)
#define ACQCMN_ACQ_TRG_SRC_SEL_AWG2_SYNC1_EN_SHIFT (13UL)
#define ACQCMN_ACQ_TRG_SRC_SEL_AWG2_SYNC0_EN_MASK (0x1000UL)
#define ACQCMN_ACQ_TRG_SRC_SEL_AWG2_SYNC0_EN_SHIFT (12UL)
#define ACQCMN_ACQ_TRG_SRC_SEL_AWG1_SYNC1_EN_MASK (0x800UL)
#define ACQCMN_ACQ_TRG_SRC_SEL_AWG1_SYNC1_EN_SHIFT (11UL)
#define ACQCMN_ACQ_TRG_SRC_SEL_AWG1_SYNC0_EN_MASK (0x400UL)
#define ACQCMN_ACQ_TRG_SRC_SEL_AWG1_SYNC0_EN_SHIFT (10UL)
#define ACQCMN_ACQ_TRG_SRC_SEL_AWG0_SYNC1_EN_MASK (0x200UL)
#define ACQCMN_ACQ_TRG_SRC_SEL_AWG0_SYNC1_EN_SHIFT (9UL)
#define ACQCMN_ACQ_TRG_SRC_SEL_AWG0_SYNC0_EN_MASK (0x100UL)
#define ACQCMN_ACQ_TRG_SRC_SEL_AWG0_SYNC0_EN_SHIFT (8UL)
#define ACQCMN_ACQ_TRG_SRC_SEL_TMR1_COUT3_EN_MASK (0x80UL)
#define ACQCMN_ACQ_TRG_SRC_SEL_TMR1_COUT3_EN_SHIFT (7UL)
#define ACQCMN_ACQ_TRG_SRC_SEL_TMR1_COUT2_EN_MASK (0x40UL)
#define ACQCMN_ACQ_TRG_SRC_SEL_TMR1_COUT2_EN_SHIFT (6UL)
#define ACQCMN_ACQ_TRG_SRC_SEL_TMR1_COUT1_EN_MASK (0x20UL)
#define ACQCMN_ACQ_TRG_SRC_SEL_TMR1_COUT1_EN_SHIFT (5UL)
#define ACQCMN_ACQ_TRG_SRC_SEL_TMR1_COUT0_EN_MASK (0x10UL)
#define ACQCMN_ACQ_TRG_SRC_SEL_TMR1_COUT0_EN_SHIFT (4UL)
#define ACQCMN_ACQ_TRG_SRC_SEL_TMR0_COUT3_EN_MASK (0x8UL)
#define ACQCMN_ACQ_TRG_SRC_SEL_TMR0_COUT3_EN_SHIFT (3UL)
#define ACQCMN_ACQ_TRG_SRC_SEL_TMR0_COUT2_EN_MASK (0x4UL)
#define ACQCMN_ACQ_TRG_SRC_SEL_TMR0_COUT2_EN_SHIFT (2UL)
#define ACQCMN_ACQ_TRG_SRC_SEL_TMR0_COUT1_EN_MASK (0x2UL)
#define ACQCMN_ACQ_TRG_SRC_SEL_TMR0_COUT1_EN_SHIFT (1UL)
#define ACQCMN_ACQ_TRG_SRC_SEL_TMR0_COUT0_EN_MASK (0x1UL)
#define ACQCMN_ACQ_TRG_SRC_SEL_TMR0_COUT0_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_HKADC_START_SRC_CTRL_TYPE;
#define ACQCMN_HKADC_START_SRC_CTRL_ACQ_TRG_MASK (0xf00000UL)
#define ACQCMN_HKADC_START_SRC_CTRL_ACQ_TRG_SHIFT (20UL)
#define ACQCMN_HKADC_START_SRC_CTRL_RESERVED_16_MASK (0xf0000UL)
#define ACQCMN_HKADC_START_SRC_CTRL_RESERVED_16_SHIFT (16UL)
#define ACQCMN_HKADC_START_SRC_CTRL_HKADC_START3_GPIO_MASK (0xf000UL)
#define ACQCMN_HKADC_START_SRC_CTRL_HKADC_START3_GPIO_SHIFT (12UL)
#define ACQCMN_HKADC_START_SRC_CTRL_HKADC_START2_GPIO_MASK (0xf00UL)
#define ACQCMN_HKADC_START_SRC_CTRL_HKADC_START2_GPIO_SHIFT (8UL)
#define ACQCMN_HKADC_START_SRC_CTRL_HKADC_START1_GPIO_MASK (0xf0UL)
#define ACQCMN_HKADC_START_SRC_CTRL_HKADC_START1_GPIO_SHIFT (4UL)
#define ACQCMN_HKADC_START_SRC_CTRL_HKADC_START0_GPIO_MASK (0xfUL)
#define ACQCMN_HKADC_START_SRC_CTRL_HKADC_START0_GPIO_SHIFT (0UL)




typedef uint32_t ACQCMN_HKADC_START_SRC_SEL_TYPE;
#define ACQCMN_HKADC_START_SRC_SEL_ACQ_TRG_EN_MASK (0x20UL)
#define ACQCMN_HKADC_START_SRC_SEL_ACQ_TRG_EN_SHIFT (5UL)
#define ACQCMN_HKADC_START_SRC_SEL_RESERVED_4_MASK (0x10UL)
#define ACQCMN_HKADC_START_SRC_SEL_RESERVED_4_SHIFT (4UL)
#define ACQCMN_HKADC_START_SRC_SEL_HKADC_START3_GPIO_EN_MASK (0x8UL)
#define ACQCMN_HKADC_START_SRC_SEL_HKADC_START3_GPIO_EN_SHIFT (3UL)
#define ACQCMN_HKADC_START_SRC_SEL_HKADC_START2_GPIO_EN_MASK (0x4UL)
#define ACQCMN_HKADC_START_SRC_SEL_HKADC_START2_GPIO_EN_SHIFT (2UL)
#define ACQCMN_HKADC_START_SRC_SEL_HKADC_START1_GPIO_EN_MASK (0x2UL)
#define ACQCMN_HKADC_START_SRC_SEL_HKADC_START1_GPIO_EN_SHIFT (1UL)
#define ACQCMN_HKADC_START_SRC_SEL_HKADC_START0_GPIO_EN_MASK (0x1UL)
#define ACQCMN_HKADC_START_SRC_SEL_HKADC_START0_GPIO_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_HKDAC_START_SRC_CTRL_TYPE;
#define ACQCMN_HKDAC_START_SRC_CTRL_ACQ_TRG_MASK (0xf0UL)
#define ACQCMN_HKDAC_START_SRC_CTRL_ACQ_TRG_SHIFT (4UL)
#define ACQCMN_HKDAC_START_SRC_CTRL_HKDAC_START_GPIO_MASK (0xfUL)
#define ACQCMN_HKDAC_START_SRC_CTRL_HKDAC_START_GPIO_SHIFT (0UL)




typedef uint32_t ACQCMN_HKDAC_START_SRC_SEL_TYPE;
#define ACQCMN_HKDAC_START_SRC_SEL_ACQ_TRG_EN_MASK (0x2UL)
#define ACQCMN_HKDAC_START_SRC_SEL_ACQ_TRG_EN_SHIFT (1UL)
#define ACQCMN_HKDAC_START_SRC_SEL_HKDAC_START_GPIO_EN_MASK (0x1UL)
#define ACQCMN_HKDAC_START_SRC_SEL_HKDAC_START_GPIO_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_NSU_EVENT0_SRC_CTRL_TYPE;
#define ACQCMN_NSU_EVENT0_SRC_CTRL_GPIO_MASK (0xfUL)
#define ACQCMN_NSU_EVENT0_SRC_CTRL_GPIO_SHIFT (0UL)




typedef uint32_t ACQCMN_NSU_EVENT0_SRC_SEL_TYPE;
#define ACQCMN_NSU_EVENT0_SRC_SEL_GPIO_EN_MASK (0x1UL)
#define ACQCMN_NSU_EVENT0_SRC_SEL_GPIO_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_NSU_EVENT1_SRC_CTRL_TYPE;
#define ACQCMN_NSU_EVENT1_SRC_CTRL_GPIO_MASK (0xfUL)
#define ACQCMN_NSU_EVENT1_SRC_CTRL_GPIO_SHIFT (0UL)




typedef uint32_t ACQCMN_NSU_EVENT1_SRC_SEL_TYPE;
#define ACQCMN_NSU_EVENT1_SRC_SEL_GPIO_EN_MASK (0x1UL)
#define ACQCMN_NSU_EVENT1_SRC_SEL_GPIO_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_NSU_EVENT2_SRC_CTRL_TYPE;
#define ACQCMN_NSU_EVENT2_SRC_CTRL_GPIO_MASK (0xfUL)
#define ACQCMN_NSU_EVENT2_SRC_CTRL_GPIO_SHIFT (0UL)




typedef uint32_t ACQCMN_NSU_EVENT2_SRC_SEL_TYPE;
#define ACQCMN_NSU_EVENT2_SRC_SEL_GPIO_EN_MASK (0x1UL)
#define ACQCMN_NSU_EVENT2_SRC_SEL_GPIO_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_NSU_EVENT3_SRC_CTRL_TYPE;
#define ACQCMN_NSU_EVENT3_SRC_CTRL_GPIO_MASK (0xfUL)
#define ACQCMN_NSU_EVENT3_SRC_CTRL_GPIO_SHIFT (0UL)




typedef uint32_t ACQCMN_NSU_EVENT3_SRC_SEL_TYPE;
#define ACQCMN_NSU_EVENT3_SRC_SEL_GPIO_EN_MASK (0x1UL)
#define ACQCMN_NSU_EVENT3_SRC_SEL_GPIO_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_NSU_EVENT4_SRC_CTRL_TYPE;
#define ACQCMN_NSU_EVENT4_SRC_CTRL_AWG0_EVENT_MASK (0xfUL)
#define ACQCMN_NSU_EVENT4_SRC_CTRL_AWG0_EVENT_SHIFT (0UL)




typedef uint32_t ACQCMN_NSU_EVENT4_SRC_SEL_TYPE;
#define ACQCMN_NSU_EVENT4_SRC_SEL_AWG0_EVENT_EN_MASK (0x1UL)
#define ACQCMN_NSU_EVENT4_SRC_SEL_AWG0_EVENT_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_NSU_EVENT5_SRC_CTRL_TYPE;
#define ACQCMN_NSU_EVENT5_SRC_CTRL_AWG1_EVENT_MASK (0xfUL)
#define ACQCMN_NSU_EVENT5_SRC_CTRL_AWG1_EVENT_SHIFT (0UL)




typedef uint32_t ACQCMN_NSU_EVENT5_SRC_SEL_TYPE;
#define ACQCMN_NSU_EVENT5_SRC_SEL_AWG1_EVENT_EN_MASK (0x1UL)
#define ACQCMN_NSU_EVENT5_SRC_SEL_AWG1_EVENT_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_NSU_EVENT6_SRC_CTRL_TYPE;
#define ACQCMN_NSU_EVENT6_SRC_CTRL_AWG2_EVENT_MASK (0xfUL)
#define ACQCMN_NSU_EVENT6_SRC_CTRL_AWG2_EVENT_SHIFT (0UL)




typedef uint32_t ACQCMN_NSU_EVENT6_SRC_SEL_TYPE;
#define ACQCMN_NSU_EVENT6_SRC_SEL_AWG2_EVENT_EN_MASK (0x1UL)
#define ACQCMN_NSU_EVENT6_SRC_SEL_AWG2_EVENT_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_NSU_EVENT7_SRC_CTRL_TYPE;
#define ACQCMN_NSU_EVENT7_SRC_CTRL_AWG3_EVENT_MASK (0xfUL)
#define ACQCMN_NSU_EVENT7_SRC_CTRL_AWG3_EVENT_SHIFT (0UL)




typedef uint32_t ACQCMN_NSU_EVENT7_SRC_SEL_TYPE;
#define ACQCMN_NSU_EVENT7_SRC_SEL_AWG3_EVENT_EN_MASK (0x1UL)
#define ACQCMN_NSU_EVENT7_SRC_SEL_AWG3_EVENT_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_NSU_CNTR_HW_RST_SRC_CTRL_TYPE;
#define ACQCMN_NSU_CNTR_HW_RST_SRC_CTRL_EVENT3_GPIO_MASK (0xf000UL)
#define ACQCMN_NSU_CNTR_HW_RST_SRC_CTRL_EVENT3_GPIO_SHIFT (12UL)
#define ACQCMN_NSU_CNTR_HW_RST_SRC_CTRL_EVENT2_GPIO_MASK (0xf00UL)
#define ACQCMN_NSU_CNTR_HW_RST_SRC_CTRL_EVENT2_GPIO_SHIFT (8UL)
#define ACQCMN_NSU_CNTR_HW_RST_SRC_CTRL_EVENT1_GPIO_MASK (0xf0UL)
#define ACQCMN_NSU_CNTR_HW_RST_SRC_CTRL_EVENT1_GPIO_SHIFT (4UL)
#define ACQCMN_NSU_CNTR_HW_RST_SRC_CTRL_EVENT0_GPIO_MASK (0xfUL)
#define ACQCMN_NSU_CNTR_HW_RST_SRC_CTRL_EVENT0_GPIO_SHIFT (0UL)




typedef uint32_t ACQCMN_NSU_CNTR_HW_RST_SRC_SEL_TYPE;
#define ACQCMN_NSU_CNTR_HW_RST_SRC_SEL_EVENT3_GPIO_EN_MASK (0x8UL)
#define ACQCMN_NSU_CNTR_HW_RST_SRC_SEL_EVENT3_GPIO_EN_SHIFT (3UL)
#define ACQCMN_NSU_CNTR_HW_RST_SRC_SEL_EVENT2_GPIO_EN_MASK (0x4UL)
#define ACQCMN_NSU_CNTR_HW_RST_SRC_SEL_EVENT2_GPIO_EN_SHIFT (2UL)
#define ACQCMN_NSU_CNTR_HW_RST_SRC_SEL_EVENT1_GPIO_EN_MASK (0x2UL)
#define ACQCMN_NSU_CNTR_HW_RST_SRC_SEL_EVENT1_GPIO_EN_SHIFT (1UL)
#define ACQCMN_NSU_CNTR_HW_RST_SRC_SEL_EVENT0_GPIO_EN_MASK (0x1UL)
#define ACQCMN_NSU_CNTR_HW_RST_SRC_SEL_EVENT0_GPIO_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_SFT_TRG_EN_TMR_TYPE;
#define ACQCMN_SFT_TRG_EN_TMR_1_IN3_EN_MASK (0x2000000UL)
#define ACQCMN_SFT_TRG_EN_TMR_1_IN3_EN_SHIFT (25UL)
#define ACQCMN_SFT_TRG_EN_TMR_1_IN2_EN_MASK (0x1000000UL)
#define ACQCMN_SFT_TRG_EN_TMR_1_IN2_EN_SHIFT (24UL)
#define ACQCMN_SFT_TRG_EN_TMR_1_IN1_EN_MASK (0x800000UL)
#define ACQCMN_SFT_TRG_EN_TMR_1_IN1_EN_SHIFT (23UL)
#define ACQCMN_SFT_TRG_EN_TMR_1_IN0_EN_MASK (0x400000UL)
#define ACQCMN_SFT_TRG_EN_TMR_1_IN0_EN_SHIFT (22UL)
#define ACQCMN_SFT_TRG_EN_TMR_1_EN_EN_MASK (0x200000UL)
#define ACQCMN_SFT_TRG_EN_TMR_1_EN_EN_SHIFT (21UL)
#define ACQCMN_SFT_TRG_EN_TMR_1_ETR_EN_MASK (0x100000UL)
#define ACQCMN_SFT_TRG_EN_TMR_1_ETR_EN_SHIFT (20UL)
#define ACQCMN_SFT_TRG_EN_TMR_1_EVENT3_EN_MASK (0x80000UL)
#define ACQCMN_SFT_TRG_EN_TMR_1_EVENT3_EN_SHIFT (19UL)
#define ACQCMN_SFT_TRG_EN_TMR_1_EVENT2_EN_MASK (0x40000UL)
#define ACQCMN_SFT_TRG_EN_TMR_1_EVENT2_EN_SHIFT (18UL)
#define ACQCMN_SFT_TRG_EN_TMR_1_EVENT1_EN_MASK (0x20000UL)
#define ACQCMN_SFT_TRG_EN_TMR_1_EVENT1_EN_SHIFT (17UL)
#define ACQCMN_SFT_TRG_EN_TMR_1_EVENT0_EN_MASK (0x10000UL)
#define ACQCMN_SFT_TRG_EN_TMR_1_EVENT0_EN_SHIFT (16UL)
#define ACQCMN_SFT_TRG_EN_TMR_0_IN3_EN_MASK (0x200UL)
#define ACQCMN_SFT_TRG_EN_TMR_0_IN3_EN_SHIFT (9UL)
#define ACQCMN_SFT_TRG_EN_TMR_0_IN2_EN_MASK (0x100UL)
#define ACQCMN_SFT_TRG_EN_TMR_0_IN2_EN_SHIFT (8UL)
#define ACQCMN_SFT_TRG_EN_TMR_0_IN1_EN_MASK (0x80UL)
#define ACQCMN_SFT_TRG_EN_TMR_0_IN1_EN_SHIFT (7UL)
#define ACQCMN_SFT_TRG_EN_TMR_0_IN0_EN_MASK (0x40UL)
#define ACQCMN_SFT_TRG_EN_TMR_0_IN0_EN_SHIFT (6UL)
#define ACQCMN_SFT_TRG_EN_TMR_0_EN_EN_MASK (0x20UL)
#define ACQCMN_SFT_TRG_EN_TMR_0_EN_EN_SHIFT (5UL)
#define ACQCMN_SFT_TRG_EN_TMR_0_ETR_EN_MASK (0x10UL)
#define ACQCMN_SFT_TRG_EN_TMR_0_ETR_EN_SHIFT (4UL)
#define ACQCMN_SFT_TRG_EN_TMR_0_EVENT3_EN_MASK (0x8UL)
#define ACQCMN_SFT_TRG_EN_TMR_0_EVENT3_EN_SHIFT (3UL)
#define ACQCMN_SFT_TRG_EN_TMR_0_EVENT2_EN_MASK (0x4UL)
#define ACQCMN_SFT_TRG_EN_TMR_0_EVENT2_EN_SHIFT (2UL)
#define ACQCMN_SFT_TRG_EN_TMR_0_EVENT1_EN_MASK (0x2UL)
#define ACQCMN_SFT_TRG_EN_TMR_0_EVENT1_EN_SHIFT (1UL)
#define ACQCMN_SFT_TRG_EN_TMR_0_EVENT0_EN_MASK (0x1UL)
#define ACQCMN_SFT_TRG_EN_TMR_0_EVENT0_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_SFT_TRG_PULSE_TMR_TYPE;
#define ACQCMN_SFT_TRG_PULSE_TMR_EN_MASK (0x1UL)
#define ACQCMN_SFT_TRG_PULSE_TMR_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_SFT_TRG_EN_AWG_TYPE;
#define ACQCMN_SFT_TRG_EN_AWG_3_INCR_EN_MASK (0x80UL)
#define ACQCMN_SFT_TRG_EN_AWG_3_INCR_EN_SHIFT (7UL)
#define ACQCMN_SFT_TRG_EN_AWG_2_INCR_EN_MASK (0x40UL)
#define ACQCMN_SFT_TRG_EN_AWG_2_INCR_EN_SHIFT (6UL)
#define ACQCMN_SFT_TRG_EN_AWG_1_INCR_EN_MASK (0x20UL)
#define ACQCMN_SFT_TRG_EN_AWG_1_INCR_EN_SHIFT (5UL)
#define ACQCMN_SFT_TRG_EN_AWG_0_INCR_EN_MASK (0x10UL)
#define ACQCMN_SFT_TRG_EN_AWG_0_INCR_EN_SHIFT (4UL)
#define ACQCMN_SFT_TRG_EN_AWG_3_START_EN_MASK (0x8UL)
#define ACQCMN_SFT_TRG_EN_AWG_3_START_EN_SHIFT (3UL)
#define ACQCMN_SFT_TRG_EN_AWG_2_START_EN_MASK (0x4UL)
#define ACQCMN_SFT_TRG_EN_AWG_2_START_EN_SHIFT (2UL)
#define ACQCMN_SFT_TRG_EN_AWG_1_START_EN_MASK (0x2UL)
#define ACQCMN_SFT_TRG_EN_AWG_1_START_EN_SHIFT (1UL)
#define ACQCMN_SFT_TRG_EN_AWG_0_START_EN_MASK (0x1UL)
#define ACQCMN_SFT_TRG_EN_AWG_0_START_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_SFT_TRG_PULSE_AWG_TYPE;
#define ACQCMN_SFT_TRG_PULSE_AWG_EN_MASK (0x1UL)
#define ACQCMN_SFT_TRG_PULSE_AWG_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_SFT_TRG_EN_HKADC_TYPE;
#define ACQCMN_SFT_TRG_EN_HKADC_START7_EN_MASK (0x80UL)
#define ACQCMN_SFT_TRG_EN_HKADC_START7_EN_SHIFT (7UL)
#define ACQCMN_SFT_TRG_EN_HKADC_START6_EN_MASK (0x40UL)
#define ACQCMN_SFT_TRG_EN_HKADC_START6_EN_SHIFT (6UL)
#define ACQCMN_SFT_TRG_EN_HKADC_START5_EN_MASK (0x20UL)
#define ACQCMN_SFT_TRG_EN_HKADC_START5_EN_SHIFT (5UL)
#define ACQCMN_SFT_TRG_EN_HKADC_START4_EN_MASK (0x10UL)
#define ACQCMN_SFT_TRG_EN_HKADC_START4_EN_SHIFT (4UL)
#define ACQCMN_SFT_TRG_EN_HKADC_START3_EN_MASK (0x8UL)
#define ACQCMN_SFT_TRG_EN_HKADC_START3_EN_SHIFT (3UL)
#define ACQCMN_SFT_TRG_EN_HKADC_START2_EN_MASK (0x4UL)
#define ACQCMN_SFT_TRG_EN_HKADC_START2_EN_SHIFT (2UL)
#define ACQCMN_SFT_TRG_EN_HKADC_START1_EN_MASK (0x2UL)
#define ACQCMN_SFT_TRG_EN_HKADC_START1_EN_SHIFT (1UL)
#define ACQCMN_SFT_TRG_EN_HKADC_START0_EN_MASK (0x1UL)
#define ACQCMN_SFT_TRG_EN_HKADC_START0_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_SFT_TRG_PULSE_HKADC_TYPE;
#define ACQCMN_SFT_TRG_PULSE_HKADC_EN_MASK (0x1UL)
#define ACQCMN_SFT_TRG_PULSE_HKADC_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_SFT_TRG_EN_HKDAC_TYPE;
#define ACQCMN_SFT_TRG_EN_HKDAC_START_MASK (0x1UL)
#define ACQCMN_SFT_TRG_EN_HKDAC_START_SHIFT (0UL)




typedef uint32_t ACQCMN_SFT_TRG_PULSE_HKDAC_TYPE;
#define ACQCMN_SFT_TRG_PULSE_HKDAC_EN_MASK (0x1UL)
#define ACQCMN_SFT_TRG_PULSE_HKDAC_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_SFT_TRG_EN_NSU_TYPE;
#define ACQCMN_SFT_TRG_EN_NSU_EVENT7_EN_MASK (0x80UL)
#define ACQCMN_SFT_TRG_EN_NSU_EVENT7_EN_SHIFT (7UL)
#define ACQCMN_SFT_TRG_EN_NSU_EVENT6_EN_MASK (0x40UL)
#define ACQCMN_SFT_TRG_EN_NSU_EVENT6_EN_SHIFT (6UL)
#define ACQCMN_SFT_TRG_EN_NSU_EVENT5_EN_MASK (0x20UL)
#define ACQCMN_SFT_TRG_EN_NSU_EVENT5_EN_SHIFT (5UL)
#define ACQCMN_SFT_TRG_EN_NSU_EVENT4_EN_MASK (0x10UL)
#define ACQCMN_SFT_TRG_EN_NSU_EVENT4_EN_SHIFT (4UL)
#define ACQCMN_SFT_TRG_EN_NSU_EVENT3_EN_MASK (0x8UL)
#define ACQCMN_SFT_TRG_EN_NSU_EVENT3_EN_SHIFT (3UL)
#define ACQCMN_SFT_TRG_EN_NSU_EVENT2_EN_MASK (0x4UL)
#define ACQCMN_SFT_TRG_EN_NSU_EVENT2_EN_SHIFT (2UL)
#define ACQCMN_SFT_TRG_EN_NSU_EVENT1_EN_MASK (0x2UL)
#define ACQCMN_SFT_TRG_EN_NSU_EVENT1_EN_SHIFT (1UL)
#define ACQCMN_SFT_TRG_EN_NSU_EVENT0_EN_MASK (0x1UL)
#define ACQCMN_SFT_TRG_EN_NSU_EVENT0_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_SFT_TRG_PULSE_NSU_TYPE;
#define ACQCMN_SFT_TRG_PULSE_NSU_EN_MASK (0x1UL)
#define ACQCMN_SFT_TRG_PULSE_NSU_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_SFT_TRG_EN_ACQ_TRG_TYPE;
#define ACQCMN_SFT_TRG_EN_ACQ_TRG_PRE_MASK (0x1UL)
#define ACQCMN_SFT_TRG_EN_ACQ_TRG_PRE_SHIFT (0UL)




typedef uint32_t ACQCMN_SFT_TRG_PULSE_ACQ_TRG_TYPE;
#define ACQCMN_SFT_TRG_PULSE_ACQ_TRG_EN_MASK (0x1UL)
#define ACQCMN_SFT_TRG_PULSE_ACQ_TRG_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_EXT_PIN_PULSE_CTRL_TYPE;
#define ACQCMN_EXT_PIN_PULSE_CTRL_SFT_PHASE_SEL_MASK (0xe0000UL)
#define ACQCMN_EXT_PIN_PULSE_CTRL_SFT_PHASE_SEL_SHIFT (17UL)
#define ACQCMN_EXT_PIN_PULSE_CTRL_SFT_EN_MASK (0x10000UL)
#define ACQCMN_EXT_PIN_PULSE_CTRL_SFT_EN_SHIFT (16UL)
#define ACQCMN_EXT_PIN_PULSE_CTRL_HW_PHASE_SEL_MASK (0x6UL)
#define ACQCMN_EXT_PIN_PULSE_CTRL_HW_PHASE_SEL_SHIFT (1UL)
#define ACQCMN_EXT_PIN_PULSE_CTRL_HW_SEARCH_EN_MASK (0x1UL)
#define ACQCMN_EXT_PIN_PULSE_CTRL_HW_SEARCH_EN_SHIFT (0UL)




typedef uint32_t ACQCMN_ACQ_TRG_CNTR_CTRL_TYPE;
#define ACQCMN_ACQ_TRG_CNTR_CTRL_ACQ_TRG_CNTR_EN_MASK (0x10000UL)
#define ACQCMN_ACQ_TRG_CNTR_CTRL_ACQ_TRG_CNTR_EN_SHIFT (16UL)
#define ACQCMN_ACQ_TRG_CNTR_CTRL_PROG_CNT_MASK (0xffffUL)
#define ACQCMN_ACQ_TRG_CNTR_CTRL_PROG_CNT_SHIFT (0UL)




typedef uint32_t ACQCMN_TRG_OUT_CTRL_MUX_TYPE;
#define ACQCMN_TRG_OUT_CTRL_MUX_SRC_SEL_MASK (0x80000000UL)
#define ACQCMN_TRG_OUT_CTRL_MUX_SRC_SEL_SHIFT (31UL)
#define ACQCMN_TRG_OUT_CTRL_MUX_PULSE_WIDTH_MASK (0x7fff0000UL)
#define ACQCMN_TRG_OUT_CTRL_MUX_PULSE_WIDTH_SHIFT (16UL)
#define ACQCMN_TRG_OUT_CTRL_MUX_POL_MASK (0x8000UL)
#define ACQCMN_TRG_OUT_CTRL_MUX_POL_SHIFT (15UL)
#define ACQCMN_TRG_OUT_CTRL_MUX_PULSE_DELAY_MASK (0x7fffUL)
#define ACQCMN_TRG_OUT_CTRL_MUX_PULSE_DELAY_SHIFT (0UL)




typedef uint32_t ACQCMN_TRG_OUT_CTRL_TYPE;
#define ACQCMN_TRG_OUT_CTRL_PULSE_WIDTH_MASK (0x7fff0000UL)
#define ACQCMN_TRG_OUT_CTRL_PULSE_WIDTH_SHIFT (16UL)
#define ACQCMN_TRG_OUT_CTRL_POL_MASK (0x8000UL)
#define ACQCMN_TRG_OUT_CTRL_POL_SHIFT (15UL)
#define ACQCMN_TRG_OUT_CTRL_PULSE_DELAY_MASK (0x7fffUL)
#define ACQCMN_TRG_OUT_CTRL_PULSE_DELAY_SHIFT (0UL)




typedef uint32_t ACQCMN_SPARE_END_ADDR_TYPE;
#define ACQCMN_SPARE_END_ADDR_MASK (0xffffffffUL)
#define ACQCMN_SPARE_END_ADDR_SHIFT (0UL)


typedef volatile struct sACQCMN_AXIS_CTRL_TYPE {
    ACQCMN_AXIS_CTRL0_TYPE axis0_ctrl0; /* OFFSET: 0x84 */
    ACQCMN_AXIS_CTRL1_TYPE axis0_ctrl1; /* OFFSET: 0x88 */
} ACQCMN_AXIS_CTRL_TYPE;


#define ACQCMN_AXIS_SIZE  (2UL)


typedef volatile struct sACQCMN_RDBType {
    ACQCMN_GLOBAL_RST_EN_TYPE global_rst_en; /* OFFSET: 0x0 */
    ACQCMN_LOCAL_RST_EN_TYPE local_rst_en; /* OFFSET: 0x4 */
    ACQCMN_CLK_ENB_TYPE clk_enb; /* OFFSET: 0x8 */
    ACQCMN_RESERVED_TYPE rsvd0[116]; /* OFFSET: 0xc */
    ACQCMN_AXIS_CMN_CTRL_TYPE axis_cmn_ctrl; /* OFFSET: 0x80 */
    ACQCMN_AXIS_CTRL_TYPE axis[ACQCMN_AXIS_SIZE]; /* OFFSET: 0x84 */
    ACQCMN_RESERVED_TYPE rsvd1[108]; /* OFFSET: 0x94 */
    ACQCMN_TMR0_EVENT0_SRC_CTRL_TYPE tmr0_event0_src_ctrl; /* OFFSET: 0x100 */
    ACQCMN_TMR0_EVENT0_SRC_SEL_TYPE tmr0_event0_src_sel; /* OFFSET: 0x104 */
    ACQCMN_TMR0_EVENT1_SRC_CTRL_TYPE tmr0_event1_src_ctrl; /* OFFSET: 0x108 */
    ACQCMN_TMR0_EVENT1_SRC_SEL_TYPE tmr0_event1_src_sel; /* OFFSET: 0x10c */
    ACQCMN_TMR0_EVENT2_SRC_CTRL_TYPE tmr0_event2_src_ctrl; /* OFFSET: 0x110 */
    ACQCMN_TMR0_EVENT2_SRC_SEL_TYPE tmr0_event2_src_sel; /* OFFSET: 0x114 */
    ACQCMN_TMR0_EVENT3_SRC_CTRL_TYPE tmr0_event3_src_ctrl; /* OFFSET: 0x118 */
    ACQCMN_TMR0_EVENT3_SRC_SEL_TYPE tmr0_event3_src_sel; /* OFFSET: 0x11c */
    ACQCMN_TMR0_ETR_SRC_CTRL_TYPE tmr0_etr_src_ctrl; /* OFFSET: 0x120 */
    ACQCMN_TMR0_ETR_SRC_SEL_TYPE tmr0_etr_src_sel; /* OFFSET: 0x124 */
    ACQCMN_TMR0_EN_SRC_CTRL_TYPE tmr0_en_src_ctrl; /* OFFSET: 0x128 */
    ACQCMN_TMR0_EN_SRC_SEL_TYPE tmr0_en_src_sel; /* OFFSET: 0x12c */
    ACQCMN_TMR0_IN0_SRC_CTRL_TYPE tmr0_in0_src_ctrl; /* OFFSET: 0x130 */
    ACQCMN_TMR0_IN0_SRC_SEL_TYPE tmr0_in0_src_sel; /* OFFSET: 0x134 */
    ACQCMN_TMR0_IN1_SRC_CTRL_TYPE tmr0_in1_src_ctrl; /* OFFSET: 0x138 */
    ACQCMN_TMR0_IN1_SRC_SEL_TYPE tmr0_in1_src_sel; /* OFFSET: 0x13c */
    ACQCMN_TMR0_IN2_SRC_CTRL_TYPE tmr0_in2_src_ctrl; /* OFFSET: 0x140 */
    ACQCMN_TMR0_IN2_SRC_SEL_TYPE tmr0_in2_src_sel; /* OFFSET: 0x144 */
    ACQCMN_TMR0_IN3_SRC_CTRL_TYPE tmr0_in3_src_ctrl; /* OFFSET: 0x148 */
    ACQCMN_TMR0_IN3_SRC_SEL_TYPE tmr0_in3_src_sel; /* OFFSET: 0x14c */
    ACQCMN_RESERVED_TYPE rsvd2[48]; /* OFFSET: 0x150 */
    ACQCMN_TMR1_EVENT0_SRC_CTRL_TYPE tmr1_event0_src_ctrl; /* OFFSET: 0x180 */
    ACQCMN_TMR1_EVENT0_SRC_SEL_TYPE tmr1_event0_src_sel; /* OFFSET: 0x184 */
    ACQCMN_TMR1_EVENT1_SRC_CTRL_TYPE tmr1_event1_src_ctrl; /* OFFSET: 0x188 */
    ACQCMN_TMR1_EVENT1_SRC_SEL_TYPE tmr1_event1_src_sel; /* OFFSET: 0x18c */
    ACQCMN_TMR1_EVENT2_SRC_CTRL_TYPE tmr1_event2_src_ctrl; /* OFFSET: 0x190 */
    ACQCMN_TMR1_EVENT2_SRC_SEL_TYPE tmr1_event2_src_sel; /* OFFSET: 0x194 */
    ACQCMN_TMR1_EVENT3_SRC_CTRL_TYPE tmr1_event3_src_ctrl; /* OFFSET: 0x198 */
    ACQCMN_TMR1_EVENT3_SRC_SEL_TYPE tmr1_event3_src_sel; /* OFFSET: 0x19c */
    ACQCMN_TMR1_ETR_SRC_CTRL_TYPE tmr1_etr_src_ctrl; /* OFFSET: 0x1a0 */
    ACQCMN_TMR1_ETR_SRC_SEL_TYPE tmr1_etr_src_sel; /* OFFSET: 0x1a4 */
    ACQCMN_TMR1_EN_SRC_CTRL_TYPE tmr1_en_src_ctrl; /* OFFSET: 0x1a8 */
    ACQCMN_TMR1_EN_SRC_SEL_TYPE tmr1_en_src_sel; /* OFFSET: 0x1ac */
    ACQCMN_TMR1_IN0_SRC_CTRL_TYPE tmr1_in0_src_ctrl; /* OFFSET: 0x1b0 */
    ACQCMN_TMR1_IN0_SRC_SEL_TYPE tmr1_in0_src_sel; /* OFFSET: 0x1b4 */
    ACQCMN_TMR1_IN1_SRC_CTRL_TYPE tmr1_in1_src_ctrl; /* OFFSET: 0x1b8 */
    ACQCMN_TMR1_IN1_SRC_SEL_TYPE tmr1_in1_src_sel; /* OFFSET: 0x1bc */
    ACQCMN_TMR1_IN2_SRC_CTRL_TYPE tmr1_in2_src_ctrl; /* OFFSET: 0x1c0 */
    ACQCMN_TMR1_IN2_SRC_SEL_TYPE tmr1_in2_src_sel; /* OFFSET: 0x1c4 */
    ACQCMN_TMR1_IN3_SRC_CTRL_TYPE tmr1_in3_src_ctrl; /* OFFSET: 0x1c8 */
    ACQCMN_TMR1_IN3_SRC_SEL_TYPE tmr1_in3_src_sel; /* OFFSET: 0x1cc */
    ACQCMN_RESERVED_TYPE rsvd3[48]; /* OFFSET: 0x1d0 */
    ACQCMN_CAPCOM_CMN_SRC_CTRL_TYPE awg0_start_src_ctrl0; /* OFFSET: 0x200 */
    ACQCMN_AWG_CMN_SRC_CTRL_TYPE awg0_start_src_ctrl1; /* OFFSET: 0x204 */
    ACQCMN_AWG_START_SRC_CTRL_TYPE awg0_start_src_ctrl2; /* OFFSET: 0x208 */
    ACQCMN_AWG_START_SRC_SEL_TYPE awg0_start_src_sel; /* OFFSET: 0x20c */
    ACQCMN_CAPCOM_CMN_SRC_CTRL_TYPE awg1_start_src_ctrl0; /* OFFSET: 0x210 */
    ACQCMN_AWG_CMN_SRC_CTRL_TYPE awg1_start_src_ctrl1; /* OFFSET: 0x214 */
    ACQCMN_AWG_START_SRC_CTRL_TYPE awg1_start_src_ctrl2; /* OFFSET: 0x218 */
    ACQCMN_AWG_START_SRC_SEL_TYPE awg1_start_src_sel; /* OFFSET: 0x21c */
    ACQCMN_CAPCOM_CMN_SRC_CTRL_TYPE awg2_start_src_ctrl0; /* OFFSET: 0x220 */
    ACQCMN_AWG_CMN_SRC_CTRL_TYPE awg2_start_src_ctrl1; /* OFFSET: 0x224 */
    ACQCMN_AWG_START_SRC_CTRL_TYPE awg2_start_src_ctrl2; /* OFFSET: 0x228 */
    ACQCMN_AWG_START_SRC_SEL_TYPE awg2_start_src_sel; /* OFFSET: 0x22c */
    ACQCMN_CAPCOM_CMN_SRC_CTRL_TYPE awg3_start_src_ctrl0; /* OFFSET: 0x230 */
    ACQCMN_AWG_CMN_SRC_CTRL_TYPE awg3_start_src_ctrl1; /* OFFSET: 0x234 */
    ACQCMN_AWG_START_SRC_CTRL_TYPE awg3_start_src_ctrl2; /* OFFSET: 0x238 */
    ACQCMN_AWG_START_SRC_SEL_TYPE awg3_start_src_sel; /* OFFSET: 0x23c */
    ACQCMN_RESERVED_TYPE rsvd4[64]; /* OFFSET: 0x240 */
    ACQCMN_CAPCOM_CMN_SRC_CTRL_TYPE awg0_incr_src_ctrl0; /* OFFSET: 0x280 */
    ACQCMN_AWG_CMN_SRC_CTRL_TYPE awg0_incr_src_ctrl1; /* OFFSET: 0x284 */
    ACQCMN_AWG_INCR_SRC_CTRL_TYPE awg0_incr_src_ctrl2; /* OFFSET: 0x288 */
    ACQCMN_AWG_INCR_SRC_SEL_TYPE awg0_incr_src_sel; /* OFFSET: 0x28c */
    ACQCMN_CAPCOM_CMN_SRC_CTRL_TYPE awg1_incr_src_ctrl0; /* OFFSET: 0x290 */
    ACQCMN_AWG_CMN_SRC_CTRL_TYPE awg1_incr_src_ctrl1; /* OFFSET: 0x294 */
    ACQCMN_AWG_INCR_SRC_CTRL_TYPE awg1_incr_src_ctrl2; /* OFFSET: 0x298 */
    ACQCMN_AWG_INCR_SRC_SEL_TYPE awg1_incr_src_sel; /* OFFSET: 0x29c */
    ACQCMN_CAPCOM_CMN_SRC_CTRL_TYPE awg2_incr_src_ctrl0; /* OFFSET: 0x2a0 */
    ACQCMN_AWG_CMN_SRC_CTRL_TYPE awg2_incr_src_ctrl1; /* OFFSET: 0x2a4 */
    ACQCMN_AWG_INCR_SRC_CTRL_TYPE awg2_incr_src_ctrl2; /* OFFSET: 0x2a8 */
    ACQCMN_AWG_INCR_SRC_SEL_TYPE awg2_incr_src_sel; /* OFFSET: 0x2ac */
    ACQCMN_CAPCOM_CMN_SRC_CTRL_TYPE awg3_incr_src_ctrl0; /* OFFSET: 0x2b0 */
    ACQCMN_AWG_CMN_SRC_CTRL_TYPE awg3_incr_src_ctrl1; /* OFFSET: 0x2b4 */
    ACQCMN_AWG_INCR_SRC_CTRL_TYPE awg3_incr_src_ctrl2; /* OFFSET: 0x2b8 */
    ACQCMN_AWG_INCR_SRC_SEL_TYPE awg3_incr_src_sel; /* OFFSET: 0x2bc */
    ACQCMN_RESERVED_TYPE rsvd5[64]; /* OFFSET: 0x2c0 */
    ACQCMN_CAPCOM_CMN_SRC_CTRL_TYPE acq_trg_src_ctrl0; /* OFFSET: 0x300 */
    ACQCMN_AWG_CMN_SRC_CTRL_TYPE acq_trg_src_ctrl1; /* OFFSET: 0x304 */
    ACQCMN_ACQ_TRG_SRC_CTRL_TYPE acq_trg_src_ctrl2; /* OFFSET: 0x308 */
    ACQCMN_ACQ_TRG_SRC_SEL_TYPE acq_trg_src_sel; /* OFFSET: 0x30c */
    ACQCMN_HKADC_START_SRC_CTRL_TYPE hkadc_start_src_ctrl; /* OFFSET: 0x310 */
    ACQCMN_HKADC_START_SRC_SEL_TYPE hkadc_start0_src_sel; /* OFFSET: 0x314 */
    ACQCMN_HKADC_START_SRC_SEL_TYPE hkadc_start1_src_sel; /* OFFSET: 0x318 */
    ACQCMN_HKADC_START_SRC_SEL_TYPE hkadc_start2_src_sel; /* OFFSET: 0x31c */
    ACQCMN_HKADC_START_SRC_SEL_TYPE hkadc_start3_src_sel; /* OFFSET: 0x320 */
    ACQCMN_HKADC_START_SRC_SEL_TYPE hkadc_start4_src_sel; /* OFFSET: 0x324 */
    ACQCMN_HKADC_START_SRC_SEL_TYPE hkadc_start5_src_sel; /* OFFSET: 0x328 */
    ACQCMN_HKADC_START_SRC_SEL_TYPE hkadc_start6_src_sel; /* OFFSET: 0x32c */
    ACQCMN_HKADC_START_SRC_SEL_TYPE hkadc_start7_src_sel; /* OFFSET: 0x330 */
    ACQCMN_RESERVED_TYPE rsvd6[76]; /* OFFSET: 0x334 */
    ACQCMN_HKDAC_START_SRC_CTRL_TYPE hkdac_start_src_ctrl; /* OFFSET: 0x380 */
    ACQCMN_HKDAC_START_SRC_SEL_TYPE hkdac_start_src_sel; /* OFFSET: 0x384 */
    ACQCMN_NSU_EVENT0_SRC_CTRL_TYPE nsu_event0_src_ctrl; /* OFFSET: 0x388 */
    ACQCMN_NSU_EVENT0_SRC_SEL_TYPE nsu_event0_src_sel; /* OFFSET: 0x38c */
    ACQCMN_NSU_EVENT1_SRC_CTRL_TYPE nsu_event1_src_ctrl; /* OFFSET: 0x390 */
    ACQCMN_NSU_EVENT1_SRC_SEL_TYPE nsu_event1_src_sel; /* OFFSET: 0x394 */
    ACQCMN_NSU_EVENT2_SRC_CTRL_TYPE nsu_event2_src_ctrl; /* OFFSET: 0x398 */
    ACQCMN_NSU_EVENT2_SRC_SEL_TYPE nsu_event2_src_sel; /* OFFSET: 0x39c */
    ACQCMN_NSU_EVENT3_SRC_CTRL_TYPE nsu_event3_src_ctrl; /* OFFSET: 0x3a0 */
    ACQCMN_NSU_EVENT3_SRC_SEL_TYPE nsu_event3_src_sel; /* OFFSET: 0x3a4 */
    ACQCMN_NSU_EVENT4_SRC_CTRL_TYPE nsu_event4_src_ctrl; /* OFFSET: 0x3a8 */
    ACQCMN_NSU_EVENT4_SRC_SEL_TYPE nsu_event4_src_sel; /* OFFSET: 0x3ac */
    ACQCMN_NSU_EVENT5_SRC_CTRL_TYPE nsu_event5_src_ctrl; /* OFFSET: 0x3b0 */
    ACQCMN_NSU_EVENT5_SRC_SEL_TYPE nsu_event5_src_sel; /* OFFSET: 0x3b4 */
    ACQCMN_NSU_EVENT6_SRC_CTRL_TYPE nsu_event6_src_ctrl; /* OFFSET: 0x3b8 */
    ACQCMN_NSU_EVENT6_SRC_SEL_TYPE nsu_event6_src_sel; /* OFFSET: 0x3bc */
    ACQCMN_NSU_EVENT7_SRC_CTRL_TYPE nsu_event7_src_ctrl; /* OFFSET: 0x3c0 */
    ACQCMN_NSU_EVENT7_SRC_SEL_TYPE nsu_event7_src_sel; /* OFFSET: 0x3c4 */
    ACQCMN_NSU_CNTR_HW_RST_SRC_CTRL_TYPE nsu_cntr_hw_rst_src_ctrl; /* OFFSET: 0x3c8 */
    ACQCMN_NSU_CNTR_HW_RST_SRC_SEL_TYPE nsu_cntr_hw_rst_src_sel; /* OFFSET: 0x3cc */
    ACQCMN_RESERVED_TYPE rsvd7[48]; /* OFFSET: 0x3d0 */
    ACQCMN_SFT_TRG_EN_TMR_TYPE sft_trg_en_tmr; /* OFFSET: 0x400 */
    ACQCMN_SFT_TRG_PULSE_TMR_TYPE sft_trg_pulse_tmr; /* OFFSET: 0x404 */
    ACQCMN_SFT_TRG_EN_AWG_TYPE sft_trg_en_awg; /* OFFSET: 0x408 */
    ACQCMN_SFT_TRG_PULSE_AWG_TYPE sft_trg_pulse_awg; /* OFFSET: 0x40c */
    ACQCMN_SFT_TRG_EN_HKADC_TYPE sft_trg_en_hkadc; /* OFFSET: 0x410 */
    ACQCMN_SFT_TRG_PULSE_HKADC_TYPE sft_trg_pulse_hkadc; /* OFFSET: 0x414 */
    ACQCMN_SFT_TRG_EN_HKDAC_TYPE sft_trg_en_hkdac; /* OFFSET: 0x418 */
    ACQCMN_SFT_TRG_PULSE_HKDAC_TYPE sft_trg_pulse_hkdac; /* OFFSET: 0x41c */
    ACQCMN_SFT_TRG_EN_NSU_TYPE sft_trg_en_nsu; /* OFFSET: 0x420 */
    ACQCMN_SFT_TRG_PULSE_NSU_TYPE sft_trg_pulse_nsu; /* OFFSET: 0x424 */
    ACQCMN_SFT_TRG_EN_ACQ_TRG_TYPE sft_trg_en_acq_trg; /* OFFSET: 0x428 */
    ACQCMN_SFT_TRG_PULSE_ACQ_TRG_TYPE sft_trg_pulse_acq_trg; /* OFFSET: 0x42c */
    ACQCMN_EXT_PIN_PULSE_CTRL_TYPE ext_pin_pulse_ctrl; /* OFFSET: 0x430 */
    uint32_t reserved_17; /* OFFSET: 0x434 */
    ACQCMN_ACQ_TRG_CNTR_CTRL_TYPE acq_trg_cntr_ctrl; /* OFFSET: 0x438 */
    ACQCMN_RESERVED_TYPE rsvd8[68]; /* OFFSET: 0x43c */
    ACQCMN_TRG_OUT_CTRL_MUX_TYPE act_clamp_out_ctrl; /* OFFSET: 0x480 */
    ACQCMN_TRG_OUT_CTRL_MUX_TYPE tia_mute_ctrl; /* OFFSET: 0x484 */
    ACQCMN_TRG_OUT_CTRL_MUX_TYPE acq_status_ctrl; /* OFFSET: 0x488 */
    ACQCMN_TRG_OUT_CTRL_TYPE txslzr_trg_out_ctrl; /* OFFSET: 0x48c */
    ACQCMN_TRG_OUT_CTRL_TYPE hsadc_trg_out_ctrl; /* OFFSET: 0x490 */
    ACQCMN_TRG_OUT_CTRL_TYPE hsref_trg_out_ctrl; /* OFFSET: 0x494 */
    ACQCMN_TRG_OUT_CTRL_TYPE nsu_trg_gpio0_out_ctrl; /* OFFSET: 0x498 */
    ACQCMN_TRG_OUT_CTRL_TYPE nsu_trg_gpio1_out_ctrl; /* OFFSET: 0x49c */
    ACQCMN_TRG_OUT_CTRL_TYPE nsu_trg_gpio2_out_ctrl; /* OFFSET: 0x4a0 */
    ACQCMN_TRG_OUT_CTRL_TYPE nsu_trg_gpio3_out_ctrl; /* OFFSET: 0x4a4 */
    ACQCMN_RESERVED_TYPE rsvd9[2644]; /* OFFSET: 0x4a8 */
    ACQCMN_SPARE_END_ADDR_TYPE spare_end_addr; /* OFFSET: 0xefc */
} ACQCMN_RDBType;


#define ACQ_COMMON_BASE                 ((uintptr_t)(0xE0600000UL))

#define ACQCMN_AXIS_CTRL_TYPE_OFFSET    (0xE0600084UL)



#define ACQCMN_MAX_HW_ID                (1UL)

#endif /* ACQCMN_RDB_H */
