/*****************************************************************************
 Copyright 2024 Broadcom.  All rights reserved.
 Broadcom Proprietary and Confidential
******************************************************************************/
/**
    @file awg_intr_rdb.h
    @brief RDB File for AWG_INTR

    @version BCM89580_A0_20230125_RDB
*/

#ifndef AWG_INTR_RDB_H
#define AWG_INTR_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t AWG_INTR_AAMISIE_TYPE;
#define AWG_INTR_AAMISIE_P_CH3_MEM_INIT_ERR_INTR_MASK (0x80000UL)
#define AWG_INTR_AAMISIE_P_CH3_MEM_INIT_ERR_INTR_SHIFT (19UL)
#define AWG_INTR_AAMISIE_P_CH2_MEM_INIT_ERR_INTR_MASK (0x40000UL)
#define AWG_INTR_AAMISIE_P_CH2_MEM_INIT_ERR_INTR_SHIFT (18UL)
#define AWG_INTR_AAMISIE_P_CH1_MEM_INIT_ERR_INTR_MASK (0x20000UL)
#define AWG_INTR_AAMISIE_P_CH1_MEM_INIT_ERR_INTR_SHIFT (17UL)
#define AWG_INTR_AAMISIE_P_CH0_MEM_INIT_ERR_INTR_MASK (0x10000UL)
#define AWG_INTR_AAMISIE_P_CH0_MEM_INIT_ERR_INTR_SHIFT (16UL)
#define AWG_INTR_AAMISIE_P_CH3_MEM_INIT_DONE_INTR_MASK (0x800UL)
#define AWG_INTR_AAMISIE_P_CH3_MEM_INIT_DONE_INTR_SHIFT (11UL)
#define AWG_INTR_AAMISIE_P_CH2_MEM_INIT_DONE_INTR_MASK (0x400UL)
#define AWG_INTR_AAMISIE_P_CH2_MEM_INIT_DONE_INTR_SHIFT (10UL)
#define AWG_INTR_AAMISIE_P_CH1_MEM_INIT_DONE_INTR_MASK (0x200UL)
#define AWG_INTR_AAMISIE_P_CH1_MEM_INIT_DONE_INTR_SHIFT (9UL)
#define AWG_INTR_AAMISIE_P_CH0_MEM_INIT_DONE_INTR_MASK (0x100UL)
#define AWG_INTR_AAMISIE_P_CH0_MEM_INIT_DONE_INTR_SHIFT (8UL)
#define AWG_INTR_AAMISIE_P_CH3_MEM_SEC_INTR_MASK (0x8UL)
#define AWG_INTR_AAMISIE_P_CH3_MEM_SEC_INTR_SHIFT (3UL)
#define AWG_INTR_AAMISIE_P_CH2_MEM_SEC_INTR_MASK (0x4UL)
#define AWG_INTR_AAMISIE_P_CH2_MEM_SEC_INTR_SHIFT (2UL)
#define AWG_INTR_AAMISIE_P_CH1_MEM_SEC_INTR_MASK (0x2UL)
#define AWG_INTR_AAMISIE_P_CH1_MEM_SEC_INTR_SHIFT (1UL)
#define AWG_INTR_AAMISIE_P_CH0_MEM_SEC_INTR_MASK (0x1UL)
#define AWG_INTR_AAMISIE_P_CH0_MEM_SEC_INTR_SHIFT (0UL)




typedef uint32_t AWG_INTR_AAMISIE1_TYPE;
#define AWG_INTR_AAMISIE1_CH3_MEM_INIT_ERR_INTR_W2CLR_MASK (0x80000UL)
#define AWG_INTR_AAMISIE1_CH3_MEM_INIT_ERR_INTR_W2CLR_SHIFT (19UL)
#define AWG_INTR_AAMISIE1_CH2_MEM_INIT_ERR_INTR_W2CLR_MASK (0x40000UL)
#define AWG_INTR_AAMISIE1_CH2_MEM_INIT_ERR_INTR_W2CLR_SHIFT (18UL)
#define AWG_INTR_AAMISIE1_CH1_MEM_INIT_ERR_INTR_W2CLR_MASK (0x20000UL)
#define AWG_INTR_AAMISIE1_CH1_MEM_INIT_ERR_INTR_W2CLR_SHIFT (17UL)
#define AWG_INTR_AAMISIE1_CH0_MEM_INIT_ERR_INTR_W2CLR_MASK (0x10000UL)
#define AWG_INTR_AAMISIE1_CH0_MEM_INIT_ERR_INTR_W2CLR_SHIFT (16UL)
#define AWG_INTR_AAMISIE1_CH3_MEM_INIT_DONE_INTR_W2CLR_MASK (0x800UL)
#define AWG_INTR_AAMISIE1_CH3_MEM_INIT_DONE_INTR_W2CLR_SHIFT (11UL)
#define AWG_INTR_AAMISIE1_CH2_MEM_INIT_DONE_INTR_W2CLR_MASK (0x400UL)
#define AWG_INTR_AAMISIE1_CH2_MEM_INIT_DONE_INTR_W2CLR_SHIFT (10UL)
#define AWG_INTR_AAMISIE1_CH1_MEM_INIT_DONE_INTR_W2CLR_MASK (0x200UL)
#define AWG_INTR_AAMISIE1_CH1_MEM_INIT_DONE_INTR_W2CLR_SHIFT (9UL)
#define AWG_INTR_AAMISIE1_CH0_MEM_INIT_DONE_INTR_W2CLR_MASK (0x100UL)
#define AWG_INTR_AAMISIE1_CH0_MEM_INIT_DONE_INTR_W2CLR_SHIFT (8UL)
#define AWG_INTR_AAMISIE1_CH3_MEM_SEC_INTR_W2CLR_MASK (0x8UL)
#define AWG_INTR_AAMISIE1_CH3_MEM_SEC_INTR_W2CLR_SHIFT (3UL)
#define AWG_INTR_AAMISIE1_CH2_MEM_SEC_INTR_W2CLR_MASK (0x4UL)
#define AWG_INTR_AAMISIE1_CH2_MEM_SEC_INTR_W2CLR_SHIFT (2UL)
#define AWG_INTR_AAMISIE1_CH1_MEM_SEC_INTR_W2CLR_MASK (0x2UL)
#define AWG_INTR_AAMISIE1_CH1_MEM_SEC_INTR_W2CLR_SHIFT (1UL)
#define AWG_INTR_AAMISIE1_CH0_MEM_SEC_INTR_W2CLR_MASK (0x1UL)
#define AWG_INTR_AAMISIE1_CH0_MEM_SEC_INTR_W2CLR_SHIFT (0UL)




typedef uint32_t AWG_INTR_AAMISIE2_TYPE;
#define AWG_INTR_AAMISIE2_ENABLE_CH3_MEM_INIT_ERR_INTR_MASK (0x80000UL)
#define AWG_INTR_AAMISIE2_ENABLE_CH3_MEM_INIT_ERR_INTR_SHIFT (19UL)
#define AWG_INTR_AAMISIE2_ENABLE_CH2_MEM_INIT_ERR_INTR_MASK (0x40000UL)
#define AWG_INTR_AAMISIE2_ENABLE_CH2_MEM_INIT_ERR_INTR_SHIFT (18UL)
#define AWG_INTR_AAMISIE2_ENABLE_CH1_MEM_INIT_ERR_INTR_MASK (0x20000UL)
#define AWG_INTR_AAMISIE2_ENABLE_CH1_MEM_INIT_ERR_INTR_SHIFT (17UL)
#define AWG_INTR_AAMISIE2_ENABLE_CH0_MEM_INIT_ERR_INTR_MASK (0x10000UL)
#define AWG_INTR_AAMISIE2_ENABLE_CH0_MEM_INIT_ERR_INTR_SHIFT (16UL)
#define AWG_INTR_AAMISIE2_ENABLE_CH3_MEM_INIT_DONE_INTR_MASK (0x800UL)
#define AWG_INTR_AAMISIE2_ENABLE_CH3_MEM_INIT_DONE_INTR_SHIFT (11UL)
#define AWG_INTR_AAMISIE2_ENABLE_CH2_MEM_INIT_DONE_INTR_MASK (0x400UL)
#define AWG_INTR_AAMISIE2_ENABLE_CH2_MEM_INIT_DONE_INTR_SHIFT (10UL)
#define AWG_INTR_AAMISIE2_ENABLE_CH1_MEM_INIT_DONE_INTR_MASK (0x200UL)
#define AWG_INTR_AAMISIE2_ENABLE_CH1_MEM_INIT_DONE_INTR_SHIFT (9UL)
#define AWG_INTR_AAMISIE2_ENABLE_CH0_MEM_INIT_DONE_INTR_MASK (0x100UL)
#define AWG_INTR_AAMISIE2_ENABLE_CH0_MEM_INIT_DONE_INTR_SHIFT (8UL)
#define AWG_INTR_AAMISIE2_ENABLE_CH3_MEM_SEC_INTR_MASK (0x8UL)
#define AWG_INTR_AAMISIE2_ENABLE_CH3_MEM_SEC_INTR_SHIFT (3UL)
#define AWG_INTR_AAMISIE2_ENABLE_CH2_MEM_SEC_INTR_MASK (0x4UL)
#define AWG_INTR_AAMISIE2_ENABLE_CH2_MEM_SEC_INTR_SHIFT (2UL)
#define AWG_INTR_AAMISIE2_ENABLE_CH1_MEM_SEC_INTR_MASK (0x2UL)
#define AWG_INTR_AAMISIE2_ENABLE_CH1_MEM_SEC_INTR_SHIFT (1UL)
#define AWG_INTR_AAMISIE2_ENABLE_CH0_MEM_SEC_INTR_MASK (0x1UL)
#define AWG_INTR_AAMISIE2_ENABLE_CH0_MEM_SEC_INTR_SHIFT (0UL)




typedef uint32_t AWG_INTR_ACQ_AWG_DED_INTR_EIPR_TYPE;
#define AWG_INTR_ACQ_AWG_DED_INTR_EIPR_P_CH3_MEM_DED_INTR_MASK (0x8UL)
#define AWG_INTR_ACQ_AWG_DED_INTR_EIPR_P_CH3_MEM_DED_INTR_SHIFT (3UL)
#define AWG_INTR_ACQ_AWG_DED_INTR_EIPR_P_CH2_MEM_DED_INTR_MASK (0x4UL)
#define AWG_INTR_ACQ_AWG_DED_INTR_EIPR_P_CH2_MEM_DED_INTR_SHIFT (2UL)
#define AWG_INTR_ACQ_AWG_DED_INTR_EIPR_P_CH1_MEM_DED_INTR_MASK (0x2UL)
#define AWG_INTR_ACQ_AWG_DED_INTR_EIPR_P_CH1_MEM_DED_INTR_SHIFT (1UL)
#define AWG_INTR_ACQ_AWG_DED_INTR_EIPR_P_CH0_MEM_DED_INTR_MASK (0x1UL)
#define AWG_INTR_ACQ_AWG_DED_INTR_EIPR_P_CH0_MEM_DED_INTR_SHIFT (0UL)




typedef uint32_t AWG_INTR_ACQ_AWG_DED_INTR_EISR_TYPE;
#define AWG_INTR_ACQ_AWG_DED_INTR_EISR_CH3_MEM_DED_INTR_W2CLR_MASK (0x8UL)
#define AWG_INTR_ACQ_AWG_DED_INTR_EISR_CH3_MEM_DED_INTR_W2CLR_SHIFT (3UL)
#define AWG_INTR_ACQ_AWG_DED_INTR_EISR_CH2_MEM_DED_INTR_W2CLR_MASK (0x4UL)
#define AWG_INTR_ACQ_AWG_DED_INTR_EISR_CH2_MEM_DED_INTR_W2CLR_SHIFT (2UL)
#define AWG_INTR_ACQ_AWG_DED_INTR_EISR_CH1_MEM_DED_INTR_W2CLR_MASK (0x2UL)
#define AWG_INTR_ACQ_AWG_DED_INTR_EISR_CH1_MEM_DED_INTR_W2CLR_SHIFT (1UL)
#define AWG_INTR_ACQ_AWG_DED_INTR_EISR_CH0_MEM_DED_INTR_W2CLR_MASK (0x1UL)
#define AWG_INTR_ACQ_AWG_DED_INTR_EISR_CH0_MEM_DED_INTR_W2CLR_SHIFT (0UL)




typedef uint32_t AWG_INTR_AADIE_TYPE;
#define AWG_INTR_AADIE_ENABLE_CH3_MEM_DED_INTR_MASK (0x8UL)
#define AWG_INTR_AADIE_ENABLE_CH3_MEM_DED_INTR_SHIFT (3UL)
#define AWG_INTR_AADIE_ENABLE_CH2_MEM_DED_INTR_MASK (0x4UL)
#define AWG_INTR_AADIE_ENABLE_CH2_MEM_DED_INTR_SHIFT (2UL)
#define AWG_INTR_AADIE_ENABLE_CH1_MEM_DED_INTR_MASK (0x2UL)
#define AWG_INTR_AADIE_ENABLE_CH1_MEM_DED_INTR_SHIFT (1UL)
#define AWG_INTR_AADIE_ENABLE_CH0_MEM_DED_INTR_MASK (0x1UL)
#define AWG_INTR_AADIE_ENABLE_CH0_MEM_DED_INTR_SHIFT (0UL)




typedef uint32_t AWG_INTR_ACQ_AWG0_STATUS_INTR_EIPR_TYPE;
#define AWG_INTR_ACQ_AWG0_STATUS_INTR_EIPR_P_CTRL3_INTR_MASK (0x20UL)
#define AWG_INTR_ACQ_AWG0_STATUS_INTR_EIPR_P_CTRL3_INTR_SHIFT (5UL)
#define AWG_INTR_ACQ_AWG0_STATUS_INTR_EIPR_P_CTRL2_INTR_MASK (0x10UL)
#define AWG_INTR_ACQ_AWG0_STATUS_INTR_EIPR_P_CTRL2_INTR_SHIFT (4UL)
#define AWG_INTR_ACQ_AWG0_STATUS_INTR_EIPR_P_CTRL1_INTR_MASK (0x8UL)
#define AWG_INTR_ACQ_AWG0_STATUS_INTR_EIPR_P_CTRL1_INTR_SHIFT (3UL)
#define AWG_INTR_ACQ_AWG0_STATUS_INTR_EIPR_P_CTRL0_INTR_MASK (0x4UL)
#define AWG_INTR_ACQ_AWG0_STATUS_INTR_EIPR_P_CTRL0_INTR_SHIFT (2UL)
#define AWG_INTR_ACQ_AWG0_STATUS_INTR_EIPR_P_RESET_INTR_MASK (0x2UL)
#define AWG_INTR_ACQ_AWG0_STATUS_INTR_EIPR_P_RESET_INTR_SHIFT (1UL)
#define AWG_INTR_ACQ_AWG0_STATUS_INTR_EIPR_P_PG_SW_DONE_MASK (0x1UL)
#define AWG_INTR_ACQ_AWG0_STATUS_INTR_EIPR_P_PG_SW_DONE_SHIFT (0UL)




typedef uint32_t AWG_INTR_ACQ_AWG0_STATUS_INTR_EISR_TYPE;
#define AWG_INTR_ACQ_AWG0_STATUS_INTR_EISR_CTRL3_INTR_W2CLR_MASK (0x20UL)
#define AWG_INTR_ACQ_AWG0_STATUS_INTR_EISR_CTRL3_INTR_W2CLR_SHIFT (5UL)
#define AWG_INTR_ACQ_AWG0_STATUS_INTR_EISR_CTRL2_INTR_W2CLR_MASK (0x10UL)
#define AWG_INTR_ACQ_AWG0_STATUS_INTR_EISR_CTRL2_INTR_W2CLR_SHIFT (4UL)
#define AWG_INTR_ACQ_AWG0_STATUS_INTR_EISR_CTRL1_INTR_W2CLR_MASK (0x8UL)
#define AWG_INTR_ACQ_AWG0_STATUS_INTR_EISR_CTRL1_INTR_W2CLR_SHIFT (3UL)
#define AWG_INTR_ACQ_AWG0_STATUS_INTR_EISR_CTRL0_INTR_W2CLR_MASK (0x4UL)
#define AWG_INTR_ACQ_AWG0_STATUS_INTR_EISR_CTRL0_INTR_W2CLR_SHIFT (2UL)
#define AWG_INTR_ACQ_AWG0_STATUS_INTR_EISR_RESET_INTR_W2CLR_MASK (0x2UL)
#define AWG_INTR_ACQ_AWG0_STATUS_INTR_EISR_RESET_INTR_W2CLR_SHIFT (1UL)
#define AWG_INTR_ACQ_AWG0_STATUS_INTR_EISR_PG_SW_DONE_W2CLR_MASK (0x1UL)
#define AWG_INTR_ACQ_AWG0_STATUS_INTR_EISR_PG_SW_DONE_W2CLR_SHIFT (0UL)




typedef uint32_t AWG_INTR_ACQ_AWG0_STATUS_INTR_EIER_TYPE;
#define AWG_INTR_ACQ_AWG0_STATUS_INTR_EIER_ENABLE_CTRL3_INTR_MASK (0x20UL)
#define AWG_INTR_ACQ_AWG0_STATUS_INTR_EIER_ENABLE_CTRL3_INTR_SHIFT (5UL)
#define AWG_INTR_ACQ_AWG0_STATUS_INTR_EIER_ENABLE_CTRL2_INTR_MASK (0x10UL)
#define AWG_INTR_ACQ_AWG0_STATUS_INTR_EIER_ENABLE_CTRL2_INTR_SHIFT (4UL)
#define AWG_INTR_ACQ_AWG0_STATUS_INTR_EIER_ENABLE_CTRL1_INTR_MASK (0x8UL)
#define AWG_INTR_ACQ_AWG0_STATUS_INTR_EIER_ENABLE_CTRL1_INTR_SHIFT (3UL)
#define AWG_INTR_ACQ_AWG0_STATUS_INTR_EIER_ENABLE_CTRL0_INTR_MASK (0x4UL)
#define AWG_INTR_ACQ_AWG0_STATUS_INTR_EIER_ENABLE_CTRL0_INTR_SHIFT (2UL)
#define AWG_INTR_ACQ_AWG0_STATUS_INTR_EIER_ENABLE_RESET_INTR_MASK (0x2UL)
#define AWG_INTR_ACQ_AWG0_STATUS_INTR_EIER_ENABLE_RESET_INTR_SHIFT (1UL)
#define AWG_INTR_ACQ_AWG0_STATUS_INTR_EIER_ENABLE_PG_SW_DONE_MASK (0x1UL)
#define AWG_INTR_ACQ_AWG0_STATUS_INTR_EIER_ENABLE_PG_SW_DONE_SHIFT (0UL)




typedef uint32_t AWG_INTR_ACQ_AWG1_STATUS_INTR_EIPR_TYPE;
#define AWG_INTR_ACQ_AWG1_STATUS_INTR_EIPR_P_CTRL3_INTR_MASK (0x20UL)
#define AWG_INTR_ACQ_AWG1_STATUS_INTR_EIPR_P_CTRL3_INTR_SHIFT (5UL)
#define AWG_INTR_ACQ_AWG1_STATUS_INTR_EIPR_P_CTRL2_INTR_MASK (0x10UL)
#define AWG_INTR_ACQ_AWG1_STATUS_INTR_EIPR_P_CTRL2_INTR_SHIFT (4UL)
#define AWG_INTR_ACQ_AWG1_STATUS_INTR_EIPR_P_CTRL1_INTR_MASK (0x8UL)
#define AWG_INTR_ACQ_AWG1_STATUS_INTR_EIPR_P_CTRL1_INTR_SHIFT (3UL)
#define AWG_INTR_ACQ_AWG1_STATUS_INTR_EIPR_P_CTRL0_INTR_MASK (0x4UL)
#define AWG_INTR_ACQ_AWG1_STATUS_INTR_EIPR_P_CTRL0_INTR_SHIFT (2UL)
#define AWG_INTR_ACQ_AWG1_STATUS_INTR_EIPR_P_RESET_INTR_MASK (0x2UL)
#define AWG_INTR_ACQ_AWG1_STATUS_INTR_EIPR_P_RESET_INTR_SHIFT (1UL)
#define AWG_INTR_ACQ_AWG1_STATUS_INTR_EIPR_P_PG_SW_DONE_MASK (0x1UL)
#define AWG_INTR_ACQ_AWG1_STATUS_INTR_EIPR_P_PG_SW_DONE_SHIFT (0UL)




typedef uint32_t AWG_INTR_ACQ_AWG1_STATUS_INTR_EISR_TYPE;
#define AWG_INTR_ACQ_AWG1_STATUS_INTR_EISR_CTRL3_INTR_W2CLR_MASK (0x20UL)
#define AWG_INTR_ACQ_AWG1_STATUS_INTR_EISR_CTRL3_INTR_W2CLR_SHIFT (5UL)
#define AWG_INTR_ACQ_AWG1_STATUS_INTR_EISR_CTRL2_INTR_W2CLR_MASK (0x10UL)
#define AWG_INTR_ACQ_AWG1_STATUS_INTR_EISR_CTRL2_INTR_W2CLR_SHIFT (4UL)
#define AWG_INTR_ACQ_AWG1_STATUS_INTR_EISR_CTRL1_INTR_W2CLR_MASK (0x8UL)
#define AWG_INTR_ACQ_AWG1_STATUS_INTR_EISR_CTRL1_INTR_W2CLR_SHIFT (3UL)
#define AWG_INTR_ACQ_AWG1_STATUS_INTR_EISR_CTRL0_INTR_W2CLR_MASK (0x4UL)
#define AWG_INTR_ACQ_AWG1_STATUS_INTR_EISR_CTRL0_INTR_W2CLR_SHIFT (2UL)
#define AWG_INTR_ACQ_AWG1_STATUS_INTR_EISR_RESET_INTR_W2CLR_MASK (0x2UL)
#define AWG_INTR_ACQ_AWG1_STATUS_INTR_EISR_RESET_INTR_W2CLR_SHIFT (1UL)
#define AWG_INTR_ACQ_AWG1_STATUS_INTR_EISR_PG_SW_DONE_W2CLR_MASK (0x1UL)
#define AWG_INTR_ACQ_AWG1_STATUS_INTR_EISR_PG_SW_DONE_W2CLR_SHIFT (0UL)




typedef uint32_t AWG_INTR_ACQ_AWG1_STATUS_INTR_EIER_TYPE;
#define AWG_INTR_ACQ_AWG1_STATUS_INTR_EIER_ENABLE_CTRL3_INTR_MASK (0x20UL)
#define AWG_INTR_ACQ_AWG1_STATUS_INTR_EIER_ENABLE_CTRL3_INTR_SHIFT (5UL)
#define AWG_INTR_ACQ_AWG1_STATUS_INTR_EIER_ENABLE_CTRL2_INTR_MASK (0x10UL)
#define AWG_INTR_ACQ_AWG1_STATUS_INTR_EIER_ENABLE_CTRL2_INTR_SHIFT (4UL)
#define AWG_INTR_ACQ_AWG1_STATUS_INTR_EIER_ENABLE_CTRL1_INTR_MASK (0x8UL)
#define AWG_INTR_ACQ_AWG1_STATUS_INTR_EIER_ENABLE_CTRL1_INTR_SHIFT (3UL)
#define AWG_INTR_ACQ_AWG1_STATUS_INTR_EIER_ENABLE_CTRL0_INTR_MASK (0x4UL)
#define AWG_INTR_ACQ_AWG1_STATUS_INTR_EIER_ENABLE_CTRL0_INTR_SHIFT (2UL)
#define AWG_INTR_ACQ_AWG1_STATUS_INTR_EIER_ENABLE_RESET_INTR_MASK (0x2UL)
#define AWG_INTR_ACQ_AWG1_STATUS_INTR_EIER_ENABLE_RESET_INTR_SHIFT (1UL)
#define AWG_INTR_ACQ_AWG1_STATUS_INTR_EIER_ENABLE_PG_SW_DONE_MASK (0x1UL)
#define AWG_INTR_ACQ_AWG1_STATUS_INTR_EIER_ENABLE_PG_SW_DONE_SHIFT (0UL)




typedef uint32_t AWG_INTR_ACQ_AWG2_STATUS_INTR_EIPR_TYPE;
#define AWG_INTR_ACQ_AWG2_STATUS_INTR_EIPR_P_CTRL3_INTR_MASK (0x20UL)
#define AWG_INTR_ACQ_AWG2_STATUS_INTR_EIPR_P_CTRL3_INTR_SHIFT (5UL)
#define AWG_INTR_ACQ_AWG2_STATUS_INTR_EIPR_P_CTRL2_INTR_MASK (0x10UL)
#define AWG_INTR_ACQ_AWG2_STATUS_INTR_EIPR_P_CTRL2_INTR_SHIFT (4UL)
#define AWG_INTR_ACQ_AWG2_STATUS_INTR_EIPR_P_CTRL1_INTR_MASK (0x8UL)
#define AWG_INTR_ACQ_AWG2_STATUS_INTR_EIPR_P_CTRL1_INTR_SHIFT (3UL)
#define AWG_INTR_ACQ_AWG2_STATUS_INTR_EIPR_P_CTRL0_INTR_MASK (0x4UL)
#define AWG_INTR_ACQ_AWG2_STATUS_INTR_EIPR_P_CTRL0_INTR_SHIFT (2UL)
#define AWG_INTR_ACQ_AWG2_STATUS_INTR_EIPR_P_RESET_INTR_MASK (0x2UL)
#define AWG_INTR_ACQ_AWG2_STATUS_INTR_EIPR_P_RESET_INTR_SHIFT (1UL)
#define AWG_INTR_ACQ_AWG2_STATUS_INTR_EIPR_P_PG_SW_DONE_MASK (0x1UL)
#define AWG_INTR_ACQ_AWG2_STATUS_INTR_EIPR_P_PG_SW_DONE_SHIFT (0UL)




typedef uint32_t AWG_INTR_ACQ_AWG2_STATUS_INTR_EISR_TYPE;
#define AWG_INTR_ACQ_AWG2_STATUS_INTR_EISR_CTRL3_INTR_W2CLR_MASK (0x20UL)
#define AWG_INTR_ACQ_AWG2_STATUS_INTR_EISR_CTRL3_INTR_W2CLR_SHIFT (5UL)
#define AWG_INTR_ACQ_AWG2_STATUS_INTR_EISR_CTRL2_INTR_W2CLR_MASK (0x10UL)
#define AWG_INTR_ACQ_AWG2_STATUS_INTR_EISR_CTRL2_INTR_W2CLR_SHIFT (4UL)
#define AWG_INTR_ACQ_AWG2_STATUS_INTR_EISR_CTRL1_INTR_W2CLR_MASK (0x8UL)
#define AWG_INTR_ACQ_AWG2_STATUS_INTR_EISR_CTRL1_INTR_W2CLR_SHIFT (3UL)
#define AWG_INTR_ACQ_AWG2_STATUS_INTR_EISR_CTRL0_INTR_W2CLR_MASK (0x4UL)
#define AWG_INTR_ACQ_AWG2_STATUS_INTR_EISR_CTRL0_INTR_W2CLR_SHIFT (2UL)
#define AWG_INTR_ACQ_AWG2_STATUS_INTR_EISR_RESET_INTR_W2CLR_MASK (0x2UL)
#define AWG_INTR_ACQ_AWG2_STATUS_INTR_EISR_RESET_INTR_W2CLR_SHIFT (1UL)
#define AWG_INTR_ACQ_AWG2_STATUS_INTR_EISR_PG_SW_DONE_W2CLR_MASK (0x1UL)
#define AWG_INTR_ACQ_AWG2_STATUS_INTR_EISR_PG_SW_DONE_W2CLR_SHIFT (0UL)




typedef uint32_t AWG_INTR_ACQ_AWG2_STATUS_INTR_EIER_TYPE;
#define AWG_INTR_ACQ_AWG2_STATUS_INTR_EIER_ENABLE_CTRL3_INTR_MASK (0x20UL)
#define AWG_INTR_ACQ_AWG2_STATUS_INTR_EIER_ENABLE_CTRL3_INTR_SHIFT (5UL)
#define AWG_INTR_ACQ_AWG2_STATUS_INTR_EIER_ENABLE_CTRL2_INTR_MASK (0x10UL)
#define AWG_INTR_ACQ_AWG2_STATUS_INTR_EIER_ENABLE_CTRL2_INTR_SHIFT (4UL)
#define AWG_INTR_ACQ_AWG2_STATUS_INTR_EIER_ENABLE_CTRL1_INTR_MASK (0x8UL)
#define AWG_INTR_ACQ_AWG2_STATUS_INTR_EIER_ENABLE_CTRL1_INTR_SHIFT (3UL)
#define AWG_INTR_ACQ_AWG2_STATUS_INTR_EIER_ENABLE_CTRL0_INTR_MASK (0x4UL)
#define AWG_INTR_ACQ_AWG2_STATUS_INTR_EIER_ENABLE_CTRL0_INTR_SHIFT (2UL)
#define AWG_INTR_ACQ_AWG2_STATUS_INTR_EIER_ENABLE_RESET_INTR_MASK (0x2UL)
#define AWG_INTR_ACQ_AWG2_STATUS_INTR_EIER_ENABLE_RESET_INTR_SHIFT (1UL)
#define AWG_INTR_ACQ_AWG2_STATUS_INTR_EIER_ENABLE_PG_SW_DONE_MASK (0x1UL)
#define AWG_INTR_ACQ_AWG2_STATUS_INTR_EIER_ENABLE_PG_SW_DONE_SHIFT (0UL)




typedef uint32_t AWG_INTR_ACQ_AWG3_STATUS_INTR_EIPR_TYPE;
#define AWG_INTR_ACQ_AWG3_STATUS_INTR_EIPR_P_CTRL3_INTR_MASK (0x20UL)
#define AWG_INTR_ACQ_AWG3_STATUS_INTR_EIPR_P_CTRL3_INTR_SHIFT (5UL)
#define AWG_INTR_ACQ_AWG3_STATUS_INTR_EIPR_P_CTRL2_INTR_MASK (0x10UL)
#define AWG_INTR_ACQ_AWG3_STATUS_INTR_EIPR_P_CTRL2_INTR_SHIFT (4UL)
#define AWG_INTR_ACQ_AWG3_STATUS_INTR_EIPR_P_CTRL1_INTR_MASK (0x8UL)
#define AWG_INTR_ACQ_AWG3_STATUS_INTR_EIPR_P_CTRL1_INTR_SHIFT (3UL)
#define AWG_INTR_ACQ_AWG3_STATUS_INTR_EIPR_P_CTRL0_INTR_MASK (0x4UL)
#define AWG_INTR_ACQ_AWG3_STATUS_INTR_EIPR_P_CTRL0_INTR_SHIFT (2UL)
#define AWG_INTR_ACQ_AWG3_STATUS_INTR_EIPR_P_RESET_INTR_MASK (0x2UL)
#define AWG_INTR_ACQ_AWG3_STATUS_INTR_EIPR_P_RESET_INTR_SHIFT (1UL)
#define AWG_INTR_ACQ_AWG3_STATUS_INTR_EIPR_P_PG_SW_DONE_MASK (0x1UL)
#define AWG_INTR_ACQ_AWG3_STATUS_INTR_EIPR_P_PG_SW_DONE_SHIFT (0UL)




typedef uint32_t AWG_INTR_ACQ_AWG3_STATUS_INTR_EISR_TYPE;
#define AWG_INTR_ACQ_AWG3_STATUS_INTR_EISR_CTRL3_INTR_W2CLR_MASK (0x20UL)
#define AWG_INTR_ACQ_AWG3_STATUS_INTR_EISR_CTRL3_INTR_W2CLR_SHIFT (5UL)
#define AWG_INTR_ACQ_AWG3_STATUS_INTR_EISR_CTRL2_INTR_W2CLR_MASK (0x10UL)
#define AWG_INTR_ACQ_AWG3_STATUS_INTR_EISR_CTRL2_INTR_W2CLR_SHIFT (4UL)
#define AWG_INTR_ACQ_AWG3_STATUS_INTR_EISR_CTRL1_INTR_W2CLR_MASK (0x8UL)
#define AWG_INTR_ACQ_AWG3_STATUS_INTR_EISR_CTRL1_INTR_W2CLR_SHIFT (3UL)
#define AWG_INTR_ACQ_AWG3_STATUS_INTR_EISR_CTRL0_INTR_W2CLR_MASK (0x4UL)
#define AWG_INTR_ACQ_AWG3_STATUS_INTR_EISR_CTRL0_INTR_W2CLR_SHIFT (2UL)
#define AWG_INTR_ACQ_AWG3_STATUS_INTR_EISR_RESET_INTR_W2CLR_MASK (0x2UL)
#define AWG_INTR_ACQ_AWG3_STATUS_INTR_EISR_RESET_INTR_W2CLR_SHIFT (1UL)
#define AWG_INTR_ACQ_AWG3_STATUS_INTR_EISR_PG_SW_DONE_W2CLR_MASK (0x1UL)
#define AWG_INTR_ACQ_AWG3_STATUS_INTR_EISR_PG_SW_DONE_W2CLR_SHIFT (0UL)




typedef uint32_t AWG_INTR_ACQ_AWG3_STATUS_INTR_EIER_TYPE;
#define AWG_INTR_ACQ_AWG3_STATUS_INTR_EIER_ENABLE_CTRL3_INTR_MASK (0x20UL)
#define AWG_INTR_ACQ_AWG3_STATUS_INTR_EIER_ENABLE_CTRL3_INTR_SHIFT (5UL)
#define AWG_INTR_ACQ_AWG3_STATUS_INTR_EIER_ENABLE_CTRL2_INTR_MASK (0x10UL)
#define AWG_INTR_ACQ_AWG3_STATUS_INTR_EIER_ENABLE_CTRL2_INTR_SHIFT (4UL)
#define AWG_INTR_ACQ_AWG3_STATUS_INTR_EIER_ENABLE_CTRL1_INTR_MASK (0x8UL)
#define AWG_INTR_ACQ_AWG3_STATUS_INTR_EIER_ENABLE_CTRL1_INTR_SHIFT (3UL)
#define AWG_INTR_ACQ_AWG3_STATUS_INTR_EIER_ENABLE_CTRL0_INTR_MASK (0x4UL)
#define AWG_INTR_ACQ_AWG3_STATUS_INTR_EIER_ENABLE_CTRL0_INTR_SHIFT (2UL)
#define AWG_INTR_ACQ_AWG3_STATUS_INTR_EIER_ENABLE_RESET_INTR_MASK (0x2UL)
#define AWG_INTR_ACQ_AWG3_STATUS_INTR_EIER_ENABLE_RESET_INTR_SHIFT (1UL)
#define AWG_INTR_ACQ_AWG3_STATUS_INTR_EIER_ENABLE_PG_SW_DONE_MASK (0x1UL)
#define AWG_INTR_ACQ_AWG3_STATUS_INTR_EIER_ENABLE_PG_SW_DONE_SHIFT (0UL)




typedef uint8_t AWG_INTR_RESERVED_TYPE;




typedef uint32_t AWG_INTR_SPARE_END_REG_TYPE;
#define AWG_INTR_SPARE_END_REG_MASK (0xffffffffUL)
#define AWG_INTR_SPARE_END_REG_SHIFT (0UL)


typedef volatile struct sAWG_CHAN_INTR_Type {
    AWG_INTR_ACQ_AWG0_STATUS_INTR_EIPR_TYPE acq_awg0_status_intr_eipr; /* OFFSET: 0x18 */
    AWG_INTR_ACQ_AWG0_STATUS_INTR_EISR_TYPE acq_awg0_status_intr_eisr; /* OFFSET: 0x1c */
    AWG_INTR_ACQ_AWG0_STATUS_INTR_EIER_TYPE acq_awg0_status_intr_eier; /* OFFSET: 0x20 */
} AWG_INTR_AWG_CHAN_INTR_Type;


#define AWG_INTR_CHAN_SIZE  (4UL)


typedef volatile struct sAWG_INTR_RDBType {
    AWG_INTR_AAMISIE_TYPE acq_awg_mem_init_sec_intr_eipr; /* OFFSET: 0x0 */
    AWG_INTR_AAMISIE1_TYPE acq_awg_mem_init_sec_intr_eisr; /* OFFSET: 0x4 */
    AWG_INTR_AAMISIE2_TYPE acq_awg_mem_init_sec_intr_eier; /* OFFSET: 0x8 */
    AWG_INTR_ACQ_AWG_DED_INTR_EIPR_TYPE acq_awg_ded_intr_eipr; /* OFFSET: 0xc */
    AWG_INTR_ACQ_AWG_DED_INTR_EISR_TYPE acq_awg_ded_intr_eisr; /* OFFSET: 0x10 */
    AWG_INTR_AADIE_TYPE acq_awg_ded_intr_eier; /* OFFSET: 0x14 */
    AWG_INTR_AWG_CHAN_INTR_Type chan[AWG_INTR_CHAN_SIZE]; /* OFFSET: 0x18 */
    AWG_INTR_RESERVED_TYPE rsvd0[180]; /* OFFSET: 0x48 */
    AWG_INTR_SPARE_END_REG_TYPE spare_end_reg; /* OFFSET: 0xfc */
} AWG_INTR_RDBType;


#define AWG_INTR_BASE                   (0xE0610F00UL)

#define AWG_CHAN_INTR_TYPE_OFFSET       (0xE0610f18UL)



#define AWG_INTR_MAX_HW_ID              (1UL)

#endif /* AWG_INTR_RDB_H */
