/*****************************************************************************
 Copyright 2024 Broadcom Corporation.  All rights reserved.

 Broadcom Proprietary and Confidential
******************************************************************************/
/**
    @file cct_rdb.h
    @brief RDB File for CCT

    @version BCM89580_A0_20230125_RDB
*/

#ifndef CCT_RDB_H
#define CCT_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t CCT_CTRLA_TYPE;
#define CCT_CTRLA_EN_MASK (0x1UL)
#define CCT_CTRLA_EN_SHIFT (0UL)




typedef uint32_t CCT_PSC_RATIO_TYPE;
#define CCT_PSC_RATIO_MASK (0xffffUL)
#define CCT_PSC_RATIO_SHIFT (0UL)




typedef uint32_t CCT_PSC_TRIG_TYPE;
#define CCT_PSC_TRIG_MASK (0x1UL)
#define CCT_PSC_TRIG_SHIFT (0UL)




typedef uint32_t CCT_PSC_CTRL_TYPE;
#define CCT_PSC_CTRL_MASK_EVT3_MASK (0x200000UL)
#define CCT_PSC_CTRL_MASK_EVT3_SHIFT (21UL)
#define CCT_PSC_CTRL_MASK_EVT2_MASK (0x100000UL)
#define CCT_PSC_CTRL_MASK_EVT2_SHIFT (20UL)
#define CCT_PSC_CTRL_MASK_EVT1_MASK (0x80000UL)
#define CCT_PSC_CTRL_MASK_EVT1_SHIFT (19UL)
#define CCT_PSC_CTRL_MASK_EVT0_MASK (0x40000UL)
#define CCT_PSC_CTRL_MASK_EVT0_SHIFT (18UL)
#define CCT_PSC_CTRL_MASK_OUT3N_MASK (0x20000UL)
#define CCT_PSC_CTRL_MASK_OUT3N_SHIFT (17UL)
#define CCT_PSC_CTRL_MASK_OUT3_MASK (0x10000UL)
#define CCT_PSC_CTRL_MASK_OUT3_SHIFT (16UL)
#define CCT_PSC_CTRL_MASK_OUT2N_MASK (0x8000UL)
#define CCT_PSC_CTRL_MASK_OUT2N_SHIFT (15UL)
#define CCT_PSC_CTRL_MASK_OUT2_MASK (0x4000UL)
#define CCT_PSC_CTRL_MASK_OUT2_SHIFT (14UL)
#define CCT_PSC_CTRL_MASK_OUT1N_MASK (0x2000UL)
#define CCT_PSC_CTRL_MASK_OUT1N_SHIFT (13UL)
#define CCT_PSC_CTRL_MASK_OUT1_MASK (0x1000UL)
#define CCT_PSC_CTRL_MASK_OUT1_SHIFT (12UL)
#define CCT_PSC_CTRL_MASK_OUT0N_MASK (0x800UL)
#define CCT_PSC_CTRL_MASK_OUT0N_SHIFT (11UL)
#define CCT_PSC_CTRL_MASK_OUT0_MASK (0x400UL)
#define CCT_PSC_CTRL_MASK_OUT0_SHIFT (10UL)
#define CCT_PSC_CTRL_MASK_IN3_FE_MASK (0x200UL)
#define CCT_PSC_CTRL_MASK_IN3_FE_SHIFT (9UL)
#define CCT_PSC_CTRL_MASK_IN3_RE_MASK (0x100UL)
#define CCT_PSC_CTRL_MASK_IN3_RE_SHIFT (8UL)
#define CCT_PSC_CTRL_MASK_IN2_FE_MASK (0x80UL)
#define CCT_PSC_CTRL_MASK_IN2_FE_SHIFT (7UL)
#define CCT_PSC_CTRL_MASK_IN2_RE_MASK (0x40UL)
#define CCT_PSC_CTRL_MASK_IN2_RE_SHIFT (6UL)
#define CCT_PSC_CTRL_MASK_IN1_FE_MASK (0x20UL)
#define CCT_PSC_CTRL_MASK_IN1_FE_SHIFT (5UL)
#define CCT_PSC_CTRL_MASK_IN1_RE_MASK (0x10UL)
#define CCT_PSC_CTRL_MASK_IN1_RE_SHIFT (4UL)
#define CCT_PSC_CTRL_MASK_IN0_FE_MASK (0x8UL)
#define CCT_PSC_CTRL_MASK_IN0_FE_SHIFT (3UL)
#define CCT_PSC_CTRL_MASK_IN0_RE_MASK (0x4UL)
#define CCT_PSC_CTRL_MASK_IN0_RE_SHIFT (2UL)
#define CCT_PSC_CTRL_MASK_ETR_FE_MASK (0x2UL)
#define CCT_PSC_CTRL_MASK_ETR_FE_SHIFT (1UL)
#define CCT_PSC_CTRL_MASK_ETR_RE_MASK (0x1UL)
#define CCT_PSC_CTRL_MASK_ETR_RE_SHIFT (0UL)




typedef uint32_t CCT_UDC_CTRL_TYPE;
#define CCT_UDC_CTRL_ARR_MASK (0xffff0000UL)
#define CCT_UDC_CTRL_ARR_SHIFT (16UL)
#define CCT_UDC_CTRL_HW_EN_OVR_MASK (0x80UL)
#define CCT_UDC_CTRL_HW_EN_OVR_SHIFT (7UL)
#define CCT_UDC_CTRL_UDEN_MASK (0x40UL)
#define CCT_UDC_CTRL_UDEN_SHIFT (6UL)
#define CCT_UDC_CTRL_UDC_MASK_EVT3_MASK (0x20UL)
#define CCT_UDC_CTRL_UDC_MASK_EVT3_SHIFT (5UL)
#define CCT_UDC_CTRL_UDC_MASK_EVT2_MASK (0x10UL)
#define CCT_UDC_CTRL_UDC_MASK_EVT2_SHIFT (4UL)
#define CCT_UDC_CTRL_UDC_MASK_EVT1_MASK (0x8UL)
#define CCT_UDC_CTRL_UDC_MASK_EVT1_SHIFT (3UL)
#define CCT_UDC_CTRL_UDC_MASK_EVT0_MASK (0x4UL)
#define CCT_UDC_CTRL_UDC_MASK_EVT0_SHIFT (2UL)
#define CCT_UDC_CTRL_UDC_MASK_ETR_FE_MASK (0x2UL)
#define CCT_UDC_CTRL_UDC_MASK_ETR_FE_SHIFT (1UL)
#define CCT_UDC_CTRL_UDC_MASK_ETR_RE_MASK (0x1UL)
#define CCT_UDC_CTRL_UDC_MASK_ETR_RE_SHIFT (0UL)




typedef uint32_t CCT_UDC_TRIG_TYPE;
#define CCT_UDC_TRIG_MASK (0x1UL)
#define CCT_UDC_TRIG_SHIFT (0UL)




typedef uint32_t CCT_CCR_VAL_TYPE;
#define CCT_CCR_VAL_B_VAL_MASK (0xffff0000UL)
#define CCT_CCR_VAL_B_VAL_SHIFT (16UL)
#define CCT_CCR_VAL_A_VAL_MASK (0xffffUL)
#define CCT_CCR_VAL_A_VAL_SHIFT (0UL)




typedef uint32_t CCT_CCR_CTRL_TYPE;
#define CCT_CCR_CTRL_B_EN_XOR_MASK (0x8000000UL)
#define CCT_CCR_CTRL_B_EN_XOR_SHIFT (27UL)
#define CCT_CCR_CTRL_B_OUT_OEB_MASK (0x4000000UL)
#define CCT_CCR_CTRL_B_OUT_OEB_SHIFT (26UL)
#define CCT_CCR_CTRL_B_POL_MASK (0x2000000UL)
#define CCT_CCR_CTRL_B_POL_SHIFT (25UL)
#define CCT_CCR_CTRL_B_CCSEL_MASK (0x1000000UL)
#define CCT_CCR_CTRL_B_CCSEL_SHIFT (24UL)
#define CCT_CCR_CTRL_B_MASK_IN3_FE_MASK (0x800000UL)
#define CCT_CCR_CTRL_B_MASK_IN3_FE_SHIFT (23UL)
#define CCT_CCR_CTRL_B_MASK_IN3_RE_MASK (0x400000UL)
#define CCT_CCR_CTRL_B_MASK_IN3_RE_SHIFT (22UL)
#define CCT_CCR_CTRL_B_MASK_IN2_FE_MASK (0x200000UL)
#define CCT_CCR_CTRL_B_MASK_IN2_FE_SHIFT (21UL)
#define CCT_CCR_CTRL_B_MASK_IN2_RE_MASK (0x100000UL)
#define CCT_CCR_CTRL_B_MASK_IN2_RE_SHIFT (20UL)
#define CCT_CCR_CTRL_B_MASK_IN1_FE_MASK (0x80000UL)
#define CCT_CCR_CTRL_B_MASK_IN1_FE_SHIFT (19UL)
#define CCT_CCR_CTRL_B_MASK_IN1_RE_MASK (0x40000UL)
#define CCT_CCR_CTRL_B_MASK_IN1_RE_SHIFT (18UL)
#define CCT_CCR_CTRL_B_MASK_IN0_FE_MASK (0x20000UL)
#define CCT_CCR_CTRL_B_MASK_IN0_FE_SHIFT (17UL)
#define CCT_CCR_CTRL_B_MASK_IN0_RE_MASK (0x10000UL)
#define CCT_CCR_CTRL_B_MASK_IN0_RE_SHIFT (16UL)
#define CCT_CCR_CTRL_A_EN_XOR_MASK (0x800UL)
#define CCT_CCR_CTRL_A_EN_XOR_SHIFT (11UL)
#define CCT_CCR_CTRL_A_OUT_OEB_MASK (0x400UL)
#define CCT_CCR_CTRL_A_OUT_OEB_SHIFT (10UL)
#define CCT_CCR_CTRL_A_POL_MASK (0x200UL)
#define CCT_CCR_CTRL_A_POL_SHIFT (9UL)
#define CCT_CCR_CTRL_A_CCSEL_MASK (0x100UL)
#define CCT_CCR_CTRL_A_CCSEL_SHIFT (8UL)
#define CCT_CCR_CTRL_A_MASK_IN3_FE_MASK (0x80UL)
#define CCT_CCR_CTRL_A_MASK_IN3_FE_SHIFT (7UL)
#define CCT_CCR_CTRL_A_MASK_IN3_RE_MASK (0x40UL)
#define CCT_CCR_CTRL_A_MASK_IN3_RE_SHIFT (6UL)
#define CCT_CCR_CTRL_A_MASK_IN2_FE_MASK (0x20UL)
#define CCT_CCR_CTRL_A_MASK_IN2_FE_SHIFT (5UL)
#define CCT_CCR_CTRL_A_MASK_IN2_RE_MASK (0x10UL)
#define CCT_CCR_CTRL_A_MASK_IN2_RE_SHIFT (4UL)
#define CCT_CCR_CTRL_A_MASK_IN1_FE_MASK (0x8UL)
#define CCT_CCR_CTRL_A_MASK_IN1_FE_SHIFT (3UL)
#define CCT_CCR_CTRL_A_MASK_IN1_RE_MASK (0x4UL)
#define CCT_CCR_CTRL_A_MASK_IN1_RE_SHIFT (2UL)
#define CCT_CCR_CTRL_A_MASK_IN0_FE_MASK (0x2UL)
#define CCT_CCR_CTRL_A_MASK_IN0_FE_SHIFT (1UL)
#define CCT_CCR_CTRL_A_MASK_IN0_RE_MASK (0x1UL)
#define CCT_CCR_CTRL_A_MASK_IN0_RE_SHIFT (0UL)




typedef uint32_t CCT_CCR_INPUT_PSC_TYPE;
#define CCT_CCR_INPUT_PSC_B_MASK (0xffff0000UL)
#define CCT_CCR_INPUT_PSC_B_SHIFT (16UL)
#define CCT_CCR_INPUT_PSC_A_MASK (0xffffUL)
#define CCT_CCR_INPUT_PSC_A_SHIFT (0UL)




typedef uint32_t CCT_CCR_TRIG_TYPE;
#define CCT_CCR_TRIG_B_TRIG_MASK (0x2UL)
#define CCT_CCR_TRIG_B_TRIG_SHIFT (1UL)
#define CCT_CCR_TRIG_A_TRIG_MASK (0x1UL)
#define CCT_CCR_TRIG_A_TRIG_SHIFT (0UL)




typedef uint32_t CCT_OUT_CTRL_TYPE;
#define CCT_OUT_CTRL_3_MASK_CH3_B_MASK (0x80000000UL)
#define CCT_OUT_CTRL_3_MASK_CH3_B_SHIFT (31UL)
#define CCT_OUT_CTRL_3_MASK_CH3_A_MASK (0x40000000UL)
#define CCT_OUT_CTRL_3_MASK_CH3_A_SHIFT (30UL)
#define CCT_OUT_CTRL_3_MASK_CH2_B_MASK (0x20000000UL)
#define CCT_OUT_CTRL_3_MASK_CH2_B_SHIFT (29UL)
#define CCT_OUT_CTRL_3_MASK_CH2_A_MASK (0x10000000UL)
#define CCT_OUT_CTRL_3_MASK_CH2_A_SHIFT (28UL)
#define CCT_OUT_CTRL_3_MASK_CH1_B_MASK (0x8000000UL)
#define CCT_OUT_CTRL_3_MASK_CH1_B_SHIFT (27UL)
#define CCT_OUT_CTRL_3_MASK_CH1_A_MASK (0x4000000UL)
#define CCT_OUT_CTRL_3_MASK_CH1_A_SHIFT (26UL)
#define CCT_OUT_CTRL_3_MASK_CH0_B_MASK (0x2000000UL)
#define CCT_OUT_CTRL_3_MASK_CH0_B_SHIFT (25UL)
#define CCT_OUT_CTRL_3_MASK_CH0_A_MASK (0x1000000UL)
#define CCT_OUT_CTRL_3_MASK_CH0_A_SHIFT (24UL)
#define CCT_OUT_CTRL_2_MASK_CH3_B_MASK (0x800000UL)
#define CCT_OUT_CTRL_2_MASK_CH3_B_SHIFT (23UL)
#define CCT_OUT_CTRL_2_MASK_CH3_A_MASK (0x400000UL)
#define CCT_OUT_CTRL_2_MASK_CH3_A_SHIFT (22UL)
#define CCT_OUT_CTRL_2_MASK_CH2_B_MASK (0x200000UL)
#define CCT_OUT_CTRL_2_MASK_CH2_B_SHIFT (21UL)
#define CCT_OUT_CTRL_2_MASK_CH2_A_MASK (0x100000UL)
#define CCT_OUT_CTRL_2_MASK_CH2_A_SHIFT (20UL)
#define CCT_OUT_CTRL_2_MASK_CH1_B_MASK (0x80000UL)
#define CCT_OUT_CTRL_2_MASK_CH1_B_SHIFT (19UL)
#define CCT_OUT_CTRL_2_MASK_CH1_A_MASK (0x40000UL)
#define CCT_OUT_CTRL_2_MASK_CH1_A_SHIFT (18UL)
#define CCT_OUT_CTRL_2_MASK_CH0_B_MASK (0x20000UL)
#define CCT_OUT_CTRL_2_MASK_CH0_B_SHIFT (17UL)
#define CCT_OUT_CTRL_2_MASK_CH0_A_MASK (0x10000UL)
#define CCT_OUT_CTRL_2_MASK_CH0_A_SHIFT (16UL)
#define CCT_OUT_CTRL_1_MASK_CH3_B_MASK (0x8000UL)
#define CCT_OUT_CTRL_1_MASK_CH3_B_SHIFT (15UL)
#define CCT_OUT_CTRL_1_MASK_CH3_A_MASK (0x4000UL)
#define CCT_OUT_CTRL_1_MASK_CH3_A_SHIFT (14UL)
#define CCT_OUT_CTRL_1_MASK_CH2_B_MASK (0x2000UL)
#define CCT_OUT_CTRL_1_MASK_CH2_B_SHIFT (13UL)
#define CCT_OUT_CTRL_1_MASK_CH2_A_MASK (0x1000UL)
#define CCT_OUT_CTRL_1_MASK_CH2_A_SHIFT (12UL)
#define CCT_OUT_CTRL_1_MASK_CH1_B_MASK (0x800UL)
#define CCT_OUT_CTRL_1_MASK_CH1_B_SHIFT (11UL)
#define CCT_OUT_CTRL_1_MASK_CH1_A_MASK (0x400UL)
#define CCT_OUT_CTRL_1_MASK_CH1_A_SHIFT (10UL)
#define CCT_OUT_CTRL_1_MASK_CH0_B_MASK (0x200UL)
#define CCT_OUT_CTRL_1_MASK_CH0_B_SHIFT (9UL)
#define CCT_OUT_CTRL_1_MASK_CH0_A_MASK (0x100UL)
#define CCT_OUT_CTRL_1_MASK_CH0_A_SHIFT (8UL)
#define CCT_OUT_CTRL_0_MASK_CH3_B_MASK (0x80UL)
#define CCT_OUT_CTRL_0_MASK_CH3_B_SHIFT (7UL)
#define CCT_OUT_CTRL_0_MASK_CH3_A_MASK (0x40UL)
#define CCT_OUT_CTRL_0_MASK_CH3_A_SHIFT (6UL)
#define CCT_OUT_CTRL_0_MASK_CH2_B_MASK (0x20UL)
#define CCT_OUT_CTRL_0_MASK_CH2_B_SHIFT (5UL)
#define CCT_OUT_CTRL_0_MASK_CH2_A_MASK (0x10UL)
#define CCT_OUT_CTRL_0_MASK_CH2_A_SHIFT (4UL)
#define CCT_OUT_CTRL_0_MASK_CH1_B_MASK (0x8UL)
#define CCT_OUT_CTRL_0_MASK_CH1_B_SHIFT (3UL)
#define CCT_OUT_CTRL_0_MASK_CH1_A_MASK (0x4UL)
#define CCT_OUT_CTRL_0_MASK_CH1_A_SHIFT (2UL)
#define CCT_OUT_CTRL_0_MASK_CH0_B_MASK (0x2UL)
#define CCT_OUT_CTRL_0_MASK_CH0_B_SHIFT (1UL)
#define CCT_OUT_CTRL_0_MASK_CH0_A_MASK (0x1UL)
#define CCT_OUT_CTRL_0_MASK_CH0_A_SHIFT (0UL)




typedef uint32_t CCT_INP_CTRL_TYPE;
#define CCT_INP_CTRL_FILTER_EN_IN3_MASK (0x1000UL)
#define CCT_INP_CTRL_FILTER_EN_IN3_SHIFT (12UL)
#define CCT_INP_CTRL_FILTER_EN_IN2_MASK (0x800UL)
#define CCT_INP_CTRL_FILTER_EN_IN2_SHIFT (11UL)
#define CCT_INP_CTRL_FILTER_EN_IN1_MASK (0x400UL)
#define CCT_INP_CTRL_FILTER_EN_IN1_SHIFT (10UL)
#define CCT_INP_CTRL_FILTER_EN_IN0_MASK (0x200UL)
#define CCT_INP_CTRL_FILTER_EN_IN0_SHIFT (9UL)
#define CCT_INP_CTRL_FILTER_EN_ETR_MASK (0x100UL)
#define CCT_INP_CTRL_FILTER_EN_ETR_SHIFT (8UL)
#define CCT_INP_CTRL_SYNC_EN_IN3_MASK (0x10UL)
#define CCT_INP_CTRL_SYNC_EN_IN3_SHIFT (4UL)
#define CCT_INP_CTRL_SYNC_EN_IN2_MASK (0x8UL)
#define CCT_INP_CTRL_SYNC_EN_IN2_SHIFT (3UL)
#define CCT_INP_CTRL_SYNC_EN_IN1_MASK (0x4UL)
#define CCT_INP_CTRL_SYNC_EN_IN1_SHIFT (2UL)
#define CCT_INP_CTRL_SYNC_EN_IN0_MASK (0x2UL)
#define CCT_INP_CTRL_SYNC_EN_IN0_SHIFT (1UL)
#define CCT_INP_CTRL_SYNC_EN_ETR_MASK (0x1UL)
#define CCT_INP_CTRL_SYNC_EN_ETR_SHIFT (0UL)




typedef uint32_t CCT_IRQ_CTRL_TYPE;
#define CCT_IRQ_CTRL_ETR_FE_IRQ_EN_MASK (0x400UL)
#define CCT_IRQ_CTRL_ETR_FE_IRQ_EN_SHIFT (10UL)
#define CCT_IRQ_CTRL_ETR_RE_IRQ_EN_MASK (0x200UL)
#define CCT_IRQ_CTRL_ETR_RE_IRQ_EN_SHIFT (9UL)
#define CCT_IRQ_CTRL_UDC_IRQ_EN_MASK (0x100UL)
#define CCT_IRQ_CTRL_UDC_IRQ_EN_SHIFT (8UL)
#define CCT_IRQ_CTRL_CCR3_B_IRQ_EN_MASK (0x80UL)
#define CCT_IRQ_CTRL_CCR3_B_IRQ_EN_SHIFT (7UL)
#define CCT_IRQ_CTRL_CCR3_A_IRQ_EN_MASK (0x40UL)
#define CCT_IRQ_CTRL_CCR3_A_IRQ_EN_SHIFT (6UL)
#define CCT_IRQ_CTRL_CCR2_B_IRQ_EN_MASK (0x20UL)
#define CCT_IRQ_CTRL_CCR2_B_IRQ_EN_SHIFT (5UL)
#define CCT_IRQ_CTRL_CCR2_A_IRQ_EN_MASK (0x10UL)
#define CCT_IRQ_CTRL_CCR2_A_IRQ_EN_SHIFT (4UL)
#define CCT_IRQ_CTRL_CCR1_B_IRQ_EN_MASK (0x8UL)
#define CCT_IRQ_CTRL_CCR1_B_IRQ_EN_SHIFT (3UL)
#define CCT_IRQ_CTRL_CCR1_A_IRQ_EN_MASK (0x4UL)
#define CCT_IRQ_CTRL_CCR1_A_IRQ_EN_SHIFT (2UL)
#define CCT_IRQ_CTRL_CCR0_B_IRQ_EN_MASK (0x2UL)
#define CCT_IRQ_CTRL_CCR0_B_IRQ_EN_SHIFT (1UL)
#define CCT_IRQ_CTRL_CCR0_A_IRQ_EN_MASK (0x1UL)
#define CCT_IRQ_CTRL_CCR0_A_IRQ_EN_SHIFT (0UL)




typedef uint32_t CCT_IRQ_STAT_TYPE;
#define CCT_IRQ_STAT_ETR_FE_IRQ_STAT_MASK (0x400UL)
#define CCT_IRQ_STAT_ETR_FE_IRQ_STAT_SHIFT (10UL)
#define CCT_IRQ_STAT_ETR_RE_IRQ_STAT_MASK (0x200UL)
#define CCT_IRQ_STAT_ETR_RE_IRQ_STAT_SHIFT (9UL)
#define CCT_IRQ_STAT_UDC_IRQ_STAT_MASK (0x100UL)
#define CCT_IRQ_STAT_UDC_IRQ_STAT_SHIFT (8UL)
#define CCT_IRQ_STAT_CCR3_B_IRQ_STAT_MASK (0x80UL)
#define CCT_IRQ_STAT_CCR3_B_IRQ_STAT_SHIFT (7UL)
#define CCT_IRQ_STAT_CCR3_A_IRQ_STAT_MASK (0x40UL)
#define CCT_IRQ_STAT_CCR3_A_IRQ_STAT_SHIFT (6UL)
#define CCT_IRQ_STAT_CCR2_B_IRQ_STAT_MASK (0x20UL)
#define CCT_IRQ_STAT_CCR2_B_IRQ_STAT_SHIFT (5UL)
#define CCT_IRQ_STAT_CCR2_A_IRQ_STAT_MASK (0x10UL)
#define CCT_IRQ_STAT_CCR2_A_IRQ_STAT_SHIFT (4UL)
#define CCT_IRQ_STAT_CCR1_B_IRQ_STAT_MASK (0x8UL)
#define CCT_IRQ_STAT_CCR1_B_IRQ_STAT_SHIFT (3UL)
#define CCT_IRQ_STAT_CCR1_A_IRQ_STAT_MASK (0x4UL)
#define CCT_IRQ_STAT_CCR1_A_IRQ_STAT_SHIFT (2UL)
#define CCT_IRQ_STAT_CCR0_B_IRQ_STAT_MASK (0x2UL)
#define CCT_IRQ_STAT_CCR0_B_IRQ_STAT_SHIFT (1UL)
#define CCT_IRQ_STAT_CCR0_A_IRQ_STAT_MASK (0x1UL)
#define CCT_IRQ_STAT_CCR0_A_IRQ_STAT_SHIFT (0UL)




typedef uint8_t CCT_RESERVED_TYPE;


typedef volatile struct sCCT_CCR_RDBType {
    CCT_CCR_VAL_TYPE ccr0_val; /* OFFSET: 0x18 */
    CCT_CCR_CTRL_TYPE ccr0_ctrl; /* OFFSET: 0x1c */
    CCT_CCR_INPUT_PSC_TYPE ccr0_input_psc; /* OFFSET: 0x20 */
    CCT_CCR_TRIG_TYPE ccr0_trig; /* OFFSET: 0x24 */
} CCT_CCR_RDBType;


#define CCT_CCR_REGS_SIZE  (4UL)


typedef volatile struct sCCT_RDBType {
    CCT_CTRLA_TYPE ctrla; /* OFFSET: 0x0 */
    CCT_PSC_RATIO_TYPE psc_ratio; /* OFFSET: 0x4 */
    CCT_PSC_TRIG_TYPE psc_trig; /* OFFSET: 0x8 */
    CCT_PSC_CTRL_TYPE psc_ctrl; /* OFFSET: 0xc */
    CCT_UDC_CTRL_TYPE udc_ctrl; /* OFFSET: 0x10 */
    CCT_UDC_TRIG_TYPE udc_trig; /* OFFSET: 0x14 */
    CCT_CCR_RDBType cct_ccr_regs[CCT_CCR_REGS_SIZE]; /* OFFSET: 0x18 */
    CCT_OUT_CTRL_TYPE out_ctrl; /* OFFSET: 0x58 */
    CCT_INP_CTRL_TYPE inp_ctrl; /* OFFSET: 0x5c */
    CCT_IRQ_CTRL_TYPE irq_ctrl; /* OFFSET: 0x60 */
    CCT_IRQ_STAT_TYPE irq_stat; /* OFFSET: 0x64 */
    CCT_RESERVED_TYPE rsvd0[3976]; /* OFFSET: 0x68 */
    CCT_RESERVED_TYPE reserved[4]; /* OFFSET: 0xff0 */
} CCT_RDBType;


#define CAPCOM_0_BASE                   (0xE0620000UL)

#define CCT_CCR_RDBTYPE_CAPCOM_0_OFFSET  (0xE0620018UL)

#define CAPCOM_1_BASE                   (0xE0621000UL)

#define CCT_CCR_RDBTYPE_CAPCOM_1_OFFSET  (0xE0621018UL)



#define CCT_MAX_HW_ID                   (2UL)


#define CCT_MAX_CHAN_CNT                (4UL)

#endif /* CCT_RDB_H */
