/*****************************************************************************
 Copyright 2025 Broadcom Corporation.  All rights reserved.

 Broadcom Proprietary and Confidential
******************************************************************************/
/**
    @file bspi_rdb.h
    @brief RDB File for BSPI

    @version BCM89580_A0_20230125_RDB
*/

#ifndef BSPI_RDB_H
#define BSPI_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t BSPI_BSPIS_REVISION_ID_TYPE;
#define BSPI_BSPIS_REVISION_ID_REGISTERS_MAJOR_MASK (0xff00UL)
#define BSPI_BSPIS_REVISION_ID_REGISTERS_MAJOR_SHIFT (8UL)
#define BSPI_BSPIS_REVISION_ID_REGISTERS_MINOR_MASK (0xffUL)
#define BSPI_BSPIS_REVISION_ID_REGISTERS_MINOR_SHIFT (0UL)




typedef uint32_t BSPI_BSPIS_SCRATCH_TYPE;
#define BSPI_BSPIS_SCRATCH_REGISTERS_MASK (0xffffffffUL)
#define BSPI_BSPIS_SCRATCH_REGISTERS_SHIFT (0UL)




typedef uint32_t BSPI_BMNBC_TYPE;
#define BSPI_BMNBC_BSPI_REGISTERS_MAST_N_BOOT_CTRL_SLAVE_SEL_MASK (0xe0UL)
#define BSPI_BMNBC_BSPI_REGISTERS_MAST_N_BOOT_CTRL_SLAVE_SEL_SHIFT (5UL)
#define BSPI_BMNBC_BRMNBCAGF_MASK (0x1cUL)
#define BSPI_BMNBC_BRMNBCAGF_SHIFT (2UL)
#define BSPI_BMNBC_BSPI_REGISTERS_MAST_N_BOOT_CTRL_ARB_GRANT_FRC_MASK (0x2UL)
#define BSPI_BMNBC_BSPI_REGISTERS_MAST_N_BOOT_CTRL_ARB_GRANT_FRC_SHIFT (1UL)
#define BSPI_BMNBC_BSPI_REGISTERS_MAST_N_BOOT_CTRL_MAST_N_BOOT_MASK (0x1UL)
#define BSPI_BMNBC_BSPI_REGISTERS_MAST_N_BOOT_CTRL_MAST_N_BOOT_SHIFT (0UL)




typedef uint32_t BSPI_BSPIS_BUSY_STATUS_TYPE;
#define BSPI_BSPIS_BUSY_STATUS_REGISTERS_MASK (0x1UL)
#define BSPI_BSPIS_BUSY_STATUS_REGISTERS_SHIFT (0UL)




typedef uint32_t BSPI_BSPIS_INTR_STATUS_TYPE;
#define BSPI_BSPIS_INTR_STATUS_REGISTERS_5_MASK (0x20UL)
#define BSPI_BSPIS_INTR_STATUS_REGISTERS_5_SHIFT (5UL)
#define BSPI_BSPIS_INTR_STATUS_REGISTERS_4_MASK (0x10UL)
#define BSPI_BSPIS_INTR_STATUS_REGISTERS_4_SHIFT (4UL)
#define BSPI_BSPIS_INTR_STATUS_REGISTERS_3_MASK (0x8UL)
#define BSPI_BSPIS_INTR_STATUS_REGISTERS_3_SHIFT (3UL)
#define BSPI_BSPIS_INTR_STATUS_REGISTERS_2_MASK (0x4UL)
#define BSPI_BSPIS_INTR_STATUS_REGISTERS_2_SHIFT (2UL)
#define BSPI_BSPIS_INTR_STATUS_REGISTERS_1_MASK (0x2UL)
#define BSPI_BSPIS_INTR_STATUS_REGISTERS_1_SHIFT (1UL)
#define BSPI_BSPIS_INTR_STATUS_REGISTERS_0_MASK (0x1UL)
#define BSPI_BSPIS_INTR_STATUS_REGISTERS_0_SHIFT (0UL)




typedef uint32_t BSPI_B0_STAT_TYPE;
#define BSPI_B0_STAT_BRB0SB0PA_MASK (0x40000000UL)
#define BSPI_B0_STAT_BRB0SB0PA_SHIFT (30UL)
#define BSPI_B0_STAT_BSPI_REGISTERS_B0_STATUS_B0_FULL_MASK (0x20000000UL)
#define BSPI_B0_STAT_BSPI_REGISTERS_B0_STATUS_B0_FULL_SHIFT (29UL)
#define BSPI_B0_STAT_BSPI_REGISTERS_B0_STATUS_B0_EMPTY_MASK (0x10000000UL)
#define BSPI_B0_STAT_BSPI_REGISTERS_B0_STATUS_B0_EMPTY_SHIFT (28UL)
#define BSPI_B0_STAT_BSPI_REGISTERS_B0_STATUS_B0_MISS_MASK (0x8000000UL)
#define BSPI_B0_STAT_BSPI_REGISTERS_B0_STATUS_B0_MISS_SHIFT (27UL)
#define BSPI_B0_STAT_BSPI_REGISTERS_B0_STATUS_B0_HIT_MASK (0x4000000UL)
#define BSPI_B0_STAT_BSPI_REGISTERS_B0_STATUS_B0_HIT_SHIFT (26UL)
#define BSPI_B0_STAT_BSPI_REGISTERS_B0_STATUS_B0_ADDRESS_MASK (0x3ffffffUL)
#define BSPI_B0_STAT_BSPI_REGISTERS_B0_STATUS_B0_ADDRESS_SHIFT (0UL)




typedef uint32_t BSPI_BSPIS_B0_CTRL_TYPE;
#define BSPI_BSPIS_B0_CTRL_REGISTERS_FLUSH_MASK (0x1UL)
#define BSPI_BSPIS_B0_CTRL_REGISTERS_FLUSH_SHIFT (0UL)




typedef uint32_t BSPI_B1_STAT_TYPE;
#define BSPI_B1_STAT_BRB1SB1PA_MASK (0x40000000UL)
#define BSPI_B1_STAT_BRB1SB1PA_SHIFT (30UL)
#define BSPI_B1_STAT_BSPI_REGISTERS_B1_STATUS_B1_FULL_MASK (0x20000000UL)
#define BSPI_B1_STAT_BSPI_REGISTERS_B1_STATUS_B1_FULL_SHIFT (29UL)
#define BSPI_B1_STAT_BSPI_REGISTERS_B1_STATUS_B1_EMPTY_MASK (0x10000000UL)
#define BSPI_B1_STAT_BSPI_REGISTERS_B1_STATUS_B1_EMPTY_SHIFT (28UL)
#define BSPI_B1_STAT_BSPI_REGISTERS_B1_STATUS_B1_MISS_MASK (0x8000000UL)
#define BSPI_B1_STAT_BSPI_REGISTERS_B1_STATUS_B1_MISS_SHIFT (27UL)
#define BSPI_B1_STAT_BSPI_REGISTERS_B1_STATUS_B1_HIT_MASK (0x4000000UL)
#define BSPI_B1_STAT_BSPI_REGISTERS_B1_STATUS_B1_HIT_SHIFT (26UL)
#define BSPI_B1_STAT_BSPI_REGISTERS_B1_STATUS_B1_ADDRESS_MASK (0x3ffffffUL)
#define BSPI_B1_STAT_BSPI_REGISTERS_B1_STATUS_B1_ADDRESS_SHIFT (0UL)




typedef uint32_t BSPI_BSPIS_B1_CTRL_TYPE;
#define BSPI_BSPIS_B1_CTRL_REGISTERS_FLUSH_MASK (0x1UL)
#define BSPI_BSPIS_B1_CTRL_REGISTERS_FLUSH_SHIFT (0UL)




typedef uint32_t BSPI_BSOC_TYPE;
#define BSPI_BSOC_BSPI_REGISTERS_STRAP_OVERRIDE_CTRL_ENDIAN_MODE_MASK (0x10UL)
#define BSPI_BSOC_BSPI_REGISTERS_STRAP_OVERRIDE_CTRL_ENDIAN_MODE_SHIFT (4UL)
#define BSPI_BSOC_BSPI_REGISTERS_STRAP_OVERRIDE_CTRL_DATA_QUAD_MASK (0x8UL)
#define BSPI_BSOC_BSPI_REGISTERS_STRAP_OVERRIDE_CTRL_DATA_QUAD_SHIFT (3UL)
#define BSPI_BSOC_BRSOCA4N3_MASK (0x4UL)
#define BSPI_BSOC_BRSOCA4N3_SHIFT (2UL)
#define BSPI_BSOC_BRSOCDDNS_MASK (0x2UL)
#define BSPI_BSOC_BRSOCDDNS_SHIFT (1UL)
#define BSPI_BSOC_BSPI_REGISTERS_STRAP_OVERRIDE_CTRL_OVERRIDE_MASK (0x1UL)
#define BSPI_BSOC_BSPI_REGISTERS_STRAP_OVERRIDE_CTRL_OVERRIDE_SHIFT (0UL)




typedef uint32_t BSPI_BFME_TYPE;
#define BSPI_BFME_BRFMEBFME_MASK (0x1UL)
#define BSPI_BFME_BRFMEBFME_SHIFT (0UL)




typedef uint32_t BSPI_BBPC_TYPE;
#define BSPI_BBPC_BRBPCBRBPCR5_MASK (0xfc000000UL)
#define BSPI_BBPC_BRBPCBRBPCR5_SHIFT (26UL)
#define BSPI_BBPC_BSPI_REGISTERS_BITS_PER_CYCLE_CMD_BPC_SELECT_MASK (0x3000000UL)
#define BSPI_BBPC_BSPI_REGISTERS_BITS_PER_CYCLE_CMD_BPC_SELECT_SHIFT (24UL)
#define BSPI_BBPC_BRBPCBRBPCR4_MASK (0xfc0000UL)
#define BSPI_BBPC_BRBPCBRBPCR4_SHIFT (18UL)
#define BSPI_BBPC_BSPI_REGISTERS_BITS_PER_CYCLE_ADDR_BPC_SELECT_MASK (0x30000UL)
#define BSPI_BBPC_BSPI_REGISTERS_BITS_PER_CYCLE_ADDR_BPC_SELECT_SHIFT (16UL)
#define BSPI_BBPC_BRBPCBRBPCR3_MASK (0xfc00UL)
#define BSPI_BBPC_BRBPCBRBPCR3_SHIFT (10UL)
#define BSPI_BBPC_BSPI_REGISTERS_BITS_PER_CYCLE_MODE_BPC_SELECT_MASK (0x300UL)
#define BSPI_BBPC_BSPI_REGISTERS_BITS_PER_CYCLE_MODE_BPC_SELECT_SHIFT (8UL)
#define BSPI_BBPC_BSPI_REGISTERS_BITS_PER_CYCLE_DATA_BPC_SELECT_MASK (0x3UL)
#define BSPI_BBPC_BSPI_REGISTERS_BITS_PER_CYCLE_DATA_BPC_SELECT_SHIFT (0UL)




typedef uint32_t BSPI_BBPP_TYPE;
#define BSPI_BBPP_BRBPPBRBPPR5_MASK (0xfe000000UL)
#define BSPI_BBPP_BRBPPBRBPPR5_SHIFT (25UL)
#define BSPI_BBPP_BSPI_REGISTERS_BITS_PER_PHASE_CMD_BPP_SELECT_MASK (0x1000000UL)
#define BSPI_BBPP_BSPI_REGISTERS_BITS_PER_PHASE_CMD_BPP_SELECT_SHIFT (24UL)
#define BSPI_BBPP_BRBPPBRBPPR4_MASK (0xfe0000UL)
#define BSPI_BBPP_BRBPPBRBPPR4_SHIFT (17UL)
#define BSPI_BBPP_BSPI_REGISTERS_BITS_PER_PHASE_ADDR_BPP_SELECT_MASK (0x10000UL)
#define BSPI_BBPP_BSPI_REGISTERS_BITS_PER_PHASE_ADDR_BPP_SELECT_SHIFT (16UL)
#define BSPI_BBPP_BSPI_REGISTERS_BITS_PER_PHASE_MODE_BPP_MASK (0x100UL)
#define BSPI_BBPP_BSPI_REGISTERS_BITS_PER_PHASE_MODE_BPP_SHIFT (8UL)
#define BSPI_BBPP_BSPI_REGISTERS_BITS_PER_PHASE_DUMMY_CYCLES_MASK (0xffUL)
#define BSPI_BBPP_BSPI_REGISTERS_BITS_PER_PHASE_DUMMY_CYCLES_SHIFT (0UL)




typedef uint32_t BSPI_BCAMB_TYPE;
#define BSPI_BCAMB_BRCAMBBRCAMBR3_MASK (0xff000000UL)
#define BSPI_BCAMB_BRCAMBBRCAMBR3_SHIFT (24UL)
#define BSPI_BCAMB_BRCAMBBMB_MASK (0xff0000UL)
#define BSPI_BCAMB_BRCAMBBMB_SHIFT (16UL)
#define BSPI_BCAMB_BSPI_REGISTERS_CMD_AND_MODE_BYTE_BSPI_CMD_BYTE_MASK (0xffUL)
#define BSPI_BCAMB_BSPI_REGISTERS_CMD_AND_MODE_BYTE_BSPI_CMD_BYTE_SHIFT (0UL)




typedef uint32_t BSPI_BBFUAB_TYPE;
#define BSPI_BBFUAB_BRBFUABBFUA_MASK (0xff000000UL)
#define BSPI_BBFUAB_BRBFUABBFUA_SHIFT (24UL)




typedef uint32_t BSPI_BBXV_TYPE;
#define BSPI_BBXV_REGISTERS_XOR_VALUE_XOR_VALUE_MASK (0xfff00000UL)
#define BSPI_BBXV_REGISTERS_XOR_VALUE_XOR_VALUE_SHIFT (20UL)




typedef uint32_t BSPI_BBXE_TYPE;
#define BSPI_BBXE_REGISTERS_XOR_ENABLE_XOR_ENABLE_MASK (0x1UL)
#define BSPI_BBXE_REGISTERS_XOR_ENABLE_XOR_ENABLE_SHIFT (0UL)




typedef uint32_t BSPI_BBPME_TYPE;
#define BSPI_BBPME_BRBPMEBPM_MASK (0x1UL)
#define BSPI_BBPME_BRBPMEBPM_SHIFT (0UL)




typedef uint32_t BSPI_BBPI_TYPE;
#define BSPI_BBPI_REGISTERS_PIO_IODIR_PIO_DIR_MASK (0x7UL)
#define BSPI_BBPI_REGISTERS_PIO_IODIR_PIO_DIR_SHIFT (0UL)




typedef uint32_t BSPI_BBPD_TYPE;
#define BSPI_BBPD_REGISTERS_PIO_DATA_PIO_DATA_MASK (0x7UL)
#define BSPI_BBPD_REGISTERS_PIO_DATA_PIO_DATA_SHIFT (0UL)




typedef uint8_t BSPI_RESERVED_TYPE;




typedef uint32_t BSPI_RAF_START_ADDR_TYPE;
#define BSPI_RAF_START_ADDR_MASK (0xffffffffUL)
#define BSPI_RAF_START_ADDR_SHIFT (0UL)




typedef uint32_t BSPI_RAF_NUM_WORDS_TYPE;
#define BSPI_RAF_NUM_WORDS_NUMWORDS_MASK (0xffffffffUL)
#define BSPI_RAF_NUM_WORDS_NUMWORDS_SHIFT (0UL)




typedef uint32_t BSPI_RAF_CTRL_TYPE;
#define BSPI_RAF_CTRL_CLEAR_MASK (0x2UL)
#define BSPI_RAF_CTRL_CLEAR_SHIFT (1UL)
#define BSPI_RAF_CTRL_START_MASK (0x1UL)
#define BSPI_RAF_CTRL_START_SHIFT (0UL)




typedef uint32_t BSPI_RAF_FULLNESS_TYPE;
#define BSPI_RAF_FULLNESS_MASK (0x7fUL)
#define BSPI_RAF_FULLNESS_SHIFT (0UL)




typedef uint32_t BSPI_RAF_WATERMARK_TYPE;
#define BSPI_RAF_WATERMARK_FULLNESS_MASK (0x3UL)
#define BSPI_RAF_WATERMARK_FULLNESS_SHIFT (0UL)




typedef uint32_t BSPI_RAF_STATUS_TYPE;
#define BSPI_RAF_STATUS_FIFO_FULL_MASK (0x4UL)
#define BSPI_RAF_STATUS_FIFO_FULL_SHIFT (2UL)
#define BSPI_RAF_STATUS_FIFO_EMPTY_MASK (0x2UL)
#define BSPI_RAF_STATUS_FIFO_EMPTY_SHIFT (1UL)
#define BSPI_RAF_STATUS_SESSION_BUSY_MASK (0x1UL)
#define BSPI_RAF_STATUS_SESSION_BUSY_SHIFT (0UL)




typedef uint32_t BSPI_RAF_READ_DATA_TYPE;
#define BSPI_RAF_READ_DATA_MASK (0xffffffffUL)
#define BSPI_RAF_READ_DATA_SHIFT (0UL)




typedef uint32_t BSPI_RAF_WORD_CNT_TYPE;
#define BSPI_RAF_WORD_CNT_CURRENT_COUNT_MASK (0xffffffffUL)
#define BSPI_RAF_WORD_CNT_CURRENT_COUNT_SHIFT (0UL)




typedef uint32_t BSPI_RAF_CURR_ADDR_TYPE;
#define BSPI_RAF_CURR_ADDR_CURRENT_ADDRESS_MASK (0xffffffffUL)
#define BSPI_RAF_CURR_ADDR_CURRENT_ADDRESS_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_SPCR0_LSB_TYPE;
#define BSPI_MSPI_SPCR0_LSB_SPBR_MASK (0xffUL)
#define BSPI_MSPI_SPCR0_LSB_SPBR_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_SPCR0_MSB_TYPE;
#define BSPI_MSPI_SPCR0_MSB_MSTR_MASK (0x80UL)
#define BSPI_MSPI_SPCR0_MSB_MSTR_SHIFT (7UL)
#define BSPI_MSPI_SPCR0_MSB_STARTTRANSDELAY_MASK (0x40UL)
#define BSPI_MSPI_SPCR0_MSB_STARTTRANSDELAY_SHIFT (6UL)
#define BSPI_MSPI_SPCR0_MSB_BITS_MASK (0x3cUL)
#define BSPI_MSPI_SPCR0_MSB_BITS_SHIFT (2UL)
#define BSPI_MSPI_SPCR0_MSB_CPOL_MASK (0x2UL)
#define BSPI_MSPI_SPCR0_MSB_CPOL_SHIFT (1UL)
#define BSPI_MSPI_SPCR0_MSB_CPHA_MASK (0x1UL)
#define BSPI_MSPI_SPCR0_MSB_CPHA_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_SPCR1_LSB_TYPE;
#define BSPI_MSPI_SPCR1_LSB_DTL_MASK (0xffUL)
#define BSPI_MSPI_SPCR1_LSB_DTL_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_SPCR1_MSB_TYPE;
#define BSPI_MSPI_SPCR1_MSB_RDSCLK_MASK (0xffUL)
#define BSPI_MSPI_SPCR1_MSB_RDSCLK_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_NEWQP_TYPE;
#define BSPI_MSPI_NEWQP_MASK (0xfUL)
#define BSPI_MSPI_NEWQP_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_ENDQP_TYPE;
#define BSPI_MSPI_ENDQP_MASK (0xfUL)
#define BSPI_MSPI_ENDQP_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_SPCR2_TYPE;
#define BSPI_MSPI_SPCR2_CONT_AFTER_CMD_MASK (0x80UL)
#define BSPI_MSPI_SPCR2_CONT_AFTER_CMD_SHIFT (7UL)
#define BSPI_MSPI_SPCR2_SPE_MASK (0x40UL)
#define BSPI_MSPI_SPCR2_SPE_SHIFT (6UL)
#define BSPI_MSPI_SPCR2_SPIFIE_MASK (0x20UL)
#define BSPI_MSPI_SPCR2_SPIFIE_SHIFT (5UL)
#define BSPI_MSPI_SPCR2_WREN_MASK (0x10UL)
#define BSPI_MSPI_SPCR2_WREN_SHIFT (4UL)
#define BSPI_MSPI_SPCR2_WRT0_MASK (0x8UL)
#define BSPI_MSPI_SPCR2_WRT0_SHIFT (3UL)
#define BSPI_MSPI_SPCR2_LOOPQ_MASK (0x4UL)
#define BSPI_MSPI_SPCR2_LOOPQ_SHIFT (2UL)
#define BSPI_MSPI_SPCR2_HIE_MASK (0x2UL)
#define BSPI_MSPI_SPCR2_HIE_SHIFT (1UL)
#define BSPI_MSPI_SPCR2_HALT_MASK (0x1UL)
#define BSPI_MSPI_SPCR2_HALT_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_MSPI_STATUS_TYPE;
#define BSPI_MSPI_MSPI_STATUS_HALTA_MASK (0x2UL)
#define BSPI_MSPI_MSPI_STATUS_HALTA_SHIFT (1UL)
#define BSPI_MSPI_MSPI_STATUS_SPIF_MASK (0x1UL)
#define BSPI_MSPI_MSPI_STATUS_SPIF_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_CPTQP_TYPE;
#define BSPI_MSPI_CPTQP_MASK (0xfUL)
#define BSPI_MSPI_CPTQP_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_TXRAM00_TYPE;
#define BSPI_MSPI_TXRAM00_TXRAM_MASK (0xffUL)
#define BSPI_MSPI_TXRAM00_TXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_TXRAM01_TYPE;
#define BSPI_MSPI_TXRAM01_TXRAM_MASK (0xffUL)
#define BSPI_MSPI_TXRAM01_TXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_TXRAM02_TYPE;
#define BSPI_MSPI_TXRAM02_TXRAM_MASK (0xffUL)
#define BSPI_MSPI_TXRAM02_TXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_TXRAM03_TYPE;
#define BSPI_MSPI_TXRAM03_TXRAM_MASK (0xffUL)
#define BSPI_MSPI_TXRAM03_TXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_TXRAM04_TYPE;
#define BSPI_MSPI_TXRAM04_TXRAM_MASK (0xffUL)
#define BSPI_MSPI_TXRAM04_TXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_TXRAM05_TYPE;
#define BSPI_MSPI_TXRAM05_TXRAM_MASK (0xffUL)
#define BSPI_MSPI_TXRAM05_TXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_TXRAM06_TYPE;
#define BSPI_MSPI_TXRAM06_TXRAM_MASK (0xffUL)
#define BSPI_MSPI_TXRAM06_TXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_TXRAM07_TYPE;
#define BSPI_MSPI_TXRAM07_TXRAM_MASK (0xffUL)
#define BSPI_MSPI_TXRAM07_TXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_TXRAM08_TYPE;
#define BSPI_MSPI_TXRAM08_TXRAM_MASK (0xffUL)
#define BSPI_MSPI_TXRAM08_TXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_TXRAM09_TYPE;
#define BSPI_MSPI_TXRAM09_TXRAM_MASK (0xffUL)
#define BSPI_MSPI_TXRAM09_TXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_TXRAM10_TYPE;
#define BSPI_MSPI_TXRAM10_TXRAM_MASK (0xffUL)
#define BSPI_MSPI_TXRAM10_TXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_TXRAM11_TYPE;
#define BSPI_MSPI_TXRAM11_TXRAM_MASK (0xffUL)
#define BSPI_MSPI_TXRAM11_TXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_TXRAM12_TYPE;
#define BSPI_MSPI_TXRAM12_TXRAM_MASK (0xffUL)
#define BSPI_MSPI_TXRAM12_TXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_TXRAM13_TYPE;
#define BSPI_MSPI_TXRAM13_TXRAM_MASK (0xffUL)
#define BSPI_MSPI_TXRAM13_TXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_TXRAM14_TYPE;
#define BSPI_MSPI_TXRAM14_TXRAM_MASK (0xffUL)
#define BSPI_MSPI_TXRAM14_TXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_TXRAM15_TYPE;
#define BSPI_MSPI_TXRAM15_TXRAM_MASK (0xffUL)
#define BSPI_MSPI_TXRAM15_TXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_TXRAM16_TYPE;
#define BSPI_MSPI_TXRAM16_TXRAM_MASK (0xffUL)
#define BSPI_MSPI_TXRAM16_TXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_TXRAM17_TYPE;
#define BSPI_MSPI_TXRAM17_TXRAM_MASK (0xffUL)
#define BSPI_MSPI_TXRAM17_TXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_TXRAM18_TYPE;
#define BSPI_MSPI_TXRAM18_TXRAM_MASK (0xffUL)
#define BSPI_MSPI_TXRAM18_TXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_TXRAM19_TYPE;
#define BSPI_MSPI_TXRAM19_TXRAM_MASK (0xffUL)
#define BSPI_MSPI_TXRAM19_TXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_TXRAM20_TYPE;
#define BSPI_MSPI_TXRAM20_TXRAM_MASK (0xffUL)
#define BSPI_MSPI_TXRAM20_TXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_TXRAM21_TYPE;
#define BSPI_MSPI_TXRAM21_TXRAM_MASK (0xffUL)
#define BSPI_MSPI_TXRAM21_TXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_TXRAM22_TYPE;
#define BSPI_MSPI_TXRAM22_TXRAM_MASK (0xffUL)
#define BSPI_MSPI_TXRAM22_TXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_TXRAM23_TYPE;
#define BSPI_MSPI_TXRAM23_TXRAM_MASK (0xffUL)
#define BSPI_MSPI_TXRAM23_TXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_TXRAM24_TYPE;
#define BSPI_MSPI_TXRAM24_TXRAM_MASK (0xffUL)
#define BSPI_MSPI_TXRAM24_TXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_TXRAM25_TYPE;
#define BSPI_MSPI_TXRAM25_TXRAM_MASK (0xffUL)
#define BSPI_MSPI_TXRAM25_TXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_TXRAM26_TYPE;
#define BSPI_MSPI_TXRAM26_TXRAM_MASK (0xffUL)
#define BSPI_MSPI_TXRAM26_TXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_TXRAM27_TYPE;
#define BSPI_MSPI_TXRAM27_TXRAM_MASK (0xffUL)
#define BSPI_MSPI_TXRAM27_TXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_TXRAM28_TYPE;
#define BSPI_MSPI_TXRAM28_TXRAM_MASK (0xffUL)
#define BSPI_MSPI_TXRAM28_TXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_TXRAM29_TYPE;
#define BSPI_MSPI_TXRAM29_TXRAM_MASK (0xffUL)
#define BSPI_MSPI_TXRAM29_TXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_TXRAM30_TYPE;
#define BSPI_MSPI_TXRAM30_TXRAM_MASK (0xffUL)
#define BSPI_MSPI_TXRAM30_TXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_TXRAM31_TYPE;
#define BSPI_MSPI_TXRAM31_TXRAM_MASK (0xffUL)
#define BSPI_MSPI_TXRAM31_TXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_RXRAM00_TYPE;
#define BSPI_MSPI_RXRAM00_RXRAM_MASK (0xffUL)
#define BSPI_MSPI_RXRAM00_RXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_RXRAM01_TYPE;
#define BSPI_MSPI_RXRAM01_RXRAM_MASK (0xffUL)
#define BSPI_MSPI_RXRAM01_RXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_RXRAM02_TYPE;
#define BSPI_MSPI_RXRAM02_RXRAM_MASK (0xffUL)
#define BSPI_MSPI_RXRAM02_RXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_RXRAM03_TYPE;
#define BSPI_MSPI_RXRAM03_RXRAM_MASK (0xffUL)
#define BSPI_MSPI_RXRAM03_RXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_RXRAM04_TYPE;
#define BSPI_MSPI_RXRAM04_RXRAM_MASK (0xffUL)
#define BSPI_MSPI_RXRAM04_RXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_RXRAM05_TYPE;
#define BSPI_MSPI_RXRAM05_RXRAM_MASK (0xffUL)
#define BSPI_MSPI_RXRAM05_RXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_RXRAM06_TYPE;
#define BSPI_MSPI_RXRAM06_RXRAM_MASK (0xffUL)
#define BSPI_MSPI_RXRAM06_RXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_RXRAM07_TYPE;
#define BSPI_MSPI_RXRAM07_RXRAM_MASK (0xffUL)
#define BSPI_MSPI_RXRAM07_RXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_RXRAM08_TYPE;
#define BSPI_MSPI_RXRAM08_RXRAM_MASK (0xffUL)
#define BSPI_MSPI_RXRAM08_RXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_RXRAM09_TYPE;
#define BSPI_MSPI_RXRAM09_RXRAM_MASK (0xffUL)
#define BSPI_MSPI_RXRAM09_RXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_RXRAM10_TYPE;
#define BSPI_MSPI_RXRAM10_RXRAM_MASK (0xffUL)
#define BSPI_MSPI_RXRAM10_RXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_RXRAM11_TYPE;
#define BSPI_MSPI_RXRAM11_RXRAM_MASK (0xffUL)
#define BSPI_MSPI_RXRAM11_RXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_RXRAM12_TYPE;
#define BSPI_MSPI_RXRAM12_RXRAM_MASK (0xffUL)
#define BSPI_MSPI_RXRAM12_RXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_RXRAM13_TYPE;
#define BSPI_MSPI_RXRAM13_RXRAM_MASK (0xffUL)
#define BSPI_MSPI_RXRAM13_RXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_RXRAM14_TYPE;
#define BSPI_MSPI_RXRAM14_RXRAM_MASK (0xffUL)
#define BSPI_MSPI_RXRAM14_RXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_RXRAM15_TYPE;
#define BSPI_MSPI_RXRAM15_RXRAM_MASK (0xffUL)
#define BSPI_MSPI_RXRAM15_RXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_RXRAM16_TYPE;
#define BSPI_MSPI_RXRAM16_RXRAM_MASK (0xffUL)
#define BSPI_MSPI_RXRAM16_RXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_RXRAM17_TYPE;
#define BSPI_MSPI_RXRAM17_RXRAM_MASK (0xffUL)
#define BSPI_MSPI_RXRAM17_RXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_RXRAM18_TYPE;
#define BSPI_MSPI_RXRAM18_RXRAM_MASK (0xffUL)
#define BSPI_MSPI_RXRAM18_RXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_RXRAM19_TYPE;
#define BSPI_MSPI_RXRAM19_RXRAM_MASK (0xffUL)
#define BSPI_MSPI_RXRAM19_RXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_RXRAM20_TYPE;
#define BSPI_MSPI_RXRAM20_RXRAM_MASK (0xffUL)
#define BSPI_MSPI_RXRAM20_RXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_RXRAM21_TYPE;
#define BSPI_MSPI_RXRAM21_RXRAM_MASK (0xffUL)
#define BSPI_MSPI_RXRAM21_RXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_RXRAM22_TYPE;
#define BSPI_MSPI_RXRAM22_RXRAM_MASK (0xffUL)
#define BSPI_MSPI_RXRAM22_RXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_RXRAM23_TYPE;
#define BSPI_MSPI_RXRAM23_RXRAM_MASK (0xffUL)
#define BSPI_MSPI_RXRAM23_RXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_RXRAM24_TYPE;
#define BSPI_MSPI_RXRAM24_RXRAM_MASK (0xffUL)
#define BSPI_MSPI_RXRAM24_RXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_RXRAM25_TYPE;
#define BSPI_MSPI_RXRAM25_RXRAM_MASK (0xffUL)
#define BSPI_MSPI_RXRAM25_RXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_RXRAM26_TYPE;
#define BSPI_MSPI_RXRAM26_RXRAM_MASK (0xffUL)
#define BSPI_MSPI_RXRAM26_RXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_RXRAM27_TYPE;
#define BSPI_MSPI_RXRAM27_RXRAM_MASK (0xffUL)
#define BSPI_MSPI_RXRAM27_RXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_RXRAM28_TYPE;
#define BSPI_MSPI_RXRAM28_RXRAM_MASK (0xffUL)
#define BSPI_MSPI_RXRAM28_RXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_RXRAM29_TYPE;
#define BSPI_MSPI_RXRAM29_RXRAM_MASK (0xffUL)
#define BSPI_MSPI_RXRAM29_RXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_RXRAM30_TYPE;
#define BSPI_MSPI_RXRAM30_RXRAM_MASK (0xffUL)
#define BSPI_MSPI_RXRAM30_RXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_RXRAM31_TYPE;
#define BSPI_MSPI_RXRAM31_RXRAM_MASK (0xffUL)
#define BSPI_MSPI_RXRAM31_RXRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_CDRAM00_TYPE;
#define BSPI_MSPI_CDRAM00_CDRAM_MASK (0xffUL)
#define BSPI_MSPI_CDRAM00_CDRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_CDRAM01_TYPE;
#define BSPI_MSPI_CDRAM01_CDRAM_MASK (0xffUL)
#define BSPI_MSPI_CDRAM01_CDRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_CDRAM02_TYPE;
#define BSPI_MSPI_CDRAM02_CDRAM_MASK (0xffUL)
#define BSPI_MSPI_CDRAM02_CDRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_CDRAM03_TYPE;
#define BSPI_MSPI_CDRAM03_CDRAM_MASK (0xffUL)
#define BSPI_MSPI_CDRAM03_CDRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_CDRAM04_TYPE;
#define BSPI_MSPI_CDRAM04_CDRAM_MASK (0xffUL)
#define BSPI_MSPI_CDRAM04_CDRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_CDRAM05_TYPE;
#define BSPI_MSPI_CDRAM05_CDRAM_MASK (0xffUL)
#define BSPI_MSPI_CDRAM05_CDRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_CDRAM06_TYPE;
#define BSPI_MSPI_CDRAM06_CDRAM_MASK (0xffUL)
#define BSPI_MSPI_CDRAM06_CDRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_CDRAM07_TYPE;
#define BSPI_MSPI_CDRAM07_CDRAM_MASK (0xffUL)
#define BSPI_MSPI_CDRAM07_CDRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_CDRAM08_TYPE;
#define BSPI_MSPI_CDRAM08_CDRAM_MASK (0xffUL)
#define BSPI_MSPI_CDRAM08_CDRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_CDRAM09_TYPE;
#define BSPI_MSPI_CDRAM09_CDRAM_MASK (0xffUL)
#define BSPI_MSPI_CDRAM09_CDRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_CDRAM10_TYPE;
#define BSPI_MSPI_CDRAM10_CDRAM_MASK (0xffUL)
#define BSPI_MSPI_CDRAM10_CDRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_CDRAM11_TYPE;
#define BSPI_MSPI_CDRAM11_CDRAM_MASK (0xffUL)
#define BSPI_MSPI_CDRAM11_CDRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_CDRAM12_TYPE;
#define BSPI_MSPI_CDRAM12_CDRAM_MASK (0xffUL)
#define BSPI_MSPI_CDRAM12_CDRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_CDRAM13_TYPE;
#define BSPI_MSPI_CDRAM13_CDRAM_MASK (0xffUL)
#define BSPI_MSPI_CDRAM13_CDRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_CDRAM14_TYPE;
#define BSPI_MSPI_CDRAM14_CDRAM_MASK (0xffUL)
#define BSPI_MSPI_CDRAM14_CDRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_CDRAM15_TYPE;
#define BSPI_MSPI_CDRAM15_CDRAM_MASK (0xffUL)
#define BSPI_MSPI_CDRAM15_CDRAM_SHIFT (0UL)




typedef uint32_t BSPI_MSPI_WRITE_LOCK_TYPE;
#define BSPI_MSPI_WRITE_LOCK_WRITELOCK_MASK (0x1UL)
#define BSPI_MSPI_WRITE_LOCK_WRITELOCK_SHIFT (0UL)




typedef uint32_t BSPI_MDFG_TYPE;
#define BSPI_MDFG_MSPI_DISABLE_FLUSH_GEN_DISABLEFLUSHGEN_MASK (0x1UL)
#define BSPI_MDFG_MSPI_DISABLE_FLUSH_GEN_DISABLEFLUSHGEN_SHIFT (0UL)




typedef uint32_t BSPI_RILFR_TYPE;
#define BSPI_RILFR_RILFRR1_MASK (0xfffffffeUL)
#define BSPI_RILFR_RILFRR1_SHIFT (1UL)
#define BSPI_RILFR_SLFR_MASK (0x1UL)
#define BSPI_RILFR_SLFR_SHIFT (0UL)




typedef uint32_t BSPI_RILT_TYPE;
#define BSPI_RILT_RILTRILTR1_MASK (0xfffffffeUL)
#define BSPI_RILT_RILTRILTR1_SHIFT (1UL)
#define BSPI_RILT_RAF_INTERRUPT_LR_TRUNCATED_SPI_LR_TRUNCATED_MASK (0x1UL)
#define BSPI_RILT_RAF_INTERRUPT_LR_TRUNCATED_SPI_LR_TRUNCATED_SHIFT (0UL)




typedef uint32_t BSPI_RILI_TYPE;
#define BSPI_RILI_RILIRILIR1_MASK (0xfffffffeUL)
#define BSPI_RILI_RILIRILIR1_SHIFT (1UL)
#define BSPI_RILI_RAF_INTERRUPT_LR_IMPATIENT_SPI_LR_IMPATIENT_MASK (0x1UL)
#define BSPI_RILI_RAF_INTERRUPT_LR_IMPATIENT_SPI_LR_IMPATIENT_SHIFT (0UL)




typedef uint32_t BSPI_RILSD_TYPE;
#define BSPI_RILSD_RILSDR1_MASK (0xfffffffeUL)
#define BSPI_RILSD_RILSDR1_SHIFT (1UL)
#define BSPI_RILSD_SLSD_MASK (0x1UL)
#define BSPI_RILSD_SLSD_SHIFT (0UL)




typedef uint32_t BSPI_RILO_TYPE;
#define BSPI_RILO_RILORILOR1_MASK (0xfffffffeUL)
#define BSPI_RILO_RILORILOR1_SHIFT (1UL)
#define BSPI_RILO_RAF_INTERRUPT_LR_OVERREAD_SPI_LR_OVERREAD_MASK (0x1UL)
#define BSPI_RILO_RAF_INTERRUPT_LR_OVERREAD_SPI_LR_OVERREAD_SHIFT (0UL)




typedef uint32_t BSPI_MIMD_TYPE;
#define BSPI_MIMD_MIMDMIMDR1_MASK (0xfffffffeUL)
#define BSPI_MIMD_MIMDMIMDR1_SHIFT (1UL)
#define BSPI_MIMD_MSPI_INTERRUPT_MSPI_DONE_MSPI_DONE_MASK (0x1UL)
#define BSPI_MIMD_MSPI_INTERRUPT_MSPI_DONE_MSPI_DONE_SHIFT (0UL)




typedef uint32_t BSPI_MIMHSTD_TYPE;
#define BSPI_MIMHSTD_MIMHSTDMIMHSTDR1_MASK (0xfffffffeUL)
#define BSPI_MIMHSTD_MIMHSTDMIMHSTDR1_SHIFT (1UL)
#define BSPI_MIMHSTD_MIMHSTDMHSTD_MASK (0x1UL)
#define BSPI_MIMHSTD_MIMHSTDMHSTD_SHIFT (0UL)




typedef volatile struct sBSPI_RDBType {
    BSPI_BSPIS_REVISION_ID_TYPE bspi_registers_revision_id; /* OFFSET: 0x0 */
    BSPI_BSPIS_SCRATCH_TYPE bspi_registers_scratch; /* OFFSET: 0x4 */
    BSPI_BMNBC_TYPE bspi_registers_mast_n_boot_ctrl; /* OFFSET: 0x8 */
    BSPI_BSPIS_BUSY_STATUS_TYPE bspi_registers_busy_status; /* OFFSET: 0xc */
    BSPI_BSPIS_INTR_STATUS_TYPE bspi_registers_intr_status; /* OFFSET: 0x10 */
    BSPI_B0_STAT_TYPE bspi_registers_b0_status; /* OFFSET: 0x14 */
    BSPI_BSPIS_B0_CTRL_TYPE bspi_registers_b0_ctrl; /* OFFSET: 0x18 */
    BSPI_B1_STAT_TYPE bspi_registers_b1_status; /* OFFSET: 0x1c */
    BSPI_BSPIS_B1_CTRL_TYPE bspi_registers_b1_ctrl; /* OFFSET: 0x20 */
    BSPI_BSOC_TYPE bspi_registers_strap_override_ctrl; /* OFFSET: 0x24 */
    BSPI_BFME_TYPE bspi_registers_flex_mode_enable; /* OFFSET: 0x28 */
    BSPI_BBPC_TYPE bspi_registers_bits_per_cycle; /* OFFSET: 0x2c */
    BSPI_BBPP_TYPE bspi_registers_bits_per_phase; /* OFFSET: 0x30 */
    BSPI_BCAMB_TYPE bspi_registers_cmd_and_mode_byte; /* OFFSET: 0x34 */
    BSPI_BBFUAB_TYPE bspi_registers_bspi_flash_upper_addr_byte; /* OFFSET: 0x38 */
    BSPI_BBXV_TYPE bspi_registers_bspi_xor_value; /* OFFSET: 0x3c */
    BSPI_BBXE_TYPE bspi_registers_bspi_xor_enable; /* OFFSET: 0x40 */
    BSPI_BBPME_TYPE bspi_registers_bspi_pio_mode_enable; /* OFFSET: 0x44 */
    BSPI_BBPI_TYPE bspi_registers_bspi_pio_iodir; /* OFFSET: 0x48 */
    BSPI_BBPD_TYPE bspi_registers_bspi_pio_data; /* OFFSET: 0x4c */
    BSPI_RESERVED_TYPE rsvd0[176]; /* OFFSET: 0x50 */
    BSPI_RAF_START_ADDR_TYPE raf_start_addr; /* OFFSET: 0x100 */
    BSPI_RAF_NUM_WORDS_TYPE raf_num_words; /* OFFSET: 0x104 */
    BSPI_RAF_CTRL_TYPE raf_ctrl; /* OFFSET: 0x108 */
    BSPI_RAF_FULLNESS_TYPE raf_fullness; /* OFFSET: 0x10c */
    BSPI_RAF_WATERMARK_TYPE raf_watermark; /* OFFSET: 0x110 */
    BSPI_RAF_STATUS_TYPE raf_status; /* OFFSET: 0x114 */
    BSPI_RAF_READ_DATA_TYPE raf_read_data; /* OFFSET: 0x118 */
    BSPI_RAF_WORD_CNT_TYPE raf_word_cnt; /* OFFSET: 0x11c */
    BSPI_RAF_CURR_ADDR_TYPE raf_curr_addr; /* OFFSET: 0x120 */
    BSPI_RESERVED_TYPE rsvd1[220]; /* OFFSET: 0x124 */
    BSPI_MSPI_SPCR0_LSB_TYPE mspi_spcr0_lsb; /* OFFSET: 0x200 */
    BSPI_MSPI_SPCR0_MSB_TYPE mspi_spcr0_msb; /* OFFSET: 0x204 */
    BSPI_MSPI_SPCR1_LSB_TYPE mspi_spcr1_lsb; /* OFFSET: 0x208 */
    BSPI_MSPI_SPCR1_MSB_TYPE mspi_spcr1_msb; /* OFFSET: 0x20c */
    BSPI_MSPI_NEWQP_TYPE mspi_newqp; /* OFFSET: 0x210 */
    BSPI_MSPI_ENDQP_TYPE mspi_endqp; /* OFFSET: 0x214 */
    BSPI_MSPI_SPCR2_TYPE mspi_spcr2; /* OFFSET: 0x218 */
    BSPI_RESERVED_TYPE rsvd2[4]; /* OFFSET: 0x21c */
    BSPI_MSPI_MSPI_STATUS_TYPE mspi_mspi_status; /* OFFSET: 0x220 */
    BSPI_MSPI_CPTQP_TYPE mspi_cptqp; /* OFFSET: 0x224 */
    BSPI_RESERVED_TYPE rsvd3[24]; /* OFFSET: 0x228 */
    BSPI_MSPI_TXRAM00_TYPE mspi_txram00; /* OFFSET: 0x240 */
    BSPI_MSPI_TXRAM01_TYPE mspi_txram01; /* OFFSET: 0x244 */
    BSPI_MSPI_TXRAM02_TYPE mspi_txram02; /* OFFSET: 0x248 */
    BSPI_MSPI_TXRAM03_TYPE mspi_txram03; /* OFFSET: 0x24c */
    BSPI_MSPI_TXRAM04_TYPE mspi_txram04; /* OFFSET: 0x250 */
    BSPI_MSPI_TXRAM05_TYPE mspi_txram05; /* OFFSET: 0x254 */
    BSPI_MSPI_TXRAM06_TYPE mspi_txram06; /* OFFSET: 0x258 */
    BSPI_MSPI_TXRAM07_TYPE mspi_txram07; /* OFFSET: 0x25c */
    BSPI_MSPI_TXRAM08_TYPE mspi_txram08; /* OFFSET: 0x260 */
    BSPI_MSPI_TXRAM09_TYPE mspi_txram09; /* OFFSET: 0x264 */
    BSPI_MSPI_TXRAM10_TYPE mspi_txram10; /* OFFSET: 0x268 */
    BSPI_MSPI_TXRAM11_TYPE mspi_txram11; /* OFFSET: 0x26c */
    BSPI_MSPI_TXRAM12_TYPE mspi_txram12; /* OFFSET: 0x270 */
    BSPI_MSPI_TXRAM13_TYPE mspi_txram13; /* OFFSET: 0x274 */
    BSPI_MSPI_TXRAM14_TYPE mspi_txram14; /* OFFSET: 0x278 */
    BSPI_MSPI_TXRAM15_TYPE mspi_txram15; /* OFFSET: 0x27c */
    BSPI_MSPI_TXRAM16_TYPE mspi_txram16; /* OFFSET: 0x280 */
    BSPI_MSPI_TXRAM17_TYPE mspi_txram17; /* OFFSET: 0x284 */
    BSPI_MSPI_TXRAM18_TYPE mspi_txram18; /* OFFSET: 0x288 */
    BSPI_MSPI_TXRAM19_TYPE mspi_txram19; /* OFFSET: 0x28c */
    BSPI_MSPI_TXRAM20_TYPE mspi_txram20; /* OFFSET: 0x290 */
    BSPI_MSPI_TXRAM21_TYPE mspi_txram21; /* OFFSET: 0x294 */
    BSPI_MSPI_TXRAM22_TYPE mspi_txram22; /* OFFSET: 0x298 */
    BSPI_MSPI_TXRAM23_TYPE mspi_txram23; /* OFFSET: 0x29c */
    BSPI_MSPI_TXRAM24_TYPE mspi_txram24; /* OFFSET: 0x2a0 */
    BSPI_MSPI_TXRAM25_TYPE mspi_txram25; /* OFFSET: 0x2a4 */
    BSPI_MSPI_TXRAM26_TYPE mspi_txram26; /* OFFSET: 0x2a8 */
    BSPI_MSPI_TXRAM27_TYPE mspi_txram27; /* OFFSET: 0x2ac */
    BSPI_MSPI_TXRAM28_TYPE mspi_txram28; /* OFFSET: 0x2b0 */
    BSPI_MSPI_TXRAM29_TYPE mspi_txram29; /* OFFSET: 0x2b4 */
    BSPI_MSPI_TXRAM30_TYPE mspi_txram30; /* OFFSET: 0x2b8 */
    BSPI_MSPI_TXRAM31_TYPE mspi_txram31; /* OFFSET: 0x2bc */
    BSPI_MSPI_RXRAM00_TYPE mspi_rxram00; /* OFFSET: 0x2c0 */
    BSPI_MSPI_RXRAM01_TYPE mspi_rxram01; /* OFFSET: 0x2c4 */
    BSPI_MSPI_RXRAM02_TYPE mspi_rxram02; /* OFFSET: 0x2c8 */
    BSPI_MSPI_RXRAM03_TYPE mspi_rxram03; /* OFFSET: 0x2cc */
    BSPI_MSPI_RXRAM04_TYPE mspi_rxram04; /* OFFSET: 0x2d0 */
    BSPI_MSPI_RXRAM05_TYPE mspi_rxram05; /* OFFSET: 0x2d4 */
    BSPI_MSPI_RXRAM06_TYPE mspi_rxram06; /* OFFSET: 0x2d8 */
    BSPI_MSPI_RXRAM07_TYPE mspi_rxram07; /* OFFSET: 0x2dc */
    BSPI_MSPI_RXRAM08_TYPE mspi_rxram08; /* OFFSET: 0x2e0 */
    BSPI_MSPI_RXRAM09_TYPE mspi_rxram09; /* OFFSET: 0x2e4 */
    BSPI_MSPI_RXRAM10_TYPE mspi_rxram10; /* OFFSET: 0x2e8 */
    BSPI_MSPI_RXRAM11_TYPE mspi_rxram11; /* OFFSET: 0x2ec */
    BSPI_MSPI_RXRAM12_TYPE mspi_rxram12; /* OFFSET: 0x2f0 */
    BSPI_MSPI_RXRAM13_TYPE mspi_rxram13; /* OFFSET: 0x2f4 */
    BSPI_MSPI_RXRAM14_TYPE mspi_rxram14; /* OFFSET: 0x2f8 */
    BSPI_MSPI_RXRAM15_TYPE mspi_rxram15; /* OFFSET: 0x2fc */
    BSPI_MSPI_RXRAM16_TYPE mspi_rxram16; /* OFFSET: 0x300 */
    BSPI_MSPI_RXRAM17_TYPE mspi_rxram17; /* OFFSET: 0x304 */
    BSPI_MSPI_RXRAM18_TYPE mspi_rxram18; /* OFFSET: 0x308 */
    BSPI_MSPI_RXRAM19_TYPE mspi_rxram19; /* OFFSET: 0x30c */
    BSPI_MSPI_RXRAM20_TYPE mspi_rxram20; /* OFFSET: 0x310 */
    BSPI_MSPI_RXRAM21_TYPE mspi_rxram21; /* OFFSET: 0x314 */
    BSPI_MSPI_RXRAM22_TYPE mspi_rxram22; /* OFFSET: 0x318 */
    BSPI_MSPI_RXRAM23_TYPE mspi_rxram23; /* OFFSET: 0x31c */
    BSPI_MSPI_RXRAM24_TYPE mspi_rxram24; /* OFFSET: 0x320 */
    BSPI_MSPI_RXRAM25_TYPE mspi_rxram25; /* OFFSET: 0x324 */
    BSPI_MSPI_RXRAM26_TYPE mspi_rxram26; /* OFFSET: 0x328 */
    BSPI_MSPI_RXRAM27_TYPE mspi_rxram27; /* OFFSET: 0x32c */
    BSPI_MSPI_RXRAM28_TYPE mspi_rxram28; /* OFFSET: 0x330 */
    BSPI_MSPI_RXRAM29_TYPE mspi_rxram29; /* OFFSET: 0x334 */
    BSPI_MSPI_RXRAM30_TYPE mspi_rxram30; /* OFFSET: 0x338 */
    BSPI_MSPI_RXRAM31_TYPE mspi_rxram31; /* OFFSET: 0x33c */
    BSPI_MSPI_CDRAM00_TYPE mspi_cdram00; /* OFFSET: 0x340 */
    BSPI_MSPI_CDRAM01_TYPE mspi_cdram01; /* OFFSET: 0x344 */
    BSPI_MSPI_CDRAM02_TYPE mspi_cdram02; /* OFFSET: 0x348 */
    BSPI_MSPI_CDRAM03_TYPE mspi_cdram03; /* OFFSET: 0x34c */
    BSPI_MSPI_CDRAM04_TYPE mspi_cdram04; /* OFFSET: 0x350 */
    BSPI_MSPI_CDRAM05_TYPE mspi_cdram05; /* OFFSET: 0x354 */
    BSPI_MSPI_CDRAM06_TYPE mspi_cdram06; /* OFFSET: 0x358 */
    BSPI_MSPI_CDRAM07_TYPE mspi_cdram07; /* OFFSET: 0x35c */
    BSPI_MSPI_CDRAM08_TYPE mspi_cdram08; /* OFFSET: 0x360 */
    BSPI_MSPI_CDRAM09_TYPE mspi_cdram09; /* OFFSET: 0x364 */
    BSPI_MSPI_CDRAM10_TYPE mspi_cdram10; /* OFFSET: 0x368 */
    BSPI_MSPI_CDRAM11_TYPE mspi_cdram11; /* OFFSET: 0x36c */
    BSPI_MSPI_CDRAM12_TYPE mspi_cdram12; /* OFFSET: 0x370 */
    BSPI_MSPI_CDRAM13_TYPE mspi_cdram13; /* OFFSET: 0x374 */
    BSPI_MSPI_CDRAM14_TYPE mspi_cdram14; /* OFFSET: 0x378 */
    BSPI_MSPI_CDRAM15_TYPE mspi_cdram15; /* OFFSET: 0x37c */
    BSPI_MSPI_WRITE_LOCK_TYPE mspi_write_lock; /* OFFSET: 0x380 */
    BSPI_MDFG_TYPE mspi_disable_flush_gen; /* OFFSET: 0x384 */
    BSPI_RESERVED_TYPE rsvd4[24]; /* OFFSET: 0x388 */
    BSPI_RILFR_TYPE raf_interrupt_lr_fullness_reached; /* OFFSET: 0x3a0 */
    BSPI_RILT_TYPE raf_interrupt_lr_truncated; /* OFFSET: 0x3a4 */
    BSPI_RILI_TYPE raf_interrupt_lr_impatient; /* OFFSET: 0x3a8 */
    BSPI_RILSD_TYPE raf_interrupt_lr_session_done; /* OFFSET: 0x3ac */
    BSPI_RILO_TYPE raf_interrupt_lr_overread; /* OFFSET: 0x3b0 */
    BSPI_MIMD_TYPE mspi_interrupt_mspi_done; /* OFFSET: 0x3b4 */
    BSPI_MIMHSTD_TYPE mspi_interrupt_mspi_halt_set_transaction_done; /* OFFSET: 0x3b8 */
} BSPI_RDBType;


#define FLASH_BSPI_BASE                 (0x1024A000UL)



#define BSPI_MAX_HW_ID                  (1UL)

#endif /* BSPI_RDB_H */
