/*****************************************************************************
 Copyright 2024 Broadcom Corporation.  All rights reserved.

 Broadcom Proprietary and Confidential
******************************************************************************/
/**
    @file qspi_rdb.h
    @brief RDB File for QSPI

    @version BCM89580_A0_20230125_RDB
*/

#ifndef QSPI_RDB_H
#define QSPI_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t QSPI_CTRL0_ADDR_TYPE;
#define QSPI_CTRL0_ADDR_VAL_MASK (0xffffffffUL)
#define QSPI_CTRL0_ADDR_VAL_SHIFT (0UL)




typedef uint32_t QSPI_CTRL1_MODEBITS_TYPE;
#define QSPI_CTRL1_MODEBITS_VAL_MASK (0xffffffffUL)
#define QSPI_CTRL1_MODEBITS_VAL_SHIFT (0UL)




typedef uint32_t QSPI_CTRL2_DATA_LEN_TYPE;
#define QSPI_CTRL2_DATA_LEN_MASK (0xffffffffUL)
#define QSPI_CTRL2_DATA_LEN_SHIFT (0UL)




typedef uint32_t QSPI_CTRL3_CONFIG_TYPE;
#define QSPI_CTRL3_CONFIG_START_SPI_MASK (0x80000000UL)
#define QSPI_CTRL3_CONFIG_START_SPI_SHIFT (31UL)
#define QSPI_CTRL3_CONFIG_WRITE_READ_N_MASK (0x40000000UL)
#define QSPI_CTRL3_CONFIG_WRITE_READ_N_SHIFT (30UL)
#define QSPI_CTRL3_CONFIG_SLAVE_SEL_MASK (0x38000000UL)
#define QSPI_CTRL3_CONFIG_SLAVE_SEL_SHIFT (27UL)
#define QSPI_CTRL3_CONFIG_RX_FSMNOTRANSIT_EN_MASK (0x2000000UL)
#define QSPI_CTRL3_CONFIG_RX_FSMNOTRANSIT_EN_SHIFT (25UL)
#define QSPI_CTRL3_CONFIG_ARBITER_IF_EN_MASK (0x1000000UL)
#define QSPI_CTRL3_CONFIG_ARBITER_IF_EN_SHIFT (24UL)
#define QSPI_CTRL3_CONFIG_DUMMY_LEN_MASK (0xf00000UL)
#define QSPI_CTRL3_CONFIG_DUMMY_LEN_SHIFT (20UL)
#define QSPI_CTRL3_CONFIG_DATA_MODE_MASK (0xc0000UL)
#define QSPI_CTRL3_CONFIG_DATA_MODE_SHIFT (18UL)
#define QSPI_CTRL3_CONFIG_MODEBITS_LEN_MASK (0x30000UL)
#define QSPI_CTRL3_CONFIG_MODEBITS_LEN_SHIFT (16UL)
#define QSPI_CTRL3_CONFIG_MODEBITS_MODE_MASK (0xc000UL)
#define QSPI_CTRL3_CONFIG_MODEBITS_MODE_SHIFT (14UL)
#define QSPI_CTRL3_CONFIG_ADDR_LEN_MASK (0x3000UL)
#define QSPI_CTRL3_CONFIG_ADDR_LEN_SHIFT (12UL)
#define QSPI_CTRL3_CONFIG_ADDR_MODE_MASK (0xc00UL)
#define QSPI_CTRL3_CONFIG_ADDR_MODE_SHIFT (10UL)
#define QSPI_CTRL3_CONFIG_OPCODE_MODE_MASK (0x300UL)
#define QSPI_CTRL3_CONFIG_OPCODE_MODE_SHIFT (8UL)
#define QSPI_CTRL3_CONFIG_OPCODE_VAL_MASK (0xffUL)
#define QSPI_CTRL3_CONFIG_OPCODE_VAL_SHIFT (0UL)




typedef uint32_t QSPI_CTRL4_CONFIG_TYPE;
#define QSPI_CTRL4_CONFIG_FDX_MODE_MASK (0x80000000UL)
#define QSPI_CTRL4_CONFIG_FDX_MODE_SHIFT (31UL)
#define QSPI_CTRL4_CONFIG_TXDMAENABLE_MASK (0x40000000UL)
#define QSPI_CTRL4_CONFIG_TXDMAENABLE_SHIFT (30UL)
#define QSPI_CTRL4_CONFIG_TXFIFOFLUSH_MASK (0x20000000UL)
#define QSPI_CTRL4_CONFIG_TXFIFOFLUSH_SHIFT (29UL)
#define QSPI_CTRL4_CONFIG_TXFIFOTHRESH_MASK (0x1f000000UL)
#define QSPI_CTRL4_CONFIG_TXFIFOTHRESH_SHIFT (24UL)
#define QSPI_CTRL4_CONFIG_RXDMAENABLE_MASK (0x800000UL)
#define QSPI_CTRL4_CONFIG_RXDMAENABLE_SHIFT (23UL)
#define QSPI_CTRL4_CONFIG_RXFIFOWORDALIGN_MASK (0x400000UL)
#define QSPI_CTRL4_CONFIG_RXFIFOWORDALIGN_SHIFT (22UL)
#define QSPI_CTRL4_CONFIG_RXFIFOFLUSH_MASK (0x200000UL)
#define QSPI_CTRL4_CONFIG_RXFIFOFLUSH_SHIFT (21UL)
#define QSPI_CTRL4_CONFIG_RXFIFOTHRESH_MASK (0x1f0000UL)
#define QSPI_CTRL4_CONFIG_RXFIFOTHRESH_SHIFT (16UL)
#define QSPI_CTRL4_CONFIG_HOLDOFF_LEN_MASK (0xf000UL)
#define QSPI_CTRL4_CONFIG_HOLDOFF_LEN_SHIFT (12UL)
#define QSPI_CTRL4_CONFIG_RXFIFO_WAIT_EN_MASK (0x800UL)
#define QSPI_CTRL4_CONFIG_RXFIFO_WAIT_EN_SHIFT (11UL)
#define QSPI_CTRL4_CONFIG_TXFIFO_WAIT_EN_MASK (0x400UL)
#define QSPI_CTRL4_CONFIG_TXFIFO_WAIT_EN_SHIFT (10UL)
#define QSPI_CTRL4_CONFIG_CLOCK_DIV_MASK (0x3f0UL)
#define QSPI_CTRL4_CONFIG_CLOCK_DIV_SHIFT (4UL)
#define QSPI_CTRL4_CONFIG_DDR_MODE_MASK (0x8UL)
#define QSPI_CTRL4_CONFIG_DDR_MODE_SHIFT (3UL)
#define QSPI_CTRL4_CONFIG_CPOL_CPHA_CTRL_MASK (0x6UL)
#define QSPI_CTRL4_CONFIG_CPOL_CPHA_CTRL_SHIFT (1UL)
#define QSPI_CTRL4_CONFIG_SPI_ENABLE_MASK (0x1UL)
#define QSPI_CTRL4_CONFIG_SPI_ENABLE_SHIFT (0UL)




typedef uint32_t QSPI_CTRL5_CONFIG_TYPE;
#define QSPI_CTRL5_CONFIG_SPI_TRANS_REPEAT_MASK (0xff000000UL)
#define QSPI_CTRL5_CONFIG_SPI_TRANS_REPEAT_SHIFT (24UL)
#define QSPI_CTRL5_CONFIG_CSB_HIGH_LEN_MASK (0xff0000UL)
#define QSPI_CTRL5_CONFIG_CSB_HIGH_LEN_SHIFT (16UL)
#define QSPI_CTRL5_CONFIG_AUTO_POLL_SELFCLEAR_MASK (0x40UL)
#define QSPI_CTRL5_CONFIG_AUTO_POLL_SELFCLEAR_SHIFT (6UL)
#define QSPI_CTRL5_CONFIG_AUTO_POLL_MODE_MASK (0x20UL)
#define QSPI_CTRL5_CONFIG_AUTO_POLL_MODE_SHIFT (5UL)
#define QSPI_CTRL5_CONFIG_AUTO_POLL_ENABLE_MASK (0x10UL)
#define QSPI_CTRL5_CONFIG_AUTO_POLL_ENABLE_SHIFT (4UL)
#define QSPI_CTRL5_CONFIG_RXDLY_EN_MASK (0x8UL)
#define QSPI_CTRL5_CONFIG_RXDLY_EN_SHIFT (3UL)
#define QSPI_CTRL5_CONFIG_QUADMODE_EN_MASK (0x4UL)
#define QSPI_CTRL5_CONFIG_QUADMODE_EN_SHIFT (2UL)
#define QSPI_CTRL5_CONFIG_HOLDN_CTRL_MASK (0x2UL)
#define QSPI_CTRL5_CONFIG_HOLDN_CTRL_SHIFT (1UL)
#define QSPI_CTRL5_CONFIG_WPN_CTRL_MASK (0x1UL)
#define QSPI_CTRL5_CONFIG_WPN_CTRL_SHIFT (0UL)




typedef uint32_t QSPI_CTRL6_AUTOPOLLEXP_TYPE;
#define QSPI_CTRL6_AUTOPOLLEXP_AUTO_POLL_EXP_MASK (0xffffffffUL)
#define QSPI_CTRL6_AUTOPOLLEXP_AUTO_POLL_EXP_SHIFT (0UL)




typedef uint32_t QSPI_CTRL7_AUTOPOLLMASK_TYPE;
#define QSPI_CTRL7_AUTOPOLLMASK_AUTO_POLL_MASK_MASK (0xffffffffUL)
#define QSPI_CTRL7_AUTOPOLLMASK_AUTO_POLL_MASK_SHIFT (0UL)




typedef uint32_t QSPI_STAT_TYPE;
#define QSPI_STAT_TXFIFOUNDERFLOWSTAT_MASK (0x1000000UL)
#define QSPI_STAT_TXFIFOUNDERFLOWSTAT_SHIFT (24UL)
#define QSPI_STAT_TXFIFOTHRESHSTAT_MASK (0x800000UL)
#define QSPI_STAT_TXFIFOTHRESHSTAT_SHIFT (23UL)
#define QSPI_STAT_TXFIFOEMPTY_MASK (0x400000UL)
#define QSPI_STAT_TXFIFOEMPTY_SHIFT (22UL)
#define QSPI_STAT_TXFIFOFULLNESSSTAT_MASK (0x3f0000UL)
#define QSPI_STAT_TXFIFOFULLNESSSTAT_SHIFT (16UL)
#define QSPI_STAT_RXFIFOOVERFLOWSTAT_MASK (0x1000UL)
#define QSPI_STAT_RXFIFOOVERFLOWSTAT_SHIFT (12UL)
#define QSPI_STAT_RXFIFOTHRESHSTAT_MASK (0x800UL)
#define QSPI_STAT_RXFIFOTHRESHSTAT_SHIFT (11UL)
#define QSPI_STAT_RXFIFOEMPTY_MASK (0x400UL)
#define QSPI_STAT_RXFIFOEMPTY_SHIFT (10UL)
#define QSPI_STAT_RXFIFOFULLNESSSTAT_MASK (0x3f0UL)
#define QSPI_STAT_RXFIFOFULLNESSSTAT_SHIFT (4UL)
#define QSPI_STAT_BUSY_MASK (0x1UL)
#define QSPI_STAT_BUSY_SHIFT (0UL)




typedef uint32_t QSPI_INT_TYPE;
#define QSPI_INT_DONEINT_MASK (0x2000UL)
#define QSPI_INT_DONEINT_SHIFT (13UL)
#define QSPI_INT_AUTOPOLLINT_MASK (0x1000UL)
#define QSPI_INT_AUTOPOLLINT_SHIFT (12UL)
#define QSPI_INT_TXUNDERFLOWINT_MASK (0x800UL)
#define QSPI_INT_TXUNDERFLOWINT_SHIFT (11UL)
#define QSPI_INT_TXFULLINT_MASK (0x400UL)
#define QSPI_INT_TXFULLINT_SHIFT (10UL)
#define QSPI_INT_TXTHRESHINT_MASK (0x200UL)
#define QSPI_INT_TXTHRESHINT_SHIFT (9UL)
#define QSPI_INT_TXEMPTYINT_MASK (0x100UL)
#define QSPI_INT_TXEMPTYINT_SHIFT (8UL)
#define QSPI_INT_SAFETYTXOVRFLWINT_MASK (0x80UL)
#define QSPI_INT_SAFETYTXOVRFLWINT_SHIFT (7UL)
#define QSPI_INT_SAFETYTXUNDFLWINT_MASK (0x40UL)
#define QSPI_INT_SAFETYTXUNDFLWINT_SHIFT (6UL)
#define QSPI_INT_SAFETYRXOVRFLWINT_MASK (0x20UL)
#define QSPI_INT_SAFETYRXOVRFLWINT_SHIFT (5UL)
#define QSPI_INT_SAFETYRXUNDFLWINT_MASK (0x10UL)
#define QSPI_INT_SAFETYRXUNDFLWINT_SHIFT (4UL)
#define QSPI_INT_RXOVERFLOWINT_MASK (0x8UL)
#define QSPI_INT_RXOVERFLOWINT_SHIFT (3UL)
#define QSPI_INT_RXFULLINT_MASK (0x4UL)
#define QSPI_INT_RXFULLINT_SHIFT (2UL)
#define QSPI_INT_RXTHRESHINT_MASK (0x2UL)
#define QSPI_INT_RXTHRESHINT_SHIFT (1UL)
#define QSPI_INT_RXEMPTYINT_MASK (0x1UL)
#define QSPI_INT_RXEMPTYINT_SHIFT (0UL)




typedef uint32_t QSPI_INTMASK_TYPE;
#define QSPI_INTMASK_DONEMASK_MASK (0x2000UL)
#define QSPI_INTMASK_DONEMASK_SHIFT (13UL)
#define QSPI_INTMASK_AUTOPOLLMASK_MASK (0x1000UL)
#define QSPI_INTMASK_AUTOPOLLMASK_SHIFT (12UL)
#define QSPI_INTMASK_TXUNDERFLOWMASK_MASK (0x800UL)
#define QSPI_INTMASK_TXUNDERFLOWMASK_SHIFT (11UL)
#define QSPI_INTMASK_TXFULLMASK_MASK (0x400UL)
#define QSPI_INTMASK_TXFULLMASK_SHIFT (10UL)
#define QSPI_INTMASK_TXTHRESHMASK_MASK (0x200UL)
#define QSPI_INTMASK_TXTHRESHMASK_SHIFT (9UL)
#define QSPI_INTMASK_TXEMPTYMASK_MASK (0x100UL)
#define QSPI_INTMASK_TXEMPTYMASK_SHIFT (8UL)
#define QSPI_INTMASK_SAFETYTXOVRFLWMASK_MASK (0x80UL)
#define QSPI_INTMASK_SAFETYTXOVRFLWMASK_SHIFT (7UL)
#define QSPI_INTMASK_SAFETYTXUNDFLWMASK_MASK (0x40UL)
#define QSPI_INTMASK_SAFETYTXUNDFLWMASK_SHIFT (6UL)
#define QSPI_INTMASK_SAFETYRXOVRFLWMASK_MASK (0x20UL)
#define QSPI_INTMASK_SAFETYRXOVRFLWMASK_SHIFT (5UL)
#define QSPI_INTMASK_SAFETYRXUNDFLWMASK_MASK (0x10UL)
#define QSPI_INTMASK_SAFETYRXUNDFLWMASK_SHIFT (4UL)
#define QSPI_INTMASK_RXOVERFLOWMASK_MASK (0x8UL)
#define QSPI_INTMASK_RXOVERFLOWMASK_SHIFT (3UL)
#define QSPI_INTMASK_RXFULLMASK_MASK (0x4UL)
#define QSPI_INTMASK_RXFULLMASK_SHIFT (2UL)
#define QSPI_INTMASK_RXTHRESHMASK_MASK (0x2UL)
#define QSPI_INTMASK_RXTHRESHMASK_SHIFT (1UL)
#define QSPI_INTMASK_RXEMPTYMASK_MASK (0x1UL)
#define QSPI_INTMASK_RXEMPTYMASK_SHIFT (0UL)




typedef uint8_t QSPI_RESERVED_TYPE;




typedef uint32_t QSPI_DATAREG_TYPE;
#define QSPI_DATAREG_DATAREGISTER_MASK (0xffffffffUL)
#define QSPI_DATAREG_DATAREGISTER_SHIFT (0UL)




typedef uint32_t QSPI_CTRL8_CRCCTRLREG_TYPE;
#define QSPI_CTRL8_CRCCTRLREG_INCL_CRC_IN_STREAM_MASK (0x8000UL)
#define QSPI_CTRL8_CRCCTRLREG_INCL_CRC_IN_STREAM_SHIFT (15UL)
#define QSPI_CTRL8_CRCCTRLREG_REV_OUT_CTRL_MASK (0x1c00UL)
#define QSPI_CTRL8_CRCCTRLREG_REV_OUT_CTRL_SHIFT (10UL)
#define QSPI_CTRL8_CRCCTRLREG_REV_IN_CTRL_MASK (0x300UL)
#define QSPI_CTRL8_CRCCTRLREG_REV_IN_CTRL_SHIFT (8UL)
#define QSPI_CTRL8_CRCCTRLREG_RD_FRAME_CRC_MASK (0x4UL)
#define QSPI_CTRL8_CRCCTRLREG_RD_FRAME_CRC_SHIFT (2UL)
#define QSPI_CTRL8_CRCCTRLREG_CRC_ENABLE_MASK (0x2UL)
#define QSPI_CTRL8_CRCCTRLREG_CRC_ENABLE_SHIFT (1UL)
#define QSPI_CTRL8_CRCCTRLREG_CRC_RESET_MASK (0x1UL)
#define QSPI_CTRL8_CRCCTRLREG_CRC_RESET_SHIFT (0UL)




typedef uint32_t QSPI_CTRL9_CRC_INIT_VAL_TYPE;
#define QSPI_CTRL9_CRC_INIT_VAL_MASK (0xffffffffUL)
#define QSPI_CTRL9_CRC_INIT_VAL_SHIFT (0UL)




typedef uint32_t QSPI_CTRL10_CRC_XOR_VAL_TYPE;
#define QSPI_CTRL10_CRC_XOR_VAL_MASK (0xffffffffUL)
#define QSPI_CTRL10_CRC_XOR_VAL_SHIFT (0UL)




typedef uint32_t QSPI_RX_CRC_DATAREG_TYPE;
#define QSPI_RX_CRC_DATAREG_DATA_MASK (0xffffffffUL)
#define QSPI_RX_CRC_DATAREG_DATA_SHIFT (0UL)




typedef uint32_t QSPI_TX_CRC_DATAREG_TYPE;
#define QSPI_TX_CRC_DATAREG_DATA_MASK (0xffffffffUL)
#define QSPI_TX_CRC_DATAREG_DATA_SHIFT (0UL)




typedef uint32_t QSPI_CRC_RX_STATUS_TYPE;
#define QSPI_CRC_RX_STATUS_DONE_MASK (0x80000000UL)
#define QSPI_CRC_RX_STATUS_DONE_SHIFT (31UL)




typedef uint32_t QSPI_CRC_TX_STATUS_TYPE;
#define QSPI_CRC_TX_STATUS_DONE_MASK (0x80000000UL)
#define QSPI_CRC_TX_STATUS_DONE_SHIFT (31UL)




typedef volatile struct sQSPI_RDBType {
    QSPI_CTRL0_ADDR_TYPE ctrl0_addr; /* OFFSET: 0x0 */
    QSPI_CTRL1_MODEBITS_TYPE ctrl1_modebits; /* OFFSET: 0x4 */
    QSPI_CTRL2_DATA_LEN_TYPE ctrl2_data_len; /* OFFSET: 0x8 */
    QSPI_CTRL3_CONFIG_TYPE ctrl3_config; /* OFFSET: 0xc */
    QSPI_CTRL4_CONFIG_TYPE ctrl4_config; /* OFFSET: 0x10 */
    QSPI_CTRL5_CONFIG_TYPE ctrl5_config; /* OFFSET: 0x14 */
    QSPI_CTRL6_AUTOPOLLEXP_TYPE ctrl6_autopollexp; /* OFFSET: 0x18 */
    QSPI_CTRL7_AUTOPOLLMASK_TYPE ctrl7_autopollmask; /* OFFSET: 0x1c */
    QSPI_STAT_TYPE stat; /* OFFSET: 0x20 */
    QSPI_INT_TYPE intr; /* OFFSET: 0x24 */
    QSPI_INTMASK_TYPE intmask; /* OFFSET: 0x28 */
    QSPI_RESERVED_TYPE rsvd0[4]; /* OFFSET: 0x2c */
    QSPI_DATAREG_TYPE dataregister; /* OFFSET: 0x30 */
    QSPI_DATAREG_TYPE dataregister_alias1; /* OFFSET: 0x34 */
    QSPI_DATAREG_TYPE dataregister_alias2; /* OFFSET: 0x38 */
    QSPI_DATAREG_TYPE dataregister_alias3; /* OFFSET: 0x3c */
    QSPI_DATAREG_TYPE dataregister_alias4; /* OFFSET: 0x40 */
    QSPI_DATAREG_TYPE dataregister_alias5; /* OFFSET: 0x44 */
    QSPI_DATAREG_TYPE dataregister_alias6; /* OFFSET: 0x48 */
    QSPI_DATAREG_TYPE dataregister_alias7; /* OFFSET: 0x4c */
    QSPI_CTRL8_CRCCTRLREG_TYPE ctrl8_crcctrlreg; /* OFFSET: 0x50 */
    QSPI_CTRL9_CRC_INIT_VAL_TYPE ctrl9_crc_init_val; /* OFFSET: 0x54 */
    QSPI_CTRL10_CRC_XOR_VAL_TYPE ctrl10_crc_xor_val; /* OFFSET: 0x58 */
    QSPI_RX_CRC_DATAREG_TYPE rx_crc_datareg; /* OFFSET: 0x5c */
    QSPI_TX_CRC_DATAREG_TYPE tx_crc_datareg; /* OFFSET: 0x60 */
    QSPI_CRC_RX_STATUS_TYPE rx_crc_status; /* OFFSET: 0x64 */
    QSPI_CRC_TX_STATUS_TYPE tx_crc_status; /* OFFSET: 0x68 */
    QSPI_RESERVED_TYPE rsvd1[144]; /* OFFSET: 0x6c */
    QSPI_RESERVED_TYPE reserved_reg[4]; /* OFFSET: 0xfc */
} QSPI_RDBType;


#define QSPI0_BASE                      (0x10246000UL)

#define QSPI1_BASE                      (0x10247000UL)

#define QSPI2_BASE                      (0x10248000UL)

#define QSPI3_BASE                      (0x1024B000UL)



#define QSPI_MAX_HW_ID                  (4UL)

#endif /* QSPI_RDB_H */
