/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file txslzr_rdb.h
    @brief RDB File for TXSLZR

    @version BCM89580_A0_20230125_RDB
*/

#ifndef TXSLZR_RDB_H
#define TXSLZR_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t TXSLZR_CONTROL_TYPE;
#define TXSLZR_CONTROL_TX_EN_DYN_ELECIDLE_MASK (0x100UL)
#define TXSLZR_CONTROL_TX_EN_DYN_ELECIDLE_SHIFT (8UL)
#define TXSLZR_CONTROL_NUM_PAGES_MASK (0x70UL)
#define TXSLZR_CONTROL_NUM_PAGES_SHIFT (4UL)
#define TXSLZR_CONTROL_PG_EN_MASK (0x1UL)
#define TXSLZR_CONTROL_PG_EN_SHIFT (0UL)




typedef uint32_t TXSLZR_PAGE_SZ_0_TYPE;
#define TXSLZR_PAGE_SZ_0_3_MASK (0xff000000UL)
#define TXSLZR_PAGE_SZ_0_3_SHIFT (24UL)
#define TXSLZR_PAGE_SZ_0_2_MASK (0xff0000UL)
#define TXSLZR_PAGE_SZ_0_2_SHIFT (16UL)
#define TXSLZR_PAGE_SZ_0_1_MASK (0xff00UL)
#define TXSLZR_PAGE_SZ_0_1_SHIFT (8UL)
#define TXSLZR_PAGE_SZ_0_0_MASK (0xffUL)
#define TXSLZR_PAGE_SZ_0_0_SHIFT (0UL)




typedef uint8_t TXSLZR_RESERVED_TYPE;




typedef uint32_t TXSLZR_TPMIWC_TYPE;
#define TXSLZR_TPMIWC_PG_MEM_IND_WR_INCR_MODE_MASK (0x10000UL)
#define TXSLZR_TPMIWC_PG_MEM_IND_WR_INCR_MODE_SHIFT (16UL)
#define TXSLZR_TPMIWC_PG_MEM_IND_WR_ADDR_MASK (0xffUL)
#define TXSLZR_TPMIWC_PG_MEM_IND_WR_ADDR_SHIFT (0UL)




typedef uint32_t TXSLZR_PG_MEM_IND_WR_DATA_TYPE;
#define TXSLZR_PG_MEM_IND_WR_DATA_MASK (0xffffffffUL)
#define TXSLZR_PG_MEM_IND_WR_DATA_SHIFT (0UL)




typedef uint32_t TXSLZR_TPMIRC_TYPE;
#define TXSLZR_TPMIRC_PG_MEM_IND_RD_INCR_MODE_MASK (0x10000UL)
#define TXSLZR_TPMIRC_PG_MEM_IND_RD_INCR_MODE_SHIFT (16UL)
#define TXSLZR_TPMIRC_PG_MEM_IND_RD_ADDR_MASK (0xffUL)
#define TXSLZR_TPMIRC_PG_MEM_IND_RD_ADDR_SHIFT (0UL)




typedef uint32_t TXSLZR_PG_MEM_IND_RD_DATA_TYPE;
#define TXSLZR_PG_MEM_IND_RD_DATA_MASK (0xffffffffUL)
#define TXSLZR_PG_MEM_IND_RD_DATA_SHIFT (0UL)




typedef uint32_t TXSLZR_SEQ_CONTROL_TYPE;
#define TXSLZR_SEQ_CONTROL_RAMP_PERIOD_MASK (0xff000000UL)
#define TXSLZR_SEQ_CONTROL_RAMP_PERIOD_SHIFT (24UL)
#define TXSLZR_SEQ_CONTROL_SEQ_SPI_CFG_MASK (0x20UL)
#define TXSLZR_SEQ_CONTROL_SEQ_SPI_CFG_SHIFT (5UL)
#define TXSLZR_SEQ_CONTROL_CONT_MODE_MASK (0x10UL)
#define TXSLZR_SEQ_CONTROL_CONT_MODE_SHIFT (4UL)
#define TXSLZR_SEQ_CONTROL_SEQ_OUTPUT_CFG_MASK (0x2UL)
#define TXSLZR_SEQ_CONTROL_SEQ_OUTPUT_CFG_SHIFT (1UL)
#define TXSLZR_SEQ_CONTROL_SEQ_EN_MASK (0x1UL)
#define TXSLZR_SEQ_CONTROL_SEQ_EN_SHIFT (0UL)




typedef uint32_t TXSLZR_SEQ_MEM_IND_WR_CONTROL_TYPE;
#define TXSLZR_SEQ_MEM_IND_WR_CONTROL_INCR_MODE_MASK (0x10000UL)
#define TXSLZR_SEQ_MEM_IND_WR_CONTROL_INCR_MODE_SHIFT (16UL)
#define TXSLZR_SEQ_MEM_IND_WR_CONTROL_ADDR_MASK (0xffUL)
#define TXSLZR_SEQ_MEM_IND_WR_CONTROL_ADDR_SHIFT (0UL)




typedef uint32_t TXSLZR_SEQ_MEM_IND_WR_DATA_TYPE;
#define TXSLZR_SEQ_MEM_IND_WR_DATA_SPI_DATA_MASK (0xffff0000UL)
#define TXSLZR_SEQ_MEM_IND_WR_DATA_SPI_DATA_SHIFT (16UL)
#define TXSLZR_SEQ_MEM_IND_WR_DATA_RPT_CNT_MASK (0x7f0UL)
#define TXSLZR_SEQ_MEM_IND_WR_DATA_RPT_CNT_SHIFT (4UL)
#define TXSLZR_SEQ_MEM_IND_WR_DATA_END_FLAG_MASK (0x1UL)
#define TXSLZR_SEQ_MEM_IND_WR_DATA_END_FLAG_SHIFT (0UL)




typedef uint32_t TXSLZR_SEQ_MEM_IND_RD_CONTROL_TYPE;
#define TXSLZR_SEQ_MEM_IND_RD_CONTROL_INCR_MODE_MASK (0x10000UL)
#define TXSLZR_SEQ_MEM_IND_RD_CONTROL_INCR_MODE_SHIFT (16UL)
#define TXSLZR_SEQ_MEM_IND_RD_CONTROL_ADDR_MASK (0xffUL)
#define TXSLZR_SEQ_MEM_IND_RD_CONTROL_ADDR_SHIFT (0UL)




typedef uint32_t TXSLZR_SEQ_MEM_IND_RD_DATA_TYPE;
#define TXSLZR_SEQ_MEM_IND_RD_DATA_SPI_DATA_MASK (0xffff0000UL)
#define TXSLZR_SEQ_MEM_IND_RD_DATA_SPI_DATA_SHIFT (16UL)
#define TXSLZR_SEQ_MEM_IND_RD_DATA_RPT_CNT_MASK (0x7f0UL)
#define TXSLZR_SEQ_MEM_IND_RD_DATA_RPT_CNT_SHIFT (4UL)
#define TXSLZR_SEQ_MEM_IND_RD_DATA_END_FLAG_MASK (0x1UL)
#define TXSLZR_SEQ_MEM_IND_RD_DATA_END_FLAG_SHIFT (0UL)




typedef uint32_t TXSLZR_SEQ_SPI_CONTROL_TYPE;
#define TXSLZR_SEQ_SPI_CONTROL_SEQ_SPI_WAIT_TIME_MASK (0xffff0000UL)
#define TXSLZR_SEQ_SPI_CONTROL_SEQ_SPI_WAIT_TIME_SHIFT (16UL)
#define TXSLZR_SEQ_SPI_CONTROL_SPI_CLK_DIVIDER_MASK (0xff00UL)
#define TXSLZR_SEQ_SPI_CONTROL_SPI_CLK_DIVIDER_SHIFT (8UL)
#define TXSLZR_SEQ_SPI_CONTROL_SPI_CMD_SIZE_MASK (0x40UL)
#define TXSLZR_SEQ_SPI_CONTROL_SPI_CMD_SIZE_SHIFT (6UL)
#define TXSLZR_SEQ_SPI_CONTROL_SPI_CMD_CNT_MASK (0x10UL)
#define TXSLZR_SEQ_SPI_CONTROL_SPI_CMD_CNT_SHIFT (4UL)
#define TXSLZR_SEQ_SPI_CONTROL_SPI_CPOL_MASK (0x8UL)
#define TXSLZR_SEQ_SPI_CONTROL_SPI_CPOL_SHIFT (3UL)
#define TXSLZR_SEQ_SPI_CONTROL_SPI_CPHA_MASK (0x4UL)
#define TXSLZR_SEQ_SPI_CONTROL_SPI_CPHA_SHIFT (2UL)
#define TXSLZR_SEQ_SPI_CONTROL_SPI_SEQ_EN_MASK (0x1UL)
#define TXSLZR_SEQ_SPI_CONTROL_SPI_SEQ_EN_SHIFT (0UL)




typedef uint32_t TXSLZR_SEQ_SPI_SFT_CONTROL_TYPE;
#define TXSLZR_SEQ_SPI_SFT_CONTROL_RD_MASK (0x1000UL)
#define TXSLZR_SEQ_SPI_SFT_CONTROL_RD_SHIFT (12UL)
#define TXSLZR_SEQ_SPI_SFT_CONTROL_WR_MASK (0x100UL)
#define TXSLZR_SEQ_SPI_SFT_CONTROL_WR_SHIFT (8UL)
#define TXSLZR_SEQ_SPI_SFT_CONTROL_RD_CMD_CFG_MASK (0x10UL)
#define TXSLZR_SEQ_SPI_SFT_CONTROL_RD_CMD_CFG_SHIFT (4UL)
#define TXSLZR_SEQ_SPI_SFT_CONTROL_RD_RD_CFG_MASK (0x1UL)
#define TXSLZR_SEQ_SPI_SFT_CONTROL_RD_RD_CFG_SHIFT (0UL)




typedef uint32_t TXSLZR_SEQ_SFT_WR_DATA_TYPE;
#define TXSLZR_SEQ_SFT_WR_DATA_SPI_MASK (0xffffUL)
#define TXSLZR_SEQ_SFT_WR_DATA_SPI_SHIFT (0UL)




typedef uint32_t TXSLZR_SEQ_SFT_RD_DATA_TYPE;
#define TXSLZR_SEQ_SFT_RD_DATA_SPI_RD_DONE_MASK (0x80000000UL)
#define TXSLZR_SEQ_SFT_RD_DATA_SPI_RD_DONE_SHIFT (31UL)
#define TXSLZR_SEQ_SFT_RD_DATA_SPI_SFT_RD_DATA_MASK (0xffffUL)
#define TXSLZR_SEQ_SFT_RD_DATA_SPI_SFT_RD_DATA_SHIFT (0UL)




typedef uint32_t TXSLZR_SEQ_MISC_SPI_CONTROL_TYPE;
#define TXSLZR_SEQ_MISC_SPI_CONTROL_TURNAROUND_MASK (0xfUL)
#define TXSLZR_SEQ_MISC_SPI_CONTROL_TURNAROUND_SHIFT (0UL)




typedef uint32_t TXSLZR_SEQ_DBG0_TYPE;
#define TXSLZR_SEQ_DBG0_DBG_SPI_BUSY_STATE_MASK (0x1000000UL)
#define TXSLZR_SEQ_DBG0_DBG_SPI_BUSY_STATE_SHIFT (24UL)
#define TXSLZR_SEQ_DBG0_DBG_SPI_SM_SPISER_STATE_MASK (0x700000UL)
#define TXSLZR_SEQ_DBG0_DBG_SPI_SM_SPISER_STATE_SHIFT (20UL)
#define TXSLZR_SEQ_DBG0_DBG_SPI_SM_STATE_MASK (0x70000UL)
#define TXSLZR_SEQ_DBG0_DBG_SPI_SM_STATE_SHIFT (16UL)
#define TXSLZR_SEQ_DBG0_DBG_SEQ_BUSY_STATE_MASK (0x100UL)
#define TXSLZR_SEQ_DBG0_DBG_SEQ_BUSY_STATE_SHIFT (8UL)
#define TXSLZR_SEQ_DBG0_DBG_SM_EX_STATE_MASK (0x70UL)
#define TXSLZR_SEQ_DBG0_DBG_SM_EX_STATE_SHIFT (4UL)
#define TXSLZR_SEQ_DBG0_DBG_SM_RD_STATE_MASK (0x7UL)
#define TXSLZR_SEQ_DBG0_DBG_SM_RD_STATE_SHIFT (0UL)




typedef uint32_t TXSLZR_SER_TX_CTRL_0_TYPE;
#define TXSLZR_SER_TX_CTRL_0_FSLICE_OVR_VAL_L_MASK (0xffff0000UL)
#define TXSLZR_SER_TX_CTRL_0_FSLICE_OVR_VAL_L_SHIFT (16UL)
#define TXSLZR_SER_TX_CTRL_0_NFSLICE_OVR_VAL_MASK (0xffffUL)
#define TXSLZR_SER_TX_CTRL_0_NFSLICE_OVR_VAL_SHIFT (0UL)




typedef uint32_t TXSLZR_SER_TX_CTRL_1_TYPE;
#define TXSLZR_SER_TX_CTRL_1_TX_CLK16_TOSER_INV_MASK (0x80000000UL)
#define TXSLZR_SER_TX_CTRL_1_TX_CLK16_TOSER_INV_SHIFT (31UL)
#define TXSLZR_SER_TX_CTRL_1_TX_CLK16_TOSER_PHASE_MASK (0x70000000UL)
#define TXSLZR_SER_TX_CTRL_1_TX_CLK16_TOSER_PHASE_SHIFT (28UL)
#define TXSLZR_SER_TX_CTRL_1_TX_RSVD_1_MASK (0xe000000UL)
#define TXSLZR_SER_TX_CTRL_1_TX_RSVD_1_SHIFT (25UL)
#define TXSLZR_SER_TX_CTRL_1_PE_MASK (0x1800000UL)
#define TXSLZR_SER_TX_CTRL_1_PE_SHIFT (23UL)
#define TXSLZR_SER_TX_CTRL_1_SWINGNOPE_MASK (0x600000UL)
#define TXSLZR_SER_TX_CTRL_1_SWINGNOPE_SHIFT (21UL)
#define TXSLZR_SER_TX_CTRL_1_TX_RSVD_0_MASK (0x1e0000UL)
#define TXSLZR_SER_TX_CTRL_1_TX_RSVD_0_SHIFT (17UL)
#define TXSLZR_SER_TX_CTRL_1_TX_LUT_OVR_EN_MASK (0x10000UL)
#define TXSLZR_SER_TX_CTRL_1_TX_LUT_OVR_EN_SHIFT (16UL)
#define TXSLZR_SER_TX_CTRL_1_TX_FSLICE_OVR_VAL_H_MASK (0xffffUL)
#define TXSLZR_SER_TX_CTRL_1_TX_FSLICE_OVR_VAL_H_SHIFT (0UL)




typedef uint32_t TXSLZR_SER_TX_CTRL_2_TYPE;
#define TXSLZR_SER_TX_CTRL_2_ANTEST_SEL_MASK (0xfff00000UL)
#define TXSLZR_SER_TX_CTRL_2_ANTEST_SEL_SHIFT (20UL)
#define TXSLZR_SER_TX_CTRL_2_TX_CLK16_TOINTF_INV_MASK (0x80000UL)
#define TXSLZR_SER_TX_CTRL_2_TX_CLK16_TOINTF_INV_SHIFT (19UL)
#define TXSLZR_SER_TX_CTRL_2_TX_CLK16_TOINTF_PHASE_MASK (0x70000UL)
#define TXSLZR_SER_TX_CTRL_2_TX_CLK16_TOINTF_PHASE_SHIFT (16UL)
#define TXSLZR_SER_TX_CTRL_2_TX_INVERT_MASK (0x8000UL)
#define TXSLZR_SER_TX_CTRL_2_TX_INVERT_SHIFT (15UL)
#define TXSLZR_SER_TX_CTRL_2_TX_WORDFLIP_MASK (0x4000UL)
#define TXSLZR_SER_TX_CTRL_2_TX_WORDFLIP_SHIFT (14UL)
#define TXSLZR_SER_TX_CTRL_2_RETIMER_CLK16_INV_MASK (0x2000UL)
#define TXSLZR_SER_TX_CTRL_2_RETIMER_CLK16_INV_SHIFT (13UL)
#define TXSLZR_SER_TX_CTRL_2_INTERFACE_CLK16_SEL_MASK (0x1000UL)
#define TXSLZR_SER_TX_CTRL_2_INTERFACE_CLK16_SEL_SHIFT (12UL)
#define TXSLZR_SER_TX_CTRL_2_RESCAL_OVR_EN_MASK (0x800UL)
#define TXSLZR_SER_TX_CTRL_2_RESCAL_OVR_EN_SHIFT (11UL)
#define TXSLZR_SER_TX_CTRL_2_RESCAL_OVR_VAL_MASK (0x780UL)
#define TXSLZR_SER_TX_CTRL_2_RESCAL_OVR_VAL_SHIFT (7UL)
#define TXSLZR_SER_TX_CTRL_2_TX_INJSTRENGTH_MASK (0x60UL)
#define TXSLZR_SER_TX_CTRL_2_TX_INJSTRENGTH_SHIFT (5UL)
#define TXSLZR_SER_TX_CTRL_2_TX_ENINJ_MASK (0x10UL)
#define TXSLZR_SER_TX_CTRL_2_TX_ENINJ_SHIFT (4UL)
#define TXSLZR_SER_TX_CTRL_2_TX_ELECIDLE_CMHOLD_MASK (0x8UL)
#define TXSLZR_SER_TX_CTRL_2_TX_ELECIDLE_CMHOLD_SHIFT (3UL)
#define TXSLZR_SER_TX_CTRL_2_TX_CM_OPAMP_IDLE_MASK (0x4UL)
#define TXSLZR_SER_TX_CTRL_2_TX_CM_OPAMP_IDLE_SHIFT (2UL)
#define TXSLZR_SER_TX_CTRL_2_TX_RSVD_2_MASK (0x3UL)
#define TXSLZR_SER_TX_CTRL_2_TX_RSVD_2_SHIFT (0UL)




typedef uint32_t TXSLZR_SER_TX_CTRL_3_TYPE;
#define TXSLZR_SER_TX_CTRL_3_DYN_ELECIDLE_CNTR_MASK (0xffffUL)
#define TXSLZR_SER_TX_CTRL_3_DYN_ELECIDLE_CNTR_SHIFT (0UL)




typedef uint32_t TXSLZR_TEST_CTRL_TYPE;
#define TXSLZR_TEST_CTRL_PG_PRBS_CFG_REVERSE_MASK (0x80UL)
#define TXSLZR_TEST_CTRL_PG_PRBS_CFG_REVERSE_SHIFT (7UL)
#define TXSLZR_TEST_CTRL_PG_PRBS_CFG_INV_MASK (0x40UL)
#define TXSLZR_TEST_CTRL_PG_PRBS_CFG_INV_SHIFT (6UL)
#define TXSLZR_TEST_CTRL_PG_PRBS_CFG_ORDER_MASK (0x20UL)
#define TXSLZR_TEST_CTRL_PG_PRBS_CFG_ORDER_SHIFT (5UL)
#define TXSLZR_TEST_CTRL_PG_PRBS_EN_MASK (0x10UL)
#define TXSLZR_TEST_CTRL_PG_PRBS_EN_SHIFT (4UL)
#define TXSLZR_TEST_CTRL_PG_EN_MASK (0x1UL)
#define TXSLZR_TEST_CTRL_PG_EN_SHIFT (0UL)




typedef uint32_t TXSLZR_SPARE_REG0_TYPE;
#define TXSLZR_SPARE_REG0_CTRL_MASK (0xffffffffUL)
#define TXSLZR_SPARE_REG0_CTRL_SHIFT (0UL)



#define TXSLZR_PAGE_SZ_SIZE  (4UL)


typedef volatile struct sTXSLZR_RDBType {
    TXSLZR_CONTROL_TYPE control; /* OFFSET: 0x0 */
    TXSLZR_PAGE_SZ_0_TYPE page_sz[TXSLZR_PAGE_SZ_SIZE]; /* OFFSET: 0x4 */
    TXSLZR_RESERVED_TYPE rsvd0[12]; /* OFFSET: 0x14 */
    TXSLZR_TPMIWC_TYPE pg_mem_ind_wr_control; /* OFFSET: 0x20 */
    TXSLZR_PG_MEM_IND_WR_DATA_TYPE pg_mem_ind_wr_data; /* OFFSET: 0x24 */
    TXSLZR_TPMIRC_TYPE pg_mem_ind_rd_control; /* OFFSET: 0x28 */
    TXSLZR_PG_MEM_IND_RD_DATA_TYPE pg_mem_ind_rd_data; /* OFFSET: 0x2c */
    TXSLZR_SEQ_CONTROL_TYPE seq_control; /* OFFSET: 0x30 */
    TXSLZR_RESERVED_TYPE rsvd1[12]; /* OFFSET: 0x34 */
    TXSLZR_SEQ_MEM_IND_WR_CONTROL_TYPE seq_mem_ind_wr_control; /* OFFSET: 0x40 */
    TXSLZR_SEQ_MEM_IND_WR_DATA_TYPE seq_mem_ind_wr_data; /* OFFSET: 0x44 */
    TXSLZR_SEQ_MEM_IND_RD_CONTROL_TYPE seq_mem_ind_rd_control; /* OFFSET: 0x48 */
    TXSLZR_SEQ_MEM_IND_RD_DATA_TYPE seq_mem_ind_rd_data; /* OFFSET: 0x4c */
    TXSLZR_SEQ_SPI_CONTROL_TYPE seq_spi_control; /* OFFSET: 0x50 */
    TXSLZR_SEQ_SPI_SFT_CONTROL_TYPE seq_spi_sft_control; /* OFFSET: 0x54 */
    TXSLZR_SEQ_SFT_WR_DATA_TYPE seq_spi_sft_wr_data; /* OFFSET: 0x58 */
    TXSLZR_SEQ_SFT_RD_DATA_TYPE seq_spi_sft_rd_data; /* OFFSET: 0x5c */
    TXSLZR_SEQ_MISC_SPI_CONTROL_TYPE seq_spi_misc_control; /* OFFSET: 0x60 */
    TXSLZR_RESERVED_TYPE rsvd2[4]; /* OFFSET: 0x64 */
    TXSLZR_SEQ_DBG0_TYPE seq_dbg0; /* OFFSET: 0x68 */
    TXSLZR_RESERVED_TYPE rsvd3[4]; /* OFFSET: 0x6c */
    TXSLZR_SER_TX_CTRL_0_TYPE ser_tx_ctrl_0; /* OFFSET: 0x70 */
    TXSLZR_SER_TX_CTRL_1_TYPE ser_tx_ctrl_1; /* OFFSET: 0x74 */
    TXSLZR_SER_TX_CTRL_2_TYPE ser_tx_ctrl_2; /* OFFSET: 0x78 */
    TXSLZR_SER_TX_CTRL_3_TYPE ser_tx_ctrl_3; /* OFFSET: 0x7c */
    TXSLZR_TEST_CTRL_TYPE test_ctrl; /* OFFSET: 0x80 */
    TXSLZR_RESERVED_TYPE rsvd4[92]; /* OFFSET: 0x84 */
    TXSLZR_SPARE_REG0_TYPE spare_reg0; /* OFFSET: 0xe0 */
} TXSLZR_RDBType;


#define TXSLZR_BASE                     (0xE0607000UL)



#define TXSLZR_MAX_HW_ID                (1UL)

#endif /* TXSLZR_RDB_H */
