/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file xgmac_mtl_rdb.h
    @brief RDB File for XGMAC_MTL

    @version BCM89580_A0_20230125_RDB
*/

#ifndef XGMAC_MTL_RDB_H
#define XGMAC_MTL_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t XGMAC_MTL_RESERVED_TYPE;




typedef uint32_t XGMAC_MTL_MTL_OPERATION_MODE_TYPE;
#define XGMAC_MTL_MTL_OPERATION_MODE_ETSALG_MASK (0x60UL)
#define XGMAC_MTL_MTL_OPERATION_MODE_ETSALG_SHIFT (5UL)
#define XGMAC_MTL_MTL_OPERATION_MODE_RAA_MASK (0x4UL)
#define XGMAC_MTL_MTL_OPERATION_MODE_RAA_SHIFT (2UL)




typedef uint32_t XGMAC_MTL_MTL_DEBUG_CONTROL_TYPE;
#define XGMAC_MTL_MTL_DEBUG_CONTROL_EIEC_MASK (0x40000UL)
#define XGMAC_MTL_MTL_DEBUG_CONTROL_EIEC_SHIFT (18UL)
#define XGMAC_MTL_MTL_DEBUG_CONTROL_EIAEE_MASK (0x20000UL)
#define XGMAC_MTL_MTL_DEBUG_CONTROL_EIAEE_SHIFT (17UL)
#define XGMAC_MTL_MTL_DEBUG_CONTROL_EIEE_MASK (0x10000UL)
#define XGMAC_MTL_MTL_DEBUG_CONTROL_EIEE_SHIFT (16UL)
#define XGMAC_MTL_MTL_DEBUG_CONTROL_PKTIE_MASK (0x4000UL)
#define XGMAC_MTL_MTL_DEBUG_CONTROL_PKTIE_SHIFT (14UL)
#define XGMAC_MTL_MTL_DEBUG_CONTROL_FIFOSEL_MASK (0x3000UL)
#define XGMAC_MTL_MTL_DEBUG_CONTROL_FIFOSEL_SHIFT (12UL)
#define XGMAC_MTL_MTL_DEBUG_CONTROL_FIFOWREN_MASK (0x800UL)
#define XGMAC_MTL_MTL_DEBUG_CONTROL_FIFOWREN_SHIFT (11UL)
#define XGMAC_MTL_MTL_DEBUG_CONTROL_FIFORDEN_MASK (0x400UL)
#define XGMAC_MTL_MTL_DEBUG_CONTROL_FIFORDEN_SHIFT (10UL)
#define XGMAC_MTL_MTL_DEBUG_CONTROL_RSTSEL_MASK (0x200UL)
#define XGMAC_MTL_MTL_DEBUG_CONTROL_RSTSEL_SHIFT (9UL)
#define XGMAC_MTL_MTL_DEBUG_CONTROL_RSTALL_MASK (0x100UL)
#define XGMAC_MTL_MTL_DEBUG_CONTROL_RSTALL_SHIFT (8UL)
#define XGMAC_MTL_MTL_DEBUG_CONTROL_PKTSTATE_MASK (0x60UL)
#define XGMAC_MTL_MTL_DEBUG_CONTROL_PKTSTATE_SHIFT (5UL)
#define XGMAC_MTL_MTL_DEBUG_CONTROL_BYTEEN_MASK (0xcUL)
#define XGMAC_MTL_MTL_DEBUG_CONTROL_BYTEEN_SHIFT (2UL)
#define XGMAC_MTL_MTL_DEBUG_CONTROL_DBGMOD_MASK (0x2UL)
#define XGMAC_MTL_MTL_DEBUG_CONTROL_DBGMOD_SHIFT (1UL)
#define XGMAC_MTL_MTL_DEBUG_CONTROL_FDBGEN_MASK (0x1UL)
#define XGMAC_MTL_MTL_DEBUG_CONTROL_FDBGEN_SHIFT (0UL)




typedef uint32_t XGMAC_MTL_MTL_DEBUG_STATUS_TYPE;
#define XGMAC_MTL_MTL_DEBUG_STATUS_LOCR_MASK (0xffff0000UL)
#define XGMAC_MTL_MTL_DEBUG_STATUS_LOCR_SHIFT (16UL)
#define XGMAC_MTL_MTL_DEBUG_STATUS_PKTI_MASK (0x100UL)
#define XGMAC_MTL_MTL_DEBUG_STATUS_PKTI_SHIFT (8UL)
#define XGMAC_MTL_MTL_DEBUG_STATUS_BYTEEN_MASK (0x18UL)
#define XGMAC_MTL_MTL_DEBUG_STATUS_BYTEEN_SHIFT (3UL)
#define XGMAC_MTL_MTL_DEBUG_STATUS_PKYSTATE_MASK (0x6UL)
#define XGMAC_MTL_MTL_DEBUG_STATUS_PKYSTATE_SHIFT (1UL)
#define XGMAC_MTL_MTL_DEBUG_STATUS_FIFOBUSY_MASK (0x1UL)
#define XGMAC_MTL_MTL_DEBUG_STATUS_FIFOBUSY_SHIFT (0UL)




typedef uint32_t XGMAC_MTL_MTL_FIFO_DEBUG_DATA_TYPE;
#define XGMAC_MTL_MTL_FIFO_DEBUG_DATA_FDBGDATA_MASK (0xffffffffUL)
#define XGMAC_MTL_MTL_FIFO_DEBUG_DATA_FDBGDATA_SHIFT (0UL)




typedef uint32_t XGMAC_MTL_MTL_INTERRUPT_STATUS_TYPE;
#define XGMAC_MTL_MTL_INTERRUPT_STATUS_DBGIS_MASK (0x20000UL)
#define XGMAC_MTL_MTL_INTERRUPT_STATUS_DBGIS_SHIFT (17UL)
#define XGMAC_MTL_MTL_INTERRUPT_STATUS_MACIS_MASK (0x10000UL)
#define XGMAC_MTL_MTL_INTERRUPT_STATUS_MACIS_SHIFT (16UL)
#define XGMAC_MTL_MTL_INTERRUPT_STATUS_Q7IS_MASK (0x80UL)
#define XGMAC_MTL_MTL_INTERRUPT_STATUS_Q7IS_SHIFT (7UL)
#define XGMAC_MTL_MTL_INTERRUPT_STATUS_Q6IS_MASK (0x40UL)
#define XGMAC_MTL_MTL_INTERRUPT_STATUS_Q6IS_SHIFT (6UL)
#define XGMAC_MTL_MTL_INTERRUPT_STATUS_Q5IS_MASK (0x20UL)
#define XGMAC_MTL_MTL_INTERRUPT_STATUS_Q5IS_SHIFT (5UL)
#define XGMAC_MTL_MTL_INTERRUPT_STATUS_Q4IS_MASK (0x10UL)
#define XGMAC_MTL_MTL_INTERRUPT_STATUS_Q4IS_SHIFT (4UL)
#define XGMAC_MTL_MTL_INTERRUPT_STATUS_Q3IS_MASK (0x8UL)
#define XGMAC_MTL_MTL_INTERRUPT_STATUS_Q3IS_SHIFT (3UL)
#define XGMAC_MTL_MTL_INTERRUPT_STATUS_Q2IS_MASK (0x4UL)
#define XGMAC_MTL_MTL_INTERRUPT_STATUS_Q2IS_SHIFT (2UL)
#define XGMAC_MTL_MTL_INTERRUPT_STATUS_Q1IS_MASK (0x2UL)
#define XGMAC_MTL_MTL_INTERRUPT_STATUS_Q1IS_SHIFT (1UL)
#define XGMAC_MTL_MTL_INTERRUPT_STATUS_Q0IS_MASK (0x1UL)
#define XGMAC_MTL_MTL_INTERRUPT_STATUS_Q0IS_SHIFT (0UL)




typedef uint32_t XGMAC_MTL_MTL_RXQ_DMA_MAP0_TYPE;
#define XGMAC_MTL_MTL_RXQ_DMA_MAP0_Q1DDMACH_MASK (0x8000UL)
#define XGMAC_MTL_MTL_RXQ_DMA_MAP0_Q1DDMACH_SHIFT (15UL)
#define XGMAC_MTL_MTL_RXQ_DMA_MAP0_Q1MDMACH_MASK (0x100UL)
#define XGMAC_MTL_MTL_RXQ_DMA_MAP0_Q1MDMACH_SHIFT (8UL)
#define XGMAC_MTL_MTL_RXQ_DMA_MAP0_Q0DDMACH_MASK (0x80UL)
#define XGMAC_MTL_MTL_RXQ_DMA_MAP0_Q0DDMACH_SHIFT (7UL)
#define XGMAC_MTL_MTL_RXQ_DMA_MAP0_Q0MDMACH_MASK (0x1UL)
#define XGMAC_MTL_MTL_RXQ_DMA_MAP0_Q0MDMACH_SHIFT (0UL)




typedef uint32_t XGMAC_MTL_MTL_TC_PRTY_MAP0_TYPE;
#define XGMAC_MTL_MTL_TC_PRTY_MAP0_PSTC3_MASK (0xff000000UL)
#define XGMAC_MTL_MTL_TC_PRTY_MAP0_PSTC3_SHIFT (24UL)
#define XGMAC_MTL_MTL_TC_PRTY_MAP0_PSTC2_MASK (0xff0000UL)
#define XGMAC_MTL_MTL_TC_PRTY_MAP0_PSTC2_SHIFT (16UL)
#define XGMAC_MTL_MTL_TC_PRTY_MAP0_PSTC1_MASK (0xff00UL)
#define XGMAC_MTL_MTL_TC_PRTY_MAP0_PSTC1_SHIFT (8UL)
#define XGMAC_MTL_MTL_TC_PRTY_MAP0_PSTC0_MASK (0xffUL)
#define XGMAC_MTL_MTL_TC_PRTY_MAP0_PSTC0_SHIFT (0UL)




typedef uint32_t XGMAC_MTL_MTL_TC_PRTY_MAP1_TYPE;
#define XGMAC_MTL_MTL_TC_PRTY_MAP1_PSTC7_MASK (0xff000000UL)
#define XGMAC_MTL_MTL_TC_PRTY_MAP1_PSTC7_SHIFT (24UL)
#define XGMAC_MTL_MTL_TC_PRTY_MAP1_PSTC6_MASK (0xff0000UL)
#define XGMAC_MTL_MTL_TC_PRTY_MAP1_PSTC6_SHIFT (16UL)
#define XGMAC_MTL_MTL_TC_PRTY_MAP1_PSTC5_MASK (0xff00UL)
#define XGMAC_MTL_MTL_TC_PRTY_MAP1_PSTC5_SHIFT (8UL)
#define XGMAC_MTL_MTL_TC_PRTY_MAP1_PSTC4_MASK (0xffUL)
#define XGMAC_MTL_MTL_TC_PRTY_MAP1_PSTC4_SHIFT (0UL)




typedef uint32_t XGMAC_MTL_MTL_ECC_CONTROL_TYPE;
#define XGMAC_MTL_MTL_ECC_CONTROL_MEEAO_MASK (0x100UL)
#define XGMAC_MTL_MTL_ECC_CONTROL_MEEAO_SHIFT (8UL)
#define XGMAC_MTL_MTL_ECC_CONTROL_DESCED_MASK (0x20UL)
#define XGMAC_MTL_MTL_ECC_CONTROL_DESCED_SHIFT (5UL)
#define XGMAC_MTL_MTL_ECC_CONTROL_MRXED_MASK (0x2UL)
#define XGMAC_MTL_MTL_ECC_CONTROL_MRXED_SHIFT (1UL)
#define XGMAC_MTL_MTL_ECC_CONTROL_MTXED_MASK (0x1UL)
#define XGMAC_MTL_MTL_ECC_CONTROL_MTXED_SHIFT (0UL)




typedef uint32_t XGMAC_MTL_MTL_SAFETY_INTERRUPT_STATUS_TYPE;
#define XGMAC_MTL_MTL_SAFETY_INTERRUPT_STATUS_MCSIS_MASK (0x80000000UL)
#define XGMAC_MTL_MTL_SAFETY_INTERRUPT_STATUS_MCSIS_SHIFT (31UL)
#define XGMAC_MTL_MTL_SAFETY_INTERRUPT_STATUS_MEUIS_MASK (0x2UL)
#define XGMAC_MTL_MTL_SAFETY_INTERRUPT_STATUS_MEUIS_SHIFT (1UL)
#define XGMAC_MTL_MTL_SAFETY_INTERRUPT_STATUS_MECIS_MASK (0x1UL)
#define XGMAC_MTL_MTL_SAFETY_INTERRUPT_STATUS_MECIS_SHIFT (0UL)




typedef uint32_t XGMAC_MTL_MTL_ECC_INTERRUPT_ENABLE_TYPE;
#define XGMAC_MTL_MTL_ECC_INTERRUPT_ENABLE_RXCEIE_MASK (0x10UL)
#define XGMAC_MTL_MTL_ECC_INTERRUPT_ENABLE_RXCEIE_SHIFT (4UL)
#define XGMAC_MTL_MTL_ECC_INTERRUPT_ENABLE_TXCEIE_MASK (0x1UL)
#define XGMAC_MTL_MTL_ECC_INTERRUPT_ENABLE_TXCEIE_SHIFT (0UL)




typedef uint32_t XGMAC_MTL_MTL_ECC_INTERRUPT_STATUS_TYPE;
#define XGMAC_MTL_MTL_ECC_INTERRUPT_STATUS_RXUES_MASK (0x40UL)
#define XGMAC_MTL_MTL_ECC_INTERRUPT_STATUS_RXUES_SHIFT (6UL)
#define XGMAC_MTL_MTL_ECC_INTERRUPT_STATUS_RXAMS_MASK (0x20UL)
#define XGMAC_MTL_MTL_ECC_INTERRUPT_STATUS_RXAMS_SHIFT (5UL)
#define XGMAC_MTL_MTL_ECC_INTERRUPT_STATUS_RXCES_MASK (0x10UL)
#define XGMAC_MTL_MTL_ECC_INTERRUPT_STATUS_RXCES_SHIFT (4UL)
#define XGMAC_MTL_MTL_ECC_INTERRUPT_STATUS_TXUES_MASK (0x4UL)
#define XGMAC_MTL_MTL_ECC_INTERRUPT_STATUS_TXUES_SHIFT (2UL)
#define XGMAC_MTL_MTL_ECC_INTERRUPT_STATUS_TXAMS_MASK (0x2UL)
#define XGMAC_MTL_MTL_ECC_INTERRUPT_STATUS_TXAMS_SHIFT (1UL)
#define XGMAC_MTL_MTL_ECC_INTERRUPT_STATUS_TXCES_MASK (0x1UL)
#define XGMAC_MTL_MTL_ECC_INTERRUPT_STATUS_TXCES_SHIFT (0UL)




typedef uint32_t XGMAC_MTL_MTL_ECC_ERR_STS_RCTL_TYPE;
#define XGMAC_MTL_MTL_ECC_ERR_STS_RCTL_CUES_MASK (0x20UL)
#define XGMAC_MTL_MTL_ECC_ERR_STS_RCTL_CUES_SHIFT (5UL)
#define XGMAC_MTL_MTL_ECC_ERR_STS_RCTL_CCES_MASK (0x10UL)
#define XGMAC_MTL_MTL_ECC_ERR_STS_RCTL_CCES_SHIFT (4UL)
#define XGMAC_MTL_MTL_ECC_ERR_STS_RCTL_EMS_MASK (0xeUL)
#define XGMAC_MTL_MTL_ECC_ERR_STS_RCTL_EMS_SHIFT (1UL)
#define XGMAC_MTL_MTL_ECC_ERR_STS_RCTL_EESRE_MASK (0x1UL)
#define XGMAC_MTL_MTL_ECC_ERR_STS_RCTL_EESRE_SHIFT (0UL)




typedef uint32_t XGMAC_MTL_MTL_ECC_ERR_ADDR_STATUS_TYPE;
#define XGMAC_MTL_MTL_ECC_ERR_ADDR_STATUS_EUEAS_MASK (0xffff0000UL)
#define XGMAC_MTL_MTL_ECC_ERR_ADDR_STATUS_EUEAS_SHIFT (16UL)
#define XGMAC_MTL_MTL_ECC_ERR_ADDR_STATUS_ECEAS_MASK (0xffffUL)
#define XGMAC_MTL_MTL_ECC_ERR_ADDR_STATUS_ECEAS_SHIFT (0UL)




typedef uint32_t XGMAC_MTL_MTL_ECC_ERR_CNTR_STATUS_TYPE;
#define XGMAC_MTL_MTL_ECC_ERR_CNTR_STATUS_EUECS_MASK (0xf0000UL)
#define XGMAC_MTL_MTL_ECC_ERR_CNTR_STATUS_EUECS_SHIFT (16UL)
#define XGMAC_MTL_MTL_ECC_ERR_CNTR_STATUS_ECECS_MASK (0xffUL)
#define XGMAC_MTL_MTL_ECC_ERR_CNTR_STATUS_ECECS_SHIFT (0UL)




typedef uint32_t XGMAC_MTL_MTL_DPP_CONTROL_TYPE;
#define XGMAC_MTL_MTL_DPP_CONTROL_IPEMRRC_MASK (0x4000UL)
#define XGMAC_MTL_MTL_DPP_CONTROL_IPEMRRC_SHIFT (14UL)
#define XGMAC_MTL_MTL_DPP_CONTROL_IPEMRWC_MASK (0x2000UL)
#define XGMAC_MTL_MTL_DPP_CONTROL_IPEMRWC_SHIFT (13UL)
#define XGMAC_MTL_MTL_DPP_CONTROL_IPEAR_MASK (0x1000UL)
#define XGMAC_MTL_MTL_DPP_CONTROL_IPEAR_SHIFT (12UL)
#define XGMAC_MTL_MTL_DPP_CONTROL_IPEMTFC_MASK (0x800UL)
#define XGMAC_MTL_MTL_DPP_CONTROL_IPEMTFC_SHIFT (11UL)
#define XGMAC_MTL_MTL_DPP_CONTROL_IPEMTBU_MASK (0x400UL)
#define XGMAC_MTL_MTL_DPP_CONTROL_IPEMTBU_SHIFT (10UL)
#define XGMAC_MTL_MTL_DPP_CONTROL_IPEMTD_MASK (0x100UL)
#define XGMAC_MTL_MTL_DPP_CONTROL_IPEMTD_SHIFT (8UL)
#define XGMAC_MTL_MTL_DPP_CONTROL_IPEDC_MASK (0x20UL)
#define XGMAC_MTL_MTL_DPP_CONTROL_IPEDC_SHIFT (5UL)
#define XGMAC_MTL_MTL_DPP_CONTROL_OPE_MASK (0x2UL)
#define XGMAC_MTL_MTL_DPP_CONTROL_OPE_SHIFT (1UL)
#define XGMAC_MTL_MTL_DPP_CONTROL_DDPP_MASK (0x1UL)
#define XGMAC_MTL_MTL_DPP_CONTROL_DDPP_SHIFT (0UL)




typedef uint32_t XGMAC_MTL_MTL_DPP_ECC_EIC_TYPE;
#define XGMAC_MTL_MTL_DPP_ECC_EIC_EIM_MASK (0x10000UL)
#define XGMAC_MTL_MTL_DPP_ECC_EIC_EIM_SHIFT (16UL)
#define XGMAC_MTL_MTL_DPP_ECC_EIC_BLEI_MASK (0xffUL)
#define XGMAC_MTL_MTL_DPP_ECC_EIC_BLEI_SHIFT (0UL)




typedef volatile struct sXGMAC_MTL_RDBType {
    XGMAC_MTL_RESERVED_TYPE rsvd0[4096]; /* OFFSET: 0x0 */
    XGMAC_MTL_MTL_OPERATION_MODE_TYPE operation_mode; /* OFFSET: 0x1000 */
    XGMAC_MTL_RESERVED_TYPE rsvd1[4]; /* OFFSET: 0x1004 */
    XGMAC_MTL_MTL_DEBUG_CONTROL_TYPE debug_control; /* OFFSET: 0x1008 */
    XGMAC_MTL_MTL_DEBUG_STATUS_TYPE debug_status; /* OFFSET: 0x100c */
    XGMAC_MTL_MTL_FIFO_DEBUG_DATA_TYPE fifo_debug_data; /* OFFSET: 0x1010 */
    XGMAC_MTL_RESERVED_TYPE rsvd2[12]; /* OFFSET: 0x1014 */
    XGMAC_MTL_MTL_INTERRUPT_STATUS_TYPE interrupt_status; /* OFFSET: 0x1020 */
    XGMAC_MTL_RESERVED_TYPE rsvd3[12]; /* OFFSET: 0x1024 */
    XGMAC_MTL_MTL_RXQ_DMA_MAP0_TYPE rxq_dma_map0; /* OFFSET: 0x1030 */
    XGMAC_MTL_RESERVED_TYPE rsvd4[12]; /* OFFSET: 0x1034 */
    XGMAC_MTL_MTL_TC_PRTY_MAP0_TYPE tc_prty_map0; /* OFFSET: 0x1040 */
    XGMAC_MTL_MTL_TC_PRTY_MAP1_TYPE tc_prty_map1; /* OFFSET: 0x1044 */
    XGMAC_MTL_RESERVED_TYPE rsvd5[120]; /* OFFSET: 0x1048 */
    XGMAC_MTL_MTL_ECC_CONTROL_TYPE ecc_control; /* OFFSET: 0x10c0 */
    XGMAC_MTL_MTL_SAFETY_INTERRUPT_STATUS_TYPE safety_interrupt_status; /* OFFSET: 0x10c4 */
    XGMAC_MTL_MTL_ECC_INTERRUPT_ENABLE_TYPE ecc_interrupt_enable; /* OFFSET: 0x10c8 */
    XGMAC_MTL_MTL_ECC_INTERRUPT_STATUS_TYPE ecc_interrupt_status; /* OFFSET: 0x10cc */
    XGMAC_MTL_MTL_ECC_ERR_STS_RCTL_TYPE ecc_err_sts_rctl; /* OFFSET: 0x10d0 */
    XGMAC_MTL_MTL_ECC_ERR_ADDR_STATUS_TYPE ecc_err_addr_status; /* OFFSET: 0x10d4 */
    XGMAC_MTL_MTL_ECC_ERR_CNTR_STATUS_TYPE ecc_err_cntr_status; /* OFFSET: 0x10d8 */
    XGMAC_MTL_RESERVED_TYPE rsvd6[4]; /* OFFSET: 0x10dc */
    XGMAC_MTL_MTL_DPP_CONTROL_TYPE dpp_control; /* OFFSET: 0x10e0 */
    XGMAC_MTL_MTL_DPP_ECC_EIC_TYPE dpp_ecc_eic; /* OFFSET: 0x10e4 */
} XGMAC_MTL_RDBType;


#define XG_MTL_BASE                     ((uintptr_t)(0xE02F0000UL))



#define XGMAC_MTL_MAX_HW_ID             (1UL)

#endif /* XGMAC_MTL_RDB_H */
