/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file xgmac_dma_rdb.h
    @brief RDB File for XGMAC_DMA

    @version BCM89580_A0_20230125_RDB
*/

#ifndef XGMAC_DMA_RDB_H
#define XGMAC_DMA_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t XGMAC_DMA_RESERVED_TYPE;




typedef uint32_t XGMAC_DMA_DMA_MODE_TYPE;
#define XGMAC_DMA_DMA_MODE_INTM_MASK (0x3000UL)
#define XGMAC_DMA_DMA_MODE_INTM_SHIFT (12UL)
#define XGMAC_DMA_DMA_MODE_DSPW_MASK (0x100UL)
#define XGMAC_DMA_DMA_MODE_DSPW_SHIFT (8UL)
#define XGMAC_DMA_DMA_MODE_TMRP_MASK (0x20UL)
#define XGMAC_DMA_DMA_MODE_TMRP_SHIFT (5UL)
#define XGMAC_DMA_DMA_MODE_TDRP_MASK (0x10UL)
#define XGMAC_DMA_DMA_MODE_TDRP_SHIFT (4UL)
#define XGMAC_DMA_DMA_MODE_SWR_MASK (0x1UL)
#define XGMAC_DMA_DMA_MODE_SWR_SHIFT (0UL)




typedef uint32_t XGMAC_DMA_DMA_SYSBUS_MODE_TYPE;
#define XGMAC_DMA_DMA_SYSBUS_MODE_WR_OSR_LMT_MASK (0x1f000000UL)
#define XGMAC_DMA_DMA_SYSBUS_MODE_WR_OSR_LMT_SHIFT (24UL)
#define XGMAC_DMA_DMA_SYSBUS_MODE_RD_OSR_LMT_MASK (0x1f0000UL)
#define XGMAC_DMA_DMA_SYSBUS_MODE_RD_OSR_LMT_SHIFT (16UL)
#define XGMAC_DMA_DMA_SYSBUS_MODE_EN_LPI_MASK (0x8000UL)
#define XGMAC_DMA_DMA_SYSBUS_MODE_EN_LPI_SHIFT (15UL)
#define XGMAC_DMA_DMA_SYSBUS_MODE_LPI_XIT_PKT_MASK (0x4000UL)
#define XGMAC_DMA_DMA_SYSBUS_MODE_LPI_XIT_PKT_SHIFT (14UL)
#define XGMAC_DMA_DMA_SYSBUS_MODE_ONEKBBE_MASK (0x2000UL)
#define XGMAC_DMA_DMA_SYSBUS_MODE_ONEKBBE_SHIFT (13UL)
#define XGMAC_DMA_DMA_SYSBUS_MODE_AAL_MASK (0x1000UL)
#define XGMAC_DMA_DMA_SYSBUS_MODE_AAL_SHIFT (12UL)
#define XGMAC_DMA_DMA_SYSBUS_MODE_AALE_MASK (0x400UL)
#define XGMAC_DMA_DMA_SYSBUS_MODE_AALE_SHIFT (10UL)
#define XGMAC_DMA_DMA_SYSBUS_MODE_BLEN256_MASK (0x80UL)
#define XGMAC_DMA_DMA_SYSBUS_MODE_BLEN256_SHIFT (7UL)
#define XGMAC_DMA_DMA_SYSBUS_MODE_BLEN128_MASK (0x40UL)
#define XGMAC_DMA_DMA_SYSBUS_MODE_BLEN128_SHIFT (6UL)
#define XGMAC_DMA_DMA_SYSBUS_MODE_BLEN64_MASK (0x20UL)
#define XGMAC_DMA_DMA_SYSBUS_MODE_BLEN64_SHIFT (5UL)
#define XGMAC_DMA_DMA_SYSBUS_MODE_BLEN32_MASK (0x10UL)
#define XGMAC_DMA_DMA_SYSBUS_MODE_BLEN32_SHIFT (4UL)
#define XGMAC_DMA_DMA_SYSBUS_MODE_BLEN16_MASK (0x8UL)
#define XGMAC_DMA_DMA_SYSBUS_MODE_BLEN16_SHIFT (3UL)
#define XGMAC_DMA_DMA_SYSBUS_MODE_BLEN8_MASK (0x4UL)
#define XGMAC_DMA_DMA_SYSBUS_MODE_BLEN8_SHIFT (2UL)
#define XGMAC_DMA_DMA_SYSBUS_MODE_BLEN4_MASK (0x2UL)
#define XGMAC_DMA_DMA_SYSBUS_MODE_BLEN4_SHIFT (1UL)
#define XGMAC_DMA_DMA_SYSBUS_MODE_UBL_MASK (0x1UL)
#define XGMAC_DMA_DMA_SYSBUS_MODE_UBL_SHIFT (0UL)




typedef uint32_t XGMAC_DMA_DMA_INTERRUPT_STATUS_TYPE;
#define XGMAC_DMA_DMA_INTERRUPT_STATUS_MACIS_MASK (0x20000UL)
#define XGMAC_DMA_DMA_INTERRUPT_STATUS_MACIS_SHIFT (17UL)
#define XGMAC_DMA_DMA_INTERRUPT_STATUS_MTLIS_MASK (0x10000UL)
#define XGMAC_DMA_DMA_INTERRUPT_STATUS_MTLIS_SHIFT (16UL)
#define XGMAC_DMA_DMA_INTERRUPT_STATUS_DC15TC8IS_MASK (0xff00UL)
#define XGMAC_DMA_DMA_INTERRUPT_STATUS_DC15TC8IS_SHIFT (8UL)
#define XGMAC_DMA_DMA_INTERRUPT_STATUS_DC7IS_MASK (0x80UL)
#define XGMAC_DMA_DMA_INTERRUPT_STATUS_DC7IS_SHIFT (7UL)
#define XGMAC_DMA_DMA_INTERRUPT_STATUS_DC6IS_MASK (0x40UL)
#define XGMAC_DMA_DMA_INTERRUPT_STATUS_DC6IS_SHIFT (6UL)
#define XGMAC_DMA_DMA_INTERRUPT_STATUS_DC5IS_MASK (0x20UL)
#define XGMAC_DMA_DMA_INTERRUPT_STATUS_DC5IS_SHIFT (5UL)
#define XGMAC_DMA_DMA_INTERRUPT_STATUS_DC4IS_MASK (0x10UL)
#define XGMAC_DMA_DMA_INTERRUPT_STATUS_DC4IS_SHIFT (4UL)
#define XGMAC_DMA_DMA_INTERRUPT_STATUS_DC3IS_MASK (0x8UL)
#define XGMAC_DMA_DMA_INTERRUPT_STATUS_DC3IS_SHIFT (3UL)
#define XGMAC_DMA_DMA_INTERRUPT_STATUS_DC2IS_MASK (0x4UL)
#define XGMAC_DMA_DMA_INTERRUPT_STATUS_DC2IS_SHIFT (2UL)
#define XGMAC_DMA_DMA_INTERRUPT_STATUS_DC1IS_MASK (0x2UL)
#define XGMAC_DMA_DMA_INTERRUPT_STATUS_DC1IS_SHIFT (1UL)
#define XGMAC_DMA_DMA_INTERRUPT_STATUS_DC0IS_MASK (0x1UL)
#define XGMAC_DMA_DMA_INTERRUPT_STATUS_DC0IS_SHIFT (0UL)




typedef uint32_t XGMAC_DMA_AXI_TX_AR_ACE_CONTROL_TYPE;
#define XGMAC_DMA_AXI_TX_AR_ACE_CONTROL_THD_MASK (0x300000UL)
#define XGMAC_DMA_AXI_TX_AR_ACE_CONTROL_THD_SHIFT (20UL)
#define XGMAC_DMA_AXI_TX_AR_ACE_CONTROL_THC_MASK (0xf0000UL)
#define XGMAC_DMA_AXI_TX_AR_ACE_CONTROL_THC_SHIFT (16UL)
#define XGMAC_DMA_AXI_TX_AR_ACE_CONTROL_TED_MASK (0x3000UL)
#define XGMAC_DMA_AXI_TX_AR_ACE_CONTROL_TED_SHIFT (12UL)
#define XGMAC_DMA_AXI_TX_AR_ACE_CONTROL_TEC_MASK (0xf00UL)
#define XGMAC_DMA_AXI_TX_AR_ACE_CONTROL_TEC_SHIFT (8UL)
#define XGMAC_DMA_AXI_TX_AR_ACE_CONTROL_TDRD_MASK (0x30UL)
#define XGMAC_DMA_AXI_TX_AR_ACE_CONTROL_TDRD_SHIFT (4UL)
#define XGMAC_DMA_AXI_TX_AR_ACE_CONTROL_TDRC_MASK (0xfUL)
#define XGMAC_DMA_AXI_TX_AR_ACE_CONTROL_TDRC_SHIFT (0UL)




typedef uint32_t XGMAC_DMA_AXI_RX_AW_ACE_CONTROL_TYPE;
#define XGMAC_DMA_AXI_RX_AW_ACE_CONTROL_RDD_MASK (0x30000000UL)
#define XGMAC_DMA_AXI_RX_AW_ACE_CONTROL_RDD_SHIFT (28UL)
#define XGMAC_DMA_AXI_RX_AW_ACE_CONTROL_RDC_MASK (0xf000000UL)
#define XGMAC_DMA_AXI_RX_AW_ACE_CONTROL_RDC_SHIFT (24UL)
#define XGMAC_DMA_AXI_RX_AW_ACE_CONTROL_RHD_MASK (0x300000UL)
#define XGMAC_DMA_AXI_RX_AW_ACE_CONTROL_RHD_SHIFT (20UL)
#define XGMAC_DMA_AXI_RX_AW_ACE_CONTROL_RHC_MASK (0xf0000UL)
#define XGMAC_DMA_AXI_RX_AW_ACE_CONTROL_RHC_SHIFT (16UL)
#define XGMAC_DMA_AXI_RX_AW_ACE_CONTROL_RPD_MASK (0x3000UL)
#define XGMAC_DMA_AXI_RX_AW_ACE_CONTROL_RPD_SHIFT (12UL)
#define XGMAC_DMA_AXI_RX_AW_ACE_CONTROL_RPC_MASK (0xf00UL)
#define XGMAC_DMA_AXI_RX_AW_ACE_CONTROL_RPC_SHIFT (8UL)
#define XGMAC_DMA_AXI_RX_AW_ACE_CONTROL_RDWD_MASK (0x30UL)
#define XGMAC_DMA_AXI_RX_AW_ACE_CONTROL_RDWD_SHIFT (4UL)
#define XGMAC_DMA_AXI_RX_AW_ACE_CONTROL_RDWC_MASK (0xfUL)
#define XGMAC_DMA_AXI_RX_AW_ACE_CONTROL_RDWC_SHIFT (0UL)




typedef uint32_t XGMAC_DMA_AXI_TXRX_AWAR_ACE_CONTROL_TYPE;
#define XGMAC_DMA_AXI_TXRX_AWAR_ACE_CONTROL_WRP_MASK (0x700000UL)
#define XGMAC_DMA_AXI_TXRX_AWAR_ACE_CONTROL_WRP_SHIFT (20UL)
#define XGMAC_DMA_AXI_TXRX_AWAR_ACE_CONTROL_RDP_MASK (0x70000UL)
#define XGMAC_DMA_AXI_TXRX_AWAR_ACE_CONTROL_RDP_SHIFT (16UL)
#define XGMAC_DMA_AXI_TXRX_AWAR_ACE_CONTROL_RDRD_MASK (0x3000UL)
#define XGMAC_DMA_AXI_TXRX_AWAR_ACE_CONTROL_RDRD_SHIFT (12UL)
#define XGMAC_DMA_AXI_TXRX_AWAR_ACE_CONTROL_RDRC_MASK (0xf00UL)
#define XGMAC_DMA_AXI_TXRX_AWAR_ACE_CONTROL_RDRC_SHIFT (8UL)
#define XGMAC_DMA_AXI_TXRX_AWAR_ACE_CONTROL_TDWD_MASK (0x30UL)
#define XGMAC_DMA_AXI_TXRX_AWAR_ACE_CONTROL_TDWD_SHIFT (4UL)
#define XGMAC_DMA_AXI_TXRX_AWAR_ACE_CONTROL_TDWC_MASK (0xfUL)
#define XGMAC_DMA_AXI_TXRX_AWAR_ACE_CONTROL_TDWC_SHIFT (0UL)




typedef uint32_t XGMAC_DMA_DMA_DEBUG_STATUS0_TYPE;
#define XGMAC_DMA_DMA_DEBUG_STATUS0_AXRHSTS_MASK (0x2UL)
#define XGMAC_DMA_DMA_DEBUG_STATUS0_AXRHSTS_SHIFT (1UL)
#define XGMAC_DMA_DMA_DEBUG_STATUS0_AXWHSTS_MASK (0x1UL)
#define XGMAC_DMA_DMA_DEBUG_STATUS0_AXWHSTS_SHIFT (0UL)




typedef uint32_t XGMAC_DMA_DMA_DEBUG_STATUS1_TYPE;
#define XGMAC_DMA_DMA_DEBUG_STATUS1_TDAS_MASK (0xffUL)
#define XGMAC_DMA_DMA_DEBUG_STATUS1_TDAS_SHIFT (0UL)




typedef uint32_t XGMAC_DMA_DMA_DEBUG_STATUS3_TYPE;
#define XGMAC_DMA_DMA_DEBUG_STATUS3_RDAS_MASK (0x3UL)
#define XGMAC_DMA_DMA_DEBUG_STATUS3_RDAS_SHIFT (0UL)




typedef uint32_t XGMAC_DMA_DMA_TX_EDMA_CONTROL_TYPE;
#define XGMAC_DMA_DMA_TX_EDMA_CONTROL_TEDM_MASK (0xc0000000UL)
#define XGMAC_DMA_DMA_TX_EDMA_CONTROL_TEDM_SHIFT (30UL)
#define XGMAC_DMA_DMA_TX_EDMA_CONTROL_TDPS_MASK (0x3UL)
#define XGMAC_DMA_DMA_TX_EDMA_CONTROL_TDPS_SHIFT (0UL)




typedef uint32_t XGMAC_DMA_DMA_RX_EDMA_CONTROL_TYPE;
#define XGMAC_DMA_DMA_RX_EDMA_CONTROL_REDM_MASK (0xc0000000UL)
#define XGMAC_DMA_DMA_RX_EDMA_CONTROL_REDM_SHIFT (30UL)
#define XGMAC_DMA_DMA_RX_EDMA_CONTROL_RDPS_MASK (0x3UL)
#define XGMAC_DMA_DMA_RX_EDMA_CONTROL_RDPS_SHIFT (0UL)




typedef uint32_t XGMAC_DMA_AXI_LPI_ENTRY_INTERVAL_TYPE;
#define XGMAC_DMA_AXI_LPI_ENTRY_INTERVAL_LPIEI_MASK (0xfUL)
#define XGMAC_DMA_AXI_LPI_ENTRY_INTERVAL_LPIEI_SHIFT (0UL)




typedef uint32_t XGMAC_DMA_DMA_SAFETY_INTERRUPT_STATUS_TYPE;
#define XGMAC_DMA_DMA_SAFETY_INTERRUPT_STATUS_MCSIS_MASK (0x80000000UL)
#define XGMAC_DMA_DMA_SAFETY_INTERRUPT_STATUS_MCSIS_SHIFT (31UL)
#define XGMAC_DMA_DMA_SAFETY_INTERRUPT_STATUS_MSUIS_MASK (0x20000000UL)
#define XGMAC_DMA_DMA_SAFETY_INTERRUPT_STATUS_MSUIS_SHIFT (29UL)
#define XGMAC_DMA_DMA_SAFETY_INTERRUPT_STATUS_MSCIS_MASK (0x10000000UL)
#define XGMAC_DMA_DMA_SAFETY_INTERRUPT_STATUS_MSCIS_SHIFT (28UL)
#define XGMAC_DMA_DMA_SAFETY_INTERRUPT_STATUS_DEUIS_MASK (0x2UL)
#define XGMAC_DMA_DMA_SAFETY_INTERRUPT_STATUS_DEUIS_SHIFT (1UL)
#define XGMAC_DMA_DMA_SAFETY_INTERRUPT_STATUS_DECIS_MASK (0x1UL)
#define XGMAC_DMA_DMA_SAFETY_INTERRUPT_STATUS_DECIS_SHIFT (0UL)




typedef uint32_t XGMAC_DMA_DMA_ECC_INTERRUPT_ENABLE_TYPE;
#define XGMAC_DMA_DMA_ECC_INTERRUPT_ENABLE_DCEIE_MASK (0x2UL)
#define XGMAC_DMA_DMA_ECC_INTERRUPT_ENABLE_DCEIE_SHIFT (1UL)




typedef uint32_t XGMAC_DMA_DMA_ECC_INTERRUPT_STATUS_TYPE;
#define XGMAC_DMA_DMA_ECC_INTERRUPT_STATUS_DUES_MASK (0x40UL)
#define XGMAC_DMA_DMA_ECC_INTERRUPT_STATUS_DUES_SHIFT (6UL)
#define XGMAC_DMA_DMA_ECC_INTERRUPT_STATUS_DAMS_MASK (0x20UL)
#define XGMAC_DMA_DMA_ECC_INTERRUPT_STATUS_DAMS_SHIFT (5UL)
#define XGMAC_DMA_DMA_ECC_INTERRUPT_STATUS_DCES_MASK (0x10UL)
#define XGMAC_DMA_DMA_ECC_INTERRUPT_STATUS_DCES_SHIFT (4UL)




typedef uint32_t XGMAC_DMA_DMA_DPP_CONTROL_TYPE;
#define XGMAC_DMA_DMA_DPP_CONTROL_IPERD_MASK (0x30000UL)
#define XGMAC_DMA_DMA_DPP_CONTROL_IPERD_SHIFT (16UL)
#define XGMAC_DMA_DMA_DPP_CONTROL_IPETD_MASK (0xffUL)
#define XGMAC_DMA_DMA_DPP_CONTROL_IPETD_SHIFT (0UL)




typedef uint32_t XGMAC_DMA_DMA_DPP_INTERRUPT_STATUS_TYPE;
#define XGMAC_DMA_DMA_DPP_INTERRUPT_STATUS_RDPES_MASK (0x30000UL)
#define XGMAC_DMA_DMA_DPP_INTERRUPT_STATUS_RDPES_SHIFT (16UL)
#define XGMAC_DMA_DMA_DPP_INTERRUPT_STATUS_TDPES_MASK (0xffUL)
#define XGMAC_DMA_DMA_DPP_INTERRUPT_STATUS_TDPES_SHIFT (0UL)




typedef uint32_t XGMAC_DMA_DMA_CH_IND_CTRL_TYPE;
#define XGMAC_DMA_DMA_CH_IND_CTRL_MSEL_MASK (0xf0000UL)
#define XGMAC_DMA_DMA_CH_IND_CTRL_MSEL_SHIFT (16UL)
#define XGMAC_DMA_DMA_CH_IND_CTRL_AOFF_MASK (0xf00UL)
#define XGMAC_DMA_DMA_CH_IND_CTRL_AOFF_SHIFT (8UL)
#define XGMAC_DMA_DMA_CH_IND_CTRL_AUTO_MASK (0x30UL)
#define XGMAC_DMA_DMA_CH_IND_CTRL_AUTO_SHIFT (4UL)
#define XGMAC_DMA_DMA_CH_IND_CTRL_CT_MASK (0x2UL)
#define XGMAC_DMA_DMA_CH_IND_CTRL_CT_SHIFT (1UL)
#define XGMAC_DMA_DMA_CH_IND_CTRL_OB_MASK (0x1UL)
#define XGMAC_DMA_DMA_CH_IND_CTRL_OB_SHIFT (0UL)




typedef uint32_t XGMAC_DMA_DMA_CH_IND_DATA_TYPE;
#define XGMAC_DMA_DMA_CH_IND_DATA_WT_MASK (0x7fUL)
#define XGMAC_DMA_DMA_CH_IND_DATA_WT_SHIFT (0UL)




typedef volatile struct sXGMAC_DMA_RDBType {
    XGMAC_DMA_RESERVED_TYPE rsvd0[12288]; /* OFFSET: 0x0 */
    XGMAC_DMA_DMA_MODE_TYPE dma_mode; /* OFFSET: 0x3000 */
    XGMAC_DMA_DMA_SYSBUS_MODE_TYPE dma_sysbus_mode; /* OFFSET: 0x3004 */
    XGMAC_DMA_DMA_INTERRUPT_STATUS_TYPE dma_interrupt_status; /* OFFSET: 0x3008 */
    XGMAC_DMA_RESERVED_TYPE rsvd1[4]; /* OFFSET: 0x300c */
    XGMAC_DMA_AXI_TX_AR_ACE_CONTROL_TYPE axi_tx_ar_ace_control; /* OFFSET: 0x3010 */
    XGMAC_DMA_RESERVED_TYPE rsvd2[4]; /* OFFSET: 0x3014 */
    XGMAC_DMA_AXI_RX_AW_ACE_CONTROL_TYPE axi_rx_aw_ace_control; /* OFFSET: 0x3018 */
    XGMAC_DMA_AXI_TXRX_AWAR_ACE_CONTROL_TYPE axi_txrx_awar_ace_control; /* OFFSET: 0x301c */
    XGMAC_DMA_DMA_DEBUG_STATUS0_TYPE dma_debug_status0; /* OFFSET: 0x3020 */
    XGMAC_DMA_DMA_DEBUG_STATUS1_TYPE dma_debug_status1; /* OFFSET: 0x3024 */
    XGMAC_DMA_RESERVED_TYPE rsvd3[4]; /* OFFSET: 0x3028 */
    XGMAC_DMA_DMA_DEBUG_STATUS3_TYPE dma_debug_status2; /* OFFSET: 0x302c */
    XGMAC_DMA_RESERVED_TYPE rsvd4[16]; /* OFFSET: 0x3030 */
    XGMAC_DMA_DMA_TX_EDMA_CONTROL_TYPE dma_tx_edma_control; /* OFFSET: 0x3040 */
    XGMAC_DMA_DMA_RX_EDMA_CONTROL_TYPE dma_rx_edma_control; /* OFFSET: 0x3044 */
    XGMAC_DMA_RESERVED_TYPE rsvd5[8]; /* OFFSET: 0x3048 */
    XGMAC_DMA_AXI_LPI_ENTRY_INTERVAL_TYPE axi_lpi_entry_interval; /* OFFSET: 0x3050 */
    XGMAC_DMA_RESERVED_TYPE rsvd6[16]; /* OFFSET: 0x3054 */
    XGMAC_DMA_DMA_SAFETY_INTERRUPT_STATUS_TYPE dma_safety_interrupt_status; /* OFFSET: 0x3064 */
    XGMAC_DMA_DMA_ECC_INTERRUPT_ENABLE_TYPE dma_ecc_interrupt_enable; /* OFFSET: 0x3068 */
    XGMAC_DMA_DMA_ECC_INTERRUPT_STATUS_TYPE dma_ecc_interrupt_status; /* OFFSET: 0x306c */
    XGMAC_DMA_DMA_DPP_CONTROL_TYPE dma_dpp_control; /* OFFSET: 0x3070 */
    XGMAC_DMA_DMA_DPP_INTERRUPT_STATUS_TYPE dma_dpp_interrupt_status; /* OFFSET: 0x3074 */
    XGMAC_DMA_RESERVED_TYPE rsvd7[8]; /* OFFSET: 0x3078 */
    XGMAC_DMA_DMA_CH_IND_CTRL_TYPE dma_ch_ind_ctrl; /* OFFSET: 0x3080 */
    XGMAC_DMA_DMA_CH_IND_DATA_TYPE dma_ch_ind_data; /* OFFSET: 0x3084 */
} XGMAC_DMA_RDBType;


#define XG_DMA_BASE                     ((uintptr_t)(0xE02F0000UL))



#define XGMAC_DMA_MAX_HW_ID             (1UL)

#endif /* XGMAC_DMA_RDB_H */
