/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file xgmac_dma_ch0_rdb.h
    @brief RDB File for XGMAC_DMA_CH0

    @version BCM89580_A0_20230125_RDB
*/

#ifndef XGMAC_DMA_CH0_RDB_H
#define XGMAC_DMA_CH0_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t XGMAC_DMA_CH0_RESERVED_TYPE;




typedef uint32_t XGMAC_DMA_CH0_DMA_CH0_CONTROL_TYPE;
#define XGMAC_DMA_CH0_DMA_CH0_CONTROL_SPH_MASK (0x1000000UL)
#define XGMAC_DMA_CH0_DMA_CH0_CONTROL_SPH_SHIFT (24UL)
#define XGMAC_DMA_CH0_DMA_CH0_CONTROL_DSL_MASK (0x1c0000UL)
#define XGMAC_DMA_CH0_DMA_CH0_CONTROL_DSL_SHIFT (18UL)
#define XGMAC_DMA_CH0_DMA_CH0_CONTROL_PBLX8_MASK (0x10000UL)
#define XGMAC_DMA_CH0_DMA_CH0_CONTROL_PBLX8_SHIFT (16UL)




typedef uint32_t XGMAC_DMA_CH0_DMA_CH0_TX_CONTROL_TYPE;
#define XGMAC_DMA_CH0_DMA_CH0_TX_CONTROL_TQOS_MASK (0xf000000UL)
#define XGMAC_DMA_CH0_DMA_CH0_TX_CONTROL_TQOS_SHIFT (24UL)
#define XGMAC_DMA_CH0_DMA_CH0_TX_CONTROL_TXPBL_MASK (0x3f0000UL)
#define XGMAC_DMA_CH0_DMA_CH0_TX_CONTROL_TXPBL_SHIFT (16UL)
#define XGMAC_DMA_CH0_DMA_CH0_TX_CONTROL_ST_MASK (0x1UL)
#define XGMAC_DMA_CH0_DMA_CH0_TX_CONTROL_ST_SHIFT (0UL)




typedef uint32_t XGMAC_DMA_CH0_DMA_CH0_RX_CONTROL_TYPE;
#define XGMAC_DMA_CH0_DMA_CH0_RX_CONTROL_RPF_MASK (0x80000000UL)
#define XGMAC_DMA_CH0_DMA_CH0_RX_CONTROL_RPF_SHIFT (31UL)
#define XGMAC_DMA_CH0_DMA_CH0_RX_CONTROL_RQOS_MASK (0xf000000UL)
#define XGMAC_DMA_CH0_DMA_CH0_RX_CONTROL_RQOS_SHIFT (24UL)
#define XGMAC_DMA_CH0_DMA_CH0_RX_CONTROL_RXPBL_MASK (0x3f0000UL)
#define XGMAC_DMA_CH0_DMA_CH0_RX_CONTROL_RXPBL_SHIFT (16UL)
#define XGMAC_DMA_CH0_DMA_CH0_RX_CONTROL_RBSZ_MASK (0x7ff0UL)
#define XGMAC_DMA_CH0_DMA_CH0_RX_CONTROL_RBSZ_SHIFT (4UL)
#define XGMAC_DMA_CH0_DMA_CH0_RX_CONTROL_SR_MASK (0x1UL)
#define XGMAC_DMA_CH0_DMA_CH0_RX_CONTROL_SR_SHIFT (0UL)




typedef uint32_t XGMAC_DMA_CH0_DMA_CH0_TXDESC_LIST_LADDRESS_TYPE;
#define XGMAC_DMA_CH0_DMA_CH0_TXDESC_LIST_LADDRESS_TDESLA_MASK (0xfffffff8UL)
#define XGMAC_DMA_CH0_DMA_CH0_TXDESC_LIST_LADDRESS_TDESLA_SHIFT (3UL)




typedef uint32_t XGMAC_DMA_CH0_DMA_CH0_RXDESC_LIST_LADDRESS_TYPE;
#define XGMAC_DMA_CH0_DMA_CH0_RXDESC_LIST_LADDRESS_RDESLA_MASK (0xfffffff8UL)
#define XGMAC_DMA_CH0_DMA_CH0_RXDESC_LIST_LADDRESS_RDESLA_SHIFT (3UL)




typedef uint32_t XGMAC_DMA_CH0_DMA_CH0_TXDESC_TAIL_LPOINTER_TYPE;
#define XGMAC_DMA_CH0_DMA_CH0_TXDESC_TAIL_LPOINTER_TDT_MASK (0xfffffff8UL)
#define XGMAC_DMA_CH0_DMA_CH0_TXDESC_TAIL_LPOINTER_TDT_SHIFT (3UL)




typedef uint32_t XGMAC_DMA_CH0_DMA_CH0_RXDESC_TAIL_LPOINTER_TYPE;
#define XGMAC_DMA_CH0_DMA_CH0_RXDESC_TAIL_LPOINTER_RDT_MASK (0xfffffff8UL)
#define XGMAC_DMA_CH0_DMA_CH0_RXDESC_TAIL_LPOINTER_RDT_SHIFT (3UL)




typedef uint32_t XGMAC_DMA_CH0_DMA_CH0_TX_CONTROL2_TYPE;
#define XGMAC_DMA_CH0_DMA_CH0_TX_CONTROL2_ORRQ_MASK (0x1000000UL)
#define XGMAC_DMA_CH0_DMA_CH0_TX_CONTROL2_ORRQ_SHIFT (24UL)
#define XGMAC_DMA_CH0_DMA_CH0_TX_CONTROL2_TDRL_MASK (0xffffUL)
#define XGMAC_DMA_CH0_DMA_CH0_TX_CONTROL2_TDRL_SHIFT (0UL)




typedef uint32_t XGMAC_DMA_CH0_DMA_CH0_RX_CONTROL2_TYPE;
#define XGMAC_DMA_CH0_DMA_CH0_RX_CONTROL2_OWRQ_MASK (0x1000000UL)
#define XGMAC_DMA_CH0_DMA_CH0_RX_CONTROL2_OWRQ_SHIFT (24UL)
#define XGMAC_DMA_CH0_DMA_CH0_RX_CONTROL2_ARBS_MASK (0xfe0000UL)
#define XGMAC_DMA_CH0_DMA_CH0_RX_CONTROL2_ARBS_SHIFT (17UL)
#define XGMAC_DMA_CH0_DMA_CH0_RX_CONTROL2_RDRL_MASK (0xffffUL)
#define XGMAC_DMA_CH0_DMA_CH0_RX_CONTROL2_RDRL_SHIFT (0UL)




typedef uint32_t XGMAC_DMA_CH0_DMA_CH0_INTERRUPT_ENABLE_TYPE;
#define XGMAC_DMA_CH0_DMA_CH0_INTERRUPT_ENABLE_NIE_MASK (0x8000UL)
#define XGMAC_DMA_CH0_DMA_CH0_INTERRUPT_ENABLE_NIE_SHIFT (15UL)
#define XGMAC_DMA_CH0_DMA_CH0_INTERRUPT_ENABLE_AIE_MASK (0x4000UL)
#define XGMAC_DMA_CH0_DMA_CH0_INTERRUPT_ENABLE_AIE_SHIFT (14UL)
#define XGMAC_DMA_CH0_DMA_CH0_INTERRUPT_ENABLE_CDEE_MASK (0x2000UL)
#define XGMAC_DMA_CH0_DMA_CH0_INTERRUPT_ENABLE_CDEE_SHIFT (13UL)
#define XGMAC_DMA_CH0_DMA_CH0_INTERRUPT_ENABLE_FBEE_MASK (0x1000UL)
#define XGMAC_DMA_CH0_DMA_CH0_INTERRUPT_ENABLE_FBEE_SHIFT (12UL)
#define XGMAC_DMA_CH0_DMA_CH0_INTERRUPT_ENABLE_DDEE_MASK (0x200UL)
#define XGMAC_DMA_CH0_DMA_CH0_INTERRUPT_ENABLE_DDEE_SHIFT (9UL)
#define XGMAC_DMA_CH0_DMA_CH0_INTERRUPT_ENABLE_RSE_MASK (0x100UL)
#define XGMAC_DMA_CH0_DMA_CH0_INTERRUPT_ENABLE_RSE_SHIFT (8UL)
#define XGMAC_DMA_CH0_DMA_CH0_INTERRUPT_ENABLE_RBUE_MASK (0x80UL)
#define XGMAC_DMA_CH0_DMA_CH0_INTERRUPT_ENABLE_RBUE_SHIFT (7UL)
#define XGMAC_DMA_CH0_DMA_CH0_INTERRUPT_ENABLE_RIE_MASK (0x40UL)
#define XGMAC_DMA_CH0_DMA_CH0_INTERRUPT_ENABLE_RIE_SHIFT (6UL)
#define XGMAC_DMA_CH0_DMA_CH0_INTERRUPT_ENABLE_TBUE_MASK (0x4UL)
#define XGMAC_DMA_CH0_DMA_CH0_INTERRUPT_ENABLE_TBUE_SHIFT (2UL)
#define XGMAC_DMA_CH0_DMA_CH0_INTERRUPT_ENABLE_TXSE_MASK (0x2UL)
#define XGMAC_DMA_CH0_DMA_CH0_INTERRUPT_ENABLE_TXSE_SHIFT (1UL)
#define XGMAC_DMA_CH0_DMA_CH0_INTERRUPT_ENABLE_TIE_MASK (0x1UL)
#define XGMAC_DMA_CH0_DMA_CH0_INTERRUPT_ENABLE_TIE_SHIFT (0UL)




typedef uint32_t XGMAC_DMA_CH0_DMA_CH0_RX_INTERRUPT_WATCHDOG_TIMER_TYPE;
#define XGMAC_DMA_CH0_DMA_CH0_RX_INTERRUPT_WATCHDOG_TIMER_PSEL_MASK (0x80000000UL)
#define XGMAC_DMA_CH0_DMA_CH0_RX_INTERRUPT_WATCHDOG_TIMER_PSEL_SHIFT (31UL)
#define XGMAC_DMA_CH0_DMA_CH0_RX_INTERRUPT_WATCHDOG_TIMER_RBCT_MASK (0x3ff0000UL)
#define XGMAC_DMA_CH0_DMA_CH0_RX_INTERRUPT_WATCHDOG_TIMER_RBCT_SHIFT (16UL)
#define XGMAC_DMA_CH0_DMA_CH0_RX_INTERRUPT_WATCHDOG_TIMER_RWTU_MASK (0x3000UL)
#define XGMAC_DMA_CH0_DMA_CH0_RX_INTERRUPT_WATCHDOG_TIMER_RWTU_SHIFT (12UL)
#define XGMAC_DMA_CH0_DMA_CH0_RX_INTERRUPT_WATCHDOG_TIMER_RWT_MASK (0xffUL)
#define XGMAC_DMA_CH0_DMA_CH0_RX_INTERRUPT_WATCHDOG_TIMER_RWT_SHIFT (0UL)




typedef uint32_t XGMAC_DMA_CH0_DMA_CH0_CURRENT_APP_TXDESC_L_TYPE;
#define XGMAC_DMA_CH0_DMA_CH0_CURRENT_APP_TXDESC_L_CURTDESAPTR_MASK (0xffffffffUL)
#define XGMAC_DMA_CH0_DMA_CH0_CURRENT_APP_TXDESC_L_CURTDESAPTR_SHIFT (0UL)




typedef uint32_t XGMAC_DMA_CH0_DMA_CH0_CURRENT_APP_RXDESC_L_TYPE;
#define XGMAC_DMA_CH0_DMA_CH0_CURRENT_APP_RXDESC_L_CURRDESAPTR_MASK (0xffffffffUL)
#define XGMAC_DMA_CH0_DMA_CH0_CURRENT_APP_RXDESC_L_CURRDESAPTR_SHIFT (0UL)




typedef uint32_t XGMAC_DMA_CH0_DMA_CH0_CURRENT_APP_TXBUFFER_L_TYPE;
#define XGMAC_DMA_CH0_DMA_CH0_CURRENT_APP_TXBUFFER_L_CURTBUFAPTR_MASK (0xffffffffUL)
#define XGMAC_DMA_CH0_DMA_CH0_CURRENT_APP_TXBUFFER_L_CURTBUFAPTR_SHIFT (0UL)




typedef uint32_t XGMAC_DMA_CH0_DMA_CH0_CURRENT_APP_RXBUFFER_L_TYPE;
#define XGMAC_DMA_CH0_DMA_CH0_CURRENT_APP_RXBUFFER_L_CURRBUFAPTR_MASK (0xffffffffUL)
#define XGMAC_DMA_CH0_DMA_CH0_CURRENT_APP_RXBUFFER_L_CURRBUFAPTR_SHIFT (0UL)




typedef uint32_t XGMAC_DMA_CH0_DMA_CH0_STATUS_TYPE;
#define XGMAC_DMA_CH0_DMA_CH0_STATUS_REB_MASK (0x380000UL)
#define XGMAC_DMA_CH0_DMA_CH0_STATUS_REB_SHIFT (19UL)
#define XGMAC_DMA_CH0_DMA_CH0_STATUS_TEB_MASK (0x70000UL)
#define XGMAC_DMA_CH0_DMA_CH0_STATUS_TEB_SHIFT (16UL)
#define XGMAC_DMA_CH0_DMA_CH0_STATUS_NIS_MASK (0x8000UL)
#define XGMAC_DMA_CH0_DMA_CH0_STATUS_NIS_SHIFT (15UL)
#define XGMAC_DMA_CH0_DMA_CH0_STATUS_AIS_MASK (0x4000UL)
#define XGMAC_DMA_CH0_DMA_CH0_STATUS_AIS_SHIFT (14UL)
#define XGMAC_DMA_CH0_DMA_CH0_STATUS_CDE_MASK (0x2000UL)
#define XGMAC_DMA_CH0_DMA_CH0_STATUS_CDE_SHIFT (13UL)
#define XGMAC_DMA_CH0_DMA_CH0_STATUS_FBE_MASK (0x1000UL)
#define XGMAC_DMA_CH0_DMA_CH0_STATUS_FBE_SHIFT (12UL)
#define XGMAC_DMA_CH0_DMA_CH0_STATUS_DDE_MASK (0x200UL)
#define XGMAC_DMA_CH0_DMA_CH0_STATUS_DDE_SHIFT (9UL)
#define XGMAC_DMA_CH0_DMA_CH0_STATUS_RPS_MASK (0x100UL)
#define XGMAC_DMA_CH0_DMA_CH0_STATUS_RPS_SHIFT (8UL)
#define XGMAC_DMA_CH0_DMA_CH0_STATUS_RBU_MASK (0x80UL)
#define XGMAC_DMA_CH0_DMA_CH0_STATUS_RBU_SHIFT (7UL)
#define XGMAC_DMA_CH0_DMA_CH0_STATUS_RI_MASK (0x40UL)
#define XGMAC_DMA_CH0_DMA_CH0_STATUS_RI_SHIFT (6UL)
#define XGMAC_DMA_CH0_DMA_CH0_STATUS_TBU_MASK (0x4UL)
#define XGMAC_DMA_CH0_DMA_CH0_STATUS_TBU_SHIFT (2UL)
#define XGMAC_DMA_CH0_DMA_CH0_STATUS_TPS_MASK (0x2UL)
#define XGMAC_DMA_CH0_DMA_CH0_STATUS_TPS_SHIFT (1UL)
#define XGMAC_DMA_CH0_DMA_CH0_STATUS_TI_MASK (0x1UL)
#define XGMAC_DMA_CH0_DMA_CH0_STATUS_TI_SHIFT (0UL)




typedef uint32_t XGMAC_DMA_CH0_DMA_CH0_DEBUG_STATUS_TYPE;
#define XGMAC_DMA_CH0_DMA_CH0_DEBUG_STATUS_RDWS_MASK (0x70000000UL)
#define XGMAC_DMA_CH0_DMA_CH0_DEBUG_STATUS_RDWS_SHIFT (28UL)
#define XGMAC_DMA_CH0_DMA_CH0_DEBUG_STATUS_RDTS_MASK (0xff80000UL)
#define XGMAC_DMA_CH0_DMA_CH0_DEBUG_STATUS_RDTS_SHIFT (19UL)
#define XGMAC_DMA_CH0_DMA_CH0_DEBUG_STATUS_RDFS_MASK (0x70000UL)
#define XGMAC_DMA_CH0_DMA_CH0_DEBUG_STATUS_RDFS_SHIFT (16UL)
#define XGMAC_DMA_CH0_DMA_CH0_DEBUG_STATUS_TDWS_MASK (0x7000UL)
#define XGMAC_DMA_CH0_DMA_CH0_DEBUG_STATUS_TDWS_SHIFT (12UL)
#define XGMAC_DMA_CH0_DMA_CH0_DEBUG_STATUS_TDTS_MASK (0xf00UL)
#define XGMAC_DMA_CH0_DMA_CH0_DEBUG_STATUS_TDTS_SHIFT (8UL)
#define XGMAC_DMA_CH0_DMA_CH0_DEBUG_STATUS_TDRS_MASK (0xc0UL)
#define XGMAC_DMA_CH0_DMA_CH0_DEBUG_STATUS_TDRS_SHIFT (6UL)
#define XGMAC_DMA_CH0_DMA_CH0_DEBUG_STATUS_TDXS_MASK (0x38UL)
#define XGMAC_DMA_CH0_DMA_CH0_DEBUG_STATUS_TDXS_SHIFT (3UL)
#define XGMAC_DMA_CH0_DMA_CH0_DEBUG_STATUS_TDFS_MASK (0x7UL)
#define XGMAC_DMA_CH0_DMA_CH0_DEBUG_STATUS_TDFS_SHIFT (0UL)




typedef uint32_t XGMAC_DMA_CH0_DC0DMCFL_TYPE;
#define XGMAC_DMA_CH0_DC0DMCFL_RX_FILL_LVL_MASK (0x7f0000UL)
#define XGMAC_DMA_CH0_DC0DMCFL_RX_FILL_LVL_SHIFT (16UL)
#define XGMAC_DMA_CH0_DC0DMCFL_TX_FILL_LVL_MASK (0x7fUL)
#define XGMAC_DMA_CH0_DC0DMCFL_TX_FILL_LVL_SHIFT (0UL)




typedef uint32_t XGMAC_DMA_CH0_DMA_CH0_MISS_PACKET_CNT_TYPE;
#define XGMAC_DMA_CH0_DMA_CH0_MISS_PACKET_CNT_MFCO_MASK (0x8000UL)
#define XGMAC_DMA_CH0_DMA_CH0_MISS_PACKET_CNT_MFCO_SHIFT (15UL)
#define XGMAC_DMA_CH0_DMA_CH0_MISS_PACKET_CNT_MDC_MASK (0x7ffUL)
#define XGMAC_DMA_CH0_DMA_CH0_MISS_PACKET_CNT_MDC_SHIFT (0UL)




typedef uint32_t XGMAC_DMA_CH0_DC0TDXRO_TYPE;
#define XGMAC_DMA_CH0_DC0TDXRO_DESC_OFFSET_MASK (0xffffUL)
#define XGMAC_DMA_CH0_DC0TDXRO_DESC_OFFSET_SHIFT (0UL)




typedef uint32_t XGMAC_DMA_CH0_DC0RDXRO_TYPE;
#define XGMAC_DMA_CH0_DC0RDXRO_DESC_OFFSET_MASK (0xffffUL)
#define XGMAC_DMA_CH0_DC0RDXRO_DESC_OFFSET_SHIFT (0UL)




typedef uint32_t XGMAC_DMA_CH0_DC0TDWRO_TYPE;
#define XGMAC_DMA_CH0_DC0TDWRO_DESC_OFFSET_MASK (0xffffUL)
#define XGMAC_DMA_CH0_DC0TDWRO_DESC_OFFSET_SHIFT (0UL)




typedef uint32_t XGMAC_DMA_CH0_DC0RDWRO_TYPE;
#define XGMAC_DMA_CH0_DC0RDWRO_DESC_OFFSET_MASK (0xffffUL)
#define XGMAC_DMA_CH0_DC0RDWRO_DESC_OFFSET_SHIFT (0UL)




typedef volatile struct sXGMAC_DMA_CH0_RDBType {
    XGMAC_DMA_CH0_RESERVED_TYPE rsvd0[12544]; /* OFFSET: 0x0 */
    XGMAC_DMA_CH0_DMA_CH0_CONTROL_TYPE control; /* OFFSET: 0x3100 */
    XGMAC_DMA_CH0_DMA_CH0_TX_CONTROL_TYPE tx_control; /* OFFSET: 0x3104 */
    XGMAC_DMA_CH0_DMA_CH0_RX_CONTROL_TYPE rx_control; /* OFFSET: 0x3108 */
    XGMAC_DMA_CH0_RESERVED_TYPE rsvd1[8]; /* OFFSET: 0x310c */
    XGMAC_DMA_CH0_DMA_CH0_TXDESC_LIST_LADDRESS_TYPE txdesc_list_laddress; /* OFFSET: 0x3114 */
    XGMAC_DMA_CH0_RESERVED_TYPE rsvd2[4]; /* OFFSET: 0x3118 */
    XGMAC_DMA_CH0_DMA_CH0_RXDESC_LIST_LADDRESS_TYPE rxdesc_list_laddress; /* OFFSET: 0x311c */
    XGMAC_DMA_CH0_RESERVED_TYPE rsvd3[4]; /* OFFSET: 0x3120 */
    XGMAC_DMA_CH0_DMA_CH0_TXDESC_TAIL_LPOINTER_TYPE txdesc_tail_lpointer; /* OFFSET: 0x3124 */
    XGMAC_DMA_CH0_RESERVED_TYPE rsvd4[4]; /* OFFSET: 0x3128 */
    XGMAC_DMA_CH0_DMA_CH0_RXDESC_TAIL_LPOINTER_TYPE rxdesc_tail_lpointer; /* OFFSET: 0x312c */
    XGMAC_DMA_CH0_DMA_CH0_TX_CONTROL2_TYPE tx_control2; /* OFFSET: 0x3130 */
    XGMAC_DMA_CH0_DMA_CH0_RX_CONTROL2_TYPE rx_control2; /* OFFSET: 0x3134 */
    XGMAC_DMA_CH0_DMA_CH0_INTERRUPT_ENABLE_TYPE interrupt_enable; /* OFFSET: 0x3138 */
    XGMAC_DMA_CH0_DMA_CH0_RX_INTERRUPT_WATCHDOG_TIMER_TYPE rx_interrupt_watchdog_timer; /* OFFSET: 0x313c */
    XGMAC_DMA_CH0_RESERVED_TYPE rsvd5[4]; /* OFFSET: 0x3140 */
    XGMAC_DMA_CH0_DMA_CH0_CURRENT_APP_TXDESC_L_TYPE current_app_txdesc_l; /* OFFSET: 0x3144 */
    XGMAC_DMA_CH0_RESERVED_TYPE rsvd6[4]; /* OFFSET: 0x3148 */
    XGMAC_DMA_CH0_DMA_CH0_CURRENT_APP_RXDESC_L_TYPE current_app_rxdesc_l; /* OFFSET: 0x314c */
    XGMAC_DMA_CH0_RESERVED_TYPE rsvd7[4]; /* OFFSET: 0x3150 */
    XGMAC_DMA_CH0_DMA_CH0_CURRENT_APP_TXBUFFER_L_TYPE current_app_txbuffer_l; /* OFFSET: 0x3154 */
    XGMAC_DMA_CH0_RESERVED_TYPE rsvd8[4]; /* OFFSET: 0x3158 */
    XGMAC_DMA_CH0_DMA_CH0_CURRENT_APP_RXBUFFER_L_TYPE current_app_rxbuffer_l; /* OFFSET: 0x315c */
    XGMAC_DMA_CH0_DMA_CH0_STATUS_TYPE status; /* OFFSET: 0x3160 */
    XGMAC_DMA_CH0_DMA_CH0_DEBUG_STATUS_TYPE debug_status; /* OFFSET: 0x3164 */
    XGMAC_DMA_CH0_DC0DMCFL_TYPE desc_mem_cache_fill_level; /* OFFSET: 0x3168 */
    XGMAC_DMA_CH0_DMA_CH0_MISS_PACKET_CNT_TYPE miss_packet_cnt; /* OFFSET: 0x316c */
    XGMAC_DMA_CH0_DC0TDXRO_TYPE tx_data_xfer_ring_offset; /* OFFSET: 0x3170 */
    XGMAC_DMA_CH0_DC0RDXRO_TYPE rx_data_xfer_ring_offset; /* OFFSET: 0x3174 */
    XGMAC_DMA_CH0_DC0TDWRO_TYPE tx_desc_write_ring_offset; /* OFFSET: 0x3178 */
    XGMAC_DMA_CH0_DC0RDWRO_TYPE rx_desc_write_ring_offset; /* OFFSET: 0x317c */
} XGMAC_DMA_CH0_RDBType;


#define XG_DMA_CH0_BASE                 ((uintptr_t)(0xE02F0000UL))



#define XGMAC_DMA_CH0_MAX_HW_ID         (1UL)

#endif /* XGMAC_DMA_CH0_RDB_H */
