/*****************************************************************************
 Copyright 2024 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file xgmac_mtl_tcq1_rdb.h
    @brief RDB File for XGMAC_MTL_TCQ1

    @version BCM89580_A0_20230125_RDB
*/

#ifndef XGMAC_MTL_TCQ1_RDB_H
#define XGMAC_MTL_TCQ1_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t XGMAC_MTL_TCQ1_RESERVED_TYPE;




typedef uint32_t XGMAC_MTL_TCQ1_MTL_TXQ1_OPERATION_MODE_TYPE;
#define XGMAC_MTL_TCQ1_MTL_TXQ1_OPERATION_MODE_RESERVED_31_Y_MASK (0xff800000UL)
#define XGMAC_MTL_TCQ1_MTL_TXQ1_OPERATION_MODE_RESERVED_31_Y_SHIFT (23UL)
#define XGMAC_MTL_TCQ1_MTL_TXQ1_OPERATION_MODE_TQS_MASK (0x7f0000UL)
#define XGMAC_MTL_TCQ1_MTL_TXQ1_OPERATION_MODE_TQS_SHIFT (16UL)
#define XGMAC_MTL_TCQ1_MTL_TXQ1_OPERATION_MODE_RESERVED_15_Y_MASK (0xf800UL)
#define XGMAC_MTL_TCQ1_MTL_TXQ1_OPERATION_MODE_RESERVED_15_Y_SHIFT (11UL)
#define XGMAC_MTL_TCQ1_MTL_TXQ1_OPERATION_MODE_Q2TCMAP_MASK (0x700UL)
#define XGMAC_MTL_TCQ1_MTL_TXQ1_OPERATION_MODE_Q2TCMAP_SHIFT (8UL)
#define XGMAC_MTL_TCQ1_MTL_TXQ1_OPERATION_MODE_RESERVED_7_MASK (0x80UL)
#define XGMAC_MTL_TCQ1_MTL_TXQ1_OPERATION_MODE_RESERVED_7_SHIFT (7UL)
#define XGMAC_MTL_TCQ1_MTL_TXQ1_OPERATION_MODE_TTC_MASK (0x70UL)
#define XGMAC_MTL_TCQ1_MTL_TXQ1_OPERATION_MODE_TTC_SHIFT (4UL)
#define XGMAC_MTL_TCQ1_MTL_TXQ1_OPERATION_MODE_TXQEN_MASK (0xcUL)
#define XGMAC_MTL_TCQ1_MTL_TXQ1_OPERATION_MODE_TXQEN_SHIFT (2UL)
#define XGMAC_MTL_TCQ1_MTL_TXQ1_OPERATION_MODE_TSF_MASK (0x2UL)
#define XGMAC_MTL_TCQ1_MTL_TXQ1_OPERATION_MODE_TSF_SHIFT (1UL)
#define XGMAC_MTL_TCQ1_MTL_TXQ1_OPERATION_MODE_FTQ_MASK (0x1UL)
#define XGMAC_MTL_TCQ1_MTL_TXQ1_OPERATION_MODE_FTQ_SHIFT (0UL)




typedef uint32_t XGMAC_MTL_TCQ1_MTL_TXQ1_UNDERFLOW_TYPE;
#define XGMAC_MTL_TCQ1_MTL_TXQ1_UNDERFLOW_RESERVED_31_16_MASK (0xffff0000UL)
#define XGMAC_MTL_TCQ1_MTL_TXQ1_UNDERFLOW_RESERVED_31_16_SHIFT (16UL)
#define XGMAC_MTL_TCQ1_MTL_TXQ1_UNDERFLOW_UFCNTOVF_MASK (0x8000UL)
#define XGMAC_MTL_TCQ1_MTL_TXQ1_UNDERFLOW_UFCNTOVF_SHIFT (15UL)
#define XGMAC_MTL_TCQ1_MTL_TXQ1_UNDERFLOW_RESERVED_14_11_MASK (0x7800UL)
#define XGMAC_MTL_TCQ1_MTL_TXQ1_UNDERFLOW_RESERVED_14_11_SHIFT (11UL)
#define XGMAC_MTL_TCQ1_MTL_TXQ1_UNDERFLOW_UFPKTCNT_MASK (0x7ffUL)
#define XGMAC_MTL_TCQ1_MTL_TXQ1_UNDERFLOW_UFPKTCNT_SHIFT (0UL)




typedef uint32_t XGMAC_MTL_TCQ1_MTL_TXQ1_DEBUG_TYPE;
#define XGMAC_MTL_TCQ1_MTL_TXQ1_DEBUG_RESERVED_31_6_MASK (0xffffffc0UL)
#define XGMAC_MTL_TCQ1_MTL_TXQ1_DEBUG_RESERVED_31_6_SHIFT (6UL)
#define XGMAC_MTL_TCQ1_MTL_TXQ1_DEBUG_TRCPSTS_MASK (0x20UL)
#define XGMAC_MTL_TCQ1_MTL_TXQ1_DEBUG_TRCPSTS_SHIFT (5UL)
#define XGMAC_MTL_TCQ1_MTL_TXQ1_DEBUG_TXQSTS_MASK (0x10UL)
#define XGMAC_MTL_TCQ1_MTL_TXQ1_DEBUG_TXQSTS_SHIFT (4UL)
#define XGMAC_MTL_TCQ1_MTL_TXQ1_DEBUG_TWCSTS_MASK (0x8UL)
#define XGMAC_MTL_TCQ1_MTL_TXQ1_DEBUG_TWCSTS_SHIFT (3UL)
#define XGMAC_MTL_TCQ1_MTL_TXQ1_DEBUG_TRCSTS_MASK (0x6UL)
#define XGMAC_MTL_TCQ1_MTL_TXQ1_DEBUG_TRCSTS_SHIFT (1UL)
#define XGMAC_MTL_TCQ1_MTL_TXQ1_DEBUG_TCPAUSED_MASK (0x1UL)
#define XGMAC_MTL_TCQ1_MTL_TXQ1_DEBUG_TCPAUSED_SHIFT (0UL)




typedef uint32_t XGMAC_MTL_TCQ1_MTL_TC1_ETS_CONTROL_TYPE;
#define XGMAC_MTL_TCQ1_MTL_TC1_ETS_CONTROL_RESERVED_31_7_MASK (0xffffff80UL)
#define XGMAC_MTL_TCQ1_MTL_TC1_ETS_CONTROL_RESERVED_31_7_SHIFT (7UL)
#define XGMAC_MTL_TCQ1_MTL_TC1_ETS_CONTROL_RESERVED_6_3_MASK (0x78UL)
#define XGMAC_MTL_TCQ1_MTL_TC1_ETS_CONTROL_RESERVED_6_3_SHIFT (3UL)
#define XGMAC_MTL_TCQ1_MTL_TC1_ETS_CONTROL_CBSEN_MASK (0x4UL)
#define XGMAC_MTL_TCQ1_MTL_TC1_ETS_CONTROL_CBSEN_SHIFT (2UL)
#define XGMAC_MTL_TCQ1_MTL_TC1_ETS_CONTROL_TSA_MASK (0x3UL)
#define XGMAC_MTL_TCQ1_MTL_TC1_ETS_CONTROL_TSA_SHIFT (0UL)




typedef uint32_t XGMAC_MTL_TCQ1_MTL_TC1_ETS_STATUS_TYPE;
#define XGMAC_MTL_TCQ1_MTL_TC1_ETS_STATUS_RESERVED_31_24_MASK (0xff000000UL)
#define XGMAC_MTL_TCQ1_MTL_TC1_ETS_STATUS_RESERVED_31_24_SHIFT (24UL)
#define XGMAC_MTL_TCQ1_MTL_TC1_ETS_STATUS_ABS_MASK (0xffffffUL)
#define XGMAC_MTL_TCQ1_MTL_TC1_ETS_STATUS_ABS_SHIFT (0UL)




typedef uint32_t XGMAC_MTL_TCQ1_MTL_TC1_QUANTUM_WEIGHT_TYPE;
#define XGMAC_MTL_TCQ1_MTL_TC1_QUANTUM_WEIGHT_RESERVED_31_21_MASK (0xffe00000UL)
#define XGMAC_MTL_TCQ1_MTL_TC1_QUANTUM_WEIGHT_RESERVED_31_21_SHIFT (21UL)
#define XGMAC_MTL_TCQ1_MTL_TC1_QUANTUM_WEIGHT_QW_MASK (0x1fffffUL)
#define XGMAC_MTL_TCQ1_MTL_TC1_QUANTUM_WEIGHT_QW_SHIFT (0UL)




typedef uint32_t XGMAC_MTL_TCQ1_MTL_RXQ1_OPERATION_MODE_TYPE;
#define XGMAC_MTL_TCQ1_MTL_RXQ1_OPERATION_MODE_RESERVED_31_Y_MASK (0xff800000UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_OPERATION_MODE_RESERVED_31_Y_SHIFT (23UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_OPERATION_MODE_RQS_MASK (0x7f0000UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_OPERATION_MODE_RQS_SHIFT (16UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_OPERATION_MODE_RESERVED_15_8_MASK (0xff00UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_OPERATION_MODE_RESERVED_15_8_SHIFT (8UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_OPERATION_MODE_EHFC_MASK (0x80UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_OPERATION_MODE_EHFC_SHIFT (7UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_OPERATION_MODE_DIS_TCP_EF_MASK (0x40UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_OPERATION_MODE_DIS_TCP_EF_SHIFT (6UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_OPERATION_MODE_RSF_MASK (0x20UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_OPERATION_MODE_RSF_SHIFT (5UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_OPERATION_MODE_FEF_MASK (0x10UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_OPERATION_MODE_FEF_SHIFT (4UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_OPERATION_MODE_FUF_MASK (0x8UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_OPERATION_MODE_FUF_SHIFT (3UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_OPERATION_MODE_RESERVED_2_MASK (0x4UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_OPERATION_MODE_RESERVED_2_SHIFT (2UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_OPERATION_MODE_RTC_MASK (0x3UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_OPERATION_MODE_RTC_SHIFT (0UL)




typedef uint32_t XGMAC_MTL_TCQ1_MR1MPOC_TYPE;
#define XGMAC_MTL_TCQ1_MR1MPOC_MISCNTOVF_MASK (0x80000000UL)
#define XGMAC_MTL_TCQ1_MR1MPOC_MISCNTOVF_SHIFT (31UL)
#define XGMAC_MTL_TCQ1_MR1MPOC_RESERVED_30_27_MASK (0x78000000UL)
#define XGMAC_MTL_TCQ1_MR1MPOC_RESERVED_30_27_SHIFT (27UL)
#define XGMAC_MTL_TCQ1_MR1MPOC_MISPKTCNT_MASK (0x7ff0000UL)
#define XGMAC_MTL_TCQ1_MR1MPOC_MISPKTCNT_SHIFT (16UL)
#define XGMAC_MTL_TCQ1_MR1MPOC_OVFCNTOVF_MASK (0x8000UL)
#define XGMAC_MTL_TCQ1_MR1MPOC_OVFCNTOVF_SHIFT (15UL)
#define XGMAC_MTL_TCQ1_MR1MPOC_RESERVED_14_11_MASK (0x7800UL)
#define XGMAC_MTL_TCQ1_MR1MPOC_RESERVED_14_11_SHIFT (11UL)
#define XGMAC_MTL_TCQ1_MR1MPOC_OVFPKTCNT_MASK (0x7ffUL)
#define XGMAC_MTL_TCQ1_MR1MPOC_OVFPKTCNT_SHIFT (0UL)




typedef uint32_t XGMAC_MTL_TCQ1_MTL_RXQ1_DEBUG_TYPE;
#define XGMAC_MTL_TCQ1_MTL_RXQ1_DEBUG_RESERVED_31_30_MASK (0xc0000000UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_DEBUG_RESERVED_31_30_SHIFT (30UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_DEBUG_PRXQ_MASK (0x3fff0000UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_DEBUG_PRXQ_SHIFT (16UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_DEBUG_RESERVED_15_6_MASK (0xffc0UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_DEBUG_RESERVED_15_6_SHIFT (6UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_DEBUG_RXQSTS_MASK (0x30UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_DEBUG_RXQSTS_SHIFT (4UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_DEBUG_RESERVED_3_MASK (0x8UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_DEBUG_RESERVED_3_SHIFT (3UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_DEBUG_RRCSTS_MASK (0x6UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_DEBUG_RRCSTS_SHIFT (1UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_DEBUG_RWCSTS_MASK (0x1UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_DEBUG_RWCSTS_SHIFT (0UL)




typedef uint32_t XGMAC_MTL_TCQ1_MTL_RXQ1_CONTROL_TYPE;
#define XGMAC_MTL_TCQ1_MTL_RXQ1_CONTROL_RESERVED_31_3_MASK (0xfffffff0UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_CONTROL_RESERVED_31_3_SHIFT (4UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_CONTROL_RXQ_PKT_ARBIT_MASK (0x8UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_CONTROL_RXQ_PKT_ARBIT_SHIFT (3UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_CONTROL_RXQ_WEGT_MASK (0x7UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_CONTROL_RXQ_WEGT_SHIFT (0UL)




typedef uint32_t XGMAC_MTL_TCQ1_MTL_RXQ1_FLOW_CONTROL_TYPE;
#define XGMAC_MTL_TCQ1_MTL_RXQ1_FLOW_CONTROL_RESERVED_31_Y_MASK (0xff800000UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_FLOW_CONTROL_RESERVED_31_Y_SHIFT (23UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_FLOW_CONTROL_RFD_MASK (0x7e0000UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_FLOW_CONTROL_RFD_SHIFT (17UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_FLOW_CONTROL_RESERVED_16_Y_MASK (0x1ff80UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_FLOW_CONTROL_RESERVED_16_Y_SHIFT (7UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_FLOW_CONTROL_RFA_MASK (0x7eUL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_FLOW_CONTROL_RFA_SHIFT (1UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_FLOW_CONTROL_RESERVED_0_MASK (0x1UL)
#define XGMAC_MTL_TCQ1_MTL_RXQ1_FLOW_CONTROL_RESERVED_0_SHIFT (0UL)




typedef uint32_t XGMAC_MTL_TCQ1_MTL_Q1_INTERRUPT_ENABLE_TYPE;
#define XGMAC_MTL_TCQ1_MTL_Q1_INTERRUPT_ENABLE_RESERVED_31_17_MASK (0xfffe0000UL)
#define XGMAC_MTL_TCQ1_MTL_Q1_INTERRUPT_ENABLE_RESERVED_31_17_SHIFT (17UL)
#define XGMAC_MTL_TCQ1_MTL_Q1_INTERRUPT_ENABLE_RXOIE_MASK (0x10000UL)
#define XGMAC_MTL_TCQ1_MTL_Q1_INTERRUPT_ENABLE_RXOIE_SHIFT (16UL)
#define XGMAC_MTL_TCQ1_MTL_Q1_INTERRUPT_ENABLE_RESERVED_15_2_MASK (0xfffcUL)
#define XGMAC_MTL_TCQ1_MTL_Q1_INTERRUPT_ENABLE_RESERVED_15_2_SHIFT (2UL)
#define XGMAC_MTL_TCQ1_MTL_Q1_INTERRUPT_ENABLE_ABPSIE_MASK (0x2UL)
#define XGMAC_MTL_TCQ1_MTL_Q1_INTERRUPT_ENABLE_ABPSIE_SHIFT (1UL)
#define XGMAC_MTL_TCQ1_MTL_Q1_INTERRUPT_ENABLE_TXUIE_MASK (0x1UL)
#define XGMAC_MTL_TCQ1_MTL_Q1_INTERRUPT_ENABLE_TXUIE_SHIFT (0UL)




typedef uint32_t XGMAC_MTL_TCQ1_MTL_Q1_INTERRUPT_STATUS_TYPE;
#define XGMAC_MTL_TCQ1_MTL_Q1_INTERRUPT_STATUS_RESERVED_31_17_MASK (0xfffe0000UL)
#define XGMAC_MTL_TCQ1_MTL_Q1_INTERRUPT_STATUS_RESERVED_31_17_SHIFT (17UL)
#define XGMAC_MTL_TCQ1_MTL_Q1_INTERRUPT_STATUS_RXOVFIS_MASK (0x10000UL)
#define XGMAC_MTL_TCQ1_MTL_Q1_INTERRUPT_STATUS_RXOVFIS_SHIFT (16UL)
#define XGMAC_MTL_TCQ1_MTL_Q1_INTERRUPT_STATUS_RESERVED_15_2_MASK (0xfffcUL)
#define XGMAC_MTL_TCQ1_MTL_Q1_INTERRUPT_STATUS_RESERVED_15_2_SHIFT (2UL)
#define XGMAC_MTL_TCQ1_MTL_Q1_INTERRUPT_STATUS_ABPSIS_MASK (0x2UL)
#define XGMAC_MTL_TCQ1_MTL_Q1_INTERRUPT_STATUS_ABPSIS_SHIFT (1UL)
#define XGMAC_MTL_TCQ1_MTL_Q1_INTERRUPT_STATUS_TXUNFIS_MASK (0x1UL)
#define XGMAC_MTL_TCQ1_MTL_Q1_INTERRUPT_STATUS_TXUNFIS_SHIFT (0UL)




typedef volatile struct sXGMAC_MTL_TCQ1_RDBType {
    XGMAC_MTL_TCQ1_RESERVED_TYPE rsvd0[4352]; /* OFFSET: 0x0 */
    XGMAC_MTL_TCQ1_MTL_TXQ1_OPERATION_MODE_TYPE txq1_operation_mode; /* OFFSET: 0x1100 */
    XGMAC_MTL_TCQ1_MTL_TXQ1_UNDERFLOW_TYPE txq1_underflow; /* OFFSET: 0x1104 */
    XGMAC_MTL_TCQ1_MTL_TXQ1_DEBUG_TYPE txq1_debug; /* OFFSET: 0x1108 */
    XGMAC_MTL_TCQ1_RESERVED_TYPE rsvd1[4]; /* OFFSET: 0x110c */
    XGMAC_MTL_TCQ1_MTL_TC1_ETS_CONTROL_TYPE tc1_ets_control; /* OFFSET: 0x1110 */
    XGMAC_MTL_TCQ1_MTL_TC1_ETS_STATUS_TYPE tc1_ets_status; /* OFFSET: 0x1114 */
    XGMAC_MTL_TCQ1_MTL_TC1_QUANTUM_WEIGHT_TYPE tc1_quantum_weight; /* OFFSET: 0x1118 */
    XGMAC_MTL_TCQ1_RESERVED_TYPE rsvd2[36]; /* OFFSET: 0x111c */
    XGMAC_MTL_TCQ1_MTL_RXQ1_OPERATION_MODE_TYPE rxq1_operation_mode; /* OFFSET: 0x1140 */
    XGMAC_MTL_TCQ1_MR1MPOC_TYPE rxq1_missed_pkt_overflow_cnt; /* OFFSET: 0x1144 */
    XGMAC_MTL_TCQ1_MTL_RXQ1_DEBUG_TYPE rxq1_debug; /* OFFSET: 0x1148 */
    XGMAC_MTL_TCQ1_MTL_RXQ1_CONTROL_TYPE rxq1_control; /* OFFSET: 0x114c */
    XGMAC_MTL_TCQ1_MTL_RXQ1_FLOW_CONTROL_TYPE rxq1_flow_control; /* OFFSET: 0x1150 */
    XGMAC_MTL_TCQ1_RESERVED_TYPE rsvd3[28]; /* OFFSET: 0x1154 */
    XGMAC_MTL_TCQ1_MTL_Q1_INTERRUPT_ENABLE_TYPE q1_interrupt_enable; /* OFFSET: 0x1170 */
    XGMAC_MTL_TCQ1_MTL_Q1_INTERRUPT_STATUS_TYPE q1_interrupt_status; /* OFFSET: 0x1174 */
} XGMAC_MTL_TCQ1_RDBType;


#define XG_MTL_TCQ1_BASE                ((uintptr_t)(0xE02F0080UL))



#define XGMAC_MTL_TCQ1_MAX_HW_ID        (1UL)

#endif /* XGMAC_MTL_TCQ1_RDB_H */
