/*****************************************************************************
 Copyright 2024 Broadcom Corporation.  All rights reserved.

 Broadcom Proprietary and Confidential
******************************************************************************/
/**
    @file hsafe_rdb.h
    @brief RDB File for HSAFE

    @version BCM89580_A0_20230125_RDB
*/

#ifndef HSAFE_RDB_H
#define HSAFE_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t HSAFE_AFE_COMMON0_TYPE;
#define HSAFE_AFE_COMMON0_BIAS_PWRDN_MASK (0x1UL)
#define HSAFE_AFE_COMMON0_BIAS_PWRDN_SHIFT (0UL)




typedef uint32_t HSAFE_RCCAL_CONTROL0_TYPE;
#define HSAFE_RCCAL_CONTROL0_RCCAL_DONE_MASK (0x80000000UL)
#define HSAFE_RCCAL_CONTROL0_RCCAL_DONE_SHIFT (31UL)
#define HSAFE_RCCAL_CONTROL0_REVID_MASK (0xf0000UL)
#define HSAFE_RCCAL_CONTROL0_REVID_SHIFT (16UL)
#define HSAFE_RCCAL_CONTROL0_RCCAL_CODE_MASK (0x1f0UL)
#define HSAFE_RCCAL_CONTROL0_RCCAL_CODE_SHIFT (4UL)
#define HSAFE_RCCAL_CONTROL0_RCCAL_RESET_MASK (0x1UL)
#define HSAFE_RCCAL_CONTROL0_RCCAL_RESET_SHIFT (0UL)




typedef uint32_t HSAFE_RESCAL_CONTROL0_TYPE;
#define HSAFE_RESCAL_CONTROL0_DIAG_ON_MASK (0x4UL)
#define HSAFE_RESCAL_CONTROL0_DIAG_ON_SHIFT (2UL)
#define HSAFE_RESCAL_CONTROL0_PWRDNB_MASK (0x2UL)
#define HSAFE_RESCAL_CONTROL0_PWRDNB_SHIFT (1UL)
#define HSAFE_RESCAL_CONTROL0_RSTB_MASK (0x1UL)
#define HSAFE_RESCAL_CONTROL0_RSTB_SHIFT (0UL)




typedef uint32_t HSAFE_RESCAL_CONTROL1_TYPE;
#define HSAFE_RESCAL_CONTROL1_CTRL_MASK (0x3ffffffUL)
#define HSAFE_RESCAL_CONTROL1_CTRL_SHIFT (0UL)




typedef uint32_t HSAFE_RESCAL_STATUS0_TYPE;
#define HSAFE_RESCAL_STATUS0_CURR_COMP_CNT_MASK (0x3f00000UL)
#define HSAFE_RESCAL_STATUS0_CURR_COMP_CNT_SHIFT (20UL)
#define HSAFE_RESCAL_STATUS0_PREV_COMP_CNT_MASK (0xf0000UL)
#define HSAFE_RESCAL_STATUS0_PREV_COMP_CNT_SHIFT (16UL)
#define HSAFE_RESCAL_STATUS0_PON_MASK (0xf00UL)
#define HSAFE_RESCAL_STATUS0_PON_SHIFT (8UL)
#define HSAFE_RESCAL_STATUS0_STATE_MASK (0x70UL)
#define HSAFE_RESCAL_STATUS0_STATE_SHIFT (4UL)
#define HSAFE_RESCAL_STATUS0_COMP_MASK (0x4UL)
#define HSAFE_RESCAL_STATUS0_COMP_SHIFT (2UL)
#define HSAFE_RESCAL_STATUS0_VALID_MASK (0x2UL)
#define HSAFE_RESCAL_STATUS0_VALID_SHIFT (1UL)
#define HSAFE_RESCAL_STATUS0_DONE_MASK (0x1UL)
#define HSAFE_RESCAL_STATUS0_DONE_SHIFT (0UL)




typedef uint32_t HSAFE_RESCAL_VALUE_TYPE;
#define HSAFE_RESCAL_VALUE_HSADC_MASK (0xfUL)
#define HSAFE_RESCAL_VALUE_HSADC_SHIFT (0UL)




typedef uint32_t HSAFE_TXAFE_CONTROL0_TYPE;
#define HSAFE_TXAFE_CONTROL0_TXSLZR_VIPER_RESETB_MASK (0x2UL)
#define HSAFE_TXAFE_CONTROL0_TXSLZR_VIPER_RESETB_SHIFT (1UL)
#define HSAFE_TXAFE_CONTROL0_TXSLZR_VIPER_PD_MASK (0x1UL)
#define HSAFE_TXAFE_CONTROL0_TXSLZR_VIPER_PD_SHIFT (0UL)




typedef uint8_t HSAFE_RESERVED_TYPE;




typedef uint32_t HSAFE_ADC_CONTROL0_TYPE;
#define HSAFE_ADC_CONTROL0_PWRDN_MASK (0x2UL)
#define HSAFE_ADC_CONTROL0_PWRDN_SHIFT (1UL)
#define HSAFE_ADC_CONTROL0_RESETB_MASK (0x1UL)
#define HSAFE_ADC_CONTROL0_RESETB_SHIFT (0UL)




typedef uint32_t HSAFE_ADC_STATUS0_TYPE;
#define HSAFE_ADC_STATUS0_CONV_STATUS_MASK (0xffffUL)
#define HSAFE_ADC_STATUS0_CONV_STATUS_SHIFT (0UL)




typedef uint32_t HSAFE_ADC_CONFIG0_TYPE;
#define HSAFE_ADC_CONFIG0_SAR_CLKGEN_DLY_MASK (0xf000UL)
#define HSAFE_ADC_CONFIG0_SAR_CLKGEN_DLY_SHIFT (12UL)
#define HSAFE_ADC_CONFIG0_ADC_MODE_SEL_MASK (0x800UL)
#define HSAFE_ADC_CONFIG0_ADC_MODE_SEL_SHIFT (11UL)
#define HSAFE_ADC_CONFIG0_EN_TH_CLK_1P25G_MASK (0x780UL)
#define HSAFE_ADC_CONFIG0_EN_TH_CLK_1P25G_SHIFT (7UL)
#define HSAFE_ADC_CONFIG0_EN_CLK_1P25G_MASK (0x40UL)
#define HSAFE_ADC_CONFIG0_EN_CLK_1P25G_SHIFT (6UL)
#define HSAFE_ADC_CONFIG0_EN_CLK_5G_MASK (0x20UL)
#define HSAFE_ADC_CONFIG0_EN_CLK_5G_SHIFT (5UL)
#define HSAFE_ADC_CONFIG0_PD_5G_MASK (0x10UL)
#define HSAFE_ADC_CONFIG0_PD_5G_SHIFT (4UL)
#define HSAFE_ADC_CONFIG0_PD_1P25G_MASK (0xfUL)
#define HSAFE_ADC_CONFIG0_PD_1P25G_SHIFT (0UL)




typedef uint32_t HSAFE_ADC_CONFIG1_TYPE;
#define HSAFE_ADC_CONFIG1_TH_CLKP_VCM_SEL_MASK (0xe000UL)
#define HSAFE_ADC_CONFIG1_TH_CLKP_VCM_SEL_SHIFT (13UL)
#define HSAFE_ADC_CONFIG1_TH_CLKN_VCM_SEL_MASK (0x1c00UL)
#define HSAFE_ADC_CONFIG1_TH_CLKN_VCM_SEL_SHIFT (10UL)
#define HSAFE_ADC_CONFIG1_LPF_1P25G_MASK (0x3c0UL)
#define HSAFE_ADC_CONFIG1_LPF_1P25G_SHIFT (6UL)
#define HSAFE_ADC_CONFIG1_LPF_5G_MASK (0x3cUL)
#define HSAFE_ADC_CONFIG1_LPF_5G_SHIFT (2UL)
#define HSAFE_ADC_CONFIG1_EN_DC_OFFSET_MASK (0x2UL)
#define HSAFE_ADC_CONFIG1_EN_DC_OFFSET_SHIFT (1UL)
#define HSAFE_ADC_CONFIG1_EN_CLKGEN_MASK (0x1UL)
#define HSAFE_ADC_CONFIG1_EN_CLKGEN_SHIFT (0UL)




typedef uint32_t HSAFE_ADC_CONFIG2_TYPE;
#define HSAFE_ADC_CONFIG2_CONFIG2_SPARE_MASK (0x8000UL)
#define HSAFE_ADC_CONFIG2_CONFIG2_SPARE_SHIFT (15UL)
#define HSAFE_ADC_CONFIG2_ADC_RETIMER_SEL_LOCAL_MASK (0x4000UL)
#define HSAFE_ADC_CONFIG2_ADC_RETIMER_SEL_LOCAL_SHIFT (14UL)
#define HSAFE_ADC_CONFIG2_DC_CLAMP_POLARITY_MASK (0x2000UL)
#define HSAFE_ADC_CONFIG2_DC_CLAMP_POLARITY_SHIFT (13UL)
#define HSAFE_ADC_CONFIG2_DC_CLAMP_OV_VAL_MASK (0x1000UL)
#define HSAFE_ADC_CONFIG2_DC_CLAMP_OV_VAL_SHIFT (12UL)
#define HSAFE_ADC_CONFIG2_DC_CLAMP_OV_MASK (0x800UL)
#define HSAFE_ADC_CONFIG2_DC_CLAMP_OV_SHIFT (11UL)
#define HSAFE_ADC_CONFIG2_TERM_RCAL_OV_VAL_MASK (0x780UL)
#define HSAFE_ADC_CONFIG2_TERM_RCAL_OV_VAL_SHIFT (7UL)
#define HSAFE_ADC_CONFIG2_TERM_RCAL_OV_MASK (0x40UL)
#define HSAFE_ADC_CONFIG2_TERM_RCAL_OV_SHIFT (6UL)
#define HSAFE_ADC_CONFIG2_CAL_SIG_SEL_MASK (0x30UL)
#define HSAFE_ADC_CONFIG2_CAL_SIG_SEL_SHIFT (4UL)
#define HSAFE_ADC_CONFIG2_CFG_CAL_R_SEL_MASK (0xcUL)
#define HSAFE_ADC_CONFIG2_CFG_CAL_R_SEL_SHIFT (2UL)
#define HSAFE_ADC_CONFIG2_CFG_CAL_C_SEL_MASK (0x3UL)
#define HSAFE_ADC_CONFIG2_CFG_CAL_C_SEL_SHIFT (0UL)




typedef uint32_t HSAFE_ADC_CONFIG3_TYPE;
#define HSAFE_ADC_CONFIG3_EN_INPUT_TERM_MASK (0x8000UL)
#define HSAFE_ADC_CONFIG3_EN_INPUT_TERM_SHIFT (15UL)
#define HSAFE_ADC_CONFIG3_SAR_INVSKEW_MASK (0x6000UL)
#define HSAFE_ADC_CONFIG3_SAR_INVSKEW_SHIFT (13UL)
#define HSAFE_ADC_CONFIG3_SAR_EDLY_MASK (0x1c00UL)
#define HSAFE_ADC_CONFIG3_SAR_EDLY_SHIFT (10UL)
#define HSAFE_ADC_CONFIG3_SAR_EN_CHGCMP_MASK (0x200UL)
#define HSAFE_ADC_CONFIG3_SAR_EN_CHGCMP_SHIFT (9UL)
#define HSAFE_ADC_CONFIG3_SAR_ZERO_DIS_DEBUG_MASK (0x100UL)
#define HSAFE_ADC_CONFIG3_SAR_ZERO_DIS_DEBUG_SHIFT (8UL)
#define HSAFE_ADC_CONFIG3_SAR_CLKGEN_RCAL_OV_VAL_MASK (0xf0UL)
#define HSAFE_ADC_CONFIG3_SAR_CLKGEN_RCAL_OV_VAL_SHIFT (4UL)
#define HSAFE_ADC_CONFIG3_SAR_CLKGEN_RCAL_OV_MASK (0x8UL)
#define HSAFE_ADC_CONFIG3_SAR_CLKGEN_RCAL_OV_SHIFT (3UL)
#define HSAFE_ADC_CONFIG3_SAR_CLKGEN_TP_EN_MASK (0x4UL)
#define HSAFE_ADC_CONFIG3_SAR_CLKGEN_TP_EN_SHIFT (2UL)
#define HSAFE_ADC_CONFIG3_PD_SAR_CLKGEN_MASK (0x2UL)
#define HSAFE_ADC_CONFIG3_PD_SAR_CLKGEN_SHIFT (1UL)
#define HSAFE_ADC_CONFIG3_PD_SAR_MASK (0x1UL)
#define HSAFE_ADC_CONFIG3_PD_SAR_SHIFT (0UL)




typedef uint32_t HSAFE_ADC_CONFIG4_TYPE;
#define HSAFE_ADC_CONFIG4_DIS_SAR_MASK (0xffffUL)
#define HSAFE_ADC_CONFIG4_DIS_SAR_SHIFT (0UL)




typedef uint32_t HSAFE_ADC_CONFIG5_TYPE;
#define HSAFE_ADC_CONFIG5_BIAS_200UA_EXT_SAR_COMP_MASK (0xf000UL)
#define HSAFE_ADC_CONFIG5_BIAS_200UA_EXT_SAR_COMP_SHIFT (12UL)
#define HSAFE_ADC_CONFIG5_BIAS_50UA_EXT_ADC_REF_MASK (0xf00UL)
#define HSAFE_ADC_CONFIG5_BIAS_50UA_EXT_ADC_REF_SHIFT (8UL)
#define HSAFE_ADC_CONFIG5_PD_ADC_BIAS_MASK (0x80UL)
#define HSAFE_ADC_CONFIG5_PD_ADC_BIAS_SHIFT (7UL)
#define HSAFE_ADC_CONFIG5_PD_ADC_REF_MASK (0x40UL)
#define HSAFE_ADC_CONFIG5_PD_ADC_REF_SHIFT (6UL)
#define HSAFE_ADC_CONFIG5_ADC_REF_HP_EN_MASK (0x20UL)
#define HSAFE_ADC_CONFIG5_ADC_REF_HP_EN_SHIFT (5UL)
#define HSAFE_ADC_CONFIG5_ADC_REF_CTRL_MASK (0x1cUL)
#define HSAFE_ADC_CONFIG5_ADC_REF_CTRL_SHIFT (2UL)
#define HSAFE_ADC_CONFIG5_ADC_REF_BIAS_MASK (0x3UL)
#define HSAFE_ADC_CONFIG5_ADC_REF_BIAS_SHIFT (0UL)




typedef uint32_t HSAFE_ADC_CONFIG6_TYPE;
#define HSAFE_ADC_CONFIG6_BIAS_50U_EXT_SF2_5G_MASK (0xf000UL)
#define HSAFE_ADC_CONFIG6_BIAS_50U_EXT_SF2_5G_SHIFT (12UL)
#define HSAFE_ADC_CONFIG6_BIAS_50U_EXT_SF1_5G_MASK (0xf00UL)
#define HSAFE_ADC_CONFIG6_BIAS_50U_EXT_SF1_5G_SHIFT (8UL)
#define HSAFE_ADC_CONFIG6_BIAS_50U_EXT_SF2_1P25G_MASK (0xf0UL)
#define HSAFE_ADC_CONFIG6_BIAS_50U_EXT_SF2_1P25G_SHIFT (4UL)
#define HSAFE_ADC_CONFIG6_BIAS_50U_EXT_SF1_1P25G_MASK (0xfUL)
#define HSAFE_ADC_CONFIG6_BIAS_50U_EXT_SF1_1P25G_SHIFT (0UL)




typedef uint32_t HSAFE_ADC_CONFIG7_TYPE;
#define HSAFE_ADC_CONFIG7_CONFIG7_SPARE_MASK (0xff00UL)
#define HSAFE_ADC_CONFIG7_CONFIG7_SPARE_SHIFT (8UL)
#define HSAFE_ADC_CONFIG7_CFG_SF_BIAS_MODE_OV_MASK (0x80UL)
#define HSAFE_ADC_CONFIG7_CFG_SF_BIAS_MODE_OV_SHIFT (7UL)
#define HSAFE_ADC_CONFIG7_CFG_SF_BIAS_MODE_OV_VAL_MASK (0x60UL)
#define HSAFE_ADC_CONFIG7_CFG_SF_BIAS_MODE_OV_VAL_SHIFT (5UL)
#define HSAFE_ADC_CONFIG7_CFG_TH_OFFSET_OV_MASK (0x10UL)
#define HSAFE_ADC_CONFIG7_CFG_TH_OFFSET_OV_SHIFT (4UL)
#define HSAFE_ADC_CONFIG7_CFG_TH_OFFSET_OV_VAL_MASK (0xfUL)
#define HSAFE_ADC_CONFIG7_CFG_TH_OFFSET_OV_VAL_SHIFT (0UL)




typedef uint32_t HSAFE_ADC_CONFIG8_TYPE;
#define HSAFE_ADC_CONFIG8_CONFIG8_SPARE_MASK (0xfff8UL)
#define HSAFE_ADC_CONFIG8_CONFIG8_SPARE_SHIFT (3UL)
#define HSAFE_ADC_CONFIG8_RX_RCCAL_CODE_MASK (0x7UL)
#define HSAFE_ADC_CONFIG8_RX_RCCAL_CODE_SHIFT (0UL)




typedef uint32_t HSAFE_ADC_CONFIG9_TYPE;
#define HSAFE_ADC_CONFIG9_SPARE_MASK (0xffffUL)
#define HSAFE_ADC_CONFIG9_SPARE_SHIFT (0UL)




typedef uint32_t HSAFE_ADC_CONFIG10_TYPE;
#define HSAFE_ADC_CONFIG10_SPARE_MASK (0xffffUL)
#define HSAFE_ADC_CONFIG10_SPARE_SHIFT (0UL)




typedef uint32_t HSAFE_ADC_CONFIG11_TYPE;
#define HSAFE_ADC_CONFIG11_SPARE_MASK (0xffffUL)
#define HSAFE_ADC_CONFIG11_SPARE_SHIFT (0UL)




typedef uint32_t HSAFE_ADCR_CONFIG0_TYPE;
#define HSAFE_ADCR_CONFIG0_CONFIG0_SPARE_MASK (0xe000UL)
#define HSAFE_ADCR_CONFIG0_CONFIG0_SPARE_SHIFT (13UL)
#define HSAFE_ADCR_CONFIG0_SAR_INVSKEW_MASK (0x1800UL)
#define HSAFE_ADCR_CONFIG0_SAR_INVSKEW_SHIFT (11UL)
#define HSAFE_ADCR_CONFIG0_SAR_EDLY_MASK (0x700UL)
#define HSAFE_ADCR_CONFIG0_SAR_EDLY_SHIFT (8UL)
#define HSAFE_ADCR_CONFIG0_SAR_EN_CHGCMP_MASK (0x80UL)
#define HSAFE_ADCR_CONFIG0_SAR_EN_CHGCMP_SHIFT (7UL)
#define HSAFE_ADCR_CONFIG0_SAR_ZERO_DIS_DEBUG_MASK (0x40UL)
#define HSAFE_ADCR_CONFIG0_SAR_ZERO_DIS_DEBUG_SHIFT (6UL)
#define HSAFE_ADCR_CONFIG0_TERM_RCAL_OV_VAL_MASK (0x3cUL)
#define HSAFE_ADCR_CONFIG0_TERM_RCAL_OV_VAL_SHIFT (2UL)
#define HSAFE_ADCR_CONFIG0_TERM_RCAL_OV_MASK (0x2UL)
#define HSAFE_ADCR_CONFIG0_TERM_RCAL_OV_SHIFT (1UL)
#define HSAFE_ADCR_CONFIG0_EN_INPUT_TERM_MASK (0x1UL)
#define HSAFE_ADCR_CONFIG0_EN_INPUT_TERM_SHIFT (0UL)




typedef uint32_t HSAFE_ADCR_CONFIG1_TYPE;
#define HSAFE_ADCR_CONFIG1_CONFIG1_SPARE_MASK (0xff00UL)
#define HSAFE_ADCR_CONFIG1_CONFIG1_SPARE_SHIFT (8UL)
#define HSAFE_ADCR_CONFIG1_ADC_REF_HP_EN_MASK (0x80UL)
#define HSAFE_ADCR_CONFIG1_ADC_REF_HP_EN_SHIFT (7UL)
#define HSAFE_ADCR_CONFIG1_ADC_REF_CTRL_MASK (0x70UL)
#define HSAFE_ADCR_CONFIG1_ADC_REF_CTRL_SHIFT (4UL)
#define HSAFE_ADCR_CONFIG1_ADC_REF_BIAS_MASK (0xcUL)
#define HSAFE_ADCR_CONFIG1_ADC_REF_BIAS_SHIFT (2UL)
#define HSAFE_ADCR_CONFIG1_ADCR_RETIMER_SEL_LOCAL_MASK (0x2UL)
#define HSAFE_ADCR_CONFIG1_ADCR_RETIMER_SEL_LOCAL_SHIFT (1UL)
#define HSAFE_ADCR_CONFIG1_EN_CLKGEN_MASK (0x1UL)
#define HSAFE_ADCR_CONFIG1_EN_CLKGEN_SHIFT (0UL)




typedef uint32_t HSAFE_ADCR_CONFIG2_TYPE;
#define HSAFE_ADCR_CONFIG2_BIAS_200UA_EXT_SAR_COMP_MASK (0xf000UL)
#define HSAFE_ADCR_CONFIG2_BIAS_200UA_EXT_SAR_COMP_SHIFT (12UL)
#define HSAFE_ADCR_CONFIG2_BIAS_50UA_EXT_ADC_REF_MASK (0xf00UL)
#define HSAFE_ADCR_CONFIG2_BIAS_50UA_EXT_ADC_REF_SHIFT (8UL)
#define HSAFE_ADCR_CONFIG2_BIAS_50U_EXT_SF_ADC1_MASK (0xf0UL)
#define HSAFE_ADCR_CONFIG2_BIAS_50U_EXT_SF_ADC1_SHIFT (4UL)
#define HSAFE_ADCR_CONFIG2_BIAS_50U_EXT_SF_ADC0_MASK (0xfUL)
#define HSAFE_ADCR_CONFIG2_BIAS_50U_EXT_SF_ADC0_SHIFT (0UL)




typedef uint32_t HSAFE_ADCR_CONFIG3_TYPE;
#define HSAFE_ADCR_CONFIG3_CONFIG3_SPARE_MASK (0xff00UL)
#define HSAFE_ADCR_CONFIG3_CONFIG3_SPARE_SHIFT (8UL)
#define HSAFE_ADCR_CONFIG3_DAC_CLKGEN_SFT_RSTB_MASK (0x80UL)
#define HSAFE_ADCR_CONFIG3_DAC_CLKGEN_SFT_RSTB_SHIFT (7UL)
#define HSAFE_ADCR_CONFIG3_PULSE_LATCH_RETIMER_SEL_LOCAL_MASK (0x40UL)
#define HSAFE_ADCR_CONFIG3_PULSE_LATCH_RETIMER_SEL_LOCAL_SHIFT (6UL)
#define HSAFE_ADCR_CONFIG3_PULSE_LATCH_EN_MASK (0x20UL)
#define HSAFE_ADCR_CONFIG3_PULSE_LATCH_EN_SHIFT (5UL)
#define HSAFE_ADCR_CONFIG3_VCM_BUFFER_EN_MASK (0x10UL)
#define HSAFE_ADCR_CONFIG3_VCM_BUFFER_EN_SHIFT (4UL)
#define HSAFE_ADCR_CONFIG3_DAC_CLKGEN_SEL_MASK (0xeUL)
#define HSAFE_ADCR_CONFIG3_DAC_CLKGEN_SEL_SHIFT (1UL)
#define HSAFE_ADCR_CONFIG3_DAC_CLKGEN_EN_MASK (0x1UL)
#define HSAFE_ADCR_CONFIG3_DAC_CLKGEN_EN_SHIFT (0UL)




typedef uint32_t HSAFE_BIAS_CONFIG0_TYPE;
#define HSAFE_BIAS_CONFIG0_BG_TRIM_MASK (0xe000UL)
#define HSAFE_BIAS_CONFIG0_BG_TRIM_SHIFT (13UL)
#define HSAFE_BIAS_CONFIG0_CTRL_BG_LPF_SHORT_MASK (0x1000UL)
#define HSAFE_BIAS_CONFIG0_CTRL_BG_LPF_SHORT_SHIFT (12UL)
#define HSAFE_BIAS_CONFIG0_STRTUP_CLAMP_BYPS_MASK (0x800UL)
#define HSAFE_BIAS_CONFIG0_STRTUP_CLAMP_BYPS_SHIFT (11UL)
#define HSAFE_BIAS_CONFIG0_TRIM_EXT_MASK (0x780UL)
#define HSAFE_BIAS_CONFIG0_TRIM_EXT_SHIFT (7UL)
#define HSAFE_BIAS_CONFIG0_TRIM_INT_MASK (0x78UL)
#define HSAFE_BIAS_CONFIG0_TRIM_INT_SHIFT (3UL)
#define HSAFE_BIAS_CONFIG0_BIAS_REF_AMP_EXT_MASK (0x6UL)
#define HSAFE_BIAS_CONFIG0_BIAS_REF_AMP_EXT_SHIFT (1UL)
#define HSAFE_BIAS_CONFIG0_VBG_TST_EN_MASK (0x1UL)
#define HSAFE_BIAS_CONFIG0_VBG_TST_EN_SHIFT (0UL)




typedef uint32_t HSAFE_BIAS_CONFIG1_TYPE;
#define HSAFE_BIAS_CONFIG1_BIAS_REF_AMP_INT_MASK (0xc000UL)
#define HSAFE_BIAS_CONFIG1_BIAS_REF_AMP_INT_SHIFT (14UL)
#define HSAFE_BIAS_CONFIG1_CONFIG1_SPARE_MASK (0x3c00UL)
#define HSAFE_BIAS_CONFIG1_CONFIG1_SPARE_SHIFT (10UL)
#define HSAFE_BIAS_CONFIG1_RCAL_TST_VAL_MASK (0x3c0UL)
#define HSAFE_BIAS_CONFIG1_RCAL_TST_VAL_SHIFT (6UL)
#define HSAFE_BIAS_CONFIG1_RCAL_TST_SEL_MASK (0x20UL)
#define HSAFE_BIAS_CONFIG1_RCAL_TST_SEL_SHIFT (5UL)
#define HSAFE_BIAS_CONFIG1_RCAL_OFFSET_MASK (0x1eUL)
#define HSAFE_BIAS_CONFIG1_RCAL_OFFSET_SHIFT (1UL)
#define HSAFE_BIAS_CONFIG1_DISABLE_R_MASK (0x1UL)
#define HSAFE_BIAS_CONFIG1_DISABLE_R_SHIFT (0UL)




typedef uint32_t HSAFE_BIAS_CONFIG2_TYPE;
#define HSAFE_BIAS_CONFIG2_CNTRL_I100U_EXT_ADC_BIAS_MASK (0xe000UL)
#define HSAFE_BIAS_CONFIG2_CNTRL_I100U_EXT_ADC_BIAS_SHIFT (13UL)
#define HSAFE_BIAS_CONFIG2_CNTRL_I100U_EXT_ADCR_BIAS_MASK (0x1c00UL)
#define HSAFE_BIAS_CONFIG2_CNTRL_I100U_EXT_ADCR_BIAS_SHIFT (10UL)
#define HSAFE_BIAS_CONFIG2_CNTRL_I100U_INT_ADC_REF_MASK (0x380UL)
#define HSAFE_BIAS_CONFIG2_CNTRL_I100U_INT_ADC_REF_SHIFT (7UL)
#define HSAFE_BIAS_CONFIG2_CNTRL_I100U_INT_ADCR_REF_MASK (0x70UL)
#define HSAFE_BIAS_CONFIG2_CNTRL_I100U_INT_ADCR_REF_SHIFT (4UL)
#define HSAFE_BIAS_CONFIG2_CNTRL_I50U_INT_ADC_SF2_MASK (0xeUL)
#define HSAFE_BIAS_CONFIG2_CNTRL_I50U_INT_ADC_SF2_SHIFT (1UL)
#define HSAFE_BIAS_CONFIG2_IBIAS_TST_EN_MASK (0x1UL)
#define HSAFE_BIAS_CONFIG2_IBIAS_TST_EN_SHIFT (0UL)




typedef uint32_t HSAFE_BIAS_CONFIG3_TYPE;
#define HSAFE_BIAS_CONFIG3_CNTRL_I50U_INT_ADCR_SF2_MASK (0xe000UL)
#define HSAFE_BIAS_CONFIG3_CNTRL_I50U_INT_ADCR_SF2_SHIFT (13UL)
#define HSAFE_BIAS_CONFIG3_CNTRL_I100U_EXT_PLL_MASK (0x1c00UL)
#define HSAFE_BIAS_CONFIG3_CNTRL_I100U_EXT_PLL_SHIFT (10UL)
#define HSAFE_BIAS_CONFIG3_CNTRL_I100U_EXT_TVCO_MASK (0x380UL)
#define HSAFE_BIAS_CONFIG3_CNTRL_I100U_EXT_TVCO_SHIFT (7UL)
#define HSAFE_BIAS_CONFIG3_CNTRL_I50U_EXT_RCCAL_MASK (0x70UL)
#define HSAFE_BIAS_CONFIG3_CNTRL_I50U_EXT_RCCAL_SHIFT (4UL)
#define HSAFE_BIAS_CONFIG3_CONFIG3_SPARE_MASK (0xfUL)
#define HSAFE_BIAS_CONFIG3_CONFIG3_SPARE_SHIFT (0UL)




typedef uint32_t HSAFE_BIAS_CONFIG4_TYPE;
#define HSAFE_BIAS_CONFIG4_CNTRL_I100U_EXT_SPARE_MASK (0xe000UL)
#define HSAFE_BIAS_CONFIG4_CNTRL_I100U_EXT_SPARE_SHIFT (13UL)
#define HSAFE_BIAS_CONFIG4_CNTRL_I50U_INT_SPARE_MASK (0x1c00UL)
#define HSAFE_BIAS_CONFIG4_CNTRL_I50U_INT_SPARE_SHIFT (10UL)
#define HSAFE_BIAS_CONFIG4_CNTRL_I100U_INT_PLL_MASK (0x380UL)
#define HSAFE_BIAS_CONFIG4_CNTRL_I100U_INT_PLL_SHIFT (7UL)
#define HSAFE_BIAS_CONFIG4_CNTRL_I100U_EXT_TEST_MASK (0x70UL)
#define HSAFE_BIAS_CONFIG4_CNTRL_I100U_EXT_TEST_SHIFT (4UL)
#define HSAFE_BIAS_CONFIG4_CONFIG4_SPARE_MASK (0xfUL)
#define HSAFE_BIAS_CONFIG4_CONFIG4_SPARE_SHIFT (0UL)




typedef uint32_t HSAFE_BIAS_CONFIG5_TYPE;
#define HSAFE_BIAS_CONFIG5_CONFIG5_SPARE_MASK (0xffe0UL)
#define HSAFE_BIAS_CONFIG5_CONFIG5_SPARE_SHIFT (5UL)
#define HSAFE_BIAS_CONFIG5_VCO_PMOS_BIAS_REG_0P8_MASK (0x1cUL)
#define HSAFE_BIAS_CONFIG5_VCO_PMOS_BIAS_REG_0P8_SHIFT (2UL)
#define HSAFE_BIAS_CONFIG5_VCO_PMOS_BIAS_OVERRIDE_0P8_MASK (0x2UL)
#define HSAFE_BIAS_CONFIG5_VCO_PMOS_BIAS_OVERRIDE_0P8_SHIFT (1UL)
#define HSAFE_BIAS_CONFIG5_EN_VCO_MODE_0P8_MASK (0x1UL)
#define HSAFE_BIAS_CONFIG5_EN_VCO_MODE_0P8_SHIFT (0UL)




typedef uint32_t HSAFE_BIAS_CONFIG6_TYPE;
#define HSAFE_BIAS_CONFIG6_SPARE_MASK (0xffffUL)
#define HSAFE_BIAS_CONFIG6_SPARE_SHIFT (0UL)




typedef uint32_t HSAFE_BIAS_CONFIG7_TYPE;
#define HSAFE_BIAS_CONFIG7_SPARE_MASK (0xffffUL)
#define HSAFE_BIAS_CONFIG7_SPARE_SHIFT (0UL)




typedef uint32_t HSAFE_BIAS_CONFIG8_TYPE;
#define HSAFE_BIAS_CONFIG8_CAL_RESET_DIG_MASK (0x8000UL)
#define HSAFE_BIAS_CONFIG8_CAL_RESET_DIG_SHIFT (15UL)
#define HSAFE_BIAS_CONFIG8_CAL_CLK_FORCE_EN_MASK (0x4000UL)
#define HSAFE_BIAS_CONFIG8_CAL_CLK_FORCE_EN_SHIFT (14UL)
#define HSAFE_BIAS_CONFIG8_CHOP_2X_EN_MASK (0x2000UL)
#define HSAFE_BIAS_CONFIG8_CHOP_2X_EN_SHIFT (13UL)
#define HSAFE_BIAS_CONFIG8_VREF_HPF_DIS_MASK (0x1000UL)
#define HSAFE_BIAS_CONFIG8_VREF_HPF_DIS_SHIFT (12UL)
#define HSAFE_BIAS_CONFIG8_VREF_SW_CTRL_MASK (0x800UL)
#define HSAFE_BIAS_CONFIG8_VREF_SW_CTRL_SHIFT (11UL)
#define HSAFE_BIAS_CONFIG8_AVG4_EN_MASK (0x400UL)
#define HSAFE_BIAS_CONFIG8_AVG4_EN_SHIFT (10UL)
#define HSAFE_BIAS_CONFIG8_CTUNE_MASK (0x380UL)
#define HSAFE_BIAS_CONFIG8_CTUNE_SHIFT (7UL)
#define HSAFE_BIAS_CONFIG8_RTUNE_MASK (0x70UL)
#define HSAFE_BIAS_CONFIG8_RTUNE_SHIFT (4UL)
#define HSAFE_BIAS_CONFIG8_VREF_CTRL_MASK (0xcUL)
#define HSAFE_BIAS_CONFIG8_VREF_CTRL_SHIFT (2UL)
#define HSAFE_BIAS_CONFIG8_RESETB_SEL_MASK (0x2UL)
#define HSAFE_BIAS_CONFIG8_RESETB_SEL_SHIFT (1UL)
#define HSAFE_BIAS_CONFIG8_CONFIG8_SPARE_MASK (0x1UL)
#define HSAFE_BIAS_CONFIG8_CONFIG8_SPARE_SHIFT (0UL)




typedef uint32_t HSAFE_BIAS_CONFIG9_TYPE;
#define HSAFE_BIAS_CONFIG9_TEST_PRESET_MASK (0x8000UL)
#define HSAFE_BIAS_CONFIG9_TEST_PRESET_SHIFT (15UL)
#define HSAFE_BIAS_CONFIG9_TEST_CODE_MASK (0x7c00UL)
#define HSAFE_BIAS_CONFIG9_TEST_CODE_SHIFT (10UL)
#define HSAFE_BIAS_CONFIG9_OFFSET_IN_MASK (0x380UL)
#define HSAFE_BIAS_CONFIG9_OFFSET_IN_SHIFT (7UL)
#define HSAFE_BIAS_CONFIG9_CONFIG9_SPARE_MASK (0x7fUL)
#define HSAFE_BIAS_CONFIG9_CONFIG9_SPARE_SHIFT (0UL)




typedef uint32_t HSAFE_CLKGEN_CONFIG0_TYPE;
#define HSAFE_CLKGEN_CONFIG0_TVCO_CLK_SEL_MASK (0xf000UL)
#define HSAFE_CLKGEN_CONFIG0_TVCO_CLK_SEL_SHIFT (12UL)
#define HSAFE_CLKGEN_CONFIG0_TVCO_ANA_SEL_MASK (0xe00UL)
#define HSAFE_CLKGEN_CONFIG0_TVCO_ANA_SEL_SHIFT (9UL)
#define HSAFE_CLKGEN_CONFIG0_TVCO_BUF_AMP_MASK (0x180UL)
#define HSAFE_CLKGEN_CONFIG0_TVCO_BUF_AMP_SHIFT (7UL)
#define HSAFE_CLKGEN_CONFIG0_LDO_1ST_BIAS_MASK (0x60UL)
#define HSAFE_CLKGEN_CONFIG0_LDO_1ST_BIAS_SHIFT (5UL)
#define HSAFE_CLKGEN_CONFIG0_LDO_2ND_BIAS_MASK (0x18UL)
#define HSAFE_CLKGEN_CONFIG0_LDO_2ND_BIAS_SHIFT (3UL)
#define HSAFE_CLKGEN_CONFIG0_LDO_EN_MASK (0x4UL)
#define HSAFE_CLKGEN_CONFIG0_LDO_EN_SHIFT (2UL)
#define HSAFE_CLKGEN_CONFIG0_CLKGEN_EN_DCC_MASK (0x2UL)
#define HSAFE_CLKGEN_CONFIG0_CLKGEN_EN_DCC_SHIFT (1UL)
#define HSAFE_CLKGEN_CONFIG0_CONFIG0_SPARE_MASK (0x1UL)
#define HSAFE_CLKGEN_CONFIG0_CONFIG0_SPARE_SHIFT (0UL)




typedef uint32_t HSAFE_CLKGEN_CONFIG1_TYPE;
#define HSAFE_CLKGEN_CONFIG1_CONFIG1_SPARE_MASK (0xfff0UL)
#define HSAFE_CLKGEN_CONFIG1_CONFIG1_SPARE_SHIFT (4UL)
#define HSAFE_CLKGEN_CONFIG1_EN_RX_TEST_CLK_MASK (0x8UL)
#define HSAFE_CLKGEN_CONFIG1_EN_RX_TEST_CLK_SHIFT (3UL)
#define HSAFE_CLKGEN_CONFIG1_CLKGEN_EN_ADCR_PL_MASK (0x4UL)
#define HSAFE_CLKGEN_CONFIG1_CLKGEN_EN_ADCR_PL_SHIFT (2UL)
#define HSAFE_CLKGEN_CONFIG1_CLKGEN_EN_ADCR_MASK (0x2UL)
#define HSAFE_CLKGEN_CONFIG1_CLKGEN_EN_ADCR_SHIFT (1UL)
#define HSAFE_CLKGEN_CONFIG1_CLKGEN_EN_SER_MASK (0x1UL)
#define HSAFE_CLKGEN_CONFIG1_CLKGEN_EN_SER_SHIFT (0UL)




typedef uint32_t HSAFE_PLL_CONTROL0_TYPE;
#define HSAFE_PLL_CONTROL0_REFCLK_FREQ_SEL_MASK (0x20UL)
#define HSAFE_PLL_CONTROL0_REFCLK_FREQ_SEL_SHIFT (5UL)
#define HSAFE_PLL_CONTROL0_PD_CML_REFCH_OUT_MASK (0x10UL)
#define HSAFE_PLL_CONTROL0_PD_CML_REFCH_OUT_SHIFT (4UL)
#define HSAFE_PLL_CONTROL0_CLKGEN_RSTB_MASK (0x8UL)
#define HSAFE_PLL_CONTROL0_CLKGEN_RSTB_SHIFT (3UL)
#define HSAFE_PLL_CONTROL0_EN_ADC_CLK_MASK (0x4UL)
#define HSAFE_PLL_CONTROL0_EN_ADC_CLK_SHIFT (2UL)
#define HSAFE_PLL_CONTROL0_PWRDN_MASK (0x2UL)
#define HSAFE_PLL_CONTROL0_PWRDN_SHIFT (1UL)
#define HSAFE_PLL_CONTROL0_RESETB_MASK (0x1UL)
#define HSAFE_PLL_CONTROL0_RESETB_SHIFT (0UL)




typedef uint32_t HSAFE_PLL_STATUS0_TYPE;
#define HSAFE_PLL_STATUS0_VCO_RANGE_MASK (0x7f00UL)
#define HSAFE_PLL_STATUS0_VCO_RANGE_SHIFT (8UL)
#define HSAFE_PLL_STATUS0_CAL_STATE_MASK (0xf0UL)
#define HSAFE_PLL_STATUS0_CAL_STATE_SHIFT (4UL)
#define HSAFE_PLL_STATUS0_REF_EPWD_MASK (0x4UL)
#define HSAFE_PLL_STATUS0_REF_EPWD_SHIFT (2UL)
#define HSAFE_PLL_STATUS0_CAL_VALID_MASK (0x2UL)
#define HSAFE_PLL_STATUS0_CAL_VALID_SHIFT (1UL)
#define HSAFE_PLL_STATUS0_LOCK_MASK (0x1UL)
#define HSAFE_PLL_STATUS0_LOCK_SHIFT (0UL)




typedef uint32_t HSAFE_PLL_CONFIG0_TYPE;
#define HSAFE_PLL_CONFIG0_CPAR_MASK (0xc000UL)
#define HSAFE_PLL_CONFIG0_CPAR_SHIFT (14UL)
#define HSAFE_PLL_CONFIG0_TERM_CM_EN_MASK (0x2000UL)
#define HSAFE_PLL_CONFIG0_TERM_CM_EN_SHIFT (13UL)
#define HSAFE_PLL_CONFIG0_ENABLE_IBG_MASK (0x1000UL)
#define HSAFE_PLL_CONFIG0_ENABLE_IBG_SHIFT (12UL)
#define HSAFE_PLL_CONFIG0_RPAR_MASK (0xe00UL)
#define HSAFE_PLL_CONFIG0_RPAR_SHIFT (9UL)
#define HSAFE_PLL_CONFIG0_LCREFCLK_ADJ_MASK (0x180UL)
#define HSAFE_PLL_CONFIG0_LCREFCLK_ADJ_SHIFT (7UL)
#define HSAFE_PLL_CONFIG0_XTAL_HIPASS_MASK (0x40UL)
#define HSAFE_PLL_CONFIG0_XTAL_HIPASS_SHIFT (6UL)
#define HSAFE_PLL_CONFIG0_XTAL_BIAS_MASK (0x30UL)
#define HSAFE_PLL_CONFIG0_XTAL_BIAS_SHIFT (4UL)
#define HSAFE_PLL_CONFIG0_XTAL_COM_MASK (0xcUL)
#define HSAFE_PLL_CONFIG0_XTAL_COM_SHIFT (2UL)
#define HSAFE_PLL_CONFIG0_XTAL_CUR_MASK (0x3UL)
#define HSAFE_PLL_CONFIG0_XTAL_CUR_SHIFT (0UL)




typedef uint32_t HSAFE_PLL_CONFIG1_TYPE;
#define HSAFE_PLL_CONFIG1_EN_HCUR_VCO_MASK (0x8000UL)
#define HSAFE_PLL_CONFIG1_EN_HCUR_VCO_SHIFT (15UL)
#define HSAFE_PLL_CONFIG1_D2C_BIAS_MASK (0x6000UL)
#define HSAFE_PLL_CONFIG1_D2C_BIAS_SHIFT (13UL)
#define HSAFE_PLL_CONFIG1_PLL_RANGE_OVRD_VAL_MASK (0x1fc0UL)
#define HSAFE_PLL_CONFIG1_PLL_RANGE_OVRD_VAL_SHIFT (6UL)
#define HSAFE_PLL_CONFIG1_EN_8P5G_VCO_MASK (0x20UL)
#define HSAFE_PLL_CONFIG1_EN_8P5G_VCO_SHIFT (5UL)
#define HSAFE_PLL_CONFIG1_PLL_CONFIG1_SPARE2_MASK (0x10UL)
#define HSAFE_PLL_CONFIG1_PLL_CONFIG1_SPARE2_SHIFT (4UL)
#define HSAFE_PLL_CONFIG1_CURR_SEL_MASK (0xfUL)
#define HSAFE_PLL_CONFIG1_CURR_SEL_SHIFT (0UL)




typedef uint32_t HSAFE_PLL_CONFIG2_TYPE;
#define HSAFE_PLL_CONFIG2_EN_I4IQBUF_MASK (0xc000UL)
#define HSAFE_PLL_CONFIG2_EN_I4IQBUF_SHIFT (14UL)
#define HSAFE_PLL_CONFIG2_VCOBUF_PON_MASK (0x3c00UL)
#define HSAFE_PLL_CONFIG2_VCOBUF_PON_SHIFT (10UL)
#define HSAFE_PLL_CONFIG2_PLL_CLKVCO_CAL_INVERT_MASK (0x200UL)
#define HSAFE_PLL_CONFIG2_PLL_CLKVCO_CAL_INVERT_SHIFT (9UL)
#define HSAFE_PLL_CONFIG2_EN_CMOS_REF_CH_HIZ_MASK (0x100UL)
#define HSAFE_PLL_CONFIG2_EN_CMOS_REF_CH_HIZ_SHIFT (8UL)
#define HSAFE_PLL_CONFIG2_CALIB_ADJ_MASK (0xe0UL)
#define HSAFE_PLL_CONFIG2_CALIB_ADJ_SHIFT (5UL)
#define HSAFE_PLL_CONFIG2_EN_8P5G_MASK (0x10UL)
#define HSAFE_PLL_CONFIG2_EN_8P5G_SHIFT (4UL)
#define HSAFE_PLL_CONFIG2_VCO_PON_MASK (0xfUL)
#define HSAFE_PLL_CONFIG2_VCO_PON_SHIFT (0UL)




typedef uint32_t HSAFE_PLL_CONFIG3_TYPE;
#define HSAFE_PLL_CONFIG3_EN_MMD_HALFRATE_MASK (0x8000UL)
#define HSAFE_PLL_CONFIG3_EN_MMD_HALFRATE_SHIFT (15UL)
#define HSAFE_PLL_CONFIG3_CP_BIAS_MASK (0x7000UL)
#define HSAFE_PLL_CONFIG3_CP_BIAS_SHIFT (12UL)
#define HSAFE_PLL_CONFIG3_SEL_MMD_MASK (0x800UL)
#define HSAFE_PLL_CONFIG3_SEL_MMD_SHIFT (11UL)
#define HSAFE_PLL_CONFIG3_REF_CMOS_HZ_MASK (0x400UL)
#define HSAFE_PLL_CONFIG3_REF_CMOS_HZ_SHIFT (10UL)
#define HSAFE_PLL_CONFIG3_REF_CML_PD_MASK (0x200UL)
#define HSAFE_PLL_CONFIG3_REF_CML_PD_SHIFT (9UL)
#define HSAFE_PLL_CONFIG3_PLLCLKSEL_MASK (0x100UL)
#define HSAFE_PLL_CONFIG3_PLLCLKSEL_SHIFT (8UL)
#define HSAFE_PLL_CONFIG3_EN_RX_CLK_REFOUT_MASK (0x80UL)
#define HSAFE_PLL_CONFIG3_EN_RX_CLK_REFOUT_SHIFT (7UL)
#define HSAFE_PLL_CONFIG3_EN_CMOS_REFOUT_OVERWRITE_MASK (0x40UL)
#define HSAFE_PLL_CONFIG3_EN_CMOS_REFOUT_OVERWRITE_SHIFT (6UL)
#define HSAFE_PLL_CONFIG3_EN_CML_REFOUT_OVERWRITE_MASK (0x20UL)
#define HSAFE_PLL_CONFIG3_EN_CML_REFOUT_OVERWRITE_SHIFT (5UL)
#define HSAFE_PLL_CONFIG3_EN_TEST_FRAC_CLK_MASK (0x10UL)
#define HSAFE_PLL_CONFIG3_EN_TEST_FRAC_CLK_SHIFT (4UL)
#define HSAFE_PLL_CONFIG3_PLL_CONFIG3_SPARE_MASK (0x8UL)
#define HSAFE_PLL_CONFIG3_PLL_CONFIG3_SPARE_SHIFT (3UL)
#define HSAFE_PLL_CONFIG3_BAND_IQBUF_CTR_MASK (0x7UL)
#define HSAFE_PLL_CONFIG3_BAND_IQBUF_CTR_SHIFT (0UL)




typedef uint32_t HSAFE_PLL_CONFIG4_TYPE;
#define HSAFE_PLL_CONFIG4_REFOUT_DIV_SEL_MASK (0x8000UL)
#define HSAFE_PLL_CONFIG4_REFOUT_DIV_SEL_SHIFT (15UL)
#define HSAFE_PLL_CONFIG4_TEST_SEL_VAL_MASK (0x7000UL)
#define HSAFE_PLL_CONFIG4_TEST_SEL_VAL_SHIFT (12UL)
#define HSAFE_PLL_CONFIG4_PLL_CONFIG4_SPARE1_MASK (0xc00UL)
#define HSAFE_PLL_CONFIG4_PLL_CONFIG4_SPARE1_SHIFT (10UL)
#define HSAFE_PLL_CONFIG4_VCO_TEST_CLK_EN_MASK (0x200UL)
#define HSAFE_PLL_CONFIG4_VCO_TEST_CLK_EN_SHIFT (9UL)
#define HSAFE_PLL_CONFIG4_BIAS_EN_MASK (0x100UL)
#define HSAFE_PLL_CONFIG4_BIAS_EN_SHIFT (8UL)
#define HSAFE_PLL_CONFIG4_VCO_HKVCO_MASK (0x80UL)
#define HSAFE_PLL_CONFIG4_VCO_HKVCO_SHIFT (7UL)
#define HSAFE_PLL_CONFIG4_BIAS_VDD_SEL_MASK (0x60UL)
#define HSAFE_PLL_CONFIG4_BIAS_VDD_SEL_SHIFT (5UL)
#define HSAFE_PLL_CONFIG4_PLL_CONFIG4_SPARE2_MASK (0x10UL)
#define HSAFE_PLL_CONFIG4_PLL_CONFIG4_SPARE2_SHIFT (4UL)
#define HSAFE_PLL_CONFIG4_CP_OPAMP_BIAS_MASK (0xcUL)
#define HSAFE_PLL_CONFIG4_CP_OPAMP_BIAS_SHIFT (2UL)
#define HSAFE_PLL_CONFIG4_LCREFCLK_ADJ_MASK (0x3UL)
#define HSAFE_PLL_CONFIG4_LCREFCLK_ADJ_SHIFT (0UL)




typedef uint32_t HSAFE_PLL_CONFIG5_TYPE;
#define HSAFE_PLL_CONFIG5_PLL_PON_MASK (0xf000UL)
#define HSAFE_PLL_CONFIG5_PLL_PON_SHIFT (12UL)
#define HSAFE_PLL_CONFIG5_VCODIV_TEST_SEL_MASK (0xe00UL)
#define HSAFE_PLL_CONFIG5_VCODIV_TEST_SEL_SHIFT (9UL)
#define HSAFE_PLL_CONFIG5_PWDB_EXTR_D2C_MASK (0x100UL)
#define HSAFE_PLL_CONFIG5_PWDB_EXTR_D2C_SHIFT (8UL)
#define HSAFE_PLL_CONFIG5_EN_REFOUT_DIV_MASK (0x80UL)
#define HSAFE_PLL_CONFIG5_EN_REFOUT_DIV_SHIFT (7UL)
#define HSAFE_PLL_CONFIG5_PLL_PWRDN_MASK (0x40UL)
#define HSAFE_PLL_CONFIG5_PLL_PWRDN_SHIFT (6UL)
#define HSAFE_PLL_CONFIG5_TERM_SEL_MASK (0x30UL)
#define HSAFE_PLL_CONFIG5_TERM_SEL_SHIFT (4UL)
#define HSAFE_PLL_CONFIG5_TEST_SEL_OVRT_MASK (0x8UL)
#define HSAFE_PLL_CONFIG5_TEST_SEL_OVRT_SHIFT (3UL)
#define HSAFE_PLL_CONFIG5_TEST_VC_MASK (0x4UL)
#define HSAFE_PLL_CONFIG5_TEST_VC_SHIFT (2UL)
#define HSAFE_PLL_CONFIG5_REFOUT_DIV_SEL_MASK (0x3UL)
#define HSAFE_PLL_CONFIG5_REFOUT_DIV_SEL_SHIFT (0UL)




typedef uint32_t HSAFE_PLL_CONFIG6_TYPE;
#define HSAFE_PLL_CONFIG6_I_NDIV_FRAC_MASK (0xff00UL)
#define HSAFE_PLL_CONFIG6_I_NDIV_FRAC_SHIFT (8UL)
#define HSAFE_PLL_CONFIG6_PFD_OFFSET_MASK (0xc0UL)
#define HSAFE_PLL_CONFIG6_PFD_OFFSET_SHIFT (6UL)
#define HSAFE_PLL_CONFIG6_VCO_CM_CAP_ENABLE_MASK (0x20UL)
#define HSAFE_PLL_CONFIG6_VCO_CM_CAP_ENABLE_SHIFT (5UL)
#define HSAFE_PLL_CONFIG6_PFD_OFFSET_ENLARGE_MASK (0x10UL)
#define HSAFE_PLL_CONFIG6_PFD_OFFSET_ENLARGE_SHIFT (4UL)
#define HSAFE_PLL_CONFIG6_VCO_I_BOOST_MASK (0xcUL)
#define HSAFE_PLL_CONFIG6_VCO_I_BOOST_SHIFT (2UL)
#define HSAFE_PLL_CONFIG6_VCO_GM_BOOST_MASK (0x3UL)
#define HSAFE_PLL_CONFIG6_VCO_GM_BOOST_SHIFT (0UL)




typedef uint32_t HSAFE_PLL_CONFIG7_TYPE;
#define HSAFE_PLL_CONFIG7_I_NDIV_INT_MASK (0xfc00UL)
#define HSAFE_PLL_CONFIG7_I_NDIV_INT_SHIFT (10UL)
#define HSAFE_PLL_CONFIG7_I_NDIV_FRAC_MASK (0x3ffUL)
#define HSAFE_PLL_CONFIG7_I_NDIV_FRAC_SHIFT (0UL)




typedef uint32_t HSAFE_PLL_CONFIG8_TYPE;
#define HSAFE_PLL_CONFIG8_SEL_FP3CAP_MASK (0xe000UL)
#define HSAFE_PLL_CONFIG8_SEL_FP3CAP_SHIFT (13UL)
#define HSAFE_PLL_CONFIG8_PLL_FRAC_MODE_MASK (0x1800UL)
#define HSAFE_PLL_CONFIG8_PLL_FRAC_MODE_SHIFT (11UL)
#define HSAFE_PLL_CONFIG8_MMD_RESETB_MASK (0x400UL)
#define HSAFE_PLL_CONFIG8_MMD_RESETB_SHIFT (10UL)
#define HSAFE_PLL_CONFIG8_I_NDIV_DITHER_EN_MASK (0x200UL)
#define HSAFE_PLL_CONFIG8_I_NDIV_DITHER_EN_SHIFT (9UL)
#define HSAFE_PLL_CONFIG8_I_PLL_SDM_PWDN_BAR_MASK (0x100UL)
#define HSAFE_PLL_CONFIG8_I_PLL_SDM_PWDN_BAR_SHIFT (8UL)
#define HSAFE_PLL_CONFIG8_VCOFB_DIV_MASK (0xc0UL)
#define HSAFE_PLL_CONFIG8_VCOFB_DIV_SHIFT (6UL)
#define HSAFE_PLL_CONFIG8_CMLREFCLK_BIAS_MASK (0x30UL)
#define HSAFE_PLL_CONFIG8_CMLREFCLK_BIAS_SHIFT (4UL)
#define HSAFE_PLL_CONFIG8_I_NDIV_INT_MASK (0xfUL)
#define HSAFE_PLL_CONFIG8_I_NDIV_INT_SHIFT (0UL)




typedef uint32_t HSAFE_PLL_CONFIG9_TYPE;
#define HSAFE_PLL_CONFIG9_OSC_D2C_BIAS_MASK (0xfc00UL)
#define HSAFE_PLL_CONFIG9_OSC_D2C_BIAS_SHIFT (10UL)
#define HSAFE_PLL_CONFIG9_CMLREFCLK_BIAS_MASK (0x300UL)
#define HSAFE_PLL_CONFIG9_CMLREFCLK_BIAS_SHIFT (8UL)
#define HSAFE_PLL_CONFIG9_BIAS_IQ_CTRL_MASK (0xe0UL)
#define HSAFE_PLL_CONFIG9_BIAS_IQ_CTRL_SHIFT (5UL)
#define HSAFE_PLL_CONFIG9_BIAS_DIV_CTRL_MASK (0x1cUL)
#define HSAFE_PLL_CONFIG9_BIAS_DIV_CTRL_SHIFT (2UL)
#define HSAFE_PLL_CONFIG9_VCO_SUPPLY_ADJ_MASK (0x2UL)
#define HSAFE_PLL_CONFIG9_VCO_SUPPLY_ADJ_SHIFT (1UL)
#define HSAFE_PLL_CONFIG9_SEL_FP3CAP_MASK (0x1UL)
#define HSAFE_PLL_CONFIG9_SEL_FP3CAP_SHIFT (0UL)




typedef uint32_t HSAFE_PLL_CONFIG10_TYPE;
#define HSAFE_PLL_CONFIG10_EN_CK80_MASK (0x8000UL)
#define HSAFE_PLL_CONFIG10_EN_CK80_SHIFT (15UL)
#define HSAFE_PLL_CONFIG10_PLL_CONFIG10_SPARE1_MASK (0x4000UL)
#define HSAFE_PLL_CONFIG10_PLL_CONFIG10_SPARE1_SHIFT (14UL)
#define HSAFE_PLL_CONFIG10_SEL_VCO20_TO_VCO32_MASK (0x3000UL)
#define HSAFE_PLL_CONFIG10_SEL_VCO20_TO_VCO32_SHIFT (12UL)
#define HSAFE_PLL_CONFIG10_EN_VCO20_TO_VCO32_MASK (0x800UL)
#define HSAFE_PLL_CONFIG10_EN_VCO20_TO_VCO32_SHIFT (11UL)
#define HSAFE_PLL_CONFIG10_PLL_CONFIG10_SPARE2_MASK (0x400UL)
#define HSAFE_PLL_CONFIG10_PLL_CONFIG10_SPARE2_SHIFT (10UL)
#define HSAFE_PLL_CONFIG10_I_TESTSEL_MASK (0x380UL)
#define HSAFE_PLL_CONFIG10_I_TESTSEL_SHIFT (7UL)
#define HSAFE_PLL_CONFIG10_BIAS_ACJ_TEST_ON_MASK (0x40UL)
#define HSAFE_PLL_CONFIG10_BIAS_ACJ_TEST_ON_SHIFT (6UL)
#define HSAFE_PLL_CONFIG10_SEL_INT_DIV_MASK (0x30UL)
#define HSAFE_PLL_CONFIG10_SEL_INT_DIV_SHIFT (4UL)
#define HSAFE_PLL_CONFIG10_PLL_CONFIG10_SPARE3_MASK (0x8UL)
#define HSAFE_PLL_CONFIG10_PLL_CONFIG10_SPARE3_SHIFT (3UL)
#define HSAFE_PLL_CONFIG10_SEL_VCO16_TO_VCO32_MASK (0x6UL)
#define HSAFE_PLL_CONFIG10_SEL_VCO16_TO_VCO32_SHIFT (1UL)
#define HSAFE_PLL_CONFIG10_EN_VCO16_TO_VCO32_MASK (0x1UL)
#define HSAFE_PLL_CONFIG10_EN_VCO16_TO_VCO32_SHIFT (0UL)




typedef uint32_t HSAFE_PLL_CONFIG11_TYPE;
#define HSAFE_PLL_CONFIG11_CONFIG_11_SPARE1_MASK (0xff80UL)
#define HSAFE_PLL_CONFIG11_CONFIG_11_SPARE1_SHIFT (7UL)
#define HSAFE_PLL_CONFIG11_I_REF_CMOS_CLK_HZ_MASK (0x40UL)
#define HSAFE_PLL_CONFIG11_I_REF_CMOS_CLK_HZ_SHIFT (6UL)
#define HSAFE_PLL_CONFIG11_SDM_RSTB_OV_MASK (0x20UL)
#define HSAFE_PLL_CONFIG11_SDM_RSTB_OV_SHIFT (5UL)
#define HSAFE_PLL_CONFIG11_CONFIG_11_SPARE2_MASK (0x10UL)
#define HSAFE_PLL_CONFIG11_CONFIG_11_SPARE2_SHIFT (4UL)
#define HSAFE_PLL_CONFIG11_PLL_PD_OV_MASK (0x8UL)
#define HSAFE_PLL_CONFIG11_PLL_PD_OV_SHIFT (3UL)
#define HSAFE_PLL_CONFIG11_PLL_PON_OV_MASK (0x4UL)
#define HSAFE_PLL_CONFIG11_PLL_PON_OV_SHIFT (2UL)
#define HSAFE_PLL_CONFIG11_VCOBUF_PON_OV_MASK (0x2UL)
#define HSAFE_PLL_CONFIG11_VCOBUF_PON_OV_SHIFT (1UL)
#define HSAFE_PLL_CONFIG11_VCO_PON_OV_MASK (0x1UL)
#define HSAFE_PLL_CONFIG11_VCO_PON_OV_SHIFT (0UL)




typedef uint32_t HSAFE_VCO_CAL_CONFIG0_TYPE;
#define HSAFE_VCO_CAL_CONFIG0_CALIB_STEP_TIME_MASK (0xffffUL)
#define HSAFE_VCO_CAL_CONFIG0_CALIB_STEP_TIME_SHIFT (0UL)




typedef uint32_t HSAFE_VCO_CAL_CONFIG1_TYPE;
#define HSAFE_VCO_CAL_CONFIG1_CALIB_CAP_CHARGE_TIME_MASK (0xffffUL)
#define HSAFE_VCO_CAL_CONFIG1_CALIB_CAP_CHARGE_TIME_SHIFT (0UL)




typedef uint32_t HSAFE_VCO_CAL_CONFIG2_TYPE;
#define HSAFE_VCO_CAL_CONFIG2_CALIB_DELAY_TIME_MASK (0xffffUL)
#define HSAFE_VCO_CAL_CONFIG2_CALIB_DELAY_TIME_SHIFT (0UL)




typedef uint32_t HSAFE_VCO_CAL_CONFIG3_TYPE;
#define HSAFE_VCO_CAL_CONFIG3_FREQMONITOR_EN_MASK (0x8000UL)
#define HSAFE_VCO_CAL_CONFIG3_FREQMONITOR_EN_SHIFT (15UL)
#define HSAFE_VCO_CAL_CONFIG3_EN_CALIB_N_MASK (0x4000UL)
#define HSAFE_VCO_CAL_CONFIG3_EN_CALIB_N_SHIFT (14UL)
#define HSAFE_VCO_CAL_CONFIG3_VCOCAL_DONE_OVRD_VAL_MASK (0x2000UL)
#define HSAFE_VCO_CAL_CONFIG3_VCOCAL_DONE_OVRD_VAL_SHIFT (13UL)
#define HSAFE_VCO_CAL_CONFIG3_VCOCAL_DONE_OVRD_MASK (0x1000UL)
#define HSAFE_VCO_CAL_CONFIG3_VCOCAL_DONE_OVRD_SHIFT (12UL)
#define HSAFE_VCO_CAL_CONFIG3_PLLRANGEHOLDING_MASK (0xfe0UL)
#define HSAFE_VCO_CAL_CONFIG3_PLLRANGEHOLDING_SHIFT (5UL)
#define HSAFE_VCO_CAL_CONFIG3_PLL_RANGE_OVRD_MASK (0x10UL)
#define HSAFE_VCO_CAL_CONFIG3_PLL_RANGE_OVRD_SHIFT (4UL)
#define HSAFE_VCO_CAL_CONFIG3_CAL_TH_MASK (0xfUL)
#define HSAFE_VCO_CAL_CONFIG3_CAL_TH_SHIFT (0UL)




typedef uint32_t HSAFE_VCO_CAL_CONFIG4_TYPE;
#define HSAFE_VCO_CAL_CONFIG4_CALIB_SEARCH_BIT_MASK (0xe000UL)
#define HSAFE_VCO_CAL_CONFIG4_CALIB_SEARCH_BIT_SHIFT (13UL)
#define HSAFE_VCO_CAL_CONFIG4_FREQDET_EN_MASK (0x1000UL)
#define HSAFE_VCO_CAL_CONFIG4_FREQDET_EN_SHIFT (12UL)
#define HSAFE_VCO_CAL_CONFIG4_SEL_DELAY_PLL_MASK (0x800UL)
#define HSAFE_VCO_CAL_CONFIG4_SEL_DELAY_PLL_SHIFT (11UL)
#define HSAFE_VCO_CAL_CONFIG4_SEL_PWRON_CALVAL_MASK (0x400UL)
#define HSAFE_VCO_CAL_CONFIG4_SEL_PWRON_CALVAL_SHIFT (10UL)
#define HSAFE_VCO_CAL_CONFIG4_SEL_ANALOGDELAY_MASK (0x200UL)
#define HSAFE_VCO_CAL_CONFIG4_SEL_ANALOGDELAY_SHIFT (9UL)
#define HSAFE_VCO_CAL_CONFIG4_IQBUF_CTRL_OVRD_MASK (0x100UL)
#define HSAFE_VCO_CAL_CONFIG4_IQBUF_CTRL_OVRD_SHIFT (8UL)
#define HSAFE_VCO_CAL_CONFIG4_IQBUF_CTRL_OVRD_VAL_MASK (0xe0UL)
#define HSAFE_VCO_CAL_CONFIG4_IQBUF_CTRL_OVRD_VAL_SHIFT (5UL)
#define HSAFE_VCO_CAL_CONFIG4_PLL_RSTB_OVRD_MASK (0x10UL)
#define HSAFE_VCO_CAL_CONFIG4_PLL_RSTB_OVRD_SHIFT (4UL)
#define HSAFE_VCO_CAL_CONFIG4_PLL_RSTB_OVRD_VAL_MASK (0x8UL)
#define HSAFE_VCO_CAL_CONFIG4_PLL_RSTB_OVRD_VAL_SHIFT (3UL)
#define HSAFE_VCO_CAL_CONFIG4_STOP_RECAL_MASK (0x4UL)
#define HSAFE_VCO_CAL_CONFIG4_STOP_RECAL_SHIFT (2UL)
#define HSAFE_VCO_CAL_CONFIG4_HALFSTEP_EN_MASK (0x2UL)
#define HSAFE_VCO_CAL_CONFIG4_HALFSTEP_EN_SHIFT (1UL)
#define HSAFE_VCO_CAL_CONFIG4_SEL_SDM_RESETB_VCOCAL_MASK (0x1UL)
#define HSAFE_VCO_CAL_CONFIG4_SEL_SDM_RESETB_VCOCAL_SHIFT (0UL)




typedef uint32_t HSAFE_VCO_CAL_CONFIG5_TYPE;
#define HSAFE_VCO_CAL_CONFIG5_WIN_MASK (0xff00UL)
#define HSAFE_VCO_CAL_CONFIG5_WIN_SHIFT (8UL)
#define HSAFE_VCO_CAL_CONFIG5_RES_MASK (0xffUL)
#define HSAFE_VCO_CAL_CONFIG5_RES_SHIFT (0UL)




typedef uint32_t HSAFE_VCO_CAL_CONFIG6_TYPE;
#define HSAFE_VCO_CAL_CONFIG6_VCO_CAL_CONFIG6_SPARE_MASK (0x8000UL)
#define HSAFE_VCO_CAL_CONFIG6_VCO_CAL_CONFIG6_SPARE_SHIFT (15UL)
#define HSAFE_VCO_CAL_CONFIG6_PM_PLLTUNINGBYPASS_MASK (0x4000UL)
#define HSAFE_VCO_CAL_CONFIG6_PM_PLLTUNINGBYPASS_SHIFT (14UL)
#define HSAFE_VCO_CAL_CONFIG6_PLL_RANGE_DFS_MASK (0x3f80UL)
#define HSAFE_VCO_CAL_CONFIG6_PLL_RANGE_DFS_SHIFT (7UL)
#define HSAFE_VCO_CAL_CONFIG6_EXT_RANGE_MASK (0x7fUL)
#define HSAFE_VCO_CAL_CONFIG6_EXT_RANGE_SHIFT (0UL)




typedef uint32_t HSAFE_AFE_SPARE_END_TYPE;
#define HSAFE_AFE_SPARE_END_MASK (0xffffffffUL)
#define HSAFE_AFE_SPARE_END_SHIFT (0UL)




typedef volatile struct sHSAFE_RDBType {
    HSAFE_AFE_COMMON0_TYPE afe_common0; /* OFFSET: 0x0 */
    HSAFE_RCCAL_CONTROL0_TYPE rccal_control0; /* OFFSET: 0x4 */
    HSAFE_RESCAL_CONTROL0_TYPE rescal_control0; /* OFFSET: 0x8 */
    HSAFE_RESCAL_CONTROL1_TYPE rescal_control1; /* OFFSET: 0xc */
    HSAFE_RESCAL_STATUS0_TYPE rescal_status0; /* OFFSET: 0x10 */
    HSAFE_RESCAL_VALUE_TYPE rescal_out; /* OFFSET: 0x14 */
    HSAFE_TXAFE_CONTROL0_TYPE txafe_control0; /* OFFSET: 0x18 */
    HSAFE_RESERVED_TYPE rsvd0[36]; /* OFFSET: 0x1c */
    HSAFE_ADC_CONTROL0_TYPE adc0_control0; /* OFFSET: 0x40 */
    HSAFE_ADC_STATUS0_TYPE adc0_status0; /* OFFSET: 0x44 */
    HSAFE_ADC_CONFIG0_TYPE adc0_config0; /* OFFSET: 0x48 */
    HSAFE_ADC_CONFIG1_TYPE adc0_config1; /* OFFSET: 0x4c */
    HSAFE_ADC_CONFIG2_TYPE adc0_config2; /* OFFSET: 0x50 */
    HSAFE_ADC_CONFIG3_TYPE adc0_config3; /* OFFSET: 0x54 */
    HSAFE_ADC_CONFIG4_TYPE adc0_config4; /* OFFSET: 0x58 */
    HSAFE_ADC_CONFIG5_TYPE adc0_config5; /* OFFSET: 0x5c */
    HSAFE_ADC_CONFIG6_TYPE adc0_config6; /* OFFSET: 0x60 */
    HSAFE_ADC_CONFIG7_TYPE adc0_config7; /* OFFSET: 0x64 */
    HSAFE_ADC_CONFIG8_TYPE adc0_config8; /* OFFSET: 0x68 */
    HSAFE_ADC_CONFIG9_TYPE adc0_config9; /* OFFSET: 0x6c */
    HSAFE_ADC_CONFIG10_TYPE adc0_config10; /* OFFSET: 0x70 */
    HSAFE_ADC_CONFIG11_TYPE adc0_config11; /* OFFSET: 0x74 */
    HSAFE_RESERVED_TYPE rsvd1[8]; /* OFFSET: 0x78 */
    HSAFE_ADC_CONTROL0_TYPE adc1_control0; /* OFFSET: 0x80 */
    HSAFE_ADC_STATUS0_TYPE adc1_status0; /* OFFSET: 0x84 */
    HSAFE_ADC_CONFIG0_TYPE adc1_config0; /* OFFSET: 0x88 */
    HSAFE_ADC_CONFIG1_TYPE adc1_config1; /* OFFSET: 0x8c */
    HSAFE_ADC_CONFIG2_TYPE adc1_config2; /* OFFSET: 0x90 */
    HSAFE_ADC_CONFIG3_TYPE adc1_config3; /* OFFSET: 0x94 */
    HSAFE_ADC_CONFIG4_TYPE adc1_config4; /* OFFSET: 0x98 */
    HSAFE_ADC_CONFIG5_TYPE adc1_config5; /* OFFSET: 0x9c */
    HSAFE_ADC_CONFIG6_TYPE adc1_config6; /* OFFSET: 0xa0 */
    HSAFE_ADC_CONFIG7_TYPE adc1_config7; /* OFFSET: 0xa4 */
    HSAFE_ADC_CONFIG8_TYPE adc1_config8; /* OFFSET: 0xa8 */
    HSAFE_ADC_CONFIG9_TYPE adc1_config9; /* OFFSET: 0xac */
    HSAFE_ADC_CONFIG10_TYPE adc1_config10; /* OFFSET: 0xb0 */
    HSAFE_ADC_CONFIG11_TYPE adc1_config11; /* OFFSET: 0xb4 */
    HSAFE_RESERVED_TYPE rsvd2[8]; /* OFFSET: 0xb8 */
    HSAFE_ADC_CONTROL0_TYPE adc2_control0; /* OFFSET: 0xc0 */
    HSAFE_ADC_STATUS0_TYPE adc2_status0; /* OFFSET: 0xc4 */
    HSAFE_ADC_CONFIG0_TYPE adc2_config0; /* OFFSET: 0xc8 */
    HSAFE_ADC_CONFIG1_TYPE adc2_config1; /* OFFSET: 0xcc */
    HSAFE_ADC_CONFIG2_TYPE adc2_config2; /* OFFSET: 0xd0 */
    HSAFE_ADC_CONFIG3_TYPE adc2_config3; /* OFFSET: 0xd4 */
    HSAFE_ADC_CONFIG4_TYPE adc2_config4; /* OFFSET: 0xd8 */
    HSAFE_ADC_CONFIG5_TYPE adc2_config5; /* OFFSET: 0xdc */
    HSAFE_ADC_CONFIG6_TYPE adc2_config6; /* OFFSET: 0xe0 */
    HSAFE_ADC_CONFIG7_TYPE adc2_config7; /* OFFSET: 0xe4 */
    HSAFE_ADC_CONFIG8_TYPE adc2_config8; /* OFFSET: 0xe8 */
    HSAFE_ADC_CONFIG9_TYPE adc2_config9; /* OFFSET: 0xec */
    HSAFE_ADC_CONFIG10_TYPE adc2_config10; /* OFFSET: 0xf0 */
    HSAFE_ADC_CONFIG11_TYPE adc2_config11; /* OFFSET: 0xf4 */
    HSAFE_RESERVED_TYPE rsvd3[8]; /* OFFSET: 0xf8 */
    HSAFE_ADC_CONTROL0_TYPE adc3_control0; /* OFFSET: 0x100 */
    HSAFE_ADC_STATUS0_TYPE adc3_status0; /* OFFSET: 0x104 */
    HSAFE_ADC_CONFIG0_TYPE adc3_config0; /* OFFSET: 0x108 */
    HSAFE_ADC_CONFIG1_TYPE adc3_config1; /* OFFSET: 0x10c */
    HSAFE_ADC_CONFIG2_TYPE adc3_config2; /* OFFSET: 0x110 */
    HSAFE_ADC_CONFIG3_TYPE adc3_config3; /* OFFSET: 0x114 */
    HSAFE_ADC_CONFIG4_TYPE adc3_config4; /* OFFSET: 0x118 */
    HSAFE_ADC_CONFIG5_TYPE adc3_config5; /* OFFSET: 0x11c */
    HSAFE_ADC_CONFIG6_TYPE adc3_config6; /* OFFSET: 0x120 */
    HSAFE_ADC_CONFIG7_TYPE adc3_config7; /* OFFSET: 0x124 */
    HSAFE_ADC_CONFIG8_TYPE adc3_config8; /* OFFSET: 0x128 */
    HSAFE_ADC_CONFIG9_TYPE adc3_config9; /* OFFSET: 0x12c */
    HSAFE_ADC_CONFIG10_TYPE adc3_config10; /* OFFSET: 0x130 */
    HSAFE_ADC_CONFIG11_TYPE adc3_config11; /* OFFSET: 0x134 */
    HSAFE_RESERVED_TYPE rsvd4[8]; /* OFFSET: 0x138 */
    HSAFE_ADC_CONTROL0_TYPE adcr_control0; /* OFFSET: 0x140 */
    HSAFE_ADC_STATUS0_TYPE adcr_status0; /* OFFSET: 0x144 */
    HSAFE_ADCR_CONFIG0_TYPE adcr_config0; /* OFFSET: 0x148 */
    HSAFE_ADCR_CONFIG1_TYPE adcr_config1; /* OFFSET: 0x14c */
    HSAFE_ADCR_CONFIG2_TYPE adcr_config2; /* OFFSET: 0x150 */
    HSAFE_ADCR_CONFIG3_TYPE adcr_config3; /* OFFSET: 0x154 */
    HSAFE_RESERVED_TYPE rsvd5[40]; /* OFFSET: 0x158 */
    HSAFE_BIAS_CONFIG0_TYPE bias_config0; /* OFFSET: 0x180 */
    HSAFE_BIAS_CONFIG1_TYPE bias_config1; /* OFFSET: 0x184 */
    HSAFE_BIAS_CONFIG2_TYPE bias_config2; /* OFFSET: 0x188 */
    HSAFE_BIAS_CONFIG3_TYPE bias_config3; /* OFFSET: 0x18c */
    HSAFE_BIAS_CONFIG4_TYPE bias_config4; /* OFFSET: 0x190 */
    HSAFE_BIAS_CONFIG5_TYPE bias_config5; /* OFFSET: 0x194 */
    HSAFE_BIAS_CONFIG6_TYPE bias_config6; /* OFFSET: 0x198 */
    HSAFE_BIAS_CONFIG7_TYPE bias_config7; /* OFFSET: 0x19c */
    HSAFE_BIAS_CONFIG8_TYPE bias_config8; /* OFFSET: 0x1a0 */
    HSAFE_BIAS_CONFIG9_TYPE bias_config9; /* OFFSET: 0x1a4 */
    HSAFE_CLKGEN_CONFIG0_TYPE clkgen_config0; /* OFFSET: 0x1a8 */
    HSAFE_CLKGEN_CONFIG1_TYPE clkgen_config1; /* OFFSET: 0x1ac */
    HSAFE_RESERVED_TYPE rsvd6[16]; /* OFFSET: 0x1b0 */
    HSAFE_PLL_CONTROL0_TYPE pll_control0; /* OFFSET: 0x1c0 */
    HSAFE_PLL_STATUS0_TYPE pll_status0; /* OFFSET: 0x1c4 */
    HSAFE_PLL_CONFIG0_TYPE pll_config0; /* OFFSET: 0x1c8 */
    HSAFE_PLL_CONFIG1_TYPE pll_config1; /* OFFSET: 0x1cc */
    HSAFE_PLL_CONFIG2_TYPE pll_config2; /* OFFSET: 0x1d0 */
    HSAFE_PLL_CONFIG3_TYPE pll_config3; /* OFFSET: 0x1d4 */
    HSAFE_PLL_CONFIG4_TYPE pll_config4; /* OFFSET: 0x1d8 */
    HSAFE_PLL_CONFIG5_TYPE pll_config5; /* OFFSET: 0x1dc */
    HSAFE_PLL_CONFIG6_TYPE pll_config6; /* OFFSET: 0x1e0 */
    HSAFE_PLL_CONFIG7_TYPE pll_config7; /* OFFSET: 0x1e4 */
    HSAFE_PLL_CONFIG8_TYPE pll_config8; /* OFFSET: 0x1e8 */
    HSAFE_PLL_CONFIG9_TYPE pll_config9; /* OFFSET: 0x1ec */
    HSAFE_PLL_CONFIG10_TYPE pll_config10; /* OFFSET: 0x1f0 */
    HSAFE_PLL_CONFIG11_TYPE pll_config11; /* OFFSET: 0x1f4 */
    HSAFE_VCO_CAL_CONFIG0_TYPE pll_cal_config0; /* OFFSET: 0x1f8 */
    HSAFE_VCO_CAL_CONFIG1_TYPE pll_cal_config1; /* OFFSET: 0x1fc */
    HSAFE_VCO_CAL_CONFIG2_TYPE pll_cal_config2; /* OFFSET: 0x200 */
    HSAFE_VCO_CAL_CONFIG3_TYPE pll_cal_config3; /* OFFSET: 0x204 */
    HSAFE_VCO_CAL_CONFIG4_TYPE pll_cal_config4; /* OFFSET: 0x208 */
    HSAFE_VCO_CAL_CONFIG5_TYPE pll_cal_config5; /* OFFSET: 0x20c */
    HSAFE_VCO_CAL_CONFIG6_TYPE pll_cal_config6; /* OFFSET: 0x210 */
    HSAFE_RESERVED_TYPE rsvd7[3304]; /* OFFSET: 0x214 */
    HSAFE_AFE_SPARE_END_TYPE afe_spare_end; /* OFFSET: 0xefc */
} HSAFE_RDBType;


#define HSAFE_BASE                      (0xE0601000UL)



#define HSAFE_MAX_HW_ID                 (1UL)

#endif /* HSAFE_RDB_H */
