/*****************************************************************************
 Copyright 2025 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file hsio_common_rdb.h
    @brief RDB File for HSIO_COMMON

    @version BCM89580_A0_20230125_RDB
*/

#ifndef HSIO_COMMON_RDB_H
#define HSIO_COMMON_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t HSIO_COMMON_HSIO_CTRL_32BIT_0_TYPE;
#define HSIO_COMMON_HSIO_CTRL_32BIT_0_POR_N_OVRD_SEL_MASK (0x80000000UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_0_POR_N_OVRD_SEL_SHIFT (31UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_0_POR_N_OVRD_VAL_MASK (0x40000000UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_0_POR_N_OVRD_VAL_SHIFT (30UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_0_PCIE_PERST_N_OVRD_SEL_MASK (0x20000000UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_0_PCIE_PERST_N_OVRD_SEL_SHIFT (29UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_0_PCIE_PERST_N_OVRD_VAL_MASK (0x10000000UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_0_PCIE_PERST_N_OVRD_VAL_SHIFT (28UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_0_MIPI_RESET_N_MASK (0x8000000UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_0_MIPI_RESET_N_SHIFT (27UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_0_ETH_SYS_RESET_N_MASK (0x4000000UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_0_ETH_SYS_RESET_N_SHIFT (26UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_0_BRPHY_PLL_RESET_N_MASK (0x2000000UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_0_BRPHY_PLL_RESET_N_SHIFT (25UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_0_ETH_CRST_N_MASK (0x1000000UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_0_ETH_CRST_N_SHIFT (24UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_0_S16U_REFCLK_RESET_N_MASK (0x800000UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_0_S16U_REFCLK_RESET_N_SHIFT (23UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_0_SPARE00_MASK (0x7fffffUL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_0_SPARE00_SHIFT (0UL)




typedef uint32_t HSIO_COMMON_HSIO_CTRL_32BIT_1_TYPE;
#define HSIO_COMMON_HSIO_CTRL_32BIT_1_RESERVED_15_MASK (0xffff8000UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_1_RESERVED_15_SHIFT (15UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_1_RESERVED_14_MASK (0x4000UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_1_RESERVED_14_SHIFT (14UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_1_RESERVED_13_MASK (0x2000UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_1_RESERVED_13_SHIFT (13UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_1_RESERVED_12_MASK (0x1000UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_1_RESERVED_12_SHIFT (12UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_1_RESERVED_4_MASK (0xff0UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_1_RESERVED_4_SHIFT (4UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_1_GPIO_SEL_MASK (0xfUL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_1_GPIO_SEL_SHIFT (0UL)




typedef uint32_t HSIO_COMMON_HSIO_CTRL_32BIT_2_TYPE;
#define HSIO_COMMON_HSIO_CTRL_32BIT_2_SPARE02_MASK (0xffffffffUL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_2_SPARE02_SHIFT (0UL)




typedef uint32_t HSIO_COMMON_HSIO_CTRL_32BIT_3_TYPE;
#define HSIO_COMMON_HSIO_CTRL_32BIT_3_SPARE03_MASK (0xffffffffUL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_3_SPARE03_SHIFT (0UL)




typedef uint32_t HSIO_COMMON_HSIO_CTRL_32BIT_4_TYPE;
#define HSIO_COMMON_HSIO_CTRL_32BIT_4_SPARE04_MASK (0xffffffffUL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_4_SPARE04_SHIFT (0UL)




typedef uint32_t HSIO_COMMON_HSIO_CTRL_32BIT_5_TYPE;
#define HSIO_COMMON_HSIO_CTRL_32BIT_5_IDDQ_OVRD_SEL_MASK (0x80000000UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_5_IDDQ_OVRD_SEL_SHIFT (31UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_5_PCIE_IDDQ_OVRD_VAL_MASK (0x40000000UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_5_PCIE_IDDQ_OVRD_VAL_SHIFT (30UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_5_MIPI_IDDQ_OVRD_VAL_MASK (0x20000000UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_5_MIPI_IDDQ_OVRD_VAL_SHIFT (29UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_5_SPARE05A_MASK (0x10000000UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_5_SPARE05A_SHIFT (28UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_5_IDDQ_S16UP_MASK (0x8000000UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_5_IDDQ_S16UP_SHIFT (27UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_5_IDDQ0_BRPHY_MASK (0x4000000UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_5_IDDQ0_BRPHY_SHIFT (26UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_5_IDDQ_BIAS_BRPHY_MASK (0x2000000UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_5_IDDQ_BIAS_BRPHY_SHIFT (25UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_5_SPARE05_MASK (0x1fe0000UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_5_SPARE05_SHIFT (17UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_5_RES_CAL_VLD_OVRD_SEL_MASK (0x10000UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_5_RES_CAL_VLD_OVRD_SEL_SHIFT (16UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_5_RES_CAL_VLD_OVRD_VAL_MASK (0x8000UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_5_RES_CAL_VLD_OVRD_VAL_SHIFT (15UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_5_ETH_RES_CAL_OVRD_SEL_MASK (0x4000UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_5_ETH_RES_CAL_OVRD_SEL_SHIFT (14UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_5_MIPI_RES_CAL_OVRD_SEL_MASK (0x2000UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_5_MIPI_RES_CAL_OVRD_SEL_SHIFT (13UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_5_PCIE_RES_CAL_OVRD_SEL_MASK (0x1000UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_5_PCIE_RES_CAL_OVRD_SEL_SHIFT (12UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_5_ETH_RES_CAL_OVRD_VAL_MASK (0xf00UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_5_ETH_RES_CAL_OVRD_VAL_SHIFT (8UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_5_MIPI_RES_CAL_OVRD_VAL_MASK (0xf0UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_5_MIPI_RES_CAL_OVRD_VAL_SHIFT (4UL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_5_PCIE_RES_CAL_OVRD_VAL_MASK (0xfUL)
#define HSIO_COMMON_HSIO_CTRL_32BIT_5_PCIE_RES_CAL_OVRD_VAL_SHIFT (0UL)




typedef uint8_t HSIO_COMMON_RESERVED_TYPE;




typedef uint32_t HSIO_COMMON_PCIE_CTRL_32BIT_0_TYPE;
#define HSIO_COMMON_PCIE_CTRL_32BIT_0_STRAP_PCIE_RC_MODE_MASK (0x80000000UL)
#define HSIO_COMMON_PCIE_CTRL_32BIT_0_STRAP_PCIE_RC_MODE_SHIFT (31UL)
#define HSIO_COMMON_PCIE_CTRL_32BIT_0_SPARE00_MASK (0x7c000000UL)
#define HSIO_COMMON_PCIE_CTRL_32BIT_0_SPARE00_SHIFT (26UL)
#define HSIO_COMMON_PCIE_CTRL_32BIT_0_PCIE_IN_WAKE_MASK (0x2000000UL)
#define HSIO_COMMON_PCIE_CTRL_32BIT_0_PCIE_IN_WAKE_SHIFT (25UL)
#define HSIO_COMMON_PCIE_CTRL_32BIT_0_ICFG_INT_ENABLE_WR1B_MODE_MASK (0x1000000UL)
#define HSIO_COMMON_PCIE_CTRL_32BIT_0_ICFG_INT_ENABLE_WR1B_MODE_SHIFT (24UL)
#define HSIO_COMMON_PCIE_CTRL_32BIT_0_STRAP_CHIP_REVISION_ID_MASK (0xff0000UL)
#define HSIO_COMMON_PCIE_CTRL_32BIT_0_STRAP_CHIP_REVISION_ID_SHIFT (16UL)
#define HSIO_COMMON_PCIE_CTRL_32BIT_0_STRAP_USER_DEVICE_ID_MASK (0xffffUL)
#define HSIO_COMMON_PCIE_CTRL_32BIT_0_STRAP_USER_DEVICE_ID_SHIFT (0UL)




typedef uint32_t HSIO_COMMON_PCIE_CTRL_32BIT_1_TYPE;
#define HSIO_COMMON_PCIE_CTRL_32BIT_1_STRAP_USER_DEVICE_ID_MASK (0xffff0000UL)
#define HSIO_COMMON_PCIE_CTRL_32BIT_1_STRAP_USER_DEVICE_ID_SHIFT (16UL)
#define HSIO_COMMON_PCIE_CTRL_32BIT_1_STRAP_IP_DISABLE_PCIE_MASK (0x8000UL)
#define HSIO_COMMON_PCIE_CTRL_32BIT_1_STRAP_IP_DISABLE_PCIE_SHIFT (15UL)
#define HSIO_COMMON_PCIE_CTRL_32BIT_1_STRAP_USER_FORCE_LANE_MASK (0x6000UL)
#define HSIO_COMMON_PCIE_CTRL_32BIT_1_STRAP_USER_FORCE_LANE_SHIFT (13UL)
#define HSIO_COMMON_PCIE_CTRL_32BIT_1_STRAP_USER_FORCE_GEN_MASK (0x1800UL)
#define HSIO_COMMON_PCIE_CTRL_32BIT_1_STRAP_USER_FORCE_GEN_SHIFT (11UL)
#define HSIO_COMMON_PCIE_CTRL_32BIT_1_RESERVED_10_MASK (0x400UL)
#define HSIO_COMMON_PCIE_CTRL_32BIT_1_RESERVED_10_SHIFT (10UL)
#define HSIO_COMMON_PCIE_CTRL_32BIT_1_RESERVED_5_MASK (0x3e0UL)
#define HSIO_COMMON_PCIE_CTRL_32BIT_1_RESERVED_5_SHIFT (5UL)
#define HSIO_COMMON_PCIE_CTRL_32BIT_1_RESERVED_0_MASK (0x1fUL)
#define HSIO_COMMON_PCIE_CTRL_32BIT_1_RESERVED_0_SHIFT (0UL)




typedef uint32_t HSIO_COMMON_PCIE_CTRL_32BIT_2_TYPE;
#define HSIO_COMMON_PCIE_CTRL_32BIT_2_SPARE_PCIE_31_16_MASK (0xffff0000UL)
#define HSIO_COMMON_PCIE_CTRL_32BIT_2_SPARE_PCIE_31_16_SHIFT (16UL)
#define HSIO_COMMON_PCIE_CTRL_32BIT_2_IMAP_PAGE_SELECT_MASK (0xc000UL)
#define HSIO_COMMON_PCIE_CTRL_32BIT_2_IMAP_PAGE_SELECT_SHIFT (14UL)
#define HSIO_COMMON_PCIE_CTRL_32BIT_2_PHY_TEST_MODE_MASK (0x2000UL)
#define HSIO_COMMON_PCIE_CTRL_32BIT_2_PHY_TEST_MODE_SHIFT (13UL)
#define HSIO_COMMON_PCIE_CTRL_32BIT_2_REFCLKZ_IN_SELECT_MASK (0x1c00UL)
#define HSIO_COMMON_PCIE_CTRL_32BIT_2_REFCLKZ_IN_SELECT_SHIFT (10UL)
#define HSIO_COMMON_PCIE_CTRL_32BIT_2_SPARE04_MASK (0x300UL)
#define HSIO_COMMON_PCIE_CTRL_32BIT_2_SPARE04_SHIFT (8UL)
#define HSIO_COMMON_PCIE_CTRL_32BIT_2_MISC_DEBUG_SEL_2_MASK (0xf0UL)
#define HSIO_COMMON_PCIE_CTRL_32BIT_2_MISC_DEBUG_SEL_2_SHIFT (4UL)
#define HSIO_COMMON_PCIE_CTRL_32BIT_2_MISC_DEBUG_SEL_1_MASK (0xfUL)
#define HSIO_COMMON_PCIE_CTRL_32BIT_2_MISC_DEBUG_SEL_1_SHIFT (0UL)




typedef uint32_t HSIO_COMMON_ETH_CTRL_32BIT_0_TYPE;
#define HSIO_COMMON_ETH_CTRL_32BIT_0_SPARE00_MASK (0xfffffe00UL)
#define HSIO_COMMON_ETH_CTRL_32BIT_0_SPARE00_SHIFT (9UL)
#define HSIO_COMMON_ETH_CTRL_32BIT_0_TEST_EN_MSPU_MASK (0x100UL)
#define HSIO_COMMON_ETH_CTRL_32BIT_0_TEST_EN_MSPU_SHIFT (8UL)
#define HSIO_COMMON_ETH_CTRL_32BIT_0_CSYSREQ_I_MASK (0x80UL)
#define HSIO_COMMON_ETH_CTRL_32BIT_0_CSYSREQ_I_SHIFT (7UL)
#define HSIO_COMMON_ETH_CTRL_32BIT_0_GMII_CRS_I_MASK (0x40UL)
#define HSIO_COMMON_ETH_CTRL_32BIT_0_GMII_CRS_I_SHIFT (6UL)
#define HSIO_COMMON_ETH_CTRL_32BIT_0_I_PLL_REFCLK_CMOS_MASK (0x20UL)
#define HSIO_COMMON_ETH_CTRL_32BIT_0_I_PLL_REFCLK_CMOS_SHIFT (5UL)
#define HSIO_COMMON_ETH_CTRL_32BIT_0_I_PLL_REFCLK_PD_MASK (0x10UL)
#define HSIO_COMMON_ETH_CTRL_32BIT_0_I_PLL_REFCLK_PD_SHIFT (4UL)
#define HSIO_COMMON_ETH_CTRL_32BIT_0_I_PLL_REFSEL_MASK (0xeUL)
#define HSIO_COMMON_ETH_CTRL_32BIT_0_I_PLL_REFSEL_SHIFT (1UL)
#define HSIO_COMMON_ETH_CTRL_32BIT_0_EXTPHY_SEL_MASK (0x1UL)
#define HSIO_COMMON_ETH_CTRL_32BIT_0_EXTPHY_SEL_SHIFT (0UL)




typedef uint32_t HSIO_COMMON_HSIO_STAT_32BIT_0_TYPE;
#define HSIO_COMMON_HSIO_STAT_32BIT_0_STATUS00_MASK (0xffffffffUL)
#define HSIO_COMMON_HSIO_STAT_32BIT_0_STATUS00_SHIFT (0UL)




typedef uint32_t HSIO_COMMON_HSIO_STAT_32BIT_1_TYPE;
#define HSIO_COMMON_HSIO_STAT_32BIT_1_STATUS01_MASK (0xffffffffUL)
#define HSIO_COMMON_HSIO_STAT_32BIT_1_STATUS01_SHIFT (0UL)




typedef uint32_t HSIO_COMMON_HSIO_STAT_32BIT_2_TYPE;
#define HSIO_COMMON_HSIO_STAT_32BIT_2_STATUS02_MASK (0xffffffffUL)
#define HSIO_COMMON_HSIO_STAT_32BIT_2_STATUS02_SHIFT (0UL)




typedef uint32_t HSIO_COMMON_HSIO_STAT_32BIT_3_TYPE;
#define HSIO_COMMON_HSIO_STAT_32BIT_3_STATUS03_MASK (0xffffffffUL)
#define HSIO_COMMON_HSIO_STAT_32BIT_3_STATUS03_SHIFT (0UL)




typedef uint32_t HSIO_COMMON_PCIE_STAT_32BIT_0_TYPE;
#define HSIO_COMMON_PCIE_STAT_32BIT_0_STATUS00_MASK (0xffffffffUL)
#define HSIO_COMMON_PCIE_STAT_32BIT_0_STATUS00_SHIFT (0UL)




typedef uint32_t HSIO_COMMON_PCIE_STAT_32BIT_1_TYPE;
#define HSIO_COMMON_PCIE_STAT_32BIT_1_STATUS01_MASK (0xffffffffUL)
#define HSIO_COMMON_PCIE_STAT_32BIT_1_STATUS01_SHIFT (0UL)




typedef uint32_t HSIO_COMMON_ETH_STAT_32BIT_0_TYPE;
#define HSIO_COMMON_ETH_STAT_32BIT_0_LED_O_PHY_MASK (0xf0000000UL)
#define HSIO_COMMON_ETH_STAT_32BIT_0_LED_O_PHY_SHIFT (28UL)
#define HSIO_COMMON_ETH_STAT_32BIT_0_STATUS00_MASK (0xff00000UL)
#define HSIO_COMMON_ETH_STAT_32BIT_0_STATUS00_SHIFT (20UL)
#define HSIO_COMMON_ETH_STAT_32BIT_0_BRPHY_LINK_STATUS_MASK (0x80000UL)
#define HSIO_COMMON_ETH_STAT_32BIT_0_BRPHY_LINK_STATUS_SHIFT (19UL)
#define HSIO_COMMON_ETH_STAT_32BIT_0_BRPHY_RX_PAUSE_MASK (0x40000UL)
#define HSIO_COMMON_ETH_STAT_32BIT_0_BRPHY_RX_PAUSE_SHIFT (18UL)
#define HSIO_COMMON_ETH_STAT_32BIT_0_BRPHY_TX_PAUSE_MASK (0x20000UL)
#define HSIO_COMMON_ETH_STAT_32BIT_0_BRPHY_TX_PAUSE_SHIFT (17UL)
#define HSIO_COMMON_ETH_STAT_32BIT_0_AXIMRC_ARQOS_M_O_MASK (0x1e000UL)
#define HSIO_COMMON_ETH_STAT_32BIT_0_AXIMRC_ARQOS_M_O_SHIFT (13UL)
#define HSIO_COMMON_ETH_STAT_32BIT_0_AXIMRC_ARDOMAIN_M_O_MASK (0x1800UL)
#define HSIO_COMMON_ETH_STAT_32BIT_0_AXIMRC_ARDOMAIN_M_O_SHIFT (11UL)
#define HSIO_COMMON_ETH_STAT_32BIT_0_ACTV_RST_CLK_TX_MASK (0x400UL)
#define HSIO_COMMON_ETH_STAT_32BIT_0_ACTV_RST_CLK_TX_SHIFT (10UL)
#define HSIO_COMMON_ETH_STAT_32BIT_0_ACTV_RST_CLK_RX_MASK (0x200UL)
#define HSIO_COMMON_ETH_STAT_32BIT_0_ACTV_RST_CLK_RX_SHIFT (9UL)
#define HSIO_COMMON_ETH_STAT_32BIT_0_ACTV_RST_CLK_PTP_MASK (0x100UL)
#define HSIO_COMMON_ETH_STAT_32BIT_0_ACTV_RST_CLK_PTP_SHIFT (8UL)
#define HSIO_COMMON_ETH_STAT_32BIT_0_ACTV_RST_CLK_CSR_MASK (0x80UL)
#define HSIO_COMMON_ETH_STAT_32BIT_0_ACTV_RST_CLK_CSR_SHIFT (7UL)
#define HSIO_COMMON_ETH_STAT_32BIT_0_ACTV_RST_CLK_APP_MASK (0x40UL)
#define HSIO_COMMON_ETH_STAT_32BIT_0_ACTV_RST_CLK_APP_SHIFT (6UL)
#define HSIO_COMMON_ETH_STAT_32BIT_0_S16UP_PAUSE_TX_MASK (0x20UL)
#define HSIO_COMMON_ETH_STAT_32BIT_0_S16UP_PAUSE_TX_SHIFT (5UL)
#define HSIO_COMMON_ETH_STAT_32BIT_0_S16UP_PAUSE_RX_MASK (0x10UL)
#define HSIO_COMMON_ETH_STAT_32BIT_0_S16UP_PAUSE_RX_SHIFT (4UL)
#define HSIO_COMMON_ETH_STAT_32BIT_0_S16UP_LINK_STATUS_MASK (0x8UL)
#define HSIO_COMMON_ETH_STAT_32BIT_0_S16UP_LINK_STATUS_SHIFT (3UL)
#define HSIO_COMMON_ETH_STAT_32BIT_0_S16UP_DUPLEX_STATUS_MASK (0x4UL)
#define HSIO_COMMON_ETH_STAT_32BIT_0_S16UP_DUPLEX_STATUS_SHIFT (2UL)
#define HSIO_COMMON_ETH_STAT_32BIT_0_S16UP_PMD_RX_LOCK_MASK (0x2UL)
#define HSIO_COMMON_ETH_STAT_32BIT_0_S16UP_PMD_RX_LOCK_SHIFT (1UL)
#define HSIO_COMMON_ETH_STAT_32BIT_0_S16UP_PLL_LOCK_MASK (0x1UL)
#define HSIO_COMMON_ETH_STAT_32BIT_0_S16UP_PLL_LOCK_SHIFT (0UL)




typedef uint32_t HSIO_COMMON_ETH_STAT_32BIT_1_TYPE;
#define HSIO_COMMON_ETH_STAT_32BIT_1_STARTUP_TPOUT_MASK (0xffffffffUL)
#define HSIO_COMMON_ETH_STAT_32BIT_1_STARTUP_TPOUT_SHIFT (0UL)




typedef uint32_t HSIO_COMMON_ETH_STAT_32BIT_2_TYPE;
#define HSIO_COMMON_ETH_STAT_32BIT_2_SPARE_MASK (0xfffffffeUL)
#define HSIO_COMMON_ETH_STAT_32BIT_2_SPARE_SHIFT (1UL)
#define HSIO_COMMON_ETH_STAT_32BIT_2_STARTUP_TPOUT_B32_MASK (0x1UL)
#define HSIO_COMMON_ETH_STAT_32BIT_2_STARTUP_TPOUT_B32_SHIFT (0UL)




typedef volatile struct sHSIO_COMMON_RDBType {
    HSIO_COMMON_HSIO_CTRL_32BIT_0_TYPE hsio_ctrl_0; /* OFFSET: 0x0 */
    HSIO_COMMON_HSIO_CTRL_32BIT_1_TYPE hsio_ctrl_1; /* OFFSET: 0x4 */
    HSIO_COMMON_HSIO_CTRL_32BIT_2_TYPE hsio_ctrl_2; /* OFFSET: 0x8 */
    HSIO_COMMON_HSIO_CTRL_32BIT_3_TYPE hsio_ctrl_3; /* OFFSET: 0xc */
    HSIO_COMMON_HSIO_CTRL_32BIT_4_TYPE hsio_ctrl_4; /* OFFSET: 0x10 */
    HSIO_COMMON_HSIO_CTRL_32BIT_5_TYPE hsio_ctrl_5; /* OFFSET: 0x14 */
    HSIO_COMMON_RESERVED_TYPE rsvd0[16]; /* OFFSET: 0x18 */
    HSIO_COMMON_PCIE_CTRL_32BIT_0_TYPE pcie_ctrl_0; /* OFFSET: 0x28 */
    HSIO_COMMON_PCIE_CTRL_32BIT_1_TYPE pcie_ctrl_1; /* OFFSET: 0x2c */
    HSIO_COMMON_PCIE_CTRL_32BIT_2_TYPE pcie_ctrl_2; /* OFFSET: 0x30 */
    HSIO_COMMON_ETH_CTRL_32BIT_0_TYPE eth_ctrl_0; /* OFFSET: 0x34 */
    HSIO_COMMON_RESERVED_TYPE rsvd1[72]; /* OFFSET: 0x38 */
    HSIO_COMMON_HSIO_STAT_32BIT_0_TYPE hsio_stat_0; /* OFFSET: 0x80 */
    HSIO_COMMON_HSIO_STAT_32BIT_1_TYPE hsio_stat_1; /* OFFSET: 0x84 */
    HSIO_COMMON_HSIO_STAT_32BIT_2_TYPE hsio_stat_2; /* OFFSET: 0x88 */
    HSIO_COMMON_HSIO_STAT_32BIT_3_TYPE hsio_stat_3; /* OFFSET: 0x8c */
    HSIO_COMMON_PCIE_STAT_32BIT_0_TYPE pcie_stat_0; /* OFFSET: 0x90 */
    HSIO_COMMON_PCIE_STAT_32BIT_1_TYPE pcie_stat_1; /* OFFSET: 0x94 */
    HSIO_COMMON_RESERVED_TYPE rsvd2[8]; /* OFFSET: 0x98 */
    HSIO_COMMON_ETH_STAT_32BIT_0_TYPE eth_stat_0; /* OFFSET: 0xa0 */
    HSIO_COMMON_ETH_STAT_32BIT_1_TYPE eth_stat_1; /* OFFSET: 0xa4 */
    HSIO_COMMON_ETH_STAT_32BIT_2_TYPE eth_stat_2; /* OFFSET: 0xa8 */
} HSIO_COMMON_RDBType;


#define HSIO_COMMON_BASE                ((uintptr_t)(0xE02D0000UL))



#define HSIO_COMMON_MAX_HW_ID           (1UL)


#define HSIO_COMMON_PAGE_SELECT_COMMON  (0UL)


#define HSIO_COMMON_PAGE_SELECT_IMAP0   (1UL)


#define HSIO_COMMON_PAGE_SELECT_IMAP1   (2UL)


#define HSIO_COMMON_PAGE_SELECT_IMAP2   (3UL)


#define HSIO_COMMON_REFCLK_SEL_INT_CML  (0UL)


#define HSIO_COMMON_REFCLK_SEL_PADS     (2UL)


#define HSIO_COMMON_REFCLK_SEL_INT_CMOS  (4UL)

#endif /* HSIO_COMMON_RDB_H */
