/*****************************************************************************
 Copyright 2024 Broadcom.  All rights reserved.

 Broadcom Proprietary and Confidential
******************************************************************************/
/**
    @file hkadc_intr_rdb.h
    @brief RDB File for HKADC_INTR

    @version BCM89580_A0_20230125_RDB
*/

#ifndef HKADC_INTR_RDB_H
#define HKADC_INTR_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t HKADC_INTR_AHA0FIE_TYPE;
#define HKADC_INTR_AHA0FIE_P_ADC0_FIFO_OVERFLOW_INTR_MASK (0x80000000UL)
#define HKADC_INTR_AHA0FIE_P_ADC0_FIFO_OVERFLOW_INTR_SHIFT (31UL)
#define HKADC_INTR_AHA0FIE_P_ADC0_FIFO_UNDERFLOW_INTR_MASK (0x4UL)
#define HKADC_INTR_AHA0FIE_P_ADC0_FIFO_UNDERFLOW_INTR_SHIFT (2UL)
#define HKADC_INTR_AHA0FIE_P_ADC0_FIFO_EMPTY_INTR_MASK (0x2UL)
#define HKADC_INTR_AHA0FIE_P_ADC0_FIFO_EMPTY_INTR_SHIFT (1UL)
#define HKADC_INTR_AHA0FIE_P_ADC0_FIFO_THESHOLD_INTR_MASK (0x1UL)
#define HKADC_INTR_AHA0FIE_P_ADC0_FIFO_THESHOLD_INTR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA0FIE1_TYPE;
#define HKADC_INTR_AHA0FIE1_ADC0_FIFO_OVERFLOW_INTR_W2CLR_MASK (0x80000000UL)
#define HKADC_INTR_AHA0FIE1_ADC0_FIFO_OVERFLOW_INTR_W2CLR_SHIFT (31UL)
#define HKADC_INTR_AHA0FIE1_ADC0_FIFO_UNDERFLOW_INTR_W2CLR_MASK (0x4UL)
#define HKADC_INTR_AHA0FIE1_ADC0_FIFO_UNDERFLOW_INTR_W2CLR_SHIFT (2UL)
#define HKADC_INTR_AHA0FIE1_ADC0_FIFO_EMPTY_INTR_W2CLR_MASK (0x2UL)
#define HKADC_INTR_AHA0FIE1_ADC0_FIFO_EMPTY_INTR_W2CLR_SHIFT (1UL)
#define HKADC_INTR_AHA0FIE1_ADC0_FIFO_THESHOLD_INTR_W2CLR_MASK (0x1UL)
#define HKADC_INTR_AHA0FIE1_ADC0_FIFO_THESHOLD_INTR_W2CLR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA0FIE2_TYPE;
#define HKADC_INTR_AHA0FIE2_ENABLE_ADC0_FIFO_OVERFLOW_INTR_MASK (0x80000000UL)
#define HKADC_INTR_AHA0FIE2_ENABLE_ADC0_FIFO_OVERFLOW_INTR_SHIFT (31UL)
#define HKADC_INTR_AHA0FIE2_ENABLE_ADC0_FIFO_UNDERFLOW_INTR_MASK (0x4UL)
#define HKADC_INTR_AHA0FIE2_ENABLE_ADC0_FIFO_UNDERFLOW_INTR_SHIFT (2UL)
#define HKADC_INTR_AHA0FIE2_ENABLE_ADC0_FIFO_EMPTY_INTR_MASK (0x2UL)
#define HKADC_INTR_AHA0FIE2_ENABLE_ADC0_FIFO_EMPTY_INTR_SHIFT (1UL)
#define HKADC_INTR_AHA0FIE2_ENABLE_ADC0_FIFO_THESHOLD_INTR_MASK (0x1UL)
#define HKADC_INTR_AHA0FIE2_ENABLE_ADC0_FIFO_THESHOLD_INTR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA0TIE_TYPE;
#define HKADC_INTR_AHA0TIE_P_ADC0_VALUE_THRESHOLD1_INTR_MASK (0x80000000UL)
#define HKADC_INTR_AHA0TIE_P_ADC0_VALUE_THRESHOLD1_INTR_SHIFT (31UL)
#define HKADC_INTR_AHA0TIE_P_ADC0_VALUE_THRESHOLD0_INTR_MASK (0x1UL)
#define HKADC_INTR_AHA0TIE_P_ADC0_VALUE_THRESHOLD0_INTR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA0TIE1_TYPE;
#define HKADC_INTR_AHA0TIE1_ADC0_VALUE_THRESHOLD1_INTR_W2CLR_MASK (0x80000000UL)
#define HKADC_INTR_AHA0TIE1_ADC0_VALUE_THRESHOLD1_INTR_W2CLR_SHIFT (31UL)
#define HKADC_INTR_AHA0TIE1_ADC0_VALUE_THRESHOLD0_INTR_W2CLR_MASK (0x1UL)
#define HKADC_INTR_AHA0TIE1_ADC0_VALUE_THRESHOLD0_INTR_W2CLR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA0TIE2_TYPE;
#define HKADC_INTR_AHA0TIE2_ENABLE_ADC0_VALUE_THRESHOLD1_INTR_MASK (0x80000000UL)
#define HKADC_INTR_AHA0TIE2_ENABLE_ADC0_VALUE_THRESHOLD1_INTR_SHIFT (31UL)
#define HKADC_INTR_AHA0TIE2_ENABLE_ADC0_VALUE_THRESHOLD0_INTR_MASK (0x1UL)
#define HKADC_INTR_AHA0TIE2_ENABLE_ADC0_VALUE_THRESHOLD0_INTR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA1FIE_TYPE;
#define HKADC_INTR_AHA1FIE_P_ADC1_FIFO_OVERFLOW_INTR_MASK (0x80000000UL)
#define HKADC_INTR_AHA1FIE_P_ADC1_FIFO_OVERFLOW_INTR_SHIFT (31UL)
#define HKADC_INTR_AHA1FIE_P_ADC1_FIFO_UNDERFLOW_INTR_MASK (0x4UL)
#define HKADC_INTR_AHA1FIE_P_ADC1_FIFO_UNDERFLOW_INTR_SHIFT (2UL)
#define HKADC_INTR_AHA1FIE_P_ADC1_FIFO_EMPTY_INTR_MASK (0x2UL)
#define HKADC_INTR_AHA1FIE_P_ADC1_FIFO_EMPTY_INTR_SHIFT (1UL)
#define HKADC_INTR_AHA1FIE_P_ADC1_FIFO_THESHOLD_INTR_MASK (0x1UL)
#define HKADC_INTR_AHA1FIE_P_ADC1_FIFO_THESHOLD_INTR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA1FIE1_TYPE;
#define HKADC_INTR_AHA1FIE1_ADC1_FIFO_OVERFLOW_INTR_W2CLR_MASK (0x80000000UL)
#define HKADC_INTR_AHA1FIE1_ADC1_FIFO_OVERFLOW_INTR_W2CLR_SHIFT (31UL)
#define HKADC_INTR_AHA1FIE1_ADC1_FIFO_UNDERFLOW_INTR_W2CLR_MASK (0x4UL)
#define HKADC_INTR_AHA1FIE1_ADC1_FIFO_UNDERFLOW_INTR_W2CLR_SHIFT (2UL)
#define HKADC_INTR_AHA1FIE1_ADC1_FIFO_EMPTY_INTR_W2CLR_MASK (0x2UL)
#define HKADC_INTR_AHA1FIE1_ADC1_FIFO_EMPTY_INTR_W2CLR_SHIFT (1UL)
#define HKADC_INTR_AHA1FIE1_ADC1_FIFO_THESHOLD_INTR_W2CLR_MASK (0x1UL)
#define HKADC_INTR_AHA1FIE1_ADC1_FIFO_THESHOLD_INTR_W2CLR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA1FIE2_TYPE;
#define HKADC_INTR_AHA1FIE2_ENABLE_ADC1_FIFO_OVERFLOW_INTR_MASK (0x80000000UL)
#define HKADC_INTR_AHA1FIE2_ENABLE_ADC1_FIFO_OVERFLOW_INTR_SHIFT (31UL)
#define HKADC_INTR_AHA1FIE2_ENABLE_ADC1_FIFO_UNDERFLOW_INTR_MASK (0x4UL)
#define HKADC_INTR_AHA1FIE2_ENABLE_ADC1_FIFO_UNDERFLOW_INTR_SHIFT (2UL)
#define HKADC_INTR_AHA1FIE2_ENABLE_ADC1_FIFO_EMPTY_INTR_MASK (0x2UL)
#define HKADC_INTR_AHA1FIE2_ENABLE_ADC1_FIFO_EMPTY_INTR_SHIFT (1UL)
#define HKADC_INTR_AHA1FIE2_ENABLE_ADC1_FIFO_THESHOLD_INTR_MASK (0x1UL)
#define HKADC_INTR_AHA1FIE2_ENABLE_ADC1_FIFO_THESHOLD_INTR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA1TIE_TYPE;
#define HKADC_INTR_AHA1TIE_P_ADC1_VALUE_THRESHOLD1_INTR_MASK (0x80000000UL)
#define HKADC_INTR_AHA1TIE_P_ADC1_VALUE_THRESHOLD1_INTR_SHIFT (31UL)
#define HKADC_INTR_AHA1TIE_P_ADC1_VALUE_THRESHOLD0_INTR_MASK (0x1UL)
#define HKADC_INTR_AHA1TIE_P_ADC1_VALUE_THRESHOLD0_INTR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA1TIE1_TYPE;
#define HKADC_INTR_AHA1TIE1_ADC1_VALUE_THRESHOLD1_INTR_W2CLR_MASK (0x80000000UL)
#define HKADC_INTR_AHA1TIE1_ADC1_VALUE_THRESHOLD1_INTR_W2CLR_SHIFT (31UL)
#define HKADC_INTR_AHA1TIE1_ADC1_VALUE_THRESHOLD0_INTR_W2CLR_MASK (0x1UL)
#define HKADC_INTR_AHA1TIE1_ADC1_VALUE_THRESHOLD0_INTR_W2CLR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA1TIE2_TYPE;
#define HKADC_INTR_AHA1TIE2_ENABLE_ADC1_VALUE_THRESHOLD1_INTR_MASK (0x80000000UL)
#define HKADC_INTR_AHA1TIE2_ENABLE_ADC1_VALUE_THRESHOLD1_INTR_SHIFT (31UL)
#define HKADC_INTR_AHA1TIE2_ENABLE_ADC1_VALUE_THRESHOLD0_INTR_MASK (0x1UL)
#define HKADC_INTR_AHA1TIE2_ENABLE_ADC1_VALUE_THRESHOLD0_INTR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA2FIE_TYPE;
#define HKADC_INTR_AHA2FIE_P_ADC2_FIFO_OVERFLOW_INTR_MASK (0x80000000UL)
#define HKADC_INTR_AHA2FIE_P_ADC2_FIFO_OVERFLOW_INTR_SHIFT (31UL)
#define HKADC_INTR_AHA2FIE_P_ADC2_FIFO_UNDERFLOW_INTR_MASK (0x4UL)
#define HKADC_INTR_AHA2FIE_P_ADC2_FIFO_UNDERFLOW_INTR_SHIFT (2UL)
#define HKADC_INTR_AHA2FIE_P_ADC2_FIFO_EMPTY_INTR_MASK (0x2UL)
#define HKADC_INTR_AHA2FIE_P_ADC2_FIFO_EMPTY_INTR_SHIFT (1UL)
#define HKADC_INTR_AHA2FIE_P_ADC2_FIFO_THESHOLD_INTR_MASK (0x1UL)
#define HKADC_INTR_AHA2FIE_P_ADC2_FIFO_THESHOLD_INTR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA2FIE1_TYPE;
#define HKADC_INTR_AHA2FIE1_ADC2_FIFO_OVERFLOW_INTR_W2CLR_MASK (0x80000000UL)
#define HKADC_INTR_AHA2FIE1_ADC2_FIFO_OVERFLOW_INTR_W2CLR_SHIFT (31UL)
#define HKADC_INTR_AHA2FIE1_ADC2_FIFO_UNDERFLOW_INTR_W2CLR_MASK (0x4UL)
#define HKADC_INTR_AHA2FIE1_ADC2_FIFO_UNDERFLOW_INTR_W2CLR_SHIFT (2UL)
#define HKADC_INTR_AHA2FIE1_ADC2_FIFO_EMPTY_INTR_W2CLR_MASK (0x2UL)
#define HKADC_INTR_AHA2FIE1_ADC2_FIFO_EMPTY_INTR_W2CLR_SHIFT (1UL)
#define HKADC_INTR_AHA2FIE1_ADC2_FIFO_THESHOLD_INTR_W2CLR_MASK (0x1UL)
#define HKADC_INTR_AHA2FIE1_ADC2_FIFO_THESHOLD_INTR_W2CLR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA2FIE2_TYPE;
#define HKADC_INTR_AHA2FIE2_ENABLE_ADC2_FIFO_OVERFLOW_INTR_MASK (0x80000000UL)
#define HKADC_INTR_AHA2FIE2_ENABLE_ADC2_FIFO_OVERFLOW_INTR_SHIFT (31UL)
#define HKADC_INTR_AHA2FIE2_ENABLE_ADC2_FIFO_UNDERFLOW_INTR_MASK (0x4UL)
#define HKADC_INTR_AHA2FIE2_ENABLE_ADC2_FIFO_UNDERFLOW_INTR_SHIFT (2UL)
#define HKADC_INTR_AHA2FIE2_ENABLE_ADC2_FIFO_EMPTY_INTR_MASK (0x2UL)
#define HKADC_INTR_AHA2FIE2_ENABLE_ADC2_FIFO_EMPTY_INTR_SHIFT (1UL)
#define HKADC_INTR_AHA2FIE2_ENABLE_ADC2_FIFO_THESHOLD_INTR_MASK (0x1UL)
#define HKADC_INTR_AHA2FIE2_ENABLE_ADC2_FIFO_THESHOLD_INTR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA2TIE_TYPE;
#define HKADC_INTR_AHA2TIE_P_ADC2_VALUE_THRESHOLD1_INTR_MASK (0x80000000UL)
#define HKADC_INTR_AHA2TIE_P_ADC2_VALUE_THRESHOLD1_INTR_SHIFT (31UL)
#define HKADC_INTR_AHA2TIE_P_ADC2_VALUE_THRESHOLD0_INTR_MASK (0x1UL)
#define HKADC_INTR_AHA2TIE_P_ADC2_VALUE_THRESHOLD0_INTR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA2TIE1_TYPE;
#define HKADC_INTR_AHA2TIE1_ADC2_VALUE_THRESHOLD1_INTR_W2CLR_MASK (0x80000000UL)
#define HKADC_INTR_AHA2TIE1_ADC2_VALUE_THRESHOLD1_INTR_W2CLR_SHIFT (31UL)
#define HKADC_INTR_AHA2TIE1_ADC2_VALUE_THRESHOLD0_INTR_W2CLR_MASK (0x1UL)
#define HKADC_INTR_AHA2TIE1_ADC2_VALUE_THRESHOLD0_INTR_W2CLR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA2TIE2_TYPE;
#define HKADC_INTR_AHA2TIE2_ENABLE_ADC2_VALUE_THRESHOLD1_INTR_MASK (0x80000000UL)
#define HKADC_INTR_AHA2TIE2_ENABLE_ADC2_VALUE_THRESHOLD1_INTR_SHIFT (31UL)
#define HKADC_INTR_AHA2TIE2_ENABLE_ADC2_VALUE_THRESHOLD0_INTR_MASK (0x1UL)
#define HKADC_INTR_AHA2TIE2_ENABLE_ADC2_VALUE_THRESHOLD0_INTR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA3FIE_TYPE;
#define HKADC_INTR_AHA3FIE_P_ADC3_FIFO_OVERFLOW_INTR_MASK (0x80000000UL)
#define HKADC_INTR_AHA3FIE_P_ADC3_FIFO_OVERFLOW_INTR_SHIFT (31UL)
#define HKADC_INTR_AHA3FIE_P_ADC3_FIFO_UNDERFLOW_INTR_MASK (0x4UL)
#define HKADC_INTR_AHA3FIE_P_ADC3_FIFO_UNDERFLOW_INTR_SHIFT (2UL)
#define HKADC_INTR_AHA3FIE_P_ADC3_FIFO_EMPTY_INTR_MASK (0x2UL)
#define HKADC_INTR_AHA3FIE_P_ADC3_FIFO_EMPTY_INTR_SHIFT (1UL)
#define HKADC_INTR_AHA3FIE_P_ADC3_FIFO_THESHOLD_INTR_MASK (0x1UL)
#define HKADC_INTR_AHA3FIE_P_ADC3_FIFO_THESHOLD_INTR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA3FIE1_TYPE;
#define HKADC_INTR_AHA3FIE1_ADC3_FIFO_OVERFLOW_INTR_W2CLR_MASK (0x80000000UL)
#define HKADC_INTR_AHA3FIE1_ADC3_FIFO_OVERFLOW_INTR_W2CLR_SHIFT (31UL)
#define HKADC_INTR_AHA3FIE1_ADC3_FIFO_UNDERFLOW_INTR_W2CLR_MASK (0x4UL)
#define HKADC_INTR_AHA3FIE1_ADC3_FIFO_UNDERFLOW_INTR_W2CLR_SHIFT (2UL)
#define HKADC_INTR_AHA3FIE1_ADC3_FIFO_EMPTY_INTR_W2CLR_MASK (0x2UL)
#define HKADC_INTR_AHA3FIE1_ADC3_FIFO_EMPTY_INTR_W2CLR_SHIFT (1UL)
#define HKADC_INTR_AHA3FIE1_ADC3_FIFO_THESHOLD_INTR_W2CLR_MASK (0x1UL)
#define HKADC_INTR_AHA3FIE1_ADC3_FIFO_THESHOLD_INTR_W2CLR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA3FIE2_TYPE;
#define HKADC_INTR_AHA3FIE2_ENABLE_ADC3_FIFO_OVERFLOW_INTR_MASK (0x80000000UL)
#define HKADC_INTR_AHA3FIE2_ENABLE_ADC3_FIFO_OVERFLOW_INTR_SHIFT (31UL)
#define HKADC_INTR_AHA3FIE2_ENABLE_ADC3_FIFO_UNDERFLOW_INTR_MASK (0x4UL)
#define HKADC_INTR_AHA3FIE2_ENABLE_ADC3_FIFO_UNDERFLOW_INTR_SHIFT (2UL)
#define HKADC_INTR_AHA3FIE2_ENABLE_ADC3_FIFO_EMPTY_INTR_MASK (0x2UL)
#define HKADC_INTR_AHA3FIE2_ENABLE_ADC3_FIFO_EMPTY_INTR_SHIFT (1UL)
#define HKADC_INTR_AHA3FIE2_ENABLE_ADC3_FIFO_THESHOLD_INTR_MASK (0x1UL)
#define HKADC_INTR_AHA3FIE2_ENABLE_ADC3_FIFO_THESHOLD_INTR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA3TIE_TYPE;
#define HKADC_INTR_AHA3TIE_P_ADC3_VALUE_THRESHOLD1_INTR_MASK (0x80000000UL)
#define HKADC_INTR_AHA3TIE_P_ADC3_VALUE_THRESHOLD1_INTR_SHIFT (31UL)
#define HKADC_INTR_AHA3TIE_P_ADC3_VALUE_THRESHOLD0_INTR_MASK (0x1UL)
#define HKADC_INTR_AHA3TIE_P_ADC3_VALUE_THRESHOLD0_INTR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA3TIE1_TYPE;
#define HKADC_INTR_AHA3TIE1_ADC3_VALUE_THRESHOLD1_INTR_W2CLR_MASK (0x80000000UL)
#define HKADC_INTR_AHA3TIE1_ADC3_VALUE_THRESHOLD1_INTR_W2CLR_SHIFT (31UL)
#define HKADC_INTR_AHA3TIE1_ADC3_VALUE_THRESHOLD0_INTR_W2CLR_MASK (0x1UL)
#define HKADC_INTR_AHA3TIE1_ADC3_VALUE_THRESHOLD0_INTR_W2CLR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA3TIE2_TYPE;
#define HKADC_INTR_AHA3TIE2_ENABLE_ADC3_VALUE_THRESHOLD1_INTR_MASK (0x80000000UL)
#define HKADC_INTR_AHA3TIE2_ENABLE_ADC3_VALUE_THRESHOLD1_INTR_SHIFT (31UL)
#define HKADC_INTR_AHA3TIE2_ENABLE_ADC3_VALUE_THRESHOLD0_INTR_MASK (0x1UL)
#define HKADC_INTR_AHA3TIE2_ENABLE_ADC3_VALUE_THRESHOLD0_INTR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA4FIE_TYPE;
#define HKADC_INTR_AHA4FIE_P_ADC4_FIFO_OVERFLOW_INTR_MASK (0x80000000UL)
#define HKADC_INTR_AHA4FIE_P_ADC4_FIFO_OVERFLOW_INTR_SHIFT (31UL)
#define HKADC_INTR_AHA4FIE_P_ADC4_FIFO_UNDERFLOW_INTR_MASK (0x4UL)
#define HKADC_INTR_AHA4FIE_P_ADC4_FIFO_UNDERFLOW_INTR_SHIFT (2UL)
#define HKADC_INTR_AHA4FIE_P_ADC4_FIFO_EMPTY_INTR_MASK (0x2UL)
#define HKADC_INTR_AHA4FIE_P_ADC4_FIFO_EMPTY_INTR_SHIFT (1UL)
#define HKADC_INTR_AHA4FIE_P_ADC4_FIFO_THESHOLD_INTR_MASK (0x1UL)
#define HKADC_INTR_AHA4FIE_P_ADC4_FIFO_THESHOLD_INTR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA4FIE1_TYPE;
#define HKADC_INTR_AHA4FIE1_ADC4_FIFO_OVERFLOW_INTR_W2CLR_MASK (0x80000000UL)
#define HKADC_INTR_AHA4FIE1_ADC4_FIFO_OVERFLOW_INTR_W2CLR_SHIFT (31UL)
#define HKADC_INTR_AHA4FIE1_ADC4_FIFO_UNDERFLOW_INTR_W2CLR_MASK (0x4UL)
#define HKADC_INTR_AHA4FIE1_ADC4_FIFO_UNDERFLOW_INTR_W2CLR_SHIFT (2UL)
#define HKADC_INTR_AHA4FIE1_ADC4_FIFO_EMPTY_INTR_W2CLR_MASK (0x2UL)
#define HKADC_INTR_AHA4FIE1_ADC4_FIFO_EMPTY_INTR_W2CLR_SHIFT (1UL)
#define HKADC_INTR_AHA4FIE1_ADC4_FIFO_THESHOLD_INTR_W2CLR_MASK (0x1UL)
#define HKADC_INTR_AHA4FIE1_ADC4_FIFO_THESHOLD_INTR_W2CLR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA4FIE2_TYPE;
#define HKADC_INTR_AHA4FIE2_ENABLE_ADC4_FIFO_OVERFLOW_INTR_MASK (0x80000000UL)
#define HKADC_INTR_AHA4FIE2_ENABLE_ADC4_FIFO_OVERFLOW_INTR_SHIFT (31UL)
#define HKADC_INTR_AHA4FIE2_ENABLE_ADC4_FIFO_UNDERFLOW_INTR_MASK (0x4UL)
#define HKADC_INTR_AHA4FIE2_ENABLE_ADC4_FIFO_UNDERFLOW_INTR_SHIFT (2UL)
#define HKADC_INTR_AHA4FIE2_ENABLE_ADC4_FIFO_EMPTY_INTR_MASK (0x2UL)
#define HKADC_INTR_AHA4FIE2_ENABLE_ADC4_FIFO_EMPTY_INTR_SHIFT (1UL)
#define HKADC_INTR_AHA4FIE2_ENABLE_ADC4_FIFO_THESHOLD_INTR_MASK (0x1UL)
#define HKADC_INTR_AHA4FIE2_ENABLE_ADC4_FIFO_THESHOLD_INTR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA4TIE_TYPE;
#define HKADC_INTR_AHA4TIE_P_ADC4_VALUE_THRESHOLD1_INTR_MASK (0x80000000UL)
#define HKADC_INTR_AHA4TIE_P_ADC4_VALUE_THRESHOLD1_INTR_SHIFT (31UL)
#define HKADC_INTR_AHA4TIE_P_ADC4_VALUE_THRESHOLD0_INTR_MASK (0x1UL)
#define HKADC_INTR_AHA4TIE_P_ADC4_VALUE_THRESHOLD0_INTR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA4TIE1_TYPE;
#define HKADC_INTR_AHA4TIE1_ADC4_VALUE_THRESHOLD1_INTR_W2CLR_MASK (0x80000000UL)
#define HKADC_INTR_AHA4TIE1_ADC4_VALUE_THRESHOLD1_INTR_W2CLR_SHIFT (31UL)
#define HKADC_INTR_AHA4TIE1_ADC4_VALUE_THRESHOLD0_INTR_W2CLR_MASK (0x1UL)
#define HKADC_INTR_AHA4TIE1_ADC4_VALUE_THRESHOLD0_INTR_W2CLR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA4TIE2_TYPE;
#define HKADC_INTR_AHA4TIE2_ENABLE_ADC4_VALUE_THRESHOLD1_INTR_MASK (0x80000000UL)
#define HKADC_INTR_AHA4TIE2_ENABLE_ADC4_VALUE_THRESHOLD1_INTR_SHIFT (31UL)
#define HKADC_INTR_AHA4TIE2_ENABLE_ADC4_VALUE_THRESHOLD0_INTR_MASK (0x1UL)
#define HKADC_INTR_AHA4TIE2_ENABLE_ADC4_VALUE_THRESHOLD0_INTR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA5FIE_TYPE;
#define HKADC_INTR_AHA5FIE_P_ADC5_FIFO_OVERFLOW_INTR_MASK (0x80000000UL)
#define HKADC_INTR_AHA5FIE_P_ADC5_FIFO_OVERFLOW_INTR_SHIFT (31UL)
#define HKADC_INTR_AHA5FIE_P_ADC5_FIFO_UNDERFLOW_INTR_MASK (0x4UL)
#define HKADC_INTR_AHA5FIE_P_ADC5_FIFO_UNDERFLOW_INTR_SHIFT (2UL)
#define HKADC_INTR_AHA5FIE_P_ADC5_FIFO_EMPTY_INTR_MASK (0x2UL)
#define HKADC_INTR_AHA5FIE_P_ADC5_FIFO_EMPTY_INTR_SHIFT (1UL)
#define HKADC_INTR_AHA5FIE_P_ADC5_FIFO_THESHOLD_INTR_MASK (0x1UL)
#define HKADC_INTR_AHA5FIE_P_ADC5_FIFO_THESHOLD_INTR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA5FIE1_TYPE;
#define HKADC_INTR_AHA5FIE1_ADC5_FIFO_OVERFLOW_INTR_W2CLR_MASK (0x80000000UL)
#define HKADC_INTR_AHA5FIE1_ADC5_FIFO_OVERFLOW_INTR_W2CLR_SHIFT (31UL)
#define HKADC_INTR_AHA5FIE1_ADC5_FIFO_UNDERFLOW_INTR_W2CLR_MASK (0x4UL)
#define HKADC_INTR_AHA5FIE1_ADC5_FIFO_UNDERFLOW_INTR_W2CLR_SHIFT (2UL)
#define HKADC_INTR_AHA5FIE1_ADC5_FIFO_EMPTY_INTR_W2CLR_MASK (0x2UL)
#define HKADC_INTR_AHA5FIE1_ADC5_FIFO_EMPTY_INTR_W2CLR_SHIFT (1UL)
#define HKADC_INTR_AHA5FIE1_ADC5_FIFO_THESHOLD_INTR_W2CLR_MASK (0x1UL)
#define HKADC_INTR_AHA5FIE1_ADC5_FIFO_THESHOLD_INTR_W2CLR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA5FIE2_TYPE;
#define HKADC_INTR_AHA5FIE2_ENABLE_ADC5_FIFO_OVERFLOW_INTR_MASK (0x80000000UL)
#define HKADC_INTR_AHA5FIE2_ENABLE_ADC5_FIFO_OVERFLOW_INTR_SHIFT (31UL)
#define HKADC_INTR_AHA5FIE2_ENABLE_ADC5_FIFO_UNDERFLOW_INTR_MASK (0x4UL)
#define HKADC_INTR_AHA5FIE2_ENABLE_ADC5_FIFO_UNDERFLOW_INTR_SHIFT (2UL)
#define HKADC_INTR_AHA5FIE2_ENABLE_ADC5_FIFO_EMPTY_INTR_MASK (0x2UL)
#define HKADC_INTR_AHA5FIE2_ENABLE_ADC5_FIFO_EMPTY_INTR_SHIFT (1UL)
#define HKADC_INTR_AHA5FIE2_ENABLE_ADC5_FIFO_THESHOLD_INTR_MASK (0x1UL)
#define HKADC_INTR_AHA5FIE2_ENABLE_ADC5_FIFO_THESHOLD_INTR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA5TIE_TYPE;
#define HKADC_INTR_AHA5TIE_P_ADC5_VALUE_THRESHOLD1_INTR_MASK (0x80000000UL)
#define HKADC_INTR_AHA5TIE_P_ADC5_VALUE_THRESHOLD1_INTR_SHIFT (31UL)
#define HKADC_INTR_AHA5TIE_P_ADC5_VALUE_THRESHOLD0_INTR_MASK (0x1UL)
#define HKADC_INTR_AHA5TIE_P_ADC5_VALUE_THRESHOLD0_INTR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA5TIE1_TYPE;
#define HKADC_INTR_AHA5TIE1_ADC5_VALUE_THRESHOLD1_INTR_W2CLR_MASK (0x80000000UL)
#define HKADC_INTR_AHA5TIE1_ADC5_VALUE_THRESHOLD1_INTR_W2CLR_SHIFT (31UL)
#define HKADC_INTR_AHA5TIE1_ADC5_VALUE_THRESHOLD0_INTR_W2CLR_MASK (0x1UL)
#define HKADC_INTR_AHA5TIE1_ADC5_VALUE_THRESHOLD0_INTR_W2CLR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA5TIE2_TYPE;
#define HKADC_INTR_AHA5TIE2_ENABLE_ADC5_VALUE_THRESHOLD1_INTR_MASK (0x80000000UL)
#define HKADC_INTR_AHA5TIE2_ENABLE_ADC5_VALUE_THRESHOLD1_INTR_SHIFT (31UL)
#define HKADC_INTR_AHA5TIE2_ENABLE_ADC5_VALUE_THRESHOLD0_INTR_MASK (0x1UL)
#define HKADC_INTR_AHA5TIE2_ENABLE_ADC5_VALUE_THRESHOLD0_INTR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA6FIE_TYPE;
#define HKADC_INTR_AHA6FIE_P_ADC6_FIFO_OVERFLOW_INTR_MASK (0x80000000UL)
#define HKADC_INTR_AHA6FIE_P_ADC6_FIFO_OVERFLOW_INTR_SHIFT (31UL)
#define HKADC_INTR_AHA6FIE_P_ADC6_SEQ_INTR_MASK (0x8UL)
#define HKADC_INTR_AHA6FIE_P_ADC6_SEQ_INTR_SHIFT (3UL)
#define HKADC_INTR_AHA6FIE_P_ADC6_FIFO_UNDERFLOW_INTR_MASK (0x4UL)
#define HKADC_INTR_AHA6FIE_P_ADC6_FIFO_UNDERFLOW_INTR_SHIFT (2UL)
#define HKADC_INTR_AHA6FIE_P_ADC6_FIFO_EMPTY_INTR_MASK (0x2UL)
#define HKADC_INTR_AHA6FIE_P_ADC6_FIFO_EMPTY_INTR_SHIFT (1UL)
#define HKADC_INTR_AHA6FIE_P_ADC6_FIFO_THESHOLD_INTR_MASK (0x1UL)
#define HKADC_INTR_AHA6FIE_P_ADC6_FIFO_THESHOLD_INTR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA6FIE1_TYPE;
#define HKADC_INTR_AHA6FIE1_ADC6_FIFO_OVERFLOW_INTR_W2CLR_MASK (0x80000000UL)
#define HKADC_INTR_AHA6FIE1_ADC6_FIFO_OVERFLOW_INTR_W2CLR_SHIFT (31UL)
#define HKADC_INTR_AHA6FIE1_ADC6_SEQ_INTR_W2CLR_MASK (0x8UL)
#define HKADC_INTR_AHA6FIE1_ADC6_SEQ_INTR_W2CLR_SHIFT (3UL)
#define HKADC_INTR_AHA6FIE1_ADC6_FIFO_UNDERFLOW_INTR_W2CLR_MASK (0x4UL)
#define HKADC_INTR_AHA6FIE1_ADC6_FIFO_UNDERFLOW_INTR_W2CLR_SHIFT (2UL)
#define HKADC_INTR_AHA6FIE1_ADC6_FIFO_EMPTY_INTR_W2CLR_MASK (0x2UL)
#define HKADC_INTR_AHA6FIE1_ADC6_FIFO_EMPTY_INTR_W2CLR_SHIFT (1UL)
#define HKADC_INTR_AHA6FIE1_ADC6_FIFO_THESHOLD_INTR_W2CLR_MASK (0x1UL)
#define HKADC_INTR_AHA6FIE1_ADC6_FIFO_THESHOLD_INTR_W2CLR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA6FIE2_TYPE;
#define HKADC_INTR_AHA6FIE2_ENABLE_ADC6_FIFO_OVERFLOW_INTR_MASK (0x80000000UL)
#define HKADC_INTR_AHA6FIE2_ENABLE_ADC6_FIFO_OVERFLOW_INTR_SHIFT (31UL)
#define HKADC_INTR_AHA6FIE2_ENABLE_ADC6_SEQ_INTR_MASK (0x8UL)
#define HKADC_INTR_AHA6FIE2_ENABLE_ADC6_SEQ_INTR_SHIFT (3UL)
#define HKADC_INTR_AHA6FIE2_ENABLE_ADC6_FIFO_UNDERFLOW_INTR_MASK (0x4UL)
#define HKADC_INTR_AHA6FIE2_ENABLE_ADC6_FIFO_UNDERFLOW_INTR_SHIFT (2UL)
#define HKADC_INTR_AHA6FIE2_ENABLE_ADC6_FIFO_EMPTY_INTR_MASK (0x2UL)
#define HKADC_INTR_AHA6FIE2_ENABLE_ADC6_FIFO_EMPTY_INTR_SHIFT (1UL)
#define HKADC_INTR_AHA6FIE2_ENABLE_ADC6_FIFO_THESHOLD_INTR_MASK (0x1UL)
#define HKADC_INTR_AHA6FIE2_ENABLE_ADC6_FIFO_THESHOLD_INTR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA6TIE_TYPE;
#define HKADC_INTR_AHA6TIE_P_ADC6_VALUE_THRESHOLD1_INTR_MASK (0x80000000UL)
#define HKADC_INTR_AHA6TIE_P_ADC6_VALUE_THRESHOLD1_INTR_SHIFT (31UL)
#define HKADC_INTR_AHA6TIE_P_ADC6_VALUE_THRESHOLD0_INTR_MASK (0x1UL)
#define HKADC_INTR_AHA6TIE_P_ADC6_VALUE_THRESHOLD0_INTR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA6TIE1_TYPE;
#define HKADC_INTR_AHA6TIE1_ADC6_VALUE_THRESHOLD1_INTR_W2CLR_MASK (0x80000000UL)
#define HKADC_INTR_AHA6TIE1_ADC6_VALUE_THRESHOLD1_INTR_W2CLR_SHIFT (31UL)
#define HKADC_INTR_AHA6TIE1_ADC6_VALUE_THRESHOLD0_INTR_W2CLR_MASK (0x1UL)
#define HKADC_INTR_AHA6TIE1_ADC6_VALUE_THRESHOLD0_INTR_W2CLR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA6TIE2_TYPE;
#define HKADC_INTR_AHA6TIE2_ENABLE_ADC6_VALUE_THRESHOLD1_INTR_MASK (0x80000000UL)
#define HKADC_INTR_AHA6TIE2_ENABLE_ADC6_VALUE_THRESHOLD1_INTR_SHIFT (31UL)
#define HKADC_INTR_AHA6TIE2_ENABLE_ADC6_VALUE_THRESHOLD0_INTR_MASK (0x1UL)
#define HKADC_INTR_AHA6TIE2_ENABLE_ADC6_VALUE_THRESHOLD0_INTR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA7FIE_TYPE;
#define HKADC_INTR_AHA7FIE_P_ADC7_FIFO_OVERFLOW_INTR_MASK (0x80000000UL)
#define HKADC_INTR_AHA7FIE_P_ADC7_FIFO_OVERFLOW_INTR_SHIFT (31UL)
#define HKADC_INTR_AHA7FIE_P_ADC7_SEQ_INTR_MASK (0x8UL)
#define HKADC_INTR_AHA7FIE_P_ADC7_SEQ_INTR_SHIFT (3UL)
#define HKADC_INTR_AHA7FIE_P_ADC7_FIFO_UNDERFLOW_INTR_MASK (0x4UL)
#define HKADC_INTR_AHA7FIE_P_ADC7_FIFO_UNDERFLOW_INTR_SHIFT (2UL)
#define HKADC_INTR_AHA7FIE_P_ADC7_FIFO_EMPTY_INTR_MASK (0x2UL)
#define HKADC_INTR_AHA7FIE_P_ADC7_FIFO_EMPTY_INTR_SHIFT (1UL)
#define HKADC_INTR_AHA7FIE_P_ADC7_FIFO_THESHOLD_INTR_MASK (0x1UL)
#define HKADC_INTR_AHA7FIE_P_ADC7_FIFO_THESHOLD_INTR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA7FIE1_TYPE;
#define HKADC_INTR_AHA7FIE1_ADC7_FIFO_OVERFLOW_INTR_W2CLR_MASK (0x80000000UL)
#define HKADC_INTR_AHA7FIE1_ADC7_FIFO_OVERFLOW_INTR_W2CLR_SHIFT (31UL)
#define HKADC_INTR_AHA7FIE1_ADC7_SEQ_INTR_W2CLR_MASK (0x8UL)
#define HKADC_INTR_AHA7FIE1_ADC7_SEQ_INTR_W2CLR_SHIFT (3UL)
#define HKADC_INTR_AHA7FIE1_ADC7_FIFO_UNDERFLOW_INTR_W2CLR_MASK (0x4UL)
#define HKADC_INTR_AHA7FIE1_ADC7_FIFO_UNDERFLOW_INTR_W2CLR_SHIFT (2UL)
#define HKADC_INTR_AHA7FIE1_ADC7_FIFO_EMPTY_INTR_W2CLR_MASK (0x2UL)
#define HKADC_INTR_AHA7FIE1_ADC7_FIFO_EMPTY_INTR_W2CLR_SHIFT (1UL)
#define HKADC_INTR_AHA7FIE1_ADC7_FIFO_THESHOLD_INTR_W2CLR_MASK (0x1UL)
#define HKADC_INTR_AHA7FIE1_ADC7_FIFO_THESHOLD_INTR_W2CLR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA7FIE2_TYPE;
#define HKADC_INTR_AHA7FIE2_ENABLE_ADC7_FIFO_OVERFLOW_INTR_MASK (0x80000000UL)
#define HKADC_INTR_AHA7FIE2_ENABLE_ADC7_FIFO_OVERFLOW_INTR_SHIFT (31UL)
#define HKADC_INTR_AHA7FIE2_ENABLE_ADC7_SEQ_INTR_MASK (0x8UL)
#define HKADC_INTR_AHA7FIE2_ENABLE_ADC7_SEQ_INTR_SHIFT (3UL)
#define HKADC_INTR_AHA7FIE2_ENABLE_ADC7_FIFO_UNDERFLOW_INTR_MASK (0x4UL)
#define HKADC_INTR_AHA7FIE2_ENABLE_ADC7_FIFO_UNDERFLOW_INTR_SHIFT (2UL)
#define HKADC_INTR_AHA7FIE2_ENABLE_ADC7_FIFO_EMPTY_INTR_MASK (0x2UL)
#define HKADC_INTR_AHA7FIE2_ENABLE_ADC7_FIFO_EMPTY_INTR_SHIFT (1UL)
#define HKADC_INTR_AHA7FIE2_ENABLE_ADC7_FIFO_THESHOLD_INTR_MASK (0x1UL)
#define HKADC_INTR_AHA7FIE2_ENABLE_ADC7_FIFO_THESHOLD_INTR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA7TIE_TYPE;
#define HKADC_INTR_AHA7TIE_P_ADC7_VALUE_THRESHOLD1_INTR_MASK (0x80000000UL)
#define HKADC_INTR_AHA7TIE_P_ADC7_VALUE_THRESHOLD1_INTR_SHIFT (31UL)
#define HKADC_INTR_AHA7TIE_P_ADC7_VALUE_THRESHOLD0_INTR_MASK (0x1UL)
#define HKADC_INTR_AHA7TIE_P_ADC7_VALUE_THRESHOLD0_INTR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA7TIE1_TYPE;
#define HKADC_INTR_AHA7TIE1_ADC7_VALUE_THRESHOLD1_INTR_W2CLR_MASK (0x80000000UL)
#define HKADC_INTR_AHA7TIE1_ADC7_VALUE_THRESHOLD1_INTR_W2CLR_SHIFT (31UL)
#define HKADC_INTR_AHA7TIE1_ADC7_VALUE_THRESHOLD0_INTR_W2CLR_MASK (0x1UL)
#define HKADC_INTR_AHA7TIE1_ADC7_VALUE_THRESHOLD0_INTR_W2CLR_SHIFT (0UL)




typedef uint32_t HKADC_INTR_AHA7TIE2_TYPE;
#define HKADC_INTR_AHA7TIE2_ENABLE_ADC7_VALUE_THRESHOLD1_INTR_MASK (0x80000000UL)
#define HKADC_INTR_AHA7TIE2_ENABLE_ADC7_VALUE_THRESHOLD1_INTR_SHIFT (31UL)
#define HKADC_INTR_AHA7TIE2_ENABLE_ADC7_VALUE_THRESHOLD0_INTR_MASK (0x1UL)
#define HKADC_INTR_AHA7TIE2_ENABLE_ADC7_VALUE_THRESHOLD0_INTR_SHIFT (0UL)




typedef uint8_t HKADC_INTR_RESERVED_TYPE;




typedef uint32_t HKADC_INTR_SPARE_END_REG_TYPE;
#define HKADC_INTR_SPARE_END_REG_MASK (0xffffffffUL)
#define HKADC_INTR_SPARE_END_REG_SHIFT (0UL)


typedef volatile struct sHKADC_INTR_HKADC_ADC_CHANNEL_INTR_TYPE {
    HKADC_INTR_AHA0FIE_TYPE acq_hkadc_adc0_fifo_intr_eipr; /* OFFSET: 0x0 */
    HKADC_INTR_AHA0FIE1_TYPE acq_hkadc_adc0_fifo_intr_eisr; /* OFFSET: 0x4 */
    HKADC_INTR_AHA0FIE2_TYPE acq_hkadc_adc0_fifo_intr_eier; /* OFFSET: 0x8 */
    HKADC_INTR_AHA0TIE_TYPE acq_hkadc_adc0_threshold_intr_eipr; /* OFFSET: 0xc */
    HKADC_INTR_AHA0TIE1_TYPE acq_hkadc_adc0_threshold_intr_eisr; /* OFFSET: 0x10 */
    HKADC_INTR_AHA0TIE2_TYPE acq_hkadc_adc0_threshold_intr_eier; /* OFFSET: 0x14 */
} HKADC_INTR_HKADC_ADC_CHANNEL_INTR_TYPE;


#define HKADC_INTR_CHANNEL_SIZE  (8UL)


typedef volatile struct sHKADC_INTR_RDBType {
    HKADC_INTR_HKADC_ADC_CHANNEL_INTR_TYPE channel[HKADC_INTR_CHANNEL_SIZE]; /* OFFSET: 0x0 */
    HKADC_INTR_RESERVED_TYPE rsvd0[60]; /* OFFSET: 0xc0 */
    HKADC_INTR_SPARE_END_REG_TYPE spare_end_reg; /* OFFSET: 0xfc */
} HKADC_INTR_RDBType;


#define HKADC_INTR_BASE                 (0xE0608F00UL)

#define HKADC_INTR_HKADC_ADC_CHANNEL_INTR_TYPE_OFFSET  (0xE0608f00UL)



#define HKADC_INTR_MAX_HW_ID            (1UL)

#endif /* HKADC_INTR_RDB_H */
