/*****************************************************************************
 Copyright 2025 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file hkadc_rdb.h
    @brief RDB File for HKADC

    @version BCM89580_A0_20230125_RDB
*/

#ifndef HKADC_RDB_H
#define HKADC_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t HKADC_CAPT_CTRL_TYPE;
#define HKADC_CAPT_CTRL_CTRL_BUSY_MASK (0x80000000UL)
#define HKADC_CAPT_CTRL_CTRL_BUSY_SHIFT (31UL)
#define HKADC_CAPT_CTRL_SEQ_MODE_MASK (0x80000UL)
#define HKADC_CAPT_CTRL_SEQ_MODE_SHIFT (19UL)
#define HKADC_CAPT_CTRL_SOFT_MODE_MASK (0x40000UL)
#define HKADC_CAPT_CTRL_SOFT_MODE_SHIFT (18UL)
#define HKADC_CAPT_CTRL_CONT_MODE_MASK (0x20000UL)
#define HKADC_CAPT_CTRL_CONT_MODE_SHIFT (17UL)
#define HKADC_CAPT_CTRL_CAPT_EN_MASK (0x10000UL)
#define HKADC_CAPT_CTRL_CAPT_EN_SHIFT (16UL)
#define HKADC_CAPT_CTRL_PROG_RATE_CNT_MASK (0xffffUL)
#define HKADC_CAPT_CTRL_PROG_RATE_CNT_SHIFT (0UL)




typedef uint32_t HKADC_ADC_FIFO_DATA_TYPE;
#define HKADC_ADC_FIFO_DATA_RDATA_MASK (0xffffUL)
#define HKADC_ADC_FIFO_DATA_RDATA_SHIFT (0UL)




typedef uint32_t HKADC_ADC_FIFO_CTRL_TYPE;
#define HKADC_ADC_FIFO_CTRL_SFT_RST_MASK (0x10000UL)
#define HKADC_ADC_FIFO_CTRL_SFT_RST_SHIFT (16UL)
#define HKADC_ADC_FIFO_CTRL_THRES_VAL_MASK (0x7fUL)
#define HKADC_ADC_FIFO_CTRL_THRES_VAL_SHIFT (0UL)




typedef uint32_t HKADC_ADC_CMP_CTRL_TYPE;
#define HKADC_ADC_CMP_CTRL_THRES_MODE_MASK (0x20000UL)
#define HKADC_ADC_CMP_CTRL_THRES_MODE_SHIFT (17UL)
#define HKADC_ADC_CMP_CTRL_EN_COMP_MASK (0x10000UL)
#define HKADC_ADC_CMP_CTRL_EN_COMP_SHIFT (16UL)
#define HKADC_ADC_CMP_CTRL_THRES_VAL_MASK (0xfffUL)
#define HKADC_ADC_CMP_CTRL_THRES_VAL_SHIFT (0UL)




typedef uint32_t HKADC_AUXADC_CONFIG0_TYPE;
#define HKADC_AUXADC_CONFIG0_I_ADC_PD_MASK (0x2000UL)
#define HKADC_AUXADC_CONFIG0_I_ADC_PD_SHIFT (13UL)
#define HKADC_AUXADC_CONFIG0_I_ADC_CALMODE_MASK (0x1fc0UL)
#define HKADC_AUXADC_CONFIG0_I_ADC_CALMODE_SHIFT (6UL)
#define HKADC_AUXADC_CONFIG0_I_ADC_CALAVG_MASK (0x30UL)
#define HKADC_AUXADC_CONFIG0_I_ADC_CALAVG_SHIFT (4UL)
#define HKADC_AUXADC_CONFIG0_I_ADC_PRECHARGE_MASK (0xeUL)
#define HKADC_AUXADC_CONFIG0_I_ADC_PRECHARGE_SHIFT (1UL)
#define HKADC_AUXADC_CONFIG0_I_ADC_GND_CTRL_MASK (0x1UL)
#define HKADC_AUXADC_CONFIG0_I_ADC_GND_CTRL_SHIFT (0UL)




typedef uint32_t HKADC_AFE_CALIB_TYPE;
#define HKADC_AFE_CALIB_CALIBRATING_MASK (0x80000000UL)
#define HKADC_AFE_CALIB_CALIBRATING_SHIFT (31UL)
#define HKADC_AFE_CALIB_CALEN_MASK (0x1UL)
#define HKADC_AFE_CALIB_CALEN_SHIFT (0UL)




typedef uint32_t HKADC_AFE_DBG_TYPE;
#define HKADC_AFE_DBG_WR_ACK_MASK (0x80000000UL)
#define HKADC_AFE_DBG_WR_ACK_SHIFT (31UL)
#define HKADC_AFE_DBG_RD_STROBE_MASK (0x4000000UL)
#define HKADC_AFE_DBG_RD_STROBE_SHIFT (26UL)
#define HKADC_AFE_DBG_WR_STROBE_MASK (0x2000000UL)
#define HKADC_AFE_DBG_WR_STROBE_SHIFT (25UL)
#define HKADC_AFE_DBG_ADDR_MASK (0x1f00000UL)
#define HKADC_AFE_DBG_ADDR_SHIFT (20UL)
#define HKADC_AFE_DBG_DATA_MASK (0xfffffUL)
#define HKADC_AFE_DBG_DATA_SHIFT (0UL)




typedef uint8_t HKADC_RESERVED_TYPE;




typedef uint32_t HKADC_ADC_WIDE_FIFO_DATA_TYPE;
#define HKADC_ADC_WIDE_FIFO_DATA_RDATA_MASK (0xfffffffUL)
#define HKADC_ADC_WIDE_FIFO_DATA_RDATA_SHIFT (0UL)




typedef uint32_t HKADC_ADC_WIDE_FIFO_CTRL_TYPE;
#define HKADC_ADC_WIDE_FIFO_CTRL_RESERVED_17_MASK (0x20000UL)
#define HKADC_ADC_WIDE_FIFO_CTRL_RESERVED_17_SHIFT (17UL)
#define HKADC_ADC_WIDE_FIFO_CTRL_SFT_RST_MASK (0x10000UL)
#define HKADC_ADC_WIDE_FIFO_CTRL_SFT_RST_SHIFT (16UL)
#define HKADC_ADC_WIDE_FIFO_CTRL_THRES_VAL_MASK (0x7fUL)
#define HKADC_ADC_WIDE_FIFO_CTRL_THRES_VAL_SHIFT (0UL)




typedef uint32_t HKADC_TXSLZR_SEQ_CONTROL_TYPE;
#define HKADC_TXSLZR_SEQ_CONTROL_OUTPUT_CFG_MASK (0x2UL)
#define HKADC_TXSLZR_SEQ_CONTROL_OUTPUT_CFG_SHIFT (1UL)




typedef uint32_t HKADC_TXSLZR_SEQ_MEM_IND_WR_CONTROL_TYPE;
#define HKADC_TXSLZR_SEQ_MEM_IND_WR_CONTROL_INCR_MODE_MASK (0x10000UL)
#define HKADC_TXSLZR_SEQ_MEM_IND_WR_CONTROL_INCR_MODE_SHIFT (16UL)
#define HKADC_TXSLZR_SEQ_MEM_IND_WR_CONTROL_ADDR_MASK (0xffUL)
#define HKADC_TXSLZR_SEQ_MEM_IND_WR_CONTROL_ADDR_SHIFT (0UL)




typedef uint32_t HKADC_SEQ_MEM_IND_WR_DATA0_TYPE;
#define HKADC_SEQ_MEM_IND_WR_DATA0_SPI_DATA_MASK (0xffff0000UL)
#define HKADC_SEQ_MEM_IND_WR_DATA0_SPI_DATA_SHIFT (16UL)
#define HKADC_SEQ_MEM_IND_WR_DATA0_RPT_CNT_MASK (0x7f0UL)
#define HKADC_SEQ_MEM_IND_WR_DATA0_RPT_CNT_SHIFT (4UL)
#define HKADC_SEQ_MEM_IND_WR_DATA0_END_FLAG_MASK (0x1UL)
#define HKADC_SEQ_MEM_IND_WR_DATA0_END_FLAG_SHIFT (0UL)




typedef uint32_t HKADC_SEQ_MEM_IND_WR_DATA1_TYPE;
#define HKADC_SEQ_MEM_IND_WR_DATA1_ID_MASK (0x1f0000UL)
#define HKADC_SEQ_MEM_IND_WR_DATA1_ID_SHIFT (16UL)
#define HKADC_SEQ_MEM_IND_WR_DATA1_POST_WAIT_CNT_MASK (0xffffUL)
#define HKADC_SEQ_MEM_IND_WR_DATA1_POST_WAIT_CNT_SHIFT (0UL)




typedef uint32_t HKADC_TXSLZR_SEQ_MEM_IND_RD_CONTROL_TYPE;
#define HKADC_TXSLZR_SEQ_MEM_IND_RD_CONTROL_INCR_MODE_MASK (0x10000UL)
#define HKADC_TXSLZR_SEQ_MEM_IND_RD_CONTROL_INCR_MODE_SHIFT (16UL)
#define HKADC_TXSLZR_SEQ_MEM_IND_RD_CONTROL_ADDR_MASK (0xffUL)
#define HKADC_TXSLZR_SEQ_MEM_IND_RD_CONTROL_ADDR_SHIFT (0UL)




typedef uint32_t HKADC_SEQ_MEM_IND_RD_DATA0_TYPE;
#define HKADC_SEQ_MEM_IND_RD_DATA0_SPI_DATA_MASK (0xffff0000UL)
#define HKADC_SEQ_MEM_IND_RD_DATA0_SPI_DATA_SHIFT (16UL)
#define HKADC_SEQ_MEM_IND_RD_DATA0_RPT_CNT_MASK (0x7f0UL)
#define HKADC_SEQ_MEM_IND_RD_DATA0_RPT_CNT_SHIFT (4UL)
#define HKADC_SEQ_MEM_IND_RD_DATA0_END_FLAG_MASK (0x1UL)
#define HKADC_SEQ_MEM_IND_RD_DATA0_END_FLAG_SHIFT (0UL)




typedef uint32_t HKADC_SEQ_MEM_IND_RD_DATA1_TYPE;
#define HKADC_SEQ_MEM_IND_RD_DATA1_ID_MASK (0x1f0000UL)
#define HKADC_SEQ_MEM_IND_RD_DATA1_ID_SHIFT (16UL)
#define HKADC_SEQ_MEM_IND_RD_DATA1_POST_WAIT_CNT_MASK (0xffffUL)
#define HKADC_SEQ_MEM_IND_RD_DATA1_POST_WAIT_CNT_SHIFT (0UL)




typedef uint32_t HKADC_TXSLZR_SEQ_SPI_CONTROL_TYPE;
#define HKADC_TXSLZR_SEQ_SPI_CONTROL_SEQ_SPI_WAIT_TIME_MASK (0xffff0000UL)
#define HKADC_TXSLZR_SEQ_SPI_CONTROL_SEQ_SPI_WAIT_TIME_SHIFT (16UL)
#define HKADC_TXSLZR_SEQ_SPI_CONTROL_SPI_CLK_DIVIDER_MASK (0xff00UL)
#define HKADC_TXSLZR_SEQ_SPI_CONTROL_SPI_CLK_DIVIDER_SHIFT (8UL)
#define HKADC_TXSLZR_SEQ_SPI_CONTROL_SPI_CMD_SIZE_MASK (0x40UL)
#define HKADC_TXSLZR_SEQ_SPI_CONTROL_SPI_CMD_SIZE_SHIFT (6UL)
#define HKADC_TXSLZR_SEQ_SPI_CONTROL_SPI_CMD_CNT_MASK (0x10UL)
#define HKADC_TXSLZR_SEQ_SPI_CONTROL_SPI_CMD_CNT_SHIFT (4UL)
#define HKADC_TXSLZR_SEQ_SPI_CONTROL_SPI_CPOL_MASK (0x8UL)
#define HKADC_TXSLZR_SEQ_SPI_CONTROL_SPI_CPOL_SHIFT (3UL)
#define HKADC_TXSLZR_SEQ_SPI_CONTROL_SPI_CPHA_MASK (0x4UL)
#define HKADC_TXSLZR_SEQ_SPI_CONTROL_SPI_CPHA_SHIFT (2UL)
#define HKADC_TXSLZR_SEQ_SPI_CONTROL_SPI_SEQ_EN_MASK (0x1UL)
#define HKADC_TXSLZR_SEQ_SPI_CONTROL_SPI_SEQ_EN_SHIFT (0UL)




typedef uint32_t HKADC_TXSLZR_SEQ_SPI_SFT_CONTROL_TYPE;
#define HKADC_TXSLZR_SEQ_SPI_SFT_CONTROL_RD_MASK (0x1000UL)
#define HKADC_TXSLZR_SEQ_SPI_SFT_CONTROL_RD_SHIFT (12UL)
#define HKADC_TXSLZR_SEQ_SPI_SFT_CONTROL_WR_MASK (0x100UL)
#define HKADC_TXSLZR_SEQ_SPI_SFT_CONTROL_WR_SHIFT (8UL)
#define HKADC_TXSLZR_SEQ_SPI_SFT_CONTROL_RD_CMD_CFG_MASK (0x10UL)
#define HKADC_TXSLZR_SEQ_SPI_SFT_CONTROL_RD_CMD_CFG_SHIFT (4UL)
#define HKADC_TXSLZR_SEQ_SPI_SFT_CONTROL_RD_RD_CFG_MASK (0x1UL)
#define HKADC_TXSLZR_SEQ_SPI_SFT_CONTROL_RD_RD_CFG_SHIFT (0UL)




typedef uint32_t HKADC_SPI_SOFT_WR_DATA_TYPE;
#define HKADC_SPI_SOFT_WR_DATA_SFT_MASK (0xffffUL)
#define HKADC_SPI_SOFT_WR_DATA_SFT_SHIFT (0UL)




typedef uint32_t HKADC_SPI_SOFT_RD_DATA_TYPE;
#define HKADC_SPI_SOFT_RD_DATA_RD_DONE_MASK (0x80000000UL)
#define HKADC_SPI_SOFT_RD_DATA_RD_DONE_SHIFT (31UL)
#define HKADC_SPI_SOFT_RD_DATA_SFT_RD_DATA_MASK (0xffffUL)
#define HKADC_SPI_SOFT_RD_DATA_SFT_RD_DATA_SHIFT (0UL)




typedef uint32_t HKADC_TXSLZR_SEQ_MISC_SPI_CONTROL_TYPE;
#define HKADC_TXSLZR_SEQ_MISC_SPI_CONTROL_TURNAROUND_MASK (0xfUL)
#define HKADC_TXSLZR_SEQ_MISC_SPI_CONTROL_TURNAROUND_SHIFT (0UL)


typedef volatile struct sHKADC_CHANNEL_TYPE {
    HKADC_CAPT_CTRL_TYPE adc0_capt_ctrl; /* OFFSET: 0x0 */
    HKADC_ADC_FIFO_DATA_TYPE adc0_fifo_data; /* OFFSET: 0x4 */
    HKADC_ADC_FIFO_CTRL_TYPE adc0_fifo_ctrl; /* OFFSET: 0x8 */
    HKADC_ADC_CMP_CTRL_TYPE adc0_cmp0; /* OFFSET: 0xc */
    HKADC_ADC_CMP_CTRL_TYPE adc0_cmp1; /* OFFSET: 0x10 */
    uint32_t adc0_dbg; /* OFFSET: 0x14 */
    HKADC_AUXADC_CONFIG0_TYPE afe0_cfg0; /* OFFSET: 0x18 */
    HKADC_AFE_CALIB_TYPE afe0_calib; /* OFFSET: 0x1c */
    HKADC_AFE_DBG_TYPE afe0_dbg; /* OFFSET: 0x20 */
    HKADC_RESERVED_TYPE rsvd0[92]; /* OFFSET: 0x24 */
} HKADC_CHANNEL_TYPE;


#define HKADC_CHAN_SIZE  (8UL)


typedef volatile struct sHKADC_RDBType {
    HKADC_CHANNEL_TYPE chan[HKADC_CHAN_SIZE]; /* OFFSET: 0x0 */
    HKADC_RESERVED_TYPE rsvd7[1024]; /* OFFSET: 0x400 */
    uint32_t reserved_57; /* OFFSET: 0x800 */
    uint32_t reserved_58; /* OFFSET: 0x804 */
    uint32_t reserved_59; /* OFFSET: 0x808 */
    uint32_t reserved_60; /* OFFSET: 0x80c */
    uint32_t reserved_61; /* OFFSET: 0x810 */
    HKADC_RESERVED_TYPE rsvd8[1768]; /* OFFSET: 0x814 */
    uint32_t reserved_62; /* OFFSET: 0xefc */
} HKADC_RDBType;


#define HKADC_BASE                      (0xE0608000UL)

#define HKADC_CHANNEL_TYPE_OFFSET       (0xE0608000UL)



#define HKADC_MAX_HW_ID                 (1UL)


#define HKADC_SEQ_MAX_CH                (2UL)


#define HKADC_SEQ_CH_START              (6UL)


#define HKADC_SEQ6_BASE_ADDR            (0xE0608324UL)


#define HKADC_SEQ7_BASE_ADDR            (0xE06083A4UL)

#endif /* HKADC_RDB_H */
