/*****************************************************************************
 Copyright 2025 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file intrctrl_gen_rdb.h
    @brief RDB File for INTRCTRL_GEN

    @version BCM89580_A0_20230125_RDB
*/

#ifndef INTRCTRL_GEN_RDB_H
#define INTRCTRL_GEN_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t INTRCTRL_GEN_GSNFIE_TYPE;
#define INTRCTRL_GEN_GSNFIE_PGS3NI_MASK (0x80UL)
#define INTRCTRL_GEN_GSNFIE_PGS3NI_SHIFT (7UL)
#define INTRCTRL_GEN_GSNFIE_P_GP_SRAM_3_WR_PARITY_FAULT_INTR_MASK (0x40UL)
#define INTRCTRL_GEN_GSNFIE_P_GP_SRAM_3_WR_PARITY_FAULT_INTR_SHIFT (6UL)
#define INTRCTRL_GEN_GSNFIE_P_GP_SRAM_2_NOPENDINGTRANS_INTR_MASK (0x20UL)
#define INTRCTRL_GEN_GSNFIE_P_GP_SRAM_2_NOPENDINGTRANS_INTR_SHIFT (5UL)
#define INTRCTRL_GEN_GSNFIE_P_GP_SRAM_2_WR_PARITY_FAULT_INTR_MASK (0x10UL)
#define INTRCTRL_GEN_GSNFIE_P_GP_SRAM_2_WR_PARITY_FAULT_INTR_SHIFT (4UL)
#define INTRCTRL_GEN_GSNFIE_P_GP_SRAM_1_NOPENDINGTRANS_INTR_MASK (0x8UL)
#define INTRCTRL_GEN_GSNFIE_P_GP_SRAM_1_NOPENDINGTRANS_INTR_SHIFT (3UL)
#define INTRCTRL_GEN_GSNFIE_P_GP_SRAM_1_WR_PARITY_FAULT_INTR_MASK (0x4UL)
#define INTRCTRL_GEN_GSNFIE_P_GP_SRAM_1_WR_PARITY_FAULT_INTR_SHIFT (2UL)
#define INTRCTRL_GEN_GSNFIE_P_GP_SRAM_0_NOPENDINGTRANS_INTR_MASK (0x2UL)
#define INTRCTRL_GEN_GSNFIE_P_GP_SRAM_0_NOPENDINGTRANS_INTR_SHIFT (1UL)
#define INTRCTRL_GEN_GSNFIE_P_GP_SRAM_0_WR_PARITY_FAULT_INTR_MASK (0x1UL)
#define INTRCTRL_GEN_GSNFIE_P_GP_SRAM_0_WR_PARITY_FAULT_INTR_SHIFT (0UL)




typedef uint32_t INTRCTRL_GEN_GSNFIE1_TYPE;
#define INTRCTRL_GEN_GSNFIE1_GS3NIW2_MASK (0x80UL)
#define INTRCTRL_GEN_GSNFIE1_GS3NIW2_SHIFT (7UL)
#define INTRCTRL_GEN_GSNFIE1_GS3WPFIW2_MASK (0x40UL)
#define INTRCTRL_GEN_GSNFIE1_GS3WPFIW2_SHIFT (6UL)
#define INTRCTRL_GEN_GSNFIE1_GP_SRAM_2_NOPENDINGTRANS_INTR_W2CLR_MASK (0x20UL)
#define INTRCTRL_GEN_GSNFIE1_GP_SRAM_2_NOPENDINGTRANS_INTR_W2CLR_SHIFT (5UL)
#define INTRCTRL_GEN_GSNFIE1_GS2WPFIW2_MASK (0x10UL)
#define INTRCTRL_GEN_GSNFIE1_GS2WPFIW2_SHIFT (4UL)
#define INTRCTRL_GEN_GSNFIE1_GP_SRAM_1_NOPENDINGTRANS_INTR_W2CLR_MASK (0x8UL)
#define INTRCTRL_GEN_GSNFIE1_GP_SRAM_1_NOPENDINGTRANS_INTR_W2CLR_SHIFT (3UL)
#define INTRCTRL_GEN_GSNFIE1_GS1WPFIW2_MASK (0x4UL)
#define INTRCTRL_GEN_GSNFIE1_GS1WPFIW2_SHIFT (2UL)
#define INTRCTRL_GEN_GSNFIE1_GP_SRAM_0_NOPENDINGTRANS_INTR_W2CLR_MASK (0x2UL)
#define INTRCTRL_GEN_GSNFIE1_GP_SRAM_0_NOPENDINGTRANS_INTR_W2CLR_SHIFT (1UL)
#define INTRCTRL_GEN_GSNFIE1_GS0WPFIW2_MASK (0x1UL)
#define INTRCTRL_GEN_GSNFIE1_GS0WPFIW2_SHIFT (0UL)




typedef uint32_t INTRCTRL_GEN_GSNFIE2_TYPE;
#define INTRCTRL_GEN_GSNFIE2_EGS3NI_MASK (0x80UL)
#define INTRCTRL_GEN_GSNFIE2_EGS3NI_SHIFT (7UL)
#define INTRCTRL_GEN_GSNFIE2_EGS3WPFI_MASK (0x40UL)
#define INTRCTRL_GEN_GSNFIE2_EGS3WPFI_SHIFT (6UL)
#define INTRCTRL_GEN_GSNFIE2_EGS2NI_MASK (0x20UL)
#define INTRCTRL_GEN_GSNFIE2_EGS2NI_SHIFT (5UL)
#define INTRCTRL_GEN_GSNFIE2_EGS2WPFI_MASK (0x10UL)
#define INTRCTRL_GEN_GSNFIE2_EGS2WPFI_SHIFT (4UL)
#define INTRCTRL_GEN_GSNFIE2_EGS1NI_MASK (0x8UL)
#define INTRCTRL_GEN_GSNFIE2_EGS1NI_SHIFT (3UL)
#define INTRCTRL_GEN_GSNFIE2_EGS1WPFI_MASK (0x4UL)
#define INTRCTRL_GEN_GSNFIE2_EGS1WPFI_SHIFT (2UL)
#define INTRCTRL_GEN_GSNFIE2_EGS0NI_MASK (0x2UL)
#define INTRCTRL_GEN_GSNFIE2_EGS0NI_SHIFT (1UL)
#define INTRCTRL_GEN_GSNFIE2_EGS0WPFI_MASK (0x1UL)
#define INTRCTRL_GEN_GSNFIE2_EGS0WPFI_SHIFT (0UL)




typedef uint32_t INTRCTRL_GEN_GSMPIE_TYPE;
#define INTRCTRL_GEN_GSMPIE_P_GP_SRAM_3_MEM_PROTECT_INTR_MASK (0x8UL)
#define INTRCTRL_GEN_GSMPIE_P_GP_SRAM_3_MEM_PROTECT_INTR_SHIFT (3UL)
#define INTRCTRL_GEN_GSMPIE_P_GP_SRAM_2_MEM_PROTECT_INTR_MASK (0x4UL)
#define INTRCTRL_GEN_GSMPIE_P_GP_SRAM_2_MEM_PROTECT_INTR_SHIFT (2UL)
#define INTRCTRL_GEN_GSMPIE_P_GP_SRAM_1_MEM_PROTECT_INTR_MASK (0x2UL)
#define INTRCTRL_GEN_GSMPIE_P_GP_SRAM_1_MEM_PROTECT_INTR_SHIFT (1UL)
#define INTRCTRL_GEN_GSMPIE_P_GP_SRAM_0_MEM_PROTECT_INTR_MASK (0x1UL)
#define INTRCTRL_GEN_GSMPIE_P_GP_SRAM_0_MEM_PROTECT_INTR_SHIFT (0UL)




typedef uint32_t INTRCTRL_GEN_GSMPIE1_TYPE;
#define INTRCTRL_GEN_GSMPIE1_GS3MPIW2_MASK (0x8UL)
#define INTRCTRL_GEN_GSMPIE1_GS3MPIW2_SHIFT (3UL)
#define INTRCTRL_GEN_GSMPIE1_GP_SRAM_2_MEM_PROTECT_INTR_W2CLR_MASK (0x4UL)
#define INTRCTRL_GEN_GSMPIE1_GP_SRAM_2_MEM_PROTECT_INTR_W2CLR_SHIFT (2UL)
#define INTRCTRL_GEN_GSMPIE1_GP_SRAM_1_MEM_PROTECT_INTR_W2CLR_MASK (0x2UL)
#define INTRCTRL_GEN_GSMPIE1_GP_SRAM_1_MEM_PROTECT_INTR_W2CLR_SHIFT (1UL)
#define INTRCTRL_GEN_GSMPIE1_GP_SRAM_0_MEM_PROTECT_INTR_W2CLR_MASK (0x1UL)
#define INTRCTRL_GEN_GSMPIE1_GP_SRAM_0_MEM_PROTECT_INTR_W2CLR_SHIFT (0UL)




typedef uint32_t INTRCTRL_GEN_GSMPIE2_TYPE;
#define INTRCTRL_GEN_GSMPIE2_EGS3MPI_MASK (0x8UL)
#define INTRCTRL_GEN_GSMPIE2_EGS3MPI_SHIFT (3UL)
#define INTRCTRL_GEN_GSMPIE2_ENABLE_GP_SRAM_2_MEM_PROTECT_INTR_MASK (0x4UL)
#define INTRCTRL_GEN_GSMPIE2_ENABLE_GP_SRAM_2_MEM_PROTECT_INTR_SHIFT (2UL)
#define INTRCTRL_GEN_GSMPIE2_ENABLE_GP_SRAM_1_MEM_PROTECT_INTR_MASK (0x2UL)
#define INTRCTRL_GEN_GSMPIE2_ENABLE_GP_SRAM_1_MEM_PROTECT_INTR_SHIFT (1UL)
#define INTRCTRL_GEN_GSMPIE2_ENABLE_GP_SRAM_0_MEM_PROTECT_INTR_MASK (0x1UL)
#define INTRCTRL_GEN_GSMPIE2_ENABLE_GP_SRAM_0_MEM_PROTECT_INTR_SHIFT (0UL)




typedef uint32_t INTRCTRL_GEN_GSDFIE_TYPE;
#define INTRCTRL_GEN_GSDFIE_P_GP_SRAM_3_DED_FLAG_INTR_MASK (0x8UL)
#define INTRCTRL_GEN_GSDFIE_P_GP_SRAM_3_DED_FLAG_INTR_SHIFT (3UL)
#define INTRCTRL_GEN_GSDFIE_P_GP_SRAM_2_DED_FLAG_INTR_MASK (0x4UL)
#define INTRCTRL_GEN_GSDFIE_P_GP_SRAM_2_DED_FLAG_INTR_SHIFT (2UL)
#define INTRCTRL_GEN_GSDFIE_P_GP_SRAM_1_DED_FLAG_INTR_MASK (0x2UL)
#define INTRCTRL_GEN_GSDFIE_P_GP_SRAM_1_DED_FLAG_INTR_SHIFT (1UL)
#define INTRCTRL_GEN_GSDFIE_P_GP_SRAM_0_DED_FLAG_INTR_MASK (0x1UL)
#define INTRCTRL_GEN_GSDFIE_P_GP_SRAM_0_DED_FLAG_INTR_SHIFT (0UL)




typedef uint32_t INTRCTRL_GEN_GSDFIE1_TYPE;
#define INTRCTRL_GEN_GSDFIE1_GS3DFIW2_MASK (0x8UL)
#define INTRCTRL_GEN_GSDFIE1_GS3DFIW2_SHIFT (3UL)
#define INTRCTRL_GEN_GSDFIE1_GP_SRAM_2_DED_FLAG_INTR_W2CLR_MASK (0x4UL)
#define INTRCTRL_GEN_GSDFIE1_GP_SRAM_2_DED_FLAG_INTR_W2CLR_SHIFT (2UL)
#define INTRCTRL_GEN_GSDFIE1_GP_SRAM_1_DED_FLAG_INTR_W2CLR_MASK (0x2UL)
#define INTRCTRL_GEN_GSDFIE1_GP_SRAM_1_DED_FLAG_INTR_W2CLR_SHIFT (1UL)
#define INTRCTRL_GEN_GSDFIE1_GP_SRAM_0_DED_FLAG_INTR_W2CLR_MASK (0x1UL)
#define INTRCTRL_GEN_GSDFIE1_GP_SRAM_0_DED_FLAG_INTR_W2CLR_SHIFT (0UL)




typedef uint32_t INTRCTRL_GEN_GSDFIE2_TYPE;
#define INTRCTRL_GEN_GSDFIE2_EGS3DFI_MASK (0x8UL)
#define INTRCTRL_GEN_GSDFIE2_EGS3DFI_SHIFT (3UL)
#define INTRCTRL_GEN_GSDFIE2_ENABLE_GP_SRAM_2_DED_FLAG_INTR_MASK (0x4UL)
#define INTRCTRL_GEN_GSDFIE2_ENABLE_GP_SRAM_2_DED_FLAG_INTR_SHIFT (2UL)
#define INTRCTRL_GEN_GSDFIE2_ENABLE_GP_SRAM_1_DED_FLAG_INTR_MASK (0x2UL)
#define INTRCTRL_GEN_GSDFIE2_ENABLE_GP_SRAM_1_DED_FLAG_INTR_SHIFT (1UL)
#define INTRCTRL_GEN_GSDFIE2_ENABLE_GP_SRAM_0_DED_FLAG_INTR_MASK (0x1UL)
#define INTRCTRL_GEN_GSDFIE2_ENABLE_GP_SRAM_0_DED_FLAG_INTR_SHIFT (0UL)




typedef uint32_t INTRCTRL_GEN_GSMIEFIE_TYPE;
#define INTRCTRL_GEN_GSMIEFIE_PGS3MIEI_MASK (0x8UL)
#define INTRCTRL_GEN_GSMIEFIE_PGS3MIEI_SHIFT (3UL)
#define INTRCTRL_GEN_GSMIEFIE_P_GP_SRAM_2_MEM_INIT_ERROR_INTR_MASK (0x4UL)
#define INTRCTRL_GEN_GSMIEFIE_P_GP_SRAM_2_MEM_INIT_ERROR_INTR_SHIFT (2UL)
#define INTRCTRL_GEN_GSMIEFIE_P_GP_SRAM_1_MEM_INIT_ERROR_INTR_MASK (0x2UL)
#define INTRCTRL_GEN_GSMIEFIE_P_GP_SRAM_1_MEM_INIT_ERROR_INTR_SHIFT (1UL)
#define INTRCTRL_GEN_GSMIEFIE_P_GP_SRAM_0_MEM_INIT_ERROR_INTR_MASK (0x1UL)
#define INTRCTRL_GEN_GSMIEFIE_P_GP_SRAM_0_MEM_INIT_ERROR_INTR_SHIFT (0UL)




typedef uint32_t INTRCTRL_GEN_GSMIEFIE1_TYPE;
#define INTRCTRL_GEN_GSMIEFIE1_GS3MIEIW2_MASK (0x8UL)
#define INTRCTRL_GEN_GSMIEFIE1_GS3MIEIW2_SHIFT (3UL)
#define INTRCTRL_GEN_GSMIEFIE1_GS2MIEIW2_MASK (0x4UL)
#define INTRCTRL_GEN_GSMIEFIE1_GS2MIEIW2_SHIFT (2UL)
#define INTRCTRL_GEN_GSMIEFIE1_GS1MIEIW2_MASK (0x2UL)
#define INTRCTRL_GEN_GSMIEFIE1_GS1MIEIW2_SHIFT (1UL)
#define INTRCTRL_GEN_GSMIEFIE1_GS0MIEIW2_MASK (0x1UL)
#define INTRCTRL_GEN_GSMIEFIE1_GS0MIEIW2_SHIFT (0UL)




typedef uint32_t INTRCTRL_GEN_GSMIEFIE2_TYPE;
#define INTRCTRL_GEN_GSMIEFIE2_EGS3MIEI_MASK (0x8UL)
#define INTRCTRL_GEN_GSMIEFIE2_EGS3MIEI_SHIFT (3UL)
#define INTRCTRL_GEN_GSMIEFIE2_EGS2MIEI_MASK (0x4UL)
#define INTRCTRL_GEN_GSMIEFIE2_EGS2MIEI_SHIFT (2UL)
#define INTRCTRL_GEN_GSMIEFIE2_EGS1MIEI_MASK (0x2UL)
#define INTRCTRL_GEN_GSMIEFIE2_EGS1MIEI_SHIFT (1UL)
#define INTRCTRL_GEN_GSMIEFIE2_EGS0MIEI_MASK (0x1UL)
#define INTRCTRL_GEN_GSMIEFIE2_EGS0MIEI_SHIFT (0UL)




typedef uint32_t INTRCTRL_GEN_GSMIIE_TYPE;
#define INTRCTRL_GEN_GSMIIE_P_GP_SRAM_3_SEC_FLAG_INTR_MASK (0x80UL)
#define INTRCTRL_GEN_GSMIIE_P_GP_SRAM_3_SEC_FLAG_INTR_SHIFT (7UL)
#define INTRCTRL_GEN_GSMIIE_P_GP_SRAM_2_SEC_FLAG_INTR_MASK (0x40UL)
#define INTRCTRL_GEN_GSMIIE_P_GP_SRAM_2_SEC_FLAG_INTR_SHIFT (6UL)
#define INTRCTRL_GEN_GSMIIE_P_GP_SRAM_1_SEC_FLAG_INTR_MASK (0x20UL)
#define INTRCTRL_GEN_GSMIIE_P_GP_SRAM_1_SEC_FLAG_INTR_SHIFT (5UL)
#define INTRCTRL_GEN_GSMIIE_P_GP_SRAM_0_SEC_FLAG_INTR_MASK (0x10UL)
#define INTRCTRL_GEN_GSMIIE_P_GP_SRAM_0_SEC_FLAG_INTR_SHIFT (4UL)
#define INTRCTRL_GEN_GSMIIE_P_GP_SRAM_3_MEM_INIT_DONE_INTR_MASK (0x8UL)
#define INTRCTRL_GEN_GSMIIE_P_GP_SRAM_3_MEM_INIT_DONE_INTR_SHIFT (3UL)
#define INTRCTRL_GEN_GSMIIE_P_GP_SRAM_2_MEM_INIT_DONE_INTR_MASK (0x4UL)
#define INTRCTRL_GEN_GSMIIE_P_GP_SRAM_2_MEM_INIT_DONE_INTR_SHIFT (2UL)
#define INTRCTRL_GEN_GSMIIE_P_GP_SRAM_1_MEM_INIT_DONE_INTR_MASK (0x2UL)
#define INTRCTRL_GEN_GSMIIE_P_GP_SRAM_1_MEM_INIT_DONE_INTR_SHIFT (1UL)
#define INTRCTRL_GEN_GSMIIE_P_GP_SRAM_0_MEM_INIT_DONE_INTR_MASK (0x1UL)
#define INTRCTRL_GEN_GSMIIE_P_GP_SRAM_0_MEM_INIT_DONE_INTR_SHIFT (0UL)




typedef uint32_t INTRCTRL_GEN_GSMIIE1_TYPE;
#define INTRCTRL_GEN_GSMIIE1_GS3SFIW2_MASK (0x80UL)
#define INTRCTRL_GEN_GSMIIE1_GS3SFIW2_SHIFT (7UL)
#define INTRCTRL_GEN_GSMIIE1_GP_SRAM_2_SEC_FLAG_INTR_W2CLR_MASK (0x40UL)
#define INTRCTRL_GEN_GSMIIE1_GP_SRAM_2_SEC_FLAG_INTR_W2CLR_SHIFT (6UL)
#define INTRCTRL_GEN_GSMIIE1_GP_SRAM_1_SEC_FLAG_INTR_W2CLR_MASK (0x20UL)
#define INTRCTRL_GEN_GSMIIE1_GP_SRAM_1_SEC_FLAG_INTR_W2CLR_SHIFT (5UL)
#define INTRCTRL_GEN_GSMIIE1_GP_SRAM_0_SEC_FLAG_INTR_W2CLR_MASK (0x10UL)
#define INTRCTRL_GEN_GSMIIE1_GP_SRAM_0_SEC_FLAG_INTR_W2CLR_SHIFT (4UL)
#define INTRCTRL_GEN_GSMIIE1_GP_SRAM_3_MEM_INIT_DONE_INTR_W2CLR_MASK (0x8UL)
#define INTRCTRL_GEN_GSMIIE1_GP_SRAM_3_MEM_INIT_DONE_INTR_W2CLR_SHIFT (3UL)
#define INTRCTRL_GEN_GSMIIE1_GP_SRAM_2_MEM_INIT_DONE_INTR_W2CLR_MASK (0x4UL)
#define INTRCTRL_GEN_GSMIIE1_GP_SRAM_2_MEM_INIT_DONE_INTR_W2CLR_SHIFT (2UL)
#define INTRCTRL_GEN_GSMIIE1_GP_SRAM_1_MEM_INIT_DONE_INTR_W2CLR_MASK (0x2UL)
#define INTRCTRL_GEN_GSMIIE1_GP_SRAM_1_MEM_INIT_DONE_INTR_W2CLR_SHIFT (1UL)
#define INTRCTRL_GEN_GSMIIE1_GP_SRAM_0_MEM_INIT_DONE_INTR_W2CLR_MASK (0x1UL)
#define INTRCTRL_GEN_GSMIIE1_GP_SRAM_0_MEM_INIT_DONE_INTR_W2CLR_SHIFT (0UL)




typedef uint32_t INTRCTRL_GEN_GSMIIE2_TYPE;
#define INTRCTRL_GEN_GSMIIE2_EGS3SFI_MASK (0x80UL)
#define INTRCTRL_GEN_GSMIIE2_EGS3SFI_SHIFT (7UL)
#define INTRCTRL_GEN_GSMIIE2_ENABLE_GP_SRAM_2_SEC_FLAG_INTR_MASK (0x40UL)
#define INTRCTRL_GEN_GSMIIE2_ENABLE_GP_SRAM_2_SEC_FLAG_INTR_SHIFT (6UL)
#define INTRCTRL_GEN_GSMIIE2_ENABLE_GP_SRAM_1_SEC_FLAG_INTR_MASK (0x20UL)
#define INTRCTRL_GEN_GSMIIE2_ENABLE_GP_SRAM_1_SEC_FLAG_INTR_SHIFT (5UL)
#define INTRCTRL_GEN_GSMIIE2_ENABLE_GP_SRAM_0_SEC_FLAG_INTR_MASK (0x10UL)
#define INTRCTRL_GEN_GSMIIE2_ENABLE_GP_SRAM_0_SEC_FLAG_INTR_SHIFT (4UL)
#define INTRCTRL_GEN_GSMIIE2_ENABLE_GP_SRAM_3_MEM_INIT_DONE_INTR_MASK (0x8UL)
#define INTRCTRL_GEN_GSMIIE2_ENABLE_GP_SRAM_3_MEM_INIT_DONE_INTR_SHIFT (3UL)
#define INTRCTRL_GEN_GSMIIE2_ENABLE_GP_SRAM_2_MEM_INIT_DONE_INTR_MASK (0x4UL)
#define INTRCTRL_GEN_GSMIIE2_ENABLE_GP_SRAM_2_MEM_INIT_DONE_INTR_SHIFT (2UL)
#define INTRCTRL_GEN_GSMIIE2_ENABLE_GP_SRAM_1_MEM_INIT_DONE_INTR_MASK (0x2UL)
#define INTRCTRL_GEN_GSMIIE2_ENABLE_GP_SRAM_1_MEM_INIT_DONE_INTR_SHIFT (1UL)
#define INTRCTRL_GEN_GSMIIE2_ENABLE_GP_SRAM_0_MEM_INIT_DONE_INTR_MASK (0x1UL)
#define INTRCTRL_GEN_GSMIIE2_ENABLE_GP_SRAM_0_MEM_INIT_DONE_INTR_SHIFT (0UL)




typedef uint32_t INTRCTRL_GEN_GANFIE_TYPE;
#define INTRCTRL_GEN_GANFIE_PGAMPFI_MASK (0x10UL)
#define INTRCTRL_GEN_GANFIE_PGAMPFI_SHIFT (4UL)
#define INTRCTRL_GEN_GANFIE_P_GLB_AHB_SLV_PARITY_FAULT_INTR_MASK (0x8UL)
#define INTRCTRL_GEN_GANFIE_P_GLB_AHB_SLV_PARITY_FAULT_INTR_SHIFT (3UL)
#define INTRCTRL_GEN_GANFIE_P_GLB_AHB_TIMEOUT_FAULT_INTR_MASK (0x4UL)
#define INTRCTRL_GEN_GANFIE_P_GLB_AHB_TIMEOUT_FAULT_INTR_SHIFT (2UL)
#define INTRCTRL_GEN_GANFIE_P_GLB_AHB_NOPENDINGTRANS_INTR_MASK (0x2UL)
#define INTRCTRL_GEN_GANFIE_P_GLB_AHB_NOPENDINGTRANS_INTR_SHIFT (1UL)
#define INTRCTRL_GEN_GANFIE_P_GLB_AHB_SLV_NOPENDINGTRANS_INTR_MASK (0x1UL)
#define INTRCTRL_GEN_GANFIE_P_GLB_AHB_SLV_NOPENDINGTRANS_INTR_SHIFT (0UL)




typedef uint32_t INTRCTRL_GEN_GANFIE1_TYPE;
#define INTRCTRL_GEN_GANFIE1_GAMPFIW2_MASK (0x10UL)
#define INTRCTRL_GEN_GANFIE1_GAMPFIW2_SHIFT (4UL)
#define INTRCTRL_GEN_GANFIE1_GLB_AHB_SLV_PARITY_FAULT_INTR_W2CLR_MASK (0x8UL)
#define INTRCTRL_GEN_GANFIE1_GLB_AHB_SLV_PARITY_FAULT_INTR_W2CLR_SHIFT (3UL)
#define INTRCTRL_GEN_GANFIE1_GLB_AHB_TIMEOUT_FAULT_INTR_W2CLR_MASK (0x4UL)
#define INTRCTRL_GEN_GANFIE1_GLB_AHB_TIMEOUT_FAULT_INTR_W2CLR_SHIFT (2UL)
#define INTRCTRL_GEN_GANFIE1_GLB_AHB_NOPENDINGTRANS_INTR_W2CLR_MASK (0x2UL)
#define INTRCTRL_GEN_GANFIE1_GLB_AHB_NOPENDINGTRANS_INTR_W2CLR_SHIFT (1UL)
#define INTRCTRL_GEN_GANFIE1_GASNIW2_MASK (0x1UL)
#define INTRCTRL_GEN_GANFIE1_GASNIW2_SHIFT (0UL)




typedef uint32_t INTRCTRL_GEN_GANFIE2_TYPE;
#define INTRCTRL_GEN_GANFIE2_EGAMPFI_MASK (0x10UL)
#define INTRCTRL_GEN_GANFIE2_EGAMPFI_SHIFT (4UL)
#define INTRCTRL_GEN_GANFIE2_EGASPFI_MASK (0x8UL)
#define INTRCTRL_GEN_GANFIE2_EGASPFI_SHIFT (3UL)
#define INTRCTRL_GEN_GANFIE2_ENABLE_GLB_AHB_TIMEOUT_FAULT_INTR_MASK (0x4UL)
#define INTRCTRL_GEN_GANFIE2_ENABLE_GLB_AHB_TIMEOUT_FAULT_INTR_SHIFT (2UL)
#define INTRCTRL_GEN_GANFIE2_ENABLE_GLB_AHB_NOPENDINGTRANS_INTR_MASK (0x2UL)
#define INTRCTRL_GEN_GANFIE2_ENABLE_GLB_AHB_NOPENDINGTRANS_INTR_SHIFT (1UL)
#define INTRCTRL_GEN_GANFIE2_EGASNI_MASK (0x1UL)
#define INTRCTRL_GEN_GANFIE2_EGASNI_SHIFT (0UL)




typedef uint32_t INTRCTRL_GEN_NSNFIE_TYPE;
#define INTRCTRL_GEN_NSNFIE_PNSNI_MASK (0x2UL)
#define INTRCTRL_GEN_NSNFIE_PNSNI_SHIFT (1UL)
#define INTRCTRL_GEN_NSNFIE_P_NOC_SVCNW_INT_NOPENDINGTRANS_INTR_MASK (0x1UL)
#define INTRCTRL_GEN_NSNFIE_P_NOC_SVCNW_INT_NOPENDINGTRANS_INTR_SHIFT (0UL)




typedef uint32_t INTRCTRL_GEN_NSNFIE1_TYPE;
#define INTRCTRL_GEN_NSNFIE1_NSNIW2_MASK (0x2UL)
#define INTRCTRL_GEN_NSNFIE1_NSNIW2_SHIFT (1UL)
#define INTRCTRL_GEN_NSNFIE1_NSINIW2_MASK (0x1UL)
#define INTRCTRL_GEN_NSNFIE1_NSINIW2_SHIFT (0UL)




typedef uint32_t INTRCTRL_GEN_NSNFIE2_TYPE;
#define INTRCTRL_GEN_NSNFIE2_ENSNI_MASK (0x2UL)
#define INTRCTRL_GEN_NSNFIE2_ENSNI_SHIFT (1UL)
#define INTRCTRL_GEN_NSNFIE2_ENSINI_MASK (0x1UL)
#define INTRCTRL_GEN_NSNFIE2_ENSINI_SHIFT (0UL)




typedef uint32_t INTRCTRL_GEN_RIGEL_GPIO_INTR_EIPR_TYPE;
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EIPR_P_SW_7_INTR_MASK (0x80UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EIPR_P_SW_7_INTR_SHIFT (7UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EIPR_P_SW_6_INTR_MASK (0x40UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EIPR_P_SW_6_INTR_SHIFT (6UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EIPR_P_SW_5_INTR_MASK (0x20UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EIPR_P_SW_5_INTR_SHIFT (5UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EIPR_P_SW_4_INTR_MASK (0x10UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EIPR_P_SW_4_INTR_SHIFT (4UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EIPR_P_SW_3_INTR_MASK (0x8UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EIPR_P_SW_3_INTR_SHIFT (3UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EIPR_P_SW_2_INTR_MASK (0x4UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EIPR_P_SW_2_INTR_SHIFT (2UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EIPR_P_SW_1_INTR_MASK (0x2UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EIPR_P_SW_1_INTR_SHIFT (1UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EIPR_P_SW_0_INTR_MASK (0x1UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EIPR_P_SW_0_INTR_SHIFT (0UL)




typedef uint32_t INTRCTRL_GEN_RIGEL_GPIO_INTR_EISR_TYPE;
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EISR_SW_7_INTR_W2CLR_MASK (0x80UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EISR_SW_7_INTR_W2CLR_SHIFT (7UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EISR_SW_6_INTR_W2CLR_MASK (0x40UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EISR_SW_6_INTR_W2CLR_SHIFT (6UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EISR_SW_5_INTR_W2CLR_MASK (0x20UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EISR_SW_5_INTR_W2CLR_SHIFT (5UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EISR_SW_4_INTR_W2CLR_MASK (0x10UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EISR_SW_4_INTR_W2CLR_SHIFT (4UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EISR_SW_3_INTR_W2CLR_MASK (0x8UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EISR_SW_3_INTR_W2CLR_SHIFT (3UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EISR_SW_2_INTR_W2CLR_MASK (0x4UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EISR_SW_2_INTR_W2CLR_SHIFT (2UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EISR_SW_1_INTR_W2CLR_MASK (0x2UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EISR_SW_1_INTR_W2CLR_SHIFT (1UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EISR_SW_0_INTR_W2CLR_MASK (0x1UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EISR_SW_0_INTR_W2CLR_SHIFT (0UL)




typedef uint32_t INTRCTRL_GEN_RIGEL_GPIO_INTR_EIER_TYPE;
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EIER_ENABLE_SW_7_INTR_MASK (0x80UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EIER_ENABLE_SW_7_INTR_SHIFT (7UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EIER_ENABLE_SW_6_INTR_MASK (0x40UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EIER_ENABLE_SW_6_INTR_SHIFT (6UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EIER_ENABLE_SW_5_INTR_MASK (0x20UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EIER_ENABLE_SW_5_INTR_SHIFT (5UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EIER_ENABLE_SW_4_INTR_MASK (0x10UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EIER_ENABLE_SW_4_INTR_SHIFT (4UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EIER_ENABLE_SW_3_INTR_MASK (0x8UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EIER_ENABLE_SW_3_INTR_SHIFT (3UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EIER_ENABLE_SW_2_INTR_MASK (0x4UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EIER_ENABLE_SW_2_INTR_SHIFT (2UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EIER_ENABLE_SW_1_INTR_MASK (0x2UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EIER_ENABLE_SW_1_INTR_SHIFT (1UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EIER_ENABLE_SW_0_INTR_MASK (0x1UL)
#define INTRCTRL_GEN_RIGEL_GPIO_INTR_EIER_ENABLE_SW_0_INTR_SHIFT (0UL)




typedef uint8_t INTRCTRL_GEN_RESERVED_TYPE;




typedef uint32_t INTRCTRL_GEN_SPARE_END_REG_TYPE;
#define INTRCTRL_GEN_SPARE_END_REG_MASK (0xffffffffUL)
#define INTRCTRL_GEN_SPARE_END_REG_SHIFT (0UL)




typedef volatile struct sINTRCTRL_GEN_RDBType {
    INTRCTRL_GEN_GSNFIE_TYPE gp_sram_noc_fault_intr_eipr; /* OFFSET: 0x0 */
    INTRCTRL_GEN_GSNFIE1_TYPE gp_sram_noc_fault_intr_eisr; /* OFFSET: 0x4 */
    INTRCTRL_GEN_GSNFIE2_TYPE gp_sram_noc_fault_intr_eier; /* OFFSET: 0x8 */
    INTRCTRL_GEN_GSMPIE_TYPE gp_sram_mem_protect_intr_eipr; /* OFFSET: 0xc */
    INTRCTRL_GEN_GSMPIE1_TYPE gp_sram_mem_protect_intr_eisr; /* OFFSET: 0x10 */
    INTRCTRL_GEN_GSMPIE2_TYPE gp_sram_mem_protect_intr_eier; /* OFFSET: 0x14 */
    INTRCTRL_GEN_GSDFIE_TYPE gp_sram_ded_fault_intr_eipr; /* OFFSET: 0x18 */
    INTRCTRL_GEN_GSDFIE1_TYPE gp_sram_ded_fault_intr_eisr; /* OFFSET: 0x1c */
    INTRCTRL_GEN_GSDFIE2_TYPE gp_sram_ded_fault_intr_eier; /* OFFSET: 0x20 */
    INTRCTRL_GEN_GSMIEFIE_TYPE gp_sram_mem_init_err_fault_intr_eipr; /* OFFSET: 0x24 */
    INTRCTRL_GEN_GSMIEFIE1_TYPE gp_sram_mem_init_err_fault_intr_eisr; /* OFFSET: 0x28 */
    INTRCTRL_GEN_GSMIEFIE2_TYPE gp_sram_mem_init_err_fault_intr_eier; /* OFFSET: 0x2c */
    INTRCTRL_GEN_GSMIIE_TYPE gp_sram_mem_init_intr_eipr; /* OFFSET: 0x30 */
    INTRCTRL_GEN_GSMIIE1_TYPE gp_sram_mem_init_intr_eisr; /* OFFSET: 0x34 */
    INTRCTRL_GEN_GSMIIE2_TYPE gp_sram_mem_init_intr_eier; /* OFFSET: 0x38 */
    INTRCTRL_GEN_GANFIE_TYPE glb_ahb_noc_fault_intr_eipr; /* OFFSET: 0x3c */
    INTRCTRL_GEN_GANFIE1_TYPE glb_ahb_noc_fault_intr_eisr; /* OFFSET: 0x40 */
    INTRCTRL_GEN_GANFIE2_TYPE glb_ahb_noc_fault_intr_eier; /* OFFSET: 0x44 */
    uint32_t reserved_7; /* OFFSET: 0x48 */
    uint32_t reserved_8; /* OFFSET: 0x4c */
    uint32_t reserved_9; /* OFFSET: 0x50 */
    INTRCTRL_GEN_NSNFIE_TYPE noc_svcnw_noc_fault_intr_eipr; /* OFFSET: 0x54 */
    INTRCTRL_GEN_NSNFIE1_TYPE noc_svcnw_noc_fault_intr_eisr; /* OFFSET: 0x58 */
    INTRCTRL_GEN_NSNFIE2_TYPE noc_svcnw_noc_fault_intr_eier; /* OFFSET: 0x5c */
    INTRCTRL_GEN_RIGEL_GPIO_INTR_EIPR_TYPE rigel_gpio_intr_eipr; /* OFFSET: 0x60 */
    INTRCTRL_GEN_RIGEL_GPIO_INTR_EISR_TYPE rigel_gpio_intr_eisr; /* OFFSET: 0x64 */
    INTRCTRL_GEN_RIGEL_GPIO_INTR_EIER_TYPE rigel_gpio_intr_eier; /* OFFSET: 0x68 */
    INTRCTRL_GEN_RESERVED_TYPE rsvd0[400]; /* OFFSET: 0x6c */
    INTRCTRL_GEN_SPARE_END_REG_TYPE spare_end_reg; /* OFFSET: 0x1fc */
} INTRCTRL_GEN_RDBType;


#define RIG_GEN_INTRCTRL_BASE           ((uintptr_t)(0x10240400UL))



#define INTRCTRL_GEN_MAX_HW_ID          (1UL)

#endif /* INTRCTRL_GEN_RDB_H */
